### ISSUE TITLE
[1][startailcoon] Deposit Modal Tweaks

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1001]
When selecting from the dashboard, we should send both the gateway and the symbol to the deposit modal so both values are populated when the modal opens. As it stands now, we are always defaulting to BTS.

![btc](https://user-images.githubusercontent.com/1254810/34806654-e3d88d32-f649-11e7-8a41-a7e83d3e44da.gif)

**Comment by startailcoon** [comment]
This is strange, it should take the Gateway and Asset when opening the modal. Something must have been missed on merging my latest PR.

This would be a very simple fix.

**Comment by startailcoon** [comment]
I will look at this, but the Web wallet works as expected. Dumb question, but are you running the latest version?

**Comment by svk31** [comment]
I did make sure it behaved like that before the release so I'm a bit surprised here. It could be that the hotfix changes modified this behaviour though.

**Comment by startailcoon** [comment]
The issue that we're having is that your opening the deposit modal with `bridge.BTC`. The modal only works with `open.X` and `rudex.X` assets at the moment.

It shouldn't be triggered on other gateway assets, or it should display a message about it when the modal is opened, like when an asset isn't available on the selected gateway.

What I understand, the `bridge.X` gateway is no longer operational? It's not available in the old deposit section.

**Comment by wmbutler** [comment]
- [ ] OK, so we should NOT present the icon if those gateways are not known in the reference wallet.
