### ISSUE TITLE
[4][pnomolos] Portfolio could use a visual representation of asset allocation

### ISSUE THREAD

**Issue by liondani** [bitshares/bitshares-ui#1002]
Something like this....  

![bitshares_wallet_pie_chart](https://user-images.githubusercontent.com/6908400/34817371-6898e4e2-f6c0-11e7-8c49-6db1fa432c8c.png)

**Comment by svk31** [comment]
I agree, I had a similar representation with a block chart in the pre-release wallet that BM vetoed, but I think we should add a pie chart like shown in your screenshot now. Calculating equivalent values in a way that's available for a pie chart representation is a little tricky but it should be possible.

We'd need a threshold for a "others" category cutoff, but that can be tweaked during the implementation. Highcharts is already included and can be used to make pie charts.

**Comment by wmbutler** [comment]
I'd like to UX something a little more balanced.

**Comment by liondani** [comment]
Have you something specific in mind @wmbutler ? Some example?

**Comment by wmbutler** [comment]
Not yet, but certainly not something so large. Some thoughts:

- Since we already have the assets listed, seems like we could include the colors in the Portfolio Table and match hover states on the graphic with those on the pie chart.
- Maybe use a semicircle donut rather than a pie chart.

![ev7us](https://user-images.githubusercontent.com/1254810/35022709-f2224eca-fafc-11e7-9746-43c7cabeb3ec.png)

**Comment by btsfav** [comment]
Concur, I love pie!

**Comment by ahdigital** [comment]
I don't think pie or semi-circle work that nicely within the UI given that almost every element has a square edge. An **[area map](https://www.highcharts.com/demo/treemap-coloraxis)** might be the best compromise between aesthetics and functionality.

**Comment by wmbutler** [comment]
A treemap did cross my mind as well for the same reasons. Excellent thought.

**Comment by pnomolos** [comment]
@wmbutler If it's been agreed that a treemap would be the best for this, I'm down to take it  :)

**Comment by svk31** [comment]
A tree map is what I had two years ago that I mentioned above, the code is here: https://github.com/cryptonomex/graphene-ui/commit/1ccdd47f20d888c647953c7fa4b3350b5f023b93

**Comment by wmbutler** [comment]
Some thoughts:

- We currently have Active and Hidden. What if we add `Visual` and clicking on that reveals the treemap? Just thinking that for really large portfolios, it could be a bit strange, otherwise.

**Comment by ahdigital** [comment]
I like this idea.

**Comment by pnomolos** [comment]
@wmbutler @btsfav @svk31 First pass ... I'm currently using https://github.com/jquintozamora/react-d3-treemap to power it but if you'd prefer I switch to a HighCharts-powered one I can do that too.  I don't have a lot of assets so it's a pretty boring treemap.

![screenshot from 2018-02-01 08-25-17](https://user-images.githubusercontent.com/36223/35690033-bca361ba-0729-11e8-860b-96f35e481987.png)

**Comment by wmbutler** [comment]
Lol, This probably does need some UX. Maybe....

- Kill the header
- Adopt Roboto Font
- Slightly larger font
- More saturated color set?

**Comment by ahdigital** [comment]
Out of the box highcharts would probably look better, but I agree with the comments suggested.

**Comment by gibbsfromncis** [comment]
@wmbutler looks like no any progress on this. I can take it and ... finish !:)

**Comment by pnomolos** [comment]
Sorry, I am still working on it :) the performance issues with the OS X
staging client are killing me right now.

**Comment by gibbsfromncis** [comment]
@pnomolos When are you going to finish it? Do I understand correct that you're blocked right now and cannot work on this? Btw I would recommend you to use high charts. It has a lot of features and may help us in future.

**Comment by pnomolos** [comment]
@gibbsfromncis I'm hoping to finish in the next day or two - have moved off my laptop and on to my main desktop which should mean I'm no longer blocked by the performance issues.  I've mostly converted to highcharts and am just finishing up a few minor things.  Should have some screenshots up today.

**Comment by gibbsfromncis** [comment]
@pnomolos sounds great!

**Comment by pnomolos** [comment]
Alright, Highcharts integrated, just sorting out some stuff in terms of converting the values over.

![screenshot from 2018-02-15 11-26-45](https://user-images.githubusercontent.com/36223/36276848-f799de0a-1243-11e8-908e-d639f2708a2d.png)

I've also converted the font to 'RobotoRegular'.

How should values be displayed?  Right now I'm converting to BTS so you get an overview of all your assets, but I could convert to BTS/percent but label with the actual amount of a give asset you have.  Thoughts?

**Comment by gibbsfromncis** [comment]
@pnomolos I suppose you should convert to the asset selected on User Settings in General tab. But what you did is quite fine.

**Comment by gibbsfromncis** [comment]
But actually it doesn't matter I suppose. convert to specific value may affect only for 0.X% of difference..

**Comment by pnomolos** [comment]
I can do that by grabbing the settings, it's more about how to label it (I think that showing each as a percentage of total value in a single unit makes the most sense)

**Comment by gibbsfromncis** [comment]
@pnomolos I suppose % value would be enough. If user want to know actual count of assets he can take a look above at his portfolio :)

**Comment by pnomolos** [comment]
OK, left to do:

- [ ] Active, Hidden, Visual tabs need to work properly
- [ ] There's some component updating oddity (sometimes it'll throw an error)
- [ ] Convert to a user's preferred internal unit
- [ ] Conversion issue (some assets appear to be converting at the wrong rate).

@svk31 @wmbutler In regards to the last one, would one of you mind taking a look at my code @ https://github.com/pnomolos/bitshares-ui/blob/d785bd3931b76802e93d8f330d5ebee7c94f6be8/app/components/Account/AccountTreemap.jsx#L134-L163 ?  I've tried to track down how the process of converting from the asset's units into BTS (or preferred unit) works by tracing the code used for the 'Active' tab on the Dashboard, but I seem to be missing something.  Some of my assets work correctly, but my bitUSD is showing up at 10x the value, so obviously something's going on with the precision.

**Comment by pnomolos** [comment]
I solved the second item by updating highcharts.  Will need to ensure this hasn't broken anything.

**Comment by pnomolos** [comment]
@svk31 @wmbutler For "Convert to a user's preferred internal unit" I see how it's done in `AccountOverview.jsx`, but I cannot for the life of me figure out where `settings` is coming from.  It's pull from the `props`, but I don't see it being set anywhere.  If you could enlighten me on where that's coming from that'd be great, thanks!

**Comment by gibbsfromncis** [comment]
@pnomolos it wraps by Containers. `SettingsStore.getState().settings`. Just use cmd+F man :)

**Comment by ahdigital** [comment]
"I solved the second item by updating highcharts. Will need to ensure this hasn't broken anything."

I think the explore->blockchain page uses highcharts for 2 graphs.
