### ISSUE TITLE
Rename "Germany" Node to More Specific Location

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#1003]
In Settings -> Access there are currently 4 nodes in Germany:

- Nuremberg, Germany
- Berlin, Germany
- Munich, Germany
- Germany

This feels a bit strange to have one called "Germany" when there are already 3 labeled as cities in Germany. Where is this node?

**Comment by HarukaMa** [comment]
@ruslansalikhov has only stated that it's provided by `blckchnd` witness so we need more information from node provider.

**Comment by ruslansalikhov** [comment]
@landry314 node is in Falkenstein.

Will update that record.
