### ISSUE TITLE
LTM Referrer Split %

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#1006]
Regarding Lifetime Membership, is this 130% fee allocation indeed correct for an account created using a LTM referral link? The registrar split is a negative 50% so the math adds up to an expected 80% since (130 +(-50)) = 80 and the network gets the other 20%.

But how does the blockchain transact a negative 50% fee to the registrar ... and is the blockchain really assigning 130% of transactional fees to the referrer?
 
![referrer-split](https://user-images.githubusercontent.com/14145836/34847997-1326a3a2-f6d2-11e7-9de0-cc55352afa93.png)

**Comment by HarukaMa** [comment]
It is showing as normal on wallet UI (20%-30%-0%-50%). Check it at https://b.mrx.im/account/falstere-6800/member-stats. Not sure why cryptofresh shows like that, seems like a bug on their site.

raw object:

```
    "network_fee_percentage": 2000,
    "lifetime_referrer_fee_percentage": 3000,
    "referrer_rewards_percentage": 10000,
```

**Comment by wmbutler** [comment]
We cannot control what cryptofresh chooses to display in this repo.
