### ISSUE TITLE
[6][zhyupe] My Markets | Top Markets | Featured Markets

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1007]
The front dash with all the "Top Markets" would be better to be replaced with a user selected version.

- Using starred markets, or a new definition of favorite markets.
- Sorted by the users choosing.

The board is very good, but serves little to no usage if the user is not interested in the displayed market.

**Comment by MarkoPaasila** [comment]
I would like to hide it completely and only see my recent activity / accounts

**Comment by startailcoon** [comment]
You can view only accounts from the accounts link on the right hand menu.

I think it's worth saving the market overview, but to make it a bit more user relevant.

**Comment by wmbutler** [comment]
This needs UX as well.

**Comment by wmbutler** [comment]
Follow this design pattern where the three tabs for:

- [ ] My Markets | Top Markets | Featured Markets are in the same location as Active | Hidden
- [ ] Filter is located as shown below

Regarding the accounts label, That's not easy, but for now just place it above the filter I suppose.

![34244847-d3a11dfc-e5ec-11e7-8cf8-4c614ea51199](https://user-images.githubusercontent.com/1254810/34886026-6ab7cbcc-f787-11e7-8187-03b1527b59ee.png)

**Comment by zhyupe** [comment]
Then where should `Accounts|Contacts|Recent activity` be placed? Obviously they are not children of `My Markets | Top Markets | Featured Markets`, but it would be strange if there are something stay unchanged when switching tabs.

**Comment by wmbutler** [comment]
@zhyupe Accounts|Contacts|Recent Activity is accessible from the Menu -> Accounts

**Comment by grctest** [comment]
Would a Smartcoin (MPA/ABA) filter checkbox be possible in this UX?

**Comment by wmbutler** [comment]
These are Markets. Aren't the Smartcoins searchable from the Asset Explorer?

**Comment by grctest** [comment]
> These are Markets. Aren't the Smartcoins searchable from the Asset Explorer?

Yeah, but it'd be great to be able to separate 'Top Markets' by UIA/MPA/All. Just my 2 cents.

**Comment by wmbutler** [comment]
Let's add a column for "Type" and then add a filter box at the top so people can just type UIA/MPA into the filter.

**Comment by wmbutler** [comment]
This will be helpful: https://github.com/bitshares/bitshares-core/pull/560

**Comment by zhyupe** [comment]
Claimed

**Comment by zhyupe** [comment]
I'm taking the markets listed in "Exchange > My Markets" as "My Markets". But there are 101 markets in this list by default and cannot be removed. As current UX design doesn't contain a base asset selector, it could be a mess to display them in a single list.

Another question is I don't know what the "Type" of market means. A pair of asset type or the type of a single asset (quote / base)?

**Comment by zhyupe** [comment]
Preview:
![image](https://user-images.githubusercontent.com/2197479/35933277-1a697bea-0c75-11e8-9734-a999197148d3.png)
![image](https://user-images.githubusercontent.com/2197479/35933681-4d50b8f6-0c76-11e8-8e1c-0913f9a16694.png)

**Comment by wmbutler** [comment]
> I'm taking the markets listed in "Exchange > My Markets" as "My Markets". But there are 101 markets in this list by default and cannot be removed. As current UX design doesn't contain a base asset selector, it could be a mess to display them in a single list.

Maybe just take the starred / favorites instead of the full 101 markets.

> I don't know what the "Type" of market means. A pair of asset type or the type of a single asset (quote / base)?

I think Type was like MPA, UIA etc.

> Should the "invert" state of each trading pair be saved?

Yes

**Comment by zhyupe** [comment]
> I think Type was like MPA, UIA etc.
I'm relatively new in BTS ... But as far as I know, MPA/UIA are asset types. Take `OPEN.BTC(UIA) : BITUSD(MPA)` for example, what's the "Type" of this market?

**Comment by wmbutler** [comment]
It's a good point, a market is not equal to an asset since it's an asset pair. Remove the type column.

**Comment by svk31** [comment]
I've merged the current work, @wmbutler you might wanna check if it's working as you intended.

**Comment by wmbutler** [comment]
Thanks, looks good.

**Comment by svk31** [comment]
Remerged after changes from @zhyupe , I've tested it with cloud login; incognito mode, wallet mode and seems ok this time around.

A natural next step would be to add sorting of the markets based on volume now.

**Comment by abitmore** [comment]
In regards to the feature that sorts markets by volume, although I don't think it's a perfect feature if it's designed to "discover" new hot markets automatically (since fake volume can be easily made up which will render the feature useless), if the UI team really want it, core can provide an API to efficiently fetch required data from the pre-calculated ticker data stored with market_history plugin (perhaps without the ability to filter/whitelist to mitigate spamming issue). 

If the sorting is among pre-defined market pairs, perhaps it's more efficient for UI to fetch data via `get_ticker` API, then sort locally. And an even more efficient way is to subscribe to the ticker data (which may require some dev work).
