### ISSUE TITLE
Avoid sell all BTS in BTS/xxx markets

### ISSUE THREAD

**Issue by vanissoft** [bitshares/bitshares-ui#1009]
In sell pane, when the user clicks on the quantity at "Balance:" the whole quantity goes to "Quantity:". 
This means the user will run out of BTS to pay the fees for subsequent operations.
We must avoid a such easy way of running out of BTS.
The same apply to buy panel for xxx/BTS markets.

**Comment by wmbutler** [comment]
I don't think this is true. We back calculate the quantity and pay the fee out of the trade. If this is actually happening, post a licecap to prove your point.

**Comment by svk31** [comment]
He's saying he can't transact after spending all his BTS, which of course makes perfect sense and isn't something we should prevent people from doing.

Fees do not need to be paid in bts, if the asset you're trading has a funded fee pool you can pay with that asset too.

**Comment by vanissoft** [comment]
We can, of course, avoid to enter the whole quantity when the user click in it.
For every other token this doesn't bother, but it is critical in BTS for don't depend of the fee pool.

**Comment by wmbutler** [comment]
I think this rule would make sense:

- [ ] If the user has insufficient BTS to fund the transaction, the UI should be smart enough to change the FEE to whichever currency is being transacted, thereby taking the fee from it.

**Comment by vanissoft** [comment]
I would like to left open this issue for more opinions. 
Mine is to left 0.01BTS in xxx/BTS market.

**Comment by wmbutler** [comment]
>I would like to left open this issue for more opinions.
Mine is to left 0.01BTS in xxx/BTS market.

I have no idea what you mean.

**Comment by vanissoft** [comment]
I usually click on the "Available quantity" whose behaviour is correct in the majority of cases, but with BTS i finnished with 0 BTS and the alternative showed was COMPUCEEDS and wasn't acepted by the system. 
My opinion is to left 0.01 BTS the first time the user click on "Available Quantity", or a message warning the user that he could not do another operations running out of "accepted coins for fees".
I understand that is logical the behaviour, but it is cumbersome for the user, having to ask around a tip for continue operations.

**Comment by wmbutler** [comment]
COMPUCEEDS needs to keep their fee pool filled.

**Comment by vanissoft** [comment]
> COMPUCEEDS needs to keep their fee pool filled.
I know, i was trading BTS/USD. Was the system's choice among all the other assets i have.
I see as a problem users running out of BTS (like related in #909).
IMO we need to avoid selling all BTS without prior warnings or at least left a fraction of BTS noticing the user he could be in the situation of being not able to trade if the fee pool is empty.
Checking fee pool (showing a warning if it's empty) would be great if we avoid user stucks.

**Comment by landry314** [comment]
@wmbutler, sometimes fee pools run out or the conversion ratio is not set correctly. It is better to always have a little BTS, like just 1 BTS is enough.

**Comment by svk31** [comment]
Closing since this is a non-issue. Selling everything should result in selling everything, we can't be subtracting random amounts just in case the user subsequently wants to trade an asset with a non-functioning fee pool.

**Comment by vanissoft** [comment]
I disagree. It's a poor user experience getting stuck for getting out of BTS. At least a message must be shown to advert the user when he is going to sell all the BTS.

**Comment by landry314** [comment]
This has become a serious issue recently. The bitCNY fee pool seems to be not working correctly and I run out of BTS and I am having order that can't cancel.

**Comment by abitmore** [comment]
@landry314 CNY fee pool seems fine: `Pool Balance | 25,603 BTS`
