### ISSUE TITLE
[1] Some witnesses in the same private test network are inactive

### ISSUE THREAD

**Issue by GildedHonour** [bitshares/bitshares-ui#1011]
We're running a private test network with 2 nodes. The 1st one contains 8 witnesses and the 2nd one 3. The 2nd node uses the 1st one as a seed. After I've run 1 and then 2nd, I see in their logs that they're working properly and see each other -- "Generated block.... Got block from ...." 

There're some errors still in the process generating blocks -- "Error when pushing , block:unlinkable_block_exception:".  Not always, but from time to time. 

**However, my main question is why doesn't bitshares-ui show that the witnesses of the 2nd node are producing any blocks at all? They're inactive.** Whereas the logs for both nodes claim that all witnesses are active, are genering and receving blocks from each other, across nodes and network.

 
![screenshot_2018-01-13_15-39-58](https://user-images.githubusercontent.com/2032888/34904422-0cd18ca4-f878-11e7-8352-198720649adf.png)

---> Witnesses 8-10 of the 2nd node are inactive.

This is the 1st node, generated a block and received one from the 9tn of the 2nd node 

![screenshot_2018-01-13_15-38-05](https://user-images.githubusercontent.com/2032888/34904409-e5177728-f877-11e7-83b2-fb63ffaace0a.png)

**Comment by abitmore** [comment]
Issues of private chains get low priority. People who want run private networks should have the capacity of solving the issues by their own, and better, submit solutions (PR's) to this project if issues found/resolved.

**Comment by abitmore** [comment]
By the way, the small screenshot below indicates the nodes are forking, as they both generated a block of same timestamp. Not an UI issue.
