### ISSUE TITLE
Shape-Shift Clone Front-End

### ISSUE THREAD

**Issue by jasonyoakam** [bitshares/bitshares-ui#1012]
Would it be possible to create a Shape-Shift clone as a front-end app to access the Bitshares blockchain? It seems like a big undertaking, but it would be a great step towards larger adoption and increased ease of use.

**Comment by jasonyoakam** [comment]
@wmbutler Could you let me know if there is a different place where I can propose this project?

**Comment by wmbutler** [comment]
I don't have a good idea. Sounds like you should build it yourself.

**Comment by jasonyoakam** [comment]
@wmbutler Am I incorrect in thinking that Bitshares has decentralized governance including the ability for the community to propose, vote on, and fund development tasks?

**Comment by wmbutler** [comment]
Yes

**Comment by jasonyoakam** [comment]
@wmbutler This seems to imply that the community is able to propose and fund projects - https://bitshares.org/technology/stakeholder-approved-project-funding/

Do you know how I can go about proposing one?

**Comment by wmbutler** [comment]
Yes,

I would start by gathering interest in a Steemit Article. Outline what you plan to do and build support around it. One of the problems with Bitshares funding it is that the service would need be integral to the blockchain (i.e. require nobody to manage it once it's running).

If you wanted to build something like that yourself without a WP, you could do that and then we could integrate the UI into your service.
