### ISSUE TITLE
[1.5][pnomolos] Send Modal Tweaks

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1013]
## Properly deduct fee when sending entire balance
- [ ] When sending all BTS to another account, we should deduct the fee from the total being sent, otherwise it generates an error for insufficient BTS.

![send](https://user-images.githubusercontent.com/1254810/34908282-a9c40df0-f852-11e7-9613-5dd66d8712ae.gif)

## Tabbing and Enter
- [ ] Users should be able to tab through all input fields and press enter to send.

## Alignment of Contact Icon
- [ ] Fix the css for the vertical and horizontal alignment of the contact icon

**Comment by pnomolos** [comment]
Since I've been working in the Send modal a lot anyway I wouldn't mind taking this, but I'm not sure if I can have it finished for Monday.

**Comment by pnomolos** [comment]
@wmbutler By the 'contact icon' do you mean the little green outline of a person (next to 'Lifetime Member' in your example)?

**Comment by pnomolos** [comment]
@wmbutler In your example you click "Available" to select the entire balance, which works fine (it subtracts the fee amount).  However, you then enter something in "Memo", which means the fee increases (but the amount you've chosen to send does not).  Do we really want to silently adjust the total being sent in that use case?  Perhaps we need some way of informing a user that by entering a memo the fee required for sending has increased - or a separate control that indicates you want to send as much BTS as you're able to.

**Comment by wmbutler** [comment]
> By the 'contact icon' do you mean the little green outline of a person (next to 'Lifetime Member' in your example)?

Yes

> Do we really want to silently adjust the total being sent in that use case?

I think we do. But this gets a little tricky because if the user has BTS in their account (i.e. they aren't sending their entire balance), we want to increase the fee. In the case where they are sending the whole balance, we will need to increase their fee and simultaneously decrease the send amount.

**Comment by pnomolos** [comment]
> Users should be able to tab through all input fields and press enter to send.

I've fixed this, but there's no "focus" style on the buttons, which means you can't tell you're tabbing on to the buttons.  Is this something that should be applied just to the SendModal's form buttons, or something that should be addressed globally?

**Comment by wmbutler** [comment]
I'd say globally, nice catch. Let me play with some css for focus and get back to you.

**Comment by pnomolos** [comment]
> In the case where they are sending the whole balance, we will need to increase their fee and simultaneously decrease the send amount.

Maybe only reduce the amount being sent if it's going to be greater than (available balance - send fee)?  My only concern is that if you enter a memo but later remove it, there's no reliable way to differentiate that case from the case where you entered an original amount to be sent that was _almost_ the full balance.

**Comment by wmbutler** [comment]
As I reviewed this, it appears that the tab action is moving to the screen behind the modal. Let's not worry about the css related to focus for this issue. We can do that as a global css effort. We still need to be sure that tab order is set.

> Maybe only reduce the amount being sent if it's going to be greater than (available balance - send fee)? My only concern is that if you enter a memo but later remove it, there's no reliable way to differentiate that case from the case where you entered an original amount to be sent that was almost the full balance.

That's true. What if we only add the memo to the **fee** as the user types (without altering the send amount), then we adjust the send amount only **after** the user clicks send. This will allow us to track the fee but properly perform this calculation when a users balance is being zeroed.

**Comment by pnomolos** [comment]
> As I reviewed this, it appears that the tab action is moving to the screen behind the modal. Let's not worry about the css related to focus for this issue. We can do that as a global css effort. We still need to be sure that tab order is set.

I'm not seeing it on the page I'm testing on, but I'm guessing you're probably running in to issues due to `tabindex` being a global property.  I'll set tabindex to start at 200 on SendModal to avoid issues like that.

> That's true. What if we only add the memo to the fee as the user types (without altering the send amount), then we adjust the send amount only after the user clicks send. This will allow us to track the fee but properly perform this calculation when a users balance is being zeroed.

So make a very specific case that (when send button is hit) if the total amount is over the user's balance by `fee for memo - fee for no memo` we silently adjust and go?

**Comment by pnomolos** [comment]
@wmbutler My apologies for the radio silence on this.  I've been working on the best way to deal with balancing the send amount and fees when the memo is changed, because we also have to take into account the use case where the user enters a partial memo, click on the full balance, then makes the memo longer.  If we're going to doing with adjusting for the memo we might as well handle all the cases.

What if the fee and amount are adjusted in the on-change handler for the memo?  That way everything should still be in sync before the Send button is hit, as opposed to silently changing after the fact.  That should provide a better user experience and should hopefully be a bit cleaner to implement.

**Comment by wmbutler** [comment]
Let's iterate into it. Why don't you create it in the way you think it's best handled and get it posted to so we can try it out? Thanks for thinking through the edge cases so carefully.

**Comment by wmbutler** [comment]
I accidentally paid you 937.50 from bitshares-ui. Can you refund? I paid the correct amount of $437.50 as well.

**Comment by pnomolos** [comment]
Yep, done :)
          
            
            On Jan 22 2018, at 2:54 pm, Bill Butler <notifications@github.com> wrote:
            
            
              I accidentally paid you 937.50 from bitshares-ui. Can you refund? I paid the correct amount of $437.50 as well.
