### ISSUE TITLE
[1][HarukaMa] Exceeded maximum price feed publishers?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1025]
![image](https://user-images.githubusercontent.com/15861527/34922098-21b63780-f983-11e7-8d47-f049df473cef.png)

I was attempting to add many price feed publishers manually instead of relying solely on active witnesses, and I got the following error (as shown in the above screenshot):

```
Assert Exception: o.new_feed_producers.size() <= d.get_global_properties().parameters.maximum_asset_feed_publishers: 
```

Is the maximum quantity of price feed publishers really 10? https://github.com/bitshares/bitshares-core/blob/015026f005123a507c572a0318565383c92e0820/libraries/chain/include/graphene/chain/config.hpp#L75

How can this be the case when you can select "All Witnesses" as publishers? [Cryptofresh](http://cryptofresh.com/a/USD) currently shows well more than 10 price feed publishers for USD.

Worth creating a Bitshares-Core issue over?

**Comment by wmbutler** [comment]
@xeroc or @abitmore may need your input here.

**Comment by HarukaMa** [comment]
For manually assigned feed publishers, the max count is indeed 10 now. Also, you should always consult the live global parameters (object `2.0.0`), not the code, as this value is dynamic and could be changed by committee, just like fees. 

http://open-explorer.io/#/objects/2.0.0

Assets which allow committee members and / or witnesses to publish fees are not affected by this parameter. 

I think you should propose the committee to change that number if you need more than 10 feed producers.

**Comment by wmbutler** [comment]
From a UI perspective then we should honor the 10 max.

**Comment by grctest** [comment]
> I think you should propose the committee to change that number if you need more than 10 feed producers.

There's no risk in increasing this value, right? So requesting the committee change it to say 25 would be reasonable?

In the mean time if the UI prevents adding/updating past the committee set value, that'd be awesome 👍

**Comment by HarukaMa** [comment]
I'd like to claim this too. Will show a warning if more than allowed producers are added.

**Comment by HarukaMa** [comment]
Shared PR #1029 as they are too closely related.
