### ISSUE TITLE
[3][ahdigital][1][gibbsfromncis] Blank screen on non-exist routes

### ISSUE THREAD

**Issue by zhyupe** [bitshares/bitshares-ui#1026]
When you navigate to somewhere not exists, it simply shows a blank page (white in development, but dark in production).
A 404 page is needed to tell normal users what to do.

![image](https://user-images.githubusercontent.com/2197479/34927559-fa3631a0-f9f1-11e7-9f6f-67952744d534.png)
![image](https://user-images.githubusercontent.com/2197479/34927702-1ea32f6a-f9f3-11e7-9a1d-23bdc5406774.png)

**Comment by ahdigital** [comment]
I would be willing to take this on depending on the milestone date.

**Comment by wmbutler** [comment]
We need a redirect for a non-existent route to a 404 page. Copy:

"This page does not exist"

Button (bitshares blue): Home

URL: `/`

**Comment by ahdigital** [comment]
I have created the 404 page and it looks like this:

![404-example](https://user-images.githubusercontent.com/3088454/35162376-0b2266f4-fd3b-11e7-9bc5-cf10949731d1.png)

However, I'm having a a problem getting the routing to work correctly. On my dev machine the 404 page is displaying as intended when any URL that doesn't match a route is entered **apart** from when the URL contains /#/.

For example, this URL will redirect to my 404 page:
`http://localhost:8080/non-existent-url`

But this URL will only load the homepage:
`http://localhost:8080/#/non-existent-url `

I'm new to ReactJS so will continue working on it, but we may have to get someone who understands the routing a bit better to finish it off.

**Comment by wmbutler** [comment]
@calvinfroedge can you offer a tweak here?

**Comment by ahdigital** [comment]
@wmbutler Thanks for the follow up. Would be good to get help on this. I've spent over 2 hours trying to fix it, but it's not happening.

I can share the code and assets for the page if Calvin csn help.

**Comment by wmbutler** [comment]
@calvinfroedge I can add time on this for you if you will help finish it.

**Comment by zhyupe** [comment]
@ahdigital I think it's OK. Your development environment uses “browser history”, and the hash is ignored by the router.

**Comment by zhyupe** [comment]
My fault ... clicked the wrong button

**Comment by wmbutler** [comment]
I need someone to claim and execute based on @ahdigital UX.

**Comment by gibbsfromncis** [comment]
PR: #1361
