### ISSUE TITLE
[1][HarukaMa] UI should not allow committee and witness feed flags together

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#1027]
You can't allow committee members and witnesses to publish feeds for smartcoins simultaneously. When creating or modifying a smartcoin, the corresponding flags should not be allowed to be enabled together, either by an error notify or disabling another one.

**Comment by grctest** [comment]
Yeah, It fails once you attempt to submit the asset changes rather than prompt you with an error upon changing the flags.

**Comment by wmbutler** [comment]
Properly manage expectations when adding to this list. Can we filter out during the selection process and throw an error based up the account role?

**Comment by HarukaMa** [comment]
I'd like to claim this. What exactly is "filter out during the selection process and throw an error based up the account role"? @wmbutler

**Comment by wmbutler** [comment]
Maybe you need to disregard my comment and just go on the previous dialog with OP. I may not fully understand the requirements here.
