### ISSUE TITLE
[2][dot5enko] CR on exchange site

### ISSUE THREAD

**Issue by apiekarczyk** [bitshares/bitshares-ui#1036]
Because of I very often monitor CR parameter it'll be very useful to see its value on every site in the wallet and especially on exchange site where most of us are spending most of time :)

Regards, Andy.

**Comment by wmbutler** [comment]
What is a CR parameter?

**Comment by apiekarczyk** [comment]
Collateral ratio

**Comment by fractalnode** [comment]
Totally agree we need our current Collateral ratio and Call Price next to Settlement (Feed Price)

**Comment by HarukaMa** [comment]
I don't think personal (current active account) information should be in the exchange ticker. Maybe somewhere near buy/sell controls but definitely not in the ticker.

**Comment by wmbutler** [comment]
- [ ] Place Collateral Ratio to the right of Settlement.
- [ ] Use same label format "Collateral Ratio"
- [ ] Only show Collateral Ratio if the user has collateral posted for that particular market (i.e. bitUSD/BTS, HERO/BTS)
- [ ] Color Collateral Ratio according to Orange or Red criteria currently being used for other areas.

**Comment by apiekarczyk** [comment]
"Color Collateral Ratio according to Orange or Red criteria currently being used for other areas."

Me, personally, would like to see all my CRs in my field of view as offten as possible becouse CR is one of the most important parameters for actively trading users. It could be even active field to click to open 'borrow editor'. Don't know if it is possible but maybe even somwhere between 'send' and padlock?

**Comment by fractalnode** [comment]
CR is as important information as the Settlement

**Comment by dot5enko** [comment]
i claim this

**Comment by dot5enko** [comment]
colors are the same as in margin positions page except when it green: i thought it would be more "comfortable" if it would be white:
![image](https://user-images.githubusercontent.com/5626922/35654558-5bb8af00-06f6-11e8-95c3-e1d71885446d.png)
