### ISSUE TITLE
[2.5][ahdigital] Inconsistent UI styling

### ISSUE THREAD

**Issue by ahdigital** [bitshares/bitshares-ui#1039]
# Issue
Whilst using the DEX I can see that there is inconsistent CSS styling which apart from appearing unprofessional/unfinished is mainly causes problems with text legibility. Mainly, the issues are:

- Many different font sizes
- Incorrect font weights causing blurry text*
- Incorrect colors (E.g. Anchor text is not BS blue from the logo)
- Inconsistent casing

*For example: 
![text-blur](https://user-images.githubusercontent.com/3088454/35111454-368e2620-fc73-11e7-851a-9c7f386f4a37.png)

## Proposal
I would like to propose spending 2 hours to review the DEX and make as many CSS updates as possible to address the points above. If I require any longer, I can comment back on this issue.

## Additional responsive amendments
I also have found some issues with mobile UI responsiveness, most of which are small fixes. I don't know whether or not we could agree to raise the hours on this ticket to cover them or if you want me to create something similar to this whereby I can fix as many as possible in the time given without raising a separate ticket for every minor bug.

**Comment by wmbutler** [comment]
Don't spend a lot of time on the exchange since many of the controls will be swapped for TradingView Libraries. Regarding other styling inconsistencies, there are a number of open issues related to them, but we would benefit from someone who is highly skilled in UX/UI owning this process. Happy to move forward with you but only if you are confident in your ability to not only point out the issues but to take ownership if the needed fixes.

**Comment by ahdigital** [comment]
@wmbutler I have made a PR for this now. I made as many CSS fixes as I could in the time allowed, but as each tweak is so minor I haven't taken screenshots for each as they're largely similar issues throughout.

**Comment by wmbutler** [comment]
Can you post the revisions here?

**Comment by ahdigital** [comment]
You mean just the list of commits?

**Comment by wmbutler** [comment]
Sorry, a licecap of the changes. Not required but makes it easy to spotcheck.

**Comment by ahdigital** [comment]
It's difficult to screenshot all of the amendments especially since I tried to make changes globally in the SCSS, and many were minor tweaks like standardizing font sizes and weights. On my branch there were  213 lines of styling changed for these things because as well as the SCSS changes, many styles are applied inline so it takes longer to find and make corrections in all the files.

Below are some screenshots showing general updates, but some may be hard to spot once GH resizes them:

![1](https://user-images.githubusercontent.com/3088454/35679776-286cd342-0750-11e8-9aae-ef30e16eaace.jpg)
![2](https://user-images.githubusercontent.com/3088454/35679787-33216d3e-0750-11e8-9807-d7c49dd1a858.jpg)
![3](https://user-images.githubusercontent.com/3088454/35679813-5033b3f0-0750-11e8-8a58-ace1ce965e10.jpg)
![4](https://user-images.githubusercontent.com/3088454/35679815-51ca8b3a-0750-11e8-9a5b-e6c889cecbac.jpg)
![5](https://user-images.githubusercontent.com/3088454/35679816-5305336a-0750-11e8-841e-4a5c8189874a.jpg)
![6](https://user-images.githubusercontent.com/3088454/35679818-53f97344-0750-11e8-8b92-31aafba0a926.jpg)
![7](https://user-images.githubusercontent.com/3088454/35679820-55104d2a-0750-11e8-83f7-a7f12dc86d92.jpg)
![8](https://user-images.githubusercontent.com/3088454/35679823-56a7138a-0750-11e8-8fdd-7d821e486392.jpg)
![9](https://user-images.githubusercontent.com/3088454/35679825-58879792-0750-11e8-955b-e7b9ba8de3a6.jpg)
![10](https://user-images.githubusercontent.com/3088454/35679827-598af896-0750-11e8-9791-ff22e73b4945.jpg)
![11](https://user-images.githubusercontent.com/3088454/35679830-5a9a5f56-0750-11e8-9150-f4dbd9389545.jpg)
![12](https://user-images.githubusercontent.com/3088454/35679833-5bb0ed2e-0750-11e8-9dc1-7f6ac68deb5e.jpg)
![13](https://user-images.githubusercontent.com/3088454/35679835-5cdf5be0-0750-11e8-8e43-f74f9568b280.jpg)
![14](https://user-images.githubusercontent.com/3088454/35679836-5dadf5f4-0750-11e8-941e-786d3e760fcd.jpg)

**Comment by wmbutler** [comment]
Thanks. Added .5

**Comment by wmbutler** [comment]
Did this get merged into 180201?

**Comment by ahdigital** [comment]
I did, yes.
