### ISSUE TITLE
BitShares light client freezing, had to force quit twice after update

### ISSUE THREAD

**Issue by r-t-c** [bitshares/bitshares-ui#1040]
had to force quit BTS light client after update twice so far after it freezes, looks like it does not complete loading, initial blank screen once, some text another time but unresponsive, running Mac OS High Sierra Version 10.13.2 (17C205) on MacBook Pro (Mid 2012) 2.7 GHz Intel Core i7

**Comment by r-t-c** [comment]
Bitshares.180115

**Comment by wmbutler** [comment]
I'm having all kinds of problems with sockets too right now. @mattbeckman is working on a fix in the js library. https://github.com/bitshares/bitsharesjs-ws/pull/11

**Comment by mattbeckman** [comment]
@wmbutler: What specs are you running on? I'm on macOS High Sierra as well. Curious if many of our problems are related to High Sierra, as I found the following thread specifically about Chrome, Slack, and Electron graphic issues after updating to High Sierra: https://github.com/electron/electron/issues/10736

**Comment by wmbutler** [comment]
Hign Sierra, MacBook, Web Browser (not electron).

**Comment by mattbeckman** [comment]
Interesting. I thought Bill was using the Electron light client. I don't usually have issues in the web browser, where the performance for me is a lot better, so I have been attributing most of the issues to Electron. It's likely a combination of factors, and we may need to add sprint items for different ways to improve performance. 

I'm still looking into the web socket angle, but congestion as the primary factor is a legitimate theory.

**Comment by landry314** [comment]
When I have only one node connecting at high latency this is when this issue arises for me. They seem completely correlated. It is as if when the application reloads and tried to connect and can't find anything it just sits there. This is why I think it is poor node connections causing this.

Interestingly, when I am having this problem, I have been throwing out my application support folder in library then opening the application again and restoring my wallet. When I do this I can connect, see more nodes and have better latency. It doesn't last very long but it works for a short time. It is quite curious that fresh preferences in the library folder would allow me to connect to nodes better.

**Comment by startailcoon** [comment]
related to #1195 perhaps?

**Comment by wmbutler** [comment]
Should be fixed for the 180302 release.
