### ISSUE TITLE
OpenLedger problem, I can't place orders and send funds to users

### ISSUE THREAD

**Issue by TheDesmondHume** [bitshares/bitshares-ui#1042]
Hi,

Today I am experiencing a strange problem with OpenLedger.io, I am not able to place buy/sell order and I am also not able to send funds to users. 

After I click confirm of the order it doesn't say anything but my order it's not filled, it's the same with transferring funds.

Please don't guide me for trying Bitshares wallet or any other redirected URL's because I can only log in on OpenLedger from my Google Chrome.

What may be the issue here?
Thanks.

**Comment by ahdigital** [comment]
What asset(s) are you trying to place orders for and what values are you entering?

Desktop or mobile? If mobile, what device please.

**Comment by TheDesmondHume** [comment]
Hi,

I tried with buying like 0.1 ETH, I also tried to buy BTS too but no luck. I tried to send some tokens to other user but the transfer never filled. 

I am currently signed in on Google Chrome on windows 10 (openledger.io)

**Comment by wmbutler** [comment]
We don't develop the UI for openledger.io. This software is specifically available at https://wallet.bitshares.org. You can import your bin file to this address and let us know if you still have an issue. Closing.

**Comment by TheDesmondHume** [comment]
Okay, I tried using your link https://wallet.bitshares.org/ and I've restored my account with the bin file, but whenever I go to log in, it says this: http://prntscr.com/i2iizv

After that I can't click on Login again, that function is not available. What should I do?

**Comment by wmbutler** [comment]
Try forcing this endpoint and set:

General -> Login Mode to Local Wallet Login

**Comment by TheDesmondHume** [comment]
I am selecting Local Wallet Login but when I go to Login the Login button won't work again.

**Comment by happyconcepts** [comment]
@wmbutler @OpenLedgerDev @svk31

> Okay, I tried using your link https://wallet.bitshares.org/ and I've restored my account with the bin file, but whenever I go to log in, it says this: http://  <--removed

It seems that when attempting to log in, the user's client is attempting to connect or send a screenshot to that URL of a screenshot posting service. This might be a user safety issue and therefore might be worth investigating further to confirm it isn't systemic.

**Comment by TheDesmondHume** [comment]
Thank you, I have some funds that I am scared of losing so I hope that this will get solved because I love using OL. I have created a backup file so if you need some more info I can leave Skype or we can try Team Viewer for a better look at this situation.

**Comment by TheDesmondHume** [comment]
Any update?
