### ISSUE TITLE
[1][startailcoon] misleading name in top information panel

### ISSUE THREAD

**Issue by fractalnode** [bitshares/bitshares-ui#1043]
In our wallet we call Settlement Price which is actually Feed price

Settlement Price =  Feed price + Settlement Offset

Both informatcion are very important, so I propose to rename Settlement for Feed Price and add real Settlement by calculate Feed price + Settlement Offset

ATM this look like this
bitUSD: Settlement Price =  Feed price + Settlement Offset (+1%)
bitCNY: Settlement Price =  Feed price + Settlement Offset (+5%)

![settle](https://user-images.githubusercontent.com/20418259/35170246-cd15b206-fd5f-11e7-933c-c113940a155c.jpg)

![cny](https://user-images.githubusercontent.com/20418259/35143284-6b26405a-fd01-11e7-9c62-137bdae15bfb.png) 
![usd](https://user-images.githubusercontent.com/20418259/35143400-b2a8b430-fd01-11e7-994d-6d967154fc0d.png)

source: 
https://cryptofresh.com/a/CNY
https://cryptofresh.com/a/USD

![8](https://user-images.githubusercontent.com/20418259/35171347-d40de0b6-fd63-11e7-9989-9b4c077a3249.png)
________________________________________________________________________________________________________
________________________________________________________________________________________________________

![6](https://user-images.githubusercontent.com/20418259/35171220-435c101a-fd63-11e7-84d1-695e1396bbb4.png)

**Comment by apiekarczyk** [comment]
Yes, this would be shown very clear in UI.

**Comment by startailcoon** [comment]
I can do this as I've dived in to the issue on the #744

**Comment by wmbutler** [comment]
@startailcoon status?

**Comment by startailcoon** [comment]
Should we add the Settlement Price to the depth chart as well, now when it's the feed price?

![image](https://user-images.githubusercontent.com/12114550/35779441-50cacf36-09cd-11e8-8a7f-5794d37f1c36.png)

**Comment by startailcoon** [comment]
closing issue
