### ISSUE TITLE
[.5][ahdigital] Increase line spacing in memo field on send modal

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1050]
This line spacing is definitely less than 1. This is an easy tweak. A global fix would be ideal. Made this 0.5 to encourage testing.

- [ ] Send Modal
- [ ] Deposit Modal

<img width="499" alt="screen shot 2018-01-20 at 6 48 41 pm" src="https://user-images.githubusercontent.com/1254810/35189583-07bdd6a0-fe13-11e7-88e7-fa44f6322209.png">

**Comment by ahdigital** [comment]
I can fix and will check globally.

**Comment by ahdigital** [comment]
@wmbutler 

I've made the following updates:

- Added line-height to textarea inputs (globally) to make lines of text more legible
- Increased height of memo textareas from 1 to 3 rows.
- Removed manual line break from modal header text ("Transfers are used for..") and converted into a paragraph element to ensure a nice line-height also

![modal-textarea](https://user-images.githubusercontent.com/3088454/35212961-dbc265e2-ff53-11e7-89c4-f614939fe5d8.PNG)

Happy for me to submit a pull request?
