### ISSUE TITLE
Extremely poor user experience under adverse network conditions + privacy concerns

### ISSUE THREAD

**Issue by xmr-karnal** [bitshares/bitshares-ui#1051]
Since a couple of months back I have noticed that 90% of the times I launch the client (no matter the version, I have updated the software here and there), after the "Loading...", all that is shown is a blank window.

Using tcpdump I can see a bunch of DNS requests followed by TCP connections - indeed, a problematic behavior in itself from a privacy standpoint, why is my client advertising to servers all over the world that I just launched the software?.

And then .. nothing. I have left the client running for 10, 20, 30 minutes, and there is zero visual feedback that something is happening.

Other than having logged on from pretty slow networks over the last few months, I am also proxying the wallet transparently through tor.

Either way, the whole UI should not freeze because some server(s) are not reachable.

Also, please consider not making so many connections to random servers over the internet without user input.

**Comment by HarukaMa** [comment]
About "random servers": they should all be api nodes. The wallet need to connect to all of them once in order to tell latencies. Check if your captured requests match those in settings - access.

**Comment by landry314** [comment]
This happens to me sometimes too.

It happens when the nodes are overloaded and it can't find one with a decent latency. I need to force quit and try again. Bad user experience.
