### ISSUE TITLE
[1][ahdigital] Clear search box on the click of “x”

### ISSUE THREAD

**Issue by fractalnode** [bitshares/bitshares-ui#1054]
![clear-search-box](https://user-images.githubusercontent.com/20418259/35213248-429b23d6-ff5d-11e7-8a3e-b79eb70711f9.png)

**Comment by ahdigital** [comment]
I can do this amendment.

**Comment by ahdigital** [comment]
I can complete this task.

**Comment by wmbutler** [comment]
It's yours.

**Comment by ahdigital** [comment]
@wmbutler 

I've implemented this feature, as seen in the example below. Are you happy for me to submit pull request?

![clear-input](https://user-images.githubusercontent.com/3088454/35263982-d44658c2-0012-11e8-92fd-829878a1239c.gif)
