### ISSUE TITLE
user adoption stinks, fix the ui

### ISSUE THREAD

**Issue by lbn349** [bitshares/bitshares-ui#1055]
Ok, was comenting on telegram that user adoption stinks. admin said do something about it. then he got so insulted he banned me from telegram. ok ill do something admin:
bitshares user adoption stinks. fix the ui. separate the wallet from the exchange. have a traditional bitcoin electrum wallet in the ui, with button for, 'open exchange in separate window'. thats how its done. conflating the sending of crypto with a overly complex exchange wallet with a million features fu()s with user adoption. and therfor fu()s with my investment in bts. so fix it. 
also fix ur overly complicated website. stop shoving linux commands into non tech savvy ppls faces

**Comment by wmbutler** [comment]
Go fuck yourself.
