### ISSUE TITLE
[1] Display current black swan price for bitassets

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares-ui#1056]
the GUI should state the current black swan price for all smartcoins so we don't have to calculate it

**Comment by wmbutler** [comment]
Where do you think they should be displayed?

**Comment by fractalnode** [comment]
I am afraid that people will subconsciously want to achieve this price. 
Additionally, it will drive fear..

**Comment by jonnybitcoin** [comment]
We should be open and transparent about the risks of holding bitassets.
People should be able to see at a glance how close to black swan they are
so they can judge the risks for themselves of holding. Being clear shows we
have confidence in our pegging system. Not showing it shows we aren't
confident.

On 23 Jan 2018 11:26, "fractalnode" <notifications@github.com> wrote:

I am afraid that people will subconsciously want to achieve this price.
Additionally, it will drive fear..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitshares/bitshares-ui/issues/1056#issuecomment-359761599>,
or mute the thread

**Comment by jonnybitcoin** [comment]
In addition to negate fear we could do with renaming black swan to
something boring and technical. Talebs definition of black swan is
different than ours. Essentially it's something that's so unlikely to
happen people assume it can't. We've had a few Bts black swans already.

On 23 Jan 2018 12:46, "Jonathan James Harrison" <
jonathanjamesharrison@gmail.com> wrote:

We should be open and transparent about the risks of holding bitassets.
People should be able to see at a glance how close to black swan they are
so they can judge the risks for themselves of holding. Being clear shows we
have confidence in our pegging system. Not showing it shows we aren't
confident.

On 23 Jan 2018 11:26, "fractalnode" <notifications@github.com> wrote:

I am afraid that people will subconsciously want to achieve this price.
Additionally, it will drive fear..

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitshares/bitshares-ui/issues/1056#issuecomment-359761599>,
or mute the thread

**Comment by fractalnode** [comment]
>> In addition to negate fear we could do with renaming black swan to something boring and technical.

Technical name is "Global Settlement"
Black Swan means rare or unlikely event

**Comment by jonnybitcoin** [comment]
Where do you think they should be displayed?

https://wallet.bitshares.org/#/asset/USD

**Comment by nbcks** [comment]
I've added this feature to the price feed tab, is this what you had in mind?
![screenshot from 2018-01-28 17-24-07](https://user-images.githubusercontent.com/16877932/35484958-29a9bec6-0450-11e8-98c6-f5be0e1eaa17.png)

**Comment by nbcks** [comment]
I had to add a translation to the price feed local in the explorer.asset key. Is there a ready made translation for global settlement price? Also is the global settlement price really part of the price feed? Or should we put it in the margin positions tab?

**Comment by wmbutler** [comment]
@svk31 ?

**Comment by svk31** [comment]
There wasn't any existing keys so that's fine.
