### ISSUE TITLE
[4.5] It is not possible to settle prediction market token in GUI

### ISSUE THREAD

**Issue by fractalnode** [bitshares/bitshares-ui#1065]
Bitshares has a built-in Binary prediction market but it is disabled in such a way that it is impossible to settle the token in the GUI. The required options are hidden from normal users (or work in this area has not been completed) and is only available from command line in CLi wallet.

Probably many of you remember the time that projects offering only this functionality reached 400 million capitalization while the entire bitshares were worth only 50 million.

**Comment by wmbutler** [comment]
Added 5 hours as a starting point.

**Comment by adamvp** [comment]
I'd like to bet using bitshares! Great idea!
Please make it top prio Devs!

**Comment by sschiessl-bcp** [comment]
@svk31 
Is that already supported in bitsharesjs?

**Comment by wmbutler** [comment]
@fractalnode this really needs an in depth discussion to simplify the process. Most users don't understand the concept of borrowing and shorting and asset to take the opposite bet. Open to suggestions here.

**Comment by fractalnode** [comment]
@wmbutler in first step we have to have MVP - simple Settle button in asset page.
ATM we have something like this: http://docs.bitshares.org/bitshares/tutorials/pm-close-manual.html
in second step we'll all think about how to simplify it.
We have to finally resolve this issue, and keep our promises about Prediction Market in BitShares with we gave in 2015, this is still in our features list but we really don't have it.
If today we were to implement bitUSD concepts, would we not do it because it is too difficult for users? Derivatives / crypro exchange is not for Mrs. Smith from vegetable store. 
We are different. BitShares is like state of mind and I'm proud of it.

**Comment by abitmore** [comment]
The word "settle" is confusing. We already have a settle button in account page, adding another "settle" with different meaning is not the best IMHO.

**Comment by sschiessl-bcp** [comment]
In the meaning for prediction market we could call it "Resolve"

**Comment by adamvp** [comment]
why this issue still open? nobody believes in potential of this solution?

**Comment by sschiessl-bcp** [comment]
I think this would be nice as a Spotlight! I ll put some thought in it

**Comment by startailcoon** [comment]
@sschiessl-bcp did you get some thoughts assembled on this topic?
Pushing this to July to enable some discussion time.

**Comment by sschiessl-bcp** [comment]
Will be added in #2717, but we should add it as an "Asset Action" in the asset overview, for example https://develop.bitshares.org/#/asset/TRUMPIMPEACH

Tasks for this issue:
 - Show a "Resolve prediction" asset actions
     - [ ] Only input is a "Yes" and "No" toggle and "Publish" button
     - [ ] "Publish" is only clickable after resolution date has passed, if not passed show a tooltip

**Comment by sschiessl-bcp** [comment]
Adusted scope a bit, see PR.

Bounty request: 4.5
Hours worked: 8.5
