### ISSUE TITLE
Bitshares wallet charts are not loading

### ISSUE THREAD

**Issue by ihorml** [bitshares/bitshares-ui#1067]
Try to open any pair from `Top Markets` on wallet.bitshares I can't see charts. I have this error in console: 

Browser: Google Chrome, MacOS 

<img width="1440" alt="screenshot 2018-01-27 15 29 12" src="https://user-images.githubusercontent.com/7770343/35472839-008425b0-0377-11e8-969c-cd3eb02f3725.png">

**Comment by ihorml** [comment]
More errors if I scroll console down:

<img width="1440" alt="screenshot 2018-01-27 15 31 54" src="https://user-images.githubusercontent.com/7770343/35472857-3b07df56-0377-11e8-8568-e6c8d595b51f.png">

**Comment by ihorml** [comment]
It's strange. Bug is gone when I clear localStorage.

**Comment by wmbutler** [comment]
LIkely has something to do with the API node you are connecting to.
