### ISSUE TITLE
[.25][gibbsfromncis] Do redirect to Top Markets after login on bitshares wallet

### ISSUE THREAD

**Issue by ihorml** [bitshares/bitshares-ui#1068]
1) Go to https://wallet.bitshares.org/#/create-account
2) Click 'Login'
3) Write credentials
4) Do Login

But I'm still on Login scene.
<img width="1440" alt="screenshot 2018-01-27 15 39 25" src="https://user-images.githubusercontent.com/7770343/35472919-46990452-0378-11e8-9422-72aab8fde7a1.png">

**Comment by wmbutler** [comment]
Maybe it makes more sense to go to the user portfolio/dashboard after logging in?

**Comment by gibbsfromncis** [comment]
Pull Request: #1088
