### ISSUE TITLE
[1][startailcoon] Searching for an asset doesn't appear even when it exists due to lag

### ISSUE THREAD

**Issue by nbcks** [bitshares/bitshares-ui#1070]
The bug can be seen when you search for an asset in the explore tab. What happens if you search for an asset such as BitSEK by typing in 'SEK' is that nothing will show for a couple of seconds, then the wallet will have loaded the assets, it will display BitSEK. 

The problem with this of course is that the user might presume the asset doesn't exist after a few seconds and leave. 

A solution would be to have some sort of graphical element which would signal to the user that the wallet is still searching for the asset. Then when all the assets have been enumerated through, the wallet would display them in a list OR display 'no assets found'.

**Comment by startailcoon** [comment]
We should add the loading indicator while it's searching for assets, users etc.

I've noticed the same behaviour, especially now when most nodes are getting more traffic

**Comment by btsfav** [comment]
yeah, a loading animation would be good.

**Comment by wmbutler** [comment]
Maybe ahdigital can UX this?

**Comment by startailcoon** [comment]
I can claim this and use the present loading animation we have for everything else presently.

**Comment by startailcoon** [comment]
## Tasks

- [ ] Implement input delay of 2500ms to decrease multiple queries
- [ ] Implement "loading screen" when fetching data to view.

**Comment by abitmore** [comment]
Currently, the asset search feature fetches and caches all assets from back end, then perform the search locally. As commented in https://github.com/bitshares/bitshares-core/issues/688#issuecomment-368257926, please try NOT to fetch all assets only for the search feature. Sooner or later it will be unpractical to do so. Why the account search feature is not implemented this way? Perhaps we need compromised UX. Perhaps we need another API or API set.

**Comment by startailcoon** [comment]
@wmbutler I advice opening a new ticket for implementing a new way to search for assets. The current way may not be the best way to do it as @abitmore writes.

**Comment by ahdigital** [comment]
> I advice opening a new ticket for implementing a new way to search for assets.

Perhaps something like Elasticsearch would be a good use for searching. I've seen it used on projects before and it is very fast at fetching and returning data.

> A new loading indicator could be a future task and overhaul everything.

As you know, on Telegram we've been discussing Ant Design. Here is a clean approach to using a [loading indicator on tables](https://ant.design/components/table/#components-table-demo-dynamic-settings). Try toggling the 'Loading' switch.

**Comment by wmbutler** [comment]
This will need to go to ES for sure.
