### ISSUE TITLE
[.25][gibbsfromncis] Shift "Propose From" dropdown so it left aligns with place order contents

### ISSUE THREAD

**Issue by ihorml** [bitshares/bitshares-ui#1071]
Just a simple low priority issue.

If you toggle the `propose` switch the place of `Propose from` dropdown is a little bit wrong. it should be aligned by `Place Order` section like this:

<img width="563" alt="screenshot 2018-01-27 18 20 12" src="https://user-images.githubusercontent.com/7770343/35474627-5232a2be-0391-11e8-9aa8-d4fb25d32f7b.png">

Now it looks like this:

<img width="563" alt="screenshot 2018-01-27 18 20 12" src="https://user-images.githubusercontent.com/7770343/35474454-bdfa1d18-038e-11e8-9ecf-e14e917af345.png">

**Comment by wmbutler** [comment]
Can you be more specific?

**Comment by ihorml** [comment]
@wmbutler updated

**Comment by gibbsfromncis** [comment]
@wmbutler assign to me please

**Comment by gibbsfromncis** [comment]
Pull Request: #1086
