### ISSUE TITLE
call price wrongly calculated for user shenxiaoyu521

### ISSUE THREAD

**Issue by nbcks** [bitshares/bitshares-ui#1075]
The user shenxiaoyu521 has a margin position in bitCNY where they have a debt of 1100 bitCNY and a collateral of 805.9 BTS. At the time of writing, their CR is 2.5 and the feed price is 0.29. This checks out since 805.9 / (0.29 * 1100) = 2.5. There call price should therefore be 805 / (MCR * 1100) = 0.4186. However, the call price displayed is 0.29486, which is incorrect. This is clearly incorrect since shenxiaoyu521 would be very close to getting margin called if their call price was so close to their feed price, yet they have a healthy collateral ratio of 2.51 (rather than a CR close to 1.75).

Steps to reproduce:

1) Visit shenxiaoyu521 in the wallets asset explorer
2) Click margin positions
3) Observe the collateral ratio, debt and call price columns

**Comment by nbcks** [comment]
![screenshot from 2018-01-28 15-32-09](https://user-images.githubusercontent.com/16877932/35483967-805b87aa-0440-11e8-9938-8f200154e3cb.png)
![screenshot from 2018-01-28 15-32-34](https://user-images.githubusercontent.com/16877932/35483968-81f4766c-0440-11e8-98eb-beb2cda1703e.png)

**Comment by abitmore** [comment]
Actually this is a core issue. That user's position was partially called, so showing a higher ratio, but the call price didn't change, so it will still be called at the original call price. https://github.com/bitshares/bitshares-core/issues/343

**Comment by wmbutler** [comment]
OK, so once the core issue is fixed, it's your believe that the UI will work as it's supposed to? If this is the case, I will leave this open but not put it into a Sprint.

**Comment by nbcks** [comment]
Ah that makes perfect sense since the UI seemed to be functioning quite well.

**Comment by nbcks** [comment]
You might say that we should instead sort the call orders by collaterial ratio rather than call price for the margin positions tab in assets (I think they are sorted by call price presently)?

**Comment by wmbutler** [comment]
Interesting thought. @abitmore what do you think about changing the sort to be the ratio?

**Comment by abitmore** [comment]
I tend to update the call price field (in the core) directly when it's partially called, so call price and ratio will always match each other. But I'm not sure if it's technically practicable so far, or how hard to implement it. Will figure it out in next weeks.

**Comment by nbcks** [comment]
I've made the change where it sorts by ratio, thoughts?

**Comment by abitmore** [comment]
If people can click the table header to sort by their own, would be useful. Anyway I don't think we need to change the default sorting.

**Comment by nbcks** [comment]
You can change both the direction and column to sort by. What we CAN change is the default sort. Anyway, sorting by call price should be the same as sorting by CR. Given this, shouldn't we default the sort to collateral ratio instead of call price @abitmore ?

**Comment by abitmore** [comment]
Different sorting has different purpose. If you've read the linked issue above, in the backend (right now), sorting by call_price is for margin calls, sorting by real collateral ratio is for force settlements. After the backend issue is fixed, both will return same result. I don't think it's wise to put efforts/time on changing default sorting right now, unless there are strong reasons showing that sorting by one field is much important than the other and need an emergency fix.

**Comment by wmbutler** [comment]
I agree with @abitmore. We are trying to fix a problem that will go away with no effort.

**Comment by nbcks** [comment]
Okay, close the issue then?
