### ISSUE TITLE
Question: How to properly logout

### ISSUE THREAD

**Issue by ihorml** [bitshares/bitshares-ui#1076]
Today I have logged in wallet under somebody's computer and when I want to log out I couldn't find any feature regarding this. I had to clear cookies on browser settings.

We have the feature to lock wallet/account but specially logout (clear sessionStorage, localStorage, cookies) I didn't find.

Is there anywhere this feature? If yes, maybe we should move it somewhere on more visible place?

**Comment by wmbutler** [comment]
Click the lock. That's your logout for the cloud wallet.
