### ISSUE TITLE
[Part of 2602] Smartcoin settle - display estimated delay if high force settlement volume?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1081]
Say 10% of bitUSD is settled (manually instead of via force settlement) by an individual, the max % settle-able is 1% of bitUSD per hour (as per the smartcoin settings), but will the user who clicks 'settle' be made aware of a potential 10 hour delay on top of their 24hr delay?

Perhaps the same warning could trigger if a whale settles & you're wanting to settle a few dollars - that the system will have to wait approx 1 hr extra to settle your funds.

Is this already the case?

**Comment by startailcoon** [comment]
Fixed part of PR for issue #2602
