### ISSUE TITLE
[6][ahdigital] Responsive & aesthetic amendments to on-boarding UI

### ISSUE THREAD

**Issue by ahdigital** [bitshares/bitshares-ui#1082]
The current on-boarding experience for mobile users isn't easy because there are issues with the UI not scaling properly and cutting off elements. Additionally, there are aesthetic improvements that can be made to cut out user frustrations and make the experience more enjoyable.

I propose to fix these issues and implement some nicer styling within 5 hours.

## Issues

The main issues with mobile responsiveness are:

**Landing**

- Elements are cut off from view, the severity of which depends on resolution:
  - The screenshots below are from iPhone 7 res
- It isn't clear to the user if the flag can be tapped on or if it is simply a region indicator 
- There are some unnecessarily big margins in there
- Button text styling is not consistent with other parts of the UI
- Both buttons have the same styling so there is no visual hierarchy for new users

![mobile-landing](https://user-images.githubusercontent.com/3088454/35522911-8427198c-0515-11e8-821b-ce52fba3bea9.png)

**Login**

- Form inputs misaligned
- Button text styling is not consistent with other parts of the UI

![mobile-login](https://user-images.githubusercontent.com/3088454/35523263-5ab35dc6-0516-11e8-9bf3-42cd3ac352b6.png)

**Create account**

- Elements are cut off from view, the severity of which depends on resolution:
  - The screenshots below are from iPhone 7 res
- The header area is just a repeat of the landing view, and doesn't say anywhere 'Create account'
- There are some weird margins appearing in there
- Button text styling is not consistent with other parts of the UI

![create-account](https://user-images.githubusercontent.com/3088454/35523400-ac18f626-0516-11e8-97e6-c87f59610822.png)

**Create account (advanced)**

- As above
- Odd use of bold fonts again

![create-account-advanced](https://user-images.githubusercontent.com/3088454/35523447-cad03746-0516-11e8-8a6f-d8bdb115b1a1.png)

## Proposed updates

**Landing desktop**

- Removed light grey background color from behind container to create more contrast
- Added visual hierarchy to buttons
- Improved meaning for restore/advanced links
- Added down caret to flag to make it feel like a button

![landing-desktop-proposed](https://user-images.githubusercontent.com/3088454/35523517-ef6302e6-0516-11e8-83f0-930e6bbbd109.png)

**Landing mobile**

- As above
- Fix responsiveness

![landing-mobile-proposed](https://user-images.githubusercontent.com/3088454/35523527-f541eb5a-0516-11e8-8cd9-29c11ce158cb.png)

**Login desktop**

- Removed clutter
- Tidied up margins

![login-desktop-proposed](https://user-images.githubusercontent.com/3088454/35523556-06244b02-0517-11e8-9a03-0c1cc949ceac.png)

**Login mobile**

- Fix responsiveness

![login-mobile-proposed](https://user-images.githubusercontent.com/3088454/35523634-35a0100a-0517-11e8-8497-b0cadcf2b70a.png)

**Create account**

- Fix responsiveness on mobile
- Remove duplicated header elements from landing view
- Add 'create account' title
- Make checkbox text look nicer and more legible

![create-account-proposed](https://user-images.githubusercontent.com/3088454/35523647-3cc4655c-0517-11e8-941c-26a23f5e0bc4.png)

**Create account (advanced)**

- Fix responsiveness on mobile
- Remove duplicated header elements from landing view
- Add 'create account' title

![create-account-advanced-proposed](https://user-images.githubusercontent.com/3088454/35523668-467a60f6-0517-11e8-8803-ba2f1aa26193.png)

**Comment by wmbutler** [comment]
This looks good. There is another issue #917 related to this. I'll close it as a duplicaet and consolidate the discussion here. I was really hoping we could get rid of the top menu but will require some thought. The redundant "Create Account" is a little vexing.

Please review the other issue so you can take all aspects into consideration.

**Comment by ahdigital** [comment]
@wmbutler I'll review the issues from the older ticket #917 and also, try to catch issues such as that reported on #1090.

I saw the hours for this set at 3, I think it will take longer than that to complete this work given it involves design, development, testing and reporting amendments back here. Also, now issues from other tickets are being considered.

**Comment by wmbutler** [comment]
Bumped to 6.

**Comment by ahdigital** [comment]
As an update, I've started work on this issue. I've implemented the issues raised here and on the referenced tickets and now just have to finish tying in #1083 which to do, I'm essentially having to rewrite the header.

I'm making bigger code changes to the header than expected so that we end up with a bar that is properly responsive, and the SCSS clean.

I'll have to do some testing to make sure the accounts drop down/local wallet etc. still work but once finished I'll post back with licecaps and summary of changes.

**Comment by ahdigital** [comment]
# Updates

The proposed changes I outlined in the original post are done. Below is a general summary of the bigger amendments along with some Licecaps to demonstrate.

- Updated general UI styling
- Removed redundant 'create account'
- 'Create account' link shown in burger menu if the user is logged out
- Burger menu displays all the time now
- Removed settings from the header bar because it is in the burger menu
- 'Dashboard' link shown in burger menu if the user is logged in
- Removed the big lock/unlock icon
- Added a small lock/unlock icon next to username to tell if logged in or not
- Updated hamburger icon to bitshares blue
- Have added functionality to truncate the username when it's too long for the resolution
- Fixed #1090
- Aligned page title on 'restore backup' view to left
- Tested both login/password and local wallet accounts

## Landing page
![1](https://user-images.githubusercontent.com/3088454/35808068-95889856-0a7c-11e8-8aa7-a4b970a7c315.gif)

## Login modal
![2](https://user-images.githubusercontent.com/3088454/35808106-b22ebfa8-0a7c-11e8-927b-2e650af70df7.gif)

## Create account
![3](https://user-images.githubusercontent.com/3088454/35808124-ba9a79a2-0a7c-11e8-887d-378c28e2f3f6.gif)

## Burger menu (logged out)
![5](https://user-images.githubusercontent.com/3088454/35808143-cb038928-0a7c-11e8-91f3-2c1f87c06aaf.gif)

## Burger menu (logged in)
![7](https://user-images.githubusercontent.com/3088454/35808215-fbbf647e-0a7c-11e8-9cac-31dc15886d4c.gif)

## Issue #1083 fix
![6](https://user-images.githubusercontent.com/3088454/35808199-f09ebbd0-0a7c-11e8-833a-7ce143b20e96.gif)

**Comment by wmbutler** [comment]
On the landing page, it would be nice to eliminate the gray bar at the top.

**Comment by ahdigital** [comment]
Will have a look at changing it just for the landing page.

**Comment by ahdigital** [comment]
@wmbutler Are you happy for me to submit PR for this and address the grey bar at the top later? There are some other things I'd like to work on with a higher priority.

**Comment by startailcoon** [comment]
It shouldn't be difficult to hide the top bar with CSS styles.

**Comment by wmbutler** [comment]
Changing the gray bar will affect other things. As long as you have thought it out. Or you can leave it for a later issue / redesign.
