### ISSUE TITLE
[1] Display modal if switching to an account where you do not hold the keys

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1089]
1) Sign in / Sign up as Wallet account
2) Go to `https://wallet.bitshares.org/#/account/rudex` (you can use any account name)
3) Now all looks like you're logged in under `rudex` account

Bug happens only if you're logged in under Wallet Account. It doesn't reproduce for Login/Password accounts

Gif: 
![gif-wrong-account](https://user-images.githubusercontent.com/35899973/35601531-dec9b3d0-0633-11e8-9986-66be0a869af9.gif)

**Comment by wmbutler** [comment]
You have essentially assumed the role of that user once chosen. Maybe we should force a logout if you choose an account where you do not hold the keys?

**Comment by gibbsfromncis** [comment]
@wmbutler my point of view as a user - if I click on somebody's username I can take a look his account info and that's it. I don't want to assume the role of this user.

It's like on social networks - if you click on Mark Zuckerberg name somewhere you can take a look his profile and more data about this man. And that's it. You are not going to be this user and see his profile as yours. 

Is this the feature? If yes, why it works only for users with wallet account? And what is the main idea of this feature? 

Because mostly it looks like a bug for me.

**Comment by wmbutler** [comment]
It used to be that way, but it is very confusing to see your own account in the menu while looking at someone else's balances, voting, etc. Try to imagine to confusion of a new user suddenly seeing all of their holdings and balanced altered while they think they are still in their account.

**Comment by gibbsfromncis** [comment]
@wmbutler okay, got it. We are on the way to change UX of some parts of Bitshares to help our new users stay with us forever :) Lets make some updates there too. 

Also we can use simple solution like place username (portfolio owner) and his balance on the page. 

But we definitely should change the current behavior.

**Comment by wmbutler** [comment]
Understood, but if you do that, you are going to have to change it everywhere, voting page, vesting balances, the list goes on and on :)

**Comment by gibbsfromncis** [comment]
@wmbutler I think the issue is only on `Account` page - because user gets to logged in after visiting this page so there is no so much effort. 

Please assign me and put estimate for 1.5h. I'll investigate it on the next week and prepare some mocks of Portfolio Owner for your approve. I suppose it's enough time to complete this task. If I see it can take more time I'll notify you for approval.

**Comment by wmbutler** [comment]
OK, be forewarned that this is going to take some creativity. I can assure you that all endpoints matter.

**Comment by gibbsfromncis** [comment]
@wmbutler I think I won't have a time to finish this issue during this Sprint. I'm working on mockups but now I don't have any option I like. 

The common issue I'm thinking about is where to move Account name with balance and some actions buttons like:
- Add user to my contact
- Transfer money
etc. 

@pavel-lipcean Hi, can you help with that? I saw you've prepared so great UI/UX for Settings. Maybe you want to help me with this section?

**Comment by wmbutler** [comment]
I'm not convinced this is groomed to feature status yet. It's also not in a Milestone as a result.

**Comment by gibbsfromncis** [comment]
@wmbutler I do not like this issue but I do not have time for this low priority task. Should I close it or unassign myself?

**Comment by abitmore** [comment]
Actually this needs UX.

Just writing some thoughts here:

* [ ] have an icon, or a symbol (e.g. `!`, `*`, `+` etc) with tool tip, or font/background color, or something else to **clearly** indicate the browsing account is 
  * my account
  * my linked account
  * my contact
  * other

I remember in older versions a blue name means my account or linked account, a white name means others.

* [ ] have an easy/quick way to switch back to "my account(s)"

* [ ] don't simply disable features when the user is on another account due to proposals (https://github.com/bitshares/bitshares-ui/issues/1285)

**Comment by wmbutler** [comment]
I'm struggling with this. @abitmore are you suggesting that a user might not already know the status of the account name at the top? I have quite a few accounts and I know the status of the ones that I own.

We have a really simple account switcher (probably could use a typeahead eventually for extreme cases, but beyond that I'm not sure if we can make it much easier.

Agreed with not disabling features regarding proposals. That is what we are working towards.

**Comment by grctest** [comment]
If you're using the bin key login mechanism, it doesn't mention any of the related accounts in the login modal panel, so if you've browsed one of your secondary accounts (different bin key, not a sub-account) the only username reference you've got is the key filename (default is not descriptive of account) and the top-right invalid username - you might end up trying to enter the password for the secondary account and freaking out that you've lost access even though you're entering the password for that second account perfectly.

I've done this in the past 🤣

**Comment by wmbutler** [comment]
What if we display a modal if you attempt to switch to an account where you do not hold the keys? The modal could have a CANCEL / CONFIRM option. Text might read:

> You are switching to someone else's account and will see everything from their view but will be unable to execute any transactions.

**Comment by startailcoon** [comment]
> 
> 
> What if we display a modal if you attempt to switch to an account where you do not hold the keys? The modal could have a CANCEL / CONFIRM option. Text might read:
> 
> > You are switching to someone else's account and will see everything from their view but will be unable to execute any transactions.

This could be one way of doing it. But I don't think we should do this every time a user changes to another account where he/she doesn't have the keys.

I propose the following

1. User switches to an account that they don't have keys for, as this is done for multiple reasons. The user recieves a notification modal stating `You're switching an account which you don't have active authority over. You will view this account as the active account, but in view mode only`. This would be closable with an OK button, and a tick-box with `Never show this again`.

2. When a user views another account which he/she has no keys for, they should have a narrow bar on the top stating they are viewing another account in `view only mode`.

**Comment by clockworkgr** [comment]
technically they can propose transactions no?

**Comment by gibbsfromncis** [comment]
@clockworkgr exactly. But in most cases when common user clicks on username he is not going to propose transactions from this account. User just wants to take a look account info like balance or something like that.

**Comment by sschiessl-bcp** [comment]
The modal is a very good idea, and also indicating the status according to abit's suggestion above.

**Comment by gibbsfromncis** [comment]
@startailcoon please adjust hours to 1.5h

**Comment by gibbsfromncis** [comment]
@startailcoon 
As task was closed because of accepted PR I adjusted hours by myself. Please let me know if you disagree or need any answers
