### ISSUE TITLE
remove the ability to execute external code in the light client

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-ui#109]
_From @btswolf on March 26, 2017 18:24_

The light client should not connect to any external sources other than default API and Chat.
Embedded websites like the one from BitKapital in the Deposit/Withdraw section represents an unnecessary security issue and should be removed.

_Copied from original issue: bitshares/bitshares-core#252_

**Comment by vikramrajkumar** [comment]
_From @oxarbitrage on March 28, 2017 12:50_

please lets move this issue to the bitshares-ui repo:
https://github.com/bitshares/bitshares-ui/issues

**Comment by wmbutler** [comment]
This merits discussion and is probably high priority. This is yet another reason to remove the trollbox.
