### ISSUE TITLE
[1][ahdigital] Text go out of block on after Account Registration

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1090]
Reproduce:
1) Create Account (Login/Password account)
2) Click "Show me password" 

Browsers where bug was reproduced: `Chrome`, `Opera`, `Safari`, `Firefox`

<img width="541" alt="screenshot 2018-01-31 03 11 28" src="https://user-images.githubusercontent.com/35899973/35601656-836978d0-0634-11e8-9429-1b2708419328.png">

**Comment by ahdigital** [comment]
Can be fixed as part of [#1082](https://github.com/bitshares/bitshares-ui/issues/1082).
