### ISSUE TITLE
[1.5][gibbsfromncis] Account Id is no longer visible anywhere in the web wallet

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1091]
Is it possible to add it somewhere in the UI again?

**Comment by wmbutler** [comment]
What if we make it the first menu item under the new account dropdown?

**Comment by gibbsfromncis** [comment]
@wmbutler I suppose it's not a good idea. We can put it to [Accounts page](https://wallet.bitshares.org/#/accounts) and just add an current user account to list (because there is no user account if he use login/password mode)

**Comment by wmbutler** [comment]
This is an easy fix that accommodates the request. We can enhance later. Thanks.

**Comment by gibbsfromncis** [comment]
@wmbutler What do you mean about `We can enhance later` if you assigned me to this task and this task is on current Sprint?

**Comment by wmbutler** [comment]
I mean to say that your solution is a good step in the right direction but I expect there are users who may want to see the account ID in a more accessible location in the future.

**Comment by gibbsfromncis** [comment]
@wmbutler okay. Should I wait for these users minds here or I can start to work on this issue?

**Comment by wmbutler** [comment]
Work it!

**Comment by gibbsfromncis** [comment]
@wmbutler I need a little bit of your help. 

If I use `wallet mode` account I can see my active account (even I have only one account) on `Accounts` list: 

<img width="1334" alt="screenshot 2018-02-07 16 55 25" src="https://user-images.githubusercontent.com/35899973/35926108-b50fb126-0c27-11e8-8111-9730b5caeb4e.png">

If I use `password mode` account I can see my active account on `Contacts` tab but not on `Accounts` tab:

<img width="1440" alt="screenshot 2018-02-07 16 56 55" src="https://user-images.githubusercontent.com/35899973/35926251-012e38e8-0c28-11e8-91d0-845b84b2ad7f.png">

And `Accounts` tab is empty:

<img width="1440" alt="screenshot 2018-02-07 16 57 03" src="https://user-images.githubusercontent.com/35899973/35926270-0b61b1c8-0c28-11e8-89bb-fb6aa2791e8f.png">

Questions:
1) Is it bug or feature? 
2) Should I see my Account on `Accounts` tab except seeing it on `Contacts` tab? 
2) if it's feature what is the idea of it?
3) If it is a bug what is the right behavior? 
4) Why do we need `Contacts` ? I googled this task: https://github.com/bitshares/bitshares-ui/issues/167 but I didn't find any usages of this feature on Money Transfer (should we create task for this one?)
5) Why do we need `star` some account? 

Some questions are not related to this task but would help me so much on my future work on bitshares.

**Comment by gibbsfromncis** [comment]
@wmbutler I've recognized this behavior like a bug so I fixed that for "login/password" accounts. For now `Login/Password` accounts and `Wallet` accounts able to see their id on `/accounts` page.

Now It looks like this: 
<img width="1440" alt="screenshot 2018-02-07 18 27 24" src="https://user-images.githubusercontent.com/35899973/35931726-c72d70e2-0c35-11e8-9f75-623cbc4a1945.png">

Also I've provided ID for contacts too (maybe someone need this):

<img width="1401" alt="screenshot 2018-02-07 18 37 02" src="https://user-images.githubusercontent.com/35899973/35931752-e6ab868e-0c35-11e8-8630-e84dd27ba857.png">

PR: #1129

**Comment by gibbsfromncis** [comment]
@wmbutler I've spent much more than .5h for this simple task because of investigation the bug described above, finding solutions and fixing it. Can you increase estimate to 1h please to compensate some of my time?

**Comment by wmbutler** [comment]
Gave you a full extra hour on this. Thanks.
