### ISSUE TITLE
[.5] Add ID column to Proposed / Active / Expired WP

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1094]
When WP's are entered accidentally there can be confusion about which WP is the correct one to vote for. Adding the ID will remedy this.

- [ ] Column Title: ID
- [ ] Column contents: 1.14.xx

**Comment by mattbeckman** [comment]
I'll handle this one real quick.

**Comment by mattbeckman** [comment]
<img width="1097" alt="screen shot 2018-01-31 at 8 28 30 pm" src="https://user-images.githubusercontent.com/928380/35661180-57c01f72-06c5-11e8-903f-3cb841d1a670.png">

Is this where you'd like it to be placed?
