### ISSUE TITLE
[1] Provide info which node is active in GUI if automatically selected

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-ui#110]
_From @btswolf on March 26, 2017 19:32_

When Full Node API Server is selected automatically please add information which node is actually active.

_Copied from original issue: bitshares/bitshares-core#253_

**Comment by vikramrajkumar** [comment]
_From @oxarbitrage on March 28, 2017 12:50_

please lets move this issue to the bitshares-ui repo:
https://github.com/bitshares/bitshares-ui/issues

**Comment by nmywn** [comment]
I've set my api access at local host and it is display as in use, which can't be true because I don't run API server:
Provide information that API is "selected" automaticaly if user choice is not available.

**Comment by wmbutler** [comment]
The screen for managing API nodes does need some TLC.

**Comment by wmbutler** [comment]
Related to #49

**Comment by calvinfroedge** [comment]
@wmbutler @vikramrajkumar Can we get some additional clarification on UI required for this issue?

**Comment by wmbutler** [comment]
This ties into #49. I've provided a UX/UI for this.

**Comment by wmbutler** [comment]
I think we are safe to close this and collect the bounty as part of #49.

**Comment by calvinfroedge** [comment]
![issue-110](https://user-images.githubusercontent.com/632938/29434629-6b8d3682-8369-11e7-8c0a-2a14bdc19e26.gif)

This issue is being resolved as part of [issue 49](https://github.com/bitshares/bitshares-ui/issues/49).

**Comment by wmbutler** [comment]
@calvinfroedge I set this to 1 hour bounty.
