### ISSUE TITLE
updated light client freezes completely on mac os 

### ISSUE THREAD

**Issue by r-t-c** [bitshares/bitshares-ui#1100]
This is happening on the web client as well. Here is a licecap with console logs. This was introduced with the latest version. @svk31 Can you please fast track this?

**Comment by wmbutler** [comment]
![wallet](https://user-images.githubusercontent.com/1254810/35748358-6365583e-0813-11e8-8e7c-d317ebe527b1.gif)

**Comment by wmbutler** [comment]
This is pretty easy to replicate just by switching accounts in the local wallet.

**Comment by svk31** [comment]
I think the problem is just the extremely poor performance of the dallas server and/or your internet connection. You got disconnected just before switching accounts, which is what caused all the red error messages when it attempted to fetch new account data.

**Comment by wmbutler** [comment]
This probably means that we need a way to exclude public nodes. This has been a problem for me and I assume others.

**Comment by wmbutler** [comment]
Revisit that after 180301 release. This may be resolved.
