### ISSUE TITLE
[1.5][ahdigital] Broken URLs and missing menu on help page

### ISSUE THREAD

**Issue by ahdigital** [bitshares/bitshares-ui#1107]
Some URLs are broken on the help page. E.g.

-BitAssets
-User-Issued Assets
-The DEX

Let me know where these should point and I will update.

Also, the menu of topics is missing on mobile.

**Comment by wmbutler** [comment]
Might want to break the mobile piece of this into another issue.

**Comment by ahdigital** [comment]
I'll check when I open the code and post back if it's not a quick fix.

**Comment by wmbutler** [comment]
What is your Telegram handle?

**Comment by ahdigital** [comment]
**Update:**

- Fixed broken URLs
- Made navigation appear on mobile
- Made page responsive
- Made navigation of links mobile friendly

![responsive-help](https://user-images.githubusercontent.com/3088454/35807280-2f5b113c-0a7a-11e8-9e8a-2e3ae840f480.gif)

**Comment by wmbutler** [comment]
That's gorgeous. Let me know if you need additional hours.

**Comment by ahdigital** [comment]
Bump it by 0.5 and that'll be fine. I'll submit PR later.
