### ISSUE TITLE
Use global ask / bid color for change-up and change-down?

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#1108]
Just a cosmetic color issue: currently `.change-up` and `.change-down` are using their own colors, but they are not so readable in order book:

![snipaste_2018-02-03_14-35-28](https://user-images.githubusercontent.com/861659/35763445-cfa33a7a-08ef-11e8-96fe-761b4a600d6c.png)
![snipaste_2018-02-03_14-35-20](https://user-images.githubusercontent.com/861659/35763446-cff06d90-08ef-11e8-8f6a-7ab67d9b25c9.png)

Should they use same color as the rest of the order book?

**Comment by startailcoon** [comment]
This applies mainly to the "Dark" theme, it should use theme changed setting so it applies to each theme differently. This is a CSS style issue.

I'm adding this to #969
