### ISSUE TITLE
180201 version, clicking "Hidden" hangs the client & memory leaks then

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#1109]
win7, latest client. on clicking "Hidden" in portfolio, client stops working, and leaks memory / drains all my CPU kernels.

**Comment by wmbutler** [comment]
I have the same issue when switching accounts. Also documented here: #1100 This is a serious bug and I'm certain is causing issues for many.

**Comment by wmbutler** [comment]
@btsfav are you referring to the latest lite wallet or the web version?

**Comment by btsfav** [comment]
@wmbutler sorry, I only use the light client

**Comment by wmbutler** [comment]
I've asked @svk31 to carefully examine things. I think this is affecting some (like us) more than others. But I cannot seem to pinpoint the cause.

**Comment by wmbutler** [comment]
Likely fixed in 180301 release.
