### ISSUE TITLE
[.5][ahdigital][2][pnomolos] MAX DEBT for current Collateral Ratio

### ISSUE THREAD

**Issue by fractalnode** [bitshares/bitshares-ui#1110]
Maximize Collateral is very cool feature, 
so that would be nice to have also MAX DEBT Button for actual CR setup
Calculated from AVAILABLE BTS and Collateral Ratio

**Comment by landry314** [comment]
Ah, so, it calculates the maximum you can borrow given the current collateral ratio and available BTS... nice.

**Comment by pnomolos** [comment]
@fractalnode I've added a PR for this if you want to give it a whirl.

**Comment by svk31** [comment]
Maybe I'm missing something here, but shouldn't this apply max collateral to a given collateral ratio? That gives you the max amount you can borrow at a given ratio. Your PR instead applies the remaining balance to a given collateral ratio, I think you should take into account the current position like what's being done in _maximizeCollateral.

Also, if the ratio is set to 0, you get a debt value of `Infinity`. It should either disable the button or better yet display a warning that the ratio needs to be set first.

**Comment by pnomolos** [comment]
@svk31 My apologies, this should be working now.  I've also disabled the button and added a tooltip if it's disabled (with a translation key).  Unfortunately I wasn't able to get the tooltip actually able to show up - I'm not sure I misunderstood how ReactTooltip is meant to be used or if using it via a modal like this has issues.  I feel like that approach (if it's possible to get working) is less convoluted then having a clickable button that presents a warning when clicked.

**Comment by fractalnode** [comment]
![max1](https://user-images.githubusercontent.com/20418259/36933330-69ce5f38-1ed7-11e8-9c5d-db866a800205.png)
![max2](https://user-images.githubusercontent.com/20418259/36933332-6dfc5b64-1ed7-11e8-861c-27c783d78788.png)

**Comment by fractalnode** [comment]
maybe you could add at the same time
"return the debt from the balance"
simple subtraction: debt minus balance

**Comment by wmbutler** [comment]
added 1 hour

**Comment by pnomolos** [comment]
@wmbutler Even with shortening the text as much as possible this can no longer fit on one line.  How would you like the UI organized?

![image](https://user-images.githubusercontent.com/36223/37258969-2aca5cee-253d-11e8-9b43-9892a54346c1.png)

**Comment by wmbutler** [comment]
@ahdigital care to take a shot at 30 minute UX on this one?

**Comment by pnomolos** [comment]
I have an idea but don’t know how well it’ll translate to other languages.
Something like

Max: [Paid debt] [Debt] [Collateral]

Sorry for email formatting, but basically remove the “Max” from each button
and add as a label

**Comment by wmbutler** [comment]
Hoping @ahdigital can work this into his styleguide.

**Comment by ahdigital** [comment]
No problem. Can I have the URL to this page please?

**Comment by pnomolos** [comment]
@ahdigital It's in the borrow modal that's available on any bitAsset page on the exchange.  I was using bitCNY (http://localhost:8080/market/CNY_BTS).  You'll need to run against the live market as I don't believe there are any bitAssets on the testnet.

**Comment by pnomolos** [comment]
I don't think having a "Use max" on the ratio slider makes sense, but the other two look good (although maybe a little small).  We'd still need a button to pay max debt, though.  That one's only available on my PR branch.

@wmbutler Thoughts?

**Comment by wmbutler** [comment]
@ahdigital the slider is a weird beast because it's current max is at 6:1, so clicking on use max would be strange because it would put the slider in the same position as the 6:1. Although, we currently already have this problem.

- Max Debt makes sense - if I understand correctly, this would set your collateral to a ratio of 1.75 right?
- Max Collateral makes sense - this would set to Max Collateral - 10BTS (just to have a few in reserve for misc trading fees)

What does "Pay Max Debt do"?

**Comment by pnomolos** [comment]
Pay max debt does what @fractalnode requested:

> maybe you could add at the same time
> "return the debt from the balance"
> simple subtraction: debt minus balance
> so that you can partially pay off the debt

Basically this makes math a little easier in the case where you have borrowed some bitAsset but have a portion of it unavailable to pay back your debt.

> Max Debt makes sense - if I understand correctly, this would set your collateral to a ratio of 1.75 right?

I guess we could add in the collateral ratio being set to 1.75 if it's not set.  Right now it calculates the max debt you can carry at the collateral ratio you selected (because it's not easy to do this otherwise, as changing the collateral amount moves the ratio slider to keep debt fixed).

> Max Collateral makes sense - this would set to Max Collateral - 10BTS (just to have a few in reserve for misc trading fees)

Yes, this would function exactly as the button currently does.

**Comment by wmbutler** [comment]
> Pay max debt does what @fractalnode requested:

But this is already handled by clicking on the bitASSET balance right? Are we actually solving a problem here? If we have to do this, maybe just place it next to `Use Max`, like `Payback Max | Use Max`

**Comment by pnomolos** [comment]
> But this is already handled by clicking on the bitASSET balance right? Are we actually solving a problem here?

Unless this is something that's in production and **not** on staging, then this isn't currently available.  "Payback Max" does sound perfect, though, and would fit well :)

All it does subtract your available balance from your currently borrowed balance, but it's handy if you're dealing with non-integer amounts.

**Comment by wmbutler** [comment]
I see this was closed, but we didn't really finish this according to the UX. @pnomolos would you mind refactoring as discussed above? Here is what it looks like currently. While it's not terrible, I really like what @ahdigital has done.

![screen shot 2018-03-13 at 10 38 21 pm](https://user-images.githubusercontent.com/1254810/37382206-7f8bd1ee-270f-11e8-8c72-81bb3779db31.png)

**Comment by pnomolos** [comment]
@wmbutler Will do.

@ahdigital Is there an existing component that does what you put together in your suggestion I can use for styles, or am I putting them together from scratch?

**Comment by ahdigital** [comment]
This would be new functionality. Also, in the mock up I made the range slider fit in better with the theme.

**Comment by wmbutler** [comment]
@pnomolos if you want to take this on for this issue, I'll bump the hours up, your call, but you'd need to work it asap before this release. Let me know. I scored this at 2 hours taking into account the additional work (not just adding a button) :)

**Comment by pnomolos** [comment]
@wmbutler Will do, should be able to have it done tonight/tomorrow (PST).

**Comment by pnomolos** [comment]
@wmbutler Done over lunch but didn't get a chance until now to grab a screenshot:

![image](https://user-images.githubusercontent.com/36223/37436402-04085eb6-27a5-11e8-8f18-0eb1702a2b81.png)

I guess it should be lowercase, or does leaving the all-caps fit better?

**Comment by ahdigital** [comment]
Sentence case would be better since that's the pattern that I'll be adopting elsewhere when it gets used.

- [ ] Sentence case for 'Use max' and 'Pay max debt'
- [ ] Make the slider track the same color as the inputs
- [ ] Give the 'reset' button hollow styling (.button .hollow .primary)

**Comment by pnomolos** [comment]
@ahdigital @wmbutler 

![image](https://user-images.githubusercontent.com/36223/37473623-c7d6f61e-282b-11e8-83e9-6752ce6fefc9.png)

I also added the 3px border-radius to the slider and turned "Use Max" for the debt slider into a disabled link when the ratio slider is 0 (as it's not clickable then)

**Comment by ahdigital** [comment]
Looks much better but the 'Use max' links aren't sentence case. Looks like it has small-caps applied?

**Comment by pnomolos** [comment]
@abitmore I've applied the change and opened a new PR :)
