### ISSUE TITLE
Bid-Offer spread display

### ISSUE THREAD

**Issue by nbcks** [bitshares/bitshares-ui#1111]
My feature proposal is that we show the bid-offer spread somewhere in the trading view, perhaps at the top.

**Comment by startailcoon** [comment]
The last version, 180201, shows the spread in the Vertical order book. 
However, since not all are using it we should find a common place to view it.

![bitshares-spread](https://user-images.githubusercontent.com/12114550/35776573-51778aec-099f-11e8-9415-da0c78b1ad3a.gif)

**Comment by nbcks** [comment]
Where can I find the vertical order book?

**Comment by startailcoon** [comment]
You can find it by clicking the up/down arrow in the vertical orderbook.

![bitshares-verticalorderbook](https://user-images.githubusercontent.com/12114550/35778415-3d5b8ff8-09be-11e8-89f1-88d40e34cbf1.gif)

**Comment by nbcks** [comment]
Ah yep, done it thanks. I was thinking we should also display it where the latest price, 24 hour volume and settlement price are display (the top row).

**Comment by nbcks** [comment]
Ah yep, done it thanks. I was thinking we should also display it where the latest price, 24 hour volume and settlement price are display (the top row).

**Comment by wmbutler** [comment]
We are running out of room at the top and that's not a very standard piece of infomation to display. It's contextually relevant in the order book.

**Comment by nbcks** [comment]
Okay I'll close the issue then. I guess it's because I wasn't aware of the vertical order book existing.
