### ISSUE TITLE
When user on Deposit/Withdrawal page menu highlight 3 items the same time

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1116]
Simple and fast task:

<img width="1329" alt="deposit-withdrawal-menu-highlight" src="https://user-images.githubusercontent.com/35899973/35822262-f3b8ae28-0aab-11e8-9f51-d172583010ac.png">

Let's do this:
- [ ] Make separate Deposit and Withdrawal menu's items as one `Deposit/Withdrawal`
- [ ] Do not highlight `Deposit(Beta)` when user on deposit-withdrawal page.

@wmbutler if you OK put me on this task

**Comment by wmbutler** [comment]
This area is getting replaced with dedicated withdraw/deposit modals.
