### ISSUE TITLE
[19] Allow a user to specify an arbitrary asset for transaction fee

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1117]
Not like when placing an order you can specify an asset for paying fee, when cancelling an order, can the user specify the fee paying asset?

https://bitsharestalk.org/index.php/topic,25930.0.html

> Hello,
> 
> I made an order yesterday and now I want to cancel it. Usually, it works great, but now, I get:
> Failed to broadcast the transaction:
> Assert Exception: core_fee_paid <= fee_asset_dyn_data->fee_pool: Fee pool balance of '0.00009 BTS' is less than the 0.00010 BTS required to convert 0.0001 ZALUPA
> 
> Why is that? is it a rounding error that will resove itself soon or is it because I have no more funds in the account beside the funds in the transaction?
> 
> Any help would be appreciated.
> 
> Thank you,
> Report to moderator     Logged
> President - NeoReel.com
> CTO- MoClip.com
> CEO- Relinked.com
>

**Comment by wmbutler** [comment]
Allow a user to specify an arbitrary asset when canceling an order.

**Comment by abitmore** [comment]
Possible UX:
* add an option in settings, e.g. "default asset for paying fees" or "fee asset", by default set to "BTS".
* when it's about to pay a fee, check if the user has enough fee asset,
  * if yes, go to the transaction signing page
  * if not, show a dialogue to let user select a fee asset, with these items:
    * list of assets
    * balances
    * CER's
    * required fee if in BTS
    * fee in selected asset
    * whether to show this dialogue in the future again
    * whether to save selected asset as default for paying fee.

* On some pages that explicitly showing a fee field, show the selected fee asset in the drop-down by default. Maybe some pages will save user previously chose one, we can stick to it, but I think it's better to have a global option and use same page-flow everywhere.

**Comment by wmbutler** [comment]
Added time for UX as well

**Comment by landry314** [comment]
Yeah, I am having serious trouble with this. If i have all my BTS locked up in an order I can't cancel the order.

**Comment by abitmore** [comment]
@wmbutler this is a serious feature. Please increase bounty amount to make this more interesting, I guess even 5/5 is not enough.

**Comment by abitmore** [comment]
Perhaps @ahdigital doesn't even know this needs UX?

**Comment by ahdigital** [comment]
I can take this.

**Comment by abitmore** [comment]
Who will work on this?

**Comment by startailcoon** [comment]
It's still up for claims. We need a UX for a coder to work from.

I've increased hours

**Comment by abitmore** [comment]
Bump.

**Comment by ahdigital** [comment]
Per discussion above, add option into the settings which will default to using BTS asset to pay fees. E.g.

![image](https://user-images.githubusercontent.com/3088454/57696268-45115f00-7648-11e9-9888-08fa4f3ed372.png)


If the user doesn't have enough funds to be able to pay a fee in the default fee paying asset, open a modal for them to select another asset to continue with.

The modal should ideally only list assets for which the user holds a balance, and that is enough to pay the fee. Assets to be ordered by balance largest to smallest, and first asset selected by default E.g.

![image](https://user-images.githubusercontent.com/3088454/57696448-ae916d80-7648-11e9-94b7-bee96ac57894.png)

**Comment by sschiessl-bcp** [comment]
> Per discussion above, add option into the settings which will default to using BTS asset to pay fees. E.g.
> 
> ![image](https://user-images.githubusercontent.com/3088454/57696268-45115f00-7648-11e9-9888-08fa4f3ed372.png)
> 
> If the user doesn't have enough funds to be able to pay a fee in the default fee paying asset, open a modal for them to select another asset to continue with.
> 
> The modal should ideally only list assets for which the user holds a balance, and that is enough to pay the fee. Assets to be ordered by balance largest to smallest, and first asset selected by default E.g.
> 
> ![image](https://user-images.githubusercontent.com/3088454/57696448-ae916d80-7648-11e9-94b7-bee96ac57894.png)

Are those Mockups, or are you secretly coding somewhere else? Glad to see UX from you, I will happily pick that up now :)

**Comment by ahdigital** [comment]
> Are those Mockups, or are you secretly coding somewhere else?

Mock ups for this task.

**Comment by sschiessl-bcp** [comment]
UX bounty exported to other issue

**Comment by sschiessl-bcp** [comment]
Bounty request in https://github.com/bitshares/bitshares-ui/pull/2924#issue-296302366

**Comment by abitmore** [comment]
@sschiessl-bcp there is no screenshot about canceling an limit order in the PR. Is this issue really fixed? Reopening so far.

**Comment by sschiessl-bcp** [comment]
Ah .. Apologies, we might have detached too much from the specific problem at hand and generalized it without revisiting what the actual cause was.

Will check.

**Comment by sschiessl-bcp** [comment]
![image](https://user-images.githubusercontent.com/33128181/61132019-cf483900-a4ba-11e9-90db-fa82cf78193a.png)

A hint was added that the default fee asset can be changed. We decided to not add the more intrusive feeselector component here. 

Do you think that is sufficient, or should we have an option to allow selection of something else directly in the cancel modal?

**Comment by startailcoon** [comment]
I see there's more work done after the comment from abit, do we have a change in the behavior afterwards?

My own opinion is that it would be nice to have a "change fee asset directly" when yo do a transaction, that doesn't stick to be the default, but just for that one op. But that's for a followup issue I think.

**Comment by sschiessl-bcp** [comment]
That work was not done by us, but by someone who apparently is linking this issue.

**Comment by sschiessl-bcp** [comment]
> ![image](https://user-images.githubusercontent.com/33128181/61132019-cf483900-a4ba-11e9-90db-fa82cf78193a.png)
> 
> A hint was added that the default fee asset can be changed. We decided to not add the more intrusive feeselector component here.
> 
> Do you think that is sufficient, or should we have an option to allow selection of something else directly in the cancel modal?

I would consider this issue complete with the linked comment, and open a new one if a direct selection should be implemented. @startailcoon if you agree please close and open a new one

**Comment by abitmore** [comment]
> I would consider this issue complete with the linked comment, and open a new one if a direct selection should be implemented.

I think it's fine. For best UX, please also check https://github.com/bitshares/bitshares-ui/issues/1498

**Comment by startailcoon** [comment]
> I would consider this issue complete with the linked comment, and open a new one if a direct selection should be implemented. @startailcoon if you agree please close and open a new one.

Agree. We'll continue on a new issue for further changes.
