### ISSUE TITLE
[6][startailcoon] Show more info on asset info page

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1119]
<del>It's now calculated as `settlement_price / MCR`, but should be `settlement_price * MSSR / MCR`.</del> 
Update: see [this comment](https://github.com/bitshares/bitshares-ui/issues/1119#issuecomment-366470594) below.
![image](https://user-images.githubusercontent.com/9946777/35852460-3da7f992-0b2b-11e8-8346-6816bcd0b660.png)

**Comment by startailcoon** [comment]
I can take this task. I think it's worth adding some more parameters at the same time, like offset percentage, and possibly some more.

**Comment by abitmore** [comment]
Actually it's a bit complicated.
The global settlement price is actually correct, but a global settlement (black swan) will trigger at 10% above that price.
So what should the UX be?

**Comment by abitmore** [comment]
Oh wait, does that "settlement price" include offset? My calculation above didn't count in the offset. I mean, median feed price is a thing, price for force settlement is another.

**Comment by startailcoon** [comment]
The field Global Settlement Price isn't provided by something from the chain in the GUI, but a manual calculation of debt and collateral. I will require some help to provide if this is correct, or requires some new way of calculation.

Code https://github.com/bitshares/bitshares-ui/blob/33a08322598e0fc8d705faa0fd6bbfbbbbbfbca3/app/components/Blockchain/Asset.jsx#L564-L611

**Comment by startailcoon** [comment]
Releasing this for anyone interested in following up on this for now.

**Comment by startailcoon** [comment]
Ping @abitmore. Can you enlighten us about my question from before?

**Comment by abitmore** [comment]
IMHO it needs UX. We have all the data, need to decide how to non-misleadingly show them.

**Comment by abitmore** [comment]
All prices described below are in terms of `debt/collateral`, aka how much debt per collateral, which may affect descriptive words like "below", "above", "lower than", "higher than", "min", "max" and etc. If the price in UI is flipped, corresponding words need to be flipped as well.

We have these data, need to show some or all of them:
* price feeds: a list, published by witnesses or other price feed producers
  * feed producer
  * price
  * CER
  * MCR
  * MSSR
* medians (already calculated by server, so get from bitasset data directly):
  * median price feed (showing as `settlement price` in OP): median of price feeds
  * median MCR
  * median MSSR
* about force settlement:
  * offset
  * delay
  * max settle-able volume per maintenance interval (percent)
  * force settle price: `median price feed * ( 100% + offset )`, the price that a force settlement order will be filled at
  * max settle-able volume before next maintenance interval (absolute value): `total supply * percent`
  * settled volume: amount settled in this maintenance interval
  * remaining settle-able volume: `max - settled`
* about margin calls:
  * MSSP: `median price feed / MSSR`, the lowest price that a margin call can be executed at
* short positions (list):
  * user
  * debt amount
  * collateral amount
  * call price: if feed price is below or equal to this value, the order will be able to be margin called
  * collateral ratio: `median price feed * collateral / debt`
* about black swan event (if an asset is not in black swan state): calculate from the short position with least collateral ratio (affected by this bug: https://github.com/bitshares/bitshares-core/issues/649, a black swan event can be deferred)
  * black swan price: `MSSR * debt / collateral`, if feed price is below this value, a black swan event may occur
* if an asset is in black swan state (e.g. GOLD):
  * global settlement price: a new settlement order will execute at this price immediately (won't delay)
  * settlement fund: how much collateral is available (should be equal to `current supply / global settlement price`)
  * a list of collateral bids
    * user
    * additional collateral amount: how much collateral the user wants to add
    * debt amount: how much debt the user wants to cover/claim

**Comment by wmbutler** [comment]
This needs UX, @ahdigital ?

**Comment by startailcoon** [comment]
Do we have a UI proposal?

**Comment by startailcoon** [comment]
@wmbutler you've assigned me and ahdigital. Is your intention that we work on this?

I need a UI proposal first, and there have been a few questions previously that I need sorted before this is worked on. It will require some information so we don't display something wrong.

**Comment by wmbutler** [comment]
Agreed. I was hoping @ahdigital would pick it up when he has some time and you would work off his ideation.

**Comment by startailcoon** [comment]
Cool, all good

**Comment by ahdigital** [comment]
I don't think I understand this well enough to be able to make a useful contribution I'm afraid.

**Comment by startailcoon** [comment]
Well, I'm not sure we need a specific UI work here? As long as we put these data in good tables to look good and make sense to the user I think we would be fine.

I can tackle this myself, just need to dig in to the data we can display as it's not always very documented.

**Comment by abitmore** [comment]
@startailcoon any question about data please feel free to ask.

**Comment by abitmore** [comment]
Forgot some data fields:
* feed lifetime (`feed_lifetime_sec`): how long a price feed would be valid
* minimum feeds (`minimum_feeds`): how many price feeds are required to make median feed valid
* backing asset (`short_backing_asset`): what backs this asset, or say, put what as collateral
```
        "bitasset_opts": {
          "feed_lifetime_sec": 86400,
          "minimum_feeds": 1,
          "force_settlement_delay_sec": 86400,
          "force_settlement_offset_percent": 0,
          "maximum_force_settlement_volume": 2000,
          "short_backing_asset": "1.3.839",
          "extensions": []
        },
```

**Comment by wmbutler** [comment]
@startailcoon I think we need to get this to a closing point.

**Comment by startailcoon** [comment]
> 
> 
> @startailcoon I think we need to get this to a closing point.

I tend to agree :)

**Comment by startailcoon** [comment]
I've posted an issue on bitshraes-core to include asset collateral volume and settled volume on chain.

https://github.com/bitshares/bitshares-core/issues/1448

**Comment by startailcoon** [comment]
Adding a few new fields

### Price Feed
![bild](https://user-images.githubusercontent.com/12114550/48984207-2ef2ff00-f0f9-11e8-8285-c61313a55472.png)

### Settlement (normal)
![bild](https://user-images.githubusercontent.com/12114550/48984209-3ca88480-f0f9-11e8-8f4f-59b63d6b366c.png)

### Settlement (in Global Settlement)
![bild](https://user-images.githubusercontent.com/12114550/48984213-577af900-f0f9-11e8-92f9-ffd95811117f.png)

I'm not sure if the Settlement Volume will change during a global settlement.

**Comment by abitmore** [comment]
Due to bsip42, the name "external price" is not so good. https://github.com/bitshares/bitshares-ui/issues/1865.

Volumes are ignored after globally settled.

**Comment by startailcoon** [comment]
@abitmore noted. Removing volume limit data on global settled asset. 

> Due to bsip42, the name "external price" is not so good

How is "Average market price"?

**Comment by sschiessl-bcp** [comment]
> How is "Average market price"?

How about waht it actually is: Feed price (median of witness feeds)

**Comment by sschiessl-bcp** [comment]
I did not read the discussion in here in detail beforehand and rearranged abit, please check if appropriate
![image](https://user-images.githubusercontent.com/33128181/49015460-71f9b480-f183-11e8-8fd5-9cd2e3a6d189.png)

![image](https://user-images.githubusercontent.com/33128181/49015480-7d4ce000-f183-11e8-90e5-6ec31c665035.png)

**Comment by startailcoon** [comment]
Looks good to me
