### ISSUE TITLE
Market pair display on exchange header

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#1120]
Currently it shows like this:

![0030-02-06 19 47 37](https://user-images.githubusercontent.com/861659/35855450-97dfd01a-0b76-11e8-9349-1bbca3192668.png)

While it is actually BTS per bitUSD, it's shown as "bitUSD / BTS". This could be very confusing. The correct notation was between bid and ask orders.

**Comment by wmbutler** [comment]
No different than GDAX, a mainstream exchange with tens of thousands of customers.

![screen shot 2018-02-06 at 9 15 00 am](https://user-images.githubusercontent.com/1254810/35866994-3f0af8e6-0b1e-11e8-87c9-6d420100ac35.png)
