### ISSUE TITLE
[1][AustinAmoruso] Order book shifts

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1133]
On the newly crafted vertical order book, the Spread/Latest bar shifts if it is scrolled to a non-centered position and an order is added or removed from the book. Let's put in necessary logic to eliminate this.

![shift](https://user-images.githubusercontent.com/1254810/35979549-3b218ea2-0cae-11e8-991a-eb15a3ff78ce.gif)

**Comment by wmbutler** [comment]
It is on the exchange page. But you must activate it by clicking the up/down arrow icon in the exchange.

![orderbook](https://user-images.githubusercontent.com/1254810/36173323-47507606-10ce-11e8-8268-335e9c7c8360.gif)

**Comment by ahdigital** [comment]
Will you make the 180215 milestone @AustinAmoruso?

**Comment by AustinAmoruso** [comment]
Can we push to next spring haven't had time to fully look over

**Comment by wmbutler** [comment]
I've moved it to 180301

**Comment by AustinAmoruso** [comment]
I have fixed this in the pr that is open

**Comment by wmbutler** [comment]
Can you send me your BTS account?

**Comment by wmbutler** [comment]
Be sure to reference in your commits as well like:

```
commit -am "fix #1133"
```
