### ISSUE TITLE
[2][gibbsfromncis] Notification for proposed transactions

### ISSUE THREAD

**Issue by Aluman** [bitshares/bitshares-ui#1136]
I have multi-sig account "Account1":
     Active Permissions:
          THRESHOLD    100
           Account2            50
           Account3            50

If I create proposed transaction from Account1 to Account4. Notification appears only for Account1:
![screenshot at 2018-02-08 22-54-25](https://user-images.githubusercontent.com/3095510/35994977-12b318bc-0d23-11e8-91f7-6be21d49cab1.png)
  
 Account2 and Account3 don't have any notifications.

**Comment by gibbsfromncis** [comment]
I've tested this issue and actually it exists. If no one take it I can work on it in the next Sprint.

**Comment by svk31** [comment]
It's a limitation of the API, not much we can do about it on our end.

**Comment by gibbsfromncis** [comment]
@svk31 mm..so this feature is not supported? Because only one account can approve transaction for now. Another accounts doesn't receive any proposal about transaction approving. Can we ask backend guys to do something with that?

**Comment by svk31** [comment]
We probably can yea.

Multisig accounts will be "discovered" as partially belonging to you when using wallet mode. Say account1 has permissions of account2 and account3 at 50% each, a wallet containing account2 will identify account1 as partially belong to account2 and include it in the "My Accounts" list

**Comment by gibbsfromncis** [comment]
@svk31 Unfortunately I don't understand how can I fix it ... should we close this one or .. what should we do?

**Comment by svk31** [comment]
It needs to be fixed in the backend so closing this one.

**Comment by gibbsfromncis** [comment]
@wmbutler I've received reward 250$ for this task. Should I transfer it back to bitshares-ui?

**Comment by wmbutler** [comment]
@gibbsfromncis please do. Thanks for your honesty.

**Comment by wmbutler** [comment]
This was paid to @gibbsfromncis for 2 hours and he will send a refund.

**Comment by gibbsfromncis** [comment]
@wmbutler It was sent back to bitshares-ui
