### ISSUE TITLE
[6][ahdigital] Page walkthrough guides

### ISSUE THREAD

**Issue by ahdigital** [bitshares/bitshares-ui#1139]
# Proposed feature
To assist new users of the DEX/trading in general, I am proposing to implement page walkthrough guides. These guides will overlay the existing UI and display short captions to explain features, buttons or concepts.

A common complaint from users is that the DEX is complicated, so this proposed feature aims to address the issue and give users confidence in their actions. It should also offer insight into the 'what to expect next' feeling the user gets before clicking a button.

The guides will be accessible via a help button located in the lower corner of the UI. On desktop, it will be next to the connectivity information and on mobile floating just above the bottom of the viewport.

The guides will be broken down into tips that overlay target elements and the user can navigate backwards and forwards through each. Upon navigation, the tips will slide animate between one another.

### User flow

**Help button**

![1](https://user-images.githubusercontent.com/3088454/36020231-e3bc62d2-0d79-11e8-8ee2-ab2b167f1922.png)

**First tip displayed**

![2](https://user-images.githubusercontent.com/3088454/36020234-e7e21398-0d79-11e8-940a-f28c8875cebc.png)

**Second tip displayed**

![3](https://user-images.githubusercontent.com/3088454/36020242-ebd57e4a-0d79-11e8-8236-15497d90930d.png)

### Example on exchange

![exchange-example](https://user-images.githubusercontent.com/3088454/36020247-f048f8ee-0d79-11e8-8f4d-39e9148e031a.png)

### Mobile

![mobile-example](https://user-images.githubusercontent.com/3088454/36020258-f816e9fa-0d79-11e8-8b65-88068fdd0181.png)

## Task breakdown

- Design
    + Desktop and mobile *(1 hour)*
- Development *(3 hours)*
    + Implementation of functionality
    + Add support for themes
    + Add support for locales
- Adding guides for: *(0.5 hours each)*
    + Landing page
    + Exchange
- Testing *(1 hour)*

**Total: 6 hours**

Please allocate to me if you agree the hours.

**Comment by wmbutler** [comment]
#577 duplicate was closed

**Comment by ahdigital** [comment]
@wmbutler For the landing page, I have added the following hints:

1. **Language flag:** "Choose from 9 different languages to use in the DEX."
2. **Create account button:** "Access the cloud wallet using an account name and password."
3. **Restore account link:** "Restore a wallet using your backup file."
4. **Advanced account link:** "Create a local wallet and download any private keys belonging to it."

Can you please check the descriptions are accurate and advise any amendments. Bear in mind these should be short succinct helpers.

**Comment by ahdigital** [comment]
I've completed this task to the above requirements.

As well as adding support for locales, I used Google Translate to add the translations for the other 8 languages. I recommend that these are checked by native speakers and if any amendments are required please raise separate issues.

The help button that launches the tips is responsive between desktop and mobile. If there are no tips on the page I have added a fall back link to an [externally hosted guide](http://docs.bitshares.org/bitshares/user/index.html) that opens in a new tab.

I've added a override stylesheet for the dark, light and midnight themes. Preview:

![theme-preview](https://user-images.githubusercontent.com/3088454/36158094-5bb94726-10d3-11e8-84fc-9bf0bcebdcf6.jpg)

**Landing page preview**

![introjs-preview](https://user-images.githubusercontent.com/3088454/36158122-6daf60d2-10d3-11e8-9b3a-2d1d1a782406.gif)

**Exchange preview**

![exchange-preview](https://user-images.githubusercontent.com/3088454/36158133-75f09b58-10d3-11e8-9277-5321f9852b1e.gif)
