### ISSUE TITLE
[3][swoopyy] Allow users to hide API nodes

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1144]
There are cases where the UI attempts to connect to a low latency node but that node may have connectivity issues. Currently, the UI will cascade through each node attempting to connect to each.

It would be beneficial for the user to move nodes into a hidden state. This should follow the same pattern as active/hidden assets. Steps:

- [ ] `Available Nodes | Hidden Nodes` to toggle between the lists
- [ ] Add an additional hover state button `Hide` in the Available Nodes
- [ ] Add an additional hover state button `Show` in the Hidden Nodes
- [ ] Scanning of nodes during discovery should be limited to only `Available Nodes`

<img width="848" alt="screen shot 2018-02-10 at 10 03 07 am" src="https://user-images.githubusercontent.com/1254810/36064037-b8791968-0e4a-11e8-8f5a-4a460967749b.png">

**Comment by wmbutler** [comment]
I will leave it open until it is claimed. Maybe someone will claim it for this Sprint.

**Comment by swoopyy** [comment]
can I take this please?

**Comment by startailcoon** [comment]
It's yours swoopyy.

**Comment by wmbutler** [comment]
@swoopyy please look at the latest Dashboard Styles to replicate the Active | Hidden filters:

https://github.com/bitshares/bitshares-ui/issues/889

**Comment by swoopyy** [comment]
@wmbutler already added grid tabs but I can redesign this the way you suggested for sure
![bts](https://user-images.githubusercontent.com/11968967/36076941-60d2efec-0f74-11e8-92f1-1eb15510445c.jpg)

**Comment by wmbutler** [comment]
@swoopyy Don't sweat it. We can sweep though later on the look.

**Comment by wmbutler** [comment]
A few bugs:

- [ ] After hiding a node, the cursor hover will not activate the button controls on the current node. User must scroll of and back onto next or previous node.
- [ ] Active node should not display in Available node list

<img width="857" alt="screen shot 2018-02-12 at 7 36 35 pm" src="https://user-images.githubusercontent.com/1254810/36129295-1b468ea8-102c-11e8-8799-691e10599aaf.png">

**Comment by wmbutler** [comment]
@swoopyy pls send your BTS address here.

**Comment by swoopyy** [comment]
@wmbutler swoopyyy7
