### ISSUE TITLE
[1] Cannot see full list of my accounts after Wallet Restore

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1146]
1) Restore my Wallet from File (btw: my wallet account has around 5 accounts)
2) I see only my main account on Accounts List:
<img width="215" alt="screenshot 2018-02-11 12 05 49" src="https://user-images.githubusercontent.com/35899973/36072690-3674e58e-0f24-11e8-96ab-1a9146a1d5c8.png">
3) Create new sub-account:
<img width="353" alt="screenshot 2018-02-11 12 06 30" src="https://user-images.githubusercontent.com/35899973/36072691-3c84a1c6-0f24-11e8-8d8a-aaff03d27703.png">
4) After this I see new account and other accounts on the list:
<img width="274" alt="screenshot 2018-02-11 12 06 35" src="https://user-images.githubusercontent.com/35899973/36072696-4dbd6978-0f24-11e8-9785-2dd72fa47298.png">

@wmbutler is it bug or not? I've checked `Accounts` on Settings and there is only my own account and that's it. I cant see full list of my accounts anywhere till I create one more. 

It was tested on Testnet only because I don't have Membership on my own account on Production. Do you have an ability to test in? Maybe it happens only for Testnet? 

This bug make me nervous because when I want to test something like this: https://github.com/bitshares/bitshares-ui/issues/1136 I should create one more account because I can't see the list of previously created accounts. (I test all issues on Incognito to prevent any mistakes from stored on my browser data).

**Comment by wmbutler** [comment]
This sounds like an unresolved promise of some sort. You might quit the browser after a restore. Then relaunch and see if your accounts are there. I will book this as a bug but you may have to figure it out if you cannot reproduce.

**Comment by gibbsfromncis** [comment]
@wmbutler Unfortunately steps you've provided don't work. I still cannot see my accounts. Only one way I can see them is to create one more account ...

**Comment by wmbutler** [comment]
Understood, but this doesn't happen for me, so if we can't reproduce, we can't fix.

**Comment by gibbsfromncis** [comment]
@wmbutler I can advice you to try register new account, create few accounts for it and then login again in Incognito. 

Maybe I do something wrong?
1) Register wallet account
2) Save backup
3) Add membership
4) Create new account
5) Replace previous backup
6) Start browser in Incognito 
7) Restore from latest backup 
8) Now you see only 1 account ..

**Comment by wmbutler** [comment]
Here is a licecap of a wallet restore in incognito mode:

![accounts](https://user-images.githubusercontent.com/1254810/36077190-0934f542-0f2d-11e8-85d1-a6661cbfa34f.gif)

**Comment by gibbsfromncis** [comment]
@wmbutler so strange... Will spend some time for investigation....

**Comment by svk31** [comment]
Might be the case that you need to unlock after restoring. There's an account lookup from brainkey-generated pubkeys that happens when you unlock.

**Comment by gibbsfromncis** [comment]
@svk31 you're right! 

@wmbutler can we add some message on Accounts dropdown like `Unlock wallet to see all accounts` ?

**Comment by gibbsfromncis** [comment]
@wmbutler should I do something with that?

**Comment by landry314** [comment]
might be somehow related to #261. Restoring a wallet causes strange things. I always default to abit's account, probably because of an alphabetical thing.

**Comment by wmbutler** [comment]
@gibbsfromncis only if you can reproduce. You want to take it?

**Comment by gibbsfromncis** [comment]
@wmbutler assign to me please, I'll investigate and fix if find the reason.

**Comment by wmbutler** [comment]
Either release or resolve.

**Comment by gibbsfromncis** [comment]
@wmbutler I've tried to debug but I do not know why this happens and already spent a lot of time.

**Comment by wmbutler** [comment]
This isn't really a feature or a bug as far as I can tell.
