### ISSUE TITLE
[1] Entered Bin file and Password 

### ISSUE THREAD

**Issue by hubba1** [bitshares/bitshares-ui#1147]
these were entered successfully but when I clicked on RESTORE WALLET it goes no further...

![image](https://user-images.githubusercontent.com/20878396/36077380-bac0e012-0f2f-11e8-92e2-358fc509d084.png)

**Comment by wmbutler** [comment]
Are you at wallet.bitshares.org?

**Comment by hubba1** [comment]
no I am trying to sign in from https://compumatrix.co/

**Comment by hubba1** [comment]
I just tried it from wallet.bitshares.org and still won't go past the restore wallet button

**Comment by hubba1** [comment]
![image](https://user-images.githubusercontent.com/20878396/36078096-1ff73a78-0f38-11e8-9ce5-5c90ce166130.png)

**Comment by hubba1** [comment]
![image](https://user-images.githubusercontent.com/20878396/36078119-56f57080-0f38-11e8-9ba5-4a3ac122e86b.png)

**Comment by gibbsfromncis** [comment]
@hubba1 what is your browser?

**Comment by hubba1** [comment]
Chrome

**Comment by gibbsfromncis** [comment]
@hubba1 are you sure you select the right file?

Because my `Restore` buttons looks like this:
<img width="424" alt="screenshot 2018-02-11 21 48 53" src="https://user-images.githubusercontent.com/35899973/36078372-81f8295c-0f75-11e8-9afe-de0aa7a9a3e4.png">

**Comment by hubba1** [comment]
![image](https://user-images.githubusercontent.com/20878396/36078387-0a0d5c08-0f3b-11e8-959f-eda1203bfea7.png)
That is the only choice I have....

**Comment by gibbsfromncis** [comment]
@hubba1 provide me please node do you use:
1) Go to `Settings`
2) Go to `Access`

Tell me which Active Node do you have?

**Comment by hubba1** [comment]
Kansas City....high latency

**Comment by gibbsfromncis** [comment]
@hubba1 Just tested on your node. it's strange because it works. If you want me to help you please try to record your screen beginning from opening wallet.bitshares.org

**Comment by hubba1** [comment]
ok..screen shots I assume?

**Comment by gibbsfromncis** [comment]
@hubba1 nope, exactly video record.

**Comment by hubba1** [comment]
ok

**Comment by wmbutler** [comment]
Use licecap for screen recordings. It's really convenient.

**Comment by hubba1** [comment]
haven't heard of that but will download it now..thanks

**Comment by hubba1** [comment]
![bin file log in](https://user-images.githubusercontent.com/20878396/36078524-43fdd210-0f3d-11e8-8a82-de81ba876f67.gif)

**Comment by gibbsfromncis** [comment]
@hubba1 actually you're doing something wrong. First of all we have new design: 
<img width="1440" alt="screenshot 2018-02-11 22 09 58" src="https://user-images.githubusercontent.com/35899973/36078553-546ea24c-0f78-11e8-9f57-e0351c0f7a1e.png">

On your screen record I see old design.

Please make sure you use RIGHT URL: **http://wallet.bitshares.org**

**Comment by hubba1** [comment]
ok I'll try that again....it was the same result when I tried it before

**Comment by gibbsfromncis** [comment]
Please login on OUR url: http://wallet.bitshares.org and change the password of your wallet.

**Comment by hubba1** [comment]
![bin file log in again](https://user-images.githubusercontent.com/20878396/36078583-378a0b2e-0f3e-11e8-9895-21380af46e6e.gif)

**Comment by hubba1** [comment]
I did try that...and it still was the same result

**Comment by wmbutler** [comment]
@hubba1 you need to do the licecap from wallet.bitshares.org or we can't help you. This is the only code that we have direct control over.

**Comment by hubba1** [comment]
![bin file log in from bitshares org](https://user-images.githubusercontent.com/20878396/36079857-5ace1800-0f4d-11e8-9768-245a3d4387ff.gif)

this log in attempt is from your url above

**Comment by wmbutler** [comment]
- [ ] Show your console in the next licecap (Option - Cmd I). Just wondering if there are some interesting logs that might help us determine what's going on.
- [ ] Try to enter an incorrect password. Do you get an error?

**Comment by hubba1** [comment]
![bin file log in from bitshares org](https://user-images.githubusercontent.com/20878396/36080011-4c425c5e-0f4f-11e8-8233-c7c57928003e.gif)

**Comment by hubba1** [comment]
![bin file log in from bitshares org 2](https://user-images.githubusercontent.com/20878396/36080044-bc860a88-0f4f-11e8-8145-b077a9e6637c.gif)

**Comment by hubba1** [comment]
is that what you wanted to see??

**Comment by hubba1** [comment]
ok will do

**Comment by hubba1** [comment]
![console](https://user-images.githubusercontent.com/20878396/36080115-db9bcf9c-0f50-11e8-9698-43bc6fd97cf7.gif)

**Comment by wmbutler** [comment]
Thanks. I've booked this bug and marked is as high priority.

**Comment by hubba1** [comment]
if it would be of any help ...I DID find a work around for this issue....it's not a fix to the problem but does get me into the account....here are the steps...
realised that since I was getting to the restore (wallet) button, the system was accepting his Bin file and password so I COULD import these into another local wallet and gain access to accounts in that way. You need to go to the dex and click settings/local wallet (you may have to click the Restore/import link first to get to the local wallet). You then create a new local wallet using your bin file and password for the account you are trying to gain access to. You then have to name the new wallet and backup the bin file and use that with your password in the future, but this should give you access to the account and it's contents. Hope that helps.

**Comment by wmbutler** [comment]
The error message is specific. It says that the wallet file is not a valid name. As such, you could try renaming the file to `default.bin` to see if this corrects the problem. Make a copy of it and rename the copy and try to load it.

If this works, it's a simple matter of removing any restrictions related to a required filename on this.

**Comment by svk31** [comment]
It's caused by the uppercase characters in the filename. There's a check that requires the wallet name to only have lowercase characters, not sure why that is though. I'll make it so the wallet name is converted to lowercase.

**Comment by hubba1** [comment]
wow...a small problem!!  thank you!!

**Comment by svk31** [comment]
Your specific issue was actually that you tried to restore the wallet without entering a name for the new wallet at all. Try restoring again but enter a name for your wallet when prompted (after selecting the file and entering your password)
