### ISSUE TITLE
[1.5][svk31] Nodes list layout and validation

### ISSUE THREAD

**Issue by swoopyy** [bitshares/bitshares-ui#1149]
- [ ] Fix overlapping in nodes list items
- [ ] Add validation for attempts to add duplicate nodes (by url)
![2k2mpxyxamg](https://user-images.githubusercontent.com/11968967/36077837-9c0e824a-0f80-11e8-91c2-7fd047d105f7.jpg)

**Comment by wmbutler** [comment]
Let's move "Reachable / Unreachable" just to the right of the node URL:

```
wss://sg.nodes.bitshares.works | Unreachable
```

**Comment by svk31** [comment]
I've merged the PR but the latency numbers still overlap the names on small screens. Another thing is that the on hover display of buttons won't work on phones, so in that case they should just be always displayed I guess.

**Comment by wmbutler** [comment]
This needs a new design pattern ultimately. Let's just fix the bugs and we can get @ahdigital to revisit UX at a later date.

**Comment by ahdigital** [comment]
@wmbutler Can you create a UX item to address the issues @svk31 raised please. Thanks.

**Comment by rngl4b** [comment]
What do you think about displaying the active node at the bottom status bar?
Maybe even better, making it a dropdown menu to show (and choose from) other available nodes?

I find unpractical the need to go into Settings every time I want to see or change the node I'm connected to.
In addition, it could make it clearer the fact that web wallets and API nodes are just different interfaces and endpoints for the same blockchain.

**Comment by ahdigital** [comment]
I agree with the concept and tried it out in my own time a couple of weeks back. I'll revisit as part of #1223 perhaps.

**Comment by wmbutler** [comment]
@rngl4b I like your idea of displaying the full node name in the lower right.

**Comment by ahdigital** [comment]
There is already a tooltip showing the node name, or did you mean something else?

![image](https://user-images.githubusercontent.com/3088454/36790079-92f92936-1c8b-11e8-9f67-fe89f1cca9f9.png)

**Comment by wmbutler** [comment]
I think he was actually talking about displaying the node without requiring the tooltip.

**Comment by happyconcepts** [comment]
Let's consider letting a user get to the settings>access screen by a simple click on either the bottom right status area or on the associated rollover tooltip?
