### ISSUE TITLE
[5] Add elasticsearch to Bitshares Foundation Nodes

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1150]
@xeroc will you please add the elasticsearch plugin and ES databases to the Foundation Nodes? This will let us greatly improve the reporting. @oxarbitrage is available to help with this.

We plan to write an endpoint for the frontend that will test for the presence of ES on the chosen API node and will use it if available, otherwise it will fallback to the standard history. I've place 5 hours on this and will award them to you once you verify it is complete.

```
        {url: "wss://eu.nodes.bitshares.works", location: "Central Europe - BitShares Infrastructure Program"},
        {url: "wss://us.nodes.bitshares.works", location: "U.S. West Coast - BitShares Infrastructure Program"},
        {url: "wss://sg.nodes.bitshares.works", location: "Singapore - BitShares Infrastructure Program"},
```

**Comment by xeroc** [comment]
Quick remark: The infrastructure nodes are provided by Blockchain Projects B.V. and the foundation merely acts as escrow for the funds .. similar to the bitshares-ui worker.
I'll look into it.

Can you tell me how you would like to deal with the endpoints? Do you want to use a specific (different) endpoint, or simply try the "access endpoint" with a `/es` postfix?

**Comment by wmbutler** [comment]
@oxarbitrage will you please discuss best practice for this?

**Comment by xeroc** [comment]
update: successfully updated my deployment script to also deploy ES .. had to fiddle around with docker a bit but ES now receives operations ... next step is to setup an ES cluster and safely expose ES to the public (maybe thru the wrapper script provided by @oxarbitrage)

**Comment by wmbutler** [comment]
You probably don't even need a cluster. Clusters are only necessary for storage redundancy and since the blockchain contains all the data redundancy is not a requirement.

**Comment by xeroc** [comment]
Ran into the problem that our backend machines only hae 160GV of storage ... with elastic search eating up 140GB and the blockchain another 20G :)
need to redeploy on a machine that has more storage. This might turns into a problem since we've so far only deployed "high-ram" nodes that come wiht "litte" disk space.
We'll get there..

**Comment by wmbutler** [comment]
If it helps, we only need one node set up for ES to complete testing.

**Comment by xeroc** [comment]
This is a first deployment:
`176.9.44.67:9200/`

Please understand that it is **not** safe for production as it opens up the whole database to the public!

**Comment by xeroc** [comment]
Goibg forward, i believe we should use wrappers like thr one from Alfredo to encapsulate and secure the backend database .. I'll deploy the code next week

**Comment by oxarbitrage** [comment]
the ES wrapper (https://github.com/oxarbitrage/bitshares-es-wrapper) is not yet very used so i am not sure if can cover all the UI needs. Need to figure it out by using.

The idea is to expose it and as the UI start using it add more stuff to it while leaving the elasticsearch plugin and database doing its work in the background.

i have the wrapper exposed right now behind nginx (check samples urls https://github.com/oxarbitrage/bitshares-es-wrapper#samples). @wmbutler your team can use those urls right away if we decide all the calls to elastic will be done throw that wrapper.

good job @xeroc . If you have any question regarding the wrapper please let me know.

**Comment by wmbutler** [comment]
@svk31

**Comment by xeroc** [comment]
Maybe it is a good idea to specify the API that is useful for UI-devs and then implement the wrapper accordingly. Adding features to the wrapper should be much work.

**Comment by wmbutler** [comment]
The first application of this should be in Activity (Account History). But that's beyond the scope of this issue. The award is for having a usable, reliable ES server.
