### ISSUE TITLE
New operation `asset_update_issuer_operation`, breaking change!

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-ui#1155]
I would like to make you guys aware of a **breaking** change that has been approved with BSIP29 and will be deployed in the next hard fork release:
https://github.com/bitshares/bitshares-core/pull/599

That means, when changing an issuer of an asset, we can no longer make use of `asset_update` operation but instead need to implement and use a new operation `asset_update_issuer`.

I am placing this issue here so the UI devs know about this in time!

**Comment by xeroc** [comment]
@wmbutler 
I am not sure .5 hours is sufficient for this change since it also needs changes to bitsharesjs to add the new operation properly. If bitsharesjs also has unit tests for operations a new unit test needs to be written as well, then a new release for bitsharesjs need to be deployed and only then can the changes in the ui be made. @svk31 what do you think? How much time would be needed for bitsharesjs alone?

**Comment by wmbutler** [comment]
Understood. @svk31 can likely estimate this at whatever level he sees fit.

**Comment by calvinfroedge** [comment]
@xeroc Does the new endpoint have documentation available? I may be able to take this issue.

**Comment by startailcoon** [comment]
Further tracked on issue #1596, closing.
