### ISSUE TITLE
[.25][startailcoon] Hand Icon should display over account name and balance

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1158]
I noticed these bugs while reviewing staging.

- [x] Lock style should be larger and blue
- [x] Hand on account name

![hand](https://user-images.githubusercontent.com/1254810/36163372-d62b6a22-10ae-11e8-9d8f-060afb7656aa.gif)

**Comment by zhyupe** [comment]
Claimed

**Comment by zhyupe** [comment]
Seems that the small lock is introduced by @startailcoon in #889. Is that a proposed change?

**Comment by ahdigital** [comment]
It was actually something I introduced to make the header less cluttered and prevent text wrapping.

I removed the on click open modal functionality since login/logout is in the burger menu. Hence why it is now white and not blue as it is no longer a button.

**Comment by startailcoon** [comment]
![screenshot from 2018-02-13 21-05-47](https://user-images.githubusercontent.com/12114550/36171356-a252a1e4-1102-11e8-986f-3b3ed0e30763.png)
![screenshot from 2018-02-13 21-06-43](https://user-images.githubusercontent.com/12114550/36171364-a732822e-1102-11e8-97ed-4faa277eeabf.png)

**Comment by wmbutler** [comment]
I didn't mean to overly complicate this issue. I thought the change to the lock was an oversight. The lock was originally to the left of the account name and I think it should remain there. I am open to debating the merit of clicking the lock to mimick the login/logout process but perhaps we should do that at a later date?

**Comment by startailcoon** [comment]
I don't see a reason for removing it. There is enough space to accommodate it.
