### ISSUE TITLE
[.5] Balance missing! BTWTY bought and not showing in wallet. #bug #moneymissing

### ISSUE THREAD

**Issue by EstefanTT** [bitshares/bitshares-ui#1161]
Hi, 

I'm EstefanTT, creator of www.bittwenty.com, BTWTY smartcoin on the DEX. 

A BTWTY buyer has contacted me because he can't find the BTWTY he bought. 

Here is the account: fd2018

As you will seel, he has bought BTWTY but they are not showing in the wallet. This situation is very bad for the reputation of BitShares and my smartcoin.

**Comment by wmbutler** [comment]
@svk31 This is interesting...

![screen shot 2018-02-14 at 9 32 48 am](https://user-images.githubusercontent.com/1254810/36212647-11fb09a2-116a-11e8-99d7-8c8835c3f8bc.png)
![screen shot 2018-02-14 at 9 32 42 am](https://user-images.githubusercontent.com/1254810/36212649-1226fd28-116a-11e8-9d21-c32fe188d840.png)

**Comment by startailcoon** [comment]
Note that the value of the user is the same as on Cryptofresh.
http://cryptofresh.com/u/fd2018

You can see the trade going trough, but the value of the users wallet isn't reflecting this. It's not limited to a UI issue of the BitShares-UI, but most likely related to something more.

**Comment by svk31** [comment]
Some kind of dust order issue maybe, where the amounts are too small to actually be counted in the end? He's dealing in 1 and 2 satoshi amounts. Dunno tbh... @abitmore ?

**Comment by EstefanTT** [comment]
BTWTY is very expensive, even 0.00001 is worth money, several BTS (around
32 at current price) . So I don't thing it's a dust thing.

[image: image.png]

**Comment by svk31** [comment]
It's dust because the precision of BTWTY is 5, meaning 1 satoshi of BTWTY is 0.00001. The value of the satoshi amount in dollars or BTS is irrelevant.

**Comment by startailcoon** [comment]
Other users with this little amount have them visible. I still think this is a core issue rather than a UI issue. 

![smartselectimage_2018-02-16-07-38-00](https://user-images.githubusercontent.com/12114550/36297916-957135d6-12f5-11e8-91ad-95bbd49e1ca0.jpg)

**Comment by roberto-1994** [comment]
Hi,
i have a similar problem.
My account name is roberto-1994.

I have bought 0.0001 BTWT the day 2018-01-30. The transition was registered in the Block Number : #23969487. it was all right.

One week later I controlled my BTWT balance and it was only 0,00002 BTWT: so, 0,00008 BTWT are disappeared!!!

I checked the history of my transactions several times with the aim of understanding if I had accidentally made some incorrect transactions, but I haven't transferred any BTWT.

Then, the day 2018-02-12 I decided to sell 0,00001: the transaction proceeded well.
Unfortunately, after this transaction, the remaining part of the balance has disappeared.

So, to date, 0.00009 have disappeared altogether, for a value of around 70 usd.

I thank everyone for their help and I apologize for my English.

**Comment by wmbutler** [comment]
@oxarbitrage ?

**Comment by oxarbitrage** [comment]
one thing i noticed while taking a look into this is that there are fees paid in BTWT for canceling limit orders in account fd2018 as:

http://open-explorer.io/#/operations/1.11.127750225
http://open-explorer.io/#/operations/1.11.127743311
...

in cryptofresh:

http://cryptofresh.com/tx/287c371e424be9fd47bb81820c4db2d76a8e8517

**Comment by oxarbitrage** [comment]
in `roberto-1994` is the same but let me continue with `fd2018` as it is an account with less history so easier to analyze.

the account purchased 4(raw blockchain numbers without precision calculation) BTWT in total by this 2 fill orders, each one receiving 2 BTWT:

http://open-explorer.io/#/operations/1.11.127087214
http://open-explorer.io/#/operations/1.11.127710771

then in the account there are 4 cancel operations that eats 1 BTWT each:

http://open-explorer.io/#/operations/1.11.127730546
http://open-explorer.io/#/operations/1.11.127743311
http://open-explorer.io/#/operations/1.11.127750225
http://open-explorer.io/#/operations/1.11.127759015

that is the reason why the BTWT balance in thbis account is 0 and by this not displayed in the UI.

**Comment by oxarbitrage** [comment]
in the case of http://cryptofresh.com/u/am1980 no BTWT was used to pay fees so as account purchased 2 BTWT the balance is  exactly that amount of coin.

**Comment by EstefanTT** [comment]
How comes that an order cancelled eat up to 0.00001 BTWTY? 

Is it because it is the smallest part of a BTWTY and the person didn't have any BTS in his account?

**Comment by oxarbitrage** [comment]
if you pay fees with that coin for any reason, it will not be less than that value.

**Comment by abitmore** [comment]
Linking the order cancel fee issue here: https://github.com/bitshares/bitshares-ui/issues/1117
@wmbutler please make it a priority.

**Comment by abitmore** [comment]
> BTWTY is very expensive, even 0.00001 is worth money, several BTS (around 32 at current price) .

I'd recommend NOT create that kind of "expensive" assets with insufficient precision. Be VERY CAREFUL when trading those. It's easy to run into rounding issues. Already lots of complaints/discussions about this, E.G. WHALESHARES and etc.

**Comment by EstefanTT** [comment]
When we created this asset it was 1000$. It looked ok with 5 decimals. 

I can't really explain right now how but we found a solution to resolve this hight value decimal situation. I'll soon publish an official announcement on the chats and forums about Bit20 evolution.

**Comment by wmbutler** [comment]
Please post the resolution here.

**Comment by abitmore** [comment]
@wmbutler fix the order cancel fee issue described in #1117 . Aka don't use an expensive asset to pay fees.

**Comment by wmbutler** [comment]
ok, closing this since #1117 will solve it.
