### ISSUE TITLE
Hamburger menu cannot be opened

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1162]
On the latest Staging version somebody crash hamburger menu for passwordAccounts

<img width="1440" alt="screenshot 2018-02-14 14 10 07" src="https://user-images.githubusercontent.com/35899973/36205907-ca13e880-1190-11e8-81a9-363c4fe2ada1.png">

I'm already working on it.

**Comment by gibbsfromncis** [comment]
@startailcoon Why did you remove this variable? Does it make any sense or it was mistake?
 https://github.com/bitshares/bitshares-ui/commit/1fc630b0954e61a7b242ca8c2b1a55a2b9fc1e55#diff-e57114ebcc66186621ffaca2f22305f2L255

**Comment by gibbsfromncis** [comment]
@wmbutler fix already submited as PR: #1163

**Comment by startailcoon** [comment]
@gibbsfromncis my bad. Its removal was never intended. I suspect a merger going wrong.
