### ISSUE TITLE
Discussion: Strange changes on Header (staging)

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1167]
I have pulled last changes and now I see everything were changed... We have removed Login page from Home Screen, we have removed Create Account/Login from header if user not logged in...

<img width="1440" alt="screenshot 2018-02-14 15 23 20" src="https://user-images.githubusercontent.com/35899973/36209215-74eb0428-119b-11e8-921c-89519a1498b6.png">

We have removed "hover" state from Account name. How user should understand he can click on account to see accounts list if there are no any Hover state and cursor is carret except be ☝️ 

We have removed "hover" from hamburger? 
![gif-strange-header](https://user-images.githubusercontent.com/35899973/36209304-b3945800-119b-11e8-9029-a89d9ed8ab53.gif)

It looks like a part of future changes or big mistake... I didn't find tasks where this changes mentioned..

**Comment by gibbsfromncis** [comment]
I even cannot Login under wallet account: #1168

**Comment by gibbsfromncis** [comment]
Why there are "Add contact" button? Which contact can I add if I even not logged in??

<img width="1440" alt="screenshot 2018-02-14 15 35 30" src="https://user-images.githubusercontent.com/35899973/36209690-bb9f945a-119c-11e8-8003-dea06daf4a5f.png">

**Comment by gibbsfromncis** [comment]
@svk31 @wmbutler guys I think cannot deploy this. And I think we should investigate why this happened. Why those changes are on staging before Sprint end...

**Comment by startailcoon** [comment]
Many changes to the header was made trough this PR https://github.com/bitshares/bitshares-ui/pull/1140

**Comment by gibbsfromncis** [comment]
@startailcoon it's nice that you discovered the issue/changes which break current staging.

What we should do with that? For me It looks really bad and current staging cannot be deployed...At least without bug fixes..

**Comment by gibbsfromncis** [comment]
@startailcoon did we remove ability to Login/Create Wallet accounts? Because i've discovered there is no way to create Wallet account too. Maybe it's feature, not a bug?

**Comment by ahdigital** [comment]
It's a bug. The user should be able to see the login selector page to login, create cloud account, create local wallet, restore local wallet etc. but this doesn't happen any more.

**Comment by wmbutler** [comment]
We have a day before we deploy so we have time to discover what's going on.

**Comment by startailcoon** [comment]
None of my changes should touch these functions as far as I'm aware of.

I agree with OP though.

PR https://github.com/bitshares/bitshares-ui/pull/1159 fixes the hover of the cursor, but not any of your other issues.

**Comment by startailcoon** [comment]
### This issues is due to PR 1142
The current landing page has been changed per PR #1142. It introduces a new Route here

https://github.com/zhyupe/bitshares-ui/blob/535290bf8f1f18ecbe97227c3266e926617d7a1c/app/Routes.jsx#L31-L33

`System.import("components/Dashboard/DashboardPage").then(loadRoute(cb)).catch(errorLoading);`

It also removes many items, such as `Dashbaord/DashboardComponent`, `Dashboard/Dashboard.jsx`, `Dashboard/DashboardContainer.jsx`.

The following is the changes: https://github.com/bitshares/bitshares-ui/pull/1142/files#diff-0a3903d5a6ab0743557c063c90f776c8

#### Issue 
The PR onboards the user directly to the newly introduced Stared and Featured market place instead of the normal Dashboard which handles new users coming in trough the gates.

This PR most likely needs to be reverted and reworked.

**Comment by gibbsfromncis** [comment]
@svk31 can you help us please?

**Comment by gibbsfromncis** [comment]
@startailcoon I suppose if @svk31 can remove this commit but it will be on another pull requests which waiting for approval...

**Comment by startailcoon** [comment]
I'm sure svk is able to revert it in some good practices.

**Comment by gibbsfromncis** [comment]
@wmbutler I saw many issues after latest changes. I will create issues to fix them when have free time

**Comment by startailcoon** [comment]
After a few hours of sifting trough the staging branch I've successfully committed the changes from #1143 that was reverted. Only thing that isn't really as it should is still the hover on accounts, as svk mentions.

**Comment by startailcoon** [comment]
Was this resolved after the new release?

**Comment by zhyupe** [comment]
The only issue introduced by #1142 is the missing welcome page for new user. I've fixed that in the new pr #1193.
