### ISSUE TITLE
[3][gibbsfromncis] Contacts Improvements

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1173]
For now user unable to add/remove Contacts. From technical perspective for now it looks like User Link/Unlink another users accounts. It looks not good because all accounts placed on the same place, use the same API, user unable to remove somebody from his contacts because he just mark Contact like "Hidden". 

Idea is to update move split Contacts and user own accounts logic.  

There is the list of updates:

- [x] (Technical task) Add API for add/remove Contacts
- [x] Make user able to remove contact from his Contacts List (for now account marks like a "Hidden") on Accounts page Contacts tab
- [x] Add Contacts list like a dropdown on Transfer page for "To" field:
<img width="604" alt="screenshot 2018-02-15 02 47 38" src="https://user-images.githubusercontent.com/35899973/36237207-c4d0169a-11fa-11e8-98f9-a5c13f3ac2d7.png">

Fair Estimate: 4 hours

**Comment by gibbsfromncis** [comment]
@wmbutler This comment from @svk31 proof my idea to rework on Contacts: #1174 (comment)

**Comment by svk31** [comment]
Definitely worth doing a pass on the contacts API as outlined by @gibbsfromncis here. A contacts API separate from the original linked accounts would be great.

**Comment by wmbutler** [comment]
OK, so then what is the functional difference between a linked account and a contact? What is the purpose of each and how are those purposes significantly different?

**Comment by gibbsfromncis** [comment]
@wmbutler linked accounts are your accounts if you use wallet account. You can see linked accounts on your Accounts Page (https://wallet.bitshares.org/#/accounts) or in dropdown when you click on your username, or in Settings->Accounts. 

For now contacts are stored as Linked Accounts. You don't see them with your accounts because on all places where your accounts are listed places a check like:
```
if(isMyAccount()) 
// display
} else {
// do not display
```

It looks like a hardcode in a lot of places and wrong logic from code perspective. This confuse developers and may produce bugs. Like if somebody will work on some user accounts list developer will miss that linkedAccounts is not only your linked accounts, there are your contacts too. 

Contacts it's just accounts which you want to use in quick way like a make transfer to your contact or propose transaction for your contact. Linked Accounts may be your contacts too because if you want to make transaction for your second account in quick way you use Contacts for this.

**Comment by gibbsfromncis** [comment]
Now Explorer/Accounts and Account/Contacts uses "Contacts API"

Also you can see your contacts on typeahead on Send page:
![gif-contacts-send](https://user-images.githubusercontent.com/35899973/37445412-2d8392e2-2818-11e8-852d-b2866270e7c5.gif)

**Comment by gibbsfromncis** [comment]
@svk31 as this task already merged I'm closing this one.
