### ISSUE TITLE
TestNet vs MainNet use

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1175]
The bitshares ui automatically reselects a new node if the current is slow or not reachable. 

Is there a way to ensure that it only connects to the same network again? I am developing something on the testnet right now and it happens that it switches to the MainNet on reload.

Stefan

**Comment by svk31** [comment]
You can hide all the mainnet nodes. The fallback ignores testnet nodes, but you can add --testnet to the webpack launch command in package json (locally) to make it include testnet nodes in the fallback.

`var config = require("./webpack.config.js")({prod: false, testnet: true});`

in server.js
