### ISSUE TITLE
[.5][pnomolos] Local Wallet Accounts visual issue

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#1177]
Lastest Light Client, win7

![image](https://user-images.githubusercontent.com/15261692/36316743-6f1e52ec-133b-11e8-8f56-c62a5d5aac1b.png)

**Comment by startailcoon** [comment]
Username has wrapped and the list is not increasing the height or width. This should be handled by increasing the width.

**Comment by pnomolos** [comment]
I'll take this one.

**Comment by pnomolos** [comment]
@startailcoon Maximum username width is 64, I don't think we really want it that long:

![image](https://user-images.githubusercontent.com/36223/36358609-e8006c50-14c5-11e8-9a4d-c830d0aa3ec3.png)

Right now it's 200px.  We could do 250-300 or dynamically calculate it based on the length of the longest name.

**Comment by startailcoon** [comment]
I thought of making it a little longer, to avoid cutting of usernames. But it shouldn't be to long, as in your image, so a maximim width and handling long usernames with a tooltip sounds like a good plan to me.

**Comment by wmbutler** [comment]
How about ... after 25 characters?

```
thisismyreallycrazylongusername...
```

**Comment by pnomolos** [comment]
@wmbutler @startailcoon I have a solution working that just uses the css "text-overflow" but I'm curious what browsers we target to make sure I don't use any CSS that's going to break :)
