### ISSUE TITLE
[1][startailcoon] Latest client, Portfolio with many assets, still CPU/Memory leaks

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#1178]
Latest light client

Clicking Portfolio / Hidden with many hidden assets grills my CPU still. 13 cores at full force...

**Comment by btsfav** [comment]
same for the chrome/html version:

![image](https://user-images.githubusercontent.com/15261692/36339766-ff09445c-13cc-11e8-8d0f-53a1ba773259.png)

**Comment by wmbutler** [comment]
Please post precise steps to reproduce. Sorry, but I'm not seeing this so it's hard to troubleshoot.

**Comment by btsfav** [comment]
click Portfolio / Hidden, or just click around in general. it's hard to say what triggers it, but I've experienced it from many actions

**Comment by btsfav** [comment]
another one: hide some nodes, then click portfolio

**Comment by compumatrix** [comment]
Got the same problem. I had to revert back from 2.0.180215 to version 2.0.180115. The new release is definitely eating up a lot and freezes all the time.

**Comment by btsfav** [comment]
@wmbutler I really think you should put in a feature freeze in place and fix the bugs now. it'll only be more complicated to find and fix at a later stage

**Comment by wmbutler** [comment]
I'll set a high bounty on this issue. It's easy to reproduce and I hope someone will want to claim it and fix it.

**Comment by startailcoon** [comment]
I can take a closer look and debug some. I haven't personally experienced this what I know of, but will try to see what I can dig up.

**Comment by startailcoon** [comment]
@compumatrix freezes may be related to this issue https://github.com/bitshares/bitshares-ui/issues/1195

**Comment by startailcoon** [comment]
After talking to @btsfav we've come to the conclusion that the issue does not exist while using BTS as preferred unit in the wallet, but does when using bitUSD. This makes me highly certain that the issue experienced is #1195, which I reported about yesterday and supplied a fix for.

Can anyone else having this issue also try this and report back if the issue is also present if using BTS as prefered unit in the wallet (ie. bitUSD, bitCNY, bitEUR etc)

**Comment by btsfav** [comment]
@wmbutler @svk31 please consider hotfixing this

**Comment by wmbutler** [comment]
I can confirm that I do not see the bug when BTS is chosen as my display currency. I would support a hotfix. @svk31 ?

**Comment by wmbutler** [comment]
@startailcoon how many hours should this get?

**Comment by startailcoon** [comment]
Debugging and tracking this, say one hour.

**Comment by wmbutler** [comment]
Nice find, btw!
