### ISSUE TITLE
[2][startailcoon] Typeahead component issues

### ISSUE THREAD

**Issue by sratemo** [bitshares/bitshares-ui#1179]
![capture](https://user-images.githubusercontent.com/4792977/36321223-f5de72a0-12fd-11e8-9f7a-6b1415b7489b.PNG)

Hi, 
While using the light theme and trying to send funds to other BTS accounts, the address field is not visible. This is a new issue that started happening after the new UI update. 

Please see attachment.

Sam

**Comment by startailcoon** [comment]
This is an issue with the Typeahead component.

### Current Issues that needs addressing
- [ ] Adapt to theme specific colors.
- [ ] Bind to the input field (see licecap)
- [ ] Open drop-down with down-arrow

![bitshares-typeahead-issues](https://user-images.githubusercontent.com/12114550/36339549-c6df07b4-13c8-11e8-8828-b94e2b283bb6.gif)

**Comment by wmbutler** [comment]
This is a theme issue and it's important. The light theme is using a black background and black text. The Midnight theme is using some of the dark theme. components.

**Comment by startailcoon** [comment]
I'll claim this

**Comment by startailcoon** [comment]
The latest addition to typeahead was written extremely static.
Sizes and colors are all hardcoded, which isn't code when we're having a dynamic app.

**Comment by startailcoon** [comment]
@AustinAmoruso I need to be able to added classNames to the Typeahead component. To be able to accommodate different styles for different themes, this is required first.

**Comment by ahdigital** [comment]
I had a look and you can leverage wrapperProps ([API](https://github.com/reactjs/react-autocomplete#wrapperprops-object-optional)) to add your own class name to the typeahead results wrapper.

For example, inside TypeAhead.js I tested the following code (shortened for brevity):

```
dropDown = () => {
    const openFlag = isMenuShowing
        ? "typeahead-open"
        : "";

    return (
        <Autocomplete
            // I specify class for wrapper, and class to know if menu is open
            wrapperProps={{ className: openFlag + " typeahead-menu" }}
        />
    );
};
```

I also managed to add my own classes to the typeahead items and inner wrapper:

```
renderItem = (item, highlighted) => {

    return (
        <div
            key={item.id}
            style={{
                backgroundColor: highlighted ? "#eee" : "transparent",
                padding: "5px"
            }}
            // This is a typeahead item
            className="typeahead-item"
        >
            <span style={{ color }}>{item.label}</span>
            <span style={{ float: "right", color: "#afafaf" }}>
                {item.status}
            </span>
        </div>
    );
};

selectedDisplay = () => {
    const { value } = this.state;
    return (
        <div
            style={{
                width: "100%",
                backgroundColor: "#3e3e3e",
                height: 32,

                borderRadius: 5,
                paddingLeft: 10,
                paddingRight: 10,
                paddingTop: 8,
                paddingBottom: 5
            }}
            onClick={this.onClick}
            // This is the container inside the typeahead wrapper
            className="typeahead-inner"
        >
            {value}
        </div>
    );
};
```

I think by adding these classes you should be able to pull the static styles out and into the themed SCSS.

**Comment by wmbutler** [comment]
@ahdigital do you need some hours for this?

**Comment by ahdigital** [comment]
@wmbutler I spent about 30mins looking into this. I'm hoping that startail can complete the task based off of my findings above.

**Comment by startailcoon** [comment]
# Final Result

There's some GIF compression in licecap that makes it look like there is no border around the dropdown, but this is how it looks like in action now.

![bitshares-typeaheadasset_1](https://user-images.githubusercontent.com/12114550/36751906-de70b2a6-1c01-11e8-9ba5-3d439878fcf3.gif)

## White Theme
![image](https://user-images.githubusercontent.com/12114550/36752046-2d25998e-1c02-11e8-8237-89bd5c9b9a80.png)

## Midnight 
![image](https://user-images.githubusercontent.com/12114550/36752070-3da3775e-1c02-11e8-880e-6ea985010cac.png)

**Comment by startailcoon** [comment]
@wmbutler This took significantly longer than estimated hours.
- Requesting 2 hours for this task

**Comment by ahdigital** [comment]
Yeah 15mins was a bit ambitious!

**Comment by AustinAmoruso** [comment]
@startailcoon I will take a look at this tomorrow to add the ability for the className to be set, sorry for the delay.

**Comment by startailcoon** [comment]
@AustinAmoruso this has already been resolved.
