### ISSUE TITLE
Remove password change option in "Account model"

### ISSUE THREAD

**Issue by nmywn** [bitshares/bitshares-ui#118]
It is misleading.
Also please look:
https://bitsharestalk.org/index.php/topic,23645.msg304646.html#msg304646 this is urgent  imo.

**Comment by wmbutler** [comment]
@svk31 curious to know your thoughts on this. OP seems to indicate this is urgent. Since I'm not familiar with the account model, I don't understand the reasoning for removing the password change option.

**Comment by svk31** [comment]
The password change in Settings only applies to the wallet so it's not relevant when using account model, however it's already been removed a long time ago but seems like I missed this issue.

![image](https://user-images.githubusercontent.com/6890015/30686521-cf2bc1c6-9eb8-11e7-8e6d-39becae92ce9.png)

**Comment by wmbutler** [comment]
Sweet!
