### ISSUE TITLE
[1] UI fixes after last deploy

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1180]
- [ ] Update top margin on Settings
![Uploading 1.png…]()

- [ ] Remove `cursor:pointer` from username if user use login/password account.
<img width="240" alt="2" src="https://user-images.githubusercontent.com/35899973/36328809-e15c49d6-1363-11e8-923b-38e55f24ceaf.png">
 
- [ ] Fix box border in Chrome
<img width="1114" alt="4" src="https://user-images.githubusercontent.com/35899973/36328878-1bd85096-1364-11e8-831a-0bc2d6b8dc78.png">
<img width="1100" alt="3" src="https://user-images.githubusercontent.com/35899973/36328879-1bf27ebc-1364-11e8-9cea-852c635b3c86.png">
<img width="787" alt="8" src="https://user-images.githubusercontent.com/35899973/36328988-8ae412a4-1364-11e8-9b6e-7155c915024b.png">

- [ ] Fix background color:
<img width="1439" alt="5" src="https://user-images.githubusercontent.com/35899973/36328910-376e9f5e-1364-11e8-9888-d596789aba4a.png">
 
<img width="1439" alt="6" src="https://user-images.githubusercontent.com/35899973/36328936-5724a622-1364-11e8-9f18-1f742c39d0ca.png">

(it looks nice only on Midnight)
<img width="1439" alt="7" src="https://user-images.githubusercontent.com/35899973/36328956-6ca6cd72-1364-11e8-9ea5-06cc511bfed0.png">

- [ ] Fix tabs design(colors) on Settings:
<img width="787" alt="8" src="https://user-images.githubusercontent.com/35899973/36328993-913513b0-1364-11e8-8616-9cd71f206dfe.png">

**Comment by gibbsfromncis** [comment]
@wmbutler you can assign my issues to me

**Comment by HarukaMa** [comment]
I even think this issue worths a hot-fix deploy. The UI in 180215 version looks really terrible.

We really need a decent UI designer for those kind of things.

**Comment by gibbsfromncis** [comment]
@HarukaMa @wmbutler first of all we need carefully work on features and fixes. Because what we have now was produced by careless work on previous Sprint. Conflicts was fixed not careful by developers, some developers didn't test their features on different cases (like somebody who use Midnight theme didn't select Dark or Light to test how his changes look on these themes). 

It wasn't suggested changes so we don't need UI designer to fix it. We need ask our developers to work more professional or just find some QA man who has time to test all pull-requests on different cases, test not only delivered issue but a whole app, who can write some UI tests to make sure pull-request doesn't break UI somewhere.

**Comment by HarukaMa** [comment]
I was referring to the whole project about UI designer thing. I didn't check the code so didn't know that those issues are by mistake. Admittedly, I thought some of the changes were intended such as removed global margin.

**Comment by wmbutler** [comment]
I agree that each developer needs to do a better job of testing their issue once everything is merged to staging to ensure that conflicts are resolved. Regardless, this is a bug and it needs to be picked up and worked. Who wants to claim it?

**Comment by gibbsfromncis** [comment]
@wmbutler Those issues are already fixed. I've unassign myself from this issue and close this task
