### ISSUE TITLE
[2] Upgrade to react 16

### ISSUE THREAD

**Issue by AustinAmoruso** [bitshares/bitshares-ui#1184]
React 16 has a lot of support and there are a lot of libraries now using it, time to jump on the future. 

https://github.com/facebook/react/releases

**Comment by AustinAmoruso** [comment]
Will take this one

**Comment by wmbutler** [comment]
Clear this with @svk31 first.

**Comment by AustinAmoruso** [comment]
@svk31 Let me know if there is any thing you want to me make sure I do with upgrade. I will make a thorough PR.

**Comment by wmbutler** [comment]
@svk31 need your input here.

**Comment by AustinAmoruso** [comment]
@wmbutler This has already taken 4 hours I understand if that doesn't change the scope and there is likely to be more on it. I'm almost done with barring changes from PR input and making sure the charts render correctly.

**Comment by wmbutler** [comment]
Fine, post total hours when complete.

**Comment by svk31** [comment]
@AustinAmoruso Can you clarify why it's taking so much time? I had a quick look and got some errors from react-foundation-components so I guess we'll have to fork that and update it ourselves.

**Comment by AustinAmoruso** [comment]
@svk31 @wmbutler 
I'm going to release this one as I haven't had time to spend on it. I already put 4 hours in and here is the current state I was in for when I got to the charts needing to be updated. 

https://github.com/AustinAmoruso/bitshares-ui/tree/1184-upgrade-to-react-16

**Comment by wmbutler** [comment]
@svk31 advance to next sprint if needed and add required hours.
