### ISSUE TITLE
[.5][ahdigital] Add Japanese translation

### ISSUE THREAD

**Issue by mattbeckman** [bitshares/bitshares-ui#1186]
User gn1 on bitsharestalk.org made a Japanese translation file. 

Opening issue so he has a place to drop it in.

**Comment by gn1github** [comment]
Hi,
As per our conversation on bitsharestalk.org, I am attaching the Japanese translation file for BitShares here. Looks like attaching .json file wasn't supported, so I have compressed the file into a zip file.

[locale-ja.json.zip](https://github.com/bitshares/bitshares-ui/files/1733337/locale-ja.json.zip)

Kindly help adding this translation to BitShares (wallet.bitshares.org) GUI.

It will be great if you can let me know the ETA!

**Comment by ahdigital** [comment]
I can take this on.

**Comment by sschiessl-bcp** [comment]
This is connected to the actual translation work from #332, which was estimated 5 hours.
Maybe gn1 can get a nice surprise here @wmbutler ?

**Comment by gn1github** [comment]
I am assuming the previous translation work was for CryptoBridge, which has different translation strings for different sections, so I believe it is a separate project.

The one I have translated came directly from the BitShares locale-en.json.

**Comment by ahdigital** [comment]
Thanks, I am working on this for the next milestone.

**Comment by mattbeckman** [comment]
Yeah, we should throw some paid hours over to @gn1github for the translation.

**Comment by wmbutler** [comment]
@mattbeckman I added @gn1github to the 5 hour issue. Is that what you were requesting?

**Comment by mattbeckman** [comment]
@wmbutler Yeah, cool!

**Comment by ahdigital** [comment]
Done and PR submitted.

**Comment by ahdigital** [comment]
@wmbutler This can be closed now as PR merged.
