### ISSUE TITLE
Bitshare Lists 

### ISSUE THREAD

**Issue by JPederson96** [bitshares/bitshares-ui#1187]
I keep seeing BUY ORDERS listed in reverse order. How do I fix this? Here is a screenshot from crypto-bridge but OpenLedger and Bitshares also show this problem.

**Comment by wmbutler** [comment]
I'm not seeing this issue.

<img width="857" alt="screen shot 2018-02-17 at 10 41 49 am" src="https://user-images.githubusercontent.com/1254810/36343244-3666c4cc-13cf-11e8-9051-133d78eab648.png">

**Comment by JPederson96** [comment]
The issue has been fixed.

**Comment by diogogomes** [comment]
@wmbutler I can reproduce this issue if I change to vertical mode and change it again to horizontal mode.

It fixes itself closing the desktop client an reopening again.

##### Linux Desktop client 180215

**Comment by wmbutler** [comment]
See bug reproduction above.
