### ISSUE TITLE
[2][ahdigital] Modal Theme Issues

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1189]
Modals, send/buy/withdraw, does not comply to theme choices.

Current setting sets theme colors to dark, independent of user choice of theme. 

##### Make sure the following comply with all themes
- [ ] Background
- [ ] Input fields
- [ ] Possible drop down
- [ ] Buttons
- [ ] Error notices
- [x] Typeahead issue addressed in #1179

**Comment by ahdigital** [comment]
Happy to do this if you're not claiming it.

**Comment by startailcoon** [comment]
Its yours ahdigital

**Comment by startailcoon** [comment]
@ahdigital I'm not really sure if the issue I had was due to a caching issue on my phone, but the issue does not seem to be present on the desktop light client for me.

**Comment by startailcoon** [comment]
The Typeahead issue is adress in #1179 

The modal background is from this line and commit, which is from me and I have no idea why it's there or how it got in there. The last release got really tangled up in itself.

https://github.com/bitshares/bitshares-ui/blob/dc1ed2a328e77eed64504370332e5974f83121f5/app/assets/stylesheets/_shame.scss#L195-L199

**Comment by ahdigital** [comment]
PR submitted, and I'm leaving the typeahead styling issue for @startailcoon. I applied these changes as globally as I could - some screenshots below:

![modal-update-1](https://user-images.githubusercontent.com/3088454/36534626-0fd6aebe-17bf-11e8-9b57-6f0ceadb3371.gif)

![modal-update-3](https://user-images.githubusercontent.com/3088454/36534636-12881bac-17bf-11e8-9b5a-7ffce4247c3e.gif)

![modal-update-2](https://user-images.githubusercontent.com/3088454/36534646-14d6c0c0-17bf-11e8-98a0-479cbba1fca5.gif)

**Comment by startailcoon** [comment]
Looking good. Not sure about the buttons as it was requested in #556 to be like that with the colors and width. @wmbutler, what do you say?

**Comment by wmbutler** [comment]
Not as worried about the buttons as I am the color of the `To` input field. I would expect it to be the same color as all the other fields...

**Comment by ahdigital** [comment]
The 'to' field is being updated by startailcoon in another task. That's why it has been left to avoid conflicts.

**Comment by startailcoon** [comment]
This issue is still present, as the modal is still changing color when getting smaller.

![bitshares-typeahead_themeissue](https://user-images.githubusercontent.com/12114550/36932192-07170478-1ec6-11e8-9226-3cedc106fca7.gif)

**Comment by ahdigital** [comment]
Oh I can update the PR today. I thought the colour changes now where how they were supposed to be when the resolution switches to mobile.

**Comment by ahdigital** [comment]
Fixed.

![modal-test](https://user-images.githubusercontent.com/3088454/36935018-bf3bd588-1ee9-11e8-8c9d-4ba764a65cd5.gif)


![modal-test-2](https://user-images.githubusercontent.com/3088454/36935012-a5255dfe-1ee9-11e8-94a6-7009cad87d93.gif)

**Comment by wmbutler** [comment]
Advancing this to the next Sprint since it didn't make it into the current one.
