### ISSUE TITLE
[.5] New "help link" is badly placed on mobile

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1197]
The new help link introduced in the latest release is badly placed as a hovering question mark on smaller screens.

As visible in the attached screenshot, the 'view more' link on transactions are hidden behind the link.

![](https://i.imgur.com/oSoHpXm.jpg)

**Comment by ahdigital** [comment]
I think the placement seems ok for most use cases. I would look to amend the UI on specific tables etc. where this is an issue.

**Comment by startailcoon** [comment]
Idd, extra padding at the footer would solve this issue on mobile units for example.

**Comment by startailcoon** [comment]
I'll take this

**Comment by startailcoon** [comment]
I've looked at this quickly and found that this most likely needs extra padding on per page level as no CSS class handles page padding on a global scale. Pushing this until next milestone as its not critical.

**Comment by wmbutler** [comment]
Maybe wait to ant rewrite. Closing as non-critical.
