### ISSUE TITLE
[5][ahdigital] Messaging UX

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1200]
This is related to #697 and is intended to allocate hours towards the UX UI for messaging users within the BTS wallet.

**Comment by ahdigital** [comment]
@wmbutler Isn't @AustinAmoruso already doing this work as part of #967 or is he aware you're splitting the work load?

**Comment by gibbsfromncis** [comment]
@ahdigital I suppose you mentioned wrong task id on your message.

**Comment by ahdigital** [comment]
Sorry.. meant #697.

**Comment by wmbutler** [comment]
This is intended to provide hours for the UX portion.

**Comment by ahdigital** [comment]
Cool. I can provide help for this.

**Comment by ahdigital** [comment]
@wmbutler Following your last comment on #697 are you happy to close that task along with this one?

**Comment by wmbutler** [comment]
Yes, we have more pressing features for the wallet.
