### ISSUE TITLE
[5] Dashbord portfolio sorting is unstable with many assets

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#1202]
Accounts with a large amount of assets in their portfolio experience a "flash" of unstable sorting of the list of assets in the portfolio. I've looked at it before but have been unable to track down the reason for it.

One good example account to use is `demo.btsbots`

**Comment by wmbutler** [comment]
Possibly related to #1178

**Comment by startailcoon** [comment]
I can't see any flashing on my machine. Do you have a liceCap of it to view what it looks like for you?

![bitshares-flashingissue](https://user-images.githubusercontent.com/12114550/36618526-c85d04d8-18eb-11e8-8b18-e04c46befab3.gif)

**Comment by svk31** [comment]
You have to leave it a little, every once in a while it just changes the sorting order, then reverts to the correct one.

**Comment by startailcoon** [comment]
Whan a portfolio has many assets, it takes a very long time to load. Could this be related? I guess we would need some debugging to make the code cleaner and quicker to resolve this issue?

**Comment by wmbutler** [comment]
Possibly retrieve and display the assets from localstorage first and then merge in the price updates without freezing the UI.

**Comment by svk31** [comment]
I'm not sure the sorting is still unstable, I think that was solved. However the performance is definitely an issue. It's partly because so much data needs to be fetched, and partly because rendering long lists of pretty much anything has bad performance. Ideally we'd implement a solution to both problems using something like this library to reduce the amount of rows being rendered: https://github.com/bvaughn/react-virtualized

**Comment by wmbutler** [comment]
I'll close this and open a separate issue for long lists of assets.
