### ISSUE TITLE
[1.5] Registration & Login front end tests

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#1207]
# BitShares Register

## Expected Behavior
* visit Wallet
* click sign-up button
* define username
* test clipboard button
* check boxes
* copy & paste password

Note: last step needs to be done by hand "account creation"

## Script

```
describe('BitShares Register', function() {
  it('wallet bitshares org', function() {
     cy.visit('https://wallet.bitshares.org')
	
	 cy.get('a.button.primary').click() //sign-up button
	
	 cy.url().should('include', '#/create-account/password')
	
	 cy.get('#username').type('favtest334') //define username
	 
     cy.get('.inline-label > .button').click() //test clipboard button
	 cy.get('#checkbox-1').click() //checkbox 1
	 cy.get('#checkbox-2').click() //checkbox 2
	 cy.get('#checkbox-3').click() //checkbox 3
	
        }) //copy&paste password to confirm password
		it('copies input values', ()=> {
        cy.get('.input-button').then($input1 => {
        cy.get('#password').invoke('val', $input1.val())

	
    })

  })
})
```

# BitShares Login

## Expected Behavior
* visit wallet
* click login
* click cancel
* click login again
* enter user name
* enter password
* click login button

## Script

```
describe('BitShares Login', function() {
  it('wallet bitshares org', function() {
    cy.visit('https://wallet.bitshares.org')
	
	cy.get('.hollow').click() //login button
	
	cy.get('.button-group > .hollow').click() //cancel button
	
	cy.get('.grid-block > .hollow').click() //login button
	
	cy.get('#username').type('btsbtc1') //login account
	cy.get('#password').type('testtesttest') //login password
	
	cy.get('button.button').click() //login button
	
  })
})
```

# Comments

This took me some hours to figure out obviously, but both scripts took around 40 mins to create I'd say.
Also, you have to be logged in to test a lot, so if you want me to go on with cypress, we'll need to keep the account & password test scripts offline.

a testwallet.bitshares.org environment would be needed too

@wmbutler @svk31

**Comment by btsfav** [comment]
@wmbutler tried to update the scripts to do the following:

select testnet and acitvate it.

and it's super frustrating to be honest. it's literally impossible to locate the testnet activate button, because it does not exists as a button somewhere. perhaps someone could give me a hint how to locate one specific button of the millions on there?

**Comment by wmbutler** [comment]
@btsfav we may be able to create an issue to make this button more accessible in the settings area for you. @startailcoon what do you think about this? We are trying to start using cypress.io to do frontend tests and it would be helpful if it was easy to script certain operations. Fav is finding it difficult to reference some frontend components. Happy to put some resources behind this to get it going.

**Comment by startailcoon** [comment]
@wmbutler @btsfav of course we could and should add hooks for items that the scripts need to work properly.

I will look at your script(s) and add some easier hooks to the things you need.

If we add an issue for tracking it I will post some updates on this during the next milestone and we can make sure we get all the things required.

**Comment by wmbutler** [comment]
Moving to next Sprint.

**Comment by startailcoon** [comment]
I've forgotten about this as an issue was never created and assigned to me. I will see if I can get some work on this before the release in a few day.

**Comment by wmbutler** [comment]
This needs completion or a PR to get paid.

**Comment by startailcoon** [comment]
I'm sorry for the missed target. I still intend to do this and will notify if I can't complete this in a few days as I agree on the necessity of this to make testing easier.

**Comment by startailcoon** [comment]
@btsfav what more do you need other than selecting the testnet node? 

So far I've done this, let me know what more you need and I will add some IDs to the items you're having issues with selecting.
```
Selecting TESTNET Nodes:
- Disable Automatic Node Select
-- Click to Disable -> ID: automatic_node_switcher
-- Click Node Switch Link -> ID: {node url} ex. wss://node.testnet.bitshares.eu
```

**Comment by sschiessl-bcp** [comment]
Are those tests included in the UI? Can someone point me to it please?

With the new release cycle this should be revisited!
