### ISSUE TITLE
Find markets tab scrolling

### ISSUE THREAD

**Issue by swoopyy** [bitshares/bitshares-ui#1208]
When clicking on find markets tab, tab bar disappears without ability to scroll content up
![](https://media.giphy.com/media/1woh8J9IVkXFTmOAl9/giphy.gif)

**Comment by wmbutler** [comment]
Confirmed. This happens when the browser height is low.

**Comment by swoopyy** [comment]
assign to me please

**Comment by swoopyy** [comment]
Not reproducible currently
