### ISSUE TITLE
Remove react-foundation-apps dependencies

### ISSUE THREAD

**Issue by AustinAmoruso** [bitshares/bitshares-ui#1209]
The app uses react-foundation-apps components in a few places this is an outdated library that hasn't be update since 2015.

https://github.com/akiran/react-foundation-apps

**Comment by AustinAmoruso** [comment]
I'm running into libraries that are old and should probably be removed at some point when I'm updating to react 16. I'm making new tickets as I find them. However I could see reasons to not remove this or to wait.

**Comment by wmbutler** [comment]
@AustinAmoruso before you move forward, please address the typeahead issues that have been requested. Thanks,

**Comment by clockworkgr** [comment]
@gibbsfromncis can you confirm if this is still the case? I remember you removing foundation dependencies.

**Comment by gibbsfromncis** [comment]
@clockworkgr I did but only for UI elements. We still use grid and we will remove it when start redesign.
