### ISSUE TITLE
Remove alt-react

### ISSUE THREAD

**Issue by AustinAmoruso** [bitshares/bitshares-ui#1210]
This seems to be a random fork someone did and only ever made one release of the alt js hasn't been updated in 2 years. 

https://www.npmjs.com/package/alt-react

https://github.com/altjs/react

**Comment by wmbutler** [comment]
@svk31 please advise just to be certain.

**Comment by wmbutler** [comment]
Moving to 180315 so we have ample time to test.

**Comment by svk31** [comment]
It's not a random fork, it's a component that was added by the alt creator to handle some changes in react that required a change in syntax.

**Comment by wmbutler** [comment]
@AustinAmoruso our team is waiting in some fixes to the typeahead component. Would you take a moment to address the topic with @startailcoon and @ahdigital ?
