### ISSUE TITLE
[1][ahdigital] UX - Denoting unsaved changes to tabs

### ISSUE THREAD

**Issue by ahdigital** [bitshares/bitshares-ui#1211]
_Related to #568_

# Background

This is the UX proposed solution for handling scenarios where a user can make changes to forms that span multiple tabs. The pattern can be implemented globally, but the specific example below is to assist with #568. An annotated screenshot is below with explanations.

# Proposal
Click image to enlarge.
![568-clear changes](https://user-images.githubusercontent.com/3088454/36665307-11bf339a-1adf-11e8-9230-d4de87db7179.png)

### 1. Default state
The annotations above should be self explanatory with the main points related to the action buttons.

### 2. Amendment on one tab
When the user changes a field on one tab, the action buttons should lose their disabled state.

### 3. Amendment on one tab and viewing another tab
If the user navigates to another tab, the previous tab text should change to bold and have an asterisk appended to the end of the name. This will denote that there is a tab with unsaved changes.

The reason to use an asterisk and not an icon is because space can sometimes be limited by the number of tabs, and choosing a single icon to accurately convey this meaning won't be easy. Using CSS a pseudo element, should make it possible to add the asterisk without 'jarring' the other tabs.

It's important to make the update to the tab text on this step and not on the previous because already the action buttons will be losing their disabled state and additional UI changes will distract the user from their objective - to review/edit fields.

### 4. Amendment on two tabs
If the user decides to amend another field on a different tab, the text on the 'Save changes' button should update to 'Save all changes'. This will provide another visual clue that changes across all tabs will be included in the save action.

This button should be wide enough to accommodate the addition of the word 'all' without causing a 'jarring' effect to adjacent elements.

### 5. Amendment on two tabs and viewing another tab
This step is the same as screenshot 3, but to show multiple tabs where changes have been made by the user.

### 6. Modal confirmation for multiple tab amendments (Optional)
As an additional (optional) safety net for the user, we could implement a confirmation modal window, which will be displayed when the user has changes across multiple tabs and clicks 'Save all changes'.

This final step would give certainty to the user that their changes from multiple tabs would be saved, giving them a chance to confirm or cancel and review. We could even make the bullet points showing tab names links, which when clicked close the modal and open the corresponding tab.

## Returning to an amended tab
To assist the user when they return to a tab where they had previously amended fields we should highlight those affected. These highlighted fields could stay solid or, fade back to their default state after ~500ms E.g.

![568-return-tab](https://user-images.githubusercontent.com/3088454/36666864-dde4713e-1ae3-11e8-9b6b-acc02b017d40.png)

**Comment by startailcoon** [comment]
Looking good.

Only question is the followikg

![](https://i.imgur.com/HG0a26v.jpg)

**Comment by ahdigital** [comment]
This just a page title, right? Not a child page of anything?

**Comment by startailcoon** [comment]
No other section has a page title between the top tabs and sub tabs.

**Comment by wmbutler** [comment]
I'd suggest it be in a transient tab to the right of "Explore". We decided last Sprint to put Send into the hamburger and remove it from being sticky at the top.

**Comment by ahdigital** [comment]
> No other section has a page title between the top tabs and sub tabs.

There's no relationship between the top tabs and 'sub-tabs', so for this reason I don't really see why we can't keep the page title there.

Hypothetically, if both tab bars _were_ touching it would look like the sub-tabs are child pages of the Dashboard. But, click 'Dashboard' and hey - they're not! The view refreshes and you see the actual children.

> I'd suggest it be in a transient tab to the right of "Explore".

I'm not 100% adverse to this idea **but**, the tab will be super wide compared to the rest and will need to be given the active state instead of Dashboard to make sense.

I can't wait for the navigation patterns and UI anatomy to get updated as part of #1213 / #1030 :)

**Comment by wmbutler** [comment]
I see.... looks like the Issued Assets contains a list so we are already 2 levels deep:

Top Level - Assets
Secondary Level - Issued Assets

That would make the third level the various settings for the issued asset which would typically be presented as the filters: `Primary Settings | Whitelist | Description ...`

I think it looks great as is, but this is yet another candidate for a complete sweep through of UX.

**Comment by ahdigital** [comment]
Agreed - I vote leave the page title where it is for now @startailcoon . We're looking into the navigation patterns atm anyway.

**Comment by startailcoon** [comment]
I'm happy with that and that we've discussed it through.

**Comment by grctest** [comment]
Seems like an appropriate issue to report this observation:
<img src="https://i.imgur.com/qEtDvVc.gif"/>

When you navigate to the page to update an asset, if you change the asset name in the URL (to check what their settings are) the asset name changes in the UI but the data from the original asset seems to remain in the fields.

**Comment by wmbutler** [comment]
@ahdigital so, for continuity purposes, once the UX is complete and approved, you should:

1. Close the issue (this issue)
2. Write up the front end development issue
3. Reference this from the FED issue
