### ISSUE TITLE
Version 180215: Lost response when access dashboard and can not connect to personal node

### ISSUE THREAD

**Issue by oflyhigh** [bitshares/bitshares-ui#1212]
When I updated my bitshares UI to version 180215(BitShares.Setup.2.0.180215.exe), I encountered a series of issues.

#### The first issue

When I open bitshares UI, and try to access the Dashboard, the software will lost response, and I can not do   anything with it. There was no help, even if I exit and restarted it.

But I can access other pages, for example Exchange, Explore......

#### The second issue

When I go to Setting->Access page, and try to use my personal node as access node.
My node shows as **Down**, and can not connected  even though I clicked "Active" Button. 

All things are working right, when I downgrade the bitshares UI to version 2.0.180115(BitShares.Setup.2.0.180115.exe).

**Comment by abitmore** [comment]
As discussed, the first one is perhaps duplicate of #1178.

**Comment by wmbutler** [comment]
I'd agree. @oflyhigh set your default display currency to BTS in Settings -> General and please post here if the problem goes away.
