### ISSUE TITLE
[3][ahdigital] UX - Navigation patterns

### ISSUE THREAD

**Issue by ahdigital** [bitshares/bitshares-ui#1213]
## Background
Navigating the DEX can be confusing because:

- There are 5 different navigation methods:
	- Top navigation
	- Sub-navigation
	- Side menu navigation
	- Tabs
	- Hyperlinks
- The current top navigation styling attempting to denote parent>child pages are confusing
- Visually, the menus look clunky with different font sizes
- Some unclear iconography
- I've noted 3/4 different ways that tab bars have been styled
- Sometimes sub-links are actually tabs, and vice versa
- Hyperlinks can be blue, white or grey depending on where you are

As part of #1030 I am proposing the following UX navigation pattern to address the above, and make a tidier looking navigation which can be used consistently by developers and understood by users.

The solution, if adopted will affect the following UI components which I hope to agree a consensus and get defined also as part of #1030.

- Top navigation
- Sub navigation
- Side menu navigation
- Tabs
- Hyperlinks
- Buttons
- Content container (E.g. Between header and footer)
- Page filter location (E.g. Table type ahead search input)

## Solution
I'll start by defining how I envisage the UI to look with regards to the header since this is where most of the user interaction begins.

The buttons in the main navigation are restyled to give the appearance of actual buttons and there is now also a clear relationship between the top and sub-navigation bar which doesn't bleed into the content body background.

The colour blue is used for the button text, the same as what should be hyperlinks so that it is clear to the user wherever they see something blue (hyperlink, button, tab, icon), it is clickable/tappable.

The content body (space between header and footer) is wrapped inside a container allowing the contents to be fluid, but also give a visual separation where we can include tabs and/or page filters. Including tabs and/or page filters here sends a message to the user that the content body is where these changes will be applied.

### Example of main navigation types
Click to enlarge image.
![navigation patterns](https://user-images.githubusercontent.com/3088454/36674906-6287c04c-1aff-11e8-97e9-e5bf39a5f1f7.png)

### Prototype
Click to enlarge prototype.
![navigation pattern](https://user-images.githubusercontent.com/3088454/36675401-b657b38e-1b00-11e8-9475-c75f4f7887a5.gif)

If everyone can agree that this solution is suitable for the DEX we can create a issue for the implementation and testing of the feature. I have mocked up these patterns for all 3 themes so colours and styling have been considered. I will also be able to help on #1030 to consolidate any styles affecting other components into the guide.

**Comment by diogogomes** [comment]
@ahdigital What is your opinion about the secondary navigation bar only being present "on hover"(Dashboard/Explore)?

It may become confusing but I think it can be solved with an icon to sign that there is a sub-menu.

**Comment by ahdigital** [comment]
I personally wouldn't have the secondary navigation bar only visible on hover. The consideration for touch devices aside, these type of menus can be annoying for users looking to operate them quickly. 

Even with hover intent implemented it's easy for the cursor to lose focus of an item as it's moved diagonally away and unintentionally rolls over an adjacent item.

**Comment by wmbutler** [comment]
Having a hard time understanding the relationship between the burger and the left side menu. Maybe this issue was not intended to address that. I like the way you are handling submenus but I still think we have a lot of discussion left around the overall hierarchy of the site.

**Comment by ahdigital** [comment]
I've included the sub-menu in that way for now, because that's how the [demo ](https://tympanus.net/Development/MultiLevelPushMenu/index2.html)I was pointed to integrate works. 

That's not to say that the side in which is opens cannot change though. I also don't think it affects the top nav, sub nav or tabs which is the crux of the issue I think.

**Comment by happyconcepts** [comment]
Not that I do not appreciate your thoughts on this, but to me the font color choice is horrible. You have put everything in either white or blue (Tabs, column data, etc) and there is no consistency to it which makes it really, really confusing. Don't fall in love with that shade of blue to the extent that you throw it around everywhere and ruin the UX. Please reconsider!

**Comment by ahdigital** [comment]
The consistency I was aiming for was body text in white with elements in blue clicking clickable/tappable. So hyperlinks in the table, clickable icons and buttons in blue for example. This pattern would get carried throughout all 3 themes with a small tweak to 'light' given the body text would be changed to black.

I'm not sure I agree that blue has been overused given that the only solid blocks of it are the buttons. But, I'm more than happy to experiment with any suggestions you could put forward?

**Comment by happyconcepts** [comment]
All diplomacy aside, how is forcing users to read blue text on a black background desirable? I'm outside on a cloudy day right now and it doesn't show up well at all on my mobile, for example.

Also, why not use any of the other popular cues for links...such as underlines or mouseovers or hover effects? Especially because, you know, bitshares is an exchange and color already has significant price meaning because, you know, we're traders.

If you re going to emphasize color, the UX should **emphasize** the colors of **prices** and price **change metrics**, not the basic UI functions.

**Comment by happyconcepts** [comment]
For example, even the list of nodes in the settings screen looks more like a financial exchange to me than the new dashboard look.

price change > node availability change and  yet somehow the UI now makes it easier for  developers to scan for nodes than it is for users to visually scan the screen for price changes. That doesn't seem right unless I want the price of bitshares to go down.

**Comment by ahdigital** [comment]
@happyconcepts 
It's great that you're engaged with the design of the UI. I haven't looked at the nodes page at all so please document your thoughts on #1223. 

In terms of the general colours etc.  this isn't the thread for it. Could I direct you to #1030 to add comments for future reference?

@diogogomes 

> How about the sub menu only fade out after click on item.

I'd love to see a working prototype of this. Part of the acceptance criteria should be that the content below the fading bar shouldn't jump up on show/hide.

> another thing that I dislike is transform the main navbar in a tab bar

I'm not sure what this means - maybe a picture would help.

> Why not use the blue of the logo that is used on bitshares.org too?

Between bitshares.org and the downloadable media kit `#35baeb`, `#00a9e0` and `#189fce` are used interchangeably. They're all quite similar so I picked one :) Post back on #1030 if you have a favourite.

**Comment by diogogomes** [comment]
@ahdigital 

> Between bitshares.org and the downloadable media kit #35baeb, #00a9e0 and #189fce are used interchangeably.

You're totally right, the media kit is not coherent and understandable of what is the main colour.

#  

> I'm not sure what this means - maybe a picture would help.

I'm referring to these tabs:
![navbar tabs](https://user-images.githubusercontent.com/9022734/36913290-551328a8-1e41-11e8-9be5-99a205940aa9.png)

One example for other decentralised exchange (that I consider a more modern and clean approach)
![other dex example](https://user-images.githubusercontent.com/9022734/36913328-7ad4c696-1e41-11e8-9cc9-86775c35dc7f.png)

**Maybe remove the horizontal borders?**

#  

> I'd love to see a working prototype of this. Part of the acceptance criteria should be that the content below the fading bar shouldn't jump up on show/hide.

It will be my pleasure.
I'll be waiting for an issue assigned to me to start.

**Comment by happyconcepts** [comment]
@ahdigital #1030 appears closed and you and diogo are doing just fine there without me.

Why do you even post these screenshots if feedback is immediately buried away into other closed issues? I feel like I wasted my time looking at your $375 of work.

**Comment by happyconcepts** [comment]
> If everyone can agree that this solution is suitable for the DEX we can create a issue for the implementation and testing of the feature.

I don't agree. I would like to, but I don't.

**Comment by diogogomes** [comment]
I agree with @happyconcepts on the two previous comments:

- We need discuss upon a Design Style Guide merged on a **docs/design** folder and not send the feedback for closed and not approved suggestions.

- I do not agree that this solution is suitable for the DEX and I'm sure that the community wants more radical changes on the evolution of the UI (ie: today I saw again comments about this on Telegram)

**Comment by ahdigital** [comment]
> I'm sure that the community wants more radical changes

So you don't agree because you think a hover state and border around the sub-nav items are the missing, is essentially what I'm getting from this.

Don't worry, I'll mock it up as part of this task so that you don't have to create another issue. It won't take long.

I'm continuing on with the navigation task and will be proposing wider reaching changes soon. The sitemap needs addressing also.

**Comment by diogogomes** [comment]
> So you don't agree because you think a hover state and border around the sub-nav items are the missing, is essentially what I'm getting from this.

No, I'm referring to all changes. Some examples from the community:

- _...my guess is if the BTS core is not able to make a friendly UI/UX then I don't see any possible rebranding coming._

- _Nevertheless there is a new worker proposal where new UI is included but I wonder if this time they will really perform._

- _So I'm not sure how I feel about the new interface...for the markets...I think it's a bit of a step back to be honest_

It's hard try to help if you want to do all the work alone.

**Please, listen the users opinions.**

**Comment by happyconcepts** [comment]
@wmbutler where is the discussion about navigation? That is my beef. It could be here on the issue on GitHub. It should be. 

And yet feedback is ignored by @ahdigital and now that ignorance becomes ratified by the project lead admonishing my attitude? Hello Bill?

**Comment by diogogomes** [comment]
@wmbutler I use the @ahdigital language

**Comment by wmbutler** [comment]
Just be respectful and constructive in your comments. Personally, I will ignore comments that don't follow respectful discourse.

**Comment by diogogomes** [comment]
I'm really confused, I read everything again and between me and ahdigital, the person that wasn't respectful was him...

**Comment by happyconcepts** [comment]
The UX is worse for me now in 2018 than it was in 2017. I am not talking about the social UX of trying to contribute here on github. I have done what I can to contribute by fixing minor bugs.

### This issue would seem to be the right place for discussion of the redesign of the User Interface Navigation.

So relatedly, a separate choice about using dark blue color for **every link** on the interface has apparently been made (issue #1030 is closed). I say relatedly because at the least the link colors clearly affect the UX of the navigation (when users cant even see it) and at most the link colors could be utilized to enhance the visibility (and usefulness) of the navigation.

Did I mention I am here to discuss navigation? I will say I am growing accustomed to the elitist attitudes in this repo, although it is not enjoyable.

**Comment by wmbutler** [comment]
I think @happyconcepts and @diogogomes should fork this repo and make it exactly the way you like it honestly.

**Comment by diogogomes** [comment]
@wmbutler I'm just trying to understand what I said wrong.

Sorry but I'll not continue discuss this here.
-- 
Diogo Gomes

**Comment by ahdigital** [comment]
I've amended the navigation patterns example that I posted originally.

It's uncessary to make user's to rely on a burger menu at desktop resolution. Ideally, the burger menu should display at lower resolutions where there's not enough space to display the uppermost menu.

Removing the burger menu at this resolution obviously raises the issue of how to display all those links in the top bar. So, I started looking at the current sitemap and explored the relationship between pages/tabs/modals etc. I've spent time grouping the pages into what I think is a more logical grouping for users to follow. As this wouldn't be an immediate update I've omitted beta/legacy links in the hope that these would be consolodated sooner.

![image](https://user-images.githubusercontent.com/3088454/37196966-bc47626c-2370-11e8-960f-74f602200a3f.png)

The idea behind 'accounts' is that via its child pages the user would be able to switch between their current account, their other accounts and 3rd party accounts. I'm trying to consolidate things so that we don't have several pages which offer similar functionality but of course this means some of the pages need to be designed/redesigned wherevever two pages have been brought together etc.

What this would look like within my amended navigation example is:

![navigation v2](https://user-images.githubusercontent.com/3088454/37196970-c1cdb1c8-2370-11e8-9158-947235ab12c6.png)

Following the feedback I played around with hover states for the sub-menu. It didn't really work when it was a horizontal bar for the reasons I mentioned but changing it to a vertical drop down style menu works nicely, and offers the benefit of being able to hold a greater number of links.

Within the visuals I added an example of notifications to show that the bar itself is extensible.

Here is a rough prototype (Not 100% like visual above or production ready code) to give a feel for it. It's more or less responsive so you can see the links stack as the viewport shrinks.

**Prototype:** https://jsfiddle.net/6j1o3cps/1/

**Comment by happyconcepts** [comment]
This is supposed to be a reference client i.e. a starting point to **encourage** others to fork other interfaces.

But instead of making the client:

1. loadable on windows
2. usable in other browsers beside chrome.
3. Usable in incognito modes.
4. making the node seek algo reliable
5. unit tests
6. etc ...

all I see is designers tweaking colors and generally fiddling while Rome burns. And I know because I have been the one cleaning up small bugs introduced by that lack of any tests.

It truly is a pity that I come here to make it a masterpiece, I speak openly and ask the tough questions,  and get told to fork off instead. The insult is that you are taking worker funds and paying yourself a hefty sum to not really accomplish much but lots of senseless commits.

How could you manage this project better?


@ahdigital @wmbutler

**Comment by happyconcepts** [comment]
I mean, other than telling me to fork off?

**Comment by diogogomes** [comment]
@ahdigital I really like this approach removing the secondary navigation bar.

**Comment by wmbutler** [comment]
@ahdigital this is the curse of having so much functionality :) Couple of thoughts:

- I like the menus better than the tabbed interface for sure
- Since the tabbed interface naturally inform the user about where they are, you will need a mechanism for conveying where the user is on each page
- I think the text in the burger should be right justified
- I think clicking the burger should activate a slide left on the page to reveal the menu as a "panel" hidden behind it.

Oh, no pressure. Rome is burning and it's all our fault. I can't believe what we've done singlehandedly to the crypto market futures.

**Comment by ahdigital** [comment]
They're some nice suggestions. How about this updated version for the navigation at mobile resolution, with the positioning you're describing and behavior like a drill down menu.

![navigation v3](https://user-images.githubusercontent.com/3088454/37334028-b629c07a-26a2-11e8-935f-d4e6a1c13a79.png)

**Comment by wmbutler** [comment]
Wish we could get rid of the notification bell, but I don't see how to avoid it. In the mobile header, I suppose we could put the badge in the burger, but that's pretty sloppy.

**Comment by ahdigital** [comment]
The notifications bell will prove to be very useful so should stay even for mobile. Many features could tie into it.

It'd be a great reference point to be able to see when you have newly proposed transactions, messages, recieved coins etc.
