### ISSUE TITLE
[.5] Send modal UI improvement

### ISSUE THREAD

**Issue by swoopyy** [bitshares/bitshares-ui#1217]
Change dropdown control to searchbar that is displayed inside the drop area currently.
![alt text](http://dl4.joxi.net/drive/2018/02/27/0023/2626/1538626/26/c8fb0b9284.jpg)

**Comment by wmbutler** [comment]
This is actually a width issue of the new typeahead component. @AustinAmoruso can you assist since you created the component?

**Comment by startailcoon** [comment]
# Fixed In PR #1221 

![bitshares-typeahead_input](https://user-images.githubusercontent.com/12114550/36754719-2561d6d8-1c0a-11e8-93af-a2d754742818.gif)

**Comment by wmbutler** [comment]
pretty slick!

**Comment by AustinAmoruso** [comment]
@wmbutler Sorry for the delay will work on this tomorrow to fix the width.
