### ISSUE TITLE
[.5][swoopyy] Allow wallet to connect to hidden nodes when none other are available

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1222]
The change that was made to allow nodes to be hidden is a great feature, but if none of the remaining nodes are responding, you will receive the error page where you need to select a new node.

From this stage you can't go to settings to change the available nodes to connect to, nor does the "reset settings" button fix anything related to nodes.

I encountered this issue when I had all nodes except the testnet nodes listed. And only way to get back to the main network was to connect to a testnet node and change settings. If this node had been down, I would not have been able to change my settings.

This can only be solved by
- connect to a node, change settings
- reset wallet settings manually

We should make the wallet able to connect to the selected node from the error page, by adding it to the list of visible nodes again, if it's hidden.

**Comment by wmbutler** [comment]
As I recall, the error screen on a failed connection is different from the settings screen. Shouldn't we just have a failed connection go straight to Settings -> Access instead?

**Comment by startailcoon** [comment]
Well, the failed page is solely to be able to select what new node you wish to try, and inform you that the node you had as selected didn't work. I don't really see why you should be redirected to the settings page.

**Comment by wmbutler** [comment]
Seems silly to have two separate pages to manage the same thing.

**Comment by swoopyy** [comment]
I can work on this
