### ISSUE TITLE
[1] Duplicate and Triplicate calls to OL

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1229]
We appear to be calling OL api servers frequently and in many cases without good reason. Note triplicate calls for a single route change.

![calls](https://user-images.githubusercontent.com/1254810/36797197-fe968284-1c6c-11e8-9770-06dd3581ad42.gif)

**Comment by svk31** [comment]
This is not a bug, and they're not being called for no good reason. They're called to check the available assets from the OL gateway, the status of which can change at any time so it's not that easy to cache these calls.

Either way these calls are completely non-blocking, nothing major waits for these calls to finish before rendering, and they're not taking up much processing power..

**Comment by wmbutler** [comment]
Why are they being called in triplicate?

**Comment by svk31** [comment]
They're not really, but now that Openledger has consolidated some of the calls I see the `coins` and `active-wallets` calls can be reused. I've added some memoization and caching of the values that should drastically cut down on the amount of calls being made. Cache TTL is set 30s right now, can be adjusted if necessary.

**Comment by wmbutler** [comment]
assigned 1 hour to your credit on this @svk31
