### ISSUE TITLE
[.25] Font size in exchange

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1234]
Is it possible to get these font sizes equalized? Looks like the order book is a bit smaller than the rest.

![screen shot 2018-02-28 at 5 01 00 pm](https://user-images.githubusercontent.com/1254810/36818101-3320a96c-1ca9-11e8-9af0-c3e030093d1b.png)

**Comment by ahdigital** [comment]
Add me please.

**Comment by ahdigital** [comment]
@wmbutler Check submitted PR for screenshot.
