### ISSUE TITLE
integrate chat via converse.js/XMPP

### ISSUE THREAD

**Issue by ihaywood3** [bitshares/bitshares-ui#1235]
If this sort of thing has been suggested before please accept my apologies.
It would be nice to have an integrated chat/messaging function in the UI, most fiat-world exchanges have this.
The main advantage is a (reasonable) certainty that user X on the chat controls the account of the same name,
An easy off-the-shelf solution would be an XMPP/Jabber server configured to grant accounts of the same name as BitShares users, on receipt of a signature proving they control that accounts' memo key.
The UI can then use [converse.js](https://conversejs.org/) to provide a popup "chat screen", users would be free to use any XMPP client of course.
I'm happy to run the XMPP server and write a BitShares-specific authentication module. However I would need some guidance on how to integrate into the UI (and more importantly, some indication that such work would be accepted)

**Comment by wmbutler** [comment]
Third party js is a security risk to users.
