### ISSUE TITLE
Must I create a new account in order to import backup?

### ISSUE THREAD

**Issue by nmywn** [bitshares/bitshares-ui#124]
I know answer to this question.
Wallet mode user after cookie clean up will see this:

![create_account](https://cloud.githubusercontent.com/assets/18205812/25491670/f536b9b8-2b70-11e7-9ae2-cf096b8ef5cc.png)

In order to import backup he must click "Create account" button, which lead to login type selection, then, if lucky enough...

![login_selection](https://cloud.githubusercontent.com/assets/18205812/25491342/00301766-2b70-11e7-8c19-71d0e1b96af8.png)

 ...to "Create Wallet" page where he have some chance to spot what he want.

![a1](https://cloud.githubusercontent.com/assets/18205812/25307471/c3d2bc78-27a1-11e7-8274-82419d2b3b4e.png)

Thats not easy. 
It should be done with one hoop from Welcome page to Restore page:

![a1](https://cloud.githubusercontent.com/assets/18205812/25307567/5ad28116-27a3-11e7-88e4-046daa4afc32.png)

**Comment by wmbutler** [comment]
I can UX this. Agreed that the user should be able to restore without going through the account creation process.

**Comment by wmbutler** [comment]
Resolved with #258. There is now a restore feature in the lower left corner.
