### ISSUE TITLE
[3] Cleaning up Backend API calls to outside gateways and bridges

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1244]
As partially discussed in issue #1228, but not related to the cause of the issue.

## Issue
The app calls on gateway and bridge issuers on different places, and sometimes on multiple and redundant positions.

One example is in `app/components/Account/BalanceWrapper.jsx` where we are calling on `GatewayActions.fetchCoins();` and `GatewayActions.fetchBridgeCoins();`, both for no reason what I can see.

The required data is already fetched in AccountPage.jsx from the GatewayStore

https://github.com/bitshares/bitshares-ui/blob/4c9ddbe7cc49c29be50308f7b9a4c1f8d537a1f4/app/components/Account/AccountPage.jsx#L117-L119

The GatewayStore uses GatewayAction to do this already.

## Proposed Work

The above issue example is only one place that needs to be looked at, and I'm sure there are a few more to attend.

I propose an issue for working on cleaning up and verify that no more than the required calls are done from the app to our outside gateways and bridges.

**Comment by startailcoon** [comment]
This would also be related to bridge assets since it's populated in GatewayStore on https://github.com/bitshares/bitshares-ui/blob/4c9ddbe7cc49c29be50308f7b9a4c1f8d537a1f4/app/stores/GatewayStore.js#L13

**Comment by svk31** [comment]
Those calls in AccountPage aren't fetching anything, they're just getting the state data from the store, because that data is used in the component.

**Comment by startailcoon** [comment]
Based on your comment @svk, do you think this is unnecessary work or is a oversight of how calls are made something that should be done? 

One example is that the new Typeahead does something that usually is passed on to it by the caller.

**Comment by svk31** [comment]
I think a general cleanup and optimization of API calls would be useful. There's also potential for caching calls like what I did recently in GatewayActions and BlocktradesMethods.

I've noticed the calls in BalanceWrapper as well and been tempted to remove them, I'll take another look to see if they're really necessary.

**Comment by startailcoon** [comment]
This task will be part of #1275 and #1276, as they are currently not included in the GatewayStore() functions. The providers have built their own functions part of AccountDepositWindraw.jsx

**Comment by startailcoon** [comment]
### Question
The issue are facing today is that previously (most) backed assets where updated and stored when the user navigated to the Deposit/Withdraw page. This page stores the data in `GatewayStorage()` which can later be fetched in other sections of the app.

Today we're moving away from that page with the new Modal structure, thus facing two issues
1. Backed assets aren't updated as the user are no longer navigating to the old Deposit/Withdraw page.
2. Moving the call to the Dashboard, where the data is used now, would face an increased amount of web calls to the APIs, as the dashboard aren't specifically used for just this task.

### Solution
We move the API calls to the Dasboard, but we should most likely add a timer to this to limit the amount of calls. A checker to see if the data is older than 1-5 minutes could do, but we would not have a live view of this then. I'm not sure if this would pose a problem, or if we should just go with updating all the time.

For the moment we would call: OpenLedger, RuDEX, BlockTrades, GDEX and Winex.

Since we need to fetch the backers coins for the Dashboard view to be able to populate the Deposit/Withdraw logic, this is most likely the only way we can do it.

**Comment by wmbutler** [comment]
I need some help understanding the purpose of updating backed assets. What information are we receiving that must be acted upon? Thanks for helping me understand this.

**Comment by startailcoon** [comment]
For implementing GDEX and Winex, for example.

With backed coins I mean the coins called WIN.xxx or GDEX.xxx for example.

Maybe that wasn't clear in my previous statement.

**Comment by wmbutler** [comment]
Seems like we should just call all of them once when we load the client and then only call them when the deposit/withdraw legacy and new endpoints are called subsequently. I don't see why we should call them outside of those situations.

**Comment by startailcoon** [comment]
Yeah, good point. 

1. Call Backers API when the app loads, and store in cache
2. Update cache when Withdraw/Deposit/Buy modals are loaded to make sure we can do the requested action.

I will work from this perspective onwards and find a good solution.
Hopefully we'll have less unessesary calls and a more unified way for the new gateways that where added recently, that aren't stored in the GatewayStorage today.

**Comment by startailcoon** [comment]
As discussed in the chat, I will work towards the following for #1275

We should have a standard way of allowing gateways in, while they themselves maintain them. What we do now is put the current ones in a way that we decided to move to, but could be risky for us since we work with outside APIs. I will continue working towards finding a unison way of adding new ones.

As long as they all use roughly the same base they could just use a simple configuration file with their settings and be done with it.

**Comment by startailcoon** [comment]
This issue is now completed as GatewayAction calls are now made in App.jsx on start. The rest of the application now uses the cache from `GatewayStore.getState().backedCoins`

To update the gateway status you should now call `updateGatewayBackers()` 
https://github.com/bitshares/bitshares-ui/blob/05378b219bd0cf957f2c4b43ab4b392869b02c9e/app/lib/common/gatewayUtils.js#L53
