### ISSUE TITLE
NaN for very small numbers

### ISSUE THREAD

**Issue by JianJolly** [bitshares/bitshares-ui#125]
![1](https://cloud.githubusercontent.com/assets/19493352/25309130/558e79c4-27cd-11e7-910b-f8a819838c72.png)

The open.LTC balance is 0.00000055. The "balance" field reads "NaN".

**Comment by svk31** [comment]
This was fixed in a previous commit, the reason was a regression in the package 'numeral' that's used to format numbers.

**Comment by landry314** [comment]
I found this same issue in the CNY Margin window under Collateral on the May 22 release for Mac OS. I was about to create an issue for it but I am not sure if it has been fixed in the meantime.

**Comment by wmbutler** [comment]
The latest light wallets are out. Can you check it and close this if it's fixed @landry314 ?
