### ISSUE TITLE
Portfolio Visual Presentation

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1257]
I worry about new visual presentation of portfolio. Maybe it's a bug but it looks like a ~big~ huge blue mistake for entire screen:

<img width="1401" alt="screenshot 2018-03-04 17 29 57" src="https://user-images.githubusercontent.com/35899973/36947838-bdcfe94e-1fd1-11e8-84e0-503738b5e2d2.png">

**Comment by ahdigital** [comment]
Colours need a review also. It should be possible in highcharts to specify an array of colours, Bitshares friendly.

**Comment by svk31** [comment]
The missing legends is a Highcharts issue, it seems the old Highcharts version is cached in the build servers which causes this. In the develop build it's fine as long as you wipe the old highcharts then reinstall

**Comment by gibbsfromncis** [comment]
@svk31 the issue not only on missing titles. There are wrong colors and their tints also. Maybe with titles it looks better but now it's just like a big blue block on the page with no sense. 

@wmbutler what about to add an ability to see Visual Presentation like a pie-chart too? All work is done - highcharts already included to project, all data collected. It's just 1 hour to add pie chart and some switch between treemap and piechart.

**Comment by wmbutler** [comment]
Honestly, I had wasting dollars on this. It's so trivial.

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/36982975-7e5cf426-2091-11e8-905e-0efb448c5e81.png)

This is what it looks like locally for me. The colors could certainly be improved, right now it loops over preset default HighCharts colors, but those don't always give good results for some reason.

**Comment by diogogomes** [comment]
> Honestly, I had wasting dollars on this. It's so trivial.

I suggest this issue continue as "Proposed Feature" and if possible, remove this interface from the client until we reach a consensus on good design.

@wmbuttler, as you consider trivial and loss of money, for me, I can go on presenting simple mockups without allocated hours.

I leave the invitation to @gibbsfromncis, @ahdigital, @svk31, and other interested people to do the same. This is a really interesting visual feature to our users but needs planning until be deployed.

Once we reach a consensus, the people designated to refine the design and to code will have allocated hours.

Once again, I think a visualisation of the portfolio is a really interesting visual feature to our users and I would also add a performance view of portfolio based on the activity of the user.

**Comment by wmbutler** [comment]
Needs UX before the next attempt. placed in 180415
