### ISSUE TITLE
Add OPEN.SBD to default markets

### ISSUE THREAD

**Issue by nmywn** [bitshares/bitshares-ui#126]
Due to USDT issues, SBD volume on Poloniex is raising ($1.8kk last 24h).

* bitUSD:OPEN.SBD => poloniex.SBD => poloniex.BTC is fast and could encourage borrowing.
* It is super easy to make bitUSD:OPEN.SBD market.
* It could be preferred way of moving value between Steem and DEX.

Currently:
* It is imposiblle to deposit SBD in Openledger's "basic mode"
* It is imposiblle to spot that market because it's hidden.

**Comment by grctest** [comment]
Shouldn't EBA tokens all be default market pairs? OPEN.GRC also doesn't show unless you go through 'Find Markets'.

**Comment by svk31** [comment]
Both of those are naturally low volume assets, but I'll add them to the default list of assets in the exchange.

**Comment by nmywn** [comment]
Thank you very much. Coins not present on that list are not available to deposit on Openledger's basic mode. So SBD and GRC will show if they merge your update, but rest remain hidden. This make no sense for me. I'm not sure if this is their choice  or just lack of attention. Any market making attempt will be failure on those markets - nobody will notice.
