### ISSUE TITLE
[.25][gibbsfromncis] After choosing an account from the dropdown, hide the dropdown

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1265]
Currently, a user must "off-click" in order to hide the dropdown.

![dropdown](https://user-images.githubusercontent.com/1254810/37014553-1565fb4e-20c7-11e8-8f51-33e22ab5ada8.gif)

**Comment by gibbsfromncis** [comment]
@wmbutler I'll work on this one

**Comment by gibbsfromncis** [comment]
PR: #1311
