### ISSUE TITLE
[.5] Withdraw (beta) bug for STEEM via RUDEX

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1268]
- [x] Memo field can be omitted
- [x] Resulting transaction must end up looking like this where to contains `rudex-steem` and memo contains `steem:<targetsteemaccount>`

Included time to test

<img width="641" alt="screen shot 2018-03-05 at 11 42 31 pm" src="https://user-images.githubusercontent.com/1254810/37015882-46562a0a-20cf-11e8-8fd7-d14ce8020734.png">

**Comment by calvinfroedge** [comment]
Resolved by #1267
