### ISSUE TITLE
Winex withdraw infinite loading

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1270]
@MannyMeadows reported in https://github.com/bitshares/bitshares-core/issues/699:
>I found an issue with the [withdraw window](https://wallet.bitshares.org/#/deposit-withdraw)...selecting Winex as the transfer gateway results in infinite loading. Since this was an accident and I meant to select OpenLedger, I had a workaround to withdraw via [OpenLedger](https://bitshares.openledger.info/deposit-withdraw/). However the [withdraw window](https://wallet.bitshares.org/#/deposit-withdraw) still remains on Winex infinite loading.

**Comment by diogogomes** [comment]
I also received this issue on Discord (I can't confirm if the user is the same that said will report here).

After testing on linux desktop client, I confirm the infinite loop and it's not possible select OpenLedger.

The workaround for me was select other section outside withdraw module and select withdraw again (example: click on dashboard and click on withdraw again)

**Comment by wmbutler** [comment]
I'm not able to reproduce this infiniteloading issue.

**Comment by MannyMeadows** [comment]
It's back in action. It seemed to be isolated to Winex only. I'll direct any future issues to Winex support.
Cheers.

**Comment by diogogomes** [comment]
@wmbutler, @MannyMeadows 

Sorry, I didn't mention my version of linux desktop client.

I don't have this issue after update to version 2.0.180306

**Comment by wmbutler** [comment]
Great @MannyMeadows ask them to submit a PR to fix this. Also, I have another issue to get their API integrated into the new withdraw modal #898

**Comment by abitmore** [comment]
Or remove them temporarily before it's fixed.

**Comment by wmbutler** [comment]
@MannyMeadows did you get a response from their team on this issue?

**Comment by wmbutler** [comment]
@MannyMeadows are you planning to address this?

**Comment by abitmore** [comment]
I'll contact their team.

**Comment by startailcoon** [comment]
@abitmore @MannyMeadows is this issue stil present?

**Comment by MannyMeadows** [comment]
I haven't had this issue again since.
