### ISSUE TITLE
[1] As a user I would like to be able to filter my active and inactive portfolio assets

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1271]
The filter should go to the left of `active | hidden | visual`. There is already a design pattern for this in other areas, so please follow it if you claim this issue.

![screen shot 2018-03-06 at 9 03 54 am](https://user-images.githubusercontent.com/1254810/37039645-99a4dce4-211d-11e8-882a-b4f8ddfe9419.png)

**Comment by fractalnode** [comment]
or maybe favorite? in this way, each new token is not on the favorites list..
and maybe also to filter tokens by their value - hide less than 1 USD worth (user defined value)

**Comment by wmbutler** [comment]
@fractalnode feel free to open a separate issue for that.

**Comment by gibbsfromncis** [comment]
PR: #1316
