### ISSUE TITLE
[1] Desktop and Web client (Linux, Mac, Windows) is not loading the content

### ISSUE THREAD

**Issue by diogogomes** [bitshares/bitshares-ui#1272]
**Version:** 2.0.180306 (desktop and web client)

**OS:**
- Xubuntu 16.04 (desktop and web client using Chromium 64.0.3282.167)
- Debian (desktop client)
- macOS Sierra (desktop client)
- Windows 10 (web client running on Opera browser 51.0.2830.40)
- OS unknown (web client running on Chrome and Firefox)

---

## Linux

**After the update linux version do not loads the content until reload the application inside the Electron window.** It's happening too on **web client using Chromium**

![linux desktop client 2 0 180306 not loading content](https://user-images.githubusercontent.com/9022734/37071983-2ab5da14-21b7-11e8-99ea-cdb4679a1821.png)

**After the reload and clicking on Dashboard** (the only option that works is the Send modal)

![linux desktop client 2 0 180306 - after reload and clicking on dashboard](https://user-images.githubusercontent.com/9022734/37072250-5ccfd5e4-21b8-11e8-92bf-f47295108688.png)

**The issue continues after cleaning all offline data**

---

## Mac

It was been reported on Telegram that after the update, **macOS Sierra version hangs clicking on Exchange button**, maybe the same problem. Other user said that it works on macOS High Sierra.

_macOS Sierra user:_
- The exchange button doesn’t work
- Using Apple Mac, downloaded the new update
- It is a desktop client...
- It is the Mac sierra
- No nothing works, no buttons open
- Constantly freezes

_macOS High Sierra user:_
- I am using Mac High Sierra having no issues

---

## Windows

It was been reported on Discord that **the same issue is happening on Windows 10 using wallet.bitshares.org with Opera** browser 51.0.2830.40

_Windows 10 user_
- It seems not working properly.

![2018-03-07](https://user-images.githubusercontent.com/9022734/37108992-aac25b82-2230-11e8-8fb8-e50132574531.png)

![2018-03-07](https://user-images.githubusercontent.com/9022734/37122110-201573ee-2257-11e8-8a05-b3c72f64791d.png)

---

## OS unknown

It was been reported on Telegram that **the same issue is happening on Chrome and Firefox** browsers. I didn't get an answer about the OS.

_Chrome and Firefox user_
- ...Can't get to my assets
- Chrome and firefox..

---

##### 2018 Mar 07:
- Added new information about web client with Opera running on Windows 10
- Added new information about web client with Chrome and Firefox

##### 2018 Mar 08
- Added result after cleaning offline data on Linux
- Added new information about web client with Chromium on Xubuntu 16.04
- Added desktop client on Debian

**Comment by diogogomes** [comment]
@wmbutler, it's possible that this bug might be high priority because it seems to happen to multiple users cross platform.

I can provide more debug information (on Linux version). Let me know what you need.

**Comment by svk31** [comment]
We've had this bug before and fixed it, not sure why it's back. It's related to the inital opening of the database that stores the key, aka the wallet. It used to be caused by a redirect happening to the "#" on app initialisation, could be same thing now.

**Comment by diogogomes** [comment]
Added new information about web client with Chrome and Firefox and console error on Opera.

**Comment by wmbutler** [comment]
@diogogomes try opening with Chrome incognito to see it the problem is related to cached elements in your browser. I'm not having any issues on Mac OS web wallet or Desktop wallet, high sierra.

**Comment by BazkieBumpercar** [comment]
Same here, Debian user. Switched back to 180302 and now it works again

**Comment by diogogomes** [comment]
@wmbutler, I cleaned all my offline data of desktop client and I continue with the same errors.

**Comment by rokii666** [comment]
Have this on High Sierra, Bitshares.180306
Buttons do not work

**Comment by svk31** [comment]
I'm unable to fix the root cause but I've put in place some workarounds that have fixed the issue as far as I can tell.

**Comment by diogogomes** [comment]
@svk31,

Navigation seems more slowly than previous versions (100Mbps web connection) but **is everything working**. Thank you

**Comment by wmbutler** [comment]
Strange. It's faster than ever for me.

**Comment by diogogomes** [comment]
@wmbutler Can be related with my node connection (I'm connected from Portugal to Germany, my closest node).

I will inform you if this situation persists with less latency.

**Comment by wmbutler** [comment]
Please do. We've solved so many extraneous calls. I still do have node disconnects but we have an active issue working towards holding onto the socket better.

**Comment by rokii666** [comment]
How to solve on Mac?
