### ISSUE TITLE
[5] Withdraw/Deposit Modal - Add Winex Support

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1275]

**Comment by startailcoon** [comment]
I'll take this

**Comment by wmbutler** [comment]
Can you work this for the current Sprint?

**Comment by startailcoon** [comment]
I plan on having this done for 180415. Sorry for the delay and missed target.

**Comment by startailcoon** [comment]
PR Submitted to include Winex Support in Deposit/Withdraw Modal.
