### ISSUE TITLE
[5] Deposit/Withdraw Modal - Add GDEX Support

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1276]

**Comment by startailcoon** [comment]
I'll take this

**Comment by startailcoon** [comment]
Extended this issue to include Deposit as well.

GDEX will require some work since their API isn't sending the data back as the others are. Their JSON structure will have to be compiled to something that we commonly use for the other backers.

**Comment by wmbutler** [comment]
Let's reach out to @mindphlux1 and see if he would consider an API that matches the one others are using first.

Would you consider making your API (possibly an additional version of it) match the API for the other gateway providers?

```
{  
   "coinType":"bts",
   "walletName":"BitShares 2.0",
   "name":"BitShares",
   "symbol":"BTS",
   "walletSymbol":"BTS",
   "walletType":"bitshares2",
   "transactionFee":"0.",
   "precision":"100000.",
   "backingCoinType":null,
   "supportsOutputMemos":true,
   "restricted":false,
   "authorized":null,
   "notAuthorizedReasons":null,
   "gateFee":0,
   "intermediateAccount":"openledger-wallet",
   "coinPriora":0
}
```

**Comment by wmbutler** [comment]
Waiting for GDEX response.

**Comment by abitmore** [comment]
I'll help contact GDEX.

**Comment by startailcoon** [comment]
As a follow-up on what GDEX is doing today.

Today GDEX handles returned data from their APIs with the following code, that transforms it into an array like the following. This does not comply with how we handle gateway assets otherwise.


https://github.com/bitshares/bitshares-ui/blob/7a2420f858ed83a1e26bee734f0f7dee0b25af49/app/components/DepositWithdraw/gdex/GdexGateway.jsx#L76 

```
{
  "innerAssetId": 1002,
  "innerAssetName": "GDEX.BTC",
  "innerSymbol": "GDEX.BTC",
  "outerAssetId": 1001,
  "outerAssetName": "bitcoin",
  "outerSymbol": "BTC",
  "status": 0,
  "gateFee": 0,
  "needMemo": 0,
  "minTransactionAmount": 1e-8,
  "type": 2,
  "relationPrecision": 8
}
```

**Comment by tianyekuo** [comment]
We will look into it. I notice there are 3 APIs: coins, trading-paires, active-wallet. Are they all necessery?
@startailcoon

**Comment by wmbutler** [comment]
I think all we are missing is intermediateAccount. It's possible this could be hardcoded to whatever value crypto-bridge uses.

**Comment by tianyekuo** [comment]
intermediateAccount is crypto in anthor API. 
Just add intermediateAccount in the asset list(coins) api for show , is that ok?

**Comment by startailcoon** [comment]
There are a few different ways we do the connections for backed coins. Let me compile a list for you what we need for each.

**Comment by startailcoon** [comment]
I've looked through the function of GDEX today, and it's quite different approach from what the other gateways uses. Both in fetching assets and linking the backing wallet and asset.

It's not impossible to make this work together with the new modal, together with the other gateways.

- Either we build a new function that handles the GDEX way but will require some additional code.
- Or GDEX applies the way the wallet works with now.

I'm compiling a document explaining the current system that the gateways uses, which I will submit in a few days when I've gotten everything correct.

I recommend we look over a possible merge after this.

**Comment by wmbutler** [comment]
Maybe we just close this and don't include GDEX on the reference wallet since they aren't expressing interest in being part of the discsussion.

**Comment by tianyekuo** [comment]
Sorry for late response, since the APIs do not work with other gateways, we will make a new set of APIs.

Implement the 3 APIs coins, trading-paires, active-wallet is all we need? @startailcoon @wmbutler

**Comment by tianyekuo** [comment]
If gdex want to catch up the milestone [21](https://github.com/bitshares/bitshares-ui/milestone/21), could you give some help, thanks!

**Comment by tianyekuo** [comment]
Thanks you, I will wait for your good news.

**Comment by startailcoon** [comment]
Moving this to the next milestone as it's quite a challenge to make sure this works.

**Comment by wmbutler** [comment]
We pushed the release to 4/18. Any chance you can get this in prior to release? @tianyekuo

**Comment by startailcoon** [comment]
I think it's to little time and I have yet no response from @tianyekuo as well as a very busy schedule at the moment.

I do not want to rush this, nor take a task I can't complete.

I'm happy to do the task though.

**Comment by tianyekuo** [comment]
Our APIs will adjust as the document required, we try to finish it early next week.  The next milestone(5/1) is better. Would that be OK with you guys.

**Comment by startailcoon** [comment]
Great news 👍

**Comment by wmbutler** [comment]
@startailcoon great work. Really appreciate you going the extra mile on this.

**Comment by tianyekuo** [comment]
@startailcoon , thanks for your great work, the document makes the integration better.

**Comment by startailcoon** [comment]
Forked update for BitShares UI with GDEX Gateway support is now available at https://github.com/bitshares/bitshares-ui/tree/1276_GDEXGateway

### This should be checked and signed of by the GDEX team before merging.

![bitshares-gdex](https://user-images.githubusercontent.com/12114550/39398311-2953d1ca-4b0c-11e8-89f1-b913dbe1eba9.gif)

**Comment by wmbutler** [comment]
@tianyekuo

**Comment by tianyekuo** [comment]
That's great, please help to release it, thanks!
