### ISSUE TITLE
[4] Withdraw Modal - Respect maxAmount / minAmount

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1277]
/coins endpoint to respective gateway service. Variable per asset.

```
maxAmount : "9999999.0000"
minAmount : "0.1000"
```

**Comment by startailcoon** [comment]
I'll take this

**Comment by startailcoon** [comment]
As I can see the gateways are not restricting any deposit amounts. They do have a minimum amount as OpenLedger has `gateFee*2` and RuDEX has `minAmount`.

I will implement a minimum amount warning on a Withdraw depending on your gateway choice.

**Comment by startailcoon** [comment]
![bitshares-disableonmindepositlimit](https://user-images.githubusercontent.com/12114550/37252275-c4546a4a-251e-11e8-84e0-e403ead3bc65.gif)

**Comment by wmbutler** [comment]
Maybe replace the `Available` message with the Minimum withdraw warning.

**Comment by startailcoon** [comment]
Not sure if that's a good choice. How will the user
1. Be able to know their account holdings so they don't try to withdraw more than they have
2. Withdraw their full amount, as the message is click able to fill in the total amount.

**Comment by wmbutler** [comment]
I just hate throwing in error messages in random places. Feels sloppy. We could put it as placeholder text in the qty...

```
Min 0.2, Max 2000
```

**Comment by svk31** [comment]
I don't really like the current positioning, looked better in your above screenshot. Also, it's always visible, no matter if the amount you entered is above or not, shouldn't it go away?

![image](https://user-images.githubusercontent.com/6890015/37330286-e1346830-26a0-11e8-9539-ae1c10885cfe.png)

**Comment by startailcoon** [comment]
@wmbutler sounds good imho. Let's do it as a placeholder as well. What if the user inputs a low amount, where do want the message to be? Do we want it to be where it is in my screenshot, but only if its to low? 

@svk31 strange that it's not right for you.

**Comment by startailcoon** [comment]
Better with a placeholder?

Should I put the error back when the user is below the min amount?

![image](https://user-images.githubusercontent.com/12114550/37367279-3a9e93fc-2703-11e8-8a8a-bd58725394fd.png)

**Comment by wmbutler** [comment]
I like it!!

**Comment by startailcoon** [comment]
It used to be just a massive red text between Quantity and Withdraw to address, that honestly wasn't a nice place.

I put it with the other just to have it in a better place, but I guess we can just get rid of it all together since we have the red quantity highlighting it.

**Comment by svk31** [comment]
I merged this now but it still looks like this to me:

![image](https://user-images.githubusercontent.com/6890015/37396591-a13d2ba2-2779-11e8-86f7-77b40c5acdfc.png)


I'll try to fix it so it looks like your licecap.

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/37396939-a462c19c-277a-11e8-8c30-0691118b8727.png)

![image](https://user-images.githubusercontent.com/6890015/37396955-aec28474-277a-11e8-8315-f1d2f2bd87ba.png)

**Comment by startailcoon** [comment]
Strange, I think I did use staging branch to go from, but something must have been missed. Thanks for the fix
