### ISSUE TITLE
Deposit/Withdraw options not fully populated?

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-ui#128]
_From @grctest on April 30, 2017 19:18_

Hey,

Is anyone else seeing the following difference between openledger and the bitshares light client?

We're unable to deposit GRC onto the light client as a result. Is this something that openledger will have to fix?

![image](https://cloud.githubusercontent.com/assets/15861527/25567275/0d12a0b0-2de2-11e7-8f2d-5d650cbfea79.png)

Cheers.

_Copied from original issue: bitshares/bitshares-core#268_

**Comment by vikramrajkumar** [comment]
_From @abitmore on April 30, 2017 19:29_

Please post to https://github.com/bitshares/bitshares-ui/issues

**Comment by grctest** [comment]
It's now showing on the Bitshares light client, was this an Openledger issue rather than a UI issue?

**Comment by svk31** [comment]
There's filtering happen depending on what coins are currently available via the gateway. If the gateway is having issues with the wallet of a particular coin it will disappear from this list.
