### ISSUE TITLE
How does WalletUnlockActions work?

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1283]
I want to react on a unlock modal got canceled. Consider following code
```
import WalletUnlockActions from "../../actions/WalletUnlockActions";
try {
    console.log("requesting unlocking");
    WalletUnlockActions.unlock().then(()=>{
        console.log("unlocked");
    }).catch((err)=>{
        console.log("errored");
    }).finally(()=>{
        console.log("finally");
    });
} catch (err) {
    console.log("errored");
}
```
I execute and click cancel on the modal, I only have in the console
![image](https://user-images.githubusercontent.com/33128181/37198958-4fec4028-2380-11e8-980d-2423d97ce233.png)

I execute and unlock successfully
![image](https://user-images.githubusercontent.com/33128181/37199036-a764ef12-2380-11e8-9a11-f7e67f843302.png)

What am I doing wrong? Shouldn't finally be _always_ executed? How can I react on modal got cancelled?

**Comment by sschiessl-bcp** [comment]
Thanks to @gibbsfromncis for his commit addressing the core issue.

**Comment by sschiessl-bcp** [comment]
Resolved with https://github.com/bitshares/bitshares-ui/pull/1347

**Comment by wmbutler** [comment]
@gibbsfromncis do you need to credit for this?

**Comment by gibbsfromncis** [comment]
@wmbutler nope, thx.
