### ISSUE TITLE
[1.25] Deposit Modal - Autoselect Gateway when available is 1

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1289]
There is broken logic since a previous update that makes the Deposit Modal not auto select the available gateway when there is only one available.

This was the case before, and should be the case.

# LiceCap
![bitshares-depositselectgateway](https://user-images.githubusercontent.com/12114550/37241252-8093bc52-2456-11e8-9639-e4a675f430f1.gif)

**Comment by wmbutler** [comment]
@calvinfroedge I'd amend this slightly. Your PR states that it autoselects the gateway from the largest balance if there are multiple. I think it's more prudent to display:

Select Gateway...

Then the user can choos which gateway to extract funds from. If there is only one gateway with funds, then you would auto-select.

**Comment by calvinfroedge** [comment]
@wmbutler Since the withdrawal modal is auto selecting the largest balance (which usually just means above 0 balance), I think what's best here is to let the deposit modal pass an alternative callback function to decide which gateway it wants. Updating this now.

**Comment by calvinfroedge** [comment]
PR Updated...shared gateway selection code can now accept an override function...gateway will be auto selected in deposit modal if there is exactly 1 choice, otherwise user will need to select.
