### ISSUE TITLE
[4] Request: Direct link from account history transaction to transaction details within block

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1292]
![image](https://user-images.githubusercontent.com/15861527/37246179-639779a4-249c-11e8-9a0e-68c6721abad0.png)

Currently, when you click the transaction type label, it takes you to the top of the block contents.

Would it be possible to skip down to the relevant transaction, so as to speed up finding the data (instead of ctrl+f 'username')?

Cheers 👍 

edit:
Do you think it'd be better to have the block/transaction link in text 'blocknumber|tx_id' as the hyperlink, instead of the asset type label being a somewhat hidden hyperlink?

**Comment by startailcoon** [comment]
This would be very handy.

I looked at this a little and came as close as to get the link from the account history page to contain the TX ID, ie `1.11.xxx`, but on the block details page I wasn't able to find how to fetch it again to put an anchor on the place of the TX.

I didn't put that much in to searching about this, but if anchors works, this would be a nice addition as you would also be able to make links like `https://wallet.bitshares.org/#/block/25131936#1.11.1234`

**Comment by gibbsfromncis** [comment]
@wmbutler looks like there is no way to delivery solution for now. Unfortunately block's operations don't have an id as @startailcoon said. I've tried to investigate but in result in 3 hours of my investigation I was reading Graphene sources and I said stop  😄

**Comment by grctest** [comment]
> Unfortunately block's operations don't have an id as @startailcoon said.

Every network operation [has an id on the blockchain](http://docs.bitshares.org/development/blockchain/objects.html), though this info is missing in the block page UI for some of the operations indeed. Would this require changes to [bitsharesjs](https://github.com/bitshares/bitsharesjs) to acquire these op IDs?

**Comment by abitmore** [comment]
@gibbsfromncis it's as easy as this: a history object has a block number and a transaction sequence number and an operation sequence number, so we can use them to locate the operation in a block.

**Comment by wmbutler** [comment]
I increase the hours on this and advanced it to 180401

**Comment by gibbsfromncis** [comment]
It looks like not so easy task. But if somebody want to take it I'm OK - just let me know. If not - I'll find some free time to work on it

**Comment by startailcoon** [comment]
I've been fiddling with this as well. We can coordinate some efforts together on this. 
I will let you know if/when I take a look at this @gibbsfromncis

**Comment by gibbsfromncis** [comment]
@startailcoon I've already done part of scroll. I only need to add "id=transaction_id" to block with operation.

**Comment by startailcoon** [comment]
If you have a fork that I can use, let me know.

**Comment by gibbsfromncis** [comment]
@startailcoon I'll create branch and do push today/tomorrow

**Comment by startailcoon** [comment]
No rush.

**Comment by clockworkgr** [comment]
@startailcoon Still haven't got it working either so I'm not gonna do a PR but left you a comment to fix the undefined error.

**Comment by clockworkgr** [comment]
@startailcoon  done @ https://github.com/bitshares/bitshares-ui/pull/1573

**Comment by startailcoon** [comment]
Thanks to @clockworkgr with some final touches, we now have a working auto scroller.

## Preview
![bitshares-autoscroll](https://user-images.githubusercontent.com/12114550/41019331-6c78673e-695e-11e8-9f9a-7300d54bd10f.gif)
