### ISSUE TITLE
Feepool no longer loads on asset overview

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1305]
On my browser it doesnt show the fee pool anymore

![image](https://user-images.githubusercontent.com/33128181/37270980-3d044098-25d1-11e8-9163-f09a7bf2d04b.png)

Common issue or just me?

**Comment by startailcoon** [comment]
Work for me on the latest release build as well as on staging branch. Must be an issue with your connected node.

**Comment by sschiessl-bcp** [comment]
Could you provide which node you are connected to?

I tried several, did not work on any. Attempted with chromium and firefox, latest version, no error in logs.

**Comment by svk31** [comment]
You're most likely missing something related to this commit: https://github.com/bitshares/bitshares-ui/commit/ec521aa9031c2a0a988f8edcccea666d8e7b5aaa#diff-92c45f254db82073dcae1e0b1b26322e

You need to update bitsharesjs for the fee pool to display after this.
