### ISSUE TITLE
Present market fee to users more prominently

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-ui#1306]
With respect to this:
https://bitsharestalk.org/index.php?topic=26083.msg316307;topicseen#new

I request that the upcoming market fee is presented to trades more prominently than only on the asset page.

http://docs.bitshares.org/user/assets-faq.html#what-if-two-different-market-fees-are-involved-in-a-trade

**Comment by abitmore** [comment]
There is already a market fee field in the market page.
![image](https://user-images.githubusercontent.com/9946777/37295420-70546b02-2618-11e8-92fd-74f8a7287acb.png)

**Comment by wmbutler** [comment]
Can you be more specific @xeroc
