### ISSUE TITLE
[1][mattbeckman] Asset description missing on asset page & console log locale warnings?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1319]
The [Hertz asset page](https://wallet.bitshares.org/#/asset/HERTZ) within the BTS web wallet isn't loading the asset's description & it's showing the following error in the console:

```
app.js:11 missing path 'assets/HERTZ' for locale 'en' help files, rolling back to alt_path 'assets/Asset'
```

Edit: Description isn't shown on bitUSD/bitCNY pages neither, was this section removed? Only visible within the tooltip in the market?

More cases:
```
missing path 'assets/XCD' for locale 'en' help files, rolling back to alt_path 'assets/Asset'
app.js:11:300320
missing path 'assets/ALTCAP.XDR' for locale 'en' help files, rolling back to alt_path 'assets/Asset'
app.js:11:300320
app.js:11 missing path 'assets/CNY' for locale 'en' help files, rolling back to alt_path 'assets/Asset'
missing path 'assets/JPY' for locale 'en' help files, rolling back to alt_path 'assets/Asset'
app.js:11 missing path 'assets/RUBLE' for locale 'en' help files, rolling back to alt_path 'assets/Asset'
```

The above warnings don't show for bitUSD.

**Comment by svk31** [comment]
Not an issue in staging, the warnings are normal and can be ignored.

![image](https://user-images.githubusercontent.com/6890015/37450945-427a4476-2830-11e8-8092-9f11c3054fff.png)

**Comment by svk31** [comment]
Still not working in the production version, not sure why yet.

**Comment by mattbeckman** [comment]
I'll look into this one, unless svk already solved it locally.

**Comment by mattbeckman** [comment]
Located the issue last night. Looks like a greedy regex. Will fix shortly.

**Comment by grctest** [comment]
@wmbutler Has this been merged into production? I don't see asset descriptions within asset pages still.

```
missing path 'assets/HERTZ' for locale 'en' help files, rolling back to alt_path 'assets/Asset' 
help section not found assets/HERTZ#summary
```

**Comment by startailcoon** [comment]
It seems to be working just fine when you check the staging branch at https://staging.bitshares.org/#/asset/hertz

The current Web-wallet on https://wallet.bitshares.org/#/asset/hertz is not updated yet, it seems.

Ping @svk31
