### ISSUE TITLE
When navigating between asset detail pages the margin positions don't update

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1321]
![bug report gif](https://i.imgur.com/CWlkfJ4.gif)

Navigate to the USD asset page, then manually navigate to the HERTZ page via the URL bar, the margin positions from USD are imposed over HERTZ margin positions. When you force refresh (CTRL+F5) the correct margin positions are shown again.

The price feeds are correctly updated, just the margin positions aren't.

**Comment by startailcoon** [comment]
I'll take this

**Comment by svk31** [comment]
Not an issue in staging, probably caused by same issue as here: https://github.com/bitshares/bitshares-ui/issues/1305
