### ISSUE TITLE
Ant Integration. New style-guide integration

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1326]
**Summary**

[Ant (clickable)](https://ant.design/docs/react/introduce) is a powerful React library with a huge set of different React Components.

The main idea to integrate and use ant is to have all needed components to develop our app fast & easy and do not use any another non-stable packages from different developers or spend our time to develop our own solution. 

**Why Ant?**
- Themes and customizing support
- The library which has all components which developer may need
- Great community & support

**Integration process**
As we have an issue that Ant uses LESS instead of SASS I would recommend to use separate github repository under Bitshares organization like: bitshares-ui-style-guide and use build version of styles on bitshares-ui (simple css file)

On this repository I'll setup simple project with 3 pages. Each page for one Bitshares theme. Those pages will look like new Style-Guide provided by @ahdigital - https://www.behance.net/gallery/62549753/Bitshares-DEX-UI-style-guide.

Each page will be like a "live" presentation of design. Also each page will have own ant-overrides file where we can overwrite ant components styles for each theme and take a look how it looks using live page. 

On result we will add our style-guide project with ANT and all redesigned components for each theme as NPM package to bitshares-ui to make an ability to use Ant components for all developers who work on bitshares-ui.

The advantages of this way are:
- We exclude our main style-guide from bitshares-ui. We will prevent risks of changing our core style-guide by third-party hands.
- If someone wants to change our style-guide he should make a pull-request on bitshares-ui-style-guide repository.
- If we want to change something on style guide UI/UX guy prepares design for this change. Than developer implements those changes on bitshares-ui-style-guide and we can check on demo pages that everything meet our requirements and design and have no issues because we will have one page where all our UI components listed.
- Usage of one specific library for all UI components move us closer to our idea of uniform style.  
- We resolve the issue with LESS. 

Phase I
- [ ] Setup bitshares-ui-style-guide project
- [ ] Integrate and restyle ANT for each style-guide
- [ ] Prepare LIVE style-guide of all used components on our project

Phase II
- [ ] Move bitshares-ui to React v16 (ant requires React v16)
- [ ] Add ant to bitshares-ui
- [ ] Prepare list of components by priority (high priority, medium priority, low priority) to replace existing components we have for ant-components

Phase III

- [ ] Replace high-priority components (tabs, modals, tables etc.)
- [ ] Replace medium priority importance components (datepickers, typeaheads etc.)
- [ ] Replace low priority components (buttons, fields, switches, checkboxes, radio buttons etc.)

I didn't include Layout changes to those phases (to discuss). I don't know is it good idea to replace foundation layouts for ant. 

I'm a person who has around 1.5 years experience of using ant so I want to take all responsibility for this integration and future style-guide support. Also I can make manage issues/do reviews of pull-requests and accept changes to style-guide repo (I don't think we will have a lot of changes/fixes to our style-guide after we integrate it, customize to our themes and fix all issues like missed colors on some components etc.)

As I said above this issue was opened to share and discuss the plan.  

When we finish discussion and approval steps of this integration we can split this big integration by smaller tasks and I will start to work.

**Comment by diogogomes** [comment]
@gibbsfromncis **I'm glad to see your proposal to have a separate style guide** like I proposed on #1030. 

#  

Some quotes from there regarding my support to your proposal:

> Implementing a UI Style Guide helps keep the entire development team (designers or coders) on the same page.
In this way, there will be a flexible starting point to maintain the consistency of a visual style in BitShares Wallet that can also be applied to the web page and can also be worked with the marketing team.
This guide will help in the development of better user-oriented desktop and mobile user interfaces in an accessible way that users can understand.

#  

There, on #1030 I came with an idea to have more than UI Style Guide and **I like to know your opinion about have an entire UI Design System** (I called Bidesy - Bitshares Design System to make referencing more convenient)

#  

One more question:

> We will prevent risks of changing our core style-guide by third-party hands.

**This will be private/closed?**

Thank you

**Comment by gibbsfromncis** [comment]
@diogogomes 

> This will be private/closed?

Nope. It will be like a separate open repo. When user works on project he may change some themes SCSS configs and don't check that his changes apply correct. Users just worry about their own task. I want to minimize risks. If somebody want to change something on style-guide he should go to the style-guide repo, submit issue, receive approve etc.

**Comment by diogogomes** [comment]
@gibbsfromncis,

> Nope. It will be like a separate open repo. When user works on project he may change some themes SCSS configs and don't check that his changes apply correct. Users just worry about their own task. I want to minimize risks. If somebody want to change something on style-guide he should go to the style-guide repo, submit issue, receive approve etc.

Okay, it seems right.

> I'll take a look when have some time

You don't need to, I copied my ideas to my previous post (above).

**Comment by gibbsfromncis** [comment]
@diogogomes Ha-ha! I've started to read your quotes and thought that it was copied from my topic so just skipped it 😄

**Comment by diogogomes** [comment]
Sorry, I'll edit.

**Comment by gibbsfromncis** [comment]
@diogogomes I mean that your ideas really match my ideas. That's why I've recognized your quotes as my quotes

**Comment by diogogomes** [comment]
@gibbsfromncis

>  I don't understand why you apologize.

Because I used quoted text and on github is a standard to previous quotes to contextualisation.

I edited to itens.

> I mean that your ideas really match my ideas.

It's why I'm so glad to see your proposal and I want to help in everything I can to make this development process real :wink:.
