### ISSUE TITLE
[12][ahdigital] Multisignature set up UX

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1329]
Bitshares allows users to set up multiple accounts as signers on a single account. The UI works, but it is unintuitive to many users. We need to design a UI that makes sense visually for users. The bar is set pretty low on this for being intuitive. It is present on both Owner and Active Permissions.

![screen shot 2018-03-15 at 6 39 40 pm](https://user-images.githubusercontent.com/1254810/37496414-5c6ef142-2880-11e8-9d1d-82b835932acb.png)

- [ ] A user should be able to navigate to an account where they hold the keys and add user accounts with varying weight.
- [ ] These weights should be portrayed as fixed numbers / percentages / graphically.
- [ ] The user should be able to confirm the various combinations of votes that could result in a successful signed transaction.
- [ ] The page should concisely explain its purpose and guide the user intuitively through the process.
- [ ] The page should present appropriate warnings and safeguards to ensure users understand what they doing to ensure they do not get locked out of an account by their actions.

**Comment by ahdigital** [comment]
Apart from the transferring the ownership of an account from one person to another are there any other use cases for owner permissions?

**Comment by abitmore** [comment]
There are many user cases, see http://docs.bitshares.org/bitshares/user/account-permissions.html for example.

Another example is one can have a key in mobile phone but another key in PC.

Owner authority can be used to do **anything** that requires active permission (although there is a bug prevent a few things to be done).

> Would editing the weight be possible whilst there is a proposal is outstanding?

Proposals will only be evaluated when an approval added to it, or an approval removed from it, or when expires. So editing account permission won't affect them.

**Comment by ahdigital** [comment]
@wmbutler This is my first pass at simplifying the UI for the active permissions. Given that we're moving forward with ANT/style guide my mock ups will be based on that to save us re skinning later on.

Would be great to get some technical feedback from you and also @abitmore. 

![image](https://user-images.githubusercontent.com/3088454/37530383-4f5f81c2-2931-11e8-8aee-677d97c6c8cd.png)

**Comment by diogogomes** [comment]
@ahdigital I liked but is possible change de "agreement required" method with total number of accounts?

i.e: 2 of 3 accounts

**Comment by abitmore** [comment]
@ahdigital looks good. By the way, how to add keys? Keys and accounts are combined in the core.

It's important that one should know what she's doing when putting herself in the list. In your case, account-name-01, if combined weight of other accounts is less than threshold, it would lock out the account.

**Comment by wmbutler** [comment]
## Introduction
@ahdigital Thanks for the first pass on this. Dan built this in a very open manner. It's so flexible that it's easy for a user to be confused by it. One of the most confusing parts for me is the idea behind what constitutes a "threshold". Essentially we need to communicate to the user how various percentages add up to influence a successful transaction.

## Threshold
I see you chose `Agreement Threshold`. I really like your use of the word influence. 

- [ ] Why don't we change it to `Influence Threshold`. I think we need a tooltip by this saying "Any combination of accounts listed above adding up to this value may authorize transactions on this account" 

Also, I've always felt that the 51% value is arbitrary. I suppose it's the throwback to the days of stocks and voting rights, but it's not even very accurate, because technically, a person would only need to have any value over 50% to have a controlling interest. So, 50.1% would be just as valid.

I think if we choose 100 as the threshold it will make more sense for the end user. We would of course honor whatever value a person chooses to enter, but I think starting with 100 is a better baseline.

## Visual confirmation
I think it's critical that we be able to show a visual to help users understand the various combination of voters who can approve a transaction. While, admittedly, this could become problematic with complex organizational structures, I think this capability would set bts apart when comparing multisig features of other blockchains. It could be a modal that scrolls downward to handle the various possibly endless combinations. In your example, it might look like this:

The following account combinations are authorized to approve transactions under your current settings:

account-name-01
account-name-02
74%

account-name-01
account-name-03
74%

account-name-01
account-name-04
59%

account-name-02
account-name-03
account-name-04
60%

Each block listed above must be above a threshhold of 51% so it would be nice to see a line representing the influence threshold and a stacked bar illustrating the contribution towards reaching that threshold.

**Comment by wmbutler** [comment]
This is admittedly a terrible drawing but what I am trying to convey is that there is a threshold represented by the line and a combination of accounts with influence represented by the stackable bars.

![untitled drawing](https://user-images.githubusercontent.com/1254810/37558885-6647cd5a-29e9-11e8-96fb-d72d67c02b81.png)

**Comment by ahdigital** [comment]
@wmbutler I've updated the visuals to include:

- Terminology change; Agreement threshold > Influence threshold
- Added [?] to trigger tooltip explanation
- Added a 'at a glance' summary section
- Added a modal window with detailed visual confirmation*

![active permissions v2](https://user-images.githubusercontent.com/3088454/37702993-2c49578a-2cec-11e8-91cd-a4b6af534f33.png)

![active permissions modal v1](https://user-images.githubusercontent.com/3088454/37703015-2fb7eecc-2cec-11e8-80b0-dbb2b510c421.png)

\* Given the potential permutations I'd suggest an array of colors that could be build into the style guide specifically for diagrams and charting.

![color-array](https://user-images.githubusercontent.com/3088454/37703022-332085a6-2cec-11e8-8fb1-fd092c90c8a6.png)

In response to your opinions regarding the threshold:

> Also, I've always felt that the 51% value is arbitrary ... So, 50.1% would be just as valid

Agreed. I just copied 51% from the example on the DEX help section.

> I think if we choose 100 as the threshold it will make more sense for the end user.

You mean this should be the default for a new set of permissions on page load, right?

That's no problem. We just use the 'weighting' system instead of 'percentages' as the default. So the default state of the table would look like this:

![active permissions default table v2](https://user-images.githubusercontent.com/3088454/37703030-381e7ec8-2cec-11e8-980c-d97684ddac1c.png)

**Comment by svk31** [comment]
This looks very nice, but I'd like to point out an issue that most people don't realize about how multi-sig setups work in Bitshares.

In order to sign a transaction, an account needs to have an active authority above the threshold, in the example above that would be 51%. So any account being included as part of a multi-sig setup needs to fully control itself, meaning it cannot itself be a multi-account because if it is it cannot sign anything.

To clarify, if we use the accounts above, account-name-01 is the one being configured for multi-sig, but it is also being included as an authority with 49% weight. That is pointless, because it cannot sign anything directly and thus cannot participate in the multi-sig setup.

**Comment by wmbutler** [comment]
> So any account being included as part of a multi-sig setup needs to fully control itself, meaning it cannot itself be a multi-account because if it is it cannot sign anything.

Does this mean that the current account, account-name-01, is not eligible to be part of its own multisig?

**Comment by ahdigital** [comment]
I think that is the case yes.

**Comment by abitmore** [comment]
> Does this mean that the current account, account-name-01, is not eligible to be part of its own multisig?

The backend doesn't check it. In original design the client software is responsible for detecting cycles (see https://bitshares.org/technology/dynamic-account-permissions/), but none of our client software has done that. There are quite some accounts been locked out: https://github.com/bitshares/bitshares-core/issues/269.

**Comment by wmbutler** [comment]
ok, so the UX needs to explicitly show that:

- [ ] The current account is not part of the percentage selection. "I understand that this account (account_name) will no longer have control over any assets within it once complete. Instead, the accounts chosen below will have cosigner (multisig) rights based on the percentages chosen below.

- [ ] For housekeeping, we should set the value to the current account to 0.
- [ ] The other accounts can be listed as you have them below.
- [ ] I would suggest that the visual display of the combinations that can vote be almost a confirmation step (so screen 2 for instance). On that screen we have a checkbox saying. "I acknowledge that only the combinations of accounts listed above will have the authority to manage funds on behalf of account: this_account."

**Comment by wmbutler** [comment]
General thought. I think the propose term is technical. I think we should discuss the terms co-sign and/or multisig instead.

**Comment by ahdigital** [comment]
Some amendments:

![active permissions default table v3](https://user-images.githubusercontent.com/3088454/37970229-d08cfbd4-31ca-11e8-8b6f-d4a7ebc4fffa.png)

![active permissions modal v2](https://user-images.githubusercontent.com/3088454/37970233-d3f70c4c-31ca-11e8-8675-6ffd31aa2a24.png)


> I think the propose term is too technical. I think we should discuss the terms co-sign and/or multisig instead.

The question is who's the target audience here? I think all those terms could be meaningless to Joe Bloggs using the DEX. I don't have a better suggestion though unfortunately..

**Comment by ahdigital** [comment]
Does anyone have anything else to add to this?

**Comment by wmbutler** [comment]
I think you need to add back the references to the public and private keyfiles for this to be complete. Please add the necessary time to the issue.

**Comment by ahdigital** [comment]
I added in the accounts / keys / addresses that the existing functionality has.

Where keys / addresses are used we'll have to truncate with an ellipsis at some point to save the UI at smaller resolutions - I suggest that when this happens a tooltip becomes available to view the entire key.

### Default table
The default view for the page when there are no permissions active. 'Weights' is the default method for defining thresholds.

![active permissions default table v4](https://user-images.githubusercontent.com/3088454/39043568-ac77fcbc-4485-11e8-804b-90196d2a953c.png)

### Permissions added
The user switched from weights to percentages and added their permissions.

![active permissions v3](https://user-images.githubusercontent.com/3088454/39043388-309630be-4485-11e8-8807-b38c1a71c466.png)

### Review outcomes & save
The user reviews their permissions, needs to confirm and click save.

![active permissions modal v3](https://user-images.githubusercontent.com/3088454/39043397-382f803c-4485-11e8-8b31-aa99931e885d.png)

**Comment by wmbutler** [comment]
The keys and the viewing of the public/private versions of them need to be shown but not incorporated into the Multisig UX. Sorry if I'm not being clear. My point here is that people still need to be able to:

- view public key
- view private key
- trigger barcode

Just want to see this displayed so the implementor knows where it goes (no need to UX that part but it does need an overhaul eventually as well).

**Comment by ahdigital** [comment]
Updated screenshots below showing the key viewer which when clicked will trigger the existing modal behaviour. 

![active permissions default table v5](https://user-images.githubusercontent.com/3088454/39464232-ff0109c4-4d13-11e8-9ef3-85ea6ff4a6b0.png)

![active permissions v4](https://user-images.githubusercontent.com/3088454/39464189-d481b928-4d13-11e8-83b7-9d835037e3f2.png)

![active permissions modal v4](https://user-images.githubusercontent.com/3088454/39464287-4f98988e-4d14-11e8-9bb3-3f52661887b6.png)

**Comment by ahdigital** [comment]
No problem.

> Since it is less likely that the user will use Multisig, can we move this operation to the bottom and place the area entitled "PUBLIC KEY DETAILS" on the top?

If somebody wanted to find their keys, would they really think first to go to 'permissions > active permissions'?

Do you have a practical reason why we shouldn't place this key viewing functionality either within the settings area or, on their own tab (E.g. Keys) as a child page of permissions. Memo key, for example has it's own tab so why not bring all these things together?

**Comment by wmbutler** [comment]
@ahdigital, thanks for your comments. This is a good conversation to have.

Permissions are exactly that. They represent the set of rules that allow a user to have controls over their funds. In this case, those permissions can be granted by a single private key, or a combination of keys (multisig). For this reason, I think it is appropriate to include private key management within the permissions area.

As discussed in this article, we have the additional task of making it clear to users that if/when they decide to go multisig, their current account keys are effectively nullified.

**Comment by ahdigital** [comment]
What I have in mind is this sequence:

### View public key
The user lands on the active permissions tab and can view the public key, which can be copied using the copy icon.

For consistency later on I think it makes sense to display the public key as a QR also.

![1](https://user-images.githubusercontent.com/3088454/39573152-ec61d354-4ec9-11e8-9e8b-5f44b3c69b03.png)

### View private key authentication
If the user clicks 'View active private key' a login modal will appear for authentication.

![2](https://user-images.githubusercontent.com/3088454/39573215-33e586e4-4eca-11e8-8419-b34d2693713b.png)

### View private key
Once authenticated the private key and QR will be displayed. Included here is an optional field for the user to enter a PIN. I called it PIN, and not password to try and prevent users entering an actual password of theirs by mistake.

There is a help symbol [?] which opens a tool tip explaining the field, and acceptable characters.

The user can hide the private key by clicking 'Hide active private key'.

![3](https://user-images.githubusercontent.com/3088454/39573319-a277482c-4eca-11e8-8ad2-8bb038af0454.png)

### Enter QR encryption PIN
As the user starts typing a PIN, the private key QR shown should grey out/disable.

![4](https://user-images.githubusercontent.com/3088454/39573401-f83f45c0-4eca-11e8-9f2c-cc303dd6de83.png)

### Encrypt and refresh QR
When the user clicks the refresh button after entering their PIN, the QR should update to show the encrypted version.

![5](https://user-images.githubusercontent.com/3088454/39573454-2cdaa86a-4ecb-11e8-9dc6-466b85b09569.png)

### QR hover
The user can hover over each QR which shows an expand icon.

![6](https://user-images.githubusercontent.com/3088454/39573470-411b72a0-4ecb-11e8-9e94-96293ef978b0.png)

### QR expand
The user can click the expand icon to open a larger version inside a modal.

![7](https://user-images.githubusercontent.com/3088454/39573499-5a9ab718-4ecb-11e8-94b1-b9166466fd54.png)

**Comment by wmbutler** [comment]
I think this looks great.

**Comment by ahdigital** [comment]
Great - can you update to 12 hours please.

**Comment by abitmore** [comment]
@ahdigital there would be not only one public key in the page. Every line in the `active permissions` list can be a key.

**Comment by ahdigital** [comment]
@abitmore 

I understand what you're saying but:

> The keys and the viewing of the public/private versions of them need to be shown but not incorporated into the Multisig UX.

I took this to mean that the keystore details shown would be for the active account (in top right) only. 

@wmbutler What approach should we be taking?

**Comment by abitmore** [comment]
@wmbutler @ahdigital more questions / thoughts:
* since private key is sensitive info, it's better to NOT always show it on the page,
  * add a warning when about to show a private key;
  * show it in a modal so the user will more likely hide it later;
  * automatically hide it after a while, perhaps with a countdown timer showing on the page;
  * another option is to download a file rather than showing it on page.
* the private key QR image without a PIN should be disabled (make it unable to scan, perhaps not only disabled) by default, since a PIN is preferred,
  * use a check box "I know it's insecure but I won't use a PIN" or something,
    * after clicked, show a warning

**Comment by abitmore** [comment]
> I took this to mean that the keystore details shown would be for the active account (in top right) only.

@ahdigital I mean every entry in the "active permissions" can be a public key or another account:
![image](https://user-images.githubusercontent.com/9946777/39630062-7ffc01a4-4fae-11e8-82f7-a182925caef4.png)

**Comment by ahdigital** [comment]
@abitmore Like I said, I understand what you're saying but Bill said that the keys and the viewing of the public/private versions of them need to be shown and not incorporated into the multisig UX.

So with that in mind, that's why I've shown just the keys for the active account shown in the top right.

**Comment by abitmore** [comment]
@ahdigital OK I understood your point now. There would be multiple keys, so doesn't make much sense to show one on the page.

**Comment by wmbutler** [comment]
@abitmore I think we need to be careful about how difficult we make the process for the user. If we are going to show the private key as text, showing the QR code is no more dangerous. Id someone takes a picture of the text, it's the exact same risk as someone taking a picture of the QR code. For this reason, I have to disagree with making the QR code more difficult to access than the private key text.

I thought through @ahdigital's UX pretty carefully and I really don't see any glaring problems.

In the current wallet, we have multisig paired with the private keys. we really aren't changing much functionality here, rather, just making it more intuitive and removing some barriers that only give the **illusion** of security.

**Comment by abitmore** [comment]
@wmbutler actually I don't like current design that shows private keys directly on UI, so I wrote the text above. I was trying to hide it as soon as possible, if can't hide it entirely.

It's true that moving key viewing to the top is wise for simple one-key accounts, although most users especially cloud wallet users won't use it anyway. One question is, how should developers deal with accounts with multiple keys? I believe you're not asking advanced users to not use reference wallet.

BTW showing a QR code for public keys makes little sense, may I ask what are the potential use cases that need it?

**Comment by wmbutler** [comment]
@abitmore, @ahdigital's reasoning was one of consistency. Adding to that, why would we ever display a public key for a user account. I'd maintain that anywhere we have long data that a user may need to copy and paste, it likely makes sense to display a QR code in that same area.

**Comment by ahdigital** [comment]
@wmbutler 

> Great - can you update to 12 hours please.

Is there any more work to do here or can this be closed?

**Comment by wmbutler** [comment]
Yes, I think this is sufficiently groomed.
