### ISSUE TITLE
[1.5] Update Order Expiration 

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1331]
- [x] Add option "1 year"
- [x] Set default expiration as "1 year"
- [x] Display calendar above Time to prevent cutting on buttom (it would be nice to add check where is better to display calendar but so much time to refactor core library and btw it would be replaced in few weeks after Ant integration) 
- [x] Remember last selected expiration time and store in localStorage

**Comment by abitmore** [comment]
For overall performance, I'd recommend not give "never" option to users on UI, instead, encourage users to set an expiration time not too far in the future. Although we don't enforce a limitation on this field in the core now, we may need to do it later.

**Comment by gibbsfromncis** [comment]
@abitmore those 2 comments - https://github.com/bitshares/bitshares-ui/issues/17#issuecomment-373635070 asked me to update expiration. So If I can't provide "never" option can you advise me what is the max expiration can be?

**Comment by abitmore** [comment]
Actually I don't know what value is best. Should ask UX guys or product manager.

**Comment by abitmore** [comment]
IIRC max order life time on bittrex is 30 days. Not sure about other exchanges.

**Comment by wmbutler** [comment]
I think 1 year should be the default and users should be able to pick anything other than that manually.

**Comment by abitmore** [comment]
1 year is OK, but don't say it's "never".

**Comment by CryptoKong** [comment]
I'd be happy with one year as a default setting, thanks for listening to my concerns guys, really appreciate it. Keep up the good work!

**Comment by wmbutler** [comment]
I agree we shouldn't use the term "never"

**Comment by tbone-bts** [comment]
A standard order option in trading UIs is GTC ("good til cancelled").  If that is problematic for some reason, then 1 year seems reasonable enough, although it would probably be helpful to somehow warn users if/when they have trades that are getting ready to expire.  

By the way, the calendar is getting cut off when the order form is near the bottom of the screen:

![order_expiration_ui](https://user-images.githubusercontent.com/15830348/37602655-2c37fbe6-2b63-11e8-85ee-385d878f688a.JPG)

**Comment by abitmore** [comment]
Some ranting here.. GTC is a feature, but not a must. In traditional exchanges, when you places a GTC order, usually the order's life time is actually "keep it open until the market closes today (or this week)". Crypto exchanges like bittrex did have the GTC option, but they've moved away from that.

**Comment by wmbutler** [comment]
I agree that GTC is not a must. It's inexact and misleading. Thanks for the bug report on the calendar. I think we can work both of these items as part o this issue. Added 1 hr because I know how these positioing issues can be a PITA.

**Comment by gibbsfromncis** [comment]
@tbone-bts please submit new issue for notifications about expired trades and we will think how to implement it on the best way

**Comment by gibbsfromncis** [comment]
PR #1357
