### ISSUE TITLE
[11][Ant Integration Phase I Part II] Create pages for Live style-guide based on UX for each theme

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1333]
Phase I part 2 of #1326

This task includes:
- [x] Setup React app on new repository #1332
- [x] Configure app builder to be able export one .css file with all themes (dark, midnight, light) of ant and include it on bitshares-ui project
- [x] Create 3 pages of Live style-guide based on [this UX](https://www.behance.net/gallery/62549753/Bitshares-DEX-UI-style-guide) where we able to check that all styles applied to all components correct. 

On result of this task we will have project which we able to include on bitshares-ui and 3 live pages but with the same ant default styles. The following task is for restyle ant for each theme #1334

**Comment by gibbsfromncis** [comment]
@wmbutler My Fair Estimate fo each subtask is:
- 1h
- 2h
- 6h 

(I'm trying to estimate like you (developer estimate * 0.65)) so please don't cut estimates so much 😃 

Please decide about your estimate and put in on the issue title.

**Comment by kapeer42** [comment]
can I claim this?

**Comment by gibbsfromncis** [comment]
@wmbutler @svk31 

There is repo and last build - https://github.com/bitshares/bitshares-ui-style-guide

Could you please validate it and close this task if you do not have any comments
