### ISSUE TITLE
[15][Ant Integration Phase I Part III] Restyle Ant for each theme based on UX

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1334]
This task includes:

- [x] Create 'midnight' theme for Ant components
- [x] Create 'dark' theme for Ant components
- [x] Create 'light' theme for Ant components

On result we have restyled for each theme ant components which can be included on bitshares-ui

[UX for this task](https://www.behance.net/gallery/62549753/Bitshares-DEX-UI-style-guide)

**Comment by gibbsfromncis** [comment]
@wmbutler The fair estimate is 12h. It relates to the issue that we cannot restyle whole ant for out needs only by updating it's variables. Some components should be restyled by overwriting their styles. First theme will take 90% of this time. Another 2 themes just 5% of time because I need just update colors on variables.

**Comment by gibbsfromncis** [comment]
@wmbutler Additionally I want to ask you to include `10 hours` for `UX` for @ahdigital to reward his work of new style-guide mentioned on this issue above. It was done without specific issue by his initiative but if I understand correct we're going to use it and all like it. Also this 10 hours include future fixes on style-guide in context of this issue which I may request from @ahdigital because on work I may catch some issues and sometimes better and faster to change UX instead of implementing existed things.

**Comment by ahdigital** [comment]
Following some recent tasks I'm working on related to login and permissions I've made use of some new components, which are now updated on the style guide.

New components are sliders, breadcrumbs and drag and drop file upload which supports multiple files.

Form helpers and modals have been updated to fall in line with the latest styling.

**Preview**

https://user-images.githubusercontent.com/3088454/38023755-05f9b84c-327b-11e8-8f93-8e6a7a40b0b6.png

**Comment by gibbsfromncis** [comment]
@wmbutler as we have a separate task for UX ([this one](https://github.com/bitshares/bitshares-ui/issues/1336)) I suppose you can remove [10] from this issue's title to prevent misunderstanding on the future.

**Comment by gibbsfromncis** [comment]
@wmbutler @svk31 

There is repo and last build - https://github.com/bitshares/bitshares-ui-style-guide

Could you please validate it and close this task if you do not have any comments

**Comment by wmbutler** [comment]
I'm a little confused about the hours on this task. I removed the 10 as you requested before, but what is the 15 for?

**Comment by gibbsfromncis** [comment]
@wmbutler it's pretty simple. I've posted the full report so you know what kind of work done and where I spent estimated time:
  
1) The [first part](https://github.com/bitshares/bitshares-ui/issues/1333) (#1333) was to:
- setup base skeleton and setup base architecture of project
- configure project to export only `bitshares-ui-style-guide` (when we have React v16 on bitshares-ui our developers will just do `import {Button} from 'bitshares-ui-style-guide'`
- setup live demo of 3 themes based on [UX](https://www.behance.net/gallery/62549753/Bitshares-DEX-UI-style-guide).

First part was more technical than visual. It doesn't contain any updates to ant default theme and customizing. On result of the first part we have the following Live Preview of our style-guide (keep in mind it's the ant default theme on each screenshot and themes are not customized so it looks really bad):
![e41837b3-8fdc-4bcc-a566-905d65e692b2](https://user-images.githubusercontent.com/35899973/39093417-de018226-461f-11e8-9150-57edbcba55ad.png)
![63cb3536-36ee-4d4e-9317-b79bbfc4bb3b](https://user-images.githubusercontent.com/35899973/39093425-f1296a1c-461f-11e8-99ce-ba5ffd815e35.png)

As you see on the screenshots the Live Demo follows [UX](https://www.behance.net/gallery/62549753/Bitshares-DEX-UI-style-guide) with only one exception - it's not customized for our themes

2) Second part (**this issue #1334**) includes exactly customizing of each theme:
- Get ant default variables and update their values (paddings, colors etc.) (pretty simple and easy)
- Add additional variables and write additional class overrides (the most part of work)
- Collaboration with Dominic, discussions regarding issues and searching of acceptable decisions from technical and design perspective. Our collaboration didn't finished on stage when Dominic provided me UX. Some of things on UX are not acceptable because of ant architecture and we should to discuss the possible solutions of those issues.

On result of this issue we have the following pages:
(Home page, when user put mouse over the theme button page applies this theme styles):
![screenshot-2018-4-22 reactjs boilerplate 3](https://user-images.githubusercontent.com/35899973/39093578-ec8a95ec-4621-11e8-8455-161bbbef1348.png)
![screenshot-2018-4-22 reactjs boilerplate 4](https://user-images.githubusercontent.com/35899973/39093579-eddf3966-4621-11e8-9b74-d3cabfbacc78.png)
![screenshot-2018-4-22 reactjs boilerplate 5](https://user-images.githubusercontent.com/35899973/39093581-efb152d8-4621-11e8-87ed-1de3156bab85.png)

And Live demo pages (already styled):
![screenshot-2018-4-22 reactjs boilerplate 2](https://user-images.githubusercontent.com/35899973/39093584-045da6c8-4622-11e8-8d8b-fa65797bf738.png)

![screenshot-2018-4-22 reactjs boilerplate 1](https://user-images.githubusercontent.com/35899973/39093585-0656f02e-4622-11e8-8c3f-bed36a5645eb.png)

![screenshot-2018-4-22 reactjs boilerplate](https://user-images.githubusercontent.com/35899973/39093590-0abed654-4622-11e8-85c8-65c381545abd.png)


@wmbutler If you have any questions regarding report posted above feel free to ask me or if you have any disagreements regarding my estimate I'm open to discuss and ready to explain why it took estimated time.

**Comment by wmbutler** [comment]
OK, so this is phase 1 part 3 and should be paid at 15 hours. Got it.
