### ISSUE TITLE
[1.5] Cannot translate some English phrases

### ISSUE THREAD

**Issue by gn1github** [bitshares/bitshares-ui#1335]
As I could not reopen #1243, I am creating a new one to report some issues.

I found a few problems.

1.  I've added "buysell_formatter": "{asset} {direction}" to locale-ja.json on line 1151, but it is not reflected properly on frontend. Moreover, the asset name is gone on the buy-side box.

<img width="1112" alt="not-reflected" src="https://user-images.githubusercontent.com/36555761/37534580-96db47dc-2988-11e8-974a-5a99adc6a0be.png">

2. It seems like there are a plenty of hardcoded English phrases on the deposit page. Can you make these translatable?

<img width="1211" alt="hard-coding" src="https://user-images.githubusercontent.com/36555761/37534593-a2bb0678-2988-11e8-8830-aeb99fb7ddc6.png">

3. It seems like the Borrow bitUSD screen that I have reported previously is still containing hardcoded English phrases. Can you make these translatable?

<img width="694" alt="hard-coding2" src="https://user-images.githubusercontent.com/36555761/37534641-be9d5922-2988-11e8-92e6-106cb55cc6f9.png">

**Comment by startailcoon** [comment]
I'm taking this under my wings as I did the previous issue that wasn't possible to be opened by OP.

**Comment by startailcoon** [comment]
### 1: 
**Solved in PR #1345** 

### 2: 
The upper section of this translation should be done in `app/help/en/components/DepositWithdraw.md`. Copy this file to the `app/help/ja/components` folder and apply your translation there.

The lower section was hardcoded by OpenLedger in their Withdraw/Deposit component.  **Solved** 

### 3
Same thing applies here, as the translation is done in the file `app/help/en/components/BorrowModal.md`. Copy the file to the appropriate folder and translate.

## Feel free to mention other sections
If you find anything else that you need help with, I'm happy to assist. I'm leaving this issue open for the current milestone for further issues in translations.

**Comment by gn1github** [comment]
Thank you for your help.

I have created a pull request, #1348.

**Comment by startailcoon** [comment]
You're welcome @gn1github 

Note the new translation variables I've created on https://github.com/bitshares/bitshares-ui/pull/1345/commits/1df997849156d8cd2d809eb1b4f5a247d8f99ab2

**Comment by gn1github** [comment]
Added Openledger translation on locale-ja.json.
Pull request #1351 created.
