### ISSUE TITLE
[.25] 'Find Market' sidebar tab target suggestion

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1337]
![image](https://i.imgur.com/iIGedlM.gif)

Currently, when you're focusing on the 'find market' side bar, after typing in the 'Quote Currency' the TAB key focuses on the top right account drop down, then the Asset name hyperlinks. 

Would it be able to instead tab to the 'Asset Name' field?

Cheers 👍

**Comment by wmbutler** [comment]
Pretty easy win.
