### ISSUE TITLE
Replace current charting library with Tradingview

### ISSUE THREAD

**Issue by ffallah** [bitshares/bitshares-ui#134]
The current charting provided in Bitshares GUI is very bad and novice.
Is it possible to replace it with Tradingview ? it is free :
https://www.tradingview.com/HTML5-stock-forex-bitcoin-charting-library/
Almost all good exchanges use Tradingview and it is fantastic.

**Comment by wmbutler** [comment]
I'd suggest we make incremental fixes to the current library.
