### ISSUE TITLE
[.25][HarukaMa] Fee schedule incomplete

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1342]
https://wallet.bitshares.org/#/explorer/fees doesn't contain all fees.

**Comment by wmbutler** [comment]
Can you detail fees needed to make this complete?

**Comment by abitmore** [comment]
The relatively new operations.

The one missing since 2016 is claiming accumulated fee.

The other is `bid_collateral` added with BSIP18.

And we'll add more operations with next hard fork.

**Comment by wmbutler** [comment]
- [ ] claim accumulated
- [ ] bid_collateral

**Comment by abitmore** [comment]
As of now, we haven't explicitly specify an bid_collateral fee on the live chain, so call_order_update fee is used for it, which is hard coded in the core. The committee can explicit set the fee, but not done yet: https://github.com/BitShares-Committee/proposals/issues/4.

**Comment by HarukaMa** [comment]
I was trying to squeeze this into a previous PR but didn't make it. I've added fee claiming already in my private fork.

I could push it to official UI.

This is a relatively minor fix and I think 0.25, or even 0.1 is enough.

**Comment by wmbutler** [comment]
@HarukaMa it's yours
