### ISSUE TITLE
When socket does timeout do some housekeeping

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1346]
- [x] Do not issue get_objects call
- [ ] Do not issue get_ticket call

```
app.js:43 keep alive timeout.
(anonymous) @ app.js:43
app.js:45 !!! GrapheneApi error:  get_objects Array(1)0: ["2.1.0"]length: 1__proto__: Array(0) Error: connection closed
    at e.i.ws.onclose (app.js:43)
    at HTMLDivElement.<anonymous> (app.js:45)
    at WebSocket.s.onclose (app.js:45) {}
app.js:45 !!! GrapheneApi error:  get_objects Array(1) Error: connection closed
    at e.i.ws.onclose (app.js:43)
    at HTMLDivElement.<anonymous> (app.js:45)
    at WebSocket.s.onclose (app.js:45) {}
app.js:45 !!! GrapheneApi error:  get_ticker Array(2) Error: connection closed
    at e.i.ws.onclose (app.js:43)
    at HTMLDivElement.<anonymous> (app.js:45)
    at WebSocket.s.onclose (app.js:45) {}
app.js:45 !!! GrapheneApi error:  get_ticker Array(2) Error: connection closed
    at e.i.ws.onclose (app.js:43)
    at HTMLDivElement.<anonymous> (app.js:45)
    at WebSocket.s.onclose (app.js:45) {}
app.js:45 !!! GrapheneApi error:  get_ticker Array(2) Error: connection closed
    at e.i.ws.onclose (app.js:43)
    at HTMLDivElement.<anonymous> (app.js:45)
    at WebSocket.s.onclose (app.js:45) {}
app.js:45 !!! GrapheneApi error:  get_ticker Array(2) Error: connection 
```

**Comment by sschiessl-bcp** [comment]
When did this timeout happen for you?

**Comment by wmbutler** [comment]
@sschiessl-bcp this happens on a regular basis for me on 180315.

**Comment by calvinfroedge** [comment]
@wmbutler @svk31 I think I'm on the right track here but not sure... https://github.com/bitshares/bitsharesjs-ws/pull/15

I think that will prevent this showing up in the error logs...``` "app.js:45 !!! GrapheneApi error:  get_objects Array(1)0: ["2.1.0"]length: 1__proto__: Array(0) Error: connection closed"```

One issue in the bitshares-ui with cleaning up the other errors is that there is code like this strewn all over the place:

```
Apis.instance()
                        .db_api()
                        .exec("get_ticker", [base.get("id"), quote.get("id")])
```

I realize that `instance` is a Singleton but the question here is how we want this bit to fail:

```
                        .db_api()
                        .exec("get_ticker", [base.get("id"), quote.get("id")])
```

Right now it fails with a log message...probably shouldn't fail silently. Thoughts?

**Comment by wmbutler** [comment]
Keep exploring. Ideally, we want to (a) supress this error (b) perfom a graceful reconnect when the node senses it has disconnected.

Also, it's important to have logs about disconnects while figuring this out. Maybe like:

Disconnected from node x.x.x at 12:45:00 am UTC
Connect to node x.x.x at 12:47:00 am UTC

**Comment by calvinfroedge** [comment]
I'd kind of like to have @svk31 opinion before getting too serious about this...`Apis.instance().db_api()` is strewn all over the place so fixing these sorts of issues could mean touching a lot of files.

**Comment by calvinfroedge** [comment]
@svk31 Bump

**Comment by svk31** [comment]
These calls are made by setInterval calls, I guess the easiest way to fix it would be to cancel them once the connection is lost.

**Comment by sschiessl-bcp** [comment]
@calvinfroedge what is the status here?

**Comment by svk31** [comment]
I did merge the `bitsharesjs-ws` PR now if that's what you're referring, I've been waiting for a reply on my latest feedback but just made the changes myself in the end and merged it.
