### ISSUE TITLE
Neutral proxy representation?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#135]
Hey,

So I was interested in becoming a proxy and found that it's as simple as another user simply searching for your account name then hitting 'publish changes', but I found out that the 'known proxies' list is a static list.

In order to be neutral when promoting 'known' proxies, would it be possible to automatically display user accounts that others are trusting as a proxy, descending in terms of vote weight? Likewise, showing their proxied vote weight would be pretty cool.

Thanks.

**Comment by svk31** [comment]
It's a good idea for sure, but there's no API available for this I'm afraid which is why the list is hard-coded. If you know of any proxies that you'd like to have added to the list, just let me know and I can add them.

**Comment by grctest** [comment]
I'd greatly appreciate having my account listed as a proxy: "customminer"

My background:
I've been a BTS holder since the BTSX days, I'm heavily involved within the Gridcoin community and aim to promote the use of Bitshares for trading OPEN.GRC instead of using centralized exchanges.

Aims as a proxy:
* Simplifying the voting process for Gridcoin community members.
* Voting for reliable witnesses who provide many accurate price feeds.
* Voting to support workers (I will not discriminate against users nor fret over 'dilution').
* Seeing the Bitshares & overall graphene crypto community succeeding.

Accounts:
Bitsharestalk: https://bitsharestalk.org/index.php?action=profile;u=42582
Cryptocointalk (gridcoin forum): https://cryptocointalk.com/user/10564-cm/
Steemit: https://steemit.com/@cm-steem/
Soundcloud (GRC hangouts & BeyondBitcoin attendances): https://soundcloud.com/gridcoin-community-hangouts

Best regards,
CM.

**Comment by grctest** [comment]
>It's a good idea for sure, but there's no API available for this I'm afraid which is why the list is hard-coded.

Would such a feature require a BSIP within the Bitshares-Core repo? A similar descending vote listing is shown for Witnesses, so it should be theoretically possible for Proxies.

**Comment by svk31** [comment]
This is something that would be ideal for a micro-service similar to what the Steemit team is currently building for Steem.
