### ISSUE TITLE
Implement "get_all_workers" for voting section

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1352]
Today we call getObject by running trough all objects in the 1.14.xxx section.
The Bitshares-core has since an while a API call to fetch all workers.

This can be called by, for example
```
Apis.instance().db_api().exec("get_all_workers", []).then(workers => {}).catch(err => {});
```

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares-ui/commit/acd83b2cf38893e7ca3a041766f509af2a5faf00
