### ISSUE TITLE
[.5] Give user feedback on establishing node connections

### ISSUE THREAD

**Issue by smogm** [bitshares/bitshares-ui#1353]
At the moment the user can not see whether the UI is just "freezed" or doing something in the background.
Especially when starting the DEX UI you will see a full grey screen for a few seconds (5-10, sometimes even longer) without knowing what's happening behind the scenes. 

Only opening the browser development tools and console shows you that the code is trying to determine and connect to a witness node.

The current behaviour is bad for the user experience, because the user believes that the DEX is slow and laggy.

It would be nice to have some type of optical user feedback like "trying to connect to node xxx.bitshares.org" or something, maybe with a loading progressbar or spinner, so that the users knows that there is code running in the background.

**Comment by sschiessl-bcp** [comment]
With my commit a LoadingIndicator will appear when the UI is reconnecting

**Comment by svk31** [comment]
I actually already fixed this with the upgrade to react router 4.

**Comment by sschiessl-bcp** [comment]
> I actually already fixed this with the upgrade to react router 4.

How did you implement the feedback?

**Comment by wmbutler** [comment]
If this was merged, please close.

**Comment by sschiessl-bcp** [comment]
@svk31 see my comment and question above

**Comment by sschiessl-bcp** [comment]
I see it now, you probably refer to the statusCallback in routerTransitioner. So I guess we implemented similar features. Anyways, this is closed now as fixed by Sigve.

**Comment by svk31** [comment]
That was more recent, I first added feedback during the react router 4 upgrade because that removed the onEnter callback for routes. That meant I had to refactor willTransition to be a pure promise which is now resolved in AppInit.
