### ISSUE TITLE
[.5][1][happyconcepts][svk31] Missing Launcher Icon

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#1367]
No icon is shown in the launcher. See lower left of screenshot.
Light client 180315 amd64 deb ...new install on ubuntu 16.04

![no_icon_linux](https://user-images.githubusercontent.com/14145836/38062341-387e5ff2-32a8-11e8-939c-55d9b178faec.png)

**Comment by happyconcepts** [comment]
@wmbutler Can i take this small bug?

**Comment by happyconcepts** [comment]
Probably more like a job for @svk31 or @calvinfroedge as i haven't touched the binary builds.

`Icon=bitshares2-light` in the .desktop file should be reset to `bitshares` or the filename which had previously been specified ...

**Comment by wmbutler** [comment]
@happyconcepts happy to give it to you if you like.

**Comment by happyconcepts** [comment]
Sure for 180401, thanks!

**Comment by happyconcepts** [comment]
So in my case (ubuntu):

1. The installer wrote bitshares2-light.png to this location: 
/usr/share/icons/hicolor/0x0/apps/bitshares2-light.png
I could not locate other bitshares icons in the larger formats e.g. 256x256, 512x512

Can we confirm that this is the right installation location? hicolor is just one of several themes in ubuntu...

2. The .desktop specifies bitshares2-light.png but without the full filepath, apparently.

Workaround is to manually edit the .desktop to:
`Icon=/usr/share/icons/hicolor/0x0/apps/bitshares2-light.png`

Ideas to make it happen in the build?

**Comment by wmbutler** [comment]
Hotfix @svk31 this is a pretty major oversight.

**Comment by happyconcepts** [comment]
might help ....
https://github.com/electron-userland/electron-builder/issues/2269#issuecomment-342168989

**Comment by svk31** [comment]
That was less complicated than it seemed: the icon.png image was being placed in a 0x0 icon folder which is not indexed by linux, so the icon was not found. And since there was an icon.png included, electron-builder did not auto-generate the proper icons from the Mac icon.icns file.

Simply deleting the icon.png file fixed the issue in the end after lots of digging..

**Comment by happyconcepts** [comment]
@wmbutler how much longer should I wait on this? Thanks.

**Comment by happyconcepts** [comment]
@wmbutler can this be paid please or did you already pay @svk31?
