### ISSUE TITLE
Multiple decimals can be entered into exchange input fields

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#137]
### Reproduce
- OS X
- Lite Wallet 2.0 v 170328
- Go to BTS/bitUSD exchange
- Focus your cursor in the BUY BTS Price field

**First Issue**
The cursor appears to the left of the zero. This isn't a huge issue, but it would make more sense for the 0 to either be removed onFocus or to place the cursor to the right of the zero.

**Second Issue**
if the user types a decimal it appears as expected, however, if the user types a decimal a second time, it is removed. A better behavior would be for a second decimal press to be ignored. The user should be required to delete the decimal.

**Third Issue**
If the user places his/her cursor to the right of the initial 0 and presses the decimal, the cursor moves to the left of the zero *without* adding a decimal.

**Fourth Issue**
Repeatedly pressing the decimal key, causes the a series of 3 actions to repeat
- Cursor to left of decimal
- decimal
- remove decimal + cursor to right of decimal

### Intended behavior
When the cursor is focused in any of these fields, it should be right justified initially. If it's my intention to set a price of 1, I'm forced to delete the 0 to avoid ordering at 10. Once a user begins to type, I'm of the opinion that the zero should immediately be replaced with whatever value the user types, be it any integer or a decimal. If the user were to type a decimal, as their first character, the zero should disappear in that case as well. If the user types the decimal in error a second time, this input should be ignored.

**Comment by wmbutler** [comment]
This is looking pretty good, just one small fix to resolve the issue of multiple decimals in a number field on the exchange:
![screen shot 2017-05-31 at 12 57 37 pm](https://cloud.githubusercontent.com/assets/1254810/26643900/e169006c-4600-11e7-8bbc-1d1a203c9fc7.png)

**Comment by calvinfroedge** [comment]
This PR should resolve the issue https://github.com/bitshares/bitshares-ui/pull/219
