### ISSUE TITLE
[1.5] Node Switcher Design Pattern

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1372]
@startailcoon @ahdigital The design pattern for the switcher is strange.

- [ ] I think the switcher icon is a little ambiguous. If you can think of something to fine tune it, please do so. If not, it's probably ok. I'd almost suggest that the 
- [ ] The description of the node and the switcher icon could use a few more px of breathing room
- [ ] After selecting the new node, can we avoid sending the user to the other selector. It's really weird to have the "Add Node" option at this point and I think new users will scratch their heads. Once the user selects the new node, just pick it... don't go to the other node screen.
- [ ] Should the mini picker node list in the lower right appear onClick instead of onHover?

![switcher](https://user-images.githubusercontent.com/1254810/38175826-639b6cf4-35a8-11e8-87d8-e69cded72f25.gif)

- [ ] There is no way to activate a node from this screen... it should be possible I think.

<img width="1056" alt="screen shot 2018-04-01 at 12 29 16 pm" src="https://user-images.githubusercontent.com/1254810/38175827-69ad77fe-35a8-11e8-8130-cf73d98bf06d.png">

**Comment by startailcoon** [comment]
> After selecting the new node, can we avoid sending the user to the other selector.

This was not happening when I created this. It needs some debugging from a socket point of view. 

> The description of the node and the switcher icon could use a few more px of breathing room

Agreed

> There is no way to activate a node from this screen... 

Not sure I understand your statement. You activate a node by clicking the arrows, as detailed in the UI work I was acting upon in #1223

**Comment by sschiessl-bcp** [comment]
The hide button also is a text button. I would suggest either having both text buttons, of both icon buttons.

I would prefer both text buttons, but if it should be an icon: is there a symbol that looks like the one for the connected node just with a broken chain?

**Comment by wmbutler** [comment]
>> There is no way to activate a node from this screen...

> Not sure I understand your statement. You activate a node by clicking the arrows, as detailed in the UI work I was acting upon in #1223

Yes, my bad. I guess I think that the switcher icon is not obvious enough.

**Comment by ahdigital** [comment]
The broken chain icon should be used for 'reconnect' as shown in #1223.

It's a shame about the switch icons in the pop up. I think they're cleaner in style than having a button with text, especially since the colors denote the connection strength.

If we have to use buttons, I'd suggest using the smallest size and the button text be 'Use'.  On the node list page the 'Hide' text could be placed inside a hollow button.

One thing I just spotted that I didn't catch in the original issue is that the active node has a 'Hide' link, which seems unnecessary considering an active node cannot be hidden.

**Comment by sschiessl-bcp** [comment]
I will make a suggestion on the icons

**Comment by sschiessl-bcp** [comment]
Here are two, but the arrow is probably not necessary (but it was my first draft so I wanted to show)
![image](https://user-images.githubusercontent.com/33128181/38236374-3ecc7e5e-3724-11e8-81bb-e29081665fb7.png)

Here without
![image](https://user-images.githubusercontent.com/33128181/38236407-57bf1908-3724-11e8-9b08-a950c6a28fc4.png)

Creating new icons was very straightforward, I like that they are all available as .svg.

**Comment by sschiessl-bcp** [comment]
Here with Icon replacement for Hide / Show
![image](https://user-images.githubusercontent.com/33128181/38239927-72aba47a-372e-11e8-9e52-9ad2819ebe1e.png)

![image](https://user-images.githubusercontent.com/33128181/38239948-7cb3fe9a-372e-11e8-9df9-199f7a838bf3.png)

Question:
Connect button with or without arrow?
Are the eyes striked on hidden or available page?

**Comment by sschiessl-bcp** [comment]
@startailcoon I hope it was ok I jumped in here

**Comment by ahdigital** [comment]
My original iconography choice was intended to compliment the terminology 'switch nodes'. Also, we use the same icon on the exchange, to *switch* paired assets.

I'm not convinced the connect / disconnect icons (without arrow) to switch nodes will make complete sense to users. In the popup for example, it looks like the buttons will cause a disconnect.. ranging in severity.

Rather than stacking the icons, can we have them inline per the examples I did in #1223.

Eye icon should be blue.

**Comment by sschiessl-bcp** [comment]
Ah I see, I just saw the reconnect icon there.

My idea was to have a consistent look and feel for "connect to" and "connected" node. I see the current icon more as flipping which I personally found not appropriate.  But I am happy to put any icons there or leave the current one, I can also do the svg if you point me in the right direction or with a mockup

**Comment by sschiessl-bcp** [comment]
I am almost done, just need feedback on the icons.

I have also found a bugs: hidden personal nodes have disappeared. are now still displayed in personal, but as hidden

**Comment by sschiessl-bcp** [comment]
I added now three new icons: connect, connected, disconnected.

My design of those icons is as follows:

disconnected (visible for all not connected nodes)
![image](https://user-images.githubusercontent.com/33128181/38487373-314ab9a6-3be0-11e8-9c7d-f1cc0a704c9b.png)

connect (visible on hover)
![image](https://user-images.githubusercontent.com/33128181/38487435-67597b40-3be0-11e8-8c45-d9184e3b92f1.png)

connected (visible on active node)
![image](https://user-images.githubusercontent.com/33128181/38487456-78465eb4-3be0-11e8-933d-b2a8944e21f3.png)

I do a pull request now, those three icons can be easily redesigned now if deemed necessary.

**Comment by sschiessl-bcp** [comment]
The behavior of the footer connection overview is still onHover.

@wmbutler What exactly do you mean with 
" The description of the node and the switcher icon could use a few more px of breathing room"

**Comment by startailcoon** [comment]
@sschiessl-bcp Please address this issue on the personal node section

![image](https://user-images.githubusercontent.com/12114550/38888519-28c9a9de-427c-11e8-932e-390a32961f79.png)
