### ISSUE TITLE
[1.5] Typeahead tweaks

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1375]
If I use the typeahead to discover a new user, it gets added to the list when I search in the same session a second time. 

- [ ] The new user should be added to the list if I choose to add contact, not because I happened to choose them at one point.
- [ ] The color to the top right of the input field (LIFETIME MEMBER, etc) should be green for trusted (added) accounts.

![send](https://user-images.githubusercontent.com/1254810/38176378-2f5f0ab2-35b3-11e8-840c-1fe89b0145ab.gif)

**Comment by gibbsfromncis** [comment]
It would be nice to fix field's "jumping" when user clicks on it too 😃

**Comment by startailcoon** [comment]
I'll take this. I agree that the typeahead shouldn't view your last searched input. I'll if I can fix that jumping as well.
