### ISSUE TITLE
Voting for a Proxy UI

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#138]
### Reproduce

The confusion seems to stem largely from the **Goto** control next to the manual input field. I think eliminating this button would be an easy improvement. The pattern that's easy to fall into if I were to vote for `xeroc` would be to:

- Click `Set` next to xeroc's Known Proxy
- Click `Goto`
- Click `Publish Changes`

Unfortunately, the UI sends the error: `cannot proxy to yourself`

The confusion is further amplified by the fact that it appears I am still on my account when looking in the upper right corner of the UI where my name is present, but not on my account looking at the left nav bar where xeroc's name is present.

![screen shot 2017-05-09 at 1 21 49 am](https://cloud.githubusercontent.com/assets/1254810/25836569/eb705e6e-3455-11e7-90c0-946e25f3cea5.png)

I'd propose the following:

- Remove the Goto button from the input field
- Remove label **PROXY VOTING ACCOUNT**
- Add label above input field **Manually enter an account as your proxy**
- Modify label **Known Proxies** to read: **Choose an account as your proxy**
- It might also be nice to show a message once the field is populated that your changes will not take effect until the user clicks publish changes above.

**Comment by grctest** [comment]
I agree, I found the 'Go To' button confusing.

Relevant proxy UI issue: https://github.com/bitshares/bitshares-ui/issues/135
