### ISSUE TITLE
Buying Margin Calls NOT Also Buying Lower Asks First

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#1387]
If there is a yellow margin call and asks lower than the price of the margin call then clicking on the margin call and buying it will not buy the lower asks first and then use the rest of the capital to buy the margin call. It just buys the margin call and ignores lower asks.

This is not what is intended, is it? When you click on the order book to choose the price it is suppose to buy the lowest ask first then higher then higher until it reaches your price.

**Comment by abitmore** [comment]
https://github.com/bitshares/bsips/blob/master/bsip-0033.md

**Comment by landry314** [comment]
not clear if this means wontfix or that it is under discussion for the core or that is in the process of being changed.

**Comment by abitmore** [comment]
It can be seen as a core issue.
