### ISSUE TITLE
Automatic switching bug

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1388]
When I toggle automatic switching on or off
![image](https://user-images.githubusercontent.com/33128181/38233586-4d05b372-371b-11e8-8bfa-e713fb9254f7.png)
 I often get the following error 
![image](https://user-images.githubusercontent.com/33128181/38233546-2aa8f640-371b-11e8-83a4-8bbe9700a0ec.png)

Anyone else getting that?

**Comment by sschiessl-bcp** [comment]
I have no account created yet, so AccountStore.getState().currentAccount in BrowserNotificationsContainer is null.

**Comment by svk31** [comment]
I saw this a few times too but thought I already fixed it. Would be helpful if you could click where it says BrowserNotifications.jsx:62 and show me the line where that takes you.

**Comment by sschiessl-bcp** [comment]
Its in line 42, I added that it also checks if props.account exists

**Comment by svk31** [comment]
Oh of course, I didn't notice that it's also doing `this.props.account.get`, not just `nextProps.account.get`
