### ISSUE TITLE
[1] Hot Switching between accounts and proxy interface

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#139]
If a user has multiple accounts in their wallet and uses the dropdown to switch between them, the value for proxy is being carried across rather than being read from the blockchain.

### Reproduce
- Account A has **no** proxy set
- Account B has a proxy set
- On account A, navigate to the Voting / Proxy area
- Hotswitch to account B. Even though Account B has a proxy set, it will still show the same values.
- Prove it by clicking Open Orders and then Voting. The proxy screen will update properly.

![screen shot 2017-05-09 at 1 47 20 am](https://cloud.githubusercontent.com/assets/1254810/25837060/7d0ed370-3459-11e7-8a9a-059ef3c618c4.png)

**Comment by wmbutler** [comment]
Time allocated here reflects a rip and replace to account switching. This needs some serious attention.

**Comment by calvinfroedge** [comment]
Issue is related to not updating state when props change on voting proxy component. 

![issue-139](https://user-images.githubusercontent.com/632938/29439794-d02498ee-8385-11e7-9644-7e746a1c4bbf.gif)

Resolved by [PR 282](https://github.com/bitshares/bitshares-ui/pull/282).
