### ISSUE TITLE
[.5] Test and add apasia.tech API nodes

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1390]
As pinned in https://t.me/Bitshares_Traders:

wss://new-york.bitshares.apasia.tech/ws
wss://us-la.bitshares.apasia.tech/ws
wss://atlanta.bitshares.apasia.tech/ws
wss://dallas.bitshares.apasia.tech/ws
wss://miami.bitshares.apasia.tech/ws

**Comment by abitmore** [comment]
More nodes: https://steemit.com/bitshares/@apasia.tech/update-bitshares-massive-infrastructure-upgrade-public-demo-available-now

**Comment by sschiessl-bcp** [comment]
Do they want to be added to the reference wallet?

**Comment by abitmore** [comment]
Just some info here:

I meant to add the nodes in PR #1423 (actually had once added already), but in last check found too many nodes were down. Since I don't know when they will be ready, I removed them afterwards.

It's been 10 days after the announcement, and status of most nodes are "OK" in the announcement, I didn't realize that they're still under deployment.

@apasia-tech Please leave a comment here when you have more info/news. Wish the nodes will be ready before next release. I can readd them at any time.

**Comment by abitmore** [comment]
@apasia-tech any update please? We're about to make the new release. May I ask, add your nodes in this release, or not? Thanks.
