### ISSUE TITLE
[.5] Test and add API nodes provided by witnesses

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1391]
According to https://bitsharestalk.org/index.php?topic=23737.msg317500#msg317500, the new ones include:

witness.yao：wss://kimziv.com/ws .   Singapore
xn-delegate:  wss://api.btsgo.net/ws Singapore
magicwallet.witness:  wss://bts.open.icowallet.net/ws Hangzhou China
delegate-zhaomu: wss://blockzms.xyz/ws USA
crazybit:  wss://crazybit.online China
witness.hiblockchain: wss://api.bts.ai Beijing China
xman:  ws://newapi.bts.ai Beijing China
witness.still:  wss://bitshares.cyberit.io  HongKong
clockwork: wss://bts-seoul.clockwork.gr (Seoul)

**Comment by ryanRfox** [comment]
PR #1393 for fox: wss://api.bts.network East Cost, USA

**Comment by sschiessl-bcp** [comment]
Is there a standard testing method for nodes?

Latency checks, stability checks, https checks, ... ?

**Comment by jademont** [comment]
Update:

witness : location : API

in.abit :USA：wss://api.bts.mobi/ws

witness.yao : Singapore://kimziv.com/ws

xn-delegate Singapore：wss://api.btsgo.net/ws

crazybit : China : wss://crazybit.online

winex.witness : China: wss://ws.winex.pro

delegate.freedom :China： wss://freedom.bts123.cc:15138

witness.hiblockchain：China: wss://api.bts.ai

witness.still : Hongkong: wss://bitshares.cyberit.io

abc123 :Hongkong: wss://bit.btsabc.org/ws

xman :Japan: wss://ws.hellobts.com

ety001 : China: wss://bts.to0l.cn:4443/ws

delegate-zhaomu :USA: wss://blockzms.xyz/ws

magicwallet.witness : China: wss://bts.open.icowallet.net/ws

**Comment by wmbutler** [comment]
I think @litepresence has an interesting test script.

**Comment by elmato** [comment]
PR https://github.com/bitshares/bitshares-ui/pull/1399 for **elmato**
[wss://api.btsxchng.com](url)
_Global (Asia Pacific (Singapore) / US East (N. Virginia) / EU (London))_

**Comment by roelandp** [comment]
roelandp: Canada: wss://btsws.roelandp.nl/ws

**Comment by startailcoon** [comment]
Already in the list, but I'll add myself in this thread for information.

sc-ol : Europe, Germany, Munich : wss://bitshares.crypto.fans

**Comment by litepresence** [comment]
I show 64 responding to east coast US with good data:

https://pastebin.com/GQit1h1E

full test

**Comment by clockworkgr** [comment]
No reason keeping this open.

Let's just make a note in the readme for witnesses to place a PR as needed.
