### ISSUE TITLE
[2] Failed transaction prompt after successful send modal tx?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1392]
![image](https://user-images.githubusercontent.com/15861527/38249246-ed932ac8-3742-11e8-94ac-031aa53874bc.png)

Sent tokens from account A to account B using the new send modal, tokens moved successfully, switched to account B (within the same browser tab, using the account drop down menu) then shortly there after the above prompt shows.

Proof tx worked:
![image](https://user-images.githubusercontent.com/15861527/38249362-58e5c182-3743-11e8-914d-67f988747e1a.png)

It's not that big of a deal, more confusing than anything else.

Cheers!

**Comment by wmbutler** [comment]
This will be hard to reproduce but I will allocate time for testing per your description.

**Comment by startailcoon** [comment]
I can confirm this. When issuing market orders with one of my accounts I get this a few seconds after the market views my buy order in the list. 3 out of 3 buy orders did this. I was on the same account during this time.

**Comment by svk31** [comment]
@sschiessl-bcp I'm guessing this is related to the WalletUnlockModal changes you made

**Comment by sschiessl-bcp** [comment]
I ll be happy to look into it, but probably wont be able before monday (enjoying some holiday right now)

**Comment by grctest** [comment]
Several users have been complaining about this on Telegram recently

**Comment by sschiessl-bcp** [comment]
I can't reproduce the error, any further intructions on how to?

**Comment by abitmore** [comment]
@clockworkgr I don't think that's related.

**Comment by startailcoon** [comment]
Last week I had this almost every order I placed, while on mobile though and on the wallet Web page. This week I haven't been able to reproduce it again.

**Comment by sschiessl-bcp** [comment]
I tried again to have this popup appear, but I can't ...

@grctest does this still happen for you?

**Comment by grctest** [comment]
Not able to replicate, but it was frequent last week. Perhaps it was an API node issue? 😕

**Comment by startailcoon** [comment]
I had this happening to me again yesterday, using wallet.bitshares.org on mobile.

Today, not an issue.

Seems very irregular. We need to narrow it down to some details to track the cause of it.

I've yet to see this on a desktop.

**Comment by grctest** [comment]
Had this occur again in chrome, cancelled a buy order and this popped up. Shortly after completing a transfer it also occurred stating that the tx hadn't been successful. Here's a screenshot:

![image](https://user-images.githubusercontent.com/15861527/39096086-08d929fe-4643-11e8-978a-da3e80686064.png)

**Comment by wmbutler** [comment]
Thanks for the console log.

**Comment by startailcoon** [comment]
I believe this is no longer an issue as none has reported it in for almost 2 months now.
