### ISSUE TITLE
[1] Issue asset is broken

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1395]
Didn't work for someone, see here

https://bitsharestalk.org/index.php?topic=26240.msg317552;topicseen#msg317552

**Comment by wmbutler** [comment]
Agreed. It appears to be broken.

![issue](https://user-images.githubusercontent.com/1254810/38271899-4f373166-374d-11e8-9449-71bbf79dff90.gif)

**Comment by svk31** [comment]
Can you please just describe the issue and copy paste or take a screenshot of the console log error messages? These gifs are more frustrating to watch than helpful.

**Comment by svk31** [comment]
@startailcoon It seems to be caused by recent changes in AccountSelector, can you take it?

**Comment by startailcoon** [comment]
@svk31 I'll take a look at this.

**Comment by startailcoon** [comment]
Please post a lice cap. This issue should be fixed.

**Comment by osoese** [comment]
I think the issue was fixed but not released - I had to go back to an earlier version to issue an asset. Will do a screen capture gif tomorrow

**Comment by osoese** [comment]
![image](https://user-images.githubusercontent.com/31746846/38915514-fa37c85e-42b1-11e8-8128-9cfaaad78ac1.png)

**Comment by startailcoon** [comment]
I don't doubt that you have an issue, but I do doubt that you use the latest version of the UI as the buttons aren't looking as they should. They where changed in the latest release.

![image](https://user-images.githubusercontent.com/12114550/38951940-61234028-434a-11e8-9edb-a814c4966c27.png)
