### ISSUE TITLE
[1] Display date and time rather than relative time in the activity Tab

### ISSUE THREAD

**Issue by mattbeckman** [bitshares/bitshares-ui#1396]
The timestamp isn't displayed via tooltip when hovering over the simplified "Time" field in account Activity. The markup includes a data-tip attribute with the timestamp, but it is not displayed.

![bts-20180403](https://user-images.githubusercontent.com/928380/38270384-1cace2d2-3738-11e8-98d0-dfa054a02f43.gif)

**Comment by wmbutler** [comment]
Can we alter this issue to change the time to an actual date and time rather than a relative time?

**Comment by abitmore** [comment]
@wmbutler I agree.

**Comment by startailcoon** [comment]
If we display relative time, we could remove the tooltip altogether I suppose

**Comment by startailcoon** [comment]
Using locale specific date format, as on the Exchange Tab.
Is this satisfactory?

![image](https://user-images.githubusercontent.com/12114550/38330902-17958842-3852-11e8-9314-beca74f137a5.png)

**Comment by wmbutler** [comment]
Not to overcomplicate this but:

- [ ] ISO Date format

The ISO date format
The international format defined by ISO (ISO 8601) tries to address all these problems by defining a numerical date system as follows:  YYYY-MM-DD where

YYYY is the year [all the digits, i.e. 2012]
MM is the month [01 (January) to 12 (December)]
DD is the day [01 to 31]
For example, "3rd of April 2002", in this international format is written: 2002-04-03.

- [ ] Time should be hh:mm:ss

**Comment by abitmore** [comment]
For more convenience, perhaps better show time in the user's timezone rather than UTC.

**Comment by happyconcepts** [comment]
Better show the year.

**Comment by startailcoon** [comment]
So, after all we should display it like `2018-02-01 22:12:12` with appended timezone name, like 'UTC', 'GMT', 'EST' etc as time is displayed in local time rather then UTC+/-X

**Comment by wmbutler** [comment]
Sounds like a plan.

**Comment by startailcoon** [comment]
### Fixed

- Now displaying the full date with timezone included. Equal to `%F %T %Z`

![image](https://user-images.githubusercontent.com/12114550/38453093-573cd50e-3a50-11e8-9669-d7ae1345d23d.png)
