### ISSUE TITLE
[3][happyconcepts] Order Expiration Date bug

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1397]
OSX, latest, Chrome Browser

## Problem

It appears that the order expiration is off by the timezone difference. In This case, it is 7:18 pm. I chose a 12 hour expiration. The confirmation modal displays 12:18 AM CDT.

![houra](https://user-images.githubusercontent.com/1254810/38282202-8372d0c6-3774-11e8-93f4-1e306864a4f9.gif)

## Expected Behavior

My current time + offset chosen = Time displayed on modal.

**Comment by gibbsfromncis** [comment]
@wmbutler what is your timezone?

**Comment by wmbutler** [comment]
CDT as displayed.

**Comment by sschiessl-bcp** [comment]
@gibbsfromncis Is this fixed?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp it want you can take a look this one. I have no idea why it happens ... It looks like bug not on my side

**Comment by happyconcepts** [comment]
I can take it. 😀

**Comment by gibbsfromncis** [comment]
@happyconcepts I'm sorry but @sschiessl-bcp messaged me on telegram he will work on it

**Comment by happyconcepts** [comment]
Ok thank you for telling me.

**Comment by happyconcepts** [comment]
I would like to claim this @gibbsfromncis @wmbutler. 

I fixed it 2 weeks ago only to be told that @sschiessl-bcp was assigned. Yes feels unloved.

**Comment by sschiessl-bcp** [comment]
If you already have a fix I think everyone would understand if you simply present it and inherently claim it the issue, even if you hear someone else gets assigned.
We don't want to do double effort. 

Anyways, I apologize for not working on it even though being assigned, I will do better next time.

**Comment by wmbutler** [comment]
Increased the issue by an hour to allow for some testing.

**Comment by happyconcepts** [comment]
Thank you, slate for sprint 0515 please.

**Comment by happyconcepts** [comment]
Yes, I was going to add it to the same PR tomorrow to make it easier for merge.
