### ISSUE TITLE
AGRS address not valid in withdraw modal

### ISSUE THREAD

**Issue by MarkoPaasila** [bitshares/bitshares-ui#1398]
Trying to withdraw OPEN.AGRS from the current GUI (2.0.180402), the modal doesn't accept a correct BTC address. AGRS is an Omnilayer asset, which use BTC addresses on the BTC blockchain. Openledger.io interface accepts a correct address.

**Comment by startailcoon** [comment]
This issue is due to an error in the Withdraw Address checker that is called from the Withdraw Modal. It sends the wrong parameters to the checker URL on the gateway system, making it always fail.

This has been fixed in PR #1383.
