### ISSUE TITLE
[1][svk] Accuracy issue about getSqueezePrice() function

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1406]
[Code](https://github.com/bitshares/bitshares-ui/blob/a5ddd816ae60db50fca5aa4a2dae0164dcf8b6dd/app/lib/common/MarketClasses.js#L405):
```
    getSqueezePrice({real = false} = {}) {
        if (!this._squeeze_price) {
            this._squeeze_price = this.clone();
            if (this.inverted)
                this._squeeze_price.base.amount = Math.floor(
                    this._squeeze_price.base.amount * this.sqr
                );
            if (!this.inverted)
                this._squeeze_price.quote.amount = Math.floor(
                    this._squeeze_price.quote.amount * this.sqr
                );
        }

        if (real) {
            return this._squeeze_price.toReal();
        }
        return this._squeeze_price;
    }
```
The two `Math.floor` calls led to loss of precision.

To be accurate, the final price should be:
* `base.amount = base * 1000`
* `quote.amount = quote * (sqr*1000)`
But be careful about integer overflow issue (the back end temporarily uses 128-bit integers to get around the overflow issue, although also has accuracy issue when finally converting to 64 bit).

#1401 is related.

**Comment by arminnaderi** [comment]
To solve overflow issue maybe we can use BigInteger class?

**Comment by abitmore** [comment]
@wmbutler it's not a serious issue IMHO, so no need to be labeled as high priority.

**Comment by svk31** [comment]
The reason I use Math.floor is that you regularly get decimals when multiplying the sqr by the base amount, but the new base amount should be an integer. Are you saying it should be rounded up instead of down?

**Comment by svk31** [comment]
Ok I think I get your point @abitmore: multiply both by 1000 to keep the same ratio but remove the decimals. I still have to do a Math.floor because javascript floating point multiplication is shit, but it won't round down the way it did before.

**Comment by clockworkgr** [comment]
I've been working with price multiplication/division in JS as part of porting xeroc's pricefeed script to JS.

The way I handle it/optimise it is do the multiplication, get the precision of the result, multiply both base and quote amounts by 10**precision to convert base back to integer, run a GCD calculation between base and quote and divide both by the GCD to get an "optimised" pair of base/quote integers...

See here: https://github.com/clockworkgr/bitshares-pricefeed-js/blob/master/lib/Price.js#L30-L46

**Comment by abitmore** [comment]
Yes, dividing by GCD will improve a bit, lead to less possible to overflow in future calculation.
