### ISSUE TITLE
[5.5][sschiessl-bcp] Node Latency and reconnect strategy

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1407]
Quoted from Telegram channel:
>when I run a "latency test" I use the same calculation; handshake.  Typically a 1-3 seconds per node; but upon connecting to a low latency node each subsequent call is about 0.125 seconds, which is what I report as latency in microDEX
In the absence of statistical approaches, I think it would be helpful in the very least, for the reference UI to update the latency number in the lower right, upon each orderbook update, with the time it took to make that orderbook call.  It would also be of use to have a "last update" live ascending second counter, for time since last successful ping.  Also, a blocktime latency to show if the data being displayed is in fact not stale.  In the absence of such, any time the orderbook is not moving the user is left not knowing... is it 30 seconds old?  30 minutes old?  3 hours?  ???!?
A combination of these ascending metrics would at least give an overall user experience of an application which is "alive"
this, though... is useless
![image](https://user-images.githubusercontent.com/9946777/38427731-509576fc-39ba-11e8-9dfd-68ac0593197a.png)
disconnected since when?  should I wait for it to reconnect on its own?  should I fiddle with buttons until better?
what is the correct block number?
there is no real information provided by that metric; no real reason for common user to even know the block number.
my point being, that even a stale blocktime there would be much more useful than a stale block number
at least I could quickly compare the stale blocktime to my computers clock
stale block number could mean anything and until it changes again I'm left watching it and losing confidence

**Comment by wmbutler** [comment]
When in disconnected state, we should know this and should run a function capable of reconnecting to the socket.

I have another piece of software that can lose the socket. When it does, and the widow is hidden in a tab, the socket does not attempt to reconnect, but when the user makes the browser tab active, it triggers a reconnect function. This is a pretty nice feature for relieving sockets and only connecting when a user is observing the page.

**Comment by wmbutler** [comment]
Let me see if I can capture the output from a session on reconnect. It's zube.io if you can get a trial account. You can create a few issues on a sprint and then leave the tab for a few hours. Come back and observe the behavior. It's very consistent in it's sleep and reconnect.

**Comment by wmbutler** [comment]
Interesting. It's not actually a websocket so I guess that doesn't apply. So the approach will need to be different.

**Comment by sschiessl-bcp** [comment]
I will do a PR for this when #1394 is merged

**Comment by litepresence** [comment]
I am currently using this to reconnect:

https://pastebin.com/MtcDE6nR

I test ping, blocktime, chain id, and zero price to confirm good handshake

**Comment by startailcoon** [comment]
@sschiessl-bcp will you work on this as mentioned here before?

**Comment by sschiessl-bcp** [comment]
Yes ... I simply forgot about it, apologies.

**Comment by sschiessl-bcp** [comment]
Fixed couple of things in the branch. I will also add that the reconnection only triggers when the user is actually looking at the screen.

Also addresses #1443, I have implemented incremental pinging and adds a Ping nodes button. Spent 4.5 hours so far.

Following questions I have:
- the reconnection only triggers when auto selection is on
- on startup quick ping strategy is used, when user clicks button the incremental ping strategy is that is slower but gives more accurate results (apparently too many connections at the same time tend to fail more often)

Should it be like this, or should this be configurable?

**Comment by sschiessl-bcp** [comment]
Added connectivity check when user switches between tabs / was idle. Tried manual implementation on blur/focus until I found ifvisible package, roughly an additional hour.

**Comment by sschiessl-bcp** [comment]
@wmbutler please include in 180721 invoice

**Comment by wmbutler** [comment]
This is such an important issue. Thanks for your work on it.
