### ISSUE TITLE
The possibility of blocking some BTS amount

### ISSUE THREAD

**Issue by apiekarczyk** [bitshares/bitshares-ui#1412]
The problem is:
When one want to sell all balance of BTS it is highly recommended to leave some amount of BTS to have possibility to do someting more on bitshares wallet. So, when I click 'balance' on 'sell bts' I have to edit the 'quantity' to not sell everything of my BTS. When market is 'on fire' it's very easy to make a mistake. It's time consuming also, not to mention about irritation. It would be nice to set somewhere in settings or maybe in 'sell bts' area an amount of bts 'not for sale' to save time and avoid mistakes.
Thank you.

**Comment by startailcoon** [comment]
What about if we add a setting to the account with something like this?
These are just suggestions, we need to find a few good options.

#### Minimum BTS reserved for fees
- 10%
- 5%
- 1%
- 10 BTS (Default)
- Disabled (not recommended)

**Comment by wmbutler** [comment]
I don't think we even need to make it a preference. We can just maintain 10bts in the account under these circumstances. This should be for trades only. If users wants to send/withdraw all of their BTS they should be allowed to do that.

**Comment by startailcoon** [comment]
> This should be for trades only.

This sounds like a good plan. I do think we should explain this somewhere, like on the help page of for example https://github.com/bitshares/bitshares-ui/blob/staging/app/help/en/dex/trading.md

**Comment by wmbutler** [comment]
Wait, it just occurred to me. What if the user has exactly 10BTS in their account and they try to trade 8 BTS? Will it tell them they don't have enough? Need to clarify this edge case.

**Comment by wmbutler** [comment]
@apiekarczyk I think you will need to clarify your statement because I am unclear on how this would work.

**Comment by apiekarczyk** [comment]
Something like this:

![block-bts](https://user-images.githubusercontent.com/35542307/38721657-531a6ee6-3efb-11e8-9fe7-8f640679cf14.JPG)

**Comment by landry314** [comment]
I wouldn't call it "block", reminds me of blocking a phone number or blocking a player in sports.

I would call it "preserve" or "save".

**Comment by wmbutler** [comment]
Understood, but what happens now when I try to sell 5 BTS?

**Comment by apiekarczyk** [comment]
simply write 'zero' in the edit area

**Comment by apiekarczyk** [comment]
And maybe one more thing... when somebody is doing many different actions may not pay attension that BTS amount for fees is going to very low level. Maybe there should be an "warning light" somwhere in the UI to warn about it.

**Comment by wmbutler** [comment]
I really don't think we are solving a problem here. Feels like we are creating one.

**Comment by landry314** [comment]
This is a serious issue. It appears the bitCNY fee pool is malfunctioning. I have had many errors not being able to cancel an order if all my BTS is locked up in it.

**Comment by wmbutler** [comment]
So then the user can't make trades when they are down to 5 BTS. Exact same problem. The user will either have to locate some obscure setting to free up the 5BTS or sell an asset to get > 5BTS.

**Comment by landry314** [comment]
i see that problem... but this is a bigger one. i had my funds all locked in an order and had to transfer less than 1BTS i happened to have in another account. i would have been screwed otherwise.

just have a condition if BTS is less than a certain amount then ignore the locked BTS setting, no?

**Comment by happyconcepts** [comment]
I think removing the cancellation fee altogether for Dex orders should be considered. 

Improved liquidity > spam potential

If cost is an issue, then increase the order fee to compensate.

Why not?

**Comment by happyconcepts** [comment]
Or could the chain allow cancellation without a fee for orders that will result in a zero balance of BTS?

**Comment by wmbutler** [comment]
This has been debated, but as you suggest, it's a core debate. We would of course comply with whatever decision was made. Seems to me that 0 fees could create a spam issue whereby someone could spin up hundreds of thousands of spam bots to bring down the network with no repercussions.
