### ISSUE TITLE
[5] Gateway Wiki Details Page

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1417]
Creating a Wikipage for the different ways a Gateway can be implemented in the UI.

Today we have a few different ways that require different levels of data.

As we have an ongoing process of making it easier to adding new gateways, it's important that the process is well documented and explained.

Expecting roughly 5 hours for this.

**Comment by wmbutler** [comment]
What if you describe a single way to do it with a standard recommended data feed.

**Comment by startailcoon** [comment]
That is my intention. We have a few ways today that is used, but we can condense it to two different types pretty much.

I'm still documenting all the ways, but we will have a simple, clean and easy way for new gateways to configure their systems for the UI.

**Comment by startailcoon** [comment]
## Full Gateway Integration Requirements

The documentation is now available on 
https://github.com/bitshares/bitshares-ui/wiki/Gateway-Integration-Requirements
