### ISSUE TITLE
Issue Asset button unresponsive on web wallet

### ISSUE THREAD

**Issue by blahbax** [bitshares/bitshares-ui#1419]
Trying to issue a UIA on wallet.bitshares.org and Issue Asset button does nada. Often get issues like this when when having node problems, but can see the blockcount ticking up in the bottom corner so doesn't appear to be network related. 

To clarify, the first instance of "Issue Asset" brings up the dialogue successfully, but the button in the dialogue does nothing.

**Comment by startailcoon** [comment]
Same as #1395, which is fixed for next release.
