### ISSUE TITLE
[1] Preferred Market Pairing Resets to null When Updating UIA

### ISSUE THREAD

**Issue by blahbax** [bitshares/bitshares-ui#1420]
Preferred market pairing resets to null when updating UIA. Occurred on wallet.bitshares.org and openledger.io so not sure if UI or core issue.

**Comment by startailcoon** [comment]
Same as #1395, which has been fixed for next release.

**Comment by startailcoon** [comment]
Closed the wrong issue.

**Comment by startailcoon** [comment]
Do you mean that this field is always blank?
What I can see, changing market pairing works, just that the field isn't filled in with the current choice.
Please elaborate if this is not the issue you're having.

![image](https://user-images.githubusercontent.com/12114550/38822683-790697fa-41a4-11e8-867a-758a36939387.png)

**Comment by blahbax** [comment]
Yeah so what was happening was I could change pairing, but as the pairing
didn't persist as a placeholder; the next time I updated some other aspect
of the UIA, the pairing would reset to BTS.

Cheers.
