### ISSUE TITLE
Let the Markets tab be hidden

### ISSUE THREAD

**Issue by MarkoPaasila** [bitshares/bitshares-ui#1422]
I would like to be able to hide the MY MARKETS/FIND MARKETS tab in the EXCHANGE view. On a small screen or on a 1920x1080 display working with a spreadsheet sharing the screen the MARKETS tab forces essential information to be crammed - itself being non-essential. I usually don't even use it as I navigate to markets from my account's recent activity.

This is exaggerated but highlights how the markets tab dominates
![image](https://user-images.githubusercontent.com/6001014/38614173-d9ce940c-3d94-11e8-997a-c462877d810d.png)

Here's how I use it together with a spreadsheet. Because the SELL and BUY boxes are crammed, they are higher, and I need to scroll down to see MY ORDERS.
![image](https://user-images.githubusercontent.com/6001014/38614355-80e52d46-3d95-11e8-8611-c7dec8f5715f.png)

So I would like to either hide or shrink the MARKETS box. Even better if markets could be found using some kind of dynamic view like a dropdown or modal.

**Comment by wmbutler** [comment]
Would you want to hide the Market depth in the bottom right as well? Seems like the answer is yes, but wanted to clarify.

**Comment by startailcoon** [comment]
I agree with the poster, we need to be able to hide the side panel.

I advise we make it collapsible and just adds a little arrow out on the right side when it is hidden that makes it view again.

Any other suggestions?

**Comment by startailcoon** [comment]
I agree with you Bill. I see it like this.

1. User can view/hide the whole rights panel with the components.

2. User can hide/view components horizontally like we have the depth chart.

At least one component on the right side is viewable and they can reordered by the user.

As we now also have the market picker going, hiding the markets on the right side isn't an impossible scenario for a user, making the right panel the order book.

Ideas, suggestions?

**Comment by MarkoPaasila** [comment]
That idea sounds really good. I don't really have any opinion about the depth chart at the bottom. I use depth-chart as my main view anyways.

**Comment by startailcoon** [comment]
@MarkoPaasila I do that as well, the small one at the bottom is usually not something I look at anyway. But since it's there some users may use it more than we do.

This will also make it easier to navigate the dex on a smaller screen or phone in landscape since before you where forced to have the right menu if your screen "fitted it", which isn't always the case as we can see.

**Comment by wmbutler** [comment]
@ahdigital hopefully these conversation will help you in your design decisions.

**Comment by startailcoon** [comment]
Is this issue obsolete due to the work done on #1449 and #905?

@wmbutler, do we want this fixed now or do we want to wait for the new layout to take effect. As I can see in the new UX of #1449 there will be a hidden arrow. But that's just the UX, so it may be related to this issue?

**Comment by wmbutler** [comment]
Duplicate #1449

**Comment by startailcoon** [comment]
Will be fixed in issue #1477
