### ISSUE TITLE
Round the prices and values of new orders to 8 digits.

### ISSUE THREAD

**Issue by smogm** [bitshares/bitshares-ui#1429]
The Bitshares protocol is working with 12 digits floating point values.
The Bitshares UI instead only displays the typical 8 digits.

This leads to some confusing orderbook display, as it is possible to have multiple orders with different price (behind the 8th digit), which will be displayed in the orderbook as same 8 digit price number.

To solve this, the order form should round the entered numbers to fixed 8 digit values. Overflows should be removed from the order's value.

**Comment by svk31** [comment]
Rounding input prices is problematic and very hard to get right, since the actual prices are defined as integer ratios and can have arbitrary numbers of decimals. The rounding to 8 decimals only applies to the display values, the code works with integer ratios just like the backend.
