### ISSUE TITLE
Light Wallet doesn't recognize 'send to' accounts

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#143]
Often when trying to send, entering "poloniexwallet" or "bittrex-deposit" into the light client (bitshares.170508 Win64) I get the error "Unknown account".  I don't think it's limited to those accounts it seems to be near all accounts not specifically in my wallet are Unknown.

Sometimes reloading fixes this but most often not.  This problem does not appear to be in the webwallet(chrome/firefox)

**Comment by dnotestein** [comment]
I had the same problem with the web wallet, resolved it by reloading the page.

**Comment by svk31** [comment]
This is just an issue with API server latency since the GUI does a lookup to resolve names.
