### ISSUE TITLE
[5][ahdigital][10][gibbsfromncis]Develop Paging Module for Wallet

### ISSUE THREAD

**Issue by oflyhigh** [bitshares/bitshares-ui#1435]
In Bitshares UI (2.0.180402) and older version, when I go to "explore->Assets", it will load all SmartCoins assets by default, the same situation will occur for "User Issued Assets".

As we know, there are already a lot of SmartCoins and UIAs in Bitshares system, so to load and display all of them will take a long time and take up a lot of resources of computer.

So I think it should be a better way to load and display them page by page.

Thank you.

**Comment by wmbutler** [comment]
As discussed above, we need a paging module. Let's make sure it's ANT compatible. Features must include:

- [ ] 25, 50, 100 groups (default 25)
- [ ] Typeahead in header
- [ ] Next and previous groups (arrows)

We need UX followed by execution.

**Comment by abitmore** [comment]
Please make sure the back end provides required APIs. If not, please submit an feature request issue to bitshares-core.

**Comment by gibbsfromncis** [comment]
@wmbutler I've assigned myself and Dominic to this issue. Can you tell me please who's responsible of backend side so I can ask this guy about assets server-side pagination/filtering?

Also I suppose it should take less time than estimate for development. If It takes less time than estimate I'll let you know when finish this task.

I want to ask @ahdigital about full page redesign as we already have design system and style-guide. What do you think about it if @ahdigital will provide UX for:
1) Main Tabs (Blockchain, Assets etc.)
2) Assets Filtering tabs (I suppose we can replace it using dropdown)
3) Table with pagination & search 

@wmbutler Do you agree?

**Comment by gibbsfromncis** [comment]
@abitmore How can I get more than 100 assets? I'll take a look front-end part, maybe sb already done logic which can help me to get assets using limit & offset like to get assets from X to Y position. 

Thanks for your help

**Comment by abitmore** [comment]
@gibbsfromncis you specify a start point and get next 100. 
> @param lower_bound_symbol Lower bound of symbol names to retrieve

**Comment by gibbsfromncis** [comment]
@abitmore sorry I didn't get what is lower_bound_symbol. Does it mean I should put the name of any asset and I'll fetch assets beginning from this asset and next 100?

**Comment by abitmore** [comment]
@gibbsfromncis yes. But I noticed it's a bit stupid that the core has 100 as limit, which means the client can only get 99 items when query for the 2nd page. I'll submit an issue to the core to change it to 101.

**Comment by wmbutler** [comment]
We could limit pagination to 50 for now until the 101 limit is addressed.

**Comment by ahdigital** [comment]
Here is an example of a paginated table combined with filters; asset type, results per row and typeahead search. It is set within a page which uses a tab component to display child pages under the parent of 'Explore'.

Below the main mock up is what it would look like against the existing header.

### Explore using updated header

![explore with new nav v4](https://user-images.githubusercontent.com/3088454/39169866-4ee71be6-4791-11e8-917e-83d108e61ba6.png)

### Explore using existing header

![explore with existing nav v3](https://user-images.githubusercontent.com/3088454/39169907-65b97ad0-4791-11e8-83be-c29223ddd6b6.png)

### Filters on mobile

I suggest that on mobile we collapse table filters and toggle them open/closed. E.g.

![mobile filters](https://user-images.githubusercontent.com/3088454/39171014-6ed042ee-4795-11e8-8521-ae0114c3445e.png)

**Comment by gibbsfromncis** [comment]
@ahdigital can you please upload radio buttons solution too? I'm still sure it looks better 😃

**Comment by ahdigital** [comment]
The radio buttons solution @gibbsfromncis is referring to is below. Instead of simple radio buttons they're presented like a button bar. I don't think it's ideal because:

1) The buttons don't stack well on mobile when there are multiple, or when the button text is lengthy
2) Visually they appear like tabs, and we already have a tab component - we don't need multiple instances IMO

![explore with new nav v3](https://user-images.githubusercontent.com/3088454/39174073-8646348e-479e-11e8-81fe-d8b8c887b972.png)

**Comment by wmbutler** [comment]
Looking great.

- [ ] Either left justify or center the pagination controls?
- [ ] How about a 25 / 50 / 100 item chooser with 25 as the default?

**Comment by ahdigital** [comment]
I think your second point has already been included.

**Comment by gibbsfromncis** [comment]
@wmbutler If I understand correct we should wait for Trading View integration first before we continue with ant and this redesign.

@ahdigital if @wmbutler is OK we can create separate task for you about UX because implementation of this task may take some time and you will be paid not soon.

**Comment by wmbutler** [comment]
Groomed and ready.
