### ISSUE TITLE
[12][kapeer42][1][svk] Consolidate Wallet Login Types

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1437]
UX and previous discussion here: #895

**Comment by kapeer42** [comment]
can I claim this?

**Comment by startailcoon** [comment]
I'll keep it

**Comment by startailcoon** [comment]
@kapeer42, if you can handle it this sprint I can hand it over since I will  otherwise be able to complete this until next sprint as it looks now.

Go ahead and start working on it if you wish to do so.

**Comment by wmbutler** [comment]
@kapeer42 can you complete this by 180501?

**Comment by kapeer42** [comment]
yes

**Comment by wmbutler** [comment]
Awesome. Please try to get your changes up soon because we will want the group to test this thoroughly.

**Comment by wmbutler** [comment]
Moving this to 180515 to accommodate testing.

**Comment by svk31** [comment]
Added 1 hour to myself for the above commit which fixes some issues with wallet accounts remaining active when switching between modes.

**Comment by wmbutler** [comment]
@svk31 I don't believe there was any intention to allow for a backup download for cloud wallets, but maybe OP will have an opinion on this. I do think it's important to make it clear to cloud wallet users that their 'backup' is just the password that was assigned to them at account creation.

**Comment by wmbutler** [comment]
@kapeer42 sorry that this didn't get paid as part of the previous sprint. Closing it here so it will get paid.
