### ISSUE TITLE
Incorrect Password

### ISSUE THREAD

**Issue by GerryCallan** [bitshares/bitshares-ui#1439]
Hi there,

I've seen others ask this question in forums and chat rooms, regarding an 'Incorrect Password' error when logging into a cloud account (in my case from https://compumatrix.co). Is there any known fix for this issue? I know my password is correct - I have multiple backups all with the same password. I used the account on a daily basis up to December 2017 when I transferred assets to a different account, but still have some outstanding open orders in the one I now can't access. I've done nothing to change my password, but I'm now getting an 'Incorrect Password' error when I try logging in with what previously worked.

Any help or suggestions would be very much appreciated.

Thanks!

Gerry

**Comment by abitmore** [comment]
Backups? Of what? Make sure your password was for cloud wallet mode. Is it possible that your password has been changed by someone else? Afaik compumatrix used to have full control over some of their users' accounts via multi-sig settings, so was able to change passwords for them.

**Comment by GerryCallan** [comment]
Thanks for the response abitmore. The backups are of saved and stored passwords. I have several backups over the last year and I checked each of them to confirm that I was using the correct password, which I was. I just hadn't accessed the account since December past. No one else had access to it nor were permissions set for anyone to have multi-sig control either. All I really can say for certain is that the password is correct but no longer works. Thanks again abitmore. :)

**Comment by abitmore** [comment]
Perhaps you need to provide your account name (and maybe password) to a developer so he can help identify what's wrong. How to contact you?

**Comment by GerryCallan** [comment]
Thanks abitmore - if anyone can help I'm contactable at gerrycallan@gmail.com.

**Comment by clockworkgr** [comment]
Are you getting a prompt to enter both account-name and password?

**Comment by GerryCallan** [comment]
Hi clockworkgr, yes I'm getting the prompt. The account name is correct as it shows the member number which is correct (and has numerous transactions recorded in 2017), but the password is now 'Incorrect'. :(

**Comment by GerryCallan** [comment]
Hi clockworkgr. Unfortunately there is no backup (.bin) file for this account. All I have are multiple saved copies of the password, dating back to various backups I made over the last year. I would have logged into the account hundreds of times with the password which now no longer works.

**Comment by clockworkgr** [comment]
I'm afraid you're out of luck then...

Your password only worked while the browser had the wallet file (what you'd backup as a bin file normally) cached in local storage so the password could decrypt it.

Your cached wallet is now gone (clear cache in browser? reinstall? some reason anyway) so you're getting the cloud login prompt instead. The wallet local password obviously doesn't work there.

**Comment by GerryCallan** [comment]
Hi clockworkgr. There never was a .bin file. It was only ever saved, used or accessed using an Account Name and Password combination. It was opened on multiple browsers over the course of the year so I thought that having the username and password was all that was required. Apparently not. :(

**Comment by clockworkgr** [comment]
in that case, it was a cloud account...no idea what the issue could be...

on the off chance there has been an incompatibility created  by ui updates, try downloading a release from when you could last access it

**Comment by GerryCallan** [comment]
Thanks clockworkgr - I'll try that. Anything is worth an attempt at this stage! :)

**Comment by wmbutler** [comment]
@GerryCallan tell me what your password started with. This is a telltale as to whether it was a cloud or local account. Second question: Did you choose your password or was it assigned to you?

**Comment by GerryCallan** [comment]
​Hi Bill,

No it wasn't assigned. I used Keepass to generate the password:

065fa27d5fb60b20cee2f84c62c7536e28bc73e78e5758c1d3c9d17ea459c364

As you can see, I used a very long string for the password

Any help appreciated - I've downloaded an older version of the Bitshares
wallet to see if I can import it into it. :)​

Gerry Callan
Email: gerrycallan@gmail.com
Tel: +353 86 3884246
Skype: gerrycallan
Google Plus: google.com/+GerryCallan

**Comment by wmbutler** [comment]
@GerryCallan if you chose your own password, this means you were definitely using what we call the local wallet. This means that when you logged in, the browser had a local database with your encrypted keys in it. Without some form of that local database, it's going to be impossible to restore your account.

**Comment by abitmore** [comment]
If it's a local wallet, how could he had logged in with another browser? Perhaps actually he hadn't?

**Comment by abitmore** [comment]
@wmbutler what's the limit of the password input box? more than 64?

**Comment by GerryCallan** [comment]
Thanks for the responses. It was a cloud account originally registered via Compumatrix .. at the time I registered, 18th April 2017, I was prompted to create a password, which I did and saved in a couple of locations, one of which was Keepass. That same password worked daily all through 2017 until I transferred most of what was in that account to a new account in December. However some open orders remained in that account, so I went back to it yesterday to try and close one of them which is when I found I could no longer access the account. During 2017 I accessed the account using the password with both Firefox and Opera, but not Chrome (otherwise I would have saved the password there!). All I can say for certain is that I know the password is correct, but it no longer lets me in. Instead I get the 'Incorrect Password' error. :)

**Comment by GerryCallan** [comment]
FWIW I tried deleting the last character in the password all the way down till there were none left. None worked.

**Comment by svk31** [comment]
@abitmore There's no limit on the password, you can use a string 1000s of characters long if you want.

**Comment by GerryCallan** [comment]
Thanks svk31 - the account name is gerryc2017

**Comment by clockworkgr** [comment]
I did actually run through the private key derivation process step by step, including visiting UI codebase from when the account was created as well as bitsharesjs at the time (PrivateKey class) ...

Couldn't find any reason why it wouldn't work apart from the password being wrong.

It's always been sha256(account+role+password) everywhere.

Using the password provided I get to active authority:

BTS73Ff1ZMGvj2SGuEHMtYbqZuuUsHrNYjFosskhLHdEFbWQnQiNa

Instead of 

BTS8KSkQZpDvbYQstMm7DSoNEZ4FmuGjNqK6HpZMSJqFF8SwFGJFN

**Comment by GerryCallan** [comment]
OK, pardon my ignorance here, but what does that mean? Does it mean that somehow the password is incorrect, even though I never changed it an no one else has ever had access to my accounts or to the password?

**Comment by clockworkgr** [comment]
Pretty much...any chance it was a different password? or the pass was for a different account?

all you can do is doublecheck carefully. Your account doesn't seem to have been updated (possible key change) since you used it in december so pass has definately not been changed.

**Comment by GerryCallan** [comment]
Thanks clockworkgr - I have checked every iteration of the backups I've kept and the password hasn't changed, at least not by me. In fact I never attempted to change the password on any of the accounts due to having what I considered was a pretty strong password to start with, which was then stored relatively securely. I had a separate encrypted text file with passwords too and have verified that it hasn't changed either. Very strange, to say the least.

**Comment by GerryCallan** [comment]
I've tried every other password I've saved, just in case including passwords for other accounts. They're all incorrect, but I'd expect them to be. The one that should be right isn't though, for whatever reason.

**Comment by wmbutler** [comment]
Please seek further help here: https://t.me/btsWalletHelp

**Comment by clockworkgr** [comment]
awesome!
