### ISSUE TITLE
[.5][TBAPI-0KA] Mouse over on the Help opens switch node menu

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1446]
<img width="318" alt="screenshot 2018-04-20 08 55 02" src="https://user-images.githubusercontent.com/35899973/39034940-88d555f0-4478-11e8-8333-af6f8ab35a66.png">

**Comment by wmbutler** [comment]
I think it should be `onClick` instead of `mouseOver`
