### ISSUE TITLE
[10][ahdigital] TradingView styling

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1449]
This issue is an additional part of #905 

@ahdigital is going to provide UX for 3 themes for TradingView. 

I'll work on applying @ahdigital UX to TradingView. 

The issue is it's not an open source and chart placed on an iframe so I'm not sure if it is possible to easily implement styling. 

@wmbutler please put estimate for UX but regarding development estimate I need spend some time to investigate how do it right and then we will discuss it if you agree.

**Comment by ahdigital** [comment]
First draft of re-skinning TradingView charts. Next week I will embed them on an exchange mock-up to see them in situe.

![charts](https://user-images.githubusercontent.com/3088454/39069176-dec4256e-44d6-11e8-93de-5c04fce26066.jpg)

**Comment by wmbutler** [comment]
This is a good start. Some other considerations now that we have tradingview:

- When the order book is displayed vertically along the left edge, it, in combination with the list of assets on the right, forces tradingview to be really narrow. I'd really like to see a layout where the order book and starred markets are on the right side.
- We could take this opportunity to move away from the dual buy/sell windows. They take up a lot of room but all the fields are the same (just an inverse operation) which could be addressed with a single buy vs sell dropdown.
- The rest of the exchange could benefit from this look including all tables, etc.
- The intervals need to be carefully though out so for instance, when the user picks 1 week as period, we intelligently pick 6 hours as the interval. Need to have a table that we agree on for this.

**Comment by HarukaMa** [comment]
Nodes can have different available periods so translating them needs to be completely dynamic. For instance, my node have the following periods in seconds:

`[3,60,300,900,1800,3600,14400,86400,604800,2592000]`

(3s, 1m, 5m, 15m, 30m, 1h, 4h, 1d, 1w, 1m)

It's possible that there will be valid 1 week and even a 1 month periods, so it should be considered.

**Comment by wmbutler** [comment]
Agreed. My point is that we need to have logical intervals chosen based on a period.

**Comment by wmbutler** [comment]
Doubled the UX hours.

**Comment by smogm** [comment]
Maybe you can add buttons to size the widget like it is done on bitfinex:
![image](https://user-images.githubusercontent.com/2078175/39087553-0b4db0d8-45a3-11e8-8bce-6c366bd01bfb.png)

If you increase the size one time the drawing toolbar is displayed on the left:
![image](https://user-images.githubusercontent.com/2078175/39087544-d98d71a0-45a2-11e8-86f0-15e2ffbd8758.png)

**Comment by svk31** [comment]
Intervals are already dynamic but I only implemented days and minutes so far, it's not a styling issue though. I've extended the logic for seconds and weeks now but don't have any nodes offering that to test with.

**Comment by svk31** [comment]
Most nodes include those buckets from what I've seen. Nodes are free to configure whichever buckets they like, they're defined in seconds in their config files. The GUI will simply display whichever buckets are available from your currently connected node. This is using eu.nodes.bitshares.ws for example:

![image](https://user-images.githubusercontent.com/6890015/39138252-d53c46d4-471f-11e8-971b-fd2212e674d1.png)

**Comment by wmbutler** [comment]
Thoughts:

Period | Interval
-- | --
All | 2w
1y | 1w
6m | 4d
3m | 2d
1m | 1d
2w | 6h
1w | 3h
1d | 1h
6h | 5m

**Comment by smogm** [comment]
@wmbutler guess the greater the interval larger the distance between them can be.
E.g. I would remove 2d, 4d and 2w and simply add 1 month instead.

**Comment by wmbutler** [comment]
@smogm I'm not sure I understand.

**Comment by startailcoon** [comment]
@ahdigital Looking really nice. Do I assume correct that you've added a "hidden" arrow for the side menu, rendering issue #1422 obsolete? I've done nothing on it yet, so if this is the case we can close it.

**Comment by gibbsfromncis** [comment]
@wmbutler as @ahdigital presented cool redesign of entire Exchange I can work on this one

**Comment by wmbutler** [comment]
## Notes
First of all I'd like to say that I think this is excellent work. I have a couple of points, but they are by no means criticisms.

- [ ] I'm hoping we can avoid the striped table rows. onHover colors can create an undesirable effect. Maybe very light divider lines or no lines at all will suffice.
- [ ] I believe it's important that the order entry screen be in view at all times. Possibly replace the Market depth view with the order screen. We currently have a buy and a sell order screen visible. Since the fields are identical except for buy/sell, I think we can consolidate to a single screen with a buy/sell toggle.
- [ ] For many traders, I think 3 screens need to be visible simultaneously: Order screen, order book, My Open Orders.
- [ ] I think Market Depth can be viewable as a toggle between the main chart view and it.

**Comment by abitmore** [comment]
IMHO "buy/sell toggle' is a bad design since it's too easy to place orders in wrong direction.

**Comment by abitmore** [comment]
Please also add the order-stacking feature in the view. More info: https://github.com/bitshares/bitshares-ui/pull/1467

**Comment by wmbutler** [comment]
@abitmore We need to save some space on the exchange. Any other thoughts? Unless you have a specific suggestion, I'm leaning towards the current UI. The button clearly says "Buy <asset>" or "Sell <asset>"

**Comment by wmbutler** [comment]
By the way, I'd use **Vertical Order Book B**

**Comment by startailcoon** [comment]
@wmbutler @abitmore one idea is to make the background of buy and sell significant different so the user can see where she is.

Not just a header color.

**Comment by wmbutler** [comment]
Green and Red would make good choices. Unambiguous. I don't see it as a problem since the acual buy button and header is labelled as such. If colors can be worked in without it looking like crap, I'd support it thought.

**Comment by ahdigital** [comment]
Rather than change colour for the tab or it's background I did it on the action button itself. So, 'Buy [asset]' would be green and 'Sell [asset]' would be red.

I've updated the visuals in the above [post](#issuecomment-384915479).

**Comment by abitmore** [comment]
@wmbutler @ahdigital please add order-stacking feature introduced with #1467.

**Comment by wmbutler** [comment]
@ahdigital I didn't see the updated colors above but I think I understand what you are suggesting.

**Comment by ahdigital** [comment]
@wmbutler Updated.

**Comment by wmbutler** [comment]
This is groomed and ready for execution.
