### ISSUE TITLE
[2] Node out of Sync: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1455]
Once a node is out of sync, the UI remains on the same screen while clicking around, repeating this same console log. This error should be caught and should trigger a node reconnect instead.

![node](https://user-images.githubusercontent.com/1254810/39098265-95e29602-462d-11e8-985e-979942adc6e4.gif)

**Comment by svk31** [comment]
It's hard to diagnose without a copy paste of the first parts of the red errors, but I suspect it's caused by a closed connection not an out of sync error.

**Comment by wmbutler** [comment]
>What actually triggered it, did you try to connect to the active node in your gif? (by the way I really hate those gifs, I'd much rather have a description of what you did and a screenshot or copy paste of the first red error in the console log..)

I'm almost positive this was the current state of my browser after I had been gone for a few hours. I happened to be on the node screen when I left. When I returned, clicking on any link yielded the console logs shown.
