### ISSUE TITLE
[3] SettingsStore doesn't merge defaults with stored defaults properly

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#1462]
See: https://github.com/bitshares/bitshares-ui/pull/1441#issuecomment-383882834

The merging of coded and stored settings and defaults is messy to say the least, and we should probably refactor the whole thing.

**Comment by wmbutler** [comment]
It's yours @kapeer42

**Comment by startailcoon** [comment]
@kapeer42, how is your progress on this issue? Will you have something ready for this milestone or should be release it for someone else to take over?

**Comment by wmbutler** [comment]
Unassigned @kapeer42

**Comment by svk31** [comment]
@sschiessl-bcp I'm assigning this to you since your refactoring in #1726 fixes this, not sure if you were aware of this issue.

**Comment by sschiessl-bcp** [comment]
No, I wasn't, thanks.
