### ISSUE TITLE
[2][ahdigital][5] Properly handle non-existent markets

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1463]
If a market does not exist, for instance,  foo_foo,  handle it gracefully and quickly. In this case, the user attempted to navigate directly to market foo_foo and the browser connected tot he chainstore of the node and hung.

- [ ] UX the empty state (Market does not exist). Should we load all the elements of the Exchange but leave them empty with the chosen foo/foo in the upper left? This would allow the user to search for an appropriate market with the new market finder menu dropdown.
- [ ] Be sure to handle case sensitivity and rewrite the lowercase to uppercase.

![market](https://user-images.githubusercontent.com/1254810/39193128-76b19df4-47a0-11e8-8a88-9324f7f4758a.gif)

**Comment by svk31** [comment]
Here's a 30s solution:

![image](https://user-images.githubusercontent.com/6890015/39237354-933840d2-487b-11e8-9a09-14e054c5d624.png)
