### ISSUE TITLE
[2][ahdigital] UX for Exchange when no market is found

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1466]
If a market does not exist, for instance,  foo_foo,  handle it gracefully and quickly. In this case, the user attempted to navigate directly to market foo_foo and the browser connected to the chainstore of the node and hung.

- [ ] UX the empty state (Market does not exist). Should we load all the elements of the Exchange but leave them empty with the chosen foo/foo in the upper left? This would allow the user to search for an appropriate market with the new market finder menu dropdown.
- [ ] Be sure to handle case sensitivity and rewrite the lowercase to uppercase.

![market](https://user-images.githubusercontent.com/1254810/39193128-76b19df4-47a0-11e8-8a88-9324f7f4758a.gif)

This was handled in a quick and dirty way for #1463. This issue atttempts to expand upon it by providing a better user experience.

**Comment by ahdigital** [comment]
Within the context of the new exchange UI and market picker we could:

- Show empty UI with messaging "Market not found"
- Automatically open the market picker with the asset that could not be found selected

![image](https://user-images.githubusercontent.com/3088454/39358335-a15916e4-4a0d-11e8-9af3-864d082c968d.png)

**Comment by wmbutler** [comment]
This UX is groomed and ready for work but should be completed as part of ANT Exchange rewrite.
