### ISSUE TITLE
[3][kapeer] UX for Send/Deposit/Withdraw beta -> legacy

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1479]
We are at a point where I think we can change the labels on Send/Deposit/Withdraw. I'd like to consolidate the choices on this and:

- Remove the beta label from the new way
- Add the legacy label to the old way

Ideally, we can move everything to the right menu and have a single row for each item with legacy as a less prominent option on that row:

- Send | legacy
- Deposit | legacy
- Withdraw | legacy

On the legacy screens, we also need some text stating that we recommend using the new send/deposit/withdraw screens.

**Comment by startailcoon** [comment]
For the record, Legacy is required for users using GDEX Gateway for specific functions, like their beta program etc. Things that we did not include in the new modals.

I think it's a good thing that we do the switch, and that the legacy still remain the background for now.

**Comment by wmbutler** [comment]
Agreed, I don't want to get rid of those screens, just want to start phasing them out.

**Comment by startailcoon** [comment]
*Pasting conversation on PR:https://github.com/bitshares/bitshares-ui/pull/1695*

@sschiessl-bcp 
> When will it be legacy? Or receive a make-over to stick to the logic from the modal?

I'm not sure, but we've talked about doing something about it. They are more Gateway specific, and could probably stay in one form or another. They provide some more space for gateway specific features and functions, like updates, news, contact details etc. I see these sections more of a space where the gateways can and should take care of their own code, push PRs when they want an update etc.

**Comment by kapeer42** [comment]
Can I claim this?
This is tagged UX but the issue seems clear enough for implementation.

**Comment by wmbutler** [comment]
@kapeer42 Yes. can you post a basic mockup to make sure we are on the same page?

**Comment by startailcoon** [comment]
Including a "Use Advanced" would be a good option until we can find a good way to get the new send modal to work the same way. 

The old gateway sections has options as mentioned above, and I think it could be considered to be their "front page in-app" section.

**Comment by kapeer42** [comment]
I agree with @sschiessl-bcp and @startailcoon.

Here's what it would look like:

### Burger menu:
![burger-demo](https://user-images.githubusercontent.com/35779885/45254736-5c8f9e00-b37d-11e8-90af-2c86a932251d.png)
### Button:
![advanced-button-demo](https://user-images.githubusercontent.com/35779885/45254738-62857f00-b37d-11e8-9f74-e85815f18521.png)
I think a button that simply reads "Advanced" would be better.
### Warning:
![phase-out-warning-demo](https://user-images.githubusercontent.com/35779885/45254741-644f4280-b37d-11e8-97dd-2432ad926a7a.png)
The "send modal" link opens the modal.
It would read "deposit modal" and "withdraw modal" on the relevant pages.

**Comment by wmbutler** [comment]
I disagree. I think we should phase out the old way completely once the new modal has the propose capability. There is nothing "advanced" about the other method.

**Comment by wmbutler** [comment]
I've submitted UX for proposed send/transfer operations here: 

https://github.com/bitshares/bitshares-ui/issues/1536#issuecomment-421018790

**Comment by kapeer42** [comment]
So to sum it up:
- no changes to the modals
- this change to the menu: 
![burger-legacy-demo](https://user-images.githubusercontent.com/35779885/45589128-b31e4e80-b920-11e8-894c-b57cfce86d1f.png)
- adding the [previously shown](https://github.com/bitshares/bitshares-ui/issues/1479#issuecomment-419643031) warning on the legacy pages

?

If I may, I propose to join the legacy deposit and withdraw button like this since they are both links to the same page:
![depost-withdraw-button-demo](https://user-images.githubusercontent.com/35779885/45589218-60459680-b922-11e8-8086-0390ef783dcb.png)

**Comment by kapeer42** [comment]
@abitmore 
Are you referring to the screenshot I posted or current implementation?
The current implementation has the send button in the page header.
The screenshot is based off that so it isn't in the menu there either.
I don't think this is a bug.

**Comment by wmbutler** [comment]
I think we should instead show:
```
Deposit | Legacy
Withdraw | Legacy
```
on the same item. I'll mock this up.

**Comment by wmbutler** [comment]
This mockup does not include the appropriate icons. Use the existing icons.

State with nothing selected
<img width="776" alt="screen shot 2018-09-23 at 10 50 02 am" src="https://user-images.githubusercontent.com/1254810/45929969-7523ba80-bf1e-11e8-8fbd-63991f96e5bd.png">

State with Send row selected but not "or Legacy Send"
<img width="744" alt="screen shot 2018-09-23 at 10 51 11 am" src="https://user-images.githubusercontent.com/1254810/45929980-9e444b00-bf1e-11e8-9b63-e972e67c5fe7.png">

State with cursor hovered over "or Legacy Send" text
<img width="773" alt="screen shot 2018-09-23 at 10 47 37 am" src="https://user-images.githubusercontent.com/1254810/45929989-bae08300-bf1e-11e8-8573-d4017472cdc7.png">

**Comment by wmbutler** [comment]
> It seems there is only "send(legacy)" but no "send" in the menu? a bug?

@abitmore I'd propose that we also move the Send out of the header and into the menu bar.

- [ ] Move Send out of header and into menu bar

**Comment by wmbutler** [comment]
@kapeer42 I feel this is groomed and ready for execution.
