### ISSUE TITLE
[3] Exchange not loading for new, zero-balance accounts

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1481]
When a new account is created via cloud login, the exchange tab doesnt load anymore for some markets.

prominent example:

does not load
https://wallet.bitshares.org/#/market/USD_BTS

does load
https://wallet.bitshares.org/#/market/BTS_USD

The issue is in https://github.com/bitshares/bitshares-ui/blob/c69f297ee1cea480b531f8f38542baf1b17a5736/app/components/Exchange/Exchange.jsx#L288 that the feeStatus does not get loaded, which causes a return null in the render method.

**Comment by sschiessl-bcp** [comment]
So far I think it's due to the promise 
https://github.com/bitshares/bitshares-ui/blob/c69f297ee1cea480b531f8f38542baf1b17a5736/app/lib/common/trxHelper.js#L150
not being resolved properly

**Comment by sschiessl-bcp** [comment]
So I probably was digging around for three hours now, learned quite some of the exchange mechanics, still no clue though.

Anyways, it seems that the issue was that there were multiple fee loading promises for BTS in the above case.

Adding this above https://github.com/bitshares/bitshares-ui/blob/c69f297ee1cea480b531f8f38542baf1b17a5736/app/components/Exchange/Exchange.jsx#L288 did resolve it for me 
```
        if (assets[0] === assets[1]) {
            assets.splice(1, 1);
        }
```

**Comment by svk31** [comment]
That does fix the issue, I'm guessing the reason is that checkFeePoolAsync fails silently at some point because it tries to fetch and use balance objects, but the concerned accounts do not have any balances to fetch.

**Comment by svk31** [comment]
Ok found it: https://github.com/bitshares/bitshares-ui/commit/c6cdd4a72ad743f6e0c4cdbe3b45d42be7d02249

**Comment by sschiessl-bcp** [comment]
@svk31 

do you think my initial fix with 

`assets[0] === assets[1]`

is also necessary (I think it could be, because I often hear "my exchange is not loading" in telegram")? The code removes double entries if they occur on index 0,2 or 1,2. Is there a reason double entries occuring on 0,1 should be kept?

**Comment by svk31** [comment]
I seem to recall that the original reason for removing duplicate assets was simply to make sure the asset info was not fetched twice in parallel. With my recent changes to trxHelper adding request queueing and caching, that's no longer a concern so we can actually just remove that duplicate check in Exchange.jsx.

**Comment by svk31** [comment]
@wmbutler Not sure how to handle hours on this issue, @sschiessl-bcp's investigations allowed me to find the root cause quite quickly, and it took me about 30 minutes to fix the issue. Stefan should also be assigned some time for his investigations imo.
