### ISSUE TITLE
[10][gibbsfromncis]Develop Paging Module for Wallet

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1483]
UX in #1435

**Comment by svk31** [comment]
I missed this issue but added pagination here: https://github.com/bitshares/bitshares-ui/commit/284bf838e8e9461a562298bae501b0d88c61b7c2

There are still some UX items from this issue to handle but I think the hour estimate should probably be reduced.

**Comment by gibbsfromncis** [comment]
@svk31 good job. I'll pull your changes and check what you have done. After that I'll ask to update estimate.

**Comment by wmbutler** [comment]
Need more guidance on the hours here. Also, this issue is not part of any milestone.

**Comment by gibbsfromncis** [comment]
@wmbutler I specially unassigned milestone because this task is irrelevant and was done in scope of another task.

**Comment by wmbutler** [comment]
But you left your name and hours on it... I need better guidance. A sentence like "Please remove me from this issues and the hours associated with it".

**Comment by gibbsfromncis** [comment]
@wmbutler Got it. My bad.
