### ISSUE TITLE
[30] [gibbsfromncis] TradingView Redesign

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1484]
This issue is the part of [Exchange redesign](https://github.com/bitshares/bitshares-ui/issues/1477) which relates only to TradingView & Market Depth Charts redesign.

UX: #1449

**Comment by wmbutler** [comment]
Thought you might get some design inspiration from the GDAX market depth chart.

![market](https://user-images.githubusercontent.com/1254810/39676192-f9546036-512b-11e8-9788-d21020198ac2.gif)

**Comment by gibbsfromncis** [comment]
@wmbutler I've moved Market Depth to separate issue: #1578. Lets discuss it on this issue and put estimate.

There are some screenshots of TV redesign based on Dominic UX:

<img width="1329" alt="dex6" src="https://user-images.githubusercontent.com/35899973/41073601-56593fb8-6a04-11e8-81f7-3a3945345a65.png">
<img width="1330" alt="dex5" src="https://user-images.githubusercontent.com/35899973/41073602-567544ce-6a04-11e8-9bfd-768764fd8cf5.png">
<img width="1330" alt="dex4" src="https://user-images.githubusercontent.com/35899973/41073603-5694e8d8-6a04-11e8-89a4-2313f0cf537c.png">
<img width="1330" alt="dex3" src="https://user-images.githubusercontent.com/35899973/41073605-56ae4f3a-6a04-11e8-94bf-2d283bc20b38.png">
<img width="1330" alt="dex2" src="https://user-images.githubusercontent.com/35899973/41073606-56dc8454-6a04-11e8-836e-100e5b7027a0.png">
<img width="1329" alt="dex1" src="https://user-images.githubusercontent.com/35899973/41073607-56f7566c-6a04-11e8-9395-16c7133282dc.png">

Unfortunately, I didn't have a chance to follow UX by 100% and I did all my best. It would be nice to rework on it when TV will provide theming feature. 

As for now TV doesn't support theming I had to overwrite styles of most components. Unfortunately TV doesn't support any idea of nesting styles because a lot of same things have different styles so I did a lot of double work and testing. 

I expect to receive bounty for 30 hours I spent on this task.

**Comment by wmbutler** [comment]
Looks pretty awesome!
