### ISSUE TITLE
Can't connect to a testnet

### ISSUE THREAD

**Issue by kapeer42** [bitshares/bitshares-ui#1495]
**Describe the bug**
I can't connect to either of the two testnet nodes available.
The node.testnet.bitshares.eu one makes the app crash, logs [here](https://pastebin.com/KtdV1kij).
The bitshares infrastructure one is not responding.

**To Reproduce**
1. Go to 'Settings'
2. Click on the connection icon for either of the two testnet nodes.
4. For the bitshares.eu node: the app stops responding, the error linked appears in the console. For the infrastructure node: a notification says that the node did not respond.

**Expected behavior**
I expect to be able to connect to a testnet.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox
 - Version: 59.0.2-2

**Comment by abitmore** [comment]
I think you can try to fix the UI crash? The node didn't crash.

**Comment by svk31** [comment]
Unable to reproduce, `wss://node.testnet.bitshares.eu` works fine but `wss://testnet.nodes.bitshares.ws` does not have the orders api available so it doesn't initialize properly.

**Comment by kapeer42** [comment]
@svk31 Thanks, I can connect to `wss://node.testnet.bitshares.eu` now. I should have captured the errors it gave me before. Closing.
