### ISSUE TITLE
[1.5][startailcoon] UX about updating short position

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1496]
**Is your feature request related to a problem? Please describe.**
When updating a short position, when dragging the "ratio" bar, sometimes I want to change debt amount but not collateral amount.

**Describe the solution you'd like**
Maybe we can add a "lock" symbol to lock the collateral amount and let the debt amount be the changing party instead.

![](https://user-images.githubusercontent.com/12114550/39675928-f70e12c8-5161-11e8-8227-51afc18afdf5.gif)

**Comment by startailcoon** [comment]
I can take this

**Comment by startailcoon** [comment]
## Proposed UX

When a user enters the Borrow Modal you have a lock/unlocked symbol on the field of `Debt` and `Collateral`. These locks represents which field will be unchanged when you drag the ratio bar.

- By default, it's as it is today, collateral will change when you drag the ratio bar.
- Clicking each of the locks will toggle the fields to do oposite, and the lock symbols changes to reflet this.

This could also make it possible to
1. Lock Collateral
2. Enter an amount of collateral you wish to use
3. Drag the ratio slider to see how much you can borrow (ie, dept)

![image](https://user-images.githubusercontent.com/12114550/40278061-72b0990a-5c2a-11e8-873a-6b1b5fc99e4c.png)

**Comment by startailcoon** [comment]
![bitshares-lockedcr](https://user-images.githubusercontent.com/12114550/40941545-6f957fec-684b-11e8-95ac-1e03dc1c58fc.gif)
