### ISSUE TITLE
[3] AltStore&AltContainer has memory leak

### ISSUE THREAD

**Issue by roths** [bitshares/bitshares-ui#1497]
AltStore&AltContainer has memory leak

AltStore problem detail in here:
https://github.com/goatslacker/alt/pull/725

AltContainer problem detail in here:
https://github.com/altjs/container/pull/11

alt-react have same problem with AltContainer  but i dont pull request to it

**Comment by startailcoon** [comment]
@svk31 is this an issue and does it require some hours to be looked at or fixed?

**Comment by wmbutler** [comment]
@roths did you observe a problem with the wallet? If not please close.

**Comment by svk31** [comment]
@roths Thanks for reporting this, you were indeed correct and all three libraries had major memory leaks in the subscription arrays, which in our case were probably quite serious since we have so many components making use of them!

**Comment by clockworkgr** [comment]
sweet
