### ISSUE TITLE
Cannot open wallet on last staging

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1500]
**Describe the bug**
Cannot open wallet on last staging:

I've opened Incognito on Chrome and tried to open wallet but no luck. I suppose the last error in console relates to this issue:
<img width="1398" alt="screenshot 2018-05-09 22 08 53" src="https://user-images.githubusercontent.com/35899973/39834434-95bda364-53d5-11e8-9604-730439dc7950.png">

**To Reproduce**
1. Pull last staging
2. Do `npm install`
3. Run wallet
4. Open on incognito to prevent any outside effects 
5. Error happened, nodes switch doesn't work.
**Expected behavior**
1. User user be able to select new node and open wallet

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version Last

**Comment by svk31** [comment]
The orders api is missing on that API server, just pick another one. I haven't seen that particular error myself though.

**Comment by lsosa3** [comment]
I have the same issue here
![issue-bitshares-ui-new](https://user-images.githubusercontent.com/14814335/40086647-4091e156-586d-11e8-8475-34c990aeec90.jpg)

**Comment by svk31** [comment]
Your local node is also out of date and configured without using the orders_api. This is not a UI issue, just compile the latest version of bitshares-core.
