### ISSUE TITLE
Adding stop loss in DEX

### ISSUE THREAD

**Issue by SimonzDiamondz** [bitshares/bitshares-ui#1501]
Hi guys,

In this post i will speak for others. I have some traders asking me to demand a stop loss feature on DEX. (they dont use to go ask on github so im doing them a favor).

Thanks !

**Comment by wmbutler** [comment]
If I understand stop/loss correctly, this would be a core feature, not a ui feature.

**Comment by SimonzDiamondz** [comment]
thanks brother. will transfert it to the right place.
