### ISSUE TITLE
[UX+UI:28][gibbsfromncis] Modal for Scaled Orders

### ISSUE THREAD

**Issue by fractalnode** [bitshares/bitshares-ui#1503]
As a trader I would like to be able to add scaled orders in the similar way to bitfinex

![image](https://user-images.githubusercontent.com/20418259/39875085-dd546d9e-546f-11e8-8b5b-3040acaccb52.png)

![image](https://user-images.githubusercontent.com/20418259/39875404-de2dd6d2-5470-11e8-8f5e-eb11d67c614d.png)

**Comment by gibbsfromncis** [comment]
@abitmore Do we support it on server side?

**Comment by svk31** [comment]
No, it would need to be done in the ui using multiple regular limit orders. That should be possible though, you can add multiple operations to one transaction.

**Comment by gibbsfromncis** [comment]
@svk31 got it. Nice.

**Comment by gibbsfromncis** [comment]
@wmbutler Can I just start to work on it or you want some UX changes there? (if yes please describe what exactly do you want to change and I'll ask some my designer to work on UX)

This feature looks very useful for me and nice path to attract more traders. We already have useful charts (TradingView) and it's nice to work on orders part.

**Comment by fractalnode** [comment]
basically, I meant a much simpler version. 
In fact, something like that would be enough
![image](https://user-images.githubusercontent.com/20418259/42126208-9fdbea18-7c84-11e8-8ae9-301c3ad1183c.png)

**Comment by wmbutler** [comment]
This definitely needs UX proposed first and should fit into the Exchange redesign with ANT.

**Comment by gibbsfromncis** [comment]
@wmbutler I'll work on UX and UI both.

**Comment by gibbsfromncis** [comment]
UX for this task:

<img width="937" alt="2018-09-17 02 26 16" src="https://user-images.githubusercontent.com/35899973/46080196-89bfb700-c199-11e8-8e71-59eb8d64f0a7.png">

@wmbutler @startailcoon 
My estimate for UI implementation is 8h. Please update the estimate or unassign myself

**Comment by wmbutler** [comment]
@gibbsfromncis please be more specific on your estimate 2 ux and 6 ui?

**Comment by gibbsfromncis** [comment]
@wmbutler The process of transactions creating etc. is complicated for me because I'm not familiar with this part. So that's why I'm asking to increase estimate or ask somebody who has more knowledge of this specifics to work on this task

**Comment by startailcoon** [comment]
I see this feature as a good implementation and we have no other given coder for the UI implementation. The feature request is months old we should increase the required hours for @gibbsfromncis to implement this.

**Comment by gibbsfromncis** [comment]
@startailcoon final estimate is much more than I expected. It is 25 hours. 

I stuck on Fees / Markets fees calculations and fixes, orders creation but finally I did it. In result it looks really cool and awesome feature.

One thing left is to add an ability to manage multiple orders to cancel them. Because using scaled orders users now can create unlimited count of orders and to cancel them users should click on circle and wait 3s until Exchange container update. 

I've created task for multiple orders management: https://github.com/bitshares/bitshares-ui/issues/2317

**Comment by startailcoon** [comment]
Nice ground work @gibbsfromncis ! I see we can expand on the types you can make later. Now we have a basic frame to work from for making multiple orders.

**Comment by fractalnode** [comment]
I'm curious. What would be the max number of operations in one transaction, and what will happend when "Order Count" exceeds this number? Will the order itself be divided into several blocks?

**Comment by gibbsfromncis** [comment]
@fractalnode I suppose for the first version we will just limit amount of orders count but yes, it is possible to divide it by multiple transactions.

**Comment by gibbsfromncis** [comment]
Adjusted to 28 hours. 1 hour was spent to fix comments on PR #2316

**Comment by gibbsfromncis** [comment]
Adjusted to 29. 1 hour was spent for investigation why Scaled Order Modal doesn't open in some cases. The reason was that if bindActionToState is missing some of "ChainType.required" parameter the component won't render without any error.
