### ISSUE TITLE
latest release, sending of assets does not work...

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#1504]
trying to send BEYONDBIT, it dies after this window:

![image](https://user-images.githubusercontent.com/15261692/39885026-dd8480ee-548b-11e8-90b3-c38a0aa5d373.png)

Client: Desktop, win7

Edit: it worked after the wallet was unlocked, had to repeat the sending. something is off here still

**Comment by startailcoon** [comment]
Fixed in PR #1499

**Comment by wmbutler** [comment]
#1437

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares-ui/issues/1508
