### ISSUE TITLE
[4][gibbsfromncis] Scan QR Code - Withdraw Modal

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1512]
Refer to UX: #998

**Comment by gibbsfromncis** [comment]
Some screenshots:
<img width="497" alt="screenshot 2018-05-21 11 47 15" src="https://user-images.githubusercontent.com/35899973/40301972-fed36cfa-5ced-11e8-8603-557dc0efa819.png">
<img width="501" alt="screenshot 2018-05-21 11 53 02" src="https://user-images.githubusercontent.com/35899973/40301971-feab95f4-5ced-11e8-86a0-5dc6f5201997.png">

Pull request: #1545

**Comment by gibbsfromncis** [comment]
Closing as it was merged

**Comment by Agorise** [comment]
![photo_2018-06-13_13-04-06](https://user-images.githubusercontent.com/31280836/41344652-52019824-6f0a-11e8-9e3b-5d7859503e10.jpg)
 
GREAT work you guys!!!!! :) 
Sorry I don't have a way to test it, can it scan this version 10 QR code? If so, then it already supports PalmPay merchants too.
