### ISSUE TITLE
Question: Less than 5min candlesticks.

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/bitshares-ui#1519]
According to this: https://github.com/bitshares/bitshares-ui/blob/bbc783368e0e46699970ba0de94f2e32a298070b/app/components/Exchange/PriceChartD3.jsx#L830-L833

Buckets less than 5 mins get filtered out. Is there a specific reason for this? My API nodes (as well as those of the infrastructure worker if I'm not mistaken, @xeroc ?) also provide 1 min buckets.

**Comment by svk31** [comment]
Because no markets had meaningful data at those time frames, so the charts looked terrible. Perhaps some of the more active markets have sufficient data now, like Cny:bts, but most others won't.

**Comment by clockworkgr** [comment]
Should we remove the filter and leave it up to the user to choose/change resolution? @svk31  @startailcoon @sschiessl-bcp  

If consensus says no, we can close this

**Comment by sschiessl-bcp** [comment]
Will be possible with #2145
