### ISSUE TITLE
[1] Cannot open Withdraw Modal (Withdraw beta) and any other items from hamburger (sometimes) 

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1520]
**Describe the bug**
I cannot open Withdraw Modal by click on it on Hamburger menu. After that I cannot open any other item from hamburger (take a look screen. I have "News" opened on header tab but I see Home screen)

Also any click on hamburger fires some errors in console

**To Reproduce**
1. Open hamburger menu
2. Click on Withdraw (Beta)
3. Try to click after that on any another item

**Expected behavior**
Withdraw modal should appears when user try to open it.

**Screenshots**
<img width="1150" alt="screenshot 2018-05-17 14 39 27" src="https://user-images.githubusercontent.com/35899973/40177968-6aa7138e-59e0-11e8-8114-5e629a4ddb5c.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Safari, Chrome, Opera
 - All latest

**Comment by gibbsfromncis** [comment]
@startailcoon there is an error on `WithdrawModalNew.jsx`:

<img width="983" alt="screenshot 2018-05-17 14 48 17" src="https://user-images.githubusercontent.com/35899973/40178292-6566394e-59e1-11e8-9540-87e3f2a3efb4.png">
<img width="399" alt="screenshot 2018-05-17 14 48 13" src="https://user-images.githubusercontent.com/35899973/40178294-6588419c-59e1-11e8-9b83-9dd3437cfc1c.png">

**Comment by startailcoon** [comment]
Fixed in PR #1507

**Comment by startailcoon** [comment]
Until this PR is released to the next release, a way around this issue is to

1. Navigate to dashboard
2. Click the withdraw icon on any of the assets in your wallet, then change it to whatever you wish if you wish to change
