### ISSUE TITLE
[7.5][TBD] Better node management

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1521]
As we gain more and more nodes from both witnesses, businesses, regular joes and worker programs, the list has grown quite long. Nodes all around the globe is in one single list, and mixed with testnet nodes, just to make the matter worse.

I propose we make a UX for a better node management.
A user should be able to filter/find/sort nodes on flags like these, but not limited:

- Country (UK, Sweden, US, China etc.)
- Region (North America, Europe, Asia etc.)
- Owner (Witness, Worker, Exchange etc)
- Network (Main or Test for the moment)
- Core version
- Buckets and History sizes 

The goal of this would be to make the list of nodes more manageable.

**Comment by clockworkgr** [comment]
Possibly amount of history & bucket sizes offered too? (although I have started a discussion in telegram to standardize bucket sizes offered for uniformity)

**Comment by svk31** [comment]
Knowing bucket sizes requires us to make an api call to the node. The amount of history is not available AFAIK.

**Comment by abitmore** [comment]
> Owner (Witness, Worker, Exchange etc)

This is useful especially when a node is having issues. Easier to contact responsible people.

**Comment by sschiessl-bcp** [comment]
During working on #1672 and refactoring I realized that this issue is probably gonna be solved on the. Can this be rated please?

**Comment by sschiessl-bcp** [comment]
During my work on this I found a bug in the SettingsStore. If any default values change (removing nodes, changing faucet), the user does not get those changes due to local storage having old values. Will include a fix for that as well

**Comment by abitmore** [comment]
Is there a way to not trigger chrome warning when one of the nodes has a bad SSL certificate?

**Comment by sschiessl-bcp** [comment]
> Is there a way to not trigger chrome warning when one of the nodes has a bad SSL certificate?

No, that can only be deactivated by the user. Even if the UI wanted to evaluate certificates itself and not connect if invalid the user would still get a notification.

**Comment by sschiessl-bcp** [comment]
I am calling out to all node operators, please provide me with the additional information to be able to give the user a more sophisticated selection process and filtering options.

See my comment above for the format, please simply comment in here with your updated node configuration in the same style (so I can copy and paste). Expectancy of a post:

Please update 
```
        {
            url: "wss://eu.nodes.bitshares.ws",
            location: "Central Europe - BitShares Infrastructure Program"
        }
```
to
```
        {
            url: "wss://eu.nodes.bitshares.ws",
            region: "Western Europe",
            country: "Germany",
            operator: "Infrastructure Worker",
            contact: "email:info@blockchainprojectsbv.com"
        }
```

Short explanation:
 - url: exact url of the node that allows a websocket connection
 - location: City of the node server
 - country: Country of the node server
 - region: Region of the node server, important for a more sophisticated geolocation-based connection strategy later on. One of the following options

https://github.com/bitshares/bitshares-ui/blob/f9736a4c5cb755b60735212e6e4ebd292128108d/app/api/apiConfig.js#L71-95

 - operator: Whatever entity is providing this server (can be Anonymous if really necessary)
 - contact: A string containing perefered contact method and  details, i.e. `"[email|telegram|github|...]:details"`. This information will not be displayed in the UI (yet), but it is essential that the UI team has some way of contacting all node operators. Examples:
    - `"github:sschiessl-bcp"`
    - `"email:info@blockchainprojectsbv.com"`
    - `"telegram:sschiessl"`

**Comment by clockworkgr** [comment]
{
            url: "wss://bts-seoul.clockwork.gr",
            region: "Southeastern Asia",
            country: "Korea",
            location: "Seoul",
            operator: "Witness: clockwork",
            contact: "email:alex@clockwork.gr"
        }

**Comment by dls-cipher** [comment]
Listing emails in pages in their native structure mailbox@domain.com that can end up in Search Engines is just an open-invite for crawlers, bots, spam and unusual activity over https://wallet.bitshares.org so no, I don't agree with adding emails as contacts.

I would also added line entry that is saying is the node standard/full so we can end that endless question of users "is there any full node".

Rest is fine.

**Comment by clockworkgr** [comment]
After DL's comment I suggest a history_ops entry specifying amount of history. 0 for full node, or number for max ops held.

Updated my comment accordingly

**Comment by abitmore** [comment]
@clockworkgr 0 for mini node with no history.

**Comment by startailcoon** [comment]
```
{ 
     url: "wss://bitshares.crypto.fans/ws", 
     region: "Western Europe", 
     country: "Germany", 
     location: "Munich",
     operator: "Witness: sc-ol", 
     contact: "telegram:startail",
     history_ops: "100"
} 
```

**Comment by abitmore** [comment]
```
{ 
     url: "wss://api.bts.mobi/ws",
     region: "Northern America",
     country: "USA",
     location: "VA",
     operator: "Witness: in.abit",
     contact: "telegram:abitmore",
     history_ops: "1000"
} 
```

Actually I think UI can detect number of `history_ops` by itself.

By the way, how about enabled plugins / apis? Version? Compile-time options(https://github.com/bitshares/bitshares-core/pull/1099,https://github.com/bitshares/bitshares-core/pull/1140)? Will the UI code detect them automatically?

**Comment by sschiessl-bcp** [comment]
@abitmore Yes, after connecting to the node that could be evaluated, but the main spirit of this update is to give the user filtering before connecting. All meanwhile the user should not be able to discriminate on facts other than location. Users like bigger numbers, running a full node is already more expensive and I want to avoid that traffic focuses there then.

After connection has been established I am hoping to get https://github.com/bitshares/bitshares-core/issues/626 to provide more intel on the node. Also in the spirit of said issue I want to avoid putting down any hardcoded information that would be excluded in such a server info API due to security risks.

**Comment by ihashfury** [comment]
```
{ 
     url: "wss://api.fr.bitsharesdex.com",
     region: "Western Europe",
     country: "FRANCE",
     location: "Paris",
     operator: "delegate.ihashfury",
     contact: "telegram:ihashfury",
     history_ops: "1000"
     bucket-size: "60,300,900,1800,3600,14400,86400,604800"
} 
```

```
{ 
     url: "wss://api.bitsharesdex.com",
     region: "Northern America",
     country: "USA",
     location: "Kansas City",
     operator: "delegate.ihashfury",
     contact: "telegram:ihashfury",
     history_ops: "1000"
     bucket-size: "60,300,900,1800,3600,14400,86400,604800"
} 
```

**Comment by roelandp** [comment]
```
{
            url: "wss://btsws.roelandp.nl/ws",
            region: "Northern Europe",
            country: "Finland",
            location: "Helsinki",
            operator: "roelandp",
            contact: "telegram:roelandp",
            history_ops: "1000",
            bucket-size: "60,300,900,1800,3600,14400,86400"
}
```

**Comment by pluswave** [comment]
{ 
     url: "wss://bts.open.icowallet.net/ws", 
     region: "Eastern Asia", 
     country: "China", 
     location: "Hangzhou",
     operator: "Witness: magicwallet.witness", 
     contact: "telegram:plus_wave",
     history_ops: "300"
}

**Comment by kimziv** [comment]
{
	url: "wss://kimziv.com/ws",
	region: "North America",
	country: "USA",
	location: "New Jersey",
	operator: "Witness: witness.yao",
	contact: "telegram: imyao",
	history_ops: "1000"
	bucket - size: "15,60,300,3600,86400"
}

**Comment by bangzi1001** [comment]
{
url: "wss://btsfullnode.bangzi.info/ws",
region: "Western Europe",
country: "Germany",
location: "Munich",
operator: "Witness: Bangzi",
contact: "Telegram: Bangzi",
history_ops: "1000",
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by ruslansalikhov** [comment]
{ 
     url: "wss://api.bts.blckchnd.com",
     region: "Western Europe",
     country: "Germany",
     location: "Falkenstein",
     operator: "witness:blckchnd",
     contact: "email:admin@blckchnd.com;telegram:ruslansalikhov;github:blckchnd",
     history_ops: "1000"
     bucket-size: "60,300,900,1800,3600,14400,86400"
},
{ 
     url: "wss://api-ru.bts.blckchnd.com",
     region: "Eastern Europe",
     country: "Russia",
     location: "Moscow",
     operator: "witness:blckchnd",
     contact: "email:admin@blckchnd.com;telegram:ruslansalikhov;github:blckchnd",
     history_ops: "1000"
     bucket-size: "60,300,900,1800,3600,14400,86400"
},
{ 
     url: "wss://node.market.rudex.org",
     region: "Western Europe",
     country: "Germany",
     location: "Falkenstein",
     operator: "witness:blckchnd",
     contact: "email:admin@blckchnd.com;telegram:ruslansalikhov;github:blckchnd",
     history_ops: "1000"
     bucket-size: "60,300,900,1800,3600,14400,86400"
},

**Comment by yuzhongzhen** [comment]
{
url: "wss://bitshares.bts123.cc:15138/",
region: "North China",
country: "China",
location: "Hangzhou",
operator: "Witness: delegate.freedom",
contact: "telegram:eggplant",
history_ops: "100",
bucket-size: "60,300,900,1800,3600,14400,86400"
}
{
url: "wss://freedom.bts123.cc:15138/",
region: South China",
country: "China",
location: "Changsha",
operator: "Witness: delegate.freedom",
contact: "telegram:eggplant",
history_ops: "100",
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by Xeldal** [comment]
{ 
     url: "wss://kc-us-dex.xeldal.com/ws", 
     region: "North America", 
     country: "USA", 
     location: "Kansas City",
     operator: "Witness:xeldal", 
     contact: "telegram:xeldal",
     history_ops: "3000"
     bucket-size: "300,900,1800,3600,14400,43200,86400"
}

**Comment by axin313** [comment]
{
url: "wss://ws.winex.pro",
region: "Asia",
location: "Singapore",
operator: "Witness: winex.witness",
contact: "telegram: zmaxin",
history_ops: "1000"
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by Zapata** [comment]
```
{ 
     url: "wss://api.dex.trading/",
     region: "Western Europe",
     country: "France",
     location: "Paris",
     operator: "Witness: zapata42-witness",
     contact: "telegram:Zapata_42",
     history_ops: "100",
     bucket-size: "60,300,900,1800,3600,14400,86400",
     network: "mainnet"
} 
```

```
{ 
     url: "wss://testnet.dex.trading/",
     region: "Western Europe",
     country: "France",
     location: "Paris",
     operator: "Witness: zapata42-witness",
     contact: "telegram:Zapata_42",
     history_ops: "100",
     bucket-size: "60,300,900,1800,3600,14400,86400",
     network: "testnet"
} 
```

Note: There is no way to specify if it's a testnet node or not, I have added a `network: mainnet|testnet` field.

**Comment by sschiessl-bcp** [comment]
Thank you.

@Zapata every node that has testnet in its URL is recognized as such

**Comment by lzmlam** [comment]
{
url: "wss://blockzms.xyz/ws ",
region: "North America",
country: "America",
location: "New Jersey",
operator: "Witness: delegate-zhaomu",
contact: "telegram:@lzmlam wechat:lzmlam",
history_ops: "100",
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by BhuzOr** [comment]
```
{ 
     url: "wss://api.bitshares.bhuz.info/ws",
     region: "Northern America",
     country: "Canada",
     location: "",
     operator: "Witness: bhuz",
     contact: "telegram: bhuzor",
     history_ops: "1000"
     bucket-size: "60,300,900,1800,3600,14400,86400"
} 
```

**Comment by crazybits** [comment]
{
url: "wss://crazybit.online",
region: "Asia",
country: "China",
location: "Shenzhen",
operator: "Witness: crazybit",
contact: "Telegram: crazybits, Wechat: JamesCai",
history_ops: "1000",
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by ryanRfox** [comment]
{ 
     url: "wss://api.bts.network/",
     region: "North America",
     country: "USA",
     location: "Virginia",
     operator: "Witness: fox",
     contact: "telegram:ryanRfox",
     history_ops: "1000",
     bucket-size: "60,300,900,1800,3600,14400,86400",
     network: "mainnet"
}

**Comment by btsabc** [comment]
{ 
     url: "wss://bit.btsabc.org/ws",
     region: "Eastern Asia",
     country: "China",
     location: "Hong Kong",
    operator: "Witness: abc123",
    contact: "QQ: 58291,email:58291@qq.com",
    history_ops: "1000",
    bucket-size: "15,60,300,3600,86400"
}

**Comment by sschiessl-bcp** [comment]
All added up till here.

**Comment by sschiessl-bcp** [comment]
These nodes are still to be updated:
 - ws.hellobts.com
 - api.bts.ai, witness.hiblockchain
 - bts-api.lafona.net/ws, delegate-1.lafona
 - api.btsxchng.com, elmato
 - btsza.co.za:8091
 - dex.rnglab.org, rnglab
 - ws.gdex.io
 - node.btscharts.com

If anyone has contacts there, please ping

**Comment by tianyekuo** [comment]
"ws.gdex.io" does not support any more, it's better remove it from the node list, thanks.

**Comment by ety001** [comment]
`{
            url: "wss://bts.to0l.cn:4443/ws",
            region: "Eastern Asia",
            country: "China",
            location: "Shandong",
            operator: "Witness: liuye",
            contact: "email:work@liuye.tech",
            history_ops: "100",
            bucket-size: "60,300,900,1800,3600,14400,86400"
}`

**Comment by viaNull** [comment]
{
url: "wss://api.bts.ai",
region: "Eastern Asia",
country: "China",
location: "Beijing",
operator: "Witness: witness.hiblockchain",
contact: "telegram:vianull ,Wechat: strugglingl",
history_ops: "400",
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by SahkanDesertHawk** [comment]
{
url: "wss://la.dexnode.net/ws",
region: "Northern America",
country: "USA",
location: "Los Angeles",
operator: "Witness: Sahkan"
contact: "telegram:Sahkan_bitshares",
history_ops: "1000",
bucket-size: "15,60,300,3600,86400",
network: "mainnet"     
},
{
url: "wss://dexnode.net/ws",
region: "Northern America",
country: "USA",
location: "Dallas",
operator: "Witness: Sahkan"
contact: "telegram:Sahkan_bitshares",
history_ops: "1000",
bucket-size: "15,60,300,3600,86400",
network: "mainnet"     
},

**Comment by jademont** [comment]
{
url: "wss://ws.hellobts.com",
region: "Eastern Asia",
country: "Japan",
location: "Tokyo",
operator: "Witness: xman",
contact: "Wechat: hidpos , Email:hellobts@qq.com",
history_ops: "500",
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by lafona** [comment]
{
url: "wss://bts-api.lafona.net/ws",
region: "Northern America",
country: "Canada",
location: "Montreal",
operator: "Witness: delegate-1.lafona",
contact: "Telegram: lafona",
history_ops: "1000",
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by sschiessl-bcp** [comment]
All added until here.

Still remain:
- api.btsxchng.com, elmato
- btsza.co.za:8091
- dex.rnglab.org, rnglab
- node.btscharts.com

**Comment by sschiessl-bcp** [comment]
Changed hours to incorporate:
 - finding node operators
 - optimize ping strategy for lower connectivity (feedback from members in chinese community on staging release)

**Comment by MikhailKavalenka** [comment]
{
            url: "wss://na.openledger.info/ws", 
            location: "Canada, Quebec",
            operator: "Witness: openledger-dc",
            contact: "telegram:mtopenledger",
            history_ops: "100",
            bucket-size  : [15,60,300,3600,86400]
}

One more from Openledger

**Comment by KKCoinLeo** [comment]
{
url: "wss://node.btscharts.com/ws",
region: "Eastern Asia",
country: "China",
location: "Beijing",
operator: "leo2017",
contact: "Wechat: wx8855221 , Email:8855221@qq.com",
history_ops: "1000",
bucket-size: "15,60,300,3600,86400"
}

**Comment by sschiessl-bcp** [comment]
Added

**Comment by elmato** [comment]
{ 
     url: "wss://api.btsxchng.com",
     region: "Multiple",
     country: "Worldwide",
     location: "Singapore / N. Virginia / London",
     operator: "Witness: elmato",
     contact: "telegram:elmato",
     history_ops: "300",
    bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by startailcoon** [comment]
@sschiessl-bcp is all nodes updates so we can close this issue?

**Comment by dls-cipher** [comment]
{
url: "wss://bitshares.nu/ws",
region: ""Northern Europe"",
country: "Sweden",
location: "Stockholm",
operator: "DAO Collaboration - Infrastructure Worker",
contact: "telegram:StaflunD",
history_ops: "100",
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by rngl4b** [comment]
{
url: "wss://dex.rnglab.org",
region: "Northern Europe",
country: "Netherlands",
location: "Amsterdam",
operator: "Witness: rnglab",
contact: "keybase:rnglab",
history_ops: "100",
bucket-size: "60,300,900,1800,3600,14400,86400,604800"
}

**Comment by ThomasFreedman** [comment]
{
url: "wss://bts.proxyhosts.info/wss",
region: "",
country: "Germany",
location: "",
operator: "Witness: verbaltech2",
contact: "keybase:jgaltman",
history_ops: "300",
bucket-size: "60,300,900,1800,3600,14400,86400"
}

**Comment by wmbutler** [comment]
Is this ready to get closed out and paid?

**Comment by barefootmouse** [comment]
```
        {
            url: "wss://de.bts.dcn.cx/ws",
            region: "Western Europe",
            country: "Germany",
            location: "Nuremberg",
            operator: "fla01",
            contact: "telegram:Otherego, telegram:BarefootMouse",
            history_ops: "256",
            bucket-size: "60,300,900,1800,3600,14400,86400"
        }

        {
            url: "wss://fi.bts.dcn.cx/ws",
            region: "Northern Europe",
            country: "Finland",
            location: "Helsinki",
            operator: "fla01",
            contact: "telegram:Otherego, telegram:BarefootMouse",
            history_ops: "256",
            bucket-size: "60,300,900,1800,3600,14400,86400"
        }

```

**Comment by sschiessl-bcp** [comment]
The next step is laid out in #1901, please evaluate
