### ISSUE TITLE
[1.5] How to clear voting proxy?

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1525]
**Describe the bug**
There was a "clear proxy" button in order versions e.g. 2.0.160420. But now we only have 2 buttons: "save" and "reset".  It seems the "proxy" text box doesn't accept empty name. Clicking "reset" doesn't clear it as well.

**To Reproduce**
1. Go to https://wallet.bitshares.org/#/account/chainsquad/voting
2. Click on the drop-down box with no label
3. input something, select an account name
4. Click reset
5. Click on the drop-down box
6. input nothing
7. click the white lock icon (or anywhere outside the box)

**Expected behavior**
- Able to clear proxy.
- The drop-down box should have a label.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/40235177-b70f5500-5aa9-11e8-8aa3-acb43e92d19f.png)
![image](https://user-images.githubusercontent.com/9946777/40235204-cd20e6c4-5aa9-11e8-865a-3ed9fff97ea5.png)
![image](https://user-images.githubusercontent.com/9946777/40235397-6ce4f5f6-5aaa-11e8-813a-faffb50988a3.png)
![image](https://user-images.githubusercontent.com/9946777/40235675-46b52760-5aab-11e8-9f96-f052b7bc6488.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser: Chrome
 - Version: latest

**Comment by startailcoon** [comment]
Idd, we are missing a 'clear vote' button.

**Comment by startailcoon** [comment]
This issue requires some tinkering with Typeahead and handling empty values or resets. I've been unable to find a good way to handle this.

**Comment by wmbutler** [comment]
I'm not convinced we need a typeahead for the proxy input field. Maybe we can keep this easy by eliminating the typeahead. what if we:

- remove the lock
- replace the lock with a "Clear Proxy" button
- When proxy is set, make input field locked / disabled with Clear Proxy button displayed

**Comment by startailcoon** [comment]
I can take this and change it to a non-typeahead style so we can handle empty inputs.
