### ISSUE TITLE
[1]Explicitly expose market picker feature

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1526]
**Is your feature request related to a problem? Please describe.**
- Nobody knows the asset symbols are clickable.
- Nobody knows the "flip market" icon is clickable.

![image](https://user-images.githubusercontent.com/9946777/40236431-d2ce5152-5aad-11e8-89b5-bc5b78ad4d1f.png)

**Describe the solution you'd like**
For example, change the color of clickable text / icons to light blue, like the "borrow bitUSD" link below?

**Describe alternatives you've considered**
Add a drop-down icon or something.

**Additional context**
None.

**Comment by wmbutler** [comment]
@ahdigital thoughts? It's a valid point. Maybe a hover state that makes it clear the symbols are clickable.

**Comment by ahdigital** [comment]
I think the asset pairs in the recent market picker mock ups had underlines to denote links. Hover state would be good to include also for both.

**Comment by wmbutler** [comment]
- Add underlines for each symbol to denote link
- Add blue? hoverstate

**Comment by startailcoon** [comment]
> I think the asset pairs in the recent market picker mock ups had underlines to denote links. Hover state would be good to include also for both.

They did not, but they are now since PR #1561

@wmbutler, solved in PR #1561 for issue #1555
