### ISSUE TITLE
[2] Proposed transactions not updating properly in the ChainStore

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#1528]
**Describe the bug**
When a proposal has authorities added or removed, and when it is fully approved, the ChainStore does not properly merge the changes and does not remove completed proposal id's from the `account.proposals` array.

**To Reproduce**
Create a proposed transfer, add an approval then remove it, or completely approve it.  In the first case the approval does not get removed, in the second the Margin Positions tab still shows 1 proposed transaction.

**Expected behavior**
Approvals should be removed and the count of proposed transactions should update.

**Additional context**
Need to be fixed in bitsharesjs. This is the cause of https://github.com/bitshares/bitshares-ui/issues/727

**Comment by abitmore** [comment]
Perhaps related to https://github.com/bitshares/bitshares-core/issues/776 ? The back end doesn't notify the UI under certain circumstances.

**Comment by svk31** [comment]
https://github.com/bitshares/bitsharesjs/commit/9a088f1a69

**Comment by svk31** [comment]
I'd already found and fixed the bug in bitsharesjs, just wanted to document it.
