### ISSUE TITLE
[0.5][happyconcepts] Expiration Time display in Open Orders 

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#1529]
Order expiration time(s) shown via tooltip in Open Orders display on the Exchange page are not displayed in user's local time. Please refer to #1397 for expected behavior and screenshot.

Unlike the modal, multiple orders can be displayed on this page. I don't see it taking more than 1 hour, mostly testing. Since this was out of scope for that issue, I have started this new one. 

I would like to claim this and can deliver for the next sprint. Greetings from Los Angeles.

**Comment by startailcoon** [comment]
@happyconcepts how is your work progressing? You mentioned that this would be delivered to "next sprint" last month. Do you still plan on completing this task or release it?

**Comment by happyconcepts** [comment]
@startailcoon The wrong information you gave me on #1570 has only delayed me momentarily on this issue.

**Comment by startailcoon** [comment]
Just checking in on uncompleted issues. Sorry for the unintentional confusion on your other issue.

**Comment by happyconcepts** [comment]
I believe you could help with debugging on #1570 and finish what you started with the node selection mess, but it's not my job to set your priorities.

**Comment by happyconcepts** [comment]
I guess I will do this today for the new develop branch @wmbutler thanks for your support.

**Comment by svk31** [comment]
@happyconcepts what's with the attitude? I looked at the issue and he didn't give you any wrong information.

**Comment by startailcoon** [comment]
@happyconcepts I don't see the reason for your tone here. Please keep your comments constructive.

I don't understand what you mean about "finish what you started with the node selection mess". I've only made a comment in the discussion. The node handling have been worked on for several different issues before and can still need more attention as mentioned there.

**Comment by happyconcepts** [comment]
> @happyconcepts what's with the attitude? I looked at the issue and he didn't give you any wrong information.

Hidden nodes do not autoconnect? My client connected to a compromised Open Ledger domain despite being hidden. But that's another issue #1570 not this one.

**Comment by happyconcepts** [comment]
@startailcoon:

> I don't see the reason for your tone here. Please keep your comments constructive.

You know, I was about to say the say exact thing to you. Because here we are, in the only two issues I have right now on this project, and you @startailcoon have not provided a single constructive comment.

My neck happens to be broken from a car accident, but that's not going to change the disgustingly dismissive tone you have used toward me and any of my comments, contributions, etc since I started in July almost a full year ago.

**Comment by startailcoon** [comment]
happyconcepts you having an accident is unfortunate, but I don't see the relevance of bringing it up here. If you have found my comments disgruntled, it was not my intention.

As soon as I have some time over, probably tomorrow, I can help you out with debugging your other issue, which are indeed relevant as you've mentioned. I have never tried to say otherwise. 

Let's move forward and find solutions to our issues instead.

**Comment by gibbsfromncis** [comment]
@happyconcepts stop to be like a dick. Anyway, your personal things or accidents or anything else don't give you any reason to rude or blame other guys who tries to help you and bitshares at all. Be polite anytime. If you can't deliver your work just unassign yourself or wait while somebody other will unassign you.

**Comment by gibbsfromncis** [comment]
@happyconcepts Anyway, nobody shouldn't help you. Guys expect from you just 2 things - request to claim and pull-request with the done issue. We spend our time to help you earn money and deliver your work. If you continue to be like an asshole you won't get any help or responses (especially from my side, I cannot answer from other guys)

**Comment by happyconcepts** [comment]
You have never helped me @gibbsfromncis, so it's quite shallow and egotistical for you  to suggest that you will "stop" helping me.

> Hidden nodes do not autoconnect? My client connected to a compromised Open Ledger domain despite being hidden. 

This remains the technical issue, but instead of help you continue to choose to attack me with ad hominem...

This is the communication issue, and what I replied to @startailcoon:

You know, I was about to say the say exact thing to you. Because here we are, in the only two issues I have right now on this project, and you @startailcoon have not provided a single constructive comment.

And look at this, none of you address the issue. Now you salivate about using my broken neck to make your case that I am the dick.

Can I get back to working on this issue now, or will you continue to turn this repo into a bullshit chatroom?

**Comment by svk31** [comment]
@happyconcepts please just stick to the issue, the simple question that triggered your ranting still remains unanswered: do you intend to complete the issue or can someone else take it over?

**Comment by happyconcepts** [comment]
it's basically done @svk31. I just have to figure out how to migrate my process to the develop branch, and with a broken neck it's hard enough. All the fuzzing and heckling just delays it. Anyone else's issues languish for months but mine is selectively enforced because ... there is so much love here for me?

So this PR should arrive by Saturday June 23 to develop and I hope that is acceptable with enough time in staging prior to the newly slated July 1 sprint.

Thank you sigve for your sensibility.
