### ISSUE TITLE
[.5][gibbsfromncis][1][svk31] No error message shows when trying to issue a big amount of asset

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1530]
**Describe the bug**
No error message shows when trying to issue a big amount of asset

**To Reproduce**
1. Go to testnet.bitshares.eu
2. Click on hamburg menu -> assets
3. Click on "Issue asset"
4. Input an account name, a big amount e.g. 1000000000000000, click "issue asset"

**Expected behavior**
A message should appear to indicate the action succeeded or failed

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version Latest

**Additional context**

**Comment by wmbutler** [comment]
We must define a "big amount" I assume. Discuss.

**Comment by gibbsfromncis** [comment]
@wmbutler If you agree to increase bounty if this task take more time - I'll take it

**Comment by startailcoon** [comment]
I'm sure we can increase the hours to support this issue to be completed.

Let's increase it to two hours and track your time off it takes much more.

**Comment by svk31** [comment]
That's from bitsharesjs and the long lib, can you give me a test case to reproduce it?

**Comment by gibbsfromncis** [comment]
@svk31 Hm.. I cannot push my code to bitshares-ui directly so I've pushed to my fork: https://github.com/gibbsfromncis/bitshares-ui/commit/c340305918f8ab8a44009d99585bcd1bf2a5c6eb

Steps:
1) Create any asset
2) Tap "Issue Asset" on created asset and put number larger than supply 
3) Submit form and you get this error. 

Btw don't forget to add error handler (take a look my commit above)

Thx

**Comment by wmbutler** [comment]
Pending @svk31

**Comment by svk31** [comment]
The overflow error happens before trying to process the transaction, that's why you can't catch it. I've made some minor changes to how the issue asset method is used and handles errors, for now it just pops up a notification that the asset issue failed.

**Comment by gibbsfromncis** [comment]
@svk31 Do I understand correct that you already fixed this bug and I should just unassign myself and assign you?

**Comment by svk31** [comment]
I just investigated the error catching you pointed out, and once fixed I simply moved the existing error message to the correct location.

I guess that did fix the issue, in that case the hour estimate was too high, only took me 45mins or so. You probably spent some time on this as well though so we can add that.

**Comment by gibbsfromncis** [comment]
@svk31 I've assigned you to this issue and splitted hours between both of us
