### ISSUE TITLE
[testnet] Cannot open node configuration page

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1531]
**Describe the bug**
Blank screen.

**To Reproduce**
1. Go to testnet.bitshares.eu
2. Click on hamburg menu -> settings
3. Click on "Nodes"
4. page doesn't load
5. https://testnet.bitshares.eu/settings/access doesn't load as well

**Expected behavior**
Page loads.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/40267498-949600e6-5b5d-11e8-8fb2-82e1427588ce.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version Latest

**Additional context**

**Comment by startailcoon** [comment]
I do not have this issue in the latest client of Bitshares UI (180509).
What version of the UI is testnet.bitshares.eu running? It's not visible at the bottom of the page as it usually is.

**Comment by abitmore** [comment]
@startailcoon more context about testnet:
* there is no "auto-selection" option
* domain name of the first node doesn't resolve

**Comment by svk31** [comment]
@xeroc A testnet GUI update would fix this.
