### ISSUE TITLE
[1] Generated password doesn't show completely

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1532]
**Describe the bug**
Account creation page, the generated password is too long, or font is too big.

**To Reproduce**
1. Go to https://wallet.bitshares.org/#/create-account/password with a new incognito window

**Expected behavior**
The whole password will show on page

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/40267535-67b4787c-5b5e-11e8-89fd-f843914e1c04.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version latest

**Additional context**

**Comment by abitmore** [comment]
Larger screenshot:
![image](https://user-images.githubusercontent.com/9946777/40267550-98f2452c-5b5e-11e8-9689-31d6a6968cf4.png)

**Comment by happyconcepts** [comment]
Probably due to the font size increase.

**Comment by wmbutler** [comment]
Let's reduce the font size to accommodate. I view this as a serious bug since some users will unwittingly copy and save only a portion of their password. Recommend a hotfix.

**Comment by startailcoon** [comment]
With an decreased font size, we can easily accomedate the password inside the input box.
![image](https://user-images.githubusercontent.com/12114550/40578532-e2ef0bee-6115-11e8-9fdf-d24c543a63a0.png)

However, there is an issue when the user is on a mobile device. The input field is now much more narrow, not viewing the whole string. However, the user doesn't copy the password by selecting it in the input (as it's disabled), but uses the copy button on the right. 

The user also has to type the whole password into the text box below, ensuring that the user actually copied the password from the box abow correctly. 

I do not see this as an imediate issue, but could be a thing for later when we have a proper responsive design in place.

![image](https://user-images.githubusercontent.com/12114550/40578539-ec83044e-6115-11e8-9147-5b83fbbe395b.png)

**Comment by startailcoon** [comment]
Using `<textarea>´ instead, resulting in the following layout.

Field is readonly and disabled, forcing the user to click the copy button as before. Firefox allow the textarea to be resized by standard.

# Edge
![image](https://user-images.githubusercontent.com/12114550/41174379-494a261e-6b5a-11e8-968a-dd5cc312b16c.png)

# Firefox
![image](https://user-images.githubusercontent.com/12114550/41174405-5886b3fe-6b5a-11e8-8674-5442bf2edfc7.png)
