### ISSUE TITLE
[0.5] Market page sometimes doesn't load

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1533]
**Describe the bug**
Market page sometimes doesn't load.

**To Reproduce**
1. Go to https://testnet.bitshares.eu/market/ASDFASDF_TEST
2. blank screen

**Expected behavior**
Page loads.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/40267763-e2e4bdd2-5b62-11e8-9c5d-b34ab3885492.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version Latest

**Additional context**
* There are buy orders on the book
* No sell order on the book
* There are settle orders
* There are a few order filling entries in history

**Comment by abitmore** [comment]
Key point to reproduce: my account has pending settle orders.

**Comment by svk31** [comment]
I did find a bug in MyOpenOrders, could be what caused it but it's hard to tell from the minified debug output. Also added a missing operation key for asset_settle_cancel so it shows properly in your transaction history.
