### ISSUE TITLE
[.5] Wrong digits for core exchange rate in asset update page

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1534]
**Describe the bug**
Unable to change core exchange rate of an asset to 1 Satoshi : 1 Satoshi.

**To Reproduce**
1. Go to https://testnet.bitshares.eu/account/abit-test/update-asset/ASDFASDF
2. Click on QUOTE ASSET AMOUNT
3. Can only input 4 digits after decimal point, while the precision of TEST is 5
4. Click on BASE ASSET AMOUNT
5. Able to input 5 digits after decimal point, while the precision of ASDFASDF is 4

**Expected behavior**
Able to input minimum value (1 Satoshi) of corresponding assets.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/40268040-b56df6ee-5b66-11e8-813c-ae881bf994b8.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version latest

**Comment by startailcoon** [comment]
**Claimed hours: 0.5**
