### ISSUE TITLE
[.75] Account activities page issues

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1535]
**Describe the bug**
1. inconsistent asset symbols
2. some asset symbols aren't clickable
3. other asset symbols show a question mark when on mouse hover, but nothing will show after clicked

**To Reproduce**
1. Go to https://wallet.bitshares.org/#/account/committee-account

**Expected behavior**
Consistent, easy to use UI.

**Screenshots**

![image](https://user-images.githubusercontent.com/9946777/40268410-015f53bc-5b6d-11e8-824d-8bf57b496ec7.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version Latest

**Comment by startailcoon** [comment]
**Claimed hours: 0.5**
