### ISSUE TITLE
[1][HarukaMa] Can't create a smartcoin which is backed by an UIA

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1537]
**Describe the bug**
Can't create a "smartcoin" which is backed by an UIA

**To Reproduce**
1. Go to https://wallet.bitshares.org/
2. Click on hamburg button, click assets
3. Click "create asset"
4. In "Primary settings" tab, click "SmartCoin"
5. Click "smartcoin options" tab, scroll down, input "AAA" in "SHORT BACKING ASSET" box
6. Shows error "That asset may not be used"
7. fill in other fields. click "create asset" button
8. login, confirm the transaction
9. asset is created which is backed by CORE asset (BTS in mainnet, TEST in testnet)

**Expected behavior**
Able to create asset that is backed by an UIA.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/40268605-01a57406-5b71-11e8-9582-860cb3bae6e1.png)

**Comment by grctest** [comment]
Isn't it by intended design that you can only back a smartcoin with BTS or MPA (which are backed by either MPA or BTS)? If an UIA was used then perhaps fractional reserve could be a concern with such backing - you could manipulate a non-liquid market then back the MPA with the inflated UIA, no?

**Comment by abitmore** [comment]
>... no?

No.

**Comment by grctest** [comment]
I disagree, IMO the reason why UIA cannot back MPA is because there's no
proven backing collateral value behind an UIA (effectively an IOU) thus
using it as backing collateral would be open for abuse.

What use case would this be necessary for? Why not use BTS or another MPA
as backing collateral?

**Comment by abitmore** [comment]
The logic is: asset issuers should be able to do whatever they want according to their business logic.

BTW if you don't trust or like an asset, don't use it.

**Comment by abitmore** [comment]
Scenario: I (as an asset issuer) issued my IOU USD backed by fiat in bank, now I want to create a prediction market to predict whether Trump will be next president of US, all my customers/clients can only participant in this market with my IOU USD. So the best approach for me is to create the new asset backed by my IOU USD. In this case BTS or other MPA are irrelevant.

**Comment by clockworkgr** [comment]
@grctest Legitimacy, proven backing etc. doesn't come into it...if core & the chain allows it, the reference UI should not place any further constraints.

**Comment by grctest** [comment]
@clockworkgr As far as I was aware the only allowed backing collateral for MPA in the BTS DEX was BTS itself and other MPA, the [MPA docs](http://docs.bitshares.org/bitshares/user/mpa.html#collateralized-tokens) make no reference to UIA being used as backing collateral - only Bitshares.

"What makes MPAs unique is that they are free from counterparty risk even though they resemble a collateralized loan." UIA backing would reintroduce counterparty risk, given that an UIA could have no real backing where as we know that Bitshares collateral is worth one of itself.

---

@abitmore How does the prediction market feature require the creation of an UIA backed MPA? Wouldn't it make more sense to allow backing prediction markets with your UIA?

"The logic is: asset issuers should be able to do whatever they want according to their business logic."

That logic breaks down if their business logic has a detrimental effect on Bitshares itself.

**Comment by abitmore** [comment]
@grctest PM's are special MPA's, thus need to specify collateral type (backing asset).

**Comment by abitmore** [comment]
When it comes to marketing, if we're using "smartcoins" for BTS backed assets, perhaps better to invent another name for UIA backed MPA, E.G. `Privatized SmartCoins`. Anyway, **UI need to present the differences**.

**Comment by happyconcepts** [comment]
@abitmore the error message in graphene is this:
> "May not create a bitasset backed by a bitasset backed by a bitasset." 

Do not make the mistake to think this error contains a duplicate typo.

I believe it is to the point made by @grctest, that *uncollateralized* "smart" coin is serious potential for fraud.

I believe the restriction to be a feature @dan thought to prevent making "smart" wrappers around uncollateralized coins.

**Comment by abitmore** [comment]
@happyconcepts as I mentioned above, there are use cases. The message you mentioned is not a typo, but is a restriction for better performance, actually I think we can be even looser (think bigger).

**Comment by HarukaMa** [comment]
I'd like to claim this, but have one extra question: is it true that only PMs can't be used as backing asset?

Should have researched it myself, but like to confirm it here.

**Comment by grctest** [comment]
@HarukaMa How have you gotten on with this change? I think this will encourage a lot of new MPA being created via the UI.

> PMs can't be used as backing asset?

I don't think there's a limit to how many times you can nest an MPA, nor should there be. It makes sense to prevent prediction market assets from being backing collateral since they can drop to 0 (forever) once resolved.

**Comment by abitmore** [comment]
@happyconcepts you can only change backing asset id when there is exactly `0` supply.

**Comment by startailcoon** [comment]
I can't see that this issue is resolved. A UIA can still not be selected in the UI.
@HarukaMa

**Comment by HarukaMa** [comment]
PR is on #1804. Checked "a bitasset backed by a bitasset backed by a bitasset" and made create button gray out if backing asset is not acceptable.

**Comment by sschiessl-bcp** [comment]
Done & Closed

**Comment by sschiessl-bcp** [comment]
Increased hours due to https://github.com/bitshares/bitshares-ui/issues/1539#issuecomment-419645671
