### ISSUE TITLE
[1][harukama] Error "That asset does not have the same precision"

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1538]
**Describe the bug**
Should only show that error when creating a prediction market asset, but not every smart coin.

**To Reproduce**
1. Go to https://wallet.bitshares.org/
2. Click on hamburg button, click assets
3. Click "create asset"
4. In "Primary settings" tab, click "SmartCoin"
5. Click "smartcoin options" tab, scroll down
6. Shows error "That asset does not have the same precision"

**Expected behavior**
Don't show the error message when not creating a prediction market.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/40268688-2a2e2a7a-5b72-11e8-8f04-2bf6b61fef41.png)

**Comment by grctest** [comment]
I see the same for the Hertz smartcoin settings, it doesn't explain what the consequences are & AFAIK you can't change the precision of a smartcoin. It doesn't seem to stop the operation of the Hertz ABA though.

![image](https://user-images.githubusercontent.com/15861527/40273789-206614c4-5bbf-11e8-985a-7936cdcd90d1.png)

**Comment by HarukaMa** [comment]
I'd like to claim this, but I think this does not worth 1hr. My initial try only added 2 lines of code to achieve this.
