### ISSUE TITLE
Unable to update a smart coin's backing asset

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1539]
**Describe the bug**
Should be able to update backing asset when supply is zero.

**To Reproduce**
1. Go to https://wallet.bitshares.org/
2. Click on hamburg button, click assets
3. Click "update asset" of an smart coin which has zero supply
4. Click "smartcoin options" tab, scroll down
5. After changed asset name in "short backing asset" box, the "update asset" button is still disabled
6. Change something else in the page
7.  click "reset" button, backing asset doesn't change
8. change something else in the page
9. Click "update asset" button
10. login,
11. check info in transaction confirmation page, the backing asset is not changed

**Expected behavior**
Able to change backing asset when supply is zero.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/40268742-419fe9f4-5b73-11e8-8f51-8c9bb02352bf.png)

![image](https://user-images.githubusercontent.com/9946777/40268744-54ea5bfc-5b73-11e8-9f6a-4ba4b88fc847.png)

![image](https://user-images.githubusercontent.com/9946777/40268745-6a994f76-5b73-11e8-91c1-96b22396d798.png)

![image](https://user-images.githubusercontent.com/9946777/40268748-882d6f0e-5b73-11e8-8b92-5ef741635abf.png)

**Comment by happyconcepts** [comment]
Related to #1537

**Comment by gibbsfromncis** [comment]
@wmbutler looks like easy task. I'll take it but if it take more time I'll let you know

**Comment by startailcoon** [comment]
Unassigned @gibbsfromncis, free to claim by anyone.

**Comment by kapeer42** [comment]
Can I claim this?

**Comment by wmbutler** [comment]
It's yours @kapeer42

**Comment by startailcoon** [comment]
@kapeer42 I believe you're right here. The issue has been fixed by another.

However, I ran in to a new problem when I tried to verify this myself.
Using testnet I navigated to update asset for one of my smart coins, and once I clicked the tab for smartcoin options I recieved the following.

**Comment by kapeer42** [comment]
Woops, forgot to open an issue for that.
The `default` case in the `onChangeBitAssetOpts` `switch` is wrong, it should do nothing I think.
Here goes the PR: #1834

Not related to this, @svk31  (`git blame` shows it's you who wrote those lines, pardon me if I'm mistaken) [this](https://daveceddia.com/why-not-modify-react-state-directly/) could be a good read on why mutating state directly and using `forceUpdate` is bad.

**Comment by sschiessl-bcp** [comment]
Adjusted hours to accomodate https://github.com/bitshares/bitshares-ui/issues/1539#issuecomment-419714431

**Comment by sschiessl-bcp** [comment]
The UI allows to change parameters of a smartcoin with > 0 supply, which is not supported by the backend. 

UI should indicate that to the user in some way

**Comment by kapeer42** [comment]
Aye

**Comment by sschiessl-bcp** [comment]
@abitmore

Could you please confirm which parameters are NOT allowed to change if supply > 0 from the backend?

**Comment by abitmore** [comment]
@kapeer42 can you tell us the block number of your test on testnet, and/or your account?

@sschiessl-bcp when supply > 0, unable to change
* backing asset,
* issuer_permissions.

**Comment by abitmore** [comment]
The screenshots in OP is an example to indicate: if I changed "delay of forced settlements", the "save" button will be enabled; if I changed "backing asset", the button remains disabled.

**Comment by grctest** [comment]
It's also impossible to change backing asset when your asset has been selected by an MPA as its backing collateral, an error message only displays once you attempt to submit the changes not when you enter a different asset in the backing collateral field.

Ideally an MPA should only be able to select another MPA as its backing collateral if its supply is greater than 0.

**Comment by wmbutler** [comment]
Where are we on this?

**Comment by kapeer42** [comment]
Everything except @grctest comment should have be addressed.
Also see https://github.com/bitshares/bitshares-ui/issues/1578#issuecomment-426741029

**Comment by startailcoon** [comment]
@kapeer42 please review your code and submit a new PR as your PR #1852 was reverted by @sschiessl-bcp in PR https://github.com/bitshares/bitshares-ui/pull/1878

@sschiessl-bcp there is no documentation on why this was reverted. I assume there has been a discussion about this somewhere together with @kapeer42

**Comment by sschiessl-bcp** [comment]
That was a double revert (#1884) to cut out the new Exchange Layout from staging. 

I would like @kapeer42 to assess the comments made in here, and reflect on what is still missing in terms of disabling / enabling and create a new issue for it. I consider this issue closed as it concerns only the backing asset, also it seems to entangled to keep it open further.

**Comment by kapeer42** [comment]
@grctest I just tried to change the backing asset of an MPA that is the backing asset of another MPA and the transaction was accepted so there seems to be no issue there. Maybe I misunderstood your comment?

**Comment by sschiessl-bcp** [comment]
> Ideally an MPA should only be able to select another MPA as its backing collateral if its supply is greater than 0.

I think the comment was targeting this specific use-case. I think that check is not necessary, as anyone must judge themselves what the collateral should be.

@kapeer42 The initial description and https://github.com/bitshares/bitshares-ui/issues/1539#issuecomment-420351499 is implemented?

**Comment by kapeer42** [comment]
@sschiessl-bcp Yes

Initial description by  https://github.com/bitshares/bitshares-ui/pull/1804, https://github.com/bitshares/bitshares-ui/pull/1834 and https://github.com/bitshares/bitshares-ui/pull/1849
And the https://github.com/bitshares/bitshares-ui/issues/1539#issuecomment-420351499 by https://github.com/bitshares/bitshares-ui/pull/1852
