### ISSUE TITLE
[1] Allow user to type in and jump to a specific block

### ISSUE THREAD

**Issue by todasun** [bitshares/bitshares-ui#154]
when user want to check a specific Block for  trans details(such as memo)
the chain explorer can't Quick location   
click the arrow  so many times to find an old  specific Block (3s/block   a block 24h ago,needs 24*60*20=28800 click)

![image](https://cloud.githubusercontent.com/assets/10720816/26294420/304cd0da-3ef6-11e7-8cf4-2e4166b06430.png)

**Comment by todasun** [comment]
when use web wallet  ,modify URL can Quick location   a specific Block

**Comment by wmbutler** [comment]
Allow user to enter a block by typing it in.

**Comment by wmbutler** [comment]
- Clicking on the block number at the top should expose an input field (without the # sign)
- Typing in the block and pressing enter should hide the input field and navigate to block
