### ISSUE TITLE
[1][swoopyy] Unable to hide certain nodes

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1541]
**Describe the bug**
Unable to hide certain nodes. I wish to hide all nodes not related to testnet, and 2 nodes are still present and unable to hide. Hiding nodes is also very slow at times and no responsive when clicking on the hide icon. 

**To Reproduce**
1. Go to Settings->Nodes
2. Click on hide nodes

**Expected behavior**
Expected to hide the node

**Screenshots**
![bitshares-issue_hidenodes](https://user-images.githubusercontent.com/12114550/40271365-a14abad6-5b9c-11e8-9cf2-60b3161fcc27.gif)

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser Firefox
 - Version 60.0 64-bit

**Comment by swoopyy** [comment]
can I claim this?

**Comment by sschiessl-bcp** [comment]
This might be old nodes that are no longer in the apiConfig as default and only in the local cache.

**Comment by clockworkgr** [comment]
Dunno about the CN one but mine should be in the apiConfig (and i believe it is)
