### ISSUE TITLE
No ability to scroll down on Exchange tab to see orders after TradingView integration

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1549]
@wmbutler @svk31 @ahdigital 

I'm working on TradingView styling and I have one issue which makes me very angry.

This how Exchange looks like on my Macbook Pro 15':

<img width="1436" alt="1" src="https://user-images.githubusercontent.com/35899973/40419554-fe39cb24-5e85-11e8-9681-a2e791bdebf1.png">

1) Scroll on Macbook
2) Chart area

Trouble is that Chart handles ALL scroll events and zoom chart. I'm unable to scroll down to see orders for buy/sell. The only one way to do it is to move mouse on Scroll. It's so terrible. If you want deploy TradingView charts lets fix it before deploy because this issue will make a lot of users VERY ANGRY.

**Comment by gibbsfromncis** [comment]
Btw I know we have issue for Exchange new UX. But this one will be deployed at least in two weeks. During this 2 weeks we will make our users and ourself very unhappy

**Comment by startailcoon** [comment]
In my opinion, I don't think that TV should handle scroll events, like zoom in/out.

Optimal would be a "lock" feature if you wish to handle it that way manually by user choice.

**Comment by gibbsfromncis** [comment]
@startailcoon I'm not sure it's possible but nice idea. I'll check it today

**Comment by ahdigital** [comment]
Google gets around this type of issue on its [mapping service](https://developers.google.com/maps/documentation/embed/guide) by allowing the user to zoom in/out with either:

- Mouse down and scroll wheel, or
- 'CTRL/CMD' and scroll wheel

As the user scrolls over the map there's an overlay to provide the user with a hint. Perhaps this would be an avenue to explore.

I can't find any documentation to find out for myself, but can we choose what toolbars and drawing tools to display? Looks like there's a lot there - maybe these could be condensed somehow.

**Comment by wmbutler** [comment]
I think this a temporary problem until the excahnge redesign. Can we live with it until that point?

**Comment by tbone-bts** [comment]
I understand OP's frustration.  But I also get the other side of the equation since I'm a Tradingview user who relies very heavily on the trackpad scroll gesture (equivalent to scroll wheel) to zoom the charts in/out.  So if there is an elegant solution that can be implemented (like holding down ctrl when you want to zoom instead of scroll) that would be the best of both worlds.  Until something like that can be implemented, though, I agree with disabling the zoom so the pane will scroll.
