### ISSUE TITLE
[1.5] Unable to access the test network on the latest release

### ISSUE THREAD

**Issue by mikakoi** [bitshares/bitshares-ui#1550]
**Describe the bug**
Using the test network nodes seems to crash the client on the latest release (2.0.180512). 
Not sure in what version the bug was introduced but I reverted my client back to version 2.0.180418b and it seems to work just fine.

The problem appears in both the desktop client and the web client

**To Reproduce**
Just change the node to either wss://node.testnet.bitshares.eu or wss://testnet.nodes.bitshares.ws

**Expected behavior**
I expect the client to work when using the test network

**Additional context**
Browser console seems to give out this error:
```
app.js:17 Dynamic page loading failed TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (app.js:17)
    at h.getHostNode (app.js:17)
    at Object.getHostNode (app.js:17)
    at h.getHostNode (app.js:17)
    at Object.getHostNode (app.js:17)
    at h.getHostNode (app.js:17)
    at Object.getHostNode (app.js:17)
    at h.getHostNode (app.js:17)
    at Object.getHostNode (app.js:17)
    at h.getHostNode (app.js:17)
```

**Comment by KristerV** [comment]
Hmm, I connected to the EU testnet and the browser went crazy, website is blank. Full output is on [Pastebin](https://pastebin.com/eeyGQHZH), here's the notable lines:

```
Warning: Failed prop type: Required prop `toAsset` was not specified in `TotalValue`.
Uncaught TypeError: Cannot read property 'get' of null
The above error occurred in the <TotalValue> component:
TypeError: Cannot read property 'get' of null at eval (MarketStatsCheck.jsx:131)
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

Node.js server console has not said anything at all. Hmm.. I'm on the branch staging at 99867a665aaa936c5d5f8a5273c2c6a70e596623.
