### ISSUE TITLE
[1] Cannot cancel orders in Firefox from Open Orders page

### ISSUE THREAD

**Issue by ppitonak** [bitshares/bitshares-ui#1553]
**Describe the bug**
Cannot cancel orders in Firefox 60 from Open Orders page

**To Reproduce**
1. Go to Open Orders page
2. Select a checkbox next to any open order, Reset & Submit buttons appear
3. Click Reset or Submit button

**Expected behavior**
* Reset - form is cleaned, i.e. no open order is selected
* Submit - order is cancelled

**Screenshots**
![peek 2018-05-24 11-19](https://user-images.githubusercontent.com/445100/40476801-37e7ac46-5f45-11e8-8514-0031acd90e68.gif)

**Desktop (please complete the following information):**
 - OS: Fedora 28
 - Browser Firefox
 - Version 60.0

**Smartphone (please complete the following information):**

**Additional context**
Works fine in Chrome

**Comment by startailcoon** [comment]
Issue was due to the click event was not set to the button, but the translation.

Fixed for Firefox, and other browsers

![bitshares-cancel](https://user-images.githubusercontent.com/12114550/41182901-0e4fc8d4-6b78-11e8-8b0d-bff003a46ba5.gif)
