### ISSUE TITLE
[1] Propose transfer of BTS asset has precision issue

### ISSUE THREAD

**Issue by tianyekuo** [bitshares/bitshares-ui#1556]
**Describe the bug**
When send BTS asset to other user with proposal, the quantity will be round with 0 precision.

**To Reproduce**
1. Click Send(legacy)
2. Input "From" field with a mutil-signed account.
3. Click Propose link
4. Input 1.1 BTS 
5. Begin to propose
6. Check the confirm dialog

**Expected behavior**
Step 6 show proposed operations: Transfer 1.1 BTS

**Issues**
Step 6 actually show “Transfer 1 BTS”.
If transfer 1.5 BTS, then the confirmation page show "Transfer 2 BTS".

**Comment by startailcoon** [comment]
Removing `decimalOffset` for proposed transaction solves this issue.

Preview below views that BTS, USD and Peerplays are rounded as expected even without this code.

![bitshares-propose](https://user-images.githubusercontent.com/12114550/41182220-fac49fd6-6b74-11e8-8378-93b6ae848cb9.gif)
