### ISSUE TITLE
[2] Show Order ID consitently

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1557]
**Is your feature request related to a problem? Please describe.**
When an order is cancelled, the order ID will show in account history. But the ID doesn't show elsewhere, so the user doesn't know which order is cancelled.

* Has ID when cancelled an order
* No ID when created an order
![image](https://user-images.githubusercontent.com/9946777/40541137-dbc4ac08-601a-11e8-9dd9-838dfe36684b.png)

* No ID in "Open Orders"

![image](https://user-images.githubusercontent.com/9946777/40541187-0fbf17be-601b-11e8-9651-1c5888d14c57.png)

**Describe the solution you'd like**
Show ID everywhere.

**Describe alternatives you've considered**

**Additional context**

**Comment by wmbutler** [comment]
- [ ] Add order id to Open Orders

**Comment by abitmore** [comment]
@wmbutler also to account history when 
- [ ] a new order is created
- [ ] an order is partially filled

**Comment by startailcoon** [comment]
# Open Order
![bild](https://user-images.githubusercontent.com/12114550/41178675-56d970c4-6b68-11e8-9244-4bc7aab3c39a.png)

# Account Activity
![bild](https://user-images.githubusercontent.com/12114550/41178795-af28cef0-6b68-11e8-8053-97e7d1e7e0b7.png)
