### ISSUE TITLE
Tradingview chart toggle and sizing buttons

### ISSUE THREAD

**Issue by tbone-bts** [bitshares/bitshares-ui#1559]
It's really great to see Tradingview charts in the Bitshares wallet.  Nice work!  I just have a couple items of feedback: 

1. It's incredibly inconvenient to switch between price chart and depth chart now.  There used to be a toggle, now it's a drop down AND it's buried within Chart Options.  I really hope to see re-implementation of the toggle at the top of the page. 

2. Having to go into the Chart Options, and then further having to type a value to change the chart size is also very inconvenient.  It would make a ton of sense to have side-by-side UP and DOWN arrow buttons located above the chart (next to the toggle) that increase and decrease the height of the chart, as Bitfinex has done. 

By the way, I didn't see any drawing tools on the new charts.  Are those disabled?

Thanks.

**Comment by alcafo** [comment]
Me too I do not see any drawing tools same issue (even If I click right button and drawing tools are ON) and if I add any indicator after restarting the dex all indicators are gone

**Comment by startailcoon** [comment]
I propose that we remove the chart controls from the exchange header, as we will need all the space we can get for other things.

My UX proposal for this is as follows

The buttons `Increase` and `Decrease` will change the chart height by a fixed number, example 50px +/-.
Do we need the user to be able to set a number of their own?

![image](https://user-images.githubusercontent.com/12114550/40584161-fc543b7c-619c-11e8-8842-04b3104b1569.png)

**Comment by startailcoon** [comment]
@svk31 @wmbutler @abitmore, any comments regarding the UX?

**Comment by svk31** [comment]
Not a big fan but I'm not a UX guy either... We used to have increase/decrease with just a + and a - sign, I think that might look better. The code is still there so would be easy to add anyway.

About the drawing tools, they're probably hidden if you're on a small screen which triggers the `mobile` version. I see them just fine on the left side of the chart:

![image](https://user-images.githubusercontent.com/6890015/40675832-20fd1bdc-6379-11e8-922b-9d2cf9d938e1.png)

**Comment by wmbutler** [comment]
My thoughts on the contents of the tradingview area:

- [ ] Remove market pair indicator, This is redundant in our case.
- [ ] Remove Volume indicator
- [ ] Revert to toggle for Market Depth

I don't see a huge need to have the height controls displayed so prominently. This should be a set it and forget it option.

**Comment by alcafo** [comment]
@startailcoon thanks for your answer, I am running bitshares latest version in MAC and I tried too in a laptop with ubuntu, both without drawing tools, here is my screenshot and as you can see drawing tools are ON
![screenshot](https://user-images.githubusercontent.com/39630646/40679575-d4acc718-6383-11e8-8f75-669b27ecd3aa.png)

**Comment by svk31** [comment]
You don't have the toolbar on the left, which means you have a small screen (low horizontal resolution). Try resizing to fullscreen, you might need to refresh afterwards.

**Comment by svk31** [comment]
Why remove the volume?  It's very useful imo

**Comment by tbone-bts** [comment]
> @wmbutler: I don't see a huge need to have the height controls displayed so prominently. This should be a set it and forget it option.

I totally disagree, this is not a set it and forget control.  It depends on what you are doing.  It also depends on whether you are in horizontal or vertical order book mode.  Burying these controls in "Chart Options" is frustratingly inconvenient.  

Vertical chart resizing controls don't need to take up much space.  Bitfinex handles it with an up and down arrow (see link below).  Also, "Chart Options" can be changed to a gear icon to take up less space (if there's even still a need for Chart Options, that is).  

http://allcoinsnews.com/wp-content/uploads/2017/02/chart-bitfinex-btc-usd-24hours-2017-02-21.png

**Comment by clockworkgr** [comment]
@svk31  Just want to confirm that under Chrome in Windows 10, 1920x1080 res:

Drawing tools are NOT visible.

100% Zoom:
![image](https://user-images.githubusercontent.com/6826762/40688401-9e84ec42-63a6-11e8-86a2-c347fd1c8aad.png)

90% Zoom: (What I normally run it at. 100% zoom font sizes are way too big)
![image](https://user-images.githubusercontent.com/6826762/40688446-c4c925c6-63a6-11e8-9733-35aac17bb779.png)

80% Zoom (Drawing bar FINALLY Visible):
![image](https://user-images.githubusercontent.com/6826762/40688470-e21d9daa-63a6-11e8-972b-1bf95310cd4c.png)

Your comment, combined with the fact that I always wondered why default font-sizes were so big (leading me to run it at 90% zoom) leads me to believe that you guys are unfamiliar with the way the wallet looks under a standard FullHD (1920x1080) setup which is probably the most common.

**Comment by tbone-bts** [comment]
I should have mentioned that I'm using 1920x1080 here as well.  

Anyway, I'm thinking there must be a TradingView setting to handle this problem.  It appears currently that **if** there isn't enough room to display 14 tool icons plus a scroll button to show more, then the toolbar doesn't display at all.  Maybe that 14 can be set to a lower number.  Or even better, maybe there is a setting that will enable the display of as many as can fit...and then you scroll (or click ellipsis) for the rest.  

One of those is clearly possible since you can see in the Bitfinex image I linked previously that only 10 chart tool icons are visible, plus an ellipsis to show more.

**Comment by wmbutler** [comment]
Keep in mind, that the exchange redesign has not yet been completed. I'd say we should avoid any extra work until the new UX https://github.com/bitshares/bitshares-ui/issues/1449 is complete.

**Comment by clockworkgr** [comment]
@wmbutler totally agree... I only commented cause the conversational exchange makes me feel there is the need for better testing across resolutions.

Are you all on Macs? :D

**Comment by wmbutler** [comment]
I'm on a Mac with a crazy large and wide monitor.

**Comment by clockworkgr** [comment]
figures :)

**Comment by gibbsfromncis** [comment]
Redesign of TradingView #1484 was finished and tools now are displayed on any screen size.

**Comment by wmbutler** [comment]
Closing per @gibbsfromncis. Please re-open if disssatisfied.
