### ISSUE TITLE
Software quality control: longer staging period

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1560]
Now we have a staging environment, and the community is engaged to help on testing, in order to deliver product with better quality, I'd recommend that we have a longer staging period before every release, perhaps 2 weeks.

That said, we need a real `staging` branch which is relatively stable, and a `develop` branch or several branches for development that iterates fast.

Please discuss.

**Comment by abitmore** [comment]
@wmbutler 3 days? I don't think it's enough. Look at this issue, you haven't even replied within 3 days. Please be aware that you play a key role in the process.

**Comment by sschiessl-bcp** [comment]
I would very much welcome this! Develop branch is very useful.

To add to the comment:
Currently @svk31 does pull requests very short term before release date, thus the staging is only very shortly at the state of the next release. If the current workflow (staging -> master) should not be changed (i.e. it is decided to not have a develop branch), I would add suggest:
  
Let's say the release cycle is X weeks (currently 2). Pull requests are continuously merged into staging with one exception. When a release cycle ends, staging will be updated one last time with incoming fixes and then no pull requests will be done (other than hotfixes) for Y days (e.g. 7). The staging branch is deployed automatically onto staging.bitshares.org, where it will sit for Y days, after which a release will be done from the staging. After the release, all pending pull requests will be merged and normal routine continuous.

**Comment by happyconcepts** [comment]
I think big features deserve their own feature branches while under development.

Many OSS projects sensibly do this, and it let's staging branch remain as ... staging branch.

**Comment by clockworkgr** [comment]
I'm with @abitmore  on this one.

Switch to at least a master/develop/staging model.

There already is essentially a feature-list/feature-lock in effect for releases. Just use that as a guide as to what goes on staging. The only difference is that @svk31 does his fast iterations on develop branch instead.

I reckon we should just bite the bullet and delay one of the future releases for 2 weeks to make testing time available and then continue on the 2 week release cycle.

Essentially, 2 weeks worth of dev work with a feature lock of what goes into that release. 
At the end of those 2 weeks, this release goes to staging for another 2 weeks of testing. Devs can work on features of the next cycle as usual over those 2 weeks and potentially fix anything that comes up in testing.

Once the 2 weeks are over, staging is released and the new set of changes gets merged into staging for testing.

We just have to delay once to end up with a staging branch that is 1 "version" ahead of release and undergoes 2 weeks of testing each time.

**Comment by wmbutler** [comment]
Fine with me. We do 3 day testing periods on our codebase, but it's fine with me if we extend it to whatever you guys agree on.

**Comment by clockworkgr** [comment]
To be honest, the testing period needs depend on the change-log. It's obvious that TV integration (to pick a recent example) would require more testing than other changes.

Seeing as it's not practical to keep changing the length of the testing period, picking a longer one is probably best to allow for testing of "bigger" changes.

Also, considering timezones and that for most of us this is not our "main" occupation (thus more limited time-availability) 3 days feels way too short, unless there was more of us. 

Granted, availability of a public facing staging server would get us more involvement/testing by the rest of the community but we also need to allow for potential fixes to stuff that breaks. And to be fair, there has been the need for hotfixes in recent releases.

In all, better to be safe than sorry and go for a longer testing period which would not delay or change the release cycle (except for the one off time as described above)

**Comment by btsfav** [comment]
after today's OL breach there's no excuse any more for the desktop wallet. 

increase the quality, probably start a 4 week sprint with with 2 weeks of testing.

**Comment by sschiessl-bcp** [comment]
Bill is currently sick, but I expect that he follows up in here as soon as he can

**Comment by svk31** [comment]
I'm fine with moving to a develop/staging/master model and a 2 week testing cycle.

**Comment by svk31** [comment]
https://develop.bitshares.org/#/ now available

**Comment by clockworkgr** [comment]
Cool...speaking of which...how easy would it be for develop/staging URLs to have the commit id as the version on the bottom left (rather than the last release date)

**Comment by svk31** [comment]
Yea I actually already coded that, but it turns out Travis doesn't actually use the git branch but works from a detached state, so my code only works while developing and building locally...

I found an old issue concerning this and apparently there's no easy workaround, but I'll see if I can figure out something.

**Comment by bangzi1001** [comment]
Telegram: @harukaff_bot suggest that the "contributing" part of the readme should be updated.

**Comment by sschiessl-bcp** [comment]
https://steemit.com/bitshares/@sschiessl/bitshares-ui-release-180629-20180619t073242585z-post

**Comment by clockworkgr** [comment]
so this release is basically in testing (frozen in staging)  for the next 10 days ?

**Comment by sschiessl-bcp** [comment]
Yes exactly.

Testing was done on development build on local deployments, and now the same on staging public deployment.

This would be a good point to have a fixed test checklist that is required to be passed before actual release @bill_butler

**Comment by clockworkgr** [comment]
@btsfav
