### ISSUE TITLE
Unable to install Bitshares dex client for windows 7

### ISSUE THREAD

**Issue by ashisht24** [bitshares/bitshares-ui#1567]
I first signed up for bitshares acocunt on bitshares.org by clicking on online exchange. I then downloaded the windows 7 client by clicking the download button on there. Below link I used.

https://bitshares.org/download/

I chose the first one which is for windows and downloaded the .exe file.

Double clicked the .exe file and installed and received some BTS to the newly created account "archanat24"

before installing, i had python, node.js, visual c++ and the files for the GEKKO BOT was running GEKKO BOT already while I was logged in to BTS DEX and Cryptobridge DEX. All at the same time.

Suddenly, there was a power faliure and my laptop abruptly went off as it had no battery. Upon reboot, I did not find Cryptobridge DEX and Bitshares DEX. It was gone from my laptop. As if it was not installed. I use cloud wallet.

Then i installed Cryptobridge DEX it was working good. So next was I installed the Bitshares DEX using the same file I downloaded before. It wont install and gave me the error. The error screen grab is attached. It was over written on Cryptobridge DEX The icon of Cryptobridge dex changed to Bitshares DEX. and when I double click it i got the same error which is attached.

So now only one DEX is being installed. either one. soon as i install the other one i get this error. and vice a versa..

Then I thought of removing python, visual c++, and node.js and tried doing it. But its still the same error.

Its overwritting on the existing dex. for example if i have Cryptobridge installed and i try to install Bitshares DEX it would give this error or if I have Bitshares installed and try to install the Cryptobridge DEX, it would also give the same error.

Currently i have cryptobridge DEX client installed and running nicely with all assets safe and running Bitshare DEX on the website, the online version and both using the cloud wallet.

**Comment by ashisht24** [comment]
![bitshare install error](https://user-images.githubusercontent.com/38988375/40840861-0bb0ddfa-65c6-11e8-8a78-6664598fbf75.JPG)
Error Screenshot

**Comment by svk31** [comment]
The executable does not depend on any of the libraries you're mentioning. It's also impossible to debug something like this without a way to reproduce the issues. I suggest you download a new version of the executable and try reinstalling it, might help to uninstall it first?
