### ISSUE TITLE
React crash: Assets missing when connecting to Testnet

### ISSUE THREAD

**Issue by KristerV** [bitshares/bitshares-ui#1568]
**Describe the bug**

Connecting to testnet in the staging branch crashes the frontend with errors. Full output is on [Pastebin](https://pastebin.com/eeyGQHZH), here are the notable lines:

```
Warning: Failed prop type: Required prop `toAsset` was not specified in `TotalValue`.
Uncaught TypeError: Cannot read property 'get' of null
The above error occurred in the <TotalValue> component:
TypeError: Cannot read property 'get' of null at eval (MarketStatsCheck.jsx:131)
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

**To Reproduce**

1. `git checkout staging`
1. `npm i && npm start`
1. `go to localhost:8080`
1. Run command in console: `localStorage.clear()`
1. Enable the Europe Testnet server.
1. Navigate around to "Explore" or [General Settings](http://localhost:8080/settings/general)
1. Witness page going blank and multitude of errors in the console.
1. You may need to change the Preffered currency to BTC.

**Expected behavior**

Navigation should work.

**Screenshots**

**Desktop (please complete the following information):**

- Chromium Version 66.0.3359.181 (Official Build)
- Arch Linux (64-bit)

**Additional context**

While writing this issue and testing different situations the errors have changed to 

```
Warning: Failed prop type: Required prop `asset` was not specified in `AssetsResolver`.
```

So it's still revolving around assets.

**Git commit**

I'm currently on commit 99867a665aaa936c5d5f8a5273c2c6a70e596623
If I roll back commit by commit the problem seems to arise with

**Comment by KristerV** [comment]
Okay so I've been debugging the last error for two days now. I know that's long, but getting into this program from scratch is quite a hurdle :)

So anyway it appears that the `wss://node.testnet.bitshares.eu` server is not returning all of the required currency symbols. Specifically BTC.

**Steps to reproduce**

1. checkout the staging branch.
1. switch node to Testnet `wss://node.testnet.bitshares.eu`
1. go to `http://localhost:8080/settings/general` (maybe `localStorace.clear()` and hard refresh)
1. See errors in console about missing prop name "asset".

**To debug**

Insert this log line into `node_modules/bitsharesjs/es/chain/src/ChainStore.js` line 405

```
console.log("API RETURNED", id_or_symbol, asset_objects[0]);
```

So it looks like this:

![image](https://user-images.githubusercontent.com/2750622/40975006-2b556b9e-68d2-11e8-941f-60448b119296.png)

Then refresh the broken page. For conveniency here's the result:

```
RETURNED TEST {id: "1.3.0", symbol: "TEST", precision: 5, issuer: "1.2.3", options: {…}, …}
RETURNED USD {id: "1.3.15", symbol: "USD", precision: 4, issuer: "1.2.55", options: {…}, …}
RETURNED CNY {id: "1.3.174", symbol: "CNY", precision: 2, issuer: "1.2.17", options: {…}, …}
RETURNED BTC null
RETURNED EUR {id: "1.3.19", symbol: "EUR", precision: 4, issuer: "1.2.35", options: {…}, …}
RETURNED GBP {id: "1.3.46", symbol: "GBP", precision: 4, issuer: "1.2.157", options: {…}, …}
```

So BTC is null. Not just sometimes - always.

**How to fix?**

I did clone this repo initially to see if I can start completing bounties and this issue hasn't got one yet. Regardless I'd be happy to fix it if someone would guide me in the right direction.

There are multiple options.

1. Contact the server admin (who, where, how?)
2. Hide assets that don't have all of the required information so the frontend wouldn't crash.
3. Give a better error if the asset is not available in the console.

I suppose all 3 should be done (exept for maybe nr 3). But would still like some feedback before I put more hours in :)

**Relating the original issue of 'toAsset' missing in 'TotalValue'**

I haven't spent more time in confirming this, but it seems that both issues are originating from the same place. It's just a matter of which page you visit.

Also the page `http://localhost:8080/market/USD_BTS` now says in the console:

```
API RETURNED USD {id: "1.3.15", symbol: "USD", precision: 4, issuer: "1.2.55", options: {…}, …}
API RETURNED BTS null
warning.js:33 Warning: Failed prop type: Required prop `baseAsset` was not specified in `ExchangeSubscriber`.
```

So this is a bigger problem than just a single page.

**Comment by abitmore** [comment]
IMHO, please do:
* Hide assets that don't have all of the required information so the frontend wouldn't crash.
* Give a better error if the asset is not available in the console.

In regards to "Contact the server admin (who, where, how?)", please be aware this is a block chain, if some data doesn't exist on the block chain, it's not a server admin's fault. In your case, "BTC" doesn't not exist on the testnet. So the code should handle this. Testnet is just another chain, with different data, it's unable to entirely fix the data. BTW you can also try to run the UI against your own private testnet, in this case none of the assets listed would exist.

> http://localhost:8080/market/USD_BTS

I guess the asset "BTS" doesn't exist on testnet as well.

**Comment by KristerV** [comment]
Oky, on it!

While I work here's two more questions:

1. How do the devs currently work on the code since I'm assuming this bug doesn't only affect me?
2. This issue is not part of any milestone yet is probably bounty eligible otherwise - is it possible to attach a [1] or [2] to this? (probably a question for @wmbutler)

**Comment by svk31** [comment]
We don't use preferred currencies other than the default on the testnet since none of those assets actually exist on the testnet...

**Comment by KristerV** [comment]
whoah, sorry, why did you close this issue @svk31 ? I'm right in the middle of fixing it. `settings/general` crashes regardless of what currency you use or don't use. Did you try to confirm this at all?

**Comment by svk31** [comment]
Only closed it because I fixed it

**Comment by abitmore** [comment]
Actually, I think in local storage or elsewhere where user settings are stored locally, we should store certain data (e.g. favorite assets) under different keys for different chain_id. That said, save a set of data for mainnet, another set for testnet, when switching from or to to testnet node, reload all related settings. Is it done this way? Perhaps need to create another issue for this.

Temporarily reopening this issue.

**Comment by svk31** [comment]
Fixed here: https://github.com/bitshares/bitshares-ui/commit/adc8a8a80c003983c5868fda5d8c01008824c17d
