### ISSUE TITLE
Memo key set to Active key on new account creation.

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/bitshares-ui#1569]
Why is this done? 

It seems like it was done on purpose back in 2015 judging by commit history.

Shouldn't we make sure unique keys are being generated for memo authority as well.

My guess is compatibility with pre- separate memo key days. But it's been 3 years now.

**Comment by bangzi1001** [comment]
This is a huge security risk. Any bad guys can setup DAPP or Airdrop ask for memo key for verification. But they do not aware memo key is same as private key.

**Comment by abitmore** [comment]
Never give out any of your keys. Verification should be done via signatures.

**Comment by clockworkgr** [comment]
First of all, I totally agree with @abitmore . It's the way we verify LTM users in discord for example.

If you don't share PKs (which you shouldn't) it should not be a security risk by itself so let's not freak people out.

However, it's still incorrect behaviour and defeats the purpose of having a memo key in the first place and should probably be fixed (depending on the impact it has to existing behaviours)

**Comment by bangzi1001** [comment]
FYI: Some Top BTS Holders and Top BTS Proxies have same owner, active and memo key. I notified some of them and hopefully they know what to do.

**Comment by HarukaMa** [comment]
I think accounts with all the same keys comes from BTS1.0 conversion though. Without #101 it could be difficult for some people to change it securely.

**Comment by grctest** [comment]
Should this change have also been applied to the public faucet registered accounts? Or is it dead code? https://github.com/bitshares/bitshares-ui/issues/3749
