### ISSUE TITLE
[UI:3][JS:1] BSIP38: Allow user to specify target_collateral_ratio when updating margin positions

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#1575]
**Is your feature request related to a problem? Please describe.**
[BSIP38](https://github.com/bitshares/bsips/blob/master/bsip-0038.md) allows users to specify target collateral ratios for margin positions to prevent them from closing completely when being called.

If the ratio is set, the position will only buy enough borrowed assets to make the final ratio higher than the set one, and will not buy more even if there are large buy orders. (BSIP31 lets the positions dynamically reorder but a big buy order could still close the position with lowest ratio completely.)  If the ratio is not set, it will act as same as before.

Note: The BSIP also states that:
> if target_collateral_ratio option is set, UI need to show exact amount of collateral that another trader is able to buy and exact amount of debt that need to pay according to the equation described above. Note that this calculation will need to use the current feed_price.

I think it should be in a different issue though, so it's _not_ included here.

**Describe the solution you'd like**
The user should able to choose if he want to set the target ratio for the margin position, so maybe a checkbox for that, then a slider or textbox to input the desired value.

**Describe alternatives you've considered**
or the min value of the slider means "not set" and other positions represents target value.

**Additional context**
ref: #1493 - creating separate feature requests for new needed UI features.

**Comment by abitmore** [comment]
[ ] One important sub-task is serialization of `extension` struct.
[ ] the other is UX

@wmbutler 2 hours is too few IMHO.

**Comment by xiangxn** [comment]
I can complete the serialization, this modify should be in bitsharesjs.

**Comment by startailcoon** [comment]
@xiangxn how are your serialization work going?

We should try to aim to implement this to enable an easy change in the UI.

**Comment by xiangxn** [comment]
I think at least 3-4 hours, this problem should also have C++ support.

**Comment by startailcoon** [comment]
@xiangxn thanks for you reply. About the requirements in code I'll have to leave it to @svk31 to assess what the requirements are. Someone from the team will reply to this thread as soon as we have an answer.

**Comment by xiangxn** [comment]
I first submitted the changes to "bitsharesjs". This workload is only one hour. However, if you want to change the "operations", it will take at least 3 hours, because there are changes as long as the "ext" is used.

**Comment by xiangxn** [comment]
After analyzing the C++ code, in fact, this issue not needs to be serialize by the "extension" type, and the object can be assigned directly.

**Comment by startailcoon** [comment]
I can work on this for next milestone 180715, unless someone else wants to take this

**Comment by abitmore** [comment]
Serialization is needed for signing the transaction. @xiangxn your code pasted in this issue perhaps works for jsonification, but I believe it won't work for signing. Can you please provide a test case?

**Comment by pluswave** [comment]
https://github.com/bitshares/bitsharesjs/pull/25

**Comment by svk31** [comment]
The PR has been merged so this can be implemented now

**Comment by startailcoon** [comment]
## Proposed UI

This is a preview of my proposed UI
 
![bild](https://user-images.githubusercontent.com/12114550/43003221-06763c54-8c2c-11e8-935e-c78595b7f9b0.png)

**Comment by wwwang89** [comment]
hello，everyone，when I set TCR in “broadcast_transaction_with_callback” method，
my Operation data like bellow：
{
fee = {
asset_id = 1.3 .0;
amount = 0;
};
extensions = {
target_collateral_ratio = 1760;
};
funding_account = 1.2 .1097304;
delta_debt = {
asset_id = 1.3 .113;
amount = 0;
};
delta_collateral = {
asset_id = 1.3 .0;
amount = 1;
};
}

but error occurred，error:missing required active authority: Missing Active Authority ...
I think the signatures is wrong，because when I not set target_collateral_ratio，the data below
{
fee = {
asset_id = 1.3 .0;
amount = 0;
};
funding_account = 1.2 .1097304;
delta_debt = {
asset_id = 1.3 .113;
amount = 0;
};
delta_collateral = {
asset_id = 1.3 .0;
amount = 1;
};
}

It succeed ！

So I am confused how the property "target_collateral_ratio" signs on the line chain ？

anyone help ？

thanks ！！

**Comment by abitmore** [comment]
@wwwang89 are you using bitsharesjs? Or another client library? Perhaps I can help you to find where is the best place to ask.

**Comment by wwwang89** [comment]
> @wwwang89 are you using bitsharesjs? Or another client library? Perhaps I can help you to find where is the best place to ask.

I  used Java in Android client。Any help ？thanks！

**Comment by wwwang89** [comment]
oh ，It worked ，do as https://github.com/bitshares/bitsharesjs/pull/25#issuecomment-403963855
