### ISSUE TITLE
[6] BSIP38: Only show executable part of the called positions in the order book

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#1576]
**Is your feature request related to a problem? Please describe.**
[BSIP38](https://github.com/bitshares/bsips/blob/master/bsip-0038.md) allows users to specify target collateral ratios for margin positions to prevent them from closing completely when being called.

If the ratio is set, the position will only buy enough borrowed assets to make the final ratio higher than the set one, and will not buy more even if there are large buy orders. So the call order in the order book (aka the yellow order) should only show the portion of the order that is executable instead of showing the whole amount of the called position.

**Describe the solution you'd like**
BSIP suggests calculating the data using `feed_price`, so I think that for every called position, the UI should check if it has target ratio set, then calculate the executable part of it and only add that to the total amount in the order book.

**Additional context**
ref: #1493 - creating separate feature requests for new needed UI features.

**Comment by startailcoon** [comment]
This is more of a task than a feature, as it is a requirement that we do this to show the orderbook correctly.

**Comment by startailcoon** [comment]
I can work on this for next milestone 180715, unless someone else wants to take this

**Comment by startailcoon** [comment]
After my work yesterday on the modal I'm working on this next.

Right now I need to wait for a market to have enough settle orders to confirm the next approach of handling the visualisation of the order book.
