### ISSUE TITLE
[2] add function to import/export favorites

### ISSUE THREAD

**Issue by btswolf** [bitshares/bitshares-ui#158]
https://steemit.com/bitshares/@mirda/my-bitshares-problem-help-needed

Favorites are not stored in the wallet backup and get messed up after webwallet update.
An import/export function so save the favorites would be awesome.

**Comment by wmbutler** [comment]
Nice to have but not urgent

**Comment by wmbutler** [comment]
Backup user prefs to web wallet file.

**Comment by happyconcepts** [comment]
@wmbutler Can I claim this please? Let's make it awesome.

**Comment by wmbutler** [comment]
You've got it.

**Comment by happyconcepts** [comment]
@wmbutler I am sorry but I won't be able to work this issue after all.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
What does web wallet file mean? The local mode bin file?

can be just a csv or json file that keeps preferences. it would be more like a layout file.

I think this can be combined with friends/contacts suggestion: same file can store various layout preferences, favorite markets, contacts

cloud/local users on web wallet or downloaded wallet might want to use this as well or even switch layouts between many files.

**Comment by wmbutler** [comment]
I believe that Markets, and Starred favorites, hidden assets, and asset pair presentation order are stored in LocalStorage. Pretty sure it's json.

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares-ui/commit/f310ddd07128a3d54c4f79f05ba96f937920bf3f
