### ISSUE TITLE
[8] Upgrade to react-router v4

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#1584]
**Is your feature request related to a problem? Please describe.**
Hot reloading is partly broken after upgrading to webpack v4 and react v16. The reason is we're still using the old react-router v3 which has issues with reloading.

**Describe the solution you'd like**
Upgrade to react-router v4

**Comment by gibbsfromncis** [comment]
@svk31 I suppose it's huge task. I have project similar to this and so large like bitshares-ui and when I started to work on upgrading to react-router v4 it took so much time on the beginning and then I stoped and left router v3.  

I you want I can take / help you with this one. We can split responsibility of course if you need my help

**Comment by svk31** [comment]
Yea it's pretty big, and I've made a couple false starts, but I've made some good headway today so I should be able to handle it, but thanks anyway!

**Comment by happyconcepts** [comment]
![4](https://user-images.githubusercontent.com/14145836/41103531-357dd5aa-6a1e-11e8-982d-ea944317d45b.png)

**Comment by svk31** [comment]
Haven't seen any more issues so closing this now, already live on https://develop.bitshares.org
