### ISSUE TITLE
Moment.js attempts to load locale.fa

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#1585]
Anyone else getting this error?

>webpack:///./node_modules/moment/moment.js?:1862 Locale fa not found. Did you forget to load it?

moment.js is a 3rd party javascript library that was added recently as a dependency.

Why the error? Security issue?

* fa is the locale file for Farsi and I do not have any use at all for the Persian language at this time.
* The fa.js file does exist in my node_modules/moment/locale/

I tend to be distrustful of 3rd party javascript ...

**Comment by happyconcepts** [comment]
>console.log( navigator.userAgent)
VM1901:1 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.79 Safari/537.36

>**console.log(moment.version)
VM1907:1 Uncaught ReferenceError: moment is not defined
    at <anonymous>:1:13
(anonymous) @ VM1907:1**

>console.log(moment.version)
VM1909:1 Uncaught ReferenceError: moment is not defined
    at <anonymous>:1:13
(anonymous) @ VM1909:1

**Comment by svk31** [comment]
It's from datepicker for which we're using a fork made by a guy that included farsi. I've stripped all the unnecessary locale files using webpack though which is why we get this error.

**Comment by svk31** [comment]
Fixed here: https://github.com/bitshares/react-datepicker2/commit/9d4c2c28a23c970badcf765c35c5493d5a49afde
