### ISSUE TITLE
The UI often crash in win10 

### ISSUE THREAD

**Issue by ebit116** [bitshares/bitshares-ui#1592]
The UI often crash in win10 .
Previously,it shows loading when the node is high delay .
Now it is a piece of black screen  even if reload  many times.

**Comment by svk31** [comment]
Which part of the UI? The Exchange? Does your computer have low RAM?

**Comment by ebit116** [comment]
After I switch any button , my wallet will be black screen.Include the Exchange.My RAM is 8G .The previous version is normal.

**Comment by wmbutler** [comment]
Please post a licecap and include version of your current client.

**Comment by startailcoon** [comment]
No additional input for 1 month, closing issue.
