### ISSUE TITLE
[2] adding new gateway to ui

### ISSUE THREAD

**Issue by snakebitekit** [bitshares/bitshares-ui#1593]
Hi, I'm trying to add a new block trades-like gateway. But got stuck a bit.
I've checked your[ wiki page ](https://github.com/bitshares/bitshares-ui/wiki/Gateway-Integration-Requirements) and my backend setup is suitable for this, but i couldn't find suitable information how to prepare a frontend part for this.

What I've done so far for this: 
- edited apiConfig.js with suitable urls and ws server
- edited assets/locales files
- copy&pasted components/DepositWithdraw/project_name from components/DepositWithdraw/blocktrades folder 
- edited components/Account/AccountDepositWithdraw.jsx to add blocktrades-like methods
- created lib/common/ AddressCache&project_nameMethods
- added options to lib/common/gateways.js

i have two errors in route /deposit-withdraw by the way:
BridgeDepositRequest.jsx: inputCoinType&outputCoinType equals null and 502 POST on /trade/simple-api/initiate-trade (i think this two are connected)

what else I need to add/modify/check?
thanks.

**Comment by abitmore** [comment]
https://github.com/bitshares/bitshares-ui/wiki/Gateway-Integration-Requirements

**Comment by startailcoon** [comment]
I'm not sure why you're copy/paste anything on the wallet frontend. If the backend complies to the wiki you're linking to, the front end should only need to be updated in two files, `apiConfig.js` and `gateways.js`.

**Comment by snakebitekit** [comment]
@startailcoon hi. thanks for your reply

here's how i modified `apiConfig.js`:

```
export const citadelAPIs = {
    BASE: "https://citadel.li/trade",
    COINS_LIST: "/coins",
    ACTIVE_WALLETS: "/active-wallets",
    TRADING_PAIRS: "/trading-pairs",
    DEPOSIT_LIMIT: "/deposit-limits",
    ESTIMATE_OUTPUT: "/estimate-output-amount",
    ESTIMATE_INPUT: "/estimate-input-amount"
};
```
```
export const settingsAPIs = {
    ....
    {url: "wss://citadel.li/node", location: "Island"},
    ....
}
```
and `gateways.js`:
```
export const availableGateways = {
    ....
    CITADEL: {
        id: "CITADEL",
        name: "CITADEL",
        baseAPI: citadelAPIs,
        isEnabled: true,
        selected: false,
        options: {
            enabled: false,
            selected: false
        },
    }
    ....
}

```
and here's full api [documentation](https://citadel.li/apidocs/#/) (u need to choose gateway tab)
everything seems like on gateway wiki page

**Comment by snakebitekit** [comment]
@startailcoon ty, i'm waiting

**Comment by startailcoon** [comment]
I've taken some looks at the code now and there is an error in your API, other than that it seems to be just fine with a few small additions to the code. 

The `components/DepositWithdraw` and `components/Account/AccountDepositWithdraw.jsx` files are legacy code. With the new modal deposit/withdraw there is no longer any need to do all these modifications.

### Here is the change that you need to do you API
The second entry in your API call for /coins at https://citadel.li/trade/coins needs to change one value.

Change:
`walletSymbol: XMR` to `walletSymbol: MONERO`

This needs to be the same as the backing asset name + the backing exchange name.

### Here is what needs to be added to the code to enable the exchange

### gateways.js
```
import {
    rudexAPIs,
    widechainAPIs,
    openledgerAPIs,
    cryptoBridgeAPIs,
    citadelAPIs,
    gdex2APIs
} from "api/apiConfig";
```

```
export const availableGateways = {
    ...........
    CITADEL: {
        id: "CITADEL",
        name: "CITADEL",
        baseAPI: citadelAPIs,
        isEnabled: true,
        selected: false,
        options: {
            enabled: false,
            selected: false
        },
    }
}
```

#### To apiConfig.js
```
export const citadelAPIs = {
    BASE: "https://citadel.li/trade",
    COINS_LIST: "/coins",
    ACTIVE_WALLETS: "/active-wallets",
    TRADING_PAIRS: "/trading-pairs",
    DEPOSIT_LIMIT: "/deposit-limits",
    ESTIMATE_OUTPUT: "/estimate-output-amount",
    ESTIMATE_INPUT: "/estimate-input-amount"
};
```

That should be it. Please see if you can push the update to the API call and I can follow up after that to see if everything is as it should be.

**Comment by snakebitekit** [comment]
@startailcoon ty for your answer
i tried to apply this, fixed api, but got an error as well
when i try to make a deposit, i got an unknown address 
<img width="505" alt="screen shot 2018-06-25 at 01 26 05" src="https://user-images.githubusercontent.com/40239947/41824314-fe4076fe-7816-11e8-876e-f24ec98edbeb.png">

**Comment by startailcoon** [comment]
Hi @snakebitekit 

This issue is related to the fact that your `inputCoin` is set to XMR, and not Monero. The API requests a deposit address with the coin name, without the prepended exchange name.

![image](https://user-images.githubusercontent.com/12114550/41898352-17086e6c-792a-11e8-8007-af0fc341ed59.png)

Once this is fixed, you will be able to fetch an address from your API backend. You may have to clear your cache.

**Comment by snakebitekit** [comment]
@startailcoon thanks for help!
everything seems working
i will test it and make a pr soon
i think there's a bug by the way: 
deposit & withdraw modal shouldn't work if user isn't logged in and should show sign up/log in buttons, 'cos in not-logged in scenario we don't get `outupAddres` (account name)

**Comment by snakebitekit** [comment]
@startailcoon 
one more question, please
how is outputMemo generating in withdraw interface?
because i'm getting `'monero:addr....'` but `'xmr:addr...'` is needed, wanna debug this

**Comment by luka-magnotta** [comment]
@snakebitekit 
I believe you're looking for https://github.com/bitshares/bitshares-ui/blob/51734c9ec558486da08c0f95f36ef04be2a0e1a1/app/components/Dashboard/SimpleDepositWithdraw.jsx#L187

**Comment by startailcoon** [comment]
@snakebitekit @luka-magnotta that is not the place this is handled for the modal. I'll get back to you as soon as I can.

**Comment by snakebitekit** [comment]
@startailcoon ty for your help.
i've made a pr with our gateway integration: https://github.com/bitshares/bitshares-ui/pull/1695

**Comment by startailcoon** [comment]
Work on adding the Citadel Gateway is completed and submitted to PR #1695
