### ISSUE TITLE
UI 170118 - Market Depth Charts don't flip with market flip

### ISSUE THREAD

**Issue by brekyrself** [bitshares/bitshares-ui#16]
When you flip the market, the depth charts do not flip.  Once you flip the market you must click back to the price chart and then go back to the depth chart for it to update.

Price chart automatically flips when you flip the market as it should.

**Comment by svk31** [comment]
I'm unable to reproduce this, which market are you using? And browser?

**Comment by brekyrself** [comment]
The latest light wallet exe on Win10 x64.  BTS : open.STEEM.

**Comment by svk31** [comment]
Right you are, seems to only happen with UIA markets, not ones involving bit assets
