### ISSUE TITLE
[1.5][gibbsfromncis] Add Language selection by available locales 

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1600]
**Describe the bug**
Account creation indicates flags as languages

http://www.flagsarenotlanguages.com/blog/why-flags-do-not-represent-language/

**To Reproduce**
![image](https://user-images.githubusercontent.com/33128181/41465901-4d0adeb0-70a0-11e8-963f-0f75d052b208.png)

**Expected behavior**
Remove flag, show the state-of-the art language indicator and language as text instead of solely the flag. When the user clicks to open the language selector, show as values: "locale - language name"

![image](https://user-images.githubusercontent.com/33128181/41466016-ab9d9922-70a0-11e8-9a74-80ea8d3445b7.png)
(color is arbitrary)

**Additional context**
Flag is simply not appropriate for language. Additionally, in terms of regulatory aspects it might be misunderstood as choosing your country, scaring anonymity-loving people.

I would propose to keep the existing component and refactor it into a "Country Selector", even though it might not be needed right now by the reference wallet. Discarding the nice work on the flag is unnecessary. A "Language Selector" component should be created as its own component.

**Comment by sschiessl-bcp** [comment]
I wouldn't even go so far as to have it searchable.

We have not so many languages right now, get more sophisticated when needed.

**Comment by startailcoon** [comment]
Nice idea. I totally agree that we shouldn't rely on flags. The UI had a language list drop down before, but was replaced with this at one point.

Can we have a nice drop down list of available languages to start with that is populated by what locales we have?

Once we have a larger list, we could look for better ways of populating the list, but this would do for now.

**Comment by gibbsfromncis** [comment]
@startailcoon did you ask me or somebody else about dropdown list?

**Comment by sschiessl-bcp** [comment]
> I want to propose idea to use only components available in ANT and move straight forward with that.

+1

**Comment by startailcoon** [comment]
@sschiessl-bcp @gibbsfromncis I fully agree with you guys.

**Comment by gibbsfromncis** [comment]
Added Ant Select with autocomplete

<img width="505" alt="screenshot 2018-09-13 05 45 25" src="https://user-images.githubusercontent.com/35899973/45466047-3caf0000-b718-11e8-9fc3-c989c9d70091.png">

<img width="468" alt="screenshot 2018-09-13 05 45 29" src="https://user-images.githubusercontent.com/35899973/45466045-3c166980-b718-11e8-9248-39271087e92a.png">

**Comment by gibbsfromncis** [comment]
PR: #1855

**Comment by sschiessl-bcp** [comment]
Most users will be happy with default language. Having it look like a combobox is too prominent IMO.

I would suggest something like
![image](https://user-images.githubusercontent.com/33128181/45619488-bed15880-ba79-11e8-9cb9-0fde8ceec29b.png)

From top to bottom:
 - normal
 - onhover
 - onclick
The language selector icon could be omitted, but I personally like it to be showing up non-intrusive.

Please evaluate @startailcoon , since this is a significant change please add hours if accepted.

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I thought English is default language. Isn't? 

I can add icon and handle hover/click actions but what you're asking to make with dropdown is not provided by our Style-Guide. We can use [dropdown](https://ant.design/components/dropdown/#) for it but it hasn't autocomplete.

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp I thought English is default language. Isn't?

Exactly, that is way I think the language selector mustn't be so prominent

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp So lets replace it for dropdown?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I agree with @startailcoon. Please put your thoughts. I want to close this task before the end of this sprint

**Comment by sschiessl-bcp** [comment]
I guess we need to agree to disagree (which is fine, no UX expert here, just gut feeling).

Is this considered completed then?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I'll add `language` icon near select and it would be fine.

**Comment by gibbsfromncis** [comment]
<img width="467" alt="screenshot 2018-09-19 09 30 14" src="https://user-images.githubusercontent.com/35899973/45737627-a767ac00-bbee-11e8-86a6-f0dbe71ed7a7.png">
<img width="463" alt="screenshot 2018-09-19 09 30 28" src="https://user-images.githubusercontent.com/35899973/45737628-a8004280-bbee-11e8-89c7-f88c3721d1a7.png">
