### ISSUE TITLE
An old UI issue:The UI should list TXID

### ISSUE THREAD

**Issue by ebit116** [bitshares/bitshares-ui#1601]
The txid is useful for me to contact with exchange customer service.So I like to get the txid easyly in the bitsharesUI .
This is basic service ,I don't think it is need to search cryptofresh.com.
No resistance is our mission。
more detail:Within explore: Add support for searching TXID? #354
bitshares/bitshares-ui#354

**Comment by startailcoon** [comment]
I agree with OP that we should try to add more capabilities to the inbuilt explorer. 

Closing as we already have an open issue for this task.
