### ISSUE TITLE
[UX:20+UX:6][gibbsfromncis] Asset Creation & Edit Redesign

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1604]
**Is your feature request related to a problem? Please describe.**

I was working on Issue #1530 and tested issue creation. I've never seen and worked with this part before and a lot of things looks not clear or not user friendly. 

**Describe the solution you'd like**
1) It would be nice to make Issue asset as step by step (ant component for this: https://ant.design/components/steps/)

2) Provide some Info icon for each field and add popover (ant component for this: https://ant.design/components/popover/)

3) Low priority changes: update switches, errors displaying etc. 

4) Add informers for all needed areas like Flags and Permissions sections with clear description for each action.
**Describe alternatives you've considered**

5) Redesign sections content. I think we can organize steps and their settings better. Please post you ideas/thoughts if you have.

6) Highlight the difference of SmartCoin and UIA and give an explanatory text

7) Add "Are you sure you want to leave without saving" alert if user tries to leave the page without saving his changes.

8) Add "Burn Asset" tab with "Danger" button, description and warning that user won't be able to restore his asset, will lost Pool Balance etc.

<img width="1399" alt="3" src="https://user-images.githubusercontent.com/35899973/42011132-609eef24-7a92-11e8-92fc-2a4d4ab2f578.png">

<img width="1396" alt="4" src="https://user-images.githubusercontent.com/35899973/42011160-822452c4-7a92-11e8-9c61-bd11170969c5.png">

**Comment by gibbsfromncis** [comment]
@wmbutler @startailcoon please put your things here. What do you think about this. Is it a nice time to start to work on redesign or lets leave it for later

**Comment by gibbsfromncis** [comment]
Btw mentioned ant components wasn't included on style-guide. This part requires styling of these components if them require it (a lot of components was restyled by colors changing but some of them requires css overrides)

**Comment by gibbsfromncis** [comment]
@wmbutler I want to use steps only for Assets Creation. On Asset Manage/Update screens we will use simple tabs. Or you are talking about when user want to come back to previous steps when creating asset?

**Comment by gibbsfromncis** [comment]
@wmbutler Idea of using Steps is to help user prevent mistakes, miss something or do unnecessary action like scroll up and then click on the next tab. Also Steps for creation process more user-friendly. I hate when UX expect something from user like "scroll up and click on the next tab". We should limit user in his own decisions and show him what he should do next.

From technical perspective and especially in this case it wouldn't be duplicate of work if design code well.

**Comment by wmbutler** [comment]
If you want to use steps, I think I'd suggest a vertical steps rather than horizontal.

**Comment by startailcoon** [comment]
5 hours set for UX work on the design of Asset Creation and Edit sections.

**Comment by gibbsfromncis** [comment]
@startailcoon @clockworkgr 

Comments from Alex (designer) regarding his design:

I want to show three possible options for the improvements of the Assets creation form.

I worked on the appearance of UI using strictly the guideline from https://styleguide.bitshares.org/#/light

Also, using the ANT steps https://ant.design/components/steps, I created several versions of the interaction of a person with the process of creating Asset, namely, over UI (internal content of step # 1. Such steps as 2,3,4,5 have remained practically without changes in the UX area, except for the added question icons and tooltip for explaining)

![monosnap 2018-09-14 01-16-27](https://user-images.githubusercontent.com/35899973/45601630-7cbffc80-ba10-11e8-9575-39a9cf9e2e93.jpg)


The screens were made in 1366 * 768 resolution (the most popular resolution of monitors in the world), I used a grid of 12 columns with a width of 1170 pixels, so that the width could fit even on the smallest laptops. The height of the block is no more than 680pieces so that all information is placed on one screen, without scrolling)

These options are a concept for understanding what is happening, that would choose one of the options and develop it further.

Option 1 (gorizontal step form left): https://app.zeplin.io/project/5b9ad751d8068c34a1715ad6/dashboard?seid=5b9ade307e6f56241fe8883e
All information is located on the left under horizontal steps.

Option 2 (gorizontal step form center): https://app.zeplin.io/project/5b9ad751d8068c34a1715ad6/dashboard?seid=5b9ade60fab6df5b497fc9a9
This option was created in order to focus the user's attention on the center of the most important information. To ensure that his eyes do not scatter on the screen. The disadvantage of this option is that it is not compact and still takes up a lot of space and does not hold the user by the hand to the necessary items to fill.

Option 3 (form border center) https://app.zeplin.io/project/5b9ad751d8068c34a1715ad6/dashboard?seid=5b9ade975b559d4509079a75

After reading the last comment from wmbutler:
> If you want to use steps, I think I'd suggest a vertical steps rather than horizontal.
I tried to fulfill his request. And I think this version is more friendly, since it clearly says what to do to the user and shows what data and in what sequence it is necessary for him to fill out.

For example, the "Number of decimal points:" stapler can now display much more and is more convenient to use.

The "SmartCoin:" and "Binary prediction market:" switches 
![ux_ 5 1604 - _ - -ui github 2018-09-14 01-34-09](https://user-images.githubusercontent.com/35899973/45601636-9a8d6180-ba10-11e8-9bcd-a560ea68b82a.jpg)
now have a common, more compact zone that visually separates them from other elements and reduces the visual load.

The "Core exchange rate:" block is also visually lighter and separated from the previous one. The fields for entering symbols are reduced in width in order to raise to the right of them "PRICE: 1.006944 / TEST" 
![ux_ 5 1604 - _ - -ui github 2018-09-14 01-37-25](https://user-images.githubusercontent.com/35899973/45601640-aed15e80-ba10-11e8-916b-b74295ce90f6.jpg)

 and leave more attention to it because it is a living element that changes in real time. Raising it to the right and making it more contour and fat, now it will be a prose to notice and vision will be on the same level.

Block with a warning: 
![monosnap 2018-09-14 01-41-21](https://user-images.githubusercontent.com/35899973/45601642-c1e42e80-ba10-11e8-8f86-f38d3c9832ce.jpg)

 is too aggressive, it looks like the user made a mistake before something clicked. It's just a hint, it should be softer and friendly. So I decided to drop the word WARNING and red color. 
![ux_ 5 1604 - _ - -ui github 2018-09-14 01-40-36](https://user-images.githubusercontent.com/35899973/45601644-cb6d9680-ba10-11e8-9155-54332e1e755b.jpg)

by replacing it with the easier hint of 
![bitshares 2 0 180814 2018-09-14 01-43-53](https://user-images.githubusercontent.com/35899973/45601650-d6282b80-ba10-11e8-9824-ec3e5b9c0222.jpg)

Now it does not look like an error.

The form tells you what to do next and where to press it thanks to the contras and the brightest element in the composition is the blue NEXT button l. It's easy to understand where you are and what to do next 
![bitshares 2 0 180814 2018-09-14 01-46-58](https://user-images.githubusercontent.com/35899973/45601653-e6400b00-ba10-11e8-887d-a40538dd3a5c.jpg)

**Comment by gibbsfromncis** [comment]
Things left to do:
- [ ] Move Market Fee from Flags section to Primary Settings
- [ ] Edit screen example
- [ ] Decide something about Fields Validation (Error displaying)
- [ ] Put "Quote Asset Amount (n/a)" on the first screen with vertical steps some where. It's not good to see it in the left side of button

@startailcoon @clockworkgr would be glad to hear your comments :)

**Comment by wmbutler** [comment]
I like where this is going. A couple of questions. 

1. If the user returns to this screen after asset creation, will they continue to use this step system or will we have to build another way to modify existing settings?
1. As I recall, either the Permission or Flags had some non-reversible action that may require extra warnings. @xeroc or @abitmore I may need you to chime in here to confirm or deny that potential issue. Further, I'd almost prefer to leave out anything in the UI that can permanently remove a feature from an asset. I have noticed that this is a very confusing issue for new asset issuers.

**Comment by wmbutler** [comment]
@gibbsfromncis I think that Alex has some talent. Does he have any interest in working on UI for 15-20 hours per week?

**Comment by gibbsfromncis** [comment]
@wmbutler This is how tabs looks like on Edit mode. He did it 6 days ago but I didn't have a time to post it:

(Vertical tabs on the left)
<img width="726" alt="screenshot 2018-09-25 11 11 26" src="https://user-images.githubusercontent.com/35899973/46004727-db8e1180-c0b3-11e8-95b3-a6b4e644ebd3.png">

(Horizontal tabs)
<img width="1019" alt="screenshot 2018-09-25 11 11 15" src="https://user-images.githubusercontent.com/35899973/46004728-dc26a800-c0b3-11e8-89b7-09d14df1f397.png">

**Comment by gibbsfromncis** [comment]
@wmbutler it's permissions tab and it already has some text of warning: 
<img width="963" alt="screenshot 2018-09-25 11 56 24" src="https://user-images.githubusercontent.com/35899973/46007351-227f0580-c0ba-11e8-8054-e54bac635070.png">

But I suppose we can use the styles of warning like on Primary Settings to make sure user will pay attention to the text:

<img width="461" alt="screenshot 2018-09-25 11 57 23" src="https://user-images.githubusercontent.com/35899973/46007368-2f035e00-c0ba-11e8-9570-8d54a1fec4ff.png">

**Comment by wmbutler** [comment]
Need more clarification on the UX for editing. For example, if the user changes a value, what prompts the user to continue to the final step to save the changes?

**Comment by startailcoon** [comment]
Increased hours for UX based on new input that needs to be worked on.

**Comment by nikandrovalex** [comment]
Hi guys @startailcoon  @wmbutler . 

I am pleased to continue working on the project😊
I came back from vacation and I can give the project more than 20 hours a week.

I updated the layouts to zeplin https://zpl.io/2vWwwve

You can also see them here: https://sketch.cloud/s/Q1AgL/p/1604-asset-creation-edit-redesign 

I finished what I described above with gibbsfromncis:

> Things left to do:
> 
> * [x]  Move Market Fee from Flags section to Primary Settings
> * [x]  Edit screen example
> * [x]  Decide something about Fields Validation (Error displaying)
> * [x]  Put "Quote Asset Amount (n/a)" on the first screen with vertical steps some where. It's not good to see it in the left side of button

What are your thoughts on this?

**Comment by gibbsfromncis** [comment]
@nikandrovalex please think about Edit mode. When user will do Edit:

- [ ] How user can save update? I do not see any buttons or something like that
- [ ] It would be nice to have some kind of marks on tabs to let user know he changed some content

**Comment by nikandrovalex** [comment]
@gibbsfromncis  

1. Do not you see these buttons? http://take.ms/OlCmXA  :)
2. Usually after similar actions it is customary to display notifications of this type http://take.ms/CQcaJ 
https://ant.design/components/notification/#header

**Comment by abitmore** [comment]
To make the UX better, we do need to understand the product first.
* valid precision range in back end is 0-12
* The **warning about CER** was there for a reason, it **was very important**. However, after 2018-07-19, fee pools are no long drain-able due to BSIP26, so it's not very important now. It's still good for asset owner/issuer to set CER (core exchange rate) properly. Need to explain what's fee pool and what's CER anyway.
* I think flipping the "disable confidential transaction" flag and "disable force settling" to "enable confidential transaction" and "enable force settling" would be better UX. Anyway code/logic should follow bitshares-core.
* for less confusion, better group the 2 "allow xxx to provide price feeds" to one "feed producers" option (drop-down or radio selection): feed-by-witnesses / feed-by-committee-members / feed-by-issuer-chosen-accounts
* for less confusion, better group "smartcoin" and "binary prediction market" to one "asset type" option (drop-down or ratio): simple(UIA) / smartcoin(MPA) / BinaryPredictionMarket(PM)

**Comment by abitmore** [comment]
* "market fee (%)" value has fixed 2 decimals, and can't go beyond 100%, UI/UX can reflect it
* "max market fee" need an explanation, I think many people understood it incorrectly. The fact is: the cap/limit is for each "fill" but not each "order".  For example, if you place an order to buy 10000 ASSETX which has a 1% market fee and max fee is 10, you may assume you'll get 9990; however, if another user sells to your order with 1000 ASSETX each time and totally 10 times, you'll pay 100 ASSETX as fee and finally get 9900. I'd say it's not a very well-designed feature in the back end, but it is there before we change it.
* IMHO the UX for setting "core exchange rate" was not good enough: two input boxes with labels "base amount" and "quote amount" which are hard to understand for average user.
* I'm not sure what the "Quote Asset Amount (n/a)" in the bottom is for, perhaps it can be removed?

**Comment by abitmore** [comment]
* about permissions:
  * actually enabling a permission means the asset issuer/owner **is able to change** the corresponding flag, disabling a permission doesn't mean the corresponding flag will be disabled. Thus, permission page and flag page should have some differences in wording.
  * when an asset has zero supply, permissions can be re-enabled.
  * please make sure that "global settling" is in permissions only, but not in flags.

**Comment by wmbutler** [comment]
> actually enabling a permission means the asset issuer/owner is able to change the corresponding flag, disabling a permission doesn't mean the corresponding flag will be disabled. Thus, permission page and flag page should have some differences in wording (and probably can't apply the grouping I mentioned for flags).

Should we not even show this as an option for the frontend since this operation permanently disables the feature? Seems to me we could just expect more advanced users to use the CLI to permanently disable these features. It may be my lack of understanding here, but I always hate giving potentially novice users access irreversible features.

**Comment by startailcoon** [comment]
Summary of what I think we need to change based on input.
Should apply to both create and edit.

### Primary Settings Tab
- Change to 2 decimal points on asset
- Replace "SmartCoin" and "Binary" toggles with a drop-down where the default is "User Issued Asset" followed by "Smart Coin" and "Binary Prediction Market". Only one can be chosen.
- Market Fee % can't be negative or over 100%, should have space enough to show error message
- Rename "Max market fee" to "Max fill order fee" and add a hower information box adding more details about the fill-fee. Could potentially be a information box with more details, not sure what it would be exactly. 

Something like this perhaps. We need to get this right.
> Enabling Market Fees would allow the asset issuer to withdraw fees based on a percentage on trade. 
> Max market fee would be the maximum amount per fill order in the order book

- We should probably add some text to inform the user what "Quote" and "Base" assets are. I propose the following 

>

- Remove the unused `Quote asset amount: N/A`
- Add more information on what a 'Fee Pool' and 'CER' is on notification. I propose we change the notification to the following, where bold are links to in client help topics: 

>Make sure your core exchange rate is higher than the market price, as it has an impact on the fee pool. 
> Read more about **fee pool** and **CER**.
>
> The core exchange rate should be updated regular to reflect market pricing of your asset

### Description Tab
- Preferred market pairing asset name should be a drop-down searchable input, filtered on allowed assets.
- I would find it more natural to have the "Short Name" of the asset before you pick the preferred market pair asset. Maybe we should flip these?

### SmartCoin Options
- Short backing asset should be a drop-down with allowed assets to use.

### Permissions
The "Permissions" tab needs a better name. I think `Flag Permissions` is a better nam. This tab is the master settings, and will enable the issuer to later toggle the "permitted" flags in the next step. Enabling someting here, doesn't mean it's activated, that needs to be done in the flags settings. Once a permission is removed, it can no longer be allowed again, unless the asset has zero supply.

I propose we change "enable" to "allow", as it's not a toggle to activate it, just to allow the flag to be activated. Thus we should have the following wordings

`Enabled market fee` = `Allow market fee`
`Require holders to be white-listed` = `Allow holders to be required in white-list`
`Issuer may transfer asset back to himself` = `Allow transfer of asset back to issuer`
`Issuer must approve all transfers` = `Allow issuer transaction approval`
`Disable force settling` = `Allow force settling`
`Allow issuer to force a global setting` = `Allow force global setting`
`Disable confidential transactions` = `Allow confidential transactions`
`Allow witnesses to provide feeds` = Same
`Allow commitee members to provide feeds` = Same

### Flags
These flags are toggles based on change permissions on the tab before.

- Remove "Allow issuer to force a global settling".
- Repalce the wording from "disable" to "enable". The UI should take care of the difference in flag permissions accordingly.
- Replace "Allow witnesses to provice feeds" and "Allow committee members to provice feeds" to a drop-down list with the title "Allowed feed providers" with the followin options: (**NOTE:** I can't find this in the documentation)
`Witnesses`, `Committee members`, `Defined accounts`. 



# Edit
When you edit an asset I think we should highlight that the tab has been changed and has unsaved changes. 

Today we have the following

- Tab should have an asterisc when it's changed
- Save button should be enabled

If possible, we could add something to make sure the user doesn't navigate away from the edit asset unexpectedly, by pressing the wrong thing in the app for example.

- Popup should appear when it's not saved and you're navigating away from the page

**Comment by startailcoon** [comment]
Create / Edit asset should also contain a tab for managing feed producers, if it's set to `Defined Accounts`.

This is how it looks today, but can be much prettier.

![bild](https://user-images.githubusercontent.com/12114550/46625791-94813100-cb35-11e8-9adf-fe0b9f939114.png)

**Comment by startailcoon** [comment]
> 
> 
> > actually enabling a permission means the asset issuer/owner is able to change the corresponding flag, disabling a permission doesn't mean the corresponding flag will be disabled. Thus, permission page and flag page should have some differences in wording (and probably can't apply the grouping I mentioned for flags).
> 
> Should we not even show this as an option for the frontend since this operation permanently disables the feature? Seems to me we could just expect more advanced users to use the CLI to permanently disable these features. It may be my lack of understanding here, but I always hate giving potentially novice users access irreversible features.

I don't see the need to hide features for the UI users, even if they are more advanced. As long as we notify what the feature does and what the expected outcome is, I don't think it should be a requirement. Enabling/Disabling flag permissions is a way of telling users of an asset what they can expect to change later on, if the issuer decides to activate a flag it has permissions to. 

This is why this should be more visible in the UI, and perhaps on the asset details page as part of https://github.com/bitshares/bitshares-ui/issues/1119

**Comment by wmbutler** [comment]
@startailcoon nice summary. I added checboxes to help the developer tick off as completed. My only other thought is that is seems odd to have a step title smart asset when that's an optional toggle. Am I right that if the "smart asset" toggle is false, the entire smart asset step will be disabled? Just seems like we can do better here, but I don't have a great idea.

**Comment by gibbsfromncis** [comment]
@startailcoon we had call with Alex regarding this task. I would like to ask you to increase estimate by 10 hours (to `UX:20+UX:6`) to finish this task.
Alex already spent around 23 and need additional 6 hours so I think increase his estimate by 10 hours would be fair.

**Comment by wmbutler** [comment]
@nikandrovalex Licecap is great for creating inline animated gifs right here. It's lighter weight than an mp3.

Also, this is the classic UI problem with Bitshares. When you submit your changes to the blockchain it costs BTS, a very small amount but it costs nonetheless. As such, when you switch to another tab in this context, the user probably doesn't want to save the changes. Rather, they want ot make adjustments to several of the tabs and then make a single submission for all the changes made on every tab. This is the problem we are trying to address. The user needs to realize that they have made changes but they have not yet saved them as they migrate from tab to tab.

**Comment by gibbsfromncis** [comment]
@startailcoon I sent some ideas to Alex and waiting for his answer. I'll work on Assets Redesign but lets create separate issue for UI implementation if you OK with that. I would be happy to receive bounty in this sprint.

**Comment by wmbutler** [comment]
I think an * on the tab isn't enough. Let's see what he comes back with.

**Comment by nikandrovalex** [comment]
Hi guys. @wmbutler @startailcoon I had a call with @gibbsfromncis  and he shared some ideas. based on them, I made this option: https://invis.io/H4OUO3053VZ 

What do you say if we make such a notification on the left when changing tabs?

**Comment by nikandrovalex** [comment]
For the click lazy 😊
<img width="1182" alt="2018-10-31 11 11 28" src="https://user-images.githubusercontent.com/43581164/47777635-d39e3e80-dcfd-11e8-9cb9-a3d27fbb6bb2.png">

**Comment by gibbsfromncis** [comment]
@startailcoon please make a review of this design

**Comment by wmbutler** [comment]
I really like this!

**Comment by startailcoon** [comment]
Can't say other than that I really love the outcome. The side panel for saving changes is a really nice solution.

**Comment by startailcoon** [comment]
This is ready for implementation, assigned issue #2117
Closing this UX task for payment.

Great work again guys @gibbsfromncis and @nikandrovalex !

**Comment by gibbsfromncis** [comment]
Combined hours for UX

**Comment by nikandrovalex** [comment]
@startailcoon Thank you very much😊. I'm glad to help. And I am ready for new tasks) I am free now and I can spend more time on these projects.

Also, thanks to everyone who helped me deal with this task.

**Comment by gibbsfromncis** [comment]
@wmbutler Notice: Issue title is correct. All hours for this task should be delivered to me because of our specific agreement with Alex.
