### ISSUE TITLE
[0.5] Bitshares StyleGuide & React Hot Reload conflicts

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1609]
When I started to work on some feature I got this error on my console for each component I use from style-guide (ant components) (2 Buttons & 1 Modal):

<img width="1403" alt="screenshot 2018-06-19 22 49 25" src="https://user-images.githubusercontent.com/35899973/41623442-15f4369e-7413-11e8-9778-7fd3d01a8c23.png">

I didn't see this issue when added `bitshares-style-guide` to our `package.json` and tested it (I've used some components to check styles apply correct and it works fine). 

@svk31 I suppose React Router v4 may affected for it (everything was fine before our migration to new Router). Maybe you changed some other parts which may affect on this? I will try to find possible fix but I really hope for your help.

**Comment by svk31** [comment]
Hm, how do I reproduce it?

**Comment by gibbsfromncis** [comment]
@svk31 Just import any component from `bitshares-ui-style-guide` like:
`import {Button} from "bitshares-ui-style-guide"` and use this Button anywhere.

**Comment by svk31** [comment]
Updating react hot reload seems to have done the trick; although I also updated antd in bitshares-ui-style-guide.
