### ISSUE TITLE
[1] 'Create account' doesn't jump user to form

### ISSUE THREAD

**Issue by ahdigital** [bitshares/bitshares-ui#1610]
### Describe the UX issue

These are mostly UX issues with mobile:

**Part A)** As a user I want to create an account, but when I click the 'create account' button from the landing page I don't notice the form because it loads in close to/below the viewport bottom whilst the UI.

**Part B)** As a user I want to create an account, but when I click the 'create account' link from the burger menu I don't see the form because the landing page appears above it, and at a glance it looks like I need to press 'create account' again.

The account creation pages used to load in separate-looking views, but now they're combined with the landing page/language selection view and thus, pushed way down the page on mobile.

### To Reproduce
Steps to reproduce the behavior for **part A**:
1. Go to Bitshares landing page with the language selection
2. Click on 'Create account' or 'advanced form'
3. User can barely notice a form loaded in

Steps to reproduce the behavior for **part B**:
1. Go to any other page and click the burger menu
2. Click on 'Create account'
3. User see landing page and thinks another tap is required on 'create account' button

### Expected behavior
If the forms are going to be displayed beneath the landing page UI, the user should be scrolled down to view them when they're requested.

### Screenshots
**Part A)**
![create-account-1](https://user-images.githubusercontent.com/3088454/41641627-c742fd28-745d-11e8-993c-8d29b5818c20.gif)

**Part B)**
![create-account-2](https://user-images.githubusercontent.com/3088454/41641641-d6b6eba2-745d-11e8-842b-2c85ab4315b8.gif)

**Smartphone**
 - Device: S8
 - OS: Android
 - Browser: Chrome
 - Version: 67

**Simulated**
 - Resolution: iPhone 6/7/8
 - Browser: Chrome
 - Version: 67

**Comment by startailcoon** [comment]
Using an anchor and the new react-scroll library, this would be an easy task to complete.

**Comment by startailcoon** [comment]
@sschiessl-bcp I forgot to remove the "staging" name from the user issue. This is of course not something that would be fixed to the staging branch. I belelive this is something that has always been there, and is thus labeled as a feature.

Only bugs should be pushed to staging.

**Comment by ahdigital** [comment]
> Was this a newly introduced bug or is this already like that in the current release?

> I believe this is something that has always been there

In my original post I mentioned the on boarding pages used to load as separate pages. Check the current live release against staging and you can see they are different.

**Comment by wmbutler** [comment]
Somebody want to claim this?

**Comment by startailcoon** [comment]
![bitshares-scrolloncreate](https://user-images.githubusercontent.com/12114550/42184356-8ac87606-7e45-11e8-9b3e-d87da7154d88.gif)
