### ISSUE TITLE
[0.25] STAGING - Withdraw (beta) modal is blank

### ISSUE THREAD

**Issue by ahdigital** [bitshares/bitshares-ui#1611]
### Describe the bug
**Part A)** The withdraw (beta) modal is blank on desktop.

~~**Part B)** On mobile, the withdraw (beta) modal displays a white screen after an asset is selected.~~

### To Reproduce
Steps to reproduce **Part A)**:
1. Open burger menu
2. Click on 'Withdraw (beta)'

~~Steps to reproduce **Part B)**:~~
~~1. Open burger menu~~
~~2. Tap on 'Withdraw (beta)'~~
~~3. Choose any asset~~
~~4. See whitescreen~~

### Screenshots
![withdraw-beta](https://user-images.githubusercontent.com/3088454/41643994-bf694650-7464-11e8-9bac-f6f52ec05c8c.gif)

**Desktop**
 - OS: Windows
 - Browser: Chrome
 - Version 67

**Smartphone**
 - Device: S8
 - OS: Android
 - Browser: Chrome
 - Version: 67

### Additional context
No console errors appear when I do this on desktop.
Mobile started working now after 5 attempts - maybe this only happens when the account shown in the top right has a lot of assets?

**Comment by svk31** [comment]
You don't have any accounts to withdraw from that's why, the withdraw option should just be hidden in that case.
