### ISSUE TITLE
Branding template

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1613]
This feature aims to facilitate branding/customizing the reference wallet, e.g. for a white-label customized exchange. It's intent is to have a single point of entry that controls key branding aspects. The most simple customization job will then only require to edit this one single file.

Reasons are:
a) It facilitates the work of anyone that wants to create their own exchange or simply have a slicker interface with less assets shown etc.
b) It gives incentive to existing exchanges to keep their wallets up-to-date and maybe even get them to upstream as well by realizing the synergies
c) Up-to-date wallets are better for security, and it doesn't matter which BitShares powered exchange gets hacked, it is still bad publicity

A pull request will follow.

**Comment by grctest** [comment]
Would custom themes be in scope of this? Or solely a method of easily replacing the branding throughout the web wallet?

**Comment by sschiessl-bcp** [comment]
After migration to the new [bitshares styleguide](https://styleguide.bitshares.org) is done it should be easily doable (right now possibly too, but waste of effort).

With the new styleguide it **should** boil down to copying one of the existing themes and adjusting it, 
 [find the new dark theme here](https://github.com/bitshares/bitshares-ui-style-guide/blob/master/app/bitshares-ui-style-guide/dark.less). I can add a call to allow for a custom theme file in branding.js, then custom theming should be very easy, shouldn't it @gibbsfromncis ?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp right. For now style-guide contains styles only for UI components we are going to use on bitshares-ui. Later I want to integrate it more close to bitshares-ui themes or even create separate repo with themes for bitshares-ui and bitshares-ui-style-guide where all info about theme will be placed in one json file.

**Comment by wmbutler** [comment]
Please post your expected hours for this.

**Comment by sschiessl-bcp** [comment]
No expected hours since this facilitates my commercial use of the wallet
