### ISSUE TITLE
[3] Include Collapses component in the UI style guide

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1614]
For the new Exchange design we require the collapsed component from AntD.

The bitshares-UI-style-guide is started and as we progress we will require more components to be included, as all aren't yet.

As the style guide is still early in development, @gibbsfromncis will make sure this is included and will handle workload between UX and UI integration.

**Comment by gibbsfromncis** [comment]
Front-end part was blocked by the following issue: https://github.com/bitshares/bitshares-ui/issues/1621

UX ready:
![dark theme_collapse](https://user-images.githubusercontent.com/35899973/41882060-0c2d7fe8-78e7-11e8-8677-73bcfbd99500.png)
![light theme_collapse](https://user-images.githubusercontent.com/35899973/41882061-0c4925c2-78e7-11e8-8eaf-301228dc86d6.png)
![midnight theme_collapse](https://user-images.githubusercontent.com/35899973/41882062-0c630a14-78e7-11e8-8910-fee35de7b598.png)

**Comment by gibbsfromncis** [comment]
@startailcoon Added support of Collapses for UI & redesigned - https://styleguide.bitshares.org/

I'll close this task. If something wrong feel free to reopen
