### ISSUE TITLE
STAGING - Put market order breaks UI

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1615]
**Describe the bug**
After putting an order the UI crashes and recovers by reconnecting / blank white screen. The gets put properly, but UX is broken

**To Reproduce**
Place any order on any market

**Expected behavior**
Should work and remain on exchange tab

**Screenshots**
![image](https://user-images.githubusercontent.com/33128181/41758972-20062202-75ec-11e8-8161-58de2077212b.png)

**Comment by startailcoon** [comment]
This issue is fixed with PR https://github.com/bitshares/bitshares-ui/pull/1608

**Comment by shulthz** [comment]
can't creat a new worker!!!

**Comment by sschiessl-bcp** [comment]
Can you be more precise please? The issue talks about market orders, you talk about worker proposals?

**Comment by shulthz** [comment]
OK, SORRY

**Comment by sschiessl-bcp** [comment]
What is it.that is not working?

**Comment by shulthz** [comment]
![1](https://user-images.githubusercontent.com/34892308/42134114-7927d11e-7d67-11e8-870b-f70f292af0b2.png)

**Comment by sschiessl-bcp** [comment]
How did you get to that screen?

**Comment by shulthz** [comment]
When i click the ”creat a new worker“ in the voting，then turned to this page.

**Comment by svk31** [comment]
Probably a missing route, it needs a new issue though since it's completely unrelated to this one.
