### ISSUE TITLE
[2][gibbsfromncis] Bitshares Style Guide less issue

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1621]
For now themes support for ant components works on this way:
```
body.darkTheme {
  @import "~antd/lib/style/components";
}
```

But it doesn't work well for the following case of less code:
```
.ant-collapse {
  background: blue;
  & > &-item {
    background: red;
  }
}
```

The compiled output looks like:
```
body.dark .ant-collapse {
  background: blue;
}
body.dark .ant-collapse > body.dark .ant-collapse-item {
  background: red;
}
```

I do not see any easy solution how to fix it on our side without touching ant sources. 

This fix requires some time and investigation

**Comment by gibbsfromncis** [comment]
@startailcoon It was not so easy to fix it but I'm done. 

###What is the issue 
As described above, some styles of ant were broken because of LESS specifics. Unfortunately there is no way for now to avoid mentioned behavior of LESS compiler. There are issues regarding this: https://github.com/less/less.js/issues/3232 (Thats mine, I'm still waiting for feedback from LESS contributors)
https://github.com/less/less.js/issues/3045 

First of all I decided to using regexps just remove not necessary usages of themes selector `body.nameTheme` but it wasn't stable and doesn't covered cases like [this](http://lesscss.org/features/#parent-selectors-feature-changing-selector-order). 

Then released [my own LESS-plugin](https://github.com/gibbsfromncis/less-plugin-precompile-import) to handle our case but in result I discovered that `less-loader` for `webpack` doesn't support this kind of plugins which extends default `FileManager`. When I investigate `less-loader` issues I get deeper to `webpack` sources and how it works inside and stopped and start to find more dirty but working solution and the only one I found is to compile themes by command-line-tools to get compiled themes and than wrap them into "body.nameTheme". 

I changed structure of bitshares-ui-style-guide ([commit](https://github.com/bitshares/bitshares-ui-style-guide/commit/f42893973853a6bc2d6f5b2c2fdbd7e632474e8d)) and added inline watchers & compilers for LESS themes (dark, light and midnight). 

In result solution is pretty easy and it works. It's not awesome but I have no idea how to solve it's better.

It was spent around 3 full-time days to fix it. I want to request *7.5h* for this to partially compensate me these 3 days. 

If you don't agree please put fair estimate by your opinion or leave it as it. Feel free to ask any questions/place any thoughts

**Comment by startailcoon** [comment]
I'm okay with increased hours, it's an issue that wasn't possible to forsee and that was found now.

@wmbutler you have final say in this I'd think.
