### ISSUE TITLE
[0.5] Typing amount on Deposit/Withdraw results in blank page

### ISSUE THREAD

**Issue by compumatrix** [bitshares/bitshares-ui#1628]
**About the bug**
This just recently occurred while typing on any of the amount fields on Deposit/Withdraw on Blocktrades. Just one keystroke turns the entire page blank.
![capture](https://user-images.githubusercontent.com/2491389/42010059-84c44e26-7abf-11e8-9f25-8a9506c01e9e.JPG)

**Comment by startailcoon** [comment]
@compumatrix can you please specify where exactly you have this issue, and what version of the application you are running?

By the looks of your comment I assume it's on `/deposit-withdraw` your having an issue when selecting Blocktrades as a bridge?

![bild](https://user-images.githubusercontent.com/12114550/42028503-baa87ce4-7acc-11e8-82d1-8d3245deb244.png)

**Comment by compumatrix** [comment]
It is on Bitshares Version: 180526 On Blocktrades Gateway. I wanted to send the exact amount of bitcoins. But it goes blank the minute I type.

![gif](https://user-images.githubusercontent.com/2491389/42032749-3453ef5c-7b0d-11e8-9d28-0101a05d069a.gif)

**Comment by startailcoon** [comment]
After some searching I've found that the code misses some checks, and throws the page in error whenever you type in an amount manually on withdraw.

This has been fixed
