### ISSUE TITLE
[2] Assets Redesign

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1629]
**Main Requirements**
1. Cross-devices support (for smartphones, tablets, laptops)

**Assets Home page**
1. Replace old tabs for tabs from style-guide
2. Hide table is user has no any assets on his list:
2.1 Add description for assets like what is Assets and how user can use them
2.2 Center description and "Create asset" button
3. Remove "Burn Asset" from Assets section because this is action which is related only for own asset.
4. Reorganize table columns. For e.g. remove description because it's not important information to see by Issue Creator and display move important information like Pool Balance
5. Add new "View" button which redirects to Asset Info page like https://wallet.bitshares.org/#/asset/ABITS.CNY

<img width="1399" alt="1" src="https://user-images.githubusercontent.com/35899973/42010703-3e24ca06-7a90-11e8-9d85-a41f23f4bbc1.png">
<img width="1398" alt="5" src="https://user-images.githubusercontent.com/35899973/42011384-80f56ef0-7a93-11e8-8051-aa5ee1845aeb.png">

**Asset Creation**
1. Replace tabs for [Steps component](https://ant.design/components/steps/) 
2. Redesign forms at all using new style-guide and [Forms components](https://ant.design/components/form/) with clear UX, error reportings etc.
3. Replace old components (Slider, Switch) for new which we have already in our style-guide
<img width="1398" alt="2" src="https://user-images.githubusercontent.com/35899973/42010954-6cb6bba8-7a91-11e8-896e-3643e082b103.png">
4. Add informers for all needed areas like Flags and Permissions sections with clear description for each action.
<img width="1399" alt="3" src="https://user-images.githubusercontent.com/35899973/42011132-609eef24-7a92-11e8-92fc-2a4d4ab2f578.png">
<img width="1396" alt="4" src="https://user-images.githubusercontent.com/35899973/42011160-822452c4-7a92-11e8-9c61-bd11170969c5.png">
5. (**BTD**) Redesign sections content. I think we can organize steps and their settings better. Please post you ideas/thoughts if you have.

6. Highlight the difference of SmartCoin and UIA and give an explanatory text 

**Asset Update**
1. (**BTD**) Remove "Save changes" button as action which applies for all tabs. It's more safe to have "Save" separate for each tab. As many actions inside "Asset Update" cannot be reverted it's better to ask user to save each form inside "Asset Update" to prevent mistakes.
2. Add "Are you sure you want to leave without saving" alert if user tries to leave the page without saving his changes.
3. Add "Burn Asset" tab with "Danger" button, description and warning that user won't be able to restore his asset, will lost Pool Balance etc.

**Comment by sschiessl-bcp** [comment]
**Asset Creation**

- Highlight the difference of SmartCoin and UIA and give an explanatory text
- Give a general explanation into permissions and flags of an asset

**Asset Update**

- Prepare two buttons for Claim and Fund fee pool, I think it should **also** be in here, additionally to those buttons in Asset View

**Comment by clockworkgr** [comment]
Agreed on "Burn asset" coming with a warning but should be moved out of the assets page completely since if I'm not mistaken it's not only the issuer that can burn an asset.

**Comment by startailcoon** [comment]
@clockworkgr indeed. Anyone that has the asset in their portfolio can burn an asset to remove it from their holdings.

Burn asset is more of an asset details function than an asset management function.

**Comment by sschiessl-bcp** [comment]
> Technically Fund fee pool is also an asset details function, although mostly used by asset issuers.
>
>Defund fee pool is a new asset management function (see #1598).

**Comment by abitmore** [comment]
> (BTD) Remove "Save changes" button as action which applies for all tabs. It's more safe to have "Save" separate for each tab. As many actions inside "Asset Update" cannot be reverted it's better to ask user to save each form inside "Asset Update" to prevent mistakes.

Please be aware that each "save" involves a transaction fee, specifically, asset updating fee, which is a bit expensive. User may want less cost rather than more convenience.

**Comment by svk31** [comment]
Agree with abit, don't force saving on each tab.

Ideally we'd have a nice summary of the intended changes before submitting.

**Comment by startailcoon** [comment]
@svk31 we have a summary since before that I did a while ago. We never did an update to the UI back then though.

I agree that we shouldn't make a transaction on each tab change. Tabs are there just to make it more convenient for the user. We shouldn't force users to do something they don't need due to the UI layout.

**Comment by gibbsfromncis** [comment]
I've updated "Burn asset" requirement. I think we should remove it from Assets at all because it doesn't  relate to Asset management

**Comment by gibbsfromncis** [comment]
@abitmore can you please clarify what is the difference between Defund fee pool and Claim Fee Pool?

**Comment by startailcoon** [comment]
@gibbsfromncis if I'm not mistaken, one is for taking out the trading fees for the asset. Like an asset that has 0.2% fee. The other is to take out BTS, which is a new function.

**Comment by startailcoon** [comment]
I like what you've made. I agree with the others that we should keep the "Save" feature for all tabs, and try to make it a one transaction save. I like the warning idea if you leave without saving your changes.

@gibbsfromncis supply your UX working hours if you are statisfied with the end result of this UX task. I assume we're free to work on the UI tasks from this as no new comments have been posted for 3 weeks.

**Comment by wmbutler** [comment]
@gibbsfromncis any estimates for your work on this?

**Comment by svk31** [comment]
pinging @gibbsfromncis again

**Comment by gibbsfromncis** [comment]
@svk31 Honestly I lost the idea of this issue. Are we still talking about redesign of all Assets pages (Home/Create/Edit) ?

**Comment by gibbsfromncis** [comment]
@svk31 ping

**Comment by svk31** [comment]
Apart from the Home part it's still remains the same as far as I can tell.

**Comment by gibbsfromncis** [comment]
@svk31 what about Home part? I've checked production and it looks the same as it was

**Comment by gibbsfromncis** [comment]
@svk31 I have no idea what time is placed there but I'm going to close this task as it is duplicate of #1604
