### ISSUE TITLE
[2] Light-Wallet: Text cut-off

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-ui#163]
_From @btsfav on May 28, 2017 14:54_

![3d40d199-c23c-453b-944d-c65a16d10e6a](https://cloud.githubusercontent.com/assets/15261692/26529751/3143dbbc-43c6-11e7-94ea-8b9fd96f2cb6.jpg)

gateway drop-downs are cut-off in the most recent version.

win7 64bit here

_Copied from original issue: bitshares/bitshares-core#293_

**Comment by vikramrajkumar** [comment]
_From @abitmore on May 28, 2017 21:4_

Please report UI issues to https://github.com/bitshares/bitshares-ui/issues/

**Comment by wmbutler** [comment]
Need to get a windows dev to confirm and fix.

**Comment by happyconcepts** [comment]
![image](https://user-images.githubusercontent.com/14145836/28488558-bd3cc640-6e61-11e7-80dc-12aa40075115.png)

Confirmed in win7 64 bit.

**Comment by abitmore** [comment]
Likely a DPI scaling issue.

**Comment by happyconcepts** [comment]
![image](https://user-images.githubusercontent.com/14145836/28592066-bc58084c-713c-11e7-8976-b8fd257838fa.png)

So the dropdown does not obscure the text for me in the account page. The dropdown on the deposit page obscures the text.

**Comment by calvinfroedge** [comment]
Estimate: 2 hours or less, I think I padding / margin / height issue (windows browsers can interpret box model a bit differently)
Fix process: Use windows VM to test local modifications

**Comment by calvinfroedge** [comment]
I can take this issue
