### ISSUE TITLE
A TLS packet with unexpected length was received.

### ISSUE THREAD

**Issue by lilianwen** [bitshares/bitshares-ui#1630]
OS：ubuntu 16.04
branch:develop

when I run the command npm install,an error occurs:

npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/cryptonomex/jdenticon.git /root/.npm/_git-remotes/git-https-github-com-cryptonomex-jdenticon-git-0700db8c: Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-cryptonomex-jdenticon-git-0700db8c'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/cryptonomex/jdenticon.git /root/.npm/_git-remotes/git-https-github-com-cryptonomex-jdenticon-git-0700db8c: error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/cryptonomex/jdenticon.git /root/.npm/_git-remotes/git-https-github-com-cryptonomex-jdenticon-git-0700db8c: fatal: The remote end hung up unexpectedly
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/cryptonomex/jdenticon.git /root/.npm/_git-remotes/git-https-github-com-cryptonomex-jdenticon-git-0700db8c: fatal: early EOF
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/cryptonomex/jdenticon.git /root/.npm/_git-remotes/git-https-github-com-cryptonomex-jdenticon-git-0700db8c: fatal: index-pack failed
npm ERR! Linux 4.2.0-16-generic
npm ERR! argv "/root/.nvm/versions/node/v6.14.3/bin/node" "/root/.nvm/versions/node/v6.14.3/bin/npm" "install"
npm ERR! node v6.14.3
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/cryptonomex/jdenticon.git /root/.npm/_git-remotes/git-https-github-com-cryptonomex-jdenticon-git-0700db8c
npm ERR! Cloning into bare repository '/root/.npm/_git-remotes/git-https-github-com-cryptonomex-jdenticon-git-0700db8c'...
npm ERR! error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
npm ERR! fatal: The remote end hung up unexpectedly
npm ERR! fatal: early EOF
npm ERR! fatal: index-pack failed
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by svk31** [comment]
Never seen that, might be a node/npm issue if you're using an old version. Try upgrading if that's the case

**Comment by svk31** [comment]
```
npm ERR! node v6.14.3
npm ERR! npm v3.10.10
```
Those are way too old, I'm using node v9 and npm v6
