### ISSUE TITLE
[2][gibbsfromncis] Implementing Ant Popover to UI Styleguide

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1632]
Implementing AntD component popover for Issue #1477

https://ant.design/components/popover/

1h for UX 
1h for UI

**Comment by gibbsfromncis** [comment]
UX:

![dark theme_style guide_popover_v2 copy](https://user-images.githubusercontent.com/35899973/44930430-8b46bc80-ad5e-11e8-8abf-1ce449bef583.png)

![light theme_style guide_popover_v2 copy](https://user-images.githubusercontent.com/35899973/44930431-8bdf5300-ad5e-11e8-8e18-3221be561158.png)

![midnight theme_style guide popover_v2 copy](https://user-images.githubusercontent.com/35899973/44930434-8bdf5300-ad5e-11e8-8e9a-9fc31c8fd0db.png)

**Comment by gibbsfromncis** [comment]
Done.
