### ISSUE TITLE
Insufficient funds error

### ISSUE THREAD

**Issue by Sepero** [bitshares/bitshares-ui#164]
I hope I'm posting this issue in the correct place. Please forgive me and make correction if I have made a mistake.

Steps to reproduce issue:
1. Open trading platform
2. Go to any exchange where you own assets for both sides (for example if you own BTS and bitUSD, go to that exchange)
3. Attempt to sell all of one asset, and pay for the fee with your other asset.
4. You will receive the error "Insufficient funds to pay fees"

**Comment by wmbutler** [comment]
@svk31 can you confirm this fix and close?

**Comment by Sepero** [comment]
My apologies. It appears to be fixed for me now. Thank you
