### ISSUE TITLE
Add Gateways to deposit/ withdraw page

### ISSUE THREAD

**Issue by CryptoKong** [bitshares/bitshares-ui#1641]
**Is your feature request related to a problem? Please describe.**
Cryptobridge and easydex are missing from the drop down menu which allows you to select deposit/ withdraw gateway.

**Describe the solution you'd like**
Cryptobridge & EasyDex should be added to the list.

![image](https://user-images.githubusercontent.com/33036236/42134957-5aad3c86-7d3c-11e8-93a6-64fe69759d03.png)

**Comment by EasyDexOOD** [comment]
Cool... can you let us know when that's ready and how to get added to it?

**Comment by wmbutler** [comment]
It's already active. Here is the Wiki:

https://github.com/bitshares/bitshares-ui/wiki/Gateway-Integration-Requirements
