### ISSUE TITLE
[8] Customisable asset tab on exchange page

### ISSUE THREAD

**Issue by CryptoKong** [bitshares/bitshares-ui#1642]
**Is your feature request related to a problem? Please describe.**
On the exchange page there are various asset tabs, eg: bitUSD, bitCNY, open.BTC, bitBTC, other. Some of these tabs are never used and others are often required rather than jumbling it all up in "other".

**Describe the solution you'd like**
I would like to be able to remove tabs like bitCNY and bitBTC if I want and add another tab for bridge.BTC and easydex.BTC

![image](https://user-images.githubusercontent.com/33036236/42135015-20f93e62-7d3d-11e8-8389-caf1e8b14035.png)

**Comment by CryptoKong** [comment]
Yes as you see fit, it was just a suggestion on my part and appreciate it being taken on board. Thanks. :)

**Comment by wmbutler** [comment]
Default tabs can initialize the same as what they currently are, but any tab can be arbitrarily dismissed. Need a method to:

- [ ] Add a tab
- [ ] Remove a tab

**Comment by froooze** [comment]
I am looking for a custom tab, which can save any trading pair and is not limited to a specific pair.

**Comment by wmbutler** [comment]
I agree, but this issue is not really related. Maybe a tab called favorites that includes all starred markets, but you should open a separate issue for this.

**Comment by froooze** [comment]
With further adoption a FIAT tab for BTS / FIAT trading pairs would give a better experience for other currencies.

**Comment by wmbutler** [comment]
I think this can be distilled into the following:

- [ ] Allow users to add/delete arbitrary tabs (up to 5 total)
- [ ] Adding a tab would need a picker so the user can pick which asset the tab refers to
- [ ] Change the label of "Other" tab to "Favorites" and make it permanent (non-removable) This tab would show all favorited (starred) markets

Essentially, this would allow users to to create one or two tabs like (BTS, USD), and add markets to them. It would also allow users to see all of the markets they have favorited by going to the Favorites tab.

**Comment by svk31** [comment]
I got inspired today to work on a slightly different solution to this issue. While adding/removing tabs would still be nice, what I've done is combine all gateway.BTC and bitBTC assets into one tab, same with any other assets that are offered by multiple provides (OPEN.USD goes in the USD tab with bitUSD for example).

![image](https://user-images.githubusercontent.com/6890015/42644797-be9df442-85fc-11e8-96cc-b3f34c5a8a43.png)

While this may cause confusion over seemingly duplicate entries, I believe it is a better way to represent the markets as it allows one to quickly compare volume over *all* BTC markets for example.

In the screenshot you see two BTS entries, the starred one is BTS:GDEX.BTC, the second one is BTS:OPEN.BTC

**Comment by svk31** [comment]
Creating a Favorites tab putting all starred markets together is problematic imo because it won't let you sort by volume anymore in a reliable manner.

**Comment by froooze** [comment]
1. combining the two BTC market tabs in one is good idea
2. creating a favorite tab for all favorites doesn't make sense
3. Just call it custom tab, with the ability to rename it, therefore anybody can use it for a special use case
4. We can ignore the favorite settings because we already have our favorites in the custom tab
5. We need some UI to easy fill the custom tabs

**Comment by wmbutler** [comment]
I still think it would be a good idea to be able to remove tabs that users feel are not useful for their needs. I also think that a definitive tab that shows all starred assets is a good idea (with or without volume display). The two-tiered approach to locating an asset pair and then starring it is still overly complex and needs an elegant solution. Looks like this was a step in the right direction.

**Comment by svk31** [comment]
I did add the ability to remove tabs.
