### ISSUE TITLE
Remove the BIT.BTC Tab 

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares-ui#1644]
BIT.BTC is barely used by anybody has it is not a reliable way to deposit and withdraw on to the BitShares blockchain. It never has been, please look at 24hr volumes for BIT.BTC, smartcoins only work well for non digital, low volatility, assets like fiat and precious metals. 
Removing this tab won't stop anyone from trading BIT.BTC as the other coins it does occasionally trade with have their own tabs. (BTS,OPEN.BTC, BITUSD, BITCNY)

The advantage of removal of BIT.BTC tab is simplicity and less confusion from having 2 BTC types. 
<img width="351" alt="screen shot 2018-07-02 at 15 01 01" src="https://user-images.githubusercontent.com/15330829/42168832-fce48f4a-7e09-11e8-8e53-92291c473707.png">

**Comment by wmbutler** [comment]
I think this falls into users being able to arbitrarily add/remove main tabs. #1642

**Comment by svk31** [comment]
@wmbutler if so then add a discussion of what the default tabs should be to that issue.
