### ISSUE TITLE
New IP Rule unfair to families

### ISSUE THREAD

**Issue by cniijane-compumatrix** [bitshares/bitshares-ui#1656]
Your new "One account per IP" is unfair to families that share the same IP.    There are three adults in the family and a few others that come and use the same IP at my home. Then there is the issue of having a separate account to do the majority of trading and wanting a "holding" account for security.  You have swept away the ability for both to be handled with this new "rule".  And given Bitshares is decentralized you have just taken a HUGE step out of that arena by looking at IP addresses!

**Comment by DustBuster1** [comment]
New IP Rule unfair especially when we have family members living with us....please reconsider this rule.
