### ISSUE TITLE
Why would you even be looking at our IP address  being a decentralized area. Not fair to family  members using this . PLEASE CHANGE THAT ASAP.  

### ISSUE THREAD

**Issue by gp1111** [bitshares/bitshares-ui#1659]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gp1111** [comment]
Why would  you even be looking at our IP address anyway being a decentralized area  ??  Not fair to family members . PLEASE CHANGE THIS ASAP .

**Comment by sschiessl-bcp** [comment]
#1655
