### ISSUE TITLE
errors/no-reaction hitting withdraw button

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [bitshares/bitshares-ui#166]
A user reported seeing this error while trying to withdraw btc through openledger gateway http://i.imgur.com/kltxd2g.png (bitshares.org/wallet portal)

I tried to replicate and withdraw open.btc through openledger gateway using bitshares.org/wallet portal and chrome/windows7. Wallet was unlocked. I had open.btc & bts. Filled out the form to withdrar 0.09 btc to my own bitcoin address, hit withdraw, no reaction, withdraw button still visible. Clicked several times - nothing. refreshed - nothing. tried openledger.io portal, same thing. tried firefox with both portals - same thing. Even blocktrades bridge was givign same thing. however, I was able to use send tab to send bitshares themselves easily.

Thanks. Something seemed very wrong just now, seems new.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
Solved my issue - memo key didn't match new active permission key after switch from wallet model to account model. copied new active permission key to memo key - everything works.

**Comment by wmbutler** [comment]
Closing.
