### ISSUE TITLE
New  IP rule? That is totally unfair to family members!!!!

### ISSUE THREAD

**Issue by andott** [bitshares/bitshares-ui#1660]
Why are you limiting family from using this site?  
Obviously anyone using computers from same home will have this issue.
This is insane.
And it is no way to grow your business - quite the opposite!
This needs to be changed NOW!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sschiessl-bcp** [comment]
#1655
