### ISSUE TITLE
[3] Tables Style-Guide improvements

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1662]
Working on this issue #1636 I've discovered that style-guide's Tables with sorting/filtering options doesn't have proper styles (dark columns when sorted, wrong color of sorting triangles) :

<img width="1381" alt="screenshot 2018-07-04 10 07 09" src="https://user-images.githubusercontent.com/35899973/42264832-12141a8e-7f72-11e8-979d-f1b1abd5456a.png">

To do:

- [ ] UX for tables with sorting & filtering for all themes
- [ ] Restyles tables based on UX for all themes

Requested hours: 1.5h for UI and 1h for UX

@wmbutler FYI me and @startailcoon decided to keep style-guide UX and UI in sync. So any even simple updates on UI (like fixing colors for table columns when sort/filters enabled) should be duplicated on UX to prevent mess in the future.

**Comment by wmbutler** [comment]
Can we agree to avoid zebra striped rows? This creates visual problems with a hover state.

**Comment by Kennybll** [comment]
I would like to claim this! We don't need a UI, just the UX, it's just a few style rules needed.

**Comment by startailcoon** [comment]
@Kennybll @gibbsfromncis have intended to work on this. He is unable to post about this here as he is unable to access his github account currently.

**Comment by Kennybll** [comment]
@startailcoon Okay, but it doesn't help that there are so many github issues that are claimed by so few, and possibly on vacation too. I would like to help on some that seem to be claimed, but still are open. Just to put that out there.

**Comment by wmbutler** [comment]
@Kennybll understood, but I think @gibbsfromncis is deep enough into the styleguide that it might make sense for him to keep this one.

**Comment by gibbsfromncis** [comment]
@Kennybll Feel free to take any issues regarding bitshares-ui. If you want to work on style-guide too please start from bitshares-ui.

**Comment by gibbsfromncis** [comment]
Screenshots of updated tables design:

<img width="1260" alt="screenshot 2018-09-13 05 10 09" src="https://user-images.githubusercontent.com/35899973/45464970-4eda6f80-b713-11e8-9ae2-bdb8593b0a7e.png">
<img width="1241" alt="screenshot 2018-09-13 05 10 04" src="https://user-images.githubusercontent.com/35899973/45464971-4eda6f80-b713-11e8-8bf6-6547b8571122.png">
<img width="1218" alt="screenshot 2018-09-13 05 09 58" src="https://user-images.githubusercontent.com/35899973/45464973-4f730600-b713-11e8-83e8-c1f6e8b68033.png">

Added by commit: https://github.com/bitshares/bitshares-ui-style-guide/commit/b1a271ba53536ca8f4cffef6901b1d48b5fd5612

**Comment by wmbutler** [comment]
It would be nice for the "No Data" area to be a placeholder that is centered vertically and horizontally without a table row.

"No items to display"

**Comment by gibbsfromncis** [comment]
@wmbutler like this?
<img width="1196" alt="screenshot 2018-09-13 05 30 36" src="https://user-images.githubusercontent.com/35899973/45465575-29029a00-b716-11e8-83e1-ac722394cb3d.png">

**Comment by wmbutler** [comment]
I like that better, yes.

**Comment by gibbsfromncis** [comment]
@wmbutler updated based on your feedback:

<img width="1170" alt="screenshot 2018-09-13 06 01 17" src="https://user-images.githubusercontent.com/35899973/45466493-7123bb80-b71a-11e8-80e2-a536b3c35d3c.png">
<img width="1172" alt="screenshot 2018-09-13 06 01 11" src="https://user-images.githubusercontent.com/35899973/45466494-7123bb80-b71a-11e8-9518-815a193576d8.png">
<img width="1170" alt="screenshot 2018-09-13 06 01 05" src="https://user-images.githubusercontent.com/35899973/45466495-7123bb80-b71a-11e8-8a6f-79b50e0cb48c.png">
