### ISSUE TITLE
Summarize Total Open Orders

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#1666]
With a lot of open orders you loose easy track how much is in the open orders.

Creating a summarize table before the open orders to get an overview.  

Asset  |  Buy  | Sell |  Delta
 ---------| ------ | ------ | ------
BTS           |  400  | 100 |  300                           
Dollar        |  50    | 200 | -150 
open.BTC |   0     | 0.01| -0.01

**Comment by startailcoon** [comment]
This is a great idea. I think it would be more useful to have it before the open order table though.

We also need to make sure we have no performance issues with large open orders lists.

**Comment by froooze** [comment]
You are right the table fits better on the top.

**Comment by wmbutler** [comment]
This seems rather trivial when looking at the big picture. Some comments:

- Open orders have 2 sides to the trade. Your Asset column doesn't reflect this reality.
- We already have a filter column to allow users to isolate assets.

**Comment by froooze** [comment]
- I have two columns in my example (Buy/Sell), so reality is reflected.
- People who provide liquidity, need to know how much they buy and sell from a specific asset class. 
I never used the filter function, but i have to calculate every time the sums of my open orders.

**Comment by wmbutler** [comment]
But you do not state the asset on the other side of the trade...

**Comment by froooze** [comment]
You mean the difference between actual price and trading price? 
Don't understand the problem, could you make an example?

**Comment by froooze** [comment]
I split one trading pair in two different rows and columns,  there is no duplication. 
I just combine all orders in one view and the delta shows me the difference after all orders are filled.

**Comment by wmbutler** [comment]
If someone can make sense of this, go for it.

**Comment by froooze** [comment]
The calculation for the sum table could be done client side via JavaScript, therefore no extra API calls are needed.

**Comment by abitmore** [comment]
If need a new API please open an issue in bitshares-core repository.

**Comment by abitmore** [comment]
IIRC the "open orders" data is obtained via `get_full_accounts` API, I guess we're able to calculate the summary from the results.

**Comment by froooze** [comment]
Already implemented.
