### ISSUE TITLE
[0.25] change order of TRADE/CANCEL collumn in open orders 

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#1667]
I think the CANCEL and TRADE columns should not be at the end of the row, because they are often used and belong to the Order ID & DESCRIPTION. 

New order should look like:
ORDER ID | CANCEL | DESCRIPTION | TRADE | PRICE | MARKET PRICE | VALUE

Or:
CANCEL | ORDER ID | DESCRIPTION | TRADE | PRICE | MARKET PRICE | VALUE

**Comment by startailcoon** [comment]
I see this as a good proposal. having the checkbox at the far right is quite weird in my opinion.

Feedback?

**Comment by wmbutler** [comment]
The checkbox should be at the leftmost or rightmost column. I have no opinion either way.

**Comment by wmbutler** [comment]
I have no idea what you are asking me.

**Comment by froooze** [comment]
Why not next to DESCRIPTION, which is already clickable ?

**Comment by wmbutler** [comment]
Because Action items make sense at one end or the other.

**Comment by froooze** [comment]
This discussion will never end, we can close this one and I will start a new one to allow customize column arrangement with hide option for columns.

**Comment by wmbutler** [comment]
I disagree with custom column arrangement but go for it.

**Comment by froooze** [comment]
Customize column is not that important at the moment. 

And Feedback on this order?
 CANCEL | TRADE | DESCRIPTION | ORDER ID | PRICE | MARKET PRICE | VALUE

**Comment by startailcoon** [comment]
Moved the table to place `Cancel` and `Trade` at the start of the table.

![bild](https://user-images.githubusercontent.com/12114550/43048009-dfa4adca-8de0-11e8-8441-0d11466091cf.png)
