### ISSUE TITLE
save switching trading pair status

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#1668]
Switching the trading pair after every revisit is just annoying. 

When I click to a trading pair the last switching state should be saved.

**Comment by wmbutler** [comment]
When you star a particular market, and return to that starred market it is saved.

**Comment by froooze** [comment]
The market is only saved in one direction. When I switch the trading pair, visit another market and revisit the switched market, it is not saved.

**Comment by wmbutler** [comment]
Your experience is different from mine:

![markets](https://user-images.githubusercontent.com/1254810/42481430-02dd3ae8-83a8-11e8-8833-ddaa52bef820.gif)

**Comment by froooze** [comment]
Maybe I wasn't clear enough about the problem. With switching the trading pair I mean the two arrow icon under the pair names. This setting doesn't get saved.

**Comment by wmbutler** [comment]
My licecap clearly shows that the market shows up according to which pair you choose from the picker on the the right.

**Comment by froooze** [comment]
The problem exists with the BTS Tab. I can only enter the market with bitFIAT / BTS. 
When I wanna have BTS / bitFIAT, I have to change the pair with the two arrows, after every revisit.

There are two solutions:
1. Save the switched state 1/BTS Tab
2. introduce a custom Tab, where any pairs can be saved.
