### ISSUE TITLE
[1.5] Tradingview save template storage

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#1669]
The trading view has the option to save a template, but last time the list was cleared and I had to redo the whole theme. 

Are there any plans how this is moderated in the future?

**Comment by froooze** [comment]
My saved template is lost again. It looks like a bug.

**Comment by wmbutler** [comment]
Worth investigating. @froooze just want to verify that you are connecting from the same browser on the same machine first.

**Comment by svk31** [comment]
The TradingView library doesn't offer any storage so we'd have to set one up. Their docs assume you run a server for this, with user login etc, but that's not an option for us imo. Another option is to use localStorage which might work, but I disabled localStorage for tradingView because it messed with the themeing.

If someone wants to handle the issue I can send them a copy of the tradingview wiki page for "Saving and Loading Charts" since their wiki is private.

**Comment by froooze** [comment]
I can take a look at the docs, but need maybe a little help for the first time.

**Comment by wmbutler** [comment]
Would you like to claim this issue?

**Comment by froooze** [comment]
Yes, how can I do that ?

**Comment by wmbutler** [comment]
It's yours.

https://github.com/bitshares/bitshares-ui/blob/develop/README.md

**Comment by froooze** [comment]
Ok and what is the easiest way to send me the private wiki from tradingview?

**Comment by svk31** [comment]
https://drive.google.com/open?id=1D3ixMYoGB-AyMBd38ljt9Nq0gWW7Cmon

Try that. Let me know when you have it and I'll take it down again

**Comment by startailcoon** [comment]
@froooze Another request for this on https://github.com/bitshares/bitshares-ui/issues/1669

**Comment by wmbutler** [comment]
@froooze timeframe?

**Comment by froooze** [comment]
I can give an update at the end of the week.

**Comment by startailcoon** [comment]
Ping @froooze

**Comment by startailcoon** [comment]
What's your progress on this issue @froooze?

**Comment by froooze** [comment]
Couldn't work on the problem, had some health and internet problems. I hope it will now work out. 
Last time I ad some compiling issues.

**Comment by froooze** [comment]
I have zero experience in Tradingview and Bitshares coding and couldn't make any progress, therefore I would give the problem to another person and use my resources for other things first.

**Comment by startailcoon** [comment]
@froooze I will remove your assignment. You're welcome back if you find any solution.

**Comment by gibbsfromncis** [comment]
@svk31 I've requested an access to Wiki. Please share it and if it's clear I'll work on this one

**Comment by gibbsfromncis** [comment]
@startailcoon to be honest I have no time for this in this sprint. I can update sprint or unassign myself. Btw it looks like no one ready to take it so this task can wait for me

**Comment by apiekarczyk** [comment]
Friendly remind that we still waiting for resolving this problem.

**Comment by froooze** [comment]
Can we put this on high priority?

**Comment by vanissoft** [comment]
Days ago i could store tradingview settings but then this ability has gone.
![image](https://user-images.githubusercontent.com/4522822/57978777-d0596e80-7a13-11e9-87d4-9fe03f7cd4a9.png)

**Comment by froooze** [comment]
@vanissoft: Storage works only temporary.

**Comment by sschiessl-bcp** [comment]
Corresponding (internal) PR is here if you are interested https://github.com/blockchainprojects/bitshares-ui/pull/89

**Comment by vanissoft** [comment]
Can this error be related to the impossibility of saving templates?

`2vendors.fd8604c09abed9f6643a.js:29 POST https://saveload.tradingview.com/1.1/study_templates?client=tradingview.com&user=public_user_id 403
send @ vendors.fd8604c09abed9f6643a.js:29
ajax @ vendors.fd8604c09abed9f6643a.js:28
a.saveStudyTemplate @ library.19c99ed5d0307c67f071.js:265
a @ library.19c99ed5d0307c67f071.js:472
i @ library.19c99ed5d0307c67f071.js:472
(anonymous) @ library.19c99ed5d0307c67f071.js:472
Promise.then (async)
(anonymous) @ library.19c99ed5d0307c67f071.js:472
(anonymous) @ library.19c99ed5d0307c67f071.js:471
a.getStudyTemplatesList @ library.19c99ed5d0307c67f071.js:265
n.refreshStudyTemplateList @ library.19c99ed5d0307c67f071.js:471
runOrSignIn.source @ library.19c99ed5d0307c67f071.js:472
window.runOrSignIn @ library.19c99ed5d0307c67f071.js:588
n.showSaveAsDialog @ library.19c99ed5d0307c67f071.js:472
(anonymous) @ library.19c99ed5d0307c67f071.js:471
e.fire @ library.19c99ed5d0307c67f071.js:28
t._change @ library.19c99ed5d0307c67f071.js:320
m @ library.19c99ed5d0307c67f071.js:102
dispatch @ vendors.fd8604c09abed9f6643a.js:14
a @ vendors.fd8604c09abed9f6643a.js:12
/charting_library/static/tv-chart.630b704a2b9d0eaf1593.html#localserver=1&symbol=USD_BTS&interval=240&toolbarbg=2a2a2a&widgetbar=%7B%22details%22%3Afalse%2C%22watchlist%22%3Afalse%2C%22watchlist_settings%22%3A%7B%22default_symbols%22%3A%5B%5D%7D%7D&timeFrames=%5B%7B%22text%22%3A%225y%22%2C%22resolution%22%3A%22W%22%7D%2C%7B%22text%22%3A%221y%22%2C%22resolution%22%3A%22W%22%7D%2C%7B%22text%22%3A%226m%22%2C%22resolution%22%3A%22120%22%7D%2C%7B%22text%22%3A%223m%22%2C%22resolution%22%3A%2260%22%7D%2C%7B%22text%22%3A%221m%22%2C%22resolution%22%3A%2230%22%7D%2C%7B%22text%22%3A%225d%22%2C%22resolution%22%3A%225%22%7D%2C%7B%22text%22%3A%221d%22%2C%22resolution%22%3A%221%22%7D%5D&locale=en&uid=tradingview_112d5&clientId=tradingview.com&userId=public_user_id&chartsStorageUrl=https%3A%2F%2Fsaveload.tradingview.com&chartsStorageVer=1.1&customCSS=darkTheme.css&debug=false&timezone=Europe%2FMadrid:1 Access to XMLHttpRequest at 'https://saveload.tradingview.com/1.1/study_templates?client=tradingview.com&user=public_user_id' from origin 'https://staging.bitshares.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

It appears when loading the page and whenever i try to save template.

**Comment by sschiessl-bcp** [comment]
Bounty request in https://github.com/bitshares/bitshares-ui/pull/2804/#issue-289595014
