### ISSUE TITLE
[1.5] Feature: friend list / address book / known contact 

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#167]
We badly need this feature, to reduce human errors while sending funds. Sorry if it's a duplicate feature request.

**Comment by grctest** [comment]
It's a good idea - most cryptocurrencies have an address book.

**Comment by abitmore** [comment]
We already have "follow account" feature in the wallet (advanced mode). There is a "pay" button when viewing a followed account. Currently it's best/safest practice to send funds via these features. Perhaps we can improve the UI/UX though.

**Comment by wmbutler** [comment]
Agreed. Part of an Account UX rewrite.

**Comment by wmbutler** [comment]
I was thinking about this and I'm pretty sure I have a good idea. 

- Why don't we change **Follow Account** to **Add to Address Book** 
- Next we could limit the typeahead when sending funds to only those accounts in the address book (those being followed). This limit could be optional with checkbox possibly stating **only search address book** and could be unchecked when trying to find someone not contained in the address book.
- Starred accounts would still show up in the drop-down.

**Comment by fractalnode** [comment]
We could also add a block on unfair addresses like "poloniex" and already put some of them in this list, certainly a poloniex account

**Comment by landry314** [comment]
But following accounts is more than for keeping addresses. I certainly agree that expanding the followed accounts into an address book feature is a great idea but how about naming it "Contacts" or something more general?

**Comment by landry314** [comment]
There was some discussion in issue #533 about this highly needed address book feature.

@tbone-bts, you might want to get in on this new discussion.

**Comment by landry314** [comment]
In issue #715 I bring up some possible issues with merging the Followed Accounts into an Address Book. Mainly, starring someone's account puts it into the dropdown menu on the upper right so you would have your friend's accounts in there which is fine if you want to check on your friend's finances but address books generally aren't for that.

Maybe have a column for "Following" which will reveal the finances of someone's account but hide it otherwise. I just think it is weird to have your friend's balances in your address book... you know what I mean?

**Comment by calvinfroedge** [comment]
Will mockups be added here or is creating them part of the estimate?

**Comment by wmbutler** [comment]
@calvinfroedge we already have a "follow" feature. I think this can be converted to "Add to Contacts" just by changing terminology. Additionally, I think there is a good pattern for preferring accounts that are in the users contacts when performing a "send" operation. This could be very helpful for ensuring that addresses are trusted.

Why don't we just take this slowly and start with changing the follow button to "Add Contact"

**Comment by wmbutler** [comment]
- Anything that's an Account (in blue), sort to accounts tab
- Anything that's a follow (in white), sort to contacts tab
- Leave the Recent Activity tab as is for now

![screen shot 2017-11-24 at 11 05 19 am](https://user-images.githubusercontent.com/1254810/33219612-e7a84f4e-d108-11e7-9562-ae7f13e3edb4.png)

**Comment by efork** [comment]
Hi, is this task available to pick up?  New to the project and figured I could grab the oldest to get my feet wet.  Should be able to complete today.

**Comment by svk31** [comment]
Ok we now have the contact list feature built in, but the Transfer screens still need to be updated to actually use the contacts.

**Comment by wmbutler** [comment]
Great work @efork. Please reply with your bts address for payment.

**Comment by efork** [comment]
Thank you,  efork-1.  Will take a look at open issues and help out where I
can in the next few days.
