### ISSUE TITLE
[2] Orders Api

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1672]
To investigate 

Christopher Sanborn:
I’m having trouble connecting the latest light-wallet to my recently updated witness (non-producing) and API node.  If I’m understanding the electron console errors correctly, it’s because of “Assert Exception: _orders_api:”

In the witness logs I see “!ec: websocket send failed: invalid state” and “{"msg":"invalid state”}” after “creating database api” and “freeing database api”.

Is there a plugin I need to enable in order to run an API node for my wallet to connect to?  I did not have connection problems with the older light-wallet and previous bitshares-core release, so this appears to be a recent change.  What’s needed to enable the correct plugin or API?

Thanks!

**Comment by sschiessl-bcp** [comment]
Abit More:
if orders_api is the issue, add it to api-access file

you may need to add grouped_orders to plugins

**Comment by sschiessl-bcp** [comment]
Is grouped mandatory? We might need to add fallback

**Comment by abitmore** [comment]
@sschiessl-bcp please check this and related commits: https://github.com/bitshares/bitsharesjs-ws/commit/d00716f4bb7c9e50b0ecabc0a2d0cb2fa40a2378

**Comment by sschiessl-bcp** [comment]
I have seen orders_api error on couple nodes. I assume it's not on per default @abitmore ?

**Comment by abitmore** [comment]
@sschiessl-bcp it's enabled by default, but only for new API nodes or nodes didn't use `plugins` option.
* when upgrading a node from an old version, if `plugins` option is used, need to manually add `grouped_orders`;
* the plugin is added in `2.0.180328` release, I guess some API nodes haven't upgraded.

**Comment by svk31** [comment]
I made it mandatory to basically filter out nodes that had not upgraded yet. Last few days I've also seen some issues with nodes running without market_history enabled which the GUI requires to run, should make that mandatory as well.

**Comment by sschiessl-bcp** [comment]
Okay, then we need to check all nodes in the reference faucet. 
If the nodes doesn't support it contact the operator. If no response, remove from list and create issue for readding after upgrading. New staging release was done today, thanks Sigve, this should be doable for this cycle.

I ll be happy to manage that

**Comment by startailcoon** [comment]
[bitshares.crypto.fans](https://bitshares.crypto.fans) is updated. This had me confused until I read that it coule be missing in the API Access settings file, and adding `orders_api` to my access file solved this.

**Comment by sschiessl-bcp** [comment]
During investigating and working on this I somehow ended up refactoring ... I don't expect to get hours for that.

Anyways, I will add a feature that automatically disables nodes that don't support required apis which could use some points.

**Comment by wmbutler** [comment]
Is this going to be claimed or just serving as reference?

**Comment by sschiessl-bcp** [comment]
This is already done, most time went into manual testing and filtering nodes.
