### ISSUE TITLE
[2.5][kapeer42] Permanently reject a proposal

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1673]
**Is your feature request related to a problem? Please describe.**
There is a "proposal_delete_operation" in the core, although a little buggy when using on multi-sig accounts, it would be quite easy and useful for normal accounts (e.g. to fight scams/phishing). Especially, as of writing, on BitShares mainnet, the required fee is zero.

**Describe the solution you'd like**
Able to permanently reject a proposal. 

**Describe alternatives you've considered**

**Additional context**
See https://bitsharestalk.org/index.php?topic=26782.msg319803#msg319803.

**Comment by wmbutler** [comment]
This sounds like a blacklist operation. Would this be a core function that we would provide a UI for?

**Comment by svk31** [comment]
It's an existing operation.

Right now in the GUI you can only add or remove authorities to a proposal, you can't reject a spam proposal like abit's example, or cancel a proposal if you did something wrong in it. Using proposal_delete_operation you can do those things.

**Comment by wmbutler** [comment]
It sounds like @abitmore wants something that will perform a recurring reject. I was trying to come up with a way for the frontend to know who to perform that operation against.

**Comment by abitmore** [comment]
@svk31 has said what I wanted to say. Thanks.

**Comment by abitmore** [comment]
According to the [(buggy) back end code](https://github.com/bitshares/bitshares-core/blob/90f365a8b0c304ce025ed4d4f5239fba698fb792/libraries/chain/proposal_evaluator.cpp#L292-L296), every account in `required_xxx_approvals` of a proposal can reject the proposal.

**Comment by startailcoon** [comment]
Increased bounty as this would need some reading up on how to make it work.

**Comment by Kennybll** [comment]
I would like to claim this.

**Comment by startailcoon** [comment]
it's yours @Kennybll

**Comment by wmbutler** [comment]
@Kennybll anticipated timeframe?

**Comment by Kennybll** [comment]
Please remove me from this task @wmbutler

**Comment by kapeer42** [comment]
Can I claim this?

**Comment by startailcoon** [comment]
It's yours @kapeer42

**Comment by kapeer42** [comment]
@abitmore 
> as of writing, the required fee is zero.
This is not true on the testnet now.

**Comment by sschiessl-bcp** [comment]
When using cloud mode, or local wallet with one account it would be nice to have fee payer account preselect, wouldn't it?

![image](https://user-images.githubusercontent.com/33128181/45618386-bf67f000-ba75-11e8-9d8a-387c1ec17117.png)

**Comment by kapeer42** [comment]
Well, actually it's the case if you click delete without selecting an account.
The AccountSelect component used does not seem to allow for a preselection. I tried to modify it quickly but it wasn't trivial. Will dig deeper.

**Comment by sschiessl-bcp** [comment]
If this causes more work raising hours is fine. UX should have preselection if only one account.
