### ISSUE TITLE
[0.5] Proposed transactions page: show proposer

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1674]
**Is your feature request related to a problem? Please describe.**
Since a release, "proposal_object" has a "proposer" field. Best if it can be shown on UI.

![image](https://user-images.githubusercontent.com/9946777/42418627-aca8ef36-82a4-11e8-89d5-fe22219ec391.png)

![image](https://user-images.githubusercontent.com/9946777/42418737-c5fcbe0c-82a6-11e8-976e-635ca83b40f6.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
https://bitsharestalk.org/index.php?topic=26782.msg319803#msg319803

**Comment by startailcoon** [comment]
What I can see, this is already implemented.

If there is a specific transaction that you see that should have this value, but hasn't, please open this issue again and specify where this is the case.

**Comment by abitmore** [comment]
@startailcoon OP updated with a screenshot. Do you know which account proposed that proposal?

**Comment by startailcoon** [comment]
I may miss something, but the operation does not contain a `proposer` field. I don't see another object ID that can be fetched for this either.

@abitmore 

Object: [1.10.11600](http://open-explorer.io/#/objects/1.10.11600)
```
[
  {
    "available_active_approvals": [],
    "available_key_approvals": [],
    "available_owner_approvals": [],
    "expiration_time": "2018-07-09T10:37:02",
    "id": "1.10.11600",
    "proposed_transaction": {
      "expiration": "2018-07-09T10:37:02",
      "extensions": [],
      "operations": [
        [
          0,
          {
            "amount": {
              "amount": 100000,
              "asset_id": "1.3.0"
            },
            "extensions": [],
            "fee": {
              "amount": 0,
              "asset_id": "1.3.0"
            },
            "from": "1.2.0",
            "memo": {
              "from": "BTS5C5ay6DU512g7xk2SurbnGL5phGMCU86rkkoaciBxvVTo26Sbh",
              "message": "c41deb51660ce34e062611fa810d3981",
              "nonce": "391946911017170",
              "to": "BTS5C5ay6DU512g7xk2SurbnGL5phGMCU86rkkoaciBxvVTo26Sbh"
            },
            "to": "1.2.166442"
          }
        ]
      ],
      "ref_block_num": 0,
      "ref_block_prefix": 0
    },
    "required_active_approvals": [
      "1.2.0"
    ],
    "required_owner_approvals": [],
    "review_period_time": "2018-07-08T10:37:02"
  }
]
```

**Comment by startailcoon** [comment]
However, when a proposal is created and recorded on the chain, we have a TX that links to said Proposal Object.

Object: [1.11.263437318](http://open-explorer.io/#/objects/1.11.263437318)

```
[
  {
    "block_num": 28541520,
    "id": "1.11.263437318",
    "op": [
      22,
      {
        "expiration_time": "2018-07-09T10:37:02",
        "extensions": [],
        "fee": {
          "amount": 90766,
          "asset_id": "1.3.0"
        },
        "fee_paying_account": "1.2.166442",
        "proposed_ops": [
          {
            "op": [
              0,
              {
                "amount": {
                  "amount": 100000,
                  "asset_id": "1.3.0"
                },
                "extensions": [],
                "fee": {
                  "amount": 0,
                  "asset_id": "1.3.0"
                },
                "from": "1.2.0",
                "memo": {
                  "from": "BTS5C5ay6DU512g7xk2SurbnGL5phGMCU86rkkoaciBxvVTo26Sbh",
                  "message": "c41deb51660ce34e062611fa810d3981",
                  "nonce": "391946911017170",
                  "to": "BTS5C5ay6DU512g7xk2SurbnGL5phGMCU86rkkoaciBxvVTo26Sbh"
                },
                "to": "1.2.166442"
              }
            ]
          }
        ],
        "review_period_seconds": 86400
      }
    ],
    "op_in_trx": 0,
    "result": [
      1,
      "1.10.11600"
    ],
    "trx_in_block": 9,
    "virtual_op": 11084
  }
]
````

**Comment by abitmore** [comment]
@startailcoon please use an up-to-date API server.

**Comment by startailcoon** [comment]
@abitmore not sure why I wasn't able to see it, maybe it was an outdated node. But this works now.

![bild](https://user-images.githubusercontent.com/12114550/42418924-f6f06172-82aa-11e8-8ea5-11f4f5294eec.png)

**Comment by abitmore** [comment]
We need to show it in **Proposed transactions page**.

**Comment by abitmore** [comment]
I'll open a new issue for this.
