### ISSUE TITLE
[0.5] Search function on exchange doesnt list all assets

### ISSUE THREAD

**Issue by CryptoKong** [bitshares/bitshares-ui#1675]
**Describe the bug**
When using the search function after typing part of the asset name it doesn't list all available assets.

**To Reproduce**
1. Go to exchange page
2. Click on search field
3. type "QTUM"

**Expected behavior**
I would expect it to list bridge.QTUM, open.QTUM, gdex.QTUM, rudex.QTUM

**Screenshots**
![image](https://user-images.githubusercontent.com/33036236/42410091-44f10928-81dc-11e8-93f8-8392572c8560.png)
![image](https://user-images.githubusercontent.com/33036236/42410110-70730a88-81dc-11e8-8ed8-585e49df691d.png)
![image](https://user-images.githubusercontent.com/33036236/42410158-12148e3e-81dd-11e8-9ac8-718ba06cf483.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - Version: 180629

**Additional context**
I've tried this with various assets and the same thing happens. I'm trying to create a list of markets such as open.BTC-bridge.BTC or open.ETH-gdex.ETH to encourage people to make these markets so I would like to be able to just type in an asset such as "BTC" or in this case "QTUM" and see every gateway its listed on.

**Comment by startailcoon** [comment]
This is because the search on `Find Markets` only searches for for assets starting with `Q` + ~20 names (I belive). There is a change that we can do to include known gateway assets. This is a minor change and is already implemented on the Market Picker (#1379).

**Comment by startailcoon** [comment]
Updated Find Market with the following changes
- Require at least 3 characters to initiate a search
- Wait timer on key input to reduce unessesary queries when typing
- Include backedAssets, defined in AssetActions and currently including `let gatewayPrefixes = [
                        "BRIDGE",
                        "GDEX",
                        "RUDEX",
                        "OPEN",
                        "WIN"
                    ];`

![bitshares-findasset](https://user-images.githubusercontent.com/12114550/42418241-5ba28898-829c-11e8-9b37-2cabdf8c34b7.gif)

**Comment by HarukaMa** [comment]
@startailcoon User reports that there are assets which names only contains two letters, for example bridge.xp, and limiting to 3 characters would make assets like those difficult to search.

**Comment by startailcoon** [comment]
@HarukaMa noted and fixed
