### ISSUE TITLE
[0.5] Show full precision of amounts in account history

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1676]
**Describe the bug**
OPEN.BTC has 8 decimals, but only shows 6 in account history.

**To Reproduce**
See screenshots below.

**Expected behavior**
Show full precision.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/42417806-74c7d8b8-8293-11e8-8cf8-438bb4de2133.png)

**Additional context**

**Comment by startailcoon** [comment]
This should indeed be using the assets decimal precision

**Comment by startailcoon** [comment]
Account History had a decimal offset setting, which I think isn't something we should have in there. If a user buys/sells an asset with 8 decimal precission, they wish to see the total amount they sold/bought and not a rounded value.

![bitshares-accountassetprecission](https://user-images.githubusercontent.com/12114550/42418408-2d135044-82a0-11e8-803f-24dcac68b12f.gif)
