### ISSUE TITLE
Account page blank screen

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1679]
**Describe the bug**

**To Reproduce**
1. Open a new incognito window
2. Go to https://develop.bitshares.org/#/account/abit-worker

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/42418666-48a733a2-82a5-11e8-95fa-82644d58e588.png)

![image](https://user-images.githubusercontent.com/9946777/42418669-5899bdde-82a5-11e8-9bcc-01b0b841614d.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version latest

**Additional context**

**Comment by svk31** [comment]
This was fixed by @startailcoon in #1683 , the issue for that was #1682 , reward should be assigned from there.
