### ISSUE TITLE
[.5] Back/forward buttons are broken

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1681]
**Describe the bug**
Valera Cogut reported:
>https://wallet.bitshares.org/#/help/introduction/bitshares  here are incorrect links for WALLET region at the end of page

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by svk31** [comment]
Actually none of the links work once you're on the help page, looking into it but it's not immediately obvious why.
