### ISSUE TITLE
[1] Add links to asset details within exchange view?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#169]
What do you think about including a link to the asset page from within the exchange view?
https://openledger.io/market/BTS_USD
https://openledger.io/asset/BTS
https://openledger.io/asset/USD

It might make it easier for users to find more information about assets when they're actively trading on the DEX, more so than just the hover info.

Cheers

**Comment by wmbutler** [comment]
Would be helpful as a favorites tab to show currencies you hold. Will keep this on the books.

**Comment by svk31** [comment]
Don't we already have this? These are links to the respective asset pages:

![image](https://user-images.githubusercontent.com/6890015/31268841-62d16720-aa7e-11e7-91ae-cedacb065e3a.png)

**Comment by wmbutler** [comment]
Yes, we do. Closing.
