### ISSUE TITLE
Request some menu change

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#1692]
![2](https://user-images.githubusercontent.com/34892308/42635031-770ee968-8617-11e8-898b-7ed7c8e8bec0.png)
Some advices of change please check the picture.

**Comment by froooze** [comment]
Adding extra words doesn't help the reading or getting easier.

**Comment by shulthz** [comment]
yes, but more easier understand than now.

**Comment by startailcoon** [comment]
Thank you for your feedback. Many of the changes you've highlighted are legacy items and will be removed later on.

- Send (legacy), changing to classic makes nothing more clear.
- Send will be the default, no need to change that
- Changing Deposit to Gateway is more confusing to new users
- Changing Withdraw to Bridge is more confusing to new users
- Deposit (beta) and Wirhdraw (beta) will be default and renamed later.
