### ISSUE TITLE
[3] Create debug report for users

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1696]
**Is your feature request related to a problem? Please describe.**
Users are having a hard time reporting found bugs that are not perfectly visible, e.g. report console log

**Describe the solution you'd like**
Add a button in the UI somewhere that allows creating an error report that is copy and pastable.

What could be included in such a button?
- calls to local storage
- console log
- remote calls
- optional: account name, OS and browser

**Comment by wmbutler** [comment]
Could potentially post these contents directly to a github issue...

**Comment by abitmore** [comment]
Just a note, please avoid including private keys in the report.

**Comment by grctest** [comment]
Sort of on topic, Google has a 'send feedback' button which shows the following prompt:

![image](https://user-images.githubusercontent.com/15861527/43676385-4d454856-97e8-11e8-9bf8-ed11cd49ffe4.png)

Perhaps the above wouldn't be suitable for raising github issues, and it may result in customer support requests instead of bug reports, but something similar to the above which sent the feedback to a helpdesk could help us identify any annoyances users are having (without the user requiring a github account)?

**Comment by sschiessl-bcp** [comment]
Agreed, i would not want automatic GitHub issue generation. But when supporting someone a report coming from that button will help enourmously

**Comment by wmbutler** [comment]
So maybe an element in the Help area that stores the important info so we can ask users to copy and paste it into a github issue.

**Comment by yurastich** [comment]
We have chosen the following method for catching console.log, console.warn, console.info, console.error - https://stackoverflow.com/questions/19846078/how-to-read-from-chromes-console-in-javascript 
Also, the unsuccessful requests are caught using the React method  - componentWillCatch.

We keep 20 last records in the local.storage and use them for the further actions. The records are updated automatically: when the new error is received, it is recorded to the first place and all records move 1 step forward, the last (oldest) record from the list is deleted).
When we click the ‘Copy errors’ button in the modal window, the data from the local.storage is copied to the clipboard.

For the screenshots the following approach was chosen: we take a screenshot of the window content using canvas https://html2canvas.hertzen.com/. It returns data in the base64 format. After that we convert the base64 format to pdf-document using the following library https://parall.ax/products/jspdf. The pdf-file is automatically uploaded to the user’s computer.

**Comment by abitmore** [comment]
I noticed there was a new comment deleted but I'm not sure why. Anyway, please keep in mind that we should avoid including private keys in the report (I guess there are risks when uploading `local.storage` and etc).

**Comment by sschiessl-bcp** [comment]
The capturing of the log was trickier than expected and required extensive trial and error. I want to present the current state and ask for feedback before more time is spent (so far .

Currently sitting in https://github.com/blockchainprojects/bitshares-ui/tree/1696_DebugReport

Report button in Footer:
![image](https://user-images.githubusercontent.com/33128181/46858637-01cde400-ce0c-11e8-8e90-1ffb25315585.png)

Report Modal:

When opened (could use styling)
![image](https://user-images.githubusercontent.com/33128181/46858863-90426580-ce0c-11e8-932b-e05af82676db.png)

Cick on Show Log (this displays raw data right now and could be formatted to reflect coloring of actual log)
![image](https://user-images.githubusercontent.com/33128181/46858747-4a859d00-ce0c-11e8-97dd-2f070e21581a.png)

Click on Show Screenshot
![image](https://user-images.githubusercontent.com/33128181/46858728-39d52700-ce0c-11e8-80f5-72266579e0ed.png)

There is a bug with the menu in the Screenshot capturing, also I am thinking a private capture that blurs the account name could be useful.

What are your thoughts?

**Comment by clockworkgr** [comment]
Does this catch browser errors (the red ones, uncaught exceptions and so on) as well?

**Comment by sschiessl-bcp** [comment]
Yes, a general error handling (global catch unhandled (with some limitatations)) is also introduced.

I want to create an error status page next (already in the pipeline, but dependent on this issue) that will replace the "white screen of death" :)

**Comment by clockworkgr** [comment]
Using window.onerror?

**Comment by sschiessl-bcp** [comment]
@startailcoon @wmbutler Any other thoughts / comments?

**Comment by wmbutler** [comment]
Looks good to me.

**Comment by sschiessl-bcp** [comment]
Hours spent see PR
