### ISSUE TITLE
[5][gibbsfromncis] Exchange: Set Expiration time for orders

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#17]
_From @valzav on June 23, 2015 18:52_

_Copied from original issue: cryptonomex/graphene-ui#6_

**Comment by fractalnode** [comment]
or Market Order

**Comment by wmbutler** [comment]
Most of the time here is for integrating a calendar widget and troubleshooting everything related to this control.

**Comment by gibbsfromncis** [comment]
@wmbutler Where do you think it should be placed? On the confirmation window (We can make it like Propose - add switch `custom expiration` and if user turns it on I'll display input with date and user be able to change it):
<img width="522" alt="screenshot 2018-02-05 00 18 17" src="https://user-images.githubusercontent.com/35899973/35783591-218d2f06-0a0a-11e8-935a-bd9c4acc7a4f.png">

or Buy/Sell order forms (it requires new field and may be not good to load this forms by not so useful field)? 

<img width="664" alt="screenshot 2018-02-05 00 15 52" src="https://user-images.githubusercontent.com/35899973/35783588-17e5c1f2-0a0a-11e8-99b6-7b7fa930abde.png">

**Comment by wmbutler** [comment]
I think it will need to be a calendar picker on the BUY/SELL controls that gets reflected on the confirmation screen.

**Comment by gibbsfromncis** [comment]
@wmbutler assign to me.

**Comment by wmbutler** [comment]
@ahdigital UX might be helpful here so @gibbsfromncis can just follow your blueprint.

**Comment by ahdigital** [comment]
I'd be tempted to put it on the modal (I have a nice idea to display it) because:

- Space is at a premium on the order form
- It adds another layer of complexity for less experienced traders

**Comment by gibbsfromncis** [comment]
@ahdigital  It's hard to put it on the Modal because on this step (when modal displayed) transaction already created. And on modal window user when user click on approve button he "sign" it instead of create it.

**Comment by ahdigital** [comment]
I see. Not in the modal then!

**Comment by gibbsfromncis** [comment]
@ahdigital do you any ideas how to present it except adding new `Expiration` field like this:

<img width="847" alt="screenshot 2018-02-26 23 43 28" src="https://user-images.githubusercontent.com/35899973/36947948-59595282-1fd3-11e8-96a8-00aec93de603.png">

**Comment by ahdigital** [comment]
Yeah sure. I can post an example in the morning UK time.

**Comment by gibbsfromncis** [comment]
@ahdigital nice! Thank you!

**Comment by abitmore** [comment]
@gibbsfromncis that looks not so good. Perhaps better use a drop down with 1 minute, 5 minute, 1 hour, 1 day and etc listed, if going this way, it's best if the list is configurable in settings, with some well-picked values as default.

**Comment by gibbsfromncis** [comment]
@abitmore 100% agree. I suppose it should be a dropdown with the following values:
- 1 minute
- 5 minutes
- 1 hour
- 3 hours
- 1 day
- Custom Time (an ability to select specific date/time)

But I don't think it's good to make this small feature so complicated. Lets go by simple way like just one dropdown and if after release a lot of users will ask us to make it configurable - we will do it.

**Comment by abitmore** [comment]
Please pick a good default value. 1 day is perhaps too short. Current default is 15 years or so.

**Comment by ahdigital** [comment]
@gibbsfromncis I was thinking something like the below example. It doesn't interrupt the amounts/totals inputs so much and acts as more of an optional step for those who want it. Putting it within the main form makes it feel like customizing the expiration might affect the total price.

I added a drop down inside the date/time picker to show how we could include preset times per @abitmore suggestion.

![image](https://user-images.githubusercontent.com/3088454/36963486-52fe7016-204b-11e8-8ed0-10400fb28b45.png)

**Comment by gibbsfromncis** [comment]
PR: #1309

**Comment by wmbutler** [comment]
@gibbsfromncis would you mind posting a licecap of this in action? You've been busy!!!

**Comment by gibbsfromncis** [comment]
@wmbutler yes sure

![ezgif com-optimize 1](https://user-images.githubusercontent.com/35899973/37415299-6d1544e0-27ab-11e8-8a4b-87d418f4badf.gif)

**Comment by wmbutler** [comment]
Really elegant solution. Nicely done!

**Comment by gibbsfromncis** [comment]
@wmbutler actually timepicker looks like I shit. I've to spent few hours to fix it's bugs. I'll replace it for Ant timepicker as soon we integrate ant.

**Comment by CryptoKong** [comment]
Hi guys, any chance we can get the default setting set to a maximum or no expirery as auto removing orders after 30 days will lower liquidity. I think its a good feature i can certainly see the benefits but the default setting should be set to max. :)

**Comment by tbone-bts** [comment]
Yes, the expiration drop-down needs a "Never" option and that should be the default since non-expiring orders make the most sense, for the reason stated by @CryptoKong, among others.  

Also, unless you have a **very** good reason to do otherwise, it's always a good rule of thumb to maintain the original default behavior when adding options for a setting that wasn't previously user-configurable...especially when such an unexpected change could actually cost someone money.

P.S.  The calendar is getting cut off when the order form is near the bottom of the screen:

![order_expiration_ui](https://user-images.githubusercontent.com/15830348/37510479-9072673e-28d1-11e8-8935-eba4293e5057.JPG)

**Comment by gibbsfromncis** [comment]
@CryptoKong @tbone-bts thanks guys for your feedback. I've created issue with changes you ask: #1331 

Is it OK if "Never" option will be 10 years?

**Comment by abitmore** [comment]
@tbone-bts @CryptoKong for overall performance, a limitation on expiration will be enforced in bitshares-core sooner or later. In fact, we can't afford that everyone puts thousands if not millions of never-expire and never-fill orders in the system. On UI, we should encourage people to set an expiration that is not too far away. For better UX, perhaps every account can have 10 orders or so that have longer expiration but certainly not all, although it's a bit too complicated.

**Comment by abitmore** [comment]
Even this: orders with longer expiration should pay higher fee.

**Comment by abitmore** [comment]
@CryptoKong you can use the "specific" time, I think it will remember your last input?

**Comment by gibbsfromncis** [comment]
@abitmore actually it doesn't but I suppose it's nice idea

**Comment by wmbutler** [comment]
For modifications, open this as a separate issue. This one is closed.

**Comment by gibbsfromncis** [comment]
This is issue for future discussions https://github.com/bitshares/bitshares-ui/issues/1331
