### ISSUE TITLE
Advanced ping strategy on application init

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1701]
At a fresh start or after every 5th connection attempt the UI is pinging all nodes. This issue is to refine the initial ping strategy.

**Current behavior**
It pings in a way that looses half of the nodes depending on their order in apiConfig. The ping seems also inaccurate due to the sheer amount of connection attempts in a very short period of time.

**Suggested behavior**
Ping all nodes subsequently which allows a more accurate latency evaluation, at the cost of increasing the overall ping time. When the user starts the app he just wants to have a connection, thus pinging is done until one is found with less than Xms (or any other value) latency, then the pinging is stopped and establishing a connection is attempted. If any previous latency results exist, the pinging is done that order to speedup the process, the user can still do manual ping in the settings overview. If no node with Xms or less can be found it is still pinging all the nodes just like before. Additionally, a more precise feedback on the pinging process is presented to the user.

Summary:
- fresh start: ping nodes as ordered in apiConfig until one with less than Xms is found
- later start: reping nodes ordered according to their latency until one with less than Xms is found

Suggestion: X = 200

**Comment by svk31** [comment]
What happens if no nodes are found with ping below 200? That seems quite low to me.

**Comment by sschiessl-bcp** [comment]
> What happens if no nodes are found with ping below 200? That seems quite low to me.

I included it in the initial description. Short answer: Then all nodes a pinged like before. The number 200ms was chosen arbitrarily

**Comment by svk31** [comment]
@sschiessl-bcp Shouldn't this have a time estimate?

**Comment by MarkoPaasila** [comment]
> fresh start: ping nodes as ordered in apiConfig until one with less than Xms is found

What determines this order? Is it sorted earlier by ping time?

**Comment by sschiessl-bcp** [comment]
@MarkoPaasila The initial order is determined by https://github.com/bitshares/bitshares-ui/blob/269506c81fcce7a78a499c548a7218083ff84a86/app/api/apiConfig.js#L70 The order is arbitrary in there.

Afterwards it is sorted by former ping when re-pinging.

**Comment by sschiessl-bcp** [comment]
@svk31 I don't have authority to assign hours (at least no one told me I am allowed to do that :) )

**Comment by svk31** [comment]
Hehe well just tell us your estimate of how long it took you and we'll add that, assuming it's reasonable ofc :)

**Comment by clockworkgr** [comment]
![image](https://user-images.githubusercontent.com/6826762/42990024-2afcf79c-8c0a-11e8-8477-849f3f8911df.png)


1 million hours :)
