### ISSUE TITLE
Configure an asset's user whitelist/blacklist from within UI

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1703]
**Is your feature request related to a problem? Please describe.**

Cannot configure an asset's user whitelist|blacklist from within the UI.

**Describe the solution you'd like**

Enable configuring an asset's user whitelist|blacklist from within the UI (when configured as an authority).

**Describe alternatives you've considered**

Configure an asset's user whitelist|blacklist via python script.

**Additional context**
Trying to test asset user whitelist functionality, hit a roadblock due to python script requirement.

**Comment by svk31** [comment]
Don't have a computer nearby but pretty sure this already exists. For assets you set a whitelisting authority (an account) which in turn sets a whitelist of other accounts.

**Comment by grctest** [comment]
Ah, so you add an user to the whitelist authority, then the user's whitelist page is enforced on the asset?

It does look like it's existing functionality in the UI then. A little description that this is how the whitelist system works in the asset update whitelist authorities page would be neat 👍
