### ISSUE TITLE
[0.25] Light theme 'Explore -> Assets' page shows white 'Exchange' text on white row background

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1704]
**Describe the bug**
When using the light theme, the assets explore page has 'Exchange' buttons with white text on white background, thus it appears blank.

**To Reproduce**
1. Enable light theme
2. Navigate to asset explore page
3. View 'exchange' button column
4. See white text on white background within button

**Expected behavior**
Able to read button text.

**Screenshots**

![image](https://user-images.githubusercontent.com/15861527/42843649-b029734a-8a08-11e8-8770-9acbe153e88c.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version Current

**Additional context**
You can assume the contents of the button (given the surrounding button text contents) & you can also highlight the text.

**Comment by startailcoon** [comment]
There are a few theme issues since a while back, always happy to see these come in to help everyone. Nice catch.

Fixed

![bild](https://user-images.githubusercontent.com/12114550/43047780-2302c70e-8ddd-11e8-9a67-ae2378f2f535.png)
