### ISSUE TITLE
[10] Maintaining translation files

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1705]
Our language files are horribly out of sync. I am currently experimenting with Translation Management Systems that provide a web frontend for visualized editing and maintaining the files.

Currently looking good: Weblate

Thoughts?

**Comment by shulthz** [comment]
support

**Comment by HarukaMa** [comment]
Out-of-sync language files are indeed annoying, as if the keys are not in the same order it's quite impossible to diff them.

Did once on SimpChinese and manually rearranged all the keys, and gave up since then...

**Comment by sschiessl-bcp** [comment]
Weblate was working fine, but more manual work needed.

Community pointed me to transifex.com, which provides free services for OpenSource project and seems more sophisticated / better maintained than Weblate. BitShares Organization existed there so I needed to get admin access. That is now done and I will continue to refresh the translation files once my personal account has write permission.

**Comment by sschiessl-bcp** [comment]
Current master now setup:

https://www.transifex.com/bitshares/bitshares-ui-1/dashboard/

**Comment by svk31** [comment]
Cool. Not sure if transifex will also do this for you, but thought I'd make sure you know that there's a script in bitshares-ui you can run that uses locale-en.json as a template and fills all the other files with any keys they're missing. That script also sorts all keys alphabetically, and can be very nice to run whenever you add new keys.

`npm run fix-locale-files`

**Comment by startailcoon** [comment]
@svk31 running that script today gave me a locale file with many moved keys and changes. Almost all of the file changed :D 

@sschiessl-bcp how can we handle translations easy via transifex? I assume we need to push updates to the site as well as pulling them when we make new builds to catch new translations. Can this be done automatically or is a manual work that someone needs to maintain?

**Comment by sschiessl-bcp** [comment]
Transifex is not for maintaing the files when adding new keys. It is to easily track translation status of the files.

In that matter the script that automatically fills in the english translation is actually hindering the progress. Transifex thinks that the translation is done then. Can the script easily be altered that it removes english duplicates in other languages (so I can run it before uploading to transifex)?

**Comment by svk31** [comment]
Yea should be easy to look for identical strings in non-English files and then remove them.

**Comment by froooze** [comment]
Any information, how I can improve the German translation?

**Comment by sschiessl-bcp** [comment]
Apologies. I want to setup the transifex account with the latest translation files while removing the english duplicates to see the actual missing entries.

The plan is to distribute the points of this issue mostly for the translation work then.

**Comment by froooze** [comment]
Can I work on the German translation?

**Comment by sschiessl-bcp** [comment]
Added a new script that removes english duplicates.

Transifex is now up-to-date, and translation files can be streamlined
https://www.transifex.com/bitshares/bitshares-ui-1/

@froooze german is yours

**Comment by clockworkgr** [comment]
reserving greek

whats the time estimate per language?

**Comment by sschiessl-bcp** [comment]
@startailcoon @wmbutler 

Do we want to have new languages? I would have someone interested in dutch.

**Comment by sschiessl-bcp** [comment]
Assignments:
- Management [2]: @sschiessl-bcp 
- German: @froooze 
- Russian: @ruslansalikhov 

Requests for new langauges will be evaluated.

**Comment by ragnaroklow** [comment]
I translated a few things in french.

**Comment by deceneus** [comment]
Romanian, if there's any interest for it...
I'm @steemmillionaire in steem.

**Comment by AboShanab** [comment]
Can I take Arabic language?

**Comment by froooze** [comment]
@sschiessl-bcp:
There are two German versions "du" and "sie" which is preferred or should I make two different versions?

**Comment by p145085** [comment]
I can help translating to Swedish.

**Comment by fractalnode** [comment]
I can do a Polish translation, I have about 5% already translated

**Comment by sschiessl-bcp** [comment]
> There are two German versions "du" and "sie", which is preferred or should I make two different versions?
Some Germans prefer the "du" verion some the "sie".

If most of the already done translations use "du" or "sie", stick with that one. If it's a complete mess right now, please streamline to "sie".

**Comment by jademont** [comment]
I can help translating English into Chinese language.

**Comment by sschiessl-bcp** [comment]
@spanishtranslator @froooze @jademont 
Please report when you are done.

**Comment by spanishtranslator** [comment]
> 
> 
> @spanishtranslator @froooze @jademont
> Please report when you are done.

60 Left

**Comment by spanishtranslator** [comment]
> 
> 
> > @spanishtranslator @froooze @jademont
> > Please report when you are done.
> 
> 60 Left

Done. My Bitshares user: newtechblog-bts

**Comment by spanishtranslator** [comment]
> 
> 
> > > @spanishtranslator @froooze @jademont
> > > Please report when you are done.
> > 
> > 
> > 60 Left
> 
> Done. My Bitshares user: newtechblog-bts

thanks @sschiessl-bcp

**Comment by sschiessl-bcp** [comment]
@froooze Please report, or can I re-assign?

**Comment by froooze** [comment]
Feed didn't not come up in my UI, had to search in WLS. I am half trough the translation, had some problems to lack of documentation. Translation will be finished next week. Progress can be seen at transifex: https://www.transifex.com/bitshares/bitshares-ui-1/viewstrings/#de/locale-enjson/150475728

**Comment by froooze** [comment]
Update: Translation is finished now and can be reviewed!

**Comment by sschiessl-bcp** [comment]
> Update: translated new string (Russian)

Much appreciated

**Comment by sschiessl-bcp** [comment]
> Update: Translation is finished now and can be reviewed!

@froooze Where do I find the completed?
![image](https://user-images.githubusercontent.com/33128181/51663159-4f82ec80-1fb6-11e9-942c-bba35b2f66f6.png)

Is there a review necessary somewhere within transifex? I normally get notifications once resources are completed, e.g. for russian here
![image](https://user-images.githubusercontent.com/33128181/51663283-953fb500-1fb6-11e9-8761-424b8fe81e4b.png)

**Comment by froooze** [comment]
@sschiessl-bcp:
I think this is a UI bug. Translation is 100% finished. If there are still untranslated strings, feel free to ask again.

**Comment by sschiessl-bcp** [comment]
@jademont still interested in updating chinese version? I ll put the new locale files up in transifex with next staging release

**Comment by clockworkgr** [comment]
I don't like the format of tracking translation work in comments. Especially when individual issues exist.

Can we add the contact details about translations and translating guide to the readme instead?

**Comment by sschiessl-bcp** [comment]
Closing this issue, my management/language review time is depleted. Should move to ReadMe now like clockwork said.

Russian, german and spanish have been updated.
