### ISSUE TITLE
[0.5] Portfolio table's MPA settle flag assumes backing is BTS (Typo)

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#1707]
**Describe the bug**
Within the dashboard (portfolio) page, the table rows with MPA assets have a settle flag which states that the MPA can be settled for BTS, however it does not replace the 'BTS' text with the MPA's actual backing asset.

**To Reproduce**
1. Go to dashboard portfolio page.
2. Have an entry for any MPA.
3. Hover over the settle MPA flat
4. See text error

**Expected behavior**
The tooltip should inform the user of the actual backing asset they will receive.

**Screenshots**

![image](https://user-images.githubusercontent.com/15861527/42889642-d7642e92-8aa2-11e8-8584-311bd3a9e215.png)

NOTE: Actual backing asset was 'TEST', not BTS.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Latest

**Additional context**
Only a minor text error, however it could mislead MPA holders of the real contents of held MPA.

**Comment by startailcoon** [comment]
The UI had no translation for another backing asset, and BTS was a fixed value.

bitXCD is backed by bitUSD and is properly displayed now.

![bitshares-backingassetsettle](https://user-images.githubusercontent.com/12114550/43047599-f9d6ce96-8dd9-11e8-939e-77075638e3af.gif)
