### ISSUE TITLE
Filter out settlement fills from chart data.

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/bitshares-ui#1711]
If I've followed a conversation in telegram correctly today, it appears that market history includes both trading fills AND settlement fills (which are performed at a percentage premium compared to feed price).

This leads to occasional spikes in the chart that do not correspond to trading activity in the sense that noone actually placed an order to buy or sell the orderbook up to settlement_premium_percentage above current price.

This can be confusing for traders so I suggest we filter settlement data out of the dataset the charts use.

**Comment by abitmore** [comment]
Screenshot:
![image](https://user-images.githubusercontent.com/9946777/43017220-9cab6400-8c55-11e8-8f2f-e1e26112a852.png)

On the other hand, force settlement fills are real volume as well as real prices, they do show in "market trades" panel. Also there is a "settle orders" panel in the page. So whether to filter them out is debatable.

**Comment by svk31** [comment]
This is not something that can be done by the GUI since we only have ohlc data, if you still want this to happen it should be done in bitshares-core.
