### ISSUE TITLE
[2] Private login feature

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1724]
**Is your feature request related to a problem? Please describe.**
When the user logs in via cloud login, the user's account name are retained even after "logging out", together with other user related values (mostly currentAccount in localStorage).

**Describe the solution you'd like**
Current behavior should not be changed in its defaults. Add a checkbox to the login modal "Remember my account(s)", which is checked per default.

*Cloud login*
No UI change necessary

*Local wallet*
UI change: Unchecking the checkbox removes all locally stored bin's from display and requires the user to provide a bin file to login.

*What the user expects*
When the user unchecks "Remember my account(s)", it is expected that no information is retained after
- user simply closes the browser
- UI crashes
- user logs out
- user logs in with different account

To achieve that (especially the first two cases) nothing can be stored in local storage or wallet database.

**How can that be achieved?**
I propose that we implement an encapsulation using a Factory to the local storage and wallet database that 
- uses the actual local storage and database if the checkbox "Remember my account(s)" is checked
- redirects to an in-RAM storage solution via a Singleton if "Remember my account(s)" is not checked 

**Additional context**
User might login on a public computer and wants any trails of his login removed afterwards. 

*Related issues*
#1360

**Comment by clockworkgr** [comment]
+5%

**Comment by wmbutler** [comment]
As long as this is restricted to cloud login and is tested thoroughly, this seems fine. Seems a bit redundant since a user could just use incognito.

**Comment by sschiessl-bcp** [comment]
Icognito implementations may vary across browsers (mobile included). This offers a reliable way for the user, additionally to any icognito features. 

What is the reason you want to exclude Local Wallet?

**Comment by wmbutler** [comment]
I wasn't suggesting we exclude the local wallet. I was referring to the cloud login (using a username and password rather than a stored file).

**Comment by sschiessl-bcp** [comment]
From how I understand you would NOT want a private login feature for local wallet, is that correct?

**Comment by sschiessl-bcp** [comment]
PR created, private login only for cloud login.
