### ISSUE TITLE
Create worker proposal via the GUI

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#173]
Hey,

I feel that we would have more worker proposal attempts if it was possible for users to create a worker proposal via the GUI rather than via the CLI/Console.

Would it be possible to add a form for creating a worker proposal?

Cheers.

**Comment by svk31** [comment]
I did so a few days ago: https://github.com/bitshares/bitshares-ui/commit/ea8b14494ccd1bc2f09a83a143a0624869959bfb
