### ISSUE TITLE
Tradeview chart slow processing in CEX exchange

### ISSUE THREAD

**Issue by Tamizhanstalin** [bitshares/bitshares-ui#1731]
I am trying to implement tradingview chart using UDF method on CodeIgniter with PHP 5.6 in my website. I am trying to show records of six months for the following intervals: 1min view, 3min, 5min, 1day, 1week, 1month views. It's working but it's too slow, like the whole chart display takes more than 30sec.

Here I am using the api-btc-alpha.com for getting the result and display using JSON. How can I boost the chart loading speed like the whole graph bars shows up in 2 to 4sec ?

**Comment by startailcoon** [comment]
I'm not sure if we would be able to provide a good solution to your question here. @svk31 is the one that implemented the new charts in our app and could perhaps provide some insight on problem you have.

Otherwise I'd advise you to use the support from the Trading View website.

**Comment by svk31** [comment]
No idea tbh; I never had to do anything to boost loading speeds.

**Comment by Tamizhanstalin** [comment]
ok

**Comment by Tamizhanstalin** [comment]
@svk31 ,  It is possible to create a DEX using the bitshare-ui , because i had downloaded from https://github.com/bitshares/bitshares-ui and it working on localhost, If possible kindly guide me i am on correct track if yes means what i do next

**Comment by svk31** [comment]
I'm not sure what you're asking for

**Comment by Tamizhanstalin** [comment]
I have installed bitshare-ui in my localhost i need to change my coin instaed of BTS that i asking, Thanx
