### ISSUE TITLE
How to disable or delete tradingview?

### ISSUE THREAD

**Issue by DATSEC** [bitshares/bitshares-ui#1732]
I'm interested in the old indicator, can it be returned without consequences?

![Image alt](https://i.ytimg.com/vi/2U3QTfFkw2A/maxresdefault.jpg)

**Comment by startailcoon** [comment]
Is there some data you think are missing in the new Trading View graphs? What are your specific reason to view the old indicators? 

@svk31, what is the impact of retaining the old graphs for backwards compatibility?

**Comment by DATSEC** [comment]
@startailcoon The old graph is better than api it can be improved and changed.
I believe that tradingview has monopolized the technology and each exchange uses their api

**Comment by wmbutler** [comment]
We are moving forward with tradingview. Feel free to fork an old version if you want the old charts.
