### ISSUE TITLE
[0.5] TradingView chart hangs when switching timeframes

### ISSUE THREAD

**Issue by bitsniper1** [bitshares/bitshares-ui#1737]
Using local wallet when trading on exchange view and change the timeframe, I get never ending "buffering dots array" have to switch to dashboard view and switch back to exchange view then I can use the newly selected timeframe. This only started after this most recent update.

![image](https://user-images.githubusercontent.com/9946777/43424214-e15432b6-944e-11e8-8fd6-36f88b4549e6.png)

**Comment by wmbutler** [comment]
Can you manually switch nodes and make sure you aren't on a VPN and let us know if the problem persists?

**Comment by svk31** [comment]
I think this is caused by using an API node that doesn't support grouped orders, the data fetching fails in that case because another api call fails.
