### ISSUE TITLE
[2] Estimated blocktime is incorrect

### ISSUE THREAD

**Issue by nowcoin-official** [bitshares/bitshares-ui#1738]
**Describe the bug**
If you check tx number 3b47eae38092807e4e9d2f38b7b49a4dd8944cc7 on open-explorer, then you will see the timestamp being different from what the BitShares Wallet Explorer is showing. Upon crosscheck with other explorers (cryptofresh, btsai) you can see that only the BitShares Wallet Explorer is showing a different timestamp, all explorers are showing the blockchain data correctly

**To Reproduce**
Check tx no 3b47eae38092807e4e9d2f38b7b49a4dd8944cc7 in open-explorer.io. See the timestamp. Then check the same in BitShares Wallet

**Expected behavior**
All explorers should show the correct timestamp

**Screenshots**
![screenshot_2018-07-30 https live nowcoingame com 1](https://user-images.githubusercontent.com/41942095/43443024-0a09f488-94a0-11e8-93ba-78135f0e67ef.png)
![screenshot_2018-07-30 tx 3b47eae3 bitshares block 29164383](https://user-images.githubusercontent.com/41942095/43443029-0d417734-94a0-11e8-9f0c-4778d5cfa09d.png)
![screenshot_2018-07-30 account 1 2 1043861 nowcoin-night-watch - bitshares blockchain explorer](https://user-images.githubusercontent.com/41942095/43443035-0f9b9e4c-94a0-11e8-922c-9e7a98c4b031.png)
![screenshot from 2018-07-30 11-12-38](https://user-images.githubusercontent.com/41942095/43443041-11dd04c0-94a0-11e8-8d1e-4898b85382b5.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint

**Comment by svk31** [comment]
No, the explorer timestamp is in UTC, the wallet timestamp is shown in your local time.

CEST = UTC + 2 hours.
02:51 UTC = 04:51 CEST

**Comment by nowcoin-official** [comment]
It is not about timezones. The explorers are all showing correct time of 2:51, while the Wallet is showing 2:52, which is different from the block timestamp.

**Comment by svk31** [comment]
Oh, I see what you mean now. The reason is that in the Activity view you're looking at the data we have does not include the actual timestamp of the operation, only the block number it happened, so we estimate the time based on the block number, the current block height and the time between blocks.

If you click the "Transfer" block it'll take you to the actual Explorer part of the wallet showing you the block, which has the correct date.

We could refactor the BlockTime component to actually fetch the block and display the correct time that way,  it's only done this way so we don't have to fetch full blocks all the time.

**Comment by nowcoin-official** [comment]
Okay, I leave it to you from there. Just noted, hope it was useful :)

**Comment by abitmore** [comment]
@svk31 just FYI there are database APIs to fetch block headers only rather than full blocks
* get_block_header
* get_block_header_batch

**Comment by svk31** [comment]
Proposed solution: refactor the BlockTime component to instead use an api call to get_block_header, and add in memory caching of block_header data to prevent calling it over and over again.

**Comment by sschiessl-bcp** [comment]
Another API call just for the time seems unnecessary.

I understand that the diplayed BlockTime is interpolated?

One could do a popup onHover that explains how the interpolation happens and onClick go to the block details, which shows the correct time.

**Comment by abitmore** [comment]
This won't be an issue after switched to ES.

In the meanwhile, best UX would be to store timestamps directly in the account history objects (modify core plugin).

By the way, what timestamps are being showed in "my trades" tab of exchange page?

**Comment by svk31** [comment]
Those are using the same component to interpolate the time, since only the block number is available.

**Comment by svk31** [comment]
Thanks, must have forgotten to assign myself.
