### ISSUE TITLE
[0.25] Disable new version available notification for release candidates

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#1748]
Notification of a new update appears under the newly installed 180808 version.
When clicked, it redirects to the latter version; https://bitshares.org/download/

1. Download and install 180808.
2. Note the version 180808 appears in the bottom left corner.
3. Note the highlighted update available below the version number 180808.
4. Click to update - redirects to https://bitshares.org/download/

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by startailcoon** [comment]
Perhaps it's better to direct the user to the github releases @svk31?

**Comment by svk31** [comment]
This is a release candidate,the notification won't go away until a final release is made.

**Comment by TechsUsInc** [comment]
Or add a new notification for RC builds - RC build - pending release. 
Disabling the notification for builds would remove any doubt or confusion though.
