### ISSUE TITLE
[.5] add additional Memo field description

### ISSUE THREAD

**Issue by btswolf** [bitshares/bitshares-ui#175]
Some users get confused with the Memo field.
Please change field description to something like:

Memo / Message / Description

**Comment by wmbutler** [comment]
Maybe a better approach would be a tooltip explaining what a memo is for.

**Comment by wmbutler** [comment]
Tooltip when hovering over word MEMO:

You may include any message in the memo field

**Comment by svk31** [comment]
Added some text to the tooltip: `You may include any message in the memo field. Memos are optional but generally required for transfers to exchanges.`
