### ISSUE TITLE
Withdrawal - GDEX

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#1750]
**Describe the bug**
(From both the local wallet and https://staging.bitshares.org)

With the account lock engaged, a user is able to read the GDEX deposit/withdrawal service agreement.
With the account lock engaged, a user is able to tick having read and agreed to the GDEX deposit/withdrawal service agreement without having to first unlock the account. Once accepted (account locked or unlocked), it is irreversibly implied as binding. The service agreement should always be visible, accessible, and tick-able for any deposit/withdrawal regardless of the first or millionth. The terms are easily forgotten between deposits/withdrawals. The service agreement should not be tick-able nor accessible at all unless the account is unlocked - attempting to do so while engaged should prompt a locked account warning.

Within the service contract, it firstly states that GDEX is a Singapore incorporated company named Obsideon Technology Co. PTE. LTD. 
Coinbase has an acquired exchange called GDAX, very recently renamed to Coinbase Pro.                         
( https://www.financemagnates.com/cryptocurrency/news/coinbase-replace-gdax-coinbase-pro-july/ )      
(https://pro.coinbase.com).
To avoid confusion and misconception, it should be boldly and clearly stated in both the service agreement (within one of those two empty reminder fields) and on the deposit/withdrawal page (under instructions) that GDEX is not the same or affiliated with GDAX or Coinbase and any assumed transaction will result in a loss.
The two bottom fields within the service agreement are void of any info.
(important reminder: and  we hereby remind you that: )

**Comment by startailcoon** [comment]
The mentioned service agreement is implemented by the GDEX Team and is nothing the Bitshares Reference Wallet have implemented. 

Any changes to the way GDEX handles their agreements to users should be pushed as an update by their official sources as PR. Additionally, any changes to their agreements, like mentioned names and possible confusion, should be handled by their respective sources as well. 

Ping @tianyekuo
