### ISSUE TITLE
[8] Improve the dashboard Featured/Starred Markets tables

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#1751]
**Is your feature request related to a problem? Please describe.**
The current tables display a lot of information but in a completely unsorted way with all kinds of markets jumbled together.

**Describe the solution you'd like**
The list of markets should be sortable by:
- [x] Volume
- [x] Price
- [x] 24hr change

The markets should be sorted by quote asset, similar to what's done in the Exchange page. Binance and Openledger are good examples.

- [x] Sort markets into quote asset tabs

Bonus tasks:

- [ ] Include some featured markets using sparkline charts similar to Binance and Openledger
- [ ] Include a News box like Openledger 

**Describe alternatives you've considered**

**Additional context**
Openledger:
![image](https://user-images.githubusercontent.com/6890015/43636113-766f1aae-9711-11e8-8132-655c87310b37.png)

Binance:

![image](https://user-images.githubusercontent.com/6890015/43636014-2dc1cf54-9711-11e8-85a5-2a6fdb63193a.png)

**Comment by sschiessl-bcp** [comment]
I am trying to figure out what changed here.

I see that `getFeaturedMarkets` is no longer used. Can you elaborate on the now implemented prosa way how they are created? Or even better, add in-code documentation for it please? :)

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/blob/1ee0ba3264abb63a3c06353e35731e80c7aee56d/app/components/Dashboard/DashboardPage.jsx#L62-L66

This creates incompatibilities with other gates, e.g. if in branding.js rudex.BTC would be defined.

**Comment by svk31** [comment]
Good catch.

The logic is basically the same as what's in MyMarkets of the exchange: instead of using an additional set of featured markets the dashboard now just displays all the markets defined in SettingsStore as defaultMarkets. Those are from getMyMarketsQuotes in branding. We also look for any gateway assets to use as quote assets, so for example the BTC tab also includes markets with OPEN.BTC, RUDEX.BTC etc.

Illiquid markets are filtered out, but like in MyMarkets I can add a toggle for that.

**Comment by sschiessl-bcp** [comment]
I really like the grouping feature, as mentioned in https://github.com/bitshares/bitshares-ui/issues/1803#issuecomment-416484040 I would suggest to refine the logic. 

If an actual symbol is given, treat it as only this symbol, no implicit grouping. If grouping is desired, symbol should have leading wildcard, e.g. '*BTC'

**Comment by svk31** [comment]
This has been live a while now, will leave out the bonus tasks and close it.
