### ISSUE TITLE
[1.5][nikandrovalex] White Theme Issues

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1753]
In asset details e.g.

![image](https://user-images.githubusercontent.com/33128181/43646102-3b2b269a-9734-11e8-869f-446f8a3eac2d.png)

and probably other places?

**Comment by svk31** [comment]
Please be a bit more specific. Are you talking about the tabs? Anything else?

**Comment by sschiessl-bcp** [comment]
Yes, the tabs. It's 36 degrees here, can't focus -_-

I will add screens if I find it in other places

**Comment by startailcoon** [comment]
@sschiessl-bcp I assume that it's the white theme you have found some issues with, and that it is the buttons for the asset details page. 

I've added an hour for searching trough CCS issues for the theme and address potential issues.

**Comment by startailcoon** [comment]
Going with a more unified color of buttons
# Light
![image](https://user-images.githubusercontent.com/12114550/44627948-7d94cf80-a937-11e8-826d-bcb9a4a20380.png)


# Dark
![image](https://user-images.githubusercontent.com/12114550/44627942-6bb32c80-a937-11e8-9d36-480847316c10.png)

**Comment by svk31** [comment]
Reverted because I don't think the blue background fits with the themes.

**Comment by startailcoon** [comment]
Fair enough. Needs some more discussion to find a good option to the current black ones.

**Comment by dot5enko** [comment]
@startailcoon tradingview chart is always dark, even in the white theme

**Comment by nikandrovalex** [comment]
Hi @startailcoon @wmbutler @dot5enko @svk31 . I think I understand what your problem is.

I suggest using the standard components https://ant.design/components/tabs/ I also used them for the Asset Creation & Edit Redesign task (https://github.com/bitshares/bitshares-ui/issues/1604) for example,  http://take.ms/YB1w2 

I added new design layouts to zeplin: https://app.zeplin.io/project/5b9ad751d8068c34a1715ad6/dashboard?seid=5bb53dc878dfe0a997a8f193 

You can also see them here:  https://sketch.cloud/s/Q1AgL/p/1753-white-theme-issues  

For the white theme, everything is clear. For a dark theme, I tried several options. My opinion is that you need to stop at this option http://take.ms/ApM3s

Thanks, waiting for feedback from you.

**Comment by startailcoon** [comment]
I like it

**Comment by wmbutler** [comment]
@nikandrovalex can you invite me to the project? wmbutler on zeplin. Thanks!

**Comment by wmbutler** [comment]
@nikandrovalex let me know about hours needed for the time spent. Looking really good and glad to have you on the team!

**Comment by nikandrovalex** [comment]
@wmbutler   Hi Bill. Thank you very much) I'm glad you liked it. I am also happy that I can help this project.

Already added you to Zeplin on bill@butler.net . I spent 1 hour and 20 minutes on this task. Each work on the project, I track in the Top-tracker. time can be seen in the screenshot http://take.ms/iiO4d . I can also send you an invitation to the Top-tracker to your email and you can see it yourself. (there are screenshots of my work table)

**Comment by startailcoon** [comment]
I agree we should use the Ant Tabs here, though, I'm unsure on how we style them the way @nikandrovalex does in his mockups. I will need some guidance by @gibbsfromncis on this.

**Comment by gibbsfromncis** [comment]
@startailcoon got it. We do not have this style of tabs in our style-guide. I created separate task for this #2015

@nikandrovalex Please provide 3 screens of tabs for each theme - Dark, Light and Midnight. I'm going to add them to our style-guide

**Comment by nikandrovalex** [comment]
@gibbsfromncis could you add another 2 hours to this task?

**Comment by gibbsfromncis** [comment]
@nikandrovalex you have an additional task for this - https://github.com/bitshares/bitshares-ui/issues/2015

**Comment by nikandrovalex** [comment]
@gibbsfromncis @startailcoon  Hello guys. Can I do something else for this task? Or is it complete?

**Comment by wmbutler** [comment]
@startailcoon your discretion  to close this.

**Comment by sschiessl-bcp** [comment]
UX is complete. Needs implementation.

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp @startailcoon the task is only to update tabs on Asset page?

**Comment by gibbsfromncis** [comment]
@startailcoon I will replace these tabs in scope of #1936 when work on all tabs replacement. I'm closing this task as you approved that UX is fine

**Comment by Jackcameback** [comment]
@nikandrovalex could you please leave your bitshares address?

**Comment by sschiessl-bcp** [comment]
> @startailcoon I will replace these tabs in scope of #1936 when work on all tabs replacement. I'm closing this task as you approved that UX is fine

Those replacement tasks would be good for our newcomers to show that the can work accurately while still seeing lots of places in the UI. What do you think of putting a generic "How To" in the issue and release #1936 ? I think your time is better suited for the style-guide or deeper going CSS issues
