### ISSUE TITLE
[4] Handle proposals related to phishing accounts 

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1755]
**Is your feature request related to a problem? Please describe.**
There are phishing attempts using proposals.
![image](https://user-images.githubusercontent.com/9946777/43668552-de3e26ea-977d-11e8-9f49-224040ece503.png)

Before a proposal is expired, it will be shown in the "proposals" tab.

**Describe the solution you'd like**
* Warn the user if the proposal is related to a phishing account
  * if proposed by a user in black list
  * if one of relevant accounts in the proposal is in black list
* Automatically hide phishing proposals
  * a button to show hidden proposals
* user can hide proposals manually

**Describe alternatives you've considered**

**Additional context**
If the account is a multi-sig account, it's hard to reject the proposal directly even if #1673 is implemented. The warning introduced in this issue can help normal users to reject phishing proposals when #1673 is implemented.

**Comment by startailcoon** [comment]
We should try to implement #1673, to make it possible to reject invalid proposals. I can see other accounts get these types of proposals as well any day. The committee-trade account is well knowledge people, but smaller accounts and new users may fall into this.

Based on sources for phishing accounts, as mentioned by #1706, we should update the UI to highlight these accounts more prominent.

## We should consider
- [ ] Hide scam proposals to part from real, visible on request
- [ ] Color and/or Text Highlight scam/blacklisted accounts
- [ ] However information details for scam/blacklisted accounts

Accounts should be considered when in:
- UI scam lists
- User Blacklisted accounts

An account has to be LTM to be able to add an account to the on-chain blacklist.

**Comment by startailcoon** [comment]
Nice work.

Only thing I'm reacting on is the "Possible Scam" notification. If we go by the style guide we should probably pick yellow notification box with an icon.

![image](https://user-images.githubusercontent.com/12114550/48664092-c4f3ad80-ea99-11e8-8b9a-5edd094fb1d0.png)

**Comment by sschiessl-bcp** [comment]
> Only thing I'm reacting on is the "Possible Scam" notification. If we go by the style guide we should probably pick yellow notification box with an icon.

Agreed, but I'd rather leave that to a style-guide'ify issue
