### ISSUE TITLE
[2] Add candlesticks and zoom functionality

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#176]
Additionally, can we add 15min, 30min, 4h, and 6h (maybe 12h too? candlestick options added to the chart? With only the options of 5m and 1h on the low end, the utility of 2d and 4d charts is rather lacking. Even better would be to make Zooms and Candlesticks configurable in settings so users can select which options to show.

**Comment by Ashaman-** [comment]
The price that trades for these tiny amounts (really all trades) execute at should be supplied to the chart before the transaction fee is subtracted. Right now it is done after.

**Comment by wmbutler** [comment]
This seems easy enough. We have the room for it.

![screen shot 2017-09-21 at 12 49 37 am](https://user-images.githubusercontent.com/1254810/30680704-c2aa1ba2-9e66-11e7-80a5-ab4afe8d384a.png)

**Comment by wmbutler** [comment]
Let's also add some logical ties between Zoom and Candlesticks. So, when a user clicks on Zoom level, We pick the corresponding zoom level for them.


 Zoom | Candle 
 --- | --- 
6h | 5m
2d | 30m
4d | 1h
1w | 4h
2w | 6h
1m | 12h
3m | 1d

**Comment by svk31** [comment]
Available candlesticks depend on what is available from the API server. They're called `buckets` in the witness_node config and each API provider sets their own, the GUI dynamically shows whatever buckets are available from the server.

**Comment by wmbutler** [comment]
Good to know. Is this something we would present to core?

**Comment by svk31** [comment]
What would you present to them? It's a RAM issue so each node operator should be able to determine how many buckets he wants to run, although I suppose some sensible defaults could be added.

**Comment by wmbutler** [comment]
Exactly, just thinking about sensible defaults, but this is fairly low priority considering the complexity.
