### ISSUE TITLE
[.5] White screen when downloading an exchange

### ISSUE THREAD

**Issue by DATSEC** [bitshares/bitshares-ui#1761]
You need to add a preload
![Image alt](https://i.imgur.com/3SWDPLO.jpg)

**Comment by sschiessl-bcp** [comment]
Could you provide browser console output please? What is your OS / browser?

It works with current release, just not with staging?

**Comment by svk31** [comment]
This isn't the way to do it, you have to override it in the custom css files. I'm making a commit for that, but at least on my end it's still flashing white a little bit even after applying the loading-indicator background override..
