### ISSUE TITLE
Allowing user-chosen passwords for the Account Model is dangerous

### ISSUE THREAD

**Issue by arhag** [bitshares/bitshares-ui#177]
The BitShares GUI is meant to be used by regular users. Regular users cannot be trusted to do the right thing when it comes to choosing high-entropy passwords. Learn from the [mistakes](https://steemit.com/steem/@robinhood/offline-attack-on-steem-user-credentials) of [Steemit](https://steemit.com/steemit/@steemitblog/steemit-to-update-password-policy). If you want to bring aboard mainstream users, they will get hacked if you allow them to choose their own password.

The user-friendly GUI must force them to accept a machine-generated password. No exceptions. If advanced users want to specify their own password, they should just use the CLI.

**Comment by abitmore** [comment]
How about force existed users to change password to a generated one (if not done already)?

**Comment by testlump** [comment]
I wanted to add to this. You should consider disabling Account mode entirely. Not only is there a risk of malicious third parties attempting to deceive a user into exposing their password, it's also the only protection layer on the account. Every exchange these days offers at the very least two factor authentication. A single password as the first and last line of defence - no matter how long and complex - exposes the user to a number of attack vectors (social engineering, malware etc). Unless there is a two-factor solution that can be made mandatory for this mode, it seems like a huge risk for a relatively small usability gain.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
An average user is not going to keep a wallet file around and almost every horror story involved losing that file. 

Account model is by far the best and most accessible solution, although I think passwords should be an automatically generated lets say 24 word mnemonic seed like other blockchains use, and it can generate entropy partially from the mouse movements for example or at least minimum character count enforced in the UI. 

Wallet model should be discarded as it confuses users who don't even remember there's a file they should back up or how to even go about doing it safely.

**Comment by testlump** [comment]
This is why the 'Wallet' model offers a Brainkey. Protecting an account by a single password - which most users will not change - is significant attack vector. Few financial institutions protect their customer with anything less than two-factor these days for this exact reason. Username and password alone have not be shown to be secure.

**Comment by btsfav** [comment]
@wmbutler can be closed, was implemented

**Comment by fractalnode** [comment]
A user who has not saved or memorized a password is more likely than a victim of a brute force attack. Strong password check (as a input text validate) would be better imo. The user is forced to write a password that will never be remembered. I realize that this is a constant discussion...

**Comment by wmbutler** [comment]
Thanks for bringing this to my attention. This issue was implemented.
