### ISSUE TITLE
[5] Snap Packaging for Linux!!!

### ISSUE THREAD

**Issue by MikeD10375** [bitshares/bitshares-ui#1774]
I had a problem with an earlier version of the platform where it would not open in Ubuntu 18.04. I'm requesting that you create a snap package downloadable version for Linux distributions. 

ADVANTAGES:
- will work with all linux distributions because dependencies are included in package
- upgrades automatically
- is sand-boxed for security
- makes it easier for users 
- etc...
You can find instructions at https://snapcraft.io/

Thanks for your time,
Mike D.

**Comment by svk31** [comment]
Available here: https://snapcraft.io/bitshares2-light

**Comment by MikeD10375** [comment]
Thanks svk31 works great... However the link on the https://bitshares.org/download/ for Linux is still in .deb form. I don't know if you forgot, don't have access to that link, or are just going to keep that the same? By the way I tweeted the info to the community that it is now available in Snap form.
