### ISSUE TITLE
please  how i get payed and  the fees are shared  .

### ISSUE THREAD

**Issue by RakyCoder** [bitshares/bitshares-ui#1777]
I have forked the bitshres ui repository and made all modification  and installation  on the project rakydex.org  but I don't  understand  how I will get the Fees  . if  there is a special wallet to  setup with the software . how I get payed as a project rakydex  owner .  thanks for help

**Comment by startailcoon** [comment]
This repository is for the Bitshares UI (user interface) app.

This is not the right place to post about chain specific questions, especially forked chains.
