### ISSUE TITLE
[1.5] Market page, margin call order amount incorrect

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1778]
**Describe the bug**
Amounts of the yellow (margin call) order seems incorrect.

**To Reproduce**
1. Go to https://develop.bitshares.org/#/market/BTS_USD
2. Scroll down

**Expected behavior**
`Price * BTS amount = bitUSD amount`

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/44055225-f8fb8cc4-9f44-11e8-80bc-2aa59b6104df.png)

**Comment by svk31** [comment]
Will do a hotfix release for this
