### ISSUE TITLE
[0.25] Asset info page, debt column in margin positions table shows strange data

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1779]
**Describe the bug**
See screenshot below. Many debt amounts are 0.000x which seems incorrect.

**To Reproduce**
1. Go to https://develop.bitshares.org/#/asset/CNY
2. Scroll down

**Expected behavior**
Show real debt amounts.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/44055697-73f5d492-9f46-11e8-9067-9f71f6b53a73.png)

**Comment by svk31** [comment]
It's displaying the max debt to sell instead of the actual debt that's why, forgot to modify the values used when adding the new calculations.
