### ISSUE TITLE
Duplicate entries in MyMarkets

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1780]
**Describe the bug**
![image](https://user-images.githubusercontent.com/33128181/44077713-d88c9e3c-9fa4-11e8-8f56-ec5d37d994d4.png)

**To Reproduce**
Open My Markets and observe, BTS and bitUSD appears duplicated

**Comment by svk31** [comment]
Duplicate issue of #1746.

Not actual duplicate entries, but different assets.
