### ISSUE TITLE
[3][kapeer42] Settlement description in account activities

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1785]
**Is your feature request related to a problem? Please describe.**
People got confused when it just says asset settlement (in account activities) and not a single note of an exchange taking place, just the amount settled.

**Describe the solution you'd like**
UI should distinguish "A settled M amount of asset X instantly, got N amount of asset Y" and "A created a settle order for M amount of asset X", the former is for assets that are globally settled already, the latter is for the others.

**Describe alternatives you've considered**

**Additional context**

**Comment by Bluffet** [comment]
That was quick abit.

I also envision a clear text note on the asset in question, and what it implies for the end user. For oversight, color code the GS assets. And why not dim down the settlement price, since it has no longer any practical function?

**Comment by startailcoon** [comment]
I assume this is referring to when users are forced settled by either a lack of collateral **or** when another user is settling their holdings and the least collateralized users has to pay for it.

The lack of notice in the logs can be both chocking and confusing to users and I've seen posts about this before from very upset users wondering where their assets went.

I need the help of @svk31 to determine if this is possible to handle, and the reason for it not being there already.

**Comment by Bluffet** [comment]
No, you are mistaken there, @startailcoon 

This is about settling an asset (from the portfolio page)  that has black swaned (global settlement, GS)

My previous comment has what I would like to see to make it clearer. 

I tried doing this on som BitBTC the other day and to my surprise, it did not show up as a sell after 24 hrs like I expected. Got the explanation from xeroc that it is immediately converted (at a rate unknown to me) to BTS but the log does not show this happening. Which makes it a bitch to account for.

**Comment by startailcoon** [comment]
Thanks for the clarification. 👍

**Comment by svk31** [comment]
@Bluffet if you have an account we could use to look at for examples the t would be helpful. It's ok if you don't want to disclose that publicly though.

**Comment by kapeer42** [comment]
Can I claim this?

**Comment by startailcoon** [comment]
@kapeer42 it's yours. Make sure to have enough discussion on the topic if required.

**Comment by kapeer42** [comment]
I think there is enough info.
I wish I knew a way to provide price feeds for the bitAssets I created on the testnet.
Otherwise I will probably need to dig for an account that have this type of transactions or run my own testnet.

**Comment by abitmore** [comment]
@kapeer42 if your asset is backed by `TEST` on testnet, you can publish feeds in action tab of asset info page.
