### ISSUE TITLE
[0.5] Quantity fails to populate for withdraw modal (bridge.ltc)

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1787]
**Describe the bug**
Quantity does not auto-populate for bridge.ltc when clicking on Available Balance in Withdraw Modal

**To Reproduce**
1. Go to Dashboard
2. Click on icon for withdrawing bridge.ltc
3. Quantity does not populate

**Expected behavior**
When clicking on the available balance, the Quantity should populate

**Screenshots**
![withdraw](https://user-images.githubusercontent.com/1254810/44313107-f63fdd00-a3c7-11e8-91c8-d2da4f2f839b.gif)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome
 - Version Latest

This does seem to populate for openledger, but I'm not sure how it works for one but not the other.

**Comment by startailcoon** [comment]
First time I've seen this

**Comment by startailcoon** [comment]
Running the latest staging version 180815-RC1 doesn't give me this issue. 

![bitshares-withdrawmodal](https://user-images.githubusercontent.com/12114550/44352306-48563080-a4a4-11e8-8e9c-f81df206876c.gif)

**Comment by startailcoon** [comment]
I'd say this is related to some local circumstances on your end as no other reports have been submitted and I'm unable to reproduce it.

**Comment by wmbutler** [comment]
Agreed, no longer seeing this bug.
