### ISSUE TITLE
[0.5] Debounce needed for Market Picker

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1788]
**Describe the bug**
When utilizing the typeahead in the market picker, it looks like we are querying for it immediately on each keystroke. It would a good idea to add a debounce of around 250-400 ms to reduce calls to the chain/es. In this example case, typing just an `l` appears to wait for over 10 seconds. In my case it didn't pull any results at all. Regardless, debounce is a good option for managing user expectations.

**To Reproduce**
1. Go to any Market
2. Click on one of the symbols in the upper left to reveal the Market Picker
3. Observe the search happen immediately instead of waiting for additional characters

**Expected behavior**
A search should be initiated after a 250-400ms delay. I'd suggest that the developer use their best judgement while writing the code.

**Screenshots**
![debounce](https://user-images.githubusercontent.com/1254810/44313509-bed52e80-a3cf-11e8-80dc-1be01e529425.gif)

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Chrome
 - Version Latest

**Additional context**
Tested on BITSHARES.180814

**Comment by startailcoon** [comment]
Not sure why this issue still persists. It is an easy fix.
