### ISSUE TITLE
[2.5][kapeer42] Notify if settle is worth less than market value

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1794]
**Is your feature request related to a problem? Please describe.**
There are periods (E.G. now) that settling an asset will result in less income in comparison to selling to market directly.

**Describe the solution you'd like**
https://bitsharestalk.org/index.php?topic=26948.msg321299#msg321299
> The GUI should be changed so that when you click force settle it prompts you with "you can get a better price by selling, do you wish to sell now"

**Describe alternatives you've considered**

**Additional context**

**Comment by startailcoon** [comment]
@abitmore Am I correct that you wish that the UI should notify the user when settling an asset on the dashboard would be settled emiedetly, and that would be for less value than selling at the desired market.

This shouldn't be to difficult to do. We just need to read the current market and see if there is 
1. An ongoing settlement
2. Market settle is not the best buyer

This would be part of improving the Settlement feature in the dashboard.

**Comment by kapeer42** [comment]
Can I claim this?

**Comment by startailcoon** [comment]
@kapeer42 it's yours.

**Comment by kapeer42** [comment]
@startailcoon  Yes please I need more details.

To me it seems you and @abitmore are talking about two different things.

Your description is not clear to me.
Could you explain in what case an MPA would be settled immediately?
If there is something returned by `get_settle_orders` does that means there is 
> An ongoing settlement

?
What does
> Market settle is not the best buyer

means?

To me, the initial issue seems to be about showing a warning like:
![warning-example-with-hint](https://user-images.githubusercontent.com/35779885/45265865-35ef6700-b452-11e8-8607-3cf8a340bd30.png)
When the settlement price shown here:
![settlement_price_example](https://user-images.githubusercontent.com/35779885/45265816-6b478500-b451-11e8-87b0-8010fbc478bc.png)
is less than the market price shown here:
![market-price-example](https://user-images.githubusercontent.com/35779885/45265828-7c909180-b451-11e8-997f-d343bed54222.png)
The warning show above is a rough example and I think it should also prevent settling unless a confirmation action is done (like ticking a box)

Please correct if I'm wrong or misunderstood.

**Comment by abitmore** [comment]
@kapeer42 I agree that you understood me correctly.
