### ISSUE TITLE
question about how the UI is using get_limit_orders and get_call_orders

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-ui#1796]
In the bitshares-core we are refactoring some API calls to accept accept symbol or id instead of just id or just symbol string. 

While doing so we found certain api calls like `get_limit_orders`, `get_call_orders` and `get_settle_orders` all use a limit parameter but this limit is not checked core side. 

I will like to know what limit is the UI using in this calls so we can adjust the core accordingly without breaking UI. 

related work in the core side is at: https://github.com/bitshares/bitshares-core/pull/1272

Thanks.

**Comment by svk31** [comment]
The GUI uses a limit of 300 for get_limit_orders, get_call_orders and get_settle_orders

The relevant code is here:

https://github.com/bitshares/bitshares-ui/blob/develop/app/actions/MarketsActions.js#L428
https://github.com/bitshares/bitshares-ui/blob/develop/app/actions/MarketsActions.js#L369

**Comment by oxarbitrage** [comment]
thank you @svk31 , i added a limit of 300 in our side to remain compatible.
