### ISSUE TITLE
Exchange black screen after first visit

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#1798]
When the light client is started and I go to Exchange tab, I get on the first time a black screen.

After a reload the Exchange loads normal. A second visit also works normal.

The problem came with version: BitShares2-light_2.0.180815_amd64.deb

vendor.7979393919a407f0d0e7.js:12 Checked 5 connections, 0 failed
app.feeadc2670e8c6b26526.js:1 Following nodes have been pinged: Object
app.feeadc2670e8c6b26526.js:1 Found nodes with sufficient latency, stopping latency update
vendor.7979393919a407f0d0e7.js:45 synced and subscribed, chainstore ready
exchange.f1162ffe76bac0f439d5.js:1 checkFeeStatusAsync error undefined
index.html#/market/BTS_EUR:1 Uncaught (in promise)  request timed out after 3000ms with object ids: ["2.0.0"]

We should test a releases better before going live to prevent adding new bugs.

**Comment by startailcoon** [comment]
Seems a little related to https://github.com/bitshares/bitshares-ui/issues/1770, but that should have been fixed since the latest release. 

Regarding testing, we do have a RC period before releasing, but all depends on testing resources. Community members are encouraged to perform testing of the release candidates as well, and help us catch any issues.

This needs more looked at, thanks for your report.

**Comment by TechsUsInc** [comment]
I experienced the same thing in both this release and the RC, but didn't have time to report it. Complete black screen upon first use followed by a reload.

**Comment by startailcoon** [comment]
Any reports or logs from these events when they occurs are appreciated.

**Comment by svk31** [comment]
Your API requests are timing out indicating either a poor internet connection or a slow API node.

**Comment by froooze** [comment]
There must be another reason to this problem, because I never had the problem on the last build and now I get the bug every time, when the client is new started.

**Comment by froooze** [comment]
The problem looks solved now. Can't reproduce the bug now.

**Comment by startailcoon** [comment]
Maybe you got connected to a bad node automatically and you're no longer using the same node or it was fixed.
