### ISSUE TITLE
Blocktrades Gateway- Doesn't load Deposit screen

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#1805]
**Describe the bug**
Unable to deposit BTC via Blocktrades on the CLI
1. CLI Release 180815 does not load the Blocktrades deposit page- hangs on retrieving current data.
2. https://staging.bitshares.org/#/deposit-withdraw loads properly though

**To Reproduce**
1. From the 180815 CLI release; Click hamburger menu
2. Click on deposit
3. Scroll down to Blocktrades
4. See error- (deposit menu appears after engaging Dev tools)
5. From the staging.bitshares.org site; Click the hamburger menu
6. Click on deposit
7. Scroll down to Blocktrades
8. See that it loads properly

**Expected behavior**
Deposit options menu should appear immediately upon clicking deposit from the hamburger menu.

![blocktrades_cli_capture](https://user-images.githubusercontent.com/18186497/44788628-30477680-ab60-11e8-95d2-3d02683c61f8.PNG)

**Comment by startailcoon** [comment]
Works for me with 180815 Light Wallet on Windows 10.
May be a fluke on the BlockTrades.us site?

We will incorporate better external requests based on #1756, which should also handle outputs when errors occur if not done so today.
