### ISSUE TITLE
Login: Wallet Type Detection

### ISSUE THREAD

**Issue by CryptoKong** [bitshares/bitshares-ui#1808]
At the login page new users are often confused about cloud or local wallets. They often have a local wallet and try to login as though they had a cloud wallet, not realising they need to restore. It would be good if at the login page, after entering the wallet address the client/ browser detected the wallet type and directed users to the appropriate page. This would save a lot of time and frustration for new, less experienced users and also community members having to help them out.

**Comment by gibbsfromncis** [comment]
Sounds cool but for local wallet users shouldn't type username because they need only wallet file and password to login. 

I suppose it should be solved on UX level when user create wallet for the first time

**Comment by CryptoKong** [comment]
Yeah but thats the point. They do then wonder why they cant log in. So if a local wallet address is typed into the cloud login could they be re directed or an error/ advice message be displayed telling them to use the restore function?

**Comment by CryptoKong** [comment]
I thought cloud/ local had different keys? Could the wallet not detect the difference? Apologies if im basing my assumptions on incorrect facts.

**Comment by gibbsfromncis** [comment]
@clockworkgr I thought there is the way to detect which type of login user uses. 

@startailcoon anyway I suppose it's interesting point to think about UX redesign because when my friend started to use bitshares he asked me about this too.

**Comment by clockworkgr** [comment]
@gibbsfromncis as far as the chain is concerned no...the chain only has public keys and no way of knowing how they were derived.

So if I created a cloud account on one browser and then tried logging in from a different one (meaning there was no prior interaction/local data) , there is NO way of knowing from the account data on chain what type of login i originally used.

**Comment by wmbutler** [comment]
@CryptoKong one telltale is that Cloud Wallets have a certain prefix to the auto-generated password.

**Comment by gibbsfromncis** [comment]
@CryptoKong To be honest I think we should fix this misunderstanding on Sing up level and make users understand the difference between those account types. 

I'll close this issue as it's not real to implement
