### ISSUE TITLE
Github Repo Issue: Unable to search the Bitshares-UI code within GitHub because it's a fork of the Graphene repo

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#181]
![image](https://user-images.githubusercontent.com/15861527/27647328-0a5b20d0-5c23-11e7-873d-9701cec93162.png)

I'm unable to search the Bitshares-UI code within GitHub because it's a fork of the Graphene repo, would we be able to change this?

Thanks 👍 

---

That said, you can easily search the code by forking the repo locally and searching with a text editor.. so perhaps worth closing this issue?

**Comment by happyconcepts** [comment]
bitshares-ui provides search results now. Enjoy!
