### ISSUE TITLE
[10] Update, Clean and Simplify Theme Templates

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1812]
For now on `_theme-template.scss` are the mess:
1) Some colors not used as variables
2) Some variables used in wrong places (like `$secondary-text-color` used as `background-color` on some places)

This issue includes the following work:
1) Review all variables usage and manage them on the right way (split, add new or delete variables)
2) Develop & provide simple instruction in the form of comments to help new contributors understand things better and keep code's quality on the high level
3) Provide new variables to have more flexibility on themes customizing

Required Estimate: 4 hours

**Comment by sschiessl-bcp** [comment]
This will be perfect in combination with #1613

At the end we could have a easy to customize framework for theming of the UI, at which point we can present that to the community in the hopes of some motivated members creating their own styles!

**Comment by gibbsfromncis** [comment]
@wmbutler @startailcoon I did review of our `themes-templates.scss` and `4h` estimate is not enough to clean up the mess and put every properties to variables. My new estimate is around `10h` but this may change if I start to work on this task.

If you agree please update the estimate or lets wait till somebody other will take care of it. I want to ask you to make sure that the guy who will be responsible for this is professional enough to make it on the right way

**Comment by sschiessl-bcp** [comment]
Can this be prioritized? 

We are getting lot's of restyling issues now and new components, and this would be best to be done beforehand IMO

**Comment by wmbutler** [comment]
@gibbsfromncis the estimate was bumped to 10.

**Comment by gibbsfromncis** [comment]
@wmbutler yea I know. I'm not sure how to deal correct with this issue and I'm not sure it is the nice time to work on it. I'll discuss it with Stefan and we will find solution or the date when we start to work on it.

**Comment by gibbsfromncis** [comment]
Unfortunately for now it is not possible to do it correct. I'll close this issue and reopen or create new one when I have an idea how to deal with it
