### ISSUE TITLE
[3] Update Asset UX

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1816]
Based on feedback on this issue - https://github.com/bitshares/bitshares-ui/issues/1757 I guess we should increase max items on the page.

**Comment by svk31** [comment]
I don't think that would help, you'd then have to scroll to see all items between clicking next page, making things worse.

**Comment by gibbsfromncis** [comment]
@svk31 agree. Could we reach an agreement on adding option to select how many items user want to see on the page?

**Comment by startailcoon** [comment]
Once all the assets are loaded, as they always has to be like @svk31 states, the user should be able to change the amount of rows placed on their screen.

I suggest we make it possible to change it between `20, 50, 70, 100, 200` per page.

**Comment by froooze** [comment]
25, 50, 100 and 200 steps makes more sense to me.

**Comment by startailcoon** [comment]
The cide fetches all by api, you can tell the pagination to use any number I guess?

**Comment by gibbsfromncis** [comment]
@startailcoon exactly but If I remember correct the limit of items to fetch per one call is 100 to do not overload backend

**Comment by sschiessl-bcp** [comment]
I suggest to add a "Show XX" combobox on the right side of 
![image](https://user-images.githubusercontent.com/33128181/45349113-b7f5a200-b5b0-11e8-87d9-dcba883698b6.png)

This combobox has 10 / 25 / 50 / 100 and All options, but also allows that the user enters a number by himself.

This needs evaluation / rating before claiming

**Comment by startailcoon** [comment]
I like the option of a few predefined options for the user to chose from, but letting them input one by their own design as well. 

It will need testing to make sure the UX is looking good/working in different window sizes and browsers.

As there is no change in how the data is fetched from server based on the users choice I see no reason to evaluate any API load.

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp @startailcoon 

Agree. I've checked the code and it looks like it fetches all items before page load. 

Task is:
- [ ] Add Select component to be able to manage amount of items on the page from the predefined list
- [ ] Add Number component to be able to manage amount of items on the page manually

During this task screenshots of realization should be provided to approve it looks nice.

Estimate is 2h

> I suggest to add a "Show XX" combobox on the right side of

@sschiessl-bcp I'll check the ability to do it like you wish but I suggest it's not possible because pagination renders by ant and takes 100% of width. If there is no chance to make it as you wish I'll take UX from there (I'll put Select & Number components above the table)
![explore with existing nav v3](https://user-images.githubusercontent.com/3088454/39169907-65b97ad0-4791-11e8-83be-c29223ddd6b6.png)

**Comment by sschiessl-bcp** [comment]
I'd like to include one more thing if you are already touching it.

While the asset list is loading a loading indicator is shown over the whole page, disabling me to search or click on an asset (if e.g. the one I am looking for is already on first page).

I suggest to put the loading indicator in the top left of the screen (in your mockup in the same row as the Select component), which allows user interaction while loading. If user exits page while loading, loading should be stopped

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp definitely agreed. Also it would be nice to make overlay over the table "white" or "dark" depending on theme. Because it makes me crazy when I'm trying to click and nothing happened because of transparent overlay...

**Comment by startailcoon** [comment]
Would be very nice if you could make the loading asynchronous in the background and let the user interact with the list, filter and options during this time. The user should be notified that the list is still populating during this time though.

I think the pagination at the bottom and selection props at the top looks good. 

- View options to `10 / 25 / 50 / 100` is good options
-  Make sure it's theme independent
- If possible, try to make sure the list works well in a smaller frame, like a mobile unit.

**Comment by svk31** [comment]
It's already async, it's just the loading indicator that blocks input.

**Comment by sschiessl-bcp** [comment]
PR referenced wrong issue

**Comment by gibbsfromncis** [comment]
Done.

<img width="166" alt="screenshot 2018-10-03 01 09 28" src="https://user-images.githubusercontent.com/35899973/46381993-04f8ff80-c6a9-11e8-895a-465388b0f193.png">
<img width="1440" alt="screenshot 2018-10-03 01 09 11" src="https://user-images.githubusercontent.com/35899973/46381994-05919600-c6a9-11e8-9700-ea5b0852cf4a.png">
<img width="1440" alt="screenshot 2018-10-03 01 09 02" src="https://user-images.githubusercontent.com/35899973/46381998-05919600-c6a9-11e8-91e3-3c0ad26c33fe.png">
<img width="1440" alt="screenshot 2018-10-03 01 08 49" src="https://user-images.githubusercontent.com/35899973/46381999-05919600-c6a9-11e8-87c3-e3a3dd534ec6.png">

**Comment by kristinlow** [comment]
Great improvement. Thanks everyone.
