### ISSUE TITLE
Cannot compile the package 

### ISSUE THREAD

**Issue by luanhaipeng** [bitshares/bitshares-ui#182]
ERROR in ./~/_react-foundation-apps@0.7.0@react-foundation-apps/src/modal/index.jsx
Module parse failed: /Users/luanhaipeng/github/bitshares/bitshares-ui/web/node_modules/_react-foundation-apps@0.7.0@react-foundation-apps/src/modal/index.jsx Unexpected token (60:6)
You may need an appropriate loader to handle this file type.
|     }
|     return (
|       <Animation active={this.state.open} animationIn="fadeIn" animationOut="fadeOut">
|         <div className='modal-overlay' style={overlayStyle} onClick={this.hideOverlay} >
|           <Animation
 @ ./app/components/Account/AccountAssets.jsx 17:0-52
 @ ./app/Routes.jsx
 @ ./app/index.js
 @ ./app/Main.js

**Comment by wmbutler** [comment]
Not enough detail here.
