### ISSUE TITLE
[2] Accept comma input for fractional part sign

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#1828]
Many user from other countries have the comma as a sign of the fractional part instead of the point on their keyboards/numpads. 

The UI should also accept comma and point as a fractional part sign.

**Comment by clockworkgr** [comment]
If we do this it should be user locale/regional settings dependant

**Comment by gibbsfromncis** [comment]
@froooze could you please provide an example of those countries?

**Comment by froooze** [comment]
I fount a map. :)
http://assets.datacamp.com/blog_assets/the_map.html

**Comment by startailcoon** [comment]
Why do we need to depend on the locale/regional settings?

I can only take myself as an example. My regional settings would have a comma for decial placement, but I usually have the english local/keyboard layout when I type in english, which has the dot as a decimal placement.

Wouldn't it just suffice that we make both `,` and `.` both acceptable decimal placements in the UI, and when we generate the transaction for the chain, just translate both of these to the correct decimal placement. 

This way we don't have to rely on a locale to be correct for the user, and at the same time make it more simple for them. Only thin we have to do is to update the update forms to accept `,` as a decimal placement and make sure there is only one in the input.

**Comment by clockworkgr** [comment]
@startailcoon keyboard has nothing to do with it...your regional settings define whether a number is displayed as 1,234.00 or 1.234,00 and also how what you type is interpreted in a locale aware app.

The assumption being that a user that cares enough about how his numbers are displayed and interpreted will have also set the regional settings to his preferences.

**Comment by clockworkgr** [comment]
you can accept it...how do you know what the user means though?

**Comment by startailcoon** [comment]
That is a good question though.

Some users _may_ believe that a `,` means a thousand delimiter and be confused once the app interpreted it as a decimal placement.

Since we only allow one of bith, its either a comma OR  dot. A misinterpretation would only mean that the user buys/sells less than intended.

**Comment by clockworkgr** [comment]
I guess...but you see what I'm getting at.

For me the proper behaviour is to accept whatever regional settings say the decimal separator is

**Comment by abitmore** [comment]
If to honor regional setting, we need to be consistent through the whole UI. It would be a mess if we accept comma in one page, but shows a dot elsewhere.

**Comment by startailcoon** [comment]
Pushing this task to 2 hours in total to implement the following
- [ ] Accept both `.` and `,` as form input type for decimal placement
- [ ] Update UI to view decimal placement based on regional settings, on all sections required.

**Comment by abitmore** [comment]
> Accept both . and , as form input type for decimal placement

@startailcoon please be VERY careful about this. People may pasting a number with no "." but only a "," E.G. `1,000` and meant to input `1000` but not `1`. BitShares is somewhat a financial system, the consequence of false detection would be serious. My opinion is to stick to one decimal placement, unless the user explicitly specified another somewhere e.g. in settings.

**Comment by svk31** [comment]
I think we need to be careful with this too. Personally my regional settings indicate a comma being used, but I would prefer using a dot.

Supporting both makes input validation more complicated so I'm inclined to say we just support one style which would be the dot.

**Comment by startailcoon** [comment]
@abitmore @svk31 I agree with both of you on this. I've pointed out what the issue would be about when implementing it, but as you state we also have to make sure to catch any edge case when doing this change.

Today you can't paste an input with a comma sign in it. The form will just not accept it. Pasting with a dot will mean `1.000` turns to `1`.

We could deny any paste of input with anything else than numbers, but that would be going backgards I think, and isn't what we wish here.

How does other financial systems take care of these cases?

I wish to see a good solution to this before we accept any PR on this.

**Comment by sschiessl-bcp** [comment]
> Today you can't paste an input with a comma sign in it.

This actually works now (e.g. pasting 1,000 USD for 1000)

**Comment by sschiessl-bcp** [comment]
> If what @sschiessl-bcp says it true, that it accepts comma as a thousand separator, that would mean users with a locale with comma decimal separator would have their pasted values multiplied by 10,000,000 (or 10 000 000,00 in my locale), which seems pretty dangerous.

Good point, will check

**Comment by wmbutler** [comment]
There is too much risk and liability associated with this issue based on the comments above.
