### ISSUE TITLE
Bitshares-ui not working with Firefox

### ISSUE THREAD

**Issue by AboShanab** [bitshares/bitshares-ui#1830]
**Describe the bug**
As the title, I can't connect at all. it shows Application initialization issues page.

**To Reproduce**
Just open develop or staging. not working.

**Expected behavior**

**Screenshots**
<img width="943" alt="firefox_2018-09-07_22-23-14" src="https://user-images.githubusercontent.com/12101368/45239080-a67c7380-b2ec-11e8-86bd-a49d8267904a.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Firefox
 - Version 62.0

**Smartphone (please complete the following information):**

**Additional context**

**Comment by startailcoon** [comment]
This issue is most likely related to some network issue on your end or a temporary glitch somewhere. 

### Right now for me it's working just fine
![image](https://user-images.githubusercontent.com/12114550/45240038-92824300-b2e7-11e8-9050-f31f064c699a.png)
