### ISSUE TITLE
Empty list by default

### ISSUE THREAD

**Issue by AboShanab** [bitshares/bitshares-ui#1831]
**Describe the bug**
When browse the wallet, it shows empty list by default (My Markets tab isn't selected by default)

**To Reproduce**
Just browse staging or develop wallet using Chrome

<img width="960" alt="chrome_2018-09-07_22-33-04" src="https://user-images.githubusercontent.com/12101368/45239475-15a69780-b2ee-11e8-912f-eedf868350d3.png">

**Expected behavior**

**Screenshots**
<img width="960" alt="chrome_2018-09-07_22-29-16" src="https://user-images.githubusercontent.com/12101368/45239467-0d4e5c80-b2ee-11e8-8b23-6726ec26fb03.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Chrome
 - Version 68.0.3440.106 x64

**Smartphone (please complete the following information):**

**Additional context**

**Comment by startailcoon** [comment]
Thanks for your report. This issue was resolved in PR #1822, but hasn't been pushed for the update yet.
