### ISSUE TITLE
[0.5][kapeer42] Use correct Backing asset on Asset Actions/Info, not default to core asset

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1833]
**Describe the bug**
I have a private smart coin on testnet backed by an UIA. I can't publish price feeds.

**To Reproduce**
1. Go to https://testnet.bitshares.eu/asset/ASDFUSDA
2. Click on 'Asset actions'
3. Scroll down to 'publish feed'

**Expected behavior**
Able to publish price feed.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/45259816-0ac73200-b3d6-11e8-81e4-65370aaefa43.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kapeer42** [comment]
I think I need this to get #1785 and maybe #1794 done and tested.

**Comment by startailcoon** [comment]
This is the same as for bitXCD (Eastern Caribbean Dollar), which is backed by bitUSD.
http://cryptofresh.com/a/XCD_USD

Assets Details should make sure to view all sections based on the correct backing asset, not default to CORE asset.

![image](https://user-images.githubusercontent.com/12114550/45589672-d7325d80-b929-11e8-8270-6a6063d0cde0.png)

**Comment by startailcoon** [comment]
Sure, it's yours @kapeer42 

Looking at this issue again, I think it's a bit to much to have this set to 2 hours. I'm setting it to 0.5 hour and you tell me if there is anything that makes it take much longer. It should be a fairly simple task.
