### ISSUE TITLE
[0.5] Deposit/Buy Modals scrolling issues

### ISSUE THREAD

**Issue by cloud-8** [bitshares/bitshares-ui#1835]
**Describe the bug**
When clicking Quick Buy a modal is launched and it generates a QR from the desired Bridge. However only a portion of the QR code is visible and the window is not scrollable. Scrolling the mouse on the modal doesnt move it and scrolling it outside the modal scrolls the background exchange view. 

**To Reproduce**
1. Go to 'Quick Buy on a market that supports an asset that can be bought by a Bridge like (https://staging.bitshares.org/#/market/OPEN.BTC_USD)
2. Try to scroll the modal window

**Expected behavior**
I should be able to scroll the modal window to see the full QR code 
**Screenshots**

https://i.supload.com/r1gj9uI7dQ.png

**Desktop (please complete the following information):**
 - OS: MACOSX 10.13.6
 - Browser Chrome
 - Version 68

**Comment by startailcoon** [comment]
There is an issue with this modal compared to the Borrow modal. When I open this modal in Firefox on Windows it will scroll the content behind it, while the Borrow modal scrolls the content of the modal. 

On Mac and Chrome this may be the reason for the lack of scrollbar.

This has been an issue from before and is present on the current release, and isn't related to the change on issue #1477

**Comment by cloud-8** [comment]
Why is it part of exchange redesign [Feature] when it is a bug with the current RC? @sschiessl-bcp

**Comment by startailcoon** [comment]
This will be fixed independently of the exchange redesign as it's also present in todays release as noted.

**Comment by startailcoon** [comment]
I will sherry pick the fix for this from the above PR and push a new PR for the development branch in a few days.

**Comment by sschiessl-bcp** [comment]
Thanks!

**Comment by startailcoon** [comment]
There is an issue with the change I made and it will fail on some parts of the code. Scrolling is fixed, but requires some more attention. Making this required to be pushed for next release instead.

**Comment by startailcoon** [comment]
Fixed part of PR https://github.com/bitshares/bitshares-ui/pull/1990
