### ISSUE TITLE
[2][Exchange Redesign] Rework Help design

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1836]
This issue is two fold.

<h3>One</h3>
When the exchange is opened the first time, or help is requested the explanation popup circles between the first two.

**Reproduce**
1. Open Exchange in mobile view
2. Click help
3. Click next in popup
4. Continue clicking

<h3>Two</h3>
Implement new help popups that explain the user the usage of Personalize etc.

**Comment by startailcoon** [comment]
It doesn't loop what I can see.

When you are on the second item, next is the replaced with back.

Done is on the left of the info window.

**Comment by sschiessl-bcp** [comment]
On Android the "Next" button is still visible

![screenshot_20180910-082054](https://user-images.githubusercontent.com/33128181/45281705-eb64fd80-b4d8-11e8-9c79-02e3bd0a7785.png)

![screenshot_20180910-082111](https://user-images.githubusercontent.com/33128181/45281709-ee5fee00-b4d8-11e8-944d-552292a25774.png)

Seems to be a browser capabilities issue.

**Comment by startailcoon** [comment]
That is a browser compatible issue.

This is how it looks for me on Edge for Android.

![](https://i.imgur.com/64WlWEi.jpg)

**Comment by startailcoon** [comment]
It's not part of the exchange section. It's a global help box component that runs independently.

**Comment by startailcoon** [comment]
There should be many help steps added to this on the new exchange design.

This would probably be a requirement before we release the update.

I see items like, but not limited to
- Hide side panel
- Switch order book order
- Personalised design settings

And more
