### ISSUE TITLE
[Exchange Redesign] Order Book details

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1837]
Deviates from suggested mockup. Furthermore does not persist settings auto scroll: 
Click on locked icon, wait until book is updated. Icon reverses to locked. Also the description might be wrong? If I see the locked icon, I expect that the order book split is always in the middle of the view, but the help text says "Enable auto scroll", which would indicate once I click the order book is auto-scrolled to have the split in the middle
![image](https://user-images.githubusercontent.com/33128181/45280372-5bbd5000-b4d4-11e8-9c4e-10f1214bf3b6.png)

Tasks:
 - [x] Adjust font sizes of Spread/Latest. Font size must be consistent with order book
 - [x] Have both both icons centered horizontally and have consistent icon size / coloring
 - [x] Persist auto-scroll setting
 - [ ] Evaluate visualization of auto scroll icon
 - [x] Include Auto-scroll option in "Personalize" modal

Group Button takes up unnecessary space
![image](https://user-images.githubusercontent.com/33128181/45280412-87d8d100-b4d4-11e8-8b28-b478ef4d2228.png)

Tasks:
 - [x] Include Grouping options in "Personalize" modal
 - [x] Find a new place for Group button or remove

**Comment by startailcoon** [comment]
Grouping is moved to Personalize modal as a global default setting. Grouping is removed on vertical panel, but left unchanged on horizontal as it has the space to contain it. We could remove it there as well if it's desired.

Autoscrolling persists on change now. Autoscrolling is also available on the Personalize modal as a global setting, and sets the desired default option. A temporary change is done directly on the order book.

Coloring, font-sizing and alignment is changed as seen below.

![image](https://user-images.githubusercontent.com/12114550/45595632-1a82df80-b9af-11e8-94c8-8358f4e168a2.png)

**Comment by startailcoon** [comment]
I would suggest we remove the "Latest" title on the middle section as seen below. Having a market with to many digits will make the orderbook unnecessary wide.

![image](https://user-images.githubusercontent.com/12114550/45595675-c9bfb680-b9af-11e8-854e-c5ff45cbfb7a.png)

**Comment by startailcoon** [comment]
## New Personalize settings modal (in progress)
Still refining the modal, but this is a first draft of it.
It's now using the Ant components.

![image](https://user-images.githubusercontent.com/12114550/45600390-4ed0bd00-b9fc-11e8-8836-77f61294edc6.png)

**Comment by sschiessl-bcp** [comment]
> Grouping is moved to Personalize modal as a global default setting. Grouping is removed on vertical panel, but left unchanged on horizontal as it has the space to contain it. We could remove it there as well if it's desired.

I suggest we include another Setting: "Hide most control buttons". If activated, all non-trade related, settings adjusting buttons are hidden, see #1866

> Still refining the modal, but this is a first draft of it.

What does "Globally" mean in this context?

**Comment by startailcoon** [comment]
Only thing left on this would be _Evaluate visualization of auto scroll icon_.

Any suggestions on this topic?

**Comment by sschiessl-bcp** [comment]
> Only thing left on this would be Evaluate visualization of auto scroll icon.
> 
> Any suggestions on this topic?

Look at the tooltip and which icon is used at what visible state. I think the icon should represent the current state, whereas the tooltip tells you what happens on click. Current tooltip is wrong.

**Comment by startailcoon** [comment]
I would probably go for https://static.thenounproject.com/png/204136-200.png
<img src='https://static.thenounproject.com/png/204136-200.png' height='100px'>

You've missed the icon for inverting the order book, switching places of sell and buy orders, which was a task in the redesign UX. However, I think we could achieve a good result by putting the toggle on the latest price. By adding a tooltip as well as adding it to the help walkthrough, I think it would be a good solution.

How can "pin" be an optional icon, either you view it or you're not in vertical order mode. As I see it we have the following icon
- Auto Scroll (mandatory)
- Pin (mandatory)
- Group (mandatory, or hidden when no group is done and it has to be done in personalize)
- Inverting order book (mandatory)

One solution would be to have Grouping as the visible icon if done, while the other three would be 
in the popup list. My reason for this is that I'd say that grouping is something you'd like to be visibly aware of while the rest is just toggles.

**Comment by sschiessl-bcp** [comment]
This goes hand in hand with #1866 

Following suggestion:
Per default all icons are gone besides auto scroll and grouping indicator,  which can be displayed next to each other. Auto-scroll click stays as is, group indicator click could open the selection popup as it does now. If user enables to show control buttons, the auto-scroll icon switches into the the above mentioned icon group popup icon and includes the rest.

I think we overestimate how many users actually user those, and I like Bills suggestion for the next step for auto scroll. If user scrolls up or down, it stays like that. If user scrolls back into the center, it snaps back and reverts to autoscroll.

**Comment by startailcoon** [comment]
I was unable to find a good way to make a popup work as the centering doesn't stay at the same place on an active market. However, I think we can add an icon stating that the order book is grouped. Here I've just used an icon in the Ant library, as I couldn't make the PNG supplied work properly.

![bild](https://user-images.githubusercontent.com/12114550/46694893-4ab84980-cc0e-11e8-963e-462164907788.png)

You will be able to change the settings in the personalize panel as discussed.

![bild](https://user-images.githubusercontent.com/12114550/46694932-6b809f00-cc0e-11e8-8a56-28d4d5aaadf0.png)

Does this sound like a good and acceptable option?

**Comment by sschiessl-bcp** [comment]
Yes it does. Should I create an .svg of  https://static.thenounproject.com/png/204136-200.png?

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/commit/bf47e2655401cb9d9b11ecd02abdbd600e30a69a

**Comment by startailcoon** [comment]
Closed part of PR #2008
