### ISSUE TITLE
[Exchange Refinement] Scrolling Behavior Part 1

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1838]
While being on mobile view it is a pain to scroll up and down when the boxes have their own scrollbars / eat the scroll event.

Current behavior:
 - Buy / Sell Orders, Market trades etc. implement their own scrollbar, thus scrolling the whole view becomes difficult

Suggestion:
 - [x] Add option to "Personalize": "Reduce scroll bars"
 - [x] If option enabled, Sell and Buy orders / My trades / Market trades do NOT have their own scrollbar on initial loading and only display as many orders as they can in the current size
 - [x] If "Show all ..." is clicked, missing entries are loaded and scroll bar is enabled independent of "Reduce scroll bars" setting

**Comment by startailcoon** [comment]
I've managed to find a good way to solve this and has so far successuflly managed to get the order book component to handle this.

Still need to rework the rest of the exchange components to be able to hide/show the content.

- [x] Option `Reduce scroll bars` in Personalize Exchange
- [x] Order Book
- [ ] Market Trades
- [ ] My Trades
- [ ] My Open Orders
- [ ] Settle Orders

Estimated work: 2 hrs

**Comment by startailcoon** [comment]
This is done and within the bounds of the #1477 bounty.

**Comment by startailcoon** [comment]
This is done and required 4 hours of work to complete.
