### ISSUE TITLE
[Exchange Refinement] Scrolling Behavior Part 2

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1839]
While being on mobile view it is a pain to scroll up and down when the boxes have their own scrollbars / eat the scroll event.

Current behavior:
 - Trading View eats scrolling event even in mobile view

Suggestion:
 - [x] In mobile view, TradingView should not be listening to scroll events
 - [ ] If possible, implement zooming on two finger drag

**Comment by sschiessl-bcp** [comment]
I have found the TradingView options, they are included as shown below

https://github.com/bitshares/bitshares-ui/blob/820b055259deb616820da2051ddcac713fe08f09/app/components/Exchange/TradingViewPriceChart.jsx#L44-L47

**Comment by startailcoon** [comment]
This works for disabling the controls of the widget on mobile, but it disables all controls. I think @svk31 needs to supply us with some more documentation regarding this, but it's disabled for the moment to satisfy the mobile design better.

Optimal would be to have pin zooming still enabled, if there is more data to display of course.

**Comment by startailcoon** [comment]
This is complete. Required no work hours to handle.
