### ISSUE TITLE
[0][kapeer42][Develop] Can't update bitasset 'Minimum number of feeds'

### ISSUE THREAD

**Issue by kapeer42** [bitshares/bitshares-ui#1848]
**To Reproduce**
1. Go to 'Assets'
2. Click on 'Update asset' on a bitasset
3. Click on 'SmartCoin options'
4. Try editing the minimum number of feeds, it's locked.

**Additional context**
This was probably the original intent of the `default` case removed in #1834, my bad for not testing more.

**Comment by startailcoon** [comment]
Set reward to 0 as it's a fix of your previos PR, nice catching it on your testing of the dev build aftewards though.

**Comment by wmbutler** [comment]
@kapeer42 did you expect to be paid for some of this?

**Comment by kapeer42** [comment]
@wmbutler I expected this to be included in the initial 1 hour here (2 - 1 given to HarukaMa) https://github.com/bitshares/bitshares-ui/issues/1539 hence the 'like' on @startailcoon comment.

On the other hand this https://github.com/bitshares/bitshares-ui/issues/1539#issuecomment-420195820 was not in the initial scope and not rewarded.
If you want an estimate, from the code I'd say it was roughly 2 hours.
I'm fine with it not being rewarded since it wasn't estimated.
