### ISSUE TITLE
[0.5][kapeer42] Unable to change password on latest reference wallet

### ISSUE THREAD

**Issue by kimchi-king** [bitshares/bitshares-ui#1856]
While using the desktop wallet version 180912 it's not possible to enter your current password on the password change page. Therefore, it's not possible to update your password for local wallets.

**To Reproduce**
1. Go to Settings --> Password
2. Unable to enter current password

**Expected behavior**
You should be able to enter your current password and then set a new password.

**Desktop (please complete the following information):**
 - OS: Mac OX X El Capitan ver. 10.11.6
 - Browser N/A
 - Version N/A

**Comment by kapeer42** [comment]
Can I claim this?

**Comment by startailcoon** [comment]
@kapeer42 it's yours. Please make sure that you don't miss any of your other issues that are still open.  Make sure it's tested well, as it's a security feature on chain we're handling here.
