### ISSUE TITLE
[Showcases] Escrowed transfer, or off-the-book trade

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1859]
<h1>Showing the strength of the blockchain</h1>
It happens quite often in telegram channel that people look for approaches how to solve their task, and quite often it happens that the existing features can already help to realize it. The reference UI should show the strength of the blockchain, and currently it mostly leverages the exchange. The showcases intend to open new possibilities. 

<h2>Escrowed transfer, or off-the-book trade</h2>
A simple escrowed transfer can be realized between two parties and an optional appointed escrow with a proposal. Let's assume account A and B, and E (escrow). The proposal contains now

- transfer of asset X from A to B
- transfer of asset Y from B to A
- optional with escrow:
  - transfer of marginal amount of BTS from E to A or B
  - transfer of approval and transfer fee plus escrow fee in BTS from A or B to E

<h3>Specification</h3>
User must be able to

- see a descriptive text that explains the leveraging of the proposal system and the fee breakdown (propose, approval and transfer fee)
- enter account A and B as well as asset and amount of X and Y
- optional with escrow: enter account E and escrow fee in BTS

<h3>Tasks</h3>

- [x] Create mockup and tile for #1857 
- [x] Implement design
- [x] Implement business logic

This issue is also for discussion and feedback collection and part of #1857

**Comment by sschiessl-bcp** [comment]
Merging this to show to people for testing

**Comment by startailcoon** [comment]
Based on information from PR:
- Hours: 27
- Devs: @sschiessl-bcp @clockworkgr 
- Payment goes to @sschiessl-bcp as issue assignee and none other info supplied for dividence
