### ISSUE TITLE
[Exchange Refinement] Ideas for Future Changes

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1863]
As the new design from #1477 had a few issues once completed I have a few ideas that I wish to bounce to the community.

I think the new layouts wasn't the best ones, and would rather wish to change it to something like the following. I'm terrible at UX design, so I'll describe my ideas as best as I can.

1. A layout with the original design, where you have the markets on the right and the order book on the left with the possibility to "unpin" it to get the orderbook within the page. At this page I would also like to make it possible to hide both side panels individually. You would also be able to "pin" the order form in replacement for the order book. `Market Trades`, `My Trades` would be tabbed,  `My Open Orders` and `Settled Orders` would be tabbed. 

2. Same as "1", but mirrored in the layout of orderbook and market side panels. This choice could be made in "Personalize" modal, OR by clicking an icon on the panels that would be easily understandable to be "switch places".

3. This layout would have `Market Trades`, `My Trades`, `My Open Orders` and `Settled Orders` in a tabbed layout. Other layout would persists with layout 1

4. This layout would have no containers in tabbed mode.

The main idea is that any change should be possible within the exchange page itself by icons, but also by the Personalize modal, which has other global settings for the layout.

I'm open for ideas.

**Comment by froooze** [comment]
- temp drawer on the side for BUY/SELL 
- use three column design till bottom
- MARKET TRADES/MY OPEN ORDERS and MY ORDERS in one column
![Exchange](https://i.postimg.cc/xTDQBSxb/Exchange-_Redesign.png)
