### ISSUE TITLE
[Exchange Refinement] Add setting to hide function buttons

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1866]
As stated in https://github.com/bitshares/bitshares-ui/issues/1837#issuecomment-421823734

The buttons spread out throughout the exchange layout that allow adjusting the layout should almost all be hidden if the user ticks the new setting "Hide most control buttons" in the "Personalize" Modal.

Example for a control button that can always be visible: 
 - Auto-scroll for Order Book
This button is expected to be used more frequently than other layouting adjustments
 - Group Orders 
Icon displays the current grouping state, which is good to visualize

**Comment by startailcoon** [comment]
I'm a little unsure on what why this is needed. Are there that many controle buttons that we need to hide? We need to have them in the personalize panel instead, but I can't say that we have that many.

**Comment by sschiessl-bcp** [comment]
Following function buttons are not yet in the Personalize modal:

- Order Book Style: Horizonal | Vertical
- If Horizontal Order Book: 
  - Show option: Buy/Sell Orders: Buy - Sell | Sell - Buy
  - Show option: Buy/Sell Asset: Buy - Sell | Sell - Buy 
  - Show option: Vertical Orders / Asset: Orders above Asset | Asset above Order
- If Vertical Order Book:
  - Show option: Autoscroll: Yes | No

**Comment by sschiessl-bcp** [comment]
The point is to make the default view as slick as possible, thus the option to hide function buttons.

**Comment by startailcoon** [comment]
Fixed part of PR #1980
