### ISSUE TITLE
error about start ui

### ISSUE THREAD

**Issue by LeeGG** [bitshares/bitshares-ui#1869]
**npm -v
5.6.0**

**node -v
v6.0.0**

**git branch 
* master**

when I start  "npm start ":

<img width="998" alt="image" src="https://user-images.githubusercontent.com/22726673/45683025-d17c8800-bb74-11e8-81b8-bb0a73333ebd.png">

source:

> BitShares2-light@2.0.180912 start /opt/blchain/exchange/bitshares-ui
> cross-env NODE_ENV=development node server.js

<--- Last few GCs --->

   37070 ms: Mark-sweep 1327.0 (1434.6) -> 1326.0 (1434.6) MB, 643.6 / 0 ms [allocation failure] [GC in old space requested].
   37733 ms: Mark-sweep 1326.0 (1434.6) -> 1326.0 (1434.6) MB, 663.0 / 0 ms [allocation failure] [GC in old space requested].
   38357 ms: Mark-sweep 1326.0 (1434.6) -> 1324.7 (1434.6) MB, 623.2 / 0 ms [last resort gc].
   38979 ms: Mark-sweep 1324.7 (1434.6) -> 1324.7 (1434.6) MB, 622.0 / 0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1a36029c9fa9 <JS Object>
    1: _findPath [module.js:~135] [pc=0x396011a98d74] (this=0x3d417c1b6c09 <JS Function Module (SharedFunctionInfo 0x3d417c1275b1)>,request=0x3c15f1367479 <String[35]: @webassemblyjs/helper-wasm-bytecode>,paths=0x3cb947d789b1 <JS Array[87]>,isMain=0x1a3602904299 <false>)
    2: _load [module.js:~381] [pc=0x396011a94cb3] (this=0x3d417c1b6c09 <JS Function Module (SharedFunctionInfo 0x3d417c1275b1...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! BitShares2-light@2.0.180912 start: `cross-env NODE_ENV=development node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BitShares2-light@2.0.180912 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-18T10_56_42_087Z-debug.log

**Comment by svk31** [comment]
Node version is too old, use v8 or v9
