### ISSUE TITLE
Add a clickable clipboard that copies your BTS "Address"

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#187]
Lots of confused users do not know that your name = address, so my proposal is to add a little clipboard sign which copies user name. 

![2017-07-08 08_54_03-bitshares](https://user-images.githubusercontent.com/15261692/27983392-349041e2-63bb-11e7-8342-b1c2ef898ea1.png)

here are some public domain clipboards: https://pixabay.com/en/photos/?q=clipboard&hp=&image_type=&cat=&min_width=&min_height=

**Comment by wmbutler** [comment]
It would be nice for it to be clickable, especially for those accounts that have long random names. This needs to be UX'd.

**Comment by happyconcepts** [comment]
[https://www.npmjs.com/browse/keyword/clipboard](https://www.npmjs.com/browse/keyword/clipboard)

several node packages are available for react...any favorites?

**Comment by wmbutler** [comment]
I'm closing this because I think this belongs in the receive / deposit area. I like the idea and plan to implement it in the appropriate place, but it'll be part of the deposit/withdraw rewrite.
