### ISSUE TITLE
[2] Fix copy issue on Withdraw modal

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1870]
When I try to copy anything inside Withdraw modal (even amount of money) I copy the following:

`PLEASE USE COPY BUTTON TO MAKE COPY OF ADDRESS OR MEMO ON THIS PAGE`

Estimate: .5h

**Comment by gibbsfromncis** [comment]
@startailcoon I've removed this terrible behavior at all for all Gateways + added new plugin for copy-to-clipboard. 

Because of terrible architecture of Withdraw/Deposit and that changes should be applied to all Gateways it took more time than expected. 

@startailcoon @wmbutler Please update an estimate to 1.5h

**Comment by gibbsfromncis** [comment]
PR: #1907

**Comment by startailcoon** [comment]
Works compared to before. Though, the reason we had this behavior before was due to the fact that it forced the users to copy the address through the "Copy" button. This would make sure that users doesn't get any extra characters while they copy, thinking it's part of the address. 

Can we have the same behavior after the update?

I believe this was done here for example: https://github.com/bitshares/bitshares-ui/pull/1907/files#diff-f17645e2b6268a11884cc80692cb2cf0L66

I've added some more time for this as well.

**Comment by gibbsfromncis** [comment]
@startailcoon Do you want to keep this behavior only if user tries to copy address or memo only?

**Comment by gibbsfromncis** [comment]
Added new component "DisableCopyText" and your feature request was implemented.

**Comment by abitmore** [comment]
Just a note: if to keep the "unable to copy with ctrl+c" behavior, please consider clearing the clipboard rather than filling it with something else. https://wallet.bitshares.org/#/account/undefined (account activity page 3) is an example that people have copied & pasted something wrong.

**Comment by wmbutler** [comment]
@abitmore @gibbsfromncis completely agree here. If we are going to disallow a copy operation, we should ensure we copy something blank to the clipboard. Otherwise the user may paste a previous address which could present a real problem.

**Comment by gibbsfromncis** [comment]
@abitmore @wmbutler I suppose proposed behavior is incorrect because it leaves user in dark and he doesn't know why he can't copy the wallet address. 

Current behavior:
- User tries to copy wallet address
- He copies "PLEASE USE COPY BUTTON TO MAKE COPY OF ADDRESS OR MEMO ON THIS PAGE" instead of address
- User press "copy address" / "copy memo" to copy everything correct
- User uses copied address / memo wherever he wants.

Proposed behavior:
- User tries to copy wallet address
- User copies NOTHING instead of address
- User tries to paste copied address or memo but no luck
- User becomes angry and want to kill him self because he spend 10 min trying to copy address or memo but his tries were unsuccessful and he had to re-type address by himself :/ 

Please tell me if I miss something

**Comment by startailcoon** [comment]
I agree with @gibbsfromncis here. The user needs to know about the recommend way to make a copy of the address/memo.

We just need to make sure the user doesn't get a bad value back instead of the message.

If the gateways returns a bad value, that's out of this issues scope.
