### ISSUE TITLE
[6] Gateway Modal ANT Implementation

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1872]
1. Update UI (use style-guide, fix UX issues)
2. Test it well for all bridges/gateways
3. Remove word "Beta" from menu
4. Decide something about old withdraw page

**Comment by startailcoon** [comment]
Related to #1479, UX for Send/Deposit/Withdraw beta -> legacy

**Comment by startailcoon** [comment]
Blocked by #1927

**Comment by wmbutler** [comment]
No longer blocked!!

**Comment by startailcoon** [comment]
Starting work on this issue

**Comment by startailcoon** [comment]
## Preview

![image](https://user-images.githubusercontent.com/12114550/53300362-49e32580-3846-11e9-9d6a-6883d061ec55.png)
