### ISSUE TITLE
[1] DEX: Total calculation (BTS) is not displayed correctly

### ISSUE THREAD

**Issue by steempower** [bitshares/bitshares-ui#188]
Total which should be a calculation of cumulative BTS on the orderbook sometime does some other calculation which results in weird display to total

http://i.imgur.com/9EJchqJ.png

**Comment by wmbutler** [comment]
I don't think I understand the problem based on your description. Can you clarify?

**Comment by wmbutler** [comment]
@steempower need clarification and steps to reproduce or I'll close this bug.

**Comment by steempower** [comment]
Sorry for the delay Bill,

The 'Total (BTS)' column is a cumulative total of all prior orders BTS values. In some situation the calculation of the cumulative value is not calculated correctly. 

For example: on the DEX right now on the WHALESHARES:BTS market - cumulative value is calculated correctly up until the 7th order (789.99353 | 5.10000 | 5 | 1.020) - after that the next order is for 1000 Whaleshares for 1000 BTS  so the expected 'Total (BTS)' should be 1789.99353 but it is calculated to 3267.96043 

http://i.imgur.com/HLQx4TC.png

Hope this makes it clearer

**Comment by wmbutler** [comment]
Thanks for the example.

**Comment by wmbutler** [comment]
Whaleshare appears to add up properly, but BTS does not.

![screen shot 2017-08-18 at 9 36 24 am](https://user-images.githubusercontent.com/1254810/29463576-cafe6b10-83f8-11e7-91b8-7bfc0bb1f836.png)

![screen shot 2017-08-18 at 9 36 33 am](https://user-images.githubusercontent.com/1254810/29463583-d8e381e8-83f8-11e7-8189-a4c356f6fc63.png)
