### ISSUE TITLE
[Exchange Refinement] Scrap Layout Selections

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1888]
I think that we should scrap the Layout Selections as part of the design in #1477.

As I've added back the option to pin the order book as part of issue #1873, we can do the following changes.

### Layout 1 and 2
Layout 1 and 2 has OrderBook, My Markets and Find Markets in the same column, which is very awkward I think. Switching tabs to look for a new market, to then switch back after the market is changed isn't good. We should keep them separated as before. 

Layout 1 is the same as Layout 5 with a pinned order book on left, markets on right.
Layout 2 is the same as Layout 5 with a pinned order book, but mirrored. 

A global option in Personalize should make it possible to set "Mirror Panels":Yes/No.
Both panels can be hidden independently.

### Layout 3 and 4
These have Buy/Sell in the same column as markets, still awkward.

I propose we put the forms in a left/right column, like order book in layout 1+2, if at all.

With a "Pin Buy/Sell Form" it could take the place for the order book in the side column. You can't pin both the form and the order book at the same time if you do this.

A global option in Personalize should make it possible to set "Mirror Panels":Yes/No.
Both panels can be hidden independently.

### Layout 5
This is the only layout left, which makes the selection option obsolete.

## Combined Details
Part of Layout 3+4 we have an option to combine/separate the details of market trades, my trades, open orders, settle orders.

What we could do, is to make an option to combine when we have limited space. 

An option in Personalize for "Combine details in limited space":"Yes/No".

This would combine the following in the following order as space gets smaller:
1. Combine "My Markets" and "Market Trades". Combine "My Open Orders" and "Settlement Orders".
2. Combine all four to one box. Combine Buy/Sell to a tabbed element.

This is one example on how to make it more dynamic. If the user chose "No", it will never combine and make it stack in a scrollable page, still nicer than today.

**Requested hours: ~3-4 hours**

**Comment by sschiessl-bcp** [comment]
If this is doable for the next release, my vote it has.

**Comment by startailcoon** [comment]
It's doable, we just need to finetune it in the end.

**Comment by startailcoon** [comment]
## Panel Grouping

The idea with this is that it should be quick and easy to setup a design style of the users choice. The four sections can be grouped in up to two groups or not at all.

Comments on this setup?

![bild](https://user-images.githubusercontent.com/12114550/46308724-aead9300-c5ba-11e8-9d0b-608c4e6ca2f7.png)

**Comment by wmbutler** [comment]
I really appreciate best practices and I hear repeatedly that users are happy with Binance's approach to the exchange layout. If we were to limit layouts, I'd go with theirs by default. Fundamentally I think that:

- My Trade History and Market Trade History can be the same column with a filter and can reside underneath My Markets on the right side
- I agree that All Markets and My Markets is an awkward tabbed interface and can go away. I also feel that a distinction between My Markets and starred markets is redundant. If it has a star, I think it should imply that it is in My Market, otherwise, it's not.
- Orderbook can be on the left side
- Open orders needs it's own container

The groups are interesting but I think I'll need to see it in practice because the definition and placement of a "Group" is not immediately intuitive to me.

**Comment by startailcoon** [comment]
Right now I'm working outwards from the UX that the current issue is built upon. Grouping settings is to make it more dynamic when I remove the "Layouts". 

This makes it possible to have a more dynamic default layout as well, and a pre defined grouping can be set for users. At the same time they can change this at will.

Some may not wish to use tabbed layouts at all, and some more wish to have all under one tab, which was one of the layouts in the UX design.

I will not do any larger change in the UX for this issue, and larger changes should be put in a new issue for discussions.

**Comment by startailcoon** [comment]
This is done and required 4 hours of work to complete.
