### ISSUE TITLE
TypeError: "u is undefined, can't access property "assetWithdrawlAlias" of it"

### ISSUE THREAD

**Issue by azartpay** [bitshares/bitshares-ui#1894]
TypeError: "u is undefined, can't access property "assetWithdrawlAlias" of it"

![a288796772](https://user-images.githubusercontent.com/39407862/45958265-73e2b280-c030-11e8-965d-3f2a64cfc10f.png)
![478849c8d6](https://user-images.githubusercontent.com/39407862/45958305-8d83fa00-c030-11e8-9593-14142b844720.png)

**Comment by startailcoon** [comment]
Duplicate of #1905
