### ISSUE TITLE
Large collection of suggestions I heard about from others

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [bitshares/bitshares-ui#190]
http://imgur.com/a/QAt6a (a-f images)

Quick summary:

a) buy borrow buttons are distractingly bad and different compared to rest of exchange design
b) newcomers mistake balance on top for how much bts they have, change to net worth or estimate e.g.. 
also all caps on name when everywhere else it's lower caps is confusing
c) no way to log out or make browser forget you easily
d) layouts should be adjustable easier, market depth should be on side of chart and show totals in both units, pair rotation is not obvious and has sig fig bug, autoscale on/off missing and messes up other pairs when off, reset view missing, maybe free library by tradingview is better for indicators for those who want it.
e) send needs note for only on-chain transaction and link to WITHDRAW for other blockchains, need to make choices for sending and fees more obvious
f) receive button should be added to clarify alias IS their address, provide QR code, and make it copiable. Additionally merchant type request systems for custom amounts should be incorporated to request specific amounts.

Hope this helps.

**Comment by viridys** [comment]
I support all of these suggestions. Maybe someone can make one or more workers for their development?

**Comment by wmbutler** [comment]
I'll break these into separate issues.

**Comment by wmbutler** [comment]
These are all getting distributed into issues. Closing it.
