### ISSUE TITLE
[10] Sophisticated ping strategy and background pinging

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1901]
<h2>Ping Strategy</h2>

The first step for the new ping strategy was completed with #1521

In the next step I propose to do a binary-tree like ping strategy.

- Ping 2 random nodes of each region
- Select 2 best regions, ping 2 random nodes in each country
- Select best country, ping all nodes within

The ping strategy stops when a sufficiently fast node has been found. If first iteration is not successfull, all nodes are pinged until a sufficiently fast one is found. In the next ping cycle the old region / country is remembered to accelerate pinging.

<h2>Background pinging</h2>

- After nodes with sufficient connectivity are found, the pinging will resume in the background

In order to achieve this it must be able to manually show the node list even if auto select is one.

**Comment by wmbutler** [comment]
Great strategy.

**Comment by sschiessl-bcp** [comment]
I will re-evaluate background pinging when doing this task (see #1940)

**Comment by startailcoon** [comment]
How is work progressing on this?

I'm looking forward to your work on background pinging as well

**Comment by sschiessl-bcp** [comment]
This is done, just not tested well enough due to delays. Will come soon.

**Comment by sschiessl-bcp** [comment]
I included the background pinging and increased the estimate, will adjust when done.

**Comment by sschiessl-bcp** [comment]
Done now. Hours have been updated, please adjust if not acceptable.

**Comment by sschiessl-bcp** [comment]
I have included a better UX for background pinging, took 1,5h more, including testing.
