### ISSUE TITLE
[.5] Click on "Buy Icon" on User Portfolio navigates to white blank screen

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1905]

**Comment by gibbsfromncis** [comment]
@wmbutler @startailcoon I did try to fix it but I discovered I have no idea what is an idea of "BUY" button. Can you please clarify it?

**Comment by startailcoon** [comment]
Buy modal is the BlockTrades in wallet trading feature. There was an error in the gatewayStatus object when assetWithdrawlAlias was missing.
