### ISSUE TITLE
Withdraw (old) Crashes APP when try to use Winnex 

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1906]
1. Go to withdraw (old)
2. Select "Winnex" 
3. App Crashes

Unfortunately our app remember the latest choice so if user once tried to select "Winnex" he doesn't have an access to Withdraw anymore. 

@wmbutler @startailcoon please lets decide something about old Withdraw/Deposit sections. Maybe lets remove it at all if we have already new Deposit/Withdraw modals?

**Comment by startailcoon** [comment]
This is also part of https://github.com/bitshares/bitshares-ui/issues/1905.

I will create a new Issue regarding the legacy gateway UX
