### ISSUE TITLE
[1] Warning message pops up when placing bid on pair that has no asks

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#191]
When you made a bid on a pair that has no asks on the books, a warning message that says "Please confirm the transaction, Your order is times higher than the lowest ask, are you sure?" pops up.

**Comment by wmbutler** [comment]
We need an exception for this case. Maybe the warning should say. 

"You are placing a trade order in a market with no open orders. Are you certain you wish to proceed?"
