### ISSUE TITLE
[UX:3][UI:4] Legacy Gateway UX

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1911]
This issue is for creating a new UX for the legacy Gateway/Bridge sections.

With the new Withdraw and Deposit (as well as Buy) modals we should retire the old section, as we currently will have two sections with the same feature.

The old gateway section is complex, and some even has an agreement that needs to be accepted, while it's not on the new Modal (which was agreed upon the PR with said gateway).

## Proposed Change
- Remove all asset deposit/withdraw handling
- Rename to `Gateways and Bridges`
- Remake to a details and general knowledge section where users can get details about gateways/bridges. Read who they are, where they operate, what their fees are etc, as well as clear contact details about who to reach out to and why it's not part of Bitshares.
- Link to the modals functions.

## Proposed hours: 
- UX: 3 hrs.
- UI: 4 hrs.

**Comment by startailcoon** [comment]
Assigned @nikandrovalex for UX

**Comment by gibbsfromncis** [comment]
@startailcoon @nikandrovalex is on vacation right now and going be back in few days.

**Comment by gibbsfromncis** [comment]
@startail please provide more details to @nikandrovalex because this section is not quite familiar for him.

**Comment by startailcoon** [comment]
This requires some creative thinking before we can start with the UX.

We need some text for this 
> Remake to a details and general knowledge section where users can get details about gateways/bridges. Read who they are, where they operate, what their fees are etc, as well as clear contact details about who to reach out to and why it's not part of Bitshares.

Essentially, red should be replaced, blue should be removed.


![bild](https://user-images.githubusercontent.com/12114550/46627704-93eb9900-cb3b-11e8-94f1-40959a4afd7d.png)

**Comment by startailcoon** [comment]
Removed UX assignement until we can find a rough mockup.
