### ISSUE TITLE
[2] Strip out non numerics when pasting into deposit/withdraw/send

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1912]
**Describe the bug**
Numbers containing non-numericvalues on the user clipboard fail to paste into the **quantity field** of deposit/withdraw/send modals.

**To Reproduce**
Copy a number with a comma and dollar sign (say $1,000) from a text file and paste it into the quantity field.

![paste](https://user-images.githubusercontent.com/1254810/46219007-c90e1500-c30b-11e8-9536-44cdfbbc129a.gif)

**Expected behavior**
Number 1000 should appear in the quantity field.

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser: Chrome
 - Version: Latest

**Comment by startailcoon** [comment]
Reverted my commit `794df16` as it doesn't do what was requested. I was unable to find a good way to solve this issue.

I've unassinged myself for now

**Comment by wmbutler** [comment]
@sschiessl-bcp can you help here? This really needs to be addressed.

**Comment by sschiessl-bcp** [comment]
Will do

**Comment by sschiessl-bcp** [comment]
The solution looks easy, but required some trial & error. Please increase to 2 hours.
