### ISSUE TITLE
No method with name 'get_account'"

### ISSUE THREAD

**Issue by romy2012** [bitshares/bitshares-ui#1913]
Started POST "/api/v1/accounts" for 127.0.0.1 at 2018-09-29 18:16:47 +0800
Processing by Api::V1::AccountsController#create as JSON
  Parameters: {"account"=>{"name"=>"romy2018", "owner_key"=>"GPH68FsLa19HeoKZn13Bv6s8wVTT2zg26LKZDYNQXFnfErZGX1DYy", "active_key"=>"GPH75wSRshrfp6UZsp1HRamihCiKhQfvW5i7Qcr6yba8Hpp6UJEBE", "memo_key"=>"GPH5G2UiG6Q2oSQmMQ1fniCTyoSxrHBKshvGZncLQuH2vFpNLGjRV", "refcode"=>nil, "referrer"=>nil}}
   (5.4ms)  BEGIN
  BtsAccount Exists (0.4ms)  SELECT  1 AS one FROM `bts_accounts` WHERE `bts_accounts`.`remote_ip` = BINARY '127.0.0.1' AND (created_at > '2018-09-29 18:11:47') LIMIT 1
---- Registering account: 'romy2018' GPH68FsLa19HeoKZn13Bv6s8wVTT2zg26LKZDYNQXFnfErZGX1DYy/GPH75wSRshrfp6UZsp1HRamihCiKhQfvW5i7Qcr6yba8Hpp6UJEBE referrer: 
call: [0, "get_account", ["romy2018"]]
call: [0, "get_account", ["romy2018"]]
Websocket RPC Error: {"code"=>1, "message"=>"Assert Exception: itr != _by_name.end(): no method with name 'get_account'", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"api_connection.hpp", "line"=>111, "method"=>"call", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:47"}, "format"=>"itr != _by_name.end(): no method with name '${name}'", "data"=>{"name"=>"get_account", "api"=>[["cancel_all_subscriptions", 4], ["get_24_volume", 44], ["get_account_balances", 25], ["get_account_by_name", 20], ["get_account_count", 24], ["get_account_id_from_string", 17], ["get_account_limit_orders", 36], ["get_account_references", 21], ["get_accounts", 18], ["get_all_workers", 56], ["get_asset_count", 33], ["get_assets", 30], ["get_balance_objects", 27], ["get_blinded_balances", 70], ["get_block", 7], ["get_block_header", 5], ["get_block_header_batch", 6], ["get_call_orders", 37], ["get_chain_id", 13], ["get_chain_properties", 10], ["get_collateral_bids", 40], ["get_committee_count", 55], ["get_committee_member_by_account", 53], ["get_committee_members", 52], ["get_config", 12], ["get_dynamic_global_properties", 14], ["get_full_accounts", 19], ["get_global_properties", 11], ["get_key_references", 15], ["get_limit_orders", 35], ["get_margin_positions", 39], ["get_named_account_balances", 26], ["get_objects", 0], ["get_order_book", 34], ["get_potential_address_signatures", 64], ["get_potential_signatures", 63], ["get_proposed_transactions", 69], ["get_recent_transaction_by_id", 9], ["get_required_fees", 68], ["get_required_signatures", 62], ["get_settle_orders", 38], ["get_ticker", 43], ["get_top_markets", 45], ["get_trade_history", 46], ["get_trade_history_by_sequence", 47], ["get_transaction", 8], ["get_transaction_hex", 60], ["get_transaction_hex_without_sig", 61], ["get_vested_balances", 28], ["get_vesting_balances", 29], ["get_withdraw_permissions_by_giver", 71], ["get_withdraw_permissions_by_recipient", 72], ["get_witness_by_account", 49], ["get_witness_count", 51], ["get_witnesses", 48], ["get_worker_count", 58], ["get_workers_by_account", 57], ["is_public_key_registered", 16], ["list_assets", 31], ["lookup_account_names", 22], ["lookup_accounts", 23], ["lookup_asset_symbols", 32], ["lookup_committee_member_accounts", 54], ["lookup_vote_ids", 59], ["lookup_witness_accounts", 50], ["set_block_applied_callback", 3], ["set_pending_transaction_callback", 2], ["set_subscribe_callback", 1], ["subscribe_to_market", 41], ["unsubscribe_from_market", 42], ["validate_transaction", 67], ["verify_account_authority", 66], ["verify_authority", 65]]}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:47"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "get_account", ["romy2018"]]}}]}}
Websocket RPC Error: {"code"=>1, "message"=>"Assert Exception: itr != _by_name.end(): no method with name 'get_account'", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"api_connection.hpp", "line"=>111, "method"=>"call", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:47"}, "format"=>"itr != _by_name.end(): no method with name '${name}'", "data"=>{"name"=>"get_account", "api"=>[["cancel_all_subscriptions", 4], ["get_24_volume", 44], ["get_account_balances", 25], ["get_account_by_name", 20], ["get_account_count", 24], ["get_account_id_from_string", 17], ["get_account_limit_orders", 36], ["get_account_references", 21], ["get_accounts", 18], ["get_all_workers", 56], ["get_asset_count", 33], ["get_assets", 30], ["get_balance_objects", 27], ["get_blinded_balances", 70], ["get_block", 7], ["get_block_header", 5], ["get_block_header_batch", 6], ["get_call_orders", 37], ["get_chain_id", 13], ["get_chain_properties", 10], ["get_collateral_bids", 40], ["get_committee_count", 55], ["get_committee_member_by_account", 53], ["get_committee_members", 52], ["get_config", 12], ["get_dynamic_global_properties", 14], ["get_full_accounts", 19], ["get_global_properties", 11], ["get_key_references", 15], ["get_limit_orders", 35], ["get_margin_positions", 39], ["get_named_account_balances", 26], ["get_objects", 0], ["get_order_book", 34], ["get_potential_address_signatures", 64], ["get_potential_signatures", 63], ["get_proposed_transactions", 69], ["get_recent_transaction_by_id", 9], ["get_required_fees", 68], ["get_required_signatures", 62], ["get_settle_orders", 38], ["get_ticker", 43], ["get_top_markets", 45], ["get_trade_history", 46], ["get_trade_history_by_sequence", 47], ["get_transaction", 8], ["get_transaction_hex", 60], ["get_transaction_hex_without_sig", 61], ["get_vested_balances", 28], ["get_vesting_balances", 29], ["get_withdraw_permissions_by_giver", 71], ["get_withdraw_permissions_by_recipient", 72], ["get_witness_by_account", 49], ["get_witness_count", 51], ["get_witnesses", 48], ["get_worker_count", 58], ["get_workers_by_account", 57], ["is_public_key_registered", 16], ["list_assets", 31], ["lookup_account_names", 22], ["lookup_accounts", 23], ["lookup_asset_symbols", 32], ["lookup_committee_member_accounts", 54], ["lookup_vote_ids", 59], ["lookup_witness_accounts", 50], ["set_block_applied_callback", 3], ["set_pending_transaction_callback", 2], ["set_subscribe_callback", 1], ["subscribe_to_market", 41], ["unsubscribe_from_market", 42], ["validate_transaction", 67], ["verify_account_authority", 66], ["verify_authority", 65]]}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:47"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "get_account", ["romy2018"]]}}]}}
call: [0, "register_account", ["romy2018", "GPH68FsLa19HeoKZn13Bv6s8wVTT2zg26LKZDYNQXFnfErZGX1DYy", "GPH75wSRshrfp6UZsp1HRamihCiKhQfvW5i7Qcr6yba8Hpp6UJEBE", "nathan", "nathan", 0, true]]
call: [0, "register_account", ["romy2018", "GPH68FsLa19HeoKZn13Bv6s8wVTT2zg26LKZDYNQXFnfErZGX1DYy", "GPH75wSRshrfp6UZsp1HRamihCiKhQfvW5i7Qcr6yba8Hpp6UJEBE", "nathan", "nathan", 0, true]]
Websocket RPC Error: {"code"=>1, "message"=>"Assert Exception: itr != _by_name.end(): no method with name 'register_account'", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"api_connection.hpp", "line"=>111, "method"=>"call", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:48"}, "format"=>"itr != _by_name.end(): no method with name '${name}'", "data"=>{"name"=>"register_account", "api"=>[["cancel_all_subscriptions", 4], ["get_24_volume", 44], ["get_account_balances", 25], ["get_account_by_name", 20], ["get_account_count", 24], ["get_account_id_from_string", 17], ["get_account_limit_orders", 36], ["get_account_references", 21], ["get_accounts", 18], ["get_all_workers", 56], ["get_asset_count", 33], ["get_assets", 30], ["get_balance_objects", 27], ["get_blinded_balances", 70], ["get_block", 7], ["get_block_header", 5], ["get_block_header_batch", 6], ["get_call_orders", 37], ["get_chain_id", 13], ["get_chain_properties", 10], ["get_collateral_bids", 40], ["get_committee_count", 55], ["get_committee_member_by_account", 53], ["get_committee_members", 52], ["get_config", 12], ["get_dynamic_global_properties", 14], ["get_full_accounts", 19], ["get_global_properties", 11], ["get_key_references", 15], ["get_limit_orders", 35], ["get_margin_positions", 39], ["get_named_account_balances", 26], ["get_objects", 0], ["get_order_book", 34], ["get_potential_address_signatures", 64], ["get_potential_signatures", 63], ["get_proposed_transactions", 69], ["get_recent_transaction_by_id", 9], ["get_required_fees", 68], ["get_required_signatures", 62], ["get_settle_orders", 38], ["get_ticker", 43], ["get_top_markets", 45], ["get_trade_history", 46], ["get_trade_history_by_sequence", 47], ["get_transaction", 8], ["get_transaction_hex", 60], ["get_transaction_hex_without_sig", 61], ["get_vested_balances", 28], ["get_vesting_balances", 29], ["get_withdraw_permissions_by_giver", 71], ["get_withdraw_permissions_by_recipient", 72], ["get_witness_by_account", 49], ["get_witness_count", 51], ["get_witnesses", 48], ["get_worker_count", 58], ["get_workers_by_account", 57], ["is_public_key_registered", 16], ["list_assets", 31], ["lookup_account_names", 22], ["lookup_accounts", 23], ["lookup_asset_symbols", 32], ["lookup_committee_member_accounts", 54], ["lookup_vote_ids", 59], ["lookup_witness_accounts", 50], ["set_block_applied_callback", 3], ["set_pending_transaction_callback", 2], ["set_subscribe_callback", 1], ["subscribe_to_market", 41], ["unsubscribe_from_market", 42], ["validate_transaction", 67], ["verify_account_authority", 66], ["verify_authority", 65]]}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:48"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "register_account", ["romy2018", "GPH68FsLa19HeoKZn13Bv6s8wVTT2zg26LKZDYNQXFnfErZGX1DYy", "GPH75wSRshrfp6UZsp1HRamihCiKhQfvW5i7Qcr6yba8Hpp6UJEBE", "nathan", "nathan", 0, true]]}}]}}
Websocket RPC Error: {"code"=>1, "message"=>"Assert Exception: itr != _by_name.end(): no method with name 'register_account'", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"api_connection.hpp", "line"=>111, "method"=>"call", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:48"}, "format"=>"itr != _by_name.end(): no method with name '${name}'", "data"=>{"name"=>"register_account", "api"=>[["cancel_all_subscriptions", 4], ["get_24_volume", 44], ["get_account_balances", 25], ["get_account_by_name", 20], ["get_account_count", 24], ["get_account_id_from_string", 17], ["get_account_limit_orders", 36], ["get_account_references", 21], ["get_accounts", 18], ["get_all_workers", 56], ["get_asset_count", 33], ["get_assets", 30], ["get_balance_objects", 27], ["get_blinded_balances", 70], ["get_block", 7], ["get_block_header", 5], ["get_block_header_batch", 6], ["get_call_orders", 37], ["get_chain_id", 13], ["get_chain_properties", 10], ["get_collateral_bids", 40], ["get_committee_count", 55], ["get_committee_member_by_account", 53], ["get_committee_members", 52], ["get_config", 12], ["get_dynamic_global_properties", 14], ["get_full_accounts", 19], ["get_global_properties", 11], ["get_key_references", 15], ["get_limit_orders", 35], ["get_margin_positions", 39], ["get_named_account_balances", 26], ["get_objects", 0], ["get_order_book", 34], ["get_potential_address_signatures", 64], ["get_potential_signatures", 63], ["get_proposed_transactions", 69], ["get_recent_transaction_by_id", 9], ["get_required_fees", 68], ["get_required_signatures", 62], ["get_settle_orders", 38], ["get_ticker", 43], ["get_top_markets", 45], ["get_trade_history", 46], ["get_trade_history_by_sequence", 47], ["get_transaction", 8], ["get_transaction_hex", 60], ["get_transaction_hex_without_sig", 61], ["get_vested_balances", 28], ["get_vesting_balances", 29], ["get_withdraw_permissions_by_giver", 71], ["get_withdraw_permissions_by_recipient", 72], ["get_witness_by_account", 49], ["get_witness_count", 51], ["get_witnesses", 48], ["get_worker_count", 58], ["get_workers_by_account", 57], ["is_public_key_registered", 16], ["list_assets", 31], ["lookup_account_names", 22], ["lookup_accounts", 23], ["lookup_asset_symbols", 32], ["lookup_committee_member_accounts", 54], ["lookup_vote_ids", 59], ["lookup_witness_accounts", 50], ["set_block_applied_callback", 3], ["set_pending_transaction_callback", 2], ["set_subscribe_callback", 1], ["subscribe_to_market", 41], ["unsubscribe_from_market", 42], ["validate_transaction", 67], ["verify_account_authority", 66], ["verify_authority", 65]]}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:48"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "register_account", ["romy2018", "GPH68FsLa19HeoKZn13Bv6s8wVTT2zg26LKZDYNQXFnfErZGX1DYy", "GPH75wSRshrfp6UZsp1HRamihCiKhQfvW5i7Qcr6yba8Hpp6UJEBE", "nathan", "nathan", 0, true]]}}]}}
!!! register_account error: {"code"=>1, "message"=>"Assert Exception: itr != _by_name.end(): no method with name 'register_account'", "data"=>{"code"=>10, "name"=>"assert_exception", "message"=>"Assert Exception", "stack"=>[{"context"=>{"level"=>"error", "file"=>"api_connection.hpp", "line"=>111, "method"=>"call", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:48"}, "format"=>"itr != _by_name.end(): no method with name '${name}'", "data"=>{"name"=>"register_account", "api"=>[["cancel_all_subscriptions", 4], ["get_24_volume", 44], ["get_account_balances", 25], ["get_account_by_name", 20], ["get_account_count", 24], ["get_account_id_from_string", 17], ["get_account_limit_orders", 36], ["get_account_references", 21], ["get_accounts", 18], ["get_all_workers", 56], ["get_asset_count", 33], ["get_assets", 30], ["get_balance_objects", 27], ["get_blinded_balances", 70], ["get_block", 7], ["get_block_header", 5], ["get_block_header_batch", 6], ["get_call_orders", 37], ["get_chain_id", 13], ["get_chain_properties", 10], ["get_collateral_bids", 40], ["get_committee_count", 55], ["get_committee_member_by_account", 53], ["get_committee_members", 52], ["get_config", 12], ["get_dynamic_global_properties", 14], ["get_full_accounts", 19], ["get_global_properties", 11], ["get_key_references", 15], ["get_limit_orders", 35], ["get_margin_positions", 39], ["get_named_account_balances", 26], ["get_objects", 0], ["get_order_book", 34], ["get_potential_address_signatures", 64], ["get_potential_signatures", 63], ["get_proposed_transactions", 69], ["get_recent_transaction_by_id", 9], ["get_required_fees", 68], ["get_required_signatures", 62], ["get_settle_orders", 38], ["get_ticker", 43], ["get_top_markets", 45], ["get_trade_history", 46], ["get_trade_history_by_sequence", 47], ["get_transaction", 8], ["get_transaction_hex", 60], ["get_transaction_hex_without_sig", 61], ["get_vested_balances", 28], ["get_vesting_balances", 29], ["get_withdraw_permissions_by_giver", 71], ["get_withdraw_permissions_by_recipient", 72], ["get_witness_by_account", 49], ["get_witness_count", 51], ["get_witnesses", 48], ["get_worker_count", 58], ["get_workers_by_account", 57], ["is_public_key_registered", 16], ["list_assets", 31], ["lookup_account_names", 22], ["lookup_accounts", 23], ["lookup_asset_symbols", 32], ["lookup_committee_member_accounts", 54], ["lookup_vote_ids", 59], ["lookup_witness_accounts", 50], ["set_block_applied_callback", 3], ["set_pending_transaction_callback", 2], ["set_subscribe_callback", 1], ["subscribe_to_market", 41], ["unsubscribe_from_market", 42], ["validate_transaction", 67], ["verify_account_authority", 66], ["verify_authority", 65]]}}, {"context"=>{"level"=>"warn", "file"=>"websocket_api.cpp", "line"=>125, "method"=>"on_message", "hostname"=>"", "thread_name"=>"th_a", "timestamp"=>"2018-09-29T10:16:48"}, "format"=>"", "data"=>{"call.method"=>"call", "call.params"=>[0, "register_account", ["romy2018", "GPH68FsLa19HeoKZn13Bv6s8wVTT2zg26LKZDYNQXFnfErZGX1DYy", "GPH75wSRshrfp6UZsp1HRamihCiKhQfvW5i7Qcr6yba8Hpp6UJEBE", "nathan", "nathan", 0, true]]}}]}}
   (0.3ms)  ROLLBACK
Completed 422 Unprocessable Entity in 196ms (Views: 0.2ms | ActiveRecord: 6.1ms)

**Comment by startailcoon** [comment]
This looks very strange. Is this really related to the Bitshares UI, and if so, where do you get this error output.

A few more details would go a long way in helping you with any issues you may have.

**Comment by clockworkgr** [comment]
This seems to be faucet and API related not bitshares-ui.

Also OP has not responded.

Closing.
