### ISSUE TITLE
[2] Duplicate Orders On Order Book/Open Orders

### ISSUE THREAD

**Issue by arminnaderi** [bitshares/bitshares-ui#1917]
**Describe the bug**

A duplicate order shows up on the order book/open orders when opening up the UI for the first time. 

**To Reproduce**

It is very difficult to reproduce. You have to create an order and open up the UI at the exact same time. This results:

First, the orders are loaded from the account balances.
Then, the market subscribe callback notifies of an order being created.
The result is that the order that was **just** created is duplicated on the order book and open orders within the account dashboard.

**Expected behavior**

The order that was created at the same time the UI was loaded should only be displayed once. 

**Screenshots**

<img width="213" alt="screen shot 2018-09-29 at 7 22 50 pm" src="https://user-images.githubusercontent.com/16402451/46251633-0ebb0280-c41e-11e8-8f08-3fd99976a438.png">

**Desktop (please complete the following information):**
 - MACOS
 - Chrome
 - Bitshares UI version = all versions within the past year

**Other Notes**

The problem is solved if you reload the UI. However, the problem can occur twice in a row if you try to reproduce the problem again (creating an order at the same time as loading the UI).

**How To Solve**

It is impractical to resolve this on the witness_node side (as explained in dev discussions), the solution is to convert the account balances and order book constructs into "sets" instead of "lists." This way there won't be any duplicate orders added no matter what the synchronization of the calls are.

**Warning:** Using a set can introduce a performance problem, however you can solve this by:

1. Keeping the lists, but also adding an additional set copy of the bid/asks.
2. When a new order arrives, add it to the set. 
3. Check if the set's size increased. If it did, add the element to the list as well.

**Comment by arminnaderi** [comment]
Yeah, that's why I was hesitant to report it. It's an edge case and won't affect most users.

**Comment by startailcoon** [comment]
Added 2 hours for researching about issues regarding this behavior. It's a visual issue, happening in rare occasions and may be difficult to find where to start.

**Comment by sschiessl-bcp** [comment]
Quote from armin
"If you call get_limit_orders at the same time an order was created, the subscribe_callback will fire at the same time and u will get 2 orders added to your order book"

**Comment by abitmore** [comment]
IIRC order IDs are returned by `get_limit_orders`, so UI should be able to identify and handle the duplicates.

**Comment by arminnaderi** [comment]
Actually, after further research, it seems like the bug isn't worth fixing.

1. It won't happen for almost all users anyway, it's a massive edge case.
2. If its fixed it will cause performance/require massive refactoring
3. If it's fixed in a simple way, ie checking for duplicates before inserting into a list (O(n) complexity), it will be 100x slower than the set implementation (I tested this out)

**Comment by sschiessl-bcp** [comment]
I concur with @arminnaderi  on this one.

Closing this one, please get in touch with @startailcoon to finalize.

**Comment by startailcoon** [comment]
I thank you @arminnaderi for further digging into this issue, and with the result you display I think it's not worth making a fix for.

**Comment by Jackcameback** [comment]
@arminnaderi Could you please submit your bit shares address?

**Comment by gibbsfromncis** [comment]
@arminnaderi please send us your bitshares account name you would like to receive bounty.

**Comment by arminnaderi** [comment]
@gibbsfromncis I've sent it to Stefan
