### ISSUE TITLE
"Switch to wallet model" on login doesn't explain where to put .bin file

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [bitshares/bitshares-ui#192]
People returning with both .bin and password can't figure out how to log in using wallet model. This issue came up 5 times this month alone. 

Typical process goes as such:

1) bitshares.org/wallet
2) login with password button (since there's no other)
3) switch to wallet model bottom right (if they notice it after failing to log in using password alone)
4) http://i.imgur.com/cJjbeBi.png All they see is "You do not have a wallet yet" with a single option to create new wallet.
5) Typically this is where they create a new wallet and get really confused and give up

Now I know they should go to settings (gear icon) and then Restore/Import, choose file, choose and upload .bin file, put in password for it, and hit restore button to log in. 

**But they do not know that unless they search for long time.**

Solution:
A) The entire Restore/Import part should be moved to "wallet model" login instead of giving "You do not have a wallet yet" and if they do have a wallet, then just regular password unlock.
B) link to Restore/Import page directly from there until they restored.

**Comment by wmbutler** [comment]
Agreed that the onboarding process needs more clarity.

**Comment by Ashaman-** [comment]
A restore backup button next to Login with Password would solve this.

**Comment by wmbutler** [comment]
Completed with login rewrite.
