### ISSUE TITLE
Upgrade ant in bitshares-ui-style-guide from v3.6.4 to v3.10.0

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1923]
Todo:

- [x] Upgrade ant from `v3.6.4` to `v3.10.0` 
- [x] Check all components we use everything fine

UPDATED: @startailcoon @wmbutler based on issues I found please put estimate 5h 

Fixes found after the review:

- [x] Popover
- [x] Collapsed list
- [x] Drag&Drop
- [x] Switches
- [x] Tables

**Comment by gibbsfromncis** [comment]
Done by commits:
https://github.com/bitshares/bitshares-ui-style-guide/commit/2930a268b946e2c4c113e2edc2de393fe1df023b

**Comment by gibbsfromncis** [comment]
There are the following issues after upgrade:

1. Collapsed list arrows went down
<img width="1173" alt="1" src="https://user-images.githubusercontent.com/35899973/46386076-aee38680-c6bf-11e8-9c6c-1d47dc8eebe0.png">

2. Drag&Drop area has additional space in top/bottom
<img width="393" alt="2" src="https://user-images.githubusercontent.com/35899973/46386102-cb7fbe80-c6bf-11e8-85aa-1140c2c7f58e.png">

3. Switches become totally different from our style-guide
<img width="289" alt="3" src="https://user-images.githubusercontent.com/35899973/46386103-cde21880-c6bf-11e8-8a17-bc9c30157ea4.png">

4. Tables icons went down, wrong hovers etc.
<img width="1193" alt="4" src="https://user-images.githubusercontent.com/35899973/46386107-d0447280-c6bf-11e8-928e-d0e52d903aa0.png">
<img width="1204" alt="5" src="https://user-images.githubusercontent.com/35899973/46386110-d2a6cc80-c6bf-11e8-84d1-55fe2c484f59.png">

**Comment by gibbsfromncis** [comment]
@startailcoon @wmbutler it would be better to spend one hour each month to upgrade ant to the last version than do upgrade each 5 month and make a lot of fixes...

**Comment by gibbsfromncis** [comment]
Done by these commits:
https://github.com/bitshares/bitshares-ui-style-guide/commit/9676b8c01492568b704d88b8c8a9b1f0892ea37d
https://github.com/bitshares/bitshares-ui-style-guide/commit/805933a21f1d025e92cadab2de7fbb43bef44d17
https://github.com/bitshares/bitshares-ui-style-guide/commit/c4c2399761b1e8928b6e023c082011ab968046cd
https://github.com/bitshares/bitshares-ui-style-guide/commit/61db4787d7599f7b3bf0c13b5cd87556f515d5bf
https://github.com/bitshares/bitshares-ui-style-guide/commit/2930a268b946e2c4c113e2edc2de393fe1df023b
https://github.com/bitshares/bitshares-ui-style-guide/commit/b287fadab9b655d50d09bd6d002dee3caae96c39

**Comment by startailcoon** [comment]
@gibbsfromncis fully agree. Please add it to your todo list each month. 👍
