### ISSUE TITLE
[~8] Provide easy way to add custom templates for Style Guide

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1925]
For now if any user wants to create his own theme for Reference Wallet it was possible to do within Reference Wallet fork. 

But when we start to work with Style Guide this ability was broken because if user of Reference Wallet start to use his own theme with different name like "myCustomTheme" all Style Guide components become broken.

The idea is to architect and provide an instruction how developers can create and use their custom themes. 

- [ ] Remove hardcode of 3 themes inside Style Guide Project
- [ ] Provide an ability to easily manage available Style-Guide themes with custom names also
- [ ] Instruction how to easily manage/use Style-Guide themes

Requested estimate: 8h

@wmbutler @startailcoon it's a little bit hard to estimate this issue because there are situations I have no idea how I'm going to solve before I start to work on this. I hope 8h is fair estimate and it's enough.

**Comment by startailcoon** [comment]
This would be a nice thing. Acknowledge that estimated hours are rough and can change. It's a task that needs to take its time

**Comment by gibbsfromncis** [comment]
@startailcoon I'll put it to next milestone if you agree.

**Comment by sschiessl-bcp** [comment]
Please add a reason for closure. I assume due to redesign?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp because I'll rethink how style-guide works when we start redesign, you're correct.
