### ISSUE TITLE
[6][kapeer42][1][gibbsfromncis] ANT Replacement for Asset Selector

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#1927]
Replace `Asset Selector` dropdown with ANT components.

Example issue #1872 

![image](https://user-images.githubusercontent.com/12114550/46503910-a8bee880-c82c-11e8-9941-bd8cbd730c6c.png)

**Comment by gibbsfromncis** [comment]
@startailcoon please create an additional component `AssetSelector` we will be able to use everywhere and make it based on ant components. But I suppose it was your plan :)

**Comment by kapeer42** [comment]
Can I claim this?

**Comment by kapeer42** [comment]
@gibbsfromncis  Currently I only have #1578 assigned and not pushed so I'm not sure what you are referring to, can you elaborate please?

**Comment by gibbsfromncis** [comment]
@kapeer42 Honestly the fact that you don't know about issues where you claimed by your requests inspires me distrust of you

You have 2 additional issues:
#1539
#1536

**Comment by kapeer42** [comment]
@gibbsfromncis 
#1539 is closed from my point of view.
#1536 is pushed.

**Comment by gibbsfromncis** [comment]
@kapeer42 What does it mean that it is closed from yours point of view? You still assigned and this task has milestone. Did you ask somebody to unclaim you?

**Comment by kapeer42** [comment]
@gibbsfromncis It means that I think that once all people involved in it will read the comment thread it will be closed.

**Comment by gibbsfromncis** [comment]
@kapeer42 I do not see the reason to continue our discussion. The fast is that you still assigned to #1539 and you didn't ask anybody to unassign you. Another fact is that you found reasons why you didn't close #1578 for the last few weeks and going to take another one. 

My idea was just to ask you to be more fair and I didn't want to start so large discussions. 

I'm just a developer like you and I have no rights to say you what you should do.

**Comment by startailcoon** [comment]
@kapeer42 I've assigned this to you. Please communicate with @gibbsfromncis regarding issues with ANT implementation.

**Comment by gibbsfromncis** [comment]
@kapeer42 please let me know when you are going to finish this task because it blocks me

**Comment by gibbsfromncis** [comment]
@startailcoon I've added `.25h` to this task because of time I spent to review & test PR #2099. If this PR will require additional testing & review I'll adjust hours.

**Comment by startailcoon** [comment]
Increased hours as stated in PR

**Comment by gibbsfromncis** [comment]
Adjusted hours because of additional time I spent on the review.

**Comment by gibbsfromncis** [comment]
@startailcoon added additional 0.5 hours

**Comment by gibbsfromncis** [comment]
@kapeer42 please do not forget to say thank you to @sschiessl-bcp. He took care of your task and we finally closed it. Please be more responsible next time when you take important task which blocks us.
