### ISSUE TITLE
Displaying MPA collateral ratios ?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#193]
Hey,

Would it be possible to display users MPA collateral ratios from within the Bitshares UI?

The only place to view this is on cryptofresh which is sometimes down, having this information within the client will enable users to set more appropriate collateral ratios in comparison to other users, so as to not be the least collateralized user.

Cheers 👍

**Comment by wmbutler** [comment]
Agreed that this would be a nice feature. In particular, it would be nice to see where your account stands relative others to see when / if you might be margin called. A further addition would be a means of notifying a user so they can take action.

**Comment by svk31** [comment]
This is impossible given the current available APIs, and highly unlikely to get added since it would require the witness_node to track all asset holders for all assets which is probably way too expensive in terms of performance and memory.

**Comment by grctest** [comment]
You mean the full_node rather than the witness_node, given that the web/light wallets talk to full nodes not the witnesses?

So this would require a change in bitshares-core prior to being possible within the bitshares-ui? Time to make a new github issue: https://github.com/bitshares/bitshares-core/issues/362

**Comment by svk31** [comment]
I mean witness_node as in the bitshares-core executable, which is what's run by both witnesses and API servers. What differs between them is simply their configuration settings.

**Comment by abitmore** [comment]
The `get_call_orders` API doesn't work? It can be used to get all short positions of one MPA.

**Comment by abitmore** [comment]
I think this can be added in the asset info page.

**Comment by wmbutler** [comment]
This issue has a lot of positive feedback. Agreed it make a lot of sense in the asset explorer. I'll UX this. Current HERO asset view pre UX:

![screen shot 2017-08-16 at 8 41 34 am](https://user-images.githubusercontent.com/1254810/29366134-c8f9bf54-825e-11e7-86d0-3e5e5c67bb19.png)

**Comment by wmbutler** [comment]
This was completed.
