### ISSUE TITLE
Ping nodes in background

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1940]
@svk31 @sschiessl-bcp @startailcoon  

Maybe I do not understand something but I start to hate my life when I see this message and should spend valuable hours of my life waiting while we do ping of all nodes.

1. What is the reason of this? 
2. Can we start to ping nodes and hide window when find any node with > 500ms node latency and continue pinging in background?

**Comment by sschiessl-bcp** [comment]
#1901
