### ISSUE TITLE
[Foundation Elimination] Button & Button Group

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1946]
Ideally **all** buttons should be replaced by ANT buttons.

**Comment by gibbsfromncis** [comment]
As I see we use `button` className in more than 300 places so it is hard work and also foundation buttons do not affect to style-guide `Button` so there is no reason to put so much effort.

**Comment by AboShanab** [comment]
@gibbsfromncis Is there's future plans to research about easier way for this issue?

**Comment by gibbsfromncis** [comment]
@AboShanab what do you mean?

**Comment by gibbsfromncis** [comment]
The task is closed. We won't replace foundation buttons for ant because we have more than 500 buttons across application

**Comment by startailcoon** [comment]
We should work towards replacing them old `<button>` with ANT replacement as we work on new implementations and code changes.

**Comment by startailcoon** [comment]
Yes, we're both saying the same thing here 👍

No use to do them all now, better to replace them as we go.
