### ISSUE TITLE
[Foundation Elimination] Modal

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1951]
Replace all Foundation Modals for ant Modals:

- [x] Phase I #1992
- [x] Phase II #1993 
- [x] Phase III #1994 
- [x] Phase IV #1995

**Comment by gibbsfromncis** [comment]
New Wallet Unlock Modal:

<img width="562" alt="screenshot 2018-10-11 05 34 13" src="https://user-images.githubusercontent.com/35899973/46777225-7bd07100-cd17-11e8-94ac-a2878b008014.png">

<img width="544" alt="screenshot 2018-10-11 05 35 49" src="https://user-images.githubusercontent.com/35899973/46777235-8559d900-cd17-11e8-9a70-d4711a7a1df5.png">

**Comment by gibbsfromncis** [comment]
### Add Node Modal

<img width="545" alt="screenshot 2018-10-11 06 09 43" src="https://user-images.githubusercontent.com/35899973/46778425-424e3480-cd1c-11e8-8e26-518b7cfe389d.png">

**Comment by gibbsfromncis** [comment]
### Chart Options Modal

<img width="461" alt="screenshot 2018-10-11 06 37 19" src="https://user-images.githubusercontent.com/35899973/46779363-20ef4780-cd20-11e8-92de-3b26bf6b2a54.png">

**Comment by gibbsfromncis** [comment]
### Deposit Modal

<img width="562" alt="screenshot 2018-10-11 07 36 29" src="https://user-images.githubusercontent.com/35899973/46781060-6b74c200-cd28-11e8-9e66-4e0fef21a8ea.png">

**Comment by startailcoon** [comment]
Do you have an estimate for this task?

**Comment by gibbsfromncis** [comment]
@startailcoon still working on it and I have no idea how much time will it take. We have around 70 modals. Most of them are in unused components but anyway it's large task I'm still working on

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp what kind of changes to UX you see?

### Old
<img width="507" alt="screenshot 2018-10-15 15 26 28" src="https://user-images.githubusercontent.com/35899973/46950854-d149ac80-d08e-11e8-8062-d5afa851dc52.png">

### New
<img width="507" alt="screenshot 2018-10-15 15 26 28" src="https://user-images.githubusercontent.com/35899973/46781162-f81f8000-cd28-11e8-8cb8-056474f328ba.png">

The task was to replace Foundation Modals for Ant Modals. Nothing in UX changed except:
1) Logo is missed (My bad)
2) Headers of Modals (title) was moved from Modal content to Modal header regarding our Style-Guide. 

So I didn't make any changes in UX based on my own choice. If you do not like something the issue is in Style-Guide UX. 

We already have the issue to discuss style-guide modals - https://github.com/bitshares/bitshares-ui/issues/2014

**Comment by sschiessl-bcp** [comment]
Please close when all sub-tasks are done and keep for general tracking in the meantime.

**Comment by sschiessl-bcp** [comment]
> what kind of changes to UX you see?

I overreacted. The modals look quite different but quite similar. Only thing missing is the highlight of the account name.

**Comment by startailcoon** [comment]
Great work, it's good to have these done as well. The only thing that I react on is the title of the modal is moved from a larger centered text to a smaller header of the modal.

Also, this parent task should be kept open until the Sub-Tasks are done. As this tracking task has no hours, there is no need to keep close it.

**Comment by startailcoon** [comment]
Closing as all sub-tasks are completed.
