### ISSUE TITLE
Check & update readme

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1954]
Check README for irrelevant info and update it

**Comment by startailcoon** [comment]
This is weird, my changes in https://github.com/bitshares/bitshares-ui/pull/1809 must have been reverted at some point.

**Comment by sschiessl-bcp** [comment]
I see them in develop/staging/master. Please elaborate

**Comment by clockworkgr** [comment]
Looks fine to me
