### ISSUE TITLE
The cross cursor displays the trading volume details incorrectly

### ISSUE THREAD

**Issue by little199011** [bitshares/bitshares-ui#1959]
**Describe the bug**
The cross cursor displays the trading volume details incorrectly. 
the data on the left is incomplete.

![wechatimg1424](https://user-images.githubusercontent.com/6262137/46653383-7c162280-cbd8-11e8-9095-3654c30e1c30.jpeg)

**Desktop (please complete the following information):**
 - OS
 - Browser : chrome
 - Version

**Comment by svk31** [comment]
You're using a very old version, we no longer have those charts.

**Comment by startailcoon** [comment]
Closed, please update your version of Bitshares UI
