### ISSUE TITLE
Importing Private Keys Makes An Account Which Doesn't Show Up In Settings

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#196]
I tired to import an account into a wallet on my computer by using the three private keys and was successful at seeing my balance and username and public keys but it will not show up in Settings -> Accounts.

It actually did at first, for a short time, then disappeared. I have tried creating a new wallet and doing it again, same problem, it doesn't show up in accounts, it wont show up in my list of followed accounts.

I tried restoring the wallet, same.

I could do a clean install of everything and go back to before I ever imported the keys but that is a last option.

I am using Mac OS X and the name IS a premium name but not a lifetime member, could that be it?

Anyone else have this problem?

**Comment by landry314** [comment]
i am thinking can i generate new keys and delete the old ones? might that work?

how about paying for a lifetime membership? would that fix it? i dont want to waste it on a broken account.

i want the name, that is why, someone sent it to me. if i am not a lifetime member YET can i see premium accounts in my wallet? i was going to buy a lifetime for it as soon as it was working smoothly.

**Comment by landry314** [comment]
Well, not like anyone cares (this seems like a ghost town) but after deleting the bitshares library folder and restoring into a fresh wallet in a clean bitshares application, I can access both my accounts.

**Comment by abitmore** [comment]
If there is next time, try this: From application menu, view -> reload, then in the UI, click Browse -> Accounts, input your account name, click the account, on the left, perhaps you'll see a "unignore" button, click it.

**Comment by landry314** [comment]
in the light wallet are you talking about "explore -> accounts"?

i see no unignore button.

**Comment by wmbutler** [comment]
@landry314 I'll try to carve out some time to test this on the test net. Is it showing up in other areas besides settings -> accounts? Are you able to make trades and send/receive funds from the imported account?

**Comment by landry314** [comment]
yes, the account was working and in the dropdown menu above but not in the accounts list in the first tab or in the accounts list in settings.

it is working fine now after a clean install and restore.

**Comment by landry314** [comment]
OK, now it isn't there anymore after I created a few new accounts. The new accounts are in the accounts list but my main account with funds is not. I can access it from the top drop down and trade with it but it will not show up in Settings -> Accounts nor in the Accounts list under the Main Bitshares tab on the upper left. So maybe it wasn't importing that account that did this?

Funny too, one of my new accounts which has no funds and which I chose to HIDE in Accounts DOES show up under Accounts in the Main Bitshares tab on the upper left. Why? It should be hidden.

There is something seriously wrong with the way the GUI keeps track of accounts, some are missing, some are not hidden when they should be, some are hidden when they shouldn't be.

@abitmore said above that there is an "unignore" button. I can't find that anywhere.

I suggest a total rehaul of this system also including fixes for #207, #210 and #215.

Will I need to do another clean install to get my account back in the list? Sigh.

**Comment by landry314** [comment]
Clean install brought my main account back to the accounts list... This is the second time I have had to do this. I think this particular account has been disappearing because it was transferred to me, I didn't create it originally... but I am just guessing. On cryptofresh it is still listed as one of the original creator's registered accounts.

**Comment by wmbutler** [comment]
Seems reasonable to create an Epic for this and lump them all into it.

**Comment by landry314** [comment]
That would be wonderful! The entire accounts management system needs a rehaul.

I highly suggest some differentiation in the names for sections.

"ACCOUNT" tab becomes "MY ACCOUNT"

"Accounts" in the "b" menu on the left becomes "Followed Accounts"

"Settings -> Accounts" just stays "Accounts" but a subcategory called "Account Management" is a rehaul to include the starring feature and all the bug fixes for disappearing accounts and maybe a sorting feature too! The other category could be the new feature #212 called "Account Transfer".

**Comment by wmbutler** [comment]
Can you post a screenshare of this issue? If it's resolved, please close it. @landry314

**Comment by landry314** [comment]
I resolved it by backing up the wallets and deleting the library folder then with a clean application, importing the wallets. this was many versions of the application ago so I don't know if the wallet management has been fixed.

As I was making new accounts or hiding accounts of importing wallets or doing too much with wallets inevitably there were bugs with missing accounts. Sometimes a reload would fix it, sometimes a clean install.

I hope it has been fixed but this issue may no longer be relevant so we should just wait until a clear reproducible issue arises to deal with.

An epic wallet management overhaul would be nice...

**Comment by xiaolujidan** [comment]
I don't know how to import the account,I used the command to create the account
```
suggest_brain_key

register_account alpha BTS5s2iBiMeaCt96hoiAhQz94AqiPChTNF2YpYt6zJNNFJonhXPTF BTS5s2iBiMeaCt96hoiAhQz94AqiPChTNF2YpYt6zJNNFJonhXPTF nathan nathan 0 true

```
