### ISSUE TITLE
Asset details errors

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1962]
**Describe the bug**
Asset description errors on initial startup

**To Reproduce**
1. Go to https://staging.bitshares.org/#/asset/BROWNIE.PTS
2. Observe the white screen of death

**Expected behavior**
Asset details page loads properly

**Screenshots**
Errors:
![image](https://user-images.githubusercontent.com/33128181/46674003-60f8e200-cbdb-11e8-82fd-7e6f7c104380.png)

![image](https://user-images.githubusercontent.com/33128181/46674024-6fdf9480-cbdb-11e8-9433-780885952b27.png)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser Chrome

**Comment by sschiessl-bcp** [comment]
If no one claims this I will have a look tomorrow. Live release is scheduled for tomorrow

**Comment by startailcoon** [comment]
Does this issue require any hours, or is it included in another issue hour?
