### ISSUE TITLE
[6][react-cat][1.5][gibbsfromncis] Replace Settings old components to ant

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1964]
Todo:

- [ ] General
- [ ] Local Wallet
- [ ] Accounts
- [ ] Password
- [ ] Backup
- [ ] Restore/import
- [ ] Nodes
- [ ] Faucet
- [ ] Reset Settings

Requested estimate: 4h

**Comment by react-cat** [comment]
@gibbsfromncis Can I claim ?

**Comment by gibbsfromncis** [comment]
@react-cat This task is not approved yet by @startailcoon so it's better to wait for my estimate approval but I'm OK if you work because this task is good enough to become familiar with our style-guide

@startailcoon when you approve my task please unassign myself and assign @react-cat

**Comment by gibbsfromncis** [comment]
@react-cat Regarding this issue - #1945 I would like to ask you to remove `block-list` usage from Settings at all. If you have any questions feel free to ask me

**Comment by startailcoon** [comment]
@react-cat welcome to the UI team. I've assigned you this task and set it for completion to the 181031 milestone, which means it should be ready for merging a few days before that to make sure we have some time to test it for issues.

**Comment by react-cat** [comment]
@startailcoon Thanks, I'm really appreciate for chance to work with you

**Comment by gibbsfromncis** [comment]
@react-cat this task relates to Foundation Elimination and blocks me. Please notify me about the date you will finish or if you have no time to work on it please unassign yourself.

**Comment by gibbsfromncis** [comment]
@startailcoon I've put 1h I spent to review & test this PR

**Comment by react-cat** [comment]
@startailcoon This task took more time that was estimated, so it would be great to raise estimate for 2 hours

**Comment by gibbsfromncis** [comment]
@startailcoon please pay attention to message above :)

**Comment by startailcoon** [comment]
Updated issue hours @react-cat.

**Comment by react-cat** [comment]
@startailcoon thanks

**Comment by react-cat** [comment]
My username for payment: react-cat
