### ISSUE TITLE
[.5][gibbsfromncis]Error running last version of develop

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1965]
```
ERROR in ./node_modules/alt-react/src/supplyFluxContext.js 15:11
Module parse failed: Unexpected token (15:11)
You may need an appropriate loader to handle this file type.
|
|   render() {
>     return <Component {...this.props} />
|   },
| })
 @ ./node_modules/alt-react/src/index.js 2:0-51 4:0-37
 @ ./app/AppInit.jsx
 @ ./app/index.js
 @ ./app/Main.js
 @ multi webpack-hot-middleware/client react-hot-loader/patch ./app/Main.js

ERROR in ./node_modules/alt-react/src/connect.js 6:23
Module parse failed: Unexpected token (6:23)
You may need an appropriate loader to handle this file type.
| export default (Component, config = {}) => {
|   return class extends ConnectBase {
>     static displayName = `Stateful${Component.displayName || Component.name}Container`
|     static contextTypes = Component.contextTypes || config.contextTypes || {}
|
 @ ./node_modules/alt-react/src/index.js 1:0-31 4:0-37
 @ ./app/AppInit.jsx
 @ ./app/index.js
 @ ./app/Main.js
 @ multi webpack-hot-middleware/client react-hot-loader/patch ./app/Main.js
```

npm `6.4.1`
node `v8.7.0`

**Comment by gibbsfromncis** [comment]
@svk31 I suppose it's better to remove `package-lock.json` from `alt-react` repo

**Comment by gibbsfromncis** [comment]
@svk31 I put .5h I spent for investigation. If you disagree just remove it and put .5h for your future fixes.

**Comment by gibbsfromncis** [comment]
# Temporary fix for contributors

If you get error when running last version of project please update your `package.json` and lock `alt-react` version to specific commit:

```
"alt-react": "git+https://github.com/bitshares/react.git#9d8cf202bc5c81aa31f0719b80fda77e3a04fa5a",
```

**PLEASE DO NOT COMMIT THIS TEMPORARY FIX. USE IT LOCALLY ONLY**

**Comment by svk31** [comment]
Not a real issue, just restart webpack

**Comment by gibbsfromncis** [comment]
@wmbutler 
I'm going to close this issue to get bounty for my investigation and find of temporal fix because OL guys get this issue and asked me for the help. I've unassigned Sigve because he will get bounty for this fix in a scope of another issue.

**Comment by g3d** [comment]
I was able to reproduce this on the clean installation on latest release & develop.
Here is backtrace: https://gist.github.com/g3d/d1f3032379f171be2143685d5932aa93

The source of problem was latest `alt-react` that was not processed by babel, so it triggered issues with splat operator.

**Comment by gibbsfromncis** [comment]
@g3d what is release branch?

**Comment by gibbsfromncis** [comment]
@g3d Please check latest release date and the date of the fix.

**Comment by g3d** [comment]
@gibbsfromncis 
The release of the stable branch happened earlier than this fix was introduced. I did not get your point. Could you please elaborate it a little bit?

**Comment by gibbsfromncis** [comment]
@g3d 
> The release of the stable branch happened earlier than this fix was 

Exactly. Please wait for the next release. 

@sschiessl-bcp

Can you please answer Bogdan when we have next release?

**Comment by g3d** [comment]
@gibbsfromncis I know when next release is. I posted the comment here as a result of discussion in BitsharesDEV telegram group & research with issues we faced one day inside Docker containers.

IMO, other people should be aware if there is some known bugs with latest stable release.
