### ISSUE TITLE
[1][Exchange Refinement] Minor Bugs

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1978]
Issue to collect bugs in the new layout

- Open BTS_USD market (refresh possibly), observe following error
![image](https://user-images.githubusercontent.com/33128181/46717697-26d62180-cc69-11e8-9dc1-7a54f24e6b16.png)

- No default for Markets is set (was the PR for #1822 merged into the new layout branch after reverting?)
![image](https://user-images.githubusercontent.com/33128181/46719721-f0030a00-cc6e-11e8-89dc-008e5b7ad17f.png)

**Comment by startailcoon** [comment]
> Open BTS_USD market (refresh possibly), observe following error

Fixed

> No default for Markets is set (was the PR for #1822 merged into the new layout branch after reverting?)

Should be, try resetting your local settings storage?

**Comment by sschiessl-bcp** [comment]
> Should be, try resetting your local settings storage?

Did, still no default

**Comment by sschiessl-bcp** [comment]
When opening exchange on first load:
![image](https://user-images.githubusercontent.com/33128181/47066805-8abb9580-d1e7-11e8-9e95-3e1441f45947.png)

**Comment by sschiessl-bcp** [comment]
> > Should be, try resetting your local settings storage?
> 
> Did, still no default

Fixed, took one hour.

**Comment by startailcoon** [comment]
Thanks @sschiessl-bcp!
