### ISSUE TITLE
[8][Exchange Refinement] Personalize Modal

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1980]
**General**
- [x] On-hover Personalize button is not pretty (maybe some margin etc.?)

**Modal**
- [x] Group Chart selections. Introduce sections a la "Panel Grouping". This one is called "Chart Options"
   - [x] Option "Type" with Price Chart | Merket Depth | Hide Chart
   - [x] Option "Height" in Pixels, maybe a slider
   - [x] Option "Tools" with Show | Hide (TradingView specific)
   - [x] Option "View" with Locked | Allow Zoom (TradingView specific)
- [x] Group Order options, call "Order Options"
   - [x] Option "Grouping" with No | 0.1 | 1
   - [x] Option "Style" with Horizontal | Vertical
     - If Horizontal Order Book: 
        - [x] Show option: Buy/Sell Orders: Buy - Sell | Sell - Buy
        - [x] Show option: Buy/Sell Asset: Buy - Sell | Sell - Buy 
        - [x] Show option: Vertical Orders / Asset: Orders above Asset | Asset above Order
     - If Vertical Order Book:
        - [x] Show option: Autoscroll: Yes | No
 - [x] Group "General"
    - [x] Rename "Mirror Panels" to "Markets Location" with Left | Right
    - [x] Option "Reduce Scroll Bars" with Yes | No
    - [x] Option "Hide function buttons" with Yes | No
    - [x] Option "Dynamic Order Form" with Yes | No 

- [x] All options should receive a "?" icon with explanatory text as well.

Defaults:
 - Chart Options Type: Price Chart
 - Chart Options Height: 620 (Fixes a bug in the TradingView options Modal)
 - Chart Options Tools: Show
 - Chart Options View:  Allow Zoom
 - Order Options Grouping: No
 - Order Options Style: Horizontal
 - Order Options Buy/Sell Orders: Buy - Sell
 - Order Options Buy/Sell Asset: Buy - Sell 
 - Order Options Vertical Orders / Asset: Asset above Order
 - General Markets Location: Right
 - General Reduce Scroll Bars: Yes
 - General Hide function buttons: Yes

**Related**
#1866
#1836

**Comment by startailcoon** [comment]
I propose we change all "Yes | No" options with a switch instead.

**Comment by startailcoon** [comment]
# Preview
![bild](https://user-images.githubusercontent.com/12114550/46765173-a520db00-ccde-11e8-8409-e339cbed2d07.png)

**Comment by startailcoon** [comment]
The following two options I need @svk31 to look at. I have no TradingView documentation to look at. The toggles will be created and managed, but someone with more experience with Trading View will have to add the finishing code that does this.

> Option "Tools" with Show | Hide (TradingView specific)
> Option "View" with Locked | Allow Zoom (TradingView specific)

**Comment by startailcoon** [comment]
> General Reduce Scroll Bars: Yes
> General Hide function buttons: Yes

I disagree with these, as they are not the default from before, especially not hiding function buttons.

**Comment by sschiessl-bcp** [comment]
> Option "Tools" with Show | Hide (TradingView specific)

Could be omitted.

> Option "View" with Locked | Allow Zoom (TradingView specific)

https://github.com/bitshares/bitshares-ui/blob/dbc0f868509d1da4d786e0eb239d58808b9b9343/app/components/Exchange/TradingViewPriceChart.jsx#L42

Add "(needs reload)" in description

> General Reduce Scroll Bars: Yes
> General Hide function buttons: Yes

This leads to the cleanest experience to newcomers. I would force that the help popups once after this update for everyone, which heavily leverages the "Personalize" component". All the old dogs will understand it, and IMO it is simply the strongest choice for usability.

**Comment by sschiessl-bcp** [comment]
Closed with latest staging release (see separate issues)
