### ISSUE TITLE
[6] Show found contact (in typeahead) above non contacts

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#1984]
**Is your feature request related to a problem? Please describe.**
If a typeahead locates a contact, it's displayed below other options.

**Describe the solution you'd like**
The green value in your contact list should appear higher in the list.

![typeahead](https://user-images.githubusercontent.com/1254810/46777867-cbdb1380-ccd6-11e8-91a0-5c950f093016.gif)

**Comment by startailcoon** [comment]
A small change that could easily be added to the UI before the next release.

This would be changed to ANT drop-down later, but doesn't limit us to make a small fix for now, before we add the new components.

**Comment by sschiessl-bcp** [comment]
The new modal is already merged, let's pick this up.

**Comment by wmbutler** [comment]
All I'm saying is that it should prioritize matches on my saved contacts first. This is especially important for names that are spelled similarly like `smith` and `smitn`. If `smitn` were in my address book, I'd much rather see it when I type `smi`

> Imagine it's at the bottom of your contacts, but you actually want the jack contact.

If jackson-butler and jack were both in my contacts and I typed `jack`, I would expect to see jack at the top, jackson-butler as the next pick.

**Comment by wmbutler** [comment]
Have to disagree here (unless I'm misunderstanding you). You should always match to those in your contact list first to avoid potentially sending to the wrong (likely unfamliar) user.

**Comment by wmbutler** [comment]
Would like to see this implemented. I use this feature all the time to send payments out and I always have to be careful to not select some random account because it shows up higher in the list than the intended (known) account.

**Comment by wmbutler** [comment]
I also noticed that we seem to be listing unknown accounts in the dropdown. There is really no reason to list unknowns in the dropdown at all.

- [ ] Do not display unknown accounts

![screen shot 2018-12-14 at 4 06 00 pm](https://user-images.githubusercontent.com/1254810/50032690-0f921800-ffbb-11e8-8e07-615a11202a42.png)

**Comment by sschiessl-bcp** [comment]
Unknown account is an account that never interacted with your account iirc 
(stored in local settings). In the case that you actually want to send to 
an account that you have never interacted with before you would need that.

Do you have an idea how to integrate that? Maybe a toggle for Show unknown?

Am 15. Dezember 2018 12:12:40 vorm. schrieb Bill Butler 
<notifications@github.com>:

**Comment by startailcoon** [comment]
Sub-Task of #2352

**Comment by startailcoon** [comment]
Updated AccountSelector.

- Favorite accounts first, starred
- Known Scam accounts with warning symbol
- Search input at the bottom
- Input not a valid account is not rendered

![accountselect](https://user-images.githubusercontent.com/12114550/50181591-1d260580-030d-11e9-8d43-df3c980aa5a7.gif)

**Comment by sschiessl-bcp** [comment]
> Hmmm, so you think this account exists on the chain?

There seems to be another bug in fetching the account. When I search for an account I have never interacted with before, it also says 'Unknown account'
![image](https://user-images.githubusercontent.com/33128181/50281863-27511c80-0451-11e9-9a17-c81a52c43f9c.png)

The second time I search (now the cache is filled), it says "Basic Member". 

My comment was with respect to the case when the account actually exists, i.e. I'm with you now.

**Comment by startailcoon** [comment]
@sschiessl-bcp yes. There are some delay issues I guess, as well as when an account does not exists at all it's listed as "unknown account", which should not be rendered at all.

**Comment by startailcoon** [comment]
Fixed as part of #2205 and #2352
