### ISSUE TITLE
[2] Hide legacy proposals

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1986]
Add a checkbox to current voting tab that reads: "Hide Legacy Proposals" next to proxy setting
![image](https://user-images.githubusercontent.com/33128181/46781734-6a8d6180-cd23-11e8-8e5e-195bff98cee8.png)

Concerning component:
app/components/Account/AccountVoting.jsx

It is enabled per default, and it hides
- all proposals that already have started, but were never active before
- checks if there are proposals from the same account, same (similar) title, and hides the older one (in case someone creates it by mistake)

**Comment by startailcoon** [comment]
I like your idea @sschiessl-bcp , it's an easy way of improving user involvement.

I'd like some clarification in your statements though.

> all proposals that already have started, but were never active before

Before what?

> checks if there are proposals from the same account, same (similar) title, and hides the older one (in case someone creates it by mistake)

I think this can be tricky. What if someone has similair titles for different things? Sure, we don't have _that_ many workers, and a second one from the same account is usually an updated one. The key part here is, how can we verify and be certain about it?

**Comment by sschiessl-bcp** [comment]
100%, never, but high confidence. 

We could also have a manual mapping of the workers (maintained by us), it's not happening that often.

**Comment by sschiessl-bcp** [comment]
Legacy proposals are:
 - duplicates (similar name, required some testing), older ID is hidden
 - workers that begun more than two months ago, are inactive and have less than 20 million votes are hidden
 - manually set workers (old rossul and scorum)
 
Hours spent: 5.5
