### ISSUE TITLE
[1.5] Open Orders are not displayed properly

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#1987]
**Describe the bug**
I have currently one open order, which is not displayed properly. I can click on the invisible checkbox under Cancel, which makes the order appear.

**To Reproduce**
1. Open any order
2. Go to Open Order Tab in Dashboard
3. Observe order not shown

See also here https://wallet.bitshares.org/#/account/sschiessl

**Expected behavior**
Order should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/33128181/46781567-762c5880-cd22-11e8-88ce-7e84bff80399.png)

**Concerning**
Component app/components/Exchange/MyOpenOrders.jsx

**Comment by svk31** [comment]
I had a quick look and it was also empty for me for a few seconds, then the order appeared
