### ISSUE TITLE
[Foundation Elimination] Modal [Phase II]

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1993]
Part of #1951

**Comment by gibbsfromncis** [comment]
### Withdraw Modal

<img width="549" alt="screenshot 2018-10-13 18 02 31" src="https://user-images.githubusercontent.com/35899973/46906828-2b713300-cf12-11e8-8eb1-04cdd18567dd.png">


### Exchange Personalization 

<img width="602" alt="screenshot 2018-10-13 18 01 33" src="https://user-images.githubusercontent.com/35899973/46906830-362bc800-cf12-11e8-8b5b-eba2eba24876.png">

**Comment by gibbsfromncis** [comment]
### Market Picker

<img width="589" alt="screenshot 2018-10-13 19 34 12" src="https://user-images.githubusercontent.com/35899973/46907686-033c0100-cf1f-11e8-93e2-2dae3173031b.png">

**Comment by gibbsfromncis** [comment]
### Quote Selection Modal

<img width="589" alt="screenshot 2018-10-13 19 34 12" src="https://user-images.githubusercontent.com/35899973/46907935-6a5bb480-cf23-11e8-9204-d2c3f3043728.png">

**Comment by gibbsfromncis** [comment]
### Transaction Confirmation

<img width="548" alt="screenshot 2018-10-13 23 28 31" src="https://user-images.githubusercontent.com/35899973/46909722-b9afde00-cf3f-11e8-870e-ba1cdd2eafbb.png">

**Comment by gibbsfromncis** [comment]
### Settle Modal

<img width="551" alt="screenshot 2018-10-14 00 18 06" src="https://user-images.githubusercontent.com/35899973/46910065-a2282380-cf46-11e8-8d9d-f1bd178bee65.png">

**Comment by froooze** [comment]
@gibbsfromncis: Why do we need a mode option (filter/search) on the market picker?

**Comment by gibbsfromncis** [comment]
@froooze this task is just to replace Foundation Modals for Ant Modals. It doesn't relate to modals content. If you want any improvements feel free to create separate issue

**Comment by startailcoon** [comment]
@gibbsfromncis please submit your required hours for this issue

**Comment by gibbsfromncis** [comment]
@startailcoon 4 hours
