### ISSUE TITLE
[11][gibbsfromncis] New Sign Up/Login style-guide integration

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#1997]
This is task was a part of #1832 but moved to separate task

**Comment by gibbsfromncis** [comment]
### Login Selector

<img width="907" alt="screenshot 2018-11-24 05 03 59" src="https://user-images.githubusercontent.com/35899973/48964383-600eea80-efa6-11e8-8301-6c43ab5dcfbf.png">
<img width="890" alt="screenshot 2018-11-24 05 03 57" src="https://user-images.githubusercontent.com/35899973/48964384-600eea80-efa6-11e8-8ff0-2aab8f3dd828.png">

### Registration Selector

<img width="831" alt="screenshot 2018-11-24 05 04 29" src="https://user-images.githubusercontent.com/35899973/48964387-6ef59d00-efa6-11e8-915e-648ce1ac47e6.png">

### Registration (Cloud)

<img width="1152" alt="screenshot 2018-11-24 05 05 01" src="https://user-images.githubusercontent.com/35899973/48964397-8b91d500-efa6-11e8-9163-efe092d2148f.png">

<img width="1178" alt="screenshot 2018-11-24 05 05 23" src="https://user-images.githubusercontent.com/35899973/48964398-8df42f00-efa6-11e8-8cbb-42d52083ae10.png">

<img width="1160" alt="screenshot 2018-11-24 05 06 26" src="https://user-images.githubusercontent.com/35899973/48964409-b714bf80-efa6-11e8-94ba-4577640651da.png">

### Registration (Local Wallet)

<img width="1177" alt="screenshot 2018-11-24 05 07 14" src="https://user-images.githubusercontent.com/35899973/48964411-d6135180-efa6-11e8-92db-c93a6aecd430.png">

<img width="1152" alt="screenshot 2018-11-24 05 08 13" src="https://user-images.githubusercontent.com/35899973/48964416-f3e0b680-efa6-11e8-8f9f-199211c830c2.png">
<img width="1190" alt="screenshot 2018-11-24 05 08 07" src="https://user-images.githubusercontent.com/35899973/48964417-f4794d00-efa6-11e8-89bb-4425d02ef9b6.png">

**Comment by gibbsfromncis** [comment]
@startailcoon final estimate: 11h

**Comment by startailcoon** [comment]
Great work as always!

**Comment by sschiessl-bcp** [comment]
The PR for this is still open ... looking at it now

**Comment by gibbsfromncis** [comment]
@startailcoon I had problems with my PR so I added 3 additional hours for communication/testing/fixes added regarding this task.
