### ISSUE TITLE
committee-account activities page white screen

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#1999]
**Describe the bug**
Committee-account activities page white screen (not always reproduce-able)

**To Reproduce**
1. Go to 'https://wallet.bitshares.org/#/account/committee-account'
2. Click on 'Activities'
3. See white screen

**Expected behavior**
No white screen

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/46906112-a892ad00-cefe-11e8-8273-d6dbbc2816a9.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome 69
 - Version 2.0.181010

**Additional context**
If open the URL in an incognito window, it's able to show the page.

**Comment by sschiessl-bcp** [comment]
You might need to reload the wallet after clicking on Activity to reproduce (at least for me)

**Comment by sschiessl-bcp** [comment]
Can you try to reproduce this with only one tab open please @abitmore 

https://www.chromestatus.com/feature/5527160148197376

**Comment by startailcoon** [comment]
I can't reproduce this.

**Comment by clockworkgr** [comment]
Re-open, can reproduce not by navigating to activity but by refreshing once there.

![image](https://user-images.githubusercontent.com/6826762/49671602-1ed00d80-fa71-11e8-8a86-3aef352ea217.png)

**Comment by startailcoon** [comment]
This is an old bug and it's no longer present what I can see.
