### ISSUE TITLE
[1] Need ability to click on the Block number

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#20]
_From @kenCode-de on November 6, 2015 8:59_

I want to easily prove to someone that I paid their bill. 

I open the light client, I find that transaction and click on it. It shows me the block number at the top of the screen. 

I would like to be able to click on that block number so that it loads up the block explorer (so I can email the link to my creditor), ie: 
http://cryptofresh.com/b/677376 

_Copied from original issue: cryptonomex/graphene-ui#455_

**Comment by svk31** [comment]
Not sure I get what you want here. You want a link from the internal block explorer to an external one link cryptofresh?

**Comment by svk31** [comment]
_From @kenCode-de on November 11, 2015 12:35_

yes please. this way it will open the users default browser with cryptofresh displaying that blocks info. makes it easier to send a URL to someone as proof that you paid them or vice versa.

**Comment by svk31** [comment]
_From @wmbutler on November 11, 2015 20:21_

@svk31 This is on a later milestone. Don't sweat this for a couple of weeks.

**Comment by wmbutler** [comment]
![screen shot 2017-07-21 at 1 24 45 pm](https://user-images.githubusercontent.com/1254810/28477069-01114bce-6e18-11e7-8ff1-48ab0cee2d2d.png)

**Comment by wmbutler** [comment]
Neither cryptofresh nor bitshares-explorer seems very reliable atm. Tabling this.
