### ISSUE TITLE
Exchange Loading Time

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2002]

**Comment by gibbsfromncis** [comment]
@startailcoon maybe your changes on Exchange affected on it. Can you please investigate?

**Comment by startailcoon** [comment]
I don't see any issue with loading times, please describe your issue a bit more in detail.

When does it happen?
Does it not load?
Does it load, but slow?
Does it always happen?
Any log outputs?

**Comment by sschiessl-bcp** [comment]
Investigate:
 - Modals may not render or load any data when they are not opened. Can that be centrally configured for the new Modals?
 - Which components can be loaded lazily? Order Book, My Market, Trade History

**Comment by startailcoon** [comment]
At least all modals on the exchange can be rendered first on request.
