### ISSUE TITLE
Update list of assets after user burn some asset

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2003]
Update list of assets in Dashboard/Portfolio after user burn some asset

**Comment by startailcoon** [comment]
@gibbsfromncis Does this issue refere to that the list of assets aren't updated once you burn something? If that is the case, this sounds more like a higher priority issue.

**Comment by gibbsfromncis** [comment]
@startailcoon yep, you got it right. I updated priority. Also I won't assign priority labels in future. Only in cases if I think something really critical
