### ISSUE TITLE
[7.5] Redesign & Antify Borrow Modal

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2004]
Old design:

<img width="707" alt="screenshot 2018-10-14 00 20 39" src="https://user-images.githubusercontent.com/35899973/46910083-0519ba80-cf47-11e8-9d1f-3f36f4275308.png">

**Comment by froooze** [comment]
What is the motivation for a redesign? 
How about a one click borrow model, for beginners?

**Comment by gibbsfromncis** [comment]
@abitmore @wmbutler @startailcoon @sschiessl-bcp please  
Do you have any suggestions/requirements for this before me and @nikandrovalex will start to work on this task?

**Comment by sschiessl-bcp** [comment]
> What about a vertical slider on the right to slide a percentage of debt/collateral?

That could be indeed nice. 

> Using start default values for the RATIO (=3.5), the TARGET COLLATERAL (=1.75)

Strong defaults are strong :)

I find the lock confusing, maybe we can have a button within the textfield (like copy button), but with a editable icon that gets striked through (e.g. https://static.thenounproject.com/png/31085-200.png)

**Comment by startailcoon** [comment]
The lock is to change the field for the slider. Before we added this feature the slider only changed collateral, if I'm not mistaken.

I'm sure we can find a better UX for this.

**Comment by froooze** [comment]
- Actually I like the look and it self explaining nature. It was introduced, while having the same idea. 
- When we introduce a slider for DEBT and COLLATERAL, it can also have the predefined buttons with percentages.

**Comment by startailcoon** [comment]
A new UX would be nice when completing this issue. 

@alexandrty, I assume you will need some walkthrough on the components of this section before you can start. 

I'd like the lock functionality to stay.

**Comment by alexandrty** [comment]
> A new UX would be nice when completing this issue.
> 
> @alexandrty, I assume you will need some walkthrough on the components of this section before you can start.
> 
> I'd like the lock functionality to stay.

Hello, it seems to me that you should not address these messages to me, I am not involved in solving these problems

**Comment by froooze** [comment]
- Do we really need the slider on the Target Collateral Ratio? This is a number which is not quite often changed and faster typed in a field also. 
- With the saved space we could add one extra slider between DEBT and COLLATERAL, which respects the lock
- The lock and slider should be more highlighted on which side they are active
- The buttons are usable despite the lock as it is today and therefore we need them twice for DEBT and Collateral 

Buttons for Debt
Slider
Buttons for Collateral

**Comment by wmbutler** [comment]
>Do we really need the slider on the Target Collateral Ratio? This is a number which is not quite often changed and faster typed in a field also.

Agreed, the slider could easily be converted to a select menu, possibly with a representation beside it (0.0000) when 4 is entered.

**Comment by dot5enko** [comment]
guys, so what's we're decided except antifying in this task?
read all the comments and haven't found any strict statements :)

**Comment by startailcoon** [comment]
@dot5enko I've unassigned you from this issue for the moment.

**Comment by gibbsfromncis** [comment]
@startailcoon yea, will work soon.

**Comment by startailcoon** [comment]
Needs UX, open for claim

**Comment by sschiessl-bcp** [comment]
> Needs UX, open for claim

Let's wait what gibbs comes up with before redesigning this in here

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I've removed it from milestone because it is better to leave it for redesign

**Comment by startailcoon** [comment]
Issue #2005 and #2007 is in need of fixing, and would require most of this Modal to be converted to Ant components. I'm capable of fixing these issues, and move it over to Ant in the meantime. Wouldn't be a new UX for this, only code cleaning and fixing. 

cc @gibbsfromncis @sschiessl-bcp as you've both said held on this issue.

**Comment by startailcoon** [comment]
After talking with Gibbs, we'll work on fixing the issues as well as moving to the new components in Style Guide. I will not work on a new UX design, but may bring in some changes based on the issues feedback.

**Comment by startailcoon** [comment]
Here are a few updates that I will do

## Lockable Asset Amount field
All asset amount fields will be able to have a lock/unlock icon appended to them so it can be used for locking functionality elsewhere. Those without will look as normal

![image](https://user-images.githubusercontent.com/12114550/58762442-53b8ab00-8550-11e9-9154-792c72d017ed.png)

**Comment by sschiessl-bcp** [comment]
Since you are touching it, one thing you could ensure is that view and 
business logic.is properly separated

Am 2. Juni 2019 4:08:02 nachm. schrieb startailcoon <notifications@github.com>:

**Comment by startailcoon** [comment]
> Since you are touching it, one thing you could ensure is that view and business logic.is properly separated Am 2. Juni 2019 4:08:02 nachm. schrieb startailcoon <notifications@github.com>:
> […](#)
> Here are a few updates that I will do Lockable Asset Amount field All asset amount fields will be able to have a lock/unlock icon appended to them so it can be used for locking functionality elsewhere. Those without will look as normal — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

If that is something we should do now, I could look into that.

**Comment by sschiessl-bcp** [comment]
> Here are a few updates that I will do
> 
> ## Lockable Asset Amount field
> All asset amount fields will be able to have a lock/unlock icon appended to them so it can be used for locking functionality elsewhere. Those without will look as normal
> 
> ![image](https://user-images.githubusercontent.com/12114550/58762442-53b8ab00-8550-11e9-9154-792c72d017ed.png)

Could the icon be hovering outside on the left side of the input in blue? Not sure if better, the left prefix is not rocking my UX buds

**Comment by froooze** [comment]
@startailcoon:
The lock should as big as the box high.
I like the actual version, even a little bigger, without any boarder more with some white space between.

**Comment by startailcoon** [comment]
> @startailcoon:
> The lock should as big as the box high.
> I like the actual version, even a little bigger, without any boarder more, with some white space between.

The lock is indeed visually difficult to see, so I've added colors to them. But this is up to the style guide to change if needed.

**Comment by startailcoon** [comment]
> Could the icon be hovering outside on the left side of the input in blue? Not sure if better, the left prefix is not rocking my UX buds

Why doesn't this "rock your UX buds"? The lock is clearly a part of the input value, and having it hovering on the side of the input, as we have had, is to me much worse.
Could it be better if we didn't have the borderd box around it and just appended before the input?

### Preview

Attached is a preview of the new modal.
Also including separation of logic code.

![image](https://user-images.githubusercontent.com/12114550/59121538-a03d2580-8958-11e9-8036-c2c2f0264783.png)

**Comment by sschiessl-bcp** [comment]
https://user-images.githubusercontent.com/12114550/59124940-42f9a200-8961-11e9-9b47-da61d9cdb765.png

This I like much better

**Comment by froooze** [comment]
@startailcoon 
- The ratio slider should be below and as wide as possible to allow changes of 0.01.
- Ratio and TCR should be in the same line, next to each other

**Comment by startailcoon** [comment]
> 
> 
> @startailcoon
> 
>     * The ratio slider should be below and as wide as possible to allow changes of 0.01
> 
>     * Ratio and TCR can be in the same line, next to each other

Working on making something like this. I'll post an updated screen soon.

**Comment by startailcoon** [comment]
Here's an update on the view based on suggestions.


![image](https://user-images.githubusercontent.com/12114550/59565926-728f6500-9059-11e9-9471-13534458cbd3.png)

When no TCR is used, it will be blank, amaking it possible to tick the box if the asset allows it.

![image](https://user-images.githubusercontent.com/12114550/59565953-a2d70380-9059-11e9-917a-6d412f44f198.png)

The only problem I see with putting the slider below is that it will be pushed when there is an error.

![image](https://user-images.githubusercontent.com/12114550/59565965-cd28c100-9059-11e9-81bb-2d55c7b19b54.png)

**Comment by sschiessl-bcp** [comment]
Can you make the yellow text have 100%?

**Comment by startailcoon** [comment]
I think @gibbsfromncis needs to take this on another issue if we want this changed. This is the best I can make it for now.

**Comment by froooze** [comment]
@startailcoon : The yellow box should be as wide as the ratio slider.

**Comment by startailcoon** [comment]
> @startailcoon : The yellow box should be as wide as the ratio slider.

Not possible today. An issue has been opened.
