### ISSUE TITLE
[0][Margin Picker] No update on available DEBT asset

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2007]
When I change the DEBT number, the amount on AVAILABLE does not get an update.

**Comment by froooze** [comment]
The COLLATERAL row works, but not the DEBT row.

**Comment by startailcoon** [comment]
The DEBT row is the amount of your available asset before your borrow. It does not change when you type something in the form, if that is what you expect.

**Comment by froooze** [comment]
When I change the DEBT amount, the AVAILABLE amount should also be adjusted, like it is on the COLLATERAL.

**Comment by startailcoon** [comment]
Hours of this issue included in sub-task #2004

**Comment by wmbutler** [comment]
It's updating for me but this value cannot be deleted as shown here

![delete](https://user-images.githubusercontent.com/1254810/50047028-5b07fd00-0073-11e9-8ebb-735709f163f5.gif)
