### ISSUE TITLE
Votable witness list incomplete

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2012]
**Describe the bug**
https://testnet.bitshares.eu doesn't show all witnesses on voting page.

**To Reproduce**
1. Go to 'https://testnet.bitshares.eu/account/xeroc/voting'
2. Click on 'witnesses'
3. Scroll down to the bottom
4. See error, only 72 witnesses are shown.

**Expected behavior**
Show all witnesses.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/46944243-db10e700-d071-11e8-91e0-4de4da40ed34.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abitmore** [comment]
The witness with highest ID in testnet is `1.6.90`.

**Comment by startailcoon** [comment]
With the latest develop branch I'm able to see 91 witnesses to vote for.

![bild](https://user-images.githubusercontent.com/12114550/47259909-80ccb780-d4b1-11e8-82f3-c3f51b5d9e3e.png)
