### ISSUE TITLE
[UX:2][UI:2] [Style-Guide] Support all styles of tabs

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2015]
The task is to add support of all styles of [ANT Tabs](https://ant.design/components/tabs)

**Comment by sschiessl-bcp** [comment]
Issues that receive label should be complete in their description.

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp updated

**Comment by gibbsfromncis** [comment]
@nikandrovalex I need design for all styles of ANT tabs for all themes: Dark, Midnight, Light

**Comment by gibbsfromncis** [comment]
@nikandrovalex we need design of these tabs:
- https://ant.design/components/tabs/#components-tabs-demo-card
- https://ant.design/components/tabs/#components-tabs-demo-card-top

For all 3 themes: `Midnight`, `Dark` and `Light` based on our current style-guide - https://styleguide.bitshares.org/#/

**Comment by gibbsfromncis** [comment]
@startailcoon My estimate for UI is 2h

**Comment by nikandrovalex** [comment]
@startailcoon 

My esitmate for this task is 2h. Can you please approve it and put on it?

**Comment by startailcoon** [comment]
@gibbsfromncis @nikandrovalex approved, great work.

**Comment by nikandrovalex** [comment]
Hello guys @gibbsfromncis @startailcoon . Please look at the design
https://invis.io/8KOE15IAFES#/328485045_TABS_DARK_THEME

**Comment by sschiessl-bcp** [comment]
For the click lazy
![image](https://user-images.githubusercontent.com/33128181/47718534-f6225000-dc48-11e8-9935-406a4c61dd9e.png)

**Comment by startailcoon** [comment]
Just needs implementation in style-guide then.

**Comment by gibbsfromncis** [comment]
@nikandrovalex as we do not have border-radius for all elements in style-guide I keep all tabs as without it too.
