### ISSUE TITLE
[1] Display Fees in Account Activity

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2016]
I created `TEST` coin and noticed I lost `10,000` BTS from my account. First this I did is to open my account activity and take a look what kind of operations I did:
<img width="614" alt="screenshot 2018-10-15 21 16 36" src="https://user-images.githubusercontent.com/35899973/46969703-9ad85580-d0bf-11e8-9138-e81709aa4c60.png">

It would be nice to display each operations fees to be able to track things like this

**Comment by clockworkgr** [comment]
and thats what testnet is for ladies and gentlemen :) 

that was a very expensive test...the bitshares blockchain thanks you for your contribution (btw...check your vesting balance..should have another 4k there)

**Comment by startailcoon** [comment]
Displaying fees could be a nice addition, some users may do wounder what their transactions costs in BTS. Hopefully none accidently creates expensive assets.

Should we perhaps have an extra highlighted section on transactions that are extremley expensive, as an extra note for the user?

**Comment by gibbsfromncis** [comment]
@startailcoon good point.

**Comment by sschiessl-bcp** [comment]
> that was a very expensive test...the bitshares blockchain thanks you for your contribution (btw...check your vesting balance..should have another 4k there)

Isn't a LTM :)

**Comment by sschiessl-bcp** [comment]
If accepted I'll tackle this one.

Question is where to put it. Two options
![image](https://user-images.githubusercontent.com/33128181/47150557-30016700-d2d7-11e8-904b-8fc9799330f3.png)
1. Put in a new column (Fee)
2. Add a on hover popup on the ID or add to Type Popup

My vote would be 1.

**Comment by clockworkgr** [comment]
agree on 1.

**Comment by startailcoon** [comment]
> Put in a new column (Fee)

Would be most usefull I think. A hower doesn't always apply, on touch only devices for example.

**Comment by sschiessl-bcp** [comment]
Adjusted hours, please adjust if anything seems off.
