### ISSUE TITLE
Highlight transactions with high fees in transaction confirmation modal

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2017]

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp @startailcoon How to determine `Expensive`/`High` fees ?

**Comment by sschiessl-bcp** [comment]
> Any ideas how to determine Expensive/High fees ?

You mean other than actually read what the popup says? 

Looking at https://cryptofresh.com/fees the following two would make sense (if this issue gets accepted)
 - "high" > 10 BTS
 - "very high" > 1000 BTS

**Comment by startailcoon** [comment]
Since the fee schedule may change in the future we shouldn't hard code this.

### My thoughts about this would be
Ref Fee: `Regular Transaction Fee` which is 0.10420 BTS
High Fee: `Ref Fee` * 20
Very High Fee: `Ref Fee` * 100

**Comment by gibbsfromncis** [comment]
@startailcoon I'll close this task and keep in mind this issue when we will work on transactions confirmation window
