### ISSUE TITLE
[Exchange Refinement] Community Feedback

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2020]
New exchange is live and visible at 
  https://develop.bitshares.org/#/market/USD_BTS

Following issues have been found already
- [x] You can't change chart size on mobile, since the option isn't available. 620px on mobile is way to big https://github.com/bitshares/bitshares-ui/commit/7a204d0f933d22ad6a468d65393c9ea9bbc5b0d4
- [x] #2021
- [ ] See https://github.com/bitshares/bitshares-ui/issues/1978#issuecomment-430506969
- [ ] First time switching from Horzontal to Vertical Order Book after fresh load
![image](https://user-images.githubusercontent.com/33128181/47072116-ab8ae780-d1f5-11e8-9d65-be96daadd22c.png)
- [ ] Order Book DOM issue
![image](https://user-images.githubusercontent.com/33128181/47072142-b80f4000-d1f5-11e8-8609-a63867e2f36c.png)
- [x] Find markets is missing in tiny and small screen (flag is `tabVerticalPanel` in `Exchange`)
![image](https://user-images.githubusercontent.com/33128181/47079672-51465280-d206-11e8-85ee-3da4c55364fa.png)

**Comment by sschiessl-bcp** [comment]
From startail:

>  I noticed that you can't change chart size on mobile, since the option isn't available. 620px on mobile is way to big

**Comment by sschiessl-bcp** [comment]
> From startail:
> 
>     I noticed that you can't change chart size on mobile, since the option isn't available. 620px on mobile is way to big


Fixed

**Comment by sschiessl-bcp** [comment]
When reducing scrollbars and vertical order book is active, the order book scrollbar is still visible. I expected that the scrollbar is gone too and only as many orders visible as are fitting.

**Comment by startailcoon** [comment]
> Dropdown Menu highlight color

This would be a style guide thing for @gibbsfromncis 

> Unify Font and styles for lists

> I'd suggest we unify font sizes on the exchange tending towards smaller fonts to ensure we can fit everything on screen.

This is a larger issue as there are font changes all over the SCSS files. I agree we should use the same types, but this would require a few hours to tangle out and make sure nothing breaks.

**Comment by gibbsfromncis** [comment]
@startailcoon if you need any updates/features/fixes on style-guide please open an issue and assign me

**Comment by startailcoon** [comment]
Will do @gibbsfromncis

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/pull/2098#issuecomment-434620401

**Comment by startailcoon** [comment]
Will extract the remaining issues from this to new ones.
