### ISSUE TITLE
Check if number pasting parsing is save

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2022]
Latest fix #1912  includes the possibility to paste "1,000 USD" for value "1000".
Include logic that "1000,00 EUR" would not be recognized as "100000".

Things to check:
- [ ] Allowed order of non-digits: Commas only (thousand separator), then optionally one dot.
- [ ] If a comma is found with one or two digits afterwards, recognize as decimal point (only on pasting)

Related
https://github.com/bitshares/bitshares-ui/issues/1828#issuecomment-430618678

**Comment by MarkoPaasila** [comment]
Will the 2 decimal check work properly? Most assets have more than 2

**Comment by sschiessl-bcp** [comment]
> Will the 2 decimal check work properly? Most assets have more than 2

It is after all a facilitation, the user can be expected to read the actual number that is the result of his pasting. Recognizing 3 digits after comma might recognize thousand separators
