### ISSUE TITLE
Migrate OpenLedger Sign in functionality.

### ISSUE THREAD

**Issue by MikhailKavalenka** [bitshares/bitshares-ui#2025]
Part of #1832

**Description**

Merge the OpenLedger Sign In page to the BitShares code.

**Comment by sschiessl-bcp** [comment]
Missing existing feature from login functionality (copied from PR):

Current login popup functionality supports existing wallets (loaded from internal database, not .bin file) with preselection of last used wallet
![image](https://user-images.githubusercontent.com/33128181/47285351-dc4e9080-d5ea-11e8-95f0-d3307399bd08.png)
![image](https://user-images.githubusercontent.com/33128181/47285324-c80a9380-d5ea-11e8-8525-e9f0317ffe67.png)
