### ISSUE TITLE
[0.5] Add a link to hackthedex.io in readme and UI

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2027]
**Is your feature request related to a problem? Please describe.**
As a community member I want a link to https://hackthedex.io (the bounty program) in the main page of this repository, and a link in the UI, so that people who find a security issue will know where and how to report it.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by startailcoon** [comment]
Adding hackthedex.io linkage would be good for the community. 
We should add it the main as well as the in app help section imho.

**Comment by cogutvalera** [comment]
> Adding hackthedex.io linkage would be good for the community.
> We should add it the main as well as the in app help section imho.

absolutely agree ! It must be near help section in menu ;)

**Comment by abitmore** [comment]
> ...  in app help section ...

I thought the "help" button would be removed some time in the future?

**Comment by startailcoon** [comment]
> I thought the "help" button would be removed some time in the future?

No reason to not add it untill this is the fact, but we shold of course add it to a place in-app that will not make it visible to users, easily.

**Comment by startailcoon** [comment]
New section added to Help doc under TOC for `Development` including a "Hack the Dex" section
