### ISSUE TITLE
Show paid fees in account activities

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2028]
**Is your feature request related to a problem? Please describe.**
A user got frustrated when unable to find where his BTS has gone.

> L:
I created some coin and noticed I lost ~10,000 BTS from my balance. I found 5,000 BTS on my coin FEE POOL and have no idea where is other ~5000 BTS... nothing interesting on my activity history. 
Does anybody know why it happened?
Why we do not mention anywhere that if you create new asset you will pay some money or do transfer from your account to asset balance pool?
> A:
We do
> L:
Where??
> A:
It's the create asset operation fee
> L:
What is this fee?
> A:
You confirmed it
> L:
5000 BTS? :D
> A:
Depends on symbol length
> L:
Fuck
I really paid 10,000 BTS yesterday when tested assets
Testing was not so terrible in my life before yesterday
Btw it would be nice to be able to see fees in account activity
Because based on my activity now I have no idea where I spent 10k bts
> B:
fees were there
![image](https://user-images.githubusercontent.com/9946777/47145791-e4e15700-d2ca-11e8-92d7-d32d20b0cc2a.png)
> L:
So some bad developer removed them :grinning:

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by clockworkgr** [comment]
whats worse...actually a UI dev :D

**Comment by fractalnode** [comment]
it would be useful to have such a message before creating a token.
"If this is your first token and you create it for testing purposes, use the test-network for this."

Now we have to provide the right amount of TEST tokens to create a token, or lower the fee. At present, you can not even create an account, and the received TEST tokens are not enough to test the network.

**Comment by sschiessl-bcp** [comment]
Duplicate #2016
