### ISSUE TITLE
[3.5] Redesign & Antify Buy Modal

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2033]
<img width="489" alt="screenshot 2018-10-19 02 13 42" src="https://user-images.githubusercontent.com/35899973/47189335-a6887e00-d344-11e8-8abd-8d31c1627fb4.png">

**Comment by startailcoon** [comment]
## Antified Buy Modal

- [x] Implemented the new Style Guide components to the Buy Modal.
- [x] Cleaned the code from redundant and/or unused code

### Normal Mode
![bild](https://user-images.githubusercontent.com/12114550/54074361-e8817480-4291-11e9-99e9-d96c33bfa957.png)

### Narrow Mode
![bild](https://user-images.githubusercontent.com/12114550/54074402-5168ec80-4292-11e9-9d4f-d8645949d8d3.png)

### Bridge Tooltip moved to hover
Using the new styleguide `<Form>` component I've moved the tooltip of the bridge to hover the selection field.

![bild](https://user-images.githubusercontent.com/12114550/54074414-752c3280-4292-11e9-8e64-0e0be3ea111d.png)


### Warning on reached Deposit Limit
![bild](https://user-images.githubusercontent.com/12114550/54074378-1a92d680-4292-11e9-8ab5-a41eeec7af49.png)
