### ISSUE TITLE
[0.75] Sell Button doesn't work on Staging

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2034]
When I try to press "Sell" on Exchange on `staging.bitshares.org` I have the following error:

<img width="1440" alt="screenshot 2018-10-19 02 26 25" src="https://user-images.githubusercontent.com/35899973/47189676-6c1fe080-d346-11e8-96b2-0da523f80fb4.png">

**Comment by gibbsfromncis** [comment]
This one maybe relates to #2036

**Comment by gibbsfromncis** [comment]
<img width="544" alt="screenshot 2018-10-19 04 42 20" src="https://user-images.githubusercontent.com/35899973/47193016-5f58b800-d359-11e8-9d0f-75ded0deb3ec.png">

**Comment by gibbsfromncis** [comment]
@startailcoon *estimate*: .75h

**Comment by sschiessl-bcp** [comment]
Please adjust the estimate if not acceptable.
