### ISSUE TITLE
[1] Deposit doesn't work correct on Exchange Staging 

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2035]
Old Exchange (wallet.bitshares.org):
<img width="518" alt="screenshot 2018-10-19 03 31 44" src="https://user-images.githubusercontent.com/35899973/47191364-827e6a00-d34f-11e8-8d7f-408dfbb80907.png">

New Exchange (staging.bitshares.org):
<img width="522" alt="screenshot 2018-10-19 03 32 03" src="https://user-images.githubusercontent.com/35899973/47191375-8dd19580-d34f-11e8-81b0-c5dac9f9d8d2.png">

<img width="511" alt="screenshot 2018-10-19 03 46 30" src="https://user-images.githubusercontent.com/35899973/47191717-9a56ed80-d351-11e8-847b-15e0179c4fd8.png">

**Comment by sschiessl-bcp** [comment]
Should we maybe switch to the general deposit modal and preselect asset and gateway?

**Comment by startailcoon** [comment]
> Long term: Should we maybe switch to the general deposit modal and preselect asset and gateway?

I was thinking the same thing when going through the exchange redesign.
