### ISSUE TITLE
[0.5] Add Ability to Invert the Call Price Ratio For Borrowed Assets

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#204]
Under ACCOUNT tab under Margin Positions I see:

x bitCNY	   y BTS	  RATIO 	(CALL PRICE)    BTS/bitCNY

but I would rather it was:

x bitCNY	   y BTS	  RATIO 	 (CALL PRICE)    bitCNY/BTS

You have the ratio flipped the least useful way.

(EDITED AFTER ERROR I MADE)

**Comment by landry314** [comment]
By the way, on cryptofresh we see the same error under "CNY Debt Positions (Call Orders)":

https://cryptofresh.com/a/CNY

**Comment by wmbutler** [comment]
Needs to be researched and once confirmed, we can classify it as a bug.

**Comment by landry314** [comment]
considering this error is also on cryptofresh, it could be in the core. you need to find where the inverse is being made as a miscalculation.

the call price is most useful as  BTS/bitCNY because that is what most people are looking at i assume. you have that label shown but the value is calculated as bitCNY/BTS.

**Comment by landry314** [comment]
This is a bug, not a question. Just go into margin and look at the column, the ratio is flipped.

**Comment by landry314** [comment]
The ratios are also inverted in the recent activity feed. Can't you see this? LOOK. This is an incredible mistake.

**Comment by wmbutler** [comment]
Man, I've got to say, your tone sucks. We are all here to help so try not to be so condescending, please.

**Comment by svk31** [comment]
Agree with Bill about the tone.

On the issue itself, your missing the fact that there is no "right" way of displaying prices, you may prefer one market direction while I prefer the other. In the recent activity feed you can click the price and invert it so it uses the direction you prefer. We could certainly enable that for the call prices as well.

**Comment by landry314** [comment]
I apologize about my tone. I appreciate all the work you have done.

I agree that adding INVERT THE PRICE for the Call Price would be a good feature to please everyone.

**Comment by wmbutler** [comment]
Could use some help estimating this @svk31

**Comment by wmbutler** [comment]
I think we need to adopt an icon for price inversion across the entire site. Ideally, clicking on an asset would take the user to the asset explorer page, while clicking on an inversion icon would invert the price and clicking on a a market/exchange icon would take them to the exchange. We are currently trying to pack too much functionality into the display of a trading pair.

**Comment by wmbutler** [comment]
Short term fix (before tables rewrite): Add text above "Update Position" titled "Invert Price"

![screen shot 2017-09-01 at 10 35 50 am](https://user-images.githubusercontent.com/1254810/29976942-61f3de3e-8f01-11e7-8266-1966fb0782cb.png)

**Comment by landry314** [comment]
Maybe "Invert Pair" or "Flip Ratio" or "Invert Ratio" might work too. "Invert Price" to me feels like an action you might be doing to your position when next to two other position actions.

**Comment by wmbutler** [comment]
"Invert pair"

**Comment by svk31** [comment]
Or we could just revert it to the old behaviour which is like this:

![image](https://user-images.githubusercontent.com/6890015/30061029-01c27f46-9246-11e7-94fe-e5a1dfa5f8a3.png)

**Comment by landry314** [comment]
One other place we can't invert the ratio is after clicking "See open orders" from the rightmost menu under ACCOUNT tab. I have to use a calculator to invert it sometimes. I'll create a new issue now.
