### ISSUE TITLE
MMORPG style trading panel

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#2041]
**Is your feature request related to a problem? Please describe.**

If/when videogames start using the BTS DEX for their inventory management, such as collectable cards or MMORPG weapons/armour, users cannot trade multiple 'items' (UIA) on the market in return for one or many items. 

Users would be limited to trading one item for another, or trading against non-item currencies on the market where anyone can jump on the open orders. If users wish to directly trade items with one another they would have to risk trading without any safety mechanisms in place (risking sending items and not having the other party hold up their end of the deal), alternatively they would have to use a human escrow entity which would slow down the trading process.

**Describe the solution you'd like**

Similar to most MMORPGs, a direct trading panel between two entities would highly improve the safety of trading directly between users (off the markets).

One user would request to trade, the recipient would get a notification and would be presented the option to either accept or deny the trade request.

Upon accepting the trade request, the users would then begin adding items/tokens to their side of the trade from their BTS portfolio (inventory). When ready, they would each click 'accept' to finalize/lock the trade conditions. If after clicking 'accept' either side changes their trade contents then the 'accept' buttons would be de-activated for both parties, so as to prevent bait & switch scams.

A memo chat mechanism within the trade interface to aid in the trade negotiations would be pretty cool but perhaps that's outside scope of the minimum trading panel functionality - something that a videogame or web wallet could implement themselves externally to the blockchain?

Where available, miniature pictures for currency/items would be shown within the trading panel, perhaps limited solely to the main assets in the reference client & item images shown within the videogame interface as opposed to supporting thousands of unique item sprites within the bitshares-ui repo.

**Describe alternatives you've considered**

Explore third party escrow mechanisms on the BTS DEX.

Not using the BTS DEX for videogame inventory management.

**Additional context**

Here's some example trading interfaces from some videogames:

![image](https://user-images.githubusercontent.com/15861527/47270887-23e10800-d56a-11e8-9c35-dd35f0033be6.png)

![image](https://user-images.githubusercontent.com/15861527/47270966-15472080-d56b-11e8-9e58-60d0e963d5fc.png)

![image](https://user-images.githubusercontent.com/15861527/47270976-44f62880-d56b-11e8-86d5-8269fb099df9.png)

**Comment by abitmore** [comment]
IMHO it's better to use proposals for p2p trading (swapping) if all the items are on the same chain, then no escrow is needed, see https://github.com/bitshares/bitshares-ui/issues/866. If an item is not on this chain, then it's a different story, perhaps HTLC would help.

**Comment by sschiessl-bcp** [comment]
> IMHO it's better to use proposals for p2p trading (swapping) if all the items are on the same chain, then no escrow is needed, see #866. If an item is not on this chain, then it's a different story, perhaps HTLC would help.

> Similar to most MMORPGs, a direct trading panel between two entities would highly improve the safety of trading directly between users (off the markets).

Will be part of #1859
