### ISSUE TITLE
History CSV filename defaults to using zero-based month

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#205]
When exporting history as csv from the GUI, the filename defaults to using zero-based month which may be confusing to end users.

Example: btshist-2017-6-22.csv is generated for a history exported on July 22.

**Comment by landry314** [comment]
i think you mean JUNE 22.

also, that is NOT a zero based month in your example, so what are you saying?

i think file names SHOULD have months with leading zeros to keep them conformed in length and therefore easier to search for when in a large list.

**Comment by wmbutler** [comment]
I'd agree that if you export a file on July 22, it should probably be named appropriately. I'd also advocate a time on the filename down to the second to differentiate it from other files downloaded on the same day. Maybe this:

```
accountname-YYYYMMDD-HH:MM:SS.csv
```

**Comment by happyconcepts** [comment]
Is this why the Bitshares GUI is so poor? This is a simple fix to an obvious (minor) bug. Yet here it gets stalled to a feature request because you want to add a time stamp.

**Comment by landry314** [comment]
I agree that this should be fixed immediately but they don't have enough programmers working to get things done quickly. This is actually the fault of the shareholders of BTS for not voting worker proposals in. We need development money asap!

I am frustrated too.

**Comment by happyconcepts** [comment]
Landry instead of changing your username and  deleting your earlier disparaging comment .... why not be supportive or even friendly? Is there some way you might even contribute toward helping solve this issue?

**Comment by landry314** [comment]
i deleted my earlier comment because i researched and realized it was technically wrong, that is all. i have not changed my username, i dont know why you think that. could you please stop using this forum for anything other than improving the software? thank you.

**Comment by happyconcepts** [comment]
Closed thx Ash

**Comment by wmbutler** [comment]
It's important that we have constructive comments here. If you choose to conduct your family or business in a disrespectful manner, that is your prerogative, but kindly refrain from gross generalizations about people's perceived capabilities or character.

**Comment by wmbutler** [comment]
@happyconcepts a time stamp doesn't stall a feature. There are many things playing into the current ui state of affairs. The time stamp suggestion plus the account name was just a suggestion designed to add more clarity to the file. This would also prevent overwriting a previous file of more than one export was pulled in a day. Also, it was a suggestion designed to be discussed on its own merits.
