### ISSUE TITLE
Node Autoselection toggle produces error

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2054]
This switch:

<img width="266" alt="screenshot 2018-10-23 07 30 05" src="https://user-images.githubusercontent.com/35899973/47335776-78cd6d00-d695-11e8-82df-69e686b45a31.png">

**Comment by sschiessl-bcp** [comment]
I could not reproduce that issue. Please provide instructions!

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp everything fine on the latest developer version
