### ISSUE TITLE
[1] Fix Add Node modal on Settings

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2056]
<img width="1406" alt="1" src="https://user-images.githubusercontent.com/35899973/47335884-014c0d80-d696-11e8-9c8f-a98dbfcd0730.png">

**Comment by startailcoon** [comment]
@gibbsfromncis Please describe what needs fixing, is it ANT migration or something else?

**Comment by gibbsfromncis** [comment]
@startailcoon button doesn't work at all. Modal doesn't appear.

**Comment by gibbsfromncis** [comment]
@startailcoon final estimate: 1h
