### ISSUE TITLE
[2] Fix broken ant form item labels

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2060]
The first Label is wrong because it is not responding our style-guide. The second label is normal. Should find workaround or fix labels based inside ant components somehow 

<img width="202" alt="screenshot 2018-10-24 07 19 22" src="https://user-images.githubusercontent.com/35899973/47406004-235c9300-d75d-11e8-83e7-0ad2aae02373.png">

**Comment by startailcoon** [comment]
Allocating 2 hours for research and workaround fix.
