### ISSUE TITLE
Replace login popup

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2068]
Related to new sign-up and login UX on separate route, dependent on a finished #2025

Aim is a single source of login code, I would envision that the login popup uses the mobile view of the login route
![image](https://user-images.githubusercontent.com/33128181/47285452-46ffcc00-d5eb-11e8-9f1a-4e5df6027ccc.png)

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I had task #1997 about replacing OL UI elements by our style-guide components.

**Comment by startailcoon** [comment]
I like the OL mobile view for login. Please coordinate efforts to make it use our style-guide.

**Comment by sschiessl-bcp** [comment]
Why closing? Is your other issue for antifying the new signup / login. But the new signup / login does not contain a login pop-up

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp my task is about to antify all changes OL migrated.

**Comment by sschiessl-bcp** [comment]
Yes, and they are not migrating a new pop-up for login

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp it looks like their popup, no?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp as I see this task relates to #2025 and #2025 relates to #1832 (OL Task). So it is still in scope of my task.
