### ISSUE TITLE
Controlling Which Accounts Are in Drop Down Menu on Top Bar

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#207]
I can't figure out how to control which accounts are in the drop down switching menu at the top.

I have an old trading account which won't go away, I don't want it there, how can I make it leave?

Is it that there is the teeeeeeniest little bit of BTS left in it which for some reason did not transfer over when I clicked on AVAILABLE when I swept the funds? (another bug, actually). To get that amount out I would have to spend more on the transfer fee than is there causing me to LOSE money, which is stupid, I want to just leave it there, but if that is the way to get that account off the 
dropdown menu then I will...

But I am only guessing how this works and why accounts get put up there.

My feature request here is to add a column to Settings -> Accounts, other than View Keys and Hide/Unhide that can control this. Maybe call it Active/Inactive or Menu/Not in Menu...

Can anyone explain how to control this? Maybe there is a command I can execute in the CLI.

**Comment by wmbutler** [comment]
This is handled with the "star".

**Comment by landry314** [comment]
Well, that is good to know, but this certainly needs to be documented or explained in a help dialog somewhere. The problem is I HID THE ACCOUNT before I ever unstarred it so it remained starred even though I couldn't see it was starred. This is bad design. I just unhid it then unstarred it and it worked. Thanks.

I recommend that "hiding" and account also "unstars" it. Does this make sense as a design change? Doesn't this match what a user would expect?

If not, how about ADDING THE STAR FEATURE to Settings -> Accounts? Now, that we can agree on, right? If that is the account management area then I should be able to star and unstar there! This would solve the confusion I had and make the account management easier.

Does anyone agree?

**Comment by landry314** [comment]
Well, I just did a clean install of my Mac OS Light Wallet Application to fix my disappearing account 
problem and I ran into some issues related to this thread.

When I first restored the Wallet, ALL of the accounts in the Wallet were in the dropdown menu above even though none of them were "starred". As I started hiding most of them, they started disappearing from the dropdown. I made sure to star the one I am trading with so I won't lose it next time my account disappears. Now it is working as expected with hiding removing them from the Follow list and unstaring removing them from the dropdown.

There are issues with account management. I suggest a rehaul making the Settings -> Accounts a place to completely manage accounts in clear way. Staring is unclear. The bugs with reloading and disappearing accounts and dropdown items staying there when hidden makes the experience uncomfortable. These are accounts with money in them and so they really need to feel solid.

**Comment by landry314** [comment]
I could create a new thread but the subject of this thread could just be changed to "Account Management Overhaul". I have posted a few issues now related to account management. It is getting a little confusing, I know, I am sorry. I could create a whole new thread with ideas on how Settings -> Accounts could be rehauled but I haven't looked at the code, only been using the application.

**Comment by landry314** [comment]
Had another idea about this... I suggest renaming the Accounts section in the bitshares menu on the left to "Followed Accounts" or something like that. It would be cleaner because the Settings -> Accounts section has the same name. Then of course there is the Account section just about the current personal account so maybe change Settings -> Accounts to "Account Management" or something like that.

**Comment by wmbutler** [comment]
I'm going to leave this closed since your question was addressed. I did, however, create an Epic to contain the account related issues.

**Comment by landry314** [comment]
I can not find the epic to deal with this issue, @wmbutler. Can you reference it here if you indeed made one?
