### ISSUE TITLE
[0.5][Buy/Sell Form] Fonts are too small

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2073]
Minimum font size should be bigger.
Version: BitShares2-light_2.0.181031-rc1_amd64.deb
![buy/sell](https://i.postimg.cc/cHkb8WMS/Buy-formular.png)

**Comment by sschiessl-bcp** [comment]
I agree, if you look at the textfields and boxes the text does a) not appear to be centered, and b) has lots of margin top and bottom that can be reduced by increasing font size (not making the box bigger tho)

Thanks for testing frooze!

**Comment by startailcoon** [comment]
Thanks!

Removed decreased font-size 

![image](https://user-images.githubusercontent.com/12114550/47525732-4478cd00-d89e-11e8-8fb9-eaa861fed7be.png)
