### ISSUE TITLE
[Buy/Sell Form] Remove one Quick Deposite button

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2074]
Having exact the same button next to each other looks like a sellout and is unnecessary.
![buy/sell](https://i.postimg.cc/cHkb8WMS/Buy-formular.png)

We can just remove the Quick Deposit on the borrow side.

**Comment by startailcoon** [comment]
The buttons have different assets, one is for the Buy asset, the other is for the Sell asset.
