### ISSUE TITLE
[0.25][Order Book] rename Volume -> Market Depth

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2076]
**Volume** should be replaced with **Market Depth**.

![volume-bug](https://i.postimg.cc/1RDrV60z/Market-Depth-Error.png)

**Comment by sschiessl-bcp** [comment]
What does binance call it?

**Comment by froooze** [comment]
Binance call it in the backend `orderbook` on the alt-icons text. The `Depth` chart is a visualization of the order book. Therefore `Market Depth` suites better than `Volume`.

**Comment by cloud-8** [comment]
Agree market depth is a measure of the cumulative total of orders in the orderbook and should be used here. Volume is a measure of turnover of both buys and sells on an orderbook. Different measures.

**Comment by sschiessl-bcp** [comment]
> Agree market depth is a measure of the cumulative total of orders in the orderbook and should be used here. Volume is a measure of turnover of both buys and sells on an orderbook. Different measures.

Agreed here, I'd recommend to accept the suggestion.

**Comment by startailcoon** [comment]
Sounds all good to me, thanks for pointing it all out nicely @cloud-8

**Comment by startailcoon** [comment]
![bild](https://user-images.githubusercontent.com/12114550/48317160-786a2700-e5ee-11e8-8cea-587efad3c22e.png)
