### ISSUE TITLE
First Wallet Has to Be Named "default"

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#208]
When creating the first wallet in the light wallet program you HAVE to call it "default". This is annoying.

I simply created another wallet with a name I wanted then deleted the "default" wallet and everything is fine. There is nothing "default" about it, JUST FIRST, which is bad programming because its name implies something about it which isn't true, nothing defaults to it for any reason.

Many people therefore will have the same name in their wallet backup file which could potentially cause confusion if there are many from different times and devices, etc., that have collected together for some reason.

Just let us name the first wallet whatever we want, please!

**Comment by wmbutler** [comment]
Can you submit some screenshots or a video of the process you are referring to? Thanks!

**Comment by landry314** [comment]
Steps to reproduce:
1) Go to https://bitshares.openledger.info/create-account/wallet
2) Click on Settings cog
3) Click on Wallet
4) You see no active wallet
5) Click on New Wallet
6) You are not given the option to name the wallet
7) The wallet created has the name "default"
8) Click on New Wallet again
9) Name the new wallet whatever you like

You must create the wallet named "default" before you can create a new wallet named what you like then you can delete the default wallet. If there is no wallet yet, it does not allow you to name it what you like.

**Comment by landry314** [comment]
![no wallet yet](https://user-images.githubusercontent.com/6866501/28541368-c5306d6c-7086-11e7-8620-c10c87940046.jpg)
![no wallet name choice](https://user-images.githubusercontent.com/6866501/28541372-c889c9a4-7086-11e7-920d-c303a595284f.jpg)

**Comment by landry314** [comment]
And I just found another bug with the default wallet name...

I just did a clean install of my light wallet then restored the backup I just made. Guess what? My wallet is now called "dafault". The restore feature just ignored the name of the wallet and called it "default". Why? Probably because it is the first wallet in this instance of the program...

The wallet management just loves the name the first wallet default when it is creating one and when it is restoring one. In the code this is probably the exact same fix... somewhere the name "default" is being forced on a wallet if there are no wallets present.

**Comment by wmbutler** [comment]
Thanks!

**Comment by Ashaman-** [comment]
I think the wallet name should default to something, rather than be an extra blank for the user to fill in during account creation. Defaulting it to the name of the first account registered instead of 'default' would make a lot of sense.

**Comment by abitmore** [comment]
From the steps we know this is for advanced users. I don't think this is high priority.

**Comment by wmbutler** [comment]
I'm closing this for now. It's such a fringe request.

**Comment by landry314** [comment]
Fair enough, but then I will create a new issue for the restoring bug mentioned on July 24 in this thread. When you restore a wallet, it changes the name to default and forgets whatever custom name you had... it is a related bug and probably has the same core reason.
