### ISSUE TITLE
[Settlement] Settlement with assets in black-swan need an extra warning about different price

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-ui#2080]
**Is your feature request related to a problem? Please describe.**
See [here](https://bitsharestalk.org/index.php?topic=27268.msg323164;topicseen#new).
A user settled bitBTC and was surprised of the settlement being executed right away at
a price that was not the feed price!

**Describe the solution you'd like**
We'd need an extra popup/warning when settling a black-swaned asset!

**Describe alternatives you've considered**
Anything works that lets the user know about the consequences of settlement in case of black-swanned assets.

**Additional context**
None

**Comment by sschiessl-bcp** [comment]
Duplicate #2048
