### ISSUE TITLE
1 Click Toggle – Market Depth / Trading View Chart

### ISSUE THREAD

**Issue by fractalnode** [bitshares/bitshares-ui#2081]
at the moment, the user needs 4 clicks to change the graph view
as an active user, I would like to make fewer moves to get information about the market that interests me. Also applies to the new version with the "Personalize" option.

![image](https://user-images.githubusercontent.com/20418259/47582408-8d8b5880-d954-11e8-9c86-86f12b0ba2ce.png)

![image](https://user-images.githubusercontent.com/20418259/47582469-b6abe900-d954-11e8-91f2-239115f11acf.png)

**Comment by froooze** [comment]
We have enough space to add:
+
-
next to Price Chart to allow people adjusting the size of the chart

**Comment by startailcoon** [comment]
To summarize the suggestions here

1. Allow switching between Price Chart and Market Depth with a toggle button directly on the screen without additional sub-menu actions.
2. Allow chart resizing directly on the screen without additional sub-menu actions.

I've had this up before, and agree with you both, especially with (1). We need to find a good place to put this action that works on mobile screens as well.

**Comment by froooze** [comment]
We could also save some space renaming the buttons to:
- Chart/Depth or Tradingview/Depth like it is on binance
- Options

**Comment by startailcoon** [comment]
This is now possible. Closing
