### ISSUE TITLE
[Buy/Sell Form] Add asset to "Quick Deposit" button

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2083]
We have two different buttons, but with the same name.
https://github.com/bitshares/bitshares-ui/issues/2074#issuecomment-433155063

We should change the name to "Deposit Asset" as it was in the old layout.

Example: "Deposit BTS" and "Deposit bitUSD" to explain the differences.

**Comment by startailcoon** [comment]
Duplicate of #2130
