### ISSUE TITLE
[2][manikey123] Change toolbar arangement and ANTify seach fields

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2084]
We should consider the top left corner as the best position for a search box, as it is on other layouts. 

![asset-arange](https://i.postimg.cc/cL4MzmCR/left-assets.png)

Preferred Layout:
| Quicksearch | Radio Buttons | rows selection ____________________|

**Comment by startailcoon** [comment]
Do you suggest that we should move the "Quick Search" to be the first element in the row of actions?

**Comment by manikey123** [comment]
I would like to claim this task

**Comment by ryanRfox** [comment]
Welcome to BitShares development @manikey123 glad we made the connection thru Telegram :) I'm going to leave you in the capable hands of my colleagues @wmbutler and @startailcoon to provide proper onbaording to the UI Team. Thanks in advance for your contributions. Cheers!

**Comment by wmbutler** [comment]
@startailcoon I agree that the quicksearch/filter should be on the left.

**Comment by manikey123** [comment]
> @startailcoon I agree that the quicksearch/filter should be on the left. @manikey123 are you open to placing this for all quicksearch occurrences as part of this issue?

sounds good. can you help me get setup ? what dev branch should i use ?

**Comment by manikey123** [comment]
completed development.

**Comment by manikey123** [comment]
git pull origin develop
git checkout -b pull-request-2084
git push origin pull-request-2084 < this step fails >

**Comment by manikey123** [comment]
error msg received - remote: Permission to bitshares/bitshares-ui.git denied to manikey123.
fatal: unable to access 'https://github.com/bitshares/bitshares-ui.git/': The requested URL returned error: 403

**Comment by cogutvalera** [comment]
you don't have permission to `bitshares` orgranization, you can commit in your organization only and make PR (Pull Request) after pushing

**Comment by manikey123** [comment]
created pull request --> https://github.com/bitshares/bitshares-ui/pull/2114#issue-228153471

**Comment by sschiessl-bcp** [comment]
> @manikey123 are you open to placing this for all quicksearch occurrences as part of this issue?

Did you scan the UI to find where other quick search bars are used?

**Comment by manikey123** [comment]
I have not scan UI for other occurrences for "quick search bars".
I shall do so and update later by PST eod.

**Comment by manikey123** [comment]
A>
The quick search option for markets looks completely different from other three search options. Do you want me to make it consistent with other three tabs ?
B> The quick search option for market tab has a clear option ie user can clear the text while he types. Now this option is unavailable in Assets, Witness, Commitee tabs. Let me know if same "Clear" option from Markets filter can be added to other three tabs.

**Comment by manikey123** [comment]
![image](https://user-images.githubusercontent.com/22608398/48247085-db697d00-e3a6-11e8-8c48-0c11d828c8fe.png)

**Comment by manikey123** [comment]
![image](https://user-images.githubusercontent.com/22608398/48247105-ee7c4d00-e3a6-11e8-949a-45f12ce3fc72.png)
![image](https://user-images.githubusercontent.com/22608398/48247139-12d82980-e3a7-11e8-8b89-e3e0fb06e36c.png)

**Comment by manikey123** [comment]
![image](https://user-images.githubusercontent.com/22608398/48247233-6b0f2b80-e3a7-11e8-9c2f-b4528137110f.png)
Explore >> Markets.    this is stretched out and has clear text option

**Comment by sschiessl-bcp** [comment]
> A>
> The quick search option for markets looks completely different from other three search options. Do you want me to make it consistent with other three tabs ?

Yes, please.

> B> The quick search option for market tab has a clear option ie user can clear the text while he types. Now this option is unavailable in Assets, Witness, Commitee tabs. Let me know if same "Clear" option from Markets filter can be added to other three tabs.

Yes, the search component could get a new props to show this clear "x" when user has typed something. This must probably be changed in style-guide? @gibbsfromncis 

> C>wallet.bitshares.org has Active | Hidden option . can be developed for the other quick search options

Active | Hidden is only necessary there

> D>In "Exchange". under MY Market and Find Market are other Filters

It should be the same component as A

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp you're talking about `allowClear` option for `Select`. For input we haven't this feature.

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp you're talking about allowClear option for Select. For input we haven't this feature.

Let's skip the clear for now, can be implemented later.

**Comment by manikey123** [comment]
![image](https://user-images.githubusercontent.com/22608398/48465028-5ad7c180-e796-11e8-9f83-c87b590c682a.png)
Comparing witness page against market page
point 1 ) Witness has placeholder as "Filter By Name "  . Markets has "Filter...". Should this be replaced by "Filter By Market"
point 2) Market has a Cross on the UI . this is part of Clear-text option. Do you want to keep that stray Cross on UI or comment that out ?

**Comment by gibbsfromncis** [comment]
@manikey123 I suppose those updates do not relate to scope of this task. You can create separate issue for that and get new estimate or somebody else will fix it

**Comment by manikey123** [comment]
Under Explore TAB, following pages have same structure, on my local. 
- Witness
- Markets
- ASSETS

Is below in scope of ticket ie making filter consistent as Explore TAB changes ?
- Exchange Tab >> Find Markets >> Asset Name Filter 
- Dashboard Tab >> Portfolio Filter 
- Dashboard Tab >> Open Order Filter

**Comment by sschiessl-bcp** [comment]
> @manikey123 I suppose those updates do not relate to scope of this task. You can create separate issue for that and get new estimate or somebody else will fix it

Bill suggested it above and mani agreed, so all good.

**Comment by gibbsfromncis** [comment]
@manikey123 @sschiessl-bcp Oh, just didn't read all comments. What I see that the task is to change toolbar arrangement but if you already start to work out of scope with @sschiessl-bcp so do it :)

**Comment by sschiessl-bcp** [comment]
> point 1 ) Witness has placeholder as "Filter By Name " . Markets has "Filter...". Should this be replaced by "Filter By Market"

My suggestion is to use "Filter ..." in both

> point 2) Market has a Cross on the UI . this is part of Clear-text option. Do you want to keep that stray Cross on UI or comment that out ?

Yes, remove it 

> - Exchange Tab >> Find Markets >> Asset Name Filter

Leave this one untouched as of now, another issue is updating that component

> - Dashboard Tab >> Portfolio Filter
> - Dashboard Tab >> Open Order Filter

Replace those

**Comment by manikey123** [comment]
thanks for the notes

**Comment by manikey123** [comment]
point 1 ) Witness has placeholder as "Filter By Name " . Markets has "Filter...". Should this be replaced by "Filter By Market"
My suggestion is to use "Filter ..." in both
Question for point1--> Should there space between Filter and "..."   ie Filter<space>... ?


point 4) Dashboard Tab >> Portfolio Filter
Dashboard Tab >> Open Order Filter
Replace those
question for point4 ) Replaced Portfolio Filter on local. Default placeholder=Filter. Should that be replaced by "Filter ..." like in point 1 ? 
![image](https://user-images.githubusercontent.com/22608398/48473233-eceac480-e7ac-11e8-9e71-27dfd2bd5428.png)

**Comment by sschiessl-bcp** [comment]
> Question for point1--> Should there space between Filter and "..." ie Filter... ?

Please decide small details like that by yourself depending on common practices and what you find suitable. If it should be not appropriate someone will point it out.

> question for point4 ) Replaced Portfolio Filter on local. Default placeholder=Filter. Should that be replaced by "Filter ..." like in point 1 ?

Yes

**Comment by manikey123** [comment]
thanks for feedback . completed majority changes on local. 
Last question - Do I implement same changes for home page  ? ( image below)

1. Update Placeholder from Filter to "Filter..."
2. Add Search Icon 

For below items: 
Favorites:
![image](https://user-images.githubusercontent.com/22608398/48475183-16a5ea80-e7b1-11e8-8fa7-a740457f3181.png)
BTC : 
![image](https://user-images.githubusercontent.com/22608398/48475230-350be600-e7b1-11e8-92c7-14919b8d5bed.png)
BTS , CNY, ETH, USD

**Comment by sschiessl-bcp** [comment]
Yes, please update to the new bitshares-style-guide components and keep it consistent.

**Comment by manikey123** [comment]
for ticket #2084, completed development. i did have a previous push. now do i merge changes to old push or create a new push request.

**Comment by manikey123** [comment]
Submitted PR. Following are Tabs impacted:

Tab Explore
	Assets      https://wallet.bitshares.org/#/explorer/assets     
	Witnesses	https://wallet.bitshares.org/#/explorer/witnesses
	Committee
	Markets

Tab Dashboard https://wallet.bitshares.org/#/account/crypto-25
	Portfolio
	Open Order

Tab Exchange 
	My Markets https://wallet.bitshares.org/#/market/BTS_USD

Tab Home https://wallet.bitshares.org/#/
	Favorites
	BTC
	BTS , CNY, ETH, USD

**Comment by cogutvalera** [comment]
@manikey123 good job ! but you also forget that you changed `Tab Explore` -> `Accounts` (Search to Filter), but search isn't filter, didn't check all details in your PR, but IMHO you don't need to change search to filter anywhere, because search and filter are different things.

**Comment by manikey123** [comment]
> @manikey123 good job ! but you also forget that you changed `Tab Explore` -> `Accounts` (Search to Filter), but search isn't filter, didn't check all details in your PR, but IMHO you don't need to change search to filter anywhere, because search and filter are different things.

Thank you for your feedback.
With regards to filter versus search, also after considering below logic, I need to revert any changes made to Explore >> Account Tab. 

"Filtering takes an existing full list, and removes items based on criteria that match/don't match.
Search takes a blank slate and adds to it based on criteria that match/don't match.
"

**Comment by sschiessl-bcp** [comment]
What is the status here?

**Comment by manikey123** [comment]
completed development. reverted change for Explore >> Account Tab. i shall upload to git in 6-7 hours from now.

**Comment by manikey123** [comment]
i have created a pull request and get error by appveyor. any idea about the issue ?

**Comment by manikey123** [comment]
2084 search fix f1 #2183  --> I just saw this label that had some feedback/changes to be made. I have not incorporated these changes. I shall do so in 24-48hrs.

**Comment by manikey123** [comment]
Updated the code based on the comments received from #2183 
https://github.com/bitshares/bitshares-ui/pull/2250

**Comment by manikey123** [comment]
bitshares account id = betas-11 
Total 6 hours effort for below Tabs impacted :

Tab Explore
    Assets
    Witnesses
    Markets
    Committee

Tab Dashboard
    Portfolio
    Open Order

Tab Exchange
    My Markets

Tab Home
    Favorites
    BTC
    BTS , CNY, ETH, USD

**Comment by startailcoon** [comment]
👍

**Comment by gibbsfromncis** [comment]
@manikey123 please send us your bitshares account name which will receive bounty for this task

**Comment by manikey123** [comment]
bitshares account name is betas-11. Thank you !!
