### ISSUE TITLE
[1.25][StyleGuide] Fix Popover if placement is not top

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2085]
Popover works bad if placement is not `top`. Screenshot:
<img width="393" alt="screenshot 2018-10-24 10 38 01" src="https://user-images.githubusercontent.com/35899973/47606286-8595ec00-da1a-11e8-88b9-35a7e8907a45.png">

**Comment by gibbsfromncis** [comment]
Done by commit: https://github.com/bitshares/bitshares-ui-style-guide/commit/73bdec1041b8a905b26ac6fd6c65d57ee4b8953d

**Comment by gibbsfromncis** [comment]
@startailcoon final estimate: 1.25h

**Comment by gibbsfromncis** [comment]
Screenshots of fixed popover:
<img width="824" alt="screenshot 2018-10-28 03 18 44" src="https://user-images.githubusercontent.com/35899973/47610875-32468c80-da60-11e8-98a7-50f2d3e6d131.png">
<img width="719" alt="screen shot 2018-10-28 at 3 17 30 am" src="https://user-images.githubusercontent.com/35899973/47610876-35da1380-da60-11e8-88ce-c65f6ca01d8e.png">
<img width="778" alt="screen shot 2018-10-28 at 3 17 24 am" src="https://user-images.githubusercontent.com/35899973/47610877-3a9ec780-da60-11e8-8a44-f6b901a1fa82.png">

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp anything wrong? Why did you reopen this issue?

**Comment by sschiessl-bcp** [comment]
Closed through https://github.com/bitshares/bitshares-ui-style-guide/commit/36c1d3f1adcf9063e27bae90a0f82456739c68b8
