### ISSUE TITLE
Keep Download on bitshares.org Up-To-Date

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#209]
I know this isn't actually about the development of the Bitshares UI so I hesitated to post it here but, in the end, maybe it will work to fix the issue.

When a new version of the GUI is released, can whoever controls the bitshares site please compile it and release it for download here:
  https://bitshares.org/download/

I am doing bug testing here with many more bugs to post so not having the newest version might be causing me to waste some time as the bug I am explaining might have already been squashed.

It is also, obviously, good for Bitshares and the Bitshares community to have easy access to the latest compiled version of the GUI.

Asking people to download a bunch of compiling software and libraries to compile their own version is counterproductive as most people won't. We need to make Bitshares as easy to use and as bug free as possible. Right guys? :-)

**Comment by wmbutler** [comment]
Definitely need a procedure for this to happen in an automated way.
