### ISSUE TITLE
[2] Explore Assets - No sorting functionality

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2090]
**Describe the bug**
The assets overview in Explore -> Assets has no sorting feature. When loading the list the assets come up in an unorderly fission. 

Smartcoins has no sorting functionality
UIA has symbol sorting functionality only.

**To Reproduce**
1. Go to Explore
2. Click on Assets

**Expected behavior**
Sorting possibility by both symbol and issuer, perhaps even by supply, and automatic sorting on loading.

**Screenshots**
![image](https://user-images.githubusercontent.com/12114550/47614546-c553e680-daa1-11e8-92ac-2ce3a38c48ba.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Light Wallet
 - Version 181031-RC1

**Comment by startailcoon** [comment]
Dashboard has same page navigation system with sorting and should be replicated on this section as well.

**Comment by alexandr-masl** [comment]
thank you

**Comment by grctest** [comment]
Sorting supply by descending sort doesn't sort correctly:
![image](https://user-images.githubusercontent.com/15861527/51568557-e3a76380-1e91-11e9-909e-04afe40f7d08.png)

**Comment by sschiessl-bcp** [comment]
It looks like it sorts by the integer value neglecting the decimal point. @alexandr-masl
