### ISSUE TITLE
White screen on start-up on Windows 10.

### ISSUE THREAD

**Issue by mountassir** [bitshares/bitshares-ui#2091]
**Describe the bug**
When the application starts, it shows an empty white window, screen shot attached. 
The wallet does seem to work however when I set compatibility to Windows 7.

**Screenshots**
![empty-screen](https://user-images.githubusercontent.com/10292481/47619278-dcf89280-dad4-11e8-823c-8f652ee736f5.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: 10.0.17134

**Additional context**
 I had this issue with both 2.0.180815 and 2.0.181010.

**Comment by startailcoon** [comment]
Can you please attach some output from the log when this happens?

Go to View - Developer Tools and click Console.

**Comment by mountassir** [comment]
I have upgraded to 2.0.181031 now and I am seeing the same issue, in fact, setting compatibilaty mode to Windows 7/8 no longer helps with this build.

These are all the logs I can see in the console:

vendor.7979393919a407f0d0e7.js:45 synced and subscribed, chainstore ready
vendor.7979393919a407f0d0e7.js:63 TypeError: Cannot read property 'url' of undefined
    at t.value (app.b373f2df3545eba73d8f.js:1)
    at t.value (app.b373f2df3545eba73d8f.js:1)
    at t.value (app.b373f2df3545eba73d8f.js:1)
    at Pi (vendor.7979393919a407f0d0e7.js:63)
    at ji (vendor.7979393919a407f0d0e7.js:63)
    at da (vendor.7979393919a407f0d0e7.js:63)
    at ha (vendor.7979393919a407f0d0e7.js:63)
    at $a (vendor.7979393919a407f0d0e7.js:63)
    at qa (vendor.7979393919a407f0d0e7.js:63)
    at Wa (vendor.7979393919a407f0d0e7.js:63)
Fi @ vendor.7979393919a407f0d0e7.js:63

**Comment by sschiessl-bcp** [comment]
This seems to be caused by a node that is out of sync (not the user's clock).

**Comment by sschiessl-bcp** [comment]
Hours included in https://github.com/bitshares/bitshares-ui/issues/1826
