### ISSUE TITLE
[10][alexandr-masl] Explore Accounts - Styleguide + Sorting Update

### ISSUE THREAD

**Issue by alexandr-masl** [bitshares/bitshares-ui#2093]
**Describe the bug**
The accounts overview in Explore -> Accounts has no sorting feature. When loading the list the accounts come up in an unorderly fission.

**To Reproduce**
1. Go to Explore
2. Click on Accounts

**Expected behavior**
Sorting possibility by all fields (id, account name, current balance, percent of total supply), and automatic sorting on loading.

**Screenshots**
![screenshot from 2018-10-29 09-38-50](https://user-images.githubusercontent.com/43892027/47635678-89cb2200-db5e-11e8-8223-2415f6989917.png)

**Desktop (please complete the following information):**
1. OS: Win 10
2. Light Wallet
3. Version 181031-RC1

**Comment by alexandr-masl** [comment]
HI everyone,
I want to make this issue,
estimating about 2 hours,
Thanks in advance

**Comment by startailcoon** [comment]
@alexandr-masl I would prefer that you didn't add hours to the title by yourself. An estimation is okay if you are confident. Also please wait for confirmation of assignment before submitting to much code, to prevent any requirements that would need your work to be redone.

I'm glad that you wish to join and help out with tasks on the repo. This task is inline with what we currently work on and should follow the layout on the Explore Assets page, with the new style guide and components. 

I've assigned this to you.

### Please read and understand the following as a new contributor to the repo.
> Welcome to contribute to the UI of Bitshares. As a new users it's important to follow the standards we use, like the [Bitshares Style Guide](https://github.com/bitshares/bitshares-ui-style-guide) for [ANT Components](https://ant.design/docs/react/introduce).
>
> Please test your cases when submitting them to the repository and follow up on any requests for changes in the submission. 
>
> Keep your PRs names styled with "IssueNo_ShortDescription" and title them "Closes IssueNo - Short Description", this makes handling PRs easier for our developers.

**Comment by alexandr-masl** [comment]
Ok, understood.
Thank you.

пн, 29 окт. 2018 г. в 11:59, startailcoon <notifications@github.com>:

**Comment by alexandr-masl** [comment]
Good day.
New PR https://github.com/bitshares/bitshares-ui/pull/2131 is ready for checking. 
Check please guys.
I've spent more than 10 hours, please extend estimation.
During solving this issue I've found new with sorting BalanceComponent. Will create new issue.
Thanks in advance.

**Comment by startailcoon** [comment]
![image](https://user-images.githubusercontent.com/12114550/48221891-8cfeb300-e393-11e8-92c0-657e93243aab.png)


My reflections for this issue.
- I think we can safely drop the title "Accounts".
- The table should wrap the whole page width, the table headers should not wrap unless necessary.
  - If table headers should be shortened, I think we could go for simple names as "Name", "Balance", "% of total supply"
- Search should be moved to reflect the layout used on Assets page.
- A "rows per page" should be added to reflect the layout used on Assets page.

**Comment by startailcoon** [comment]
I've updated the issue hours to reflect the extended tasks to it.

**Comment by alexandr-masl** [comment]
Hi,
still waiting  for compensation.
Thanks in advance
best regards.

**Comment by sschiessl-bcp** [comment]
The respective invoice is currently being processed
