### ISSUE TITLE
Placeholder for Beet: Planned Development #3: Implement origin verification and authorisation persistence

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/bitshares-ui#2096]
Here: https://github.com/bitshares/beet/issues/9

Closed here: https://github.com/bitshares/beet/pull/24

**Comment by sschiessl-bcp** [comment]
Also https://github.com/bitshares/beet-js/pull/7

**Comment by clockworkgr** [comment]
Closed here: https://github.com/bitshares/beet/pull/26

**Comment by startailcoon** [comment]
As requested, 25 hours for this part of the Beet development process.
