### ISSUE TITLE
[1] Explore Assets - Sorting on issuer sorts by ID

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2100]
Should sort by account name, but might need more extensive refactoring.

**Comment by manikey123** [comment]
dont mind taking this up.
can u elaborate with screen-shot what all sorting on what all fields is needed ? 
what does "extensive refactoring mean ? "
![image](https://user-images.githubusercontent.com/22608398/47948722-c64aa500-def3-11e8-92ef-74a7069019f3.png)

**Comment by alexandr-masl** [comment]
Hi everybody,

So sorry..
Can I get this issue, because  I know what is the problem here, I've made #2090 issue which was similar. 
And I have already started to make it.
Is it possible to assign this issue to me please ?
Sorry one more time

**Comment by sschiessl-bcp** [comment]
@manikey123 I agree with @alexandr-masl and would kindly ask you to pass this on. He worked on the original issue where this surfaced.

Please investigate the issue at hand, and how the account names are rendered. The solution must not fetch the account name twice. Likely the account name must be resolved already for dataSource

**Comment by manikey123** [comment]
@alexandr-masl  please proceed with the ticket   @sschiessl-bcp

**Comment by alexandr-masl** [comment]
Ok, thank you,  
Sorry @manikey123 for your time, will be carefuly next time.
In process ..

**Comment by wmbutler** [comment]
@alexandr-masl Can you finish this up? Let us know if you need more hours.

**Comment by alexandr-masl** [comment]
Hi, @wmbutler 
Yes, had problems  with my phone, i've lost it
i'm back in process now, will make this issue and than tell you how much time i've spent.
Best regards

**Comment by alexandr-masl** [comment]
also don't have access to my Telegram yet
temporary I've connect only through github

**Comment by wmbutler** [comment]
Status...

**Comment by alexandr-masl** [comment]
HI,
a lot of time took the investigation, because the problem, there is not only in sorting.
there comes a wrong data.
So it was necessary to do -RESEARCH and REFACTORING.
I'm very close now,  will finish soon.
Thank you, best regards.

**Comment by sschiessl-bcp** [comment]
@alexandr-masl is your fix already completed? I'd like too see it either way!

**Comment by alexandr-masl** [comment]
Hi, 
Yes- it's ok with issuer column,
But there is another problem in 'SYMBOL' column- the sorter can't see the 'bit' prefix, and now it is sorts by the first symbol after the prefix.
Also in search- you can't filter Assets including the prefix, only by the first smbol after.
Will you also fix that by yourself ?

![screen shot 2018-12-04 at 11 13 27 am](https://user-images.githubusercontent.com/43892027/49431443-33cd4800-f7b6-11e8-8cb0-882c447f4009.png)

![screen shot 2018-12-04 at 11 13 12 am](https://user-images.githubusercontent.com/43892027/49431447-35970b80-f7b6-11e8-8298-30e0a3a1f4a6.png)

**Comment by sschiessl-bcp** [comment]
@alexandr-masl I'd say open a new issue and describe how the functionality should be!
