### ISSUE TITLE
[4.5][nikandrovalex][2][gibbsfromncis] AddonBefore & AddonAfter for StyleGuide Inputs

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2101]
I find the color choices quite ugly, expecially the blue background of the markets / assets.
![image](https://user-images.githubusercontent.com/33128181/47713238-10a0fd00-dc3a-11e8-8d55-8a087dab7056.png)

Thoughts?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp one thought - update it. 

I'll take care about this.

**Comment by gibbsfromncis** [comment]
@nikandrovalex Please based in our style-guide inputs provide nice design for Pre/Post tabs for Inputs (https://ant.design/components/input/#components-input-demo-addon) for all 3 themes

**Comment by startailcoon** [comment]
I'm guilty for this as I wasn't fully knowing the guidelines of the style-guide back when I re-made this and used the ANT components. I've made a few bad overrides to make it look good based on the designs, which wasn't fully compatible with the provided UX.

I'm putthing this in the capable hands of @gibbsfromncis and added an estimated hour to look over this.

**Comment by wmbutler** [comment]
@gibbsfromncis this one is 17 days since claimed. Thoughts?

**Comment by gibbsfromncis** [comment]
@wmbutler Waiting for UX...

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp not much. I'll propose my options and ask @nikandrovalex for his agreement

**Comment by nikandrovalex** [comment]
@sschiessl-bcp please check 
![image](https://user-images.githubusercontent.com/43581164/49668105-d2330500-fa65-11e8-9490-877cf7c256a9.png)

**Comment by nikandrovalex** [comment]
@sschiessl-bcp  I spent 4 hours and 38 minutes on this task. There was a lot of incomprehensible, but @gibbsfromncis  helped me, thanks)

**Comment by gibbsfromncis** [comment]
@nikandrovalex about estimates ping @startailcoon 

@startailcoon added .5h for a call to sync with Alex

**Comment by gibbsfromncis** [comment]
Added hours for time I spent for development
