### ISSUE TITLE
[blckchnd] Maintain Russian language

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2104]
Part of #1705 and split for payout.

Please report your hours @ruslansalikhov

**Comment by ruslansalikhov** [comment]
5 hours

**Comment by Jackcameback** [comment]
@ruslansalikhov Am I paying you? If so please confirm your bit shares address.

**Comment by ruslansalikhov** [comment]
> @ruslansalikhov Am I paying you? If so please confirm your bitshares address.

Hi. Sorry for delay - our account is "blckchnd"
