### ISSUE TITLE
Market page scrolls by itself

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2107]
**Describe the bug**
Market page scrolls by itself

**To Reproduce**
1. Go to 'https://wallet.bitshares.org/#/market/BTS_USD'
2. Scroll down to near the bottom, leave a few orders in order book in the screen
3. Click on "market trades"
4. Wait
5. The page scrolls up and down by itself

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/47809702-d884e180-dd41-11e8-9f04-09b7714e9e3c.png)

![image](https://user-images.githubusercontent.com/9946777/47809738-e63a6700-dd41-11e8-9d6b-e3f5799d347d.png)

![image](https://user-images.githubusercontent.com/9946777/47809849-2568b800-dd42-11e8-8bf9-3c29cf4f261e.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version 69

**Additional context**

**Comment by manikey123** [comment]
can u highlight/color-code  the issue if possible ?

**Comment by manikey123** [comment]
![image](https://user-images.githubusercontent.com/22608398/47959111-6eff1000-df99-11e8-9426-d22f71a70edf.png)  
![image](https://user-images.githubusercontent.com/22608398/47959116-7de5c280-df99-11e8-8a22-7ddb07b60710.png)
is above screen-shot of error captured correctly , captured on regular laptop? kindly confirm so i can develop. i however do not see the same error on larger screen. kindly confirm so i can look into this further.

**Comment by manikey123** [comment]
what is "liceCap" ?

**Comment by abitmore** [comment]
Resize the window to 1366*768 and see. The "asks" tab/panel on the page changes among 5, 6 to 7 lines back and forth.

**Comment by wmbutler** [comment]
A licecap would be very helpful.
