### ISSUE TITLE
[1] [rrandom] Clicking EXCHANGE defaults to "bitUSD : BTS" if Already in Exchange

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#211]
I am almost always using BTS : bitCNY and it stays as the default for me as I change tabs and move around the GUI but if I accidentally click on EXCHANGE at the top WHILE I am already in the exchange area then it switches to "bitUSD : BTS". Why this is the default, I don't know.

The expected behavior for a GUI when you click into somewhere you already are is to DO NOTHING. To change the pair to another pair is unexpected and annoying because every time I do this I need to find my pair again. It wastes time and is not clean programming: there is no reason to assume I would want to switch to bitUSD : BTS.

**Comment by Ashaman-** [comment]
I only observe this after a wallet reload. Otherwise switching between exchange and other tabs returns me to the last trading pair I had open - BTS:bitCNY.

**Comment by rrandom** [comment]
Hi, I could take this issue

**Comment by wmbutler** [comment]
The bounty is for 1 hour. Assigned to @rrandom. Thanks!
