### ISSUE TITLE
'My open orders' contains mixed pairs orders in latest release 181031

### ISSUE THREAD

**Issue by rPman** [bitshares/bitshares-ui#2110]
'My open orders' contains mixed pairs orders from different trading pair and not affected while switching trading pair or change it

**To Reproduce**
go to Exchange page and select any trading pair even if not used in orders

**Expected behavior**
list orders limited only selected trading pair

this bug appears in web or desktop app

**Comment by clockworkgr** [comment]
@startailcoon  @sschiessl-bcp  @gibbsfromncis 

To fix, revert: https://github.com/bitshares/bitshares-ui/commit/e137f9a229fe3eade9cbd5423d13a87dfbf0baee

**Comment by sschiessl-bcp** [comment]
Worst case yes. Hoping to find another way to fix the bug that was targeted with that

**Comment by startailcoon** [comment]
I assume there was no hours added to this

**Comment by sschiessl-bcp** [comment]
Correct

**Comment by startailcoon** [comment]
No hours assigned, removed from milestone
