### ISSUE TITLE
[4] snap bitshares2-light does not start: "Trace/breakpoint trap"

### ISSUE THREAD

**Issue by jcalfee** [bitshares/bitshares-ui#2111]
**Describe the bug**

The snap installed just fine but the client did not start.

**To Reproduce**
```bash
$ snap search bitshares
Name              Version     Publisher  Notes  Summary
bitshares2-light  2.0.180815  svk31      -      Reference wallet for the decentralized exchange and cryptocurrency BitShares (BTS)

$ sudo snap install bitshares2-light
bitshares2-light 2.0.180815 from svk31 installed

$ bitshares2-light 
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Trace/breakpoint trap
```

The Gtk message appears in other apps but the apps still work.  It is probably unrelated.

**Desktop (please complete the following information):**
Debian GNU/Linux 9 (stretch)

**Comment by wmbutler** [comment]
@svk31

**Comment by startailcoon** [comment]
Anyone experienced with snap care to claim this issue?

**Comment by sschiessl-bcp** [comment]
@jcalfee Sorry for the late replay ..

Can you please try with the latest snap, 190227?

**Comment by jcalfee** [comment]
BitShares2-light_2.0.190227_amd64.snap works.

I like the snap because it sandboxes apps.  This snap will be much easier to use than my alternatives: nginx with a local https certificate (that was needed for the API to work reliably), docker..

 Thanks!

**Comment by jcalfee** [comment]
By the way, are you publishing to snap's repo too?  That would need to be updated eventually.
```
$ sudo snap refresh bitshares2-light
snap "bitshares2-light" has no updates available
```

**Comment by sschiessl-bcp** [comment]
> By the way, are you publishing to snap's repo too? That would need to be updated eventually.
> 
> ```
> $ sudo snap refresh bitshares2-light
> snap "bitshares2-light" has no updates available
> ```

Yes, every release. Are you maybe on latest release?
![image](https://user-images.githubusercontent.com/33128181/53948887-24b5a900-40c9-11e9-92ef-c1da5819584f.png)

**Comment by jcalfee** [comment]
Looks good
