### ISSUE TITLE
Assets represented by column Symbol containing "BIT" - not sorted alphabetically

### ISSUE THREAD

**Issue by manikey123** [bitshares/bitshares-ui#2113]
**Describe the bug**
Assets represented by column Symbol, not clearly sorted when they have key-word "BIT"
Part of 2090

**To Reproduce**
1. Go to 'https://wallet.bitshares.org/#/explorer/assets'
2. Click on Symbol sort
3. Scroll down to descending order

**Expected behavior**
Assets with symbol containing "BIT" like BITXCD and BITUSD should be sored under alphabet B

**Screenshots**
![image](https://user-images.githubusercontent.com/22608398/47959258-7247cb00-df9c-11e8-9b7c-78a0103f1cde.png)

**Desktop (please complete the following information):**

 - Browser [e.g. chrome, ]

**Additional context**

**Comment by manikey123** [comment]
kindly confirm if this is bug if so can look into this.

**Comment by startailcoon** [comment]
Duplicate #2100
