### ISSUE TITLE
Add Account Transfer Feature

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#212]
Right now, in order to fully transfer an account to you from another user, you need to generate new private keys in a paper wallet program then send the public keys to them, have them import the public keys into the account being transferred to give you control over that account then you have to delete their old public keys.

This is way too technical for the average user and uncomfortable as well because you need to trust you are doing it right or you can get your account swept (if you forget to delete the other user's keys before funding it or if the paper wallet program is secretly stealing your private keys).

Why not add an account transfer feature to the GUI? This is a more serious project but eventually it needs to be done. As Bitshares becomes more popular, this will be necessary.

**Comment by landry314** [comment]
And a question, I had an account transferred to me and it works fine but it is still a registered account under the person who created it. Is there is a way to change this? To officially transfer it other than just making new keys and deleting the old?

**Comment by landry314** [comment]
Transferring an account from one wallet to another within the same client is almost as difficult. This is another reason we need this new feature.

**Comment by landry314** [comment]
There is a fee called "TRANSFER ACCOUNT". Is transferring an account to another user supported by the blockchain?

**Comment by wmbutler** [comment]
Agree this would be very useful (and complicated)

**Comment by wmbutler** [comment]
Duplicate #264
