### ISSUE TITLE
[0.5] Remove any global & local ant hardcodes if possible

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2120]
<img width="653" alt="screenshot 2018-11-06 04 56 08" src="https://user-images.githubusercontent.com/35899973/48042084-48e79480-e180-11e8-86a4-5684dda4a1c9.png">

Things like this should be handled on style-guide side and any overrides are not possible

**Comment by gibbsfromncis** [comment]
This is an example why ant overrides are bad:
<img width="559" alt="screenshot 2018-11-06 04 59 33" src="https://user-images.githubusercontent.com/35899973/48042185-c6130980-e180-11e8-9552-989fad9f8b7a.png">

**Comment by gibbsfromncis** [comment]
@startailcoon estimate: .5h

**Comment by startailcoon** [comment]
Nice, thanks for fixing this!
