### ISSUE TITLE
Chart size way too big

### ISSUE THREAD

**Issue by leshacat** [bitshares/bitshares-ui#2128]
**Describe the bug**
Graph does not fit inside iframe/window

**To Reproduce**
1. Log In
2. See error

**Expected behavior**
Chart to fit within window, so dont have to scroll up and down to look at the chart.

**Screenshots**
![cryptobridge-bug](https://user-images.githubusercontent.com/43627985/48094925-67ca4300-e1e1-11e8-857c-b5470702b2e0.png)

**Desktop (please complete the following information):**
 - OS: Linux / Debian 9
 - Browser Chromium
 - Version Latest

**Additional context**
Have to scroll up and down to see whole chart

**Comment by leshacat** [comment]
Would be nice if we could also see the orderbook & wall without scrolling down.

Thanks!

**Comment by sschiessl-bcp** [comment]
Please try this at wallet.bitshares.org, CryptoBridge is a third party that has its own UI adjustments

**Comment by froooze** [comment]
In Chart Options you can change the size?

**Comment by gibbsfromncis** [comment]
@leshacat you can use "Chart Options on the right top to change chart height. 

Also https://wallet.crypto-bridge.org is a third-party wallet and we do not support it. Please use https://wallet.bitshares.org
