### ISSUE TITLE
[1.5] View-only mode: Mobile view

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2129]
The new "View Mode" hinders a proper mobile view of the header:

![image](https://user-images.githubusercontent.com/33128181/48124915-ce9d3a00-e27d-11e8-81dd-0500c371593d.png)

My suggestion is that the button minimizes (Icon could also be trailing):
![image](https://user-images.githubusercontent.com/33128181/48125290-9a764900-e27e-11e8-8002-3b07c8d8fa11.png)

This minimization should take place when the Captions in the Header Icons is removed as well, i.e. 
from 
![image](https://user-images.githubusercontent.com/33128181/48125353-c4c80680-e27e-11e8-87ba-aed258e099b2.png)
to 
![image](https://user-images.githubusercontent.com/33128181/48125368-cd204180-e27e-11e8-9503-55c42df19485.png)

**Comment by startailcoon** [comment]
I noticed this issue as well 👍

**Comment by startailcoon** [comment]
View Mode on screen less than 640px breakpoint to be a small icon.
Used the `<Popover />` component for the new icon, as data-tooltip seems to have issues on re-rendering. We should evaluate this problem.

![bitshares-viewmode](https://user-images.githubusercontent.com/12114550/48316515-fcb7ac80-e5e4-11e8-8433-40ab58433274.gif)
