### ISSUE TITLE
Incorrect Max Amount Calculations in Sell Orders to Allow Room for Fees

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#213]
If I am trying to place an order and I want to sell the maximum amount of an asset then sometimes the system makes a miscalculation as to what to make the maximum amount in order to cover the fee at the same time. When the order attempts to place, instead of it placing, an error is triggered that is a human unreadable code dump. If you look carefully you can see the word "Fee" in the code somewhere.

There are 2 separate issues here but since they come from the same situation I am putting them on one github page:

1) I don't know why the calculations are wrong sometimes; I haven't seen the pattern yet. All I know is how to workaround. Usually, I simply click in the quantity edit box and subtract 1 from the least significant digit then try again, but, occasionally, I have to subtract more until it finally works. Why? No idea.

2) Error dialogs should never be just a code dump which is unreadable to the average user. At the least, any error without a specific dialog should trigger a generic dialog that says "Unknown Error" and which has a link to the raw code if needed to troubleshoot. A code dump is ugly and scares a user: it looks like something just crashed which instills fear and lack of trust.

We need to make maximum sell orders happen smoothly without calculation errors and without ugly error dialogs.

Can anyone out there confirm this issue and try to offer more information on why it is happening?

The next time it happens for me I will take a screen shot and upload it.

**Comment by wmbutler** [comment]
This is too general. Please submit specific issues to help resolve specific problems. I do agree with your assessment, but devs need reproducible steps in order to fix problems. Thanks for your help.

**Comment by landry314** [comment]
You closed this already? This is a HUGE problem for many users and I said I would take a screenshot next time. Maybe another user browsing this github would find this and upload their screenshot or comment that they had the same issue. I have this issue quite often.

Also, the second part about the dialog with the code dump, that is something you have to agree on, right? When I get a screenshot, I'll make another issue, because that just looks horrible to the average user.

**Comment by landry314** [comment]
Steps to Reproduce:
1) Have an account with ONLY bitCNY
2) Go to EXCHANGE
3) Choose a price
4) In the BUY BTS window, click on the total amount of bitCNY you have next to "Balance: ___"
5) Notice Fee is 0.0114 bitCNY
5) Click BUY, log in, click CONFIRM
6) You get an error message, "Failed to broadcast the transaction:"
7) Notice the Fee in the bottom row. It says "0.0115 bitCNY"

So, the autocalculation of total amount of bitCNY to sell minus the fee charged is slightly off.

When this happens to me, I simply go back and reduce the amount in the "Total:" field by 0.0001 bitCNY then the order gets placed without a problem.

I didn’t want to upload a screen shot because there is personal information in there and I would have to black out so much it wouldn’t even be helpful. You can just try it yourself.

**Comment by wmbutler** [comment]
Thanks for the update. Reopened and we will take a look if the WP is accepted.

**Comment by wmbutler** [comment]
Merge #298  that fixed this and a number of other issues.
