### ISSUE TITLE
[1.5] Sorting Explorer Accounts by Balance breaks page

### ISSUE THREAD

**Issue by alexandr-masl** [bitshares/bitshares-ui#2132]
**Describe the bug**
The sorting for BalanceComponent in Explore -> Accounts doesn't work as expected, after few clicks appears white screen.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Explore
2. Click on Accounts
3. Click on Current Balance column several times

**Expected behaviour**
Sort BalanceComponent without white screen.

**Comment by startailcoon** [comment]
Issue still persists. Investigating

**Comment by startailcoon** [comment]
Page breaks as it doesn't load the balance object before trying to sort. 
Adding ChainStore load of balance object on sort, and caching to eliminate redudant calls on re-sorting.
