### ISSUE TITLE
[StyleGuide] Add support of Steps 

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2135]
The issue is to add support of [Steps component](https://ant.design/components/steps/) to our style-guide

**Comment by sschiessl-bcp** [comment]
Is that the component that will be used for asset cration wizard?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp yep, exactly.

**Comment by gibbsfromncis** [comment]
@startailcoon Estimate: 2h

**Comment by sschiessl-bcp** [comment]
Screeeens :)

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp soooooryyyy :)
