### ISSUE TITLE
wallet - bitshares - exchange returns blank page

### ISSUE THREAD

**Issue by manikey123** [bitshares/bitshares-ui#2136]
**Describe the bug**

**To Reproduce**
1. Go to 'https://wallet.bitshares.org/#/'
2. Click on 'Exchange Tab ie https://wallet.bitshares.org/#/market/XBTSX.NVC_USD'
3. See error  ---> blank page observed

**Expected behavior**
See some web page
**Screenshots**
![image](https://user-images.githubusercontent.com/22608398/48247390-01435180-e3a8-11e8-896b-31a798544243.png)

**Desktop (please complete the following information):**

 - Browser [e.g. chrome]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by startailcoon** [comment]
Are you able to attach some output from the console? The error you describe can be of a number of reasons, one which I can't see by just browsing to the page as it works for me.

**Comment by manikey123** [comment]
Please close this ticket.
I rolled back code from git
Tried on different system. works
