### ISSUE TITLE
ANTify tooltips

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2137]
Replace existing ReactTooltips with new style-guide-tooltips.

Task:
 - [x] Cross reference how many there are in the UI
 - [x] Report back in here the proper way to replace them
 - [x] Do one sample replacement to check out the solution and wait for feedback
 - [x] Actually replace them all after positive feedback

**Comment by startailcoon** [comment]
This would be quite a large project, but a good thing to work on.

**Comment by sschiessl-bcp** [comment]
Process described in the issue happened here
https://github.com/blockchainprojects/bitshares-ui/issues/53
