### ISSUE TITLE
Toggle Preferred Unit of Account by Clicking on ACCOUNT VALUE in Header

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#214]
I quite frequently want to change the preferred base unit in which balances are calculated like when I change the assets I am holding or when I am just curious what value I hold in a variety of other currencies.

Currently to do this we need to go into Settings -> General then find the pulldown there.

I offer a feature request here to make the balance calculation on the top bar be clickable and when clicked simply toggle through the possible units available. This way we can change this often used setting more easily and on-the-fly!

Does anyone else agree?

**Comment by wmbutler** [comment]
Nice as a feature request. This could become cumbersome with a lot of currencies. Maybe a link to take the user to the settings page where this control can be modified.

**Comment by landry314** [comment]
As of now, there are only 6 currencies in my list. That isn't much to toggle through. I only really need 3 of them. If I could select my preferred currencies from a list in the Settings and have only those be the ones that toggle through that would be ideal.

Of course, while we are making this feature, why not add the ability to select ANY ASSET for the display of Balance. Let's say I want to display my Balance in HEROs or EOSes or bitGolds or whatever. It might be cumbersome but if it could be done somehow, it would give the user more power.

**Comment by landry314** [comment]
Well, in the new GUI, clicking on the Account Value at the top has become a pull down menu...

I think the pull down menu should be activated by clicking on the triangle and not the account name in which case this issue could still be implemented as a click on the account name and balance... what do people think?

**Comment by wmbutler** [comment]
Hrmmm. I like being able to click anywhere on the menu. Part of me like the idea of changing the currency from the menu, but honestly, I rarely do that and the settings menu is easily accessible.

**Comment by wmbutler** [comment]
Closing this for now. Haven't seen a very passionate outcry for this.
