### ISSUE TITLE
New column "in orders" in portfolio menu

### ISSUE THREAD

**Issue by fractalnode** [bitshares/bitshares-ui#2140]
As a trader I would like to have clear view on my asset list and the percentage proportions I have.

At the moment, the **Visual** and **Active** tab does not contain assets, **which I still have** in open orders. That makes me mislead.
The number of assets I currently own, including those in open orders, should be displayed either in brackets or in an additional column.

![image](https://user-images.githubusercontent.com/20418259/48264729-ccc4a980-e42a-11e8-822a-1c7ac0be8e69.png)

**Comment by startailcoon** [comment]
The problem with your request is that the portfolio contains a list of single assets, one by one.
The open orders tab contains a list of pairs you're trading.

For example, if you have an order open for bitCNY/BTS, there is no clear assetd the "In Orders" would be attached to.

**Comment by fractalnode** [comment]
you always have token witch you want to SELL

**Comment by startailcoon** [comment]
I'm not sure how to best explain this, but the exchange doesn't store on-chain what asset you're tryint to sell or buy. It's treated as a trade operation. Thus we can't determine the direction of the trade.

**Comment by froooze** [comment]
You are looking for  #1666?

**Comment by fractalnode** [comment]
In some way, the tab "Orders open" knows what assets I want to SELL and in what amount

**Comment by cloud-8** [comment]
Yes as per @fractalnode above, the Open Orders tab does differentiate between what you want to Sell and what you want to Buy, from that it is possible to determine what asset I actually have. Therefore I dont see why a summary of Open Orders should not be possible.

**Comment by abitmore** [comment]
A summary in "portfolio" menu is good for overview. Open orders are details, although a summary there is also helpful (#1666).

By the way, besides of "in orders", we can have "in collateral", "in vesting balances" as well.

I can say most if not all data is available in result of "get_full_accounts" API call. If any is missing, please submit an issue in bitshares-core respository.

**Comment by abitmore** [comment]
Replaced by #2655.
