### ISSUE TITLE
wrong display of orders in new ui

### ISSUE THREAD

**Issue by bitcoiners** [bitshares/bitshares-ui#2141]
https://wallet.bitshares.org/#/market/BTS_OPEN.EOS

Buy and Sell orders are displayed with mismatched prices. Buy orders are shown as BTS/EOS, and sell orders as EOS/BTS

![image](https://user-images.githubusercontent.com/38520/48301743-39bc6a00-e525-11e8-924c-65c98c696cbe.png)

**Comment by startailcoon** [comment]
This was reported in another issue, but I can't find it as of now. 
@sschiessl-bcp you where working on a fix for this, or reverting the commit that created this issue?

**Comment by sschiessl-bcp** [comment]
@bitcoiners 
Do you have an account name where I can see this reproduce?

**Comment by bitcoiners** [comment]
see this account
https://wallet.bitshares.org/#/account/dinkova-1

https://wallet.bitshares.org/#/market/OPEN.EOS_BTS

**Comment by sschiessl-bcp** [comment]
This is resolved in new version
https://develop.bitshares.org/#/market/OPEN.EOS_BTS
