### ISSUE TITLE
[3][skenan] Hiding Some Brand New Accounts Removes Them From the List Until Reload

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#215]
After creating a few new accounts then going to Settings -> Accounts and clicking on Hide next to those accounts, a few of the new accounts disappear completely and a reload is necessary to see them again.

This has happened to me a few times after creating a few new accounts in a row.

The last time it made my main account disappear and I still haven't gotten it back in that list.

The account management for the GUI has some serious bugs... I have posted more like #210 and #196.

I suggest a rehaul. Something is wrong with the arrays used to track accounts.

**Comment by wmbutler** [comment]
Agreed.

**Comment by skenan** [comment]
Can I take this one?

**Comment by wmbutler** [comment]
Sure. @svk31 will you take a look an ensure that a 3 hour estimate is fair on this one? Then we can allow @skenan to work the bounty on it.

**Comment by skenan** [comment]
The cause for this bug is after creating a new account, the AccountRefsStore didn't update. I suggest to resync the ChainStore after creating.

**Comment by wmbutler** [comment]
@skenan are you planning to submit a PR?

**Comment by skenan** [comment]
@wmbutler  Yeah. Will do that this week.

**Comment by skenan** [comment]
Fix this one as the PR #297
