### ISSUE TITLE
[2][yura5hem] Exchange Font sizes

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2150]
Extracted from issue #2020 

By @wmbutler 
> See screenshot for font differences and color differences. I like the right font and colors better but still think we could go smaller

![bild](https://user-images.githubusercontent.com/1254810/47529832-8db12880-d86e-11e8-9e23-be1cfb24e426.png)

By @wmbutler 
> I'd suggest we unify font sizes on the exchange tending towards smaller fonts to ensure we can fit everything on screen.

![bild](https://user-images.githubusercontent.com/1254810/47527051-2f347c00-d867-11e8-89c4-bc03a5ced879.png)

**Comment by froooze** [comment]
- I would not go in general for smaller fonts. We can define smaller fonts, when wide is smaller than a critical one. 
- Price,  Quantity ...  Balance, should have the same font size as the in input box.

**Comment by wmbutler** [comment]
@froooze look at pretty much every other exchange. Small font size is often necessary in order to fit all the detail onto an exchange.

**Comment by froooze** [comment]
@wmbutler 
We can use smaller fonts, but only dependent on the wide. 
When there is not enough space fonts should get smaller.

**Comment by startailcoon** [comment]
Anyone willing to do some research and estimations on what sizes are good to use? 
This would be an easy task, with some research and comparison of other exchanges that would fit nicely with ours.

**Comment by yura5hem** [comment]
I claim it

**Comment by wmbutler** [comment]
@yura5hem It's yours. Please review a few exchanges and report back with font sizes and maybe even font faces. Two hours allocated.

**Comment by yura5hem** [comment]
![coinbene](https://user-images.githubusercontent.com/2905901/49685454-34364d80-faec-11e8-8f82-7edce4e86e11.png)
![huobi](https://user-images.githubusercontent.com/2905901/49685455-34364d80-faec-11e8-986a-9207e9064cda.png)
![poloniex](https://user-images.githubusercontent.com/2905901/49685456-34364d80-faec-11e8-898f-3ca45eefb48d.png)
![binance](https://user-images.githubusercontent.com/2905901/49685457-34cee400-faec-11e8-9fc1-94b6fdf0246b.png)
![bitfinex](https://user-images.githubusercontent.com/2905901/49685458-34cee400-faec-11e8-9ca5-ece30cd244e9.png)

I think on bitshares DEX we need to use a font-face roboto with dimensions of 12 pixels (order forms, order books, market trades, open orders and other blocks) and 14/16 pixels for other inscriptions @wmbutler

**Comment by wmbutler** [comment]
Great research. This is ready to be worked. @yura5hem would you like to do the work as well for additional fee or should this go to a dev now?

@gibbsfromncis can you get this into the styleguide (open another issue for your time there).

- [ ] Current size id .875rem. Let's got to .75rem as suggested (12px)
- [ ] .875rem for the "others" as suggested.

**Comment by yura5hem** [comment]
@wmbutler yes, I'll do it

**Comment by gibbsfromncis** [comment]
@yura5hem please send us your bitshares account name which should receive your bounty.
