### ISSUE TITLE
[6] Exchange Vertical Orderbook rendering warnings

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2151]
Switching to a vertical order book will throw two rendering issues

### Issue 1
![bild](https://user-images.githubusercontent.com/12114550/48317856-891f9a80-e5f8-11e8-9f50-7c4ab514c273.png)

### Issue 2
![bild](https://user-images.githubusercontent.com/12114550/48317861-950b5c80-e5f8-11e8-81de-6f8e3c775e59.png)

**Comment by sschiessl-bcp** [comment]
Will investigate where the issues come from and report back. This was mentioned in other issue as well and appear often throughout the exchange. Actually fixing it might need heavy refactoring, we will see.

**Comment by startailcoon** [comment]
I know at least one is related to the first function for vertical order book in https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Exchange/OrderBook.jsx

**Comment by startailcoon** [comment]
@sschiessl-bcp any solutions on this issue by your guys?

**Comment by sschiessl-bcp** [comment]
Still under discussion, you can follow the investigation here:
  https://github.com/blockchainprojects/bitshares-ui/pull/49
