### ISSUE TITLE
TypeError: "this.defaults.unit is undefined"

### ISSUE THREAD

**Issue by romy2012** [bitshares/bitshares-ui#2154]
![qq 20181112164520](https://user-images.githubusercontent.com/10843381/48336057-65ad2c00-e69a-11e8-84e4-7b0c88328315.png)

Use My node (ws://192.168.0.119:38090)
TypeError: "this.defaults.unit is undefined"

**Comment by sschiessl-bcp** [comment]
Was this on a clean checkout of develop branch?

**Comment by clockworkgr** [comment]
no response. closing
