### ISSUE TITLE
no method with name 'get_account'

### ISSUE THREAD

**Issue by romy2012** [bitshares/bitshares-ui#2155]
no method with name 'get_account'

![2](https://user-images.githubusercontent.com/10843381/48337687-94c59c80-e69e-11e8-8bd3-c6346a88ac35.png)

![3](https://user-images.githubusercontent.com/10843381/48337690-998a5080-e69e-11e8-9a84-10eda04138a5.png)

**Comment by sschiessl-bcp** [comment]
What aer you doing when that occurs?

**Comment by startailcoon** [comment]
Is this really UI related?

**Comment by romy2012** [comment]
![1](https://user-images.githubusercontent.com/10843381/48536259-fc6f2800-e8e8-11e8-867d-6bb0bf442735.png)

![2](https://user-images.githubusercontent.com/10843381/48536266-0133dc00-e8e9-11e8-9241-2e4f8002b6b6.png)


![qq 20181115151432](https://user-images.githubusercontent.com/10843381/48536318-2de7f380-e8e9-11e8-9393-4b6772a0918f.png)

I found:

get_accounts,  But no get_account .

what happen?

**Comment by sschiessl-bcp** [comment]
Please direct your question to https://github.com/bitshares/bitshares-core, this is for the BitShares UI

**Comment by cogutvalera** [comment]
It is JS related as we discussed in BitShares-Core here https://github.com/bitshares/bitshares-core/issues/1435

Also it seems @romy2012  missed `refcode` (it is `null`) and `referrer` (it is also `null`) while creating new account (according to this comment https://github.com/bitshares/bitshares-core/issues/1435#issuecomment-438998570).

`get_account` method works in `cli_wallet` and @romy2012 approved it, so the problem isn't related to BitShares-Core repo.

Thanks !

**Comment by sschiessl-bcp** [comment]
In the picture above only `wscat` is used, which is not related to bitsharesjs. 

Please open a new issue with the problem and description you have found in the core issue.

**Comment by cogutvalera** [comment]
@sschiessl-bcp look please this comment and screenshot, it isn't related to core issue, @romy2012 started bitshares-ui

@romy2012 how do you trying to create new account, where ? in command line or on web UI localhost ?

As I understood the problem creating new account was on web UI localhost, right ?

**Comment by cogutvalera** [comment]
IMHO @romy2012 missed some parameters while creating new account and that's why there is a problem
