### ISSUE TITLE
[1] Account Page, Open Orders: Unstable trading pair direction

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2156]
**Describe the bug**
In account page, open orders tab, direction of orders is not stable. Sometimes shows selling BTS for CNY with a price showing in BTS/CNY, sometimes shows buying CNY with BTS with a price showing in CNY/BTS.

**To Reproduce**
1. Go to https://wallet.bitshares.org/#/account/arb-bot
2. Click on 'Open Orders'
3. Watch and wait (please be patient)

**Expected behavior**
Stable direction.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/48341327-10a6f100-e66d-11e8-8232-779ee3679de1.png)

![image](https://user-images.githubusercontent.com/9946777/48341268-e9502400-e66c-11e8-9b19-d9271bf94db5.png)

![image](https://user-images.githubusercontent.com/9946777/48341295-fa009a00-e66c-11e8-8a99-f94155a55ba1.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version 69

**Additional context**
- UI version 2.0.181031

**Comment by sschiessl-bcp** [comment]
This is probably fixed with staging release (same order display logic used here)

**Comment by sschiessl-bcp** [comment]
It is fixed, no hours needed.
