### ISSUE TITLE
Exchange page, my open orders, wrong price direction

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2157]
**Describe the bug**

**To Reproduce**
1. Go to https://wallet.bitshares.org/#/account/arb-bot, or browse to the arb-bot account
1. Go to https://wallet.bitshares.org/#/market/BTS_CNY
3. Scroll down to 'my open orders'

**Expected behavior**
Prices of bids and asks show in same direction.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/48341729-1224e900-e66e-11e8-8d6e-ba13ce37f6ad.png)

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Chrome
 - Version 69

**Additional context**
- UI version 2.0.181031

**Comment by sschiessl-bcp** [comment]
> Prices of bids and asks show in same direction.

Do you mean that the second row, the price 1.51 is inverted?

**Comment by abitmore** [comment]
> Do you mean that the second row, the price 1.51 is inverted?

The data there is totally wrong. Actually, both orders are around 580 BTS and around 380 CNY.

In addition, in "my open orders" tab, bids should be in green and asks should be in red.

**Comment by sschiessl-bcp** [comment]
I see. It seems that the market of that order was not inverted.

**Comment by sschiessl-bcp** [comment]
Fixed with https://github.com/bitshares/bitshares-ui/issues/2110

**Comment by startailcoon** [comment]
No hours assigned to this issue, removed from milestone.
