### ISSUE TITLE
Accounts Section Redesign

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2158]
The task is to go ahead and continue our work on redesigning parts of Reference Wallet like we did before #1604 with Assets. 

This task is for redesign Account & Activity section - https://wallet.bitshares.org/#/account/gibbs-from-ncis

Please put your thoughts and wishes

**Comment by froooze** [comment]
Is this about 
- Explore -> Accounts or 
- Manage Accounts?

**Comment by wmbutler** [comment]
@nikandrovalex ?

**Comment by nikandrovalex** [comment]
@wmbutler Sorry, I did not see your message. I will be able to start on the 5th of January

**Comment by startailcoon** [comment]
Removed from milestone as it's unclear on the requirements of working on this issue at the moment.

**Comment by gibbsfromncis** [comment]
@startailcoon closed. It will be refactored in new design
