### ISSUE TITLE
Clicking on Wallet Setting while looking at Wallet Setting Causes "select wallet to delete" to Disappear

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#216]
This is barely a bug, but rather a curiosity.

Go to Settings -> Wallet then click on Wallet again, you will see the "Select wallet to delete..." text under "Delete Wallet" disappear. It is just changing the option to the blank one instead of "Select wallet to delete...". Weird. I just mention this because it is not something a user would expect. The user would expect NOTHING to happen if you click on the same category you are already in.

**Comment by wmbutler** [comment]
This seems intuitive to me and while I agree it could be organized better, let's handle that during a bigger UX push. Closing this but keeping it in mind.
