### ISSUE TITLE
More straightforward Dockerization

### ISSUE THREAD

**Issue by nathanhourt** [bitshares/bitshares-ui#2161]
The existing Dockerization does not work for me, and seems rather excessively complicated. For anyone interested, a more straightforward and stable dockerization can be achieved using the following Dockerfile in an otherwise empty build directory. It's just my 2 cents, take it for what it's worth, and ignore if desired.

```
FROM node:6
MAINTAINER unmaintained

RUN /bin/bash -c 'npm install -g http-server; \
    git clone https://github.com/bitshares/bitshares-ui /bitshares-ui; \
    cd /bitshares-ui; \
    npm install; \
    npm run build; \
    cp -ar build/dist /html; \
    rm -rf /bitshares-ui'

WORKDIR /html

EXPOSE 8080
ENTRYPOINT ["http-server", "."]
```

I note that in theory, the above should work; however, in my environment, it fails due to #1958. Pending the merge of #2160 which resolves this bug, this failure can be resolved by changing the git clone line to:
`git clone --single-branch -b patch-1 https://github.com/nathanhourt/bitshares-ui /bitshares-ui; \`

**Comment by wmbutler** [comment]
Thanks!
