### ISSUE TITLE
ETH market volume and 24 hr columns are null

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2167]
**Describe the bug**
ETH market volume and 24 hr columns are void of data

1. Go ETH market
2. Note the 24 hr and volume columns
   Other markets are fine
   Release 181031b

![eth-capture](https://user-images.githubusercontent.com/18186497/48481815-6cd85500-e7d4-11e8-96ca-292f80da9878.JPG)

**Comment by sschiessl-bcp** [comment]
Was your connected node possibly slow?

Can you choose another one, and give it some time to load?

**Comment by startailcoon** [comment]
Works just fine. Please check that you're connected to a good node.

![image](https://user-images.githubusercontent.com/12114550/48508707-8ec2ed80-e84f-11e8-9e9e-72be2911a2d1.png)

**Comment by TechsUsInc** [comment]
@sschiessl-bcp @startailcoon  Sorry for the delay. 
I switched nodes, waited, same null. Reloaded with data present.
Switched back to my original node. Data maintained.
Thanks for your time
