### ISSUE TITLE
CSV history download inoperable

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2168]
**Describe the bug**
Tried to download history both locked and unlocked.
brief 3 dots followed by nothing.

**To Reproduce**
1. Go the Activity tab by clicking the Dashboard tab first
2. Scroll to the bottom of the page, noting the small CSV icon on the bottom left
3. Note the tooltip informs click to download a .CSV history
4. Click the CSV history download icon
5. Note the brief 3 dots menu followed by nothing
6. Scroll to the top of the page, noting the failed to download notification in bold red

**Expected behavior**
A CSV history download of the account

Release 181031b

**Additional context**
See issue #68 
Consider moving the CSV icon to the top of the page because;
a) Being at the bottom of the page, it is easily missed.
b) Being at the top of the page, it is firstly seen. 
c) Being at the top of the page, the notification will pop

Consider a larger, more noticeable and applicable icon
![csv_capture_1](https://user-images.githubusercontent.com/18186497/48484858-e70cd780-e7dc-11e8-9ced-eff9fae51363.JPG)
![csv_capture_3](https://user-images.githubusercontent.com/18186497/48484865-ee33e580-e7dc-11e8-9491-7a3dac88cf99.JPG)
![csv_capture_2](https://user-images.githubusercontent.com/18186497/48484885-f55af380-e7dc-11e8-8204-dcd35ea374a2.JPG)

 

I have never been able to download a history successfully. In past releases, it was inconstant in data downloaded if it would download at all. The CSV file would require an edit. It should be easily formatted, readable, and complete from day one to current in one click.

**Comment by startailcoon** [comment]
@svk31 , you built the current CSV export feature. Any input/comments on the current problem?

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/48509364-342a9100-e851-11e8-97a2-52b8091c9efe.png)





@sschiessl-bcp Think I already mentioned this erorr occuring sometimes, looks like it still happens.

**Comment by sschiessl-bcp** [comment]
Will have a look, thanks

**Comment by Bluffet** [comment]
I'm in desperate need to balance my account. I would appreciate if this was prioritised.

**Comment by startailcoon** [comment]
@Bluffet We're an open community of developers and we can't tell anyone to work on/fix an issue. I agree though, that it's a higher priority as it's a feature expected to work.

If you are in need of exporting your history, you have a few other options. If you want to use a console you can look at https://github.com/svk31/bitshares-report. There is also a web function to export to a CSV report on http://open-explorer.io/bitshares-account-exporter/

**Comment by svk31** [comment]
It just needs the api fixed then it should work again.

**Comment by Bluffet** [comment]
I'm aware of it, @startailcoon And I appreciate all the great things that comes out of it. This function being one of the most important, as I cant figure out how to properly format it myself. And going to binance would probably save me a lot of time.

**Comment by sschiessl-bcp** [comment]
After the deployment has happened please use https://develop.bitshares.org/ or wait until next release

**Comment by Bluffet** [comment]
Thanks a bunch, Stefan!

**Comment by pault70** [comment]
Any timeframe for when this fix will be deployed? As of now the export is still not working. I am guessing it's quite important now people need to think about tax reporting for 2018.

**Comment by TechsUsInc** [comment]
![181212-rc5_csv](https://user-images.githubusercontent.com/18186497/50735432-b90c9980-1174-11e9-9deb-1ed8d9b9bb6b.gif)

**Comment by sschiessl-bcp** [comment]
Please try again in develop.bitshares.org, has been moved to header
![image](https://user-images.githubusercontent.com/33128181/50841481-1ff0a500-1365-11e9-81a3-7e7cfee6b4b1.png)

**Comment by pault70** [comment]
Awesome, it works! Thanks.

**Comment by JRizzly** [comment]
I get different number of orders using the web version vs the desktop version. 45 operations for fill type on desktop and 30 operations for fill type on web version. Why is there a difference?

**Comment by sschiessl-bcp** [comment]
> I get different number of orders using the web version vs the desktop version. 45 operations for fill type on desktop and 30 operations for fill type on web version. Why is there a difference?

What versions do they both have? Might differ inbetween versions, but the same version on light or webwallet should produce the same.
