### ISSUE TITLE
Missing TRADE link for BTS in Account Screen

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#217]
In the Account screen on the Windows Light Client there is no link to trade BTS in the right column:
![trade_bts_option](https://user-images.githubusercontent.com/14145836/28593720-39486612-7142-11e7-95e5-e75931ca9d0c.png)

**Comment by wmbutler** [comment]
That's because it wouldn't know which market to go to BTS/BTS? Closing this. The accounts area needs a full rewrite anyway.

**Comment by happyconcepts** [comment]
Wow closed so fast.

**Comment by happyconcepts** [comment]
Bill, you should reconsider reopening this issue, right? I heard a rumor
this was an open source project but it looks like you just want to control
every commit.

Rather than call you emporer, I would point out that users can set their
display currency in the preferences (why not give them what they ask for
huh) and that if the default BTS is the user setting then you might just
send them to a BTS pair with some random coin worth $38 billion somewhere
if you can manage to find one.
