### ISSUE TITLE
TypeError: "this.defaults.unit is undefined"

### ISSUE THREAD

**Issue by romy2012** [bitshares/bitshares-ui#2170]
develop branch

After setting local

TypeError: "this.defaults.unit is undefined"

![qq 20181115164526](https://user-images.githubusercontent.com/10843381/48540782-04819480-e8f6-11e8-948f-c7f6fcb35aae.png)

**Comment by startailcoon** [comment]
Your log states "Unknown chain" so I assume you're doing some testing of your own. Maybe you're missing some parameters. This will be hard to debug without more details. Someone could check `onUpdateUnits` to see if there is something that needs to be done, but it's very low priority for the UI team as we work primarily for the main chain to work on the UI.

**Comment by romy2012** [comment]
@startailcoon Thank you.
