### ISSUE TITLE
[1] Integration Testing - Transfer modal covering login modal

### ISSUE THREAD

**Issue by toi16** [bitshares/bitshares-ui#2173]
**Describe the bug**
When you try and send a transfer with the account locked, the login modal appears behind the existing send modal, therefore you cannot see the login modal.

**To Reproduce**
1. Click on padlock to close it, then go to 'Menu'
2. Click on 'Send'
3. Fill in account name, qty, memo
4. Click 'Send' button on modal
5. Error: Login modal appears BEHIND the send modal, and cannot be seen.

**Expected behavior**
When you send a transfer request with the account locked, the login modal should be presented on top of the send modal so that you can authenticate your account before sending.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.102 (Official Build) (64-bit)

**Additional context**
Issue found during integration testing version 181121-RC1

**Comment by sschiessl-bcp** [comment]
Included in review
