### ISSUE TITLE
[1.5] Integration Testing - Private Login retaining information

### ISSUE THREAD

**Issue by toi16** [bitshares/bitshares-ui#2176]
**Describe the bug**
Login while having "Remember Me" disabled. Close the wallet in some way and reopen it. 
account Name is retained.

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Login'
3. Toggle 'Remember Me' OFF
4. Login using 'cloud wallet'
5. Close wallet (via Padlock) or close browser tab and navigate back to https://staging.bitshares.org
6. Go to 'Menu'
7. Click on 'Login'
8. ERROR: Account Name is still present from previous login.

**Expected behavior**
When logging in using the 'Cloud Wallet' with the 'Remember Me' option disabled, after closing the wallet and going back in to login, the login modal fields should be blank.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 70.0.3538.102 (Official Build) (64-bit)

**Additional context**
Bitshares Wallet 181121-RC1

**Comment by toi16** [comment]
**THIS RELATES TO FIREFOX ONLY**
Describe the bug
Login while having "Remember Me" disabled. Close the wallet in some way and reopen it.
account Name is retained.
*** HOWEVER IF YOU CLOSE THE LOGIN MODAL AND RE-OPEN IT AGAIN THE FIELDS ARE BLANK. ***

To Reproduce
Steps to reproduce the behavior:

Go to 'Menu'
Click on 'Login'
Toggle 'Remember Me' OFF
Login using 'cloud wallet'
Close wallet (via Padlock) or close browser tab and navigate back to https://staging.bitshares.org
Go to 'Menu'
Click on 'Login'
ERROR: Account Name is still present from previous login.
Close Login Modal
Go to 'Menu'
Click on 'Login'
Account Name is now empty.

Expected behavior
When logging in using the 'Cloud Wallet' with the 'Remember Me' option disabled, after closing the wallet and going back in to login, the login modal fields should be blank.

Desktop (please complete the following information):
OS: Windows 10
**Browser: Firefox
Version 63.0.3 (64-bit)**

**Comment by sschiessl-bcp** [comment]
Did you login with that account before testing "Remember Me"? If the account name made it into localStorage beforehand it will also be there afterwards. 

Login with account X, Remember Me checked. Then login with account Y, Remember Me unchecked. Logout in any way and reload, account X should be present again.

**Comment by toi16** [comment]
Firefox:
Logged in with Account X, remember me checked.
Logged in with Account Y, remember me unchecked.
Logged out
Navigated to login - Account Y showing
Refreshed Browser window then went to login - Account X showing.

**Comment by toi16** [comment]
Chrome:
Logged in with Account X, remember me checked.
Logged in with Account Y, remember me unchecked.
Logged out
Navigated to login - Account Y showing
Refreshed Browser window then went to login - Account X showing.

The page refresh is required to remove the private account name. Not sure if this is by design. 

The only issue with this is that if I logout and walk away from the device, someone could go to login and see my private account name.

**Comment by toi16** [comment]
Glad to be of help :-)

**Comment by sschiessl-bcp** [comment]
Was an easy fix after all, 0.5 hours.
