### ISSUE TITLE
[2.0.181121-rc1] Integration Testing - DUMMY REPORT - Win10/Chrome

### ISSUE THREAD

**Issue by toi16** [bitshares/bitshares-ui#2177]
**Describe the bug**
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
error: checkConnectionsFailed to connect to wss://us-east-1.bts.crypto-bridge.org Error: "Connection attempt timed out after 5s"
log: Checked 1 connections, 1 failed
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]

**Screenshots**
![dummy](https://user-images.githubusercontent.com/23018324/48620784-30098b00-e999-11e8-9e37-7f15f2c59155.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.102 (Official Build) (64-bit)

**Comment by sschiessl-bcp** [comment]
Thanks!
