### ISSUE TITLE
[2.0.181121-rc1] Integration Testing - Error Report - Screen Capture Blank

### ISSUE THREAD

**Issue by toi16** [bitshares/bitshares-ui#2179]
**Describe the bug**
When creating an error report the screenshot is not displayed, only an empty image placeholder.

**To Reproduce**
1. Go to bottom right of screen and click on 'Report'
2. Click on '+' to left of 'SCREENSHOT'
3. Error: No image is displayed, No image can be copied.

**Expected behavior**
When producing a report the 'SCREENSHOT' should appear visible so that it can be copied.

**Screenshots**

![report error](https://user-images.githubusercontent.com/23018324/48623558-e96c5e80-e9a1-11e8-9681-af8dfaa0dcaf.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 63.0.3 (64-bit)

**Additional context**
BitShares.181121-rc1

**Comment by sschiessl-bcp** [comment]
Please provide browser console log when the modal happens and screenshot is not loaded

**Comment by toi16** [comment]
Here you go:
Screenshot could not be captured Provided element is not within a Document app.d0181e3ebf68acc745b8.js:1:585489
	n https://staging.bitshares.org/app.d0181e3ebf68acc745b8.js:1:585489
	value/console.error https://staging.bitshares.org/app.d0181e3ebf68acc745b8.js:1:585904
	value/< https://staging.bitshares.org/app.d0181e3ebf68acc745b8.js:1:667804
	a https://staging.bitshares.org/vendor.edd3a92fcced7cf64be8.js:25:1955064
	N/< https://staging.bitshares.org/vendor.edd3a92fcced7cf64be8.js:25:1955209
	l https://staging.bitshares.org/vendor.edd3a92fcced7cf64be8.js:25:332880

**Comment by sschiessl-bcp** [comment]
You report Safari on Windows 10 above. What did you mean? :)

**Comment by toi16** [comment]
Sorry meant Firefox have corrected it now.
