### ISSUE TITLE
[1.5][2.0.181121-rc1] Integration Testing - Price Alerts not showing

### ISSUE THREAD

**Issue by toi16** [bitshares/bitshares-ui#2181]
**Describe the bug**
Put an alert above and below current market prive of e.g. BTS/CNY or BTS/USD. 
Wait until the alert triggers and if it displays properly.
Alert never displays.

**To Reproduce**
1. Go to 'https://staging.bitshares.org/#/market/BTS_USD'
2. Click on 'notify bell icon' (to left of trading pair)
3. Set a 'Higher Than' price alert
4. Click on '+ add rule' and select 'Lower Than' from the dropdown menu, then enter the price.
5. Click on 'Save'
6. Wait for both thresholds to be breached, and monitor for relevant alerts
7. ERROR: Thresholds are breached but NO alerts are presented.

**Expected behavior**
When a 'Higher Than' and / or 'Lower Than' threshold is met display an alert to the end user.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome AND Firefox
 - Version 70.0.3538.102 (Official Build) (64-bit) / 63.0.3 (64-bit)

**Additional context**
BitShares.181121-rc1

**Comment by startailcoon** [comment]
Type|Description
-|-
Needs Verification | I'd like a second user report on this.
High Priority | It's a feature that is expected to function.
Bug | It's not functional.
