### ISSUE TITLE
 Improvement to Landing Page

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2184]
We should try to improve the current landing page

I have in mind that we have things like
* News items
* Largest proxy
* New workers to vote for
* Reminder to vote and/or check proxy selections

We can probably come up with some really good things. The main idea here is that we should have more than just all the favorite assets.

This needs a good UX and I'd like to see one by new year if possible :)

## Related tasks
#1934

**Comment by sschiessl-bcp** [comment]
Thanks for creating this issue. I've postponed it in my head all the time. 

I imagine to finally use the dynamic grid for this to allow customization.

**Comment by startailcoon** [comment]
Indeed, I as well see the usage of a Grid layout testing ground a perfect thing for this issue once we have a good UX done. 

Right now we should focus on what we may want to have on the landing page. I imagine that we want bits and pieces of everything there, that we can link to and inform the user of. Like vesting balance for example, just to name one thing.

**Comment by startailcoon** [comment]
We need an updated UX for a good landing page. My vision for this is that the user should have quick details in short from different parts of the application, making them aware of things without having to navigate directly to them.

• News, latest 5 items.
• Accounts quick info list (account name + value) 
• Workers, latest 5 items. Not expired or hidden. Highlighted if not voted for 180 days
• Proxies, 4 largest + 2 newest proxies. If using proxy, highlight if not changed for 180 days. Dismissable.
• Witnesses, 4 largest + 2 newest witnesses. If not using proxy, highlight if not changed for 180 days. Dismissable.
• Commitie members, 4 largest + 2 newest. If not using proxy highlight if not changed for 180 days. Dismissable.
• Latest 10 received transactions. 
• 5 most volume assets + 5 most volume starred assets
• Other quick details
 ○ Vesting balance available

**Comment by sschiessl-bcp** [comment]
Voting should not be highlighted that prominently on landing page. It could be a mere panel that gives a "hightlights ticker", with voting reminder or similar but no details, and on click expands into the voting panel resulting from https://github.com/bitshares/bitshares-ui/issues/1934

**Comment by gibbsfromncis** [comment]
@startailcoon @sschiessl-bcp please take a look - https://github.com/bitshares/bitshares-ui/issues/2275

**Comment by startailcoon** [comment]
@gibbsfromncis why did you open a similar issue as this one by its own? I like the concept you present there, so I will close this issue and move the discussion to issue #2275 instead to keep consistency.

cc @nikandrovalex

**Comment by gibbsfromncis** [comment]
@startailcoon Your idea is cool and it was the base for my idea. But I do not want to mislead anyone who will start to read this issue. Also you proposed nice widgets and I will copy/paste them into my issue.
