### ISSUE TITLE
"Page Not Found!" after clicking "UPDATE AVAILABLE" trying to download the latest core/GUI client.

### ISSUE THREAD

**Issue by liondani** [bitshares/bitshares-ui#2187]
When clicking on "UPDATE AVAILABLE"
![screenshot from 2018-11-19 12-39-12](https://user-images.githubusercontent.com/6908400/48701867-2fbafb00-ebf8-11e8-89dc-dd7e7ad247bd.png)

it redirects to the nonexistent page
https://bitshares.org/download
![screenshot from 2018-11-19 12-45-54](https://user-images.githubusercontent.com/6908400/48702233-15355180-ebf9-11e8-9fdf-d81b0a4ba1f6.png)

instead of 

https://bitshares.org/Download

Obviously it will be solved when changing the word
"download" >>> "Download"   (with capital D)

 - OS: [Linux Mint]
 - Browser [Latest Brave]

**Comment by liondani** [comment]
Please check if this solved the problem https://github.com/bitshares/bitshares-ui/pull/2188

**Comment by startailcoon** [comment]
This is fixed by the webpage and doesn't need an update to the UI
