### ISSUE TITLE
#1696 dummy bug report 

### ISSUE THREAD

**Issue by thehapax** [bitshares/bitshares-ui#2191]
**Describe the bug**
Testing report button on bitshares web UI for staging.bitshares.org

**To Reproduce**
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: auto selecting to wss://api.open-asset.tech/ws after latency update
log: Connecting to wss://api.open-asset.tech/ws
log: synced and subscribed, chainstore ready
log: Your node is out of sync since 5.049000024795532 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 4.903000116348267 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 5.071000099182129 seconds, waiting 10 seconds, then we notify you
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: 891mshtml2canvas (1672e2355db):Canvas renderer initialized (541.015625x493 at 0,0) with scale 2

**Expected behavior**

**Screenshots**
![unknown](https://user-images.githubusercontent.com/39811582/48735066-27fd5580-ebfc-11e8-9587-8680470145f0.png)

My OS:

Mac Version: 10.13.6
My Browser:

Safari Version: 12.0.1

**Additional context**

**Comment by startailcoon** [comment]
Thanks for testing it out.
