### ISSUE TITLE
[4] Support core budget_record_object for Voting Page support

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2192]
As described in issue #2174 , the removal of 2.13.x object rendered the UI voting page useless. The impact of object removal wasn't fully understood until recently. 

The UI should follow the new `budget_record_object` once merged by PR  https://github.com/bitshares/bitshares-core/pull/1440

> As mentioned in Telegram, the logic in @xeroc's code is incorrect, since 2.0.0 data is a "hard" limit but not the actual available budget. It's not easy for UI to calculate without a 2.13.x object thus far. For this issue, we'll revert the changes done in core, so UI will work with next bitshares-core release. Later, for better performance and easier to understand, IMHO we should create a special API in core to query for data required by this page (need to modify core as well as UI, so need new issues for both repository).

- [ ] Update UI to follow new `budget_record_object`

**Comment by startailcoon** [comment]
Oh, I guess I miss understood you on the statement *IMHO we should create a special API in core to query for data required by this page (need to modify core as well as UI, so need new issues for both repository)*.

This would be a future hard-fork of the core with a "special API" for better performance?

Closing issue as it wouldn't require anything for now to be done then.

**Comment by abitmore** [comment]
> This would be a future hard-fork of the core with a "special API" for better performance?

Not a hard fork, but only a new API call.

**Comment by startailcoon** [comment]
Nice
