### ISSUE TITLE
[2.0.181121-rc1] #1696 Integration Testing - missing log out put for chrome OSX

### ISSUE THREAD

**Issue by thehapax** [bitshares/bitshares-ui#2194]
**Describe the bug**
Logs don't show any content

**To Reproduce**
1. Go to Exchange
2. Click on Report in lower right corner
3. Expand last 20 log entries
4. No content, but screenshot displays

**Expected behavior**
should show log entries. 

**Screenshots**

<img width="560" alt="screen shot 2018-11-20 at 6 14 46 pm" src="https://user-images.githubusercontent.com/39811582/48818918-46e60f80-ed02-11e8-87e9-4056a9d9fac4.png">

![screenshot1](https://user-images.githubusercontent.com/39811582/48818986-a3e1c580-ed02-11e8-9a8c-a9ccb7bcb516.png)

**Desktop (please complete the following information):**
My OS:
Mac Version: 10.13.6
My Browser:
Chrome Version: 70.0.3538.77

General
n/a

**Comment by sschiessl-bcp** [comment]
I tried on three Mac versions, it all reproduces. 

Can you please try again, it might have been a collision with testing the "Remember Me" feature.

**Comment by thehapax** [comment]
I am really confused, today i look at the site and i don't even see a report button or an alert next to the symbols traded. 

<img width="884" alt="screen shot 2018-11-21 at 3 14 56 pm" src="https://user-images.githubusercontent.com/39811582/48872990-882cfc80-eda0-11e8-9d11-280bcf5ed6e4.png">

**Comment by sschiessl-bcp** [comment]
Maybe an old cached version?

**Comment by thehapax** [comment]
possibly. can we close this bug report now?

**Comment by sschiessl-bcp** [comment]
Is it working correctly now?

**Comment by thehapax** [comment]
Yes it is.
