### ISSUE TITLE
[1][Style-Guide] Fix disabled inputs design

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2199]
Fix design for disabled inputs:

<img width="310" alt="screenshot 2018-11-23 01 44 23" src="https://user-images.githubusercontent.com/35899973/48925193-5069a600-eec1-11e8-8530-d2ee83b6c701.png">
<img width="693" alt="screenshot 2018-11-23 01 44 12" src="https://user-images.githubusercontent.com/35899973/48925194-5069a600-eec1-11e8-8dd8-941bb30d9c69.png">

It is impossible to see placeholder & value when it is disabled

**Comment by gibbsfromncis** [comment]
@startailcoon estimate: 1h

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp screenshots:

<img width="994" alt="screenshot 2018-11-24 00 45 55" src="https://user-images.githubusercontent.com/35899973/48962613-51164100-ef82-11e8-8159-9c72eafb6bc7.png">
<img width="1002" alt="screenshot 2018-11-24 00 45 46" src="https://user-images.githubusercontent.com/35899973/48962614-51164100-ef82-11e8-82d3-928ffd719c0b.png">
<img width="447" alt="screenshot 2018-11-23 21 30 03" src="https://user-images.githubusercontent.com/35899973/48962616-51164100-ef82-11e8-8d70-37702acc3e10.png">

**Comment by sschiessl-bcp** [comment]
Please always reference the corresponding style guide commits
