### ISSUE TITLE
[1] Hidden Asset Count is Wrong in Balances

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#220]
![hidden assets](https://user-images.githubusercontent.com/6866501/28609825-2bfe0ad0-71b4-11e7-9755-fc246dc7c695.jpg)

**Comment by landry314** [comment]
And it changes quite randomly, every day it seems the assets are different and there is a different number of them but the count is ALWAYS 1 higher at any given time than the actual number of assets marked as hidden.

Seems like an off-by-one error in the code.

The fact that these assets have been chosen for me to be in my Balances unless I hide them is strange. Why not have a button "Add Assets to Balances" where we can simply choose which assets we want in there? The red x circle could just remove it from the list until it is added again. I don't see the benefit of the current system.

**Comment by landry314** [comment]
Oh, and why is there a count anyway??? Who cares how many are there?

**Comment by wmbutler** [comment]
Simple fix

**Comment by ppitonak** [comment]
Reproducible only if one of selected assets is hidden - bitCNY, OPEN.BTC, OPEN.DASH, OPEN.ETH, OPEN.MAID, OPEN.STEEM, OPEN.USDT
