### ISSUE TITLE
How to call bitshares-ui functionalities from another server(PHP)?

### ISSUE THREAD

**Issue by Leon-Zhang** [bitshares/bitshares-ui#2200]
In this repository,
https://github.com/bitshares/bitshares-ui-api

I found the api library for call bitshares haven't ready yet, I'm working on a project that require
register wallet, send & receive using bitshares through RESTful api calls.

May I ask when will bitshares-ui-api repository be ready for functions described above and is there an alternative way to invoke bitshares-ui functionalities programmatically from another language like PHP?

Thanks.

**Comment by startailcoon** [comment]
I'd advice posting issues related to other repositories in their respective repositories.

I can see that this repo was only committed once and was about a year ago.

What makes you say that it doesn't work yet?

**Comment by Leon-Zhang** [comment]
> I'd advice posting issues related to other repositories in their respective repositories.
> 
> I can see that this repo was only committed once and was about a year ago.
> 
> What makes you say that it doesn't work yet?

Hello @startailcoon , thanks for reply.

As you can see, there's only market functions in bitshares-ui-api repo, I need to register account and do transfer programmatically.
Since bitshares-ui repo haven't expose any api for this purpose, is there any convenient way I can implement this?

Thanks.

**Comment by sschiessl-bcp** [comment]
You can use the CLI, controlled through a php server

**Comment by Leon-Zhang** [comment]
> You can use the CLI, controlled through a php server

Hello, thanks for your reply, do you mean command line interface by CLI? Could you please provide a simple example to show case how to do it?

Thanks.

**Comment by clockworkgr** [comment]
There's 2 ways to perform transactions (ie write to the blockchain rather than read) in BitShares:

a) you run a cli-wallet instance with the keys imported, let it handle transaction signing and use the wallet API 

b) you implement your own serialisation and signing methods (or use existing implementations such as bitsharesjs for javascript) and interact directly with the API nodes

Seeing as there is no serialisation/signing library for PHP and it is no trivial task to implement,your only option is a). See: http://dev.bitshares.works/en/master/development/apps/cli_wallet.html

**Comment by clockworkgr** [comment]
what do you mean multiple wallets ? you can have multiple accounts in one wallet

**Comment by Leon-Zhang** [comment]
I need to perform transfer from one wallet to another by api calling from php program, and which wallet I use depends on the login user: every registered user have one wallet attached with their account, and they can buy bitshares coin charge to their wallet, and transfer transaction performed later on will been issue from this user wallet. Am I clear?

**Comment by sschiessl-bcp** [comment]
> Am I clear?

No, you are not.

One wallet can contain multiple accounts (through the respective private keys). You want to transfer inbetween accounts I assume.

What do you want to do?

a) transfer from any user account to any other user account
b) transfer always from the same account to any other user account

**Comment by Leon-Zhang** [comment]
Thanks for reply, what I need is a), is there any example showcase how to do so?
I think need to 
 1, register associated account in wallet while new user register to our database;
 2, transfer from user's wallet account to another user's wallet account.
