### ISSUE TITLE
[4][spanishtranslator] Maintain Spanish language

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2201]
Done with https://github.com/bitshares/bitshares-ui/commit/d3448e8210ef0899f2222184d09f90375ec4a995

See https://github.com/bitshares/bitshares-ui/issues/1705#issuecomment-439083573 for BitShares Account. Hours for updating estimated to 4, please report if not sufficient @spanishtranslator

**Comment by spanishtranslator** [comment]
Bitshares user: newtechblog-bts  4 Hours it´s OK
