### ISSUE TITLE
Price Alert can be set/deleted in authorized/unauthorized locked accounts

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2202]
**Describe the bug**
Price Alert can be set/deleted in authorized locked account.
Price Alert can be set/deleted in unauthorized locked account.

**To Reproduce**
1.   Without unlocking the account, go to the Exchange Tab; click any asset pair. For this test, I used 
      BTS:Open.BTC
2.   Click the Price Alert icon
3.   Set a Price Alert for both below and above the suggested price (by clicking add alert); click the blue 
      save button
4.   Note that the Price Alert window closes, the Price Alert icon turns blue
5.   Click the blue Price Alert icon confirming both alerts were saved.
6.   Unlock the account; Click the blue Price Alert icon confirming both alerts are still saved
7.   Lock the account 
8.   Click on the Explore tab; should default to Blockchain activity 
9.   Click on any random account from the Blockchain Explorer (document the account name for later)
10. Navigate to the Exchange tab from within the random account taken from the Explorer
11.  Select the same pair as above; BTS:Open.BTC
12.  Note that the Price Alert icon is blue
13.  Click the Price Alert icon noting that the Price Alerts originally saved above from within your account 
      are also saved within the randomly selected account from the Explorer. 
14.  From the random account, click on the Price Alert icon and delete both the alerts (above/below) set 
      initially and save
15.  Note that the Price Alert icon is no longer blue, and is now white
16.  Navigate back to your account by clicking Explorer>>accounts or by any other means
17.  Confirm that the account is still locked and note that the Price alert icon is white
18.  Click the Price Alert icon noting that both the alerts set have been deleted 
19.  Unlock the account, click the white Price Alert icon confirming both alerts are still deleted
20.  Click on Explorer>>accounts>> type the random account used above or by any other means
21.  Click on the now white Price Alert icon noting that both alerts are also deleted 

**Expected behavior**
Unable to set/delete Price Alerts from an authorized account if it is locked.
Unable to set/delete Price Alerts from an unauthorized account if it is locked.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera

 **additional context**
More related issues detected but will be reported separately.

**Comment by sschiessl-bcp** [comment]
The price alerts are not on-chain, they are merely in the local storage of your computer. In that meaning they are not set per account, but per-open-browser-window.

I ll suggest to add it as a description.
