### ISSUE TITLE
[3.5] Send Modal tweaks

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#2205]
**Is your feature request related to a problem? Please describe.**
Default keyboard action and focus states for buttons and fields in send modal

**Describe the solution you'd like**
- Enter key should trigger send and acknowledgements where appropriate
- Fields should be focused when modals open where appropriate

**Describe alternatives you've considered**
- [ ] Focus the `To` field when send modal opens
![focus](https://user-images.githubusercontent.com/1254810/48956681-fb0db300-ef19-11e8-9dd1-192f82e6adc2.gif)

- [ ] Enter key should trigger SEND button.
![enter](https://user-images.githubusercontent.com/1254810/48956742-4cb63d80-ef1a-11e8-99ad-ecd3a8306150.gif)

- [ ] When login modal appears, "Password" field should get focus by default. If it's the cloud wallet, the username should have focus (but I haven't tested it since I don't have a cloud wallet).
- [ ] Login button should be activated by the Enter key.
![focus](https://user-images.githubusercontent.com/1254810/48956814-b9c9d300-ef1a-11e8-9f55-619c1ba0d78e.gif)

**Comment by gibbsfromncis** [comment]
I'll take it and work on it in few days

**Comment by startailcoon** [comment]
@gibbsfromncis feel free to apply the style guide while your at this, and add appropriate hours for it.

**Comment by startailcoon** [comment]
I'm taking over this, will look at enhancements and adding the Style Guide to the Send modal.

**Comment by startailcoon** [comment]
# Antified Send Modal

Updated Send Modal to use the new Style Guide. 
A few changes have been made to the design at this update

- Scam accounts can't be added to contacts directly when sending.
- Scam accounts will show a warning symbol on label (red) as well as in the list.
- Accounts that the user hold keys no longer display "remove contact". Instead it shows that the user has keys to mentioned account.
- Account in contact list now shows a filled star
- Account not in contact list shows an unfilled star
- Memo on proposed send will highlight in yellow 

Dropdown list shows accounts in the following order
1. Personal accounts
2. Contacts
3. Other matches to the search


### Regular Send
![SendModalAntified](https://user-images.githubusercontent.com/12114550/54083021-8a4ea300-431e-11e9-9cad-aa157c16d045.gif)

### Propose Send
![SendModalAntified_Propose](https://user-images.githubusercontent.com/12114550/54083020-8a4ea300-431e-11e9-894f-339b9b99d1d5.gif)
