### ISSUE TITLE
Integration Test - Dummy Issue

### ISSUE THREAD

**Issue by bieglich** [bitshares/bitshares-ui#2213]
Log entries
log: new owner pubkeyBTS6mMPXi1y5FMqWZorW66Yyz3TeToJ8zE5URYWWmQVpU5TGpBq8g
log: new memo pubkeyBTS828SeZudHeBuxegEh64SCLN2Nw4V5csohC2FRZ1BXz85zb2Lnk
log: Your node is out of sync since 5.07699990272522 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 5.95799994468689 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 12.069000005722046 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 21.492000102996826 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 22.4760000705719 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 23.740999937057495 seconds, waiting 10 seconds, then we notify you
log: browser notifications disabled by Browser Permissions
log: Connecting to wss://api.open-asset.tech/ws
log: browser notifications disabled by Browser Permissions
log: Your connection was lost
log: Error: Error: connection closed
log: Your node is out of sync since 61.46600008010864 seconds, waiting 10 seconds, then we notify you
log: synced and subscribed, chainstore ready
log: browser notifications disabled by Browser Permissions
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: Your node is out of sync since 6.236999988555908 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 5.0290000438690186 seconds, waiting 10 seconds, then we notify you
log: synced and subscribed, chainstore ready

Screenshot
![image](https://user-images.githubusercontent.com/45090761/48972614-5d57d800-f02e-11e8-8762-b682c1e639b9.png)

**Comment by startailcoon** [comment]
Thanks for testing the integrated reporting features
