### ISSUE TITLE
[1] Integration Test - Private Login 

### ISSUE THREAD

**Issue by bieglich** [bitshares/bitshares-ui#2214]
**Is your feature request related to a problem? Please describe.**
Windows 10 / Chrome
 - Toggle the checkbox, and the entered account name disappears
 - On a complete fresh wallet, login with account, Remember Me unchecked. When logging out, the account name still remains (after the fix of the other issue I saw), though after reload its gone.
Android/Chrome
 - Lock in View mode of another account, logged in account still remains

**Comment by sschiessl-bcp** [comment]
Can reproduce on Linux/Chrome

**Comment by startailcoon** [comment]
The modal doesn't check if `rememberMe` is true/false when rendering the Modal. If rememberMe is false, the name shouldn't be filled in.

**Comment by sschiessl-bcp** [comment]
Took 0.25
