### ISSUE TITLE
Type of Login select doesn't work in Login modal

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2216]
Select of Login type doesn't work:

<img width="504" alt="screenshot 2018-11-25 02 11 42" src="https://user-images.githubusercontent.com/35899973/48979356-17485600-f0ba-11e8-97af-d6669430c265.png">

**Comment by gibbsfromncis** [comment]
@startailcoon final estimate 1h. It took a little bit of time to discover why it happens because I saw all reasons to see this select dropdown but it wasn't showing. The reason was really simple: z-index issue. Modal z-index was higher than select dropdown index.

**Comment by sschiessl-bcp** [comment]
That was me .. I never thought that the dropdown would have an absolute zIndex, and not relative to parent ....
