### ISSUE TITLE
[15] Add collateral bidding

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2221]
For details see https://github.com/bitshares/bsips/blob/master/bsip-0018.md

`bid_collateral_operation` can be used to put a bid, `collateral_bid_object` can be used to display bids.

First tasks: 
- [ ] Discuss where to put it!
- [ ] Ensure it is available in bitsharesjs, I haven't found it right now

**Comment by sschiessl-bcp** [comment]
Suggestion:
Put it in `Asset actions`, that allows bidding and also displays the current bid (if any)

**Comment by startailcoon** [comment]
Looks like a very good thing to include as well. Will loik closer to this

**Comment by startailcoon** [comment]
### collateral_bid_objects
Documented here https://bitshares.org/doxygen/classgraphene_1_1wallet_1_1wallet__api.html#aea65645fc8ae366d9d510a01e32db5a8

Can be called by 
```
Apis.instance().db_api().exec("get_collateral_bids", [this.props.asset.get("id"), 100, 0]).then(...);
```

**Comment by startailcoon** [comment]
Going to tackle this task during the week to see if we can make a feature in the wallet to allow collateral bidding to help settling bitUSD.

Already spent time to understand the concept and features of the function.

**Comment by clockworkgr** [comment]
I claim 10% of your time for the explanations :P j/k

**Comment by sschiessl-bcp** [comment]
3 hours for my adjustments
