### ISSUE TITLE
[1][oldbusdriver] Settling bitUSD breaks application

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2224]
When Settling bitUSD on the dashboard the application breaks with a white screen.

Requested settle does execute, but something after it breaks the application. 

Using development branch.

Console output:

![bild](https://user-images.githubusercontent.com/12114550/49043533-a7c28b80-f1cb-11e8-8081-9797ce4ec7f2.png)

![bild](https://user-images.githubusercontent.com/12114550/49043568-bc068880-f1cb-11e8-8acb-1a0fd7596178.png)

![bild](https://user-images.githubusercontent.com/12114550/49043583-c4f75a00-f1cb-11e8-89e5-1d12189b4484.png)

![bild](https://user-images.githubusercontent.com/12114550/49043600-d80a2a00-f1cb-11e8-8efe-3322feb41160.png)
![bild](https://user-images.githubusercontent.com/12114550/49043631-ece6bd80-f1cb-11e8-962c-cd8db7374949.png)

**Comment by clockworkgr** [comment]
the settlement does work btw

**Comment by startailcoon** [comment]
@clockworkgr it does indeed, forgot to mention that

**Comment by oldbusdriver** [comment]
can I claim this?

**Comment by startailcoon** [comment]
@oldbusdriver it's yours. If possible, I'd like to see this in the next release.

**Comment by gibbsfromncis** [comment]
@oldbusdriver please send us your bitshares account name which should receive bounty

**Comment by oldbusdriver** [comment]
> @oldbusdriver please send us your bitshares account name which should receive bounty

bus-driver
Thank you.
