### ISSUE TITLE
[.5] Voting shortcut

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2231]
Implement a new route for voting (shortcut, because its always annoying to explain):
```
/voting
```
This shortcut should do the same as `/account/{account_name}/voting`, with the currently active account as the default selection (`AccountStore.getState().currentAccount`). If there is no currently active account, put `committee-account`.

See App.jsx and AccountPage.jsx for the existing routing. Estimate is 2.

**Comment by wmbutler** [comment]
Redirect `/voting` tp `/account/{account_name/voting`

I think this redirect issue is more like .5 unless you suggest otherwise.
