### ISSUE TITLE
[Showcases] Create Collaterized Debt Position wizard

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2232]
Add a showcase tile to https://github.com/bitshares/bitshares-ui/issues/1857#issuecomment-441674409 that has a wizard like view to borrow a smartcoin, similar to 
https://cdp.makerdao.com/

The existing modal remains.

**Comment by cloud-8** [comment]
Agree right now you really need to: 

1. Know Bitshares exists and has a smartcoin function built into the wallet
2. Find that function somewhere in the wallet
3. Read docs about how it works from somewhere that is not your wallet, likely the poorly documented (until recently) Bitshares.org website. 

So having a better wizard walkthrough in the wallet itself would be great and also some explainer text in simple terms just like MKRDAO.

**Comment by sschiessl-bcp** [comment]
Style Guide now contains the "Steps" component, could be nice to be used.
