### ISSUE TITLE
[1.5][MikhailKavalenka] Not save personalize settings

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-ui#2233]
Changes in settings in menu "Personalize" applyed immediately but after change trade pair - resetting.
Maybe not all parameters, but Panel Grouping just resetting.

Desktop:
OS - Windows 10 x64 1803
Version - 181121

**Comment by MikhailKavalenka** [comment]
@startailcoon I can take this one.

**Comment by sschiessl-bcp** [comment]
The actual bug was minor, please check/confirm the estimate @MikhailKavalenka

**Comment by MikhailKavalenka** [comment]
@sschiessl-bcp , you can put an hour, thanks.

**Comment by startailcoon** [comment]
Assume you've tested it properly and the requirements to find the issue.
