### ISSUE TITLE
[1.5][nikandrovalex] Design of Style-Guide Notifications

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2238]

**Comment by nikandrovalex** [comment]
Hi guys. @gibbsfromncis @startailcoon Please check and approve the design of the notify.

I spent 1 hours 35 min on this task. 
![image](https://user-images.githubusercontent.com/43581164/49666909-18866500-fa62-11e8-93b1-8cedf8184342.png)


ZEPLIN - https://app.zeplin.io/project/5b9ad751d8068c34a1715ad6/dashboard?seid=5c0ac1661c54935ee653181e

**Comment by gibbsfromncis** [comment]
@nikandrovalex awesome. Good job!

**Comment by gibbsfromncis** [comment]
Unfortunately I didn't noticed that ant doesn't provide an ability to customize notifications depending on status. My bad. 

@nikandrovalex please provide design of notification with default background and styles.

**Comment by gibbsfromncis** [comment]
@startailcoon I put hours for Alex and closed task because we do not have the way to update design of notifications regarding Alex's design... It was my bad..
