### ISSUE TITLE
[1][Style-Guide] Add support for Drawer

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2239]
This task is to add [Drawer](https://ant.design/components/drawer/) to our style-guide.

I want to use it for [Scaled Orders feature](https://github.com/bitshares/bitshares-ui/issues/1503). Modals usage is not possible because it closes order books and I think it is important for user to see them when user creates new order.

**Comment by gibbsfromncis** [comment]
@startailcoon estimate: 1h

**Comment by sschiessl-bcp** [comment]
Done
