### ISSUE TITLE
[18] Automate build process for Linux, Windows

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#224]
We need to automate the builds for all three binaries and the web wallet:

- [x] Web
- [x] Windows
- [x] Linux

This task will be considered complete when the creation and posting of all wallets is handled by a single turn key operation. It has been placed into the 100914 Milestone.

**Comment by wmbutler** [comment]
Worded this differently and closed #209

**Comment by xeroc** [comment]
I can help you with this .. if you take a look at the wallet.bitshares.eu repository in the bitshareseurope organization, you can find a bunch of additional files in the root dir along with a .travis.yml file that shows how to use travis-ci for automated building

**Comment by wmbutler** [comment]
Great, adding this to milestone 171001. This will allow us to knock out bugs while manually building and then hopefully have a complete build -> save -> notify loop to ensure that end users are aware of upgrades as they are released.

**Comment by wmbutler** [comment]
https://blog.axosoft.com/2016/12/07/continuous-integration-cross-platform-application-building/

Windows CD Tool
https://www.appveyor.com/

**Comment by svk31** [comment]
https://github.com/electron-userland/electron-builder/wiki/Multi-Platform-Build

Looks we can use the free github integrations from AppVeyor and Travis.

**Comment by wmbutler** [comment]
Should I purchase the account at appveyor?

**Comment by svk31** [comment]
No, it's free for open-source projects.

**Comment by wmbutler** [comment]
Awesome, so you need nothing from me on this?

**Comment by xeroc** [comment]
I just pushed a new branch which adds .travis.yml and a few build scripts for automation.
https://github.com/bitshares/bitshares-ui/commit/921f9eba60249d12c93c90590421677b5515e56d

Travis compile progress can be found here.
https://travis-ci.org/bitshares/bitshares-ui/branches

What needs to be discussed is, if we want it to auto-deploy on bitshares.org/wallet
https://github.com/bitshares/bitshares-ui/blob/224-travis-build-automation/deploy.sh

.. and if we want the scripts to be located elsewhere to keep the root directory clean

**Comment by wmbutler** [comment]
My opinion on the matter is that we should do the following for each Sprint:

- In a perfect world the `bitshares` branch goes away in lieu of 'master`
- `master` is merged into `staging`
- Contributors should create an issue# branch from `staging`
- @svk31 would merge all accepted issues into `staging`
- Once `staging` has been fully tested, those completed changes are merged into `master`
- `master` is tagged with the release number
- `master` triggers builds for all electron binaries and push to production web site wallet

**Comment by xeroc** [comment]
>     In a perfect world the bitshares branch goes away in lieu of master

In `bitshares-core`, the `bitshares` branch represents "stable" releases which are tagged and thus would be what you consider `master`. It has it's separate branch because the repository also hosts `testnet` which is the testnet-specific branch. If we were to move the testnet frontend into github as well (which I would like to recommend anyways), then it makes sense to keep `bitshares` as master branch. IMHO.

>     master is merged into staging

I never worked with `staging´ branches so I don't have an opinion on it. I personally would like `master` to represent the latest tag, but I am open for other schemes too.

>     Contributors should create an issue# branch from staging

looks similar to the [git flow](https://danielkummer.github.io/git-flow-cheatsheet/)

>     @svk31 would merge all accepted issues into staging
>     Once staging has been fully tested, those completed changes are merged into master
>     master is tagged with the release number 170901

Looks like a reasonable approve. Note that travis-ci would build each and every branch in the repo unless you give it a white- or black list.

>     master triggers builds for all electron binaries and push to production web site wallet

I haven't looked into electron builds yet but I am almost sure that travis could be used for those too. Ultimately, they install a whole virtual environment/OS for you.

**Comment by wmbutler** [comment]
The point of the staging branch is to allow for testing in a single consolidated branch before deploying.

**Comment by xeroc** [comment]
> The point of the staging branch is to allow for testing in a single consolidated branch before deploying.

I'd say, go for it .. since the deploy script for travis can obtain the branch name it is operating on, we can restrict deploys for `bitshares` branch ..

**Comment by wmbutler** [comment]
This would allow us to create a staging server as well to make testing accessible to even non-technical types.... staging should also be a protected branch.

## Incremental fixes merge into staging
staging branch -> build -> deploy -> staging.bitshares.org

## Staging gets merged into bitshares at end of Sprint
bitshares branch -> build -> deploy -> bitshares.org/wallet | electon wallets

**Comment by landry314** [comment]
The sha256 for the recent Aug 29 release for Mac OS on https://bitshares.org/download/ is not correct.

If an automatic build system is implemented it needs to also update the shasums along with the builds.

**Comment by landry314** [comment]
Don't forget to update the shasums as referred to in issue #343.

**Comment by wmbutler** [comment]
@svk31 I personally view this as our most valuable achievement for the 170914 Sprint. Getting automation established will improve our process and set a solid foundation for future efforts.

**Comment by svk31** [comment]
This took far longer than the original 8 hours due to requiring a refactor of the codebase, and lots of tweaking of Travis and AppVeyor settings to get it to work properly.

**Comment by wmbutler** [comment]
Well worth it for the consistency and automation we gain. Did the OS X build properly too after Travis CI backlog?
