### ISSUE TITLE
[4] Wallet Merchant Protocol not work

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-ui#2244]
In [last documentation](http://dev.bitshares.works/en/master/development/use_cases/uc_merchant.html#wallet-merchant-protocol) describe using this function, but my test url show that feature work only in very old clients. In new - error 404.
171121: [work](https://old.rudex.org/#/invoice/Ch8t3vKjc9Ydc6qskfBoDZAen1fdUAtukiLyoeeG2veD1Dv6DzGDctrDoQkUB4dBMoQn8qoon3TgbdKHdJP9yFK3r443uTpEUYHPSbwUiWJRnwi1qRumDUidzwGySGGgpb3bonKJTBeYHYvDkraz7C72RXaPFXLujCDioJMrSzqJgvL3Rd1ajA8i1GQYRf9YQZT7qhYDLPy44zEZiRmumcgS5EKZbdbXHxrQwnVh62F18Zf5fCct9CZ25xwEEHJsasLHR7Q8aVkSqtoJTzmFqse3LTijugrj3tpH34h4r1k1hnaZQUmhk2yUjgfyimnETTUasbkNtNTh)
181118: [not work](https://market.rudex.org/#/invoice/Ch8t3vKjc9Ydc6qskfBoDZAen1fdUAtukiLyoeeG2veD1Dv6DzGDctrDoQkUB4dBMoQn8qoon3TgbdKHdJP9yFK3r443uTpEUYHPSbwUiWJRnwi1qRumDUidzwGySGGgpb3bonKJTBeYHYvDkraz7C72RXaPFXLujCDioJMrSzqJgvL3Rd1ajA8i1GQYRf9YQZT7qhYDLPy44zEZiRmumcgS5EKZbdbXHxrQwnVh62F18Zf5fCct9CZ25xwEEHJsasLHR7Q8aVkSqtoJTzmFqse3LTijugrj3tpH34h4r1k1hnaZQUmhk2yUjgfyimnETTUasbkNtNTh)
In my opinion it big mistake that such function not work very long.

**Comment by startailcoon** [comment]
Invoice feature was removed in PR https://github.com/bitshares/bitshares-ui/pull/2053

Is this a desired feature to keep? If so, we should introduce it once again, with updates.

**Comment by cloud-8** [comment]
It is described in the Bitshares docs and is a function of the protocol, yes it should be supported.

**Comment by clockworkgr** [comment]
I believe this should be re-added. Right @sschiessl-bcp  ?

**Comment by startailcoon** [comment]
@clockworkgr Yes, it should be added in again as it looks like this was/is a used feature by the community. Can't see the reason for the removal of it.

**Comment by sschiessl-bcp** [comment]
Does anyone have screenshots of old feature and common use-cases?

**Comment by startailcoon** [comment]
@sschiessl-bcp [RuDEX has it here](https://old.rudex.org/#/invoice/Ch8t3vKjc9Ydc6qskfBoDZAen1fdUAtukiLyoeeG2veD1Dv6DzGDctrDoQkUB4dBMoQn8qoon3TgbdKHdJP9yFK3r443uTpEUYHPSbwUiWJRnwi1qRumDUidzwGySGGgpb3bonKJTBeYHYvDkraz7C72RXaPFXLujCDioJMrSzqJgvL3Rd1ajA8i1GQYRf9YQZT7qhYDLPy44zEZiRmumcgS5EKZbdbXHxrQwnVh62F18Zf5fCct9CZ25xwEEHJsasLHR7Q8aVkSqtoJTzmFqse3LTijugrj3tpH34h4r1k1hnaZQUmhk2yUjgfyimnETTUasbkNtNTh) and common use-cases are [in documentation](http://dev.bitshares.works/en/master/development/use_cases/uc_merchant.html#wallet-merchant-protocol), it's to make a transaction (payment) based on an invoice that is loaded by a Base58 encoded URL that the user can review before approving it.

**Comment by sschiessl-bcp** [comment]
For reference

![image](https://user-images.githubusercontent.com/33128181/55267633-ac837300-5283-11e9-8d0f-a3b56ed8dd60.png)
![image](https://user-images.githubusercontent.com/33128181/55267636-b1e0bd80-5283-11e9-927d-7ece5e3ad90c.png)

**Comment by sschiessl-bcp** [comment]
Task for this issue:

- [ ] Restore the old wallet merchant protocol

For a future issue we will then refactor it.

**Comment by startailcoon** [comment]
@sschiessl-bcp progress on this?

**Comment by startailcoon** [comment]
@sschiessl-bcp ping

**Comment by sschiessl-bcp** [comment]
Hours spent: 30:53
Bounty requested: 14.5

**Comment by sschiessl-bcp** [comment]
To test
https://develop.bitshares.org/#/invoice/2r4TgkAmeFTNgDZi78ivaPDfX5vk9We7KyNjB3yCkXtKp5yJJYwDPdPfphScXvyAfTXXCVhJz1knGkDjFMkGp9yD23bHGT5MrtUj5VmBusaUwEYpw5GFEgwiuCSHwZnuC1uRb48MwJbjv186RmuGuUNhXBkH59A43KBNbofmF8Pv6hk2NfGRMiKyGx5xbF26jYEntn22yG8s8SChV1v3hptAN3HvF7k95ewzCgbE8hVxHyNajHHj2ymXYJSFnRWJYXiJNBjh4kbmH1Z

**Comment by sschiessl-bcp** [comment]
I have not noticed that my bounty request was not adressed in here. Can you please check @clockworkgr ? Actual payment has been done for 4.

**Comment by clockworkgr** [comment]
@sschiessl-bcp a-ha... correct..

Will add the remaining 10.5 next invoice.

Thats why I ask you guys to doublecheck exprense reports :)

**Comment by sschiessl-bcp** [comment]
In the pipeline #3084
