### ISSUE TITLE
Improve Release Process

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#225]

**Comment by testlump** [comment]
This user story should encapsulate an improvement to the process flow for testing, packaging and deploying stable branch releases for MAC OSX (dmg), LINUX (.deb) and WINDOWS (.exe) to the https://bitshares.org/download - automated nightly/weekly packaged builds from development branch would also be handy.

**Comment by wmbutler** [comment]
Actually, this is the Epic. Issue #224 covers this topic and is tied to this Epic.
