### ISSUE TITLE
CORS network error has to do with Assert Exception Error???

### ISSUE THREAD

**Issue by yoshimizusano** [bitshares/bitshares-ui#2253]
**Describe the bug**
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gateway.winex.pro/api/v0/ol/support/trading-pairs.

**To Reproduce**
1. Open Firefox Quantum 63.0.3 (64bit) on Fedora linux 28.
2. Go to https://wallet.bitshares.org
3. Hit F12 key
4. See the CORS error in the console log.
5. Go to the Dashboard.
6. Adjust one of the margin positions

**Expected behavior**
Error: "Assert Exception: !_bitasset_data->has_settlement(): Cannot update debt position when the asset has been globally settled bitshares-crypto

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/45410740/49345961-b7255700-f659-11e8-8f75-dd1770149c59.png)

**Desktop (please complete the following information):**
 - OS: Fedora 28
 - Firefox Quantum
 - 63.0.3 (64bit)

**Additional context**
I use WiFi to connect the Internet.

**Comment by yoshimizusano** [comment]
Thank you for your response. NONE of the assets of debt position can be adjusted. It is not only bitUSD (bitSilver either). I find it very buggy and frustrating!!!

**Comment by yoshimizusano** [comment]
![screenshot](https://user-images.githubusercontent.com/45410740/49380321-6a845f00-f6df-11e8-850f-da5431152c1a.png)

**Comment by startailcoon** [comment]
There are many updates to the application this milestone due to the recently globally settled assets. If I'm not mistaken, I think this has been fixed in the current development branch.

**Comment by yoshimizusano** [comment]
Then it only means one thing. This is a bug. Bug is still there. Please fix it as soon as possible. Thousands of us are fleeing to XLM and other coins due to the bugs like this. People like me usually do not report bugs unless one is really determined to do so.

**Comment by startailcoon** [comment]
Next release will have this fixed. No need to panic.
