### ISSUE TITLE
Activity Tab- Doesn't auto-populate recent transactions

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2256]
**Describe the bug**
1. After install of 2.0.181129 no recent transaction history appears in the activity tab.
![no_transactions_capture](https://user-images.githubusercontent.com/18186497/49417225-8cfb9400-f742-11e8-9579-99ca5f274efe.JPG)
![no_transactions_capture_2](https://user-images.githubusercontent.com/18186497/49417226-8cfb9400-f742-11e8-88d4-94d6a048c98a.JPG)

2. Made several transactions, went back to the activity tab, still no history.
3. Disabled auto-node selection; switched nodes; checking the activity tab again now shows recent 
    transaction history.

**To Reproduce**
1. Go to Activity tab after installation of 2.0.181129; note no recent transactions
    Also note that the account value under the account name next to the lock doesn't reflect accurately 
    until the activity tab populates

2. Click on Node access popup (bottom right)
3. Click to disable auto node switching
4. Node settings window opens; switch to a different node and connect by clicking on it
5. Recent transactions populates 

**Expected behavior**
Recent transactions to populate in the activity tab.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera

**Comment by startailcoon** [comment]
I would think that the node you had connection to wasn't working properly. As you switched node and the transaction history got populated I wouldn't say that this is an issue for now.
