### ISSUE TITLE
[2][MikhailKavalenka] Deposit EOS.* Gateway Assets

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2260]
### Enable Deposit OpenLedger EOS assets

Open Ledger has a asset type name of EOS.*
For example,
- EOS is named EOS.EOS
- IQ is named EOS.IQ

While other gateways does not have the prepended EOS name. This requires some refactoring of the code to enable EOS.* assets pairing.

This issue is to enable **deposit** of said asset through the Gateway modal.

**Comment by MikhailKavalenka** [comment]
@startailcoon , I can take this issue.

**Comment by sschiessl-bcp** [comment]
The work for withdrawal can be seen here
https://github.com/bitshares/bitshares-ui/issues/2259

**Comment by MikhailKavalenka** [comment]
> The work for withdrawal can be seen here
> #2259 
thanks!

Here is the PR. https://github.com/bitshares/bitshares-ui/pull/2304
