### ISSUE TITLE
Personalize- inactive tooltips

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2266]
**Describe the bug**
Inactive tooltips in the Personalize modal

**To Reproduce**
1. Go to Exchange tab
2. Click on Personalize clog
3. Hover over a "?" or "i" tooltip

**Expected behavior**
Personalize modal active tooltips when hovered over

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Opera
 - Version 2.0.181129
 - Version 2.0.181121-rc2

**Comment by manikey123** [comment]
![image](https://user-images.githubusercontent.com/22608398/49570503-a68c0f80-f8eb-11e8-8930-f82ac3fdb481.png)
I can see the message popup

**Comment by sschiessl-bcp** [comment]
This is faulty behavior of the ReactTooltip. We are transitioning to ANT Tooltips with https://github.com/bitshares/bitshares-ui/issues/2137

**Comment by TechsUsInc** [comment]
Yes Sir. I still don't see the message in 2.0.181212-rc1 or the latter release.

**Comment by sschiessl-bcp** [comment]
develop.bitshares.org

Will transition with the next release cycle
