### ISSUE TITLE
[4] Visual Issue in Trading Price Buy/Sell Table

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#227]
There is a visual issue in the table for selling and buying prices in the UI.

Navigating to the GRC:BTS market it appears to bee buy and sell orders at the same price. But when you click on them to get the price that they are set to you get a different number.

Clicking the Sell Price, that looks like

BTS|GRC|Price
-|-|-
0.40887 | 1.514298 | 0.27000

You get the correct numbers, looking like this:
![selling price grc - corrently displayed](https://user-images.githubusercontent.com/12114550/28917874-7aaae510-7847-11e7-8d0e-99dd9223f2dc.PNG)

The issue I found is that when you click the Buy Price, that looks like

BTS|GRC|Price
-|-|-
0.00019 | 0.000703 | 0.27000

What you get is actually this
![buying price grc - incorrectly displayed](https://user-images.githubusercontent.com/12114550/28917907-9871d946-7847-11e7-80ac-fa24dce6fe0b.PNG)

----
I expected to get a number starting with 0.27xxxx, but get a price of `0,25604552`. This number is not visible in the ledger at all, so where does it come from?

Is the buy price visually incorrect, or is the UI parsing the wrong number making the order price incorrect?

The rest of the Buy prices in the ledger is correct, it's only this first one that behaves very strange.

**Comment by wmbutler** [comment]
Agreed. Thanks for a detailed, complete report.

**Comment by svk31** [comment]
Unable to reproduce this.

**Comment by startailcoon** [comment]
So am I. It was only there for a while during the time there wasn't any change in the trading. If I encounter is again I will post about it again.
