### ISSUE TITLE
Add tooltips to the node access pop up, Report modal, and Help modal

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2270]
**Is your feature request related to a problem? Please describe.**
Please consider adding hoverable tooltips to:
1. The node access pop up informing the user to click for advanced node settings or to enable/disable 
    auto node switching
2. Report modal informing the user to click for error reporting tools
3. Help modal informing the user to click for self help section

**Describe the solution you'd like**
hoverable tooltips to guide the user towards self help enhancing the user experience

**Comment by sschiessl-bcp** [comment]
Took 0.5, played around with tooltip options
