### ISSUE TITLE
Warning Notification for low-collateralized MPA

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-ui#2277]
Asset holders may not notice for a long time that their asset has a low level of collateral. I propose to make the option enabled by default, which will show a periodical pop-up hint when the asset's collateral ratio drops below 1.25 for any bitasset/MPA in portfolio.

**Comment by startailcoon** [comment]
Low collateralized margin positions are warned to the user when it drops below 2, and then by 1.75 by

1. Value of margin positions highlighted in orange (below 2) and red (below 1.75)
![image](https://user-images.githubusercontent.com/12114550/49688296-006d1f00-fb10-11e8-84b2-4e5bd8765b8f.png)

2. Ratio highlighted in in orange (below 2) and red (below 1.75)
![image](https://user-images.githubusercontent.com/12114550/49688298-0bc04a80-fb10-11e8-82b5-e796ede32a3f.png)

We could include something more on the new Dashboard concept (#2275)

**Comment by akledirs** [comment]
This show only for borrower. I suggest show notification about low-collateralized active for holders.
