### ISSUE TITLE
[2][gibbsfromncis] Dashboard UX

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2278]
This is subtask for [Dashboard concept](https://github.com/bitshares/bitshares-ui/issues/2275)

This task is to design the following things:
1) Empty dashboard in Preview Mode
2) Dashboard with "base" widget in Preview Mode
3) Dashboard with "base" widget in Edit Mode
4) Add Widget modal with widgets preview 
5) Configure Widget modal

**Comment by gibbsfromncis** [comment]
@startailcoon this task is for UX only for Alex to create basics of Dashboard. The description maybe is not so clear but Alex know what he should we because we had a call to discuss it. If you have any questions feel free to ask.

**Comment by gibbsfromncis** [comment]
Updated estimate due additional call (30 mins) 1.5h -> 2h

**Comment by nikandrovalex** [comment]
@gibbsfromncis Hi Please check

**Comment by gibbsfromncis** [comment]
@nikandrovalex check what?

**Comment by startailcoon** [comment]
@nikandrovalex nice concept design. I think we could make something nice from this.

**Comment by wmbutler** [comment]
Approved for payment.

**Comment by startailcoon** [comment]
@nikandrovalex I think we're missing your hours for this task.

**Comment by nikandrovalex** [comment]
@startailcoon Hi, I spent 8hr 23min for this task
