### ISSUE TITLE
[0] Update Available Notifcation in the UI

### ISSUE THREAD

**Issue by testlump** [bitshares/bitshares-ui#228]
Description
-----
In order to ensure users are notified when new releases are available and keep their clients up to date, it would be helpful to have a message along the base of the UI to indicate when a new official release is available. 

![image](https://user-images.githubusercontent.com/29457910/28971766-1a15ebee-7925-11e7-8b57-e3b61f9921ff.png)

Expected Behaviour
------
When a new release is available, the client should display the message. If builds from multiple branches will be available (E.g. DEVELOPMENT / STABLE branch), then the message should reflect the version for the appropriate branch. The BRANCH to emit the new version alerts on should be selectable in the Settings menu.

**Comment by wmbutler** [comment]
Duplicate #43
