### ISSUE TITLE
Balance / In Orders Summary

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2280]
This issue is for brainstorming, and that we can get create some order and work out what we gonna implement

**Related**
- https://github.com/bitshares/bitshares-ui/issues/1468
- https://github.com/bitshares/bitshares-ui/issues/1666
- https://github.com/bitshares/bitshares-ui/issues/2140

**Comment by cloud-8** [comment]
Not sure specifically what this task is trying to achieve but the main comment I have here is that we do need an Open Orders summary, right now it is not possible to know the total in specific assets that you have elected to Buy or Sell (even though Open Orders does differentiate individual orders by what you are buying or selling). Important feature.

**Comment by abitmore** [comment]
IMHO this ticket is a duplicate.

**Comment by abitmore** [comment]
Please put this and/or the linked tickets to milestones. Thanks.

**Comment by sschiessl-bcp** [comment]
Let's define #1468 as main issue
