### ISSUE TITLE
[2.0.181212-rc1][1] Integration testing by toi16 - Settlement UI Issues

### ISSUE THREAD

**Issue by toi16** [bitshares/bitshares-ui#2284]
**Describe the bug**
A. When using the 'Settle Instantly' feature in the exchange the 'Request settlement of USD' modal allows you to try and settle more bitUSD than you actually have in your balance. You are able to confirm the transaction , but then get a 'Failed to broadcast the transaction' error.

B. When using the Margin Positions table to adjust a margin on bitUSD (ADDING A NEW MARGIN) you are able to create a new margin, and confirm your transaction, but then get a broadcast the transaction' error.

**To Reproduce A**

1. Go to 'Exchange' bitUSD/BTS market
2. Click on 'Settle Instantly'
3. Enter 10 in 'Amount to Settle', (with a 0 USD balance)
4. Click 'Settle Asset'
5. Click 'Confirm,
6. See error

**To Reproduce B**
1. Go to 'Dashboard
2. Click 'Margin Positions' Tab
3. Click 'Adjust' icon next to 'bitUSD'
4. Fill in the NEW margin debt and collateral.
5. Click 'Update Position'
6. Click Confirm
7. See Error

**Expected behavior A**
After clicking on 'Settle Instantly' button in exchange the 'Request settlement of USD' modal should have the 'Settle Asset' button disabled leaving just the close button active, with a message stating that you have no USD in your balance to settle. OR The 'Settle Instantly' button is disabled on the exchange screen if you have no USD in your wallet to settle.

**Expected behavior B**
After clicking on the 'Adjust' button in the 'Margin Positions' table you should not be able to create a new margin, and should be notified that bitUSD is in GS. If you already have a margin the addition of a 'Settle Instantly' button should be displayed.

**Screenshots**
![settle](https://user-images.githubusercontent.com/23018324/49662133-f7624c00-fa42-11e8-9c0a-27bf7baff3c1.PNG)

![settle2](https://user-images.githubusercontent.com/23018324/49662166-05b06800-fa43-11e8-9bd6-6284b1013d8b.PNG)

![settle3](https://user-images.githubusercontent.com/23018324/49662173-0943ef00-fa43-11e8-9429-e184684fdec6.PNG)

![settle4](https://user-images.githubusercontent.com/23018324/49662176-0c3edf80-fa43-11e8-8d8b-03487fa8e233.PNG)

My OS:
Windows 10, Version: 1803 (OS Build 17134.407)

My Browser:
Chrome, Version 71.0.3578.80 (Official Build) (64-bit)

**Additional context**

**Comment by startailcoon** [comment]
These are two issues in one really. Well described by OP.

- Once bit asset is in GS, change margin position should be disabled. Settle should be instant settle.
- You shouldn't be able to use instant settle if you have a zero balance.

**Comment by startailcoon** [comment]
This is fixed, part of PR #2342 and others.
