### ISSUE TITLE
[1] Show reason why a proposal has failed to execute

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2288]
**Is your feature request related to a problem? Please describe.**
Now a failed proposal only shows a "failed" status but does not show the reason. With the latest core release, it's possible to get the reason: `proposal_object` now have a `fail_reason` field.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sschiessl-bcp** [comment]
Is the `fail_reason` directly in the proposal object? It seems to be absent there.

Both testnet and mainnet have that?

**Comment by startailcoon** [comment]
@sschiessl-bcp you should probably open an issue on bitshares/bitshares-core for this I believe.

This was implemented on https://github.com/bitshares/bitshares-core/commit/9d54a5ce0bc3f8da33758d8d4b3b641e501f321a through PR https://github.com/bitshares/bitshares-core/pull/1036.

As it seems it doesn't seem to add any value to the `fail_reason` string.

**Comment by sschiessl-bcp** [comment]
Can this be due to lack of proper JSON object in bitsharesjs?

@dot5enko you are a pro now, care to check please?

**Comment by dot5enko** [comment]
@sschiessl-bcp sure, i'll check it today. if its already in release of bitshares-core we can add it to bitsharesjs as well

**Comment by dot5enko** [comment]
@sschiessl-bcp this issue has no direct  attitude to bitsharesjs but i can fix it if someone point me a place where such error happen on wallet.

**Comment by dot5enko** [comment]
so can somebody tell me how to fail execution of proposal?

**Comment by sschiessl-bcp** [comment]
Set one up with review period, and approve it. Set one up that transfers more than you have, and approve.

**Comment by dot5enko** [comment]
@sschiessl-bcp  to my great regret last commiter forget to add `fail_reason` field into reflection meta of [ proposal_object.hpp](https://github.com/bitshares/bitshares-core/blob/develop/libraries/chain/include/graphene/chain/proposal_object.hpp#L107), so proposals get serialized without that field, and reason not propagated on rpc api. It took ~2 hours for me to find the problem :)

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp to my great regret last commiter forget to add `fail_reason` field into reflection meta of [ proposal_object.hpp](https://github.com/bitshares/bitshares-core/blob/develop/libraries/chain/include/graphene/chain/proposal_object.hpp#L107), so proposals get serialized without that field, and this field is not accessible over rpc api. It took ~2 hours for me to find the problem :)
> 
> Created an issue [bitshares/bitshares-core#1730](https://github.com/bitshares/bitshares-core/issues/1730)

Awesome find, thank you so much!

**Comment by sschiessl-bcp** [comment]
The feature release is currently being deployed on testnet, once that is done you can start on this again.

**Comment by startailcoon** [comment]
This was blocked by a core issue that was fixed in 3.1.0. Do we have any results on this so we can merge it to main network yet?

**Comment by dot5enko** [comment]
@startailcoon i'll check it

**Comment by dot5enko** [comment]
![image](https://user-images.githubusercontent.com/5626922/58295203-ac60a900-7dd6-11e9-9c6e-8ded622864f4.png)

**Comment by sschiessl-bcp** [comment]
Agree with the overhead, sync with core was necessary.

**Comment by startailcoon** [comment]
> @startailcoon i've put it into tooltip. Havent tested it on mainnet, but in case node version is not >= 3.1.0 there would be empty message. Can we increase the bounty to 2 hours? it took a little bit more time to detect the problem first

Increased
