### ISSUE TITLE
Make Setting a Referrer Possible in Light Client

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#229]
Currently, in order to set up a new account in a light client for a friend where I am trying to be his referrer, I have to do it with the web address referral link in a browser then backup the wallet then restore it into a light client.

Can we make a way to set the referrer for a new account directly from the light client?

**Comment by wmbutler** [comment]
You might want to propose a mechanism to accomplish this. The Electrum wallet is not called by a URL. The only way I can think to handle it would be to ask who referred them prior to registering their first account. Alternatively, you could initially refer the user to the bitshares.io url and then encourage them to download the light wallet.

**Comment by landry314** [comment]
I think the label "proposed feature" works here.

The feature I propose is to have a mechanism to set a non-default referrer within the light client upon initial creation of the first account in a wallet.

**Comment by wmbutler** [comment]
The only thing I can come up with is something allowing the account creator to enter the referrer's username.

**Comment by wmbutler** [comment]
The easiest way to accomplish this is to get the user to signup on the web with the Cloud Wallet and the referral code and then they can migrate over to the Light Client later.
