### ISSUE TITLE
Wallet load and connection timeouts

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2291]
**Describe the bug**
Wallet loading and node connections is extremely lengthy

**To Reproduce**
1. Download and open the release 181212-rc1
2. Note the wallet load and connection timeouts

**Expected behavior**
The wallet load and connection to be extremely quick and reliable

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera
 - Version 56.0.3051.116

**Additional context**
*Note*
The capture is 7 minutes long
![181212-rc1_2_start_gif](https://user-images.githubusercontent.com/18186497/49695961-42c24a80-fb68-11e8-82a3-1dedaf2e7435.gif)

**Comment by startailcoon** [comment]
@sschiessl-bcp you've had some work going on with this, right?

**Comment by sschiessl-bcp** [comment]
Yes, it's the ping strategy. Depending on your location this might take a while. I'm closing this issue in favor of creating a new one, e.g. to introduce a geolocation based ping using an optional external service
