### ISSUE TITLE
Installation alert

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2295]
**Describe the bug**
Windows alert pops up for every Windows release

**To Reproduce**
1. Download the latest release and install
2. See error

**Expected behavior**
Known Publisher listing or Windows alert bypass

**Screenshots**
![bitshares_upgrade_capture](https://user-images.githubusercontent.com/18186497/49696565-1c54dd00-fb71-11e8-8c34-de4b3524d1e1.JPG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera 
 - Version 56.0.3051.116

**Additional context**

**Comment by startailcoon** [comment]
Been discussed before

Duplicate https://github.com/bitshares/bitshares-ui/issues/701
