### ISSUE TITLE
[4] Update Language Translation 'Spanish'

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2298]
**Describe the bug**
When language is chosen, not all of the text within the interface is translated

**To Reproduce**
1. From the Welcome to Bitshares page:
![welcome_to_bitshares_landing_1_1_capture](https://user-images.githubusercontent.com/18186497/49714871-38f62100-fc14-11e8-9abf-e027af4ae098.JPG)
2. Next to the blue globe, click within the box for a pull down menu to switch the language to one of 9 offered languages; click on a language. Consider adding the country flag next to the existing language choices for visual reference
![181212-rc1_language_1_capture](https://user-images.githubusercontent.com/18186497/49714975-925e5000-fc14-11e8-87e8-4749c0f88f96.JPG)
![181212-rc1_language_2_capture](https://user-images.githubusercontent.com/18186497/49714985-9b4f2180-fc14-11e8-83bd-846795a96b1e.JPG)
3. Note not all is translated. Important DEX feature tabs and directives are not translated (report, help, 
    exchange, explore, etc )   
4. I did check the rest of the interface in a different languages and there are missed translations

**Expected behavior**
A complete language translation of any and all text to enhance the user experience and convey professional development

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera 
 - Version 56.0.3051.116
 - RC 181212-rc1

**Additional context**
Assuming that the user manages to load their wallet or create an account successfully in another chosen language, the user would have to know to go to the hamburger menu and click settings to change the language. With that said, please consider adding the same language modal seen above, next to the account name or below it in the top right corner of the interface in the event that the user wishes to change languages after login. Top right corner is most common and universally recognizable.

**Comment by startailcoon** [comment]
We're struggling with language translation. I'd settle for an updated spanish translation for this issue.
I see your point in making an easy to find toggle place for the language selection.

**Comment by TechsUsInc** [comment]
I see your point of using a country flag for a language that may be spoken in multiple countries. I had two thoughts.
1. Consider using the existing pull down added next to, or under the account name, or (under manage accounts but before the account name list). If the user clicks the pull down and hovers over one of the 9 languages, maybe a pop up with multiple country flags that support a common language, or just the country name list in the pop up. 
2. Consider using the existing pull down added next to, or under the account name, or (under manage accounts but before the account name lust).  If the user clicks the pull down, it redirects to the settings page in the hamburger menu. 
![181212-rc1_language_01_capture](https://user-images.githubusercontent.com/18186497/49931377-5a614200-fe8c-11e8-8470-ff93645f33f4.jpg)
![181212-rc1_language_4_capture](https://user-images.githubusercontent.com/18186497/49931418-69e08b00-fe8c-11e8-8ff4-8f228f4856ce.jpg)

**Comment by calvinfroedge** [comment]
@startailcoon Just verifying, this issue is to go through the entire UI in Spanish and make sure everything has a translation

**Comment by startailcoon** [comment]
@calvinfroedge yes.

Any other suggestions for change should be added to new issues, to simplify the workflow.

**Comment by calvinfroedge** [comment]
@startailcoon @TechsUsInc Hey guys, just so you're aware I have pushed a branch with an updated Spanish translation file...as much as I could within allocated time I verified correct translations (I used Google translate and my own semi-fluent Spanish). Work is on this branch:

https://github.com/bitshares/bitshares-ui/tree/2298-spanish_translations

I will verify and cleanup soon.

**Comment by sschiessl-bcp** [comment]
Translations are maintained using transifex, see #1705 and #2201
and
https://www.transifex.com/bitshares/bitshares-ui-1/

There might have been some that are missing, I will cross-reference when you do your PR

**Comment by calvinfroedge** [comment]
I have verified my translations @sschiessl-bcp
