### ISSUE TITLE
[3] Missing 'introduction' elements and scrolling issues

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2299]
**Describe the bug**
1. Clicking the _help_ button could use tweaking.
    consistent numerical placement of the pop up.
2. Consider swapping the _done_ and _back_ click-able text at the end of the help pop up.
3. Clicking help from the _advanced form_ does not yield any help.

**To Reproduce**
1. From the Welcome to Bitshares page;
![welcome_to_bitshares_landing_1_1_capture](https://user-images.githubusercontent.com/18186497/49716332-0d296a00-fc19-11e8-83b3-10c4da434d5e.JPG)
2. Click on the blue _help_ button (bottom right corner) noting the pop up (#1) on language
![welcome_to_bitshares_landing_1_capture](https://user-images.githubusercontent.com/18186497/49716412-4e217e80-fc19-11e8-8cef-cad84042a0a0.JPG)
3. Click _next_ for help pop up (#2)
![welcome_to_bitshares_landing_3_capture](https://user-images.githubusercontent.com/18186497/49716680-0ea76200-fc1a-11e8-98d7-f4cd99cc1757.JPG)
Consider changing the text to say _create a cloud wallet using an account name and password_

4. Click _next_ for help pop up (#3)
![welcome_to_bitshares_landing_4_capture](https://user-images.githubusercontent.com/18186497/49716688-18c96080-fc1a-11e8-8bfe-2607d87fc87a.JPG)
5. Click next for help pop up (#4)
![welcome_to_bitshares_landing_2_capture](https://user-images.githubusercontent.com/18186497/49716718-2ed72100-fc1a-11e8-9b93-dcf1cdbcc114.JPG)
Note that the help pop up numbers (1-4) are all located in the top left corner of the pop up. They are consistent and look good. Note that the user is asked four times to click on the right to proceed next, but lastly asked to click on the left side now to complete the help pop ups. Please consider swapping _done_ with _back_ for a better user experience in pop up (#4).
6. Click _done_
![welcome_to_bitshares_landing_1_1_capture](https://user-images.githubusercontent.com/18186497/49716971-03a10180-fc1b-11e8-9dd4-303b7fb36355.JPG)
7. Click _Advanced form_
8. Click the blue _help_ button again; note that there is no help for the page and clicking help reverts back to the _Welcome to Bitshares help_ pop up (1-4)
![welcome_to_bitshares_landing_1_capture](https://user-images.githubusercontent.com/18186497/49717225-f2a4c000-fc1b-11e8-91d9-8b0c836aa6df.JPG)
9. Click _skip_ closing the _help_ pop up
10. Click _restore your account_
![181212-rc1_restore_backup_1_capture](https://user-images.githubusercontent.com/18186497/49717358-76f74300-fc1c-11e8-896b-bcd947c5688d.JPG)
11. Click the blue _help_ button again noting that there is no help pop ups; directs to the Graphene Help documents. If pointing to the Graphene documentation is the intention, consider pointing to the specific section of the Graphene documentation for a better user experience and self help, professionalism, and less customer support.

**Expected behavior**
Consistent and easy help pop ups and directives

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera
 - Version 56.0.3051.116
 - Release 181212-rc1

**Additional context**
Additional help pop up errors enclosed for easy reference to the aforementioned issue
![bts_advanced_login_capture_2](https://user-images.githubusercontent.com/18186497/49717990-5def9180-fc1e-11e8-91c5-06bb95c28f76.JPG)Missing the help pop up number
![bts_advanced_login_capture_3](https://user-images.githubusercontent.com/18186497/49718003-66e06300-fc1e-11e8-8fcb-4ccc0592aac8.JPG)Favorite is misspelled 
![bts_advanced_login_capture_4_shouldb5](https://user-images.githubusercontent.com/18186497/49718017-719af800-fc1e-11e8-8d71-a8d6ec00abb8.JPG)
![bts_advanced_login_capture_5](https://user-images.githubusercontent.com/18186497/49718024-7b246000-fc1e-11e8-9bd2-f2ddadc09c79.JPG)
![bts_advanced_login_capture_6](https://user-images.githubusercontent.com/18186497/49718035-82e40480-fc1e-11e8-99a7-d99386ea7693.JPG)
![bts_advanced_login_capture_7](https://user-images.githubusercontent.com/18186497/49718054-91322080-fc1e-11e8-85a4-50b28cb05754.JPG) Consider swapping _done_ and _back_

**Comment by sschiessl-bcp** [comment]
> * Scrolling issue may require some hours to find a fix for.

This is postponed. No feasible solution available. 

The sign up page should be refactored to include the new login mask anyways, closing this.
