### ISSUE TITLE
[.5] Make "wss" default in ADD API

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#230]
In Settings -> Access -> Add API the default string starts "ws://" but almost all nodes use "wss://" so it would make more sense to have that as the prefilled beginning of the address.

**Comment by wmbutler** [comment]
Agreed that this can default to wss://

**Comment by wmbutler** [comment]
![screen shot 2017-08-13 at 7 44 34 pm](https://user-images.githubusercontent.com/1254810/29254775-dbdbd450-805f-11e7-81a6-ff1b828c79cf.png)

**Comment by wmbutler** [comment]
Addressed this in #49 closing as duplicate.
