### ISSUE TITLE
Adding language and country flag modal next to the account name

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2300]
**Is your feature request related to a problem? Please describe.**
Please see #2298

**Describe the solution you'd like**
Please consider adding a language and country flag next to the account name after login

**Describe alternatives you've considered**
Adding language and country flag to the hamburger menu (inside general or new tab)

**Additional context**
Top right corner of the page is always visible and universally accepted

**Comment by startailcoon** [comment]
We've discussed this before, and came to the decision that a flag is not appropriate for language selection. What country flag would you choose for English, or Spanish, etc? A country has nothing to do with a specific language.

Closing
