### ISSUE TITLE
[1.5][MikhailKavalenka] Login restoring from a backup key- double loads chose a file twice

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2301]
**Describe the bug**
Trying to login using a _restore from key (.BIN)_; once the back up file is chosen and open is clicked, the chosen file window closes and another opens but is blank

**To Reproduce**
1. From the _Welcome to Bitshares_ page:
![welcome_to_bitshares_landing_1_1_capture](https://user-images.githubusercontent.com/18186497/49719500-ee2fd580-fc22-11e8-9dd7-b91b2201f091.JPG)
2. Click _Login_
![181212-rc1_login_restoring_backup_1_capture](https://user-images.githubusercontent.com/18186497/49719565-1e777400-fc23-11e8-8871-0aa526992563.JPG)
3. Select _Key file (local wallet)_ from the first drop down menu
4. Click _restore key file_ ; Chose file window pops up
5. Scroll to your back up .BIN key file and click open
6. Note the window closes and another appears.
    Scrolling down to the .BIN key file and clicking open a second time loads for the password prompt 
    and login is successful, **but** the _restore from a key_ window closes and reopens again first.3 
    different windows open/close twice each
    Conversely and if chosen,clicking cancel (in the chose file window) closes and opens again (same 
    behavior). Clicking cancel a second time closes the window. 

**Expected behavior**
For the chosen .BIN file to load the first time
Same for cancel if chosen 

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera 
 - Version 56.0.3051.116
 - Release 181212-rc1

**Additional context**
First time use after installation, I didn't have any issues. I was unable to duplicate this issue until after I had cleared cache and cookies.

**Comment by startailcoon** [comment]
Sounds like a cache issue after you've removed your keys and tried to import them again.

**Comment by startailcoon** [comment]
@MikhailKavalenka what is your progress?

**Comment by sschiessl-bcp** [comment]
Duplicate, or related to #2282
