### ISSUE TITLE
Replace wording from Welcome to Bitshares 

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2302]
**Is your feature request related to a problem? Please describe.**
Given global regulations and enforcement, careful wording is crucial  

**Describe the solution you'd like**
Replace wording _Your Decentralized Exchange_ with something else; _Platform_ , _Interface_, or _DEX_ _Solutions_, or very simply.....
**_Your Decentralized Blockchain_**
 _**You're Decentralized**_ 
_**Your DEX**_
of course DEX is an acronym for Decentralized Exchange but it could also be Distributed Execution
_Decentralized Enterprise DLT solutions_
_Decentralized DLT Solutions_
_Industrial DLT Solutions_

**Describe alternatives you've considered**
_Industrial Decentralized DLT solutions_
![welcome_to_bitshares_landing_1_1_capture](https://user-images.githubusercontent.com/18186497/49721521-ff2f1580-fc27-11e8-96a4-dca63f34b603.JPG)

**Additional context**
Very careful attention to wording and guidance to global regulations should be headed

**Comment by startailcoon** [comment]
Would love to hear other opinions on this topic. I'm not against the suggestion, but would probably be necessary for a overlook of the whole app to strip out the relation to the specific chain.

I see this as an opportunity to format the UI to a "global" client for "Bitshare types of chains".

**Comment by sschiessl-bcp** [comment]
"Your Decentralized Platform"
