### ISSUE TITLE
[3] Throw error on form when gate fee >= quantity to withdraw

### ISSUE THREAD

**Issue by robrigo** [bitshares/bitshares-ui#231]
There has been a lot of confusion with the OpenLedger gateway asset OPEN.MUSE, as people attempting to withdraw a test amount see nothing come through. This is usually because the test amount is less than the gate fee. Instead of donating their tokens to the gateway, the interface should prevent them from submitting an amount less than the gateway fee. Another problem is that in the latest release of the desktop wallet, it doesn't even display the gate fee, whereas on openledger.io, it does. Also the gate fee that is displayed on openledger.io is wrong. The gateway is actually taking 20 OPEN.MUSE but the label says 8 OPEN.MUSE. Lastly, depending on how the access the "Withdraw" functionality (in your asset list vs. gateway tab), the withdraw screen looks different.

Desktop wallet
![screen shot 2017-08-08 at 4 16 40 pm](https://user-images.githubusercontent.com/590263/29093261-352c94ca-7c57-11e7-9b08-02322ff9fe76.png)

openledger.io
![screen shot 2017-08-08 at 4 18 10 pm](https://user-images.githubusercontent.com/590263/29093271-41f1c6c6-7c57-11e7-84ec-cdc64446f2e0.png)

Accessing "Withdraw" link from the asset list looks different
![screen shot 2017-08-08 at 4 17 05 pm](https://user-images.githubusercontent.com/590263/29093306-648b8730-7c57-11e7-8a6c-ae05f389562a.png)

**Comment by wmbutler** [comment]
The Bitshares Light Wallet should display the gateway fee. We should also have better feedback regarding how many funds the user should expect to see in their target account once the transaction is complete like:

Amount to Withdraw: 11.6726
Gateway Fee: 8
Transaction Fee: .21851
Net Deposit: 3.45409

**Comment by wmbutler** [comment]
Bill to UX

**Comment by wmbutler** [comment]
- [ ] If fees > total withdrawal, leave withdrawal button DISABLED
- [ ] Only display warning if AMOUNT TO WITHDRAW is populated
- [ ] Remove dropdown from withdrawal address
- [ ] Ensure that neither Network fee or Gateway fee are editable

![screen shot 2017-08-14 at 2 56 34 pm](https://user-images.githubusercontent.com/1254810/29289213-2b16e5c2-8101-11e7-8577-30d964c87983.png)

**Comment by abitmore** [comment]
Gateway fees are charged by the UIA issuer, in addition to the fees that are paid to the network and referral program. They should maintain them, not us.

**Comment by wmbutler** [comment]
@abitmore Maybe I've misunderstood this issue. Users were complaining that they did not have visibility into all the fees being charged when withdrawing funds. My UX proposes to include the gateway fee on the withdraw screen so users have all the information needed to determine how much they need to send for say, a test transaction. There are cases where they might send 1 MUSE for a test, but since the gateway fee is 6 MUSE, their transaction will fail.

**Comment by robrigo** [comment]
I think what @abitmore was getting at, was that hardcoding gateway fees set by the UIA issuer (in this case OpenLedger) into the client for each pair offered by a gateway is a lot of maintenance work. I tend to agree.

Perhaps this could be solved as a piece of the #232 proposed feature to dynamically populate gateway data, by including the gateway fee for each trading pair in the manifest that a gateway would be required to publish.

**Comment by abitmore** [comment]
Best if gate fee is defined in the asset info. However, many people can setup gateways for assets like bitCNY with different fee, so it's not a perfect solution. alternatively, the 3rd gateway providers can provide an API for gate fees, so the wallet will know the latest fee rate. We can define a general format for this kind of APIs.

**Comment by abitmore** [comment]
> Perhaps this could be solved as a piece of the #232 proposed feature to dynamically populate gateway data, by including the gateway fee for each trading pair in the manifest that a gateway would be required to publish.

Agreed. This issue can be closed. Let's discuss in #232 .

**Comment by wmbutler** [comment]
Oh, I assumed that the gateway fee was defined in the asset info. Sorry for the disconnect here. Closing as suggested to work as part of #232.
