### ISSUE TITLE
[6] Dashboard Portfolio columns

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2311]
**Describe the bug**
The column value (BTS) is the only column underlined.

**To Reproduce**
1. Go to Dashboard Portfolio
2. Note value (BTS) is the only column underlined
![181212-rc1_dashboard_portfolio_2capture](https://user-images.githubusercontent.com/18186497/49791626-8480fb80-fcf6-11e8-96e9-89bbf1387436.JPG)

**Expected behavior**
Consistent with or without underlined columns

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera 
 - Version 56.0.3051.116
 - Release 181212-rc1

**Additional context**
Consider replacing the column __percent of Total Supply__ to _% Total Supply_ 
In the burn column, consider adding a "-"  (to be consistent with the rest of the page), or "N/A", or "X" for bitassets

**Comment by startailcoon** [comment]
Underlined header is the sorting column. This may not be obvious though.

### Task
- Add arrow up/down to sorted column, depending on order.
- Underline all sortable columns
- Rename percentage header
- Fix non-burnable assets

**Comment by sschiessl-bcp** [comment]
Using style-guide table should resolve all that easily, right?

**Comment by sschiessl-bcp** [comment]
Estimate for replacing with style guide is 6

**Comment by startailcoon** [comment]
@sschiessl-bcp do you have an update on the progress of this task?

**Comment by sschiessl-bcp** [comment]
Yes, PR soon

**Comment by sschiessl-bcp** [comment]
Hours needed was 11.5 due to increased complexity. Many components have been streamlined and refactored, see visual overview here https://github.com/bitshares/bitshares-ui/pull/2644#issue-274321369

Refactoring went also in the PaginatedList and Table component.
