### ISSUE TITLE
Settling bitUSD

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2312]
**Describe the bug**
1. Both from the Dashboard Portfolio Margin table and instant settlement of bitUSD (and all other 
   assets) it is possible to attempt to settle an asset with dust or zero balance. Please see #2310 
2. From the margin adjustment modal, clicking reset cancels instead
3. Debt and Collateral input field can not be backspaced in all cases
4. Click-able blue text Pay max debt under debt adjustment does not yield any results 

**To Reproduce**
1. Go toDashboard Portfolio Margin table
2. Click on the settlement flag for bitUSD
3. When margin adjustment window opens, note the input fields for debt (0) and collateral (0.00000)
4. Note that hovering over debt Use Max, informs the user that a collateral ratio is required before debt 
    can be maximized.
5. So, scroll down to collateral and click Use Max. Note that it changes from 0.00000 to 0 regardless of 
    the account balance available.
6. Note that the zero in collateral can't be backspaced for a blank field.
7. Input a 1 for a collateral of 10 BTS (note that clicking use collateral max again will zero it out instead)
8. Click the Debt Pay Max Debt again noting that nothing changes.
9. Attempt to click the Debt Use Max, as instructed before, 10 BTS were entered into the collateral field 
   so clicking Use Debt Max now should be possible but it is not click-able.
10. Input a 1 for a debt of 10 bitUSD noting that the collateral field changed back to 0.00000
11. Try to click Pay Max Debt and Use Max once more 
12. Click collateral Use Max now, noting a likelihood of insufficient funds. 
13. Attempt to backspace the 10 input in debt noting that the 1 remains undelete-able (and the 4 in the 
     collateral field if you tried)
     ATM 1bitUSD shows a collateral of 49.43820 at 1.76 ratio
14. Clicking Use Target Collateral Ratio was under development I think; yields no response.
15. Clicking Update Position ends with failed to broadcast after confirming the transaction and closes the 
     modal. 
![181212-rc1_bitusd_settlement_2_capture](https://user-images.githubusercontent.com/18186497/49799924-d6804c00-fd0b-11e8-814b-f91dccc92dc7.JPG)
16. Click on the bitUSD settlement flag in the margin table again opening up the margin modal
17. Note that the same data input earlier remains.
18. Click reset noting that the window closes
19. Again, click on the bitUSD settlement flag in the margin table, opening up the margin modal noting 
     that the fields are zero again. 

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera
 - Version 56.0.3051.116

**Additional context**
Both from the Dashboard Portfolio Margin table and the Exchange produced the same results; ability to attempt a TX with dust, zero, or more funds than available.
Consider adding a cancel button

**Comment by startailcoon** [comment]
PR https://github.com/bitshares/bitshares-ui/pull/2294 would solve this issue.
