### ISSUE TITLE
[3] Ability to cancel multiple orders on Exchange 

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2317]
Now we have "Scaled Orders" feature. It helps users to create multiple orders. But unfortunately users unable to cancel these multiple orders on easy way.

**Comment by startailcoon** [comment]
There is a way of doing this on the "Open Orders" of the dashboard.

![image](https://user-images.githubusercontent.com/12114550/49883806-b8157000-fe33-11e8-9a76-546624691640.png)

However, this doesn't seem to work when using a cloud account.

**Comment by gibbsfromncis** [comment]
@startailcoon I've unassigned myself

**Comment by startailcoon** [comment]
I will look on a feature for this

**Comment by startailcoon** [comment]
The following feature will enable the same feature on exchange as available in "Open Orders" today.

Each row has a checkbox that can be selected. It's also possible to use the "global" checkbox to toggle/un-toggle all checkboxes.
Once at least one checkbox is checked, the cancel button is visible. This is today limited to one OP per order that you wish to cancel.

## Order Rows
![image](https://user-images.githubusercontent.com/12114550/55687960-6c9f4880-5973-11e9-811b-d0cb0323a147.png)
