### ISSUE TITLE
Bitshares UI will not load with Firefox

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2321]
**Describe the bug**
Will not load at all. White "loading" screen only at staging.bitshares.org

**To Reproduce**
1. Using Firefox, go to staging.bitshares.org
2. See white "loading" screen

**Expected behavior**
A quick reliable connection.

**Screenshots**
![181212-rc1_firefox_loading_2_capture](https://user-images.githubusercontent.com/18186497/49865351-5836af00-fdca-11e8-87f5-78fd17c1194d.JPG)
![181212-rc1_firefox_loading_3_capture](https://user-images.githubusercontent.com/18186497/49865362-62f14400-fdca-11e8-9d5b-f1c545eed97a.JPG)
![181212-rc1_firefox_loading_5_capture](https://user-images.githubusercontent.com/18186497/49865395-769caa80-fdca-11e8-8621-17438d743c6c.JPG)
![181212-rc1_staging_firefox_loading_1](https://user-images.githubusercontent.com/18186497/49865420-80bea900-fdca-11e8-8eb0-a05a5aa50c93.gif)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Firefox 
 - Version 63.0.3(64-bit
 - Release 181212rc-1

**Additional context**
Same results except a black "loading" screen at openledger.io
![181212-rc1_firefox_loading_7_openledgerio_capture](https://user-images.githubusercontent.com/18186497/49866584-caf55980-fdcd-11e8-85ea-c81d0088c077.JPG)
At wallet.bitshares.org it finally loads after the same long timeouts as seen with Google and Opera
![181212-rc1_firefox_loading_6_walletbitsharesorg_capture](https://user-images.githubusercontent.com/18186497/49866678-01cb6f80-fdce-11e8-9773-d66f4abd90db.JPG)

**Comment by startailcoon** [comment]
I can not reproduce this, neither on staging.bitshares.org nor on openledger.io

Openledger.io did give me a node timeout error to select another node, but worked fine after selecting one.

**Comment by TechsUsInc** [comment]
After a reboot and Firefox auto update (which is the same version 64.0) another attempt at staging.bitshares.org with Firefox was more successful. Same issues seen with Opera and Google, nothing additional. 
Openledger.io still wouldn't load for me.
