### ISSUE TITLE
[1.5][kennybll] Login and confirm button require mouse click

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2322]
**Describe the bug**
Both the login button and the confirm button require a mouse click; the user can't hit the enter key to proceed.

**To Reproduce**
1. Go to login, enter the account, password, hit enter; see there is no response
2. Click on login; see response
3. Go to the Exchange and select a trade
4. Click buy or sell 
5. Hit the Enter key to confirm noting no response
6. Click confirm; see response

**Expected behavior**
For login and confirm buttons, enable the enter key

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera
 - Version 56.0.3051.116
 - Release 181212cr-1

**Additional context**
Same for Google Version 70.0.3538.110  
Same for Firefox Version 63.0.3

**Comment by startailcoon** [comment]
I agree, enter key should trigger the form submit.

**Comment by Kennybll** [comment]
I can take this

**Comment by startailcoon** [comment]
it's yours
