### ISSUE TITLE
Explorer-disabling view mode when adding an account does not disable view mode

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2323]
**Describe the bug**
When adding an account via the _Explorer Accounts_ tab a warning _viewing unauthorized account_ pops up. If _Never Show Again_ is clicked, the pop up goes away but the _view mode_ button remains next to the account name.

**To Reproduce**
1. Go Explorer 
2. Click on Accounts
3. Type the name of a known account (preferably authorized)
4. See error; Viewing unauthorized account
5. Click Never Show Again noting the pop up goes away
6. Note that the view mode button remains next to the account name
7. Click it noting it then goes away

**Expected behavior**
Clicking Never Show Again to remove the view mode button 

**Desktop (please complete the following information):**
 - OS:Windows 8.1
 - Browser Opera 
 - Version 56.0.3051.116
 - Release 181212rc-1

**Additional context**
Same with Google and Firefox

**Comment by startailcoon** [comment]
The `View Mode` button is there to notify you that you're viewing another account, not any of your own accounts.

Toggling `Never Show Again` on the popup will only hide the popup again, not the `View Mode` button that you use to toggle back to on of your own accounts again.

This is expected handling.
