### ISSUE TITLE
[0.5] Legacy Deposit/Withdraw Citadel and WinEX issues

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2325]
### As described in PR #2285 

WinEX has some issue making the app hang on loading as it doesn't catch failure. Citadel had some fetching issues as well, but did not hang the client. As they are the only ones not working, my plan was to do a new PR with a fix for them, but disable them until then to make sure we get the BlockTrades fix in an the application halting errors out for the time being.

_Originally posted by @startailcoon in https://github.com/bitshares/bitshares-ui/pull/2296#issuecomment-446231152_

- Fix currently disabled Citadel Gateway
- Fix currently disabled WinEX Gateway

**Comment by sschiessl-bcp** [comment]
No response on latest ping from Winex, removing now.
