### ISSUE TITLE
Sell order expiration 8760 x too short

### ISSUE THREAD

**Issue by MarkoPaasila** [bitshares/bitshares-ui#2326]
**Describe the bug**
Order expiration time for sell orders is just 1h.

**Expected behavior**
Sell order expiration same as buy order expiration; 1 year.

**Screenshots**
![](https://i.imgur.com/DOllcAO.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Appimage
 - Version 181121

**Comment by startailcoon** [comment]
Are you sure you haven't set it to 1 hour yourself? This value is stored in cache and should always be 1 year if not set at all. I can not replicate this with a cleared local cache.
