### ISSUE TITLE
[1][twksos] Adding a color legend to the Visual Portfolio in the Dashboard

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2327]
**Is your feature request related to a problem? Please describe.**
The Dashboard Visual Portfolio blocks vary with color, percentage of asset in the account.

**Describe the solution you'd like**
Consider a tooltip at (visual and active) explaining what a Visual and (active)Portfolio is.
Consider adding a color legend next to the word visual. 
Consider adding the 24hr column from the Active Portfolio to the Visual Portfolio (under the asset name-in green, red, or white)
![181212-rc1_visual_1_capture](https://user-images.githubusercontent.com/18186497/49932016-b5dfff80-fe8d-11e8-8fbc-38989a61b849.JPG)
![181212-rc1_visual_2_capture](https://user-images.githubusercontent.com/18186497/49932017-b5dfff80-fe8d-11e8-9478-a23e8fccb502.JPG)
![181212-rc1_visual_3_capture](https://user-images.githubusercontent.com/18186497/49932019-b6789600-fe8d-11e8-9b0f-4ecc750225b9.JPG)
![181212-rc1_visual_4_capture](https://user-images.githubusercontent.com/18186497/49932020-b6789600-fe8d-11e8-8767-97893f71bfe9.JPG)
Consider clicking on an asset in the Visual Portfolio takes you to the market
OR, re-directs to a Cryptofresh type page incorporated with similar to what you see here:     
https://www.tradingview.com/symbols/NASDAQ-TLRY/# 
including news/Graphene project feeds (Steemit, Whaleshares,etc). The technical oscillator would be a useful tool.

**Comment by twksos** [comment]
request to work on this issue

**Comment by startailcoon** [comment]
@twksos it's yours

**Comment by sschiessl-bcp** [comment]
@twksos please state your bitshares account for bounty

**Comment by clockworkgr** [comment]
@twksos ping

**Comment by twksos** [comment]
@sschiessl-bcp @clockworkgr 
My bitshares account is `twksos02`

**Comment by clockworkgr** [comment]
> @sschiessl-bcp @clockworkgr
> My bitshares account is `twksos02`

paid
