### ISSUE TITLE
[1.5] Remember Me switch added to the hamburger menu settings

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2328]
**Is your feature request related to a problem? Please describe.**
The Remember Me switch is only seen by a user when they log in with a cleared cache. (From what I recall)

**Describe the solution you'd like**
Consider adding the same switch to the hamburger menu settings page in the event a user wants to disable it before closing Bitshares, or switching accounts, or sharing a device, etc

**Describe alternatives you've considered**
Remember Me switch added somewhere near the account name, but it would clutter

**Comment by startailcoon** [comment]
Could pose a problem yes, since to have it "forget" the account you now have to lock/logout and then login and toggle off remember me.

Can we find a good place to have it in the menu?

**Comment by clockworkgr** [comment]
@gibbsfromncis have a look at this

**Comment by gibbsfromncis** [comment]
@startailcoon @sschiessl-bcp  what is the logic of "Remember Me" feature?

**Comment by startailcoon** [comment]
When I see a "Remember Me" toggle and have it set to 
1. **On**. Expect to not have to fill in username again, but prompt for password login.
2. **Off**. Expect that the application will not automatically fill in my username again, making the next usage not reviel who logged in last.

**Comment by sschiessl-bcp** [comment]
The remember me features, from the technical perspective, switches from a persistent localStorage implementation to an in-ram implementation.

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp would you like to take this issue?

**Comment by sschiessl-bcp** [comment]
IMO remember me on login dialog is enough

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I suppose @TechsUsInc means he wants to have some kind of "Logout" feature. 

@TechsUsInc Am I correct?

**Comment by TechsUsInc** [comment]
> @sschiessl-bcp I suppose @TechsUsInc means he wants to have some kind of "Logout" feature.
> 
> @TechsUsInc Am I correct?

Yes correct. I had assumed the easiest solution was to just offer secondary access to the same feature for security, a better user experience, and anticipating increased adoption consider the following use case examples:

- More than one BitShares user sharing a device such as (husband,wife,kids,Grandparents,etc); home computer, laptop, tablet. Applicable regardless if the whole family has a BitShares account or only 1 member has an account. If remember me is enabled for said 1 account, others may gain unauthorized account access.

- Potential unauthorized access to an account from a public utilized device; public library, Internet cafe, University resources, friends or family devices, etc.

- One or more users sharing a device, each having multiple accounts; personal, business, arb bots, staking, etc

- Account Switching between BitShares and BEOS, or other 

- Preventing unauthorized access via a device that is to be sold, donated, or upgraded.

**Comment by sschiessl-bcp** [comment]
Ok, so you would like something like a logout feature. We have a separate issue for that one. Closing this
