### ISSUE TITLE
[0.5][Kennybll] Add the word testnet to the node access pop up

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2329]
**Is your feature request related to a problem? Please describe.**
Some testnet WS locations are the same as in available and personal, so the node access pop up may say France-Paris in any case.

**Describe the solution you'd like**
Consider adding the word TESTNET in the node access pop up next to the location (France-Paris) for easy quick self help or addition to the last 20 logs (customer support)
![181212rc-1_node_access_popup_2_capture](https://user-images.githubusercontent.com/18186497/49943555-cbfdb800-fead-11e8-8fc0-0a19aae9fd05.jpg)

**Comment by startailcoon** [comment]
Good idea!

**Comment by Kennybll** [comment]
I can take this one 😃

**Comment by startailcoon** [comment]
See if you can make it look good 👍

**Comment by Kennybll** [comment]
This look good @startailcoon ?
![image](https://user-images.githubusercontent.com/14302151/50010409-5f56ec00-ff87-11e8-8341-036cc01b859f.png)

**Comment by startailcoon** [comment]
Clean and consise 👍
