### ISSUE TITLE
Sign any message with any account key

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-ui#233]
I would like to have a feature that allows the wallet to sign any message with any key in the wallet.
Ideally, this can be used to prove ownership of an account.
The page would have these input fields

* message
* key (list accounts, then pick from active, owner, memo - if pressent ... or pick `other key` to list all known keys in the wallet)
* signature (signature for the message)

I would recommend to use the same syntax that bitcoin uses which looks like this:

```
-----BEGIN BITCOIN SIGNED MESSAGE-----
This is an example of a signed message.asfasf
-----BEGIN BITCOIN SIGNATURE-----
Version: Bitcoin-qt (1.0)
Address: 1HZwkjkeaoZfTSaJxDw6aKkxp45agDiEzN

G7uxfdHRjFEpnvcv+m4HUg0dUwWIjmpJ6wI3DjaU8/Kcb9CZOLF9JUfBUtav8SUjm5bnxQPsbM4fHyW1rui/DMc=
-----END BITCOIN SIGNATURE-----
```

Except that we should use a public key instead of an address .. like this:

```
-----BEGIN BITCOIN SIGNED MESSAGE-----
This is an example of a signed message.asfasf
-----BEGIN BITCOIN SIGNATURE-----
Chain: BitShares
Account: xeroc
Publickey: BTS5TPTziKkLexhVKsQKtSpo4bAv5RnB8oXcG4sMHEwCcTf3r7dqE

G7uxfdHRjFEpnvcv+m4HUg0dUwWIjmpJ6wI3DjaU8/Kcb9CZOLF9JUfBUtav8SUjm5bnxQPsbM4fHyW1rui/DMc=
-----END BITCOIN SIGNATURE-----
```

**Comment by btsfav** [comment]
yes, please!

**Comment by btsfav** [comment]
can this be pushed?

**Comment by calvinfroedge** [comment]
@xeroc Does this just generate a message you'd then copy paste with the signature?

**Comment by btsfav** [comment]
@calvinfroedge feature is implemented since last update
