### ISSUE TITLE
Blank Screen After Settling A Small Balance

### ISSUE THREAD

**Issue by Kennybll** [bitshares/bitshares-ui#2333]
**Describe the bug**
When I settled an asset with a really small amount, the page broadcasted the operation, but then the site went to a blank white-ish page.

**To Reproduce**
1. Your assets list
2. Click on the settle flag, enter a small amount, 0.00001 TESLACOM
3. Scroll down to console

**Expected behavior**
I don't know if it's related to the small amount, or in general. But for the page not to go to a blank screen.

**Screenshots**
![image](https://user-images.githubusercontent.com/14302151/49957440-c3b97300-fed5-11e8-886b-0ecdd23ebcd5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 70.0.3538.110 (Official Build) (64-bit)

**Also**
You may be missing a translation:
![image](https://user-images.githubusercontent.com/14302151/49957604-59550280-fed6-11e8-9b21-29b11ab1c898.png)

**Comment by startailcoon** [comment]
What version of Bitshares client did you do this on? We've had a few fixes for the current RC (181212-RC1)

**Comment by Kennybll** [comment]
Bitshares.181129. So I guess this might not be relevant?

**Comment by startailcoon** [comment]
Please try with staging.bitshares.org or the latest RC client.

**Comment by Kennybll** [comment]
Works now, thanks @startailcoon
