### ISSUE TITLE
[1.5] Account name resets when trying to login

### ISSUE THREAD

**Issue by Kennybll** [bitshares/bitshares-ui#2335]
**Describe the bug**
I noticed this on my Windows 10 pc, and now on my Android tablet. When I try to log into staging.bitshares.org and am typing into the account name input it keeps deleting what I put in randomly. After awhile on my pc it finally took.

**To Reproduce**
1. Go to the login screen
2. Click on login with account name
3. Start to type in your account name

**Expected behavior**
The input field to not reset after typing halfway through my account name.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Chrome 
 - Version 70.0.3538.110 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Tab A 8.0
 - OS: Android 7.1.1
 - Browser Firefox
 - Version 63.0.2

**Comment by startailcoon** [comment]
@sschiessl-bcp I've noticed this once to and I think it relates to the node ping that is done at the same time. When the node ping text is updated the form is cleared.

**Comment by sschiessl-bcp** [comment]
I suspect when there is no account in AccountStore set and the Settings 
update with a ping, it resets the login form to what the Settings say.

The login form should only set the account name once on mounting and not 
when Settings change.

Am 14. Dezember 2018 11:01:22 nachm. schrieb startailcoon 
<notifications@github.com>:

**Comment by hldzlk** [comment]
I can take this.

**Comment by hldzlk** [comment]
`bitshares-ui/app/components/Wallet/WalletUnlockModal.jsx`
```js
    componentWillReceiveProps(np) {
        const {walletSelected, restoringBackup, accountName} = this.state;
        const {
            currentWallet: newCurrentWallet,
            passwordAccount: newPasswordAccount
        } = np;

        const newState = {};
        // There is no need to update accountname in real time
        // if (
        //     (newPasswordAccount && !accountName) ||
        //     newPasswordAccount !== accountName
        // )
        //     newState.accountName = newPasswordAccount;
        if (walletSelected && !restoringBackup && !newCurrentWallet)
            newState.walletSelected = false;
        if (this.props.passwordLogin != np.passwordLogin) {
            newState.passwordError = false;
            newState.customError = null;
        }

        this.setState(newState);
    }
```

**Comment by sschiessl-bcp** [comment]
Please do a PR for this

**Comment by startailcoon** [comment]
@hldzlk please submit a Bitshares account for the reward to be sent to. Thanks!

**Comment by hldzlk** [comment]
@startailcoon  My Bitshares account is ``` hldzlk```. Thanks!
