### ISSUE TITLE
[1] Fix TESTNET problem with no default preferred asset

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2337]
Whenever a testnet does not use a default asset from the branding.js settings file (due to an unknown chain etc) the application would fail on a few of the components that had no failsafe.

This issue is to track hours for fixing those errors.

**Comment by startailcoon** [comment]
Requires additional review for PR

**Comment by clockworkgr** [comment]
@sschiessl-bcp lets review and close this in this sprint

**Comment by startailcoon** [comment]
From PR

> I see no high priority on this PR as Ryan solved his issues based on my change. Though, it would be beneficial to work out the kinks in it, and it will be looked on when I have the time to.

Will continue to work on this when time lets me.
