### ISSUE TITLE
[1][MikhailKavalenka] 'Input' field background issues

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2344]
Since a few commits ago we have an issue with `<input />` fields having a white background, making them impossible to use for submitting forms.

These fields are the standard input fields, not converted to the new Style Guide.

### Examples 

`/create-account/password`
![bild](https://user-images.githubusercontent.com/12114550/50044402-39af0d00-0083-11e9-9812-74913d83b7cf.png)

`/deposit-withdraw`
![bild](https://user-images.githubusercontent.com/12114550/50044405-429fde80-0083-11e9-9e58-e0eda303763a.png)

**Comment by MikhailKavalenka** [comment]
@startailcoon , I can it

**Comment by startailcoon** [comment]
👍
