### ISSUE TITLE
Update CONTRIBUTING.md To Use Develop Branch

### ISSUE THREAD

**Issue by Kennybll** [bitshares/bitshares-ui#2348]
**Describe the bug**
In the [CONTRIBUTING.md](https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md) guide it says to use the staging branch as a base for contributing.

**Expected behavior**
It should say to use the develop branch as a base for contributing.

**Additional context**
I actually has to close and reopen a pull request because I used staging instead of develop.

**Comment by startailcoon** [comment]
👍 Will do
