### ISSUE TITLE
[2][manikey123] Cannot delete value in Collateral Field

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#2350]
It's updating for me but this value cannot be deleted as shown here

![delete](https://user-images.githubusercontent.com/1254810/50047028-5b07fd00-0073-11e9-8ebb-735709f163f5.gif)

**Comment by manikey123** [comment]
claiming this
can u share the path to navigate to collateral tab ?

**Comment by sschiessl-bcp** [comment]
Go to Dashboard, find Margin Positions and click the Borrow icon

**Comment by manikey123** [comment]
Simulated the "value cannot be deleted scenario" and went through corresponding code. 

Tried different combinations, finally after removing below filter existing in AmountSelector.jsx, the "value cannot be deleted scenario" is resolved
	                //amount: this.getNumericEventValue(e)
					
Impact:
The component AmountSelector.jsx is used at multiple places. 
\bitshares-ui\app\components\Account\AccountAssetCreate.jsx
\bitshares-ui\app\components\Account\AccountAssetUpdate.jsx
\bitshares-ui\app\components\Account\FeePoolOperation.jsx
\bitshares-ui\app\components\Blockchain\AssetPublishFeed.jsx
\bitshares-ui\app\components\Blockchain\BidCollateralOperation.jsx
\bitshares-ui\app\components\DepositWithdraw\bitspark\BitsparkWithdrawModal.jsx
\bitshares-ui\app\components\DepositWithdraw\blocktrades\WithdrawModalBlocktrades.jsx
\bitshares-ui\app\components\DepositWithdraw\citadel\WithdrawModalCitadel.jsx
\bitshares-ui\app\components\DepositWithdraw\gdex\GdexWithdrawModal.jsx
\bitshares-ui\app\components\DepositWithdraw\openledger\DepositFiatOpenLedger.jsx
\bitshares-ui\app\components\DepositWithdraw\openledger\WithdrawFiatOpenLedger.jsx
\bitshares-ui\app\components\DepositWithdraw\rudex\RuDexWithdrawModal.jsx
\bitshares-ui\app\components\DepositWithdraw\winex\WinexWithdrawModal.jsx
\bitshares-ui\app\components\DepositWithdraw\WithdrawModal.jsx
\bitshares-ui\app\components\DepositWithdraw\xbtsx\XbtsxWithdrawModal.jsx
\bitshares-ui\app\components\Modal\BorrowModal.jsx
\bitshares-ui\app\components\Modal\IssueModal.jsx
\bitshares-ui\app\components\Modal\ReserveAssetModal.jsx
\bitshares-ui\app\components\Modal\SendModal.jsx
\bitshares-ui\app\components\Modal\SettleModal.jsx
\bitshares-ui\app\components\Modal\WithdrawModalNew.jsx
\bitshares-ui\app\components\Transfer\Transfer.jsx
\bitshares-ui\app\components\Utility\PriceInput.jsx

Possible Resolution1:
Change the class name ( for example AmountSelector2.jsx ) and remove the filter/function causing the issue.

Possible Resolution2:
Study impact of above change on above multiple JSX file

Let me know which Resolution to proceed with. If any thing better do let me know. ( 3 hrs spent on ticket).

**Comment by manikey123** [comment]
Let me know any feedback @sschiessl-bcp @startailcoon

**Comment by sschiessl-bcp** [comment]
I'd assume that the event value should be allowed to be an empty string. 

Can you check the history of that file what was changed in the past?

**Comment by sschiessl-bcp** [comment]
I mean was there any change in the past that would cause this behavior? Or was it always like that?

I'd aim for a fix that either allows that the numeric input value is null (when string in field is "") or similar

**Comment by manikey123** [comment]
thanks. will go through code and update !

**Comment by manikey123** [comment]
> I mean was there any change in the past that would cause this behavior? Or was it always like that?

From history file history file AmountSelector.jsx Line 91 8a92c6c#diff-059c22265510dbbbdd056857f0e4311d, there is a change "this.getNumericEventValue(e)" this causes the bug provided by @wmbutler "updating for me but this value cannot be deleted as shown here"
![image](https://user-images.githubusercontent.com/22608398/51163469-981c0680-184e-11e9-93da-17b3373eedb3.png)

> I mean was there any change in the past that would cause this behavior? Or was it always like that?
> 
> I'd aim for a fix that either allows that the numeric input value is null (when string in field is "") or similar

Based on the fix of removing "this.getNumericEventValue(e)" , string numeric value of null is allowed.
Initial : 
![image](https://user-images.githubusercontent.com/22608398/51163580-12e52180-184f-11e9-82d4-d2a327131669.png)
After clicking on "update position"
![image](https://user-images.githubusercontent.com/22608398/51163617-314b1d00-184f-11e9-9368-7744d0ed5193.png)


Current web version https://wallet.bitshares.org also works if u pass null. 
however if u provide a number and then backspace to remove, it does not remove , due to bug we cannot get null state.

**Comment by sschiessl-bcp** [comment]
My suggestion would be to check the event `e` and if it contains a valid null/empty string value as user input, forward `""` as value to `onChange`, otherwise `this.getNumericEventValue(e)`

**Comment by manikey123** [comment]
added above logic and tested it out. Create PR #2412. Plz review
@sschiessl-bcp

**Comment by manikey123** [comment]
@sschiessl-bcp : let me know if any thing needs to be done on this ticket. otherwise we can close the ticket. Thanks.

**Comment by manikey123** [comment]
please update time spent to 4 hours
-3 hours spent on simulating, fixing and providing recommendation ( as mentioned on dec 25)
-1 hour spent on review note and history changes
