### ISSUE TITLE
[0.1][hldzlk] Datetime picker Expiration - expand datetime picker field

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2355]
**Describe the bug**
In some instances the datetime picker information does not show
Please see #2356 

**To Reproduce**
1. Go the Exchange tab
2. Click on the BTS tab for BitCNY:BTS pair
3. Scroll down past the chart to buy/sell
4. Click on default expiration of 1 year
![181212rc-1_datetime_picker_1_1yr_capture](https://user-images.githubusercontent.com/18186497/50131521-1f725c00-0248-11e9-8461-760b0bb1dbfe.JPG)
5. See error of the "M" in AM or PM scrolls out of the window
![181212rc-1_datetime_picker_1_1_capture](https://user-images.githubusercontent.com/18186497/50130435-3d898d80-0243-11e9-8bc5-f409b26a6f4b.JPG)

4. Click on "A" or "P" in AM or PM respectively
5. Arrow key right noting that the "M" in AM or PM is now visible 
(closing the calendar or clicking anywhere reverts back to the "M" missing)

**Expected behavior**
Day-Month-Year-Time- visible for any day and any year.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera
 - Version 56.0.3051.116
 - Release 181212rc-1

**Comment by hldzlk** [comment]
I can take this.

**Comment by startailcoon** [comment]
It's your @hldzlk
