### ISSUE TITLE
[0.5] Explore Asset tab - clicking asset breaks the site

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2359]
**Describe the bug**
Clicking an asset breaks the page.
I checked most (broke the page) with the exception of Bit.xxx (committee-account)

**To Reproduce**
1. Go to Explore
2. Click on Assets
3. See that Smartcoins is selected (default)
4. Click on ABITS.CNY
![181212rc-1_explore_asset_1_capture](https://user-images.githubusercontent.com/18186497/50140323-f662c300-0269-11e9-924a-b5bae354dee5.JPG)

5. See error
![181212-rc1_explore_assets_1](https://user-images.githubusercontent.com/18186497/50140364-1d20f980-026a-11e9-9837-09306d8df1ea.gif)

**Expected behavior**
A synopsis of the asset in a tooltip
Clicking on an asset to go to the asset information page

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser Opera
 - Version 56.0.3051.116
 - Release 181212rc-1

**Additional context**
Note
![181212rc-1_explore_asset_2_capture](https://user-images.githubusercontent.com/18186497/50140344-0aa6c000-026a-11e9-97c7-04f79b85f289.jpg)

**Comment by startailcoon** [comment]
The asset wasn't possible to load due to the missing in feed providers of the asset. As no feed where able, the code crashed when using feed price to calculate.

**Comment by TechsUsInc** [comment]
Yes Sir. Is it possible to have it load a blank synops with " missing feed price of asset" or something similar to avoid a code crash (customer support issue declination) so the user can continue (self help).
