### ISSUE TITLE
[.5][ariesjia] Delete "Try To Claim All" Button

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#236]
Account > Vesting Balances

after a short discussion with @svk31 - this button should be obsolete.

![](https://i.imgur.com/MDEEdOJ.png)

**Comment by abitmore** [comment]
Actually all needed data is in the object, so we can get the exact amount that can be claimed with calculations. However, looks like it's hard to do 128 bit calculations with JS? Perhaps it's best to add an API to get claim-able amount.

**Comment by wmbutler** [comment]
@svk31 I think we'll need your input on this to estimate unless it's going to be a simple button removal. If it's just a button removal, I'd give it .5 hours.

**Comment by svk31** [comment]
In a previous commit I added the get_vesting_balance api call to make sure the claiming amount was correct, but also added this 'try to claim all' button just in case the api gave incorrect data. There might also be rounding errors like abit mentioned. I suggest we try to simply remove it, then if we get reports of people being unable to claim the full amounts we can look into it then.

**Comment by wmbutler** [comment]
Agreed. Remove it. Please claim it if you decide to work it.
