### ISSUE TITLE
[0.1][iamredbar] GUI issue - Misspelling when depositing

### ISSUE THREAD

**Issue by iamredbar** [bitshares/bitshares-ui#2369]
Description: There is a misspelling in the desktop wallet when going to deposit an asset. This goes for any asset that allows depositing.

**To Reproduce**
1. Go to BITUSD/BTS pair on desktop wallet under exchange.
2. Click on "Deposit BTS"
3. See error. The word Bridge is misspelled on the deposit page.

**Expected behavior**
Correct spelling.

**Screenshots**
![screen shot 2018-12-20 at 3 33 31 pm](https://user-images.githubusercontent.com/16945982/50312326-963c6e80-046d-11e9-87e2-a84ab56bf771.png)

**Desktop**
 - OS: High Sierra (10.13.6)
 - Desktop Wallet
 - Version 2.0.181129 (2.0.181129.2062)

**Comment by iamredbar** [comment]
I have also found the same error on staging.bitshares.org.

![screen shot 2018-12-21 at 5 14 02 pm](https://user-images.githubusercontent.com/16945982/50367214-48466a00-0544-11e9-92d2-7968b3ff1007.png)

**Comment by iamredbar** [comment]
I would like to claim this issue.

To make the changes, I pull from development branch and fix. Correct? This will be my first time contributing.

**Comment by iamredbar** [comment]
Please refer to Pull Request #2373 for completed issue. This took me less than an hour.

**Comment by startailcoon** [comment]
Thanks for your contribution @iamredbar

**Comment by iamredbar** [comment]
BitShares account name: iamredbar1
