### ISSUE TITLE
[1][ariesjia] UI Visual Issue: Switching Trading Pairs when using Horizontal Mode

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#237]
There is a UI Visualization Issue when using the Horizontal Price Trading Ledger.

If you pick a trading pair, say `GRC : BTS` and then switch to `SBD : BTS` the list will not go back to the bottom. I think the issue here is that the list is made for the normal Vertical Price Trading Ledger and it hasn't been taken in to consideration that this works the opposite way.

Doing this when not using the Horizontal ledger works without any issues.

Example Images

`GRC:BTS`
![bts_tradingpairhorizontal_btsgrc](https://user-images.githubusercontent.com/12114550/29248366-e2695c28-8016-11e7-83b2-eadc30116b63.PNG)

`SBD:BTS` right after switching pairs. You can see that the ruler on the side is scrolled down far in the list.
![bts_tradingpairhorizontal_btssbd_1](https://user-images.githubusercontent.com/12114550/29248369-ef19395c-8016-11e7-93ed-a5090da37794.PNG)

`SBD:BTS` after I scroll the ruler up in the list and find the prices again.
![bts_tradingpairhorizontal_btssbd_2](https://user-images.githubusercontent.com/12114550/29248373-09fef1d0-8017-11e7-85a7-534c00269d4a.PNG)

**Comment by wmbutler** [comment]
Well documented bug. I've experienced this as well.
