### ISSUE TITLE
[1.5] Collateral bidding: Fix to work for non-BTS backed SmartCoins

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2370]
e.g. https://develop.bitshares.org/#/asset/COMPUMATRIX.USD

**Comment by startailcoon** [comment]
Issue fixed. 

There where a few issues with the code for this asset.

- We had Core asset as always the backing asset. Fixed
- Asset has no valid price data to calculate the ratios. Fixed
- Asset has no valid fees to display the feed table. Fixed


![image](https://user-images.githubusercontent.com/12114550/58757624-c05f8580-850f-11e9-9ae8-49327f2ea474.png)

![image](https://user-images.githubusercontent.com/12114550/58757628-d53c1900-850f-11e9-8ef3-2f1af39045f9.png)
