### ISSUE TITLE
[0.5] Missing Market Fee on Exchange

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2375]
Market Fee on Exchange is not populated correctly when values are changed.
The value would always stay to 0.

**Comment by MindfulMe** [comment]
@startailcoon I can take care of it

**Comment by startailcoon** [comment]
@MindfulMe this issue already has a PR waiting for merging.
An issue is free to claim if there are no assignees, or no name attached to the title.
