### ISSUE TITLE
Testnet does not work

### ISSUE THREAD

**Issue by erdonmez** [bitshares/bitshares-ui#2377]
Testnet does not work
https://testnet.bitshares.eu/
![image](https://user-images.githubusercontent.com/9018170/50387437-63180a80-070d-11e9-8e24-ce221921e334.png)

**Comment by startailcoon** [comment]
This page has nothing to do with the Bitshares UI repository. 
However, I'm able to use the testnet.bitshares.eu page. 

![image](https://user-images.githubusercontent.com/12114550/50398637-706ade80-0779-11e9-8f21-1f8caa34e75c.png)
