### ISSUE TITLE
Consider NOT using Ant Design library

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#2379]
**Describe the bug**
Ant Design library may change the appearances of UI elements without prior notification on specific dates.

**To Reproduce**
1. Go to initialization failed page
2. See retry button

Actually
1. Just use the UI for a while
2. Notice how some buttons change appearances

N.B. make sure the system date is 12/25.

**Expected behavior**
UI should be stable and there shouldn't be any UI changes by date like that.

**Screenshots**
![0030-12-25 13 06 23](https://user-images.githubusercontent.com/861659/50411897-0de01400-0847-11e9-9696-a1780bdbe5dd.png)

**Desktop (please complete the following information):**
Irrelevant

**Smartphone (please complete the following information):**
Irrelevant

**Additional context**
I think a good UI library should not have behaviors like that. The appearances of UI elements should be as stable as possible. I don't think we can trust this library after it showed this behavior.

Or hack through their code and remove all related functions.

Maybe I'm just ranting about this, but seriously this behavior should not be accepted.

**Comment by startailcoon** [comment]
I to reacted on this and got very surprised about this "feature". Since Christmas isn't a "world wide event" I'd say that this was a very bad judgment by some of their developers. You can see that they've been pretty scolded by this on their repository https://github.com/ant-design/ant-design/issues/13098

Our issue #2241 is for updating this repository to the latest one.

**Comment by HarukaMa** [comment]
@startailcoon I was just trying to convince others that this specific library may not worth the trust, especially for a reference wallet implementation.

If just updating the library is your final decision, I will say nothing more on it.

**Comment by startailcoon** [comment]
We take your concern with highest respect.

While it's most unfortunate, the framework won't be changed short term. Once the UI is transitioned to use the new style guide everywhere, exchanging the underlying framework should be easier.
