### ISSUE TITLE
Integrate shapeshift.io as a bridge via their API

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#238]
While it is my understanding that traditionally a company who wishes to provide a bridge or gateway service is responsible for contributing the code necessary to enable their service, I don't think ShapeShift would consider this to be a high priority for them (they're busy establishing partnerships with companies like OverStock), and as much as I hate to admit this - as thing are today, we need this more than they do.

It has come to my attention that ShapeShift has an [affiliate program](https://shapeshift.io/legacy/affiliate.html), which creates an incentive for wallet providers to see the addition of this feature, as they could create affiliate accounts with ShapeShift, and could potentially earn a commission from the fees. This does, however, raise the question of whose ShapeShift affiliate key belongs in the reference implementation. IMHO, it is a reasonable bonus for whichever developer contributes the code to make their affiliate pubkey the default, for a pre-determined and agreed upon (by shareholder vote, or some other mechanism though?) period of time. In advance of the expiration of that period of time, a mechanism should be established for any payouts earned by the default ShapeShift affiliate find their way into the reward pool.

**Comment by wmbutler** [comment]
Might make sense for a BTS general fund to receive a commission for this. @xeroc might have some thoughts.

**Comment by btsfav** [comment]
please make sure to measure the safety as well before integration. 

can shapeshift widget be sandboxed?

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
Sometimes shapeshift (and other bridges and gateways) have downtimes. 

For safety, it would have to know when shapeshift support for BTS is down.

I know openledger often has times when you don't know their node for that coin are down until you try to generate a new address and it reports error.

**Comment by grctest** [comment]
Bitshares is currently disabled on Shapeshift, perhaps alternative bridge websites like flyp.me could replace shapeshift in this scenario?

**Comment by Ashaman-** [comment]
@o5j5vg55bv5hv5j5f8799f9 You make a good point. I believe [shapeshift's API supports checking availability status of coins](https://info.shapeshift.io/#api-104).

**Comment by wmbutler** [comment]
BTS related assets are not available from Shapeshift as of this date.
