### ISSUE TITLE
[0.5] Market resolution date for Prediction Assets GUI bug in Dark mode

### ISSUE THREAD

**Issue by iamredbar** [bitshares/bitshares-ui#2380]
**Describe the bug**
Market Resolution Date cannot be seen in GUI when creating a Prediction Market asset.

**To Reproduce**
1. Turn on Dark mode in settings
2. Go to "Assets" from hamburger menu
3. Click on "Create Asset"
4. Turn on "Smart Coin" flag
5. Turn on "Binary Prediction Market" flag
6. Click on "Description" tab
7. See issue

**Expected behavior**
This should be visible in any mode, not just light mode.

**Video**
![1](https://user-images.githubusercontent.com/16945982/50430012-0d676d80-0887-11e9-8c07-7522b18b7542.gif)

**Screenshots**
![screen shot 2018-12-25 at 8 38 10 pm](https://user-images.githubusercontent.com/16945982/50429588-0e979b00-0885-11e9-93c2-70b33b36524b.png)

**Desktop**
 - OS: High Sierra version 10.13.6
 - Desktop GUI
 - Version 2.0.181129.2062

**Additional context**
The issue does not present itself in light mode, and isn't as big of a problem in midnight mode.

**Comment by startailcoon** [comment]
Thanks for the report. Even if this isn't a big of an issue for the "ordinary user", it's not good

**Comment by MindfulMe** [comment]
@startailcoon Is there anyone assigned here? Can I submit the PR to fix the issue? Thx in advance

**Comment by MindfulMe** [comment]
I was able to reproduce the issue, I will submit PR now

**Comment by MindfulMe** [comment]
If anything we can apply the color only to the input, but I think due to the completely white color it can look bad in the future for this theme somewhere else too so please leave some feedback 🍪

**Comment by MindfulMe** [comment]
<img width="1680" alt="screen shot 2019-01-28 at 22 54 32" src="https://user-images.githubusercontent.com/26275425/51865871-3a101880-2350-11e9-978c-2bd3f43f81d6.png">

**Comment by startailcoon** [comment]
@MindfulMe we'll need a bitshares account name to pay out the Bounty of the issue. Thanks!

**Comment by MindfulMe** [comment]
@startailcoon bitshares account: mindful-me
