### ISSUE TITLE
My account can`t login

### ISSUE THREAD

**Issue by prettyCoders** [bitshares/bitshares-ui#2387]
Today! I try to login my account "bi-jie" ,But the GUI show me "Incorrect password"
![image](https://user-images.githubusercontent.com/36216120/50586151-44ef9e80-0eb3-11e9-984a-790df0e782d3.png)
I don`t know what happend! help me please!

**Comment by startailcoon** [comment]
I see your account was created by Open Ledger on 2018‎-‎04‎-‎19‎ ‎02‎:‎50‎:‎27, http://open-explorer.io/#/accounts/bi-jie

I'd avcise you to contact them directly on https://openledger.freshdesk.com/support/home and see if they can help you with your issue.
