### ISSUE TITLE
[1] Chinese version bug

### ISSUE THREAD

**Issue by 200495** [bitshares/bitshares-ui#2392]
Now I find a problem of bitshare-ui.The Chinese version of bitshare-ui can't be opened when there is claim asset fees.
![image](https://user-images.githubusercontent.com/23026128/50762379-b8285480-12a7-11e9-8e3f-7190ea07f926.png)

It can work in English version.But language change to  Chinese,the page can't be opened.
When the record doesn't have claim asset fees record,Chinese version page can be opened.But when there exist claim asset fees record,it become not to be opened.

**Comment by sschiessl-bcp** [comment]
Fixed, was translation error
