### ISSUE TITLE
[3] Add login enhancement when account is locked

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2396]
**Is your feature request related to a problem? Please describe.**
Currently if a user initiates a function while the account is locked a password is required to unlock the account to proceed which works fine, but the process could be simplified for a better user experience. For example, if a user decides to make a buy/sell (or perform any function which requires the account to be unlocked) and clicks buy/sell the login window appears (because the account has timed out and locked) but the user has to navigate to the password field, click inside, then type the password.

**Describe the solution you'd like**
Can you add a global listener if the user clicks buy/sell and the key is locked, when the login window appears because PW is required) the curser automatically defaults to the login text input so that the user can start typing?
It would pretty much apply to any case where the login window (PW) is prompted for password entry because it has timed out and the account is locked after some time.

**Comment by startailcoon** [comment]
Sounds like a reasonable request imho. We could add a `opRequest` (or similar) on the login to set the cursor to password field. 

I'd like to add that it would be a nice feature to add the amount of to auto lock the wallet as well, with security notices of course. Running on a local machine with none other accessing it, extending the logout timer would sometimes be preferred.

**Comment by TechsUsInc** [comment]
@sschiessl-bcp If you were asking me,my request is that when the login window appears (PW needed due to timeout) the cursor moves to the password field.
 I think @startailcoon defined the solution
> We could add a opRequest (or similar) on the login to set the cursor to password field.

![181212-login_3_capture](https://user-images.githubusercontent.com/18186497/51611084-f8144c00-1ee3-11e9-84e4-c04096aa5e27.JPG)
![1881212-login_1_capture](https://user-images.githubusercontent.com/18186497/51611086-f8ace280-1ee3-11e9-946c-b739e849aba5.JPG)
![181212-login_2_capture](https://user-images.githubusercontent.com/18186497/51611083-f8144c00-1ee3-11e9-99c9-307cb29fb3d6.JPG)

**Comment by TechsUsInc** [comment]
@sschiessl-bcp If you were asking me,my request is that when the login window appears (PW needed due to timeout) the cursor moves to the password field.
 I think @startailcoon defined the solution
> We could add a opRequest (or similar) on the login to set the cursor to password field.

![181212-login_3_capture](https://user-images.githubusercontent.com/18186497/51611084-f8144c00-1ee3-11e9-84e4-c04096aa5e27.JPG)
![1881212-login_1_capture](https://user-images.githubusercontent.com/18186497/51611086-f8ace280-1ee3-11e9-946c-b739e849aba5.JPG)
![181212-login_2_capture](https://user-images.githubusercontent.com/18186497/51611083-f8144c00-1ee3-11e9-99c9-307cb29fb3d6.JPG)

**Comment by sschiessl-bcp** [comment]
Yes, that is clear, any time you open login dialog with account preselected focus should be password.

What is not clear is the scope with the autolock
