### ISSUE TITLE
Year on Chart

### ISSUE THREAD

**Issue by akledirs** [bitshares/bitshares-ui#2399]
2018 is displayed instead of 2019 on the graph
![image](https://user-images.githubusercontent.com/6587277/50937574-5de4ea80-1485-11e9-958b-2808934f92c8.png)

**Comment by startailcoon** [comment]
Can't see this on my client. Must have been some issue with TradingView API.

![image](https://user-images.githubusercontent.com/12114550/51491925-37418080-1db0-11e9-89c6-2fffa3405c35.png)
