### ISSUE TITLE
[3][twksos] Replace Market Picker

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2400]
UX and comments: https://github.com/bitshares/bitshares-ui/issues/1975#issuecomment-448065737

**Comment by twksos** [comment]
request to work on this one

**Comment by gibbsfromncis** [comment]
@twksos Can you please share your experience? What are the reasons moved you to request redesign? Your experience, suggestions or troubles of usage will help us to understand the problematic and put right priorities

**Comment by twksos** [comment]
@gibbsfromncis 
If this card is for a redesign then its not for me.
I'm a full-stack developer.
I think the design has been done in #1975 and this one is for its implementation.

**Comment by gibbsfromncis** [comment]
@twksos Got it. My bad, I misunderstood you. Yep you get it correct. It is for implementation [UX from this comment](https://github.com/bitshares/bitshares-ui/issues/1975#issuecomment-448065737)

Our manager is @startailcoon. He is responsible to assign you to this task.

@startailcoon your turn.

**Comment by startailcoon** [comment]
@twksos you're welcome to work on it.

**Comment by startailcoon** [comment]
@twksos please report your progress on this task.

**Comment by twksos** [comment]
@startailcoon busy working on a game in last few weeks.
just finished up the left part (issuer may not be load at once) and created a PR.

**Comment by sschiessl-bcp** [comment]
@twksos Would you be interested to refine the "Find Markets" search in the same way?

**Comment by twksos** [comment]
@sschiessl-bcp Surely I would like to. However, my contribution time may not be stable until May 14. Could you show me the issue?

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/issues/1675
https://github.com/bitshares/bitshares-ui/issues/2544
