### ISSUE TITLE
[1.5] WSOD on asset details page

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#2403]
**Describe the bug**
White screen of death triggers when you navigate to the following pages:

https://wallet.bitshares.org/#/asset/Verthandi
https://wallet.bitshares.org/#/asset/Skuld
https://wallet.bitshares.org/#/asset/Urthr

**To Reproduce**

From a blank web tab, or from the explore asset pane, navigate directly to the asset details page for one of the 3 above bitassets.

**Expected behavior**

The asset details for the requested asset are shown.

**Screenshots**

It's a white screen, not much else to say.

**Debug logs**

```
Error: Base and Quote assets must be different
Uncaught Error: Base and Quote assets must be different
Uncaught (in promise) Error: websocket state error:3
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Client: Firefox web wallet & light client
 - Version: 181212

**Additional context**

Creating 3 bitassets as part of a three phase oscillating crypto project, they're backed by BTS and reference BTS with an oscillation modifier.

Side note, the asset explore page has 'smartcoin' as a radio button filter, but technically the 'smartcoin' terminology is reserved for the committee owned bitassets. A more neutral term would simply be 'bitasset'.

**Comment by sschiessl-bcp** [comment]
I'd have said the opposite on the wording, gnahaha

Either case, bug confirmed.

**Comment by startailcoon** [comment]
Seen the same thing on some of the older assets.
