### ISSUE TITLE
Can't Log in to account using same password as before

### ISSUE THREAD

**Issue by bert-hornback** [bitshares/bitshares-ui#2405]
Can't log in even though my password has not changed and I have used the same password in fact I made a deposit to crypoto bridge exchange and  access2 minutes later I tried to log in with same password and it said incorrect password  can some one please help with this there must be a bug in the system because the password worked 2 minutes earlier I was sent to  https://wallet.bitshares.org/ and still could not log in with same password

 log: asdasd
log: fetchTradingPairs error from https://gateway.winex.pro/api/v0/ol/support/trading-pairs: TypeError: Failed to fetch
log: asdasd
log: fetchCoins error from https://gateway.winex.pro/api/v0/ol/support/coins: TypeError: Failed to fetch
log: asdasd
log: error fetching blocktrades active walletsTypeError: Failed to fetchhttps://gateway.winex.pro/api/v0/ol/support/active-wallets
log: asdasd
error: TypeError: Cannot read property 'password_pubkey' of null
log: Switching to InRam storage for private session
log: asdasd
error: TypeError: Cannot read property 'password_pubkey' of null
log: asdasd
error: TypeError: Cannot read property 'password_pubkey' of null
log: asdasd
error: TypeError: Cannot read property 'password_pubkey' of null
log: asdasd
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: asdasd
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: asdasd

**Comment by grctest** [comment]
Are you using the cloud login, or the 'bin' file login mechanism? Are you logging into the same interface which you registered on?

**Comment by bert-hornback** [comment]
Just got it to work I'm logged in
