### ISSUE TITLE
Quantity discrepancy

### ISSUE THREAD

**Issue by dmarks2061** [bitshares/bitshares-ui#2415]
I've been away during the crypto winter, and just reconnected. 
There is a small discrepancy in total BTS shown (4981.14) and what I have in my records (4983.7)
Has there been a change, or a charge, since last I looked? Please advise.

**Comment by startailcoon** [comment]
Does the public explorers say the same thing, for example on http://open-explorer.io/#/accounts/{your-account-name}.

You need to give an account name, but it would be impossible to say the reason for the discrepancy if that says the same thing. If your records does match the explorer, then we need to take a look at the UI.

**Comment by startailcoon** [comment]
You mention your balance is `4980`, which is the BTS value of your assets. As your portfolio consists of three asset types (BTS, SEED and BADCOIN) this is the reason of the value change you mention. As these other assets decrease in value against BTS, your portfolio decreases in value as well.

Your portfolio still consists of the same amount in the three assets, as no transactions have been made, just their values against BTS have changed.

I hope this makes it more clear for you.

**Comment by dmarks2061** [comment]
It does, STC, thanks. I don't understand it fully, but it IS clearer.
But I didn't have any choice in SEED & BADCOIN; I didn't order them. So it's a little scary that the system automatically gave me those coins and debited my BTS balance. You say that's normal, so I guess I'll accept it (it DOES make life a little easier).
(If I wanted to pursue this, I'd question why those 2 xactions occurred last March & April and I saw the reduction of 1.14BTS last weekend. I don't know what to do about it though so, like I said, I'll accept it for now)
Thank you for helping me with this.
M___

    On Tuesday, January 22, 2019, 2:03:52 PM CST, startailcoon <notifications@github.com> wrote:  
 
 
You mention your balance is 4980, which is the BTS value of your assets. As your portfolio consists of three asset types (BTS, SEED and BADCOIN) this is the reason of the value change you mention. As these other assets decrease in value against BTS, your portfolio decreases in value as well.

Your portfolio still consists of the same amount in the three assets, as no transactions have been made, just their values against BTS have changed.

I hope this makes it more clear for you.

**Comment by sschiessl-bcp** [comment]
> What I DO object to is that they can charge me a fee when I didn't authorize the exchange.

That might be due to poor UX. The fee is always paid by the account that triggered the action. In that case, the sender of the transfer paid the fee, not you.

**Comment by startailcoon** [comment]
Nothing really changed during the time you where gone. The "fee" you see is the transaction fee, which was paid by the sender, not the receiver. 

Your account always had the exact same amount of BTS, your two deposits, for the entire time. Then someone sent you BADCOIN and SEED, which was also always the same amount during the entire time.

What does confuse you though, is the way the wallet display the "wallet value". This is always done in one type of asset, in your case this is BTS. This means that it needs to "estimate" the value of SEED and BADCOIN to BTS, and that can change as people trade with them. The "wallet value" has always been:
 `BTS Value` + `SEED * BTS Exchange  Price` + `BAADCOIN * BTS Exchange Price`

**Comment by dmarks2061** [comment]
OK. Thank you for the explanation. Can I opt out of receiving "free" coins?
(Really, I had a different value initially. Something got subtracted from my BTS value. Possibly the value of SEED & BADCOIN diminished total supply. If so I'd rather not receive them! I accept your idea of faulty UI more than this one, but I see no real choices in the matter. I WOULD like to make sure my possibly imaginary deductions don't happen again, so if there's a way to opt out I would exercise it. Unfortunately, due to the crypto winter I never increased my supply of BTS and so do not have enough to even sell what I have. It does not make sense at this time to incur fees by sending more BTC to buy enough BTS to liquidate the position. Hopefully, someday, there will be another chance to work with your coin more.)
Thank you,
M___

    On Tuesday, January 29, 2019, 12:51:17 PM CST, startailcoon <notifications@github.com> wrote:  
 
 
Nothing really changed during the time you where gone. The "fee" you see is the transaction fee, which was paid by the sender, not the receiver.

Your account always had the exact same amount of BTS, your two deposits, for the entire time. Then someone sent you BADCOIN and SEED, which was also always the same amount during the entire time.

What does confuse you though, is the way the wallet display the "wallet value". This is always done in one type of asset, in your case this is BTS. This means that it needs to "estimate" the value of SEED and BADCOIN to BTS, and that can change as people trade with them. The "wallet value" has always been:
BTS Value + SEED * BTS Exchange Price + BAADCOIN * BTS Exchange Price

**Comment by sschiessl-bcp** [comment]
Opting out of free coins is not possible, as you receive them via transfer operation. 

You can however burn those tokens in the asset overview, they will disappear then.

**Comment by dmarks2061** [comment]
I see that you have closed this ticket, and that will be fine with me. But I don't think you understand what I'm trying to communicate. Just knowing I haven't been heard is the main reason why I persist.
I am not complaining about a drop in value; that's happened with every coin since 2017. My point is that I bought 4983.7BTS in the summer of 2017. The amount had dropped to 4981.14BTS when I started this ticket 20 days ago. That's a discrepancy of 2.56BTS. I currently show 4980.42BTS. I NEVER "SPENT" A SINGLE BTS!! (until I sold the "free" coins recently) So why did my total BTS decrease initially?
It has nothing to do with value. The amounts are minuscule. It's the principle behind your actions. It might be, as previously suggested, that I somehow paid the fees for receiving free coins. That's not right. The fact that this can happen with your coin and, further, that no one associated with Bitshares is willing to do anything constructive about it, only assures I will not put any more money into your project. Nor would I recommend your coin to any potential investors.
As long as all that is understood and you're willing to accept it, that really says it all. This may well be my final communication. Thank you for your time and consideration.
Mark


    On Thursday, February 7, 2019, 6:27:09 AM CST, Stefan Schießl <notifications@github.com> wrote:  
 
 
Opting out of free coins is not possible, as you receive them via transfer operation.

You can however burn those tokens in the asset overview, they will disappear then.

**Comment by sschiessl-bcp** [comment]
No one took anything from your account.

I looked in it:
- You received 4,980 BTS through poloniex
- You sold the free tokens for some gain
- You bought and sold BTC, incurring a small loss

Please note that every action on the blockchain costs a small transaction fee as well. Currently you hold 4,980.42 BTS.

Just receiving free token does not decrease your BTS amount.

**Comment by sschiessl-bcp** [comment]
> The fact that this can happen with your coin and, further, that no one associated with Bitshares is willing to do anything constructive about it, only assures I will not put any more money into your project. Nor would I recommend your coin to any potential investors.

This statement has not been true

> It might be, as previously suggested, that I somehow paid the fees for receiving free coins.

If you don't actively use your account the total amount of BTS will not change, and NO one can do anything about that. No airdrop, no block producer, no nothing. Please watch your account and observe that your amount of BTS will not change.

**Comment by dmarks2061** [comment]
OK. Thank you for more detail.
On the BTS blockchain explorer I see two transactions on 10/10/2017 for 85BTS (to test) and 4895BTS for a total of 4980 from poloniex. Perhaps this discrepancy is fees charged from poloniex to transfer the coins (4983.7-4980=3.7BTS).
I appreciate you hammering my head till I got this far, and retract my derogatory comments. Thank you, Stefan.
M___


    On Friday, February 8, 2019, 9:07:48 AM CST, Stefan Schießl <notifications@github.com> wrote:  
 
 

The fact that this can happen with your coin and, further, that no one associated with Bitshares is willing to do anything constructive about it, only assures I will not put any more money into your project. Nor would I recommend your coin to any potential investors.


This statement has not been true


It might be, as previously suggested, that I somehow paid the fees for receiving free coins.


If you don't actively use your account the total amount of BTS will not change, and NO one can do anything about that. No airdrop, no block producer, no nothing. Please watch your account and observe that your amount of BTS will not change.
