### ISSUE TITLE
[4][frooze] Maintain German language

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2426]
Issue birthed from #1705 for german language

**Comment by froooze** [comment]
Are the language files updated?
Should I download the source again?

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/pull/2427

**Comment by sschiessl-bcp** [comment]
In general the german translation is very weird and would need a complete overhaul IMO

**Comment by froooze** [comment]
What do you think is weird? Maybe you are used the English word and don't expect the German version?
Found two errors in line 452 and 1896. Updated the file.

**Comment by sschiessl-bcp** [comment]
Where did you adjust those errors? In transifex? The PR is merged and this issue is closed.

**Comment by froooze** [comment]
I changed only the transifex file.

**Comment by sschiessl-bcp** [comment]
We have reviewed the work and also the extent of it and can offer a bounty of 9 (1125 bitUSD).

The limits of this task were given in the original issue, which was rated with 10. We have switched how the hours are distributed since then, apologies for not being precise in the formulation. The key comment [is this one](https://github.com/bitshares/bitshares-ui/issues/1705#issuecomment-421388431). I hope this is a good compromise for you.

**Comment by clockworkgr** [comment]
@froooze I will need your BTS account for payment

**Comment by froooze** [comment]
@clockworkgr: Can I DM you the next days?

**Comment by clockworkgr** [comment]
sure...
