### ISSUE TITLE
How do I import an account created using a private chain

### ISSUE THREAD

**Issue by xiaolujidan** [bitshares/bitshares-ui#2433]
### Set up the chain of private
```
suggest_brain_key

Create a private key

*** create account ***
register_account alpha BTS5s2iBiMeaCt96hoiAhQz94AqiPChTNF2YpYt6zJNNFJonhXPTF BTS5s2iBiMeaCt96hoiAhQz94AqiPChTNF2YpYt6zJNNFJonhXPTF nathan nathan 0 true

```

Connect to private chain nodes using the latest bitshares

**Comment by clockworkgr** [comment]
I am not entirely sure what you mean?

Did you create an account using the cli_wallet and want to use it with the web UI?

**Comment by xiaolujidan** [comment]
I connect my private chain.But I can't create an account directly
I guess it's because there's no tap.
How to configure the faucet of illicit catenary.

**Comment by sschiessl-bcp** [comment]
Faucet is an external service that allows account creation. Tapin is one example of an open source implementation of a faucet.

If you need one for a private chain and want as little hassle as possible, you can also contact BitShares.eu and use their services.
