### ISSUE TITLE
Staging testing - Borrow spotlight login prompt

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#2438]
**Describe the bug**

When not logged into the staging client, you can go through the 'Collateralized Debt Position' wizard & click 'Borrow -> Update Position' without getting a login prompt, instead it causes an error in the console.

**To Reproduce**

* Launch the staging client version 'BitShares.190207-rc2'.
* Navigate to the 'Collateralized Debt Position' spotlight wizard
* Proceed through the steps
* Without being logged in, click 'Borrow -> Update Position'

See console warning: `TypeError: this.state.wallet is null`

**Expected behavior**

Get asked to login to the client before proceeding.

**Desktop (please complete the following information):**
Windows, Firefox, BitShares.190207-rc2

**Additional context**

N/A

**Comment by sschiessl-bcp** [comment]
Can you specify OS/Browser version please

**Comment by grctest** [comment]
Windows 10 64bit
Firefox 66.0b4 (64-bit)

**Comment by grctest** [comment]
```
TypeError: this.state.wallet is null[Learn More] app.76e1908f2317e5101327.js:1:14180
    value app.76e1908f2317e5101327.js:1
    value (index):978
    value app.76e1908f2317e5101327.js:1
    value (index):974
    handleClick vendor.9ea7f4a010dba124a569.js:132
    invokeGuardedCallback vendor.9ea7f4a010dba124a569.js:148
    invokeGuardedCallback vendor.9ea7f4a010dba124a569.js:148
    invokeGuardedCallbackAndCatchFirstError vendor.9ea7f4a010dba124a569.js:148
    B vendor.9ea7f4a010dba124a569.js:148
    P vendor.9ea7f4a010dba124a569.js:148
    L vendor.9ea7f4a010dba124a569.js:148
    T vendor.9ea7f4a010dba124a569.js:148
    F vendor.9ea7f4a010dba124a569.js:148
    D vendor.9ea7f4a010dba124a569.js:148
    On vendor.9ea7f4a010dba124a569.js:148
    Za vendor.9ea7f4a010dba124a569.js:148
    Je vendor.9ea7f4a010dba124a569.js:148
    zn vendor.9ea7f4a010dba124a569.js:148
    ns vendor.9ea7f4a010dba124a569.js:148
    Ln vendor.9ea7f4a010dba124a569.js:148
    Ln (index):1018
```

**Comment by sschiessl-bcp** [comment]
Can't reproduce anymore ... 0.25 for investigations.
