### ISSUE TITLE
Can not register account

### ISSUE THREAD

**Issue by rokii666** [bitshares/bitshares-ui#2441]
Can not register account, dots gif just keeps rolling and nothing happens.
Fresh install Bitshares on Windows.
![camphoto_758783491](https://user-images.githubusercontent.com/11616598/52227221-9aa2d680-28b7-11e9-816f-f73864622bac.JPG)

**Comment by xiaolujidan** [comment]
![image](https://user-images.githubusercontent.com/41559541/52570398-4a46ee00-2e4e-11e9-9d79-17d9596c9112.png)

This is regarded as registered success

**Comment by clockworkgr** [comment]
@rokii666  Can you check if this happens on the latest release? https://github.com/bitshares/bitshares-ui/releases/tag/2.0.181212

**Comment by xiaolujidan** [comment]
This page cannot be clicked
![image](https://user-images.githubusercontent.com/41559541/52770092-21507400-306d-11e9-88ae-9b229993c3ab.png)

**Comment by xiaolujidan** [comment]
can't click on the page，
![image](https://user-images.githubusercontent.com/41559541/52770092-21507400-306d-11e9-88ae-9b229993c3ab.png)
This bug appears in an endless loop
![image](https://user-images.githubusercontent.com/41559541/52770202-6ecce100-306d-11e9-952b-6df330c89929.png)

**Comment by rokii666** [comment]
> @rokii666 Can you check if this happens on the latest release? https://github.com/bitshares/bitshares-ui/releases/tag/2.0.181212

I tried on online wallet.bitshares.org with success. I wonder why I can not find link on the wallet on main page bitshares.org. It was there I remember.

**Comment by startailcoon** [comment]
No new updates in 30 Days by reporter. No second cases reported. Closing
