### ISSUE TITLE
Cannot send BTS with filled memo in develop branch

### ISSUE THREAD

**Issue by szechem** [bitshares/bitshares-ui#2443]
1. Bug is possible with develop branch. It is not possible to send BTS with filled memo.

2. Go to send, type memo, fill 'to' and 'quantity' fields and click 'send'.

3. In console you will get 'Cannot read property 'transfer_op' of undefined'.

4.
 - Ubuntu 16.04 LTS
 - Chrome 70.0.3538.110

**Comment by sschiessl-bcp** [comment]
Please try again

**Comment by szechem** [comment]
![errors](https://user-images.githubusercontent.com/24317158/52569859-69278f00-2e12-11e9-9cd3-600240d3bdc9.png)

**Comment by szechem** [comment]
I have got new develop branch built and errors are like on above screenshot.

**Comment by szechem** [comment]
This error is only if memo is filled.

**Comment by sschiessl-bcp** [comment]
Does it work with the new send modal?

**Comment by szechem** [comment]
No, problem is with ApplicationApi.js.

If I change (lines 143-145):

```
if (propose_account) {
    chain_propose_account = chain_memo_sender;
}
```
to
```
if (memo_sender_account) {
    chain_propose_account = chain_memo_sender;
}
```
it works.
In line 116 there is:
`propose_account = null, // should be called memo_sender, but is not for compatibility reasons with transfer. Is set to "from_account" for non proposals`, maybe it is not solved

**Comment by sschiessl-bcp** [comment]
Fixed with https://github.com/bitshares/bitshares-ui/commit/ce6e415a79a64a3996c65d698e2d81e8302aba6f
