### ISSUE TITLE
Send asset operation - Inoperable  

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2444]
**Describe the bug**
TX failed on both send and legacy send operation.

**To Reproduce**
1. Go to Hamburger menu
2. Click on send or legacy send (tried both - failures were identical)
3. When the Send window pops up, input the from, to, quantity, and memo fields then click send
4. Enter password if account is locked
5. Click Confirm
6. See errors; The to, quantity, and memo inputs purge while the from field remains. TX fails without 
   warning or completion

**Expected behavior**
Able to send (or send legacy) asset to another account.
Able to send a memo to another account.
Warning if error
Was not an issue in previous release.

![2 0 190207-rc2_send_1_capture](https://user-images.githubusercontent.com/18186497/52519924-b516e000-2c28-11e9-8af7-76eea9dbb823.JPG)
![2 0 190207-rc2_legsend_3_capture](https://user-images.githubusercontent.com/18186497/52519928-bf38de80-2c28-11e9-8c19-e50959290cf8.JPG)
![2 0 190207-rc2_legsend_2_capture](https://user-images.githubusercontent.com/18186497/52519929-c52ebf80-2c28-11e9-96f7-fcf1dc8ab5a9.JPG)
![2 0 190207-rc2_legsend_1_capture](https://user-images.githubusercontent.com/18186497/52519931-c9f37380-2c28-11e9-9cf0-c9193f6e5002.JPG)

**Desktop (please complete the following information):**
 - OS: Windows, Version: 8.1 (Primary)
   Windows, Version 10

 - Browser: Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - Confirmed with secondary browser: Opera 56.0.3051.116 (Primary)

  - Version 2.0.190207-rc2

**Comment by sschiessl-bcp** [comment]
Resolved in staging
