### ISSUE TITLE
New Deposit / Withdraw modal u/s

### ISSUE THREAD

**Issue by hot-bit-git** [bitshares/bitshares-ui#2446]
**Describe the bug**
Unable to withdraw funds using **new modal** while **legacy modal** still (in some cases) works. Proper gateway is not displayed, despite funds being available in the account.

**To Reproduce**
1. Go to 'Menu'
2. Click on 'Withdraw'
3. Choose Asset 'STEEM'

Probably only open.STEEM  is possible to choose
Message about  dysfunctional OpenLedger  gateway is displayed
Unable to find RUDEX gateway service

**Expected behavior**
1. Account available STEEM assets (i.e rudex.STEEM, open.STEEM) are displayed if balances greater than zero
2. Proper gateways are available (i.e RUDEX, OPENLEDGER) 

**Screenshots**

![gateways](https://user-images.githubusercontent.com/35734693/52536710-0a044480-2d56-11e9-87f9-1d1efee27052.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser firefox 
 - Version 181031

**Comment by sschiessl-bcp** [comment]
Can you reproduce this on staging.wallet.org?

**Comment by startailcoon** [comment]
Part of the following two issues
- https://github.com/bitshares/bitshares-ui/issues/1771, Gateway/Bridge Codebase Enhancements
- https://github.com/bitshares/bitshares-ui/issues/1872, Gateway Modal ANT Implementation

There are a number of weird issues that I will look over to hunt down. Some asses are missing on the new modal, while they are still visible in the old section, while some are missing even though they shouldn't.

Any reports in this issue would be included in my work on this.

**Comment by startailcoon** [comment]
Fixed as part of #1872
