### ISSUE TITLE
[8] Automate Light Wallet Build Process

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#245]
Light Wallets for Linux, Mac, WIndows need to be built automatically and posted to the download site automatically. This issue is critical to rapid delivery of our client.

**Comment by landry314** [comment]
The sha256 for the recent Aug 29 release for Mac OS on https://bitshares.org/download/ is not correct.

If automatic build system is implemented it needs to also update the shasums along with the builds.

**Comment by wmbutler** [comment]
We need to automate the builds for all three binaries and the web wallet:

- [ ] Web
- [ ] Windows
- [ ] Linux
- [ ] OS X

This task will be considered complete when the creation and posting of all wallets is handled by a single turn key operation. It has been placed into the 100914 Milestone.

**Comment by wmbutler** [comment]
Duplicate #224
