### ISSUE TITLE
BSIP58 activated on bitCNY

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2451]
**BSIP58: Global Settlement Protection Through Price Feeding**, has been voted through on bitCNY by the community. We should investigate what changes the UI need to handle these changes.

BSIP-58 details -> https://github.com/bitshares/bsips/blob/master/bsip-0058.md
Converstaion thread -> https://bitsharestalk.org/index.php?topic=27753.0

## Poll Results
poll worker|proposal|votes
-|-|-
1.14.160|Poll-BSIP58-Global Settlement Protection on bitCNY|345M 
1.14.161|Poll-BSIP58-No Global Settlement Protection on bitCNY|17M

**Comment by sschiessl-bcp** [comment]
No change necessary, global settlement won't occur
