### ISSUE TITLE
Spotlight Barter - Real time balance validation issues

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2461]
**Describe the bug**
Using Spotlight Barter, it is possible to enter multiple assets of the same kind and quantity because the balance does not validate the assets as they are added to the barter. In this case, the proposal is approved but not executed. The Blockchain does not update with a canceled or failed execution. Understood off chain variance. 

**To Reproduce**
1. Go toSpotlight
2. Click on barter
3. Scroll down to Bartering Asset
4. Select an asset with sufficient quantity (i.e. BTS) and enter an amount (i.e. 20 BTS)
5. Click on +add Asset
6. Select the same asset (i.e. BTS) and enter an amount (i.e. 20 BTS)
7. See error with asset balance (BTS) is not subtracted from either asset assigned to barter.
8. See error when use max asset is clicked - does not auto input max available.

**Expected behavior**
I first thought the easiest way to resolve this would be to disable the ability to include the same asset more than once. But, there are user situations where that may be a necessity (i.e. invoice or records, memos or notes, etc). With that said, the balance would need to validate each time to reflect a correct balance. Also, note that the fees vary. While this proposal failed to execute, the fees were still applied (on a LTM account). I'm assuming it will rectify after 24hrs  Waiting to see. *Update* Proposal canceled (assuming timed out) before 20 hours elapsed. 

**Screenshots**
![190207-rc3_barter_2_capture](https://user-images.githubusercontent.com/18186497/52901710-78b92600-31cc-11e9-8970-f395dc9d184e.JPG)
The screenshot above was not executed in the included operation
![190207-rc3_barter_3_capture](https://user-images.githubusercontent.com/18186497/52901711-78b92600-31cc-11e9-957f-8fd30b0174c8.JPG)
![190207-rc3_barter_4_capture](https://user-images.githubusercontent.com/18186497/52901712-78b92600-31cc-11e9-978b-74021b0d0c3e.JPG)
Above P2P Proposal; Peer 1 with memo, Peer 2 with memo, plus escrow 

**Desktop (please complete the following information):**
 - OS: Windows, Version: 8.1
 - Browser Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600

**Comment by clockworkgr** [comment]
This is expected behaviour (sort of).

A proposal is only evaluated on execution if approved. You have every right to create a proposal with insufficient balances and ensure they're sufficient at time of execution.

However, I guess we could "tag" the potentially failing operations of the TX somehow as a UX hint.

@gibbsfromncis / @sschiessl-bcp ?

**Comment by sschiessl-bcp** [comment]
Agree with the notion
