### ISSUE TITLE
Spotlight Barter - Peer 2 memo

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2462]
**Describe the bug**
Peer 1 is able to create and edit a memo.
Peer 2 does not have the ability to create/edit a memo prior to approving a proposal.

**To Reproduce**
1. Go to Hamburger menu
2. Click on Spotlight
3. Click on Barter
4. Enter the info for Peer 1 with memo and Peer 2 with memo
5. Submit proposal
6. Switch to Peer 2 account
7. Click Dashboard
8. Click Proposed Transactions (should have a number next to it)
9. Note error of in-ability to respond to Peer 1 with a memo. 
10.Note Peer 2 memo is readable if account is unlocked.
11. Note that Peer 2 memo was written by Peer 1, not Peer 2

**Expected behavior**
All Peers able to respond to a proposal with a memo (or multiple memos) without having to approve the proposal first. Considering that this is basically a P2P transaction, and other means of communication may not be available or known, several memo's may be required between the 2 Peers (and escrow).

One Peer unable to edit another Peers memo but all Peers involved able to read all memo's.

![190207-rc3_barter_2_2_capture](https://user-images.githubusercontent.com/18186497/52903561-d48fa900-31e4-11e9-8aba-d8a291760daf.jpg)

**Desktop:**
 - OS:Windows 8.1
 - Browser Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - 2.190207-rc3

**Comment by clockworkgr** [comment]
What you are suggesting is not possible.

An on-chain proposal is fixed at time of submission to the chain. Memos are part of the ops contained in the TX proposal.

They cannot be modified after the fact.  A counter-offer would take the form of rejecting the proposal and creating a new one with the new suggested terms.

Again, this could be handled on a UX level by offering the ability for a user to "clone" an incoming proposal's ops and modify them prior to submitting as a one-button feature.

@gibbsfromncis  / @sschiessl-bcp  / @startailcoon  ?

**Comment by sschiessl-bcp** [comment]
Yes, there will be a new panel that shows barter proposal with a nice UX within the spotlight, just not formulated as an issue yet. This could include "Counter offer", which automatically (permanently) rejects the current barter.
