### ISSUE TITLE
Spotlight Barter - fair trade procedure

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2463]
**Describe the bug**
To ensure a better user experience, and taking into account that any user may not know how or where to find a reliable means of crypto conversion of assets to make an informed decision. For example, Peer One could offer to trade Peer Two 0.001 BTS for 2 BTS.  

**To Reproduce**
1. Go to Hamburger menu
2. Click on Spotlight
3. Click on Barter
4. Scroll down to Peer 1 assets and choose 1
5. Scroll over to Peer 2 assets and choose 1
5. See error of not knowing a fair and equitable trade.

**Expected behavior**
A warning, alert, or way of ensuring a fair trade. It would be nice if both Peers values would turn green when they are a fair trade as they are increased/decreased decimally. 

**Desktop :**
 - OS:Windows 8.1
 - Browser: Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - 2.190207-rc3

**Additional context**
Ideally and long term solution is a crypto converter/calculator specific to the DEX assets that the user can pull up from anywhere within the DEX.
A secondary option could be to simply show (on the Barter page) the real time price of BTS in USD for reference, then show the real time price of the alternate assets in the barter equivalent in BTS for reference.
I am assuming that one Peer is usually going to benefit from the barter, but a point of reference could help lessen the sting.

**Comment by clockworkgr** [comment]
Although I understand your reasoning, I think this might be too much work/overprotection of the users.

I'd assume a user gets into a barter agreement as a SECONDARY option because he can't get a better price or enough liquidity for the amount to be traded.

@startailcoon  thoughts?

**Comment by sschiessl-bcp** [comment]
This is intentionally not done (I initially had the price of the barter included) because scam assets have a easily manipulated price feed that would give false security to the user.
