### ISSUE TITLE
Spotlight Collateral Debt Position - Assets list issues

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2464]
**Describe the bug**
From within the Spotlight Collateral Debt Position;
1. clicking the asset list populates assets which the user may _not_ be a holder of or has a zero balance.
2. Clicking the asset list excludes assets which the user may **be** a holder of or has more than a zero 
   balance. When this is the case, the user must navigate to the Exchange tab for a applicable asset, then 
   click borrow to access the margin position.
**Additional context**
3. The a-for-mentioned # 2 above is true for the Margin page (from within Dashboard) as well.

**To Reproduce**
1. Go to the _Hamburger Menu_
2. Click on _Collateralized Debt Position_ 
3. Click _get started_
4. Click _next_ 3 times followed by _Let's do it!_
5. Scroll down and click on _select an asset_
6. See error that not all assets which can be borrowed against are listed.
7. See error that user may not be a holder of all listed assets or has a zero balance in one or more.
8. See error when use max available balance is clicked - does not auto input max available balance of 
   asset.

**Expected behavior**
The Spotlight Collateralized Debt Position should clarify a list of applicable assets for a better user experience and informed decision making;
1. Zero balance or non-holder grayed out or not listed at all.
2. User held assets with a positive balance with a green hue or listed only.
3.Last resort option; Only list user held assets with a positive balance.

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - Version: 2.190207-rc3

**Comment by clockworkgr** [comment]
Spotlight section can't really show ALL MPAs...

a) Too many

b) Spotlight transfers some degree of trust/legitimacy to the assets showcased. As we have no control over 3rd party MPAs, we should not list them

The proper way is to only show bitAssets (committee-issued ones) but even those, some are inactive (e.g. bitOIL) so a selection needs to be made. I believe the current list is enough. 

@sschiessl-bcp ?

**Comment by sschiessl-bcp** [comment]
Similar to #2465, agree to Alex. The list is hardcoded.

**Comment by sschiessl-bcp** [comment]
Restricted to commonly known bitassests. Might be worth to re-evaluate in the future

**Comment by sschiessl-bcp** [comment]
Hours 0.75
