### ISSUE TITLE
Dashboard Margin Position tab - Asset list 

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2465]
**Describe the bug**
From within the Dashboard Margin Position Tab;
1. Assets populated exclude assets which _can not_ be borrowed against unless accessed via the Exchange Tab using the Borrow Button.
2. Assets populated include assets which the user may not be a holder of or has a zero balance.

**To Reproduce**
1. Go to Dashboard
2. Click on Margin Positions
3. See error that _not all_ assets which can be marginally positioned are listed.

**Expected behavior**
All assets listed that can be borrowed against.

**Desktop :**
 - OS: Windows 8.1 
 - Browser Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - Version 2.190207-rc3

**Additional comments**
Didn't we have a global settlement warning on the Margin Positions tab??
Disregard additional comment - I see the icon now.

**Comment by clockworkgr** [comment]
Hmmm...good point

I'm not sure where/how that list is initialized.

My suggestion would be to ONLY show actual positiosn there (only what you've borrowed).

@sschiessl-bcp ?

**Comment by sschiessl-bcp** [comment]
The list that is always shown is hardcoded and contains the committee-owned SmartCoins. This is intended, extension could be discussed (or possible to add a "More"/"Search" button or similar)

**Comment by clockworkgr** [comment]
> The list that is always shown is hardcoded and contains the committee-owned SmartCoins. This is intended, extension could be discussed (or possible to add a "More"/"Search" button or similar)

I know, but as mentioned in the referenced issue, it does not include ALL committee-owned MPAs. What's the selection filter?

**Comment by sschiessl-bcp** [comment]
> What's the selection filter?

Arbitrary I suppose (copy & paste **shame**)

**Comment by sschiessl-bcp** [comment]
Restricted to commonly known bitassests. Might be worth to re-evaluate in the future

**Comment by sschiessl-bcp** [comment]
Hours only for #2465
