### ISSUE TITLE
Spotlight Collateralized Position Tab - Navigation

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2466]
**Describe the bug**
From within the Spotlight Collateralized Debt Position Wizard, navigation can get lost with the arrow keys. (up/down) emulates left/right. 

**To Reproduce**
1. Go to Hamburger Menu
2. Click on Spotlight
3. Click on Collateralized Debt Position
4. See error when navigating through the wizard with up/down and left/right arrow keys.
    (Up/right navigates the wizard forward; Down/left navigates the wizard backward
5. See error of being able to select an asset (which the user may/may not hold and/or may/may not have 
   a positive balance)
6. See error of then being able to click borrow
    **Note that currently a zero balance does appear in the next window if borrow is clicked**

**Expected behavior**
Consider adding listener; if up/down arrow keys pressed, scroll page up/down. If left/right arrow keys pressed, changes wizard page forward or backwards.

**Desktop :**
 - OS: Windows 8.1
 - Browser: Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - Version 2.190207-rc3

**Additional context**
Borrow screen opens if borrow button is clicked without even selecting an asset.

**Comment by sschiessl-bcp** [comment]
> 6\. Note that currently a zero balance does appear in the next window if borrow is clicked

This is intended, you are allowed to create new margins there. I streamlined which assets have been shown and fixed the navigation.
