### ISSUE TITLE
Send or Legacy send tab - rename to Proposal or Send tab

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2467]
**Is your feature request related to a problem? Please describe.**
Proposals can be accessed from the Spotlight Wizard. 
Proposals can also be accessed from the Send or Legacy send tab.
The Send or Legacy send tab could easily be renamed for clarity and easy navigation.

**Describe the solution you'd like**
Consider renaming (Send or Legacy Send) for a better user experience to (Proposal or Send) .

**Describe alternatives you've considered**
Keeping the send or legacy send tab (but renamed to propose or send tab) provides a secondary method of proposing or sending for users not aware of the Spotlight CDP Wizard.

**Additional context**
Using the CDP Wizard only would free up real estate on the Hamburger menu.

**Comment by startailcoon** [comment]
I understand what your idea is here, but proposals aren't just for send operations, they can be applied to any kind of operation. Renaming Send to include proposal isn't nessesary in my opinion, as it should always be possible to do a proposal.

**Comment by TechsUsInc** [comment]
@startailcoon 
I think we are in agreement here. Basically, I'm suggesting the rename to bring more attention to both sending and (if not more) proposing as opposed to sending and sending (current logical comprehension). Propose, Send, and Spotlight Barter are all unique in usage as well as data captured. The data in Send is not necessarily represented in Propose or Barter (i.e. Recent Activity).

**Comment by clockworkgr** [comment]
This would just cause more confusion IMHO.

Spotlight is for showcasing features to new users and providing a slightly better UX.

The option to make ANY operation a proposal is just a feature of any operation (including send) and should not describe or overshadow the operation itself
