### ISSUE TITLE
[0.5] Withdraw or legacy withdraw operation - inoperable

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2468]
**Describe the bug**
Withdraw or Legacy Withdraw operation is inoperable.

**To Reproduce**
1. Go to Hamburger Menu
2. Click Withdraw and/or Legacy Withdraw
3. See error- inoperable- no response

**Expected behavior**
Withdraw or Legacy Withdraw to operate.

**Desktop :**
 - OS: Windows 8.1
 - Browser Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - Version 2.190207-rc3

**Comment by clockworkgr** [comment]
Can duplicate on chrome...new modals appear inoperable

**Comment by startailcoon** [comment]
For the record, I used wallet.bitshares.org today to withdraw some assets, and it worked just as expected. None the less, I will investigate. It could very well be due to an asset or some holdings of the account used that breaks the app.

Any logs when these errors occur would be appreciated.

**Comment by clockworkgr** [comment]
works for me on wallet. doesn't work on develop.

**Comment by startailcoon** [comment]
k, will investigate

**Comment by sschiessl-bcp** [comment]
Done through PR
