### ISSUE TITLE
[0.5] Deposit operation - inoperable

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2469]
**Describe the bug**
Deposit tab is inoperable.

**To Reproduce**
1. Go the Hamburger Menu
2. Click Deposit
3. See error of no response - inoperable

**Expected behavior**
Clicking Deposit opens the Deposit menu.

**Desktop :**
 - OS: Windows 8.1
 - Browser Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - Version 2.1902097-rc3

**Additional context**
Clicking _Legacy Deposit_ redirects to the Deposit menu.

**Comment by startailcoon** [comment]
Thanks for the report. Added to the Epic of Improving usability of Gateway/Bridges.

**Comment by sschiessl-bcp** [comment]
Can you clarify @startailcoon ? Does the deposit modal not work currently?

**Comment by sschiessl-bcp** [comment]
Done through PR
