### ISSUE TITLE
Create Better System to Decide Which Assets are in Account --> Balances

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#247]
Currently the assets in the Balances list are decided for us and, yes, we can hide what we don't need but they change seemingly randomly and we can not add other assets that we want fixed in there regardless of if we own them currently. The assets that are fixed are chosen for us unless we unhide them.

I suggest a rehaul of the Balances system where ANY asset can be fixed into the list and any asset can be removed (not just hidden) until put back. The idea that we need "Hidden Assets" seems useless to me and so does the need to count them (see issue #220). I suggest eliminating hidden assets altogether and just have an "Add Fixed Asset" feature and make the red X just remove the asset until added again.

Of course, if any amount of an asset is currently owned then it would have to appear but not have a red X because it can't be removed until it is sold.

I have wanted to add bitCNY permanently many times because when I currently didn't have any and I wanted to borrow some I would need to find an exchange that included it and then click borrow there. I need to borrow bitCNY or bitUSD quite often so it would be helpful to always have them in my Balances regardless of if I currently owned any. I would like to choose this.

Inversely, I have never wanted MAID coin but it has always been there (yes, I can hide it, I know, but still). Who decides which coins are there by default and why?

Also, while you are there, consider adding any of the ideas in issue #67 as well! ;-)

**Comment by wmbutler** [comment]
While I agree that you may want to have certain assets available whether you own them or not, I think they deserve to be in a heading other than "Balances". Let's face it, balances are indeed balances. Seems to me that we should always show an asset under the balance heading if you own it.

Seems to me that there should be another area to create a portfolio or watchlist with a custom name where you could add and track currencies. I'll leave this open for discussion.

**Comment by landry314** [comment]
I agree, @wmbutler, it is called Balances and should only hold balances.

Therefore, below it and above "Open orders" let's create a new category called "Favorite Assets" or "Followed Assets" or something like that where the user can choose which coins and bitassets he wants to keep easy access too. Instead of the current system of having some default coins placed in Balances and allowing them to be hidden, let's place those coins in this new category and allow them to be deleted and other coins/assets to be added. Wouldn't that be nice? :-)

Doing this would immediately also resolve issue #220.

**Comment by wmbutler** [comment]
Sounds like a plan. I'll get a UX going for this.

**Comment by wmbutler** [comment]
#378 will address this as well.
