### ISSUE TITLE
[0.5] Dashboard Portfolio - Trade asset bug

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2473]
**Describe the bug**
From within the Dashboard Portfolio tab, clicking the Trade icon does not reflect the value of the asset properly in Tradingview. In fact, Tradingview shows the chosen market pairing is correct, however the value represented in the chart is actually carried over from what-ever asset was viewed lastly from the Exchange tab.

**To Reproduce**
1.   Go to the Exchange tab
2.   Click on an asset in the BTS market. For this issue, use 
      https://staging.bitshares.org/#/market/OPEN.BTC_BTS
3.   Make a mental note of the value in the Tradingview chart; Should also reflect accordingly in the 
      Market pair list.
4.   Click on Dashboard
5.   Click on Portfolio
6.   Scroll down to the asset OPEN.EOS (assuming you are a holder and it is listed in your Portfolio)
7.   Scroll over to the Trade Column and click Trade
8.   Note and ensure after clicking Trade, re-direct to the Exchange 
      shows https://staging.bitshares.org/#/market/OPEN.EOS_USD
9.   Note that the market is now USD, not BTS (most other assets revert to BTS market)
10. Note and confirm that in Tradinview (top left) that it corresponds and reflects the OPEN.EOS BITUSD 
      market
11. Note the value represented in the Tradingview Chart; It should reflect the same exact price captured 
     earlier in the OPENBTC market.
12. Note that OPENBTC was only used as an example and the issue can be duplicated with any chosen 
     asset.

**Expected behavior**
Correct value correlation throughout the platform.

**Screenshots**
![190207-rc3_port_1_](https://user-images.githubusercontent.com/18186497/52955188-ada2b580-3351-11e9-8eb7-cd82c4fd9f61.JPG)
![190207-rc3_port_2_](https://user-images.githubusercontent.com/18186497/52955189-ada2b580-3351-11e9-886a-b7d5ea6a4126.JPG)

**Desktop:**
 - OS: Windows 8.1
 - Browser: Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - Version 2.190207-rc3

**Additional context**
Clicking the switch trading pair icon and then back again reflects the accurate price.
Reloading also works.

**Comment by sschiessl-bcp** [comment]
Needs validation and investigation

**Comment by sschiessl-bcp** [comment]
Confirmed, TradingView shows incorrect axis ticks.

**Comment by sschiessl-bcp** [comment]
Since this is not crucial and likely was there before, I ll remove it as blocker

**Comment by startailcoon** [comment]
@sschiessl-bcp you assinged yourself to this issue. Will you be clearing this issue?

**Comment by startailcoon** [comment]
@sschiessl-bcp ping

**Comment by startailcoon** [comment]
@sschiessl-bcp ping again, related to #2725 ?

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp ping again, related to #2725 ?

Results of investigation not conclusive yet, found one bug but there is still another one hidden somewhere.

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/pull/3073#issue-321709571
