### ISSUE TITLE
[0.75] Explore Assets - clicking asset breaks the site

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2475]
**Describe the bug**
Please see #2359  #1757 #2453
In regards to #2453 I see the same behavior seen in #1757 and I am able to reproduce his issue but only at https://wallet.bitshares.org (black screen though).
At https://staging.bitshares.org version 2.190297-rc3 it works fine.
Local wallet 2.190207-rc2 also works fine. 

**To Reproduce**
1. Go to Explore tab https://wallet.bitshares.org/#/explorer
2. Click on Assets (default smartcoins ticked) https://wallet.bitshares.org/#/explorer/assets
3. Scroll down to any UIA by derivatives-dex (Alibabacom, Boeingcom,etc)
4. Click on Boeingcom Symbol or Exchange icon https://wallet.bitshares.org/#/asset/BOEINGCOM
5. See error

**Expected behavior**
No white or black screen 
Same behavior across all versions

**Screenshots**
![190207-rc3_deri_1_capture](https://user-images.githubusercontent.com/18186497/52960876-50adfc00-335f-11e9-871c-659c1b5b0b7b.JPG)
![190207-rc3_deri_2_capture](https://user-images.githubusercontent.com/18186497/52960877-51469280-335f-11e9-898c-ce5ec9b0274f.JPG)

**Desktop:**
 - OS: Windows 8.1
 - Browser:  * Browser Brave Version 0.25.2 V8 6.9.427.23 OS Release 6.3.9600
 - Version: 2.190207-rc3
 - Version: 2.190207-rc2

**Additional Context**
This issue could be a useful tool for inaccurate price feeds if applied.

**Comment by clockworkgr** [comment]
Duplicate : https://github.com/bitshares/bitshares-ui/issues/2453

**Comment by clockworkgr** [comment]
https://github.com/bitshares/bitshares-core/issues/1602

**Comment by startailcoon** [comment]
The following is thrown

`r = this._getFeedPrice();` 

In _getFeedPrice the following fails

```
            return new k.d({
              priceObject: r,
              market_base: this.props.asset.get('id'),
              sqr: n,
              assets: t
            })
```

due to

```
f = s(this, (t.__proto__ || Object.getPrototypeOf(t)).call(this, {
          base: p ? m : d,
          quote: p ? d : m,
          real: u
        }));
```

All this is due to `let feedPrice = this._getFeedPrice();` returns null when there is no feeds.
