### ISSUE TITLE
Export file contains the wrong format timestamp for Cointracking.info

### ISSUE THREAD

**Issue by inoue-a** [bitshares/bitshares-ui#2476]
**Describe the bug**
Export file contains the wrong format timestamp for Cointracking.info
Cointracking.info uses this format `18.02.2019 hh:mm:ss GMT+xxxx`
but export file's timestamp format is `Mon Feb 18 2019 hh:mm:ss GMT+xxxx (timezone name)`

**Screenshots**
Import result:
![](https://i.imgur.com/Mfznynu.png)

**Desktop (please complete the following information):**
 - OS: Windows7
 - Browser Google Chrome 72.0.3626.109
 - Version 190207-rc3 in https://staging.bitshares.org/#/

**Comment by sschiessl-bcp** [comment]
Took 1

**Comment by sschiessl-bcp** [comment]
@inoue-a

Please try again on develop.bitshares.org

**Comment by inoue-a** [comment]
@sschiessl-bcp
It works. Thank you for your quick update :)
