### ISSUE TITLE
[1.5] Deleting Active Wallet Has Semi-Switching Effect Until Reload

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#248]
Steps to Reproduce:

1) Go to Settings --> Wallet
2) Create a new wallet - This should switch you to it automatically
3) Delete the new wallet while it is still the current active wallet:

This will have a strange effect of not updating the upper right where balances and the current account are shown so it appears to still be in the old wallet. This is not right.

4) Go to Settings --> Accounts - The correct accounts for your normal wallet should show up
5) Go to Account --> Balances - This is all correct like your normal wallet
6) Go to Send and look at the Transfer details under "From":

You should see your current active account in there but below it it says "Not your account (Propose)". This is NOT correct.

7) Play around for a while, see what is right and what is wrong.
8) Reload the program - Everything is fixed.

So, a reload must occur after switching wallets or weird things happen.
This was also my diagnosis for #210.
I believe this is an issue occurring from the same bug and both issues can be solved together.

**Comment by wmbutler** [comment]
Classified as a bug and added to 9/14 milestone.

**Comment by landry314** [comment]
So I just opened my light client today for the first time after bug testing last night and the Accounts, Send and Exchange tabs are working fine and my account is showing up there but every tab to the right of Exchange is not there just like after I deleted the wallet but hadn't reloaded yet as explained in the steps above.

This time reloading is not working and I am going to have to restore my wallet from the bin file to fix it.

What is even more disturbing is that my account is NOT showing up in Settings --> Accounts nor in the b tab on the upper left under the subcategory of Accounts. I have had this happen a few times before and the only way to fix it was to delete the library folder and freshly restore my wallet. I talked about this in issue #196.

@wmbutler, you mentioned creating an epic for this in #196. In #196, I also reference issues #207, #210 and #215. I believe an epic for all these issues can be created because the code for dealing with wallets and accounts has some serious bugs to the point where I think a complete rehaul would be in order. I talk about this in #207 suggesting a new epic called "Account Management Overhaul" but now I think "Wallet and Account System Overhaul" would be a better title.

I highly suggest renaming the three areas with "accounts" to make it clearer. I talk about this here:
https://github.com/bitshares/bitshares-ui/issues/207#issuecomment-317587171

I would love to get into an epic if it is created and consolidate my ideas for how to structure the new system.

**Comment by wmbutler** [comment]
I forgot that I use zenhub.io for epic creation and it's not native to github. I'll try to come up with another way to group these. I really like zube.io for managing issues, epics and sprints but need to talk with the team about the best way forward. One thing is for certain. Until we have a good management platform, these issues, especially the bug related issues need to be atomic. Note the bug, steps to reproduce the bug.

Long descriptions with various related issues create confusion and in all likelihood reduce the chances that the issue wil be resolved and worked.

**Comment by landry314** [comment]
I agree, @wmbutler, the way it is laid out now is not easy to read or think about. I am open to a better way.

**Comment by wmbutler** [comment]
@landry314, does the bug, as portrayed in the original description exist or not?

**Comment by landry314** [comment]
yes it does
