### ISSUE TITLE
[0.5] Tradingview chart - full access to scale properties

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#2494]
**Describe the bug**
Within Tradingview is a cog with multiple scale property settings. 
- Once the cog is clicked, the list is very hard to grab and access the bottom preferences and conversely 
   scroll back up.
- With web wallet, the list is dependent on the users screen truncation. 
- With local wallet, the screen truncation requires additionally advanced steps.
- Adding chart width to the personalize menu may not rectify; may push the menu/scrollbar outside view.

**To Reproduce**
1. Go to Exchange tab
2. Click on scale properties cog
3. Scroll down to the last option in the scale properties

**Expected behavior**
Access to the scale properties scrollbar with functionality.

**Screenshots**
![3109f53-tv-scalepropertiesclog_capture](https://user-images.githubusercontent.com/18186497/53289842-11b5e700-3761-11e9-8da0-409a949e6de7.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera 
 - Version  3109f53

**Comment by startailcoon** [comment]
It seems there is to little padding between the scrollbar for the exchange section and the trading view charts. The menu you open is to far to the right to be able to properly view the scrollbar for it. The item you've rounded in with yellow is the scrollbar for the page itself.

We should add padding to the exchange section to make this possible to use better.

**Comment by TechsUsInc** [comment]
> It seems there is to little padding between the scrollbar for the exchange section and the trading view charts. The menu you open is to far to the right to be able to properly view the scrollbar for it. The item you've rounded in with yellow is the scrollbar for the page itself.
> 
> We should add padding to the exchange section to make this possible to use better.

Yes, please see the GIF.
- Note decimal prices when the scrollbar is hovered - missing digits - padding between price chart and 
  market
- Note both scrollbars in use - padding between scrollbars
- Note behavior when the scale properties cog is clicked and the browser image is reduced

![3109f53-opera-](https://user-images.githubusercontent.com/18186497/53382141-d8d06a80-3938-11e9-9556-9c099a4fcb48.gif)

**Comment by startailcoon** [comment]
Increased the padding to the right of the chart to account for the scrollbar. The TV menu doesn't seem to view its own scrollbar though, which would probably need to be looked at further.
