### ISSUE TITLE
Missing funds at selling

### ISSUE THREAD

**Issue by clgc1972** [bitshares/bitshares-ui#2496]
**Describe the bug**
A clear and concise description of what the bug is. Yesterday. I tried to sell all my funds (bitusd) to bts, when got it, it didn´t appearing like pending, simply lost or missing in my portfolio and total account funds

**To Reproduce**
1. Go to '.sell bitusd to bts..'
2. Click on '.sell...'
4. See error open orders lefting transaction and desappear funds but in blockchain appears transactions
[BitShares - Cuenta - clgc1972.pdf](https://github.com/bitshares/bitshares-ui/files/2899787/BitShares.-.Cuenta.-.clgc1972.pdf)
[BitShares - Cuenta - clgc1972 (1).pdf](https://github.com/bitshares/bitshares-ui/files/2899788/BitShares.-.Cuenta.-.clgc1972.1.pdf)

**Expected behavior**
all my funds (more than 2600 bitusd) to bts through selling

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 8,1 pro
 - Browser [e.g. chrome, safari] app, google chrome and firefox

**Additional context**
in the begginig appears all amount bitusd on my portfolio dashboard in bts but without exchanging possibility (opposite after disappearing

**Comment by sschiessl-bcp** [comment]
It appears that you have been accepting a "Proposed transaction" that has given away control of your account to a third party. Is that correct?

**Comment by clgc1972** [comment]
I don´t know.

Please, look at  4th, 5th, 6th, 7th and 8th transaction, which in adittion take more than 2600 bitusd and check it that I didn´t received any BTS in my account after selling since this date and hour.

Could you help to know what is happening with this transactions? and coming back cryptos to my account, a sum so high that I can not afford to lose.

Thank you for your attention
________________________________
De: Stefan Schießl <notifications@github.com>
Enviado: lunes, 25 de febrero de 2019 13:40
Para: bitshares/bitshares-ui
Cc: clgc1972; Author
Asunto: Re: [bitshares/bitshares-ui] Missing funds at selling (#2496)


It appears that you have been accepting a "Proposed transaction" that has given away control of your account to a third party. Is that correct?

**Comment by clgc1972** [comment]
Good night stefan.

have you any notice in order to helping about my missed or bugged transactions to recover my funds? I don´t understand that it was happening with thiis one.

Thank you
________________________________
De: Azucena Márquez <stromean123@hotmail.com>
Enviado: lunes, 25 de febrero de 2019 17:44
Para: bitshares/bitshares-ui; bitshares/bitshares-ui
Cc: Author
Asunto: RE: [bitshares/bitshares-ui] Missing funds at selling (#2496)

I don´t know.

Please, look at  4th, 5th, 6th, 7th and 8th transaction, which in adittion take more than 2600 bitusd and check it that I didn´t received any BTS in my account after selling since this date and hour.

Could you help to know what is happening with this transactions? and coming back cryptos to my account, a sum so high that I can not afford to lose.

Thank you for your attention
________________________________
De: Stefan Schießl <notifications@github.com>
Enviado: lunes, 25 de febrero de 2019 13:40
Para: bitshares/bitshares-ui
Cc: clgc1972; Author
Asunto: Re: [bitshares/bitshares-ui] Missing funds at selling (#2496)


It appears that you have been accepting a "Proposed transaction" that has given away control of your account to a third party. Is that correct?

**Comment by sschiessl-bcp** [comment]
Unfortunately, recovery of funds is not possible since your account got hacked. The UI displays an additional necessary verification step when trying to approve a proposal from unknown source. From a developers perspective, this issue is done.

If there are any chances of recovery (unlikely imo), please come to telegram in the channel @btswallethelp
