### ISSUE TITLE
[12] Scaled Orders UX improvements

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2497]
- [ ] Find the way for users to see Buy/Sell orders book
- [ ] Find the better way to display type of Distribution

**Comment by fractalnode** [comment]
in my opinion, the Scaled Order should be placed in a separate tab, next to the currently default "Limit Order" 
![screenshot_5](https://user-images.githubusercontent.com/20418259/53744047-75948a00-3e9c-11e9-9ec2-023171c398b4.jpg)

**Comment by gibbsfromncis** [comment]
@fractalnode I agree with your opinion. I'll think about it as one of possible solutions.

**Comment by gibbsfromncis** [comment]
Hours Reporting: 8:28:22

**Comment by gibbsfromncis** [comment]
Time adjusted to 12h
