### ISSUE TITLE
[2] BindToChainState doesn't render when required parameter is missed

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2498]
if some component wrapped to `BindToChainState` and has some required ChainType parameters:

```
static propTypes = {
        currentAccount: ChainTypes.ChainAccount.isRequired,
}
```

component doesn't render if currentAccount is missed without any error/warning message.

The task is to display some kind of warning or error message to let developers know about the issue and save a lot of time for debugging process.

**Comment by sschiessl-bcp** [comment]
Basically you want that BindToChainState renderes an error "required props not given" instead of nothing?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp exactly

**Comment by sschiessl-bcp** [comment]
Ok, will you have time this sprint?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp I suppose not :) I'll work on next one

**Comment by startailcoon** [comment]
@gibbsfromncis should we open this task to someone else to work on?

**Comment by gibbsfromncis** [comment]
@startailcoon I guess yes.

**Comment by OpenLedgerApp** [comment]
@startailcoon I can take this one.

**Comment by startailcoon** [comment]
> @startailcoon I can take this one.

Assigned.
