### ISSUE TITLE
[4] Clearly render proposal contents

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/bitshares-ui#2499]
We need to CLEARLY display to the user the contents/actions to be taken as part of a proposed transaction.

Also possibly add an EXTRA notification when operation changes account authorities.

This is an urgent issue

**Comment by abitmore** [comment]
Just FYI BTS++ Mobile App (https://github.com/bitshares/bitshares-mobile-app) now shows detailed account updating info in proposal.

**Comment by abitmore** [comment]
By the way I don't understand why an issue with "critical priority" had no progress (?) in about 3 months.

**Comment by sschiessl-bcp** [comment]
This is how `account_update` will look like
![image](https://user-images.githubusercontent.com/33128181/58082876-29fa9e00-7bb8-11e9-9731-c9b426fdbae2.png)

**Comment by sschiessl-bcp** [comment]
> By the way I don't understand why an issue with "critical priority" had no progress (?) in about 3 months.
> 
> Update: saw progress here [blockchainprojects#87](https://github.com/blockchainprojects/bitshares-ui/pull/87). IMHO we could have firstly added account_update in a previous release then do other things later, since priority of other operations aren't that high.

I agree that my choice to refactor everything was maybe too extensive for high priority .. Important and quick update was that the "Approve" button get's hidden and the user needs to manually make it visible by unchecking "Hide suspicious"
