### ISSUE TITLE
[1.5] Removing an api from apiConfig breaks any user (white screen) that has it as apiServer in local Storage

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2500]
```
app.4af293f1ab2d2fcfcb03.js:1 TypeError: Cannot read property 'url' of undefined
```

**Comment by clockworkgr** [comment]
i thought we'd fixed that?

**Comment by sschiessl-bcp** [comment]
Me too ...

**Comment by startailcoon** [comment]
Adding some buffering time to clearly find the issue here. Lets squish this thing.

**Comment by sschiessl-bcp** [comment]
Reproduce:
 - add a node in apiConfig
 - connect to that node, close UI
 - remote that node from apiConfig
 - load UI, observer stuff breaking
