### ISSUE TITLE
[25] - Beet Development (Dec/Jan/Feb)

### ISSUE THREAD

**Issue by clockworkgr** [bitshares/bitshares-ui#2501]
- Various bug fixes
- Implement Beet Branding and UX redesign using guide in:  https://github.com/bitshares/bitshares-ui/issues/2226
- PD4 https://github.com/bitshares/beet/issues/10
- Update Build scripts (appveyor/travis)
- Enable Copy/Paste Support https://github.com/bitshares/beet/issues/61
- Refactor beet-js library architecture

**Comment by sschiessl-bcp** [comment]
[8] paid in 0301
