### ISSUE TITLE
AssetSelect in Burn Modal show null

### ISSUE THREAD

**Issue by Cryptrade-Dev** [bitshares/bitshares-ui#2506]
**Describe the bug**
see title

**To Reproduce**
1. Go to Account > Portfolio > Burn
2. Click on 'Burn'
3. Open the Burn Modal

**Expected behavior**

**Screenshots**
![issue_burn_modal](https://user-images.githubusercontent.com/44422194/53677979-8786f900-3cf3-11e9-8cf7-9075e54fd6fa.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chorme
 - Version 22

**Comment by startailcoon** [comment]
Already addressed in PR https://github.com/bitshares/bitshares-ui/pull/2495

**Comment by startailcoon** [comment]
Already addressed in PR #2495
