### ISSUE TITLE
Account history export with full details

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2512]
The current account history export explicitly maps operations to rows in the file and skips certain operations. This issue is meant to allow the requesting of 
 -  the current report as is (cointracking compatible)
 - a full history of all operations (can be different format)

For that we need a ChoiceModal popping up when the user clicks the current export button that offers both choices.

**Comment by loweherz** [comment]
In testing the creation and selling of an asset, we saw no registration of it in the account history / .csv file. Please could you take this up as well.

**Comment by sschiessl-bcp** [comment]
> In testing the creation and selling of an asset, we saw no registration of it in the account history / .csv file. Please could you take this up as well.

What account have you been using?

**Comment by loweherz** [comment]
team1000

**Comment by sschiessl-bcp** [comment]
Now part of #2543
