### ISSUE TITLE
account hacked

### ISSUE THREAD

**Issue by rich4231** [bitshares/bitshares-ui#2513]
hello,
my bitshares account was hacked. I was sent a proposal from an unknown account and being a new user Iunknowingly accepted it. now I am locked out from my own account as my permissions has been changed. I still have all my money I just can withdraw it or trade it. the account was openledger-security which has been blacklisted in the past. the txid is 
Tx b19978a52f50eccf23728695a4e98bf409c66ec7
my account is rich4231.

**Comment by abitmore** [comment]
If you can still trade or withdraw your money, it's recommended that you create a new account and transfer all your money to the new account as soon as possible. It's you that approved the proposal with your private key, the blockchain can not undo it.

**Comment by abitmore** [comment]
Actually I don't think you are able to trade or withdraw. Your money has gone.

**Comment by rich4231** [comment]
does bitshare really not have any control over there own exchange?

**Comment by abitmore** [comment]
Users control their accounts via private keys. Users are fully responsible for their accounts and private keys. The blockchain can not identify an account update operation is intended or due to phishing (in your word, others have no control).

**Comment by xeroc** [comment]
SFYL, but there is nothing anyone can do to help you. It compares nicely with losing your bitcoin wallet -> no one can recover them.

closing
