### ISSUE TITLE
Asset Disbursment Math Error

### ISSUE THREAD

**Issue by remedycoin** [bitshares/bitshares-ui#2514]
When I created remedy.Destinia with 1 million shares I then dispersed 500000 of the tokens to my account Joe-baker. I later found that I was not able to disperse any more.  The client application seems to get the math wrong thinking that I am exceeding the maximum number of tokens. Maybe I'm doing something wrong. I'm reporting this from my phone so I don't have full access to screenshots and such but I will get some more details in the future. This issue has been going on ever since I created the token perhaps four or five months ago.

**Comment by startailcoon** [comment]
If possible, can you reproduce this on the bitshares testnet and post some more details about it?

**Comment by startailcoon** [comment]
No respons from reporter
