### ISSUE TITLE
[1.5] Build OS X Electron Wallet

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#252]
A manual build of Electron Wallet for OS X. This will eventually be automated. First time for @calvinfroedge so including setup and orientation time.

**Comment by calvinfroedge** [comment]
Latest OSX build: https://drive.google.com/file/d/0BzvuEYutkmtdSk45RUpCb2ozTkE/view?usp=sharing

sha1: acb78293a129e06399f5959150065d6d6b9c3540
sha256: d271edeece9c04165a84cbf3e6b5ed2060af87a5b42810e4f7048696d8f0ca27

**Comment by calvinfroedge** [comment]
PR: https://github.com/bitshares/bitshares-ui/pull/259

**Comment by calvinfroedge** [comment]
@wmbutler Estimate was updated to 1.5

**Comment by wmbutler** [comment]
The intention here was to have a manual build for the 170901 release. I was thinking I'd leave it open until the last day since it depends upon the rest of the code being complete.
