### ISSUE TITLE
[0] Exchange header 24hr change indicator broken

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2526]
https://wallet.bitshares.org/#/market/NOWCOIN_BTS

![image](https://user-images.githubusercontent.com/33128181/54124978-14bd0280-4404-11e9-89e2-b9590c151023.png)

I guess it happens on illiquid markets when there is no data available

**Comment by abitmore** [comment]
Is this issue related to https://github.com/bitshares/bitshares-core/issues/1620? Try switch to an API server that is not running 2.0.190219?

**Comment by sschiessl-bcp** [comment]
Almost certain it is, thanks a lot for the pointer!

**Comment by abitmore** [comment]
OK. Anyway, it's harmless if UI tolerates back end bugs. ;)

**Comment by startailcoon** [comment]
Should we find a better way to display this other than "NaN"?
It's not really a great identification for users what it means.

We should just replace "NaN" with 0 if it's empty I guess.

**Comment by sschiessl-bcp** [comment]
Proper replacement IMO would be to indicate that nothing happened, e.g. with a dash

**Comment by froooze** [comment]
> Proper replacement IMO would be to indicate that nothing happened, e.g. with a dash

Why not 0%?

**Comment by sschiessl-bcp** [comment]
0% also means it went up and down and now there is the same value. Different than nothing happened

**Comment by sschiessl-bcp** [comment]
fixed during review
