### ISSUE TITLE
Add Scam Alert

### ISSUE THREAD

**Issue by bangzi1001** [bitshares/bitshares-ui#2529]
**Is your feature request related to a problem? Please describe.**
Lot of scam going around Bitshares DEX causing lot of users losing money and also also reputation of Bitshares. The reason users get scammed easily because the reference UI and gateway UI does not deliver the message to users until they get scammed and then come to Telegram to see what is happening. 

**Describe the solution you'd like**
1. Scam Alert via Popup Message when users open reference wallet wallet.bitshares.org or gateway UI. Describe what is happening and how to prevent it. This does not limited to proposal scam because scammer will change to different method once it become useless. If users are well informed, then the damage will be zero or minimal. 
2. A "SCAM ALERT" Menu beside REPORT and HELP.

**Comment by grctest** [comment]
I think a popup or extra steps required to transfer ownership of your account in a proposal is appropriate, but a generic scam warning could be too broad to prevent users from falling for such scams.

**Comment by bangzi1001** [comment]
The proposal scam is sophisticated social engineering attack, thus even the UI add extra 3-5 steps also meaningless for users who are not aware it is a scam. What users see is security upgrade which is required and then they just press the buttons. 

Information is Power. The scam Alert via Popup Message is the best way to inform and educate the users what kind of scam is happening now and thus even they see the proposal or any scam attempt, they can avoid it. If they don't, then they only can blame themselves. 

Last but not least, "popup or extra steps required to transfer ownership of your account in a proposal " only prevent one type of scam, the proposal type scam. But "scam Alert via Popup Message" able to prevent different type of scams as soon as it happen, the UI able to alert all users when they open the wallet.

**Comment by grctest** [comment]
Who would have the power/authority to distribute these popup messages? If they dismiss the message without reading it will they see it again if they encounter a scam situation?

I think that if they're informed that by transferring their account keys/ownership to someone else that it's an irreversible action & that nobody from bitshares/gateways will ever ask them to do this and for them to go through an extra hoop or two may be enough to stop this one type of scam from being successful again in the future. That said, you're right that some people will blindly click but that's then their own fault.

**Comment by sschiessl-bcp** [comment]
What is the idea on the scam alert?

Should:
 - the UI recognize that something scammy is going on by itself and do a warning?
 - the UI connect to for example a dedicated github repositories where scam alerts can be pushed that will then be shown once in UI?

**Comment by bangzi1001** [comment]
"the UI connect to for example a dedicated github repositories where scam alerts can be pushed that will then be shown once in UI?"

Something like this but only UI team(to prevent misuse by others) able push scam alert that show on UI. Not once but probably few times or a period of time.

**Comment by bangzi1001** [comment]
![2019-04-10_23h26_03a](https://user-images.githubusercontent.com/36911788/55892112-4a623080-5be8-11e9-97a8-9322f4ef5c92.jpg)

**Comment by abitmore** [comment]
https://github.com/bitshares/bitshares-ui/issues/2658#issuecomment-489321182

**Comment by bangzi1001** [comment]
Just saw Openledger warn users with this method. It is simple but effective. 
![2019-05-10_01h24_03](https://user-images.githubusercontent.com/36911788/57473486-85788200-72c2-11e9-920b-399e9af26ebd.jpg)

**Comment by sschiessl-bcp** [comment]
> Just saw Openledger warn users with this method. It is simple but effective.
> ![2019-05-10_01h24_03](https://user-images.githubusercontent.com/36911788/57473486-85788200-72c2-11e9-920b-399e9af26ebd.jpg)

In the pipeline for next release #2679

**Comment by sschiessl-bcp** [comment]
@bangzi1001 does the solution of #2679 satisfy your needs described?

**Comment by blincadmin** [comment]
Excellent addition to the UI

**Comment by sschiessl-bcp** [comment]
Thanks, closing this now, done.
