### ISSUE TITLE
[2] Proposer doesn't show on proposals

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2531]
**Describe the bug**
On "proposed transactions" page, <del>when there is a translation error,</del> proposer name doesn't show.

**To Reproduce**
1. Go to 'https://develop.bitshares.org/#/account/committee-account'
2. Click on 'Proposed transactions'
3. See error "missing translation: en.proposal.proposal_update "

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/54481049-336e2f80-4830-11e9-83a1-12bbfccc37ee.png)

**Expected behavior**
See **proposer** and proposal details in the page.
![image](https://user-images.githubusercontent.com/9946777/54481235-792bf780-4832-11e9-9ce5-12e6d73a6aff.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abitmore** [comment]
Actually, if there is no error, the proposer name still doesn't show. See https://develop.bitshares.org/#/account/static-checker . I only know the name was added in #1680 requested by #1674, when did it get removed?

**Comment by startailcoon** [comment]
I thought we had this fixed :|
Would require some testing and making sure that proposer is working everywhere, still a higher priority at the current time.

**Comment by sschiessl-bcp** [comment]
Checking this now, needs to be in next release

**Comment by sschiessl-bcp** [comment]
#1680 only added the proposer name if the first operation is a `transfer`. Generalizing now

**Comment by sschiessl-bcp** [comment]
Took 0.5

**Comment by sschiessl-bcp** [comment]
Will be refactored within #2499 as well
