### ISSUE TITLE
[2.5] Coin Days not correctly displaying in Vesting Balance

### ISSUE THREAD

**Issue by iamredbar** [bitshares/bitshares-ui#2532]
**Describe the bug**
In the desktop GUI and web wallet vesting balances that are not BTS do not correctly display coin days.

**To Reproduce**

(on desktop GUI or web wallet)
1. Go to hamburger menu, top right
2. Click on 'Vesting Balances'
3. See vesting balances
4. See incorrect coin days for assets other than BTS

(on wallet.crypto-bridge.org)
1. Click on 'Dashboard'
2. Click on BridgeCoin Staking
3. See correct coin days

**Expected behavior**
Correct coin days displayed in desktop GUI and web wallet.

**Screenshots**
![Screen Shot 2019-03-16 at 6 48 52 PM](https://user-images.githubusercontent.com/16945982/54483137-b2f20380-481c-11e9-8b6d-ba93777f0c3d.png)

![Screen Shot 2019-03-16 at 6 48 36 PM](https://user-images.githubusercontent.com/16945982/54483138-b7b6b780-481c-11e9-99a8-65878a060685.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser Firefox
 - Version 65.0.1 (64-bit)

**Comment by iamredbar** [comment]
Here is another example from today:

![](https://cdn.steemitimages.com/DQmPjU7rr2AfWjizVzqUmv8THYotYtq9NQj3WRzG1NtUJDx/Screen%20Shot%202019-04-02%20at%209.38.38%20AM.png)

![](https://cdn.steemitimages.com/DQmUMiUkHTusjJ3MGhCfhJw62GMnE7NkvhMhNkMrkdTDSuJ/Screen%20Shot%202019-04-02%20at%209.38.25%20AM.png)

Even though it has been enough days to withdraw, I can only withdraw it on CryptoBridge.

Could this have to do with the asset that was used as the fee? Since it was staked using BCO as the fee asset, would that affect coin days?

**Comment by abitmore** [comment]
It's due to bitshares-core's lazy-updating design: API only returns `last_update_time` and `coin_seconds_on_last_update`. Ideally UI should calculate and show current coin-second value based on the results. However, strictly speaking, it needs 128-bit multiplication, I don't know if it's hard for JS.

**Comment by iamredbar** [comment]
I don’t do JS, so I wouldn’t know either. I hope this is something that can be done, it would be nice to be able to get vesting balances in whatever wallet you are using.

**Comment by startailcoon** [comment]
Obviously crypto-bridge does this correctly. We should check out their source for this.

**Comment by abitmore** [comment]
@startailcoon please assign someone / a milestone?

**Comment by startailcoon** [comment]
I've managed to isolate the issue and it will be resolved in the coming days.

**Comment by startailcoon** [comment]
End result with BCO Staking being possible to claim

Chain Vesting type is "unspecified", which is why it states the type to be that.

![image](https://user-images.githubusercontent.com/12114550/61404029-d2865f00-a8d6-11e9-8fa0-cef39874ef4b.png)

**Comment by abitmore** [comment]
@startailcoon I'm talking about this:

https://wallet.bitshares.org/#/account/bitcrab/vesting

![image](https://user-images.githubusercontent.com/9946777/61405934-27c46f80-a8db-11e9-9f32-84c1bf709689.png)

From cli_wallet:
```
unlocked >>> get_vesting_balances 1.13.282
[{
    "id": "1.13.282",
    "owner": "1.2.121",
    "balance": {
      "amount": 908264200,
      "asset_id": "1.3.0"
    },
    "policy": [
      1,{
        "vesting_seconds": 7776000,
        "start_claim": "1970-01-01T00:00:00",
        "coin_seconds_earned": "2468605808706060",
        "coin_seconds_earned_last_update": "2019-07-17T06:00:00"
      }
    ],
    "balance_type": "cashback",
    "allowed_withdraw": {
      "amount": 323183088,
      "asset_id": "1.3.0"
    },
    "allowed_withdraw_time": "2019-07-17T19:35:57"
  }
]

```

`3174 BTS` vs `3231 BTS` allowed to withdraw. The reason is GUI calculates with `coin_seconds_earned` only but ignored `coin_seconds_earned_last_update`, but CLI calculates with all the fields and current time (output as `allowed_withdraw_time`).

Also, "days left of vesting period" need to be recalculated.

```
coin_seconds_earned_now = coin_seconds_earned + balance * (now - coin_seconds_earned_last_update)
allowed_to_withdraw = coin_seconds_earned_now / balance
days_left = vesting_seconds - coin_seconds_earned_now / balance
```

**Comment by startailcoon** [comment]
Thanks for the details @abitmore, didn't catch that issue. It's as you mention that the wallet UI simply didn't account for the last_update field, which mean it didn't allow the full amount to be claimed.

I'll supply a fix.

With the update the claim balance is what you want it to be while the last update is still `"coin_seconds_earned_last_update": "2019-07-17T06:00:00"`

![image](https://user-images.githubusercontent.com/12114550/61442326-b078f500-a947-11e9-9e18-40092ce44623.png)
