### ISSUE TITLE
[2.0.190207-rc2] Integration tests by @xiaolujidan

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2537]
https://github.com/bitshares/bitshares-ui/issues/2436#issuecomment-463018223

**Comment by sschiessl-bcp** [comment]
Bounty: 0.5 (1 platform/browser)

**Comment by sschiessl-bcp** [comment]
@xiaolujidan please state your bitshares account in order to receive the bounty

**Comment by clockworkgr** [comment]
@xiaolujidan ping

**Comment by clockworkgr** [comment]
@xiaolujidan @sschiessl-bcp  ping again
