### ISSUE TITLE
[0.25] Incorrect links in the Membership section

### ISSUE THREAD

**Issue by serdrdoor** [bitshares/bitshares-ui#2539]
**Steps to reproduce the behavior:**
Being on page:
1. https://wallet.bitshares.org/#/account/ACCOUNT/member-stats
And if you follow the links that are listed below, then there is no transition to viewing your account.

Lifetime Referrer
Registrar
Affiliate Referrer

![image](https://user-images.githubusercontent.com/11815105/54706665-7ee64d80-4b50-11e9-8516-e44507b227b9.png)

Links are incorrect to display information:

![image](https://user-images.githubusercontent.com/11815105/54707349-e8b32700-4b51-11e9-9cb7-92cb3e9e41ad.png)

**Expected behavior:**
Link of this type:
https://wallet.bitshares.org/#/account/ACCOUNT

The problem is in the link itself, so I do not specify the types of browsers and devices.

**Comment by startailcoon** [comment]
Simple fix to this. Thanks for finding this
