### ISSUE TITLE
[4][hyper-bola] Alignment and spacing fixes

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#254]
Light Wallet latest version

Issued Assets > Update Assets

Here's the normal view:

![](https://i.imgur.com/vgBekPY.png)

here's the wrong alignment

![](https://i.imgur.com/M74vtJY.png)

**Comment by wmbutler** [comment]
I'd really like to see this left justified with 20px of padding/margin. Does anyone object to this? I always thought the center justification felt a bit hokey.

**Comment by btsfav** [comment]
@wmbutler not sure how/if this would affect user experience. Pretty sure there are some studies on eye movement and design, but that's way beyond my experience

**Comment by wmbutler** [comment]
There is an arbitrary amount of margin depending on the width of the users' browser. Seems like it wasn't thought out very clearly.

## Browser Wide
![screen shot 2017-08-15 at 4 37 33 pm](https://user-images.githubusercontent.com/1254810/29337747-20c34af2-81d8-11e7-890d-dedbc5beee0e.png)

## Browser Narrow
![screen shot 2017-08-15 at 4 37 45 pm](https://user-images.githubusercontent.com/1254810/29337748-20c3e9bc-81d8-11e7-996a-1faa67e1af5b.png)

If we left justified it, we'd fix your issue and, in the process, improve the overall experience.

**Comment by btsfav** [comment]
Sounds good!

**Comment by wmbutler** [comment]
Left justify the main body block of the reference wallet. Likely 20px of padding on the left. This will be a change that affects many screens so some testing is in order. Made the issue 2 hours to accommodate testing.

**Comment by wmbutler** [comment]
@hyper-bola great work. If you can remember to do so, please reference the issue in your commits like:

```
git commit -m "I fixed this bad bug #254"
```

It's helpful because then we see the commits in the actual issue that you are getting the bounty for. Also, let me know how much extra time you put into this issue. I know you had already put about 2 hours in for the previous work.

**Comment by hyper-bola** [comment]
@wmbutler done, thanks. And I put about 2 extra hours into this issue and code refactoring related in #277.

**Comment by wmbutler** [comment]
Update to 4 hours per additional hours stated above.

**Comment by wmbutler** [comment]
There is a second PR related to this issue. Re-opening until updated.
