### ISSUE TITLE
[5][Keegan-lee] Account activities: Refine export function

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2543]
**Is your feature request related to a problem? Please describe.**
The export feature is not obvious enough.
![image](https://user-images.githubusercontent.com/9946777/54870354-aa15aa80-4da5-11e9-8367-5e0847b95455.png)

**Describe the solution you'd like**
Add text.

**Describe alternatives you've considered**

**Additional context**

**Comment by startailcoon** [comment]
We have enough space to at least have a label to this, very true.

**Comment by sschiessl-bcp** [comment]
Tasks:

- [ ] Properly center the icon vertically
- [ ] Add a label on the right side of the icon
- [ ] Add a choice modal to allow 
  - a) cointracking report (current export)
  - b) full report (merely put raw data in excel file)

**Comment by Keegan-lee** [comment]
I'd like to claim this.

**Comment by sschiessl-bcp** [comment]
Cool, will give some more details tomorrow I had some thoughts on

**Comment by sschiessl-bcp** [comment]
The logic is currently built into `RecentTransactions` method `_generateCSV`.
I would like to separate business logic from the frontend, therefore please create a new class `AccountHistoryExporter` (or similar) that receives an account name or id and what type of history it should export (full or cointracking). 

The export uses the bitshares-report from sigve, which I had to modify to match the latest ES database structure. Ideally, those changes are put in a PR onto the bitshares-report repository as well to take out the overhead on our end, see the line `data.amount = data.amount_;` (the `_` was added for compatibility).

I ll let you dig in and we can discuss again once you are familiar with the code.

**Comment by startailcoon** [comment]
@Keegan-lee got a status update for us?

**Comment by sschiessl-bcp** [comment]
There is a PR for this https://github.com/bitshares/bitshares-ui/pull/2590

**Comment by startailcoon** [comment]
> There is a PR for this #2590

Missed it since github didn't link it to here :)
