### ISSUE TITLE
[0.5] Update account history object sorting logic

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2545]
**Describe the bug**
Current code for sorting account history object will be obsolete after https://github.com/bitshares/bitshares-core/issues/1675 is done.
https://github.com/bitshares/bitshares-ui/blob/83edcc3a7bee73410d9efeee690ffbf86a70d6a9/app/components/Account/RecentTransactions.jsx#L22-L28

The correct logic is to compare all the 4 fields `(block_num, trx_in_block, op_in_trx, virtual_op)` in the object (it is also correct before https://github.com/bitshares/bitshares-core/issues/1675 is done).

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexandr-masl** [comment]
hi everyone, can I take this one.
thanks in advance.

**Comment by startailcoon** [comment]
@alexandr-masl it's yours. 

The changes mentioned will be live in version 3.1.0, Testnet relase 16 April, and main network release 30 April. 

Make sure to check if it's required to keep backwards compatibility.

**Comment by sschiessl-bcp** [comment]
There is also a PR for this one in our repo, will be forwarded after RC is done
