### ISSUE TITLE
Do direct WebSocket pings instead of using ChainWebSocket

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2559]
Currently the UI uses ChainWebSocket to ping. This causes great overhead. To speed up the ping, implement
 - [ ] direct ping via websocket
 - [ ] re-introduce parallel ping
 - [ ] increase latency acceptance (lifting good from 200 to 500ms)

**Comment by sschiessl-bcp** [comment]
Took 1.25 for adjusting and testing clockworks base

**Comment by clockworkgr** [comment]
original work on base DirectPinger and testing  took about 1.5
