### ISSUE TITLE
[0.5][Tradingview] Quick Chart resize does not honor limit values

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2564]
**Describe the bug**
The up and down arrows for Tradingview chart size don't work.

**To Reproduce**
Go to Exchange and click on the arrows

**Expected behavior**
Change size of Tradingview

**Screenshots**
![Resize-chart](https://user-images.githubusercontent.com/40874087/55348399-6c0c3b00-54b7-11e9-8271-d0250aa01bad.png)

**Desktop (please complete the following information):**
 - MX-Linux
-  BitShares2-light_2.0.190410-rc1_amd64.deb

**Additional context**
I didn't had the problem on Linux Mint (Ubuntu), but the problem exists for a Debian based Linux.

**Comment by startailcoon** [comment]
This seems like a very specific local issue for you. Have you been able to confirm the problem with a second unit using the same setup and software?

**Comment by froooze** [comment]
Best thing would be a test on another Debian distro?

**Comment by startailcoon** [comment]
> Best thing would be a test on another Debian distro?

Indeed

Does resizing of the chart work by changing it in the settings, or doesn't that work either?
Does the client give you any errors in console when you do this?
Is this problem a new one, or has it never worked?

**Comment by froooze** [comment]
The Problem was in Personalize. The height was under 420px, which looks like the minimum height.
When the height is set to 300px it takes several clicks to see any action. 

To solve this problem:
The increasing button needs to set the height to 430px, when the start value is under 420px.

**Comment by froooze** [comment]
The Problem was in Personalize. The height was under 420px, which looks like the minimum height.
When the height is set to 300px it takes several clicks to see any action. 

To solve this problem:
The increasing button needs to set the height to 440px, when the start value is under 420px.

**Comment by startailcoon** [comment]
So the chart was below the minimum by setting, and when you tried to expand it, it took seveal clicks to go over the minimum height?

This should really not be possible and should be looked at. Thanks for the find.

**Comment by froooze** [comment]
Right!
