### ISSUE TITLE
[Keegan-lee][1] Add cumulative amount in collateral bids table

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2570]
**Is your feature request related to a problem? Please describe.**
https://wallet.bitshares.org/#/asset/USD
Current collateral bids table:
![image](https://user-images.githubusercontent.com/9946777/55390677-feecba00-5537-11e9-87e9-cebdb244b64c.png)

It would be more convenient if there is a "cumulative debt" column, just like the order book:

![image](https://user-images.githubusercontent.com/9946777/55390809-42472880-5538-11e9-9866-0164e31ef288.png)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Keegan-lee** [comment]
I'd like to claim this.

**Comment by startailcoon** [comment]
@Keegan-lee I've assigned you to this issue.
