### ISSUE TITLE
[1][OpenLedgerApp] Honor setting on "View only mode" after restart

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2577]
**Describe the bug**
When I switch an account after a restart of the light client it doesn't remember my decision of not warning me again.  

**To Reproduce**
Switch Account -> Never show again -> Restart light client -> Switch Account again -> Never show again

**Expected behavior**
Decision should be saved permanent. 

**Screenshot**
![Never-Show-Again](https://user-images.githubusercontent.com/40874087/55564823-0c9d6d80-56f9-11e9-812f-359d3a40639b.png)

**Desktop (please complete the following information):**
  -  MX-Linux
  -  BitShares2-light_2.0.190410-rc1_amd64.deb

**Comment by sschiessl-bcp** [comment]
Never show again what?

**Comment by froooze** [comment]
Included a screenshot in first post.

**Comment by OpenLedgerApp** [comment]
@startailcoon, I can take this one.

**Comment by startailcoon** [comment]
@OpenLedgerApp Assigned

**Comment by startailcoon** [comment]
# Task

- When browsing another user, honor the "Never show" selection
- Enable option to show/hide "View only mode" in "Settings -> General"

**Comment by sschiessl-bcp** [comment]
> # Task
> * When browsing another user, honor the "Never show" selection
> * Enable option to show/hide "View only mode" in "Settings -> General"

Note on the second: This is not meaning that user should not be able to use that mode anymore. Only if the popup comes again or not.

**Comment by startailcoon** [comment]
> 
> 
> > # Task
> > 
> > * When browsing another user, honor the "Never show" selection
> > * Enable option to show/hide "View only mode" in "Settings -> General"
> 
> Note on the second: This is not meaning that user should not be able to use that mode anymore. Only if the popup comes again or not.

Sorry, was I unclear about that? It is of course to allow the user to be able to enable the popup for "View Only Mode" again. If the user clicks "Never show", they should be able to revert that setting.

### Example
- User x goes to user y wallet
- User x is displayed the "View only mode" popup
- User x clicks "Never show" button
- User x wish to see the popup whenever they are on any other account again
- User x goes to settings, and disable "Never show `View only mode`" setting in the settings view.

Without this, the user has to remove the setting manually in the browser settings.
