### ISSUE TITLE
[0.25] Notify user on Asset Burn

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2581]
When a new user uses "Asset Burn" feature in the wallet there is currently no information what this action does.

Initially we should add a notification alert that any submitted action to the chain when using burn/reserve will destroy said asset amount.

![image](https://user-images.githubusercontent.com/12114550/55581911-62384100-571e-11e9-979b-a30a1baf4c6c.png)

**Comment by shulthz** [comment]
yes,we need this notification
