### ISSUE TITLE
I created new Theme Template and i think the modals are not working, help please :)

### ISSUE THREAD

**Issue by chadbernal** [bitshares/bitshares-ui#2583]
![issue](https://user-images.githubusercontent.com/34367744/55603601-10370000-579e-11e9-9688-47031e5912ed.png)

**Comment by sschiessl-bcp** [comment]
@gibbsfromncis

**Comment by chadbernal** [comment]
I created it from scss templates located in bitshares-ui, I hope its okay, :(

**Comment by gibbsfromncis** [comment]
@chadbernal please provide me more details

**Comment by chadbernal** [comment]
I configure bitshares-style-guide and it works already :)

**Comment by sschiessl-bcp** [comment]
What was the issue you have faced and how did you solve it? 

Any insight will help others in the future!

**Comment by chadbernal** [comment]
When creating another template for your theme, modals and other style are not in place.
What i did is edit the node_modules/bisthares-style-guide/dist/style/style.css.
add your theme.
And it works! :)

**Comment by gibbsfromncis** [comment]
@chadbernal by best practices you can create a fork of `bitshares-ui-style-guide`, update link in package.json and then modify bitshares-ui-style-guide. 

I'll create more detailed instruction soon.

**Comment by chadbernal** [comment]
Thank you, thats what i did :)
