### ISSUE TITLE
failed to broadcast transaction while adjust bitUSD position using a MULTI SIG account

### ISSUE THREAD

**Issue by bitcrab** [bitshares/bitshares-ui#2588]
**Describe the bug**
failed to broadcast transaction while adjust bitUSD position using a MULTI SIG account

![bug](https://user-images.githubusercontent.com/5886543/55616267-ff998080-57c3-11e9-82ea-723e1208d247.jpg)

**Comment by clockworkgr** [comment]
@bitcrab  Can you get us a console log Jerry?

**Comment by bitcrab** [comment]
console log:

log: Checked 1 connections, 1 failed
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: Checked 1 connections, 0 failed
log: Latency result:[object Object]
log: fetchCoins error from https://ol-api1.openledger.info/api/v0/ol/support/coins: TypeError: Failed to fetch
log: synced and subscribed, chainstore ready
log: fetchCoins error from https://ol-api1.openledger.info/api/v0/ol/support/coins: TypeError: Failed to fetch
log: auto locking after600s
log: Your node is out of sync since 8.254999876022339 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 5.641000032424927 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 6.66100001335144 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 5.698999881744385 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 6.361999988555908 seconds, waiting 10 seconds, then we notify you
log: synced and subscribed, chainstore ready
log: Your node is out of sync since 7.332000017166138 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 7.664000034332275 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 6.716000080108643 seconds, waiting 10 seconds, then we notify you

**Comment by clockworkgr** [comment]
working as intended: see: https://github.com/bitshares/bitshares-core/pull/1566
