### ISSUE TITLE
[10][dot5enko] Add support for HTLC operations

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2589]
Add 
 - [htlc_create_operation](https://github.com/bitshares/bitshares-core/blob/8c1a78b7f3f0083abee695c1b8a9b944f2c4a1be/libraries/chain/include/graphene/chain/protocol/htlc.hpp#L48)
 - [htlc_redeem_operation](https://github.com/bitshares/bitshares-core/blob/8c1a78b7f3f0083abee695c1b8a9b944f2c4a1be/libraries/chain/include/graphene/chain/protocol/htlc.hpp#L87)
 - [htlc_extend_operation](https://github.com/bitshares/bitshares-core/blob/8c1a78b7f3f0083abee695c1b8a9b944f2c4a1be/libraries/chain/include/graphene/chain/protocol/htlc.hpp#L143)

to bitsharesjs like e.g. this one https://github.com/bitshares/bitsharesjs/search?q=withdraw_permission_create&unscoped_q=withdraw_permission_create

There is a tool from bitshares-core that create the serialization files to be used. This issue includes creating documentation how to do the whole process.

**Comment by abitmore** [comment]
Also need to support the new virtual operations, in order to show them in account activities.

**Comment by dot5enko** [comment]
i can't upload to `bitsharesjs` cause i don't have permissions. Also i have trouble to sign tx and actually test if it works: `missing required active authority: Missing Active Authority`, i've tried different keys but none works  :) , so need someone's help here @sschiessl-bcp

**Comment by sschiessl-bcp** [comment]
Please fork it and do a PR, we ll discuss in it then

**Comment by dot5enko** [comment]
it was  a very late night and i wanted to push the pr directly to branch into `bitsharesjs` ))
done - https://github.com/bitshares/bitsharesjs/pull/47

**Comment by dot5enko** [comment]
> This issue includes creating documentation how to do the whole process.
@sschiessl-bcp  how you want it to be done? i've created two examples for create and redeem ops in examples folder

**Comment by sschiessl-bcp** [comment]
> > This issue includes creating documentation how to do the whole process.
> 
> @sschiessl-bcp how you want it to be done? i've created two examples for create and redeem ops in examples folder. Also can we adjust bounty for virtual ops?
> 
> As i seen we could make a wrapper for htlc as a HtlcActions in bitshares-ui. i can handle it too

Please state your effort. I like the HTLCActions idea, go for it!

How about adding the "How to adjust serialization" into Wiki? To point out the required steps, doesnt have to be much text.

**Comment by dot5enko** [comment]
here's "wiki" on how to add new ops to bitsharesjs cause i haven't seen where to add it 

# How to adjust serialization
### Generating new operations serialization objects
1. [Compile](https://github.com/bitshares/bitshares-core/wiki#building) [`js_operation_serializer`](https://github.com/bitshares/bitshares-core/tree/master/programs/js_operation_serializer) program of `bitshares-core` with
--  `make js_operation_serializer`
2. generate `lib/serializer/src/operations.js` using `js_operation_serializer` output. (Actually its a bit outdated now and needs some PR's ([#1714](https://github.com/bitshares/bitshares-core/pull/1714),[#1702]()) to be merged before it would actually work as expected. But you can use it as is and its very helpfull now though)
3. edit `lib/chain/src/ChainTypes.js` by adding proper values to:
-- `ChainTypes.object_type` if you adding new operation type 
-- `ChainTypes.operations` if you adding new operation of some existing type (js_operation_serializer provides those ids actually)
4. write some examples if needed into `examples` folder
5. write tests
6. run tests `npm test`

**Comment by dot5enko** [comment]
@sschiessl-bcp  need new bitsharesjs with htlc ops to test bitshares-ui.  PR submited

**Comment by dot5enko** [comment]
@sschiessl-bcp can we increase the bounty up to 10hrs as virtual ops requested above and HtlcActions was added after issue was created and it took me a little bit more time?

**Comment by startailcoon** [comment]
I've updated the estimate to 10 hours.

**Comment by dot5enko** [comment]
@sschiessl-bcp  work done, ready to merge
- added htlc ops to account activity, block explorer and fee schedule

**Comment by sschiessl-bcp** [comment]
For testing, connect to testnet and check http://localhost:8080/account/thtlc-3

`bnitsharesjs` examples can be used to create more for those accounts.

**Comment by sschiessl-bcp** [comment]
I will accept this ticket, minus fee schedule which was forgotton and have that on a new ticket.

**Comment by dot5enko** [comment]
@sschiessl-bcp https://github.com/bitshares/bitshares-ui/commit/5dd4c2b8568388aec25aa22327a8a6030ddd9cad
