### ISSUE TITLE
[1] request settlement tab <settlement price> is wrong

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#2593]
![图片](https://user-images.githubusercontent.com/34892308/55666308-9f681480-587f-11e9-95b2-3517c3ea3381.png)

the settlement price should be feed price*1.02, now it is feed price.

**Comment by startailcoon** [comment]
Indeed, this view is missing the settlement offset for the asset.

**Comment by startailcoon** [comment]
Should fix following
- [ ] Settlement price should include correct settlement offset percentage
- [ ] Remaining settleable volume
- [ ] Notify user an estimated delay based on variables `Max. settlement volume each maintenance period`, `Already settled supply` and `Remaining settleable volume`.

**Comment by startailcoon** [comment]
Settlement price fixed to include % offset.
Also views current asset price % offset.

## Normal Asset
![image](https://user-images.githubusercontent.com/12114550/55683612-f6ceb900-5941-11e9-8138-fbff367709d8.png)

## GS Asset
![image](https://user-images.githubusercontent.com/12114550/55683632-1665e180-5942-11e9-8aae-4f683c5322b0.png)

Notifying on remaining settleable volume will require more work

**Comment by sschiessl-bcp** [comment]
Please refrain from finalizing the issue until merged
