### ISSUE TITLE
[1][dot5enko] Add support for market fee sharing

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2594]
**Is your feature request related to a problem? Please describe.**

`extensions` field of `asset_options` has a new type in bitshares-core 3.0.0: https://github.com/bitshares/bitshares-core/blob/3.0.0/libraries/chain/include/graphene/chain/protocol/asset_ops.hpp#L85, we need to
- update serialization https://github.com/bitshares/bitsharesjs/issues/45
- update UI to add support for the new extensions
  - [ ] "asset info" page
  - [ ] "create asset" page
  - [ ] "update asset" page
  - [ ] maybe transaction confirmation page
  - [ ] maybe block explorer page
  - [ ] maybe the "create order" panel in market page

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by startailcoon** [comment]
Blocked By bitshares/bitsharesjs#45

**Comment by dot5enko** [comment]
@sschiessl-bcp as i've took related bitsharesjs issue i've handle this too

**Comment by sschiessl-bcp** [comment]
Available in `bitsharesjs@3.0.0-rc4`

**Comment by startailcoon** [comment]
Ping @dot5enko

**Comment by dot5enko** [comment]
@startailcoon still work in progress

**Comment by sschiessl-bcp** [comment]
Work faster!

**Comment by dot5enko** [comment]
@sschiessl-bcp  for some reason `Available in bitsharesjs@3.0.0-rc4` not contains that serialization in it.

**Comment by dot5enko** [comment]
@startailcoon can we adjust the bounty to 2.5h? it was a lot of investigation and stuff needed cause asset create/update components are a little bit hardcoded/copypasted. Also bitsahresjs was a little bit fixed https://github.com/bitshares/bitsharesjs/pull/52 in collaboration with @sschiessl-bcp

**Comment by startailcoon** [comment]
> can we adjust the bounty to 2.5h?

Adjusted
