### ISSUE TITLE
[0.5] Vesting balance type

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2595]
**Is your feature request related to a problem? Please describe.**

`vesting_balance_object` has a new field `balance_type` in bitshares-core 3.0.0, to indicate the source of the balance. See https://github.com/bitshares/bitshares-core/blob/3.0.0/libraries/chain/include/graphene/chain/vesting_balance_object.hpp#L148-L170

We need to
- [ ] update the "vesting balances" page in bitshares-ui

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alexandr-masl** [comment]
Hi, if I understand correctly you want update the "vesting balances" page which is on screenshot below?
and if I'm right -  what values you want to publish from  the enum below ?
vesting_balance_type {   unspecified,
                                       cashback,
                                       worker,
                                       witness,
                                       market_fee_sharing };

**Comment by alexandr-masl** [comment]
![photo_2019-04-17_20-32-01](https://user-images.githubusercontent.com/43892027/56308396-ec859980-614f-11e9-9a56-014de5f91fae.jpg)

**Comment by sschiessl-bcp** [comment]
Yes, and this issue is already assigned d

**Comment by alexandr-masl** [comment]
oh, sorry)
