### ISSUE TITLE
[0.5][RC] - [Withdraw] Replace default empty result

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2597]
**Describe the bug**
When I enter for example BTC in the first box of Withdraw I get no results. 

**Expected behavior**
The search results of available coins should get listed after the first letter.

**Screenshots**
![BTC-withdraw](https://user-images.githubusercontent.com/40874087/55669682-9294f200-587a-11e9-9539-1d22a495bdaa.png)

**Desktop (please complete the following information):**
 - Firefox 66
- 2.0.190410-rc1

**Additional context**
I had the same problem with light client RC, but suddenly, after fiddling around and trying different times I got it to work. It does remember selected coins, but the initial search failed.

**Comment by startailcoon** [comment]
This seems like an issue due to the list having nothing to view. I've not seen this before. Would need some investigating.

**Comment by sschiessl-bcp** [comment]
It shows only coins you have available in the account. Did you do this on an empty account?

**Comment by froooze** [comment]
I bought extra some Sparkdex.BTC to find out, if it depends on this, but didn't change anything.

**Comment by startailcoon** [comment]
> It shows only coins you have available in the account. Did you do this on an empty account?

That would be the issue. I've tested it with an empty account and it display the same. We should replace the default behaviour to something that better suits our case.

**Comment by sschiessl-bcp** [comment]
> > It shows only coins you have available in the account. Did you do this on an empty account?
> 
> That would be the issue. I've tested it with an empty account and it display the same. We should replace the default behaviour to something that better suits our case.

Please give a description of the cases and how they should be handled when opening the modal

**Comment by startailcoon** [comment]
Currently the user receives a message that the list has no data when user has no withdrawable assets (ie, no assets that the gateways can handle).

The user should receive a clearer message that this is the case. 

![bild](https://user-images.githubusercontent.com/12114550/56229371-12d90580-607a-11e9-9fea-c6ff4242d7ce.png)
