### ISSUE TITLE
[0.5][MikhailKavalenka][RC] - [Scaled Order] - Problems with long asset names

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2599]
**Describe the bug**
The name boxes for price lower and upper only show a fraction when asset name is longer.  

**To Reproduce**
Go to scaled orders on Sparkdex.BTC / BTS

**Expected behavior**
Show full name in the box.

**Screenshots**
![scaled-orders-name](https://user-images.githubusercontent.com/40874087/55671590-df37f780-5891-11e9-8cc7-df82744821bc.png)

**Version:**
 - 2.0.190410-rc1

**Comment by froooze** [comment]
Column size and position should be the same for LIMIT and SCALED ORDERS.

**Comment by MikhailKavalenka** [comment]
@startailcoon , I can take this issue.

**Comment by startailcoon** [comment]
@MikhailKavalenka 👍

**Comment by sschiessl-bcp** [comment]
Done with #2611

Please use the PR template in the future

**Comment by MikhailKavalenka** [comment]
> Done with #2611
> 
> Please use the PR template in the future

Will do, thnx)
