### ISSUE TITLE
[.5] Add Openledger gateway assets to reference wallet

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#260]
Missing: SBD, PPY, STEEM, PPC, GOLOS, GBG

Light Wallet
![screen shot 2017-08-15 at 1 18 47 pm](https://user-images.githubusercontent.com/1254810/29335710-30f01e3e-81d1-11e7-8e5d-922ec7cdeea7.png)

Openledger Wallet
![screen shot 2017-08-15 at 1 18 24 pm](https://user-images.githubusercontent.com/1254810/29335709-30eb8022-81d1-11e7-89e7-4a9dd1463fb8.png)

**Comment by svk31** [comment]
This will probably get fixed by the PR #241

**Comment by wmbutler** [comment]
But will #241 happen by end of month? Just think we should manually add these in the meantime.

**Comment by svk31** [comment]
Yes, I have it almost ready to merge now.

**Comment by svk31** [comment]
Fixed by #270
