### ISSUE TITLE
[1.5][MikhailKavalenka] Include "Remaining Settlement Volume" in Settlement Modal 

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2602]
When a user wants to settle a specific volume, the network has a limit per maintenance period that is allowed for the asset to be settled. This should be included in the information for the user _if_ the limit is reached.

- [ ] Remaining settleable volume
- [ ] Notify user an estimated delay based on variables `Max. settlement volume each maintenance period`, `Already settled supply` and `Remaining settleable volume`.

Also part of https://github.com/bitshares/bitshares-ui/issues/1081

**Comment by MikhailKavalenka** [comment]
@startailcoon , I can take it.

**Comment by startailcoon** [comment]
That's great. It's all yours Mikhail

**Comment by OpenLedgerApp** [comment]
"Max. settlement volume of each maintenance period", "Remaining settleable volume" - where may we get these fields?
If a user enters a number greater than the limit where the notification should appear?here?
![image](https://user-images.githubusercontent.com/42674402/56742737-f9247600-677d-11e9-9c89-d3699d46e38d.png)


Where "Remaining settleable volume" should be displayed?

Now delay is displaying here. What is the "estimated delay", where may we get this value and where should it be displayed?
![image](https://user-images.githubusercontent.com/42674402/56742672-db571100-677d-11e9-9b38-ef2645833860.png)

Could you provide more info and sreenshots?

**Comment by startailcoon** [comment]
You can see the calculations for the remaining amount of settleble volume on the Assets details page currently. I'm not sure if this is done right, cause I've never seen this at any other value than 100%.

https://github.com/bitshares/bitshares-ui/blob/aebf2218e054d3ac3f7eee050e0fc00ac71714ed/app/components/Blockchain/Asset.jsx#L915-L933

This comes from the Assets that have the BitAsset option `maximum_force_settlement_volume`, documented here https://dev.bitshares.works/en/master/bts_guide/assets-faq.html?highlight=maximum_force_settlement_volume#market-pegged-assets

My understanding is that when `Maximum Force Settlement Volume` is reached, or the user makes it reach the max value, it will then overflow the remaining to the next period, causing the settlement to take more than one period (in case of USD 24hr).

You'll have to take in the following data of the assets to calculate this correctly:
- BitAsset
-- force_settled_volume
- BitAsset Options
-- maximum_force_settlement_volume
-- force_settlement_delay_sec
- BitAsset Dynamic Data
-- current_supply

## What to do when user settles more than remaning
When the user then tries to settle more than the remaining volume for the period the user should **not** be hindered to so, but be informed about this.

I propose the follwoing
- inform the user how much can be settled in one period
- inform the user how much remaining volume can be settled in the period
- if the period can't contain the settlement volume, add an information about it below the input, but don't hinder the form to be submitted.
