### ISSUE TITLE
[0.25][Translation]"SETTLEMENT PRICE" in the price feed data should be "Feed price"

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#2603]
![图片](https://user-images.githubusercontent.com/34892308/55683795-4d55ea80-5976-11e9-9d28-fb549da51bc4.png)

"SETTLEMENT PRICE" in the price feed data should be "Feed price".
https://github.com/bitshares/bitshares-ui/blob/c5edb498b6e2db7abdfb1f7974a02222378cd58e/app/assets/locales/locale-en.json#L772

**Comment by froooze** [comment]
*Settlement price* includes the discount from *force settlement offset* and is not the same as *feed price*.

**Comment by shulthz** [comment]
> _Settlement price_ includes the discount from _force settlement offset_ and is not the same as _feed price_.

I know, but there should be feed price.

**Comment by froooze** [comment]
Ok I see your argument now. Feed price suites better than settlement price.

**Comment by sschiessl-bcp** [comment]
Is the translation wrong, or should the complete column be exchanged to feed price?

**Comment by shulthz** [comment]
> 
> 
> Is the translation wrong, or should the complete column be exchanged to feed price?



> 
> 
> Is the translation wrong, or should the complete column be exchanged to feed price?

Translation wrong.

**Comment by sschiessl-bcp** [comment]
Task 
- [ ] Check that the displayed price is in fact the feed price for the column currently displayed as Settlement price
- [ ] Switch the column header to the correct key (feed price)

**Comment by alexandr-masl** [comment]
would like to take this one too.
thank you.

**Comment by alexandr-masl** [comment]
excuse me, i made all changes in code, but how can I reproduce the bug, to check the fix ? 
can't understand from the screenshot.
thank u.

**Comment by sschiessl-bcp** [comment]
Go to any SmartCoin (bitUSD, bitCNY) and check if the feed price is properly labeled and displayed as such

**Comment by alexandr-masl** [comment]
ok, thanks

**Comment by alexandr-masl** [comment]
this fix must be for all languages, or only for english, because in other languages  the same situations ?

**Comment by sschiessl-bcp** [comment]
Please send PR asap, preferably yesterday

**Comment by sschiessl-bcp** [comment]
Issue escalated https://github.com/bitshares/bitshares-ui/commit/a4d4960c2502a0018efe09998a3b24053c6c92d3
