### ISSUE TITLE
[alexandr-masl][0.25][Translation]"Force Settlement price" in the Publish feed should be "Feed price"?

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#2605]
![图片](https://user-images.githubusercontent.com/34892308/55684789-e2aaac00-5981-11e9-8156-297cad9276f3.png)

"Force Settlement price" in the Publish feed should be ""Feed price"?
https://github.com/bitshares/bitshares-ui/blob/c5edb498b6e2db7abdfb1f7974a02222378cd58e/app/assets/locales/locale-en.json#L763

**Comment by sschiessl-bcp** [comment]
Task is to:
 - [ ] Double check in the code that the value is properly pushed as the feed price (no meddling with offset whatsoever
 - [ ] Fix the translation by switching to the correct key

**Comment by alexandr-masl** [comment]
Hi, can i take this issue ?
thanks in advance .

**Comment by sschiessl-bcp** [comment]
It's yours. Since this is a release candidate blocker, please work on this asap

**Comment by sschiessl-bcp** [comment]
Also intereted in #2603?

**Comment by alexandr-masl** [comment]
yes, thank you.

**Comment by sschiessl-bcp** [comment]
Status?

**Comment by alexandr-masl** [comment]
It's done. also as 2603. I replaced in all languages, if you don't mind can push it.

**Comment by sschiessl-bcp** [comment]
PR against develop please

**Comment by sschiessl-bcp** [comment]
Please send PR asap, preferably yesterday :)

**Comment by alexandr-masl** [comment]
Got it 
will push today

**Comment by sschiessl-bcp** [comment]
Issue escalated https://github.com/bitshares/bitshares-ui/commit/a4d4960c2502a0018efe09998a3b24053c6c92d3
