### ISSUE TITLE
[0.1][froooze] Remove the "Help" entry from burger menu

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2609]
**Is your feature request related to a problem? Please describe.**
We have a lot of entries in the burger menu and we already have a good place on the right corner for the help button, which is also better visible.

**Describe the solution you'd like**
Remove the "Help" entry from the burger menu.

**Comment by startailcoon** [comment]
Haven't even thought about that. They do the same thing, +1 for this

**Comment by froooze** [comment]
Can I claim this?

**Comment by startailcoon** [comment]
@froooze it's yours

**Comment by startailcoon** [comment]
Got a PR for us @froooze ?

**Comment by froooze** [comment]
I wanted to do a PR this week.

**Comment by startailcoon** [comment]
Closed by the merger of PR https://github.com/bitshares/bitshares-ui/pull/2689
