### ISSUE TITLE
[1.5][svk] Restoring Wallet Defaults to Followed Account Not Owned By User

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#261]
When I restore my wallet into a fresh install of the light client it opens an account I am following but which I do not have private keys for.

Steps to Reproduce:
1) Follow a few accounts you don't own
2) Make sure only one account is "starred" and in the top pulldown to switch accounts
3) Backup wallet
4) Delete library files or install client on another computer, whatever to get a fresh install
5) Restore Wallet to fresh install of light client

In the pulldown list of accounts on the top right there are many accounts which I own and some which I don't own. For me a huge account appears as if it were mine. I can look through it like it is mine, in every detail, except I don't have the keys so I can't make any exchange.

To fix this, I need to go into Settings --> Accounts and Unhide everything except my main account then go to the b tab and down to Followed Accounts and make sure only my main account is starred to get it in the top menu then select it in the top menu to activate it. This will clear every other account from the top pulldown activate menu.

This is yet another bug related to wallet importation, deletion, and hiding/unhiding accounts that should be included in the epic discussed recently here: https://github.com/bitshares/bitshares-ui/issues/248#issuecomment-322556706

**Comment by wmbutler** [comment]
I wouldn't classify this as a bug but it is unexpected. Tell me which account should be the default account when importing your wallet. Is the default account the first one alphabetically? Anything obvious here?

**Comment by landry314** [comment]
That is a good question, I don't know which account should be the default account on a new wallet restore BUT I absolutely know it should NOT be SOMEONE ELSE'S account.

This is a bug because opening someone else's account like it was my own BY DEFAULT is very bizarre and certainly not as a user would expect.

**Comment by wmbutler** [comment]
Without a suggestion on how best to proceed, there isn't much actionable detail here.

**Comment by landry314** [comment]
expand the .bin format to include a flag for the last active account and set that one as active
OR 
upon restoring the wallet fetch balances and make the account with the highest balance the active one

that is two good ideas.

right now it CAN set as the active account a followed account which isnt even owned by the user of the wallet. that is not acceptable behavior.

**Comment by wmbutler** [comment]
Suggestion 2 sounds like a reasonable way to proceed.

**Comment by svk31** [comment]
I ended up fixing this as part of https://github.com/bitshares/bitshares-ui/issues/248.

**Comment by landry314** [comment]
I don't have the newest build yet where this was supposedly fixed but I still wanted to say that I found out how to reproduce this in a simpler way:

1) Make sure you are following other people
2) Switch to an account in your wallet
3) Go to Settings -> Accounts and then Hide that account WHILE IT IS THE ACTIVE ACCOUNT

BitShares will then automatically pick another account as the active one. For me it is ALWAYS "gamma-rabbit" for some reason, maybe because it has such a huge account value? I have no idea. I don't know what determines which account is chosen or how it works for other people.

**Comment by landry314** [comment]
This is not fixed. When I restore my wallet I get a followed account which is not my own becoming active by default.
