### ISSUE TITLE
[Inaccurate description] Inaccurate description of direct debit

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#2613]
> Setup a direct debit authorization for recurring payments. The authorization allows another account to transfer funds out of your account, with a limit on the amount for defined time intervals.

This is a Inaccurate description of direct debit, as you didn't give anyone the authorization or active Permissions to use your founds, you just make an autopay.

**Comment by sschiessl-bcp** [comment]
It's correct IMO since I am allowing another account to take a specified asset and specified amount out of my account every X time interval.

Would you have a suggestion how to formulate it differently?

**Comment by shulthz** [comment]
You send a specified asset and specified amount to another account every X time interval.

**Comment by sschiessl-bcp** [comment]
> You can send a specified asset and specified amount to another account every X time interval.

It does not happen automatically, in each interval you need to claim the transfer and specify the amount (up to the limit)

**Comment by shulthz** [comment]
> 
> 
> > You can send a specified asset and specified amount to another account every X time interval.
> 
> It does not happen automatically, in each interval you need to claim the transfer and specify the amount (up to the limit)

This maybe as a description.

**Comment by shulthz** [comment]
I know.
You make a withdraw permission, this permission allows another account to withdraw from your account, with a limit on the amount for defined time intervals.

**Comment by clockworkgr** [comment]
Imo description is accurate...this is literally what a direct debit is.

![image](https://user-images.githubusercontent.com/6826762/56347941-141b4700-61ce-11e9-80c7-69c7ee32cdab.png)

**Comment by shulthz** [comment]
Got it.
A direct debit or direct withdrawal is a financial transaction in which one person (or company) withdraws funds from another person's bank account.

https://en.m.wikipedia.org/wiki/Direct_debit

**Comment by startailcoon** [comment]
Based on these discussions I take this issue as completed without any required changes.
