### ISSUE TITLE
Worker Payouts for Submitting Bug Reports that Got Solved?

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#262]
I propose that the users who submit issues to this github which eventually get merged should get paid something for their time and effort out of the 201708-bitsharesui worker proposal.

Obviously the coders should get more, but the bug testing and reporting is work. Beta Testing and Program Design is real work.

Personally, I have submitted many bug reports and feature requests and commented on many others. I have not made any commits or submitted any code but I have spent hours of time finding bugs, organizing them, taking screenshots and editing them, creating github issues, and following through with them. I have thought about the structure of the program and how to improve it and tried to express that to the coders.

Can some of the BTS be given to the users who created new issues after they are solved and merged?

This could incentivize users to submit bug reports when they find them or feature requests when they have good ideas.

Does anyone agree?

**Comment by wmbutler** [comment]
People who submit bugs do not get paid. People who submit PR's that get accepted get paid.

**Comment by landry314** [comment]
Right, a coder who spends 30 minutes fixing an easy bug gets paid but someone who spends 10 hours researching and posting 20 relevant bugs and descriptions on how to reproduce gets nothing, sure, that is fair, closed.

**Comment by btsfav** [comment]
Current worker pays for bug fixes not bug reports
