### ISSUE TITLE
The feed price disappear in the UI of new release

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#2625]
#2605 #2603 maybe cause the bugs of feed price disappear， these two were only translation problem，don‘t need to change so much place.

**Comment by jieshuren** [comment]
I can't borrow money!

**Comment by shulthz** [comment]
> 
> 
> I can't borrow money!

https://wallet.bitshares.org/

**Comment by sschiessl-bcp** [comment]
Closed by https://github.com/bitshares/bitshares-ui/commit/1001b07a55b4ae1c9e2e4d3cb8e295a72285275f

Took 1.25
