### ISSUE TITLE
[2] Add a [Poll tab/function] to Voting page

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2626]
**Is your feature request related to a problem? Please describe.**
The Worker tab in Voting gets confusing, when it is misused for polls. 

**Describe the solution you'd like**
Ad a new **Poll tab/function** next to Witnesses, Committee and Worker.

A extra UI for creating a poll is also needed:
- Poll question
- Poll options
- Options per user
- Poll duration

**Comment by startailcoon** [comment]
Since we currently only display what data the chain holds on each of these tabs, in this case `Workers´, this would require a change in the core to incorporate some sort of poll feature.

Workers section are populated by the [Worker Object](https://dev.bitshares.works/en/master/components/lib_objects.html?highlight=worker#id31).

We are unable to create any extra UI for a feature that is non-existing.

**Comment by froooze** [comment]
Should I also open a ticket for the core?

**Comment by clockworkgr** [comment]
> Since we currently only display what data the chain holds on each of these tabs, in this case `Workers´, this would require a change in the core to incorporate some sort of poll feature.
> 
> Workers section are populated by the [Worker Object](https://dev.bitshares.works/en/master/components/lib_objects.html?highlight=worker#id31).
> 
> We are unable to create any extra UI for a feature that is non-existing.

technically we could agree with core (on cli_wallet) and our worker proposal flow to add a "Poll:" to the worker title if user has chosen to create a poll worker and just display them separately based on that.

**Comment by startailcoon** [comment]
> technically we could agree with core (on cli_wallet) and our worker proposal flow to add a "Poll:" to the worker title if user has chosen to create a poll worker and just display them separately based on that.

That would technically work. It would mean that everyone making a "Poll" through CLI would have to know about it. The UI could have a selector for it.

Needs to be approved by the core team.

**Comment by sschiessl-bcp** [comment]
I think this is a good idea as well, will add a new tab that simply does recognition and/or fixed list similar to Legacy proposals. Refine when core has agreed to something

**Comment by startailcoon** [comment]
Anything that goes into the new `Poll` tab should not show up on the worker tab though.

**Comment by sschiessl-bcp** [comment]
Due to heavier refactoring time needed is 4.5

**Comment by startailcoon** [comment]
👍
