### ISSUE TITLE
 Add [RUDEX.markets] to default markets

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2630]
**Is your feature request related to a problem? Please describe.**
We have a lot of new users, which can't find their favorite coin or don't realize there are also Rudex markets, because the problem #1792 still exists. 

The Rudex Gateway has the best uptime and one of the lowest fees, it is a shame to not add them to the defaults markets.

**Describe the solution you'd like**
Add the following markets to default markets:
- Rudex.EOS / BTS 
- Rudex.EOS / bitUSD 
- Rudex.WLS / BTS
- Rudex.SMOKE / BTS

**Comment by djlethalskillz** [comment]
100%

**Comment by startailcoon** [comment]
@froooze It's yours. Supply a PR and we'll add them. 
I agree with that we should give RuDEX a bit more love.

**Comment by froooze** [comment]
I wanna claim 0.5 for doing some research and removing dead coins.
#2693

**Comment by startailcoon** [comment]
> 
> 
> I wanna claim 0.5 for doing some research and removing dead coins.
> #2693

Approved

**Comment by startailcoon** [comment]
Was this work done or was it an overlap of something else? I see the PR was closed.

**Comment by froooze** [comment]
@startailcoon: Yes this overlapped with another PR!
