### ISSUE TITLE
[3] 3.0.0 call_price field

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2634]
**Is your feature request related to a problem? Please describe.**

Margin positions' `call_price` field will be always `1` after the consensus upgrade (23rd Apr 2019). If we still want to show a "call price" field in UI, we should calculate using other fields. See https://github.com/bitshares/bitshares-core/wiki/Testing-HF-1270:-Effects-of-MCR-Change-on-Call-Price#-3-feed-publisher-changes-mcr-to-20

> The call_price field of every loan will always appear with an effective price of 1.0 after the hardfork. The call_price of the bitasset is now left as a calculation to client software to calculate. The call price of the bitasset denominated in the collateral token (e.g. bitCNY/BTS) should be calculated as
>```
>call_price = (collateral × MCR) ÷ debt
>```

Related pages:
- [x] account - debt positions
![image](https://user-images.githubusercontent.com/9946777/56592437-fd6c5a00-65ea-11e9-9ebf-bb558955010e.png)

- [x] asset - debt positions
![image](https://user-images.githubusercontent.com/9946777/56592512-1d9c1900-65eb-11e9-8c3e-84e6981e3139.png)

- [x] market page - buy/sell orders
![image](https://user-images.githubusercontent.com/9946777/56592289-abc3cf80-65ea-11e9-983f-f5a7aa91d391.png)

- [x] market page - call limit
![](https://user-images.githubusercontent.com/34892308/56587318-e3933d00-6613-11e9-9238-965d4400da13.png)

- [ ] other pages

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sschiessl-bcp** [comment]
What's the reason for this change?

**Comment by clockworkgr** [comment]
does it matter? it's not like core can be changed back right now :)

**Comment by sschiessl-bcp** [comment]
Matters for my curiousity

Am 23. April 2019 11:41:39 schrieb Alex Megalokonomos 
<notifications@github.com>:

**Comment by clockworkgr** [comment]
curiosity killed the cat

**Comment by startailcoon** [comment]
Will look at this today

**Comment by abitmore** [comment]
> What's the reason for this change?

Because
1. we can't update it every time when MCR changes, we will not use it anymore in core after the upgrade, if leave it unchanged, the value would be probably inconsistent (aka wrong), see https://github.com/bitshares/bitshares-core/issues/1270
2. being always `1` has slightly performance than leaving it unchanged in the long run

**Comment by startailcoon** [comment]
This should now be resolved in PR

**Comment by clockworkgr** [comment]
good job @startailcoon ...is it on staging or develop yet so we can test out if everything appears normal?
