### ISSUE TITLE
[10] Basic HTLC support

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2643]
This issue is to create a simple HTLC overview and possibility to create / redeem, which can be used for any use case outside of trading.

Raw integration of HTLC was done with #2589, for simple usage please find `app/actions/HtlcActions.js`.

Additional usage for dead simple cross-chain trading, preferably built-in the exchange directly will be done in another issue.

The general layout should be like Direct Debit Authorizations with following adjustements (copy code, do not reuse):
 - [ ] Add route `/htlc`
 - [ ] Button in header says: "Create HTLC"
 - [ ] Create HTLC modal
    - Fields Recipient (account), Amount (amount and asset), Preimage (see below), Expiration (datetime), Fee
    -  Preimage contains two fields (hash and size) and a button "Enter secret preimage". If the user pushes that button he is prompted to enter a string that is the secret, and then the hash and the size is being calculated and filled in the form fields. Add a method to `HtlcActions` called `calculateHash` that takes a string (the secret) and returns the hash and size. 
 - [ ] Extend HTLC modal: Reuse create modal, allow only to change the expiration (must be bigger than before)
 - [ ] Redeem HTLC
    - Fields: Sender (prefilled, not editable), Recipient (prefilled, not editable), Preimage (string)
 - [ ] Columns in overview: #, from, to, amount, hash, expires, actions
   - [ ] Actions for the recipient "Claim"
   - [ ] Actions fhe sender: "Extend"

**Comment by dot5enko** [comment]
seems like i can take this too, like a person who integrated htlc. but if there's anyone interested more than me he could take it :)

**Comment by startailcoon** [comment]
If you're willing, I'll assign you to this task @dot5enko

**Comment by startailcoon** [comment]
Looks like @sschiessl-bcp already assign this task to himself.

**Comment by sschiessl-bcp** [comment]
Yes I did. See progress here https://github.com/blockchainprojects/bitshares-ui/pull/105#issuecomment-490817743

**Comment by startailcoon** [comment]
Great, report back the results here when completed and we'll discuss.

**Comment by sschiessl-bcp** [comment]
Time spent is 18 due to needed refactoring, adding of spotlight and changes for UX due to user feedback
