### ISSUE TITLE
[.5] When creating asset - edit middle of 'symbol' and 'asset name' fields forces append mode

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#265]
Hey,

I've only tested this on OpenLedger, but when I was creating the 'pololostkeys' token, I noticed that the 'symbol' and 'asset name' fields don't allow you to edit the middle of text, instead it forces you to append to the existing text after the first character. 

Example term 'TESTING' has word 'MIDDLE' typed between the S & T. The result is 'TES**M**TING**IDDLE**' instead of 'TES**MIDDLE**TING'.

![image](https://user-images.githubusercontent.com/15861527/29361967-b44a984e-8281-11e7-9b56-3435212ae05e.png)

---

This is a minor issue, but was mildly annoying.

**Comment by wmbutler** [comment]
Legitimate bug. Easy fix.
