### ISSUE TITLE
Add HTLC to fee schedule

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2652]
Follow up of #2589

Add HTLC operations to https://wallet.bitshares.org/#/explorer/fees

**Comment by sschiessl-bcp** [comment]
@dot5enko ?

**Comment by dot5enko** [comment]
@sschiessl-bcp hm, i've already added them

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp hm, i've already added them

Thanks, that's correct. I fixed some translation issues.
