### ISSUE TITLE
[0.5] Light client freeze with [German language]

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2653]
**Describe the bug**
After browsing to Exchange (German language) the client freezes. 

**To Reproduce**
Change language to German, browse to "Börse" and click on several markets.

**Expected behavior**
No freeze.

**Screenshots**
![Börse-blank](https://user-images.githubusercontent.com/40874087/57049338-ee834880-6c77-11e9-8dc5-4ffdcd37334d.png)

**Desktop (please complete the following information):**
 - MX-Linux
 - Light Client: 190424

**Additional context**
Problem could also happen on "Übersicht" but not as likely.

**Comment by sschiessl-bcp** [comment]
Only crashes in light, or also webwallet?

**Comment by froooze** [comment]
Webwallet also freezes (Chromium).

**Comment by sschiessl-bcp** [comment]
Can you please tell me exactly what you are clicking on?

**Comment by froooze** [comment]
Click on a market Open.EOS / BTS

**Comment by froooze** [comment]
Other Gateways don't have the problem Open.LTC / BTS or Open.DODGE also crash.

**Comment by startailcoon** [comment]
Unescaped percentage in locale file made the translation fail to render
