### ISSUE TITLE
[1][OpenLedgerApp] Show target collateral ratio in "my margin positions" page

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2659]
**Is your feature request related to a problem? Please describe.**
Unable to see target collateral ratio of my debt positions in my margin positions page. Need to click adjust icon to check.

**Describe the solution you'd like**
Show target collateral ratio directly in "my margin positions" page (add a column).

**Describe alternatives you've considered**

**Additional context**

**Comment by startailcoon** [comment]
Good suggestion, should be there indeed.

**Comment by OpenLedgerApp** [comment]
@startailcoon, we can take this one.

**Comment by startailcoon** [comment]
@OpenLedgerApp it's yours.

This sections is getting quite packed with information right now, but I'd suggest we add this to the page for now and look at optimizing the section later in a new task. It would need some looking at.
