### ISSUE TITLE
My Markets should only show markets I care about

### ISSUE THREAD

**Issue by destenson** [bitshares/bitshares-ui#266]
"My Markets" is a misleading title since I can't easily add markets to that list, and none of the defaults can be removed from it.

**Comment by grctest** [comment]
You can add markets to your 'favourite' trading pair tab, that's about it in terms of 'my market' personalization. I do agree that 'my markets' is more of 'featured markets' than your personalized trading pair tabs.

**Comment by wmbutler** [comment]
The Markets needs a full UI treatment. This isn't really an actionable issue.
