### ISSUE TITLE
[0.5] No memo option in Withdraw

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2661]
**Describe the bug**
The Withdraw function has no memo field.

**To Reproduce**
Burger menu -> Withdraw -> select any coin

**Expected behavior**
A memo field after address 

**Screenshots**
![no-memo](https://user-images.githubusercontent.com/40874087/57178922-15a86880-6e78-11e9-9d75-7f736c81d57e.png)

- MX-Linux
- Light Client: 190424

**Comment by startailcoon** [comment]
Memo field is used by the gateway operator and should not be changed by the user directly.

**Comment by froooze** [comment]
This is valid, because when I wanna withdraw coins to another exchange/gateway I need a personal memo, like in legacy withdraw. 

Memo for withdraw is essential!

**Comment by sschiessl-bcp** [comment]
> Memo field is used by the gateway operator and should not be changed by the user directly.

Not completely true. It depends on the support of the gateway. Some do allow that user specifies the memo, this is dynamically added. Does Rudex offer memo in Legacy?

**Comment by froooze** [comment]
Rudex offers memo in legacy and others too, which was the only way to send my EOS to the exchange.

**Comment by startailcoon** [comment]
Thanks for the information about these edge cases. I wasn't aware of them. 

# Task

- Investigate cases when `Memo` is required to be specified by the user on withdraw
  - Includes all current Gateways and their assets
- Implement edge cases in `Withdraw Modal`
- Add new gateway setting for the cases to follow internal standard

**Comment by startailcoon** [comment]
Will take this task

**Comment by sschiessl-bcp** [comment]
Can you put it in a (then considered binding) Milestone, or release it?

We already have code for that, I've seen the memo popping up in new Modal. Should be a (possibly stupid) small error.

**Comment by startailcoon** [comment]
### Solved

Sorry for the delay. It was indeed a simple missing flag that didn't enable memos on assets that had the flag "supportsMemos".

![image](https://user-images.githubusercontent.com/12114550/60295368-d6504280-9923-11e9-8e5b-dfdf62579c51.png)
