### ISSUE TITLE
Transfer open.EOS to Simple EOS not credited?

### ISSUE THREAD

**Issue by HB1github** [bitshares/bitshares-ui#2666]
Transfer open.EOS to Simple EOS not credited?

#20: TRANSFER |  
-- | --
From | hbscc
To | openledger-dex
Quantity | 9.339655 open.EOS
Memo / Message | eos:gmzdqmrqgene
Fee | 0.48132 BTS

**Comment by froooze** [comment]
> My account is hacked!
I don't would call this a hack, it is more a scam you accepted yourself. 
#2658

**Comment by froooze** [comment]
You accepted the hack! 
#2658

**Comment by startailcoon** [comment]
A few questions, 

- Did you use the "Withdraw" feature to withdraw your open.EOS assets to your EOS account?
- Are you the owner of the EOS account `gmzdqmrqgene`?

As `openledger-dex` is the official account for withdrawing funds from the Open Ledger exchanger, your assets are sent to the supplied account.
