### ISSUE TITLE
[blockchained-fond][2.0.190410-rc1] Review Language

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2674]
https://github.com/bitshares/bitshares-ui/issues/2586#issuecomment-490830021

It was agreed in telegram that Blckchnd does review of the Russian translation, this is the missing issue for those efforts. Transifex was open to anyone and mistakes were done by other translators which were also corrected/reverted by Blckchnd.

Initial bounty for review was stated here https://github.com/bitshares/bitshares-ui/issues/2558#issue-427207702

**Comment by sschiessl-bcp** [comment]
From old issue

> we spent 16 hours on Russian translation and review of mistakes that cause by previous translators 

@DimaBLCKCHND 
Please break it down for time needed to correct those 69 keys with mistakes vs reviewing everything

**Comment by sschiessl-bcp** [comment]
The russian translation was generally quite flawed and re-translations were necessary.

Here is a breakdown of necessary translation
![image](https://user-images.githubusercontent.com/33128181/57448245-2b8fa200-7259-11e9-9998-04d11d96684a.png)

 - Correcting the mistakes should be paid according to the translation bounty (0.15 per word) since actual hours for that are not known. From the last issue https://github.com/bitshares/bitshares-ui/issues/2586#issue-429618171 there were 6513 words translated in the review process, which is a bounty of `6513 * 0.15 = 7.82`

 - Reviewing the translation has a bounty of 4 (see https://github.com/bitshares/bitshares-ui/issues/2558#issue-427207702)

Together we have a bounty of rounded `12`. Please confirm or state otherwise @DimaBLCKCHND

**Comment by DimaBLCKCHND** [comment]
I confirm

**Comment by sschiessl-bcp** [comment]
Marked for payout in Sprint 190510.

**Comment by sschiessl-bcp** [comment]
@DimaBLCKCHND Is blockchained-fond the bitshares payout account?

**Comment by DimaBLCKCHND** [comment]
@sschiessl-bcp yes it is `blockchained-fond`
