### ISSUE TITLE
[5] ANTify, restyle and refactor voting overview

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2677]
The new voting section should only using ANT style-guide components.

Here is a rough mockup of how I imagine the positioning

![image](https://user-images.githubusercontent.com/33128181/58248620-e725fb00-7d5c-11e9-9a33-268526ac0fb6.png)

- [ ] Proxy button and Save/Reset go in an area above the tables. 
- [ ] Where proxy is now we need a filter button
- [ ] The coloring and margins of the mockup need to be ignored, use defaults from style guide
- [ ] All functionality must remain
- [ ] Make sure unnecessary re-rendering are avoided
- [ ] Use a RadioGroup for the Proposed / Active / Expired, like seen here https://codepen.io/pen/?&editable=true&editors=001
- [ ] Tables should be transitioned to ANT table as well
   - [ ] allow sorting on id, description, votes, needed, duration (sort start date) and daily pay.
   - [ ] dataSource of table should only contain raw data, use render for styling
- [ ] Make sure the Table is responsive

**Comment by froooze** [comment]
Can we add a filter box for voting to find things faster?

**Comment by startailcoon** [comment]
Added a rough estimate of this task. Nice work!

**Comment by sschiessl-bcp** [comment]
Bounty request in PR https://github.com/bitshares/bitshares-ui/pull/2741#issue-284542766
