### ISSUE TITLE
[1] Add cumulative amount in margin positions table

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2684]
**Is your feature request related to a problem? Please describe.**
https://wallet.bitshares.org/#/asset/USD
![image](https://user-images.githubusercontent.com/9946777/57586653-2486bf00-74f9-11e9-923b-b59c08f885ee.png)

I think it's good to have a "cumulative debt" column and probably a "cumulative collateral" column.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by startailcoon** [comment]
To avoid making the table to wide, may I suggest we use a mouse over tooltip that can display the cumulative debt or collateral instead?

**Comment by abitmore** [comment]
How about responsive design? I don't know what if the user has no mouse.

**Comment by startailcoon** [comment]
A responsive design would be good, but not sure how we should design it. We should have it in mind for the next design. 

However, I've pushed an update to allow for a tool-tip. A user without a mouse can still get the tool-tip by clicking on the field for collateral or debt.

**Comment by abitmore** [comment]
Honestly speaking, I don't like the mouse-over tooltip. The reason why I (as a trader) want a cumulative debt column is to quickly find out info: if I place an order to buy into the margin calls, E.G. buy BTS with 100K bitUSD, where my order will stop at.

Actually, this table has no such info right now because TCR isn't taken into calculation, total debt or collateral of a position is different than trade-able debt or collateral. Looks like we need to reopen https://github.com/bitshares/bitshares-ui/issues/1576.

**Comment by startailcoon** [comment]
Thanks for your feedback abit. I'll take another look at it to see what we can do to visualize it

**Comment by froooze** [comment]
How about a market depth chart with collateral and debt as parameter?

**Comment by startailcoon** [comment]
Does this look more like what you're looking for?

I've removed some of the Asset details, as I think it's unnecessary to  type them out in the headers, as the backing asset is the collateral. This could be explained better with a tooltip if anything needs to be cleared. TCR is explained by a tooltip as well.

![image](https://user-images.githubusercontent.com/12114550/57648499-f15e3180-75c5-11e9-893a-db14d7cf2dc0.png)

@froooze interesting idea. Could be another tab to view a chart for that.

**Comment by froooze** [comment]
@startailcoon: I thought to put the graphic before the table.

Why not make the table clickable? Standard view with COLLATERAL and DEBT, and by clicking at any point, I get TOTAL COLLATERAL and TOTAL DEBT instead?

**Comment by abitmore** [comment]
@startailcoon that table now looks a bit confusing. Sorry. Wish a UX expert join the discussion.  @gibbsfromncis ?

**Comment by froooze** [comment]
@abitmore: Yes looks confusing now, what about my solution?

**Comment by abitmore** [comment]
@froooze click to toggle the column names and data? Sounds interesting, but I don't know if it's good UX, could be confusing as well.

**Comment by froooze** [comment]
@abitmore: If someone clicks without knowing, he will just click once again and get around it. 
No extra space is needed.

**Comment by gibbsfromncis** [comment]
@abitmore @froooze to be honest I'm not sure we will come to this point with new design soon. If it is really important feature we should implement it on old design. 

I see the potential solution is to use fixed columns: https://ant.design/components/table/#components-table-demo-fixed-columns 

If screen is too small to display any data we can make a scroll inside the page and make important columns fixed.

**Comment by froooze** [comment]
@abitmore & @startailcoon: We have a consensus to not use extra space and switch between standard and cumulative view?

I see two options to switch between the two views
1. Make columns clickable
2. Add a cumulative switch on top of the table

**Comment by startailcoon** [comment]
Making it switchable between cumulative and standard view sounds to me like the most obvious plan, yes.

It would make it easier to overlook, compared to my previous post.

**Comment by startailcoon** [comment]
Will make a new commit in a few days and post.

**Comment by startailcoon** [comment]
See issue #2736 for details
