### ISSUE TITLE
Obtain TEST asset

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2687]
I propose to take over the asset TEST and use it for the headline of #2679 initially.

@gibbsfromncis has accidently created this asset a while back and paid `5,789.18749 BTS` for it (fee pool etc. already substracted). If I create a new 5 digit asset now, this would cost the UI worker `1263.03811*0.2 = 252.60`, which would be significantly less. My reasoning is as follows

 - The UI does not care which asset is being used to show notifications
 - The `TEST` symbol is also used on the testnet, and might be used for scam attempts if gibbs hadn't registered it. It should belong to the community

This issue comes with a cost of `5,789.18749 BTS` which are to be paid out after proof of ownership transfer.

New owner for TEST asset `bitshares.org-notifications`. 
 - Active multi-sig 2/2
    - BitShares UI team (represented by bitshares account bitshares-ui-team)
    - Owner of bitshares.org
 - Owner multi-sig 3/4
    - BitShares UI team (represented by bitshares account bitshares-ui-team)
    - Owner of bitshares.org
    - Committee Account
    - Witness Account

@dls-cipher Thoughts? If agree, what account should it be for you?

**Comment by startailcoon** [comment]
I agree. 

TEST asset should be obtained to the community and can be used for the purpose of on-chain notifications, for example.  The UI worker is the payee account and is part owner together with the community and activity on the asset should be shared like proposed between UI and Bitshares.org.

**Comment by abitmore** [comment]
I thought we had reimbursed the 5K BTS asset creation fee to @gibbsfromncis. @xeroc can you confirm?

**Comment by abitmore** [comment]
On 2019-01-10, block 33873691, txid afb204b49f22f57a3ec6b5a3bd1c5bd695be1f1d (tx_in_block=31), there was a proposal created for the committee to "buy" the `TEST` asset from @gibbsfromncis , but it seems @gibbsfromncis didn't approve it so it expired eventually. So it's still up to @gibbsfromncis to make a decision.

**Comment by gibbsfromncis** [comment]
@abitmore yeah, Xeroc contacted me to approve proposal but I miss it. Anyway, I'm still ready to provide all rights for `TEST` asset for community on the same  requirements - if community ready to compensate fee I paid for this asset creation without any profit for my self.

**Comment by abitmore** [comment]
@gibbsfromncis thank you.

In the proposal @xeroc created, the reimbursed fee was `4,631.34999 BTS`. 

On block 31340011, txid cc54108010775464a008091b673c5277d58191c9, 2018-10-13T23:26:57 UTC gibbs-from-ncis created asset 'TEST'    (Fee: 11578.37498 BTS). 50% of total fee, aka 5789.18749 BTS went into asset fee pool then claimed by the owner later, 40% (4631.34999) went to referral program (I guess `onboarding.bitshares.foundation` got it), 10% (1157.83750) is the actual fee.

Assuming `onboarding.bitshares.foundation` will put the referral income in good use, I think reimburse `5789.18749 BTS` is fine.

**Comment by sschiessl-bcp** [comment]
I'm glad our numbers match :)

**Comment by gibbsfromncis** [comment]
@abitmore 👍 just let me know when I should move rights and whom

**Comment by dls-cipher** [comment]
1) appreciate the respect and trust given to Move Institute (Zavod Premik) as owner of bitshares.org
2) @gibbsfromncis - +5
3) BitShares account to be added for multi-sig: zavod.premik 

Chee®s

**Comment by sschiessl-bcp** [comment]
I have modified the account `bitshares.org-notifications`. I synced with Fabian who suggested in should be a 2/3 owner permission.

Please check @dls-cipher that the permissions are correct.

Once confirmation is done, asset can be transferred.

 @gibbsfromncis the easiest way would be you transfer ownership and get reimbursed through this issue. Is that acceptable?

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp yep.

**Comment by dls-cipher** [comment]
@sschiessl-bcp - Confirmed and approved on blockchain. 

Thanks and chee®s

**Comment by gibbsfromncis** [comment]
@sschiessl-bcp transfered. 

Please, include additional `252.60273 BTS` as fee for rights transfer

Transaction - https://wallet.bitshares.org/#/block/37460534/18

**Comment by sschiessl-bcp** [comment]
Confirmed bounty 252.60273 BTS + 5,789.18749 BTS

**Comment by gibbsfromncis** [comment]
`Total`: `6,041.79022 BTS`
