### ISSUE TITLE
Asset details allow for HTML

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#269]
Just a quick check - An asset issuer is allowed to use HTML within their asset details, right?

Because it's possible to do so within the web/light wallets: https://openledger.io/asset/HERTZ

On cryptofresh, the HTML is escaped and shows the true asset details:
http://cryptofresh.com/a/HERTZ

**Comment by wmbutler** [comment]
I checked it on the light client and the answer is yes.

**Comment by grctest** [comment]
External javascript seems blocked though it could just be because the UI uses react. The script tags were not however excluded from the asset details, perhaps an external site like cryptofresh or the new block explorers will have to prevent this from executing on their own websites.

You are however able to import your own CSS from an external source (though it is blocked by some, not all web wallets). Couldn't you use CSS to perform cross site scripting attacks? At the very least, perhaps it'd be possible to make basic changes to the theme of the wallet whilst viewing the asset details page?
