### ISSUE TITLE
[1][OpenLedgerApp] Delete button for search/filter input

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2698]
**Is your feature request related to a problem? Please describe.**
The old user interface search had a X to clear the input.

**Describe the solution you'd like**
Adding a X to delete the search input.

**Comment by startailcoon** [comment]
Can you give a place in the app where this is?

**Comment by froooze** [comment]
Explore -> Assets -> Filter ...
Exchange -> MY MARKET -> Filter

**Comment by startailcoon** [comment]
# Task

- Add clear button on input
- Make it an optional item (ie. `onClearButton: ...` or the like)

Not sure if this requires changes to the style-guide base or can be implemented directly.

cc @gibbsfromncis

**Comment by OpenLedgerApp** [comment]
@startailcoon, I can take this one.

**Comment by sschiessl-bcp** [comment]
iirc the little magnifying glass is added via an addon to the input in the UI, not styleguide.
![image](https://user-images.githubusercontent.com/33128181/58424123-fecfed00-8096-11e9-8402-b21d37278625.png)

The "x" should either appear non intrusive within the input, or replace the magnifying glass when content is present. The last option is only possible if the magnifying glass is not used as a button somewhere.

This issue should result in a new "SearchInput" component or something, if that does not exist yet.

**Comment by startailcoon** [comment]
Making a non intrusive `X` to the right would be the most common usage I assume. Not sure if we should replace the magnifying glass, could be quite confusing.

Making a new component as `SearchInput` could be a good idea, to make it more search specific for these cases.
