### ISSUE TITLE
Electron light wallet --data-dir param

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#27]
_From @testzcrypto on December 10, 2015 12:57_

Please add possibility to specify electron light wallet data directory where to keep wallet data. In current version all data stores at %APPDATA%\BitShares2-light (under Windows).

**Related links:**
https://www.chromium.org/user-experience/user-data-directory
https://github.com/atom/electron/blob/master/docs/api/app.md#appgetpathname
https://github.com/atom/electron/issues/647
https://github.com/atom/brightray/pull/89

_Copied from original issue: cryptonomex/graphene-ui#602_

**Comment by svk31** [comment]
_From @wmbutler on December 29, 2015 16:6_

I'm not convinced this is an issue. @svk31 ?

**Comment by svk31** [comment]
I have no idea how the electron stuff works, @valzav can you take this one please?

**Comment by valzav** [comment]
I'll take a look if it's doable.
