### ISSUE TITLE
[froooze][0.1] Low latency as integer in Nodes

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2701]
**Describe the bug**
The low latency number is not a integer as in the footer. 

**To Reproduce**
Go to Nodes

**Expected behavior**
The interface should display the ms numbers as integer.

**Screenshots**
![latency](https://user-images.githubusercontent.com/40874087/57990029-efeba800-7aa2-11e9-8073-0e04dc93b32a.png)

**Additional context**
The time in seconds, needs still two decimal places.

**Comment by froooze** [comment]
Can I claim this ?

**Comment by sschiessl-bcp** [comment]
> Can I claim this ?

Sure, it should in AccessSettings.jsx.

**Comment by genievot** [comment]
Thanks to @sschiessl-bcp for pointing the file, 
Can be solved with changing at line 193 to
let pingInMs = parseInt(this.props.node.ping);

**Comment by startailcoon** [comment]
@froooze ping

**Comment by froooze** [comment]
@startailcoon: @genievot can do a pull request here?

**Comment by froooze** [comment]
Already implemented.
