### ISSUE TITLE
[13][Wallet Redesign] Dashboard first draft

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2702]
This task is about to make a first draft of a design for Dashboard - https://projects.invisionapp.com/share/ZHRXAC4JBRF#/screens in Light Theme to understand find the best stylistics we want.  

Our team decided to use similar stylistics to this - https://dribbble.com/shots/4918360-DASHBOARD

Requested Estimate - 15h

This estimate includes:
1) New design of a Dashboard Screen
2) Basic style-guide of components needed to delivery Dashboard

**Comment by gibbsfromncis** [comment]
There are 6 versions: https://www.figma.com/proto/IiodFPl5EckMtBbEHdBjyO3n/BTS-DASHBOARD?node-id=7%3A364&viewport=2009%2C246%2C0.38582053780555725&scaling=min-zoom

Please pay attention to the following things on each version and give your answer:

1. Left Side Bar
- [ ] Dark 
- [ ] Light (Page # 6)
2. Left Side Bar Corners 
- [ ] Rounded (Page # 5)
- [ ] Not Rounded (Page # 1)
3. Widgets Shadow
- [ ] With shadow (Page # 4)
- [ ] Without Shadow (Page # 3)
4. Widgets Border
- [ ] With Border (Page # 2)
- [ ] Without Border (Page # 3)
5. Widgets border-radius
- [ ] 15px (Page # 4)
- [ ] 4px (Page # 3)
6. Input / Button box radius (Take a look on Quick Deposit widget)
- [ ] 15px (Page # 3)
- [ ] 4px (Page # 4)

**Comment by startailcoon** [comment]
1. Left side bar looks good in light/dark. Nothing special there. Personally not a fan of light themes, but I imagine it's as good as it can be in light?
2. Don't like the rounded corner and don't see the need for one. More clean without it.
3. I like the light shadowed boxes better.
4. With borders, personally. Makes them stand out better/easier from the background, with the shadow.
5. Larger rounded corners look good imho.
6. Smaller rounded corners look best, the larger rounded corners doesn't look good at all.

**Comment by abitmore** [comment]
IMHO we don't really need a new look, if only for the look. What we more need is good/better UX, which should be easy to use and easy to understand. Or say, business flow is more important.

To do a re-design, before drawing pages (Visual Design), my questions would be: what do we want exactly? For example, what parts are hard to tweak in our current design but we badly need them?

The design Methodologies proposed by Scorum team would be good practice: https://bitsharestalk.org/index.php?topic=26734.0
> Our desk research shows that BitShares has a lot of UX and UI problems: too difficult for new users, lacking in tools for experienced traders, visually outdated and has accessibility issues. The results are obvious: we see low traffic on BitShares Exchange while centralized and more simple exchanges grow in popularity. In addition, the crypto world has inherent gaps in new users adoption experience.
>
>To solve these problems a huge amount of work should be done: from detailed UX research to interactive design by applying modern design patterns and accessibility requirements.
>
>*    Methodologies are important. We will do more than just redesign the current screens, we are going to rebuild the entire user experience by applying Service Design – a multidisciplinary approach to developing services that deliver more value for both customers and service providers with user research and collaboration with the community at the heart of the process.
>*    UX research is an important investment. It encompasses gathering and analyzing data in a way to improve usability, using a set of research techniques (interviews, usability tests, card sorting). Large companies like Facebook (blog), Amazon and AirBnB (blog) are now insisting on research driven user experience work to be carried out on their websites, Apps and UI’s before final visual design starts.
>*    To offer the most value from our proposal, in addition to design mockups we are going to create a Bitshares design system – a collection of reusable components guided by clear standards that can be assembled together to build any number of applications. Companies like Uber and AirBnB value the importance of design systems.

>UX/UI Design: Service Design Approach (proven methodology by design-led companies like Facebook and Uber) focused on user research and collaboration with community, that consists of following phases:
>
>*    Research Phase – from surveys among users to Ideal Customer Journey Map
>*    UX Design Phase – from exchange wireframes to UX design testing
>*    Visual Design Phase – from definition of Bitshares visual language to interactions

**Comment by clockworkgr** [comment]
> IMHO we don't really need a new look, if only for the look. What we more need is good/better UX, which should be easy to use and easy to understand. Or say, business flow is more important.
> 
> To do a re-design, before drawing pages (Visual Design), my questions would be: what do we want exactly? For example, what parts are hard to tweak in our current design but we badly need them?
> 
> The design Methodologies proposed by Scorum team would be good practice: https://bitsharestalk.org/index.php?topic=26734.0
> 
> > Our desk research shows that BitShares has a lot of UX and UI problems: too difficult for new users, lacking in tools for experienced traders, visually outdated and has accessibility issues. The results are obvious: we see low traffic on BitShares Exchange while centralized and more simple exchanges grow in popularity. In addition, the crypto world has inherent gaps in new users adoption experience.
> > To solve these problems a huge amount of work should be done: from detailed UX research to interactive design by applying modern design patterns and accessibility requirements.
> > 
> > * Methodologies are important. We will do more than just redesign the current screens, we are going to rebuild the entire user experience by applying Service Design – a multidisciplinary approach to developing services that deliver more value for both customers and service providers with user research and collaboration with the community at the heart of the process.
> > * UX research is an important investment. It encompasses gathering and analyzing data in a way to improve usability, using a set of research techniques (interviews, usability tests, card sorting). Large companies like Facebook (blog), Amazon and AirBnB (blog) are now insisting on research driven user experience work to be carried out on their websites, Apps and UI’s before final visual design starts.
> > * To offer the most value from our proposal, in addition to design mockups we are going to create a Bitshares design system – a collection of reusable components guided by clear standards that can be assembled together to build any number of applications. Companies like Uber and AirBnB value the importance of design systems.
> 
> > UX/UI Design: Service Design Approach (proven methodology by design-led companies like Facebook and Uber) focused on user research and collaboration with community, that consists of following phases:
> > 
> > * Research Phase – from surveys among users to Ideal Customer Journey Map
> > * UX Design Phase – from exchange wireframes to UX design testing
> > * Visual Design Phase – from definition of Bitshares visual language to interactions





> This first draft took `13 hours`:
> 
> There are 6 versions: https://www.figma.com/proto/IiodFPl5EckMtBbEHdBjyO3n/BTS-DASHBOARD?node-id=7%3A364&viewport=2009%2C246%2C0.38582053780555725&scaling=min-zoom
> 
> Please pay attention to the following things on each version and give your answer:
> 
> 1. Left Side Bar
> 
> * [x]  Dark
> * [ ]  Light (Page # 6)
> 
> 1. Left Side Bar Corners
> 
> * [ ]  Rounded (Page # 5)
> * [x]  Not Rounded (Page # 1)
> 
> 1. Widgets Shadow
> 
> * [x]  With shadow (Page # 4)
> * [ ]  Without Shadow (Page # 3)
> 
> 1. Widgets Border
> 
> * [x]  With Border (Page # 2)
> * [ ]  Without Border (Page # 3)
> 
> 1. Widgets border-radius
> 
> * [x]  15px (Page # 4)
> * [ ]  4px (Page # 3)
> 
> 1. Input / Button box radius (Take a look on Quick Deposit widget)
> 
> * [ ]  15px (Page # 3)
> * [x]  4px (Page # 4)

pretty much agree with @startailcoon

**Comment by sschiessl-bcp** [comment]
Also agree with @startailcoon choices, except **Widgets border-radius**, which I find better if it's small. Ultimately thats a easily adjustable detail later on.

**Comment by abitmore** [comment]
OK, just found #2668 is the summary. I'm behind, will start from there. Sorry for the off-topic comments.
