### ISSUE TITLE
State when a proposed transaction will handover control

### ISSUE THREAD

**Issue by matle85** [bitshares/bitshares-ui#2703]
**Is your feature request related to a problem? Please describe.**

Scam proposals continue to be a problem and in every case people have not realised what they are accepting until it is too late. This is in part because the text is very generic and relates to 'updating account'.

**Describe the solution you'd like**

For this particular proposal that hands over control it should be stated that this is what is happening.

I.e. "Committee-account are proposing to take control of your account, managing they will have ownership and control over your funds." or similar.

I recognise the current text is quite generic but considering how fundamental this type of proposed transaction is it would seem sensible for it to expressly state what it does.

**Describe alternatives you've considered**

1) Charge for failed proposals by locking up a fee of 500 BTS or so that is returned if the proposal is accepted. The collected fees from scam proposals could potentially feed into a restitution fund.

2) Create an update that means previous versions of the Client won't work so that everyone has to update (a lot of people seem to be getting scammed as they are on the old Client)

**Additional context**
N/A

**Comment by abitmore** [comment]
For UI, see #2499. For core changes, please discuss in https://github.com/bitshares/bsips/issues/154

**Comment by startailcoon** [comment]
Closed as duplicate
