### ISSUE TITLE
[3] Freshen up (light) template

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2705]
Usage of the styleguide makes the landing page inherently ugly, needs some attention

![image](https://user-images.githubusercontent.com/33128181/58181161-94d8d180-7cab-11e9-915e-6da36ddb6f08.png)

**Comment by startailcoon** [comment]
The "No Data" needs a default value so we don't display that icon everywhere we use something that has no data.

**Comment by gibbsfromncis** [comment]
@startailcoon what do you mean about "default value" ?

**Comment by startailcoon** [comment]
What I mean is that the component `<Table />` doesn't have a default value when empty, resulting in the "No Data" image with the English text. This should be replaced with something language independent. We have/had a similar issue on forms in various places.

Not exactly sure what else @sschiessl-bcp is thinking on, but it could need a new overhaul/design/idea on what to have the space for?

**Comment by gibbsfromncis** [comment]
This one took `3h`:
- All changes separated to variables
- Changes apply to all themes

(It should took up to 2 hours but took 3 hours because I was confused about the bug related to tabs text align)
