### ISSUE TITLE
Spotlight: Prediction Market

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2717]
From the basic layout it behaves similar to Direct Debit and HTLC. A prediction market is a special kind of bitasset that can be used to allow the users to bet on the outcome of a real world event. In the text below BACKING refers to the collateral of the prediction market (BTS, USD, CNY), and PREDICTIONMARKET refers to the prediction market asset. For other wording, please try to create an asset and toggle "SmartCoin" on and then "Prediction Market" on here: https://wallet.bitshares.org/#/account/sschiessl/create-asset

- [ ] Add a header with a centered title and description for explanatory text
- [ ] We have one main table with filter and create button ontop
![image](https://user-images.githubusercontent.com/33128181/58418482-2a97a680-8088-11e9-86ac-3dd836697126.png)
    - [ ] Columns are
        - #: asset id
        - house: issuer / feed producer
        - prediction: asset condition
        - description: asset description
        - odds: optional, leave empty for now
        - actions: room for buttons
    - [ ] Button "Create Prediction Market" opens a modal with fields
        - Symbol
        - Condition
        - Description
        - Resolution date
        - Backing asset
        - Participation fee
    - [ ] Rows show all non-expired prediction market, might be only from a subset of all accounts due to scam possibilities
    - [ ] Condition is a question, thus the action buttons are "Yes" or "No"
    - [ ] Filter filters house, prediction and description
    - [ ] If logged in user is issuer / feed producer, add 
        - an action button "Resolve" if expired. Opens a modal that shows Symbol and Condition (not editable) and "Yes" or "No" as toggle input
- [ ] If the user pushes one of "Yes" "No" the action buttons, or clicks generally in any row, a second table below the first table appears
![image](https://user-images.githubusercontent.com/33128181/58419056-d261a400-8089-11e9-9e85-47527fcadb23.png)
    - [ ] Columns are
        - #: order id
        - opinionator: account of order
        - opinion: depending if it sells or buys the prediction market asset, "yes" or "no"
        - amount: amount of order
        - odds: calculated by sale/buy price (not visible in picture)
        - fee: market fee if set 
        - actions: room for buttons
    - [ ] Button "Add Opinion" opens a model with fields
        - Symbol (not editable)
        - Condition (not editable)
        - Opinion (Yes/No)
        - Amount
    - [ ] Rows show all orders on the "BACKING / PREDICTIONMARKET" market, depending if it sells or buys the PREDICTIONMARKET
    - [ ] Filter filters opinionator and opinion
    - [ ] Button "Oppose" buys/borrows+sells the amount corresponding for that row.
    - [ ] If current user is the owner of the order, add a "Cancel" action, no modal needed. It cancels the order directly

Please not the exact wording is yet to be exactly defined, will streamline at the end.

**Comment by sschiessl-bcp** [comment]
Pending #1776 for further understanding.

**Comment by sschiessl-bcp** [comment]
- when user loads the PM overview for the first time, only show the top table with the assets
 - when user clicks on one of the rows in the first table or the action buttons, please highlight this selected row somehow and remove all other prediction market from the view. then load the second table below with opinions of the selected row. another click on the row deselects it, removes the second table again (make sure to abort loading / unsubscribe) and adds the other rows back into the view.
 - add resolution (expiration) date into the first table as a column
 - only load prediction market assets that are not globally settled yet
 - add a toggle behind the search input field with label "Hide unknown houses", default is checked, no view settings needed (default is simply always checked). If the toggle is checked, only show assets from a specified whitelist of asset issuers (hardcode that whitelist to be ["iamredbar1", "sports-owner"] for now). if not checked, load all assets that match general loading criteria

**Comment by sschiessl-bcp** [comment]
Bounty request in https://github.com/bitshares/bitshares-ui/pull/3011#issue-304608014

**Comment by sschiessl-bcp** [comment]
This issue will be closed for payout. Further refinements due to feedback of testers will go on new issue.

**Comment by startailcoon** [comment]
Nice work @sschiessl-bcp !
