### ISSUE TITLE
Create HTLC button is disabled

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-ui#2721]
**Describe the bug**
The "Create" button on the HTLC form is always disabled

**To Reproduce**

1. Load the wallet https://develop.bitshares.org.
2. Change the connection to one of the public testnet nodes
3. Log in with a cloud account
4. Click on Spotlight
5. Click on HTLC
6. Type in the name in the recipient account box.  Click on the suggested recipient name.
7. Type in amount

The "Fee" amount remains blank

The "Create" button remains disabled

**Expected behavior**

The "Fee" amount should be automatically filled in
The "Create" button should become enabled

**Desktop:**
 - OS: Linux
 - Browser Firefox
 - Version 66

**Comment by sschiessl-bcp** [comment]
Bounty request: 1
