### ISSUE TITLE
HTLC preimage hash should be editable for second-stage of ACCS

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-ui#2723]
**Is your feature request related to a problem? Please describe.**

It is desirable to have an editable HTLC preimage **hash** to allow use of the reference wallet for atomic crosschain swaps (ACCS).

ACCS involve two stages.  The first stage occurs on one blockchain, and the second chain occurs on another blockchain.  This scenario is targetting when the second blockchain is BitShares.

During the second stage of an ACCS, a BitShares user will create an HTLC that uses the same preimage **hash** from the first stage.

The reference wallet does not permit the editing the pre-image hash.

**Describe the solution you'd like**

The reference wallet should permit a _mode_ where the pre-image hash can be specified by the user.  This mode should also not have a preimage box because that is still unknown during the second stage of an ACCS.

**Describe alternatives you've considered**

An alternative is to use the CLI wallet for the second stage

**Comment by sschiessl-bcp** [comment]
Bounty requested: 1.25
