### ISSUE TITLE
HTLC preimage should be editable for first-stage of ACCS

### ISSUE THREAD

**Issue by MichelSantos** [bitshares/bitshares-ui#2724]
**Is your feature request related to a problem? Please describe.**

It is desirable to have an editable HTLC **preimage** for **some** use cases of the reference wallet for atomic crosschain swaps (ACCS).

ACCS involve two stages.  The first stage occurs on one blockchain, and the second chain occurs on another blockchain.  This scenario is targetting when the _first_ blockchain is BitShares.

During the first stage of an ACCS, a BitShares user will create an HTLC where the preimage could be some text that is meaningful to the participants.

The reference wallet does not permit editing the pre-image.

**Describe the solution you'd like**

The reference wallet should permit the pre-image to be edited by the user.

**Describe alternatives you've considered**

An alternative is to use the CLI wallet for the first stage

**Comment by sschiessl-bcp** [comment]
Bounty requested: 1.25
