### ISSUE TITLE
[0.5] No update for Dashboard pages after account reswitch

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2726]
**Describe the bug**
Changing the view to another account and back doesn't change the Dashboard view back.

**To Reproduce**
1. Start with own account A
1. Go to Dashboard (all sub pages get no update)
1. Visit account B (from Manage Accounts)
1. Click **VIEW MODE** to switch back
1. No update on UI

**Expected behavior**
Update on UI

**Desktop (please complete the following information):**
 - MX-Linux
 - Light client: 190424

**Comment by startailcoon** [comment]
Yeah, this isn't good. The view of the current page should update with the new account data when you click "View Mode".

# Task

- Update current view when clicking `View Mode`

**Comment by OpenLedgerApp** [comment]
@startailcoon, I can take this one.

**Comment by startailcoon** [comment]
> @startailcoon, I can take this one.

It's yours
