### ISSUE TITLE
[0.5] Enable filter asset selector on SEND

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2728]
**Describe the bug**
Go to Send, searching for bitAssets or Gateway IUOs brings no search results

**To Reproduce**
1. Go to Send
2. Browse through the list of available assets
3. Search for a bitAsset or Gateway IUO
4. no data

**Expected behavior**
List available coins, with prefix (bit, Open ...) and suffix (EUR, EOS).

**Screenshots**
![search](https://user-images.githubusercontent.com/40874087/58482032-e37be500-815d-11e9-85ca-d00fdbf9e1c4.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - Version: 190424

**Comment by startailcoon** [comment]
Confirmed. 

When you try to filter the asset list it will give you a "No Data" error when you click the list. 
If there is only one asset, the list will directly give you a "No Data" error when you open it.

# Task

- Allow filtering of assets
- Create a new placeholder when there is nothing matching
- When only one asset is available, disable the list.

**Comment by OpenLedgerApp** [comment]
@startailcoon, could I claim this one?

**Comment by startailcoon** [comment]
@OpenLedgerApp assigned
