### ISSUE TITLE
ZRX deposit not reflecting account

### ISSUE THREAD

**Issue by WilliamCruz** [bitshares/bitshares-ui#2733]
On may 27, 2019; I made a deposit of −98.60542488 ZRX to my bitshares wallet from coinbase and this has not reflected my bitshares account. I have attached the transaction hash:

0x0dfb1e098d132dd669ac9dc68d7864b333ef7e900bb77831b4def6537082a3e6

Thank You.

**Comment by sschiessl-bcp** [comment]
You have used one of the gateways on the blockchain, presumably through OpenLedger. Please open a support ticket with them.
