### ISSUE TITLE
[5] Update Asset PriceFeed/MarginPosition with Style-Guide Table

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2736]
The Asset information page needs to be updated to the new Style-Guide table code. 

# Tasks
- Replace old components with the new Style-Guide components
- Ensure we lacy load components (not done today)
- Include #2684

**Comment by startailcoon** [comment]
## Margin Positions

### Margin Warning
Margin positions now has an icon instead of previous filled background.
Danger icon = below MCR
Warning Icon = near MCR

![image](https://user-images.githubusercontent.com/12114550/58750052-5d2d0f00-848d-11e9-8503-72bec47544c4.png)


### Header
![image](https://user-images.githubusercontent.com/12114550/58750009-f3146a00-848c-11e9-9d49-5bd36517633a.png)

### Footer
With Pagination
![image](https://user-images.githubusercontent.com/12114550/58750022-0f180b80-848d-11e9-81aa-05ea777c119d.png)

**Comment by sschiessl-bcp** [comment]
Did you account for collateral bid positions?

**Comment by startailcoon** [comment]
> Did you account for collateral bid positions?

Indeed I did. There where also some fixes to some missing translation.

### Collateral Bids

![image](https://user-images.githubusercontent.com/12114550/58757057-f51a0f80-8504-11e9-8b3e-b68068c20a92.png)
