### ISSUE TITLE
Further voting refactor

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2742]
<h1>Tasks</h1>
- Add more text in header
- Enhance visualization of rows (progress bar for workers, yes/no for polls, acceptance for committee/witnesses)

**Comment by startailcoon** [comment]
Expected time requirements for this?

**Comment by sschiessl-bcp** [comment]
> Expected time requirements for this?

Will be given when mockups come

**Comment by sschiessl-bcp** [comment]
Splitting this up in several issues.
