### ISSUE TITLE
[0.5] Withdraw function wrong ammount

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2747]
**Describe the bug**
I wanted to send 1 RUDEX.EOS, but in confirmation window the amount changed to 1.7 RUDEX.EOS

**To Reproduce**
1. Go to Withdraw
2. Select RUDEX.EOS
3. Withdraw 1 RUDEX.EOS
4. Withdraw amount is 1.7

**Expected behavior**
Same amount 

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - BitShares.190424

**Additional context**
I did not test other coins/gateways maybe this is a bigger problem?

**Comment by startailcoon** [comment]
This is indeed not right. Unless the UI displays the wrong gateway fee for RUDEX.EOS it should be 1 RUDEX.EOS. The fee for OPEN.EOS is 0.7, maybe this is interfering with it? It should be looked at.

**Comment by OpenLedgerApp** [comment]
@startailcoon, I can take this one.

**Comment by sschiessl-bcp** [comment]
Thanks @OpenLedgerApp

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp I added PR, could you check please?
