### ISSUE TITLE
[1][ariesjia] Chart Height Value Becomes Meaningles and "Random" When Edited to Be Blank

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#275]
It was hard to pick a title for this one.

Steps to Reproduce:
1) Switch to the Price Chart
2) Click on the gear to the right of TOOLS
3) Try to edit the chart height by deleting the entire number
4) When the last digit is deleted, a seemingly random negative number is filled in for that value.

So, in order to change the Chart Height value you have to append your value to the current value THEN delete the old value at the beginning. You can not just delete the current value and then put in your new value which is more intuitive.

I am assuming this is because the real-time auto-adjusting of the chart height fails at a zero value. In the code, I would change it so that the chart display function does nothing when a zero value comes in and just keeps the last display (and a blank value) until a non-zero value is inserted. There is no empty case in the code.

**Comment by wmbutler** [comment]
Either remove chart height indicator or fix intended functionality.

![screen shot 2017-08-17 at 9 39 34 am](https://user-images.githubusercontent.com/1254810/29417810-147e4a86-8330-11e7-9ce6-60af62cec9bf.png)

**Comment by svk31** [comment]
It's an easy fix, just force a min height.

**Comment by ariesjia** [comment]
@wmbutler can i take this bug

**Comment by wmbutler** [comment]
Yes. It's yours!
