### ISSUE TITLE
[0.5][3.1.190618-rc1] Maintain Language

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2754]
Translations are done through transifex, please find the file here

https://www.transifex.com/bitshares/bitshares-ui-1

Bounties:
 - Translate per Word: Complete Chinese, Russian, German and Spanish. When assigning a language, please state before how many words are missing. Bounty $0.15/word, according to https://search.proz.com/employers/rates plus BitShares knowledge as bonus, open to discussion if that is unsuitable

 - max. 4 each: Review Chinese, Russian, German and Spanish. Must be different person than the one doing the translation

Please voice interest in other languages that are already partly translated and we discuss bounties. Every effort through this issue must be approved beforehand.

**Comment by shulthz** [comment]
I will translate Chinese.

**Comment by froooze** [comment]
I wanna do German.

**Comment by allfory0u** [comment]
I will translate Russian.

**Comment by allfory0u** [comment]
Could you also add Ukrainian to the list? Ukraine has a large cryptocommunity, which would be happy to see the Ukrainian language as the language of the interface on BitShares
I would help with this.

**Comment by sschiessl-bcp** [comment]
@shulthz @froooze go ahead with translation

@allfory0u russian is maintained by BLCKCHND which I would offer first dibs on that, sorry about that. @DimaBLCKCHND please confirm.

**Comment by sschiessl-bcp** [comment]
> Could you also add Ukrainian to the list? Ukraine has a large cryptocommunity, which would be happy to see the Ukrainian language as the language of the interface on BitShares
> I would help with this.

The translations require somewhat in-depth knowledge of the ongoings and methodology of BitShares. How much experience do you bring to that?

**Comment by allfory0u** [comment]
> The translations require somewhat in-depth knowledge of the ongoings and methodology of BitShares. How much experience do you bring to that?
I am an active member of Bitshares for 2 years. I used or tested most of the existing features and understand how they work. Now in my free time I am developing something like the BitShares explorer, which can be used in Telegram.

**Comment by DimaBLCKCHND** [comment]
@sschiessl-bcp On it
