### ISSUE TITLE
[7] Account Selector should not auto-match on type-ahead version

### ISSUE THREAD

**Issue by bitcrab** [bitshares/bitshares-ui#2756]
it's not a good design to auto list some candidates to-account while user type to-account

![image](https://user-images.githubusercontent.com/5886543/59161734-e8a34180-8b18-11e9-9819-087e5aed696e.png)

because of this, I have wrongly transfered to account "alpha" while acctually want to transfer to "alpha-go", several times.

![image](https://user-images.githubusercontent.com/5886543/59161777-69623d80-8b19-11e9-8dff-415001e05dc9.png)

alt has also mentioned this in forum

https://bitsharestalk.org/index.php?topic=28250.0

please remove this feature.

and maybe one better solution is to set one white list for each wallet, users can only select accounts in white list to send to.

**Comment by sschiessl-bcp** [comment]
You would prefer that the account is only shown for a complete match?

Funny enough this seems to be the case for me on wallet.bitshares.org
![image](https://user-images.githubusercontent.com/33128181/59256162-a4f12a80-8c33-11e9-82bb-b42a021fdb6b.png)

Did we change logic here @startailcoon ?

@bitcrab can you please let us know what version you are running?

**Comment by startailcoon** [comment]
We do have a bad design on this component, when you type a name it will auto match as you type and stick to it if no match is done when you're done typing. 

### Example

- You want to search for "bituser".
- As you've typed "bitu" a match is found and the component sets it.
- You type forward, but no match is found for "bituser", but the component is now set to "bitu" as it was found as you typed.

### Proposal

- When you type, no user will auto match.
- The component will *only* set a user if it's actively selected in the menu of users.

**Comment by abitmore** [comment]
This was an old bug (I didn't find the old issue though). I thought it's fixed already.

**Comment by startailcoon** [comment]
I'm not sure, but it sounds very familiar. Sorry if we've missed it before.

**Comment by sschiessl-bcp** [comment]
#1984

**Comment by startailcoon** [comment]
That issue solved when there where no account at all, not the auto select when the input matches said account, at least that's what I understand.

Anyhow, we should probably change this. I agree with bitcrab

**Comment by startailcoon** [comment]
Submitted a PR that fixes this on all sections of the app that uses the Account Selector component. Default, and so far only, behavior will be to require an active select in the list to select an account.

**Comment by startailcoon** [comment]
New PR supplied which updates the whole AccountSelector component.
