### ISSUE TITLE
[3.1.190618-rc1] Voting Section design issues

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2758]
The voting section for Workers have a blue border on the section of ` Proposed (13)Active (9)BSIPs/Polls (47)Expired `, see example below.

The  `Votes required to activate (BTS)` shouldn't break in my opinion.

![image](https://user-images.githubusercontent.com/12114550/59161923-08bb0c80-8ae9-11e9-9ac4-b40b6e06810e.png)

**Comment by sschiessl-bcp** [comment]
Fixed in develop
