### ISSUE TITLE
fill order took me more than a day to wait

### ISSUE THREAD

**Issue by fycee** [bitshares/bitshares-ui#2759]
Order ID #371230267
--

Buy 678.6427 WEKUCOIN for 34 BTS
--

I sold ny BTS @ 0.0501 Price but waited for days and checked out that it is the latest price of BTS to Wekucoin the time I sold it.

I even shared this experience because it was a triumphant 200% trade.
https://deals.weku.io/trading/@fycee/i-have-doubled-my-weku-coins-on-wallet-bitshares-org-thru-rev-bank

**Comment by sschiessl-bcp** [comment]
You placed and order that was not filled immediately and price changed. All good on that part. Did you want to report a bug here? If so, please reopen.

**Comment by fycee** [comment]
Thank you so much.
