### ISSUE TITLE
[.5] Move faucet selection to Settings -> Faucet

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#276]
It's currently under the Access menu. Quick fix.

**Comment by wmbutler** [comment]
The "FAUCET ADDRESS" control is currently under Settings -> Access as shown in this screenshot.
![screen shot 2017-08-17 at 1 35 41 pm](https://user-images.githubusercontent.com/1254810/29427960-178adf66-8351-11e7-98a9-c6b7f1282156.png)

Let's create another category inside **Settings** called **Faucet** and move the Faucet address dropdown there.

**Comment by wmbutler** [comment]
Note that this text needs to be moved as well:

### Faucet
The faucet is used to pay the registration fee for new users.

**Comment by btsfav** [comment]
but why do you even need a faucet after registration? 

is it even worth getting a dedicated menu?

**Comment by wmbutler** [comment]
The new node selection UI for #49 effectively buried it.

**Comment by calvinfroedge** [comment]
[PR 278](https://github.com/bitshares/bitshares-ui/pull/278) which handles related issues [49](https://github.com/bitshares/bitshares-ui/issues/49) and [110](https://github.com/bitshares/bitshares-ui/issues/110) has been updated to include changing the location of the faucet address. Please see attached screencast.

![issue-276](https://user-images.githubusercontent.com/632938/29435932-ca4dac1a-836e-11e7-979c-6efb7c80f29d.gif)

**Comment by calvinfroedge** [comment]
@svk31 This is ready for review
