### ISSUE TITLE
HTLC missing headrow entry

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2762]
![image](https://user-images.githubusercontent.com/33128181/59261699-40879880-8c3e-11e9-88f8-ff267fff16f2.png)

**Comment by startailcoon** [comment]
Please provide some more details @sschiessl-bcp if you want someone to pick this up. What exactly are we missing here? The screenshot doesn't give me any more information.

**Comment by sschiessl-bcp** [comment]
Direct Debit has head

**Comment by sschiessl-bcp** [comment]
See `active` in `render` of `Header.jsx`

**Comment by startailcoon** [comment]
Thanks 👍

**Comment by startailcoon** [comment]
We need to select a proper/good icon for this menu entry

**Comment by sschiessl-bcp** [comment]
The spotlight one should do

**Comment by sschiessl-bcp** [comment]
This was done through https://github.com/blockchainprojects/bitshares-ui/issues/122 but not all hours were accounted for on the other issues (which is my fault for not requesting differently). Since the others are already finalized, I request a bounty of 1.

**Comment by startailcoon** [comment]
Approved
