### ISSUE TITLE
Set new headline: Proposal scam warning

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2763]
New headline (asset description of TEST)

```
This asset is used for decentralized configuration of the BitShares UI placed under bitshares.org.
{
  "notifications": [
    {
      "type": "warning",
      "begin_date": "16.05.2019",
      "end_date": "31.12.2019",
      "content": "Please be aware of scam attempts using Proposed Transactions in your Dashboard. Never approve a proposal if you are not expecting one!"
    },
    {
      "type": "info",
      "begin_date": "02.07.2019",
      "end_date": "09.07.2019",
      "content": "2nd Global Graphene Blockchain Developer Conference is happening on 6th-7th July 2019 in Shanghai. Get more information here http://gbacenter.org/event/index_en.html!"
    }
  ],
  "blacklists": {
    "assets": [],
    "accounts": []
  }
}
```

**Comment by startailcoon** [comment]
Please provide some more details if you want anyone else to work on this @sschiessl-bcp, or please complete it so we can close it.

**Comment by sschiessl-bcp** [comment]
This is for me and Lucifer to set the proper description for the TEST asset to display the scam warning.

**Comment by sschiessl-bcp** [comment]
@murda_ra please confirm

**Comment by sschiessl-bcp** [comment]
The bounty for this issue will be reimbursement to my account `sschiessl` of the spent `BTS`, see here
https://develop.bitshares.org/#/block/37690276/1

**Comment by dls-cipher** [comment]
Confirmed.

**Comment by dls-cipher** [comment]
Approved on chain.

**Comment by startailcoon** [comment]
> 
> 
> The bounty for this issue will be reimbursement of the spent `BTS`, see here
> https://develop.bitshares.org/#/block/37690276/1, payable in `bitCNY`.

120 BTS = ~50 bitCNY
