### ISSUE TITLE
[1] Exchange: More margin for order cancellation

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2764]
See screen, you accidently click on scroll bar. Maybe put checkbox in front of row?

![image](https://user-images.githubusercontent.com/33128181/59262145-f3f08d00-8c3e-11e9-8a52-17d214dda1e9.png)

**Comment by startailcoon** [comment]
Agreed, tick-box could be in front of the row instead.

It also needs some minor work as the checked array doesn't reset properly at times, making it want to cancel orders that have been filled or removed elsewhere.

**Comment by startailcoon** [comment]
## Fixes 
- Now aligned to the left.
- Checkbox update to style-guide.
- Checkbox logic improved


![image](https://user-images.githubusercontent.com/12114550/59567745-dd4c9a80-9071-11e9-8d7e-31d5ef396b3e.png)
