### ISSUE TITLE
[0.5] Volume lists are wrong

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2765]
![image](https://user-images.githubusercontent.com/33128181/59263288-0966b680-8c41-11e9-89ad-1db3e3ad41eb.png)

**Comment by startailcoon** [comment]
Does all these *ETH* assets have volume then?

**Comment by OpenLedgerApp** [comment]
@startailcoon, these pairs don't have volume, but the sorting works wrong. It works good on wallet.bitshares.org, but not good on develop.bitshares.org and you can also see 0 values on prod and null cells on develop

![image](https://user-images.githubusercontent.com/42674402/59592114-0e6fae00-90f8-11e9-8ff1-8d5a382b671a.png)

![image](https://user-images.githubusercontent.com/42674402/59592156-26dfc880-90f8-11e9-893e-85e213e34b17.png)

**Comment by sschiessl-bcp** [comment]
@OpenLedgerApp you wanna look into this? It's blocking RC

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp yes, I can take this one.

**Comment by sschiessl-bcp** [comment]
> or also 0 value with asset precision must be set if there is no volume for pair (like on prod)?

I'd like a simple `0` (strike all those decimals)
