### ISSUE TITLE
[0.5][3.1.190618-rc1] - No Dashboard switch, after account switch

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2774]
**Describe the bug**
Account switch does not update Dashboard.
Problem with local wallet and cloud wallet

**To Reproduce**
1. Go to Dashboard 
2. Log out
3. Log in with new user
4. Dahsboard shows old account

**Expected behavior**
Update Dashboard and Voting page

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MX-Linux

**Additional context**
#2726

**Comment by startailcoon** [comment]
Is this issue the same when you use Cloud Wallet *and* Local Wallet?

**Comment by froooze** [comment]
Both make problems, but it could be a different issue.

**Comment by OpenLedgerApp** [comment]
@startailcoon I can take this issue, but I suppose it's not connected with #2726 , it's a separate issue.

**Comment by sschiessl-bcp** [comment]
> @startailcoon I can take this issue, but I suppose it's not connected with #2726 , it's a separate issue.

Awesome, go ahead! Blocker issue
