### ISSUE TITLE
[0.1][3.1.190618-rc1] - Increase area for new delete button

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2775]
**Describe the bug**
The area for the new delete button should also include a 9px border.

**Expected behavior**
Support for the delete button on the edge

**Screenshots**
![Delte-button](https://user-images.githubusercontent.com/40874087/59568219-f3f5f000-9077-11e9-84af-d5a8861dbdd9.png)

**Comment by startailcoon** [comment]
I assume you mean it should react on a click around the actual image, then I agree with you as I expected it did have that.

**Comment by sschiessl-bcp** [comment]
Component in question is SearchInput
