### ISSUE TITLE
[0.75][3.1.190618-rc1] - Include delete button to all search boxes

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2776]
**Describe the bug**
There are still some search boxes without the delete button:

**Dashboard:** 
-> Portfolio
-> Open Orders

**Explore:**
-> Accounts
-> Witnesses

**Voteing**

**Expected behavior**
Support delete button for all search fields

**Comment by sschiessl-bcp** [comment]
Agreed. All occurances of 
![image](https://user-images.githubusercontent.com/33128181/59608435-a16b1100-9115-11e9-80e4-8be3d5b4283f.png)
should use the new SearchInput component

**Comment by froooze** [comment]
Voteing has now also a searchbox!
