### ISSUE TITLE
[0.5][3.1.190618-rc1] - Include unity only in header of margin positons

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2778]
**Describe the bug**
The whole column uses the same unity. Why is the unity not in the header and excluded form the rows. 

**To Reproduce**
1. Go to margin positon list

**Expected behavior**
Put the unit only in header of table. 
Could also be in a second row of the header, to save more space!

**Screenshots**
![margin-positions](https://user-images.githubusercontent.com/40874087/59568552-7bddf900-907c-11e9-867e-cfa57c7d7149.png)

**Comment by startailcoon** [comment]
We would have some issues with long asset names. If possible, we could as suggested have a second sub-title row with the asset and asset pair.

**Comment by froooze** [comment]
@startailcoon: Using two lines for the table header should do the trick!

**Comment by sschiessl-bcp** [comment]
> @startailcoon: Using two lines for the table header should do the trick!

This would be ideal
