### ISSUE TITLE
[0][3.1.190618-rc1] - Highlight RATIO column again

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2779]
**Describe the bug**
The RATIO column doesn't have a color background highlight anymore
I don't like the icon at the end of the table because:
-  it doesn't highlight the RATIO column
- it is confusing, needs extra space, is at the end, doesn't provide any action by clicking on it

**Expected behavior**
Use a color highlight for different RATIO: red, orange and green

**Comment by startailcoon** [comment]
Will take the background back again.

**Comment by startailcoon** [comment]
![image](https://user-images.githubusercontent.com/12114550/59632510-a7c7b000-914a-11e9-8374-485339807d8a.png)


Back to as it was before with 
- Below MCR = red
- Near MCR = orange
- Other = none colored

**Comment by froooze** [comment]
>     * Below MCR = red
>     * Near MCR = orange
>     * Other = none colored
Better, what do you to color the other green ?

**Comment by sschiessl-bcp** [comment]
Please open a new issue to define new logic for coloring.

Currently 
```
        if (cr < mr) {
            return "danger";
        } else if (cr < mr + 0.5) {
            return "warning";
        } else {
            return "";
        }
```

**Comment by startailcoon** [comment]
@sschiessl-bcp can you please elaborate on your wish on this task?

We take the status to color the field by class, danger or warning. We currently have this logic on the following to get the status.

https://github.com/bitshares/bitshares-ui/blob/636d381770b75413b6614e6638c3845a09f5a861/app/lib/common/MarketClasses.js#L997-L1012
