### ISSUE TITLE
[0.25][3.1.190618-rc1] - Save "group by asset" state

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2780]
**Describe the bug**
Using the group by asset function in open orders is not saved for revisit.

**To Reproduce**
1. Go to Dashboard -> Open orders
2. Turn on group by asset
3. Go to margin position or any other side
4. No group by asset

**Expected behavior**
Save group by asset state

**Desktop (please complete the following information):**
 - OS: MX-Linux

**Comment by sschiessl-bcp** [comment]
Add as viewSettings
