### ISSUE TITLE
[0.5] Wrong price while withdrawing

### ISSUE THREAD

**Issue by pmconrad** [bitshares/bitshares-ui#2783]
**Describe the bug**
It seems that entering an amount in the "withdraw" dialog updates the BTS price of the asset to withdraw in the background. This price update seems to handle precision wrongly.

**To Reproduce**
1. Go to Dashboard / Portfolio
2. Click on e. g. OPEN.BTC -> Withdraw
3. Enter amount to withdraw
4. The background dashboard updates the price of OPEN.BTC. New price is too high by a factor of 1000.

**Expected behavior**
Nothing (or display correct price)

**Screenshots**
![Screenshot_20190617_091701](https://user-images.githubusercontent.com/6449255/59585458-d14bf180-90e0-11e9-9c47-82bc328984ac.png)

(OPEN.BTC price is 141M not 141K, see GDEX.BTC for comparison)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium
 - Version 74.0.3729.157 (openSUSE Build) (64-Bit)

**Comment by sschiessl-bcp** [comment]
#2747

**Comment by sschiessl-bcp** [comment]
Misread the issue, re-opening

**Comment by OpenLedgerApp** [comment]
@startailcoon, I can take this one.

**Comment by sschiessl-bcp** [comment]
> @startailcoon, I can take this one.

Awesome, go ahead! Blocker issue

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp, This issue is not so easy, unfortunately I haven't time to finish it today. I will try to complete it tommorow.

**Comment by sschiessl-bcp** [comment]
Removed blocker label because it was mistaken for a different issue. This one is visual only.
