### ISSUE TITLE
[0] Can't update TCR

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2785]
**Describe the bug**
Updating only the TCR leads to an error

**To Reproduce**
1. Go to margin positions
2. Change TCR
3. Save

**Expected behavior**
Allow TCR change without changing debt or collateral 

**Screenshots**
![margin-position-failed](https://user-images.githubusercontent.com/40874087/59606573-c493c180-9111-11e9-9d77-0ca05a59a930.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - Version: 3.1.190618-rc1-rc1

**Additional context**
I looked for `delta_collateral.amount` and `delta_debt.amount` but did not find any logic for this.

**Comment by sschiessl-bcp** [comment]
Needs validation

**Comment by startailcoon** [comment]
Not possible. Either collateral or debt has to change.

If no change is made, but TCR does, we should change collateral with +1 of the lowest precision unit of the collateral asset.

**Comment by froooze** [comment]
> Not possible. Either collateral or debt has to change. This is a core limitation.
Therefore, I did not found an logic for this on UI.

>If no change is made, but TCR does, we should change collateral with +1 of the lowest precision unit of the collateral asset.

This would be a quick fix from the UI!

**Comment by startailcoon** [comment]
Will fix this to enable near zero collateral change when it's not done by the user.

**Comment by abitmore** [comment]
It's a core "feature".
