### ISSUE TITLE
[0.5] Scaled trade doesn't work

### ISSUE THREAD

**Issue by gades** [bitshares/bitshares-ui#2786]
**Describe the bug**
I'm trying to set scaled order for sale and price the same for all orders

**To Reproduce**
1. Go to trading
2. Click on Scaled
3. set Price Lower, Price Upper, Quantity, Order Count
3. Press the sell button
4. all orders will have the same rate

**Expected behavior**
The rate must be increased like it for buy action

**Screenshots**
<img width="619" alt="Screen Shot 2019-06-17 at 21 31 22" src="https://user-images.githubusercontent.com/4200730/59627689-7b5e6480-9147-11e9-8209-6ab19f2c9f3f.png">

**Desktop (please complete the following information):**
 - OS: macos 10.14.5 (18F132)
 - Browser chrome Version 74.0.3729.169 (Official Build) (64-bit)
 - Version 94497cd436da4955cd1831421a473c3fd2599e30

**Comment by startailcoon** [comment]
Some investigation I did on this @gibbsfromncis 

> When you make more orders than what it can fit within the price range, it will take the lower price.
> 
> Example on open.ETH/BTS: 
> - Low: 0.00026
> - High: 0.00027
> - Quantity: 1000 BTS
> - Orders: 25
> 
> This wlll give all orders a sell of 0.000260 open.ETH/BTS
> 
> Also, if you make 20 orders within that range, it will not stop at 0.000270, but at 0.000279, which is equal to 20 orders.
