### ISSUE TITLE
[1] missing path 'assets/BTS' for locale 'ru'

### ISSUE THREAD

**Issue by gades** [bitshares/bitshares-ui#2789]
**Describe the bug**
Russian locale hat issues and hung interface

**To Reproduce**
1. Go to settings
2. Switch it to russian
3. Go to Инфопанель (Dashboard)-> Портфель (Portfolio) -> BTS

**Expected behavior**
it must show information like on EN locale

**Screenshots**
![photo_2019-06-18_00-30-02](https://user-images.githubusercontent.com/4200730/59638783-f46ab580-9161-11e9-98e4-715cec34a682.jpg)
![photo_2019-06-18_00-30-17](https://user-images.githubusercontent.com/4200730/59638790-f896d300-9161-11e9-9f45-99af670bc06b.jpg)
![photo_2019-06-18_00-30-31](https://user-images.githubusercontent.com/4200730/59638795-fc2a5a00-9161-11e9-87c8-216a963335c8.jpg)

**Desktop (please complete the following information):**
 - OS: mac os 10.14.5 (18F132)
 - Browser crome Version 74.0.3729.169 (Official Build) (64-bit)
 - Version 94497cd436da4955cd1831421a473c3fd2599e30

**Additional context**
`app.34d8d72b5e00aa405b59.js:1 missing path 'assets/BTS' for locale 'ru' help files, rolling back to 'en'
n @ app.34d8d72b5e00aa405b59.js:1
console.warn @ app.34d8d72b5e00aa405b59.js:1
value @ app.34d8d72b5e00aa405b59.js:1
Bi @ vendor.78dfe2a401cbe42d67c9.js:148
Ni @ vendor.78dfe2a401cbe42d67c9.js:148
da @ vendor.78dfe2a401cbe42d67c9.js:148
ha @ vendor.78dfe2a401cbe42d67c9.js:148
Ga @ vendor.78dfe2a401cbe42d67c9.js:148
qa @ vendor.78dfe2a401cbe42d67c9.js:148
Ka @ vendor.78dfe2a401cbe42d67c9.js:148
Ua @ vendor.78dfe2a401cbe42d67c9.js:148
ga @ vendor.78dfe2a401cbe42d67c9.js:148
enqueueSetState @ vendor.78dfe2a401cbe42d67c9.js:148
b.setState @ vendor.78dfe2a401cbe42d67c9.js:140
t @ vendor.78dfe2a401cbe42d67c9.js:32
(anonymous) @ vendor.78dfe2a401cbe42d67c9.js:32
Promise.then (async)
n._loadModule @ vendor.78dfe2a401cbe42d67c9.js:32
n.componentWillMount @ vendor.78dfe2a401cbe42d67c9.js:32
li @ vendor.78dfe2a401cbe42d67c9.js:148
Ni @ vendor.78dfe2a401cbe42d67c9.js:148
da @ vendor.78dfe2a401cbe42d67c9.js:148
ha @ vendor.78dfe2a401cbe42d67c9.js:148
Ga @ vendor.78dfe2a401cbe42d67c9.js:148
qa @ vendor.78dfe2a401cbe42d67c9.js:148
Ka @ vendor.78dfe2a401cbe42d67c9.js:148
ns @ vendor.78dfe2a401cbe42d67c9.js:148
Ln @ vendor.78dfe2a401cbe42d67c9.js:148
app.34d8d72b5e00aa405b59.js:1 missing path 'assets/BTS' for locale 'ru' help files, rolling back to alt_path 'assets/Asset'`

multiple errors 

`app.34d8d72b5e00aa405b59.js:1 missing path 'assets/BTS' for locale 'ru' help files, rolling back to 'en'
n @ app.34d8d72b5e00aa405b59.js:1
console.warn @ app.34d8d72b5e00aa405b59.js:1
value @ app.34d8d72b5e00aa405b59.js:1
Bi @ vendor.78dfe2a401cbe42d67c9.js:148
Ni @ vendor.78dfe2a401cbe42d67c9.js:148
da @ vendor.78dfe2a401cbe42d67c9.js:148
ha @ vendor.78dfe2a401cbe42d67c9.js:148
Ga @ vendor.78dfe2a401cbe42d67c9.js:148
qa @ vendor.78dfe2a401cbe42d67c9.js:148
Ka @ vendor.78dfe2a401cbe42d67c9.js:148
Ua @ vendor.78dfe2a401cbe42d67c9.js:148
ga @ vendor.78dfe2a401cbe42d67c9.js:148
enqueueSetState @ vendor.78dfe2a401cbe42d67c9.js:148
b.setState @ vendor.78dfe2a401cbe42d67c9.js:140
t @ vendor.78dfe2a401cbe42d67c9.js:32
(anonymous) @ vendor.78dfe2a401cbe42d67c9.js:32
Promise.then (async)
n._loadModule @ vendor.78dfe2a401cbe42d67c9.js:32
n.componentWillMount @ vendor.78dfe2a401cbe42d67c9.js:32
li @ vendor.78dfe2a401cbe42d67c9.js:148
Ni @ vendor.78dfe2a401cbe42d67c9.js:148
da @ vendor.78dfe2a401cbe42d67c9.js:148
ha @ vendor.78dfe2a401cbe42d67c9.js:148
Ga @ vendor.78dfe2a401cbe42d67c9.js:148
qa @ vendor.78dfe2a401cbe42d67c9.js:148
Ka @ vendor.78dfe2a401cbe42d67c9.js:148
ns @ vendor.78dfe2a401cbe42d67c9.js:148
Ln @ vendor.78dfe2a401cbe42d67c9.js:148
app.34d8d72b5e00aa405b59.js:1 missing path 'assets/BTS' for locale 'ru' help files, rolling back to alt_path 'assets/Asset'`

**Comment by startailcoon** [comment]
Needs to verify all Russian  locale 'ru' help files I think. Also, a missing help file should not hang the interface, it should change to default (en) as it say.

**Comment by gades** [comment]
it's working fine in case i running from `npm start` but it doesn't work after make bundle or app

**Comment by OpenLedgerApp** [comment]
@startailcoon I can take this one.

**Comment by sschiessl-bcp** [comment]
Does this issue reproduce on the latest wallet.bitshares.org, or the local install of it? You are using a private fork. @gades

**Comment by gades** [comment]
@sschiessl-bcp 
<img width="1023" alt="Screen Shot 2019-06-26 at 17 45 32" src="https://user-images.githubusercontent.com/4200730/60189832-484c5d00-983a-11e9-8dbf-0ef649e582fa.png">

i able to reproduce it on your side and yes - I'm using own fork

**Comment by gades** [comment]
also, this issue can be reproduced only after building bundle or application and from dev mode it's working fine (I'm thinking that it's issue with compilation)

**Comment by gades** [comment]
it still doesn't work.

For replicate this issue please:
- generate bundle **npm run package-mac**
- run app and go to dashboard->portfolio->bts

<img width="1165" alt="Screen Shot 2019-07-12 at 22 57 58" src="https://user-images.githubusercontent.com/4200730/61155196-f3c30600-a4f8-11e9-8c4d-491b8037ed9b.png">

**Comment by gades** [comment]
@sschiessl-bcp please reopen this ticket!

<img width="1112" alt="Screen Shot 2019-07-12 at 23 07 25" src="https://user-images.githubusercontent.com/4200730/61155562-e5c1b500-a4f9-11e9-8050-a509d63a2a21.png">

**Comment by sschiessl-bcp** [comment]
Are you using develop branch?
