### ISSUE TITLE
[0.25] [3.1.190618-rc1] Dashboard - margin position alignment

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2790]
**Describe the bug**
When the margin position window is in wide position the column Total BTS until Feed Price is not aligned on the right side

**To Reproduce**
1. Go to margin position
2. Put Window in max wide
3. See error

**Expected behavior**
Same alignment as other columns

**Screenshots**
![margin-position-layout](https://user-images.githubusercontent.com/40874087/59642814-d3589380-9166-11e9-8256-d82fb6488df2.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux, Light client

**Comment by sschiessl-bcp** [comment]
Looks like content is centered

**Comment by OpenLedgerApp** [comment]
@startailcoon I can take this one
