### ISSUE TITLE
Enhancement - Trade UI - Consider removing the "favorite" stars from "My Markets" tab and make them visible only when hovering. Reduces bloat

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#28]
_From @ValentinJesse on December 21, 2015 11:47_

Something similar to this:

![2015-12-21_13-45-18](https://cloud.githubusercontent.com/assets/7979136/11930107/4891edce-a7e9-11e5-926c-881e3eb604ed.png)

_Copied from original issue: cryptonomex/graphene-ui#621_

**Comment by svk31** [comment]
_From @wmbutler on December 29, 2015 16:9_

Not sure I understand. The star indicates that it's a favorite.

**Comment by svk31** [comment]
He wants the stars to be hidden unless you hover over a market.

**Comment by wmbutler** [comment]
There is no spacing benefit to this and I think it's more user-friendly to show the dimmed star when not hovered.

![screen shot 2017-07-21 at 1 32 06 pm](https://user-images.githubusercontent.com/1254810/28477305-03cb1830-6e19-11e7-9306-5369400cb5b3.png)
