### ISSUE TITLE
[3.1.190618-rc1] - German Übersicht - White screen

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2800]
**Describe the bug**
Visiting "Übersicht" with German language gives a white screen!

**To Reproduce**
1. Switch to German language
2. Visit **Übersicht**
4. White screen

**Expected behavior**
no white screen

**Desktop (please complete the following information):**
 - OS: MX-Linux, light client

**Additional context**
[german-lang-white.log](https://github.com/bitshares/bitshares-ui/files/3303915/german-lang-white.log)

**Comment by startailcoon** [comment]
Can't reproduce. On what account does this happen?

**Comment by froooze** [comment]
@startailcoon: I can't reproduce this bug with 3.1.190618 now. I do now further testing with German language.
