### ISSUE TITLE
[2] Refine explanation of referral rewards program

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2803]
![image](https://user-images.githubusercontent.com/33128181/59745283-c32eda00-9274-11e9-8c69-acbc78b9648d.png)

It's not as self-explanatory as it should be.

**Comment by froooze** [comment]
- less text
- headlines bigger
- highlight key figures
- use icons next to figures
- integrate interactive graphic with circles and arrows
- max-wide and small-wide (mobile) friendly

**Comment by startailcoon** [comment]
Will take this as part of #661

**Comment by abitmore** [comment]
I believe you'll remember to add info about market fee sharing to the page.

**Comment by startailcoon** [comment]
> integrate interactive graphic with circles and arrows

Would need some help with this, do we have any good infographs?

**Comment by sschiessl-bcp** [comment]
> > integrate interactive graphic with circles and arrows
> 
> Would need some help with this, do we have any good infographs?

I'd say create the frame and data provision, visualizations can be tinkered around by someone else with less gateway or subscription knowledge :)

**Comment by startailcoon** [comment]
https://github.com/bitshares/bitshares-ui/issues/661#issuecomment-520176401

**Comment by sschiessl-bcp** [comment]
Merged, please check if all desired data is visible. Currelntly running on one ES instance without fallback.

**Comment by abitmore** [comment]
The description doesn't make much sense for LTMs, see https://develop.bitshares.org/#/account/jademont/member-stats .

**Comment by abitmore** [comment]
Oh, I need to wait a bit for the page to be deployed.

**Comment by abitmore** [comment]
This sentence should be shown in LTMs' page, but not on the basic members' page
> `Fee shares, market rewards and other rewards is found on the Vesting Balances page`
