### ISSUE TITLE
VOTE - Trollbox

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#281]
Just a sample of the riveting conversation, use the thumbs up / thumbs down reaction at the top of this comment.

![screen shot 2017-08-17 at 5 57 51 pm](https://user-images.githubusercontent.com/1254810/29437350-aa1aa2b6-8375-11e7-8bca-adcaaa1ade8a.png)

- Thumbs Up to Keep the Trollbox
- Thumbs Down to Ditch the Trollbox

**Comment by flux627** [comment]
This has always been a super embarrassing feature, however at least the name is accurate.

**Comment by calvinfroedge** [comment]
High effort, low value

**Comment by ThomasFreedman** [comment]
There were  S O O O O  many people screaming to have a "trollbox" implemented. Go look at the forums. I've never been a fan of the concept. Very distracting, and I would say obsolete with all the social media apps available these days.

**Comment by btsfav** [comment]
just add links to our official channels (telegram/discord/forum)

**Comment by testlump** [comment]
Ditch it entirely. It's cheap and tacky. Leave the collaboration/trolling to purpose built platforms like Telegram, Github and Bitsharestalk.

**Comment by grctest** [comment]
Replacing the trollbox with links to telegram/slack/bitsharestalk/steemit/wechat/other would probably be better than the trollbox (IMO). Alternatively, we could bridge the trollbox to some of the external chat systems (though that could be a nightmare to moderate).
