### ISSUE TITLE
[0.5][3.1.190618-rc1] Send - missing translation

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2813]
**Describe the bug**
When I go to send, there is a translation missing

**To Reproduce**
1. Go to send
2. click on To
3. See error

**Expected behavior**
No error

**Screenshots**
![missing-translation](https://user-images.githubusercontent.com/40874087/59848675-061caa80-9366-11e9-8657-88c71894f1c1.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux

**Additional context**
Error does solve, when used a second time sometimes by itself

**Comment by startailcoon** [comment]
An account should not be undefined, there's something not working as expected here. Most likely a missing error check. Good catch.

**Comment by OpenLedgerApp** [comment]
@startailcoon, I can take this one.

**Comment by sschiessl-bcp** [comment]
> @startailcoon, I can take this one.

Go ahead
