### ISSUE TITLE
grammar needs to be fixed on the new Prediction Markets card

### ISSUE THREAD

**Issue by Agorise** [bitshares/bitshares-ui#2814]
**Describe the bug**
the grammar on that card should be tweaked a bit imo. maybe something like this: 
 
Create a collateralized Prediction Market whereby others can agree or disagree on the outcome.
 
https://develop.bitshares.org/#/spotlight

**Comment by sschiessl-bcp** [comment]
I've changed the wording slightly, and added a meaningful comma:
`Create a prediction into the future that others can agree or disagree with, leveraged with collateral.`

The issue I see with your text is that it insinuates that the creator provides the collateral, which is not true. The person that creates the prediction asset and sells it provides the collateral.

**Comment by Agorise** [comment]
Perfect! Thank you! :)
