### ISSUE TITLE
[3.1.190618-rc1] White screen - HTLC

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2817]
**Describe the bug**
White screen occurred in HTLC overview window.

**To Reproduce**
1. Go Spotlight
2. HTLC

**Expected behavior**
No white screen

**Desktop (please complete the following information):**
 - OS: MX-Linux

**Additional context**
[Whitescrenn-HTLC.log](https://github.com/bitshares/bitshares-ui/files/3318359/Whitescrenn-HTLC.log)

**Comment by startailcoon** [comment]
I can't reproduce. Could it be related to something else. Does it always do this for you when you go to the HTCL of the Spotlight section?

**Comment by froooze** [comment]
Could be related to something else.

**Comment by sschiessl-bcp** [comment]
Found an error in loading history
