### ISSUE TITLE
[3.1.190618-rc1] Could not redeem HTLC

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2818]
**Describe the bug**
Could not redeem HTLC. I used the preimage from the creator. 

**To Reproduce**
1. Create HTLC
2. Switch account
3. Redeem HTLC

**Expected behavior**
Redeem HTLC

**Screenshots**
![HTLC](https://user-images.githubusercontent.com/40874087/59980110-49d71480-95f1-11e9-959f-9676ceec4b9b.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux

**Additional context**
It is unclear from the UI, how to get the secret.

**Comment by startailcoon** [comment]
Needs some investigating on why this happened. I've flagged it as critical prio to start with.

**Comment by sschiessl-bcp** [comment]
Please contact me via telegram @sschiessl-bcp to sort this out quickly.

**Comment by sschiessl-bcp** [comment]
My guess is that the preimage was re-calculated (possibly due to bad UX)  .. Please try to re-create (put tx fee on your integration test ticket)

**Comment by froooze** [comment]
I did two new HTLC, which worked!
