### ISSUE TITLE
[3.1.190618-rc1] Help section - Broken internal links

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2821]
**Describe the bug**
Broken links to internal sections in the Help section.

**To Reproduce**
1.1 Go to [Bitshares](https://staging.bitshares.org/#/help/introduction/bitshares)
1.2 Click on ["BitAssets"](https://staging.bitshares.org/#/help//help/assets/mpa) or click on ["User-Issued Assets"](https://staging.bitshares.org/#/help//help/assets/uia) or click on ["The DEX"](https://staging.bitshares.org/#/help//help/dex/introduction)
1.3 If you open a link in the same window, you will not see any text. If you open the link in a new window, you will see the message "404 page not found. This page does not exist".

2.1 Go to [Wallet](https://staging.bitshares.org/#/help/introduction/wallets)
2.2 Click on ["See managing **backups**"](https://staging.bitshares.org/#/help//help/introduction/backups) or click on [""...a proper **Backup** in the..."](https://staging.bitshares.org/#/help//help/introduction/backups)
2.3 If you open a link in the same window, you will not see any text. If you open the link in a new window, you will see the message "404 page not found. This page does not exist".

3.1 Go to [Backups](https://staging.bitshares.org/#/help/introduction/backups)
3.2 Click on ["Settings -> Backup"](https://staging.bitshares.org/#/help//settings)
3.3 If you open a link in the same window, you will not see any text. If you open the link in a new window, you will see the message "404 page not found. This page does not exist".

4.1 Go to [Voting](https://staging.bitshares.org/#/help/voting)
4.2 Click on ["...check out these **channels**"](https://staging.bitshares.org/#/help//help/introduction/bitshares)
4.3 If you open a link in the same window, you will not see any text. If you open the link in a new window, you will see the message "404 page not found. This page does not exist".

5.1 Go to [Membership](https://staging.bitshares.org/#/help/accounts/membership)
5.2 Click on ["...**in this schedule**"](https://staging.bitshares.org/#/help//explorer/fees)
5.3 If you open a link in the same window, you will not see any text. If you open the link in a new window, you will see the message "404 page not found. This page does not exist".

**Additional context**
Links contain an extra part "/ help /"

**Comment by sschiessl-bcp** [comment]
Thanks

**Comment by sschiessl-bcp** [comment]
We would like to offer you a bounty of 0.3 for integration testing. The release candidate is published, the integration tests for it were conducted through #2753

We would be happy if you come back for the next round of integration tests, or if you conduct more testing now (in the second case please contact us to see how that could be compensated)

**Comment by allfory0u** [comment]
Thank you, @sschiessl-bcp 

> We would be happy if you come back for the next round of integration tests, or if you conduct more testing now (in the second case please contact us to see how that could be compensated)

I will do both: come back for the next round of integration tests and conduct more testing now.

> Please state your bitshares account @allfory0u  

My bitshares account is **allforyou**.
