### ISSUE TITLE
[0][3.1.190618-rc1] Exchange - Refine cancel feature

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2825]
<h1>1</h1>
**Describe the bug**
When the cancel order master box is set active and performed it is afterwards still active.

**To Reproduce**
1. Exchange
2. Create a order
3. Activate the master cancel box
4. Cancel selected orders
5. Create new orders
6. Master box is still active, but new orders are not selected

**Expected behavior**
Reset master checkbox after order cancel operation

**Screenshots**
![master-checkbox](https://user-images.githubusercontent.com/40874087/60060722-51321700-96f2-11e9-96f1-2d8236c0d076.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux

<h1>2</h1> **Describe the bug**
Tooltip does describes wrong action

**To Reproduce**
1. Go Exchange
2. Hover on master cancel button

**Expected behavior**
Select order for cancel

**Screenshots**
![select-lang](https://user-images.githubusercontent.com/40874087/60092065-53be5c00-9746-11e9-81df-17be81192d24.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux

**Comment by startailcoon** [comment]
Fixed by PR https://github.com/bitshares/bitshares-ui/pull/2773.

The second issue may still need to be checked. It could need another description.
