### ISSUE TITLE
[3.1.190618-rc1] Select cancel order - language logic

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2827]
**Describe the bug**
Tooltip does describes wrong action

**To Reproduce**
1. Go Exchange
2. Hover on master cancel button

**Expected behavior**
Select order for cancel

**Screenshots**
![select-lang](https://user-images.githubusercontent.com/40874087/60092065-53be5c00-9746-11e9-81df-17be81192d24.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux

**Comment by sschiessl-bcp** [comment]
Moved into #2825
