### ISSUE TITLE
[2.64] Publication for 190618 release

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2832]
In the past I did publication for releases in a quite raw format, see for example here
https://steemit.com/blockchain/@sschiessl/the-bitshares-blockchain-ui-release-20190410

For the [current release candidate](https://steemit.com/bitshares/@sschiessl/bitshares-ui-release-candidate-190618) I want a post crafted that is fun to read, informative and possible have side posts with it that include "How to" instructions or videos. It should also talk about the direct debit authorizations that came with the last release. Furthermore, I would imagine that [the release notes](https://github.com/bitshares/bitshares-ui/releases/tag/2.0.190618) are touched and for-the-daily-joe interesting parts are highlighted.

Tasks:
 - [2.5] Publication for release
 - [1] Insight: Direct Debit Authorization
 - [1] Insight: HTLC
 - [1] Insight: Voting Panel

Please ping if any reading material should be provided, or any features needs explanation. Happy to explain / schedule a call.

The bounty numbers of this task refer to a content writer a $60/h.

**Comment by sschiessl-bcp** [comment]
Reserved for Scott atm

**Comment by swehman** [comment]
Indeed, looking forward to getting involved.

**Comment by sschiessl-bcp** [comment]
Awesome, go ahead!

**Comment by sschiessl-bcp** [comment]
<h1>The BitShares Blockchain: UI Release 20190618</h1>

The BitShares Blockchain is an industrial-grade and fully decentralized platform that is open source and maintained by its community. The BitShares UI serves as secure wallet for the private keys of your BitShares account and a point of entry to interact with the BitShares blockchain. Among many other features lies the natively built-in decentralized exchange (DEX). Have a look [here](https://bitshares.org/) and [there](https://fortunejack.com/blog/article/bitshares-a-fully-decentralized-platform-community) for more information, there is also the [whitepaper](https://www.bitshares.foundation/download/articles/BitSharesBlockchain.pdf).

Today the [BitShares UI Team](https://www.bitshares.foundation/workers/2019-02-bitshares-ui) is pleased to bring you the most recent iteration of the user interface which includes several exciting new features. These items are the result of the team’s pursuit of it its mission to expand the utility of BitShares for advanced users as well as simply and improve the experience for all skill and interest levels.

The new release of the BitShares UI has been published (Version 2.0.190618) and is available at

https://wallet.bitshares.org/

<h2>Spotlight Features</h2>

<h3>Hash Time-Locked Contracts</h3>

Atomic Cross Chain Swaps (ACCS) or simply “Atomic Swaps” require the receiver to acknowledge a transaction prior to a deadline by generating cryptographic proof of payment. This is accomplished through the use of a hash and preimage via [Hash Time-Locked Contracts](https://en.bitcoin.it/wiki/Hash_Time_Locked_Contracts) (HTLC). Should the recipient fail to supply the proof, they will forfeit the ability to claim the payment and it will return to the payer. This functionality allows for completely trustless wallet-to-wallet trading between assets and enables a significant reduction in counterparty risk.

The implementation of HTLC significantly widens the permeability of the BitShares ecosystem as it allows transfers between BTS and other HTLC-enabled blockchains directly and in a completely decentralized fashion. Trading with assets outside the BitShares ecosystem is now possible and eliminates the necessity of using a gateway. For a detailed explanation, consult the [user guide here](https://github.com/bitshares/bitshares-core/wiki/HTLC). Try it out [here](https://wallet.bitshares.org/#/htlc).

<h3>Awareness Alerts</h3>

Following attempts to compromise the accounts of more novice users via misleading [proposals](asd) (first detailed in [this post from February, 2019](https://steemit.com/bitshares/@krazykrista/bitshares-scam-do-not-accept-proposed-transactions-that-update-your-account-data)), highly visible information and warnings about these will appear in the dashboard section if an account becomes targeted. 

![image](https://user-images.githubusercontent.com/33128181/61295108-9cae8100-a7d7-11e9-83dc-9f3314be0d4a.png)

A news and alert banner in the top section of the wallet will also direct all users to emerging threats which exist in a timely fashion, or simply distribute news in a rapid and effective manner (see example below).

![image](https://user-images.githubusercontent.com/33128181/61295146-ad5ef700-a7d7-11e9-810d-99958e2a8b8d.png)

<h3>Direct Debit Authorization</h3>

Recurring payment authorizations (a basic but significant business use) are now possible to arrange for secure disbursement of funds. Users may give access to payments for specified accounts and may control parameters over the assets, sums and intervals they desire with ease and flexibility. Try it out [here](https://wallet.bitshares.org/#/direct-debit).

<h3>Market Fee Sharing</h3>

Asset owners such as Gateway operators can now define that a percent of all market fees for a given asset are funneled through the referral rewards program. The flexibility of this new feature creates enormous incentive for web admins to onboard new users into BitShares.

Given that the bitUSD and bitCNY stablecoins support asset fee sharing, it is possible to provide reliable incentive for referring entities to bring new users to the ecosystem. Each time a referral is completed, any given percentage (defined by asset owner) of the market fee is set aside and funneled into the already existing [referral rewards program](https://bitshares.org/technology/referral-rewards-program/). When combined with new features such as the direct debit authorization, these funds are able to be distributed in a straightforward and “hands off” fashion leaving those involved to more important tasks.

At the time of writing, market fee sharing is enabled for bitUSD, bitCNY and bitEUR (a staggering 80%). The possibilities are vast and can already be seen on the existing onboarding ways for the BitShares Blockchain. The biggest effect can currently be seen on the [registrar](https://wallet.bitshares.org/#/account/icowallet.reg/vesting) of [MagicWallet](https://www.magicw.net/indexen.html), which could accumulate 70,700 bitCNY since the beginning of July through market fee sharing. This is certainly due to the heavy use of bitCNY and the direct on- and offramping possibilities in their mobile app. The [registrar](https://wallet.bitshares.org/#/account/onboarding.bitshares.foundation/vesting) of the reference wallet has accumulate 4000 bitCNY in the same period.

<h3>Interface Optimization</h3>

Open orders may now be grouped by asset and selectively cancelled in one operation if desired. A full CSV history can also be exported in both [CoinTracking](http://cointracking.info) and personally refined formats. If you have any formats or other statistics services that require a specific format, please feel free to tell the [BitShares UI team](https://github.com/bitshares/bitshares-ui/issues) and it might just get supported!

Default templates have been expanded and users may choose from light, night and midnight layouts

<h4>Light</h4>

![image](https://user-images.githubusercontent.com/33128181/61296322-2f501f80-a7da-11e9-9610-13fe4ca6ffb3.png)

<h4>Dark</h4>

![image](https://user-images.githubusercontent.com/33128181/61296358-3ecf6880-a7da-11e9-9a6d-9ffedbdd19db.png)

<h4>Midnight</h4>

![image](https://user-images.githubusercontent.com/33128181/61296387-4b53c100-a7da-11e9-8df0-8197cd2bcf8a.png)

<h3>Get Involved</h3>

Do you like what you see here, and want to help guide the direction of the team? The full history and discussion of this and past release candidates are [posted in the forum](https://bitsharestalk.org/index.php?topic=26727), so any and all comments, suggestions and bug reports are highly appreciated!

Best regards,
[The BitShares UI team](https://www.bitshares.foundation/workers/2019-02-bitshares-ui)

<p align="center"><i>Release notes and binaries for a local install can be found [here on GitHub](https://github.com/bitshares/bitshares-ui/releases/tag/3.1.190618.1).</i></p>

**Comment by sschiessl-bcp** [comment]
https://whaleshares.io/@sschiessl/the-bitshares-blockchain-ui-release-20190618

https://steemit.com/blockchain/@sschiessl/the-bitshares-blockchain-ui-release-20190618

**Comment by sschiessl-bcp** [comment]
@swehman Will you be doing separate how-to articles (like a series) like mentioned in the initial description?

**Comment by abitmore** [comment]
@sschiessl-bcp why the version is 20190618? It's July now.

**Comment by swehman** [comment]
### Spotlight on: Direct Debit Authorization

Creating permissions to withdraw specific assets for accounts is now possible directly within the BitShares wallet. This application opens up a variety of possible applications such as automated distribution of salary or expense account funds, reward or referral payouts, even a weekly allowance for your children (a great way to incentivize learning about self-sovereign finances)!

To begin, choose the Spotlight Section from the menu.

![debit-1](https://user-images.githubusercontent.com/52246972/61318189-7d612500-a7d2-11e9-91d4-638faa5e90a4.jpg)

Then select the Direct Debit menu.

![debit-2](https://user-images.githubusercontent.com/52246972/61318216-8d790480-a7d2-11e9-9fe5-a5cde683d4b2.jpg)

You will now see a blank layout where all your authorizations will appear. Choose “Create Authorization”. 

![debit-3](https://user-images.githubusercontent.com/52246972/61318242-a08bd480-a7d2-11e9-93ff-83cc6ff4aeac.jpg)

From this sub-menu, you may define which account you are authorizing funds to be released to (use the dropdown to select from the available assets), how often (minute, hour, day, week) and a start date.

![debit-4](https://user-images.githubusercontent.com/52246972/61318264-a8e40f80-a7d2-11e9-8412-583bb78c6cd6.jpg)

Once you have defined all the parameters of your authorization, confirm the transaction (be prepared for the fee). 

![debit-5](https://user-images.githubusercontent.com/52246972/61318290-b5686800-a7d2-11e9-932f-cccf4f463da9.png)

You may create as many authorizations as you please!

![debit-6](https://user-images.githubusercontent.com/52246972/61318309-c1ecc080-a7d2-11e9-8a9c-6f754255245c.png)

The account which has been authorized will see the new permission appear in their activity feed.

![debit-7](https://user-images.githubusercontent.com/52246972/61318323-c9ac6500-a7d2-11e9-944e-45fa497accb5.jpg)

**Comment by swehman** [comment]
> https://whaleshares.io/@sschiessl/the-bitshares-blockchain-ui-release-20190618
> 
> https://steemit.com/blockchain/@sschiessl/the-bitshares-blockchain-ui-release-20190618

In the future I will have some suggestions for some of the additional text and formatting you've added if you wish to use this as a template @sschiessl-bcp

**Comment by sschiessl-bcp** [comment]
> @sschiessl-bcp why the version is 20190618? It's July now.

It is indeed the publication post for the June version (delayed).

**Comment by swehman** [comment]
### Spotlight on: Hashed Time-Lock Contracts (HTLC)

HTLC operations (aka “atomic swaps”) are now possible on the BitShares blockchain, allowing for completely trustless digital asset trades with compatible blockchains! Below is a high-level overview and steps on how to create your own HTLC transaction.

### Overview

There are two parties (a depositor and recipient) involved in such a transaction. The depositor selects the asset and amount, creates a preimage (the “secret”), a time-limited hash of this preimage and a time-lock (the expiration date/time) of the transaction. Operation fees apply for the operation, its duration and to redeem.

The recipient will need to meet the conditions of the proposed transaction to facilitate the trade before it expires. If this does not occur, then the original funds return to the depositor.

### Process

To begin, unlock your wallet and choose the Spotlight section from the menu. 
![Menu-Spotlight](https://user-images.githubusercontent.com/52246972/61591426-692f7600-ab8c-11e9-95e8-4340b4aed7af.png)

Then, select HTLC from the available choices.
![Choose-HTLC](https://user-images.githubusercontent.com/52246972/61591443-98de7e00-ab8c-11e9-969f-df8f7947154d.png)

You will now see a blank layout where all your HLTC transactions will appear. Choose “Create HTLC”. 
![Create-HLTC](https://user-images.githubusercontent.com/52246972/61591447-a3991300-ab8c-11e9-8aec-a789919cbe3f.png)

Next you will be presented with a dialog box which where you specify all the conditions: recipient, preimage preferences and expiration date.
![Create-HLTC](https://user-images.githubusercontent.com/52246972/61591450-b01d6b80-ab8c-11e9-9146-d9603979e6a6.png)

Confirm the transaction.
![Confirm-HTLC](https://user-images.githubusercontent.com/52246972/61591455-b9a6d380-ab8c-11e9-8885-f50c75348481.png)

The HTLC transaction has now been created and its status can be viewed in the wallet. Optional extension of its duration is possible as well.
![HTLC-final](https://user-images.githubusercontent.com/52246972/61591465-c7f4ef80-ab8c-11e9-925f-1a4150413c65.png)

For a more detailed explanation and discussion of the above along with potential in-depth business applications, please visit the bsip on GitHub.

**Comment by swehman** [comment]
Supplement to the original post, per @sschiessl-bcp :

### Voting Panel
 
Several new navigation features have been integrated to make the process of locating and interacting with proposals more intuitive and enjoyable. The selection box for your voting proxy account is now placed more highly above the list of proposals and a filter box for proposals is in the previous location. You may easily save and reset your proxy from this same area. Proposed, active and expired proposals are viewed by their respective radio buttons. Sorting by columns for ID, description, votes, duration and daily pay is also now possible from the header row.

**Comment by swehman** [comment]
account: swehman-1

**Comment by sschiessl-bcp** [comment]
Resolved to a Bounty of 2.64

**Comment by startailcoon** [comment]
@sschiessl-bcp I assume this task is supposed to be tagged for @swehman and payment is for his account.
