### ISSUE TITLE
[0.5] Proposal object without owner breaks dashboard

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2834]
When an account has a Create proposal transaction and it miss the owner object it will break the dashboard as the transaction history can't load.

- 0.5h to find the exact cause of this breakage

**Comment by sschiessl-bcp** [comment]
Can you please give more insight into the error? Stack trace etc.? What exactly is owner object for you?

**Comment by sschiessl-bcp** [comment]
What account does that happen on?

**Comment by startailcoon** [comment]
This happens on account `sc-trade`.
It happens when a proposal is to change active, but not owner.
Owner is null, and active is not null for the "Proposed Transaction" tab.

![image](https://user-images.githubusercontent.com/12114550/60292656-ecf39b00-991d-11e9-9e71-9059b92b5799.png)

#### Error Log
```
BindToChainState(Proposals) TypeError: "owner is undefined"
AccountUpdate AccountUpdate.jsx:151
```

Op Object missing `Owner`

```
{
  "fee": {
    "amount": 2529,
    "asset_id": "1.3.0"
  },
  "account": "1.2.802379",
  "active": {
    "weight_threshold": 2,
    "account_auths": [
      [
        "1.2.1602048",
        2
      ]
    ],
    "key_auths": [
      [
        "BTS54pWpqYUZ8bZMDtRZKJYWdXVHs5fej11y8SnFXnM6FM56DhWYu",
        1
      ]
    ],
    "address_auths": []
  },
  "extensions": {}
}
```

https://github.com/bitshares/bitshares-ui/blob/2f5076a3d8ed6cd67909ae9400506effeb8578b0/app/components/Blockchain/operations/AccountUpdate.jsx#L50-L51

It will fail here when it should set owner to active, as owner is null.

https://github.com/bitshares/bitshares-ui/blob/2f5076a3d8ed6cd67909ae9400506effeb8578b0/app/components/Blockchain/operations/AccountUpdate.jsx#L144

It only checks active, not owner.

https://github.com/bitshares/bitshares-ui/blob/2f5076a3d8ed6cd67909ae9400506effeb8578b0/app/components/Blockchain/operations/AccountUpdate.jsx#L120
