### ISSUE TITLE
[mrugakshee][1.25] Unable to Import Key from WIF

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-ui#2837]
**Describe the bug**
Unable to import private key (WIF) to `BITSHARES 3.1.190618`

**To Reproduce**
1. Login with: key file (local wallet)
2. Navigate: Settings >> Restore/Import
3. Select: Import a private key
4. Paste: privKey (WIF)
5. Click: Submit 

Result: no UI response. Same if the field is left blank and click submit.

**Expected behavior**
In the past, the privKey is added to the wallet and the associated account(s) is displayed. Also, if the field is blank, or not a WIF format (length?) the UI should inform the user of the error.

**Comment by startailcoon** [comment]
This task has two goals

1. Fix UI breakage when importing WIF.
2. Alert user when an import fails due to any reason.

**Comment by mrugakshee** [comment]
I would like to take this issue.

**Comment by startailcoon** [comment]
Hi @mrugakshee, welcome to the Bitshares UI project. 

I'll assign you to this issue. Please make sure to read [CONTRIBUTING.md](https://github.com/bitshares/bitshares-ui/blob/develop/CONTRIBUTING.md) for any initial questions.

**Comment by efe-dev** [comment]
I have the same issue and problem is in the
```
// ImportKeys.jsx:77
let value = this.refs.wifInput.value; // Current implementation. Problem is there is no wifInput.value 
const value = this.refs.wifInput.state.value; // It works.

**Comment by mrugakshee** [comment]
Hi @startailcoon 
For clarification, 
- Is the associated account(s) displayed in spot #1 or #2?
- For the alert upon failure of import, do you want a modal or an error message in spot #2 or an error below the WIF input box?

<img width="1280" alt="Screen Shot 2019-07-13 at 8 46 51 PM" src="https://user-images.githubusercontent.com/36647571/61177607-1c5a0700-a5b0-11e9-9e06-d6a0d41dd537.png">

**Comment by sschiessl-bcp** [comment]
The error should be shown within the panel (no popup). We so far dont have error popups.

Associated account of current import attempt should be shown in panel. In sport 1 is the currently active account of the UI

**Comment by startailcoon** [comment]
@mrugakshee please post a bitshares address that the reward for this task will be sent to.

**Comment by mrugakshee** [comment]
> @mrugakshee please post a bitshares address that the reward for this task will be sent to.

mrugakshee-palwe
