### ISSUE TITLE
[0.5] Blocks freeze after a transaction occurs.

### ISSUE THREAD

**Issue by AXS-WILSON** [bitshares/bitshares-ui#2838]
**Description**

Dashboard / Activity
Pending blocks display freezes after a transaction occurs.

**Version**
190618 - Master
Any browser.

**Comment by startailcoon** [comment]
What type of a transaction are you doing when the UI freezes?
Please describe your steps so we can reproduce.

Thanks.

**Comment by AXS-WILSON** [comment]
Any type of transaction. 
This happens when any transaction with an account is done. Trade, deposit or withdraw. Any.
Directly in the Activity tab. At the time of the transaction.
Just switching to Margin Positions and back helps update information.

![freezing](https://user-images.githubusercontent.com/35869952/60310816-33b4b580-995d-11e9-8c02-39f8e6b5d880.jpg)

**Comment by startailcoon** [comment]
The reason for this problem can be larger than what it seems. Adding 0.5h to locate the problem and supply a fix. If the issue is larger than expected (ie. needing some larger patch) the hours can be adjusted.

**Comment by OpenLedgerApp** [comment]
@startailcoon I can take this one

**Comment by startailcoon** [comment]
@OpenLedgerApp please report back if the issue is larger than estimated
