### ISSUE TITLE
[0][3.1.190618-rc1] MCR should be MSSR

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2839]
**Describe the bug**
The MSSR column is also tagged with MCR

**To Reproduce**
1. Go to Margin Positions

**Expected behavior**
Show MSSR

**Screenshots**
![MSSR](https://user-images.githubusercontent.com/40874087/60257292-78940a00-98d3-11e9-811e-7265f605c1ce.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux

**Comment by startailcoon** [comment]
😱
