### ISSUE TITLE
[1] Persistent application initialization issue

### ISSUE THREAD

**Issue by blahbax** [bitshares/bitshares-ui#284]
Whenever I open the Bitshares desktop client it takes me at least 5 retries/node switches to actually get into the program. Would be great if this was automated so the program automatically retried the selected node and then moved on to the next node after a few retries.

I am on a satellite connection which is pretty fast, but like all satellite connections, the latency is shocking. I've heard of other users having these init issues too, but it could well be my connection making the problem worse.

**Comment by svk31** [comment]
That's exactly what the current behaviour is: retry the next node if it fails to connect to the first one. The websocket connection requires you to have a decent internet connection, not much we can do about this tbh.

**Comment by wmbutler** [comment]
@blahbax can you please report back on this?

**Comment by blahbax** [comment]
Hi @wmbutler I have been having a whole lot less issues lately, I usually only have to press retry once or twice now and some times I get in right away. Having said that, this behaviour doesn't fit with what @svk31 says above - otherwise I'd never have to hit retry.

**Comment by wmbutler** [comment]
Might be nice for you to submit a speed test to a site near whatever node you are using. There is only so much we can do about poor connections. I'm closing this issue since, without the requested evidence, there is no way to help you. Glad it's going better though.
