### ISSUE TITLE
GUI installed - Got this error.

### ISSUE THREAD

**Issue by icsugti** [bitshares/bitshares-ui#2843]
[https://i.ibb.co/ZGCzxtc/image.png](url)

in ./app/components/Blockchain/Asset.jsx Module build failed (from ./node_modules/babel-loader/lib/index.js): Duplicate declaration "counterpart"   27 | import {Tab, Tabs} from "../Utility/Tabs";
  28 | import {Tooltip, Icon, Table, Tabs as AntTabs} from "bitshares-ui-style-guide";
> 29 | import counterpart from "counterpart";
     |        ^
  30 | // TODO: Replace remaining old style Tabs with new
  31 | 
  32 | class AssetFlag extends React.Component { @ ./app/App.jsx 107:15-86 @ ./app/AppInit.jsx @ ./app/index.js @ ./app/Main.js @ multi webpack-hot-middleware/client react-hot-loader/patch ./app/Main.js

**Comment by startailcoon** [comment]
Fixed by commit https://github.com/bitshares/bitshares-ui/commit/0d54862aa12a3ba40dd69f7e25528afce8340d17#diff-92c45f254db82073dcae1e0b1b26322e
