### ISSUE TITLE
issue of ChainStore.getObject()

### ISSUE THREAD

**Issue by crazybits** [bitshares/bitshares-ui#285]
the ChainStore has been init, but ChainStore.getObject(balanceID) always return a undefined object in react native, any idea？

**Comment by wmbutler** [comment]
@svk

**Comment by svk31** [comment]
In theory this is an issue for https://github.com/bitshares/bitshares-js and https://github.com/bitshares/bitsharesjs-ws. React-native is not currently supported by the websocket library which is probably the cause of your issue.
