### ISSUE TITLE
[0.25] Change order MY TRADES/MARKET TRADES

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2858]
**Describe the bug**
When I have MY TRADES and MARKET TRADES in one group, MY TRADES is always before MARKET TRADES, which does not make much sense for me.

**To Reproduce**
1. Go to Exchange 

**Expected behavior**
Change order in Personalize and Exchange for MY TRADES/MARKET TRADES

**Screenshots**
![Market trades](https://user-images.githubusercontent.com/40874087/60395888-610a8a80-9b3a-11e9-97ec-5a689953c0c6.png)

**Comment by startailcoon** [comment]
Good suggestion, haven't really thought about it myself, but it makes sens to be able to change the order of these as well.

**Comment by froooze** [comment]
@startailcoon: It would be enough to have MARKET TRADES before MY TRADES as default value.

**Comment by startailcoon** [comment]
Applied a fix to sort the tabs by key, which means:
1. Market History
2. My History
3. My Orders
4. Open Settle orders

This is not optimal imho. Ideally I'd like to see this to be fully customizable, perhaps on a drag and drop scale on the Personalize modal. This would be quite a task though, and we should probably wait and see what we can make.
