### ISSUE TITLE
Light client - very slight cosmetic glitch on overview page

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#286]
![image](https://user-images.githubusercontent.com/15861527/29461395-76aa3712-8423-11e7-9869-eed9d3394995.png)

When first loaded (or when the client view is refreshed) the overview page shows a very slight cosmetic glitch where the bottom left trading pair border is missing & the next trading pair (to the right) has a slightly off-centre border.

When you hover your mouse over the cell, it fixes the border.

Running the latest release (not self-compiled latest codebase).

**Comment by wmbutler** [comment]
Unable to reproduce. I'm envisioning Top markets will get a rewrite so probably best not to spend developer time on something that will be re-written.
