### ISSUE TITLE
[react-cat][1.5] Account switch tooltip should not hide user menu

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2860]
**Describe the bug**
Switching to a different account shows a toolip, which hides the user menu entry

**To Reproduce**
1. Click on username to switch account
2. Click on username to switch account again

**Expected behavior**
Move tooltip to the left to not hide user menu

**Screenshots**
![acc-switch-tooltip](https://user-images.githubusercontent.com/40874087/60396176-2145a200-9b3e-11e9-899c-cb470642c605.png)

**Comment by react-cat** [comment]
@startailcoon I'd like to work on this task. 
Also after reproduce I noticed that not only user menu is being hidden by notification popup, but manage accounts menu too.
![AwesomeScreenshot-BitShares-Account-react-cat-2019-07-13-18-07-65](https://user-images.githubusercontent.com/43940398/61173365-10177f00-a59b-11e9-93ce-47b6a341cb52.png)
![AwesomeScreenshot-BitShares-Account-react-cat-2019-07-13-18-07-15](https://user-images.githubusercontent.com/43940398/61173366-1148ac00-a59b-11e9-8bcc-921851342784.png)
 
Also moving notification popup to the left as was suggested above might cause an unexpected behavior on small resolutions, for example here is screen on the smallest browser resolution: 
![AwesomeScreenshot-BitShares-Account-react-cat-2019-07-13-18-07-54](https://user-images.githubusercontent.com/43940398/61173392-65539080-a59b-11e9-8b01-f7539d747491.png)

So as a suggestion, it might be better to close popup on click to one of menu or account buttons, or to close notification on any click outside of notification box. 
What do you think about this ?

**Comment by sschiessl-bcp** [comment]
I think closing the notification if the user clicks on the menu while the notification is visible is acceptable. We could restrict it to only auto closing the active account switcher notification.

**Comment by froooze** [comment]
> I think closing the notification if the user clicks on the menu while the notification is visible is acceptable.
Closing every time the notification is not an option here, when switching between several accounts. 

Tooltips should be placed to not hide important UI elements.

**Comment by sschiessl-bcp** [comment]
@react-cat The account switch notification is the one most likely to be over the menu for local wallet users. So if the active notification is the account switch one, it can be closed automatically. Any other notification stays there to not miss it. 

But maybe that distinction is not necessary, what are your thoughts?

**Comment by react-cat** [comment]
@sschiessl-bcp I think that when notification appears, first of all user paying attention to it and then performs some actions, so at the moment when he clicks anywhere, he already read notification. 
There is only one exception when user clicks multiple times in a row. In that case he could miss notification, cause it would be closed immediately after it appear. 

We can make it only for account switch notification and expand that logic to other notifications in future if it would be necessary.

**Comment by react-cat** [comment]
@sschiessl-bcp And also handling the case only with account notification would be easier to implement

**Comment by react-cat** [comment]
@sschiessl-bcp So as a final suggestion I propose to handle only account notifications and force close it in case user click on menu or open account management dropdown. My estimate for this is 1.5 hours
