### ISSUE TITLE
[2] No scroll reset on Exchange

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2862]
**Describe the bug**
Scrolling down a list on the Exchange and switching to a different pair does not reset the scroll position. 

**To Reproduce**
1. Go to Exchange bitCNY/BTS
2. Scroll down MARKET TRADES list till bottom
3. Select a different market RUDEX.WLS/BTS 
4. List looks empty, scrolling is needed to see entries

**Expected behavior**
Show the list from the top

**Screenshots**
![empty-lists](https://user-images.githubusercontent.com/40874087/60396330-5226d680-9b40-11e9-85bb-4b64f5355414.png)

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - Version 3.1.190618

**Comment by startailcoon** [comment]
Also includes some updates to code/view splitting.
