### ISSUE TITLE
[.5] Within 'send' tab's transfer details: Editing the middle of 'amount' field switches to append mode in light client (similar to #265)

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#287]
Similar closed/completed issue: https://github.com/bitshares/bitshares-ui/issues/265

On the 'send' page within the bitshares-light wallet, the 'amount' field similarly switches to append-mode when attempting to change the value in the middle.

5's added to middle of 1's:
![image](https://user-images.githubusercontent.com/15861527/29461762-cf7338f2-8424-11e7-9ae9-a9ab0a72babf.png)

This issue is not present on the openledger web-wallet, so perhaps the latest codebase (or OL devs) have fixed this?

**Comment by wmbutler** [comment]
Confirmed from Send link (Transfer Details) Heading page as well. Another interesting difference is the label **Amount** in the screenshot above vs **Quantity** in my screenshot. I'm using 170522 client for my screenshot and I think Quantity is a better label.

![screen shot 2017-08-18 at 8 56 31 am](https://user-images.githubusercontent.com/1254810/29462052-9a881e9a-83f3-11e7-9052-fa2fb4da4552.png)

**Comment by svk31** [comment]
Don't do anything with this yet, I have pending changes that touches the input here and will probably fix this.

**Comment by wmbutler** [comment]
I assigned this to you to ensure it would t get claimed.

**Comment by svk31** [comment]
I've removed the ',' formatting which fixes this issue.
