### ISSUE TITLE
[0.75] Open Orders Toolbar refinments

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2871]
**Is your feature request related to a problem? Please describe.**
The reset button before the Submit button is confusing. 
Current location of button is also confusing

**Describe the solution you'd like**
All to the left!
Group by asset (different style) | Submit | Reset | Filter 

**Screenshot**
![open-orders-toolbar](https://user-images.githubusercontent.com/40874087/60400329-97fc9280-9b72-11e9-99d8-f4e73f3012f4.png)

**Comment by sschiessl-bcp** [comment]
For consitency with the remaining wallet the filter bar should be the most left, then place the `[x] Group by asset`. Action buttons could then be on the right.

**Comment by froooze** [comment]
@sschiessl-bcp : This?
Filter | Group by asset (different style) | Submit | Reset

**Comment by sschiessl-bcp** [comment]
Bounty request: 0.75
