### ISSUE TITLE
[0.75][3.1.190618-rc2] Barter - problem with entering amount of bartering asset

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2873]
**Describe the bug**
Interface elements are repaint when you try to enter the amount of bartering asset and memo field is open.

**To Reproduce**
1. Go to [Barter](https://staging.bitshares.org/#/barter)
2. Click on icon for adding memo field
3. Click on "Bartering asset" field
4. Try to enter any number
5. As a result, the page was refreshed and all elements returned to their original state.

**Expected behavior**
Nothing should happen

**Screenshots**
![Barter](https://user-images.githubusercontent.com/17462020/60427219-e6f00980-9bfe-11e9-957a-de7b96ca419b.gif)

Information from console:
![Barter_cr](https://user-images.githubusercontent.com/17462020/60427224-e8b9cd00-9bfe-11e9-925a-6db1a7bc303b.jpg)

**Desktop:**
 - Windows 7
 - Chrome 71.0.3578.98

**Comment by startailcoon** [comment]
Seems like an re-render triggering issue.

**Comment by OpenLedgerApp** [comment]
@startailcoon I can take this one.
