### ISSUE TITLE
[0.5][3.1.190618-rc2] HTLC - mismatch between "Expiration date" and "Expires"

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2874]
**Describe the bug**
In the list of all HTLC data from the "Expires" column do not match the "Expiration date" in the form of "Extend HTLC". "Expiration date" in the called form "Extend HTLC" is always the same for all HTLC

**To Reproduce**
1. Go to [HTLC](https://staging.bitshares.org/#/htlc)
2. Click on 'Extend'
3. See the difference between "Expiration date" and "Expires"

**Expected behavior**
The expiration date for each of the HTLC should be different and relevant.

**Screenshots**
![HTLC](https://user-images.githubusercontent.com/17462020/60434495-ee6bde80-9c0f-11e9-96ae-48a5cea03f41.gif)
![HTLC-1](https://user-images.githubusercontent.com/17462020/60434504-f166cf00-9c0f-11e9-955b-db8c1188e5db.jpg)
![HTLC-2](https://user-images.githubusercontent.com/17462020/60434506-f297fc00-9c0f-11e9-983b-ba0056e8bb2e.jpg)

**Desktop (please complete the following information):**
 - Windows 7
 - Chrome 71.0.3578.98

**Additional context**
I think it`s related with #2868

**Comment by sschiessl-bcp** [comment]
Yes, it probably does the same logic there: Date in modal is now + one day.

**Comment by sschiessl-bcp** [comment]
Related #2868
