### ISSUE TITLE
[0.25][3.1.190618-rc2] Activity - incorrect information about the amount of locked BTS

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2875]
**Describe the bug**
If the amount of blocked in HTLC BTS is less than 0.5, then in Activity it is displayed as 0

**To Reproduce**
1. Go to [HTLC](https://staging.bitshares.org/#/htlc)
2. Click on 'CREATE HTLC'
3. Create HTLC with the amount of locked BTS is less than 0.5
4. Go to 'Dashboard' and 'Activity'
5. See "... account locked 0 BTS for account..."

**Expected behavior**
See the actual amount of locked BTS

**Screenshots**
![Locked-1](https://user-images.githubusercontent.com/17462020/60436536-e6fb0400-9c14-11e9-8037-5c765d5b20a6.jpg)
![Locked-2](https://user-images.githubusercontent.com/17462020/60436542-e82c3100-9c14-11e9-903f-e4c5eddf2a82.jpg)
![Locked-3](https://user-images.githubusercontent.com/17462020/60436546-eb272180-9c14-11e9-8282-6e7e5e5fe7dd.jpg)

**Desktop (please complete the following information):**
 - Windows 7
 - Chrome 71.0.3578.98

**Comment by startailcoon** [comment]
I assume this is a rounding issue, making it look like 0 as there are no decimals visible.

**Comment by OpenLedgerApp** [comment]
@startailcoon I can take this one
