### ISSUE TITLE
[2] Missing vesting balances

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2876]
**Describe the bug**
The list displayed in the vesting balance page is incomplete.

For example, `temp-account` has these vesting balances:
```
locked >>> get_vesting_balances temp-account
[{
    "id": "1.13.24542",
    "owner": "1.2.4",
    "balance": {
      "amount": 136174,
      "asset_id": "1.3.113"
    },
    "policy": [
      2,{}
    ],
    "balance_type": "market_fee_sharing",
    "allowed_withdraw": {
      "amount": 136174,
      "asset_id": "1.3.113"
    },
    "allowed_withdraw_time": "2019-07-01T18:09:15"
  },{
    "id": "1.13.24648",
    "owner": "1.2.4",
    "balance": {
      "amount": 24,
      "asset_id": "1.3.121"
    },
    "policy": [
      2,{}
    ],
    "balance_type": "market_fee_sharing",
    "allowed_withdraw": {
      "amount": 24,
      "asset_id": "1.3.121"
    },
    "allowed_withdraw_time": "2019-07-01T18:09:15"
  }
]
```

**To Reproduce**
1. Go to 'https://develop.bitshares.org/#/account/temp-account/vesting'

**Expected behavior**
Data match.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/60457570-a6af7c00-9c3c-11e9-93c3-b5410286a637.png)

**Comment by allfory0u** [comment]
After the page is loaded, nothing is really displayed.
But after some actions (I can’t determine what exactly helps), the vesting balances are displayed.
Or you can go to another page of the exchange, and then go back. Also balances are visible for a split second when the page is reloaded later.

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/issues/2879#issue-463033748

**Comment by startailcoon** [comment]
https://github.com/bitshares/bitshares-ui/issues/2879#issue-463033748

> The vesting balances have no loading indicator and the user does not know if it already has properly loaded. This issue is to show a loading indicator non-intrusive under the descriptive text as long as they are being loaded.

### Tasks
The task of this issue would be to make a non-intrusive loading indicator of the vesting balance page to let the user know the data is loading from the node.

**Comment by startailcoon** [comment]
Please note that the issue https://github.com/bitshares/bitshares-ui/issues/2532 will do some changes to the files of this issue. I'm removing some unnecessary components, like `<Tabs>` and `<Tab>`.

**Comment by startailcoon** [comment]
@sschiessl-bcp how is work going on this?

I think we should move the vesting page to a nice table structure instead of today's list, but would like this to work first.

**Comment by startailcoon** [comment]
There is an issue in this that still needs to be fixed.

If you go to an accounts vesting balance page, it will not show anything. When you change your active account (if you have more) it will show previous accounts vesting balances, and so on.

Please supply a fix for this.

**Comment by startailcoon** [comment]
It also seems to be some kind of loading issue, because it loads 2 of my 4 vesting balances on reloading the page. But two are just "Loading" and it looks really weird to have a loading symbol in the middle. Can't we add a "Loading Vesting Balances" at the top while we're still fetching them?

![image](https://user-images.githubusercontent.com/12114550/62165926-d0cd8a00-b31f-11e9-8e6b-be5714015cf3.png)

**Comment by sschiessl-bcp** [comment]
Please re-check after latest update

**Comment by allfory0u** [comment]
Looks nice and informative :+1: 

![изображение](https://user-images.githubusercontent.com/17462020/62539624-57bdbd80-b85e-11e9-879d-256b561903a8.png)

**Comment by abitmore** [comment]
The only issue is the background color of the blank area below the table doesn't look too good. https://develop.bitshares.org/#/account/temp-account/vesting
![image](https://user-images.githubusercontent.com/9946777/62560316-12f54f00-b87d-11e9-886d-52cadc7468c5.png)

**Comment by sschiessl-bcp** [comment]
> The only issue is the background color of the blank area below the table doesn't look too good. https://develop.bitshares.org/#/account/temp-account/vesting
> ![image](https://user-images.githubusercontent.com/9946777/62560316-12f54f00-b87d-11e9-886d-52cadc7468c5.png)

Fixed

**Comment by startailcoon** [comment]
Looks good to me now 👍
