### ISSUE TITLE
[0.75] Spontaneous URL change after node change

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2878]
**Describe the bug**
Switching to another node changes the URL to the wrong one. If you change a node while on the develop.bitshares.org/#/account/temp-account/vesting page, then after changing the node, the URL will change to develop.bitshares.org/#/account//vesting

**To Reproduce**
1. Go to [https://develop.bitshares.org/#/account/temp/vesting](https://develop.bitshares.org/#/account/temp/vesting)
2. Click on 'Switch Node'
3. Click on 'Connect to this API Node
4. See error "404 page not found", because the page has changed to develop.bitshares.org/#/account//vesting

**Expected behavior**
URL should not change

**Screenshots**
![MhF7OcvYCG](https://user-images.githubusercontent.com/17462020/60459620-56d7b180-9c4a-11e9-812c-599d733c2e18.gif)

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 67.0.4
 - Bitshares 0d54862

**Comment by startailcoon** [comment]
Should be pretty obvious to fix once debugged. Setting .75 hrs to this to begin with.
