### ISSUE TITLE
Vesting Balance Loading

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2879]
Here is a collection of faucet accounts

https://wallet.bitshares.org/#/account/onboarding.bitshares.foundation/vesting
https://wallet.bitshares.org/#/account/cryptobridge/vesting
https://wallet.bitshares.org/#/account/openledger/vesting
https://wallet.bitshares.org/#/account/onboarding-sparkdex/vesting
https://wallet.bitshares.org/#/account/btsabc.reg/vesting
https://wallet.bitshares.org/#/account/blckchnd/vesting
https://wallet.bitshares.org/#/account/gdex-faucet/vesting

The vesting balances have no loading indicator and the user does not know if it already has properly loaded. This issue is to show a loading indicator non-intrusive under the descriptive text as long as they are being loaded.

**Comment by abitmore** [comment]
#2876?
