### ISSUE TITLE
[3.1.190618.1] Menu - links look inactive

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2884]
**Describe the bug**
When you first use a Light Client (or the web version in the browser), then most of the links in the menu look inactive, although this is not the case.

**To Reproduce**
1. Clear cookies
2. Go to [staging.bitshares.org](https://staging.bitshares.org) or install Light Client
3. Go to 'Menu'
4. See inactive links

**Expected behavior**
See active links

**Screenshots**
![menu](https://user-images.githubusercontent.com/17462020/60590916-de860300-9da5-11e9-8f6d-63d06c835775.jpg)
![menu](https://user-images.githubusercontent.com/17462020/60590950-f78eb400-9da5-11e9-8c1c-4dd0b7c12321.gif)

**Desktop (please complete the following information):**
 - Windows 10
 - Light Client 3.1.190618.1
 - Firefox 67.0.4
 - Chrome 71

**Comment by froooze** [comment]
Because you are not logged in.

**Comment by allfory0u** [comment]
> 
> 
> Because you are not logged in.

In the video above you can see that although I’m not logged in, the links became active, but only when I clicked one of them.

**Comment by react-cat** [comment]
@froooze Also after testing, I noticed that send, deposit and withdraw button are really disabled, but buttons from Voting to Permissions have styles of disabled button, but still clickable. 

Also you can get to Voting page for example by typing link directly, like https://wallet.bitshares.org/#/account/null/voting

If we really need those buttons to be disabled we should disable them in menu and forbid unauthorized users to visit links like that. 

What do you think about that ? We need those buttons (from Voting to Permissions) to be disabled ?

**Comment by sschiessl-bcp** [comment]
They can be activated since they are used for visualizations.

**Comment by startailcoon** [comment]
While we're at it, I think we should activate `Vesting Balances` links for all accounts.

**Comment by sschiessl-bcp** [comment]
> While we're at it, I think we should activate `Vesting Balances` links for all accounts. This is at the moment not visible when you're viewing an account that is not your own.

Agreed
