### ISSUE TITLE
[0.1][3.1.190618.1] - Exchange - wrong description

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2885]
**Describe the bug**
The description "No open orders" in sections 'My trades' or 'Market trades'  is wrong, if the account did not make any trades on the trading pair or/and if there was no trading on the pair.

**To Reproduce**
1. Go to [staging.bitshares.org/#/market/BRIDGE.MONA_RUDEX.ETH](https://staging.bitshares.org/#/market/BRIDGE.MONA_RUDEX.ETH) (for example)
2. See 'No open orders'

**Expected behavior**
See more relevant decription

**Screenshots**
![No open orders](https://user-images.githubusercontent.com/17462020/60592840-1b53f900-9daa-11e9-838f-a9e27bce3e8f.jpg)
![no open orders](https://user-images.githubusercontent.com/17462020/60592810-0e370a00-9daa-11e9-9f3e-7a3f54e22671.gif)

**Desktop (please complete the following information):**
 - Windows 7/10
 - Light Client 3.1.190618.1
 - Firefox 67.0.4
 - Chrome 71

**Comment by startailcoon** [comment]
Good catch, should be "No order history".
