### ISSUE TITLE
[3.1.190618.1] HTLC - the HTLC list isn't updated after creating a new HTLC

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2886]
**Describe the bug**
The HTLC list isn`t updated after creating a new HTLC. Therefore, the user may think that the HTLC wasn't created because he doesn't see it in the list. In order to see the new HTLC, you need to refresh the page, which isn't obvious in the Light Client.

**To Reproduce**
1. Go to [HTLC](https://staging.bitshares.org/#/htlc)
2. Create HTLC
3. See that after this a new HTLC does not appear in the list.

**Expected behavior**
See the new HTLC

**Screenshots**
![D4s0XHXP4S](https://user-images.githubusercontent.com/17462020/60594789-640db100-9dae-11e9-85eb-bd7d897f89cc.gif)

**Desktop (please complete the following information):**
 - Windows 7/10
 - Light Client 3.1.190618.1
 - Firefox 67.0.4
 - Chrome 71

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/pull/3129#issue-342184216
