### ISSUE TITLE
Error: MD5 of downloaded file (6F0AAC4B3D4F478B37F9F57A3E502F1C) not matches expected (0F4B4F04A2BD6511722F666CA89248D1)

### ISSUE THREAD

**Issue by gades** [bitshares/bitshares-ui#2889]
**Describe the bug**
Can't install install-charting-library

**To Reproduce**
1. Clone latest code
2. npm install 
3. See error

**Additional context**
> BitShares2-light@3.1.190618-rc1 postinstall /Users/hades/Documents/repos/bitshares-ui
> npm run install-charting-library

> BitShares2-light@3.1.190618-rc1 install-charting-library /Users/hades/Documents/repos/bitshares-ui
> node ./charting_library/install-charting-library.js

/Users/hades/Documents/repos/bitshares-ui/charting_library/install-charting-library.js:27
        throw new Error("MD5 of downloaded file (" + actualDigest + ") not matches expected (" + expectedDigest + ")");
        ^

Error: MD5 of downloaded file (6F0AAC4B3D4F478B37F9F57A3E502F1C) not matches expected (0F4B4F04A2BD6511722F666CA89248D1)
    at WriteStream.outputFile.on (/Users/hades/Documents/repos/bitshares-ui/charting_library/install-charting-library.js:27:15)
    at WriteStream.emit (events.js:185:15)
    at finishMaybe (_stream_writable.js:636:14)
    at afterWrite (_stream_writable.js:478:3)
    at onwrite (_stream_writable.js:468:7)
    at fs.write (fs.js:2254:5)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:700:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! BitShares2-light@3.1.190618-rc1 install-charting-library: `node ./charting_library/install-charting-library.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BitShares2-light@3.1.190618-rc1 install-charting-library script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hades/.npm/_logs/2019-07-04T05_18_05_771Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! BitShares2-light@3.1.190618-rc1 postinstall: `npm run install-charting-library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BitShares2-light@3.1.190618-rc1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/hades/.npm/_logs/2019-07-04T05_18_05_812Z-debug.log

**Comment by allfory0u** [comment]
Maybe it's related with #2826?

**Comment by gades** [comment]
@allfory0u probably yes

**Comment by mrugakshee** [comment]
I have the same error.

**Comment by startailcoon** [comment]
This issue is related to the move of the charting library, as mentioned before here. For some reason the expected hash doesn't match the file hash of the download.

Does the hash error look the same to you @mrugakshee?

**Comment by mrugakshee** [comment]
> This issue is related to the move of the charting library, as mentioned before here. For some reason the expected hash doesn't match the file hash of the download.
> 
> Does the hash error look the same to you @mrugakshee?

Yes, it looks the same:

Error: MD5 of downloaded file (6F0AAC4B3D4F478B37F9F57A3E502F1C) not matches expected (0F4B4F04A2BD6511722F666CA89248D1)

at WriteStream.outputFile.on (/Users/mrugaksheepalwe/Documents/Git/bitshares-ui/charting_library/install-charting-library.js:27:15)
    at WriteStream.emit (events.js:185:15)
    at finishMaybe (_stream_writable.js:636:14)
    at afterWrite (_stream_writable.js:478:3)
    at onwrite (_stream_writable.js:468:7)
    at fs.write (fs.js:2254:5)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:700:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! BitShares2-light@3.1.190618-rc1 install-charting-library: `node ./charting_library/install-charting-library.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the BitShares2-light@3.1.190618-rc1 install-charting-library script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mrugaksheepalwe/.npm/_logs/2019-07-03T23_11_56_445Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by mrugakshee** [comment]
I just pulled new changes and the md5 hash matched, no error anymore on npm install! @startailcoon 
@gades

**Comment by gades** [comment]
@mrugakshee Thanks, it's working now.
