### ISSUE TITLE
Add an easy shapeshift-like currency conversion tool

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#290]
Here's a mockup of an instant exchange idea for BitShares.

![instadex.png](https://steemitimages.com/DQmWA4hbC4YzgtvxAZfAV7L8f3XRWkFB5zkLEAoHz12LJG5/instadex.png)
[Download](https://anonfile.com/34Z1i2cfbb/BTSmokup.psd) PST

Here's how I imagine it:

* Click `INSTANT dEXCHANGE`
* enter amount and asset you want to buy (ex. 10 BITUSD-Dropdown)
* select the payment asset (ex. BTS-Dropdown)
* select slippage (default 5%) - this is to protect the buyer from irrational price differences. It will only buy ask+max slippage

* Click `SUMMARIZE`

Here you'll see the estimated order data.

* Click Here to Finalize Your Order

after you confirmed transaction, there should be another summary stating how much you bought, average price etc.

Feedback?

@billbutler would this be an UI issue?

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
May I suggest summary including progress bar 0-100% or 0-n coins showing how much of your order has filled with a cancel button to keep it simple.

**Comment by wmbutler** [comment]
I don't have any specific feedback here but I am leaving it open as a proposed feature.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
Interface for such a tool could be similar to #21 suggestion or how https://www.0xproject.com/portal or shapeshift.io format it, could be a whole new tab on top like "simple exchange." 

I don't like simple mode concept openledger.io does that changes and hides too much, another tab is plenty.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
This got tagged under **deposit withdraw rewrite**, but this has nothing to do with deposit or withdraw.

It's just simplified interface for exchanging asset A for asset B for those who don't know how to use normal exchange interface.

Like on-chain shapeshift.
