### ISSUE TITLE
[0.5] No auto focus for market picker input field

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2900]
**Describe the bug**
Market picker does not auto focus the input field

**To Reproduce**
1. Click on market picker
2. start typing
3. no input

**Expected behavior**
Auto focus input field for market picker

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - Bitshares 3.1.190618

**Comment by startailcoon** [comment]
Good suggestion. I've enabled autofocus to the input, and also added tabbing the results list with changing market on pressing enter key.

**Comment by startailcoon** [comment]
Accidently pushed this directly to Develop on Commit https://github.com/bitshares/bitshares-ui/commit/6e6d42adb039eff66640695f2c37d39a84cd2e7e

@sschiessl-bcp

**Comment by startailcoon** [comment]
This was fixed part of a direct commit to develop as mentioned above.
Closing issue.
