### ISSUE TITLE
[2] My Open Orders and Settle Tabs does not update on Market Change

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2906]
The same issue that was reported in https://github.com/bitshares/bitshares-ui/issues/2862 exists in the MyOpenOrders component that is used to render a users open orders and market settle orders.

This task is to apply the same fix to this component as done to the MarketHistory.

It will also handle code/view split.

**Comment by sschiessl-bcp** [comment]
here interested
