### ISSUE TITLE
White screen - sending BTS

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2909]
**Describe the bug**
Could not send BTS because of white screen happened 

**To Reproduce**
1. Go to Exchange
2. Click on Send
3. White screen

**Expected behavior**
No white screen

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - Bitshares 3.1.190618

**Additional context**
Error does only come occasional. 
[White-screen-send.log](https://github.com/bitshares/bitshares-ui/files/3372587/White-screen-send.log)

**Comment by startailcoon** [comment]
I can't reproduce this issue.

As you mention you go to the Exchange first, I assume you pick "Send" from the drawer menu on the right. What market are you loading in the background?

**Comment by froooze** [comment]
It already happened once. Some wired circumstances ...

**Comment by sschiessl-bcp** [comment]
reopen if happens again
