### ISSUE TITLE
[1][fletchertyler914] Limit 'asset name' and 'filter' search field length?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#291]
![image](https://user-images.githubusercontent.com/15861527/29467532-cd96083e-8438-11e7-8e95-1d632788e0c0.png)

The 'my market -> **filter**' and 'find market -> **asset name**' fields are not limited in length despite the possible search results being limited in length.

If you open the dev console then paste in a couple hundred thousand characters directly into these fields it increases the CPU resource utilization and somewhat locks up the dev console.

**Comment by svk31** [comment]
That begs the question of why you would ever do such a thing..

**Comment by wmbutler** [comment]
@calvin wondering if there is an easy solution here. @svk31 is there a max allowable number of characters for a reading symbol?

**Comment by wmbutler** [comment]
Trading

**Comment by svk31** [comment]
Yes, it is 16 characters maximum.

```
#define GRAPHENE_MIN_ASSET_SYMBOL_LENGTH 3
#define GRAPHENE_MAX_ASSET_SYMBOL_LENGTH 16
```

**Comment by wmbutler** [comment]
In that case, I think we can safely set maxes on those input fields to solve the pasting issue.

**Comment by fletchertyler914** [comment]
I will claim this one if no one else is working on it.

**Comment by wmbutler** [comment]
It's yours.

**Comment by fletchertyler914** [comment]
PR Submitted:
https://github.com/bitshares/bitshares-ui/pull/317
