### ISSUE TITLE
[1] Find markets 'Base Currency' field doesn't always detect an invalid asset name immediately

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#292]
![image](https://user-images.githubusercontent.com/15861527/29468209-3f495ace-843b-11e7-80e0-3c30f8bd5348.png)

You can enter BTS (valid asset name) then append multiple special characters such as $£"' and it will show as still valid until say 8 special characters have been added, at which the client enforces asset name validity until all of the special characters are gone.

It only works with the same special character in a row, BTS$A | BTS$£ | BTS$1 will be detected as invalid, but BTS$$$$$$ doesn't immediately flag as invalid.

I don't think this would cause any problems for users in production, it's only present within the bitshares light client (webwallets like openledger have a different system for finding markets).

**Comment by wmbutler** [comment]
This is an easily fixable issue

**Comment by wmbutler** [comment]
@rrandom Just wanted to let you know that this will need to be completed in 24 hours to qualify for bounty by 09/01/17

**Comment by rrandom** [comment]
Sorry, I cant do that, I give up



发自我的小米手机
在 Bill Butler <notifications@github.com>，2017年8月29日 00:11写道：

@rrandom<https://github.com/rrandom> Just wanted to let you know that this will need to be completed in 24 hours to qualify for bounty by 09/01/17

**Comment by wmbutler** [comment]
I'll leave this in the 170914 Sprint. Are you still planning to work it, or do you give up completely?

**Comment by rrandom** [comment]
@wmbutler , Thanks, But I think others are free to pick up this issue :)
