### ISSUE TITLE
[0.25][3.1.190618.2-rc1] - Restore/import - missing translation: en.settings.undefined

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2921]
**Describe the bug**
When I go to Restore/Import, there is a translation missing

**To Reproduce**
1. Go to [staging.bitshares.org/#/settings/general](https://staging.bitshares.org/#/settings/general) in mobile browser
2. Click on 'Menu'
3. Click on 'Menu' - 'Settings' - 'Restore/Import'
3. See error - 'missing translation: en.settings.undefined'

**Expected behavior**
No missing translation

**Screenshots**
![image](https://user-images.githubusercontent.com/17462020/60994233-cc353780-a358-11e9-838e-9dec8150944b.png)
![ezgif-3-79ecf363a59c](https://user-images.githubusercontent.com/17462020/60994250-d3f4dc00-a358-11e9-8d1b-ac76b801fe3f.gif)

**Smartphone (please complete the following information):**
 - Android 5.1.1 (MIUI Global 7.2) / Android 9
 - Standart browser v10.4.5 / Chrome 75

**Comment by startailcoon** [comment]
Looks like the translation is using a variable parameter to define what to view, and it's for some reason not set. Shouldn't be to difficult to investigate the reason for this.

**Comment by sschiessl-bcp** [comment]
How did that come back again? We fixed that already at some point ..
