### ISSUE TITLE
[0.5][3.1.190618.2-rc1] - Borrow - text doesn't display the selected borrowed asset

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2926]
**Describe the bug**
Text 'BTS' in the list doesn't change after the choice of a borrowed asset

**To Reproduce**
1. Go to [staging.bitshares.org/#/borrow](https://staging.bitshares.org/#/borrow)
2. Click on list
3. Сhoose a borrowed asset
4. See that the text 'BTS' hasn't changed

**Expected behavior**
See that the text changes according to the selected asset

**Screenshots**
![aQ2j8G2UPy](https://user-images.githubusercontent.com/17462020/60998165-13bfc180-a361-11e9-9a2c-8fb14b012f1e.gif)

**Desktop (please complete the following information):**
 - Windows 7/10
 - Chrome 71 / Firefox 67.0.4

**Comment by startailcoon** [comment]
Should be fairly simple to fix. I expect it to be a state that isn't properly fired.
