### ISSUE TITLE
No TradingView chart update in VIEW MODE

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2928]
**Describe the bug**
Tradingview gets no update from Open Orders icon link

**To Reproduce**
1. Go to another user (VIEW MODE)
2. Click on RUDEX.EOS / BTS 
3. Dashboard -> Open Orders -> Market icon (another market)
4. TradingView shows still RUDEX.EOS / BTS 

**Expected behavior**
Update TradingView

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - Version: 3.1.190618

**Additional context**
similar to #2714

**Comment by froooze** [comment]
similar to #2714

**Comment by startailcoon** [comment]
I can not duplicate this.

Steps I did

1. Go to explore
2. Pick random new user
3. Pick random asset market
4. Trading View appears
5. Click Dashboard
6. Pick other random asset market
7. Trading View appears for that market

What type of account does you have, is it a cloud account or a wallet account? I think this makes a difference. When you go to another account, do you see your own account name or the other account name at the top?

**Comment by froooze** [comment]
@startailcoon: I could **not** reproduce this anymore!

**Comment by startailcoon** [comment]
Closing
