### ISSUE TITLE
Trying to proxy voting to your lifetime / affiliate referrer errors: "cannot proxy to yourself"

### ISSUE THREAD

**Issue by robrigo** [bitshares/bitshares-ui#293]
I noticed a strange bug when I was signing my friend for bitshares up the other day. He used my referral code to access OpenLedger (bitshares.openledger.info?r=robrigo), registered an account, and we saw that I was set to his Lifetime and Affiliate Referrer as expected:

![screen shot 2017-08-19 at 10 02 59 am](https://user-images.githubusercontent.com/590263/29487381-fc94d042-84c5-11e7-8606-9761cf16c8c4.png)

Now here's the weird bug- if he tries to set me to be his voting proxy, the operation errors out as seen below:

![screen shot 2017-08-19 at 10 02 03 am](https://user-images.githubusercontent.com/590263/29487385-1d4fe88a-84c6-11e7-8564-a80a9c897cf5.png)

Notice in that screenshot the user is actually "proxy-bug-testing", but trying to set "robrigo" as a voting proxy fails with "cannot proxy to yourself". Also, the context changes from the logged in user's account view to robrigo's account view at the same time the error is thrown.

I believe the expected behavior is to allow a user to set their referrer as voting proxy without any errors.

**Comment by robrigo** [comment]
Oh yeah, I am using the following build of the Bitshares light client: Version 2.0.170522

**Comment by robrigo** [comment]
Actually I don't think this is even related to referrer system, as I was able to reproduce it on another account that does not have "robrigo" as referrer. IF that's the case, I would say this bug is more urgent than I originally thought; the code to set proxy seems to work only part of the time.

**Comment by btsfav** [comment]
the user is actually watching robrigo's account point of view. so it's naturally not possible to vote there

**Comment by robrigo** [comment]
@btsfav "the context changes from the logged in user's account view to robrigo's account view at the same time the error is thrown."

See:

![bitshares-proxy-bug](https://user-images.githubusercontent.com/590263/29488200-1eb439de-84d4-11e7-9636-9d6aac129001.gif)

**Comment by btsfav** [comment]
@robrigo OpenLedger bug, unable to reproduce in the official webwallet / light client

**Comment by abitmore** [comment]
@robrigo don't click "go to". Click "publish changes" directly.

**Comment by btsfav** [comment]
@wmbutler please close

**Comment by wmbutler** [comment]
@robrigo we fixed this silliness in the bts version. Doesn't look like openledger has pulled out fixes.
