### ISSUE TITLE
[1] Make collateral positions easier accessable

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#2930]
**Is your feature request related to a problem? Please describe.**
I think the collateral levels are too much hidden and not direct accessible. 

**Describe the solution you'd like**
- Default retract **Permissions**, **Fee Pool**, **Price Feed**, **Settlement**
- Show **Margin Positions** as default before **Price Feed Data**

**Describe alternatives you've considered**
Save state of retract or non retract

**Screenshot** 
![Asset-info](https://user-images.githubusercontent.com/40874087/61091162-5e186f80-a441-11e9-8ed3-ecd087399c60.png)

**Comment by sschiessl-bcp** [comment]
I agree to all of that.

 - use a collapsible component from style guide (e.g. a + sign at the end of the front)
 - allow the collapsed component to display one in-line piece of information
   - permissions have no in-line information
   - price feed shows current price feed
   - fee pool shows current pool balance
   - settlment show current current force settlement price
- view needs to be responsive in terms of moving cards around
- switch margin position and price feed, default is margin

**Comment by sschiessl-bcp** [comment]
Bounty request: https://github.com/bitshares/bitshares-ui/pull/3013#issue-304671344
