### ISSUE TITLE
Organize localization for Reference UI

### ISSUE THREAD

**Issue by dls-cipher** [bitshares/bitshares-ui#2933]
**Is your feature request related to a problem? Please describe.**
WalletUI is missing proper translations management ever since I've joined BitShares 2017 (probably longer, but lets discuss facts). 
Under the previous management of the team, inconsistency in the terms and data for translation it was just nasty. We did Slovenian and Thai translation in July 2018 and we're not planning to redo if some translation tool is not provided for it. It takes days and hours to be done, and redoing it is not an easy task.

**Describe the solution you'd like**
Transifex or any other localization platform.

**Describe alternatives you've considered**
Up to the management of the team.

**Additional context**
I suggest UI provide funds/budget for translations/bounties with proper review (we have a lot of different businesses/communities from different countries that makes this very doable). 
Nobody is gonna translate it for free, and content is quite extensive where only professional can be hired for proper translation. 

We need **as much as possible** BitShares tools/dapps **available in multi-language.**

**Comment by sschiessl-bcp** [comment]
https://www.transifex.com/bitshares/bitshares-ui-1/dashboard/#

**Comment by sschiessl-bcp** [comment]
Last two rounds (in sync with release cycles):

 - https://github.com/bitshares/bitshares-ui/issues/2754
 - https://github.com/bitshares/bitshares-ui/issues/2558

All that is needed is active contributors.

**Comment by dls-cipher** [comment]
I'm very sorry, I haven't re-checked or followed back ever since July. Wasn't mean to fud and excellent work. Ill login and send requests for Slo, Srb and Thai. 

Close and chee®s

**Comment by sschiessl-bcp** [comment]
> I'm very sorry, I haven't re-checked or followed back ever since July 2018. Wasn't mean to fud, and btw excellent work. Ill login and send requests for Slo, Srb and Thai.
> 
> Close and chee®s

What's your native language?
