### ISSUE TITLE
[4] Use new FeeSelectorComponent accross UI

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2934]
Use new component and remove duplicate code.

1. app/components/Dashboard/SimpleDepositWithdraw.jsx
2. app/components/Showcases/Barter.jsx
3. app/components/Modal/HtlcModal.jsx
4. app/components/Modal/WithdrawModalNew.jsx
5. app/components/Modal/DirectDebitModal.jsx
6. app/components/Modal/DirectDebitClaimModal.jsx

**Comment by startailcoon** [comment]
Please make sure the new component doesn't suffer from the same issue as reported in #2941
