### ISSUE TITLE
[3.1.190618.2-rc1] - Propose form - can't change fee asset or quantity of asset

### ISSUE THREAD

**Issue by allfory0u** [bitshares/bitshares-ui#2940]
**Describe the bug**
In 'Propose' form you can't change fee asset or quantity of asset..It remains the same as was selected on the 'Send' form.

**To Reproduce**
1. Go to 'Send/Propose' form
2. Choose a fee asset
3. Click in 'Propose'
4. See that you can`t change fee asset or quantity of asset in 'Propose' form

**Expected behavior**
Chance to change a fee asset

**Screenshots**
![BUf3XFx9jV](https://user-images.githubusercontent.com/17462020/61159347-62599100-a504-11e9-8003-2e4503aec370.gif)

**Desktop (please complete the following information):**
 - Windows 7/10
 - Light Client 3.1.190618.1
 - Firefox 67.0.4
 - Chrome 71

**Smartphone (please complete the following information):**
 - Android 5.1.1 (MIUI Global 7.2) / Android 9
 - Standard browser v10.4.5 / Chrome 75

**Comment by startailcoon** [comment]
You need to select the "From" account first, as it's the account that dictates what assets that are available.
