### ISSUE TITLE
Withdrawal fee is using wrong asset

### ISSUE THREAD

**Issue by gades** [bitshares/bitshares-ui#2941]
**Describe the bug**
in case of withdrawal, you can choose BTS and other assets (BTS is working fine, but in case choose a different one it will use first asses from the list but not selected)

**To Reproduce**
1) create two asset
2) issue some coins to each asset
3) goto to withdraw and select as fee any asset 
4) please check which asset will be used
5) try to select the new one for fees 
6) please check which asset will be used 

![ezgif com-video-to-apng](https://user-images.githubusercontent.com/4200730/61168282-2cdc9400-a554-11e9-80e6-b981506ae09a.png)

**Expected behavior**
it must use selected asset 

**Desktop (please complete the following information):**
 - OS: mac os 0.14.5 (18F132)
 - Browser crome Version 75.0.3770.100 (Official Build) (64-bit)
 - Version 00d7b162d999ae9c7b75572870e41d9f84c69416

**Comment by startailcoon** [comment]
Duplicate #2934
