### ISSUE TITLE
[0.25] Default market for BitAssets should be the collateral (not always BTS)

### ISSUE THREAD

**Issue by cloud-8** [bitshares/bitshares-ui#2942]
**Describe the bug**
The 'Market' button takes a user to the default market on the DEX for that smartcoin, for most (all?) smartcoins that is BTS as it is the backing asset, except stable.PHP or other private smartcoins that may be collateralized with an asset that is not BTS. In this case the backing asset in bitUSD and this should be the default market for this asset. The bug is that it still links to BTS in UI. 

**To Reproduce**
1. Go to 'Explore'
2. Click on 'Smartcoins'
3. Type 'stable.PHP'
4. Click on 'Market'
5. User redirected to stable.PHP/BTS market

**Expected behavior**
Step 5 of above user should be redirected to stable.PHP / BitUSD market. 

**Screenshots**
Uploaded

**Additional context**
<img width="1240" alt="BitUSD market stable" src="https://user-images.githubusercontent.com/12015961/61192452-f7b47b00-a6e6-11e9-84bf-679cb6d429e8.png">

**Comment by abitmore** [comment]
STABLE.PHP has this attribute:
```
"description": "{\"main\":\"STABLE.PHP is a trustless Stablecoin pegged to the value of 1 Philippines Peso. It is created by locking BitUSD as collateral on the Bitshares DEX (dex.bitspark.io). \",\"short_name\":\"1 Philippines Peso\",\"market\":\"\"}"
```
It means no default market has been specified by the asset owner. An easy solution is to ask the asset owner to set a default market.

**Comment by sschiessl-bcp** [comment]
Exactly, you can set the default market in the UI under update asset or manually (but need to stick to the json payload).

So the discussion can be: Is BTS a feasible default for a non-BTS backed bitasset?

**Comment by cloud-8** [comment]
Great ok asset issuer has updated default market. 

> So the discussion can be: Is BTS a feasible default for a non-BTS backed bitasset?

Probably as an ease of use change the default should be the underlying collateral asset unless otherwise defined by issuer.

**Comment by startailcoon** [comment]
I agree with @cloud-8 here, if the asset owner hasn't defined a specific market, the collateral asset defined should be the default market. I don't see why BTS should be the default if it's not the collateral asset.

User Issued Asset can have BTS, as they have no collateral.
