### ISSUE TITLE
[0.5] Sortable Feed Table w/ offset

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2947]
An assets Feed table wasn't possible to sort. This makes it difficult to view if any of the current feeders have issues. Having an easy way to view the current offset from the median price feed further makes it possible to view a witness feeds.

An offset of +/- 1% will view the value in a red-ish style.

### With offset

![image](https://user-images.githubusercontent.com/12114550/61228090-daeb6800-a725-11e9-92db-57bdbed198a4.png)

**Comment by sschiessl-bcp** [comment]
@sschiessl-bcp
add different levels and add alert as well (5 yellow,10 red)

**Comment by startailcoon** [comment]
> @sschiessl-bcp
> add different levels and add alert as well (5 yellow, 10 red)

You mean that we should add additional colors when offset is +/- 5% and +/- 10% as well?

**Comment by sschiessl-bcp** [comment]
> > @sschiessl-bcp
> > add different levels and add alert as well (5 yellow, 10 red)
> 
> You mean that we should add additional colors when offset is +/- 5% and +/- 10% as well?

Changed now to: median=white, below=red, above=green
