### ISSUE TITLE
[1] Voting: Ensure filtering works across witness, committee and workers

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2953]
![image](https://user-images.githubusercontent.com/33128181/61375185-83243c80-a89e-11e9-8aa6-09d0b7446294.png)

**Comment by sschiessl-bcp** [comment]
Offspring of https://github.com/bitshares/bitshares-ui/issues/2742

**Comment by startailcoon** [comment]
Adding an hour for this task.

**Comment by sschiessl-bcp** [comment]
I accidently fixed it in the refactoring :)
