### ISSUE TITLE
BitShares Deposit/Withdraw Engine upgrade

### ISSUE THREAD

**Issue by btswolf** [bitshares/bitshares-ui#296]
The BitShares user base is growing quickly and we have to prepare for many additional businesses and transfer providers that  will join the ecosystem. 

If you are familiar with  the BitShares reference client you might get used on how to deposit, withdraw and send funds on- and off-chain, hereafter called the DW-Engine. But new users often struggle to understand how to use the DW-Engine and the result is many questions and complaints raised in the community channels.
Therefor I recommend to upgrade the DW-Engine and simplify all procedures as far as possible.

To begin with I would suggest to get rid of the separate "SEND" menu and merge the send and withdraw function in a single Menu. 

#### Menu
**Deposit/Withdraw**
#### Submenu
**Deposit**
**Withdraw**->choose between send and withdraw
**Custom**->Legacy DW-Engine provided by transfer providers, also for FIAT etc.

#### High-Level
* Merge send and withdraw function
* Guide the user through the process
* Display only required fields and options

#### Mid-Level
* Choose between deposit and withdraw or custom
* Select a token
* Enter amount
* Choose between on/off-chain
* Select transfer-provider (optional)
* Enter recipient (send/withdraw)
* Enter memo (send/withdraw)
* Switch fee token (optional)
* Custom service provider (custom/legacy DW engine)

#### Detail-Level
* see process diagram

To make the DW-Engine smart enough a small database/table is required to host and maintain the required transfer-provider information. The table could be embedded in the client itself or if possible could be hosted on github repository for realtime updates(if approved by n devs).
* Token
* Name
* Symbol
* Provider
* URL

I am not a developer nor a designer but I've created a couple of mockup screens for **Deposit**, **Withdraw** and **Send** as well as a process diagram to visualize how the procedures could be built to match the mockup screens.
This github issue is only for the DW-Engine, other visible mockup design elements or colors are not part of my suggestion.

[![DEPOSIT Screen](https://steemitimages.com/DQmTKBzE5WsTV3ZzseyYrVWEHf96gSgm5hPtYEuDMax2WMQ/Slide5.PNG)](https://steemitimages.com/DQmTKBzE5WsTV3ZzseyYrVWEHf96gSgm5hPtYEuDMax2WMQ/Slide5.PNG)
**Deposit example**

[![SEND Screen](https://steemitimages.com/DQmYE5nUH7vCw2GWHiWRgNn7JuTwNtxH8vRs5YPZRMGD9Mp/Slide6.PNG)](https://steemitimages.com/DQmYE5nUH7vCw2GWHiWRgNn7JuTwNtxH8vRs5YPZRMGD9Mp/Slide6.PNG)
**SEND example**

[![WITHDRAW Screen](https://steemitimages.com/DQme49zwjb7eb9a7G2wc2jy3mg1rXH9YZirnudcXsh6iN4J/Slide7.PNG)](https://steemitimages.com/DQme49zwjb7eb9a7G2wc2jy3mg1rXH9YZirnudcXsh6iN4J/Slide7.PNG)
**WITHDRAW example**

[![CUSTOM Screen](https://steemitimages.com/DQmcibZrs5G2Lk3ky66EnRx3Sj1RC73bhQzDpapUFg574T2/Slide8.PNG)](https://steemitimages.com/DQmcibZrs5G2Lk3ky66EnRx3Sj1RC73bhQzDpapUFg574T2/Slide8.PNG)
**CUSTOM example** for legacy DW-Engine and FIAT operations

[![DW-Engine_process_diagram](https://steemitimages.com/DQmTzVXmmwnyRnvcKkUryGvtGeXJeB5jLuwta74bhK3EvKN/DW-Engine_process_diagram.png)](https://steemitimages.com/DQmTzVXmmwnyRnvcKkUryGvtGeXJeB5jLuwta74bhK3EvKN/DW-Engine_process_diagram.png)
**DW-Engine Process diagram**

[![Transfer_Provider_Information_example](https://steemitimages.com/DQmQNiBfwaKqLcn1Ky2XaRbRc99MZdQcev8HcMZemzmXLRc/Transfer_Provider_Information_example.png)](https://steemitimages.com/DQmQNiBfwaKqLcn1Ky2XaRbRc99MZdQcev8HcMZemzmXLRc/Transfer_Provider_Information_example.png)
**Transfer-Provider-Information example table** required for the automatic token to transfer-provider enumeration

Even if my mockup's may be to complex I hope we can at least use some parts to make the DW-Engine somewhat more comfortable.

**Comment by jonnybitcoin** [comment]
I feel that the UI used for blocktrades bridge could be used as a gateway. deposit Bitcoin.  then choose which BTC.UIA you want to receive.  Simple

**Comment by wmbutler** [comment]
- #556 
- #557
