### ISSUE TITLE
[4] Refine wallet merchant protocol

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2960]
Tasks:

1. Add to spotlight
2. Add QR code for payment (in the middle right of the screen). Add a toggle button that allows to switch between invoice QR code, and payment QR code. Default is payment QR code.
![image](https://user-images.githubusercontent.com/33128181/62054673-56671200-b21a-11e9-99fb-c4aad5b2ce77.png)
   - payment QR code contains `bitshares:operation/transfer?to=<pay_to_account>&from=<pay_from_account>&asset=<currency>&amount=<amount>&memo=<invoiceno>`
   - invoice QR code contains the invoice string
3. Add route `/invoice`, has two tabs (Request, and Pay)
   1. Request allows to create an invoice string (see the getExample in the Invoice component)
       - User specifies recipient account (default currentAccount)
       - Identifier (the string "Invoice #1234" in the above screenshot)
       - Currency
       - Optional recipient name
       - Optional Note
       - Dynamic form to input items (use https://ant.design/components/form/#components-form-demo-dynamic-form-item)
    2. Pay shows the user a simple textarea input with confirm, and if mobile allows the user to scan a QR code
4. When loading a invoice string, make sure the json format is properly filled (there is a validateInvoice method in Invoice component)

**Comment by abitmore** [comment]
BSIP60 compatible?

**Comment by sschiessl-bcp** [comment]
Bounty request in https://github.com/bitshares/bitshares-ui/pull/3052#issue-312153080
