### ISSUE TITLE
[0.5] Incorrect settle orders data in exchanges page

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2965]
**Describe the bug**

**To Reproduce**
1. Go to 'https://wallet.bitshares.org/#/market/BTS_CNY' (type URL in address bar)
2. Scroll down to 'settle orders'
![image](https://user-images.githubusercontent.com/9946777/61523440-abce4280-aa14-11e9-9823-bf47ae90a7dd.png)

3. click another market from the market list, e.g. BTS/bitusd
![image](https://user-images.githubusercontent.com/9946777/61523560-e932d000-aa14-11e9-8e18-5f4169f3d130.png)

4. See error data in the page
![image](https://user-images.githubusercontent.com/9946777/61523700-2ac37b00-aa15-11e9-89de-253020777d02.png)

**Comment by startailcoon** [comment]
I suspect that there's a state change that isn't firing. Should be small fix.
