### ISSUE TITLE
Require an active agreement before Proposals can be used in UI

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2967]
We've had many issues with proposals on the chain lately, and we've enabled various fail safes and requirements for users so they don't accidently accept a proposal. Many of the later cases have been users not upgrading the UI that has these countermeasures. 

However, even with the requirement of a propose to be in the white-list and that approve is automatically disabled for these accounts I suspect that some users just doesn't understand that a proposal coming from an account that looks like a gateway really isn't one.

I propose that when a user goes to the proposals tab for the first time, the user is shown the text from the help document (which should also be updated), and then required to approve that they have read and understood this.

This is then stored in the app, and not displayed again, unless the user resets or installs the app again.

### Proposed Transactions (Today)

The current text regarding proposed transactions are outdate, just stating that it's used for multisig account and that you don't need it unless you use it.

> This is an advanced feature of Bitshares accessible from the send feature. It allows for something known a multisig. Imagine you have a single account but require more than one person to authorize a transaction. This capability is built into bitshares, but requires advanced knowledge and there is a setup process. If you haven't previously setup multisig for your account, it's safe to say you do not need it.

### Proposed Transaction (Suggested)

>With the feature of a proposal, anyone can submit a transaction to the blockchain with a "Proposed" action. This is an advanced feature mostly used for accounts that is owned by several individuals or entities, but is not limited to this type.
>
>An example of proposals are when an account, which requires operations to be signed by several parties. One of the parties submit a proposal that requires a predefined amount of support of the owners to be executed.
>
>Regular usage very seldom requires the usage of proposed transactions. If one have been submitted to your account without you expecting one, be very careful. 
>
>Always contact third parties directly, such as gateways, bridges or other accounts, when in doubt of something that is required of you that seems to involve a proposed transaction.
>
>---- Approve Here -----
>[ ] - I have read and understood what Proposed Transactions are and what they are used for on the Bitshares Blockchain.
>[ ] - I understand that a proposed transaction is another account, proposing that my account does something.
>[ ] - I understand that any actions on the blockchain is irreversible and can not be undone.
>
>[Approve]
>
-----

**Comment by abitmore** [comment]
Generally this is good.

> Regular usage very seldom requires the usage of proposed transactions.

See Barter and etc in Spotlights, quite some of them make use of proposals.

It is an advanced feature for sure. But seldom used? IMHO no.

**Comment by startailcoon** [comment]
The text can be adjusted. Generally I feel it's not used by new users, but I may be wrong. The goal here is to make users understand it's not something they have to use unless they expect it. I've read about users thinking it's something a gateway do, which is not the case.

**Comment by sschiessl-bcp** [comment]
Agreed, a popup with links and reference to help would be a good addition.

**Comment by abitmore** [comment]
ETA of this feature?

**Comment by startailcoon** [comment]
ETA around the end of current milestone hopefully.

**Comment by sschiessl-bcp** [comment]
Adjusted the help text.
