### ISSUE TITLE
OPEN.EOS withdrawal issue

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#2968]
https://steemit.com/cn/@tvb/bitshares-eos

* A user tried to withdraw OPEN.EOS on https://wallet.bitshares.org, in the end the funds sent to `openledger-dex` account, but she didn't receive on EOS network;
* Openleger support refunded her the funds, asked her to withdraw on https://dex.openledger.io, finally funds sent to `openledger-gateway` account;
* She tried to withdraw on https://wallet.bitshares.org again, failed again.

![image](https://user-images.githubusercontent.com/9946777/61595418-4dad8500-abf7-11e9-9933-a87724610e57.png)

If OpenLedger is not going to maintain the functionality, is it better to remove the gateway from the reference UI?

**Comment by startailcoon** [comment]
Seems very strange that the wallet doesn't get the correct account from the API of OL.

**Comment by OpenLedgerApp** [comment]
@startailcoon this is the issue in the old api, could you please look into this pr?
https://github.com/bitshares/bitshares-ui/pull/2573

**Comment by sschiessl-bcp** [comment]
We need to finalize standardization of new API, and your PR is delayed until then. If your old API is no longer working we need to disable it in the reference wallet until the standardization is completed. 

What is your preferred way? Fix old API, or disable and wait until new is ready?

**Comment by startailcoon** [comment]
> 
> 
> @startailcoon this is the issue in the old api, could you please check this pr?
> #2573

You mean the old API does not work as expected any more? Please clarify, as you've stated the following in the PR #2573 

> ... we are gradually moving to a new api, and when all coins will work with new api, we will need to refactor because now gateway system works for both api.

I understand this comment as
1. All coins does not yet work with the new API
2. Current gateway works with both current and your new API structures

Is this not true?

**Comment by OpenLedgerApp** [comment]
@sschiessl-bcp we will fix old api.

**Comment by startailcoon** [comment]
> 
> 
> @sschiessl-bcp we will fix old api.

ETA?

**Comment by OpenLedgerApp** [comment]
@startailcoon we will be able to give you the ETA on Friday this week

**Comment by startailcoon** [comment]
Without thinking on it I just withdrew an amount of OPEN.ETH, which was went to the wrong account. I've submitted a support ticket about this.

But I think that in case this is not fixed for the new release coming out, we will have to disable Opel Ledger Gateway on the reference wallet. 

@sschiessl-bcp @OpenLedgerApp

**Comment by startailcoon** [comment]
@OpenLedgerApp Friday passed and no ETA?

**Comment by OpenLedgerApp** [comment]
@startailcoon sorry for delay. To fix old api we need more than one month.

**Comment by sschiessl-bcp** [comment]
How can this break just like that, and then need a one month fix? That sucks, but so be it ...

**Comment by startailcoon** [comment]
This issue will be solved in short term by disabling the openledger gateway in the next release. We will work on a on-chain dynamic gateway toggle, see issue #3008

**Comment by sschiessl-bcp** [comment]
@OpenLedgerApp deactivated OPEN gateway for now

**Comment by abitmore** [comment]
Done / stale.
