### ISSUE TITLE
Simplified order form for ordinary users (i.e. non-traders) 

### ISSUE THREAD

**Issue by tbone-bts** [bitshares/bitshares-ui#2973]
It would be very useful and would promote adoption if the wallet offered a simplified form for ordinary users (i.e. non-traders) to convert one token to another WITHOUT an orderbook by simply specifying a) the token they have, b) the token they want, and c) a quantity. 

To date, it has not been feasible to offer such a UI for the DEX due to lack of liquidity. However, with arbitrage / mirrored liquidity feature coming to DexBot soon, this type of UI could offer a far better user experience than previously possible.

Of course, even with improved liquidity, not all markets will have sufficient liquidity at all times. But by giving feedback to the user about e.g. how their average price would compare to the current best price, even a beginning user could make an intelligent decision about whether to proceed.

The user could even be presented with the option to essentially place a limit order (even though they wouldn't see the orderbook), with the proviso that the order would likely not get filled instantly (or might not be filled completely). For example, by placing a buy order with a price perhaps slightly above the best ask (or a sell order with a price slightly below the best bid), it would fill partially and then the remaining shares should present an arbitrage opportunity that can be taken advantage of by DexBots monitoring that market, thus filling the rest of the order and completing the user's requested conversion.

I strongly believe the lack of this type of user-friendly UI is one of the factors contributing to low adoption rate of the DEX. 

Thoughts?

**Comment by startailcoon** [comment]
Sounds like a good idea to me, I like it. As mentioned, the risk here is that the market has low liquidity, making the price divert from the actual price. I believe that this could easily be solved by a good design, and where we highlight the variation from median / last price on that market.

We could for example have that if a users market trade will result in more than x% of median / last price, it will notify the user and require a final confirm. We could also, always display the variation and the price.

**Comment by startailcoon** [comment]
We could look on making an easy popup (not modal) like with the "Go to mark & Invert" popup we have. With a simple form that would calculate the conversion result and price difference from market.

![image](https://user-images.githubusercontent.com/12114550/61824225-c281f880-ae5d-11e9-9f9c-c5365bc5235d.png)

**Comment by sschiessl-bcp** [comment]
Add a new button in that popup, and a new route. We could call it `Quick Trade`, or even `Market Swap`. I have a UX in mind ... will try to sketch it and post here.

**Comment by startailcoon** [comment]
> 
> 
> Add a new button in that popup, and a new route. We could call it `Quick Trade`, or even `Market Swap`. I have a UX in mind ... will try to sketch it and post here.

Nice, looking forwards to it.

**Comment by sschiessl-bcp** [comment]
![image](https://user-images.githubusercontent.com/33128181/62462389-96cd0f80-b787-11e9-9078-28f600e6adb1.png)

**Comment by sschiessl-bcp** [comment]
<h1>On the UI</h2>

Sell and receive are horizontally aligned for screen > smallWidth, otherwise vertically.
Price / Fees / Orders are collapsable and contain lists of detail data, label on the left and content on the right.

Price contains:
 - price of the above displayed trade
 - current feed price
 - current last market price

Fees contains:
 - Two numbers, format is 00,00%, percent difference: `(1 - your_price / market_price)` and  `(1 - your_price / feed_price)` 
 - Market fee if any incurred
 - Transaction fee incurred

Orders contain:
 - Contains a table with all orders that would get matched if my trade is executed and at what price (I always get best price of the maker order, even if I have a worse price defined in my own order)

**Comment by sschiessl-bcp** [comment]
<h1>On the implementation</h1>
Re-use where possible and avoid code duplication. Wrap everything in a middle centered card like prediction markets or borrow. Use BindToCurrentAccount.

<h2>Sell and Receive</h2>
Create one component that provides this, essentially it is a restyled asset selector component. 

<h2>Price, Fees, Orders</h2>
Style guide is a collapsable component. Order details are a antd table, please check if anything from exchange / open orders can be re-used.

<h2>Integration to blockchain / markets</h2>
Provide an abstract components that provides:

 - `getOrders`: Returns a list of dicts with keys `id`, `seller` `amount` and `price` and respective values, input is selected assets and amount to sell
 - `getPrices`: Returns a dict with keys `feedPrice` and `lastPrice` and respective values, input is selected assets and amounts
 - `calculateFees`: Returns a dict with keys `liquidityPenalty`, `marketFee` and `transactionFee`, input is selected assets and amounts
 - `getAssetsToSell`: Returns a list of asset ids that the user can sell
 - `getAssetsToReceive`: Returns a list of asset ids that the user can buy, input is selected asset to sell

**Comment by sschiessl-bcp** [comment]
<h2>On the UX</h2>
Both select components are empty when screen loads, collapsable components are not visible. When user selects the asset to sell, the list of assets to receive is populated, pre-select the first in the list, then show and load the collapsable components, all 3 collapsed as default.

Will refine as we go.

**Comment by tbone-bts** [comment]
@sschiessl-bcp I think what you describe is a very good start. And for this purpose, I really like your idea of displaying info only from the relevant side of the order book. In fact I've long thought this would be very helpful in creating a simplified buy/sell UX. 

Perhaps that table can include columns that indicate to the user how many cumulative shares they would instantly get at each level, the average price, and how many shares they would have to wait for. Maybe something like this?


![QuickExchange_infotable2](https://user-images.githubusercontent.com/15830348/62734710-a488cc00-b9f7-11e9-8d7a-78bf8e6548e0.JPG)

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/pull/3077#issue-321737208
