### ISSUE TITLE
[4] Implement new FeeSelect component

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#2975]
New component introduced in https://github.com/bitshares/bitshares-ui/issues/1117.

This task is refactoring / code clean-up only.

1. app/components/Dashboard/SimpleDepositWithdraw.jsx
2. app/components/Showcases/Barter.jsx
3. app/components/Modal/HtlcModal.jsx
4. app/components/Modal/WithdrawModalNew.jsx
5. app/components/Modal/DirectDebitModal.jsx
6. app/components/Modal/DirectDebitClaimModal.jsx

Report the current UI for each change beforehand, in case we need to adjust UX.

**Comment by startailcoon** [comment]
What is the difference from https://github.com/bitshares/bitshares-ui/issues/2934?

**Comment by sschiessl-bcp** [comment]
I forgot the other one existed ....

**Comment by startailcoon** [comment]
Closed other one. Here's a comment I made on the other issues

> Please make sure the new component doesn't suffer from the same issue as reported in #2941
