### ISSUE TITLE
[3] Update Vesting Balances to Table Style

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#2979]
Today we have the vesting balances in a uncomfortable list, mainly because it wasn't used by others than witnesses and workers, while LTM had usually just one object, their normal vesting balance.

Since we started with the market fee reward, a LTM will have one object per asset reward, which can be a very large number.

I feel that a table structure would be beneficial for the usage of this.

### Proposed Structure

The table should be sortable and searchable by "ID" and "Type".

ID|Type|Balance|Required|Earned|Remaining|Available|Action
-|-|-|-|-|-|-|-
1.13.001|Cashback|80 BTS|1000&nbsp;coin&nbsp;days|800&nbsp;coin&nbsp;days|200&nbsp;coin&nbsp;days|80%|[Claim]
1.13.002|Market&nbsp;Fee|10&nbsp;bitUSD|-|-|-|100%|[Claim]
1.13.003|Other|300&nbsp;MYASSET|100 days|50 days|50 days|0%|-

**Comment by sschiessl-bcp** [comment]
Bounty request in https://github.com/bitshares/bitshares-ui/pull/3014#issue-304681417

**Comment by startailcoon** [comment]
The state isn't updated correctly when switching between accounts in the header menu.

`retrieveVestingBalances()` is called correctly, when the account changes, but the following doesn't update correctly and needs checking.

https://github.com/bitshares/bitshares-ui/blob/a23543832ccd96a1ee66cf4bcd943a693ea5ec0d/app/components/Account/AccountVesting.jsx#L197

**Comment by sschiessl-bcp** [comment]
Fixed https://github.com/bitshares/bitshares-ui/commit/de1d7b512f7c8d1bd4b95ec617ee9d4be6e3da24

**Comment by startailcoon** [comment]
> 
> 
> Fixed [de1d7b5](https://github.com/bitshares/bitshares-ui/commit/de1d7b512f7c8d1bd4b95ec617ee9d4be6e3da24)

Was this the only requirements to make this work? If it's verified to work I'm okay with it.
