### ISSUE TITLE
[0.25] Gdex.usdt withdraw minimum

### ISSUE THREAD

**Issue by Mahdi321** [bitshares/bitshares-ui#2982]
The withdraw form doesn't recognize how big number is in below condition

**To Reproduce**
1. Open gdex.usdt withdraw form
2. Enter an amount that start with number 1

**Screenshots**
![image](https://user-images.githubusercontent.com/27496531/61947221-0274e700-afe8-11e9-808a-2a8038f24982.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.1.190618.1

**Comment by startailcoon** [comment]
That's a strange thing, needs some checking on.

**Comment by OpenLedgerApp** [comment]
@startailcoon I can take this one.

**Comment by startailcoon** [comment]
> @startailcoon I can take this one.

Assigned. Make sure there is no location issue for this, never seen this issue before when using it.
