### ISSUE TITLE
[5.5][Wallet Redesign] Beginners Guide

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2984]
![Begginer's guide (1)](https://user-images.githubusercontent.com/35899973/61962926-f3cc0700-afca-11e9-8fc4-1310ac803531.jpg)

This is a concept of the design for Beginners Guide. 

@sschiessl-bcp @startailcoon for the other tabs I need to get texts what are the info we should display and tell to our users when they visit our Platform for the first time. 

When I receive texts, Alex will work on the other steps and their good visualization.

**Comment by sschiessl-bcp** [comment]
What does the numbering indicate?
