### ISSUE TITLE
[8.5][Wallet Redesign] Mobile Layout + Mobile Dashboard

### ISSUE THREAD

**Issue by gibbsfromncis** [bitshares/bitshares-ui#2987]
### Mobile Dashboard 

As a sample for mobile Layout, we took a Dashboard. The first thing regarding Layout is 
- **Should we display Bitshares Logo in the top or not.**  cc @sschiessl-bcp @startailcoon 

<img width="350" alt="Screenshot 2019-07-26 17 48 04" src="https://user-images.githubusercontent.com/35899973/61964164-8a99c300-afcd-11e9-89db-45ef463b3b42.png">

### Dashboard without logo full-size
<img src="https://user-images.githubusercontent.com/35899973/61964052-4e666280-afcd-11e9-847e-c38b7c6b382e.jpg" width="350"/> 

### Dashboard with logo full-size
<img src="https://user-images.githubusercontent.com/35899973/61964054-50302600-afcd-11e9-839b-f113ef30ac3a.jpg" width="350"/>

### Dashboard when user clicks on "full-screen" icon on some widget:

<img src="https://user-images.githubusercontent.com/35899973/61964639-a94c8980-afce-11e9-8a96-526acddf65a5.jpg" width="350"/>

### Mobile Dashboard add a widget

We have 3 options:
1) Do not display steps navigation and "back" icon for sub-views
2) Display steps navigation for things like pages create / edit on Mobile Devices.
3) Display only "back" icon for sub-views 

<img width="883" alt="Screenshot 2019-07-26 17 50 15" src="https://user-images.githubusercontent.com/35899973/61964301-d9dff380-afcd-11e9-9337-1df034b81c82.png">

### Sub-view with steps-navigation

<img width="250" src="https://user-images.githubusercontent.com/35899973/61964459-33482280-afce-11e9-9933-80378de92158.jpg">

### Sub-view with "back" icon

<img width="250" src="https://user-images.githubusercontent.com/35899973/61964463-34794f80-afce-11e9-8cb5-9b4b82e21112.jpg">

### Sub-view without back icon and without navigation

<img width="250" src="https://user-images.githubusercontent.com/35899973/61964466-37744000-afce-11e9-9a2c-282d6547b7aa.jpg">

## Mobile Menu

On the mobile menu user will see:

- An account with the ability to click on it to see a full list of accounts + logic/signup link
- Account related-menu (Manage Account, Membership, Logout)
- The same navigation menu like on a desktop version in the left side.

<img width="454" alt="Screenshot 2019-07-26 17 56 57" src="https://user-images.githubusercontent.com/35899973/61964692-c5502b00-afce-11e9-9a3e-893979a4c769.png">

### Mobile Menu with/without Logo

We also have 2 variations of Mobile Menu - with and without bitshares logo:

<img width="450" alt="Screenshot 2019-07-26 18 00 03" src="https://user-images.githubusercontent.com/35899973/61964867-3db6ec00-afcf-11e9-9e46-c55b430a4a9b.png">

**Comment by sschiessl-bcp** [comment]
How do other apps to it with regards to logo?
