### ISSUE TITLE
[.5] warn user on creating/following more than 100 accounts

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares-ui#299]
there is a problem with users having or following more than 100 accounts with the performance of the light client. details of it can be found here: https://github.com/bitshares/bitshares-core/issues/295

last commit will fix the performance problem for users with more than 100 accounts but only subscribe to the first 100. ui should alert or disallow if a user registers or follows are greater than 100.

**Comment by svk31** [comment]
The GUI uses get_full_accounts anytime it needs data for an account, so it's not just limited to accounts you're actively following. The main reason for this is that it's generally the only way to get the data needed without making a lot more API calls.

**Comment by wmbutler** [comment]
So, the user should get a warning if accounts = 99 right?

**Comment by svk31** [comment]
Will most likely be a non-issue after the next release as the GUI now uses get_full_accounts with subscribe=false in most cases.
