### ISSUE TITLE
Withdraw quantity are ignored (always use the total quantity)

### ISSUE THREAD

**Issue by bazan101** [bitshares/bitshares-ui#3004]
**Describe the bug**
Withdrawing a partial amount of BTC for instance the confirmatin modal window  does take into account the quantity asked but the total quantity of asset in the wallet

**To Reproduce**
1. Go to withdrw BTC
2. change the quantity you want to withdraw
3. click "withdraw"
4. the confirmation modal window does not show the quantity asked to withdraw!!!

**Expected behavior**
the quantity in the confirmation window should be the quantity asked to withdraw

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 75

**Additional context**
error: wss://france.bitshares.apasia.tech/wssFailed to initialize with errorundefined
log: fallback to new url:wss://eu-central-1.bts.crypto-bridge.org
log: synced and subscribed, chainstore ready
log: browser notifications disabled by Browser Permissions
log: [object Object]
error: Error: Assert Exception: abo->get_balance() >= -delta: Insufficient Balance: nazab-101's balance of 0 BRIDGE.BTC is less than required 0.00000490 BRIDGE.BTC
bitshares-crypto  digest 9f7bd59239903d2b8380e2bc9c0eee3aacd02a63dffe895e8e6e8eec02ef1363 transaction 6dbfba6c9d7bdbd5425d0100ea01000000000000a20cf79d65a6ee16cfa00b0000000000a20c0102871d084808f6e8096d7cb64a3420629d3f2aed75a322da6f82085506a90e6af203fd657854d21790e34ca9596b5381f342b2b46cf4d706177962fa0a28ecaf96d3fc801c134d6c010040043a8c24bb376bc6dd224841d18dde84b4b67a3ab4ff5477936bcaf623474d44b3f9e3dad07e5518c9add3eec182cfe40dbd22c62d0c9f516c38bf59334b5cec0000 {"ref_block_num":49005,"ref_block_prefix":2073914554,"expiration":"2019-08-01T12:06:51","operations":[[0,{"fee":{"amount":"490","asset_id":"1.3.1570"},"from":"1.2.1658615","to":"1.2.374566","amount":{"amount":"762063","asset_id":"1.3.1570"},"memo":{"from":"BTS5uzeKfZazEZfWad8VTweCCZTyVRSbVdpLD9qWCuVBXxVCKMD6Z","to":"BTS8kqCZbfPP2zQhazivJ9aS44aCd9oprBU55dWGKQZ9Es9tY1gYm","nonce":"400553265627388","message":"043a8c24bb376bc6dd224841d18dde84b4b67a3ab4ff5477936bcaf623474d44b3f9e3dad07e5518c9add3eec182cfe40dbd22c62d0c9f516c38bf59334b5cec"},"extensions":[]}]],"extensions":[],"signatures":["1f3be024b41cc8a8711e387c40f631560f4680a466225e4a34d73f6f622500ad8c25dea9bdd429b8e26c2f11fbd8a3a9fc262cdb63a529d3098d58bb85e5a2a4d5"]}
log: auto selecting to wss://france.bitshares.apasia.tech/wss
log: Connecting to wss://france.bitshares.apasia.tech/wss
error: wss://france.bitshares.apasia.tech/wssFailed to initialize with errorundefined
log: fallback to new url:wss://eu-central-1.bts.crypto-bridge.org
log: synced and subscribed, chainstore ready
log: auto selecting to wss://france.bitshares.apasia.tech/wss
log: Latency result:[object Object]
log: auto selecting to wss://eu-central-1.bts.crypto-bridge.org after latency update
log: Connecting to wss://eu-central-1.bts.crypto-bridge.org
log: synced and subscribed, chainstore ready
log: browser notifications disabled by Browser Permissions
log: Latency result:[object Object]
log: [object Object]
error: Error: Assert Exception: abo->get_balance() >= -delta: Insufficient Balance: nazab-101's balance of 0 BRIDGE.BTC is less than required 0.00000490 BRIDGE.BTC
bitshares-crypto  digest efb053af521ec0ebecd1a4774ee02e2ba57980b79d79b07b7cfb671a29195ec8 transaction aabf8528b14e9dd6425d0100ea01000000000000a20cf79d65a6ee16cfa00b0000000000a20c0102871d084808f6e8096d7cb64a3420629d3f2aed75a322da6f82085506a90e6af203fd657854d21790e34ca9596b5381f342b2b46cf4d706177962fa0a28ecaf96d33530f8154d6c0100400ebbbcfadbbedbc22c0f18a973b0ac573b8906a6b28aec3e301cdb696c73d702a17290f8888494441c46b7209562a797eb0e725d6e40476e9a67088449ab475f0000 {"ref_block_num":49066,"ref_block_prefix":1320233093,"expiration":"2019-08-01T12:10:05","operations":[[0,{"fee":{"amount":"490","asset_id":"1.3.1570"},"from":"1.2.1658615","to":"1.2.374566","amount":{"amount":"762063","asset_id":"1.3.1570"},"memo":{"from":"BTS5uzeKfZazEZfWad8VTweCCZTyVRSbVdpLD9qWCuVBXxVCKMD6Z","to":"BTS8kqCZbfPP2zQhazivJ9aS44aCd9oprBU55dWGKQZ9Es9tY1gYm","nonce":"400553313579061","message":"0ebbbcfadbbedbc22c0f18a973b0ac573b8906a6b28aec3e301cdb696c73d702a17290f8888494441c46b7209562a797eb0e725d6e40476e9a67088449ab475f"},"extensions":[]}]],"extensions":[],"signatures":["1f2849909b1037ec1a279f7d7821fa8e011e955d15ac635c2eb14e82d715c04c933f9ebf113f6c6b48cce6865ca0f972defc9075f29c5bd5c020ebf547710a5b70"]}

**Comment by allfory0u** [comment]
Does this issue occur when using wallet.bitshares.org?

**Comment by sschiessl-bcp** [comment]
Please check in develop.bitshares.org

**Comment by bazan101** [comment]
> Does this issue occur when using wallet.bitshares.org?

yes it occure using wallet.bitshare.org

**Comment by bazan101** [comment]
> Please check in develop.bitshares.org

same situation with develop.bitshares.org

**Comment by allfory0u** [comment]
I think one of the reasons for the problem is that there is no BTS on the account for direct payment of fee

**Comment by bazan101** [comment]
Can I pay in BTC?

**Comment by startailcoon** [comment]
When issue #2975 is implemented, this would be possible to do without BTS.

**Comment by sschiessl-bcp** [comment]
> When issue #2975 is implemented, this would be possible to do without BTS.

Done
