### ISSUE TITLE
Allow gateways to be activated/deactivated on-chain

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#3008]
Two tasks:

1. Cut out the logic from NewsHeadline that loads the on-chain configuration from the asset description. Put it in `lib/chain/onChainConfig` and provide `get` functions, e.g. the notifications are made accesible by exporting `getNotifications` from `onChainConfig`
2. Add a `getGateways` to the `onChainConfig` which returns the key `gateways`. `gateways` is a dict, e.g. could look like
```
gateways = {
    someGatewayId: {
        enabled: false
    }
}
```
3. Gateway configuration in `gateways.js` contains `availableGateways` and in it for each gateway a `isEnabled` flag. On startup, and after connecting to a chain, check if the on chain config has an entry for each gateway, and if `getGateways().gatewayid.enabled == false` then set `isEnabled` to `false`.

**Comment by startailcoon** [comment]
This is a really good idea!

**Comment by sschiessl-bcp** [comment]
Bounty request in https://github.com/bitshares/bitshares-ui/pull/3030#issue-306551866
