### ISSUE TITLE
BitShares GUI Account and Wallet model proposal

### ISSUE THREAD

**Issue by btswolf** [bitshares/bitshares-ui#301]
Since the introduction of the Account model we have to deal with two different models in the #BitShares reference Client GUI, Wallet and Account model.
This has raised numerous questions in the support channels and often it is not obvious which model the user has chosen.
Here are my suggestions to ease the user decision to choose a model and how each model is presented in the GUI.

------------

**First** I suggest to simplify the account creation page in the GUI by adding a simple radio button question.

Are you new to BitShares?
- Yes (`show Account model/grey out Wallet model`)
- No (`show Wallet model/grey out Account model`)

[![Account_Creation](https://steemitimages.com/DQme7bdCdWxTR7d9TcbGfEHGbfzj6XMZ3tXrKtmZ7wXyBBV/Slide1.PNG)](https://steemitimages.com/DQme7bdCdWxTR7d9TcbGfEHGbfzj6XMZ3tXrKtmZ7wXyBBV/Slide1.PNG)

# Account model text
### Account model
The Account model is for beginners as you can use your account and password on any BitShares Client at the same time without additional steps. It provides higher convenience but it is less secure then the Wallet model. However you can start with the Account model now and upgrade later to the Wallet model.
**Use a strong password, ideally 20+ characters!**
- Single account
- Easy login
- Moderate security

# Wallet model text
### Wallet model
The Wallet model stores your BitShares wallet on your computer. It is encrypted with a password of your choice, and can be backed up by either using a brainkey or an encrypted binary file that contains all the private keys. You can create multiple accounts in your wallet and it is more secure then the Account model, but it is restricted to your current computer or browser. To use your wallet in another browser or computer, you must import the wallet backup file or brainkey.
- Multiple accounts
- Wallet file backup required
- High security

------------

**Secondly**, I suggest to change how each model is presented in the GUI as followed.
1. Detect if Wallet or Account model is enabled.
1. If Account model is enabled show ACCOUNT in header menu and sub-menu OVERVIEW as account page
1. If Wallet model is enabled show WALLET in header menu and sub-menu OVERVIEW (all accounts) and ACCOUNT as account page
1. Also if Wallet model is enabled make "Active account" field in header menu a drop-down list to select a different account from wallet.

# Wallet model
### Menu: Wallet -> Overview
[![Wallet_model](https://steemitimages.com/DQmS4DhtTQKoRGewTET4xBKpfFieZ7ozWcCezxgyuW5MELa/Slide2.PNG)](https://steemitimages.com/DQmS4DhtTQKoRGewTET4xBKpfFieZ7ozWcCezxgyuW5MELa/Slide2.PNG)
Show all accounts (including following accounts)
- Account table (`sortable`)
- owner or following
- Account name
- Est. Value
- Voting (`Yes/No/Proxy`)
- Open Orders (`number of open orders and link to open orders`)
- Assets (`number of assets`)
- Collateral (`debt in BTS, warning if a debt position is low [e.g. one of last 5 least collateralized positions]`)
- Account `un-hide-all/hide/un-hide/un-follow`

* Combined History (`including following accounts`)

### Wallet -> Account
[![Wallet_account](https://steemitimages.com/DQmUEynUyY2siBVPXacYDU8jtLGn7s1RoZzDHwJ6kMvGe3m/Slide3.PNG)](https://steemitimages.com/DQmUEynUyY2siBVPXacYDU8jtLGn7s1RoZzDHwJ6kMvGe3m/Slide3.PNG)
**Show active account page**

# Account model
### Account -> Overview
[![Account_model](https://steemitimages.com/DQmXEoywzwLne1NpvkXvTSzVMpTuSMBt1rAoyESKodD7jYn/Slide4.PNG)](https://steemitimages.com/DQmXEoywzwLne1NpvkXvTSzVMpTuSMBt1rAoyESKodD7jYn/Slide4.PNG)
**Show active account page**

**Comment by btsfav** [comment]
See https://github.com/bitshares/bitshares-ui/issues/258

**Comment by btswolf** [comment]
I've moved the account page details to a separate issue since it is not required for this issue.
https://github.com/bitshares/bitshares-ui/issues/310

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
I agree with what's currently called wallet model to be hidden as advanced option. 

I think the use of "wallet" in "wallet model" is the most out of place usecase of that word so far. 

The confusion over whether {bts has a wallet or just a dex, how to withdraw from dex to a wallet?, web wallet and light wallet vs wallet model, is account model a wallet or is just wallet model a wallet}... all stems from the use of "wallet" in that model and lack of reference to that word inside UI.

I mentioned it here https://github.com/bitshares/bitshares-ui/issues/378#issuecomment-329916838 while suggesting having the word "wallet" visible for all and used in general way its always used to describe where money is viewed/accessed.

 "multi-account model" or "multi-account file model" or "file model" seems more appropriate

**Comment by btsfav** [comment]
@o5j5vg55bv5hv5j5f8799f9 or call it "desktop wallet" or something. that implies files.

further, I'd rather call the wallet either "Portfolio" or "Vault".

**Comment by landry314** [comment]
I agree, @btsfav, that "Vault" is more appropriately named than "Wallet" as a wallet is somewhere to hold money and information and this is true for both models. Also, a new app just came out called "BitShares Wallet" further confusing things.

As for the "Account Model", what it is is a way to log in from anywhere with only a password, so shouldn't it be called "Universal Model" or "Remote Model" or "Anywhere Model"? Anyone have any other ideas?

**Comment by landry314** [comment]
There are some more comments on this here https://github.com/bitshares/bitshares-ui/issues/258#issuecomment-324195297 . We should make a new issue for renaming the two models and creating icons for them so we can close #258.

**Comment by tbone-bts** [comment]
This is a good discussion.  There is definitely way too much confusion surrounding the mode names and I agree that this must be rectified.  However, I don't think it's necessary to remove the word "wallet".  Can simply insert the word "file".  I think it also helps to use word "cloud" with "account" (as suggested above).  And finally, I think the word "mode" is more appropriate and clear than "model".  Putting it all together, I think this wording will avoid confusion: 

1. **Wallet File** Mode  _(Multiple accounts, need wallet file to login, maximum security)_
2. **Cloud Account** Mode  _(Single account, login in from any computer, moderate security)_

**Comment by btswolf** [comment]
or 
User mode -> login from any computer, requires username and password
Computer mode -> requires wallet file on your computer, username and password

**Comment by landry314** [comment]
Except it doesn't require a username, I mean, sure, you have an active account, but the wallet is being unlocked with the password and that opens all the accounts in the wallet.

**Comment by landry314** [comment]
@tbone-bts, I think the word "account" needs to be completely dropped from the anywhere model, it is super confusing.

I prefer Model to Mode myself; it is a particular model for verification.

Secure Wallet Model
Cloud Login Model

are some more ideas...

**Comment by wmbutler** [comment]
Even more descriptive is:

- Wallet Model
- Username / Password Model

**Comment by landry314** [comment]
But Username/Password is too long and both methods use a password... How about:

- Local Wallet Model
- Remote Access Model

**Comment by btswolf** [comment]
Local Wallet
Anywhere Login

**Comment by wmbutler** [comment]
Not a fan of "anywhere login"

**Comment by landry314** [comment]
Roaming Access, Universal Access, Cloud Sign-In Model ??

**Comment by btsfav** [comment]
* Locale Wallet
* Single sign-on (SSO) (ref: https://en.wikipedia.org/wiki/Single_sign-on)

**Comment by tbone-bts** [comment]
Calling it "Wallet Model" is confusing as articulated in the post below.  "Wallet File Model" helps avoid that confusion.  As for "Username/Password Model" that's also a bit confusing since there is no username, only an account name.  Also, both models require a password, so it's a bit confusing in that regard as well.  

> I agree with you and fav that what's currently called wallet model to be hidden as advanced option.
>
> I think the use of "wallet" in "wallet model" is the most out of place usecase of that word so far.
>
> Theconfusion over whether {bts has a wallet or just a dex, how to withdraw from dex to a wallet?, web wallet and light wallet vs wallet model, is account model a wallet or is just wallet model a wallet}... all stems from the use of "wallet" in that model and lack of reference to that word inside UI.
>
> I mentioned it here #378 (comment) while suggesting having the word "wallet" visible for all and used in general way its always used to describe where money is viewed/accessed.
>
> "multi-account model" or "multi-account file model" or "file model" seems more appropriate

**Comment by landry314** [comment]
Wallet is not that bad of a word. You store money in your wallet, you take out your wallet to pay for things, you trade money from your wallet for other money at a currency exchange place, you put money in your wallet when someone pays you or you sell something. The question is the confusion over the difference in the models and you do all these things in both models so I do understand why it might be confusing.

The word "file" I feel is weird and maybe to technical?

To break it down to what is really happening:

- Multi-Account Local Interface
- Cloud-Based Universal Login

This explains the difference well but it is too many words. This is really difficult...

**Comment by wmbutler** [comment]
Er mah gerd.

**Comment by wmbutler** [comment]
How about the S3gpo P38 Space Modulator login.

**Comment by kimchi-king** [comment]
Here are my ideas.

Native Vault Model (Multiple wallets, need wallet file to login, maximum security)
Universal Vault Model (Single wallet, login in from any computer, moderate security)

Local Vault Model (Multiple wallets, need wallet file to login, maximum security)
Omni-Vault Model (Single wallet, login in from any computer, moderate security)

Local Vault (Multiple wallets, need wallet file to login, maximum security)
Omni-Vault (Single wallet, login in from any computer, moderate security)

Local Vault (Multiple wallets, need wallet file to login, maximum security)
Universal Vault (Single wallet, login in from any computer, moderate security)

Native Wallet Model (Multiple accounts, need wallet file to login, maximum security)
Universal Wallet Model (Single account, login in from any computer, moderate security)

**Comment by tbone-bts** [comment]
This is getting out of hand, so I'm not going to spend too much more time on it.  But @landry314,  no, "file" is not too technical of a term.  File?  Too technical?  Really?  

Also, no one said "wallet" is a bad word.  But it's being used to mean different things, which is causing confusion.  Did you not read the post by @o5j5vg55bv5hv5j5f8799f9, which I quoted in my previous post?  

We don't need to come up with off-the-wall alternatives.  We simply need to better distinguish between the 2 different modes without using the word "wallet" in different ways...and without naming the single account mode as if the other mode doesn't also have accounts, which is another source of confusion.

Perhaps it should simply be:
**Single-Account** Mode (Single account, login in from any computer, moderate security)
**Multi-Account** Mode (Multiple accounts, need wallet file to login, maximum security)

**Comment by Xeldal** [comment]
Here's my thought.

**USER** – The person
   --**ACCOUNT** – refrences a single bitshares username
       -----**WALLET** – Cointains Coins
       -----**SECURITY TYPE**: (Login)
           --------**LOCAL login** – Requires local encrypted file with password
           --------**CLOUD login** – Uses password only. Access from anywhere
   
   --**ROSTER**: -- User defined list of various accounts
       ----- **SECURITY TYPE**:
	   -------- **LOCAL Login** only

An Account is singular.  Contains only 1 username

Every Account has the option to add CLOUD login privilege.  
CLOUD Login is the default for account creation with the option of a more secure LOCAL login advanced option.
 
Every Account has a wallet.  The wallet contains coins, not other accounts.

The User can add multiple Accounts together into a single Account Roster.
The Roster can be accessed with LOCAL login only.  While each individual Account in the Roster can be accessed with either LOCAL or CLOUD login depending on users setup.

Users can create any number of different Rosters each containing a different list of accounts.

Every account can add the CLOUD login attribute at anytime.

**Comment by jonnybitcoin** [comment]
- Single Wallet 
- Multi-wallet

**Comment by tbone-bts** [comment]
@jonnybitcoin The simplicity is good.  But it's still confusing because the difference between the 2 modes is that one allows multiple **accounts**, not multiple wallets.    

>Single Wallet
>Multi-wallet

@xeldal I believe a wallet does **not** contain coins.  Rather, it contains the private keys for one or more accounts belonging to the user.  Also, I'm not sure where the term "roster" comes from.  That said, I agree with the concept you are advancing that the user should be able to enable/disable "Cloud login" for each individual account within a wallet

**Comment by landry314** [comment]
Yes, a Wallet should contain coins and not accounts, that makes sense.

- Single-Device Secure Login
- Universal Easy Login

**Comment by Xeldal** [comment]
@tbone-bts  As someone else suggested, the word _wallet_ as it is now and as you describe it is potentially out of place and confusing.  I'm just continuing with that thought with a possible example solution.  Roster is just a list of people or players or accounts.  Something to call the user created list of accounts that is currently being called a wallet.  Just an idea.

**Comment by jonnybitcoin** [comment]
- Basic Account
- Multi Account Wallet

**Comment by wmbutler** [comment]
Thoughts?

- Cloud Login
- Local Login

**Comment by landry314** [comment]
- Secure Login
- Cloud Login

The main feature of the local keys model is that it is the most secure. The main feature of the cloud model is that you can get access from anywhere which I think the word "cloud" implies these days so it is clear.

People might think that the Cloud Login is NOT secure from these names but, well, it is vulnerable to brute force attacks and so people do need to be very careful and choose a serious password. I 
think instilling a little fear is a good thing so the contrast with its opposite is helpful here.

People might think that the Secure Login is NOT convenient like cloud computing is which is true; you need to be at that one device to do anything... so, again, the contrast is useful.

The names are not too long or technical and they get to the heart of the difference. I think this simplicity and clarity is what we need.

Give me a thumbs up if you agree?

**Comment by wmbutler** [comment]
Secure is not a good descriptor. The cloud model is "secure" if proper credentials are used. The main difference between the two methods is that one relies on the possession of a local file with a password to unlock it. The other relies on two pieces of information. Both are secure, but one is more portable.

**Comment by wmbutler** [comment]
The more I look at Cloud Wallet / Local Wallet, the more I like it.

**Comment by tbone-bts** [comment]
Yeah, I like **Cloud Wallet / Local Wallet** too.  I think it concisely and properly distinguishes one mode from the other.

>The more I look at Cloud Wallet / Local Wallet, the more I like it.

By the way, has there been any discussion about making it easier to manage the login modes?  Here was some recent discussion on Telegram:  

Gilgamesh wrote in Telegram chat:
> i do think permissions could use a little more work to make it obvious what you have.  i should be able to really obviously see, using the current login method at that specific time, which permissions I have and not. clicking on stuff and see if it opens isn't obvious

tbone responded to Gilgamesh:
>i totally agree.  and it should be possible to easily switch between wallet and account modes.  the fact is that some people initially choose the wrong mode for their needs and will want/need to switch.  that shouldn't be a risky and harrowing event.  not to mention, some people will, for example, primarily use wallet mode but might temporarily want to enable account mode (e.g. if they will be travelling and don't want to or can't carry their wallet file).

**Comment by wmbutler** [comment]
@tbone-bts glad you like it. I hope we can get some consensus around it.

    By the way, has there been any discussion about making it easier to manage the login modes? 

This is something I believe is very important to work through. I mentioned to @svk31 that I need an in depth discussion on the technical nuances of the two. I do plan to approach this carefully once we can agree on terminology. It will clear the air immensely once we break this down.

**Comment by landry314** [comment]
I now agree with @wmbutler, the best choices are "Local Wallet" and "Cloud Wallet". The idea that they store something is indeed clear and that can be accounts, not just coins.

Local and Cloud get the idea across with the least amount of words.

**Comment by btsfav** [comment]
fine with Local & Cloud Wallet too.

**Comment by wmbutler** [comment]
This was handled in #258
