### ISSUE TITLE
Use a referrer parser to extract referrer info

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3010]
**Is your feature request related to a problem? Please describe.**

https://bitsharestalk.org/index.php?topic=28821.msg333146#msg333146
> The referer parser enrichment uses the Snowplow referer-parser to extract attribution data from referer URLs. You can provide a list of internal subdomains which will be treated as "internal" rather than unknown.

https://github.com/snowplow-referer-parser/nodejs-referer-parser
> This is the node.js (JavaScript) implementation of referer-parser, the library for extracting search marketing data from referer (sic) URLs.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sschiessl-bcp** [comment]
What is the purpose of this? When we parse all arguments, what do we do with it?

Currently, the value of `?r=x` gets sent to the faucet.

**Comment by abitmore** [comment]
It turns out that the linked message in the forum has been updated to a spam. Since I didn't know what's it, I thought it's related to reference wallet. Now I guess it's just a random spam post.

**Comment by abitmore** [comment]
BTW there is a BSIP issue for discussing link formats: https://github.com/bitshares/bsips/issues/246
