### ISSUE TITLE
[1.5] Order book UI: Highlight user's orders in Order Book.

### ISSUE THREAD

**Issue by xanoxt** [bitshares/bitshares-ui#302]
There are two parts in this request, either colour or star highlight the orders in the order book, something like this:
![](https://camo.githubusercontent.com/bb03e17dec0682b7b17b4b0e3c02b5e59ae489eb/68747470733a2f2f7332392e706f7374696d672e6f72672f7363396533316d6f372f696d6167652e706e67)

Anorther nice feature would be if orders bigger than certain size would be bolded.

**Comment by wmbutler** [comment]
I think a user icon to the left or right of the row would be more intuitive.

**Comment by wmbutler** [comment]
![screen shot 2017-08-21 at 4 13 27 pm](https://user-images.githubusercontent.com/1254810/29538488-b3c343cc-868b-11e7-8bd3-6c7c57f203d0.png)

**Comment by svk31** [comment]
Adding an icon can be problematic at certain screen widths and with large values in the orderbook, so I'd prefer a color highlight.

Not much space for an icon here:
![image](https://user-images.githubusercontent.com/6890015/31881901-56f85d36-b7e5-11e7-8ef3-aa1471770cf8.png)

**Comment by startailcoon** [comment]
> Adding an icon can be problematic at certain screen widths and with large values in the orderbook, so I'd prefer a color highlight.

It will also make it much easier to follow the entire row from left to right when it's colored, rather than with an icon. I don't think an icon is giving the desired outcome here. 

An additional feature could be to be able to set the row color to a user preferred color.

**Comment by wmbutler** [comment]
What if we just bold it?

![screen shot 2017-10-23 at 11 04 22 pm](https://user-images.githubusercontent.com/1254810/31924401-90613668-b846-11e7-83a3-d77babf9e7bc.png)

**Comment by startailcoon** [comment]
Anything that makes the row stand out is fine imho

**Comment by landry314** [comment]
Bittrex uses a star icon next to your order.

**Comment by wmbutler** [comment]
But @svk31 just indicated that an icon would take up too much space. We are working towards a solution.

**Comment by startailcoon** [comment]
So, what should we go for? OP proposed to give big orders in the book a bolder status and users orders a colored row.

I think a colored row would look good, but would need to be theme dependent. A bold row is just slightly highlighting for users.

How does all other exchanges do it? If everyone else does this the same way and we do something different, we might end up having a few confused users.

**Comment by wmbutler** [comment]
I'd suggest bold. It's easy and we can always fine tune it.

**Comment by startailcoon** [comment]
I agree with a bold text since color can be difficult to pick as it may depend on location of user, choice of theme and readability.

One solution, that we could come back to later, would be to let the user choose their own light/dark theme color they wish to see.

**Comment by startailcoon** [comment]
I can claim this, and possibly fix it before the end of this milestone

**Comment by svk31** [comment]
This requires some changes to be made to market classes for orders that are summed at the same price point, so I prefer to handle this myself.

**Comment by startailcoon** [comment]
Of course, just offering my services.
