### ISSUE TITLE
'Sell' book not showing in light client

### ISSUE THREAD

**Issue by iefken** [bitshares/bitshares-ui#303]
Hi,

When you change the trading pair in the lightclient, the 'sell' book doesn't show untill you scroll all the way up. BTSWolf encouraged me to report it here so here it is: 
![afbeelding](https://user-images.githubusercontent.com/27020088/29538061-5adf6ae0-86c4-11e7-9f4f-e91eb124ec5b.png)

Greetings

**Comment by wmbutler** [comment]
It's a scrolling issue that was already fixed and will be released 170901
