### ISSUE TITLE
Unable to view the 5th page of account activities

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3036]
**To Reproduce**

1. Go to 'https://wallet.bitshares.org/#/account/btspp-team'
2. Click on 'Activity'
3. Scroll down
4. Click on 'page 4', normal
5. Click on 'page 5', UI jumps to page one
6. Click on 'page 5' again, blank screen

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/63176751-ca8d1c80-c046-11e9-8022-575f731f61a7.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 68.0.1

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/pull/3075#issue-321720634
