### ISSUE TITLE
[1] ApiInstance, Crypto API Error

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#304]
I'm seeing this in my Chrome Browser console log when I load: https://bitshares.org/wallet. It happens when the wallet first loads prior to login.

![screen shot 2017-08-21 at 4 32 23 pm](https://user-images.githubusercontent.com/1254810/29539294-deebcc1a-868e-11e7-9c35-139cdaa71e6a.png)

**Comment by svk31** [comment]
I think this is from an API server that is incorrectly configured, wss://bitshares.crypto.fans/ws

**Comment by wmbutler** [comment]
I think we should either remove misconfigured servers or throw a more meaningful message, like:

- wss://bitshares.crypto.fans/ws is inaccessible or misconfigured
