### ISSUE TITLE
[3] Adapt error messages to new JSON-RPC of bitshares-core 3.2.0

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#3040]
https://bitsharestalk.org/index.php?topic=29284.0

Currently error messages from core are displayed as is. With the 3.2.0 update we can give a better visualization of the error.

Task:
- check where in UI the raw core error is displayed (i think only transactionconfirm dialog), and report back here
- adjust the transaction confirm dialog such that it can handle both error reponses (old core, and new json error response starting with 3.2.0)
- for new json error response display "code - message" as the error string. if "data" is present, add a "Show more" clickable text that if clicked shows "data"
- on error, check the error response to handle the old response the old way and the new response the new way

**Comment by abitmore** [comment]
Starting from bitshares-core 3.2.0 release we updated JSON-RPC server to follow a standard about error reporting. Perhaps this is a side-effect of the change.

https://github.com/bitshares/bitshares-core/issues/1688
https://github.com/bitshares/bitshares-fc/pull/135

The specification is https://www.jsonrpc.org/specification

Please create an issue in bitshares-core repository if something went wrong.
