### ISSUE TITLE
problem with a transfer

### ISSUE THREAD

**Issue by chilix123** [bitshares/bitshares-ui#3045]
make a transfer from whaleshare and I never get to my bitchare wallet and I'd like to know pro that or if there's any mistake

![image](https://user-images.githubusercontent.com/54379049/63471939-9f3b7080-c43e-11e9-80cf-04683171fd00.png)

**Comment by froooze** [comment]
You can join https://t.me/btsWalletHelp to find out what gone wrong?

**Comment by allfory0u** [comment]
> there's any mistake

The minimum amount is 500 WLS.

**Comment by sschiessl-bcp** [comment]
Thanks guys!
