### ISSUE TITLE
SHASUM For OSX Latest UI Release?

### ISSUE THREAD

**Issue by Emily7777** [bitshares/bitshares-ui#3047]
Hi Folks,
I see that the Win SHASUMS are included on the latest release here:

https://github.com/bitshares/bitshares-ui/releases/tag/3.1.190618.1

...But unless I missed something, I can't find the SHASUMS for the OSX version?

Please advise.

Thanks

**Comment by froooze** [comment]
Linux sum is also missing, the reason I did not update my client.

**Comment by sschiessl-bcp** [comment]
I ll check and make sure new release contains it

**Comment by sschiessl-bcp** [comment]
Done

https://github.com/bitshares/bitshares-ui/releases/tag/3.3.191120
