### ISSUE TITLE
[.5][ariesjia] Content Security Policies delivered via a <meta> element

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#305]
I'm seeing this error in the console when first loading the bitshares.org/wallet. 

![screen shot 2017-08-21 at 4 39 56 pm](https://user-images.githubusercontent.com/1254810/29539421-65fcbe94-868f-11e7-920e-c619c01900bf.png)

**Comment by ariesjia** [comment]
@wmbutler  can i take the bug

**Comment by wmbutler** [comment]
Assigned to you @ariesjia Thanks.

**Comment by ariesjia** [comment]
Yes , I will quick fix  the bug
