### ISSUE TITLE
[0,5] Asset info white screen

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3053]
**Describe the bug**

**To Reproduce**
1. Go to https://wallet.bitshares.org/#/asset/GCNY or https://develop.bitshares.org/#/asset/GCNY
2. See white screen

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/63984996-e0cabc00-cacd-11e9-89a8-55af86ed13dd.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 65.0.1

**Additional context**
GCNY is a MPA backed by GDEX.BTC

**Comment by startailcoon** [comment]
Seems like a missing check. Should be a quick fix

**Comment by startailcoon** [comment]
Can't reproduce any more.

**Comment by abitmore** [comment]
Still white screen for me.
![image](https://user-images.githubusercontent.com/9946777/66789336-6c1bd780-eeeb-11e9-8065-be2a2bb88f50.png)

**Comment by allfory0u** [comment]
I confirm this
![изображение](https://user-images.githubusercontent.com/17462020/66805288-44e5fa00-ef2d-11e9-92d9-155e7e977d1f.png)

**Comment by sschiessl-bcp** [comment]
Does this reproduce if you load another page first?

Open https://develop.bitshares.org/#/market/GCNY_BTS then navigate manually to asset info of GCNY.
I still can't reproduce it :(

**Comment by abitmore** [comment]
@sschiessl-bcp open a chrome incognito window, type https://wallet.bitshares.org/#/asset/GCNY directly.

**Comment by abitmore** [comment]
It works now. Thanks.

**Comment by sschiessl-bcp** [comment]
:P Closing it now
