### ISSUE TITLE
please something is wrong with servers they are down

### ISSUE THREAD

**Issue by elitzen12** [bitshares/bitshares-ui#3058]
trying to login into my account and is not letting me login it said error of server i saw nodes and there are all red not enable please help and fix soon thankyou sorry forgot is in cryptobridge the problem in GHR/BTC thanks.

**Comment by shulthz** [comment]
all is ok now

**Comment by elitzen12** [comment]
No same problem cant deposit or WD

**Comment by elitzen12** [comment]
I will try tomorrow

**Comment by shulthz** [comment]
all the node need to update, just wait they finished.
