### ISSUE TITLE
How to build bitshares-light wallet on windows?

### ISSUE THREAD

**Issue by lilianwen** [bitshares/bitshares-ui#306]
i find it is impossible to build on windows and the readme file did not say how to do it.

**Comment by svk31** [comment]
Exact same way you build it for Linux and osx. Install node then run the commands in a node console.

**Comment by wmbutler** [comment]
We plan to release new binaries for all 3 platforms at the end of every milestone. Expect new binaries on 170901.

**Comment by hiquanta** [comment]
This is still no longer windows compile ah

**Comment by svk31** [comment]
```
npm install
npm run package
```

**Comment by wwg2018new** [comment]
@lilianwen  
Is it successful in Windows compilation？
