### ISSUE TITLE
Requirements to be a DEX Gateway like openledger or cryptobridge?

### ISSUE THREAD

**Issue by revivalist777** [bitshares/bitshares-ui#3065]
Hello, first of all i'm sorry if i come to a wrong place. New registration on bitsharestalk.org is disabled and i was kicked from bitshares telegram group because asking about the topic.

So far, i have successfully personalized bitshares-ui with my brand and preferences, also i have prepared my API using "Gateway Integration Requirements" guide to serve requests from the front end. All are ready and setup until i try to create asset (UIA), it gives error **"Execution Error"**

I tried multiple times within the last 12 hours with any kind of settings from my own UI, Bitshares MAC wallet and on https://wallet.bitshares.org/ all result in the same error

From the console log i found this message:
`"asset_symbol_itr != asset_indx.end(): Asset ${s} may only be created by issuer of ${p}, but ${p} has not been registered"`

I searched on google, reading so many articles and documentations but could not find anything to solve my problem.

**What i want to achieve is** _to create an asset with this format: PREFIX:ABR, like OPEN.BTC, in short i want to create an exchange or become a gateway_

Oh another thing, my account still a basic member but if required, i will upgrade to paid membership.

I've learnt all the technical things but i assume i have to talk to someone about it.

Can anyone help me out about this? Or should i contact someone in private if it's business related issue?

I hope at least i can find some clues here, i don't know where else to go and ask this.

Thanks in advance.

**Comment by shulthz** [comment]
http://dev.bitshares.works/en/master/bts_guide/tutorials/index.html

**Comment by revivalist777** [comment]
thanks @shulthz it fixed now.
