### ISSUE TITLE
Scam Proposals - Consequences 

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#3069]
**Is your feature request related to a problem? Please describe.**
This is response regarding issue #3068. #3068 does not address or fix the issue. It does however, add to the options and features of the DEX, albeit there are already safeguards in place. Some issues that come to mind are:

1.  It does nothing for a user with an older client and/or has not updated.
2.  Do "new members" know what a proposal is let alone enable/disable it?
3.  "New members" could also be looped in with "inactive members" in that, an inactive member 
    was once a "new member" and not necessarily "active" therefore, no more unassuming any 
    more crypto educated.
4. Most importantly, it does not stop, hinder, nor delve consequences to the nefarious actor.
    And, what if that actor is also holding a compensated position within BitShares?
5. Logic dictates that the spam proposals will continue.
6. The DEX is a highly sophisticated financial platform with unimaginable potential and abilities.
    These features should be embraced and honed to perfection without compromise.
 
**Describe the solution you'd like**

- Spam proposals met with severe and quick consequences.
I opened this issue for discussion and hopeful resolution. While I don't condone "confiscation", how can we finally put an end to these? Liquidate the scammers assets and recycle it to the pool?
Again, while I don't condone this, it does provide a justifiable means of massive BTS movement on the DEX; A solution that is also reversible; A solution that could return the assets back to the holder, however, is that the solution? the user accepted the proposal, thus forfeiture should be too. Perhaps a more ideal solution is to allow a one time return of assets and only under scam proposal conditions; A solution that shows by example the consequences of scamming on the DEX. Real world consequences are exemplified here, in one of EtherDelta sealed indictments https://www.docdroid.net/TVOeRNc/etherdelta-hacker-indictment.pdf 
 Many of the solutions offered can be combined to help, but in the end, the scammer gets away with others windfalls. Please review the following images. I counted over 100 _known_ spam proposal accounts, but there are many more. Both now and in the past, the pattern has been to quickly send the stolen funds to a gateway. Gateways should always be quick and without delay. The gateway should have the ability to monitor and stop this from happening. How? maybe a withdrawal timed lock? Gateway Guarantee? Based on what metrics? the asset? The quantity?  Time lock Withdrawal on first XXXX number of withdrawals?Account registration date? And, how to keep it gateway universally compliant to ensure the proposer doesn't just use another gateway?
We are still seeing that happen, but right now at this point in BitShares short life, it is under attack once again from every side and BTS is being held on the DEX longer than usual for voting, which is an issue all in itself. Scam proposals combined with voting lead to a disaster.

![cn-member1](https://user-images.githubusercontent.com/18186497/65380213-0fd2e880-dc9c-11e9-8600-093e93eb7a52.JPG)
![cn-member2](https://user-images.githubusercontent.com/18186497/65380214-0fd2e880-dc9c-11e9-89a8-7d3ae5d89e70.JPG)
![cn-member3](https://user-images.githubusercontent.com/18186497/65380215-0fd2e880-dc9c-11e9-9a29-56f89305cd8e.JPG)
![cn-member4](https://user-images.githubusercontent.com/18186497/65380216-0fd2e880-dc9c-11e9-81ed-3fea39c174c9.JPG)
![cn-member5](https://user-images.githubusercontent.com/18186497/65380217-0fd2e880-dc9c-11e9-8c07-cb274208ac24.JPG)
![cn-member6](https://user-images.githubusercontent.com/18186497/65380218-0fd2e880-dc9c-11e9-8382-10c1c4034ded.JPG)
![cn-member7](https://user-images.githubusercontent.com/18186497/65380219-0fd2e880-dc9c-11e9-954b-9d97a145c64e.JPG)
![cn-member8](https://user-images.githubusercontent.com/18186497/65380220-106b7f00-dc9c-11e9-9867-771052e7f226.JPG)
![cn-member9](https://user-images.githubusercontent.com/18186497/65380221-106b7f00-dc9c-11e9-93e7-ade6467f0e73.JPG)

**Describe alternatives you've considered**
#2417 #2423

**Comment by sschiessl-bcp** [comment]
> 1. It does nothing for a user with an older client and/or has not updated.

And no solution will, only a core change would. For a core change the behavior could easily change such that core would not recognize anymore. Futile exercise in my opinion

> 2. Do "new members" know what a proposal is let alone enable/disable it?

No they don't, they should have a tooltip with explanation.

> 3. "New members" could also be looped in with "inactive members" in that, an inactive member
>    was once a "new member" and not necessarily "active" therefore, no more unassuming any
>    more crypto educated.

Your point?

> 4. Most importantly, it does not stop, hinder, nor delve consequences to the nefarious actor.
>    And, what if that actor is also holding a compensated position within BitShares?

Only a core change could. In a permissionless system this is borderline impossible.

> 5. Logic dictates that the spam proposals will continue.

Agreed.

> 6. The DEX is a highly sophisticated financial platform with unimaginable potential and abilities.
>    These features should be embraced and honed to perfection without compromise.

And explaned!

To the suggestion:
Gateway behavior and core changes are out of scope for the UI. A general solution is simply not possible IMO.
