### ISSUE TITLE
no current-release.json

### ISSUE THREAD

**Issue by lilianwen** [bitshares/bitshares-ui#307]
I want to build a bitshares-light wallet. I follow the steps.
```
cd electron
npm install
cd ../web
npm run electron
cd ../electron
npm run release
```

When it coms to the last step, error occurs.Like this:

 node ./tasks/write_digest

C:\Users\llw\Desktop\sfile\wsBitshareUI\bitshares-ui\electron\tasks\write_digest.js:14
var file = path.resolve('releases/', currentRelease[utils.os()]);
                                                          ^

TypeError: Cannot read property 'windows' of undefined
    at Object.<anonymous> (C:\Users\llw\Desktop\sfile\wsBitshareUI\bitshares-ui\electron\tasks\write_digest.js:14:59)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ postrelease: `node ./tasks/write_digest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ postrelease script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Program Files\nodejs\node_cache\_logs\2017-08-22T11_45_58_945Z-debug.log

when i open the file bitshares-ui\electron\tasks\write_digest.js,I find this 

```
var releasesDir = jetpack.dir('./releases');

var currentRelease = releasesDir.read("current-release.json", "json");
```

and in fact there is no file named current-release.json in 'releases' directory(it is empty), and not in the whole project.

**Comment by wmbutler** [comment]
@svk31 can you please address this one? It's a bit over my head.

**Comment by svk31** [comment]
current-release.json is generated by the build process. Make sure you have all the dependencies installed and that you're running node v7.
