### ISSUE TITLE
[0] Wrong value in Portfolio

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3071]
**Describe the bug**
Data in the `value` column is wrong.

**To Reproduce**
1. Go to 'https://develop.bitshares.org/#/account/gamma-rabbit'

**Expected behavior**
1. The data should be sum of numbers, but not strings joined.
2. When sorting, if the triangle icon `^` is in blue, the smallest number should be on the top.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/65517034-5e71c400-dee2-11e9-94ef-54280dfc5cc9.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 65

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/pull/3079

**Comment by abitmore** [comment]
Now the string joining issue is fixed. But the data is still wrong, because there can be multiple debt positions in an account, but current code only takes one. BTW data in "in orders" seems correct. See https://develop.bitshares.org/#/account/abc.btsbots

**Comment by sschiessl-bcp** [comment]
@abitmore done

**Comment by abitmore** [comment]
@sschiessl-bcp thanks. Verified.
