### ISSUE TITLE
When choosing SmartCoin on dropdown menu it remains BTS regardless of choice (creation of Collateralized Debt Position)

### ISSUE THREAD

**Issue by liondani** [bitshares/bitshares-ui#3085]
When choosing a SmartCoin from the dropdown menu when trying to create a Collaterized Debt Position via the "Spotlight" option, BTS remains as choice visually. In reality the system takes the choice right and after clicking "BORROW" you can continue BUT visual it is not correct.

1. Go to the sandwich button upper right
2. Click on "Spotlight"
3. Click "Collatralized Debt Position"
4. Click "Get Started"
5. Click "NEXT" 3 times
6. Click "LET'S DO IT"
7. Click on dropdown menu and try to choose a SmartCoin.

Normally BTS should be replaced with the SmartCoin name you have chosen.

![Screenshot from 2019-10-02 23-26-13](https://user-images.githubusercontent.com/6908400/66080093-0b48e280-e56e-11e9-8d69-e8760de6137f.png)

 - OS: Linux Mint 19.2 Cinnamon
 - Bitshares Client version: 3.1.190618.1

**Comment by sschiessl-bcp** [comment]
Does this reproduce on develop.bitshares.org?

**Comment by allfory0u** [comment]
> 
> 
> Does this reproduce on develop.bitshares.org?

No. It has already been fixed in #2961
