### ISSUE TITLE
"issuer" or "owner" description of Asset

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#3095]
**Asset actions**    
 **Asset info**
> Unclaimed issuer income
The asset issuer may claim any accumulated fees here.
The asset owner may change the owner to another account using this form:
The asset owner may withdraw funds from the fee pool using this form:

"Unclaimed **issuer** income" or "Unclaimed **owner** income"?
"The asset **issuer** may claim any accumulated fees here" or "The asset **owner** may claim any accumulated fees here"?

**Comment by sschiessl-bcp** [comment]
The wording refers to owner.
