### ISSUE TITLE
show more details on Account page

### ISSUE THREAD

**Issue by btswolf** [bitshares/bitshares-ui#310]
The current account page could be used to show more important high-level information that users are looking often for. I suggest to enhance the information that is displayed on the account page and put some links to the sub-pages with more in-depth information from there. 

[![Wallet_account](https://i.imgsafe.org/c7/c738522264.png)](https://i.imgsafe.org/c7/c738522264.png)
**Show active account page**
* Icon
* Account ID
* Accountname (`option to unfollow if followed`)
* Estimated account value: 999 BitUSD
* Membership: Standard or Lifetime(`link to Membership page`)
* (`if LTM`)Your referral link: `https://wallet.bitshares.eu/?r=accountname` (`copy function`)
* Cashback/Vesting: 13,403 of 19,010 BTS (`claim function or link to membership page`)
* Votes with: 102,020 BTS as xeroc (`not voting(link to voting)/voting stake and if set the "proxy" account`)

**Balance table**
* Token type (`UIA/SmartCoin ...`)
* SYMBOL (`link to token page`)
* Est. Value (`show value and link to releated exchange trading pair with most volume in 24h`)
* Debt (`show value, token and link to "Close position"`)
* Collateral (`show collateral and link to "Update position"`)
* Collateral Ratio (`CR`)
* Call price
* Debt position (`count from least collateralized position, 1-5 Warning, >5 OK, tooltip=add more collateral or you risk a margin call`)
* Token (`hide/un-hide/un-hide all`)

**History table**
* Operation
* Info
* Timestamp
* Block nr.

**Comment by btsfav** [comment]
I'd like to see 

* count of referrals
* income generated
  * ltm purchases
