### ISSUE TITLE
Spotlight - Prediction Market - % of Open Orders and Prediction Likelihood

### ISSUE THREAD

**Issue by TechsUsInc** [bitshares/bitshares-ui#3105]
**Describe the bug**
Errors in the Market Prediction Likelihood column
**To Reproduce**
1. Go Hamburger Menu
2. Click Spotlight
3. Scroll down to Prediction Market; click to enter
4. de-select Unknown Houses 
5. See errors in the Market Prediction Likelihood column
![node28Capture](https://user-images.githubusercontent.com/18186497/67763905-bc7c5480-fa16-11e9-9127-31a5d795f246.JPG)
 
**Expected behavior**
1. Consistency of Open Orders percentage
2. Prediction Market Open Orders percentage information tooltip

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser Opera
 - Version 64.0.3417.73

**Comment by sschiessl-bcp** [comment]
It's not an error. Predicted likelihood is reflected by open orders. No order present, no prediction.
