### ISSUE TITLE
Merchant Protocol： print receipt PDF problem

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#3114]
When print the PDF, the Chinese characters were all garbled in the PDF.

![2019-10-30_152116](https://user-images.githubusercontent.com/34892308/67837031-11a88b00-fb29-11e9-9408-a9852a29e299.png)
![2019-10-30_152323](https://user-images.githubusercontent.com/34892308/67837107-40266600-fb29-11e9-9fd7-e03e0e454516.png)

**Comment by sschiessl-bcp** [comment]
This is surprisingly not straightforward. https://github.com/MrRio/jsPDF#use-of-utf-8--ttf

Will default to english
