### ISSUE TITLE
For branding purposes, hard coded "BitShares" should be replaced with getWalletName() from branding.js

### ISSUE THREAD

**Issue by ioBanker** [bitshares/bitshares-ui#3132]
In order to satisfy the ultimate goal of branding.js approach and to enhance the simplicity of customizing bitshares-ui to business or users, branding.js was created to ease the customization and branding, the hardcoded "BitShares" text in /app/lib/common/titleUtils.js should be replaced with getWalletName() coming from app/branding.js.

https://github.com/bitshares/bitshares-ui/blob/ae5c66bbb04f0cb6239432e93bde20620fa652d8/app/lib/common/titleUtils.js#L9

**Comment by sschiessl-bcp** [comment]
Please go ahead and provide a PR for this :)

**Comment by ioBanker** [comment]
Done.

**Comment by abitmore** [comment]
FWIW the PR is https://github.com/bitshares/bitshares-ui/pull/3133.

**Comment by ioBanker** [comment]
FWIW the PR has been changed to #3135 and #3133 was closed.

**Comment by sschiessl-bcp** [comment]
Done

> FWIW the PR has been changed to #3135 and #3133 was closed.
