### ISSUE TITLE
Failed to withdraw 1000000 PGN, please handle it, thank you! 1000000PGN取款失败，请帮处理，谢谢！

### ISSUE THREAD

**Issue by wec168** [bitshares/bitshares-ui#3134]
There are 2 consecutive withdrawals of 1 million, only one has been received.

Withdrawal Id1: 1.11.10161280211000000pgn = fcb3424a7740bde730ec4a7d6f36553c681cf502c54de9007b06df619dd1e78b, 2019-11-20 12:31:12, which was successfully received.

Withdrawal Id2: 1.11.10161282311000000pgn = (?) , 2019-11-20 12:31:39, this withdrawal failed, please help check, thank you!

连续取款2个100万，只收到一个。
取款ID1:1.11.1016128021，1000000PGN=fcb3424a7740bde730ec4a7d6f36553c681cf502c54de9007b06df619dd1e78b，2019-11-20 12:31:12，这笔成功到账。
取款ID2:1.11.1016128231，1000000PGN=（？），2019-11-20 12:31:39，这笔取款失败了，请帮助检查，谢谢！

![image](https://user-images.githubusercontent.com/58012431/69286690-d8969e80-0c2e-11ea-8750-7cf59163cd76.png)

**Comment by shulthz** [comment]
请联系cryptobridge

**Comment by wec168** [comment]
我按照cryptobridge要求在网页中提交了发生的问题，以为这样他们会很快看到，以便及时处理，原来这样还不行。发邮件给他们处理问题太慢了，少则三四天，多者十几天才有回复，只有继续发邮件给他们。
谢谢你！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shulthz"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 上午8:01
收件人:&nbsp;"bitshares/bitshares-ui"<bitshares-ui@noreply.github.com&gt;;
抄送:&nbsp;"danpai"<danpai@foxmail.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [bitshares/bitshares-ui] Failed to withdraw 1000000 PGN, please handle it, thank you! 1000000PGN取款失败，请帮处理，谢谢！ (#3134)




请联系cryptobridge

**Comment by wec168** [comment]
有联系cryptobridge最快捷的方法吗？

**Comment by wec168** [comment]
I submitted the problems in the web page according to the requirements of cryptobridge, thinking that they would soon see that the brakes were in time to deal with them, which was not good. It's too slow to send emails to them to deal with problems, three or four days less, more than ten days to reply, only to continue to send emails to them. Thank you!

Is there the quickest way to connect with cryptobridge?

**Comment by shulthz** [comment]
> 
> 
> 有联系cryptobridge最快捷的方法吗？

找找看看有没有电报群吧
https://crypto-bridge.org/contact-us/

**Comment by wec168** [comment]
这些都打不开
https://discordapp.com/invite/H6Qt2dQ
https://twitter.com/CryptoBridge
https://www.reddit.com/r/CryptoBridge/

**Comment by shulthz** [comment]
搜搜电报群有没有频道吧，我是没用过...

**Comment by wec168** [comment]
是不是要翻墙啊

**Comment by shulthz** [comment]
> 
> 
> 是不是要翻墙啊

必须的啊，上面那几个频道也是要梯子啊

**Comment by wec168** [comment]
下载个蓝灯试试看。谢谢你！
CB很麻烦的，沟通太不方便了。
