### ISSUE TITLE
The function “barter” can't work in the 3.3.191120-rc1 Release

### ISSUE THREAD

**Issue by shulthz** [bitshares/bitshares-ui#3138]
Can't work in: https://staging.bitshares.org
The "PROPOSE" didn't have any response.
The function “HTLC” have this problem too.

![2019-11-25 16_21_49-Window](https://user-images.githubusercontent.com/34892308/69523847-d1a9bc00-0f9f-11ea-8269-e41c0e3309e8.png)

Worked fine in: https://wallet.bitshares.org

**Comment by sschiessl-bcp** [comment]
Yea, seems broken. It is likely due to the new FeeSelect component, should be somethign small as the component generally works on the other components.

**Comment by sschiessl-bcp** [comment]
Please retry on develop.bitshares.org

**Comment by shulthz** [comment]
> 
> 
> Please retry on develop.bitshares.org

Can't work.

**Comment by sschiessl-bcp** [comment]
Please make sure you use version 922eb03

You might have been to quick there and used the old version.
![image](https://user-images.githubusercontent.com/33128181/69726428-d9dd3500-1120-11ea-8ff5-46215160bc8d.png)

**Comment by shulthz** [comment]
Work fine now, thks.
