### ISSUE TITLE
Hijacked :(   Please help ASAP!!!

### ISSUE THREAD

**Issue by johnnythinker** [bitshares/bitshares-ui#3141]
**Describe the bug**
My account,   bitcoin-wizards   was hijacked. I am unable to make any transaction now. 
It says, Failed to broadcast the transaction:
Execution error
Whenever I try to make a transaction now. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by johnnythinker** [comment]
ACCOUNT / KEY / ADDRESS | WEIGHT | ACTION
-- | -- | --
  | openledger-witness | 2 | Remove
  | BTS7GQdy5f*********************5Gvp5daZMBkzk1W | 1 | Remove

**Comment by abitmore** [comment]
`Please be aware of scam attempts using Proposed Transactions in your Dashboard. Never approve a proposal if you are not expecting one!`

Sorry, we're unable to help.
