### ISSUE TITLE
HKD settle orders not showing

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3145]
**Describe the bug**
The "settle orders" tab shows nothing in https://develop.bitshares.org/#/market/BTS_HKD .
There is a settle order according to cli_wallet
```
locked >>> get_settle_orders HKD 10
[{
    "id": "1.4.6871",
    "owner": "1.2.17391",
    "balance": {
      "amount": 3158538,
      "asset_id": "1.3.109"
    },
    "settlement_date": "2019-12-03T03:27:06"
  }
]
```

In CNY market, the page does show the settle orders.

**To Reproduce**
1. Go to 'https://develop.bitshares.org/#/market/BTS_HKD'
2. Scroll down
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 70.0.1

**Additional context**

**Comment by startailcoon** [comment]
Can this one be related to #3176 ?
What I can see you're posting this after the settle date, and the volume is much more than the max settlement per period.

**Comment by abitmore** [comment]
I think it's the same issue. Thanks.
