### ISSUE TITLE
Withdraw fund stuck

### ISSUE THREAD

**Issue by bobcricket** [bitshares/bitshares-ui#3146]
**Describe the bug**

**To Reproduce**

I made a withdraw of open.BTC from Bitshares to my wallet on the 02/12/2019 at 17:16:42 but never received the fung in my wallet... I checked and had enough BTS to pay the fees. 
I join a screenshot of the transaction.
What can i do now ?

**Screenshots**
![Bishare withdraw stuck](https://user-images.githubusercontent.com/58574223/70280109-07c51800-17b8-11ea-9c73-b95814caca65.png)

**Comment by sschiessl-bcp** [comment]
Please contact OpenLedger through their freshdesk

https://openledger.freshdesk.com/support/home
