### ISSUE TITLE
Quick trade is limited to current assets

### ISSUE THREAD

**Issue by froooze** [bitshares/bitshares-ui#3172]
**Describe the bug**
Quicktrade only knows assets, which are already in the portfolio available.

**To Reproduce**
1. Go to Quicktrade
2. Enter new asset
3. Asset is not found

**Expected behavior**
Find new assets

**Desktop (please complete the following information):**
 - OS: MX-Linux
 - Browser: Firefox 
 - Version: 191120

**Comment by sschiessl-bcp** [comment]
You can trade any assets by putting the respective symbols in address

**Comment by froooze** [comment]
No:
![LTC](https://user-images.githubusercontent.com/40874087/71609667-95fba680-2b8a-11ea-92b4-fba04c0cfc08.png)
