### ISSUE TITLE
I can't see my transactions in bitshares exchange.  I transferred some BTC to coinbase on Friday and it still has not arrived.  

### ISSUE THREAD

**Issue by michaelbolick** [bitshares/bitshares-ui#3173]
This is my the error report from my activity log: 

Latency result:[object Object]
log: Your node is out of sync since 5.747000217437744 seconds, waiting 10 seconds, then we notify you
log: synced and subscribed, chainstore ready
log: INFO	browserEntropy gathered
log: fetchCoins error from https://api.crypto-bridge.org/api/v1/coins: TypeError: Failed to fetch
log: fetchTradingPairs error from https://api.crypto-bridge.org/api/v1/trading-pairs: TypeError: Failed to fetch
log: error fetching blocktrades active walletsTypeError: Failed to fetchhttps://api.crypto-bridge.org/api/v1/wallets
log: INFO	browserEntropy gathered
log: auto locking after600s
log: synced and subscribed, chainstore ready
log: INFO	browserEntropy gathered
log: fetchCoins error from https://api.crypto-bridge.org/api/v1/coins: TypeError: Failed to fetch
log: fetchTradingPairs error from https://api.crypto-bridge.org/api/v1/trading-pairs: TypeError: Failed to fetch
log: error fetching blocktrades active walletsTypeError: Failed to fetchhttps://api.crypto-bridge.org/api/v1/wallets
log: auto locking after600s
log: synced and subscribed, chainstore ready
log: INFO	browserEntropy gathered
log: fetchCoins error from https://api.crypto-bridge.org/api/v1/coins: TypeError: Failed to fetch
log: fetchTradingPairs error from https://api.crypto-bridge.org/api/v1/trading-pairs: TypeError: Failed to fetch
log: error fetching blocktrades active walletsTypeError: Failed to fetchhttps://api.crypto-bridge.org/api/v1/wallets

**Comment by blincadmin** [comment]
Cryptobridge had already bid farewell as gateway. There are no support lines available.

**Comment by sschiessl-bcp** [comment]
The liquidation of Liquidblocks ApS (company behind CryptoBridge) is handled by attorney-at-law Kasper F. Langgaard. Direct any outstanding claims to liquidblocks@njordlaw.com
