### ISSUE TITLE
fail to create account

### ISSUE THREAD

**Issue by cxxcunow** [bitshares/bitshares-ui#319]
I compile witness nodes with private network test, 
my rpc-endpoint is 10.0.0.228:11011, and I set the api-access with 10.0.0.228:11011, faucet address as https://10.0.0.228, 

it shows connected status. but when I create account it shows me with unknow error. do you know why?
[10.0.0.228-1503572342190.TXT](https://github.com/bitshares/bitshares-ui/files/1248580/10.0.0.228-1503572342190.TXT)

**Comment by abitmore** [comment]
More info please.

**Comment by cxxcunow** [comment]
I update with web log above

**Comment by svk31** [comment]
Duplicate of #324
