### ISSUE TITLE
Cursor moves improperly when inserting characters in edit box

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#32]
_From @dnotestein on January 10, 2016 19:4_

When you type a character into the middle of a text string in an edit box (e.g. in the amount field of the transfer form), it moves the cursor to the end of the edit box. This is extremely annoying.

_Copied from original issue: cryptonomex/graphene-ui#662_

**Comment by svk31** [comment]
_From @steempower on January 13, 2017 4:48_

This should be a high priority, it is very frustrating and hopefully should only take a very short amount of time to resolve
+5% 

When selecting price box, default value should disappear or if not disappear when i place my cursor to the right hand side of the default value (0) and try to enter a '.' (so the price would be a fraction of the base currency e.g 0.02 BTS/BTC/....). it should allow me to do so. Currently i click to the right hand side of the 0 and press '.' the cursor jumps to the left of the 0.

**Comment by wmbutler** [comment]
Addressed and fixed in #137
