### ISSUE TITLE
This can make the dex platform/exchange more easy to use. Userfriendly. Suggestions.

### ISSUE THREAD

**Issue by technologicss** [bitshares/bitshares-ui#320]
Just trying to help. No offense. 
![image](https://user-images.githubusercontent.com/31315400/29671063-d8214b60-88e8-11e7-9f00-a1ce504ad0cc.png)
too many possible pushbuttons on one buy/sell screen. 5 is too much.
![image](https://user-images.githubusercontent.com/31315400/29671137-029f8a82-88e9-11e7-9ef4-665b382ff871.png)
8 fields looks like you can fill them in, too much.  btfx only 2
![image](https://user-images.githubusercontent.com/31315400/29671209-340f32a2-88e9-11e7-8cc9-9811e4f9bdd5.png)
remove the /xxx after every price field. I hace never seen something like that. You are in the Ether buy or sell field. Dont mention it again. Confusion. 

Kind regards,
Maybe this can help DEx to atrrack more volume.
Im a dex believer.
The community are wonderfull people!

**Comment by technologicss** [comment]
Adition:
The only info needed for trading is something like this. All the information is available.
![image](https://user-images.githubusercontent.com/31315400/29676085-52625f50-88f7-11e7-8057-39be1182199c.png)
2 fields and 2 pushbuttons. Works perfect.
Only once is the crypto mentioned, and only once the other currency.
If you count them on the dex screen, i count 19!!! against 2.

**Comment by fletchertyler914** [comment]
@technologicss How do you borrow with this setup above? You have completely removed a feature that a lot of people use in exchange for over-simplicity. I think this should depend on if the user is in"Advanced Mode" or not, very similar to openledger.io, but still being able to see the charts. 

For instance: Person 'A' that is in "Basic Mode" will see the simple buy/sell screen like above, but person B in "Advanced Mode" will see the normal buy/sell/borrow with all of the input fields. 

I agree that we could take out the redundant currency name, as that should be implied when you click on the market.

**Comment by wmbutler** [comment]
I've been absorbing this, primarily the idea of keeping a single set of fields with a dropdown to signify buy vs sell. No rush on this, but I would like to see a lot of discussion before any decisions are made.
