### ISSUE TITLE
Can't create a PARENT asset

### ISSUE THREAD

**Issue by yukadev** [bitshares/bitshares-ui#3209]
### Unable to create a PARENT asset. 
The user already has a lifetime subscription ([wa11dex - ID: 1.2.1691129](https://bts.ai/details/account/wa11dex)). 

Tried all the nodes.

What could be the reason?

![bts1](https://user-images.githubusercontent.com/60086143/75144797-cd10b300-5708-11ea-83b4-a51126413683.png)

Windows, Firefox

**Comment by blincadmin** [comment]
WA11DEX must be an asset.

**Comment by yukadev** [comment]
Thank you!
