### ISSUE TITLE
Impossible to put order on 2 currency pairs

### ISSUE THREAD

**Issue by jmartin291** [bitshares/bitshares-ui#3239]
Hello,

i can not put on order on 2 currency pair :
open.RISE /BTS
open.ETP / BTS

Is it normal ?

Regards

Julien

**Comment by sschiessl-bcp** [comment]
You will need to check with OpenLedger's freshdesk on that question as they operate the OPEN assets.

**Comment by blincadmin** [comment]
Openledger has disabled trading for these assets against BTS

**Comment by jmartin291** [comment]
Thank you for your answer.
How can I sell those crypto then ?

Le sam. 11 avr. 2020 à 19:09, BLINC Einstein <notifications@github.com> a
écrit :

**Comment by abitmore** [comment]
https://openledger.info/contacts
