### ISSUE TITLE
about light wallet

### ISSUE THREAD

**Issue by cxxcunow** [bitshares/bitshares-ui#324]
my win10  run a virtual box with ubuntu with one private testnet witness node, it listen on 10.0.0.239:11011
I install one light wallet in win10, and try to create account but fail with
AddressIndex save 10
PrivateKeyStore.js:206 p: Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
PrivateKeyStore.js:206 p: Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
create-account:1 Fetch API cannot load http://10.0.0.239:11011/api/v1/accounts. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.0.0.239:8080' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
WalletActions.js:142 Warning! faucet registration failed, falling back to direct application_api.create_account..
CreateAccount.jsx:159 ERROR AccountActions.createAccount Error: value required for registrar_id: null
    at Object.required (ChainValidation.js:111)
    at ApplicationApi.create_account (ApplicationApi.js:25)
    at create_account (WalletActions.js:93)
    at eval (WalletActions.js:143)
    at <anonymous>
AddressIndex.js:193 AddressIndex save 20
WalletUnlockStore.js:100 auto locking after 600 s

it is the first account for the wallet.

**Comment by svk31** [comment]
The browser won't let you use a local faucet, no way around it.
