### ISSUE TITLE
blanck web page

### ISSUE THREAD

**Issue by ChrestenK** [bitshares/bitshares-ui#3256]
**Describe the bug**

**To Reproduce**
1. Go to 'https://bitshareswallet.beos.world/account/chresten1'

**Expected behavior**
blanck web page

**Screenshots**
![billede](https://user-images.githubusercontent.com/31180998/82791181-98c6a300-9e6d-11ea-89e9-061b24095817.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 76.0.1

**Comment by sschiessl-bcp** [comment]
https://bitshareswallet.beos.world is a private fork the this UI. Please retry using either wallet.bitshares.org or for latest changes staging.bitshares.org

**Comment by ChrestenK** [comment]
OK  
Thanks
