### ISSUE TITLE
Unknown error is not allowing me create account.

### ISSUE THREAD

**Issue by bynarikode** [bitshares/bitshares-ui#3257]
![image](https://user-images.githubusercontent.com/57950074/83008945-e67a1180-a00d-11ea-9b97-eeeb5bb5ba94.png)

Hello,
I keep getting unknown error when I try to create account. I've tried on different networks and devices and it says the same thing.
Thanks.

**Comment by xeroc** [comment]
What's the actual error message you see?

**Comment by bynarikode** [comment]
Hi,
It just shows

Failed to create account: okhie1 - unknown error

That's it.

**Comment by xeroc** [comment]
try https://wallet.bitshares.eu - slightly older version but should work

**Comment by bynarikode** [comment]
Thanks its working now account created.
