### ISSUE TITLE
Getting error while Cancelling the request

### ISSUE THREAD

**Issue by Sey30** [bitshares/bitshares-ui#3263]
**Describe the bug**
I have placed a order for bts to bitUSD, i tried to cancel the order but i couldn't cancel. 

**To Reproduce**
1. Go to 'My Open Orders'
2. Click on 'Cancel.'
3. See error

**Expected behavior**
I would like to cancel the order

**Screenshots**
![image](https://user-images.githubusercontent.com/66202420/85252418-0c74c380-b49f-11ea-8b66-253467d52d3f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome]

**Additional context**
10 - Execution error
Hide
{
    "code": 10,
    "name": "assert_exception",
    "message": "Assert Exception",
    "stack": [
        {
            "context": {
                "level": "error",
                "file": "evaluator.cpp",
                "line": 76,
                "method": "prepare_fee",
                "hostname": "",
                "thread_name": "th_a",
                "timestamp": "2020-06-22T05:41:35"
            },
            "format": "core_fee_paid <= fee_asset_dyn_data->fee_pool: Fee pool balance of '${b}' is less than the ${r} required to convert ${c}",
            "data": {
                "r": "0.02656 BTS",
                "b": "0.01302 BTS",
                "c": "0.00001 APPLECOM"
            }
        },
        {
            "context": {

**Comment by sschiessl-bcp** [comment]
You are trying to pay the transaction fee with the asset APPLECOM. This asset cant be used for that since the asset fee pool is empty. You simply require some BTS to pay the cancellation fee.

**Comment by abitmore** [comment]
@sschiessl-bcp it's the UI's fault (bad UX) that OP is paying `APPLECOM` as fee. An issue that has existed for 3 years. See #183 #201 #1009 #1117 #1498.

**Comment by Sey30** [comment]
But, how do I change that to cancel that order?

**Comment by abitmore** [comment]
Further discussion and work in progress in https://github.com/bitshares/bitshares-ui/issues/3486.

**Comment by abitmore** [comment]
By the way, the fee asset can be configured in settings.

![image](https://user-images.githubusercontent.com/9946777/164985736-bac0e97a-ded5-4a29-abc0-1ecb1075e121.png)
