### ISSUE TITLE
DEX Dashboard page blank

### ISSUE THREAD

**Issue by dxmynw-cld** [bitshares/bitshares-ui#3265]
For the past several days, if not weeks, I have been unable to see my dashboard on the DEX.  If I select that option, the top header "flashes" (no body) for less than a second the whole page is blank.  If I select "Exchange" or any of the other options, I see the page with the correct information.  I have tried several different times of the day and methods of logging in and opening the settings of the account with no luck.

**Comment by abitmore** [comment]
When the page went blank, is there any error message in the web console?
If you don't know how to open the web console, search for "how to open web console" with your favorite search engine.

**Comment by abitmore** [comment]
Perhaps try https://staging.bitshares.org/ which is the next release candidate.

**Comment by abitmore** [comment]
What's your account name?

**Comment by dxmynw-cld** [comment]
Dxmynw-cod

**Comment by abitmore** [comment]
Account `dxmynw-cod` does not exist on the chain.

If you mean `dxmynw-cld`, in my browsers (Firefox and Chrome) the dashboard https://wallet.bitshares.org/#/account/dxmynw-cld works fine. If you were not on https://wallet.bitshares.org but on another hosted web wallet, perhaps it's an issue on their end. Note that I've checked https://dex.compumatrix.co/#/account/dxmynw-cld and it works fine for me too.

**Comment by blincadmin** [comment]
Have you tried a full refresh? Ctrl F5

**Comment by shulthz** [comment]
USE: 3.3.200510-rc1
https://github.com/bitshares/bitshares-ui/releases

**Comment by dxmynw-cld** [comment]
While on the DEX site and using Chrome, I clicked CTRL+SHIFT+I and nothing showed up.  I tried Safari using CTRL+ALT+J and got the same results.
Ken

how to open web console



-----Original Message-----

**Comment by dxmynw-cld** [comment]
This worked.  Thank you.Ken Hamlin


-----Original Message-----
