### ISSUE TITLE
DEX values

### ISSUE THREAD

**Issue by dxmynw-cld** [bitshares/bitshares-ui#3266]
I recently had an issue with not being able to see my DEX account dashboard.  Support gave me a few options to try to see if any corrected the problem.  I found one..https://staging.bitshares.org/#/account/dxmynw-cld.  My DEX account is dxmynw-cld.  I noticed the BitUSD prices for the assets were not what I have normally been seeing lately...especially BTC.  My total value decreased to about 250,000 bitUSD to not quite 1,500.  I have included a screenshot of the dashboard with the numbers in question.
<img width="1517" alt="DEX Dashboard June 26 2020" src="https://user-images.githubusercontent.com/63297791/85905718-27ff0780-b7da-11ea-88e8-c12d2a3b899f.png">

Please advise.

Kenneth Hamlin

**Comment by sschiessl-bcp** [comment]
The USD and BTC you have are backed by Compumatrix. Seems best to contact them about it or withdraw them into real BTC and USD.

**Comment by blincadmin** [comment]
On your Compumatrix DEX, you pair it with COMPUMATRIX.USD and not bitUSD. That should explain why.  Please coordinate with them. Each ecosystem and community is different.
