### ISSUE TITLE
Local wallet creation is broken

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#3274]
The account creation via advanced form is broken, error below

![image](https://user-images.githubusercontent.com/33128181/87762382-56896480-c813-11ea-847a-9da2a398c26d.png)

Should be an easy fix as likely the pointer is "only" wrong. Also, it prints the entered password as cleartext, needs to be removed

**Comment by abitmore** [comment]
Should have been fixed by #3275.
