### ISSUE TITLE
bitshares does not recognize my password

### ISSUE THREAD

**Issue by DavidR72** [bitshares/bitshares-ui#3276]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavidR72** [comment]
bitshares .org does not accept my password

**Comment by sschiessl-bcp** [comment]
Please provide a holistic description of what is happening, plus error logs. Alternatively, visit https://t.me/btsWalletHelp

**Comment by ron931** [comment]
HI DavidR72, I just went to my bitshares account page. It shows me and my coins but I have the same problem as you. Bitshares.org does not accept my password. Did anyone ever figure out why?
