### ISSUE TITLE
i cant used open btc neither open Maid pls help

### ISSUE THREAD

**Issue by nacazu** [bitshares/bitshares-ui#3277]
i cant used open btc neither open Maid pls help
![bitshares](https://user-images.githubusercontent.com/31170376/88228050-78954380-cc66-11ea-84b8-008bd8c3e9c9.png)

**Comment by sschiessl-bcp** [comment]
Those assets are governed by OpenLedger. Please contact their support. They have shut down earlier this year.

**Comment by nacazu** [comment]
can you give me the link  for customer services of openledger please. .I
cant find itmany thnks

**Comment by abitmore** [comment]
Maybe https://openledger.info/contacts/ .

BTW there was a freshdesk support link https://openledger.freshdesk.com/ but seems it's closed too.
