### ISSUE TITLE
about#324

### ISSUE THREAD

**Issue by cxxcunow** [bitshares/bitshares-ui#328]
I download the wallet source codes modify the chainid and compile it ,but it fail to creat account. for local witness node and faucet network, can we modify some wallet codes to compile and use it?or how to construct the local faucet?because I want to code my private wallet ang private chain.

**Comment by svk31** [comment]
Just use a VPN for your faucet.

**Comment by wmbutler** [comment]
Please post questions to: https://t.me/BitSharesDEX
