### ISSUE TITLE
Cant create new accout

### ISSUE THREAD

**Issue by KENTua** [bitshares/bitshares-ui#3283]
when i try create new accout in https://wallet.bitshares.org/#/create-account/password, i always see error "Failed to create account: rattle129 - Unknown referrer code: onboarding"
i try:
opera on android
opera gx on windows
firefox on debian
and i always have this error

log:
`warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: INFO	browserEntropy gathered
log: synced and subscribed, chainstore ready
log: INFO	browserEntropy gathered
log: create account:rattle189
log: new active pubkeyBTS69hfAHCfSy8CpLQfTbsKp48Z2756wRZbrpLyDYBWxmEsjai2yC
log: new owner pubkeyBTS7GxSCQJt9At6BV2rHpcxSDeQkEiS3wkS9h7T7ntYonAHoHEsm6
log: new memo pubkeyBTS63uEccYLRCAsCw9qmyu1MW98m8zm4VduznPyXfcXbXQwKXncvD
log: ERROR AccountActions.createAccount[object Object]
log: Your node is out of sync since 5.8979997634887695 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 14.947999954223633 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 15.905999898910522 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 15.980999946594238 seconds, waiting 10 seconds, then we notify you
log: synced and subscribed, chainstore ready
log: INFO	browserEntropy gathered
log: create account:rattle129
log: new active pubkeyBTS86qKecD3DuCp7s6Xx34TiFA5RmrRWhht95aspjryfcMGvZxsQW
log: new owner pubkeyBTS53SwMZfxP8iWCvRcvpueKxAfraXHXM7iLAWs1g8ceW7q9gb1JD
log: new memo pubkeyBTS5j2h5w1RxLadxUCyYvzWFMnu4X8qveorV47MosF9geSLaQJ2C6
log: ERROR AccountActions.createAccount[object Object]`

**Comment by abitmore** [comment]
Try create your account via another hosted wallet E.G. https://ex.xbts.io/ . The account can then be used with all wallets. More info https://github.com/bitshares/awesome-bitshares/#hosted-wallets .

**Comment by shulthz** [comment]
Same problem in https://wallet.bitshares.org
