### ISSUE TITLE
cannot create NBS WALLET ACCOUNT

### ISSUE THREAD

**Issue by jeep1111** [bitshares/bitshares-ui#3287]
**Describe the bug**
CANNOT CREATE NBS wallet account

ERROR SHOW AS THESE:
log: 197242978ma19724true
log: [object Object]
log: 197242978ma197242true
log: [object Object]
log: 197242978ma1972429true
log: [object Object]
log: 197242978ma19724297true
log: [object Object]
log: 197242978ma197242978true
log: [object Object]
log: 197242978ma197242978mtrue
log: [object Object]
log: 197242978ma197242978mafalse
log: [object Object]
log: 197242978ma197242978mafalse
log: ------------ chain_idcd931cb96d657ff0ef0226f7ae9d25175b3cc96a84490a674ed36170830324e7
log: INFO	browserEntropy gathered
log: Congratulations, your wallet was successfully created.
log: ERROR AccountActions.createAccountTypeError: Failed to fetch
log: INFO	browserEntropy gathered

WHAT'S WRONG OF THESE?

**Comment by shulthz** [comment]
You need to ask NBS

**Comment by abitmore** [comment]
Please report in https://github.com/bitshares-cnvote/newbitshares-ui
