### ISSUE TITLE
Build fails for release 3.3.191120 (current wallet.bitshares.org release)

### ISSUE THREAD

**Issue by typoworx-de** [bitshares/bitshares-ui#3288]
**Describe the bug**
```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! BitShares2-light@3.3.191120 build: `cross-env NODE_ENV=production webpack --env.prod`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the BitShares2-light@3.3.191120 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gabriel/.npm/_logs/2020-09-16T11_27_01_485Z-debug.log
Failed: npm run build
```
**To Reproduce**
Followed "getting started" (https://github.com/bitshares/bitshares-ui/tree/3.3.191120#getting-started)

installed nvm, npm, did **npm run build** (run build crashes)

and finally build docker container from it.

**Expected behavior**
A clean build

**Screenshots**
![image](https://user-images.githubusercontent.com/1282298/93338130-4ea56b00-f82a-11ea-8aac-963022757728.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS

**Additional context**
Is there any release note or git tag stating which version is the current stable?

I had to go to https://wallet.bitshares.org/ and looked for the current release running there (left bottom corner).

**Comment by shulthz** [comment]
https://github.com/bitshares/bitshares-core/releases/tag/4.0.0

**Comment by abitmore** [comment]
Too old.

**Comment by abitmore** [comment]
> Is there any release note or git tag stating which version is the current stable?

The release notes are at https://github.com/bitshares/bitshares-ui/releases
