### ISSUE TITLE
[3] Inconsistent password after password change

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#33]
_From @dnotestein on January 10, 2016 19:25_

I changed the password of an account while I had two tabs open to that account (in the same browser). The old page still uses the old password for locking and unlocking the account. I'm also wondering if it's possible that the old password could be inadvertently saved back to the browser cache by the page that still uses the old password.

_Copied from original issue: cryptonomex/graphene-ui#663_

**Comment by wmbutler** [comment]
@dnotestein can you assist with reproduction of this issue including screenshots?

**Comment by calvinfroedge** [comment]
@wmbutler @dnotestein Possible to have more exact reproduction steps here?

**Comment by wmbutler** [comment]
Closing this after two requests for clarification with no response.
