### ISSUE TITLE
Migrate from Travis CI to Github Actions

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3302]
Travis-CI.org will be shut down on December 31, 2020. Full details are in [this newsletter from Travis](https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D).

Now is the time to migrate to Travis-CI.com.

Instructions for migrating to Travis-CI.com are available in the [Travis documentation on repository migration](https://docs.travis-ci.com/user/migrate/open-source-repository-migration).

In addition to migrating the repository to Travis-CI.com, please remember to also update the Travis status badges in the README.md files, make sure that all of the README.md files are using the Travis-CI.com badges. More information on Travis status badges is available in the [Travis documentation page on status images](https://docs.travis-ci.com/user/status-images/).

Reference: https://discourse.julialang.org/t/reminder-travis-ci-org-shuts-down-on-december-31-2020/47234

**Comment by sschiessl-bcp** [comment]
I'd suggest to migrate to GitHub actions if anything

**Comment by abitmore** [comment]
I do agree that Github Actions is good to have though. Anyway migration from travis-ci.org to travis-ci.com is just a few clicks.

**Comment by abitmore** [comment]
It seems the .com free plan is not suitable for us. See https://travis-ci.com/organizations/bitshares/plan

> Builds have been temporarily disabled for private and public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance.

**Comment by abitmore** [comment]
It is possible to get more credits, but I'm not sure how much work is needed (and I'm not going to try):

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
>
>* Your account name and VCS provider How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)

**Comment by abitmore** [comment]
This is mostly done for `develop` branch. The latest PR was https://github.com/bitshares/bitshares-ui/pull/3326.

By viewing the deployment history, https://github.com/bitshares/develop.bitshares.org/commits/master, we can see that Travis CI deployed again after Github Actions deployed.

I noticed there are some differences between the Travis CI flow and the Github Actions flow, see https://github.com/bitshares/develop.bitshares.org/commit/a64062387f04b5bdb3009ca50c358afa1a18df75,
*  `deposit-withdraw/index.html` is in the Travis flow but not in the Github Actions flow;
*  a line of code `<base href="/">` in `index.html` is in the Github Actions flow but not in Travis.

**Comment by sschiessl-bcp** [comment]
The deposit-withdraw file is [used by blocktrades](https://github.com/bitshares/bitshares-ui/blob/develop/app/components/DepositWithdraw/blocktrades/index.html). 

When we have a staging version this should be tested.

**Comment by abitmore** [comment]
New PR: https://github.com/bitshares/bitshares-ui/pull/3338

**Comment by abitmore** [comment]
BTW it seems we're not pushing to staging.bitshares.org via Github Actions.

**Comment by sschiessl-bcp** [comment]
Staging and master is next. Need to transfer the release bundling flow.

**Comment by abitmore** [comment]
Deploy key for staging is now active.

FWIW I added a deploy key to the `wallet.bitshares.org` repository but removed it later, because I thought there could be security issues -- according to https://github.com/github/docs/pull/2330, all user with write access to this repository is able to use the secrets via REST API thus is able to update the target repository. Any idea how to automate more safely?

**Comment by abitmore** [comment]
> deploy key ... security issues ...

It seems the "environments" feature would fit our needs, see https://docs.github.com/en/actions/reference/environments 
> You can configure environments with protection rules and secrets. A workflow job can reference an environment to use the environment's protection rules and secrets.

> When a workflow job references an environment, the job won't start until all of the environment's protection rules pass. A job also cannot access secrets that are defined in an environment until all the environment protection rules pass.

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/actions/runs/1977673859

This ones gonna fail due to missing secret. Need to check out https://docs.github.com/en/actions/reference/environments now

**Comment by abitmore** [comment]
Done.
