### ISSUE TITLE
can not trade 

### ISSUE THREAD

**Issue by wrj429** [bitshares/bitshares-ui#3303]
Today I made a tade, and after that, I can not tade anymore. 
The following codes are the record of my trade.
Tx:493931b622ae79ae90bab5f7915e1ea827d6ace6@53420889
When I click the "asset" to check my asset(BTS) on page "dashboard",  the screen （opened page）will be white.
so I can not make any trades.

**Comment by shulthz** [comment]
try: https://develop.bitshares.org/

**Comment by abitmore** [comment]
It seems to be a "white screen" issue.
Too old. Closing.
