### ISSUE TITLE
Cannot create new account

### ISSUE THREAD

**Issue by fitzie01730** [bitshares/bitshares-ui#3305]
Unknown error:

Logslog: ------------ chain_idcd931cb96d657ff0ef0226f7ae9d25175b3cc96a84490a674ed36170830324e7
log: synced and subscribed, chainstore ready
log: INFO	browserEntropy gathered
error: Required prop currentAccount isn't given, but still loading, this indicates that the rendering transitions are not well defined
error: Required prop baseAsset isn't given, but still loading, this indicates that the rendering transitions are not well defined
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: ------------ chain_idcd931cb96d657ff0ef0226f7ae9d25175b3cc96a84490a674ed36170830324e7
log: Error: Blocktime not available right now
log: ------------ chain_idcd931cb96d657ff0ef0226f7ae9d25175b3cc96a84490a674ed36170830324e7
error: InvalidStateError: An attempt was made to start a new transaction on a database connection that is not open
log: Error: Blocktime not available right now
log: ------------ chain_idcd931cb96d657ff0ef0226f7ae9d25175b3cc96a84490a674ed36170830324e7
log: ERROR AccountActions.createAccountTypeError: Failed to fetch
error: Required prop globalObject isn't given, but still loading, this indicates that the rendering transitions are not well defined
warn: Asking for non-existing fee id %d! Check group settings in Fees.jsx49
warn: Asking for non-existing fee id %d! Check group settings in Fees.jsx50
warn: Asking for non-existing fee id %d! Check group settings in Fees.jsx52
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: auto locking after600s
log: ERROR AccountActions.createAccountTypeError: Failed to fetch

**Comment by sschiessl-bcp** [comment]
Which Blockchain are you trying to connect to?

**Comment by abitmore** [comment]
Out of scope. Closing.
