### ISSUE TITLE
Loads White Screen On Account When An Operation Is Not Supported

### ISSUE THREAD

**Issue by iamredbar** [bitshares/bitshares-ui#3309]
**Describe the bug**
The UI fails to load when there is an operation that it cannot define, ie Voting Tickets. Specifically, it will not display a proposal of a voting ticket. This causes a white screen to appear and not be able to use the dashboard.
All other areas of the UI work, but with this operation in the history it causes problems.

**To Reproduce**
1. Have a proposal of a voting ticket sent to you
2. Try to load account information in the UI
3. See error

**Expected behavior**
UI to function normally except for the small function that it cannot perform, like displaying an operation type not yet supported.

**Screenshots**
Working page:
<img width="1391" alt="Screen Shot 2020-12-01 at 5 57 47 PM" src="https://user-images.githubusercontent.com/16945982/100810794-d436c100-33fe-11eb-9283-75d800af40fe.png">
Non-working page:
<img width="1391" alt="Screen Shot 2020-12-01 at 5 53 31 PM" src="https://user-images.githubusercontent.com/16945982/100810590-6c807600-33fe-11eb-9624-fabe9409104c.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave (10.14.6)
 - Browser: Brave
 - Version: 1.17.73 (Chromium 87.0.4280.67)

**Comment by iamredbar** [comment]
It appears like Safari version 14.0 (14610.1.28.1.9) doesn't have the issue...
<img width="1937" alt="Screen Shot 2020-12-01 at 6 03 55 PM" src="https://user-images.githubusercontent.com/16945982/100811253-ccc3e780-33ff-11eb-8c17-332a731b3e75.png">

**Comment by iamredbar** [comment]
Safari and Chrome both work, but they show nothing on the activity page when loaded.
<img width="1312" alt="Screen Shot 2020-12-01 at 6 10 10 PM" src="https://user-images.githubusercontent.com/16945982/100811931-7192f480-3401-11eb-976d-12fb0cbac736.png">

**Comment by iamredbar** [comment]
staging.bitshares.org doesn't crash on Brave Browser, but still shows no account activity with a non-supported operation.
<img width="1391" alt="Screen Shot 2020-12-01 at 6 21 13 PM" src="https://user-images.githubusercontent.com/16945982/100812253-3218d800-3402-11eb-96da-491ee9296404.png">

**Comment by abitmore** [comment]
Just FWIW it works for me both in Firefox and Chrome on Ubuntu 18, although shows no detail, at least doesn't show a white screen.

![image](https://user-images.githubusercontent.com/9946777/100815535-79c05380-3444-11eb-8074-7f4a7fcda214.png)

**Comment by abitmore** [comment]
Update: it seems that the New Jersey node doesn't return account history. Please try another node.

**Comment by iamredbar** [comment]
Thanks @abitmore. I'll try a different node. Closing issue.
