### ISSUE TITLE
about faucet

### ISSUE THREAD

**Issue by cxxcunow** [bitshares/bitshares-ui#331]
in the http://docs.bitshares.org/testnet/7-faucet.html#rails-api,  it says we should use this https://github.com/cryptonomex/faucet and it is two years ago. and when run mina deploy, it fails for 
not a git repository:'tmp/deploy/.git' 
change_dir "/faucet//tmp/deploy" no suche file : here you see it is //tmp but not /tmp
and resync error : some file not transferred

and installing gem dependencies using bundler: could not locate gemfile error.

**Comment by wmbutler** [comment]
Please post issues related to documentation here: https://github.com/bitshares/bitshares.github.io/issues
