### ISSUE TITLE
[5][gn1github] Japanese Translation

### ISSUE THREAD

**Issue by crypto-1** [bitshares/bitshares-ui#332]
Hi,

I have someone who is willing to do a japanese client translation. Please let me know how proceed.

best regards
~mindphlux

**Comment by wmbutler** [comment]
I'd probably estimate this at 2 hours. @svk31 is there any setup required to add a new translation?

**Comment by wmbutler** [comment]
I've assigned this 2 hour bounty to you due 9/14.

**Comment by VANCO-JP** [comment]
I will have the engineer and review the information and reply ASAP.. thank you

**Comment by svk31** [comment]
No additional setup needed, just translate all the keys in locale-en.json in a new file locale-jp.json and add jp as a language in the `defaults` of SettingsStore.js

**Comment by wmbutler** [comment]
@VANCO-JP are you claiming this or not?

**Comment by wmbutler** [comment]
Removing from Milestone.

**Comment by wmbutler** [comment]
@gn1github need your BTS address

**Comment by gn1github** [comment]
It's gn1
