### ISSUE TITLE
Can't Claim Fee Pool Balance

### ISSUE THREAD

**Issue by wolfix9** [bitshares/bitshares-ui#3322]
If I try to claim the Fee Pool Balance, an error pops up that says 

**10 - Execution error: Assert Exception: fee.asset_id != asset_id:** 

If I show more details, here is what it says:

**{
    "code": 10,
    "name": "assert_exception",
    "message": "Assert Exception",
    "stack": [
        {
            "context": {
                "level": "error",
                "file": "asset_ops.cpp",
                "line": 334,
                "method": "validate",
                "hostname": "",
                "thread_name": "pool worker 3",
                "timestamp": "2021-01-15T16:09:55"
            },
            "format": "fee.asset_id != asset_id: ",
            "data": {}
        }
    ]
}**

_To Reproduce_
1. Go to 'Asset Actions'
2. Click on 'Claim Fee Pool Balance'
3. Propose

<img width="505" alt="Claim Fee Error" src="https://user-images.githubusercontent.com/77501950/104750746-c80b8680-5754-11eb-8e5b-1dffd0b8a5cb.png">

Thank you so much for your help!
Really appreciate it

**Comment by abitmore** [comment]
It is not a bug, but a feature of the core, although some people think it is annoying.

When claiming fee pool of an asset you can not use that asset to pay the transaction fee, because the amount in the fee pool would be reduced due to the payment. Try pay fee with BTS directly.

**Comment by wolfix9** [comment]
Thank you for your rapid response :)
How do I do that? I just propose and accept the proposal, it doesn't give me the option to choose where to take the transaction fee from

**Comment by wolfix9** [comment]
I do have enough for the fee and the default paying asset is BTS, but it still doesn't work :(

**Comment by abitmore** [comment]
Can you click "Show raw json" to see more info and paste here? Note that there are multiple levels nested, best expand all.

BTW why create a proposal? If you're the asset owner you can claim the pool directly.

**Comment by abitmore** [comment]
Or what's on your screen when seeing this dialogue?

![image](https://user-images.githubusercontent.com/9946777/104755327-93023280-575a-11eb-8f6d-a52d170e7143.png)

**Comment by wolfix9** [comment]
root:[] 2 items
0:22
1:{} 6 items
fee:{} 2 items
amount:974879
asset_id:1.3.0
fee_paying_account:1.2.423082
expiration_time:2021-01-16T16:50:48
proposed_ops:[] 1 item
0:{} 1 item
op:[] 2 items
0:47
1:{} 5 items
fee:{} 2 items
amount:482609
asset_id:1.3.0
issuer:1.2.3
asset_id:1.3.0
amount_to_claim:{} 2 items
amount:2759699835
asset_id:1.3.0
extensions:[] 0 items
review_period_seconds:undefined
extensions:[] 0 items

Here are the sequences of the steps that I'm following, is there another way to claim them directly?

<img width="1269" alt="Screenshot 2021-01-15 at 17 50 46" src="https://user-images.githubusercontent.com/77501950/104755536-dbb9eb80-575a-11eb-96f6-189d16d203bc.png">

<img width="1280" alt="Screenshot 2021-01-15 at 17 50 56" src="https://user-images.githubusercontent.com/77501950/104755548-e07e9f80-575a-11eb-9083-84efe34b582b.png">

**Comment by abitmore** [comment]
It seems you're trying to claim fee pool of the BTS asset, which is not possible.

**Comment by wolfix9** [comment]
Oh damn, I thought they were in my account cause I saw the available balance

My bad :) sorry for wasting your time!

Thank you for your support
