### ISSUE TITLE
cannot login with .bin file 

### ISSUE THREAD

**Issue by zerranne** [bitshares/bitshares-ui#3328]
log: fallback to new url:wss://openledger.hk/ws
error: wss://openledger.hk/wsFailed to initialize with errorundefined
log: fallback to new url:wss://bit.btsabc.org/ws
error: wss://bit.btsabc.org/wsFailed to initialize with errorundefined
log: fallback to new url:wss://ws.gdex.top
log: synced and subscribed, chainstore ready
log: Latency result:[object Object]
error: getCachedProperty error:InvalidStateError: An attempt was made to start a new transaction on a database connection that is not open
log: Error: Blocktime not available right now
error: getCachedProperty error:InvalidStateError: An attempt was made to start a new transaction on a database connection that is not open
log: Error: Blocktime not available right now
log: synced and subscribed, chainstore ready
error: Required prop currentAccount isn't given, but still loading, this indicates that the rendering transitions are not well defined
error: Required prop quoteAsset isn't given, but still loading, this indicates that the rendering transitions are not well defined
error: 1.3.121_1.3.0does not have a properly configured feed price
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: Error: Blocktime not available right now
log: synced and subscribed, chainstore ready
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: synced and subscribed, chainstore ready

Here is what i have got, i just restored my account through restore button, then entered my password and it moves me to the main page and nothing happens, i have some tokens on my wallet, want them

please help

**Comment by abitmore** [comment]
Please recreate an issue using the bug-report template.

**Comment by abitmore** [comment]
Link: https://github.com/bitshares/bitshares-ui/issues/new?assignees=&labels=&template=Bug_report.md
