### ISSUE TITLE
cannot login with .bin file

### ISSUE THREAD

**Issue by zerranne** [bitshares/bitshares-ui#3329]
og: fallback to new url:wss://openledger.hk/ws
error: wss://openledger.hk/wsFailed to initialize with errorundefined
log: fallback to new url:wss://bit.btsabc.org/ws
error: wss://bit.btsabc.org/wsFailed to initialize with errorundefined
log: fallback to new url:wss://ws.gdex.top
log: synced and subscribed, chainstore ready
log: Latency result:[object Object]
error: getCachedProperty error:InvalidStateError: An attempt was made to start a new transaction on a database connection that is not open
log: Error: Blocktime not available right now
error: getCachedProperty error:InvalidStateError: An attempt was made to start a new transaction on a database connection that is not open
log: Error: Blocktime not available right now
log: synced and subscribed, chainstore ready
error: Required prop currentAccount isn't given, but still loading, this indicates that the rendering transitions are not well defined
error: Required prop quoteAsset isn't given, but still loading, this indicates that the rendering transitions are not well defined
error: 1.3.121_1.3.0does not have a properly configured feed price
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: Error: Blocktime not available right now
log: synced and subscribed, chainstore ready
warn: Deprecated: please use require("intro.js") directly, instead of the introJs method of the function
log: synced and subscribed, chainstore ready

Here is what i have got, i just restored my account through restore button, then entered my password and it moves me to the main page and nothing happens, i have some tokens on my wallet, want them

please help

**Comment by abitmore** [comment]
Are you using the downloaded app or browser?

If it's a browser, is it incognito/private mode? Try use the standard mode.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

You can also try https://develop.bitshares.org/

**Comment by zerranne** [comment]
I have attached video, and also, i tried develop.bitshares

and nothing happens

i tried through

OS 13
Browser Safari

and also

Macbook air 13 M1 
Safari 

and also

inside the Macbook M1 virtual machine on parallel space 
Windows 10 Pr Insider Preview
Chrome

**Comment by zerranne** [comment]
cannot upload video

**Comment by zerranne** [comment]
it just nothinh happens after i enter the correct password to my bin file

**Comment by zerranne** [comment]
https://filebin.net/wpsb701xudywnd7k

**Comment by abitmore** [comment]
Perhaps your bin file is corrupted, or it does not contain your account (E.G. you made the bin file when you were using cloud/account mode). Please feel free to ask in Telegram group: https://t.me/btsWalletHelp

**Comment by zerranne** [comment]
so how should i restore my account then? could you please explain. i had some
bts tokens there

**Comment by sschiessl-bcp** [comment]
> Perhaps your bin file is corrupted, or it does not contain your account (E.G. you made the bin file when you were using cloud/account mode). Please feel free to ask in Telegram group: https://t.me/btsWalletHelp

This
