### ISSUE TITLE
BTS Payment Addresses

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#333]
For contributors:

- @happyconcepts
- @calvinfroedge 
- @tylerflether914
- @skenan
- @hyper-bola
- @ariesjia
- @rrandom

Please provide me with an accurate bitshares account so I can pay your bounties. To confirm the amount you are owed, feel free to review this spreadsheet. Leave a comment below with your bts address.

https://docs.google.com/spreadsheets/d/1jKPNWp-dw-ku2ufd51Omje20yucsKb3F9gcQsONROzU/edit?usp=sharing

**Comment by hyper-bola** [comment]
Hi Bill, my BTS account is `para-shd`, thanks.

**Comment by calvinfroedge** [comment]
`calvin-froedge`

**Comment by skenan** [comment]
skenan-bitshares

**Comment by ariesjia** [comment]
`ares-chen`

**Comment by rrandom** [comment]
emanon-h

**Comment by happyconcepts** [comment]
`sell-bitcoin`
