### ISSUE TITLE
An error appears while I'm trying to update the CHZ owner account

### ISSUE THREAD

**Issue by vldvld** [bitshares/bitshares-ui#3335]
**Describe the bug**
When I confirm the transaction to update the CHZ to my account I get the "An error occured while broadcasting"

**To Reproduce**
1. Go to Chiliz (CHZ) asset actions
2. Click on the Update owner button
3. Select the New asset owner account as my account
4. Click the Update owner button
5. Click the Confirm button

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/13893240/107500308-b031f180-6b9e-11eb-8e88-5656268cff4f.png)
![image](https://user-images.githubusercontent.com/13893240/107500367-c049d100-6b9e-11eb-9bfb-149081c4491a.png)

**Desktop (Macbook pro 2015):**
 - OS: [Big sur]
 - Browser [Chrome]
 - Version [88]

**Additional context**
log: auto selecting to wss://api.dex.trading/
log: Connecting to wss://api.dex.trading/
log: synced and subscribed, chainstore ready
log: browser notifications disabled by Browser Permissions
warn: missing path 'assets/CHILIZ' for locale 'en' help files, rolling back to alt_path 'assets/Asset'
log: browser notifications disabled by Browser Permissions
warn: missing path 'assets/CHILIZ' for locale 'en' help files, rolling back to alt_path 'assets/Asset'
error: Error: Transaction was not signed. Do you have a private key? [no_signers]
warn: missing path 'assets/CHILIZ' for locale 'en' help files, rolling back to alt_path 'assets/Asset'
error: Error: Transaction was not signed. Do you have a private key? [no_signers]
warn: missing path 'assets/CHILIZ' for locale 'en' help files, rolling back to alt_path 'assets/Asset'

**Comment by sschiessl-bcp** [comment]
Are you signing the transaction with your owner permission?

**Comment by abitmore** [comment]
It strange that no detailed message shown on the page though.

**Comment by vldvld** [comment]
> Are you signing the transaction with your owner permission?

What do you mean by my owner's permission?
This is my first bitshares transaction, so I do not clearly understand this

where can I sign my transaction with my owner's permission? Thanks

**Comment by vldvld** [comment]
@sschiessl-bcp hi Stefan, could you check my previous message?

**Comment by abitmore** [comment]
@vldvld to update the asset you need to sign in as `chiliz0` but not `marco-bonucci`.

**Comment by vldvld** [comment]
@abitmore but the marco-bonucci is my only account 
I don't know why bt I cannot withdraw my CHZ due to the fact that the coin is displayed as unavailable
https://prnt.sc/zzye50 - screenshot

**Comment by abitmore** [comment]
@vldvld it seems you got scammed by someone so you bought that coin which is unable to be withdrawn. The warning on your screenshot didn't prevent you from doing so. Sorry to see your losses.

![image](https://user-images.githubusercontent.com/9946777/108388464-f4f90080-720e-11eb-9a71-72a38e1d4748.png)
