### ISSUE TITLE
[1][ariesjia] Available Collateral Becomes "NAN" When Borrowing BitAsset

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#334]
This might have been fixed since the May 22 release but in case not:

1) Try to borrow a bitAsset
2) Start typing any value in Collateral then delete all the digits (should become 0.0)
3) Start typing anything in Debt field

The available collateral should become "Available: NAN BTS".

This fixes if you start typing in the Collateral field again. I think the problem is that the value of "0.0" confuses the calculation while "0" does not.

Another possibly related curiosity is that if you have typed nothing yet in Collateral field and you start typing in the Debt field, the collateral field changes to "0.00000" but if you have typed ANYTHING in the Collateral field (even a letter which does nothing) then typing in the Debt field will make the collateral field "0.0".

I made a screencast but looking at the github supported file types I can't see which format I could use. GIF?

**Comment by ariesjia** [comment]
@wmbutler  can i take this issue

**Comment by wmbutler** [comment]
It's yours.
