### ISSUE TITLE
Avoid multi-auth phishing attack

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3343]
**Is your feature request related to a problem? Please describe.**

Several people have been phished by so-called "multi-auth attack" recently.

The attacker registered a lot of phishing accounts which are similar to exchange deposit accounts or frequent recipients of victims, and added the victims' to the phishing accounts' active authorities with a low weight. When a victim opens the "Send" dialogue, a phishing account will appear in the drop down list of "to" field automatically, if the victim didn't pay attention but clicked the phishing account, funds will be sent to the phishing account.

Note: it only affects key-file (.bin file or local wallet) login mode.

![image](https://user-images.githubusercontent.com/9946777/109020404-37f91f00-76ba-11eb-99c9-da3c85a83caa.png)

I've tried to reproduce, see screenshots below.
![image](https://user-images.githubusercontent.com/9946777/109020090-f10b2980-76b9-11eb-97f0-efd20930c7ec.png)

![image](https://user-images.githubusercontent.com/9946777/109019910-bd300400-76b9-11eb-8288-3e0e94445155.png)

**Describe the solution you'd like**

A quick workaround is to disable the drop down list temporarily.

Better solutions are to be discussed.

**Comment by abitmore** [comment]
Some ideas for long-term solution:
* label "my accounts" and "contacts" in account selector with different color and/or text
* improve the `isKnownScammer` check to check from dynamic data source (E.G. https://github.com/bitshares/bitshares-ui/issues/2658#issuecomment-705196013).
* warn user when detected it's the first time to transfer to a recipient (this may be not as useful due to limited history size)

**Comment by shulthz** [comment]
> 
A quick workaround is to disable the drop down list temporarily.

or only "my accounts" and "contacts" or “history” can be in this list.

-------------------------
There hava a BTS ID for every account, maybe as a authentication for “multi-auth” confirm.

**Comment by abitmore** [comment]
> or only "my accounts" and "contacts" or “history” can be in this list.

Actually the multi-auth phishing accounts are identified as "my accounts" now, because the victims "own" a weight of those accounts. We need to figure out a way to distinguish them (probably via UX).

By the way, if pay attention, when transferring, accounts in contacts now show an "star" icon, while my accounts and such phishing accounts show a user icon, and the account inputted has no icon if not in my accounts, contacts or known scam account list.

The screenshot below was for reproducing a scenario that assumes `abit-test` is the attacker, `abit-test2` is the victim, and `abit` is in contacts.

![image](https://user-images.githubusercontent.com/9946777/109127780-16964280-774f-11eb-9e34-23f4b2695662.png)

The workaround in pull request #3344 won't show my accounts at all, which is a bit inconvenient but safer (a test environment is temporarily available at https://pr.bts.mobi/):

![image](https://user-images.githubusercontent.com/9946777/109128317-a936e180-774f-11eb-9873-5891738a1f62.png)

**Comment by abitmore** [comment]
I think this is fixed.
