### ISSUE TITLE
Eliminate Leading Zeros in Borrowing BitAssets Window

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#335]
Leading zeros in digits look silly... they do. Also, it causes the placement of the commas to be off.

Steps to Reproduce:
1) Borrow a bitAsset of which you have no current debt.
2) Click after the default 0 in any value entry field.
3) Start typing digits.

You will see that that default zero stays in front of the number and after you type 3 digits then it places a comma before them allowing for numbers like "0,832" which is ridiculous.

I am using the May 22 light client release on Mac OS.

**Comment by ariesjia** [comment]
@wmbutler  can i take this issue

**Comment by wmbutler** [comment]
It's yours. Thanks!

**Comment by ariesjia** [comment]
This issue is already fixed ， This bug doesn't  appear  right now

**Comment by wmbutler** [comment]
OK, it must have been resolved in the previous Sprint. Thanks.
