### ISSUE TITLE
Send of NBS never received on Binance

### ISSUE THREAD

**Issue by tmt77** [bitshares/bitshares-ui#3358]
**Describe the bug**
On 2021-03-10 17:32:42 I sent 1,604.43980 rudex.NBS to binance-nbs-02 (memo field was populated with 101357145, as per Binance's deposit instructions)

The Binance support team have indicated that they have not found any evidence of the deposit, although I wasn't able to provide them with a TxHash (TxId) as I don't no where to find it.

Can you please investigate the transaction from your side and advise?

Thank you.

**Screenshots**
![image](https://user-images.githubusercontent.com/80967752/111794716-21468200-888c-11eb-81cd-74452002b8e6.png)

![image](https://user-images.githubusercontent.com/80967752/111797669-fc074300-888e-11eb-8ef1-179bd459f0c4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome]
 - Version 89.0.4389.82 (Official Build) (64-bit)

**Comment by sschiessl-bcp** [comment]
Please ask RuDEX or NBS team for support, this is the BitShares blockchain.

If your transaction happened here, you can get the trx hash on blocksights.info.

**Comment by tmt77** [comment]
Yes, I used a simple "send" (the withdraw icon/button was not an available option).  NOTE: I had also used the simple "send" to send my BTS to Binance and that occurred without issue. It was just the NBS that never arrived at Binance.

By asking me to go to the RuDEX or NBS team for support are you also implying that I should *not* have initiated the "send" of the NBS from my BitShares online wallet (https://wallet.bitshares.org/), even though the RUDEX.NBS balance was clearly visible there as well as the "Send" icon/button available.

Also, I have no idea how to access the RuDEX or NBS support teams.  Can you please help guide me?

Thank you.

**Comment by abitmore** [comment]
@tmt77 Rudex support link is on their home page https://rudex.org/ https://rudex.freshdesk.com/support/home
