### ISSUE TITLE
BTS TRANSACTION ID

### ISSUE THREAD

**Issue by jherazo1946** [bitshares/bitshares-ui#3360]

**Comment by abitmore** [comment]
Please find it on https://blocksights.info/

**Comment by jherazo1946** [comment]
https://blocksights.info/  Do you know if it can be searched by specific date? I went to  https://blocksights.info/ but it does not give the option to search by specific date but searching multiple pages with thousands of transactions.

**Comment by iamredbar** [comment]
Go to the explorer that Abit mentioned and search your account name. Then you can find the transaction and information about the transaction

**Comment by jherazo1946** [comment]
Thank you very much. I found it.

EMAIL CHANGE.

1.Full name (including middle names, please be consistent with your document)

JOSE ROBERTO HERAZO OSORIO

2.Date of birth,

12 NOVEMBER 1946

3.Nationality,

COLOMBIAN

4.Type of identity document

COLOMBIAN PASSPORT

5.Identity document number,

AQ531530

6.The photo of your identity document.

ATTACHED

7. The account you want to unlink:
NO. I ONLY WANT TO CHANGE MY EMAIL ADDRESS FROM JH@A1G-LLC.COM to JRHO1946@PM.ME

8. Do you agree us to freeze your withdrawal function until you complete the
KYC 2?

NO. I ONLY WANT TO CHANGE MY EMAIL ADDRESS FROM JH@A1G-LLC.COM to JRHO1946@PM.ME

Thank you.

JOSE HERAZO

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by iamredbar** [comment]
@jherazo1946 please edit your comment, it has your information in it. It should not be there. Please delete.

**Comment by iamredbar** [comment]
@abitmore @sschiessl-bcp can someone please edit or remove the post above with the personal info in it?

**Comment by jherazo1946** [comment]
Thanks, I am new to github. thank you for your assistance.

**Comment by iamredbar** [comment]
No problem. Please close out the issue if it has been resolved.

**Comment by jherazo1946** [comment]
Closed. Thank you,
