### ISSUE TITLE
lost funds

### ISSUE THREAD

**Issue by Dollardog4422** [bitshares/bitshares-ui#3361]
My account on Bitshares has disappeared. When I sign in my user name is not recognized and my account V44-236qw2  can not be found.

Michael Guglielmino        mguglielmino@earthlink.net

**Comment by iamredbar** [comment]
I've found an account "v44-z36qw2"
<img width="1304" alt="Screen Shot 2021-03-24 at 5 18 08 PM" src="https://user-images.githubusercontent.com/16945982/112390887-ff526280-8cc4-11eb-9d43-ba38af093f07.png">

**Comment by Dollardog4422** [comment]
That is my account, thank you.  But, I have not been able to gain access to it.When I put in my account name, I am told it is not recognized. I was able to create a new password but I am still not recognized by my password, so I can't get in.Should I attempt to create a new account name?Michael Guglielmino     -----Original Message-----

**Comment by iamredbar** [comment]
I know that it isn't recognized, I am guessing that when you wrote down your account you confused the z with a 2. That is why I told you I found an account that is the exact same as what you are looking for, except it has a z instead of a 2. They are easily confused.

**Comment by Dollardog4422** [comment]
Mr. Brendan Jensen,Thank your for your assistance, it is much appreciated.  Yes, you are correct, I was misreading the z for a 2.  You have identified my account and the correct account number. That solved problem #1, but unfortunately I have a more basic problem as well, the system does not recognize my account name, which is or was Dollardog4422. When I take the first step to open my account and enter Dollardog4422  in the account box to gain entry to my account, red letters beneath the entry area say unknown account and I can go no farther. I have tried my email address as well with the same result. Is there a method to regain my account name or for me to reset to a new account name, so that I can proceed to my account?Thanks again for your help,Michael Guglielmino-----Original Message-----

**Comment by iamredbar** [comment]
When you log into the BitShares wallet, you use your account. It does not have a separate name, you use your account when logging in.
The only account on-chain that has dollardog in it is "dollardog-323".

**Comment by abitmore** [comment]
Too old. Closing.
