### ISSUE TITLE
Cannot login cloud wallet via username and password

### ISSUE THREAD

**Issue by SaffiYang** [bitshares/bitshares-ui#3367]
Tried to login the cloud wallet via username and password and cannot continue without any error but the password input box turned red like following picture
![image](https://user-images.githubusercontent.com/6907408/115229325-7d2f4f80-a145-11eb-8d64-47976f94efc3.png)

Can anyone help me on this? thanks.

**Comment by abitmore** [comment]
Typically the password of a cloud wallet starts with `P5` and is more than 50 characters long. Your password looks short, so I think it's not for a cloud wallet. Please try find a .bin file from your backup device and login with it in key-file mode.

**Comment by SaffiYang** [comment]
I lost the computer that I used to create the account, does it means that it's impossible to get it back without it?

**Comment by sschiessl-bcp** [comment]
> I lost the computer that I used to create the account, does it means that it's impossible to get it back without it?

If you had a local wallet, your account is lost without the .bin file, or if you don't have any other backup of your keys.

**Comment by abitmore** [comment]
Too old and no progress. Closing.
