### ISSUE TITLE
Can't access open.BTC and open.ETH

### ISSUE THREAD

**Issue by rorsta99** [bitshares/bitshares-ui#3368]
Hi, I'm trying to access my funds and Bitshares says deposits and withdrawals are disabled for open.BTC and open.ETH. How do I get access to my coins and trade or withdraw them? 

Accounts: 
my-coin
petes-coin

Cheers!

**Comment by sschiessl-bcp** [comment]
OpenLedger closed its business.

https://develop.bitshares.org/#/asset/OPEN.BTC/

**Comment by sschiessl-bcp** [comment]
From telegram

> Abit More, [29.03.21 09:24]
> For issues about OpenLedger, please check this (and please be aware that the investigation itself can be a scam too, please > do your own diligence) https://www.reddit.com/r/Bitcoin/comments/k0unea/openledger_dex_alleged_fraud_investigation/
