### ISSUE TITLE
[1] v2.0.170829 unable to add nodes

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#337]
In settings->access, it jumps to main page when clicking "add node".

**Comment by wmbutler** [comment]
Agreed. @calvinfroedge

**Comment by wmbutler** [comment]
Calvin, I tested this at bitshares.org/wallet and the bug report is accurate. I've added it into a patch milestone because this should be a hotfix for release today.

**Comment by btsfav** [comment]
@wmbutler it's also bugged in the light wallet(windows). if you click access the main screen gets stuck

**Comment by wmbutler** [comment]
@btsfav Yes, we saw that and it's being addressed.

**Comment by btsfav** [comment]
just tested in webwallet... the bugs seem slightly different?

see:
![](http://i.imgur.com/xtjcEBQ.gif)

@wmbutler @svk31

**Comment by calvinfroedge** [comment]
@abitmore @btsfav 

There seem to be a few different issues here...

1) Electron issue being able to add nodes was resolved...apparently electron handles links slightly differently than a browser does and I could not use an anchor tag for the link. PR: https://github.com/bitshares/bitshares-ui/pull/340

2) I cannot reproduce the error clicking the "Access" tab. However, I was not able to use the bitshares.org/wallet at all until clearing local storage.

**Comment by abitmore** [comment]
@btsfav try delete everything under Local Storage -> file:// . #336

**Comment by calvinfroedge** [comment]
Updated build:

https://drive.google.com/file/d/0BzvuEYutkmtdTHFYbWRuWkFxX2s/view?usp=sharing

sha1: 79e65edf1ef57f32768501031ca85bc6d565fcb2
sha256: f15892e3edd1328343f7f5a89a51b92a1ee41ef9653de5c0d3da7d1e244e5c96

**Comment by btsfav** [comment]
@calvinfroedge 

maybe this helps

![](https://i.imgur.com/8iQsmGq.png)

@abitmore 

not sure what you want me to do

**Comment by calvinfroedge** [comment]
@btsfav Open your console and type `localStorage.clear()`. I'm trying to support you on this, but did not create the issue you're experiencing.

**Comment by btsfav** [comment]
@calvinfroedge 
localStorage.clear()
undefined

**Comment by calvinfroedge** [comment]
```
edit2: shows all nodes as DOWN though :)
```

@btsfav I added that as 3rd point above. It does not seem to be related to the changes I made. This works in the electron version and in local builds. The ping logic was not changed, so I imagine this issue is environment specific and was pre-existing. We can address it as a separate issue but we will need to do some additional work to set up effective testing in every environment bitshares is being deployed.

**Comment by abitmore** [comment]
@btsfav 
![f7c2364c-ad6d-474e-ab9c-2f3f05b9d5b8](https://user-images.githubusercontent.com/9946777/29883982-3c7f38a6-8db2-11e7-8812-dc81e5be677f.jpg)

**Comment by btsfav** [comment]
@calvinfroedge the nodes shown as DOWN because I used a non-listed NODE. after I selected "closest..." nodes are displayed correctly

@abitmore thanks, worked via the console cmd

**Comment by calvinfroedge** [comment]
@btsfav Ok, good to know that selecting closest fixes, I will check to see if I can figure out why.

**Comment by wmbutler** [comment]
When a new version of the client is released, browser localstorage can hold onto information that causes unexpected behavior regarding node status and selection. The user can delete localstorage manually, but a better system would be for the code to compare it's version, possible a version in `package.json` to a value place in localstorage. If the versions match, leave localstorage untouched. If values are different, clear localstorage.

**Comment by calvinfroedge** [comment]
@wmbutler It would probably be a good idea to include the patch / PR I already issued for fixing the electron issue now rather than waiting till 9/14.

**Comment by wmbutler** [comment]
Agreed... @svk31

**Comment by svk31** [comment]
Clearing local storage is a bad idea, lots of useful stuff is stored, like all the user's settings, possibly deposit addresses etc.

**Comment by wmbutler** [comment]
But we do need a way to resolve this issue that doesn't require user intervention, So I'm keeping it open for discussion.

**Comment by wmbutler** [comment]
I'll simplify this issue as adding a node and we can tackle localstorage issue elsewhere.
