### ISSUE TITLE
Lost over 100 dollars

### ISSUE THREAD

**Issue by ckerflag** [bitshares/bitshares-ui#3389]
log: Your node is out of sync since 5.746999979019165 seconds, waiting 10 seconds, then we notify you
log: auto locking after600s
log: unimplemented op:63,[object Object]
log: Your node is out of sync since 5.743000030517578 seconds, waiting 10 seconds, then we notify you
log: synced and subscribed, chainstore ready
log: fetchCoins error from https://api.gdex.io/adjust/coins: TypeError: Failed to fetch
log: fetchTradingPairs error from https://api.gdex.io/adjust/trading-pairs: TypeError: Failed to fetch
log: error fetching blocktrades active walletsTypeError: Failed to fetchhttps://api.gdex.io/adjust/active-wallets
log: Latency result:[object Object]
warn: No nodes length, returning all of them
log: Connecting to wss://api.bts.mobi/ws
log: synced and subscribed, chainstore ready
log: Latency result:[object Object]
log: fetchCoins error from https://api.gdex.io/adjust/coins: TypeError: Failed to fetch
log: fetchTradingPairs error from https://api.gdex.io/adjust/trading-pairs: TypeError: Failed to fetch
log: error fetching blocktrades active walletsTypeError: Failed to fetchhttps://api.gdex.io/adjust/active-wallets
log: Latency result:[object Object]
log: Your node is out of sync since 9.141000032424927 seconds, waiting 10 seconds, then we notify you
log: Your node is out of sync since 11.280999898910522 seconds, waiting 10 seconds, then we notify you
log: auto locking after600s
![image](https://user-images.githubusercontent.com/34635509/129429860-8a077b17-a501-4f87-83ca-15738b81faa7.png)

**Comment by ckerflag** [comment]
Lost internet had to restart...... but my browser was still connected ....it was just the site when the feed price got refreshed I got a no internet page with the blue retry button....that is when I noticed I was way short like over112 dollars + the profit

**Comment by abitmore** [comment]
What are you talking about? Seems unrelated to the bitshares-ui repository. Closing.
