### ISSUE TITLE
Vertical order book glitches out after changing markets.

### ISSUE THREAD

**Issue by xanoxt** [bitshares/bitshares-ui#339]
![](https://camo.githubusercontent.com/ba7ff0d9489f340dea0c8a6f53a19e21c65188a2/68747470733a2f2f7331372e706f7374696d672e6f72672f6b6c6d743778646b662f696d6167652e706e67)

The upwards bit disappears because of the scrolling. It is a known issue, although I can't seem to find it in this issue tracker. Also, sometimes the last price between the halves of the book dissapears.

https://github.com/blckchnd/rudex-ui/issues/57

**Comment by wmbutler** [comment]
This was a bug in the reference client. We fixed it in the reference client during the last Sprint. Tell the creator of the Rudex Exchange that they can pull our latest code and it will fix it for their client as well.
