### ISSUE TITLE
Node.js version 10 end-of-life

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3406]
**Is your feature request related to a problem? Please describe.**

According to https://nodejs.org/en/about/releases/, Node.js version 10 reached its end-of-life in April 2021.

Also see https://github.com/actions/virtual-environments/issues/4356 where Github announced that pre-installed Node.js version 10 will be removed from Github Actions:
>[All OSs] Node.js version 10 will be removed from the images on November, 15
>
>**The motivation for the changes**
>Node.js 16 has moved to Active LTS status and is ready for general use. According to our [Software and image guidelines](https://github.com/actions/virtual-environments/blob/main/docs/software-and-images-guidelines.md)
we support 3 latest LTS versions of Node.js, which are 12, 14 & 16 at the moment.

We're using Node.js version 10 in the `build-and-deploy` workflow. Although it still works because we install it with [`actions/setup-node`](https://github.com/actions/setup-node), it is not ideal to still use this version. BTW we're using an old version of `setup-node`, better upgrade if we still need to use it.

**Describe the solution you'd like**
Upgrade Node.js to a newer version.

**Describe alternatives you've considered**

**Additional context**

**Comment by sschiessl-bcp** [comment]
I agree, moving everything to Node16 would be amazing. Our electron build is a bit in the way of that, maybe we need to abandon it ...

**Comment by abitmore** [comment]
Done.
