### ISSUE TITLE
Part of the transaction history cannot be displayed

### ISSUE THREAD

**Issue by xiangxn** [bitshares/bitshares-ui#3408]
Part of the transaction history cannot be displayed
![image](https://user-images.githubusercontent.com/6350089/144533501-0c8c1af4-ddb7-46ba-a18f-6420458694a9.png)

**Comment by sschiessl-bcp** [comment]
mainnet / testnet?

**Comment by sschiessl-bcp** [comment]
There are three positions for this (plus locales), just as pointers :)

https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Blockchain/operations/index.js#L63
https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Blockchain/Transaction.jsx#L205
https://github.com/bitshares/bitshares-ui/blob/develop/app/components/Blockchain/OperationAnt.js#L55
