### ISSUE TITLE
[.25][happyconcepts] Remove 3rd party java script Bitkapital

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#341]
We decided earlier this year to not add the telegram widget because it means side loading scripts, a potential security leak.

but looks like bitkapital is doing exactly the same with their transfer service form

`<script type="text/javascript" src="//cdn-main1.123contactform.com/modules/custom-components/js/custom-components.js.minified.js?398aa2b"></script>`

https://github.com/bitshares/bitshares-ui/search?utf8=%E2%9C%93&q=123contactform&type=

so, delete?

**Comment by wmbutler** [comment]
I'm inclined to agree. @svk31 I'll place a small bounty on this but will retract it if you oppose. Seems to me that bitKapital should follow the same method as openledger for the time being. they can submit a PR for that.

**Comment by btsfav** [comment]
if you decide to delete: keep the tab and add "Currently under Maintenance" or something please.

**Comment by wmbutler** [comment]
Agreed.

**Comment by happyconcepts** [comment]
Agreed @btsfav @wmbutler
I will claim if ok.
Do you expect bK to come back with a PR soon?

**Comment by wmbutler** [comment]
bK?

**Comment by happyconcepts** [comment]
bitKapital.

**Comment by wmbutler** [comment]
Ah, I don't know what they will do. I have no contact with them.

**Comment by btsfav** [comment]
it's up to bitkapital to react / follow github if they want to issue a workaround, in my opinion.

**Comment by happyconcepts** [comment]
So just to be clear, removing the form will not provide a way for users to make a deposit, for the time being, right?

**Comment by btsfav** [comment]
@happyconcepts exactly, that's why I'd like to see a "under maintenance" message appearing under the tab

**Comment by happyconcepts** [comment]
"Onarım" in turkish - got it, thanks

**Comment by happyconcepts** [comment]
@wmbutler will you please check this [0.25] as I did not see it come through with #358 on 170914. Thanks!

**Comment by wmbutler** [comment]
Oops. Just covered this for you.
