### ISSUE TITLE
[1] Failed to broadcast the transaction: bitshares-crypto digest 

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#342]
We used to be able to know the exact error message when failed to broadcast a transaction from the GUI. But now:

![e9077481-2e9b-4cd0-813c-f828d2c958cf](https://user-images.githubusercontent.com/9946777/29884421-ba74a894-8db3-11e7-903b-fbb602313cd8.jpg)

How to reproduce: try to place an order in ICOWT/BTS market pair, if you're not whitelisted.

In the console we can still see the error message: 
```
Error: Assert Exception: is_authorized_asset( d, *_seller, *_receive_asset ): 
bitshares-crypto digest 73af88dc3dad432624af5f67f426be03be5b36ebe735a60f199ba1699d6ccf64 transaction 
```
But the first line is not shown in GUI.

I'm not sure if it's caused by a node API change. Also reported here: https://github.com/bitshares/bitshares-core/issues/382

**Comment by wmbutler** [comment]
Display an appropriate error message for this raw message:

"You are not approved to trade on this market"

I'm open to suggestions on the proper wording for this particular error.

**Comment by abitmore** [comment]
@wmbutler I'm not talking about a special case, but a common one. Some messages returned by the backend can be shown on UI directly, for example, insufficient balance. Sometimes there are detailed messages, sometimes with error codes. I admit that not all errors come with a message, but it can be fixed in backend.

**Comment by wmbutler** [comment]
Each Message needs a clear plain text message that the end user can understand. Additionally, the user should be able to look at the console for the more technical message.

**Comment by abitmore** [comment]
That's why there are error codes. We can have a table, no need to fix every single issue.

**Comment by wmbutler** [comment]
So, you'd like this to be displayed in a location visible to the end user?

```
Error: Assert Exception: is_authorized_asset( d, *_seller, *_receive_asset ):
```

**Comment by abitmore** [comment]
@wmbutler please check my messages in Telegram Dev Channel.

**Comment by abitmore** [comment]
>So, you'd like this to be displayed in a location visible to the end user?
Error: Assert Exception: is_authorized_asset( d, *_seller, *_receive_asset ):
And we can leave the crypto-digest message in the console?

Yes, something like this.
Actually in the node(backend), there is usually a message after the last `:`, so usually GUI need to display that message and do NOT display the expression before the `:`; sometimes there is also an error code, which can be translated and displayed in GUI; for this special error neither the message nor the code is there, so we should add a message and/or a code in the node (the backend).

**Comment by wmbutler** [comment]
Bill to review various errors, error codes and plaintext messages and work out a place to display these errors.

**Comment by svk31** [comment]
Are there error codes broadcast by bitshares-core? Can't remember seeing any.

I'm not sure what's changed here, as far as I can see the error coming from the API has been treated the same for ever, at least all of 2017, from TransactionConfirmActions.jsx:

```
// messages of length 1 are local exceptions (use the 1st line)
// longer messages are remote API exceptions (use the 2nd line)
let splitError = error.message.split( "\n" );
let message = splitError[splitError.length === 1 ? 0 : 1];
```

I can change it to just use the first part of the error, which is the assert exception.

**Comment by wmbutler** [comment]
@abitmore can you clarify for @svk31 ?
