### ISSUE TITLE
SHA256 incorrect on Mac OS Wallet build

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#343]
The sha256 for the recent Aug 29 release for Mac OS on https://bitshares.org/download/ is not correct.

If an automatic build system is implemented it needs to also update the shasums along with the builds.

**Comment by landry314** [comment]
Ah, I see, you wanted to make it a new post, bill.

> shasum -a 256   on the dmg for me yields:
6319c9477a8e0d36b6ab0a7295f74b7f871e52f8b9f2936ec964046c328fab41

**Comment by wmbutler** [comment]
Yeah, it's not a good idea to lump bugs onto a larger issue. It'll get lost.

**Comment by svk31** [comment]
That's my bad, looks like I reused an old sha256 sum in the release here, which got copied to bitshares.github.io. I did verify the sha sum @calvinfroedge gave for the binary he generated though.

**Comment by calvinfroedge** [comment]
[Newest build](https://drive.google.com/open?id=0BzvuEYutkmtdNkFaVUk1bGlNS2c)

```
BitShares-light_2.0.170830.dmg
sha1: 676d085cc336ed1cffbfd55d66daac9f2302d37f
sha256: 594d8dccd9f73b78b335b9ceb73f0bf687d91b11db6078e407eab3cdc086fde7
```
