### ISSUE TITLE
Legacy deposit/withdraw is broken on develop.bitshares.org

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3431]
**Describe the bug**

The page does not load. It shows 3 dots.

This is high priority because GDEX relies on it.

**To Reproduce**
1. Go to https://develop.bitshares.org
2. Click on the hamburg menu, then 'Legacy Deposit' or 'Legacy withdraw'
3. See error

**Expected behavior**
Page loads.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/147565579-bc9dfb30-06f5-435e-b94d-53063dbea786.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox / Chrome
 - Version: latest

**Additional context**
The same feature works fine on https://pr.bts.mobi which is on an older version of bitshares-ui, specifically, before the node and dependencies upgrade (https://github.com/bitshares/bitshares-ui/pull/3422).

**Comment by sschiessl-bcp** [comment]
https://github.com/bitshares/bitshares-ui/pull/3432

**Comment by sschiessl-bcp** [comment]
> This is mainly because webpack 5 no longer automatically packs process and buffer. The code location is:
> https://github.com/bitshares/bitshares-ui/blob/develop/app/components/DepositWithdraw/gdex/GdexGateway.jsx#L18
> 
> Among them, node-rsa requires these two libraries

**Comment by abitmore** [comment]
Assuming it got fixed by #3432, closing.
