### ISSUE TITLE
White screen https://develop.bitshares.org/#/account/committee-account/

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3434]
**Describe the bug**

https://develop.bitshares.org/#/account/committee-account/ now shows a blank page when clicked the `Activity` tab, or say, a white screen. Perhaps related to https://github.com/bitshares/bitshares-ui/pull/3422.

Error messages in console:
![image](https://user-images.githubusercontent.com/9946777/147755952-53319bcb-592c-448d-a076-0cb72b782f5f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox / Chrome
 - Version: latest

**Comment by xiangxn** [comment]
This is caused by a variable declaration and use problem, which has been dealt with
