### ISSUE TITLE
Can Not Add Node Anymore in Settings

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#344]
With the Aug 29 release I can no longer add a node in settings.

1) Go to Settings -> Access
2) Click the blue link "Add Node" to the right

For me it redirects to the home "b" tab and does nothing else.

**Comment by btsfav** [comment]
https://github.com/bitshares/bitshares-ui/issues/337 ...

**Comment by wmbutler** [comment]
We have a PR in for this already, waiting to be released.

**Comment by landry314** [comment]
oops, sorry.
