### ISSUE TITLE
 Report fraudulent cvnbts-swap wallet address to arbitrarily seize investors' money

### ISSUE THREAD

**Issue by thangpham1** [bitshares/bitshares-ui#3441]
I have a problem like this:
I joined Crypviser's CVCOIN (CVN) project since 2017 and invested more than 10000 usd to buy the amount of 24230 CVN. Recently, the project development team announced the conversion of CVN code to Token on the HECO chain at website https://cvnx.app/. I made a transfer of 24230 CVN from wallet address thang540128 to wallet cvnbts-swap as the guys behind the project seized and did not transfer Tokens on Heco chain for me. I took a picture of the entire Telegram chat. I suggest the Bitshare administration consider withdrawing and returning the total number of CVN 24229 from the wallet address cvnbts-swap illegally seized mine and returned it to my wallet address thang540128.

![scam3](https://user-images.githubusercontent.com/34408865/149868890-20d3928b-b5f3-45e1-b6de-c70db5d0498f.jpg)

![image](https://user-images.githubusercontent.com/34408865/149868843-df6463ab-99ab-442f-85ec-6a1d5b4512ed.png)

**Comment by abitmore** [comment]
I think you need to report to the police, but not here.
