### ISSUE TITLE
[.25][skenan] Asset page not using full screen width

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#345]
![image](https://user-images.githubusercontent.com/15861527/29901683-356b8576-8df1-11e7-9097-12d795789367.png)

When navigating to the 'Assets' page, there is a scrollbar mid way through the view on the right, and the full screen width is no longer used. This isn't the case with the rest of the client.

**Comment by skenan** [comment]
Can I take this one?

**Comment by wmbutler** [comment]
All yours.
