### ISSUE TITLE
A white screen appears on some asset display pages.

### ISSUE THREAD

**Issue by xiangxn** [bitshares/bitshares-ui#3474]
**Describe the bug**
A white screen appears on some asset display pages.

https://develop.bitshares.org/#/asset/CNY

**Comment by xiangxn** [comment]
Does not appear in English

**Comment by sschiessl-bcp** [comment]
Reproduces here too, looks like the Help file loading loops endlessly

**Comment by xiangxn** [comment]
This is because there is no "Asset.md" in the target language resulting in an infinite loop.

**Comment by xiangxn** [comment]
The above PR is invalid. I found that the entire help will be wrong. It seems to be caused by upgrading react, because this error will not appear when it is not build-hash.

**Comment by xiangxn** [comment]
Strangely, when I comment out the following 'console.warn' in the 'render()' function, the error doesn't reproduce anymore.

**Comment by sschiessl-bcp** [comment]
I have an idea what the issue is, but I can't reproduce the error
![image](https://user-images.githubusercontent.com/33128181/163782367-31ac4f1e-4ee7-4303-b0c8-40fac57ccc55.png)

Does it for you?

**Comment by abitmore** [comment]
@sschiessl-bcp sorry I don't understand.

**Comment by sschiessl-bcp** [comment]
What do I need to do to reproduce the white screen? I can't anymore

**Comment by sschiessl-bcp** [comment]
A nope, sorry. I can reproduce. It does happen on develop, but not on my local build ... so it seems like a minifying issue

**Comment by abitmore** [comment]
Or perhaps due to the hash `#`?

**Comment by abitmore** [comment]
I think it's a timing/racing issue.

When it loads normally:
![image](https://user-images.githubusercontent.com/9946777/164077885-b025b8ea-e15d-4aff-ab7d-720dc053d970.png)

When it loops infinitely (because `setState` re-triggers `render()`?):
![image](https://user-images.githubusercontent.com/9946777/164078128-b02d0a16-5f99-4cbb-9e20-11c405c7f1e6.png)

**Comment by abitmore** [comment]
I think it's a timing/racing issue.

When it loads normally:
![image](https://user-images.githubusercontent.com/9946777/164077885-b025b8ea-e15d-4aff-ab7d-720dc053d970.png)

When it loops infinitely (because `setState` re-triggers `render()`?):
![image](https://user-images.githubusercontent.com/9946777/164078128-b02d0a16-5f99-4cbb-9e20-11c405c7f1e6.png)

**Comment by abitmore** [comment]
The `za` in the stack is https://github.com/facebook/react/blob/v16.14.0/packages/react-reconciler/src/ReactFiberBeginWork.new.js#L852-L858
```
function updateClassComponent(
  current: Fiber | null,
  workInProgress: Fiber,
  Component: any,
  nextProps: any,
  renderLanes: Lanes,
)
```
and the `_i` it calls is https://github.com/facebook/react/blob/v16.14.0/packages/react-reconciler/src/ReactFiberBeginWork.new.js#L902
```
  mountClassInstance(workInProgress, Component, nextProps, renderLanes);
```
`Ra` is https://github.com/facebook/react/blob/v16.14.0/packages/react-reconciler/src/ReactFiberBeginWork.new.js#L921-L928
```
  const nextUnitOfWork = finishClassComponent(
    current,
    workInProgress,
    Component,
    shouldUpdate,
    hasContext,
    renderLanes,
  );
  ...
  return nextUnitOfWork;
```
Not sure if it helps.

**Comment by abitmore** [comment]
Found the reason.

`console.warn()` is overridden in `AppInit.jsx`: https://github.com/bitshares/bitshares-ui/blob/3a8beceee978522695076d81811d75411c6c5b1c/app/AppInit.jsx#L139-L141

`saveLog()` calls `saveExtendedLog()` which then calls `setState()` : https://github.com/bitshares/bitshares-ui/blob/3a8beceee978522695076d81811d75411c6c5b1c/app/AppInit.jsx#L92

When `console.warn()` is called in `render()`, the `setState()` call will trigger another `render()` call, and it leads to infinite recursion, so the page will not complete rendering and we finally get a blank page.

The tricky thing is, if we simply wrap the `setState()` call with a `setTimeout()` (E.G. https://github.com/abitmore/bitshares-ui/pull/73/commits/d02dafc6df1016b8a75f0e7c81521990a2f502ce), although `render()` returns fast and the page shows soon, the delayed `setState()` call will still trigger another `render()`, and it leads to an infinite loop, and the page becomes unresponsive quickly.

I don't understand why a `setState()` call in the `AppInit` class triggers `render()` of the `Asset` class.

**Comment by abitmore** [comment]
Note that there is a check in `saveExtendedLog()`: https://github.com/bitshares/bitshares-ui/blob/3a8beceee978522695076d81811d75411c6c5b1c/app/AppInit.jsx#L89

If the new log entry is the same as the last one, it will be skipped, thus `setState()` will not be called. This is why commenting out 2 `console.warn()` calls "fixes" the issue (E.G. https://github.com/abitmore/bitshares-ui/commit/efdf508dbbe2407059e0d1ce3b60ad8d9b1947e7). This is also why #3495 "fixes" the issue. This is also why the same page in English language works. When opening the page in a non-English language, `console.warn()` gets called 3 times with different messages, so infinite recursion / loop occurs.

**Comment by sschiessl-bcp** [comment]
I have not received a single report since introducing that feature, so I will deactivate it

**Comment by sschiessl-bcp** [comment]
I still can't reproduce the error, but please try again https://github.com/bitshares/bitshares-ui/commit/9c19369116e8b98be44cfe372efdf4f28a034a49

**Comment by abitmore** [comment]
> I still can't reproduce the error, but please try again [9c19369](https://github.com/bitshares/bitshares-ui/commit/9c19369116e8b98be44cfe372efdf4f28a034a49)

It seems it's fixed. Thanks. @xiangxn can you please recheck?

**Comment by xiangxn** [comment]
OK, I'll pull it out and test it locally.

**Comment by xiangxn** [comment]
After testing, the problem has indeed been fixed. Can close PR #3495 now
