### ISSUE TITLE
Replace highcharts with d3

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#348]
Since react-stockcharts uses d3 we now include both highcharts and d3. Using only d3 would shave a significant amount off the total package size.

**Comment by wmbutler** [comment]
Awesome. Added to current Sprint.

**Comment by svk31** [comment]
This turned out to be far more work than expected, since react-stockcharts doesn't actually use d3 for plotting but instead uses canvas and svgs. I suggest we drop it until such time as react-stockcharts actually implements depth charts.

**Comment by wmbutler** [comment]
OK, so are we still planning to bring react-stockcharts up to a current version?

**Comment by svk31** [comment]
Yes but it's already at the latest stable release, next version up is still in beta.

**Comment by wmbutler** [comment]
OK, closing this and the upgrade ticket.
