### ISSUE TITLE
Order cancellation fee error

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3486]
**Describe the bug**

Why the fee to be paid is coming up in "bullion" and not BTS?

**To Reproduce**
"Just cancelling my orders and re-doing them because their about to expire, It's not doing it to all of them but more than just 1"

**Expected behavior**
Fee in BTS.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/161428576-7309079c-21ed-4647-8861-8d72bdf07ea4.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
"bug looks very random, had to cancel a lot of orders, before the fee asset switched"

**Comment by abitmore** [comment]
"bug looks very random, had to cancel a lot of orders, before the fee asset switched"

**Comment by sschiessl-bcp** [comment]
Reproducable?

**Comment by xiangxn** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/6350089/161898132-bc777205-c471-4653-8ff8-c8df55d36942.png">
I have not been able to reproduce the issue either, it may be related to the data of a single account.

**Comment by abitmore** [comment]
"When i want to cancel 1 order,it's not working,no chance of canceling.But when i select 2 orders to get canceled in the same time,then it works good."

**Comment by abitmore** [comment]
It seems to happen on the market page.

**Comment by xiangxn** [comment]
see: https://github.com/bitshares/bitshares-ui/blob/develop/app/lib/common/account_utils.js#L92

This doesn't seem to be a bug, according to the logic of the current code, the cancellation fee is not defaulted to BTS

**Comment by abitmore** [comment]
The default cancellation fee asset should be the one configured in settings by the user, which is not always BTS. If the account has no sufficient balance of that asset to pay the fee, or the fee pool of that asset is not usable, then use the fallback logic.

**Comment by xiangxn** [comment]
I have dealt with this issue, if you have time you can review and merge.
@sschiessl-bcp @abitmore

**Comment by abitmore** [comment]
Reopening for review.

**Comment by sschiessl-bcp** [comment]
The fix helps in a case where the user sees that he is able to pay the fee, but actually can't, because it's too many orders.
