### ISSUE TITLE
Inaccurate floating point numbers used in credit offers

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3487]
**Describe the bug**

Certain credit offers cannot be accepted due to the use of inaccurate floating point numbers to calculate collateral amounts.

**To Reproduce**
1. Go to https://develop.bitshares.org/#/lending/p2p , page 2
2. Click on '$' icon of the `1.21.79` offer
3. Input amount `100` (`XBTSX.HIVE`), see the collateral amount is `5,999.99881 BTS`, which is insufficient because the required collateral ratio is `1 HIVE / 60 BTS`
4. Submit, see error

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/162443736-9880d5f1-bc78-4fd7-9d10-c82990f04d2f.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: Latest

**Additional context**

**Comment by xiangxn** [comment]
I have dealt with this issue, if you have time you can review and merge.
@sschiessl-bcp @abitmore

**Comment by sschiessl-bcp** [comment]
Please check again

**Comment by abitmore** [comment]
![image](https://user-images.githubusercontent.com/9946777/163692834-a428c967-81ec-444c-b8d6-50c5a98b6b1b.png)

**Comment by abitmore** [comment]
I think it's not fixed.

**Comment by xiangxn** [comment]
I replaced the division with multiplication, the precision should no longer affect
@abitmore

**Comment by sschiessl-bcp** [comment]
@xiangxn please check the calculation and if accurate now we can close

**Comment by abitmore** [comment]
Offer 1.21.67, this is fine:
![image](https://user-images.githubusercontent.com/9946777/163808785-bee20441-617a-4479-99be-e1b9d65a3ed7.png)

but too much collateral here:
![image](https://user-images.githubusercontent.com/9946777/163808690-e2a153de-b8da-4587-8f05-f749538d74fb.png)

**Comment by xiangxn** [comment]
Sorry, I forgot to clean up the original `ceil` function

**Comment by xiangxn** [comment]
I've fixed this and tested it. you can merge.

@sschiessl-bcp @abitmore

**Comment by abitmore** [comment]
I think `ceil` is still needed somewhere.

For example, for offer `1.21.3`, if to borrow `1 BTS`, the collateral `0.2381 CNY` is sufficient,
![image](https://user-images.githubusercontent.com/9946777/164984574-81f69999-fa9e-41c2-9add-786e79fd2a74.png)

But if to borrow `0.1 BTS`, the collateral `0.0238 CNY` is insufficient:
![image](https://user-images.githubusercontent.com/9946777/164984613-e4b9e7ad-dc4d-4295-8cd5-ce1c1d825377.png)

By the way, the amount of fee (`0.86869 BTS`) is wrong. It should be `1 BTS`.

**Comment by xiangxn** [comment]
I have reprocessed. @abitmore 

The Fee issue, I checked it, this is because the partial op number returned by the api did not cause the front-end read to fail, which requires opening a new `issue`

**Comment by sschiessl-bcp** [comment]
Checked the cases above, looks good. 

I guess the one below is not an issue, still there is a rounding error with big numbers. Funny enough, adding another 0 rounds properly again
![image](https://user-images.githubusercontent.com/33128181/165515251-5a4c18a9-123c-4db0-9795-eeb35adfb088.png)
