### ISSUE TITLE
Credit offer repayment period "No limit"

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3490]
**Describe the bug**

When the repayment period of an offer is not within the predefined set of UI, it shows as "No limit".

**To Reproduce**
1. Go to https://develop.bitshares.org/#/lending/p2p
2. Scroll down to '1.21.67'
3. See error

**Expected behavior**
Correct values on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/162613831-b38c7128-ce93-45de-8900-092a3299ea84.png)

**Desktop (please complete the following information):**
/

**Additional context**

**Comment by xiangxn** [comment]
I have dealt with this issue, if you have time you can review and merge.
@sschiessl-bcp @abitmore

**Comment by abitmore** [comment]
Better add some white spaces. BTW "1Hours" and "1Days" look strange, they should be "1 hour" or "1 day". Actually, do we have some standard i18n library to use?

![image](https://user-images.githubusercontent.com/9946777/163692875-c605ce8f-5e18-4835-bf2a-33caea24c680.png)

**Comment by xiangxn** [comment]
I have reformatted it.

@abitmore
