### ISSUE TITLE
Missing commit hash in generated commit message for web-wallet deployment

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3502]
**Description**

Starting from https://github.com/bitshares/bitshares-ui/commit/fd99821c3c20e64631d165d6989a35b444fb14bf (after https://github.com/bitshares/bitshares-ui/commit/c19b2d9afc20c1f53e771d5a8d3fcdef6a88455f), the commit hash of the source code is no longer in the generated commit messages for web-wallet deployment.

This is caused by the separation of jobs - there isn't a `checkout` step in the 2nd job, so unable to get the commit hash.

I have a fix in my fork repository: https://github.com/abitmore/bitshares-ui/commit/9681602acf01770d8cb956cb273308da425fa0e1 .

**To Reproduce**
1. Go to https://github.com/bitshares/develop.bitshares.org/commits/master
2. Scroll down

**Expected behavior**
The same behavior as before.

**Screenshots**
![image](https://user-images.githubusercontent.com/9946777/164026004-cd157b91-a7df-4f39-8688-a3450685662b.png)

**Additional context**

**Comment by sschiessl-bcp** [comment]
works now

**Comment by abitmore** [comment]
Fixed by @sschiessl-bcp via https://github.com/bitshares/bitshares-ui/commit/0995347eece74ea72a29826ad477efa8aa71d96c and earlier commits.
