### ISSUE TITLE
[2] Failed to Sync with API Server UI

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#351]
This page should have the same User Experience as the Settings page for server selection.

![screen shot 2017-08-31 at 8 10 59 am](https://user-images.githubusercontent.com/1254810/29924954-5ec9191e-8e24-11e7-83fe-61f950cab21e.png)

That means incorporating the list and selectors with the same view as shown below:

![screen shot 2017-08-31 at 8 13 31 am](https://user-images.githubusercontent.com/1254810/29924935-4f6db632-8e24-11e7-9eeb-650f3ad2cf86.png)

**Comment by pureland** [comment]
check you local time

**Comment by wmbutler** [comment]
@pureland You need to read the issue more carefully. This is a UI/UX issue, not a time issue.

**Comment by M-Zeeshan-Haider** [comment]
did you recolved this?  https://github.com/bitshares/bitshares-core/issues/1519
