### ISSUE TITLE
Charting Tools: Feature Request: Extend Tools to future

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#352]
Extension of the chart (and its trendlines) into future time is standard chart behavior on "pro" systems like Bloomberg, and I must admit some love for tradingview charts and how they do this:
![kraken-extension-ex](https://user-images.githubusercontent.com/14145836/29945323-94aa030a-8e55-11e7-925f-b36da9b5b3ed.png)

 and here is the link if you want to see for yourself: [TradingView:BTC:USD](https://www.tradingview.com/chart/?symbol=KRAKEN:XBTUSD)

On Bitshares the trendlines drawn on the chart by the user all stop at the current date/time as shown in the image. I forgot to draw the fib retrace but it stops too. The teal extension on the image was hand drawn by me, and it's getting to be laborious to do this when updating charts.

![bts-extension-ex](https://user-images.githubusercontent.com/14145836/29945527-513ebf9c-8e56-11e7-8e2b-9d1e3f0d6213.png)

While I could probably "hack" it with an arbitrary addition like 30 days into the future...I feel it would be more solid and more beneficial to extend the lines without some arbitrary limit if possible. 

One additional aspect to think about: future new Tools (if any) would then be expected to exhibit this "alltime" behavior unless the tool depends on price data. 

In this context I think it's not too much more to ask for the future dates to be populated on the chart too, like tradingview does it.

**Comment by wmbutler** [comment]
Moving to #361
