### ISSUE TITLE
Adding liquidity pool feature request

### ISSUE THREAD

**Issue by xiao93** [bitshares/bitshares-ui#3546]
https://wallet.bitshares.org/#/pools

As a user, when adding a liquidity pool, I hope that when A is determined, B will also be determined.

<img width="530" alt="image" src="https://user-images.githubusercontent.com/42384581/188765776-6aa436a6-c89d-44c4-b035-0c88e287f32a.png">

**Comment by sschiessl-bcp** [comment]
This is convenient when you want to follow the price suggested by the pool. Sometimes you might not want to do that.

I suggest you add a lock symbol that can be unlocked by click. If locked, you calculate price when entering one asset, if unocked, you dont
