### ISSUE TITLE
Decimal error when collateral bidding

### ISSUE THREAD

**Issue by iamredbar** [bitshares/bitshares-ui#3549]
**Describe the bug**
There is a decimal error when bidding on collateral. It is present in main branch as well as develop. Versions are below.

**To Reproduce**
1. Go to asset HONEST.ETH1
2. Traverse down to bid on collateral
3. Enter values in screenshots

**Expected behavior**
Correct values to be present.

**Screenshots**
![Screenshot 2022-09-11 155042](https://user-images.githubusercontent.com/16945982/189548781-2d2c872e-6280-46d4-b1b4-fad5af031aba.png)
![dev](https://user-images.githubusercontent.com/16945982/189548785-d127dbd4-5640-47db-8732-700bc56d955e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Chrome, Version 105.0.5195.102 (Official Build) (64-bit)
 - Prod UI: 220701 (wallet.bitshares.org)
 - Dev UI: 24c9e71 (develop.bitshares.org)

**Additional context**
Bug currently breaks collateral bidding when present.

**Comment by iamredbar** [comment]
Similar issue to #3317, if not the same.

**Comment by abitmore** [comment]
I think #3317 is not the same issue, but #3545 is.
