### ISSUE TITLE
Pool collateral between shorts?

### ISSUE THREAD

**Issue by brekyrself** [bitshares/bitshares-ui#356]
Is it possible within the BitShares framework to automate collateral levels between different shorts?  This would help the casual shorter with a longer term interest that would not have to constantly check the collateral ratio with such a volatile market.

1.  Set a range to keep a short (ie between 2.15x and 2.5x). Once it goes below 2.15x it can draw from a pool or once it goes above the 2.5x it will return to the pool?
2.  Have the ability to prioritize which short positions draw from the pool when it goes below the lower set threshold.

If this were possible I believe many people would short more assets, creating much needed liquidity.

**Comment by wmbutler** [comment]
Wondering if this is more of a core proposal since the UI will have nothing to do with automating this, other than telling the backend what to do initially.

**Comment by svk31** [comment]
It is indeed a core proposal, it also is a huge change to how collateral is treated so it would be a massive change requiring a hardfork.
