### ISSUE TITLE
Credit offer loan window bug

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#3565]
**Describe the bug**
When you click on the available quantity, the quantity field is filled out, however the collateral and estimated fee sections are not updated to reflect this input.

**To Reproduce**
Login, click on another user's loan (dollar button) which has available loanable assets, click the available quantity like in the gif, see fields not updated to reflect change in input field.

**Expected behavior**
When I click on the available assets to fill the field with all assets, update the calculations to reflect this input action.

**Screenshots**

![bug](https://user-images.githubusercontent.com/15861527/193292939-776c918b-4b99-4f21-855f-2011b7e126e9.gif)

**Desktop (please complete the following information):**
Windows, firefox.

**Comment by ihorml** [comment]
@sschiessl-bcp please close this one
