### ISSUE TITLE
Credit offer - cannot edit existing offer

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#3567]
**Describe the bug**
I have offered all of one asset I own in a credit offer.

When I try to edit the credit offer, I'm unable to click submit because I have 0 of the asset I wish to lend (as it's all in this credit offer I'm trying to edit).

I am thus unable to edit a credit offer in the web wallet.

**To Reproduce**
Create a credit offer, offer all of an asset in your balance (1 of 1 for example) for loan.

Go to your created credit offer in your portfolio, click the edit button.

Try to make any changes, you cannot.

The available balance is highlighted red, indicating it's failing the form validation, despite not wanting to change the offered asset quantity but rather the expiration date.

**Expected behavior**
I can edit a credit offer I have created.

**Screenshots**
![image](https://user-images.githubusercontent.com/15861527/193297548-eb0e8d86-5751-495e-bc34-414afee8198a.png)

**Desktop (please complete the following information):**
web wallet, firefox

**Additional context**
To edit the credit offer I have to delete it and create it from scratch.

**Comment by ihorml** [comment]
@abitmore hey there. 

I've fixed the issue on a front-end side but looks like the same bug applies to blockchain logic. 

I have already existed offer and I changed a whitelisted account only:

<img width="517" alt="Screenshot 2022-11-21 at 14 49 18" src="https://user-images.githubusercontent.com/7770343/203059455-f59a6323-c5ea-4716-858e-81122d25e7a3.png">

When I tries to update the offer I see the following error:

<img width="519" alt="Screenshot 2022-11-21 at 14 48 34" src="https://user-images.githubusercontent.com/7770343/203059326-907f6700-c4e8-4d09-8261-24d2a4dd33e6.png">

Please redirect me in the right direction if I get the logic of the credit offer update in the wrong way. But from my user perspective, if I updates the whitelisted account and didn't touch the amount of offer - it should be updated fine.

**Comment by ihorml** [comment]
@abitmore okay, what I see from the logic is the field "amount" is used like an "amount to change" instead of "total amount" (what User expects to see)

In this case, the UI has a bad UX and I'll change the title to a proper one to avoid misunderstanding.

**Comment by abitmore** [comment]
> @abitmore okay, what I see from the logic is the field "amount" is used like an "amount to change" instead of "total amount" (what User expects to see)
> 
> In this case, the UI has a bad UX and I'll change the title to a proper one to avoid misunderstanding.

I think a better UX is that showing the new amount (and probably the change too) and submitting the change to the blockchain, just like the UX about borrowing bitUSD. Thanks.

**Comment by ihorml** [comment]
@abitmore hm, good point. I'll show a new amount field and send to the server a delta of current/new to update it in a proper way. Thanks!
