### ISSUE TITLE
credit offer uncaught error

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#3575]
**Describe the bug**
`Uncaught Error: Base and Quote assets must be different`

You can attempt to create a credit offer where the lending and collateral assets are identical, only an uncaught error in console is shown.

**To Reproduce**
Go to the credit offer creation page
Select 1 BTS as lending asset
Select 1 BTS as backing collateral
Enter valid details for other fields
Click select
Open console for above error

**Expected behavior**
Submit button should be disabled until the invalid form fields are fixed by the user.

**Screenshots**

**Desktop (please complete the following information):**
https://wallet.bitshares.org

**Comment by ihorml** [comment]
@sschiessl-bcp you can close this issue

<img width="513" alt="Screenshot 2022-12-01 at 14 08 57" src="https://user-images.githubusercontent.com/7770343/205049202-297d8e03-95ca-47c6-bcf2-90732ca28122.png">
