### ISSUE TITLE
[.5][happyconcepts] Display account name in lower case letters

### ISSUE THREAD

**Issue by btswolf** [bitshares/bitshares-ui#358]
To avoid confusion with the account names I suggest to display the account name with lower case letters consistently in the whole GUI.
[![image](https://user-images.githubusercontent.com/11035520/30002228-4c3f270c-90a4-11e7-9952-0045da8b69aa.png)](https://user-images.githubusercontent.com/11035520/30002228-4c3f270c-90a4-11e7-9952-0045da8b69aa.png)

**Comment by iPerky** [comment]
The standard reference throughout the GUI:

all "ASSETS" should be "UPPER CASE"
all "user names" should be "lower case"

**Comment by btsfav** [comment]
merge with https://github.com/bitshares/bitshares-ui/issues/187 please @wmbutler

**Comment by happyconcepts** [comment]
@wmbutler @btsfav I can fix the account names for the current sprint if you like; however the relation to #187 eludes me.

Is my understanding correct that a recipient's Bitshares address (user input) is to be lowercase in the form field on the SEND page too?

**Comment by wmbutler** [comment]
I like the consistency of all assets UC and all uernames LC. Does commit 6b65bb1 cover thi throughout the entire wallet?

**Comment by happyconcepts** [comment]
More testing is always welcomed as I don't have much experience writing unit tests. I'm learning Travis but not at production level yet.

**Comment by happyconcepts** [comment]
FWIW the uppercase transform was being applied to everything in the header; I don't see a use case for capitalizing the account names in any other place in the current GUI.

**Comment by wmbutler** [comment]
It's not a matter of user case really, it's just a consistency thing.

**Comment by happyconcepts** [comment]
Well in the meantime, if we are sure that React's use of the variable declaration
  `account_display_name` is enforced throughout all the jsx files ... then I can search the codebase:

[https://github.com/bitshares/bitshares-ui/search?utf8=%E2%9C%93&q=account_display_name&type=](https://github.com/bitshares/bitshares-ui/search?utf8=%E2%9C%93&q=account_display_name&type=)

Is there a 2.0 or 2.x style/implementation guide I can refer to?

**Comment by wmbutler** [comment]
@svk31 may have an answer for you.

**Comment by happyconcepts** [comment]
Sure, very happy to help with these smaller issues for 0914.

**Comment by landry314** [comment]
My username seems so small next to all those ALL CAPS words... I think it looks a bit strange.

**Comment by landry314** [comment]
If you click on the username tab on the upper right while multiple accounts are starred then a menu pulls down with the usernames still in ALL CAPS. We are trying to be consistent throughout the GUI, right? Then should we change it here too?

**Comment by landry314** [comment]
Is commenting in a closed issue thread a bad idea? It seems to get lost more often. I commented here because it is directly related to this issue. There are still account names in uppercase letters...

@happyconcepts, do you want to handle this?

**Comment by happyconcepts** [comment]
I was going to make that change before I was fuzzed, sidelined and
forgotten. You fuzzed me here from my very first post @landry314
@landryracoon @whatevernewnameyoumaketoday so this is great for you to come
stalk all my PRs too.

**Comment by landry314** [comment]
I am just trying to help the program, not insulting or stalking you. I noticed there is another place where this comes up so I posted it but it seemed to go unnoticed. I think posting in closed issues doesn't work very well so I tagged you because you were assigned this before.

**Comment by happyconcepts** [comment]
PR is submitted.
