### ISSUE TITLE
GitHub Actions: Deprecating `save-state` and `set-output` commands

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#3585]
As described in https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/, the `save-state` and `set-out` commands will be deprecated.
> ... We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using `save-state` or `set-output` commands via stdout will fail with an error.
> ...
> Action and workflow authors who are using `save-state` or `set-output` via stdout should update to use the new [environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files).

We are using the `set-output` command here: https://github.com/bitshares/bitshares-ui/blob/5e2af49279c3f73b3053a307a3569107dcb0450f/.github/workflows/build-release-binaries.yml#L40-L42

so we need to update it.

**Comment by grctest** [comment]
```
echo "dmghash=$(sha256sum build/binaries/*.dmg|cut -c-64)" >> $GITHUB_OUTPUT
echo "debhash=$(sha256sum build/binaries/*.deb|cut -c-64)" >> $GITHUB_OUTPUT
echo "exehash=$(sha256sum build/binaries/*.exe|cut -c-64)" >> $GITHUB_OUTPUT
```

To something like the above?
