### ISSUE TITLE
Display BTS fuel prominently

### ISSUE THREAD

**Issue by btswolf** [bitshares/bitshares-ui#359]
BTS is the fuel of all transactions and operations but many users do not know this fact and as long as the fee pools are properly maintained there is no need to have BTS.  But it will happen more often that fee pools are empty and people will need BTS as fuel to use the affected tokens. 

Therefor I suggest to add an indicator in the GUI at a prominent place to show the BTS fuel status.
1. If each user would hold some BTS that would avoid confusion if fee pools are not filled.
2. It would increase demand for BTS.
3. The user might feel better if the GUI does honor visually if she own some BTS.

Here is an example screen of how this could be displayed visually.
[![image](https://user-images.githubusercontent.com/11035520/30003890-4efbca38-90c5-11e7-894b-4fa7579d10d7.png)](https://user-images.githubusercontent.com/11035520/30003890-4efbca38-90c5-11e7-894b-4fa7579d10d7.png)

Mouse-over text: 
Your remaining amount of `<amount`> BTS is good for <`amount/fee`> standard transactions. Keep in mind that you need BTS for many of the operations in BitShares such as sending funds or trading. If your BTS amount is too low you may have to deposit more BTS.

**Comment by wmbutler** [comment]
Let's do this:

- [ ] If BTS <=1, display `(purchase BTS)` next to the symbol on the Portfolio View.
- [ ] Continuously pulse the Buy icon in green

<img width="1221" alt="screen shot 2018-01-14 at 8 56 02 pm" src="https://user-images.githubusercontent.com/1254810/34925219-901d95da-f96d-11e7-8250-cc0a8cebda9b.png">

**Comment by AustinAmoruso** [comment]
I'll take this one

**Comment by AustinAmoruso** [comment]
Does this ticket include making sure that BTS is always displayed or only when the user makes BTS display?

**Comment by wmbutler** [comment]
BTS is always displayed in the portfolio. This issue refers to the case where the user has < 1 BTS and is designed to encourage the user to buy more.

**Comment by AustinAmoruso** [comment]
@wmbutler I think this ticket is done then it got merged in, unless I'm missing something

**Comment by wmbutler** [comment]
@AustinAmoruso please either work this or give it up to someone else.

**Comment by AustinAmoruso** [comment]
@wmbutler what is missing from this? I thought it was just making the icon flash when it was lower than 1 bts?

**Comment by wmbutler** [comment]
Let's do this:

- [ ] If BTS <=1, display `(purchase BTS)` next to the symbol on the Portfolio View.
- [ ] Continuously pulse the Buy icon ($) in green. 1 pulse per second.

<img width="1221" alt="screen shot 2018-01-14 at 8 56 02 pm" src="https://user-images.githubusercontent.com/1254810/34925219-901d95da-f96d-11e7-8250-cc0a8cebda9b.png">

**Comment by AustinAmoruso** [comment]
I'm going to release this one as I don't have time and am unclear as to what isn't complete on it.

**Comment by wmbutler** [comment]
Closing this. It has gotten zero traction for 8 months.
