### ISSUE TITLE
Draggable widgets in UI

### ISSUE THREAD

**Issue by malcolmjmr** [bitshares/bitshares-ui#360]
UI should be as customizable as possible. We shouldn't assume how a user wants their dashboard or trading interface formatted. 

I think that Bitmex.com has one of the best UI's for trading. A huge part of its appeal are the draggable and resizable widgets which allow users to define their own trading interface and workflow. 

I'd like to see the UI be even more modular and amendable. Users should be able to define there own tabs which can be comprised of an arbitrary number of widgets. While there would be the same default tabs Dashboard, Account, Send, Exchange, Deposit/Withdrawal, users could add to or delete these from their wallet preferences. 

Tabs could then incorporate widgets that have data and functionality that is currently buried within different pages of the current site. Ideally a user would only have one customized tab in which they can expose all of the data and functionality that they actually want. 

Using this widget model could also improve the speed of development if building out widgets is made easy enough for inexperienced developers.

Not sure how feasibly this would be but [Gridstack.js](https://github.com/troolee/gridstack.js) is mobile friendly js library for draggable and resizable widgets that seems like it could be easily integrated.

Would like to know your thoughts @wmbutler , @svk31

**Comment by wmbutler** [comment]
Many steps to go through before this, but this is too general to generate an actionable user story.

**Comment by malcolmjmr** [comment]
I guess I'm really just wondering how much work it would take to render the app components as gridstack elements that can easily be added or deleted by the user, like [this](http://troolee.github.io/gridstack.js/demo/knockout2.html).

I'd like to be able to resize the price chart window and move elements that I don't need out of focus or delete them all together.

**Comment by wmbutler** [comment]
Closing this. Too broad.
