### ISSUE TITLE
loading gray screen lacks info

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [bitshares/bitshares-ui#365]
friend was at gray loading screen for long time without info on what it's doing or steps to fix it

This is screen shot of it happening before he gave up:

![image](https://user-images.githubusercontent.com/22536095/30115671-64b574f2-92e9-11e7-9832-71b7d6696a38.png)

It's likely a bad/slow node issue, but he didn't see API screen with node selection or what it's doing

1) Needs info on what it's doing so he's more willing to wait if just slow
2) Needs steps to fix it if it doesn't load like link to node selection

ubuntu 14 - chrome

Thanks

**Comment by wmbutler** [comment]
I would be nice to know what's going on. Curious to know what we have at our disposal. 

- Connecting To Node: node.bitshares.org

**Comment by wmbutler** [comment]
Maybe switch to an animated spinner like this instead as well?

![screen shot 2017-09-21 at 12 05 14 am](https://user-images.githubusercontent.com/1254810/30679671-a4d54ba2-9e60-11e7-955f-50e5b3441c14.png)

**Comment by wmbutler** [comment]
![screen shot 2017-09-21 at 12 10 01 am](https://user-images.githubusercontent.com/1254810/30679754-3cb31724-9e61-11e7-85de-782c5e260426.png)

**Comment by svk31** [comment]
This is more difficult than you think, because what happens is we're waiting for the router to start and at that point nothing is being rendered..

**Comment by wmbutler** [comment]
@calvinfroedge since you claimed this, maybe you have some thoughts. I'm pretty sure we have console logs so maybe you have some ideas on how we can get a spinner and some text related to those logs in place.

**Comment by svk31** [comment]
This issue was affected by https://github.com/bitshares/bitshares-ui/commit/8795eb0b479fa9eaa7ed3dabe9dd8e03e45552c4

The app init chain has been improved, but it means the white screen might stay a little longer (when checking latencies or connecting to a slow node), but on the other hand you no longer have this gray loading screen as shown in the OP.

**Comment by calvinfroedge** [comment]
I think the changes discussed by @svk31 make this issue irrelevant
