### ISSUE TITLE
Add replace order feature

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#367]
The ability to replace an order in one click, instead of having to cancel open order and then wait to submit a new one. Similar to what is implemented in cryptowat.ch

**Comment by fractalnode** [comment]
something like edit, but in two steps, remove and place a new order

**Comment by landry314** [comment]
Wait, isn't the bitshares blockchain capable of canceling an order and replacing in one command? Isn't this a feature of the blockchain which isn't implemented in the GUI yet?

**Comment by svk31** [comment]
It is indeed capable of doing so yes, but the GUI does not include that feature in many places. The GUI uses two operations in one transaction for the short operation for prediction markets for example.
