### ISSUE TITLE
Skip order confirmation feature

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#368]
And an option to disable the confirm order box (with configurable parameters, so it still asks to confirm when you're buying/selling significantly higher/lower than market rate)

**Comment by wmbutler** [comment]
I think this is a bad idea.

**Comment by landry314** [comment]
I agree, when moving money, a confirmation is always important.

**Comment by tximiss** [comment]
For the sake of being an agile trading platform it could be good a setting for enable/disable order confirmations.
Name it "Pro Trader" :-)

**Comment by landry314** [comment]
Yeah, I changed my mind, I think an advanced setting would be good, maybe with a warning.

**Comment by tximiss** [comment]
From https://t.me/Bitshares_Traders we clearly see two profiles of users. One is a trading professional who is waiting for more advanced charts (TradingView style) and don't need a periodic popup for every operation he does. The other profile are the users we want to reach, for whom all the trading features looks like a spacecraft console.

**Comment by btsfav** [comment]
This wallet is a reference client, it's supposed to showcase all features. 

you want a tailored wallet, which can be done by 3rd party services/companies or you.
