### ISSUE TITLE
Dynamically select API server.

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#369]
We should be able to dynamically select which API to use based on ping / lowest latency etc, if "auto" select is provided, and manually to fixed server (as it is now) if not auto. Electrum does it, it isn't an overly complicated algorithm.

**Comment by svk31** [comment]
How does this differ from the current implementation? The current implementation works as follows:

1. If you choose auto, it will ping all nodes and sort them according to latency, and connect to the lowest latency node
2. If you choose a specific node, it will try to connect to that node but fallback to other nodes (again sorted by latency) if your selected node doesn't work

**Comment by wmbutler** [comment]
I agree that this feature already exists.
