### ISSUE TITLE
My funds in Cryptobridge

### ISSUE THREAD

**Issue by Khalidarab** [bitshares/bitshares-ui#3706]
I just want someone to help me withdraw my funds in Cryptobridge exchange, please!
When I log in bitshares portfolio I can see my funds there...
I tried many times to send my funds to another wallet but the address box became blanc again.

Please anyone find me a solution...
Thank you 

Khaled

**Comment by abitmore** [comment]
CryptoBridge closed 4 years ago. I think you've got a notification in the wallet if you own their assets.
![image](https://github.com/bitshares/bitshares-ui/assets/9946777/b3897582-d081-4a93-8bc8-b66e1f46a8fa)
