### ISSUE TITLE
[.5][ariesjia] Change Word and Calculation from "BALANCE" to "VALUE" on Top Bar

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#374]
Ok, here is my argument:

1) Word: Under the Account tab you have "Balances". Balances are just which assets you hold which exclude assets in open orders and debt. The calculation on the top bar called "BALANCE" DOES include open orders and debt in the calculation. Using the same word is confusing to many people. People might think that they are holding BTS if the Preferred Unit is BTS and it says "BALANCE: XXX BTS" on the top bar even though it is an approximate calculation of the equivalent VALUE in BTS. Why not change the word to "VALUE"?

2) Calculation: In the "b" tab on the upper left, if you scroll down to Accounts and look on the rightmost column you see it is called "TOTAL VALUE". This is a calculation of balances, orders, and debt and it is appropriately referred to as the account value. This calculation SHOULD be the SAME as the calculation on the upper right but it is not because it lacks a bug as discussed in issue #206. So, why not clone the calculation for "TOTAL VALUE" into the top bar to fix issue #206. They are trying to do the same thing while one is failing and the other is succeeding. I think the calculation is trying to sum the values in the the "Equivalent Value" column in ACCOUNT including open orders but it is failing when all values in Balances are Unknown (because they are too small?). Instead of using this calculation, let's use the one that already works.

This is so simple, change the calculation on the top bar to the same one used in b -> Accounts -> Total Value and rename it to VALUE. This is so easy and makes the program cleaner and clearer.

**Comment by wmbutler** [comment]
Let's use the label "ACCOUNT VALUE" in the top and under the Overview.

![screen shot 2017-09-09 at 7 06 56 pm](https://user-images.githubusercontent.com/1254810/30245020-2e437152-9592-11e7-97d0-1f95045630b4.png)

![screen shot 2017-09-09 at 7 07 59 pm](https://user-images.githubusercontent.com/1254810/30245023-38d0b724-9592-11e7-88ca-bdb6d347ea33.png)

**Comment by ariesjia** [comment]
can i take this issue

**Comment by wmbutler** [comment]
Yes, did you change the label in both locations as specified?

**Comment by ariesjia** [comment]
yes ，i change the all the locations

**Comment by landry314** [comment]
What about the calculation? Did you find the formula used in _ b -> Accounts -> Total Value _ and copy it to the calculation used in the top bar? That formula works when the other fails. Test it out by creating an open order for every bit of an asset for every asset. You should see 0 or "Unknown Value" for every asset in _ Account -> Balances -> Equivalent Value and the calculation in the top bar should say "0". It ignores the open orders. Just making sure you got my point above!

**Comment by landry314** [comment]
![balance 0](https://user-images.githubusercontent.com/6866501/30260225-138eb9ae-9694-11e7-9eb0-cab0c9f97fac.jpg)

**Comment by landry314** [comment]
Actually, that photo is from an older version of the program. It seems that it no longer says "Unknown value" in the newest build, sorry about that, BUT it still says "Balance: 0" on top when all assets are completely in open orders and the Equivalent Value column says "0 BTS" for every asset.

**Comment by landry314** [comment]
This commit only fixes the name and not the calculation bug.

**Comment by wmbutler** [comment]
It would be helpful if you would delete screenshots that are from older versions of software. Posting outdated bugs takes time for us to troubleshoot.

![screen shot 2017-09-12 at 8 20 01 am](https://user-images.githubusercontent.com/1254810/30327857-332de514-9793-11e7-8a38-f17861c7578c.png)

**Comment by landry314** [comment]
Ok, I deleted it. Thank you for submitting a newer screenshot, @wmbutler. So, now it says "0 BTS" instead of "Unknown value" but the bug is the same. We can't see you have an open order there but I assume you do.

**Comment by calvinfroedge** [comment]
Closing this issue as it has been merged

**Comment by Ashaman-** [comment]
Should this issue have been closed, given that the calculation bug has not been fixed yet?

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
Entire point of this was to point out it's an estimate. Might actually be way off if one of your asset's markets is not liquid. 

Equivalent value and value are two different things. First one implies estimated value (one through calculation and second is just value. the top text doesn't communicate that it isn't meeting goal. I'd almost favor 

"EST. VALUE: ~" or "EST. TOTAL: ~" or "EST. BALANCE: ~" or "TOTAL VALUE: ~"

but I see issue is closed so I won't follow up on it again.

**Comment by landry314** [comment]
Just installed the new GUI and the ACCOUNT VALUE calculation bug is still there. It says "ACCOUNT VALUE: 0" because all my assets are in open orders while the TOTAL VALUE for my account in the "b" tab on the upper left is properly calculating my account value... still there... :-(

**Comment by Ashaman-** [comment]
@o5j5vg55bv5hv5j5f8799f9 I agree that the point of it is an estimate, but it should work consistently. I have seen it say 0 estimated value intermittently as well, and it always scares the shit out of me (and I expect it will continue to do so until the Ledger Nano integration is complete)...

**Comment by landry314** [comment]
Intermittently, @Ashaman-? I guess I need to put numbers so people pay attention:

Steps to Reproduce:

1) Create an open order which is maxed out to take every last unit of your asset out of balances.
2) Repeat for every asset you have
3) Look at the Account Value at the top, it says "Account Value: 0"
4) Click on the "b" tab on the upper left. Find your active account under Accounts.
5) Look all the way to the right under the column TOTAL VALUE.
6) Notice that is does NOT say "0" but calculates correctly.

Why wouldn't we simply clone the correct calculation to the Account Value on the top? Any reason?

**Comment by landry314** [comment]
You don't know how happy that makes me! :-)
