### ISSUE TITLE
On Voting/Workers page it's not obvious that changes take no effect until published

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#38]
_From @valzav on February 5, 2016 19:26_

So maybe after Approve button is pressed, it needs to say something like "Supported (publish to cast your vote)" in the status field?

_Copied from original issue: cryptonomex/graphene-ui#718_

**Comment by svk31** [comment]
_From @abitmore on February 6, 2016 4:51_

And best if we have a warning before user leave the page, if some changes made but not published.

**Comment by svk31** [comment]
_From @abitmore on February 6, 2016 4:52_

And/Or maybe just pop up the confirmation window.

**Comment by svk31** [comment]
_From @dnotestein on February 6, 2016 5:4_

Requiring the user to either publish or cancel pending changes before they leave the page (as I think abit is suggesting) sounds like a reasonable idea. As I understand current operation, it doesn't immediately pop up a confirm when you press the button so that you can "batch" several votes into one transaction.

**Comment by wmbutler** [comment]
This will happen on voting UI update. Closing.
