### ISSUE TITLE
[.5] Height Setting should apply to both Price Chart and Market Depth

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#384]
The user can adjust the chart height for the Price Chart but can not for the Market Depth. I am referring to when the Market Depth is displayed above the orders by clicking "MARKET DEPTH" just to the left of the word "My Market" and below the account value calculation on the top. This is a fixed height and so I can not adjust it to control my screen real estate properly.

I suggest having one height setting for both the Market Depth and Price Chart and just applying it to both. Maybe make the settings gear icon available when seeing Market Depth as well as the Price Chart. Or, have two variables...

And if you are adding this gear then why not add "Show Settle Orders" like we can control in Settings -> General.

**Comment by tbone-bts** [comment]
OP makes a good point re: the height setting control.  It should apply to both the Price Chart and the Market Depth view.  This is a screen configuration, not a chart configuration and therefore should logically not be included in the chart gear icon.  Instead, it would make the most sense for this setting to be up/down or plus/minus buttons (similar to Bitfinex, see image) in the open space to the left of the Market Dept/Price Chart selector.  This would be FAR more convenient. 

![dex_chart_height_control](https://user-images.githubusercontent.com/15830348/30617144-c2c57564-9d62-11e7-95ef-277da00a34a7.jpg)

![dex_chart_height_control_2](https://user-images.githubusercontent.com/15830348/30617404-ec36c762-9d63-11e7-94e5-1c943d3a3514.jpg)

**Comment by wmbutler** [comment]
Totally agree.

**Comment by wmbutler** [comment]
Closing for #361
