### ISSUE TITLE
tag 2.0.17.08.30 issue  error code EBADPLATFORM

### ISSUE THREAD

**Issue by 15963** [bitshares/bitshares-ui#387]
hello!
reference address: https://github.com/bitshares/bitshares-ui/tree/2.0.170830
I build bitshares-ui in ubuntu16.04.1 ,
when i run : cd electron
                   npm install
there is a error:

`npm ERR! Linux 4.10.0-33-generic
npm ERR! argv "/home/fu/.nvm/versions/node/v6.11.3/bin/node" "/home/fu/.nvm/versions/node/v6.11.3/bin/npm" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for appdmg@0.4.5: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/fu/codes/bitshares-ui/electron/npm-debug.log`

**Comment by svk31** [comment]
There is no electron folder anymore, if you want to build the latest version just use the `master` or `staging` branches and run `npm i && npm run package`
