### ISSUE TITLE
[1] Conform bitAsset Unit Names Throughout Program 

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#388]
In _ Settings -> General -> Preferred Unit of Account _ you see the names of fiat currencies like CNY, USD, EUR but the calculations to this selected unit are actually using bitCNY, bitUSD, bitEUR.

The top bar calculation now says BITUSD, BITCNY, etc, but if you mouse over the calculation you see the components written below in USD, CNY, etc.

We need to conform the unit throughout the program. I think bitCNY, bitUSD, etc is best because it is more accurate. Are we using witness feed prices or prices from the last trade in the pair being used to estimate value? It seems like it is recent trades because of the way it moves, therefore it is not actually CNY, USD, EUR, etc.

Whichever one it is, it needs to be that one throughout or it creates confusion.

**Comment by landry314** [comment]
Actually, due to recent events in China, I think it is very important to make it always say bitCNY to make it very clear there is no Chinese fiat currency involved but rather a coin tracking the value of CNY. As chinese people move to the DEX, this could help them be more comfortable trading it.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
Consistent names should be used EVERYWHERE for ALL assets.

Here's more examples: 
![image](https://user-images.githubusercontent.com/22536095/30770992-0f4c076c-a00c-11e7-8a22-c15ca2401f7f.png)

![image](https://user-images.githubusercontent.com/22536095/30771007-3993b006-a00c-11e7-8917-4a58a8855131.png)

There's two assets that look identical even though one is open.lisk and another is just lisk
https://bitshares.org/wallet/#/asset/OPEN.LISK
https://bitshares.org/wallet/#/asset/LISK

This just cannot happen. Especially if we get more gateway providers for same coins. All this info including issuer and full name should be always available.

**Comment by landry314** [comment]
Well, if we all have agreed in issue #116 that we need to use open.ASSET consistently then I think that conforming the bitASSET names as we are discussing here is a logical next step.

**Comment by landry314** [comment]
We are going to need to dredge through the program to find them all... so far I see:

- Settings -> Preferred Unit of Account

- When hovering over ACCOUNT VALUE on the top bar

- Searching for assets in Find Markets

- Displaying assets in User Issued Assets

- In the Send tab in the QUANTITY and FEE fields

Anyone find anymore?

**Comment by wmbutler** [comment]
I'm inclined to agree. Might be nice to ask for some votes on this to be sure.

**Comment by landry314** [comment]
I also think that part of this conformity should be always using a lowercase CAP font for the "BIT" and uppercase for the ASSET.

Therefore, the font for the unit after ACCOUNT VALUE on the top should also have a lowercase cap BIT as well.

Finally, another place to conform is discussed in issue #478 where a lowercase bit was used instead of a lowercase cap font.

That might be all the places to make the bitASSET names uniform...

**Comment by landry314** [comment]
I found another place, in the Margin Adjustment window it says "CNY Margin" or "USD Margin"...

I think this issue is actually quite important. Providing margin for REAL USD would certain violate United States SEC regulations... borrowing bitUSD from the BitShares blockchain is not the same thing and I think it is very important to highlight this difference. We are not providing USD loans... This is not a bank in the traditional sense.

**Comment by landry314** [comment]
Is it HERO or bitHERO? In the BTS/HERO market you see "borrow bitHERO" in the SELL HERO tile but it is always called HERO.

We should drop the "bit" here, right?

**Comment by landry314** [comment]
Why has no one claimed this?

A particular important instance of this problem I see is in the Find Markets. If you open the pulldown menu in Quote Currency you see both "BTC" and "OPEN.BTC". It is really unclear that OPEN.BTC is real BTC held by open ledger and BTC is bitBTC held on the BitShares blockchain. A new user might just assume BTC is real BTC and open.BTC is some other weird thing...

Of course open should be in the lower case CAPS font if possible or just regular lowercase if not...

Who wants to take this issue? Be sure to get all the instances in https://github.com/bitshares/bitshares-ui/issues/388#issuecomment-333370761
