### ISSUE TITLE
Display Volume Unit Next to "VOL" in My Markets

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#389]
In MY MARKETS, there is a VOL column but it is unclear which unit the volume is measured in. It would be very helpful to put it in parenthesis or before the word VOL.

Examples:

VOL (BTS)
BTC VOL

Also, why is it shortened to "VOL"? "VOLUME" would be even clearer.

VOLUME (BTS)
BTC VOLUME

I personally think the parenthesis are clearer.

**Comment by svk31** [comment]
It's shortened because of space concerns. Volume (BTS) may work, but Volume (VERYLONGASSETNAM) will completely skew the column.

**Comment by wmbutler** [comment]
It's implied that the volume is that trading pair. I don't really think this makes much sense.

**Comment by landry314** [comment]
So, here is how it looks on Bittrex. Notice they put the unit the volume is measured in before the word VOL to make it clear. It is not clear in My Markets. You need to find it at the top under "24hr Volume:" to be sure.

![bittrex volume for github](https://user-images.githubusercontent.com/6866501/30903962-76c5602a-a33e-11e7-9829-94e0e9513248.jpg)

![volume in usd on bittrex](https://user-images.githubusercontent.com/6866501/30904188-40b3f860-a33f-11e7-8388-283977e2bfb2.jpg)

**Comment by wmbutler** [comment]
@svk31 I think it's reasonable to increase the height of My Markets to include this. We continually need to be able to display more at a glance in various places and adding a row to each market would give us that flexibility. My favorite markets only occupies a portion of the overall height and I think this could help us add clarity. I can UX this.

**Comment by landry314** [comment]
This is a feature, not a question.

**Comment by wmbutler** [comment]
It's a question until we reach consensus on how to implement it.

**Comment by wmbutler** [comment]
I agree that this really will not fit in My Markets for long symbols.
