### ISSUE TITLE
add client-server connection status

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#39]
_From @btswolf on February 5, 2016 21:34_

For troubleshooting reasons is would be great to have an indicator that shows the connection quality to the server.

maybe at the bottom left of the Blocks.
GOOD (<30ms), SLOW (<150ms), POOR (>150ms)
GREEN/YELLOW/RED

_Copied from original issue: cryptonomex/graphene-ui#719_

**Comment by wmbutler** [comment]
Agreed that this is an important feature. I'll generate a UI for this.

**Comment by wmbutler** [comment]
Closing this and noting we still have a few bugs addressed here. #376
