### ISSUE TITLE
[.5] Price Entry Field Ignores '.' Character When Overwriting Selected Number

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#390]
Steps to Reproduce:

1) Go to the Exchange
2) Type any number in the Price field
3) Select all data in the Price field
4) Type the '.' (period, full-stop, decimal point) character

It will clear the field but NOT add the '.' character. Note that any digit entered instead of the '.' at step 4 will clear the field AND add that digit as expected.

I have made this mistake a few times, typing my price and then realizing it did not start with a '.' then having to add it again before placing the order. It wastes time and could lead to the wrong price being submitted (though the way out of range warning should trigger).

**Comment by wmbutler** [comment]
This is definitely a bug and easy to reproduce.

**Comment by landry314** [comment]
Looks like this bug is back in full force as of the 171015 release. Following the original steps to reproduce you now won't clear the field, in fact now using the '.' character does nothing at all.

ALSO, try clearing the field THEN typing a '.' as the first character... nothing happens again.

It appears the '.' character can not be used until there is already a number in the Price field. This is a problem when the price is less than 1 and the normal way to begin typing it is with a '.'

**Comment by landry314** [comment]
Should I create a new issue? I mean, it is almost the same bug we squashed before, now back...
