### ISSUE TITLE
[2] My Open Orders Window Not Displaying Orders Beyond 5 Million BTS Depth

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#393]
Steps to Reproduce:

1) Go to BTS : bitCNY when it has a lot of buy orders (now)
2) Create a very low buy order
3) Switch to Market Depth
4) Move the cursor to the left on the chart until it goes further left than 5 million BTS
5) Observe the lack of your order in the My Open Orders window.

Since the cumulative volume of bitCNY buy orders is over 5 million BTS then the Market Depth chart is maxed out. The cursor won't even go past this lower limit which is 0.47 bitCNY/BTS at the moment.

I currently have a buy order which is less than 0.47 and it does NOT show up in the My Open Orders window but it DOES show up in the Account area. The order is in the blockchain but it is not in the Exchange area.

While I understand that the Market Depth and Buy and Sell Orders windows must have a maximum for display purposes and to reduce lag due to too much data, not having an order appear in "My Open Orders" is very bad because it makes the user think the order is not actually submitted. Also, as the volume increases on the DEX with time, this maximum will be reached with much less spread from the current feed price and so this issue will become more and more of a problem.

I think this will be a high priority bug soon if not now.

**Comment by wmbutler** [comment]
A licecap screencast of this might be helpful.

**Comment by svk31** [comment]
There are two simple issues at work here, the first is that the data being used is different: under accounts the open orders are fetched from the account object while in the exchange they're fetched from the list of limit orders. Secondly, the list of limit orders is limited a 400 entries maximum, which is why some orders don't show up in the MyOpenOrders component used in the exchange.

I'll up the limit slightly and refactor MyOpenOrders to use the open orders from the account object instead.

**Comment by landry314** [comment]
It actually isn't 5 million as right now in BTS : bitCNY it is stuck at a limit of 4.52 million. I don't know how this limit is set.

As for some orders not showing up in the My Open Orders, couldn't the orders be fetched from the same place as the Account data?

**Comment by wmbutler** [comment]
@svk31 maybe we can adopt units in the display to deal with really large numbers like:

4,000,000 = 4,000k

I think we all agree that all orders must be displayed for us to be taken seriously as an exchange.

**Comment by wmbutler** [comment]
@svk31 this is in the 171001 sprint. Is it your intention to include this in the 170914 Sprint?
