### ISSUE TITLE
[.5][skenan] Toggling Show volume chart causes x-axis to shift upwards

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#402]
![show_volume_chart](https://user-images.githubusercontent.com/1254810/30402709-45baa2e6-98a4-11e7-9362-0bca6cf4e256.gif)

**Comment by skenan** [comment]
Can I take this one?

**Comment by wmbutler** [comment]
Yep!

**Comment by svk31** [comment]
Oh shit sorry I just fixed this, didn't notice it was taken..

**Comment by skenan** [comment]
@svk31 Thanks for taking that. I haven't spent much time on that.
