### ISSUE TITLE
[.25] Change equivalent value to Estimated Value

### ISSUE THREAD

**Issue by knifewine** [bitshares/bitshares-ui#411]
On the account page, there's a column for "Equivalent Value".

When the asset value is already displayed in that denomination, the Equivalent Value column should probably just show the same value, or be blank. E.g. when the account has 0.57 USD, it's odd to display the Equivalent Value as "1 USD".

To repro:
Set account to display in USD.
Make sure account holds a non-integer amount of USD (e.g. 0.57)
Look at the Accounts screen.

![issue](https://user-images.githubusercontent.com/123593/30491119-726f138e-99f9-11e7-9f72-7c6beb6fbbae.png)

**Comment by wmbutler** [comment]
I'm guessing we are doing some rounding here to provide an overview. The label could definitely be better. Maybe change the label to `approximate value`.

**Comment by wmbutler** [comment]
See #378 Tables Rewrite as well regarding this label display.

**Comment by landry314** [comment]
But the word "equivalent" is good when it is converting from another unit.

maybe "Estimated Value"?
