### ISSUE TITLE
Cannot read property 'chain_id' of null

### ISSUE THREAD

**Issue by ronenteva** [bitshares/bitshares-ui#412]
When submitting an order, I keep getting `Uncaught TypeError: Cannot read property 'chain_id' of null`

**Comment by svk31** [comment]
That's an API issue that indicates you're not connected to a server. Are you running one of the light wallets or hosted web wallets, or a local build?

**Comment by ronenteva** [comment]
It kept happening on bitshares.org, everything else worked fine.
The light wallet for windows works fine.

**Comment by wmbutler** [comment]
Please post steps to reproduce or a screencast with licecap.
