### ISSUE TITLE
Open order are not displayed correctly in 170915

### ISSUE THREAD

**Issue by btswolf** [bitshares/bitshares-ui#415]
[![image](https://user-images.githubusercontent.com/11035520/30513984-6d76d15e-9b0d-11e7-9c93-be79073b79a1.png)](https://user-images.githubusercontent.com/11035520/30514000-c708dd0c-9b0d-11e7-97e0-a727ae0d6e42.png)
Seems the orders are not updated or somewhat strangly misinterpreted.
Only red orders and mixed values.

**Comment by btsfav** [comment]
buy orders are wrong it seems

**Comment by svk31** [comment]
Already fixed.
