### ISSUE TITLE
[2] Make inverting trading pairs more obvious

### ISSUE THREAD

**Issue by knifewine** [bitshares/bitshares-ui#416]
Users can click on the trading pair names near top left to invert, but this is very non-obvious.
![example](https://user-images.githubusercontent.com/123593/30514699-71610784-9ad7-11e7-98fb-4bfd3df1e794.png)

I think a lot of newer users would benefit from knowing they can do this.

The UI should have a better visual indication that this is possible.

For example if you visit the BTS:USD pair, but realize you want the opposite it's very easy to invert the trading pair with one click. I suspect most new users have to go hunt through the market tabs and get frustrated in the process.

**Comment by landry314** [comment]
yes, an invert button would be clearer.

**Comment by wmbutler** [comment]
Bill to UX

**Comment by wmbutler** [comment]
Better? We should remove the click action from the text values with this change. Ultimately clicking on the asset could take the user to the asset explorer.

![screen shot 2017-09-19 at 9 51 40 pm](https://user-images.githubusercontent.com/1254810/30624746-bf9be540-9d84-11e7-88af-5b22f8f1b45e.png)

**Comment by wmbutler** [comment]
Made this 2 hours because this needs to be updated throughout the site for bounty.

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/30732623-b95b28c6-9f73-11e7-92ae-9068ff6edde8.png)

Made it grey so it shows up in light theme also, clicking on the asset names now takes you to the asset page.

**Comment by landry314** [comment]
@svk31, if clicking an asset name now takes you to the asset page then I guess you can close issue #280.

**Comment by svk31** [comment]
Yep, good catch, thanks.
