### ISSUE TITLE
[.25] New Mac OS Client Backup Files Missing .bin Extension 

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#417]
The newer builds of the Light Client for Mac OS no longer create backup files which have the .bin extension and as such are treated as text files by Mac OS and have a very generic text icon.

The older files looked better and the .bin extension made it clearer that they were backup files.

**Comment by wmbutler** [comment]
Agreed. This appears to be an oversight, at least on the Mac client.

![screen shot 2017-09-16 at 5 44 14 pm](https://user-images.githubusercontent.com/1254810/30516501-b9faa4ee-9b06-11e7-9f56-f7237059bec4.png)
![screen shot 2017-09-16 at 5 43 30 pm](https://user-images.githubusercontent.com/1254810/30516502-b9fb4cdc-9b06-11e7-84ec-c4e19cffaf73.png)

**Comment by svk31** [comment]
This must be a change in the OS and how it handles saving files; or a change in the file-saver package. Either I'm unable to test this since I don't have a Mac, maybe @calvinfroedge can handle it?

**Comment by wmbutler** [comment]
@calvinfroedge will you claim this and test? Add time to it if it's not enough.

**Comment by landry314** [comment]
@wmbutler, @svk31... @calvinfroedge has not replied to this request. Is there someone else who can test this?

**Comment by ariesjia** [comment]
I test it , it's electron issue.

**Comment by ariesjia** [comment]
I update electron version to fixed this issue .   It's related to electron issues : 
https://github.com/electron/electron/issues/10121     https://github.com/electron/electron/pull/10469
