### ISSUE TITLE
[0.25] Change Name of Program to "BitShares"

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#418]
The program is called the "Light Wallet" and inside of it there are "Wallets" you can create and control or you can use the Account Model and not use a wallet.

It is confusing to have the same name for two different things. Is the wallet the program or the things that hold my accounts inside the program? This confuses new users.

Since the word wallet is used to refer to the account-holding object within the program much more than the program itself and since the program actually does much more than just function as a wallet, the easiest and clearest thing to do is simply rename the program.

"BitShares Light Client" is ok but most users have no idea why is it called "Light" anyway. What about these ideas:

- BitShares Client
- BitShares Browser
- BitShares (like it used to be called in the 0.9.3c days)
- BitShares Interface

I think plain old "BitShares" it the best but I understand using the same name as the blockchain or the BTS asset might confuse something. "BitShares Client" fixes that but an average user doesn't necessarily understand the computer jargon "client/server" so they might think it is for the clients of some company, I don't know.

Also, should we capitalize the S in shares? I'm not sure.

Finally, I do also understand we want to differentiate the web interface from the program. That might be why the word light was used in the first place. I don't know.

Plain old BitShares is my vote. Simple, Elegant, Clear. Haha.

**Comment by landry314** [comment]
This has been discussed but not had an issue opened.

https://github.com/bitshares/bitshares-ui/issues/378#issuecomment-329916838
https://github.com/bitshares/bitshares-ui/issues/301#issuecomment-329937206

**Comment by wmbutler** [comment]
I like just Bitshares.

**Comment by btswolf** [comment]
![image](https://user-images.githubusercontent.com/11035520/30565304-076efa46-9cc8-11e7-8ff3-3b9c0527f414.png)

**Comment by btswolf** [comment]
[![bitshares_client](https://user-images.githubusercontent.com/11035520/30565339-280b3260-9cc8-11e7-89a3-de45a4164343.png)](https://user-images.githubusercontent.com/11035520/30565339-280b3260-9cc8-11e7-89a3-de45a4164343.png)

**Comment by landry314** [comment]
@btswolf, Everywhere I look online the S is capital in BitShares. I guess that is the way we should write it.

**Comment by wmbutler** [comment]
@svk31 Probably does make sense to just call all the binaries just "Bitshares"

**Comment by ariesjia** [comment]
Can i take this feature ?

**Comment by wmbutler** [comment]
@ariesjia This should probably be claimed by @svk31 or @calvinfroedge because they have worked with the binary builds.

**Comment by svk31** [comment]
Personally I prefer Bitshares with lowercase s, but we did a round on this a while back and the community decision was to use BitShares with a capitalised S so that's what the GUI tries to use everywhere.

One problem with renaming the binaries is that it may create a new storage domain, meaning that old wallets will not be available from the new binaries.

**Comment by landry314** [comment]
On Mac OS, the name was just changed from "BitShares2-light" to "BitShares Light Wallet" and nothing weird happened. Maybe because the support folder at _ Library -> Application Support -> BitShares2-light _ retained the same name.

**Comment by svk31** [comment]
Right, as long as the package name defined here: https://github.com/bitshares/bitshares-ui/blob/staging/package.json#L2 remains the same, the storage domain will be the same. 

The product name (Bitshares Light Wallet) is defined here: https://github.com/bitshares/bitshares-ui/blob/staging/package.json#L76 and can safely be changed.

**Comment by wmbutler** [comment]
I think all that really matters is the visual here. We have a lot of extra words that aren't relevant anymore:

- Light used to be relevant to distinguish it from the full client
- Wallet used to be relevant before we added the account model
