### ISSUE TITLE
Preference tooltips on/off

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#419]
I didn't know what to call them but when you hover over the dotted underlined links then a popup bubble with a tip appears. This is useful to new users but useless to regular users and just kind of a nuisance after a while.

Why not add a setting in Settings -> General to disable these altogether? Once a user has read them all, he no longer benefits from them.

**Comment by wmbutler** [comment]
I think we can do better than this. If you look at highly trafficed sites, it's not a common pattern to enable disable tooltips.
