### ISSUE TITLE
Wallet Auto-Lock Time Setting Has Too Much Padding Below Name

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#420]
The padding below the words "WALLET AUTO-LOCK TIME (SECONDS, 0 TO DISABLE)" is more than for all the other settings in Settings -> General.

For visual consistency, it would be nice to conform it.

**Comment by wmbutler** [comment]
Let's handle this with tables rewrite. There are endless areas where spacing sucks.
