### ISSUE TITLE
[15][gibbsfromncis] Set Price Alerts

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#422]
Many trading interfaces have alert systems when a price is reached or when a certain percentage move occurs. It would be a nice addition to this platform to include such features.

Alerts could trigger a sound and/or a popup and/or an email sent to an address of choice.

**Comment by landry314** [comment]
This is mentioned in #288 briefly.

**Comment by fractalnode** [comment]
It would also be nice to have an alarm below the specified value of Collateral Ratio

**Comment by wmbutler** [comment]
Chrome Notifications can handle this. Let's start this off with alerts for:

- [ ] Predetermined collateral value
- [ ] Price target (enter as percentage or as fixed number, but stored as a fixed number either way)

**Comment by gibbsfromncis** [comment]
@wmbutler I can integrate this to my Browser Notifications. But we need some UX for this on Exchange I guess. But make sure that Browser Notifications work only if tab opened.

**Comment by gibbsfromncis** [comment]
- [ ] Add ability to enable/disable "Price Alert" browser notification on Settings -> Browser Notifications
- [ ]  (Simple) Add "Alarm" Icon on Exchange near Latest Price. When user click he can specify price at which he should receive the notification. 
- [ ] (Complex) Add "Alarm" Icon on Bids/Asks header. When user click on it he can specify price and minimal amount of order at which he should receive the notification.
- [ ] Add Price Alert (idk where we can add this) manage section. We should have one place where user able to See/Delete/Add price alerts for different pairs.  

<img width="1396" alt="price-alarm" src="https://user-images.githubusercontent.com/35899973/36260180-dfccb438-1260-11e8-86a7-b60f4531e7a7.png">

**Comment by wmbutler** [comment]
Pushing this out pretty far. UX needed.

**Comment by diogogomes** [comment]
This can be included with activity. We can put an belt icon on the main navbar like I proposed on my style guide (on the right).

When belt is selected it shows last notifications on a small dropdown popup (last 5 notifications for example).

This dropdown popup can also have two tabs, one for market notifications and one for last activity notifications.

I also recommend put a link to all activity / notifications that open a new page with this informations.

This way we can also remove the activity section from the dashboard and make it one isolated module. This can bring more accessibility for the activity/notifications that is one of the first things that users want to see (when using the client for trading).

**Comment by gibbsfromncis** [comment]
@wmbutler if someone provide UX I can work on this one.

**Comment by diogogomes** [comment]
@wmbutler 

I'm available to provide the UI/UX.

**Comment by gibbsfromncis** [comment]
@diogogomes What about now? Are you ready ?

**Comment by diogogomes** [comment]
I'm sorry @gibbsfromncis,  I don't understand your question. Can you reformulate? Thanks

**Comment by gibbsfromncis** [comment]
@wmbutler what about this issue? Do we wait for UX from this task - https://github.com/bitshares/bitshares-ui/issues/1263 ?

**Comment by wmbutler** [comment]
I guess so.

**Comment by gibbsfromncis** [comment]
@wmbutler If I understand correct the UX is finished. I can implement Price Alerts but I have no idea how to notify users about these alerts. Bell UX was removed from diogo so we have only Price Setup UX

**Comment by wmbutler** [comment]
We need to determine if this is the screen for setting alerts or reporting those alerts. I think if your just work on setting price alerts, you can route those requests to Chrome. We can later built a price alert screen for dismissing them, etc.

**Comment by gibbsfromncis** [comment]
@wmbutler based on UX please increase to 5 hours because it was put before we get UX.

**Comment by gibbsfromncis** [comment]
@wmbutler @startailcoon 

I have troubles regarding this issue. I've started to use `bitshares-ui-style-guide` but `bitshares-ui` uses references to global html tags on his css. 

This is screenshot to help you understand issue better:
<img width="967" alt="btsuiconflict" src="https://user-images.githubusercontent.com/35899973/41624580-739ec5ea-7416-11e8-8b79-9c143349be2b.png">

This is how Style Guide components looks like. Dropdown has left padding on itself, <Input> totally different because we uses global styles in our css like `ul { }` and `input{ }`. I suppose we will have more troubles with that. 

I have no idea how to fix it now and how much time this will take. Just wanted to let you know about problem of using `bitshares-ui-style-guide` now and that estimate will be changed because I'm going to fix this conflicts in the scope of this issue.

**Comment by wmbutler** [comment]
@gibbsfromncis did you resolve this in a different issue?

**Comment by gibbsfromncis** [comment]
@wmbutler me and @startailcoon decided to fix what we need on specific file on bitshares-ui like style-guide-fixes.scss so I will be able to delivery this issue on the next sprint

**Comment by gibbsfromncis** [comment]
@wmbutler @startailcoon I'm so close to finish this task but I'm out of my estimate. Please increase it to 10h or just unassign myself.

**Comment by gibbsfromncis** [comment]
### Notifications
<img width="417" alt="screenshot 2018-11-06 03 29 12" src="https://user-images.githubusercontent.com/35899973/48039228-264f7e80-e174-11e8-9a34-f7b59f71755d.png">

### Price Alert Icon

<img width="169" alt="screenshot 2018-11-06 03 08 00" src="https://user-images.githubusercontent.com/35899973/48038498-2d28c200-e171-11e8-9a4a-c45aa247b64e.png">

It is blue when pair has notifications and simple when hasn't

### Price Alert Manage

<img width="552" alt="screenshot 2018-11-06 03 09 17" src="https://user-images.githubusercontent.com/35899973/48038539-5a757000-e171-11e8-8ef3-0ff5eb6e0470.png">
<img width="554" alt="screenshot 2018-11-06 03 09 09" src="https://user-images.githubusercontent.com/35899973/48038540-5a757000-e171-11e8-9c94-927b813d9a14.png">

**Comment by gibbsfromncis** [comment]
@startailcoon it took a little bit more than I expected but now i'm familiar well with Market operations. 

Final estimate: 15h
