### ISSUE TITLE
Staging branch doesn't load Dev Server for me :(

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#427]
Is the `staging` branch expected to load the dev server?

I have been syncing my local fork upstream to the `bitshares` branch using `git pull` and my dev server builds just fine. But now I have fetched the `staging` branch and when I checkout and try `npm start` I get a packaging error:

>spark@sparkmaster:/projects/repos/bitshares-ui$ nvm use v6
>Now using node v6.11.1 (npm v3.10.10)
>spark@sparkmaster:/projects/repos/bitshares-ui$ cd web
>spark@sparkmaster:/projects/repos/bitshares-ui/web$ npm start
>npm ERR! Linux 4.10.0-30-generic
>npm ERR! argv "/home/spark/.nvm/versions/node/v6.11.1/bin/node" "/home/spark/.nvm/versions/node/v6.11.1/bin/npm" "start"
>npm ERR! node v6.11.1
>npm ERR! npm  v3.10.10
>npm ERR! path /home/spark/projects/repos/bitshares-ui/web/package.json
>npm ERR! code ENOENT
>npm ERR! errno -2
>npm ERR! syscall open
>
>npm ERR! enoent ENOENT: no such file or directory, open '/home/spark/projects/repos/bitshares-ui/web/package.json'
>

**Comment by fletchertyler914** [comment]
Try to run it from the root level instead of /web

**Comment by happyconcepts** [comment]
Thanks ... I tried that but get this now:

spark@sparkmaster:/projects/repos/bitshares-ui/web$ cd ..
spark@sparkmaster:/projects/repos/bitshares-ui$ npm start

> BitShares2-light@2.0.170915 start /home/spark/projects/repos/bitshares-ui
> cross-env NODE_ENV=development node server.js

sh: 1: cross-env: not found

I do not have cross-env installed; can someone confirm that the source has been audited? I am aware of  [the cross-env hacks on npm last month](http://blog.npmjs.org/post/163723642530/crossenv-malware-on-the-npm-registry).

**Comment by fletchertyler914** [comment]
Hmm... I can confirm there is something weird going on. 
I am now getting a failed to compile after building once an stopping the server. 
I fixed it once by switching branches and then switching back to staging, but now I can't get it to build. 

Going to keep digging.

**Comment by svk31** [comment]
You simply need to run npm install at the root level after switching to staging. I was not aware of the crossenv hack but we are using the correct package so it does not affect us.
