### ISSUE TITLE
Wallet is not shown after restore (and before page reload)

### ISSUE THREAD

**Issue by youaresofunny** [bitshares/bitshares-ui#428]
1. Clear storage
2. Restore wallet using /create-wallet-brainkey
3. Got succes message
4. Header is still like no account / wallet (lock - unlock icon is there, but not working)
5. Reload page
6. Now unlock works, and after it i see my account in header

**Comment by youaresofunny** [comment]
Can u reproduce it? (no account name in header after wallet restore by brainkey)

**Comment by landry314** [comment]
Why did you close this?

**Comment by youaresofunny** [comment]
@landry314 because can't reproduce again (and no one can)
