### ISSUE TITLE
[.25][ariesjia] Right Justify Column Headers for My Trades, Market Trades, My Open Orders

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#429]
![screen shot 2017-09-19 at 9 44 10 pm](https://user-images.githubusercontent.com/1254810/30624584-d41f576e-9d83-11e7-830b-55eca38f7bcf.png)

**Comment by wmbutler** [comment]
![screen shot 2017-09-19 at 9 45 54 pm](https://user-images.githubusercontent.com/1254810/30624598-ee1f3a12-9d83-11e7-82c7-189ea26cd737.png)

**Comment by ariesjia** [comment]
can i take this easy feature :stuck_out_tongue:

**Comment by wmbutler** [comment]
It's yours!

**Comment by ariesjia** [comment]
@wmbutler  This pull request is merged .
