### ISSUE TITLE
[4] Notify users about available update in the wallet

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#43]
_From @btswolf on March 9, 2016 16:7_

If there is a new public release of the light wallet there should be an indicator that a newer version is available. Could be at the bottom. Update available.... outdated etc...

_Copied from original issue: cryptonomex/graphene-ui#765_

**Comment by wmbutler** [comment]
Agreed. The client needs to be able to report this only after the binaries are in place. To enhance this further, the client would initiate the download and self-update once the user agrees.

**Comment by wmbutler** [comment]
This isn't pixel perfect, but the idea here is that the cloud download icon would open an external browser to reveal: https://bitshares.org/download/

This is a screenshot of the lower left corner of the Bitshares light wallet when it has detected that there is an update that can be downloaded by the user. It's important that the notification detect an actual downloadable binary. If we don't do that, it's possible that we would release a new version and the end user would be unable to locate a binary if it hadn't yet been built.

![screen shot 2017-07-30 at 6 57 48 pm](https://user-images.githubusercontent.com/1254810/28758158-09782498-7559-11e7-997f-6cdfc94dfbab.png)

**Comment by testlump** [comment]
The development should take into account differing releases of the UI. For example RuDEX create their own builds based off of the bitshares-ui core repository. 

Basic security features such as possibly signing update notification alerts should be implemented alongside ways to ensure differing UI releases can easily override signing keys (possibly global constant?) to provide their own notification channels to their users (E.g. RuDEX UI builds). 

A hyperlink to the download page would also be helpful but only if it poses no risk of manipulation by malicious actors. In may be easier to place this into the settings menu and just have a "Get Latest Release" hyperlink and hardcode the URI into the build.

**Comment by wmbutler** [comment]
I'd suggest that RuDEX create their own notification system. They can fork this REPO and follow our lead if they decide to.

**Comment by wmbutler** [comment]
If update is available display:

- cloud download icon
- update available text

If update is not available, just display the version number.
