### ISSUE TITLE
[4] Show list of open debt positions for smartcoin assets and warn when a position is at risk of force settlement

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#430]
The only way that I am aware of to view the complete list of open debt positions ordered by collateral ratio is cryptofresh - I dont think this functionality is implemented in bitshares-exlorer yet. Knowing the open debt positions is very important  for borrowers of smartcoins when there are force settlement orders open on the books, since their exposure to the possible risk of forced settlement is directly related to how many less collateralized positions than theirs exist. Users should be able to view the list of open debt positions and their respective collateral ratios directly in the wallet software. 

On the account page where it lists open debt positions, I think it should be possible to view the sum of debt positions with a lower collateral ratio than theirs (ie. rolling the mouse over collateral ratio could reveal that there are 1,223,523 bitUSD with a lower collateral ratio than yours). When a position is at risk of being force settled by  a settle order on the books by being within its direct reach, the UI in Account should reflect that with a warning similar to the one that alerts you of a dangerously low collateral ratio.

**Comment by landry314** [comment]
Yes, I use this link all the time to view open debt positions in bitCNY:
http://stage.cryptofresh.com/a/CNY

I think it would be great to have this integrated into the Explorer within the GUI. Currently, there is not enough useful information in there under SmartCoins -> CNY .

**Comment by wmbutler** [comment]
I'll UX This.

**Comment by wmbutler** [comment]
From cryptofresh to begin UX:

![screen shot 2017-10-05 at 1 48 49 am](https://user-images.githubusercontent.com/1254810/31214110-6189e988-a96f-11e7-86ce-01eb5b3610fb.png)

**Comment by wmbutler** [comment]
Latest table display:

![screen shot 2017-10-05 at 1 49 57 am](https://user-images.githubusercontent.com/1254810/31214148-8d70141e-a96f-11e7-8d27-771ff35db83f.png)

**Comment by wmbutler** [comment]
Current Asset Screen:

![screen shot 2017-10-05 at 1 51 16 am](https://user-images.githubusercontent.com/1254810/31214180-ba043078-a96f-11e7-9927-eeab9e6f1cf5.png)

**Comment by wmbutler** [comment]
I think we should use our new table layout with the tabs at the top to handle this. Of course, there is a technical component to this. It's possible cryptofresh is doing some extra caching to be able to display this data, but if it is technically possible to gather the data, I'd suggest we handle it the same way we do the user dashboard with tabs:

Price Feeds | Debt Positions

![screen shot 2017-10-05 at 2 04 54 am](https://user-images.githubusercontent.com/1254810/31214624-9e8073aa-a971-11e7-9663-096531b63914.png)

Obviously no need for dollar values. This screenshot is just to help convey the tabs comment above.

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/31689396-9632dd46-b38f-11e7-9f3b-f284f54e829c.png)

**Comment by svk31** [comment]
Where exactly do you want the warning to appear? Including this information in the account dashboard would add a lot of datafetching to that page, possibly impacting performance for accounts with many margin positions.

**Comment by wmbutler** [comment]
I think what you've done is fine. Users will have a visual cue from the color of the value under margin positions. Then they will be able to click through to the asset page and view this. Really nice!

**Comment by wmbutler** [comment]
- [ ] Small bug in the sort order of the ratio column for /asset/bitUSD

See how 667.809 is out of place.

![screen shot 2017-10-23 at 11 01 11 am](https://user-images.githubusercontent.com/1254810/31899810-3353846c-b7e2-11e7-89f4-08c473ab289e.png)

**Comment by svk31** [comment]
Yea I saw that too and couldn't really figure out why it was happening :/

**Comment by svk31** [comment]
It looks like it's something weird happening for these xxx-collateral-holder accounts, where the call_price is not updated after the debt/collateral ratio has been changed. So this particular margin position with the 667 ratio displays a correct ratio but the actual call price is much lower.
