### ISSUE TITLE
[1.5] Display more than 100 accounts on "PAY WITH ACCOUNT" list

### ISSUE THREAD

**Issue by kimchi-king** [bitshares/bitshares-ui#431]
## Account creation:

On the "New BitShares account" page, the dropdown menu for "Pay with Account" is hard coded to only allow 100 names to be listed.

Error: Object {code: 1, message: "Assert Exception: std::distance(_subscribed_accounts.begin(), _subscribed_accounts.end()) <= 100: ", data: Object}

Can we please increase this to say 1000 or more?

**Comment by wmbutler** [comment]
This should probably be a typeahead instead of a dropdown.

**Comment by svk31** [comment]
That error is from the API server, same error as here: https://github.com/bitshares/bitshares-ui/issues/202

I still don't think it's a good idea to have that many accounts in a wallet, and I'm not sure why the error gets triggered here.

**Comment by wmbutler** [comment]
@kimchi-king We are limited by the API. I have a suggestion. Let's do a typeahead like in the account explorer. The negative is that it would show all account, event those you don't own. The plus side is that you will have access to any number of accounts and the API can handle it. Please reply with your thoughts.

![screen shot 2017-09-21 at 9 13 45 am](https://user-images.githubusercontent.com/1254810/30700417-323d91a6-9ead-11e7-870f-edb89a04d2df.png)

**Comment by kimchi-king** [comment]
@wmbutler Hi Bill. I'm happy with your suggestion as long as it works. I know right now, I have problems with searching for account names in the "Explore" tool. Most likely attributed to the large number of accounts I have linked to my kimchi-king account.

**Comment by svk31** [comment]
Right, the main problem here is that he has too many accounts in his wallet, and the API can't handle that properly. The way the wallet works we have to subscribe to accounts that you own so that the state of those accounts are kept up to date.

Using a search like in the explorer wouldn't change anything.

**Comment by happyconcepts** [comment]
@svk31 Instead, can this not be done with the CLI and some scripting ingenuity by the OP instead? 

typeahead seems to sacrifice ease of use for regular users in order to support this particular edge case for an advanced user at the cost of extra latency for the server round trips too.

**Comment by kimchi-king** [comment]
For now, I need to transfer some of my accounts into a new LTM wallet. Hopefully, I can make this happen because it's almost impossible to do anything in my wallet at the moment due to the API issues. Thanks to all of you for taking the time to look into this.

**Comment by wmbutler** [comment]
@kimchi-king what is your use case for so many accounts in a single wallet?

**Comment by kimchi-king** [comment]
@wmbutler I had no specific use case in mind. I was investing in these accounts through my kimchi-king account because I was receiving 80% of my investment returned back to me. If I would have known there was a limitation set by the API I would have spread them out amongst a few LTM accounts.

**Comment by wmbutler** [comment]
OK, why don't you consolidate to fewer accounts by transferring the balances to the ones you care about? I'm going to close this issue since there isn't really a use case for having 100+ accounts.
