### ISSUE TITLE
[1] Fix indicators in exchange

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#432]
This is truncated on the right

![screen shot 2017-09-20 at 11 48 14 pm](https://user-images.githubusercontent.com/1254810/30679376-ccea9f2c-9e5e-11e7-85f4-fd525f50f2c5.png)

This is covering up the date label on the bottom

![screen shot 2017-09-20 at 11 48 01 pm](https://user-images.githubusercontent.com/1254810/30679377-ccfa9508-9e5e-11e7-9100-666747279010.png)

This is truncated on the left

![screen shot 2017-09-20 at 11 48 20 pm](https://user-images.githubusercontent.com/1254810/30679407-fc841ed4-9e5e-11e7-99eb-4937c9e95882.png)

**Comment by svk31** [comment]
I don't agree that the date label should be modified, it is working as intended. The left and right labels are tricky to get correct though, I've already tried.

**Comment by wmbutler** [comment]
I think part of the problem with the date coverup on the bottom is that the date is also partially obscured but the zoom and Candlestick indicators. Maybe someone will claim this so you don't have to mess with it.

![screen shot 2017-09-21 at 9 06 14 am](https://user-images.githubusercontent.com/1254810/30700076-248572c8-9eac-11e7-873f-727f1759a5cf.png)

**Comment by wmbutler** [comment]
Notice how tradingview keeps these indicators in a nice lane. It almost lookes better without the arrowed shape (just a rectangle). It would be nice for a css person to present some options here.

Side:
![screen shot 2017-09-21 at 9 15 17 am](https://user-images.githubusercontent.com/1254810/30700579-91c04254-9ead-11e7-9e0e-ce6d2cd3d470.png)

Bottom:
![screen shot 2017-09-21 at 9 16 54 am](https://user-images.githubusercontent.com/1254810/30700615-a9c0234c-9ead-11e7-8b25-1711d29e0958.png)

**Comment by svk31** [comment]
That's weird, the zoom buttons don't overlap like that on my screen.

![image](https://user-images.githubusercontent.com/6890015/30704025-aa784c26-9ef1-11e7-88ed-675015f86704.png)

**Comment by tbone-bts** [comment]
I think the issue with the left and right labels getting cut off could be solved with rounding.  For example, anything priced in fiat could be rounded to 2 decimals.  For anything else, I would consider having a limit of 8 total digits before and after the decimal combined.

**Comment by wmbutler** [comment]
@tbone-bts no, it's a css issue. ok, so this is a css issue specifically related to the Mac client I suppose.

**Comment by tbone-bts** [comment]
@wmbutler I'm not on a Mac and I see the labels getting cut off.  It looks like that happens any time there are more than 8 digits before and after the decimal combined.  

As for prices denominated in US Dollar (or other fiat currencies), that may be a separate issue but the point still stands that it would be preferable in such cases not to display so many digits after the decimal.

**Comment by wmbutler** [comment]
This is covering up the date label on the bottom. The decimal fix won't solve this. Should I break it into a separate issue?

![screen shot 2017-09-20 at 11 48 01 pm](https://user-images.githubusercontent.com/1254810/30679377-ccfa9508-9e5e-11e7-9100-666747279010.png)

**Comment by wmbutler** [comment]
Understood, the problem is not so much that it's covering the date, but that the vertical alignment is off by a few px. Note how the bottom of the g is not covered. This is a very small detail, but also should be a simple fix.

**Comment by svk31** [comment]
That's some pretty crazy nit-picking to be honest, sure it's worth it? Modifying positioning of svg elements generated by react-stockcharts probably isn't that easy.

The legend starts from the exact bottom of the x-axis as expected, and extends as far down as it needs to in order to show its content. The positioning of the x-axis labels seems irrelevant to me.

**Comment by wmbutler** [comment]
Migration to #361 TradingView will solve this.
