### ISSUE TITLE
[.5] Price need to have units like in the Price boxes below

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#433]
Price is displayed as BTS/ETH

![screen shot 2017-09-20 at 11 55 12 pm](https://user-images.githubusercontent.com/1254810/30679430-2bc555aa-9e5f-11e7-9ef1-8d7594d8b85a.png)

Do the same here:

![screen shot 2017-09-20 at 11 51 53 pm](https://user-images.githubusercontent.com/1254810/30679431-2bcc6fd4-9e5f-11e7-81bc-8b931a17e89d.png)

Make sure you account for long symbol names. TEST!!

**Comment by svk31** [comment]
It looks a bit awkard to me for long asset names but oh well. I also made the asset names consistent with the rest of the page, so bitUSD and BTC (for OPEN.BTC).
