### ISSUE TITLE
Make Icons for Explorer and Help and Move Them Out of the Settings Gear Menu

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#436]
The gear icon has come to refer to Settings in modern programs and it is used properly for this in the BitShares GUI but clicking on it pulls up a menu which also includes Explorer and Help, probably because they needed to go somewhere out of the way at the time...

I feel it would be cleaner to make icons for these two functions and place them next to the Settings Gear in their own right. It would make Help easier to find for new users and it would make opening Settings faster too. Icons are also cute! :-)

This was discussed more in issue #84 after it was closed.

Personally, I think icons would be better than adding more ALL CAPS tabs to the top bar. The icon for help is usually some kind of question mark. The icon for explorer could be a small version of one of the icons in the explorer section, like the Accounts one maybe.

**Comment by wmbutler** [comment]
I'm proposing a full rewrite for this menu. Closing this but noting your comments.

**Comment by landry314** [comment]
Cool, but let me add that using the Gear icon for a menu that has more than settings is not proper form these days. Help and Explore are not settings and as such should be in a different place OR the menu should not be a gear icon, in my opinion.

I also think the Explore and Help sections are a bit buried the way they are now and exposing them would help make the program feel more robust.
