### ISSUE TITLE
Explore Accounts Search Function Returns Limited Data Set

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#439]
To reproduce, go to Explore -> Accounts and type "bit" in the search field.

Since there are many names that start with "bit", what is returned is only the beginning of the set alphabetically with no means to scroll down or load more of the set. What if I need to browse to find what I am looking for?

Also, what about names that contain "bit" but don't start with "bit", like "abit" for example? Shouldn't the search include infixed strings too?

**Comment by svk31** [comment]
The search is limited by the API, which only works by searching from the start of the name, so it's not possible to get 'abit' when searching for 'bit'. If you don't see the account you're looking for, just be more specific in the search.

Scrolling works fine for me on bitshares.org/wallet:

![image](https://user-images.githubusercontent.com/6890015/30752469-aa9eeaae-9fbc-11e7-9023-15e6ffa664e9.png)

**Comment by landry314** [comment]
Yes, there is a scroll bar but it ends very quickly at "bit-bow1". There are many many more hits for this search term that are not loading... a next arrow or a "number of terms to display" would solve this.

**Comment by landry314** [comment]
You can't implement a way to load more of the hits?? Not possible?
