### ISSUE TITLE
UI/UX: Need ability to search Recent Activity

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#44]
_From @kenCode-de on March 10, 2016 15:49_

Right next to the CSV link would be a great place to put a search field. Maybe even add from/to date range fields. 

Then, ability to export just those search results to CSV would be cool too. I need to be able to quickly prove every payment that was received from someone.

_Copied from original issue: cryptonomex/graphene-ui#769_

**Comment by svk31** [comment]
_From @cryptokarnal on June 27, 2016 21:10_

Agreed, this would be very useful.

**Comment by wmbutler** [comment]
@oxarbitrage are we able to search the memo field? If not, I'll push this to December. If you und up going the elasticsearch route, this will be a cake walk.

**Comment by svk31** [comment]
Memos are encrypted so there's no way an API call can provide search functionality there.

They could be searchable in the GUI, but only in your currently downloaded transfer history, and the wallet would need to be unlocked first for it to work.

**Comment by wmbutler** [comment]
Oh, that's right...changing this to just search by:

- from
- type
- date range

**Comment by wmbutler** [comment]
@oxarbitrage checking on this again. Do you expect progress by 11/15 or should I push it to 12/1?

**Comment by oxarbitrage** [comment]
the elasticsearch plugin is being fine tuned here: https://github.com/bitshares/bitshares-core/pull/444
it is pretty much ready, all the changes proposed had been made in the last weeks but does not depend fully on me to make the merge. once merged to `develop` it will be "official" and i will document the calls needed to make this and all kind of searches inside the account history.
i hope that will be soon but can't know exactly, it is a mixture of me, @pmconrad and @abitmore that are reviewing the code.

**Comment by wmbutler** [comment]
Thanks for the updated. I'll shift this issue to 171201

**Comment by calvinfroedge** [comment]
@wmbutler @oxarbitrage @svk31 I don't think elastic search is necessary to complete this issue unless I'm missing something? The activity is already there, we just want a quick way to filter it from the interface, right?

I.e. you type and only data with matches are shown...

For the `type` attribute, this is the order type or the asset types involved?

**Comment by svk31** [comment]
Not strictly necessary but it will reduce data fetching a lot. The current API just lets you fetch something like 200 entries of history at a time, with no filtering so you'll have to fetch the entire account history.

**Comment by oxarbitrage** [comment]
exactly as @svk31 . if you are after an account with lets say 100 operations then you will be fine, problems came when you need to start looking after an account with lets say 5 million ops or even more. the time the client will need to look inside that will be so much that you will have to tell the user "hey, wait 15 mins there until i find the results that match your query", not to mention that you have to pull account in blocks of 100 ops and all the computation power those huge loops will consume.

The elasticsearch plugin is already merged to the core develop branch and i have a node of it running without problems since 2+  weeks now. it is fully ready to make all kind of searches inside account history. i communicated this to @wmbutler a few days ago and he is going to organize a call/chat session to start using this new possibilities, hope you can be there as well @calvinfroedge

**Comment by calvinfroedge** [comment]
@wmbutler @oxarbitrage @svk31 Ok, I understand, and would like to attend the chat =)

**Comment by wmbutler** [comment]
Calvin, it's all yours. I started this at 15 hours and expect it will be more. Keep us in the loop as you progress.

**Comment by wmbutler** [comment]
With ES, this should all be possible now.

**Comment by calvinfroedge** [comment]
@wmbutler Picking this back up, sorry for the wait

**Comment by wmbutler** [comment]
Great news. Please work with @oxarbitrage and @xeroc on this. Not sure if you are aware but there are now official Bitshares Foundation Nodes. Ideally, we can count on xeroc to assure us that the foundation nodes will have wrappers that point to reliable ES servers. He has a separate 5 hour issue related to this part. You will need to lead the charge to see that these wrappers and ES servers are coordinated. The Nodes need to use the elasticsearch plugin written by @oxarbitrage.

**Comment by wmbutler** [comment]
Duplicate. ES search.

**Comment by sschiessl-bcp** [comment]
Which is the duplicate issue here?

I would be interested to start on working how the elastic search database can finally be integrated from a code framework point of view.

**Comment by wmbutler** [comment]
We have a number of areas where search via ES would offer massive improvements:

- [ ] Dashboard -> Activity
- [ ] Exchange -> My Trades
- [ ] Exchange -> Market trades
- [ ] Explore -> Assets

These need to be broken into separate issues and worked. The tricky part is that they all need to be backwards compatible so if the ES server is inaccessible, the info can still be queried on-chain.
