### ISSUE TITLE
[0.5][svk] "My Markets" Tab displayes inaccurate Price for GRC

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#440]
When viewing the currencies of the BTS tab in BitShares there is a column viewing the current price of the asset. The GRC asset is not showing the correct price.

Same thing is viewable on the bitUSD list when viewing GRC.

The other assets seems to be correct, at least the ones I checked.

### **GRC/BTS**
![bitshares-priceissue-grc](https://user-images.githubusercontent.com/12114550/30776230-26c9e714-a0a3-11e7-9f9a-0ceeef213399.PNG)

### **GRC/bitUSD**
![bitshares-priceissue-grcvsbitusd](https://user-images.githubusercontent.com/12114550/30776256-859fc9f2-a0a3-11e7-888b-31bd9e6a32e5.PNG)

**Comment by svk31** [comment]
Good catch, was due to a variable that I'd forgotten to replace when updating how market stats were calculated.
