### ISSUE TITLE
[4] Can we create a QR code for a private key?

### ISSUE THREAD

**Issue by xiangxn** [bitshares/bitshares-ui#444]
Can we create a QR code for a private key?
This makes it easy for third parties to read the import private key.
I can finish the job within a business day.

**Comment by abitmore** [comment]
Sounds like something like https://github.com/steemit/condenser/pull/1364 .

For private keys, I think it's better to NOT show the QR code of private key directly, instead, we can define a workflow, for example:
* user click "show QR code" button
* the UI generate a random 6-digit number, shows to the user; or let the user input a number
* the UI encrypt the private key with this number, generate QR code of the encrypted key
* user scan the QR code with 3rd-party app
* 3rd-party app get the encrypted key from the QR code
* 3rd-party app asks for the random number
* user input the number
* 3rd-party app decrypt the key with the number, get the real private key

**Comment by abitmore** [comment]
Hmm, just found it's the workflow adopted by YOYOW (https://wallet.yoyow.org/). This issue is opened by the developer.

**Comment by xiangxn** [comment]
The QR code is optional encryption, if the password is empty is not encrypt.

**Comment by wmbutler** [comment]
This will be part of the UI rewrite as well. Fairly easy fix that needs UX.

**Comment by xiangxn** [comment]
There are several third party developers in China who have a strong demand, so I have implemented the code. Of course, you can also quickly achieve.

**Comment by abitmore** [comment]
@wmbutler IMHO this is high priority. AFAIK there is at least one mobile wallet project waiting for this feature.
@xiangxn if you have the code already, perhaps just create a pull request.

**Comment by wmbutler** [comment]
OK, I'll get this on the Sprint for 171015. I will UX it as well.

**Comment by wmbutler** [comment]
I feel like this is being made more difficult than it actually is... Why can't we import a QR code library to handle this? We can simply display the QR code when the user decides to view their private key in each of owner/active/memo.

![screen shot 2017-10-02 at 4 48 35 pm](https://user-images.githubusercontent.com/1254810/31101101-daec5890-a791-11e7-9398-3e1ca8439a89.png)

**Comment by wmbutler** [comment]
@xiangxn would like to claim this issue? If so, let me know if you think this UX is a reasonable path.

**Comment by xiangxn** [comment]
Private key QR-code should not be display directly, and should be opened each time with a different password encryption, so I think it should be at least 4 hours, and can not use the above UX.

**Comment by xiangxn** [comment]
@wmbutler If this UX, 3 hours of time is possible.

**Comment by xiangxn** [comment]
@wmbutler You can see what i have achieved the code:
https://github.com/xiangxn/bitshares-ui/blob/xn-staging/app/components/Modal/QrcodeModal.jsx

**Comment by wmbutler** [comment]
I'm not the dev, so that doesn't explain anything meaningful to me. Submit a UX before you begin work. Upgraded to 4 hours but won't assign without knowing how this is going to look first.

**Comment by xiangxn** [comment]
@wmbutler Do you think this is okay?
![1](https://user-images.githubusercontent.com/6350089/31176768-9455a538-a946-11e7-8fe0-5f4370246347.png)
![2](https://user-images.githubusercontent.com/6350089/31176781-9d4eeb18-a946-11e7-94e2-223e2dd6a0dc.png)
![3](https://user-images.githubusercontent.com/6350089/31176788-a78c190c-a946-11e7-91bf-26bd5f100a82.png)

**Comment by xiangxn** [comment]
@wmbutler If you decide to use your UX, I can finish it in 3 hours.

**Comment by wmbutler** [comment]
I don't understand the purpose of an encrypted QR code. @svk31 can you shed some light on this? Seems to me that we can just display to qr code that represents the users' private key.

**Comment by svk31** [comment]
To be honest I don't really see the point either, unless you want to print and store that qr code, in which case it makes sense to encrypt it as long as you're confident you remember the password.

For the proposed use case of transferring a private key to an app, I would assume you would do so in the privacy of your home or somewhere that doesn't require you to encrypt the qr code, but maybe that's just me. 

@abit care to comment on why it's necessary?

**Comment by xiangxn** [comment]
@wmbutler @svk31 Encryption is not for storage, but to prevent accidental storage.
Most users may print and store it.
The purpose of encryption is to, in the import process, the private key will not leak.

**Comment by wmbutler** [comment]
@xiangxn something is getting lost in translation. I don't understand your reasoning.

**Comment by xiangxn** [comment]
@wmbutler 
We just want to provide users with a qr code that can choose encryption to meet the needs of different users.

**Comment by wmbutler** [comment]
I see that you are suggesting that the encryption aspect is optional. I'd suggest re UXing this in a way that allows for the unencrypted QR code by default with a checkbox that a more savvy user might choose to encrypt the QR code.

This really requires more than one screenshot to fully communicate. Would you like for me to take a shot at it now that I understand the encryption is optional? Other questions this brings to mind:

- What encryption algorithm are you proposing?
- Why are you choosing that one in particular?
- How can a user on the other end be sure they are using the same encryption method you have chosen?

**Comment by xiangxn** [comment]
I use the AES encryption algorithm in bitsharesjs, and third-party developers can use bitsharesjs libraries, or they can implement AES decryption algorithm on their own.

**Comment by wmbutler** [comment]
ok, thanks for the explanation. I'll spend some time working out a UX for this. I think I understand all the requirements now.

**Comment by abitmore** [comment]
> I'd suggest re UXing this in a way that allows for the unencrypted QR code by default with a checkbox that a more savvy user might choose to encrypt the QR code.

@wmbutler: encrypted QR code should be default. By reading above conversation, I think you've got it. The code/password is to prevent scenarios that users accidentally stored the QR code (image) to her phone, or the image is cached by browser or another app, or synced to the cloud, or MITM, etc, lots of ways to be leaked if it's plain text. Actually I'd recommend NOT have the option to set an empty code/password.

Image that your new WIFI router has a default password; when pairing new blue-tooth devices the user will be prompted to input a short code, etc. It's not terrible UX.

**Comment by abitmore** [comment]
@xiangxn I'd recommend NOT show the text format by default, which is plain text, thus insecure.

![image](https://user-images.githubusercontent.com/9946777/31228947-7cc062a2-a9df-11e7-95a6-233f1224d322.png)

Do something like this:

![image](https://user-images.githubusercontent.com/9946777/31228839-1fddba4e-a9df-11e7-9564-a6948bb1e4b8.png)

**Comment by wmbutler** [comment]
The data over a wss:// socket is encrypted regardless of what's going on with WIFI. The private key is in the browser data whether it's being visibly displayed or not.

**Comment by abitmore** [comment]
Ok, perhaps my example aren't so suitable here. I just mean we can use a simple code in this feature. Not meant to discuss how data is transferred via WIFI.

**Comment by xiangxn** [comment]
The text of the qr code is not a default display, and the password of the wallet will be entered before the display. A hide button will be displayed, and a view button will be encrypt the qr code, as shown in the figure above.

**Comment by xiangxn** [comment]
@wmbutler  this is my BTS account: necklace
