### ISSUE TITLE
Horizontal Bar off left price indicator on Price Chart

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#447]
The horizontal indicator can be 3 different colors depending on the circumstance. I'd suggest that we remove the bar or set the color to the same color as the background in all cases. It's not particularly helpful and only serves as a distraction.

It's green!
![screen shot 2017-09-24 at 10 51 52 am](https://user-images.githubusercontent.com/1254810/30784205-baa9f258-a116-11e7-9ee2-9663e41822d8.png)

It's black!
![screen shot 2017-09-24 at 10 51 46 am](https://user-images.githubusercontent.com/1254810/30784206-baaae9b0-a116-11e7-9174-f10ec20abf42.png)

It's gray!
![screen shot 2017-09-24 at 10 51 27 am](https://user-images.githubusercontent.com/1254810/30784207-baab0594-a116-11e7-9720-fd64e2924f7c.png)

**Comment by svk31** [comment]
It's actually green but very thin so it looks black in your second screenshot, and yellow in the third. The yellow is from the recent PR where you requested the very thin columns be made another color because they looked black.

**Comment by wmbutler** [comment]
I believe we are talking about two different things. I was referring to the like that is drawn from the label to the bar. See in the third image how it runs from the side label to the top of the candle?

**Comment by wmbutler** [comment]
Closing since migrating to #361
