### ISSUE TITLE
[1][gibbsfromncis] Add operation ID to transaction history

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#450]
OpenLedger have added an "operation id" to the transaction history in their wallet. They require the ID be provided with a support request when opening a ticket relating to problems with a withdrawal. https://openledger.freshdesk.com/support/solutions/articles/33000206336-how-to-identify-withdrawal-transaction-
It would be very convenient if the desktop wallet included this (maybe hidden by default with a button to show it), because otherwise we have to jump through hoops backing up our wallets and importing the backup into OL's wallet if we need to open a ticket in response to an error with their gateway service.

**Comment by wmbutler** [comment]
It's part of the UX for the new tables. #378

**Comment by abitmore** [comment]
#378 has been closed. The ID is still not there.

**Comment by gibbsfromncis** [comment]
@wmbutler can I take this one? Where exactly the ID should be?

**Comment by wmbutler** [comment]
@gibbsfromncis please send questions to OP

**Comment by gibbsfromncis** [comment]
@Ashaman- can you provide more information? If not we will close this issue.

**Comment by abitmore** [comment]
It means adding an "operation_id" column or something similar in account history. Needs UX.

**Comment by abitmore** [comment]
To be clear, operation ID is "1.11.XXX".

**Comment by gibbsfromncis** [comment]
@abitmore okay, nice. I'll think about it and post my proposal to @wmbutler

**Comment by wmbutler** [comment]
This is a fairly easy add to activity. I don't think it requires UX.

**Comment by wmbutler** [comment]
Easy win. Somebody pick this up please.

**Comment by gibbsfromncis** [comment]
PR: #1310
