### ISSUE TITLE
[3] Non committee/witness (private) feed producers within UI?

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#452]
HERO uses private feed producers (who are not strictly members of the committee/witnesses): https://github.com/hero-global/scripts/blob/master/hero-setup.py#L24

It's possible to do this using uptick or the bitshares_python tools, but not possible to do this within the BTS UI.

**Comment by wmbutler** [comment]
"It's possible to do this"

You are going to need to be more specific. What feature are you asking for?

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
I think he means adding sources for feeds. You can see them here https://bitshares.org/wallet/#/asset/HERO but I guess he wants

```
hero.update_feed_producers([
    "blckchnd",
    "delegate.ihashfury",
    "rnglab",
    "taconator-witness",
    "verbaltech2",
    "delegate-1.lafona",
    "roelandp",
    "wackou",
    "spartako",
    "sahkan-bitshares",
])
```

to be editable in asset creation/edit in gui.

**Comment by grctest** [comment]
@o5j5vg55bv5hv5j5f8799f9 Thanks, yeah this is what I meant.

The bitshares documentation lists that only witnesses and committee members are able to publish price feed updates, but HERO has implemented a separate list of price feed publishers whom are not (AFAIK) witnesses nor committee members.

It'd something that would likely be seldomly configured, however its existence is not well documented and seems to have only been implemented within the HERO MPA.

**Comment by svk31** [comment]
It's not HERO specific, that's just an example. Any private bit asset can define their own set of feed publishers, they're just asking for that to be added to the GUI in the asset create and update screens.

**Comment by wmbutler** [comment]
Ok, so maybe I UX an area in the Asset Explorer to include the list of feed producers?

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
> Ok, so maybe I UX an area in the Asset Explorer to include the list of feed producers?

public viewable list of feed producers already exists, like **example** bottom of https://bitshares.org/wallet/#/asset/HERO 

he means specifically here https://bitshares.org/wallet/#/account/**USERNAME**/create-asset/ (substitute your own name)

**Comment by grctest** [comment]
> he means specifically here https://bitshares.org/wallet/#/account/USERNAME/create-asset/ (substitute your own name)

Yeah, a similar interface to add feed producers for a private MPA as selecting witnesses/committee members in the voting page (via a search box).

**Comment by wmbutler** [comment]
Got it. So a way to search for and build the feed producers array witihn the asset creation area. I will UX>

**Comment by wmbutler** [comment]
You can put this in place the same way you did UIA whitelisting, although you need to limit the eligible accounts to just witnesses.

**Comment by grctest** [comment]
> although you need to limit the eligible accounts to just witnesses.

How come? You can have committee & user-selected "private" publishers. Are only the witnesses available to display within the UI?

**Comment by wmbutler** [comment]
> How come? You can have committee & user-selected "private" publishers. Are only the witnesses available to display within the UI?

Ah, I did not know that.
