### ISSUE TITLE
Can we add OPEN.MUSEOL-BTS pair to GUI homepage?

### ISSUE THREAD

**Issue by philipli-yq** [bitshares/bitshares-ui#453]
OPEN.MUSEOL asset is backed 1:1 by the real MUSE on PEERTRACKS blockchain - which is a replacement asset to OPEN.MUSE.
OPEN.MUSE was one of the most actively traded asset in BTS for the past 2 years, definitely contributing more volume than some of the bitassets already listed in the "Top markets".  Can you add OPEN.MUSEOL-BTS pair to GUI homepage so people can easily access the market?  Thank you..

**Comment by mn769521** [comment]
muse is getting better and better : http://47.91.234.69/2017/09/26/muse-re-launch/      we  should do it

**Comment by grctest** [comment]
Muse abandoned their investors and the muse subforum on bitsharestalk for well over a year, they're not the best to promote by default, imo.
