### ISSUE TITLE
[4][bigspider] Italian language translation

### ISSUE THREAD

**Issue by bigspider** [bitshares/bitshares-ui#454]
Hello, is there interest for an Italian language translation? I'm a native speaker, and as I'd like to contribute in the future, that could be a good way for me to get started.

**Comment by wmbutler** [comment]
I can allocate 4 hours to the italian translation. There is a framework for it. Need any assistance?

**Comment by bigspider** [comment]
Cool, I'll start working on it!
So I will:
1. copy locales-en.js to locales-it.js and translate all the keys
2. add 'it' in 'defaults' of SettingsStore.js

Anything I missed?

**Comment by wmbutler** [comment]
@svk31 please confirm for @bigspider 

@bigspider will you have this complete prior to 10/01 or should I push to 10/15?

**Comment by svk31** [comment]
Should also add Italian to the language key of each of the other json files.

**Comment by bigspider** [comment]
@wmbutler I'm finding difficult to translate some things (meaning that I sometimes need to research on the proper translation, or understand the BitShares software itself); so let's keep it safe and push it to 10/15, if you don't mind.

**Comment by wmbutler** [comment]
Done

**Comment by bigspider** [comment]
Well, this took me quite some time more than the scheduled 4h, but it was worth it, I learnt a lot in the process.
Compared to the points above, I also added the  `require()` in `locales.js`.

**Comment by wmbutler** [comment]
How much additional time did it take you?

**Comment by bigspider** [comment]
Hard to say exactly, as I split it across many days; but I'd guess somewhere between 10 and 15 hours. But I wasn't complaining about the allocation, as there were many technical terms relative to finance or specific to BitShares that I had to research before attempting a translation.

I'll use my BitShares in Italian so I can keep updating the translations if I spot mistakes or otherwise improve them.

**Comment by wmbutler** [comment]
I'll bump it to 6 hours. Not sure I can justify more than that. But thanks for adding another language!!

**Comment by wmbutler** [comment]
Need your bitshares address for payment

**Comment by bigspider** [comment]
My address is "spider-1". Thank you!
