### ISSUE TITLE
[.5] Remove The Deprecated Trollbox and Add Support Link to Help Area

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#455]
So, we removed the Trollbox from discussion in issues #281 and #289 but now that it is no longer a Trollbox for chatting, but rather a few links to start the chat somewhere else, let's expand its usage to more general useful links and change its name from CHAT to LINKS.

I suggest adding these links as well as the ones already there:

https://bitshares.org/download/
https://cryptofresh.com/
http://bitshares-explorer.io/#/dashboard
https://github.com/bitshares/bitshares-ui/issues
https://coinmarketcap.com/currencies/bitshares/
https://www.btc123.com/market/?symbol=btc38btscny

Anyone else have any good BitShares links?

**Comment by wmbutler** [comment]
I think it's a better idea to remove this tab completely and have a support menu in a more standard location. The support should link a page outside the wallet which can then contain all these links. It doesn't make a lot of sense to have the wallet be the source of truth for this when we have the bitshares.org site.

**Comment by landry314** [comment]
Then why not rename this issue to "Remove The Deprecated Trollbox and Add Links to Help Area"?

**Comment by landry314** [comment]
@wmbutler, can you reopen this under its new title? I could create a new issue but why waste the time when we have already discussed it here?

**Comment by wmbutler** [comment]
I opened the issue here: https://github.com/bitshares/bitshares.github.io/issues/109

**Comment by wmbutler** [comment]
Concept for Account Switcher and replacement for sidebar menus. Note Support link that could call bitshares.org/support

![screen shot 2017-09-28 at 8 48 29 am](https://user-images.githubusercontent.com/1254810/30970064-d6637f26-a429-11e7-8caf-5acba0bc7523.png)

**Comment by btsfav** [comment]
> bitshares.org/support

you plan to run a support team too @wmbutler ?

**Comment by happyconcepts** [comment]
I would  recommend moving Support to the bottom of the list or even set off by a visual separator like Switch Accounts.

**Comment by happyconcepts** [comment]
About the window formerly known as the trollbox ... I suggest you consider re-purposing it instead to make a more personalized wallet experience. If I had a personal list of coin pairs that I wanted to watch, they could go here.

**Comment by wmbutler** [comment]
@btsfav that's not in my immediate plans, although the thought has crossed my mind. My point here was that we don't need to have every support option available in the wallet. Rather, we can direct people to an official support area at bitshares.org. This would also allow anyone who forks the code to change the link to their support methodology.

@happyconcepts that's just silly. Coin pair you want to watch make more sense in a watchlist that would somewhat mirror your portfolio.

**Comment by happyconcepts** [comment]
>Coin pairs you want to watch make more sense in a watchlist that would somewhat mirror your portfolio.
@wmbutler How does that make sense to duplicate my portfolio just to watch it? I am a trader so I look around for trading ideas instead of looking at my portfolio balance. 

>I would recommend moving Support to the bottom of the list or even set off by a visual separator like Switch Accounts.

Please.

**Comment by wmbutler** [comment]
I wasn't suggesting you duplicate your portfolio. I was suggesting that a watchlist has a similar data and potentially a similar layout style making it a good proximity match. You need a lot of the same fields (excluding qty and total value).

**Comment by svk31** [comment]
How do you add remove markets from this market list?

**Comment by svk31** [comment]
I gotta say I think it's quite useful to have the links to telegram and discord easily available, so if we're completely removing the chat box we need to put those links somewhere else.

**Comment by wmbutler** [comment]
I agree. That's why I was suggesting a support link that could ultimately go to the bitshares.org/support (but apparently nobody really manages it or at least I don't know who to talk to about it).

We also have the help endpoint. This page could display links to telegram and discord:

- [ ] Change Help to Support

![screen shot 2017-10-22 at 9 44 02 pm](https://user-images.githubusercontent.com/1254810/31870184-25c5e314-b772-11e7-93b9-75f21481392f.png)


![screen shot 2017-10-22 at 9 42 44 pm](https://user-images.githubusercontent.com/1254810/31870168-08b72f6c-b772-11e7-8681-4ce06be3834d.png)

**Comment by wmbutler** [comment]
Help Menu now shows Telegram and Discord.

![screen shot 2017-10-23 at 11 17 43 am](https://user-images.githubusercontent.com/1254810/31900434-ead01b5e-b7e3-11e7-81bb-1d85a7827ad9.png)

**Comment by wmbutler** [comment]
@svk31 The trollbox can be removed not that we have a link from the Help Menu.
