### ISSUE TITLE
build 2.0.170830 error 

### ISSUE THREAD

**Issue by 15963** [bitshares/bitshares-ui#456]
hello, everyone!
I build bitshares-ui, reference  address is https://github.com/bitshares/bitshares-ui/tree/2.0.170830

I get a error ,when i run this : (cd web -->npm install). 
This error is {-- UNMET PEER DEPENDENCY react-responsive-mixin@*
`                    -- UNMET PEER DEPENDENCY webpack@3.6.0}
when i ignore this error , it generate a exe file at last。
## **But this exe is in the loading page .**
help me ! thanks!

**Comment by svk31** [comment]
Those errors can be safely ignored. Did you try to simply reload the page? Ctrl+r i think it is.

**Comment by 15963** [comment]
@svk31 not ok ！ it is in the loading page.

**Comment by abitmore** [comment]
@15963 logs/errors in the web-dev console would be helpful.

**Comment by 15963** [comment]
@abitmore @svk31 
thank you! 
I build with 2.0.170915 version. It is ok!
please close this question!
