### ISSUE TITLE
[0.25] no activate button show for newly added access node

### ISSUE THREAD

**Issue by tianyekuo** [bitshares/bitshares-ui#457]
Repo:
1. setup a new witness_node
2. go to settings -> access, click "Add node"
3. input the valid node address and confirm

Issue:
The status of newly added node is "DOWN", and no activate button show when hover on it.
If fact, the new node can be access with wscat.

Don't know the mechanism yet, I guess it will wait sometime to do the sync check, which cause this issue.
PS: if i start the node at localhost on port 8090, it will wait for quit a long time until the status changes from "DOWN" to "UP".

**Comment by wmbutler** [comment]
@calvinfroedge this might be an easy win for you since you've been working on this.
