### ISSUE TITLE
[4] Asset update: Claim asset fees amount checking issue

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#46]
_From @abitmore on March 12, 2016 9:19_

When there is 1,000,000,000 fee accumulated, it's unable to claim more than 1000 each time, otherwise the "claim" button got disabled. (CER = 1,000,000 asset : 1 BTS)

_Copied from original issue: cryptonomex/graphene-ui#773_

**Comment by wmbutler** [comment]
@abitmore can you help us reproduce this?

**Comment by calvinfroedge** [comment]
@wmbutler @abitmore Need exact reproduce steps
