### ISSUE TITLE
[1][ariesjia] Better form field validation

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#460]
Closed #459 in order to create an actionable item:

- Should fail validation if account does not exist
- Should fail validation if non-numeric value is present in qty

![validate](https://user-images.githubusercontent.com/1254810/30891722-5c8aeba6-a2fa-11e7-9980-e7b0366e374e.gif)

**Comment by ariesjia** [comment]
can i take this issue .

**Comment by wmbutler** [comment]
Yes, can you please knock it out today? Really want this in the current sprint.
