### ISSUE TITLE
import a valid private key,but not import account

### ISSUE THREAD

**Issue by 15963** [bitshares/bitshares-ui#461]
my step is : settings --> Restore/import --> select import a private key --> input my private key 
-->submit --> show "Found 1 valid key." and click import keys --> pop "import a valid key"

after this ,I click "Accounts" --> it is show "this wallet does not contain any accounts" 

step error or bug?

how to do import a private key?? help me !!!!!
@abitmore @svk31

**Comment by svk31** [comment]
A valid private key does not necessarily control an account. Where is the private key from?

**Comment by 15963** [comment]
test version : 2.17.0830;
2.17.0915 version is ok!
please close this question!
@svk31

**Comment by landry314** [comment]
@15963, you can close your own issue. Look below to the left of "Comment". See "Close issue"?

**Comment by 15963** [comment]
ok!
