### ISSUE TITLE
UI to manage white and black lists for UIA and transfer approvals

### ISSUE THREAD

**Issue by bitcoiners** [bitshares/bitshares-ui#462]
Maybe I am missing something, but there seems to be no interface avaliable to manage 
white and black lists for UIA and no UI for approving transfers for assets that require it.

**Comment by svk31** [comment]
White listing works via accounts, which do have a ui available in the account section. What's missing is a way to set the whitelisting authority of an asset, but I believe there's already an open issue for that.

**Comment by bitcoiners** [comment]
There is a section for white lists, but not for UIAs.
How does a user manage lists of people allowed to hold UIA?
How about approve transfers for UIAs that mandate it?

**Comment by svk31** [comment]
You're right, there are two whitelists/blacklists. The one defined on the asset itself is for whitelisting/blacklisting markets, while the accounts whitelisted/blacklisted by the account designated as the whitelisting authority are the ones allowed to hold and trade the asset. The first one need a ui.  

There's also no ui for approving transfers for assets requiring that, that could be a new separate issue.

**Comment by wmbutler** [comment]
Bill to UX

**Comment by svk31** [comment]
Please make a new issue for approving transfers if necessary, I've added whitelist functionality to the asset update page now.

**Comment by svk31** [comment]
Since this was so similar to #70 I ended up doing both at once and moved this to the 171015 milestone.

The UX borrows heavily from the new account tables rewrite.

![image](https://user-images.githubusercontent.com/6890015/31487575-55559730-af3b-11e7-9e5b-1d1af3024d17.png)
