### ISSUE TITLE
[0.25][svk] Left OrderBook doesn't work

### ISSUE THREAD

**Issue by ruslansalikhov** [bitshares/bitshares-ui#464]
Hi

If you will try to show orders book on left side (exchange tab) - you will get this bug:

http://prntscr.com/gqfks8

**Comment by ruslansalikhov** [comment]
It is broken by this commit - https://github.com/bitshares/bitshares-ui/commit/376bffb5c11cbbf764de78ce930a7dc802f1252d

**Comment by ruslansalikhov** [comment]
Issue in this line:

http://prntscr.com/gqgbw8

Will removing this css property be good fix?

**Comment by svk31** [comment]
I never use that mode so I missed the bug, thanks.
