### ISSUE TITLE
Replace ACCOUNT -> See Open Orders with Expandable Show Open Orders

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#468]
It appears that open orders have been totaled together in one line in the ACCOUNT section to save screen space. We need to click "See open orders" to get a breakdown of all the orders on a different window.

Why not make this an expandable section within the ACCOUNT area where you click on a triangle or "SHOW OPEN ORDERS" to make it expand. This is exactly how SHOW/HIDE HIDDEN ASSETS works right now in the same area and it is nicer than a separate window.

**Comment by wmbutler** [comment]
See #378 It's going to supercede the existing layout.
