### ISSUE TITLE
[1.5] Missing wallet preferred currency on hover at total sum

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#47]
_From @btswolf on March 13, 2016 19:2_

![image](https://cloud.githubusercontent.com/assets/11035520/13730692/5f7022d2-e956-11e5-999e-a518d6a18448.png)

_Copied from original issue: cryptonomex/graphene-ui#777_

**Comment by wmbutler** [comment]
Hours: 1

**Comment by calvinfroedge** [comment]
I can take this issue
