### ISSUE TITLE
[.25] Add Label to Box Column in Find Markets

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#471]
The farmost right column in Find Markets is for adding pairs to My Markets but that is not clear as it is not labeled at all. Every other column is labeled.

How about "ADD" as it is a short word and there is barely any room.

**Comment by wmbutler** [comment]
Right Justify: ADD

about the checkbox column.

![screen shot 2017-10-01 at 4 55 34 pm](https://user-images.githubusercontent.com/1254810/31059536-6aaf1f0e-a6c9-11e7-9037-4a215d495575.png)
