### ISSUE TITLE
display BTS-bitCNY  same as BTS-BitUSD!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by todasun** [bitshares/bitshares-ui#472]
Do you know what user experience is?？？？？？
How much time does it waste  to click to reverse each time   when  you enter the interface?？？？？？
How much time does it waste  to explain to new users  why the bts price is so high？？？？
it's  bts-bitcny！！！  the most used bts-cny in exchange！！！！！
not  bitCNY-bts！！！！
let bts-bitcny  same as bts-bitusd！！！

![image](https://user-images.githubusercontent.com/10720816/31047095-e3e7a55a-a636-11e7-9c75-c0d71932e40f.png)

**Comment by abitmore** [comment]
Duplicate of #413
