### ISSUE TITLE
[.25] Setup Webhook for Git Monitoring in Discord

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#476]
![](https://i.imgur.com/PvyJpTQ.png)

Please create webhook to https://www.yappybots.tk/ - so we can easily monitor activities via the github channel on discord.

**Comment by wmbutler** [comment]
I looked over at this and it was not very obvious how to set it up. Feel free to set it up and let me know what we need to do to approve events to the bot.

**Comment by btsfav** [comment]
@wmbutler you need to add it as webhook to this github. so the bot can use the data stream

**Comment by wmbutler** [comment]
@svk31 I cannot do this because I don't have access to this Repo's settings. Think you can take this?

![screen shot 2017-10-01 at 5 08 47 pm](https://user-images.githubusercontent.com/1254810/31059633-3567a2e2-a6cb-11e7-84d0-372188f9467e.png)

**Comment by svk31** [comment]
Ok, done, setup like this:

![image](https://user-images.githubusercontent.com/6890015/31068424-3ac54f5e-a758-11e7-84bd-2ef162e51157.png)

**Comment by btsfav** [comment]
@svk31  could you enable - issue comment - milestone and - release please?
