### ISSUE TITLE
Make open.EOS Default in My Markets

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#477]
I don't know who decides which pairs are defaulted to My Markets but now that Open Ledger added it, open.EOS will definitely be one people are looking for.

I had to search for it then click the box next to it to get it in the list, when I figured out what this box did as I discuss in issue #471.

Maybe even put it in the Dashboard, it will be big...

**Comment by landry314** [comment]
I hope these commits are merged before the new release today!

I say this because they were not added to the 171001 milestone (or any milestone).

https://github.com/bitshares/bitshares-ui/milestone/4

**Comment by svk31** [comment]
They were indeed, I've just started building binaries now but it's late here so I won't be able to publish before tomorrow morning.
