### ISSUE TITLE
[.1] Font for bitCNY Different in the Total and Fee Fields in EXCHANGE

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#478]
Steps to Reproduce:

1) Make sure you have bitCNY in your Balances
2) Put all BTS or any other assets you can use to pay a fee in open orders
3) Go to EXCHANGE
4) Go to any bitCNY market
5) look at the Total and Fee fields

In the Total field you see a lowercase ALL CAPS font for "bit".
In the Fee field you see a lowercase regular font for "bit".

**Comment by baidang201** [comment]
so we should change Total field, Fee field  to  lowercase ALL CAPS  for "bit"?

**Comment by wmbutler** [comment]
That sounds like the issue. Do you want to claim it? We are releasing on Sunday.

**Comment by landry314** [comment]
@baidang201, actually, the Total field is already correctly lowercase all caps. It is the Fee field which is not conforming to the program wide style.

**Comment by svk31** [comment]
The fee field uses an option element which cannot be styled in the way required to fix this.
