### ISSUE TITLE
[1] Max supply bug in Chrome

### ISSUE THREAD

**Issue by rwynden** [bitshares/bitshares-ui#479]
the way to recreate this likely Maximum Supply bug is this: 1) just enter a huge max supply (100... the largest you can).  2) then change the number of decimal points to 8, now 3) max supply will no longer be editable.  4) if you select it and wipe it out, when you re-enter the value you will be restricted to a much smaller max supply

Or... just watch this movie of the interaction... tx
https://www.useloom.com/share/55f57a2e79c8416c9a2f4009ca089ec1

**Comment by rwynden** [comment]
Also... once this has happened another issue crops up:

the SmartCoin and Binary Prediciton Market buttons disappear when you hover over them.  they still work, but the user experience is rather funky when that happens, because you can't see the toggle

**Comment by rwynden** [comment]
I am using Chrome Canary
Version 62.0.3171.0 (Official Build) canary (64-bit)

**Comment by rwynden** [comment]
Note: In the video, please note that i started with a number that exceeds the allowed limit, and that displays the correct error message.  --> but then i adjusted the decimal places, and later tried to edit the max limit ... that's when the bug happens, the max limit is frozen at a low value.

**Comment by calvinfroedge** [comment]
@wmbutler @rwynden en How about picking an arbitrary max supply which is known to not cause issues? Open to suggestions.

**Comment by wmbutler** [comment]
This is a really strange bug. It's not serious but it is, in fact, a bug. There must be a reason for the maximum digits. I'm not sure if it's a combination of precision and integer or not, but @xeroc can tell us what the limits of issued shares are. Once we know this, I think it's an easy bug fix. There is no reason the Maximum Supply field should become un-editable.
