### ISSUE TITLE
[2] Ignored accounts appear again after relaunch

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#48]
_From @abitmore on March 15, 2016 8:58_

It seems current size of ignore_account_list is still too small for me? After relaunched the light client, about 10 accounts appear again, other accounts are still hidden well.

_Copied from original issue: cryptonomex/graphene-ui#781_

**Comment by calvinfroedge** [comment]
@abitmore @svk31 Can we get exact reproduction steps for this issue?

**Comment by svk31** [comment]
I can't help with that I'm afraid, never seen this happen myself.

**Comment by wmbutler** [comment]
Closing since no further clarifications or comments.
