### ISSUE TITLE
[0.75][svk] Open Orders misaligned in 171001

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#480]
Something changed in the latest release:

![](https://i.imgur.com/iXdmB7T.png)

vs the older ver

![](https://i.imgur.com/4WcuRcc.png)

**Comment by landry314** [comment]
Yeah, we swapped mislabeled columns from issue #421. This must be a byproduct of that.

**Comment by wmbutler** [comment]
@svk31 do you think this warrants a hotfix to place it on the 171001 milestone?

**Comment by landry314** [comment]
![open orders misaligned](https://user-images.githubusercontent.com/6866501/31062857-c1eb883e-a6fb-11e7-8318-1d38a15aa9a9.jpg)

**Comment by svk31** [comment]
I really don't think merits a high priority label nor a hotfix release, it's just a minor visual bug.

**Comment by landry314** [comment]
In the Exchange it looks awful to have numbers overlap. In the Open Orders section in Account, that can be pushed to the next release but I feel that this is something every user will experience and it warrants a quick fix and a release of 171002 today with a few fixes including the node reload issue just solved... imho.

**Comment by btsfav** [comment]
![](https://i.imgur.com/FIbmnWQ.png)

still off in new version

**Comment by svk31** [comment]
That's not off, they're independent tables so the columns will be different between them. That whole table is going away anyway with the tables rewrite so I'm not spending any more time on this.

**Comment by wmbutler** [comment]
Agreed.
