### ISSUE TITLE
My Open Orders in EXCHANGE Has Multiple Columns Overlapping in 171001

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#481]
The open orders in My Open Orders (Edit: in the EXCHANGE) have overlapping data between the two asset value columns in most of the possible sizing of the tiles on my screen. I can adjust the window to a few sizes to fix this but most cause overlapping.

@svk31, @wmbutler - HIGH PRIORITY!! This definitely needs a hotfix for 171001.

**Comment by wmbutler** [comment]
@svk31 if you agree, I'm good adding this to the current Sprint. Feel free to add appropriate time to the fix.

**Comment by wmbutler** [comment]
@landry314 I can't duplicate this. I think right justifying all headers on this screen will be fine for now. This is a bug, but I wouldn't call it critical unless you submit a screenshot to demonstrate.

![screen shot 2017-10-01 at 7 02 40 pm](https://user-images.githubusercontent.com/1254810/31060548-3e52505e-a6db-11e7-8677-8bf4ac696acd.png)

**Comment by landry314** [comment]
I meant in the EXCHANGE in "My Open Orders".

**Comment by landry314** [comment]
![my open orders 2](https://user-images.githubusercontent.com/6866501/31063440-e562d0ec-a700-11e7-8b22-355b3dbb8f04.jpg)

**Comment by svk31** [comment]
This is a duplicate issue of #480 (because the same componet is used in both places), please check whether existing issues already cover your problem before creating new issues.

**Comment by landry314** [comment]
@svk31, I always check if the issue already exists. I did not know it was the same component because it is in a different place.
