### ISSUE TITLE
[.25] Clear certain fields AFTER a successful transfer

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#482]
If the user successfully transfers an asset, the resulting transfer form qty remains populated. This is not a good idea for forms. Ideally, all fields should be cleared.

- [x] Recipient
- [x] Quantity
- [x] Memo

![screen shot 2017-10-01 at 7 22 54 pm](https://user-images.githubusercontent.com/1254810/31060758-75c8ec98-a6de-11e7-91b8-9a3d84382b09.png)

**Comment by svk31** [comment]
Not sure why you made two issues about this :)

Closing as duplicate of #533
