### ISSUE TITLE
Changing Nodes Does Not Work Until a Program Reload

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#485]
Steps to Reproduce:

1) Go to Settings -> Access
2) Activate a different node

Notice you can not access your account, no data is coming in.

3) Reload the program

Yeah, I would guess this is related to unintended consequences from solving issue #279.

Anyone else have this issue?

**Comment by svk31** [comment]
I was testing this primarily by switching chains from main net to testnet, looks like I missed something in the reset logic when staying on the same chain.
