### ISSUE TITLE
[1] Node selection indicators

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#486]
Still, have some metric reporting issues on the Electron Wallet. This was tested on the Mac version but I'd imagine the problem exists on other platforms as well.

![access](https://user-images.githubusercontent.com/1254810/31082205-e7dd117c-a753-11e7-9155-9ceca6a8e20a.gif)

**Comment by darzuaga** [comment]
hey @wmbutler what specifically is the issue? i'm new to the group... how is this expected to function?

**Comment by wmbutler** [comment]
Pretty sure @svk31 already addressed this but I'm making sure it's added into the current build. This screen is expected to show various nodes to connect to and help the operator make a determination about the best node to connect to based upon state and latency.

**Comment by svk31** [comment]
I don't have nearly as many nodes listed as down from my computer, one reason might be that I've set a 5s timeout, so if you're not able to open a connection within 5s that node will be listed as down. I've now added a notification that tells the user a connection failed when attempting to connect to a "Down" node, and the GUI now falls back to a known working node when that happens.

![image](https://user-images.githubusercontent.com/6890015/31096546-a9b653fe-a7bc-11e7-8309-d2dfac355789.png)

**Comment by wmbutler** [comment]
As I see the latency numbers, I wonder if we should assign different threshold colors. I think green is set to a very low latency but that appears to be unachievable so maybe we should change to:

0-400ms green
401-600ms yellow
601ms+ red

I'll write this up as a separate issue but wanted to say it out loud while I was thinking about it.

**Comment by wmbutler** [comment]
Have the electron versions been rebuilt with your fix? I'm still showing the DOWN indicators.

**Comment by svk31** [comment]
No, building a 171002 release now.
