### ISSUE TITLE
[.25] Incorrect GUI version number on bitshares.org/download page

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#489]
![screen shot 2017-10-02 at 12 24 06 pm](https://user-images.githubusercontent.com/1254810/31090292-c829da0e-a76c-11e7-8422-8a17198ec4af.png)

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares.github.io/commit/af217339fe520351a154594d645cb28a177622f6
