### ISSUE TITLE
[.25] Change latency color indicator thresholds on node selection page

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#490]
As I see the latency numbers, I wonder if we should assign different threshold colors. I think green is set to a very low latency but that appears to be unachievable so maybe we should change to:

0-400ms green
401-600ms yellow
601ms+ red

I'll write this up as a separate issue but wanted to say it out loud while I was thinking about it.

**Comment by btsfav** [comment]
yeah, but is it really needed? I doubt that many users take more than 2 seconds in this screen anyways

**Comment by wmbutler** [comment]
Color coding helps some people. Remember, not everyone knows what a number means, but colors have associations that can provide meaning beyond words.

**Comment by svk31** [comment]
Fixed in https://github.com/bitshares/bitshares-ui/commit/4445b25b978630ea455613b4d3a41e935c0a05f5.

New ranges are 0-400, 400-800, 800+
