### ISSUE TITLE
Cannot create new accounts using wallet mode

### ISSUE THREAD

**Issue by codemunchies** [bitshares/bitshares-ui#492]
I'm not sure the issue is related directly to bitshares-ui because it's happening in the browser as well but when creating a new account in wallet mode I get the error "Account name should end with a digit or letter" when trying the names "testtest-123test" or "ncc-1701-d" (or anything at all).  

Sometimes I get an error that says the account name should not contain any vowels as they are reserved for non-free accounts, although this issue is not consistent in my tests.

**Comment by cleankicks11** [comment]
Sorry, im new to Github, is the issue fixed. I cannot make an account in Bitshares-ui

**Comment by wmbutler** [comment]
Get the latest version of the wallet or use: https://bitshares.org/wallet

**Comment by cleankicks11** [comment]
https://bitshares.org/wallet/#/init-error - I get this in the location bar when I got to bitshares.org/wallet and the username enter is not accepted even those I follow the on-screen prompts.

**Comment by codesynapse** [comment]
I am trying the account creation process and it is throwing uncaptured exception (is_valid_name) error.

**Comment by wmbutler** [comment]
Please check out the Telegram channel for support:

https://t.me/BitSharesDEX
