### ISSUE TITLE
Download Links on Bitshares.org Not Working 404 Error

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#493]
at https://bitshares.org/download/ the links to download are:

https://github.com/bitshares/bitshares-ui/releases/download/2.0.171001/BitShares.Setup.2.0.171002.exe

https://github.com/bitshares/bitshares-ui/releases/download/2.0.171001/BitShares-2.0.171002.dmg

but should be:

https://github.com/bitshares/bitshares-ui/releases/download/2.0.171002/BitShares.Setup.2.0.171002.exe

https://github.com/bitshares/bitshares-ui/releases/download/2.0.171002/BitShares-2.0.171002.dmg

with 171002, not 171001... they are giving 404 Errors.

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares.github.io/commit/95f1ba0255e26198ab194d4b5a7d0d6bd3918965
