### ISSUE TITLE
[.25][ashaman] Wrong bitsharestalk link on Voting->Witnesses page

### ISSUE THREAD

**Issue by johan-martensson** [bitshares/bitshares-ui#494]
The link to witness proposals on the Voting->Witnesses page https://bitsharestalk.org/index.php/board,61.0.html seems wrong. It should probably be
https://bitsharestalk.org/index.php/board,75.0.html instead.

**Comment by Ashaman-** [comment]
There appear to be several of these broken links. I'll fix this
