### ISSUE TITLE
New trade resets chart.  (zoom, pan, height, width etc.)

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#495]
Using Lightwallet-windows7-x64 (.171003)

If you zoom in/out or drag left/right from the default chart position and then a new trade goes through it automatically resets the chart to default position.  The chart should update with the new price information but the zoom, pan, height and width etc. characteristics should not be changed back to default.  Other than the new price data the chart view should not change.

**Comment by Xeldal** [comment]
I'd suggest this is a bug, not a proposed feature.  On actively traded markets this bug makes the chart unusable. Unless the proposed feature tag is just where we're storing bugs we don't care enough about right now to fix. It's not a critical bug, but still a bug.

**Comment by svk31** [comment]
Yea it's a bug that I know about, it's in the charting library we use. I submitted a fix for it that was accepted so when a new version is released we'll upgrade and it will fix this bug.

**Comment by wmbutler** [comment]
Closing this since it relies on a 3rd party.

**Comment by svk31** [comment]
If you don't mind we should keep it open and close it once react-stockcharts has been upgraded, we'll probably get duplicate reports if not.

**Comment by wmbutler** [comment]
Since we are talking about migrating to tradingview. I'll close this.
