### ISSUE TITLE
[.5] Buy/Sell makes odd assumptions

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#497]
Carefully watch this screencast. It appears that we are making some odd calculation assumptions based upon previously entered qty values.I don't think it's very wise to make these assumptions. An order should start fresh each time. In the case below, you will see that a qty of 3 open.LTC had been previously entered. After clearing all 3 values, the frontend operates under the assumption of 3 units until it is manually cleared again.

I think the solution is to start with a clean slate and only calculate the third number when at least two others have been **manually* populated.

![buy](https://user-images.githubusercontent.com/1254810/31206966-d4f04cca-a940-11e7-93a2-e47f4e70820e.gif)

**Comment by svk31** [comment]
This was an issue with the Asset class not accepting 0 as an input, it was fixed here: https://github.com/bitshares/bitshares-ui/commit/c7b6e4373212fdc7bc17d2cbfe94103aa089c372
