### ISSUE TITLE
[0.25][svk] OrderBook scroll bar(and others) should be always visible

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#498]
Using LightClient bitshares.171003 (windows7x64)

Suggestion:  make scroll bars always visible.

Currently you are able to scroll the buy and sell order books.  After scrolling, the scroll bar disappears and it may give the impression the highest bid or lowest ask is something that it is not.  In particular with the vertical orderbooks, because you can scroll so far.  The orders nearest the center can be vastly different from whats actually the highest and lowest bid/ask.

It's a minor distinction and really should be the users responsibility but it's happened to me several times looking at the book and getting confused as to why the number are so far off.  It's also easy to have mistakenly scrolled one of the books while trying to scroll the main page.  Having the scroll bar always visible is an easy clue.  

Should be an easy fix that adds a good deal of UX benefit.  Just make the scroll bar always visible.

**Comment by wmbutler** [comment]
I would disagree. I really don't like to see scroll bars when they are not actively scrolling.

**Comment by Xeldal** [comment]
Nothing to do with whether you like to see them or not.  It is a point of confusion.  There is currently no visual clue to indicate that the book is adjusted off screen.  If you don't like the minuscule bar, at least for the sake of usability get rid of the possibility to scroll.

**Comment by wmbutler** [comment]
Scrollbar visibility is determined by the browser. We have no control over this.

**Comment by Xeldal** [comment]
You are too quick to close an issue.  You must really have a thing with scroll bars?
This issue is referring to the Lightwallet.  Which browser is that?
Tested in Crome FF and Lightwallet.  The exchange screen has a scroll bar always visible for the main page and then the smaller tables have their own scrollbars that disappear.  Clearly this is not a browser controlled setting. As the code is showing both.  It is either the type of scroll bar you are using or an attribute setting. {:isVisible} or {:onHover}  If you want it you can get it.  So don't bullshit with "We have no control over this"

**Comment by svk31** [comment]
The light client is a Chromium browser so equivalent to Chrome. Scrollbars are different between operating systems which is probably why Bill can't see the difference in scrollbars, they all look the same on Macs but in Windows and Linux you'll see two differen types of scrollbars in the GUI.

The orderbook and most other tables use a special scrolling library that visually mimics the scrollbars of OSX. The reason for that is to give us better control of how and where scrolling is allowed. and also for the fact that they are hidden unless you want to use them, which makes for a much cleaner visual experience.

**Comment by Xeldal** [comment]
I agree it looks cleaner, but it is undesirable from a usability standpoint.  Look at Poloniex for example.  Their interface is very close to ours.  Their scroll bars are always visible.  They use a similar style of small and unobtrusive but always visible.  The standard windows scrollbar I agree would be huge and obnoxious.  We don't need the ability to click on the scroll bar, so it doesn't need to be big.  We just need to see it.  So we have some visual clue when we are not looking at the top of the book.

**Comment by svk31** [comment]
Decided to implement this since it's a quick fix and does make sense.

![image](https://user-images.githubusercontent.com/6890015/31600170-b7022fd0-b255-11e7-937b-6e369b4bedfd.png)
