### ISSUE TITLE
Check BTC/PTS addresses on key/balance import?

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#50]
_From @abitmore on March 15, 2016 23:49_

Latest CLI has the ability to import BTC/PTS keys. Is it possible with GUI?
See
https://github.com/cryptonomex/graphene/pull/558
https://github.com/cryptonomex/graphene/issues/557

_Copied from original issue: cryptonomex/graphene-ui#785_

**Comment by wmbutler** [comment]
This is legacy. Probably not worth the effort.
