### ISSUE TITLE
[.25] Asset explorer table alignment

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#501]
- Move publisher column to leftmost
- Align all columns and headings with numeric including % data **right justified**
- Align all columns and heading with non-numeric data **left justified**
- Exception: right justify Published column

![screen shot 2017-10-05 at 1 53 36 am](https://user-images.githubusercontent.com/1254810/31214391-8ba57a38-a970-11e7-9642-3710ff2e68dd.png)

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares-ui/commit/49d3a8d80291a216dd0c17002a859469040b3f10
