### ISSUE TITLE
[3][MikhailKavalenka] Distinguish visually between external and internal links in UI

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#504]
When going through the voting UI the other day, I noticed that internal links are the same color as external ones. For example, if you go to Voting: Workers, the link for workers (internal link to wallet documentation) should be visually distinguishable from the link to BitSharestalk, as the latter is external.

**Comment by grctest** [comment]
Same could be said for the internal documentation section.

**Comment by wmbutler** [comment]
I like to see an icon for external links usually rather than a different color.

**Comment by startailcoon** [comment]
Bumping this task as I think all external links should have this icon to notify the user that it leads to an external source. 

This icon is already in our app and used on the voting section.

This task would be to add the icon to all external links in the app, as well as the help section.
Estimated hours for this task is set to 3 hours.

![bild](https://user-images.githubusercontent.com/12114550/47260237-b1afeb00-d4b7-11e8-883c-c91159e252ba.png)

**Comment by clockworkgr** [comment]
@startailcoon are you close to implementing this on all links?

**Comment by startailcoon** [comment]
@clockworkgr no. Never assigned myself to this task. It's free for grabs. I could take a look at it if none else wishes to work on it.

**Comment by MikhailKavalenka** [comment]
@startailcoon , I can take this one.

**Comment by startailcoon** [comment]
It's yours Mikhail Kavalenka

**Comment by OpenLedgerApp** [comment]
@startailcoon please review PR
