### ISSUE TITLE
Some times I don't see full/correct list of my open orders

### ISSUE THREAD

**Issue by fractalnode** [bitshares/bitshares-ui#505]
Some times I don't see full/correct list of my open orders, when I'm in the EXCHAGE tab. 
At the same time, the correct / complete list is displayed in ACCOUNT > Open orders

**Comment by wmbutler** [comment]
@fractalnode can you please post screenshot details? If we can reproduce it, we can fix it. Thanks for the report.

**Comment by fractalnode** [comment]
atm I have 2 identical orders/ 1 pair
but a moment ago, I had 2 pairs of identical orders

![screenshot_2](https://user-images.githubusercontent.com/20418259/31260851-17247164-aa51-11e7-8a02-c13108558ea1.png)
----------------
![screenshot_3](https://user-images.githubusercontent.com/20418259/31260755-5e6f3852-aa50-11e7-90c6-5c4bea3cac1f.png)
----------------
![screenshot_1](https://user-images.githubusercontent.com/20418259/31260758-60c4af92-aa50-11e7-8633-354a47c32e3a.png)

**Comment by wmbutler** [comment]
What happens if you flip the order in your open orders screen? This seems like a precision/grouping issue

**Comment by fractalnode** [comment]
This time it does not work, I know this trick

**Comment by fractalnode** [comment]
> What happens if you flip the order in your open orders screen?
the same, no changes. Today I had the same situation 
with the difference that one was at 8000 and the other at 5000
these orders did not add up

**Comment by svk31** [comment]
Hard to fix this without any more details on how to reproduce it. Open orders are not grouped in any way so that's not the issue, although they might have been in previous releases.

**Comment by svk31** [comment]
Fixed in #578
