### ISSUE TITLE
[.5] Referral should be acknowledged by frontend with or without trailing slash

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#506]
We're currently showing openldeger as ref link under membership tab, but since they stopped following core wallet & standards we're building here, I'd like to see bitshares.org/wallet?r=ID if that's working.

* Test Reflink
* Change to bitshares.org/wallet?r=ID

**Comment by wmbutler** [comment]
Agreed, this should read: https://bitshares.org/wallet/?r=accountname

![screen shot 2017-10-06 at 12 08 05 am](https://user-images.githubusercontent.com/1254810/31263831-7c8614d0-aa2a-11e7-89fb-520bb085e238.png)

**Comment by btsfav** [comment]
@wmbutler important to test first, as far as I know the current syntax is bitshares.org/wallet?r=ID (without / between)

**Comment by wmbutler** [comment]
Pretty sure the trailing slash is required.

**Comment by btsfav** [comment]
@wmbutler just tested with bitshares.org/wallet/?r=fav account tst44 - was not assigne to my ref name.

**Comment by wmbutler** [comment]
ok, updated. That's really strange. Both should work. I'm going to add some additional time to troubleshoot this issue further because the client should properly pass referral codes through regardless of the trailing / being in place or not as demonstrated in Postman:

![params](https://user-images.githubusercontent.com/1254810/31265029-41952048-aa32-11e7-9fce-2948188cbd4c.gif)

**Comment by wmbutler** [comment]
- [ ] Test to be sure both syntax properly generates a referral.

**Comment by btsfav** [comment]
paging @xeroc may be the issue for bitshares.eu too

**Comment by xeroc** [comment]
I can confirm: this is not an issue with bitshares.eu's referral program. The webwallet does not make proper use of the referral link and the faucet cannot know ..

**Comment by wmbutler** [comment]
Critical fix @svk31

**Comment by svk31** [comment]
Looks like referrals were no longer being set properly due to a change in how the account store state was initialized. For reference the following queries are checked and can all be used:

validQueries = ["r", "ref", "referrer", "referral"]

**Comment by btsfav** [comment]
@svk31 did you change the reflink in membership tab too? (initial request)
