### ISSUE TITLE
[.25][ppitonak] Base Currency Mislabeled in Find Markets

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#508]
I spun this issue out of #499, where it got overlooked.

When using Find Markets, the first pulldown says "BASE CURRENCY" but when you choose it and then the "ASSET NAME", the market which comes up is displayed with that initial currency as the QUOTE CURRENCY.

For example, choose USD in "BASE CURRENCY" then search for BTC and choose open.BTC, what opens is BTC/USD showing a price around $4300. This is where USD is the QUOTE CURRENCY.

By the way, it is actually bitUSD, not USD, and should be changed as explained in issue #388.

**Comment by ppitonak** [comment]
@wmbutler I could fix this one

**Comment by wmbutler** [comment]
It's yours. Please be sure to post a screenshot of your completed work to ensure the OP agrees with your fix.

**Comment by ppitonak** [comment]
screenshot is in PR #510

**Comment by ppitonak** [comment]
@wmbutler the PR was merged, can this issue be closed now?

**Comment by wmbutler** [comment]
Need your bitshares address for payment
