### ISSUE TITLE
Can't send BTS from UI on converted account

### ISSUE THREAD

**Issue by jojapoppa** [bitshares/bitshares-ui#512]
Hi,

I created a new account and then converted that to wallet mode afterwards.  But this account cannot send funds.

See movie (had been working with fav in support in Discord on this one...)

Thanks!!
jojapopa

https://www.useloom.com/share/85794f17971240c1bf424602acbe0b6b

**Comment by svk31** [comment]
Did you import the active, owner and memo private keys? A console log would be more useful than a video.

**Comment by jojapoppa** [comment]
No, I didn't realize that I need to import private keys when I switch to wallet mode.

How does one generate a console log?

Thanks!!!!

**Comment by svk31** [comment]
Then you haven't "converted" to wallet mode, there's no such functionality. When you change login to wallet mode you will need to create a new wallet, which will not know anything about the account you created initially using the account mode. If you then want to move your account model account to the wallet, you will need to manually import all three private keys into the wallet.

![image](https://user-images.githubusercontent.com/6890015/31305467-ac10c338-ab3a-11e7-8c8f-d89e8d18d597.png)

So in your case there's nothing to look at in the console, but here's how anyway:

https://developers.google.com/web/tools/chrome-devtools/console/

**Comment by jojapoppa** [comment]
This really explains a lot.  Thank you.

I believe that the user experience needs some work here.  The hierarchical nature of accounts and wallets is not suggested by the current UI design at all.  Wow, that was confusing.

**Comment by wmbutler** [comment]
We agree and are working towards clarity.

**Comment by jojapoppa** [comment]
Got it.  Thank you.  :-)
