### ISSUE TITLE
Vesting Claims allow users to Pay more than they can Claim

### ISSUE THREAD

**Issue by beyondbitcoin** [bitshares/bitshares-ui#513]
### **Problem Statement**
When a recent user joins the platform they can gain "vesting" bts into a pool that comes from referring others and open markets.  Gained bitshares remain in the vesting pool until withdrawn, but there is a charge of approximately 24.27 BTS.  

In many cases, when a new user claims the funds, they are not immediately made aware that this charge is more than what they will earn by withdrawing from the pool.  

### **Proposal:**
There needs to be a warning (meaning in bold red text w/ accompanying imagery) to let these users know 
**"The current fee of ____BTS _(in this case 24.27)_ is more than you are attempting to withdraw. Would you still like to proceed?"**

**Comment by btsfav** [comment]
isn't the threshold for vesting a fee greater than 100?

**Comment by landry314** [comment]
I honestly think this should be added to the core. The blockchain should not allow the user to claim less than the claim fee.

**Comment by beyondbitcoin** [comment]
Unfortunately it is not (yet).  This came from someone who approached me because it happened to them.  They were new and said that they didnt realize it until after it was done.  nice avatar btw : P

**Comment by startailcoon** [comment]
A "simple" error message with the following text on the transaction confirmation screen would suffice, wouldn't it?

*Please note that your vesting balance quantity is less than the current transaction fee*

**Comment by startailcoon** [comment]
I can claim this

I propose that we stick with a simple error message until the bitshares-core solves this in another way.

**Comment by landry314** [comment]
The thing is, I think lifetime members get 80% back on the vesting fee itself so it get's more complicated.

**Comment by startailcoon** [comment]
Yes, they do. But as I understand It, a user has to pay ~22 BTS for the vesting transaction. 80% of that goes back to the next vesting round because of the way the system works. You could essentially claim over and over again and lose 20% each time even though the system said you have BTS to claim.

This should ofcourse be factored in.

**Comment by wmbutler** [comment]
I think we are quibbling over $1 for non-LTM and $.20 for LTM

**Comment by startailcoon** [comment]
I can take this task and submit a proposal on it

**Comment by wmbutler** [comment]
progress?

**Comment by landry314** [comment]
Now that the fee to withdraw a vesting balance is 1.85 BTS for non-lifetime members, does this matter anymore?

I think it can be closed as a wontfix.
