### ISSUE TITLE
Can't tell if funds are stored in wallet or account subsequent to wallet mode conversion.

### ISSUE THREAD

**Issue by jojapoppa** [bitshares/bitshares-ui#514]
This is an enhancement request:

I started out with the Account model (because it was easier), and then converted over to the wallet model later.  how can i verify that my funds are now stored via wallet as apposed to by account? 
 the UI looks identical... so I can't seem to tell.

I think the issue centers around the "ACCOUNT" screen UI design.  There isn't anything on the screen that shows, specifically that assets are stored in "account" or stored in "wallet".  So, subsequent to conversion you can't tell.

so the specific request is: on ACCOUNT there's "ASSET" and "ESTIMATED VALUE" columns in the UI, and there would be a new column added after that which shows that the asset is stored in an "account" or in a "wallet".  then, perhaps subsequent to fixing bug #512, I could just transfer the funds over from one to the other ... but right now, there's nothing in the UI design that would allow such an action.

(related BUG ticket is #512 )

**Comment by svk31** [comment]
You are confused about what wallets and accounts are in Bitshares, also see my response in #512 

Wallet store accounts, accounts hold funds.

Wallet model is multi-account, account model is single-account.

**Comment by wmbutler** [comment]
Yet another reasont o migrate terminology to:

Cloud Wallet
Local Wallet

**Comment by jojapoppa** [comment]
I agree.  Perhaps a simple terminology change would help.

But, the ticket has been closed.  

You know... I was shooting for an enhancement request here... not a trouble ticket.  I'm absolutely positive that a large number of users find this confusing at present.  Sooner or later, someone will need to address that.
