### ISSUE TITLE
Transaction was not signed. Do you have a private key? [no_signers]

### ISSUE THREAD

**Issue by hiquanta** [bitshares/bitshares-ui#515]
I can not trade and transfer, suggesting that it is not signed. Do you have a private key? [No_signers]

**Comment by svk31** [comment]
That means exactly what it says, that you're missing the required private key. How are you unlocking your account?

**Comment by hiquanta** [comment]
But I have imported the private key, and I use normal windows, but Ubuntu16.04 have this problem, I also installed uptick, is there a conflict

**Comment by svk31** [comment]
Check your permissions tab under Account, if your wallet includes the private keys they will be blue. Make sure you have the active and memo keys imported.

**Comment by hiquanta** [comment]
yes ,It is blue ,and I can enter my password to view my private key

**Comment by wmbutler** [comment]
Maybe you can seek help on the Telegram Channel: https://t.me/BitSharesDEX
