### ISSUE TITLE
[1] Continued issues with node stats

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#517]
This needs to be resolved and is a high priority issue. We are giving incorrect information and it causes people to mistrust the network. I'm giving it 4 hours. I really hope someone will claim this and work through it.

Nodes that are clearly active and running are being displayed as down with no latency indicators. @xeroc if you can lend a hand here, it's my opinion that this should not be delayed.

![nodes](https://user-images.githubusercontent.com/1254810/31309848-afa49a98-ab52-11e7-8020-63d274faa667.gif)

**Comment by svk31** [comment]
If a node fails the latency check then it will be listed as down, there's no way to "fix" that. My above commit updates the latency of a node that previously failed but is successful on manual activation. It also changes the latency values to just say low, medium and high latency, and increased the color ranges slightly.

**Comment by wmbutler** [comment]
Awesome. Moved this it 171009.
