### ISSUE TITLE
Remove BIT prefix from SmartCoins displayed name

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#519]
In keeping with displaying the asset names as they are in the code.  Dropping the BIT seems like the next step.  It will need some way to distinguish it as NOT an IOU or Gateway backed token though.  I'd suggest adding either the bitshares symbol before or after the Assets name or using a new symbol. 

Similar to how you have USDT as USD-Tether aka Tether USD. 
We would call it USDb or USD-Bitshares aka BitShares USD... BitUSD for short.

So you keep the short hand name.  Add the Bitshares branding to the token(USD-BitShares) when spoken about.  Simplify the impression of what it is to the user.  And you maintain consistency with naming the Asset exactly what it is in the code.  (There's no such thing as a BITUSD in the code.  No such asset exists.)  I think it would be good to start calling it USD-Bitshares as well for BitShares branding recognition.  Hearing BITUSD tells you nothing about where to find it.  who's behind it etc.  It's currently a missed opportunity to use the name BitShares.  

![](https://content.screencast.com/users/Enkianu/folders/Jing/media/d4bf8c72-e160-4d6a-a91a-209065b94209/2017-10-06_1434.png)

**Comment by wmbutler** [comment]
This will not happen. The majority of users have indicated that they need to distinguish from FIAT. I'll leave this up but will be really surprised if this garners any support.

**Comment by Xeldal** [comment]
I think it distinguishes from fiat just as well as the current naming.   Same as it distinguishes from BTC (BITBTC)  That is the purpose of including the symbol.  It's not called USD it's called USDb , with a smartcoin symbol or some other qualifier.

How does BITUSD actually distinguish any more than USDb?

As well, any actual fiat on the system will have a prefix.  Like OPEN.USD . Which also by itself does little to distinguish that it IS in fact a fiat IOU.

The whole point of SmartCoins is to mimic pegged asset.  You want it to be very clear that it is meant to be the value of USD and also clear that it is a SmartCoin and not a Fiat promise.  The name "BITUSD" does this just as well(or poorly) as "USDb" or "USD<symbol>".  I don't see the difference other than we are used to seeing it a certain way.

There are a lot of things we could do to help clarify that it is not fiat USD.  If that is the goal.  But whether the name is BitUSD or USDB I think is of little or no consequence in that regard.

**Comment by btsfav** [comment]
against it.

**Comment by iPerky** [comment]
Dropping the BIT will simplify the user experience.

All core MPAs should simply be named CNY, USD, GBP, GOLD, SILVER ...

http://cryptofresh.com is "KISS" and users understand the naming.

I see no reason why the GUI can't be the same.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
Here's a really nasty example why it can't be removed: 

bitBTC used to be called "BTC" in one of the wallets and was one of the most confusing aspects of the entire exchange.

Them being confused for real assets like BTC is a real problem, especially when users try to withdraw. Transparency and education is more important than catching people who don't know how bitUSD works to think it's just USD. Full name makes it also searchable on google for more information.

I'm more in favor of far more detail introduced describing how bitAssets work, Specifically settling process is a huge mystery usually for them. 

Mouse over tool tips are a great tool and needs more work to describe them.
I can see I can now click in left right on assets to pull up their asset page but these should really have links to wiki page or help page on bit assets, on how settling process works, and so on.

**Comment by Xeldal** [comment]
And now it's closed.  Bill has decreed he won't allow it to be fixed.
End of discussion.

**Comment by Xeldal** [comment]
An important issue such as this is given 24 hours over a weekend with little/no discussion, 6 pairs of eyes 4 of which seem to support the idea and the issue is closed?  Is this how things work around here?
