### ISSUE TITLE
No STEEM or SBD deposit/withdrawal options on desktop client

### ISSUE THREAD

**Issue by blahbax** [bitshares/bitshares-ui#520]
Hi, I thought STEEM and SBD deposit/withdrawal options had been pulled all together a couple of months ago, but a user has just informed me they can still be accessed from the web client.

Desktop Client:

![image](https://user-images.githubusercontent.com/23710592/31313620-a7ad4a9c-ac33-11e7-8286-3a2b84a1ed91.png)

Web Client:

![image](https://user-images.githubusercontent.com/23710592/31313622-bfcb531c-ac33-11e7-854d-492606d548d6.png)

Same story with the Deposit/Withdrawal page and Exchange pages: options are there on the web client, but not on the desktop.

**Comment by svk31** [comment]
Works fine in my Linux desktop client. Please not that openledger deposit withdrawal service status can change, sometimes they have wallet issues for example so a coin can be down.

Also, the deposit/withdraw links only appear in accounts you have the private keys for.

**Comment by wmbutler** [comment]
Also, make sure the desktop client is current: 171002 or newer.
