### ISSUE TITLE
Select Deposit or Withdraw before Selecting Coin

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#523]
Currently on the Deposit Withdrawal page, if you follow the instructions from left to right.  You will first select your Coin.  Then you will select whether you want to deposit or withdraw.  If the default is Deposit and you want to Withdraw, clicking the Withdraw button will reset the COIN you selected previously and you will have to select your COIN again.  Same thing happens the other way around, if the default is Withdraw and you click Deposit.

If we simply have the user select whether to Deposit of Withdraw before selecting the COIN we avoid this.  Moving the Deposit Withdraw buttons to the left of above the Coin selection should work.

**Comment by wmbutler** [comment]
This will be undergoing a huge rewrite.
