### ISSUE TITLE
Native Coins need Deposit Withdraw Info for unaware users

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#525]
Every day i see someone saying "how do I deposit BTS to my Bitshares wallet."  "There is no option in the dropdown"

I would suggest adding BTS to the drop down BUT then you'd have to add every single native coin there as well and the drop down would be a mess.  

I think a better solution would be to have a textbox filter incorporated with the dropdown.  BTS and other native coins would not show up in the drop down unless you typed text in the box.  In which case the filtered coins for the gateway would show first in the list followed by all other coins that pass the text filter(different color perhaps and seperated).  Selecting one of these would instruct the user that a gateway is not necessary and that they can simply send that coin to their BitShares account name and that no memo is necessary.

I'm amazed that so many people miss the text right there on the deposit/withdraw page that explains this but it happens all the time.

**Comment by wmbutler** [comment]
This is also being addressed here #488
