### ISSUE TITLE
[.5] Assets should not appear in Portfolio if I do not own them

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#528]
The purpose of a portfolio is to display assets that are owned by me. There are some assets that appear to be forced into my portfolio. As a reference wallet, it is not up to us to make this arbitrary decision.

![screen shot 2017-10-09 at 12 23 40 am](https://user-images.githubusercontent.com/1254810/31325965-74f4dc46-ac88-11e7-93a3-659c807195f0.png)

**Comment by svk31** [comment]
These were added as shortcuts highlighting interesting assets when I introduced the quick buy and deposit/withdraw links to that page. They had pretty universal support at the time so I'd like to have some more input on this subject.

**Comment by wmbutler** [comment]
That's fine. It's biased unfortunately and always subject to opinion. I'm not faulting you for it.

**Comment by landry314** [comment]
We have discussed some of this in the past in issue #247.

I agree with Bill; nothing should be forced into our portfolio. I would like to see the ability to add and remove permanent assets from the list.

**Comment by svk31** [comment]
Fixed here: https://github.com/bitshares/bitshares-ui/commit/8be82a6eabf8632b6ab44eab0134cb2eb4e72f16
