### ISSUE TITLE
[4] Voting: show standby witnesses and committee members

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#53]
_From @abitmore on March 31, 2016 13:13_

We should show standby witnesses and committee members in GUI, so people can vote for them.

_Copied from original issue: cryptonomex/graphene-ui#801_

**Comment by wmbutler** [comment]
Opening a discussion here. I think that all witnesses who have registered should be displayed on the witness page. 

- [ ] Display in order of descending votes.
- [ ] Display in one common list whether the witness is active or not

## Single list
Currently, there is a top list identifying those I have voted for and a bottom list identifying those I haven't voted for. This creates a problem in the UI for voting by forcing the user to scroll up and down to reaffirm who they have voted for visually. Instead, I think there should be a visual cue on on each row that indicates a vote cast/not cast. Additionally, it's important that the user knows to place the vote after making their selections.

I'll do a real mockup, but this should work for discussion:


|Support|Witness|Votes|Status|Action|
|-----|-------|-------|-------|------|
|Yes|in.abit|829,680|Active|Toggle Vote|
|Yes|wackou|806,290|Active|Toggle Vote|
|Yes|fox|803,555|Active|Toggle Vote|
|Yes|verbaltech2|799,388|Active|Toggle Vote|
|Yes|bhuz|798,168|Active|Toggle Vote|
|Yes|rnglab|760,679|Active|Toggle Vote|
|No|badwit|755,000|Active|Toggle Vote|
|Yes|xman|754,671|Active|Toggle Vote|
|Yes|billbutler|250,000|Inactive|Toggle Vote|
|Yes|bob|200,000|Inactive|Toggle Vote|
|Yes|fred|150,000|Inactive|Toggle Vote|
|Yes|sparky|10,000|Inactive|Toggle Vote|

**Comment by wmbutler** [comment]
@svk31 Is this going into the 170914 release?

**Comment by svk31** [comment]
Yes it is :)

**Comment by wmbutler** [comment]
Sweet!!
