### ISSUE TITLE
change noone to no one on registration page

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#532]
![screen shot 2017-10-09 at 1 29 20 pm](https://user-images.githubusercontent.com/1254810/31352855-e9c883fc-acf5-11e7-9436-284af9b2f0d9.png)

**Comment by kimchi-king** [comment]
Also "OHERWISE" should be "OTHERWISE"

**Comment by SmileyChris** [comment]
OHERWISE fix in #534
