### ISSUE TITLE
[20] Witness / Committee / Worker Proposal / Proxy UX

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#538]
This is a rough first attempt at voting rework, notes:

- [x] If proxy is set, All witness, committee and worker vote tabs should display the values that the proxy has voted for instead of the current account.
- [x] The lock only appears if the proxy is set.
- [x] Must click the save button to set the proxy.
- [x] Need a small save notifcation next to the save button if form is dirty on any tab.
- [x] I don't love the placement of save/cancel but can't think of anything better.
- [x] Toggle Vote controls for Witness/Committee/Workers are all replaced with small locks if proxy is set.
- [x] Lock icon next to proxy input field is invisible if no proxy is set.
- [x] Get rid of proxy list in reference wallet. It's unfair to list proxies here.
- [x] Still must be able to validate that the proxy is a valid account name before saving.
- [x] Selected vs not selected is more subtle but still clear. Bright white / Yes / Checkbox.
- [x] ~Hovering over the toggle vote icon should swap the icon to the other one, clicking should select it.~
- [x] Line number is important. It's nice to know how many active witnesses, committee members and wp's there are without manually counting.
- [x] small blue lock on each line appears in place of circlecheck/- control if proxy is set. Shown adjacent to each.

![screen shot 2017-10-10 at 1 40 34 am](https://user-images.githubusercontent.com/1254810/31372573-09b2d774-ad5c-11e7-9c2a-ab73ff85d034.png)

**Comment by wmbutler** [comment]
Committee and Worker follow the same pattern. I can UX the rest if ambiguous. The worker will likely need more work but we can come back to that later.

**Comment by svk31** [comment]
Getting rid of the proxy list will make it hard to find proxies again though.

**Comment by svk31** [comment]
Another question is what should happen to all the text, remove it?

**Comment by svk31** [comment]
@wmbutler I'd like some feedback on the workers tab please, since it's a bit different from the others. Here's my current WIP:

![image](https://user-images.githubusercontent.com/6890015/31721203-0d466c7a-b419-11e7-9654-a9cc413ff69f.png)

**Comment by wmbutler** [comment]
Sorry it took me so long to respond. Github isn't notifying my properly right now of comments. Notes:

- Remove wordy text above table
- Make 3 sections Proposed / Active / Expired
- Remove link icon from creator (but allow text to have href)
- Votes rather than Net Votes
- Remove Unclaimed Pay (not really critical to the voting screen)
- Remove **supported** column. We have a color indicator and a checkbox to indicate support
- Gray every field including Creator when worker proposal is unsupported
- "Click save to finish" text when form is dirty

![screen shot 2017-10-22 at 8 43 09 pm](https://user-images.githubusercontent.com/1254810/31868916-b3b22646-b769-11e7-82be-8ea1fa60ac49.png)

**Comment by wmbutler** [comment]
To reduce wordiness on these screens, help documentation has been updated to explain proxy/witness/committee/worker. Please provide links to each.

/help/voting/proxy
/help/voting/witness
/help/voting/committee
/help/voting/worker

**Comment by svk31** [comment]
Where would you prefer those links to be? The proxy one especially doesn't have an obvious place to go.

Oh and the "Click to save finish" text can't really go there, it works on a wide screen like in the screenshot but becomes a nightmare to manage once screens get narrower.

**Comment by wmbutler** [comment]
- [ ] Moved Click save to finish up
- [ ] Help link for proxy is in place of lock when unpopulated
- [ ] Help link for worker/committee/witness is inside the respective tab top left of table

**Comment by wmbutler** [comment]
- [ ] More padding between buttons and right edge
- [x] Looking great as usual

![screen shot 2017-10-23 at 11 45 17 pm](https://user-images.githubusercontent.com/1254810/31925140-4768a896-b84c-11e7-8f04-0a63e68daba2.png)

**Comment by wmbutler** [comment]
Smaller gap between these:

![screen shot 2017-10-23 at 11 49 22 pm](https://user-images.githubusercontent.com/1254810/31925217-da15b030-b84c-11e7-8a69-fa17a0b3c1aa.png)

**Comment by wmbutler** [comment]
We need to define criteria for a worker that has been proposed but is not yet active. Let's try:

- Today < expiration date
- Funding < 100%

![screen shot 2017-10-23 at 11 52 59 pm](https://user-images.githubusercontent.com/1254810/31925365-e2bcd622-b84d-11e7-8c13-d9227cb58b5d.png)


I find the refund400 very confusing because it has an effect on things, but it's only 73% funded. I have no idea where 73% comes from or how we should classify it.

**Comment by svk31** [comment]
The way worker funding works is that there's a certain daily budget (which was previously included above the table), and workers use up as much of that budget as they can depending on their position (amount of votes).

As of today the total daily budget is around $16300. The first three workers in your screenshot only require around $1100, leaving $15200 for the rest of the workers. However, the refund worker which is in fourth place will use up to $20800, meaning it will consume all of the remaining 15200. With respect to the maximal daily pay of the refund worker, the funding status is 15200/20800=73%.

**Comment by svk31** [comment]
The way I defined active previously is any worker that is currently in it's defined period. Proposed workers are those who have not yet reached their start date.

**Comment by wmbutler** [comment]
> As of today the total daily budget is around $16300
How do you know this?

- [ ] I don't like where I added the small help icons. Sometimes it's hard to be creative. What would you think if I just created a /help/voting endpoint and we used just the one icon that's in the proxy area?

**Comment by svk31** [comment]
No, the daily budget is calculated from the blockchain budget object, it depends on how much is in the reserve pool and how much is being paid to witnesses IIRC. Like I said above, it used to be included in the worker screen, you can see it listed above the table in one  of my screenshots above.

In terms of the budget refund and burn workers are treated exactly the same as any other workers, they consume as much of the remaining budget as they can according to their position.

Proposed to me just means they've not yet reached their starting date.

**Comment by btsfav** [comment]
worker is worker, makes no sense to split them/filter

**Comment by wmbutler** [comment]
OK,

Let's try this:

![screen shot 2017-10-25 at 6 13 58 pm](https://user-images.githubusercontent.com/1254810/32027743-52e2450a-b9b0-11e7-9276-dae8632edb32.png)

**Comment by wmbutler** [comment]
Lastly, I would disagree that an **active** proposal is determined strictly based upon date. It should be in the relevant date range **and** be receiving payouts.

- [ ] Move those workers not being paid to Proposed

**Comment by svk31** [comment]
The problem with splitting them like that is that you won't know where those 'inactive' proposals stand with respect to the active ones, you can't tell from a glance how many votes are needed to push them into active payouts.

The "Available" row at the bottom of your table will always read 0 because the refund worker will eat any available budget.

**Comment by wmbutler** [comment]
Then we need to somehow display the daily pay that is consumed by the refund worker so all the numbers add up. This is a math operation right? We owe it to the community to be able to show the details of the worker budget / ledger. The fact that we have to explain it to people is really not an acceptable solution. This is why we write code.

In my previous UX, I attempted to demonstrate how the refund400 worker set the bar for the budget. In this next iteration, I'm told that there is a budget of $16,300 with no explanation as to where that number comes from. It's probably a good thing that you are having a difficult time explaining it to me because where I come from budgets are documented and everything adds up.

If you say that the refund worker will always eat up the remainder of the budget, and that the budget remainder is 0, how will we ever communicate to others that there are eligible funds for future worker proposals? If I am someone interested in a WP, the first thing I'd want to know is: "Are there eligible funds for me to apply for?".

We can't show 0. It makes no sense. So we need an alternative. My understanding is that we have an 11,800 budget for any WP that exceeds the number of votes in the refund400 worker. Am I wrong?

Last, Just because a WP is within its effective date doesn't make it active, at least not in the eyes of whoever is supposed to be getting paid. What if we have 50 worker proposals and only one of them gets enough votes to get paid. Does it make sense to show them as active? It only makes sense to show them as proposed. These proposed workers can move to active if they get enough votes to start receiving a payout.

**Comment by btsfav** [comment]
refund is just like any other worker, it can be voted out too. 

I'd like to see the total available funds (pool) somewhere in this screen too

**Comment by svk31** [comment]
I'm not sure what else I can say to explain it, I feel like I've addressed all your points about how this works in previous comments.

The budget is defined on the blockchain level and depends on the reserve pool size, witness pay and probably the amount of fees being paid, as well as the amount being consumed by the refund worker (which simply channels worker pay back into the reserve pool).

The only reason the refund worker sets the bar is that the daily pay it asks for is higher than the total worker budget, so if a worker has less votes than refund400 it will not get paid. If refund400 is in first place, noone else gets paid.

> We can't show 0. It makes no sense. So we need an alternative. My understanding is that we have an 11,800 budget for any WP that exceeds the number of votes in the refund400 worker. Am I wrong?

Yes you're wrong. We have a total budget of 16300, if there were enough workers above refund400 to consume that, refund400 would get 0.

**Comment by svk31** [comment]
Maybe this helps, I've restored the display of the total budget, and added a column that shows how much of that budget remains as you move down the list of workers.

![image](https://user-images.githubusercontent.com/6890015/32092752-150c1760-bafa-11e7-8c5b-c8a8cbee8942.png)

**Comment by svk31** [comment]
I've implemented what I feel makes sense if we're to split the workers based on your criteria. The "Votes required to active" threshold is dynamic and just depends on the amount of votes of the worker that is currently consuming the final part of the budget, right now that is the refund400 worker.

I changed Daily Pay to say "Asking Pay" which I feel better describes the way this works. You're asking for a certain pay, but the actual pay received depends on how much of the budget remains.

![image](https://user-images.githubusercontent.com/6890015/32094094-f1e566c4-bafe-11e7-9325-e7131dc72b93.png)

Active then looks like this:

![image](https://user-images.githubusercontent.com/6890015/32094313-9f9dabc8-baff-11e7-9847-47685c6543a6.png)

**Comment by wmbutler** [comment]
This is great. I changed a few labels for brevity. Really happy with how this turned out.

**Comment by wmbutler** [comment]
- [ ] bug, greater china representative wp is missing
- [ ] Due to length of url and name, stack the proposal name and the account name

![screen shot 2017-10-30 at 11 30 15 am](https://user-images.githubusercontent.com/1254810/32182965-fcabcf4e-bd65-11e7-99e6-bfb8d1f6a188.png)

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares-ui/commit/71821f19e3619351b8ff8a06eb541880244d3971
