### ISSUE TITLE
Troll box can eat up all socket connections for firefox

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#54]
_From @dnotestein on May 5, 2016 14:58_

This results in web sites not resolving via DNS until OpenLedger web page is closed.

_Copied from original issue: cryptonomex/graphene-ui#844_

**Comment by wmbutler** [comment]
I would vote to remove the troll box completely. I think it's more trouble than it's worth. Interested in upvotes to my comment here.

**Comment by wmbutler** [comment]
#289
