### ISSUE TITLE
[1] Display Status based upon block count incrementing

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#543]
We need a foolproof way to know if a user is connected or not. We should be able to use this during troubleshooting with clients by saying: Look at the lower right corner. Does it say connected or disconnected?

- [ ] Add the footer status bar and version to the exchange screen (it's currently missing)
- [ ] Get rid of the check box icon
- [ ] Display words connected / disconnected depending upon block count incrementing. It's possible for the socket to be connected without an incrementing blockcount so the socket alone is not a foolproof indicator.

![screen shot 2017-10-10 at 8 57 20 am](https://user-images.githubusercontent.com/1254810/31391333-cf84178a-ad9b-11e7-882f-5e575b9c6672.png)

- [ ] Current Look

![screen shot 2017-10-10 at 8 57 09 am](https://user-images.githubusercontent.com/1254810/31391334-cfa019da-ad9b-11e7-8362-bb1357b8c61f.png)

- [ ] Proposed look

![screen shot 2017-10-10 at 9 22 44 am](https://user-images.githubusercontent.com/1254810/31391582-9a628f90-ad9c-11e7-9207-c6b0fe51ae44.png)
![screen shot 2017-10-10 at 9 21 38 am](https://user-images.githubusercontent.com/1254810/31391583-9a7517d2-ad9c-11e7-906d-f3f8638e55ae.png)

**Comment by svk31** [comment]
There actually is some logic to show a warning when the blockchain status is out of sync, but it appears to have been broken some time ago.

I think your version is much cleaner anyway.

The footer was hidden in the exchange to gain some vertical height.

**Comment by wmbutler** [comment]
I hope you can add the footer back because it will help us troubleshoot if the user happens to be in the exchange.

**Comment by calvinfroedge** [comment]
@wmbutler Should there be some sort of timeout logic where if a new block is not received in x seconds, we show disconnected?

Or do we show connected indefinitely as soon as block count increments the first time?

**Comment by wmbutler** [comment]
I think you should look at a 10-second interval. This would mean that if 10 seconds pass without a block increment, you would report a down condition.

Conversely, you would report and up condition if the opposite is true.

**Comment by calvinfroedge** [comment]
@svk31 Where can I check that the block count is incrementing? I can figure this out on my own but I will need more time.

**Comment by svk31** [comment]
Actually, the API node being out of sync is probably the error you're trying to capture here, and it's different from "Disconnected". If you're disconnected you'll be redirected to the init-error page.

We already have a warning message for that, but I see the logic isn't working very well. If you don't mind @calvinfroedge I can take this on.

**Comment by svk31** [comment]
I looked into why the synced prop of Footer.jsx was no longer useful and made some changes that I've just pushed, you should be able to take it from there. Synced will now become false if the latest block is more than 5s old compared to the user's local time.

**Comment by svk31** [comment]
Wanted to get this in before the deadline tomorrow so I just fixed it.
