### ISSUE TITLE
US IP blocked by OpenLedger (Faucet&API)

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#544]
> Looking at the "faucet" https://bitshares.openledger.info/, when I try to load that URL in my browser it says "Thank you for your interest in OpenLedger, but unfortunately US citizens cannot access our site."
would that matter?

we tested it with 6 proxy US IPs 2 native US IPs, no one is able to create an account, I'm not even able to connect due to init error.

* Delete OL Nodes & Faucet
* Add node wss://node.market.rudex.org
* Add Faucet (???) - there's no real alternative at this point. 
Rudex is closed source it seems, but I asked them and they're okay to use it as bandaid see https://github.com/blckchnd/rudex-ui to find the faucet adr
 ** **NOTE: Rudex is setting Proxy to self on sign-up, so this can only be a bandaid for now**

**Comment by btsfav** [comment]
here's what they get when trying to visit bitshares.openledger.info

![](https://media.discordapp.net/attachments/363995642000965633/367317098403463168/unknown.png)

**Comment by btsfav** [comment]
@svk31 @wmbutler

**Comment by btsfav** [comment]
Update: according to ronny and people on discord development it's working again.

OL as business is blocking US IPs though, so it may be wise to come up with a fallback/contingency plan asap.

**Comment by jonnybitcoin** [comment]
is openledger.io giving the same message?

**Comment by svk31** [comment]
If @xeroc has fixed the bitshares.eu faucet maybe we could use that?

**Comment by btsfav** [comment]
@svk31 bitshares.eu does auto-proxy too...

**Comment by wmbutler** [comment]
Closed since Ronny fixed it.

**Comment by btsfav** [comment]
still won't save us next time. there must be a contingency plan

**Comment by wmbutler** [comment]
Then make one.
