### ISSUE TITLE
[1] Show status message for unavailable gateway coins instead of hiding them

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#545]
Currently if a coin's wallet is disable by the gateway it is not displayed in the drop down list of available coins.

Instead, All coins should be listed but disabled coins should be marked (disabled) and greyed out and not clickable.. or clickable resulting in an explanation page regarding wallet status.

It is confusing / frightening for a user to have a coin and have it appear to be unsupported with no possibility to withdraw

#524 - Link to broad rewrite of Deposit/Withdraw page

**Comment by wmbutler** [comment]
#557
