### ISSUE TITLE
Include open.* prefix for Withdrawal and deposit screens

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#546]
![screen shot 2017-10-10 at 11 20 34 am](https://user-images.githubusercontent.com/1254810/31397987-250f5c62-adad-11e7-9870-a467f8f9a360.png)
![screen shot 2017-10-10 at 11 20 25 am](https://user-images.githubusercontent.com/1254810/31397988-25277644-adad-11e7-90b7-5fecc0630937.png)

**Comment by Xeldal** [comment]
I think the current behavior is correct.  
You wouldn't be depositing OPEN.BTC.  You'd be depositing real BTC in exchange for OPEN.BTC

yes the user is expecting to have _on deposit_ OPEN.BTC after he sends BTC, but I think that is the wrong perspective to understand the word deposit.

**Comment by wmbutler** [comment]
I think we need to be consistent in using the OPEN.* symbol within the exchange. Remember, this will eventually go away with branded exchanges.

**Comment by svk31** [comment]
Agree with xeldal on this one.
