### ISSUE TITLE
[2] If the API to openledger/rudex etc doesn't return in 10 seconds, display a down message

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#547]
- [x] The Rudex Gateway | Openledger Gateway is down or experiencing an issue.
- [x] Display a message immediately below the drop-down indicating that the gateway is down.

![screen shot 2017-10-10 at 11 43 56 am](https://user-images.githubusercontent.com/1254810/31398981-5446837c-adb0-11e7-8624-6e4f8b76b51d.png)

**Comment by calvinfroedge** [comment]
Closing issue as it has been merged
