### ISSUE TITLE
Change Book, Depth, Buy/Sell etc (directional) colors to match Market and Chart (directional) colors.  

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#548]
At one point All the colors matched with traditional Red and Green.  Then they were all changed to Orange and off-Green.  Either of these options would have been ok but now -for a long time- since the last color change only some elements were changed and they do not match. imo the are very ugly together.

Choose either the traditional Green and Red or the off-Green and Orange for every (directional) color everywhere.  The mix is ugly.

My personal preference is the traditional Green and Red. 

![](https://content.screencast.com/users/Enkianu/folders/Jing/media/898984ec-4733-4dbf-a9c3-632b9f8f302c/2017-10-10_1146.png)

![](https://content.screencast.com/users/Enkianu/folders/Jing/media/9e2c34c7-922b-4a6a-8fdc-abc21a10d559/2017-10-10_1152.png)

**Comment by svk31** [comment]
We've had this discussion before, and no I don't think those colors were ever the same.

The reasoning is still the same: there are red and greens for up/down, and there are other colors for buy/sell.

"ugly" colors are very subjective, I think they look nice for example..

**Comment by wmbutler** [comment]
I'd refer that all the color be the same red and green, but we are just disagreeing on everything today :)

**Comment by Xeldal** [comment]
I seem to remember they were but this was so long ago, maybe it bts 0.x .  I have some older pics showing a magenta (almost purple) and a teal blue.  

Doesn't matter.  The history is not important. 

There's no reason to have different colors.  The reason you've given doesn't amount to a real difference.
The up and down and buy and sell are different measures, representations, mechanics of essentially the same thing.
 
If the last price is lower than the opening price of the current candle, the candle is red. (down)  
If the price is down it is due to sell pressure.  (sell)
Down and Sell are the same thing.  Up and Buy are the same mechanism.
Lower price on chart = sell pressure = percentage down

No reason to separate these things.  The whole point of giving buy and sell a color in the first place is to correlate them to price movements and forces.

And of course.  The orange and off-green don't go well with red and green. : ) (subjective experience)

It's not that they have to be exactly the same color.  They just need to be pretty close.  Looking through various exchanges, most use the red and green scheme everywhere but often the greens and reds are very slightly different shades.  Barely noticeable.  Probably due to bars and text showing better with a lighter or darker hue.  Some exchanges don't color their orderbooks at all.  Few exchanges employ 4 obviously different colors.  And when they do -with a couple exceptions- they are at least complementary colors or used based on the color of their company logo.

**Comment by wmbutler** [comment]
Maybe we can match these to tradingview once we integrate #361

**Comment by wmbutler** [comment]
Closing this for tradingview integration
