### ISSUE TITLE
[1] open.lisk is not populated in the dropdown

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#549]
But it is in the JSON from the network request. It's possible that we are missing other currencies as well. Please review the list and ensure that the drop-down is populated with all currencies in the network request.

![screen shot 2017-10-10 at 12 47 45 pm](https://user-images.githubusercontent.com/1254810/31401743-678fda10-adb9-11e7-9564-c9ce6ec83602.png)

**Comment by btsfav** [comment]
shouldn't OL pay for this one instead?

**Comment by wmbutler** [comment]
No, OL is feeding us the data but we aren't displaying it. This is a bug in the reference wallet

**Comment by svk31** [comment]
You need to also check the active-wallets call which tells you which external blockchain wallets are actually available.

**Comment by Xeldal** [comment]
#545

**Comment by svk31** [comment]
Let's track this in #545 instead, it's more descriptive of the actual problem.
