### ISSUE TITLE
Trollbox causes high and increasing CPU usage

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#55]
_From @svk31 on May 12, 2016 6:35_

Looks like this is a Chrome/browser bug related to WebRTC connections. It has been present for quite some time but will apparently be fixed in an upcoming release, as reports are saying it's fixed in the current Chrome Canary build (v52).

https://bugs.chromium.org/p/webrtc/issues/detail?id=5733

_Copied from original issue: cryptonomex/graphene-ui#846_

**Comment by wmbutler** [comment]
Another good argument for removing the trollbox. Upvotes on this comment please.

**Comment by wmbutler** [comment]
#289

**Comment by svk31** [comment]
The trollbox is already disabled so we can close this imo.

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/29610452-778810e8-87fa-11e7-99c9-bc09a569cc8e.png)
