### ISSUE TITLE
Yellow margin orders scroll orders off screen.

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#550]
I noticed yesterday with the large margin call order on CNY that with the orderbook in Vertical position, the yellow order would occasionally disappear and then reappear.  This could be from feed price changing and toggling the order in and out of margin call or simply the feed changing the price point of margin order, but I don't think that was all it as it would remain "disappeared" for more than 3 - 6 seconds sometimes.  local network delays maybe? IDK

Occasionally when i would return to the wallet the orderbox had scrolled itself up 2 or 3 positions hiding the margin call order and/or the few orders below/above it.  (another reason to show the scroll bars at all times #498 ) 

I wasn't able to test this behavior with the horizontal layout.
I've not noticed this behavior anywhere since. Never seen it when a margin call order is not present.  

Sorry, don't have a lot of information on this one.

**Comment by wmbutler** [comment]
Closing. Please don't post issues related to the Charting. We will be moving to #361 for all these types of bugs.
