### ISSUE TITLE
[.5] Deposit Address creation should be more helpful

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#551]
- [ ] A hard reload should trigger a deposit address create for the chosen coin if there is not address currently
- [ ] Choosing a different asset from the dropdown list should trigger a "Get New Address" action if there is no address currently
- [ ] User should never see "unknown" address since we are able to detect this and generate it.

![deposit](https://user-images.githubusercontent.com/1254810/31403071-a2352b76-adbd-11e7-8a81-0e1cf736780d.gif)

**Comment by btsfav** [comment]
you can only generate if the gateway is running, so unknown or not available is right

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
yes, currently I always generate new address b/c getting an error or not is the only way to know if a gateway for that coin is working at all.

**Comment by wmbutler** [comment]
In this case, the gateway was running. Clicking "Get New Address" generated an address. Our frontend is capable of attempting to get an address if it's currently set to unknown. If the gateway is down, we have an issue to generate an error beneath the name of the gateway. Please think through things before you snap judgment comment on my posts. This takes long enough without having to come back and defend each item.

**Comment by calvinfroedge** [comment]
@wmbutler Please provide specific steps for reproducing this behavior as I was not able to.

**Comment by wmbutler** [comment]
I am having a conversation with the dev at Openledger now to determine how we might know if a particular symbol/coin on the gateway is down even if the gateway works for other coins.

**Comment by svk31** [comment]
I mentioned how in another issue, they have an API call that lists active wallets and we set the status of a coin based on that. I already added warnings for assets that are currently down here: https://github.com/bitshares/bitshares-ui/commit/fb55b69a634865aa6d41afdf0878387878a77d01

**Comment by svk31** [comment]
Both of your first points are already the case. After the changes today, coins that are not available also just display a warning message, they no longer show the "Generate new address" button.

**Comment by wmbutler** [comment]
Looks like @calvinfroedge claimed this. Can you two reconcile the bounty?

**Comment by svk31** [comment]
Not sure if we'll still see the 'unknown' message, the others should be fine already.

**Comment by calvinfroedge** [comment]
I think we should close this issue unless someone else can reproduce seeing the "Unknown" text
