### ISSUE TITLE
Suggestion: extremely brief explanation tutorial during account creation

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [bitshares/bitshares-ui#552]
Users do not understand this is a separate blockchain and how its names/addresses work.

Most frequent question in telegram is people trying to send to the DEX and not understanding how.

UI should do the job imo instead of a youtube tutorial at guiding the user in general.

Confusion between send/receive and deposit/withdraw comes from same thing.

I know some have said this might be overkill, but

I propose short tutorial, just a bit of bite sized text to guide the eyes w/o distractions and maybe colors do the trick, no major coding challenge.

![1](https://user-images.githubusercontent.com/22536095/31404990-abc43f84-adcb-11e7-8785-61d339a6f218.png)

![2](https://user-images.githubusercontent.com/22536095/31404994-af11eb50-adcb-11e7-9f82-c5258f55fb50.png)

![3](https://user-images.githubusercontent.com/22536095/31404996-b0d373aa-adcb-11e7-9130-be05085a8364.png)

![4](https://user-images.githubusercontent.com/22536095/31404999-b22f265e-adcb-11e7-934b-295cdec841b4.png)

![5](https://user-images.githubusercontent.com/22536095/31405001-b3ae087e-adcb-11e7-9496-4475aeb6b498.png)

This was my attempt at it. 

I understand it's not a priority, but maybe there will be a volunteer.

**Comment by wmbutler** [comment]
Tutorials can go on the bitshares.org site. This is out of scope for the UI.
