### ISSUE TITLE
[.25] Toggle Settings --> General --> Cloud Wallet: no

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#553]
When user uploads a restore bin file or a brainkey for Local Wallet mode.

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares-ui/commit/e49b352746148b40c25ab658ba5b35118dfd6b35
https://github.com/bitshares/bitshares-ui/commit/211b26f0d30a838b36422eb5c144481b5495c95e

Messed up the commit text on the last one there.

**Comment by landry314** [comment]
In Settings -> General, shouldn't we rename LOGIN MODE (YES, NO) to make it clearer? It seems like we tried to from the title of this but I don't see it in the new release 171015.

Or wouldn't it be better somewhere else in the system?

**Comment by svk31** [comment]
I changed it to login mode to make it more clear for uses looking for the local wallet mode. Previously there was no mention of "Local Wallet" anywhere.
