### ISSUE TITLE
[8][startailcoon] Send Modal

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#556]
There is a lot packed into this. The primary change is that the Send function is set as a modal.

## Notes
- [x] This should present well on a smart phone.
- [x] User can no longer change account from the dropdown. User should first navigate to the correct account in the wallet.
- [x] Moved all error message to top right of input field. This is to stop the shifting that we see in the BTS forms.
- [x] Available funds turns red if Quantity exceeds availability
- [x] Memo / Message is two lines that wrap.
- [x] Fee is half width
- [x] Fee shows available funds for the selected currency. This is important so the user understands why the transfer button fails to activate.
- [x] Clicking Cancel closes the modal

## Send Screen
![screen shot 2017-10-11 at 12 30 22 am](https://user-images.githubusercontent.com/1254810/31423622-8036404c-ae1b-11e7-88ca-41011b225596.png)

- [x] Clicking Transfer locks down all fields, adds the propose slider and changes the blue transfer button to a green confirm button.
- [x] Tooltip next to Propose label is a tooltip for briefly explaining propose
- [x] Clicking Confirm sends the transaction and closes the modal
- [x] Clicking cancel returns the user to the Transfer activity, leaving the modal open

## Confirm Screen
![screen shot 2017-10-15 at 5 06 01 pm](https://user-images.githubusercontent.com/1254810/31589676-31f5847a-b1cb-11e7-9a8d-de7e724bdfaf.png)

**Comment by svk31** [comment]
Where is this modal triggered from?

**Comment by wmbutler** [comment]
Currently we have a send to button which is strange because it pits whatever account you are on in the destination field. I think we need a send menu. I have designed this dropdown but we might need to have a conversation about the timing for changing the menu.

**Comment by wmbutler** [comment]
For now, call the modal from the send to button.

**Comment by abitmore** [comment]
The "send to" button is actually for sending funds to a contact / saved address / followed account, so when the original "send" modal popped up, the "from" field was left empty.

This feature should be linked to the "send" on the top (if it's still there).

By the way, the "deposit bts" button is for depositing to yourself, so "deposit bts" and "send to" should not appear at same time. This is why I always feel the "deposit bts" button is strange when we can still click to other accounts from our own wallet and then follow. So when we're finally working on the "address book" feature, we should think about how to reuse this modal.

**Comment by abitmore** [comment]
Another thing, why can't change "from" in this modal? We will no longer have multiple accounts in a wallet?

**Comment by wmbutler** [comment]
The user will navigate the appropriate account first and then choose to send. This solves many issues related to knowing which account a user is 'in'. It logically makes sense to choose the account you wish to send from before you initiate a send operation.

**Comment by abitmore** [comment]
>The user will navigate the appropriate account first and then choose to send. This solves many issues related to knowing which account a user is 'in'. It logically makes sense to choose the account you wish to send from before you initiate a send operation.

That's fine. But please remember the scenario around "send to" button (not the "send" button).

**Comment by wmbutler** [comment]
Yeah, honestly, I'm hoping to remove the side menu completely due to the problems it creates for responsive design on smaller devices. The pattern of navigating to the recipients account and then choosing 'send to' is unfamiliar and confusing to most people who use our software.

**Comment by abitmore** [comment]
Can we have another repository for a new design?

**Comment by wmbutler** [comment]
Why would we do that? That's what branches are for.

**Comment by startailcoon** [comment]
I can take this task since the Buy BTS task (#651) is soon completed.

**Comment by wmbutler** [comment]
Add to header:

Sendbeta will bring up the new user modal instead of the old Send Screen. The other button will continue to work as before.

![screen shot 2017-11-10 at 10 43 14 am](https://user-images.githubusercontent.com/1254810/32668792-3068a658-c604-11e7-9130-12f0e44faaab.png)

**Comment by startailcoon** [comment]
# Progress Tracker

### Send
- [ ] Clicking Transfer locks down all fields, adds the propose slider and changes the blue transfer button to a green confirm button.
- [ ] Tooltip next to Propose label is a tooltip for briefly explaining propose
- [ ] Clicking Confirm sends the transaction and closes the modal
- [ ] Clicking cancel returns the user to the Transfer activity, leaving the modal open

### Confirm
- [ ] Confirm Modal

### Additional Notes
- [ ] Added Header
- [ ] This should present well on a smart phone.
- [ ] User can no longer change account from the dropdown. User should first navigate to the correct account in the wallet.
- [ ] Moved all error message to top right of input field. This is to stop the shifting that we see in the BTS forms.
- [ ] Available funds turns red if Quantity exceeds availability
- [ ] Memo / Message is two lines that wrap.
- [ ] Fee is half width
- [ ] Fee shows available funds for the selected currency. This is important so the user understands why the transfer button fails to activate.
- [ ] Clicking Cancel closes the modal

**Comment by startailcoon** [comment]
I will make a slight change in the way this works, to make it work better with proposed transactions and at the same time we will retain the simplicity of the modal.

### Scenario 1 - Sending from user account to another user account
- Sending account is the current wallet account
- Viewed account is automatically filled in as receiving account, unless it's the same as the sending account.

### Scenario 2 - Proposing a transaction
- Sending account is the current wallet account.
- Viewed account is automatically filled in as receiving account, unless it's the same as the sending account.
- User toggles "Propose", which reverts sending and receiving account and changes the header to `Propose Send from {account_name}`
- If the proposed account doesn't have the asset or asset amount, the form will clear itself, otherwise it will retain the values when toggling the switch.
- Proposing account will be the current wallet account.

**Comment by wmbutler** [comment]
Well thought out. Thanks for putting the time into this.

**Comment by wmbutler** [comment]
The send modal should also:

- indicate if the recipient is in the user's contact list (followed)
- allow the user to add the recipient to the contact list (followed)

## Unknown Account state
![screen shot 2017-12-01 at 1 27 49 pm](https://user-images.githubusercontent.com/1254810/33499669-7e13947e-d69b-11e7-81c6-c91a343883f7.png)

## Known Account but not followed (clicking toggles to followed)
![screen shot 2017-12-01 at 1 25 34 pm](https://user-images.githubusercontent.com/1254810/33499715-b0fd3354-d69b-11e7-9d9e-35e1f95c337e.png)

## Known Account and followed (clicking toggles to not followed)
![screen shot 2017-12-01 at 1 25 39 pm](https://user-images.githubusercontent.com/1254810/33499688-91c85392-d69b-11e7-9723-8d563c0007a1.png)

**Comment by startailcoon** [comment]
# Progress Preview

![bitshares-sendmodal_preview1](https://user-images.githubusercontent.com/12114550/33519469-78de1ea4-d7a7-11e7-871b-14d733d7846c.gif)

**Comment by wmbutler** [comment]
Pretty awesome. I'm assuming you have a little UI work left. Really great work.

- [ ] Let's keep the bitshares blue for the send button
- [ ] Let's keep the existing button styles (sorry my mock had something different)

Probably more responsible to sweep through all the buttons at a later date.

**Comment by startailcoon** [comment]
@wmbutler regarding the confirm modal, I think that should wait for now. The confirm screen is deeply integrated with other functions and changing this would require additional work. I propose that we stick with the current confirm screen for the time being, letting the confirm screen be its own issue tracker.

**Comment by wmbutler** [comment]
A few more tweaks:

- [ ] Reduce vertical spacing between labels and input fields
- [ ] Allow contact icon to toggle to plus sign (unfollow)
- [ ] Make cancel / send buttons same width occupying half of the width each (with appropriate margins)
- [ ] Additional 5px margin on left/right of modal 

![screen shot 2017-12-03 at 10 51 51 am](https://user-images.githubusercontent.com/1254810/33527534-43fcab62-d818-11e7-87d7-ac83fda50151.png)

**Comment by startailcoon** [comment]
## Final Version
A sample of the final version.

![bitshares-sendmodal_final](https://user-images.githubusercontent.com/12114550/33528035-3333705c-d85b-11e7-9380-07e621d59c6b.gif)

**Comment by startailcoon** [comment]
All fixed
