### ISSUE TITLE
[11.5][startailcoon] Deposit Modal

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#557]
This too is a significant departure from where we've are now. There are far fewer words. It's greatly simplified.

## Notes
- [x] Entering the symbol first is more intuitive than entering the gateway first. People know which symbol they want to deposit. Since we will have multiple gateways, we can parse down the eligible gateways after knowing which symbol they plan to deposit.
- [x] Gateways will be a dropdown list containing only gateways capable of sending the chosen symbol.
- [x] The help icon should open a browser tab to the support site for the specific gateway entered.

## Successful address creation and barcode generation
![screen shot 2017-10-11 at 12 05 51 am](https://user-images.githubusercontent.com/1254810/31423082-fbbb65a2-ae17-11e7-9730-bd4e3bdfbcb6.png)

## Failure mode
- [ ] Service gateway down indicates that we cannot contact the gateway at all.
- [ ] Unable to generate address could occur for a given symbol even if the gateway is online.
- [ ] Show all symbols in the dropdown list whether they are active or not.
- [ ] Keep modal height/width fixed regardless

![screen shot 2017-10-10 at 11 53 48 pm](https://user-images.githubusercontent.com/1254810/31422910-a83ed216-ae16-11e7-99fd-33b589f04e41.png)

**Comment by clockworkgr** [comment]
It might be beneficial to also mention who the responsible party is for gateway issues and who to contact.

I know an e-mail address is currently provided but it can be made clearer with a simple disclaimer  such as 
"Service Gateway Down - Wallet unavailable. Please contact xxx@xxx or try again later"

**Comment by wmbutler** [comment]
> It might be beneficial to also mention who the responsible party is for gateway issues and who to contact.

That's what the question mark icon is for next to the word: gateway

**Comment by abitmore** [comment]
It's best to let newbies know how to deposit BTS with this UI.

**Comment by wmbutler** [comment]
> It's best to let newbies know how to deposit BTS with this UI.

Agreed. I'll add that next.

**Comment by wmbutler** [comment]
If the user types BTS for the symbol, we do not need the gateway input field. Note the additional text as well.

![screen shot 2017-10-15 at 4 11 08 pm](https://user-images.githubusercontent.com/1254810/31589210-853d474c-b1c3-11e7-93a0-8d2073209b6d.png)

**Comment by wmbutler** [comment]
Add icon/link to BTS deposit modal (pre-populate BTS in the symbol).

![screen shot 2017-10-15 at 4 24 20 pm](https://user-images.githubusercontent.com/1254810/31589343-8f4703d4-b1c5-11e7-83ef-63588dee1fb1.png)

**Comment by svk31** [comment]
So is this a replacement for the current modal used in the portfolio? Because it doesn't make sense to have asset selection in that modal since it's triggered by clicking on the asset you want to deposit..

If it's a replacement for the deposit/withdraw screen then I don't understand why they're modals. They look nice though don't get me wrong!

**Comment by abitmore** [comment]
I'd like that the SYMBOL field be a drop down box instead of an input box. Show BTS by default.

**Comment by abitmore** [comment]
> So is this a replacement for the current modal used in the portfolio? Because it doesn't make sense to have asset selection in that modal since it's triggered by clicking on the asset you want to deposit..

I image it like this: clicking on the links on the portfolio page opens this modal.

**Comment by svk31** [comment]
@wmbutler Can you please explain where these modals are supposed to be triggered from? What do they replace in the current GUI?

**Comment by wmbutler** [comment]
Ultimately they replace the extremely wordy deposit/withdraw and send screens. 

I think it makes sense to have asset selection in the modal. You will include the asset as a parameter when calling the modal so it will pre-populate.

**Comment by wmbutler** [comment]
I'm having a hard time determining where they are all triggered from. I think it'll be tough to make all the changes at once.

I have a plan for creating a menu with send withdraw deposit. What if we break deposit / withdraw into two separate buttons and have each of them call the appropriate modal. That would involve very little work and wouldn't change things too much.

**Comment by wmbutler** [comment]
@abitmore I don't think a drop-down is appropriate. There could be hundreds of symbols. I think as a bare minimum we can agree that a user needs to know the name of their symbol.

**Comment by abitmore** [comment]
@wmbutler drop-down is a good tool to avoid typos. I strongly prefer mouse-clicking over keyboard-typing, at least the most popular ones should be able to be easily selected. When talking about "deposit", we know for non-BTS assets they're provided by trusted gateways, so the quantity will be limited so far. I admit we'll need better UX when have more gateways providing more assets.

**Comment by startailcoon** [comment]
If drop down is not preferred, maybe a few tags of popular tokens/coins would be better?
Under the "Symbol" input you can have one row of tags that could be easily selected, maybe 10 most used coins sorted by volume?

**Comment by wmbutler** [comment]
@abitmore whatever a user types in will have to be validated against each currency that gateway offers. A dropdown is not the right tool for this situation. A typeahead would be a much better option and I would concede that.

**Comment by abitmore** [comment]
Yes, a typeahead would be good. When the user typed nothing, list a few pre-defined coins instead so the user can click without type.

**Comment by startailcoon** [comment]
I can take this task for the next milestone

**Comment by wmbutler** [comment]
Bill Butler, [09.12.17 14:21]
The values in the typeahead should be a UNION of all available gateways

Bill Butler, [09.12.17 14:23]
For example is all the postential gateway assets were: RUDEX.PPY, OPEN.PPY, OPEN.BTC, BRIDGE.BTC, OPEN.LTC, the typeahead would contain: PPY, BTC, LTC

Bill Butler, [09.12.17 14:23]
If the user selected, LTC, the only gateway option would be Openledger

startail, [09.12.17 14:24]
gotcha

Bill Butler, [09.12.17 14:24]
If the user selected BTC, there would be only 2 gateway options: Openledger and Crypto-Bridge

Bill Butler, [09.12.17 14:25]
The idea here is to let the user start with what they know and logically narrow their options based on what is available

Bill Butler, [09.12.17 14:25]
"I know I want to deposit LTC"

Bill Butler, [09.12.17 14:25]
Just tell me what my options are.

Bill Butler, [09.12.17 14:26]
The wallet goes about this in completely the opposite fashion now and it causes paralysis

Bill Butler, [09.12.17 14:27]
NOTE: if more than 1 gateway is available, we must force the user to select a gateway.

Bill Butler, [09.12.17 14:27]
With so few gateways, this can be a dropdown, but the default selection should be "Select preferred gateway"

Bill Butler, [09.12.17 14:28]
If there is only 1 gateway for the currency, then present that gateway

**Comment by wmbutler** [comment]
- [ ] Use ASSET instead of SYMBOL

**Comment by wmbutler** [comment]
@startailcoon tell me if you need time added to this. This really needs to go out this Sprint.

**Comment by startailcoon** [comment]
@wmbutler  I'm making this my priority this sprint. I'm planning on completing all my tasks for next sprint, or as many as I can do.

**Comment by wmbutler** [comment]
Also review this form OpenLedger just to be sure: https://github.com/bitshares/bitshares-ui/pull/923

**Comment by startailcoon** [comment]
Do we want something like this available depending on what gateway the user selects?

![image](https://user-images.githubusercontent.com/12114550/34448197-82cd8a04-eceb-11e7-8a4f-5ea3dddf398f.png)

![image](https://user-images.githubusercontent.com/12114550/34448202-91caf4e2-eceb-11e7-92b3-1e22bd39a0e2.png)

**Comment by wmbutler** [comment]
The question mark should take the user to the appropriate help area (open a new tab so they don't lose the modal).

https://github.com/bitshares/bitshares-ui/issues/631

**Comment by startailcoon** [comment]
## Progress so far
Still a few things left to fix, but the progress so far is good.

Still missing:
- Gateway `?` link
- Single gateway automatically selected
- Copy Address/Memo
- Disable QR on memo (as in Send Modal)
- Fix for double assets when more than one gateway share it (TypeAhead)
- General Layout

Here's a preview of it.

![bitshares-depositmodal](https://user-images.githubusercontent.com/12114550/34471508-f0f5f798-ef4b-11e7-9a84-29890b6cfca9.gif)

**Comment by wmbutler** [comment]
- [ ] Hide the Memo: label if no memo is used
- [ ] Do not show the QR code if a memo is required, reason: users may scan the qr code and not realize that they need a memo. We should have a warning that the memo is required as well. This should mimick the same styling as the the Buy modal when a memo is required.

Great Work!

**Comment by startailcoon** [comment]
## An updated version

Still need to do:
- [ ] overall translation code
- [ ] css styling
- [ ] code cleaning
- [ ] handling `unknown` address when gateway say it isn't disabled

![bitshares-depositmodal-2](https://user-images.githubusercontent.com/12114550/34529211-8a0ea85c-f0ab-11e7-9ceb-480e5fef8267.gif)

**Comment by startailcoon** [comment]
@wmbutler, Additional hours requested: 3 hours (10 hours total)

**Comment by wmbutler** [comment]
- [ ] Fix the height of the modal (pick a value that is tall enough to accommodate any circumstance)

Added .5 for this.

**Comment by startailcoon** [comment]
### Fixed

- [x] Fixes for modal popup issues
- [x] Ensure modal stays the same height
- [x] Ensure all themes apply
- [x] Translation fixes
- [x] Corrected links for '?'

**Comment by startailcoon** [comment]
Hotfix: #970 
~1 hour extra spent on this

**Comment by wmbutler** [comment]
@svk31 please see if you can take care of this before release. Currently the assets in the deposit modal dropdown are NOT alphabetized. Please see that this is fixed before release.

**Comment by wmbutler** [comment]
- [ ] Reduce font size enough to handle most addresses. Maybe 1 point size smaller.

<img width="468" alt="screen shot 2018-01-08 at 1 11 27 am" src="https://user-images.githubusercontent.com/1254810/34661695-010f5998-f411-11e7-922e-acf5595a5808.png">
