### ISSUE TITLE
Populate withdraw amount with a click

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#56]
_From @nmywn on May 17, 2016 14:39_

![openledger](https://cloud.githubusercontent.com/assets/18205812/15326061/d3ec8140-1c4c-11e6-9f86-612285386816.png)

_Copied from original issue: cryptonomex/graphene-ui#848_

**Comment by wmbutler** [comment]
Easy win.

**Comment by wmbutler** [comment]
Tested. This works according to the description above.

**Comment by fletchertyler914** [comment]
This functionality already appears to exist. Should we close this issue?
