### ISSUE TITLE
[5][startailcoon] "clear changes?" when moving tabs in asset updates

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#568]
This is a needed feature, it allows you to tailor many changes in one operation.

However, someone just changed the owner of his asset unknowingly by first playing with the fields, then moving to the actual tab, add change, and clicking update asset.

The tabs don't forget, so the owner change went through.

not critical and definitely not too important, but can be frustrating

![](https://i.imgur.com/VEQw0V3.gif)

Proposal: 
* When changing Tabs, popup asks if client should reset settings in current tab

**Comment by wmbutler** [comment]
This will get handled in 171101 when we switch to the new tables. Agree this is a problem.

**Comment by landry314** [comment]
also when changing markets from one trading pairs to another the same trading values from the last market remain... there are many places this is a problem. i will open new issues then if the new tables don't solve this.

**Comment by wmbutler** [comment]
Maybe ultimately we need to present a confirmation dialog of all the changes so the user has an opportunity to approve.

**Comment by wmbutler** [comment]
- [ ] I think we need to move the save button up to the top right like we have it in the Voting section.

**Comment by startailcoon** [comment]
I'll claim this

**Comment by startailcoon** [comment]
As far as I can see, this is already present in the wallet today.
The update asset button is now in the tab section and updates all changes from all tabs until it's submitted.

It seems to have been fixed as part of https://github.com/bitshares/bitshares-ui/issues/1024

**Comment by startailcoon** [comment]
### Suggestion

When you edit one tab and switch there are unsaved changes, which may or not be remembered by the user upon saving with the save button on the tab bar.

I propose to add a message whenever the user changes something, to let them know there are unsaved changes.

I need some input on a good message and placement for this. 

![bitshares-warningonchangeasset](https://user-images.githubusercontent.com/12114550/36640363-1acdf61e-1a1d-11e8-987e-ca0a75445639.gif)

**Comment by gibbsfromncis** [comment]
@startailcoon what do you think about some "warning" or "edited" icon on each tab where changes made?

**Comment by startailcoon** [comment]
@gibbsfromncis I like that idea.

> Leroy Jethro Gibbs, [25.02.18 12:44]
>@startail I've  posted one idea. I don't thing message is necessary. We can add  some icon on each tab and if user do mouseover on this Icon just display the message like "you did some changes on this tab please do not forget to save ... "
>
>Leroy Jethro Gibbs, [25.02.18 12:48]
>On this way user will know where he made changes and we don't spam with warning message. Because message like you provided mostly looks like a some error except notification
>
>startail, [25.02.18 13:14]
>that's very true. Though, I will need to track down what change was made and where it's modified then. Right now I just check if there are any modifications at all. But I do like that better.
>
>startail, [25.02.18 13:15]
>What we're actually looking for is rather a notification that there are modifications to other tabs than the current. The save/reset button will always activate whenever there are modifications.

**Comment by wmbutler** [comment]
I feel that we need something near the update asset button to complete the circle. I also think that the notification is a little wordy. Maybe @ahdigital can help here? Happy to make a small UX item for this.

**Comment by ahdigital** [comment]
@wmbutler please. I'm planing to look at this tomorrow.

**Comment by startailcoon** [comment]
I like the design proposal mockup and I'd like to work on it for this task. 

> startail:
> I'd like to set this at 5 hours since the design of this section has no tabular knowledge today. I need to split it up to track changes and what is on what tab.

**Comment by wmbutler** [comment]
UX Approved and complete. Assigned to you for 180315

**Comment by startailcoon** [comment]
# New Asset Update

Updated hours to total 5 hrs as announced after the UX work by ahdigital.

### The new asset update now
- Adds asterisk on tab settings change
- Features modal when more than one tab is updated
- Fixed "Whitelist" tab where separation wasn't working on filtered sections of the tab.

### Other changes
Started a "global." section in the translation file for things that shouldn't be put in one section since they can be used elsewhere, like "confirm" and "cancel".

## LiceCap
This licecap shows the changes including the modal. 
**NOTE** The modal overlay wasn't enabled when this was recorded, which makes the modal blend in the background. This is not the case in the final version.

![bitshares-assetupdate](https://user-images.githubusercontent.com/12114550/37258345-d6a5068e-2576-11e8-9f47-0ec617f8d808.gif)
