### ISSUE TITLE
[2][svk] Wallet does not load

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#571]
when trying to visit via incognito mode.

![](https://i.imgur.com/vPQRk5z.png)

**Comment by btsfav** [comment]
the window stays black

**Comment by svk31** [comment]
Some more info please, light wallet or website? Cloud wallet?

**Comment by btsfav** [comment]
@svk31 incognito, bitshares.org/wallet so no wallet

**Comment by btsfav** [comment]
refreshed, got some more errors

![](https://i.imgur.com/GFKdWb1.png)

**Comment by kimchi-king** [comment]
The page loads just fine when I use incognito, but there seems to be some errors showing up.
![screen shot 2017-10-12 at 7 22 53 pm](https://user-images.githubusercontent.com/32033560/31509766-e7347da0-af82-11e7-8891-d2142fd1da4a.png)

**Comment by btsfav** [comment]
replicated the error in Brave browser, NO incognito mode

![](https://i.imgur.com/ocY80Gz.png)

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
I see it not loading on chrome or firefox incognito modes. it works eventually if you refresh a few times. i also haven't seen incognito warning (which is really only relevant to "local account" anyway) for a while now that i think about it. 

![image](https://user-images.githubusercontent.com/22536095/31510014-63497efe-af51-11e7-82d1-35d4a1c02ca9.png)

**Comment by jonnybitcoin** [comment]
incognito chrome MacOS works for me

**Comment by svk31** [comment]
We might need to narrow this down to chrome versions, can you please list yours?

**Comment by btsfav** [comment]
* Version 61.0.3163.100 (Official Build) (64-bit)

* Brave | 0.18.36 x64

**Comment by svk31** [comment]
Ok that might be a lead then, v61 isn't yet available for Linux so I'm still on v60.

**Comment by btsfav** [comment]
but firefox shows errors too

**Comment by svk31** [comment]
You shouldn't use Firefox.. We used to have a warning for that, not sure where it went.

**Comment by wmbutler** [comment]
@svk31 I think this is related to the issue I had (that you couldn't replicate). I could load repeatedly and it only initialized properly for me if it his the Dallas, TX node (which has low latency for me).

#531

**Comment by wmbutler** [comment]
It's possible that #531 has resolved it but it hasn't get been released.

**Comment by btsfav** [comment]
@svk31 yea, just for reference. tested 3 browsers, everyone gave me errors. it's strange, behavior, because sometimes it works after one refresh

**Comment by wmbutler** [comment]
There is a console log showing which node it connected to. Try to discover a pattern.

**Comment by btsfav** [comment]
eu.openledger and crypto.fans

**Comment by wmbutler** [comment]
I mean to say, try to see if there is a correlation between successful connections and failed connections.

**Comment by wmbutler** [comment]
Firefox Incognito OS X
- 55.0.3 (64-bit)
- 56.0

Staging Branch

![firefox](https://user-images.githubusercontent.com/1254810/31512581-19f276f2-af51-11e7-9429-0ed509ee3d26.gif)

**Comment by svk31** [comment]
Ok I believe I've found the cause, working on a fix now. For now, an easy workaround should be to link to https://bitshares.org/wallet/#/, make sure you include the hash.

**Comment by svk31** [comment]
I fixed this for bitshares.org/wallet using a server level forwarding rule that redirects from bitshares.org/wallet to bitshares.org/wallet/#/ 

Anyone hosting a web wallet and using the hash history setup should look into doing the same for their websites. Still looking for a way to solve it in the light clients where it also happens sometimes.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
user Xeldal just reported this in telegram chat (firefox regular mode) 

I can't reproduce it in regular firefox (I have no addons, he does)

but

I reproduced it in firefox new private window

specifically https://bitshares.org/wallet

I see "Loading..." flash for a sec and then

![image](https://user-images.githubusercontent.com/22536095/31581289-f929d762-b135-11e7-9dcf-037129f2d957.png)

chrome, chrome incognito, firefox for me seem ok now.

(I don't know if it's rude to post on closed issues, but didn't seem worth opening new issue since this might just be edge case of firefox private mode)
