### ISSUE TITLE
[.25] These nodes are verifiably down

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#574]
Should we remove them from the GUI until the owners get them running again?

![screen shot 2017-10-12 at 2 55 06 pm](https://user-images.githubusercontent.com/1254810/31516249-8c7401e4-af5d-11e7-83d3-8abd8040394a.png)

**Comment by btsfav** [comment]
I guess transwiser and freedomledger are gone for good. so yes

**Comment by wmbutler** [comment]
I didn't mean to include the locally hosted one on the screengrab.

**Comment by abitmore** [comment]
I will check with bitcrab nevertheless.

**Comment by abitmore** [comment]
Update: bitcrab is in the progress of migrating API service to another domain name.
