### ISSUE TITLE
[.25] "SEE GET STARTED TIPS" Does Nothing

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#576]
In the account creation area there is a dead link called "SEE GET STARTED TIPS". It does nothing.

Work on this area done in issue #258.

**Comment by landry314** [comment]
By the way, I would call it "Getting Starting Tips" because I think it sounds better than "Get Started Tips". "Get Started" sounds harsher because it is in the imperative tense which is forceful.

**Comment by wmbutler** [comment]
Change link to say: "GETTING STARTED"

**Comment by landry314** [comment]
Ah, the link now works... maybe it didn't work for me before because of the same reason I couldn't see the new settings names in issue #592.

Meaning... updates in the software are having issues with the old library data in Mac OS... this could be another issue to deal with. What do you think, @svk31? Tell users to delete the old data or somehow refresh the cache on the install of a new version? Should I open an issue? Do you think this could have been the problem here? I just noticed the link works now so not sure if it is due to my "clean data folder" since issue #592.
