### ISSUE TITLE
[1] Show bitUSD at default balances screen

### ISSUE THREAD

**Issue by magicstone1412** [bitshares/bitshares-ui#579]
I have no bitUSD at the moment, but I wannna borrow some bitUSDs to by a desired token. But it does not show bitUSD on default balances page. I know that we can find the pair of bitUSD/Assets and borrow from that but it is not convenience. 

Therefore I would like to propose bitUSD should be show on default balances page.  

![Bitshares DEX](https://i.imgur.com/Ese3S8G.png)

**Comment by svk31** [comment]
We used to have that actually, but now in the next release we're actually removing all the assets that you don't hold from this list of assets as discussed in this issue: https://github.com/bitshares/bitshares-ui/issues/528

I tend to agree with you however that it would be nice to have some default assets show up to guide new users, could be BTS, USD, CNY and OPEN.BTC for example.

**Comment by jonnybitcoin** [comment]
Now that BitUSD doesn't show on the account page people can't borrow BitUSD. 
Well they can but they'll never find the button and it will be harder to understand
I've had to keep 0.001 in the assets I want to be showing. 

I tend to agree with svk that we need BTS, USD, CNY and OPEN.BTC their as a minimum really.

We really need to encourage borrowing and not having BitUSD listed as a default is not helpful.

**Comment by wmbutler** [comment]
I suggested that assets not be listed in portfolio unless a user holds them. I still feel that way but I do understand the need/desire to market the bitAssets.

What if we include assets in the Margin Positions area that are eligible? Once a user borrows from the Margin Position the bitUSD would show up in the portfolio. Is this a reasonable compromise?

**Comment by jonnybitcoin** [comment]
I really think at least BitUSD needs to be on the account page as thats where it makes sense to borrow from. I just made this video and realised noobs won't even be able to borrow BitUSD, its hard enough as it is.  https://www.youtube.com/watch?v=ZRdXwgtaBj8

**Comment by wmbutler** [comment]
The problem is, it's not really an accounts page, it's a portfolio page. A portfolio is representative of your personal holdings. Placing it in margin positions makes a lot more sense because it is eligible for margin. It makes sense to display it in your portfolio only if you actually hold it.

**Comment by landry314** [comment]
Right, @jonnybitcoin, but there could be many bitAssets to borrow, especially in the future when BitShares is huge and it has over 200 bitCurrencies to peg the value of every country's fiat (it will!).

Adding the defaults of bitCNY, bitUSD, and bitBTC would be helpful but for future scaling I suggest a more broad solution like a search function or alphabetized list (or both) which pops up after hitting a borrow button somewhere in Account.

**Comment by svk31** [comment]
They're the only ones that make sense though and we need liquidity and attention concentrated to those assets.

I wish Bitshares had been created with only bitUSD and bitCNY, would have made it way more successful.

**Comment by btsfav** [comment]
I think we should still display bitUSD & bitCNY - it's biased, but for the moment our best showcases

**Comment by landry314** [comment]
I agree. Maybe this compromise will help:

Let's separate My Portfolio into two areas, the first called "My Assets" or "Held Assets", and the second called "Followed Assets" which by default will hold bitUSD and bitCNY and maybe OPEN.BTC too. We should be able to hide them like before like we still can in My Portfolio. This is a relatively simple fix that will give most people what they want.

Of course, I will reference my issue #247 again here and suggest that we add a system for managing followed assets, searching for them, adding and deleting them... almost all stock trading platforms include this feature and they usually call it a "Watchlist". Now that we have a nice Portfolio here that tracks current market prices we could easily expand it to include a Watchlist feature... oh no, I feel a new issue coming on...

**Comment by landry314** [comment]
So, now I suggest my quick fix above of Held Assets and Followed Assets be scrapped in lieu of a full Watchlist as described in issue #604 if it is not too hard to implement and can be added to the 171101 milestone!

**Comment by wmbutler** [comment]
I like having a Watchlist. It can live on the Dashboard. We do have a fundamental problem with Watchlist vs Portfolio. Your portfolio just references a single asset whereas our current "star" watchlist refers to a full trading pair so this definitely needs more discussion.

It would be awesome to make a user's watchlist the same thing as the stars on the exchange page. This would create a nice link between the two and remove the complications associated with discovering markets (which I definitely want to tackle for 171115).

**Comment by jonnybitcoin** [comment]
This discussion is getting away from the crux of it. 
The main assets BTS BitUSD BitCNY OPEN.BTC should be displayed by default to make it easy for users to learn how they can easily Buy Borrow Settle Withdraw Deposit.

User friendliness and BitUSD adoption should be laser focused. We had it before,  I don't see why it was taken away.

**Comment by landry314** [comment]
@jonnybitcoin, it was taken away to close issue #528.

Unfortunately, this happened before a good replacement system was added. During the discussion of issue #247 was where the idea for a watchlist first came up and we are still working on making that happen.

Maybe it would have been better in retrospect to wait to close #528 until we were finished with the watchlist.

**Comment by jonnybitcoin** [comment]
A compromise would be to show BTS BitUSD BitCNY OPEN.BTC by default for new users (help them learn)  then those who don't wish to see can toggle hide zero balances. This is what poloniex does but for all assets.

**Comment by landry314** [comment]
Bittrex also has a "Hide Zero Balances" option in their "Wallet" but I personally don't think that would be the best way to do it. Until the Watchlist is ready though, it might be a quick fix.

**Comment by nottsmic** [comment]
Hi bitUSD should appear on my profile as default, the option to hide is there if people do not want it. I cannot borrow unless I already have some even if I go in margin positions. If it can’t stay as default why not have a borrow tab at top. Why do I have to go to exchange to borrow bitUSD

**Comment by wmbutler** [comment]
I think it makes more sense to have it in Margin Positions (because that's where you borrow things into existence, but I'm not overly concerned about this topic. We do need a definitive list of what should appear by default. So:

- bitUSD
- bitCNY
- bitBTC
- bitEUR

Is that is or is there more?

**Comment by svk31** [comment]
Ok I think we can agree to just put them under Margin Positions. I personally don't think it's worth having bitEUR there since it's a very low liquidity asset, but I suppose we can include it.

How about BTWTY and HERO?

**Comment by btsfav** [comment]
I'd rather see

### Blockchain Issued Smartcoin
bitUSD
bitCNY 

### User Issued Smartcoin
HERO
BTWTY

**Comment by nottsmic** [comment]
Could we have a drop down menu or something that lists all bit assets and you just de select the ones you don’t want? With the top 5 in volume being auto selected

**Comment by landry314** [comment]
Maybe using this list of most traded fiat currencies would help us decide which to add by default:
https://en.wikipedia.org/wiki/Template:Most_traded_currencies

As for the dropdown idea @nottsmic just mentioned, yes, this could be developed. I have been talking about this for a while. The real fix here is a system to choose which assets you like and eliminate the rest... a Watchlist... until that is coded, we can rely on defaults like we are discussing here.

**Comment by wmbutler** [comment]
I updated the complete list adding HERO and BTWTY.

**Comment by startailcoon** [comment]
I personally think we should list all borrowable assets under the Margin Positions tab, even if you don't own any. This way you can always find which assets are borrowable. Today it can take some searching to find which are and aren't.

We should **not** display any other assets in the portfolio that the user doesn't own.

We could split up the Margin Positions tab to have two tables, one for Blockchain Issued Smartcoins and one for User Issued Smartcoins, to make it more evident of the differences, if there is any(?).
