### ISSUE TITLE
[.5][happyconcepts] Annual Fee 

### ISSUE THREAD

**Issue by happyconcepts** [bitshares/bitshares-ui#580]
Is the annual fee really this expensive or just deterringly high?

And while we are here on the fee schedule UI : How about we remove BTS from the columns (hyper- repetitive) and put BTS up in the column headers instead? Open up some extra width for the number values themselves.

**Comment by svk31** [comment]
It was set like that by the committee to effectively disable it, can't quite remember the reason but there was a bug or something.

**Comment by btsfav** [comment]
and no one bought it. focus is on full membership

**Comment by happyconcepts** [comment]
Thanks, if this were a bigger issue I would suggest strikethrough for the ~~annual membership~~  and show the fee as 0 or strikethrough the actual previous price but i'm not in the vanguard, clearly.

**Comment by wmbutler** [comment]
I gave this .5 because it requires some thought and discussion.

**Comment by svk31** [comment]
A strikethrough over that entry in the fee table sounds fine to me, easy fix.

**Comment by svk31** [comment]
Sure
