### ISSUE TITLE
[1] Request: Display asset's market fees in Exchange screen.

### ISSUE THREAD

**Issue by xanoxt** [bitshares/bitshares-ui#581]
Hi.

Now that we have a team working on the User Experience, I'd like to suggest we take steps in improving the transparency of our Exchange functionality. First good step would be to display asset's market fee on the Exchange screen somewhere on the BUY/SELL widgets, as they do have a "fee" field that displays bts transaction fee, but not the market fee. Listing market fee for the asset would be great.

Also perhaps displaying it in the "Please confirm the transaction" window, would also be good.

Right now the DEX is less transparent than centralized exchanges, and we want to be better than them!

**Comment by svk31** [comment]
Market fees are only applied to a user buying an asset that has a market fee; so someone who enters a buy order for 1 OPEN.BTC would be charged a 0.2% fee, which is equivalent to 0.002 OPEN.BTC. They would then receive 1 - 0.002 OPEN.BTC, or 0.998 OPEN.BTC

There's also a max_market_fees parameter that sets an upper limit to how big the market fee can be, but Openledger has left it at the default value so it can become very high indeed. I've implemented the math and a possible version of how we could add this to the exchange page:

![image](https://user-images.githubusercontent.com/6890015/31604633-3d248f28-b264-11e7-8fba-7e40a89d22bf.png)

**Comment by landry314** [comment]
The bitshares trading fees are taken for placing and canceling a trade while the trade itself has no fee but aren't the gateway fees applied when the trade occurs (baked into the price) and not when the order gets made? I am not totally clear on this.

This leads to a complication in showing or explaining the gateway fees at the time of exchange... how would we do it so that this difference is made clear?

**Comment by svk31** [comment]
You're right and that's one reason I never showed them here earlier. The market fees simply get deducted from the amount received when buying an asset, they're applied on the fill_order operation. You think you're buying 100 but you only receive 98.

**Comment by landry314** [comment]
Right, so I totally agree with the sentiment that the fees need to be made transparent (I wasn't aware of them for a while) but also somehow clear that they are not deducted until the trade occurs. I think changing "Fee" to "Order Fee" to differentiate it is a good idea and move the Market Fee higher before the Total field to show that it is part of the total and, of course, it will be a non-editable field.

On bittrex it looks like this:

![bittrex order window](https://user-images.githubusercontent.com/6866501/31657407-96fd1554-b32e-11e7-865a-800e27319446.jpg)

**Comment by wmbutler** [comment]
> You're right and that's one reason I never showed them here earlier. The market fees simply get deducted from the amount received when buying an asset, they're applied on the fill_order operation. You think you're buying 100 but you only receive 98.

So, we should add an additional field called Market Fee for those assets that charge and additional fee and display it below the Fee.

![screen shot 2017-10-22 at 9 25 00 pm](https://user-images.githubusercontent.com/1254810/31869741-9f01028e-b76f-11e7-9e9a-9a0e67adda74.png)

**Comment by landry314** [comment]
This is exactly what Sigve commented about above: https://github.com/bitshares/bitshares-ui/issues/581#issuecomment-336830202

Fee needs to be renamed to "Order Fee" to differentiate.

**Comment by wmbutler** [comment]
- [ ] If the user decides to purchase a specific quantity of an asset, they should end up with the exact quantity they elected to purchase in their wallet once the purchase is complete. We currently are deducting market fees from the trade instead of from the user's balance.

**Comment by svk31** [comment]
That's just how it works in bitshares-core though unfortunately, the fees are subtracted from fills and not charged up front. 

Doing it the way you say means we'll have to place an order to buy 102 instead of 100 if that's what the user entered, or clicked, which will probably make it harder to match orders.

**Comment by landry314** [comment]
That is too bad :-(

**Comment by wmbutler** [comment]
@xeroc @oxarbitrage This is a nasty issue. Any creative thought on how to deal with this? Essentially, we need a way for a user to end up with 5 shares if they buy 5. The implication in this thread is that fees cannot be deducted from a users account balance but must come from the trade.

**Comment by wmbutler** [comment]
@abitmore you have any words of wisdom here?

**Comment by wmbutler** [comment]
Let's at least display the market fee. Easy win for now.
