### ISSUE TITLE
Webwallet: Scrollbar appears whith advanced features collapsed

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#582]
see ![](https://i.imgur.com/mGI2ILn.png)

**Comment by wmbutler** [comment]
Scrollbars appear when required. This is controlled by the browser, not us.

**Comment by svk31** [comment]
There's a bit of padding underneath the button that's why it appears when it does, but yea I agree with Bill.

**Comment by btsfav** [comment]
it would appear in the light client too, but it's fine there. so something's off?

**Comment by svk31** [comment]
It just depends on the height of your browser/light client window, if it's not high enough you get a scrollbar.
