### ISSUE TITLE
[2] Feature: Make Portfolio sortable

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#583]
![](https://i.imgur.com/UwPE1NO.png)

Behaviour example

Clicking Asset either sorts A-Z or Z-A

Clicking Price sorts High-Low or Low-High

**Comment by wmbutler** [comment]
Make all columns sortable.

**Comment by svk31** [comment]
I'll take this one since the values aren't readily available making it quite complicated.

**Comment by svk31** [comment]
I've added sorting for asset, price and value. I could add Qty but it doesn't really make sense to sort there.

**Comment by svk31** [comment]
Default is by value, high to low.

**Comment by btsfav** [comment]
@wmbutler @svk31 please reopen, sorting should work top-bottom and reverse. it's only one-sided at the moment

**Comment by btsfav** [comment]
edit2: nvm, two-way sorting ONLY works if you do not have assets hidden.

**Comment by landry314** [comment]
@svk31, you are right, it doesn't make sense to sort by Qty but for consistency, it might be nice to add.
