### ISSUE TITLE
[.25] Feature: Clicking "Deposit BTS" should copy your address

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#584]
see topic

**Comment by wmbutler** [comment]
Great idea. Maybe a notification can let the user know it was copied to clipboard.

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
this symbol 
![image](https://user-images.githubusercontent.com/22536095/31791249-00dbc692-b4e6-11e7-9385-7abd9f405e3a.png)

or

![image](https://user-images.githubusercontent.com/22536095/31791314-2ac951e0-b4e6-11e7-9889-a4cf743ea4d0.png)

or similar

next to your account name on very top right bar next to lock AND on left under account tab could help too so people know they can click it.

**Comment by startailcoon** [comment]
Can I claim this?

**Comment by wmbutler** [comment]
I'm going to close this issue since we have new deposit modal on the way this Sprint #557
