### ISSUE TITLE
[.5] Fields Don't Clear When Switching Between Markets in Exchange

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#586]
Not sure if this is intentional or what is the best way to do it but I personally think that when you change markets then any data in the Price, Quantity, and Total fields should be cleared. The data is no longer applicable in the new market and a mistake could be made if the user doesn't notice the old data there.

We just discussed similar problems in issues #533 (solved with #564) and #568 with data not clearing. I propose clearing old data when switching or executing commands be the standard practice.

This could also be a problem when switching accounts. Let's say I have an order ready to send in one account then I switch to check something in another. I am looking at the same order ready to go and might forget which account I am using. I just think it is safer to clear always.

**Comment by svk31** [comment]
The actual values were being cleared; just the input fields that were visually still displaying the old values.

**Comment by wmbutler** [comment]
The input fields need to be cleared. The values on one market have nothing to do with those on another market. This could cause a very nasty trade.

![but_fields](https://user-images.githubusercontent.com/1254810/31748025-e6b4b040-b435-11e7-91ac-b4aa7cac80e0.gif)

**Comment by landry314** [comment]
I'd like the point out that when switching markets the price value from the old market is usually way out of range and the buy or sell buttons are greyed out. If you hover over them it says "Invalid price". I am not sure what happens if the price and quantity happen to be in an acceptable range... maybe a trade could be made by accident?

I don't understand the difference between the "actual values" and the value in the input fields but slight alterations to the values in the field after switching markets to bring them into a range that new market could use will allow execution of a trade. The values displayed are actual data in the input fields... so...

@svk31, was this actually solved in https://github.com/bitshares/bitshares-ui/commit/702ccdc56efa2c633e3cc32f9d65ba01533269e3 or not? Bill thinks it wasn't.

**Comment by svk31** [comment]
Not sure why he reopened it and reposted the same issue :/ It was fixed already in my commit.
