### ISSUE TITLE
[.1] Download Page version should be October 15th, 2017

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#587]
![screen shot 2017-10-15 at 7 48 30 pm](https://user-images.githubusercontent.com/1254810/31591142-fdde7356-b1e1-11e7-9706-a38909dd4d5e.png)

**Comment by happyconcepts** [comment]
[https://github.com/bitshares/bitshares.github.io/pull/110/files](PR submitted)

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares.github.io/commit/f2cc330c5eed3ca431a98668ddaaa7afbcf4cef4
