### ISSUE TITLE
[.1] Discuss: Change Reserve Asset to Burn Asset

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#590]
![screen shot 2017-10-15 at 10 42 39 pm](https://user-images.githubusercontent.com/1254810/31594395-42f6f39c-b1fa-11e7-8c92-f617df02f2e7.png)

**Comment by svk31** [comment]
Makes sense to me, never liked the word Reserve anyway, just used it since that's what it's called in the bitshares-core code.

**Comment by happyconcepts** [comment]
can I please claim this 6 minute gem?

**Comment by svk31** [comment]
Sure
