### ISSUE TITLE
In order book, round up sell price and round down buy price

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#591]
For better UX, when showing order book, it's better to always round up price of sell orders, and round down price of buy orders. Just like what we've done for #562. When this is done, people will no longer find a pending buy order and a pending sell order showing in the order book have same price at same time.

**Comment by abitmore** [comment]
A bit more things to discuss. Actually, it's more tricky to round the prices showing in the "place new order" area. Let's take a new buy order as an example:
* if we round up the price of the new buy order,
  * Cons:
    * after the buy order is submitted, when it shows on the order book, the price will be rounded down, which will likely be different than the one before submit. This is somehow bad UX because it may confuse users, people may complain "why I submitted a buy order with price 1.23 but it shows 1.22 on the book".
    * sometimes when showing as same prices, the real price of new order may be slightly lower than the lowest ask on the book, thus won't match, the user may get confused.
  * Pros:
    * When clicking on the book, the price shows on the new order will be same as the one shows on the book, so the user won't get confused, thus is good UX.
    * If the price of new order if less than lowest ask, it's sure that they won't match, so the user won't get confused, thus is good UX.
* if we round down the price of the new buy order, effects are the opposite:
  * Pros:
    * after submitted an order, the showing price is "unchanged"
    * if the user submitted an buy order which shows the same price as the lowest ask, we're sure it will match
  * Cons:
    * when clicking on the order book, the price filled in the new order will be shown as lower than the one on the book, even if they can match. People may get confused.
    * sometimes when people submitted an order which shows a price lower than the lowest ask, it may still match, which may be not desired, thus is bad UX.

One way I've thought of is to display a plus sign or something near the prices that got rounded up or down, so people may be noticed, when hovering over the price more digits (higher precision) can be shown in a tool tip. However this approach may be too complicated for some users (traders).

Thoughts?

**Comment by wmbutler** [comment]
I don't fully follow, but my gut feeling says that users will accept a situation as long as they got **a better deal** than they expected. This may not be part of the argument here, but as long as the con is one of perception and the user got a more favorable deal, I do not see a problem.

**Comment by wmbutler** [comment]
I think this has largely been solved.
