### ISSUE TITLE
[.25] Change Elements within Login Mode Setting to the Names of the Two Login Modes

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#592]
In Settings -> General, we should rename "LOGIN MODE" to "CLOUD WALLET" as implied in issue #553.

**Comment by landry314** [comment]
Hitting that return key by accident when typing the title... hate that.

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/31612392-e1cebbc8-b27f-11e7-81a4-a94024c7e991.png)

What's wrong with having "login mode" and actually displaying the name of the two modes?

**Comment by landry314** [comment]
@svk31, excellent idea, Sivge, of course that is the best!

**Comment by landry314** [comment]
I think the setting should be moved higher in the list too. Certainly above Show Asset Percentages (who uses this?). I think it is important enough to be much higher in the list.

On my 13 inch laptop screen it is below the screen unless you scroll down... a little hidden.

**Comment by svk31** [comment]
My screenshot refers to the current status btw, that's what it's like in the 171015 release. I can certainly move it a bit higher.

**Comment by landry314** [comment]
Not for me! I have YES/NO and i am using 171015 which it you can see on the lower left...

I am using the Mac OS BitShares stand alone application.

![login mode yes no](https://user-images.githubusercontent.com/6866501/31618164-7555dc94-b291-11e7-89c4-23f9761f9f52.jpg)

**Comment by svk31** [comment]
Might be an issue with saved default values, try clearing the `__graphene__defaults_v1` key in dev console Application -> Local Storage

**Comment by landry314** [comment]
yes, deleting the library folder solved it, thanks!

I think the work "Login" after each Login Mode is redundant, but yes, this is better!
