### ISSUE TITLE
Integrate Send and Deposit/Withdraw into One Tab Called Transfer

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#593]
It takes time and energy for newbies to learn the difference between these two tabs and it even slows down experienced users because we have to think if we are sending within the BitShares blockchain or through a gateway whenever we want to move value.

Having two tabs takes up more room on the top and on smaller 13" laptop screens this screen real estate matters.

Finally, the '/' character between Deposit and Withdraw is not so pretty. Those two words look squished together uncomfortably.

I suggest a new tab called Transfer which covers all of the functions of both. When you click on it you get a section where you can choose "Send BitShares Assets" or "Withdraw Through Gateway" or "Deposit Through Gateway" or something that makes it clear.

Within the Deposit/Withdraw tab right now you have to click on a button to make one of these choices anyway. I think this button should be at the top, not hiding on the middle right... I suggest integrating these areas and making the choice clear through 3 subtabs, not 3 buttons. The cleaning up of the Deposit/Withdraw area was starting to be discussed in issue #524, I am simply expanding this to include the Send area.

And of course, Bill just opened these three issues #556, #557, #588 which are related. These dialogs can be called from a new Transfer area just as easily as from the current two areas.

**Comment by btsfav** [comment]
I would not merge those two tabs. it's hard enough for people to not mess up. even now some send OPEN.STEEM via bitshares to bittrex.... if any we need better distinction and alert popup if you want to send 3rd party assets within the network

**Comment by wmbutler** [comment]
Addressed in these rewrites:

- #556 #557 #588

**Comment by landry314** [comment]
I don't see how this is addressed in any of the other issues. How are the new dialogs accessed? Through the same Send and Deposit/Withdraw tabs, right?

They are beautifully done, btw.
