### ISSUE TITLE
Deposit/withdraw buttons don't appear for rudex UIAs on account page

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares-ui#596]
Deposit/withdraw buttons don't appear for rudex UIAs on account page

**Comment by wmbutler** [comment]
Please provide screenshots to support your assertion. What do you require in order to deposit?

![screen shot 2017-10-16 at 8 02 41 pm](https://user-images.githubusercontent.com/1254810/31641840-0ca03b56-b2ad-11e7-89e1-7301f2ae2f21.png)

**Comment by jonnybitcoin** [comment]
Just on the account page

**Comment by svk31** [comment]
Yea their system is slightly different so we need to either adjust the current modal or create a new one for their gateway.

**Comment by startailcoon** [comment]
Fixed
