### ISSUE TITLE
[.25][startailcoon] Collateral Field in Margin Adjust Window Becomes Shorter When Available Collateral is Negative

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#598]
Steps to Reproduce:

1) Try to borrow an asset
2) Start typing numbers in the collateral field until it eats up all your available BTS

When the amount of collateral is more than you own in BTS then the available collateral becomes negative and the field gets shorter. Delete some numbers in collateral, it gets longer again.

**Comment by wmbutler** [comment]
Spooky...

![collateral](https://user-images.githubusercontent.com/1254810/31643403-fe321860-b2b5-11e7-8f9d-1a62f977fd2c.gif)

**Comment by landry314** [comment]
This also occurs when you move the slider far to the right, of course...

**Comment by startailcoon** [comment]
I have a tiny fix for this error, but uncertain on how to do a proper commit/PR to the GitHub project

**Comment by wmbutler** [comment]
The readme explains how to claim an item. I'll assign this to you but please request prior in the future. And thanks for your work.
