### ISSUE TITLE
Create Another Way to Borrow bitAssets

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#599]
Currently the way to borrow bitAssets is by going to the exchange and finding a market with that particular bitAssset in the pair then clicking a small link "borrow [bitAsset]" at the top of the BUY or SELL area. This is not that obvious.

Another way is if you already own some of that bitAsset then you can go to your Portfolio and click in the Borrow column in that asset's row. But the problem here is you have to already own some of the bitAsset to do this.

Maybe there can be another way to do this? Maybe a Borrow bitAsset button in the Account area that pulls up a list or a search function?

Any other ideas? Just trying to start a conversation...

**Comment by wmbutler** [comment]
It was mentioned in #581 that it was missing from the portfolio. I suggested that we have it in Margin Positions whether it's been borrowed or not.

**Comment by landry314** [comment]
I think you referenced the wrong issue above, @wmbutler. There is no mention of this in that issue.

**Comment by wmbutler** [comment]
oops...there.
