### ISSUE TITLE
When "Account" tab is active, "b" tab shows active as well

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#600]
Only tested in LightClient.171015 (win)

The top tab "Account", when active also shows the "b" tab (dashboard) as active.  It shouldn't.

**Comment by wmbutler** [comment]
Agreed, but that top area is getting a rewrite. Rather than pay for a dev to fix it, let's just wait for the menubar release.

**Comment by svk31** [comment]
This is a tiny fix so we might as well include it, it's just because the active state is triggered by the word dashboard in the URL,  which is now included in the account dashboard url as well.
