### ISSUE TITLE
Asset Details Page for 'BTS' Breaks Navigation

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#605]
Navigate to the asset 'BTS' and the navigation breaks.

Replication Steps:
- Main Dashboard -> Click your account name
- Main Account Overview -> Click BTS Asset
- Navigation is now broken.

This does not happen on other assets as far as I can tell.

Running `bitshares.171015`

**Comment by startailcoon** [comment]
And suddenly it works again.
I've had this issue several times and only solution is to press F5 to reload the session.

**Comment by wmbutler** [comment]
I cannot reproduce. Please list:

OS and version:
Browser type and version:
Light Wallet or Browser:

**Comment by startailcoon** [comment]
OS: Windows 10
Light-wallet, latest version

**Comment by startailcoon** [comment]
The error I get is:

![image](https://user-images.githubusercontent.com/12114550/31677134-25b380cc-b36a-11e7-923c-83867fbf745b.png)

**Comment by svk31** [comment]
It's because the market link tries to send you to the BTS_BTS market, I'll fix that. To reproduce, click the MARKET link..
