### ISSUE TITLE
Use symbols to save space?

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#606]
We have 5 currencies that can be used to provide estimated values of various assets. Unfortunately the names tend to take up a lot of space in tables and aren't very clean. Could we consider using symbols for these instead?

![screen shot 2017-10-17 at 11 22 58 am](https://user-images.githubusercontent.com/1254810/31676838-77d56528-b32e-11e7-83f3-b31a4b9407d0.png)

![screen shot 2017-10-17 at 11 23 17 am](https://user-images.githubusercontent.com/1254810/31676848-819e9962-b32e-11e7-8b03-6f35c9666e85.png)

**Comment by svk31** [comment]
Not opposed but you'd have to make some meaningful symbols then.

**Comment by Xeldal** [comment]
The actual names are much shorter of course.  ie USD EUR CNY.   I support replacing all instances of "bit" with a symbol.  Or at least coloring the names to signify "SmartCoin".   If you're apposed to just replacing the "bit" I don't see how you could possibly support replacing the entire name with a symbol.  (if that's what your suggesting. IDK)

**Comment by landry314** [comment]
Well, the bit is important to make sure people know it is not actually fiat. This is important to keep governments happy and also to be precise to establish trust.

How about "bit$", "bit£", "bit€"? These take up less room and still maintain the "bit". This requires that every currency has a symbol though, and maybe some do not, but all have a three letter code.

**Comment by clockworkgr** [comment]
this will cause more trouble than it's worth. 

Can't remove bit because it's TOO well known and "bit$", "bit£", "bit€" just looks terrible.
