### ISSUE TITLE
[.25] Long Line Wrapping Issue

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#607]
Open https://bitshares.org/wallet/#/ in incognito window or use a browser that has no wallet file created before, Select Chinese. The long introducing sentence on the first page didn't wrap.

**Comment by mattbeckman** [comment]
PR #613

**Comment by wmbutler** [comment]
@mattbeckman are you claiming this? If so, please request it and I will add your name to the top. This is to keep multiple people from working on the same issue.

**Comment by mattbeckman** [comment]
Sure. It was a quick fix, so I wasn't sure if the format request was necessary, but will keep that in mind for the future.

**Comment by wmbutler** [comment]
@mattbeckman reply here with your bts address

**Comment by mattbeckman** [comment]
Thanks, @wmbutler. It's **netdragonx-2017**
