### ISSUE TITLE
Make a blinking effect when clicking "deposit BTS" button

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#608]
IMHO the current flash animation is not obvious enough to attract attention. We can make a blinking effect, for example quickly change the font color to red then change back for 3 times.

**Comment by btsfav** [comment]
or skip this and just use https://github.com/bitshares/bitshares-ui/issues/584

**Comment by wmbutler** [comment]
That side panel is eventually going away. Noted.
