### ISSUE TITLE
Slider Bar in Margin Window Hard to Use Around Call/Disallowed Range

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#610]
When you move the ratio slider in the Margin window right at the point when the disallowed ratio text and margin call warning text changes over, it causes the slider to bounce around and the text to flash and the slider bar length to change.

This is strongly related to issue #598 because, I am guessing, this is being caused by the length of the slider bar getting shorter which throws off the graphical ratio calculations as it is being redrawn which causes the numbers to jump.

I think this is due to the margin call warning text being word-wrapped into two lines while the disallowed text is only one line. Just my guess.

**Comment by wmbutler** [comment]
This is getting a rewrite as well. Noted!
