### ISSUE TITLE
Two Decimal Places in Account Value (Total Value) Unnecessary

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#611]
All of a sudden the account value and total value are being displayed with two decimal places. This is unnecessary, wastes a little space, and makes the number slightly harder to read.

Why did this happen?

**Comment by wmbutler** [comment]
I'm not aware that we changed it, but 2 decimal precision is not exactly unprecedented.

**Comment by svk31** [comment]
I set a 2 decimal minimum for assets since it was hard to make it consistent with 0 decimals some places and more in others. In general decimals are very hard to get right in BTS due to the large range of asset precisions (0-8) and asset valuation in $ terms which makes it important to show many decimals for something like OPEN.BTC, but unimportant for BTS.

**Comment by landry314** [comment]
I understand this complication... tough one.

So, of all the choices for Preferred Unit, I guess only bitBTC would need more precision than an integer.

Couldn't the particular algorithm for "Account Value" be changed to round all numbers to integers except bitBTC? Right now, bitBTC is using 4 decimal places if you set it as the Preferred Unit. So, somewhere bitBTC is being set to display differently than bitUSD, BTS, etc, anyway...

**Comment by Xeldal** [comment]
something like this maybe.
```
func howManyDecimals(AssetX Coin) int {
   var ret int = 0  //return how many decimal places to show.
   var n float = 1  // amount of AssetX to test value
   for(k=0, k < AssetX.precision, k++) {
      if  value(n, AssetX) >= 1USD {
         n /= 10
         }  else {
            return k
         }
      ret = k
   }
   return ret
}

```

Where 1 of the Asset is worth less than $1 display with zero decimals
less than $10 with 1 decimal
less than $100 with 2 decimals
less than $1000 with 3 decimals
bitcoin would display with 4 decimals

**Comment by clockworkgr** [comment]
I don't see any reason to change this at this point.

It's been the standard for 1.5 years on the UI, 2 decimals is "historically" adopted in general and I haven't seen any other requests for it.
