### ISSUE TITLE
[.25] Inconsistency when switching language on password page

### ISSUE THREAD

**Issue by mattbeckman** [bitshares/bitshares-ui#615]
If a user attempts to switch the language on the password creation page (https://bitshares.org/wallet/#/create-account/password) for a new account, the field "Account Name (Public)" is not re-bound. 

It is only bound to the appropriate language if the language preference is set on the initial page (https://bitshares.org/wallet/#/dashboard).

Example: Select "Chinese" as language on dashboard page, then click the New Account button. On the 2nd page, select "English", and the "Account Name (Public)" description will stay in Chinese.

**Comment by svk31** [comment]
Yea I just noticed this today as well, it's because the path for downloading locale files is relative in IntlActions.js, I'll fix it tomorrow.
