### ISSUE TITLE
Highlight own orders (active account) in orderbook

### ISSUE THREAD

**Issue by MarkoPaasila** [bitshares/bitshares-ui#618]
Maybe use a slightly different font color for one's own limit orders (in the _BUY ORDERS_ and _SELL ORDERS_), so you can spot them from among all the other orders.

This would make easier it to figure out the situation without reading all the numbers in the orderbook and comparing it with one's _OWN ORDERS_. Visual information is hundreds, if not thousands of times faster to consume.

I'm not sure if this could entirely replace the _MY OPEN ORDERS_ box. If it could, it would be saved real-estate in the UI. This would require adding the _cancel order_ button to the order book listing.

**Comment by svk31** [comment]
Orders in the orderbook are grouped at similar price points so this won't work.

**Comment by landry314** [comment]
Do you mean if two orders are set at the same price?

Couldn't you still color it just to show that that is where YOUR order is? This would be a very helpful thing while looking at the order book.

**Comment by svk31** [comment]
Yes I can highlight the order where you have orders also, but I can't really add a cancel button there.

**Comment by wmbutler** [comment]
#302 Duplicate
