### ISSUE TITLE
Add "unit of account" label to both axis of the trading chart

### ISSUE THREAD

**Issue by MarkoPaasila** [bitshares/bitshares-ui#620]
Both the X-axis and the Y-axis need indications of what they measure. It must be completely obvious what is measured and what is the unit of measurement. In case of the _PRICE CHART_ it is obvious that the X-axis represents time, but it isn't entirely obvious which asset is measured and in what unit. The  _MARKET DEPTH_ chart has the problem on both axis. Unless you are very used to the interface it takes some pondering to understand which way things are.

**Needed features:**

- In _MARKET DEPTH_ chart the X-axis should show the unit of account.
- In _MARKET DEPTH_ chart the Y-axis should show the unit of account, which apparently is the opposite of the X-axis
- In _PRICE CHART_ the Y-axis should be labeled with the unit of account. If a user is interested in the price of BTS in USD, the unit is USD
- In _PRICE CHART_ there should be a clear indication of what the chart shows. Does it show the price of USD in BTS or the opposite.

I think this would significantly improve the user experience for all users, but especially for new users trying out the DEX. They often complain about the complex UI, and the lack of these labels is surely one of the reasons. I also imagine it's not too hard to fix.

**Comment by happyconcepts** [comment]
FYI #361 is about migrating to TradingView
