### ISSUE TITLE
[.5][happyconcepts] Harmonize Login Screens

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#622]
Local Wallet and Cloud Wallet have very different looks. It would be nice to get them in line with one another. Extra points

- Reduce width of both to be the same as the registration screen.

## Cloud Wallet
![screen shot 2017-10-20 at 8 30 31 am](https://user-images.githubusercontent.com/1254810/31823250-1dba2674-b571-11e7-88d7-87486ce4ba26.png)

## Local Wallet
![screen shot 2017-10-20 at 8 30 36 am](https://user-images.githubusercontent.com/1254810/31823254-23c3f82e-b571-11e7-99bf-ba11be445de5.png)

Changes:

- Header should read: Local Wallet Login
- Button should read: Login
- Password label should read: Password

**Comment by happyconcepts** [comment]
Can I pls claim this?
