### ISSUE TITLE
[2][izmlam] Chinese Translation

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#623]
We need updated translations throughout:

- Wallet
- Readme.md

Please be very thorough.

**Comment by lzmlam** [comment]
Claim it. I will do my best.

**Comment by wmbutler** [comment]
It's yours.

**Comment by lzmlam** [comment]
Have done. Please tell me anything that needed to be modified. BTW my bts account is : zhaomu8

**Comment by wmbutler** [comment]
I need your bts address to pay you.
