### ISSUE TITLE
[.5][startailcoon] Display Published value as an actual date/time in localized time zone

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#627]
On my system, that runs on UTC+2, the price feed time stamp on the asset details page is displayed wrong.

The Asset Price Feed Data sais the price feed was updated 2 hours ago, but looking on the timestamp of the block it's right now. The text is not taking my UTC+2 in account and should be handled the same throughout the entire application.

![bitshares-feedtime-issue](https://user-images.githubusercontent.com/12114550/31852949-c1855098-b680-11e7-935b-ff9b6a02dfc6.png)

![bitshares-feedtime-issue](https://user-images.githubusercontent.com/12114550/31852958-f1c47522-b680-11e7-99ba-342f5a175b14.png)

![image](https://user-images.githubusercontent.com/12114550/31852948-bd4ad796-b680-11e7-9a06-dec87aa44cf1.png)

**Comment by wmbutler** [comment]
Format: `Jan 01, 2017 5:05:23 pm`

**Comment by startailcoon** [comment]
If allowed, I can look at this and claim it?

**Comment by svk31** [comment]
Sure
