### ISSUE TITLE
User experience Optimization: API & Language selection should displayed in the home page and start page

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#63]
_From @imYao on August 21, 2016 16:16_

User experience Optimization: API & Language selection should **displayed in the home page and start page.**
Thanks for your job.

_Copied from original issue: cryptonomex/graphene-ui#869_

**Comment by svk31** [comment]
_From @xeroc on August 21, 2016 17:56_

I don't understand this issue ..
you looking for something like this?
http://docs.bitshares.eu/api/

**Comment by svk31** [comment]
_From @imYao on August 22, 2016 5:1_

@xeroc sorry, I didn't explain it clearly. I mean, for **newbies**:

If you are an American, don't understand Chinese, what do you want to do when you open a Chinese website? I will change the Default Language first.

API servers are in different countries, the default API server of BitShares 2.0 GUI is OpenLedger, some people may be difficult to access OpenLedger, he might have been unable to enter the wallet home page, all the time. He need to change the Defaule API server first.

I hope you can understand this now.

**Comment by svk31** [comment]
This is something we talked about for the revamp of account creation but got lost somewhere, it's definitely something we should do.

**Comment by wmbutler** [comment]
We have country flags on the top right now. This satisfies
![screen shot 2017-09-21 at 12 29 39 am](https://user-images.githubusercontent.com/1254810/30680213-f889bbae-9e63-11e7-81cc-92e3e85f2501.png)
 the issue.
