### ISSUE TITLE
[1][startailcoon] Connection status visible throughout the entire application

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#632]
Today we're inconsistent with how we display the connection and sync status as the footer is only displayed on various sections of the app. 

We should view the footer with sync status, but also toward what server we're connected to. I may wish to stay connected to a specific server, but if this server fails I'm silently moved over to another one. This is fine, but we should let the user see towards which server it's connected to.

My Light-wallet lost connection to a node in Europe, and set a US node as default instead for the time being. This came to my attention when I checked the access section again.

**Comment by wmbutler** [comment]
Totally agree. This was actually a requirement as part of the previous connection status rewrite but it didn't get done.

**Comment by startailcoon** [comment]
I can claim this one

**Comment by wmbutler** [comment]
It's yours.

**Comment by startailcoon** [comment]
- [x] Footer visible on Market section
- [ ] View current node status

### Would like some input on this change.
- Added the node URL to the hover tooltip
- Added dynamic color of the "Sync" text depending on ping time, using the values from the access page.

What I don't like is that the URL address is a little clunky and not specifically pretty, but would let you quickly see what node you're connected to without having to go to the access page.

I was thinking about adding a section on the left of the block sync status viewing the ping time to the current node with the tooltip viewing the node address and name. This section would take you to the Setting Access page, while clicking on the network sync section would take you to the `Explore -> Network` section instead.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/12114550/32135201-53ff1d58-bbfb-11e7-868c-4eaf255c0938.gif)

**Comment by wmbutler** [comment]
I like what you've done with this, although I think seeing "synced" while it's red is an ambiguous control. Probably best to be green when in sync and red when out of sync. There is no need to draw the users attention just because latency is low.
