### ISSUE TITLE
[.25][startailcoon] Clicking on connection status should take user to Settings --> Access

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#633]
![screen shot 2017-10-23 at 12 48 37 pm](https://user-images.githubusercontent.com/1254810/31904337-951b3efc-b7f0-11e7-880e-39728c80f27f.png)

![screen shot 2017-10-23 at 12 49 25 pm](https://user-images.githubusercontent.com/1254810/31904357-a02e81f0-b7f0-11e7-8f22-073e12a251cb.png)

**Comment by startailcoon** [comment]
I can claim this

**Comment by wmbutler** [comment]
It's yours!

**Comment by startailcoon** [comment]
I've enabled the Block Sync status box to take you to the Settings page, but I'm unable to find a way to access the "Access" section in the same action, and I can't find that this is done from any other section of the software either. 

The settings page will show the last accessed section of the settings page.

May need some code rework to actually take you to the access page directly.

https://github.com/startailcoon/bitshares-ui/commit/2c0f01ab94a3c9a8ab7e47f700e6a5ddb1b915bc
