### ISSUE TITLE
[1.5] Detect indexdb and inform users of migration path to wallet.bitshares.org

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#635]
Text:

"In an effort to provide enhanced security for the web-based wallet, we are migrating it to the subdomain `https://wallet.bitshares.org`. We will phase out `https://bitshares.org/wallet` by November 15, 2017. Please backup your wallet now and restore the backup file to https://wallet.bitshares.org, which will be your new address for the web wallet. Thanks for your continued support."

**Comment by happyconcepts** [comment]
>Please backup your wallet now and restore the backup file

So I have a web-based wallet account but there is no option there to create a backup file.

Should I be making backups of my keys instead, is that the right approach?

**Comment by svk31** [comment]
The backup message will only be shown to local wallet users, that's what the indexed dB detection is for.

If you're using a cloud wallet account your backup path is to write down and store your username and password.

**Comment by happyconcepts** [comment]
Both `web wallet` and `web-based wallet' are used in the copy text and as the reader I did not understand that it is a reference to the local wallet. Thanks.

**Comment by happyconcepts** [comment]
This is a timely message and should be made highly visible. Where do you propose it will be shown?

**Comment by happyconcepts** [comment]
@svk31 good day ... I started a PR #675 to help the project. Perhaps you have in mind somewhere else other than the backup screen for the notice.

**Comment by svk31** [comment]
I was thinking I'd make a stripped down build for bitshares.org/wallet that only includes the message and a way to backup the wallet.

**Comment by wmbutler** [comment]
I will UX this for discussion and post it here.

**Comment by wmbutler** [comment]
For reference:

## Bitshares Light Client (Downloaded Client)
This won't affect you. Just download the newest version as usual

## Cloud Wallet Users
All you need to do is change your bookmark to https://wallet.bitshares.org. You will need to reset all your preferred markets and for that we are sorry for the inconveience.

## Local Wallet Users
If access a local wallet from https://bitshares.org/wallet, you will need to take a backup of your .bin file then import it into http://wallet.bitshares.org.

**Comment by wmbutler** [comment]
Keeping this UX pretty simple. From 11/15/2017 onwards for bitshares.org/wallet:

- [ ] Only display this endpoint: https://wallet.bitshares.org/#/settings
- [ ] Add an href telling the user to go to https://wallet.bitshares.org/ to restore their backup
- [ ] Change "No backup is needed" to "After creating your backup file, please restore it at https://wallet.bitshares.org. This will be your new permanent location for your wallet."

![screen shot 2017-11-10 at 3 14 56 pm](https://user-images.githubusercontent.com/1254810/32679060-a12be9b0-c62a-11e7-929b-cae041e83bbe.png)

**Comment by wmbutler** [comment]
- [ ] If we do not detect indexdb, just display that this wallet is no longer available and that they should use: https://wallet.bitshares.org from now on.

**Comment by wmbutler** [comment]
## Cloud Wallet Copy

### Notice
In an effort to provide enhanced security for the web-based wallet, we are migrating it, **effective immediately** to:

https://wallet.bitshares.org

**Comment by toma53** [comment]
So in your effort to enhance security, you have locked out existing users.  What do you do if you are only seeing this message after Nov 15th to backup your local wallet.  All I have is the BTS default backup.  This is very disturbing.

**Comment by wmbutler** [comment]
Then go to wallet.bitshares.org/wallet and take a backup. We haven't done anything "disturbing" here.
