### ISSUE TITLE
Unable to generate BTC deposit/withdraw address on Android mobile device

### ISSUE THREAD

**Issue by kimchi-king** [bitshares/bitshares-ui#643]
I'm using an HTC One M7 with the latest Android software.

I was trying to get a BTC address to determine if it were possible to deposit BTC via a mobile device.

Unfortunately, no deposit or withdraw address is displayed.

![screenshot_2017-10-24-12-30-21_1](https://user-images.githubusercontent.com/32033560/31938416-c97a4540-b8b7-11e7-8a2f-7904e355e785.jpg)

**Comment by wmbutler** [comment]
New deposit modal will have better feedback when openledger fails to generate an address. #557
