### ISSUE TITLE
Market Exchange Timestamp cuts off short 

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#644]
The date and timestamp is not viewed fully since it's to long. Can we condense it or view a timeAgo instead?

![wp_ss_20171024_0001](https://user-images.githubusercontent.com/12114550/31940725-6d8ce474-b8bf-11e7-8b93-d497f6ef634f.png)

**Comment by wmbutler** [comment]
I have no idea what this refers to. Will you please include a screenshot or a licecap to clarify?

**Comment by startailcoon** [comment]
Sorry for the lack of description. 

What I refer to is the "Market Trade" table, where we display the timestamp of the trade. It is to short to view a full string of "Year/Month/Date Hour:Min:Sec". On my phone (capture from prev. comment) I can't see the month, just Year and Time, and on my desktop I can see month/year and time. 

I can't see what date the exchange was made, which renders the date column useless.

The hover tooltip however, does give some more details about the date.

## Cut short on my Desktop
![image](https://user-images.githubusercontent.com/12114550/31950092-27233530-b8db-11e7-85bc-1a989b3a4c20.png)

## Proposals
- Change DateTime to view either "TimeAge" as on the transactions history page, or to view only in the format of "Date Hour:Minute:Second".

- Make the Date/Time clickable to view the block, as we do on the "My Trades"-tab.

- Make the two tabs consistent and change "Block" to "Date" on "My Trades", and link to the block from it.

**Comment by svk31** [comment]
The format used doesn't even include the year so I'm not sure why your tables show the year. Either way these commits: https://github.com/bitshares/bitshares-ui/commit/f29e5664f497870c465d0f69d56d5e96fd0306b2 and https://github.com/bitshares/bitshares-ui/commit/70f38cf1d599765a3896a51ac34230495bd544e7 changed the formatting to use counterpart's `localize` function instead which should fix this. Americans get their weird MM/DD format, everyone else gets DD/MM.

**Comment by startailcoon** [comment]
That's strange. I'll see if it's still weird after the update
