### ISSUE TITLE
Better Explorer navigation

### ISSUE THREAD

**Issue by tbone-bts** [bitshares/bitshares-ui#646]

**Comment by wmbutler** [comment]
This is not actionable.

**Comment by tbone-bts** [comment]
Hmmm.  Didn't mean to create this  Can you delete?

**Comment by landry314** [comment]
You can delete it, @tbone-bts! Look below this on the right. Do you see the "Close issue" button?

**Comment by tbone-bts** [comment]
"Close" means "delete"?  Who knew?!
