### ISSUE TITLE
After 1st sign-up you constantly see the "loading" animation

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#650]
Usually a simple refresh does the trick, but I'm hearing this every now and then from new users. 

can you setup an auto-refresh?

**Comment by wmbutler** [comment]
Probably a bad idea to do an auto-refresh. If you can't reproduce it consistently, we can't fix it. I'm guessing this has to do with latency and timeouts.

**Comment by wmbutler** [comment]
Marking as a question until we can reproduce.

**Comment by svk31** [comment]
It's an issue with the faucet that only occurs randomly, hard to fix without being able to reproduce. I've had it happen a few times myself too, but the account still got created and a refresh always fixed it.

**Comment by startailcoon** [comment]
Closing this as nothing further has been reported since the fix supplied in nov last year.
