### ISSUE TITLE
[9][startailcoon] Buy Modal

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#651]
We need an easy way for users to purchase BTS.

- [x] Ensure that BTS is always shown in My Portfolio whether the user owns any or not.
- [x] Link the buy icon on My Portfolio to this newly designed Purchase screen
- [x] Include a calculation in the effective price showing the price in the users chosen currency
- [x] Show a QR code for the deposit address (only if a memo is **not** required)
- [ ] Link help to blocktrades site: https://blocktrades.us/
- [ ] Don't allow user to exceed deposit limit on entry area
- [ ] User should also be able to type into the receive area and it should back calculate

![screen shot 2017-10-28 at 1 57 58 pm](https://user-images.githubusercontent.com/1254810/32137565-0c12e352-bbe8-11e7-8b69-b0c340b7ada9.png)

**Comment by abitmore** [comment]
Don't mix blocktrades with the dex.

**Comment by wmbutler** [comment]
You are going to need to elaborate. Blocktrades is already in place. All I'm doing is creating interfaces that match.

![screen shot 2017-10-26 at 7 48 17 pm](https://user-images.githubusercontent.com/1254810/32083215-b8ae07b2-ba86-11e7-8a2b-6e1d5c7e5167.png)

![screen shot 2017-10-26 at 7 48 23 pm](https://user-images.githubusercontent.com/1254810/32083219-bdb501f2-ba86-11e7-8c99-07d8a7f879a3.png)

**Comment by abitmore** [comment]
I was talking about the first screenshot. "BTC sent to this address will show up as OPEN.BTC" is simply wrong.

This is a blocktrades feature and is already there and works fine, I don't think it's necessary to create a duplicate one or redesign it.

Although we may want to integrate shapeshift and/or changelly and/or whatever else in the future, but it's not that easy to do all of them in one page, as all their API's are different.

**Comment by wmbutler** [comment]
Correct it will show up as BTS. Just an oversight on the UX. I'll get that corrected.

**Comment by abitmore** [comment]
We love and hate blocktrades. People can trade in and out BTS via it, that's good. It maintains an off-chain order book with a significant depth (many pairs are deeper than the on-chain order book), that sounds not that good for the Dex.

**Comment by wmbutler** [comment]
It's already there. It's an easy way to buy BTS for new users. All I'm doing is adding consistency. Don't shoot the messenger.

**Comment by abitmore** [comment]
If the "buy BTS" feature is based on the on-chain order book, then it will be much better, like the "buy" and "sell" button in the basic view.

**Comment by abitmore** [comment]
If this feature only works with blocktrades, it should be funded by blocktrades but not the worker.

**Comment by wmbutler** [comment]
It's a dropdown list. That's what the downward arrow specifies. Why don't you open the existing wallet and give it a try?

**Comment by wmbutler** [comment]
- [ ] Updated text to indicate "will show up as BTS"
- [ ] Display address below barcode only

**Comment by abitmore** [comment]
> It's a dropdown list. That's what the downward arrow specifies.

Thanks. I overlooked the arrow on the left, only saw no arrow on the right (now I know it's not there for a reason).

**Comment by startailcoon** [comment]
I can take this task

**Comment by o5j5vg55bv5hv5j5f8799f9** [comment]
terminology on gateway seems wrong: it refers to blocktrades as gateway when it's a bridge

**Comment by startailcoon** [comment]
@wmbutler with only a few issues left, mainly CSS related and the back calculate of the output value, this modal will have the new layout for the next release.

**Comment by startailcoon** [comment]
I need a few tips on how to solve an issue with deposits with Steem, which has a required memo rather than address. 
## Deposit to generated address w/ memo
This is not a suggestion, but rather how it looks before any fixing. We need to find a good placement for the buttons when we have this many. I also think we need some more explanation of address vs. memo for users to understand what this text means that we show.

![bitshares-deposit_memo](https://user-images.githubusercontent.com/12114550/32506170-2e7d1166-c3e4-11e7-8781-acc3ce5519f8.png)

## Deposit to generated address
I'm quite pleased how the deposit looks so far with address though.

![bitshares-deposit_address](https://user-images.githubusercontent.com/12114550/32506161-2bed90b0-c3e4-11e7-874d-5e0886b1a3fb.png)

**Comment by wmbutler** [comment]
If a memo is required to perform any transaction, we should

- hide the QR Code
- DASH sent to this address will show up as BTS
- Memo required for proper routing to your account

**Comment by wmbutler** [comment]
Let's center the **close button** for all modals and leave the copy next to the address as an icon in very case.

**Comment by startailcoon** [comment]
## Progress Tracking

- [x] Ensure that BTS is always shown in My Portfolio whether the user owns any or not.
- [x] Link the buy icon on My Portfolio to this newly designed Purchase screen
- [x] Include a calculation in the effective price showing the price in the users chosen currency
- [x] Show a QR code for the deposit address (only if a memo is not required)
- [ ] Link help to blocktrades site: https://blocktrades.us/
- [ ] Don't allow user to exceed deposit limit on entry area
- [ ] User should also be able to type into the receive area and it should back calculate

#### If a memo is required to perform any transaction, we should
- [x] hide the QR Code when we have a memo

#### Other modifications
- [x] "DASH sent to this address will show up as BTS"
- [x] "Memo required for proper routing to your account"
- [ ] Place copy icons to the right of each address and memo
- [ ] Remove the "Get new address button". This can be triggered when the modal is first opened instead.
- [x] Be sure to make your address/memo fonts small enough to comfortably account for the copy button(s)
- [x] Center the close button for all modals
- [x] Remove large copy button in lieu of copy icons next to the address/memo


### Progress Preview so far, note that this is **not** finished.

![bitshares-buybts_modal_2](https://user-images.githubusercontent.com/12114550/32629575-00edcf76-c59a-11e7-958a-da905d5c66b4.gif)

**Comment by wmbutler** [comment]
Looking great. Small cosmetic tweaks:

- [ ] A bit more spacing between QR code and address label
- [ ] Larger copy button that is positioned higher and spans label and address

Looking really really good!

**Comment by wmbutler** [comment]
- [ ] Change Purchase to "Buy" to conform with Portfolio terminology.

**Comment by wmbutler** [comment]
Question: Is the functionality you've build only intended to address the Deposit portion of the Blocktrades API? It's fine if it is, but I'd like clarity.

![screen shot 2017-11-10 at 11 09 51 am](https://user-images.githubusercontent.com/1254810/32670012-0867d7ce-c608-11e7-9fa4-ecf805b4c929.png)

**Comment by wmbutler** [comment]
- [ ] Make sure there is a buy icon for each eligible symbol offered with Blocktrades

![screen shot 2017-11-10 at 11 15 07 am](https://user-images.githubusercontent.com/1254810/32670145-82ae4d6a-c608-11e7-83ed-edcf6fd73a2c.png)
![screen shot 2017-11-10 at 11 13 38 am](https://user-images.githubusercontent.com/1254810/32670146-82be485a-c608-11e7-93a8-39f7b26b9600.png)

**Comment by startailcoon** [comment]
> Looking really really good!

Thank you :)

> Question: Is the functionality you've build only intended to address the Deposit portion of the Blocktrades API? It's fine if it is, but I'd like clarity.

It's built around the current Purchase functionality that we have in the wallet, so at the moment it's only for the Blocktrades API.

**Comment by wmbutler** [comment]
Right, but the blocktrades API has three functions. I was just clarifying that you are only addressing what is currently referred to as the "deposit" portion right now (not the withdraw or transfer functions)

**Comment by wmbutler** [comment]
Only BTS should be in the portfolio by default.

**Comment by startailcoon** [comment]
- Yes, the API has more functions and here we're addressing the deposit and will be the only one worked on. Understand that you're just making sure I'm not going to large. The withdraw and transfer functions will be in the future modals, correct.

- We can work on a future task for making an easier way of accessing the modals different portions of buying other assets trough different bridges later on, good idea.

**Comment by startailcoon** [comment]
# Latest Preview as of 11/11
- [ ] Fix input value issue

Current update of the new modal. Found a new issue with the input when you type in a number with a decimal in it, as you can see. Other than that, it's almost complete.

![bitshares-buybts_modal_3](https://user-images.githubusercontent.com/12114550/32691697-ebb628c4-c70b-11e7-8165-39b20cdee174.gif)

**Comment by startailcoon** [comment]
Found an issue where the Buy Modal doesn't give the same assets for sending as the BlockTrades Bridge page gives.

For example, it's missing LTC and SBD.

![bitshares-buybts-modal](https://user-images.githubusercontent.com/12114550/32698096-0dd9db92-c79f-11e7-8a53-d89b6b7193d7.png)

![bitshares-brdigedeposit-sbd](https://user-images.githubusercontent.com/12114550/32698102-36917252-c79f-11e7-861e-585f5e43e658.png)
![bitshares-brdige-ltc](https://user-images.githubusercontent.com/12114550/32698103-36b74680-c79f-11e7-8f08-4c565b7af938.png)

**Comment by wmbutler** [comment]
![screen shot 2017-11-12 at 11 55 54 am](https://user-images.githubusercontent.com/1254810/32701745-86e6b0d6-c7a0-11e7-9bfd-e99e19165ecc.png)

Cosmetic Changes

- [ ] The top part of the page (logo and label) take up too much vertical space. Reduce padding/margin
- [ ] The red warnings do not stand out on that color background. Maybe bold or choose a better color.
- [ ] Copy button is slightly too far left when compared with input fields and labels above.
- [ ] Close button needs more margin on bottom.
- [ ] Memo/address feel cramped vertically.

**Comment by svk31** [comment]
Looks like I might have merged this too soon, @startailcoon would you like me to revert it or do you want to just make a new PR with the additional changes?

**Comment by startailcoon** [comment]
@svk31, the layout fixes from Bill is in the commit you used so all good.

**Comment by wmbutler** [comment]
![screen shot 2017-11-13 at 9 00 48 am](https://user-images.githubusercontent.com/1254810/32732153-5f7a794a-c851-11e7-8b8f-bdf26c208505.png)

- [ ] Limit reached is causing a shift. Please right justify.
- [ ] See few items up top that are still issues on staging

Sorry to be so detail oriented here, but you are very very close to having this completed!

**Comment by startailcoon** [comment]
> Sorry to be so detail oriented here, but you are very very close to having this completed!

Absolutely no worries. I want to have all the feedback you can give me so we can get this as good as possible. If that means I have to revisit it 10 times more because I missed something little in some weird case or screen resolution I will of course do it. All the tiny details that can be found I wish to have.

**Comment by startailcoon** [comment]
@svk31, I will submit a new PR with the last few changes in a day or two. No need to revert this.

**Comment by wmbutler** [comment]
This is hard to explain using licecap.

![buy](https://user-images.githubusercontent.com/1254810/32755688-1cc384b6-c89c-11e7-9333-6251149098a9.gif)

- [ ] The buy modal defaults to Qty 1. Let's default to Qty 0
- [ ] In the screen share, I highlighted the `1` and then typed `.2`. As you can see, it entered a `2` instead of `.2`
