### ISSUE TITLE
[1.5] Cloud-wallet only deployment - still possible to enable wallet/local mode

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-ui#653]
When I comment `local_wallet` in SettingsStore
```
            passwordLogin: [
                {translate: "cloud_login"},
                // Do not allow local wallet
                //{translate: "local_wallet"}
            ]
```

I am still provided a button to enable wallet in Settings->Import
![](https://i.imgur.com/kBF7ybQ.png)

When clicking it, I cannot go back to cloud wallet in the settings dropdown anymore

**Comment by wmbutler** [comment]
Thanks for this bug report.

**Comment by svk31** [comment]
It wasn't coded to support that so this needs a bit of restructuring I think. Not sure I agree it's high priority tbh

**Comment by gibbsfromncis** [comment]
@wmbutler @svk31 if you tell me what is the issue and what is the expected behavior I can work on this one.

**Comment by sschiessl-bcp** [comment]
This is solved with the introduction of branding.js and getDefaultLogin / getAllowedLogins
