### ISSUE TITLE
[1][bigspider] locale/language support seprated among multiple files

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-ui#654]
If I wanted to remove a language from the drop down, it is not sufficient to remove it from the
`defaults.locale` key, but you would also need to remove it from `IntlStore`
Could the imports be made so that they depend on what the config/settingsstore says, please?

**Comment by bigspider** [comment]
Sorry for not asking to have it assigned beforehand; I directly submitted a pull request, instead.

**Comment by wmbutler** [comment]
Thanks. I assigned it to you.

**Comment by wmbutler** [comment]
@bigspider, please send me your bts address.

**Comment by bigspider** [comment]
@wmbutler, my bts address is "spider-1". Thanks!

**Comment by wmbutler** [comment]
Paid you.
