### ISSUE TITLE
Price History Zoom Issue

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#656]
When selecting a candlestick period that is larger than the zoom level, the program will freeze with a loading message. To revert back the user needs to reload the screen, select a smaller candlestick to match the zoom and reload again.

![bitshares-pricehistory-bug](https://user-images.githubusercontent.com/12114550/32124400-e29ad848-bb67-11e7-9fad-63bfdadf1dbb.gif)

### Reproduce
- Select any trading pair 
- Select Zoom to 6h
- Select Candlestick to 1d
- Loading screen appears and never ends due to not finding data related to the selected zoom/candlestick level.

### Solution to solve issue today
- Reload Page
- Select a new zoom/candlestick level that works
- Reload Page
- The price graph is now working again

**Comment by wmbutler** [comment]
Duplicate #361
