### ISSUE TITLE
[1] MARKET TRADE / MY TRADES

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#66]
_From @wmbutler on August 31, 2016 22:10_

![screen shot 2016-08-31 at 6 07 45 pm](https://cloud.githubusercontent.com/assets/1254810/18148131/e73132ee-6fa5-11e6-8dc1-8a7e08325a80.png)

This is a cosmetic bug. To reproduce, you must be on an asset that you have already traded in the past in the Exchange tab.
- choose the MARKET TRADES tab
- Scroll down a bit
- Switch to MY TRADES tab
- None of your transactions will appear until you scroll up.

_Copied from original issue: cryptonomex/graphene-ui#874_

**Comment by svk31** [comment]
_From @steempower on January 13, 2017 4:10_

This also occurs on all list boxes including buy / sell orderbook's

**Comment by calvinfroedge** [comment]
I can take this issue

**Comment by calvinfroedge** [comment]
@svk31 @wmbutler I am having a bit of trouble reproducing this issue. Please see the following screen cast:

![issue-66](https://user-images.githubusercontent.com/632938/29290139-9babea78-8104-11e7-9f8b-155a6011981a.gif)

Please upload your own screen cast (I used licecap) if you are seeing something different so that I can reproduce.

**Comment by abitmore** [comment]
In "market trades" tab, there is a scroll bar that you can scroll down, if it's not there, please check another pair that has more records, for example `BTS:bitCNY`. Scroll down, then click "my trades".

**Comment by abitmore** [comment]
PR #246. Next time it's best link the PR and the issue explicitly (putting issue number in title of PR won't link them automatically).

**Comment by calvinfroedge** [comment]
@wmbutler Can you close this issue? Code has been merged
