### ISSUE TITLE
[6] View referrals in wallet

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#661]
It would be a good tool to view referrals inside the wallet. At the moment we can only do this online at cryptofresh. I see a list of username and date of signup as the minimal task for this.

Additional tasks could be to add a tab in the account activity to also view Referral commissions that you will receive.

I think this would make it more visible for others that you can refer others and earn commission on their transactions.

**Comment by wmbutler** [comment]
I've been thinking about this as well. Maybe from this endpoint? I need to UX that whole screen and add referrals.

http://localhost:8080/account/billbutler/member-stats/

**Comment by btsfav** [comment]
LTM upgrades are not associated with affiliates, this could be a problem. 

I'd like to see 

* Total Refs
* Total LTM Upgrades
* Earnings

**Comment by wmbutler** [comment]
Oh, I thought affiliates had to be LTM?

**Comment by btsfav** [comment]
should be under membership stats, close to the referral link

**Comment by wmbutler** [comment]
That's what I suggested 7 days ago and your next comment was this:

> LTM upgrades are not associated with affiliates, this could be a problem.

**Comment by btsfav** [comment]
If someone signs up under you, you're their referrer. However, if they ugprade to LTM, this changes to self. the blockchain loses track who registered a LTM so to say

**Comment by abitmore** [comment]
Related info can be tracked in the back end by adding a non-consensus field or two into account object.

**Comment by btsfav** [comment]
@wmbutler could you open an issue in core if you see this feasible please?

**Comment by wmbutler** [comment]
How about baby steps. Let's track what we can without core changes and make that a separate issue.

**Comment by wmbutler** [comment]
If nobody wants to claim it, I'm going to push it...

**Comment by pnomolos** [comment]
@wmbutler I was looking for this information the other day so I'd be down to take it.

**Comment by wmbutler** [comment]
Awesome!

**Comment by pnomolos** [comment]
I spoke with @oxarbitrage on Discord and it appears like we should probably wait for https://github.com/bitshares/bitshares-core/pull/500 until working on this more.  Otherwise the only way to pull this information is to iterate over every account manually.

**Comment by oxarbitrage** [comment]
https://github.com/bitshares/bitshares-core/pull/500
the plugin is the second in elasticsearch series that will export among other things account data to the database making the query for all the accounts under a referral account easy and fast.

it has been in the freezer in the last time but maybe is time to resume the efforts on it an include it.

the problem is that there is no core code to efficiently get this data. i suffered from this problem when trying to get referral data to the open explorer and the plugin was created for that reason among other similar issues.

**Comment by wmbutler** [comment]
I moved this out to 180301 to accommodate the ES need.

**Comment by startailcoon** [comment]
Do we have any ES Plugin that enable this to be fetched to the UI yet?

**Comment by wmbutler** [comment]
@oxarbitrage ?

**Comment by wmbutler** [comment]
@nikandrovalex care to draw up some designs for this?

**Comment by calvinfroedge** [comment]
I can take this on if @oxarbitrage can help me understand how to pull the data (clicking link above gives me a not found)

**Comment by wmbutler** [comment]
@oxarbitrage

**Comment by calvinfroedge** [comment]
bump @oxarbitrage @wmbutler

**Comment by startailcoon** [comment]
With the use of ES we can now safely make this work.

**Comment by startailcoon** [comment]
# New Layout for Membership Stats

## LTM

### Details Section
![Screenshot_2019-08-10_20-26-02](https://user-images.githubusercontent.com/12114550/62826398-f463c080-bbba-11e9-951c-cc7df60e0de7.png)

### New Referrals List

This list is limited to non sort-able due to the ES query not supporting it yet. Accounts are loaded only for current page to decrease node stress.


![Screenshot from 2019-08-10 20-27-10](https://user-images.githubusercontent.com/12114550/62826397-f463c080-bbba-11e9-8f70-7d34d3c2512c.png)



## Basic Members

Basic members have almost the same layout, except for the information about a lifetime membership and the signup button.

![Screenshot_2019-08-10_22-08-36](https://user-images.githubusercontent.com/12114550/62826420-6dfbae80-bbbb-11e9-88bd-e8d7ff73a191.png)
