### ISSUE TITLE
Price colors missing from horizontal orderbook.

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#669]
The vertical orderbook prices are colored orange and green.

The Horizontal orderbook is missing these colors.

**Comment by svk31** [comment]
I think I removed the colors on purpose in the horizontal tables and simply forgot about the vertical orderbook since I never use it.

@wmbutler should we use the colors or not? Either we restore them to the horizontal tables or we remove them from the vertical tables.

**Comment by wmbutler** [comment]
I like the colors. It provides a nice visual cue for which part of the order book they apply to.

**Comment by svk31** [comment]
Yep I like em too, not sure why I removed them in the first place. I'll put em back for tomorrow's release.
