### ISSUE TITLE
[0.75][svk] Display dates instead blocks in the My Trades table

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#670]
Currently the "My Trades" tab on the exchange page has the 4th column of "block" and the "Market Trades" tab has the 4th column of "Date"

Use one or the other and use it for both tabs.  Either way you can link to the block as the My Trades tab currently does.

I'd suggest listing the time/date for both and have them link to the block.  No one cares at a glace what block it was in.  That information isn't meaningful.  Where as the time/date is very useful at a glance.  The block number and all other related block data can be determined with a click of the link if needed.

**Comment by svk31** [comment]
The reason one has blocks and the other has dates is that that's what's provided as data from the API. I can't link directly from a date to a block without doing a lot of API calls to determine the block number, but I can add a component that takes a block number and outputs the date.

**Comment by startailcoon** [comment]
I agree that the time is more useful than the block number, and that the layout should be consistent. The date should link to the block number for more detailed information if the user wishes.
