### ISSUE TITLE
[.25] wallet.bitshares.org referral does not work: unknown referrer code

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#677]
![](https://i.imgur.com/jft7iAb.png)

**Comment by wmbutler** [comment]
Please post the exact url you used for the referral. Thanks.

**Comment by btsfav** [comment]
wallet.bitshares.org?=fav

**Comment by svk31** [comment]
@xeroc What's the correct way to send this to the new faucet?

**Comment by btsfav** [comment]
bitshares.org/wallet referral doesn't work either, are you guys kidding me? 

@svk31 @wmbutler this is not acceptable, please test this stuff first before you change. ALL ref links are worthless now.

**Comment by xeroc** [comment]
Dang .. I need to fix this asap .. I missed that people use bitshares.org with the old style referal account string

**Comment by hubba1** [comment]
that referral link for fav doesn't work either....I got an error that says fav is an unknown referrer

**Comment by happyconcepts** [comment]
Are Openledger referral codes working or does this also affect Openledger signups?

**Comment by wmbutler** [comment]
@svk31 this need to be tested soon, prior to deployment on the 15th with the new .eu faucet.

r=
ref=
referral=

**Comment by btsfav** [comment]
is the faucet active?
