### ISSUE TITLE
Remove "Market Depth" button.  Label graph drawer in lower right. 

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#679]
Market depth graph is viewable in 2 places on exchange page.  Only need 1.  The sliding drawer in the lower right I feel is the better one as I don't think it needs to be any bigger than that, but it doesn't currently have a label.

Label the drawer in the bottom right "Market Depth" or "Depth Graph"
Remove "Market Depth" button at the top of the chart.

Another option if it's part of the charting package is having the depth graph display vertically along the right side of the chart.  It should probably retain it's clickable property that fills the Buy/Sell fields like the graph does now though if it is changed.  I know some people use this feature.  If implementing this option both current depth graphs should be removed.

**Comment by wmbutler** [comment]
Can we table this since we are adding Tradingview and it will likely influence this?

**Comment by wmbutler** [comment]
#361

**Comment by Xeldal** [comment]
Yeah no sense in changing things twice if it's covered under a larger issue.

**Comment by landry314** [comment]
I use the large market depth all the time and would personally prefer removing the small one, actually... but, when the new charts are out and the left over dust/wicks issue is solved then that might change. I agree with Bill, the new charts should be added first then this discussion will be more relevant.

**Comment by jonnybitcoin** [comment]
I also use the large depth graph more than anything. The small depth graph doesn't give enough detail and I'd like to see it removed.

**Comment by landry314** [comment]
@jonnybitcoin, you know, the little triangle hides the small market depth on the lower right...

**Comment by startailcoon** [comment]
I can't understand why we should remove features that aren't taking any space. You wish to remove the large, more detailed data window that isn't visible unless you tell it to, but save the smaller window that you can also hide if you wish. None takes any space, don't remove this. 

When we change to the new system, we can revisit this and talk about what to have and not to have.

**Comment by wmbutler** [comment]
@jonnybitcoin funny you say that because I toggle to the large market as well...

**Comment by wmbutler** [comment]
#361
