### ISSUE TITLE
OpenBTC Withdrawal - No response

### ISSUE THREAD

**Issue by Jrejoire** [bitshares/bitshares-ui#680]
Hey everyone, 
I'm having bit of an issue on BTS exchange. I'm trying to withdraw my open BTC to a paper wallet in prevision to the hard fork. But I get no response when hitting the withdraw button. I tried various amounts... Anyone having issues?

![untitled](https://user-images.githubusercontent.com/33304306/32307857-f3658d5c-bf82-11e7-9517-1af41c88cc22.png)

**Comment by wmbutler** [comment]
Wallet Version:
Account Name:

Try from the deposit/withdraw screen instead under openledger. I'd be curious to know the result.

**Comment by svk31** [comment]
Even more useful: console logs from the dev console.

**Comment by Jrejoire** [comment]
Thanks you for your quick reply. 
I'm using the web version of the wallet, Not sure the version.
Account name: jrejoire-86

The withdrawal through Openledger (OPEN.X) didn't response either. 
Same thing when I click the Withdraw now button.

I tried trading to Steem through Blocktrades but it did the same thing.
I tried various browsers as well but it doesn't seem to be causing the problem.

Any solution is welcome.
Thanks in advance.

**Comment by abitmore** [comment]
Perhaps a time/clock syncing issue?

@Jrejoire: in Chrome, press ctrl+shift+I to get console logs, paste screenshot here.

**Comment by Jrejoire** [comment]
Thanks for mentioning that. It should provide some extra information...
Here is what I got.

![untitled](https://user-images.githubusercontent.com/33304306/32401600-818d4bfc-c112-11e7-9f63-0de47f982212.png)

**Comment by Jrejoire** [comment]
It finally worked out for me. I added BTS to my account, renewed my Private Memo key, then used BTS for the fee. Might have been the issue. Thank you so much for helping out everyone! ;-)

**Comment by svk31** [comment]
Yea, the problem was your memo key, one question is how you ended up logged in but without access to your memo key. Have you used the cloud wallet migration form to setup new keys?

**Comment by Jrejoire** [comment]
Not sure why. It worked for me before. I did have access to a Memo key but I just renewed it. I suspect the problem being because of having no BTS on my account. I'm glad it turned out fine for me. Hope it helps others with the same issue.

**Comment by abitmore** [comment]
This is still a bug and need a fix.

**Comment by wmbutler** [comment]
This error also needs to be handled on the new #588 Withdraw Modal since the old one will go away. Tracking the hours to fix the issue on #777

**Comment by abitmore** [comment]
Should have been fixed in #777.
