### ISSUE TITLE
Can't load market

### ISSUE THREAD

**Issue by page1** [bitshares/bitshares-ui#681]
I created this issue in core, but I think its probably best here. (unless its an underlying issue)
https://github.com/bitshares/bitshares-core/issues/457

I can't get the markets to load - https://wallet.bitshares.org/#/market/BTS_BTC
![image](https://user-images.githubusercontent.com/6609556/32311175-b7e0d21c-bf5c-11e7-84c8-9a4af3a5522a.png)

I've tried with chrome and edge.

I just downloaded the client and this is what I see.
![image](https://user-images.githubusercontent.com/6609556/32311837-4f8d26f8-bf60-11e7-9fee-575ba247f8a3.png)

Any ideas? Its just completely stuck loading.

**Comment by page1** [comment]
Maybe this invalid date is related?
![image](https://user-images.githubusercontent.com/6609556/32311968-d573ab02-bf60-11e7-9548-817e33967914.png)

**Comment by startailcoon** [comment]
Have the same issue as well, it's not only you. Using Edge gives the same loading error. I think there is something in the last update if the UI that made this.

**Comment by svk31** [comment]
Unrelated to dates, it's from the new highlighting of your own orders in the orderbook. I'll put out a hotfix during the day, will include a fix for the dates as well.
