### ISSUE TITLE
[.1] Hash Download for new release empty

### ISSUE THREAD

**Issue by compumatrix** [bitshares/bitshares-ui#682]
hash_history_dist_2.0.171102.zip is empty

**Comment by compumatrix** [comment]
any progress on this issue?

**Comment by happyconcepts** [comment]
Does this help, from [bitshares download page](https://bitshares.org/download/) 

BitShares 2 (October 25th, 2017 / GUI November 2nd, 2017)

  Windows
sha256: 4e12af37e36493f42d59a09b903e1d7cfcad00cbc595ee4a697ac3576de9ad0c

  Mac
sha256: cc06cff51605714bdb8c07d74cf38012e159c5b7142b1598c87c66bf21306205

  Linux
sha256: 7ae0a3b873ca265669f7c913829bacfab401bc71b00e2b7575d2477ca8f28d44

**Comment by compumatrix** [comment]
thanks @happyconcepts but what we need is the hash_history_dist.zip file for the current release.

**Comment by svk31** [comment]
Still happened in this automated build so I updated it manually instead.
