### ISSUE TITLE
Who decided to change the default faucet and why?

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#683]
Who made the decision to ninja change the default registrar faucet (which is not even working) and why? 

Let me remind you that openledger offers tons of access nodes, they fully deserve to be the default faucet.

also, I *HOPE* whoever made this decision checked with bitshares.eu that they disable the "default proxy" setting, or else you'll commit to voter bias in the reference client.

**Comment by kimchi-king** [comment]
Reducing the affiliate percentage and changing the referral link all together without notifying the community is totally uncalled for.

How does something like this happens?

I don't believe this was thought through as well as it should have been and reflects poorly on the processes we all hold dear.

**Comment by wmbutler** [comment]
Agreed. I'll get a statement out on this soon.
