### ISSUE TITLE
[6][gibbsfromncis] Browser Notifications

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#686]
It would be pretty interesting to build in chrome notifications for trade orders.

**Comment by startailcoon** [comment]
System notifications would be a great feature. But we should try to make it universal notifications not just Chrome, so we can use the Windows 10 notification system as well.

**Comment by diogogomes** [comment]
Can this issue be for all major browsers? Chrome, Firefox, etc.

Maybe renaming to **`Browser Notifications`**?

**Comment by wmbutler** [comment]
Would be nice if we also provided a setting area for:

- [ ] enable/disable notifications

This would help users by not forcing them to enable/disable.

**Comment by gibbsfromncis** [comment]
@wmbutler lets discuss all things about this and I can work on this task. 

For now I see the following things to do:

- [ ] Prepare the list of events to be notified (like bought something / sell something etc) (I guess @wmbutler should provide me this list) 

- [ ] Add `enable/disable all notifications` option on Settings

- [ ]  Add `enable/disable` for specific notification on Settings (if we have a large list of events to be notified user may be want to receive some specific notifications)

Like this:
<img width="273" alt="screenshot 2018-02-01 14 12 19" src="https://user-images.githubusercontent.com/35899973/35680201-f1052120-0759-11e8-8f0a-f43da0c37c29.png">
<img width="277" alt="screenshot 2018-02-01 14 12 08" src="https://user-images.githubusercontent.com/35899973/35680202-f121895a-0759-11e8-9feb-e79025cb0ffb.png">


- [ ] (optional) Add some section on UI where all notifications can be collected. (I can keep all notifications on cookies so user be able to see all of them, mark as read, disable specific notifications or click "manage" and be redirected to Settings -> Notifications page) (the analog of [Facebook Notifications](https://www.wikihow.com/images/thumb/6/66/View-Your-Facebook-Notifications-Step-8.jpg/aid261180-v4-728px-View-Your-Facebook-Notifications-Step-8.jpg))

- [ ] Add Notifications for Chrome

- [ ] Add Notifications for Firefox

- [ ] Add Notifications for Opera

- [ ] Add Notifications for Safari

I've made some research and found this library - https://alexgibson.github.io/notify.js/. It looks quite enough for our requirements and supports all browsers we need

Please make sure notifications will be send only if tab with bitshares is opened. We have another way to send notifications even tab is closed but we need backend for this or design Browser extension. It may be cool but lets make it like a next part of this task.

**Comment by gibbsfromncis** [comment]
@wmbutler please claim me if you want me to work on it :)

**Comment by gibbsfromncis** [comment]
@wmbutler I don't know a whole bitshares system. Please help me to extend the list of events:

The list of notifications:
- New coins come to account
- Coins Sold on EX
- Coins Bought on EX

**Comment by wmbutler** [comment]
Start simply. Observe transfer operations only.

**Comment by gibbsfromncis** [comment]
@wmbutler 

1) Now when user opens app for the first time browser will ask him to allow notifications
2) For now supported only "transfer to me" notifications but it's scaleable and easy to track more events and fire notifications for them.
3) If user disabled permissions for Notifications on Browser Settings (or just click Deny when browser ask for permission to send notifications) and user has "Allow browser notifications" on settings I display the following message: 

<img width="1440" alt="screenshot 2018-02-15 01 05 21" src="https://user-images.githubusercontent.com/35899973/36234956-33ff3b66-11ee-11e8-8ac6-c215bbd3c184.png">
(Link opens google - turn on browser notifications, on new tab)

If Notifications disabled there is no any message:
<img width="373" alt="screenshot 2018-02-15 01 21 08" src="https://user-images.githubusercontent.com/35899973/36235019-88cdad12-11ee-11e8-9141-6bee8ec696ca.png">

4) User is able to disable specific event (for now we have only one event) 

<img width="366" alt="screenshot 2018-02-15 01 17 02" src="https://user-images.githubusercontent.com/35899973/36235068-c219a8aa-11ee-11e8-8d4f-eb54b90b02f2.png">
<img width="385" alt="screenshot 2018-02-15 01 13 28" src="https://user-images.githubusercontent.com/35899973/36235069-c239007e-11ee-11e8-890b-37eb58361d0a.png">
<img width="374" alt="screenshot 2018-02-15 01 11 03" src="https://user-images.githubusercontent.com/35899973/36235070-c25461fc-11ee-11e8-8af6-2dab6e7f80db.png">

**Comment by gibbsfromncis** [comment]
Pull Request: #1172
