### ISSUE TITLE
My Portfolio should show total quantity of each asset

### ISSUE THREAD

**Issue by vanissoft** [bitshares/bitshares-ui#687]
At this moment Account shows the asset balance distributed between "My Porfolio" "Open Orders" and "Margin Positions".
In Bittrex, for example, the "Wallet" contains all the assets, including the ones in sell orders. They are distributed in balance, available and open orders. 
IMO have more sense if the Portfolio would show Qty and Value we got and Qty and Value available (total minus the sell orders).
Maybe putting totals in "My Portfolio" and creating a new tab called "Available" could do the job, and changing color of the total showed in "My Portfolio" to white for matching with Account value.

**Comment by landry314** [comment]
I too agree that one tab containing everything would be easier than switching tabs constantly, like how this program used to be. If you have a lot of assets then the tabs become more useful, yes, but I too would like a tab that contains a list of all the assets I am currently working with and their totals...

![hide zero balances off](https://user-images.githubusercontent.com/6866501/32372783-b1d4e5f0-c06c-11e7-9553-c8b804e8ef78.jpg)

The new structure of the Portfolio section is discussed in issues #604 and #641. You might want to read them to catch up with design decisions.

**Comment by fractalnode** [comment]
for me very important column would be:
whats is percentage value of every assets in the whole portfolio?

**Comment by wmbutler** [comment]
@fractalnode please open a separate issue for your request.

**Comment by ai3d-brodie** [comment]
Yes agree portfolio should include open order funds similar to any other exchange. thx

**Comment by abitmore** [comment]
Should have been done. See #2655.
