### ISSUE TITLE
[1][mattbeckman] Sort order in Portfolio is unreliable

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#689]
I find that sometimes sort activates and sometimes not. It happens frequently enough that with just a little bit of fiddling I think you can reproduce.

**Comment by svk31** [comment]
Sorting of what?

**Comment by startailcoon** [comment]
I think @wmbutler talks about the sorting of assets on the account dashboard, I've had the same issues using it in the new version.

I'll try to reproduce some logging.

**Comment by ppitonak** [comment]
Sorting of assets in "My Portfolio" tab works fine for me but I have three objections:

1. smartcoins are sorted as if they didn't have "BIT" prefix so it produces somehow strange results - e.g. BTS, STEALTH, bitUSD but I would expect bitUSD, BTS, STEALTH
2. when I click on "Asset" column header, it sorts assets in ascending order but when I click it second time, nothing happens
3. sorting by "Price" or "Value" produces strange results

**Comment by mattbeckman** [comment]
I'll handle this one.

**Comment by wmbutler** [comment]
@mattbeckman I added time to this and have included this screenshare to clarify the problem:

- [ ] Sort numerically and include `--` values as "lower" than 0

```
100
99
0
0
--
```

![sorting](https://user-images.githubusercontent.com/1254810/32902098-1a55855e-cab7-11e7-8b13-b7711a747984.gif)
