### ISSUE TITLE
[.5] Add bitshares-core version to witness list

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#690]
Column header: VERSION

![screen shot 2017-11-03 at 3 15 55 pm](https://user-images.githubusercontent.com/1254810/32394130-10ccde04-c0aa-11e7-987b-5e9bfe320f2d.png)

**Comment by startailcoon** [comment]
Correct me if I'm wrong, but the `witness_object` in the BitShares chain does not contain this information.

https://bitshares.org/doxygen/classgraphene_1_1chain_1_1witness__object.html

**Comment by svk31** [comment]
You are correct, there's no way to know this information.
