### ISSUE TITLE
[4][zhyupe] Portfolio flash / glow / pulse on price change

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#691]
This is cosmetic, but a green/red flash based upon price movement draws the eye and help the observer intuitively understand the direction of the market. With our low liquidity, this won't be too active, but I do think it would be a subtle UX win.

Make all three values the same color and follow the pulse css.

- [ ] pulse %change
- [ ] pulse price
- [ ] pulse value

**Comment by startailcoon** [comment]
I can take this task

**Comment by wmbutler** [comment]
It might be better to just have the number glow on price change... Maybe have it subtly go from green to bright green and back.

**Comment by wmbutler** [comment]
Here is a codepen for what I'm thinking.

https://codepen.io/wmbutler/project/editor/APypBD

**Comment by startailcoon** [comment]
Preview of the function. The delay is most likely due to me debugging and running a lot at the same time. The code adds/removes the desired flash clash and is up to the browser/system.

![bitshares-marketflashonchange](https://user-images.githubusercontent.com/12114550/34013906-89151982-e119-11e7-9597-886afbe91eb6.gif)

**Comment by wmbutler** [comment]
My original intention was to apply this to Portfolio. That's why I included:

- [ ] pulse %change
- [ ] pulse price
- [ ] pulse value

in the description. Also, the intended effect was to have the font color of price and value = the color for % channge even when the pulse effect was not triggering. This would reinforce the direction of the price action (red/green for up down and white for no movement) over 24 hours. Can you update this if I add .5 tor he issue?

**Comment by startailcoon** [comment]
> My original intention was to apply this to Portfolio.

That makes total sense, didn't even knew it was to be honest. I may have mixed your idea up with some other issue requesting flash on the market tabs.

**Comment by startailcoon** [comment]
When trying to work with the change on the portfolio dashboard I get the following issue, and I have no idea how to fix it.

![image](https://user-images.githubusercontent.com/12114550/34069568-d30f49e0-e254-11e7-8fa7-724961497b67.png)

**Comment by startailcoon** [comment]
# Pulse on Dashbaord Change

Pulse should now work on the dashboard as well. Even though the update isn't that frequent. 
A revisit to that function may be in order.

![image](https://user-images.githubusercontent.com/12114550/34082227-b0eaa614-e35a-11e7-89bf-2c391f6ef255.png)

**Comment by wmbutler** [comment]
- [ ] Since quantity does not change, you can leave it white and not apply the pulse to it.
- [ ] Value should be colored appropriately and pulse.

**Comment by svk31** [comment]
I prefer to keep only the change column colored as it was before.

![image](https://user-images.githubusercontent.com/6890015/34121823-a93b92d6-e42a-11e7-994a-337174180706.png)

**Comment by startailcoon** [comment]
I agree with @svk and reverted the Volume column to have no color.
The volume can change regardless of price changes.

**Comment by wmbutler** [comment]
+1 hour

**Comment by wmbutler** [comment]
@startailcoon

**Comment by wmbutler** [comment]
Hey, please remove your assignment if you aren't able to complete.

**Comment by zhyupe** [comment]
Claimed.
And I need to make sure if this effect is only applied to portfolio.

**Comment by wmbutler** [comment]
Spend some time posting some proposed pulses here before you implement it. There are a lot of different ways to implement this and it might be nice to get some opinions on the animation here.

**Comment by zhyupe** [comment]
https://codepen.io/zhyupe/pen/yvgXEB
![gif](https://user-images.githubusercontent.com/2197479/35993470-6db0d6da-0d48-11e8-9eb9-595c7acb44cb.gif)

Ported a pulse from exchange

**Comment by wmbutler** [comment]
Looking great.... Just want to talk through some details since there are several states related to the pulse and what it means.

- If the price has gone in an upward direction, we pulse green and leave the price green
- If the price has gone in a downward direction, we pulse red and leave the price red
- 24hr change should never pulse
- volume should never pulse

What happens if a trade occurs and the price does not change? Do we pulse the same color as the previous pulse?

**Comment by zhyupe** [comment]
The price won't pulse if it's not changed. We can keep it's color unchanged.

**Comment by wmbutler** [comment]
In the spirit of full understanding, do you agree with my points above? If not, let's discuss here so we can clear up any potential mis-understanding.

**Comment by zhyupe** [comment]
Agree with 3,4.
Have a little concern about 1,2. The pulse are meant to represent real-time changing direction *compared to previous state*. But if we keep it green (red), it then can be considered as it's gone upward (downward) since a specific time, and may be confusing if it's different with 24hr's change.

BTW, it suddenly come to me if there are really some people staring at portfolio page instead of market or somewhere more important ... maybe real-time changing indicator(pulse and stay normal) + "change since you leave" indicator is a better solution.

**Comment by wmbutler** [comment]
Glad we are having this conversation. If you think through the pulse, the goal of it is to draw your eye to the change and then leave it in the most recent state. Consider an uptick. An uptick in price without a pulse would be green, even if the previous price had been downward (red). So normally, it would turn from red to green on an uptick.

The intention of the pulse it to draw your eye to a lighter shade of the direction of movement and then settle on the appropriate color indication so....

Price ticking up pulses light green to green and stays on green.
Price ticking down pulses to light red and stays on red.

**Comment by svk31** [comment]
https://github.com/bitshares/bitshares-ui/pull/1214#issuecomment-368857528

I see the original intent was to leave the color in place so that's fine then. The animation is still so subtle it's not really noticeable but we can tweak that, same goes for the colors being used. So I'll merge the current PR and we can iterate some more from there on my two points above.
