### ISSUE TITLE
[.5][startailcoon] Roboto instead of Roboto Condensed in tables?

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#693]
Roboto Condensed

![screen shot 2017-11-03 at 6 37 33 pm](https://user-images.githubusercontent.com/1254810/32399697-2a807790-c0c6-11e7-86d8-41b63805cc50.png)

Roboto

![screen shot 2017-11-03 at 6 38 54 pm](https://user-images.githubusercontent.com/1254810/32399709-4dedde02-c0c6-11e7-99b6-c9698b6df74b.png)

These attributes will help with legibility as well:

font-family: Roboto;
    font-style: normal;
    font-weight: 300;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;

**Comment by startailcoon** [comment]
I think the second image is harder to read, but it may just be the screen capture.

I can claim this task

**Comment by wmbutler** [comment]
I'm not sold on it. Maybe with a font weight of 400. Maybe post a few samples. My main goal here is to move away from condensed because I think it has its own set of readability problems.

**Comment by startailcoon** [comment]
Agree, condensed font has its own issues as well and isn't the best choice. Bold or Condensed fonts shouldn't be used unless you're trying to highlight something particular. Normal text, like this, should be using something more of standard. 

I will post a few samples and we can go forward after that.

**Comment by startailcoon** [comment]
Today we use RobotRegular for the header of the table and RobotCondensed for the table body. I suggest we switch these around, example in Take 2 is what I like the most.

Table Header uses a `font-weight: 600` and `font-size: 80%`
Table Body uses a `font-weight: normal` and `font-size: 100%`

Here are a few samples.

# Original Today:
Using: 
```
Table Header
@mixin RobotoRegular {
  font-family: 'Roboto-Regular', arial, sans-serif;
  font-weight: normal;
  font-style: normal;   
}

Table Body
@mixin RobotoCondensed {
  font-family: 'RobotoCondensed-Regular', arial, sans-serif;
  font-weight: normal;
  font-style: normal;
}
```
![bitshares-dashboardfont-current](https://user-images.githubusercontent.com/12114550/32407082-bf4190b8-c183-11e7-9287-9656e665e485.png)

# Take 1
Using the same header font, but body uses RobotRegular suggestion by wmbutler
```
Table Header
@mixin RobotoRegular {
  font-family: 'Roboto-Regular', arial, sans-serif;
  font-weight: normal;
  font-style: normal;   
}

Table Body
@mixin RobotoRegular_1 {
  font-family: 'Robot-Regular', arial, sans-serif;
  font-weight: 300;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}
```
![bitshares-dashboard_font-take1](https://user-images.githubusercontent.com/12114550/32407096-0a0cf4c0-c184-11e7-817d-4823d2c5f254.png)

# Take 2
Using Roboto Consedsed for the table header, and the suggested Robot Regular for the body.
```
Table Header
@mixin RobotoCondensed {
  font-family: 'RobotoCondensed-Regular', arial, sans-serif;
  font-weight: normal;
  font-style: normal;
}

Table Body
@mixin RobotoRegular_1 {
  font-family: 'Robot-Regular', arial, sans-serif;
  font-weight: 300;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}
```
![bitshares-dashboard_font-take2](https://user-images.githubusercontent.com/12114550/32407110-3adbbf6e-c184-11e7-8c2f-4d1a09a66bf3.png)

**Comment by wmbutler** [comment]
Let's try to find 1 font for both I think that Roboto will work for everything (not Roboto-Regular). Try with a 400 weight and go a few a point size smaller.

**Comment by startailcoon** [comment]
## Take 3

This time we use the `Robot Light` font, which is the only other font I can find on [the font specifications](https://www.fontsquirrel.com/fonts/roboto).

![bitshares-dashboardfont-take2](https://user-images.githubusercontent.com/12114550/32413294-fb72afe6-c20e-11e7-94f9-4543662f4d51.png)

```
Font: Roboto Light

Table Header
font-weight: bold (instead of 600)
font-size: 0.8rem (instead of 80%)

Table Body
font-weight: normal
font-size: 0.85rem; (instead of 0.9rem)
```

## Take 4

This is an alternative to Take 3, but with the first column of the tbody in bold. This is because the blue link to the asset can disappear in the blue background. 

![bitshares-dashboard_font-take4](https://user-images.githubusercontent.com/12114550/32413353-292e70c2-c210-11e7-97cd-0851a63fe1b2.png)

**Comment by happyconcepts** [comment]
>Let's try to find 1 font for both I think that Roboto will work for everything ...

The Roboto Light is hard to see against the table background; why not go with Roboto as suggested?

**Comment by startailcoon** [comment]
There is no "Roboto" font as far as I can tell. 
https://www.fontsquirrel.com/fonts/roboto

**Comment by wmbutler** [comment]
@happyconcepts I added in RobotoMedium and set most of the site to RobotoRegular which looks pretty good. It's thick enough. It does need some size tweaking in the tables. Maybe you can take a shot a that on branch 693-RobotoMedium. I'm not taking any pay for this issue.

**Comment by wmbutler** [comment]
![screen shot 2017-11-07 at 5 14 23 pm](https://user-images.githubusercontent.com/1254810/32522999-26e02696-c3df-11e7-9e81-9a8f8440ad18.png)

**Comment by startailcoon** [comment]
Idd, Roboto Regular is the base font as I understood as well. Good to get it all uniformed and in a nice font.
