### ISSUE TITLE
[.5] Asset Doesn't Appear After Creating User Issued Asset Until A Reload

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#694]
Steps To Reproduce:

1) Go to ACCOUNT -> Advanced Features -> Issued Assets
2) Create an asset

The asset will not appear in the list of Issued Assets until after the user reloads the program. A reload solves this problem.

I am using the Mac OS stand-alone program.

**Comment by svk31** [comment]
I think this is actually a bitshares-core issue, it seems there's no update of the account subscription following an asset creation event, so our chain state doesn't get updated. Try making an issue in the bitshares-core repo instead.
