### ISSUE TITLE
[1.5] Add current price quote to Open Orders Screen

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#698]
Column: QUOTE

![screen shot 2017-11-04 at 3 24 28 pm](https://user-images.githubusercontent.com/1254810/32409155-58740212-c174-11e7-8294-a5dd71ddbeeb.png)

**Comment by landry314** [comment]
Wouldn't a "Current Price" column go well with a "Current Value" column if the "Order Value" column was renamed as I suggested in issue #624? I feel this would make it clearer.

**Comment by calvinfroedge** [comment]
@wmbutler To clarify here, you want a new column named "Quote" added that shows the current price quote for the asset. Should this go between "Order Value" and "Trade"?

**Comment by wmbutler** [comment]
- [ ] Maybe it would be better between Market and Price

**Comment by calvinfroedge** [comment]
@svk31 I'm almost done implementing this but need to know how to retrieve the current quoted price. 

```
let priceQuote = utils.get_asset_price(1, quote, 1, base);
```

I'm assuming that the `1s` need to be the highest current offer price...can you validate that assumption and let me know how I can retrieve that value?

**Comment by svk31** [comment]
I added a new utility component you can use to get the latest market price, MarketPrice.jsx.

Syntax:

```
<MarketPrice
   base={base.get("id")}
   quote={quote.get("id")}
   marketId={base.get("symbol") + "_" + quote.get("symbol")}
/>
```

**Comment by wmbutler** [comment]
- [ ] Need to add last `<td>`

![screen shot 2017-11-26 at 11 51 31 am](https://user-images.githubusercontent.com/1254810/33242834-7b3d2926-d2a0-11e7-8acb-b19acd1254e0.png)

- [ ] Quote math should be same as price math

**Comment by wmbutler** [comment]
- [ ] Quote should flip when price flips. See licecap. I added .5 to this since this likely required more work than you anticipated.

![flip](https://user-images.githubusercontent.com/1254810/33300787-c7a9615e-d3b7-11e7-829e-13188828600b.gif)

**Comment by calvinfroedge** [comment]
@wmbutler No problem
