### ISSUE TITLE
When creating a PM or MPA via the GUI...

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#699]
@svk31 saw this conversation and wanted to make sure you could check it out.

Tim, [04.11.17 15:07]
When creating a PM or MPA via the GUI, the field for minimum number of price feeds cannot be modified. It recognizes the default 7 as an integer, but once modified, it thinks the input is not an integer. So to even create my PM, I had to create it with the default input, and then update the feed requirements using the update GUI which did recognize 1 as an integer

Peter Conrad, [04.11.17 15:08]
I think that's a bug in the UI.

**Comment by svk31** [comment]
Unable to reproduce, integer inputs work fine for me.
