### ISSUE TITLE
[1] Asset Whitelist Authority

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#70]
_From @xeroc on January 17, 2017 14:22_

We need to update the asset-update page to allow adding/removing of white- and blacklist authorities.
Basically, it's just an array of user-ids and can be changed with the issuers active key by using `asset_update` op

_Copied from original issue: cryptonomex/graphene-ui#899_

**Comment by wmbutler** [comment]
@svk31 should we upgrade this to a feature? Wondering how heavy this lift is and if I should add it into 171015?

**Comment by svk31** [comment]
Probably quite easy to add.
