### ISSUE TITLE
Openledger Faucet - auto sets as proxy

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#703]
Yup, they did it. 

New sign-ups auto set proxy to openledger, which breaks the neutrality of the reference wallet. 

Is there any faucet without this setting?

Needs to be changed asap

**Comment by grctest** [comment]
Voting proxy, or the faucet used to sign up new users?

If the first, that's not acceptable. If the later, perhaps a round-robin style faucet selection mechanism within the light client would be acceptable?

**Comment by btsfav** [comment]
@grctest new sign-ups are set to auto-vote for OL proxy

**Comment by grctest** [comment]
> @grctest new sign-ups are set to auto-vote for OL proxy

That's entirely unacceptable, IMO.

**Comment by xeroc** [comment]
The reference/downloadable wallet/wallet.bitshares.org ... needs to decouple from OpenLedger anyways ...

**Comment by btsfav** [comment]
@xeroc 

> referrer should be committee-account or null-account ..

default ref? yea, just make sure to not destroy the referral system. I prefer to use the core wallet to send refs to

**Comment by wmbutler** [comment]
Action items proposed for **reference wallet** from bitshares.org:

- [ ] Use .eu faucet
- [ ] Use referral r=bitshares.foundation (for now)

Longer term plans:

- [ ] bitshares to fund its own faucet

**Comment by btsfav** [comment]
@wmbutler 

> Use referral r=bitshares.foundation (for now)

why? they will be registrar

**Comment by wmbutler** [comment]
They pay for the .eu faucet right now. But they would be earmarking the referral for the foundation, not for their company. Again, this is a short-term thought.

**Comment by btsfav** [comment]
mh yeah, as long as the regular referral program works and this is just a default setting

**Comment by startailcoon** [comment]
> They pay for the .eu faucet right now. But they would be earmarking the referral for the foundation, not for their company. Again, this is a short-term thought.

Why not make an account called `registrar.bitshares.foundation` and any money earned towards it for referrals are automatically used for new registrations. This way we can track that the funds earned for the registration process isn't used for anything other than what it's intended for.

Any usage of these funds, transferring funds out of this account, would then require a worker proposal.

**Comment by wmbutler** [comment]
Ronny indicated that it's going to be reverted on the openledger site, but this was a change we were looking at making regardless since the reference wallet should be impartial.

**Comment by startailcoon** [comment]
If anything, this made us aware of a potential issue. They just made this much more aware when doing this, even if it was unintentional. Going forward with a new faucet should be regarded as a higher priority imho.

**Comment by xeroc** [comment]
Just to clarify,
when using the faucet url: `https://faucet.bitshares.eu/onboarding`, these are the settings:
* registrar: `bitshareseurope` (pays the fee)
* referrer: `onboarding.bitshares.foundation` unless a ref is defined in the request, e.g. via `?r=xxx`

This is the settings from bitshares.eu

![](https://i.imgur.com/cwZkJBP.png)

Every single line can be discussed further.

**Comment by btsfav** [comment]
@xeroc so we would actually get referral stats like on bitshares.eu? would be awesome

**Comment by happyconcepts** [comment]
So `Default Proxy` should be "none" for the Open ledger faucet.

**Comment by wmbutler** [comment]
@svk31 Let's make this happen as of 11/15. I think we will also want a redirect from:

bitshares.org/wallet/r=xxxxx

to

wallet.bitshares.org/r=xxxxx

This will ensure that old links will continue to work during the transition.

**Comment by fractalnode** [comment]
In the light wallet the new user should be able to type in the referrer and registrar manually. If user skip this optional field, then the default should be set committee-account or null-account.

**Comment by rngl4b** [comment]
There's another issue: as the description from the proxy field resides inside the box, when there's a default proxy new users can't read what that field is for.

I find the faucet's default proxy feature inappropriate. Not much different than encouraging centralized exchanges to vote with their customers stake without agreement.

**Comment by rngl4b** [comment]
It seems to me that this issue is already escalating as expected. Where;s the difference between external and -BitShares based-  private exchanges using their user's stake to vote without approval,  without them even being aware about voting at all?

There may be arguments in favor of the benefits about free competition to obtain users/voters, but if we shadow everyone's possibility to influence decisions by default, how are we far from the corrupted democracies that motivated this technology in the first place?
Wouldn't that result into cheating ourselves with obscurity as security once again?

The only fair solution I can see is to disable the ability to proxy votes in the registration stage,  at protocol level.

**Comment by StaflunD** [comment]
i have the openledger.exchange domain if someone what create a issue

**Comment by abitmore** [comment]
@rngl4b it's not as easy as "disable proxy in registration stage". If a registrar wants to set proxy for a new account, it can register the account with it's own key, then set proxy with another operation, then change the keys to the user requested.

**Comment by abitmore** [comment]
@rngl4b https://github.com/bitshares/bsips/issues/68
