### ISSUE TITLE
[2][mattbeckman] 24hr %change in Portfolio

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#705]
I don't know if this is possible, but can we display the 24hr % change in red/green in the Portfolio view?

- [ ] Column header label: 24hr

up - green (+3,2%)
down - red (-0.9%)

- [ ] display price in same color
- [ ] display value in same color
- [ ] if no change, leave white

**Comment by mattbeckman** [comment]
I'll handle this one if nobody else is. I started looking into it last night. It should be possible, but I'll need to find the cleanest way to do it.

**Comment by calvinfroedge** [comment]
@mattbeckman Any updates here?

**Comment by mattbeckman** [comment]
@calvinfroedge Here is a screenshot. It's late and I haven't finalized it yet, so if you guys have any input, let me know. I should have the PR up tomorrow. 

<img width="328" alt="screen shot 2017-11-16 at 12 40 17 am" src="https://user-images.githubusercontent.com/928380/32881650-c3be03ba-ca66-11e7-8ee9-9b38bddb402e.png">

**Comment by wmbutler** [comment]
@mattbeckman looks pretty awesome.

- [ ] Can you have price and value follow the same color scheme as 24hr?
- [ ] Also, can you change the label to just 24hr to keep the column narrow?

**Comment by wmbutler** [comment]
I added .5 to this issue:

- [ ] Allow user to sort on the 24hr column

**Comment by mattbeckman** [comment]
Are you sure "Value" should be red/green? My approach uses MarketStats to get the 24 hour change, but MarketStats is based on the asset itself not the gain/loss for the user specifically based on qty/transaction.
