### ISSUE TITLE
[.5] Cannot access node

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#708]
IP: `ws://52.70.171.15:8090`

Can you add in some console logs to explain why the web client cannot connect? Also, I'd be interested to know why this node (one that I set up and is synced) is failing.

**Comment by abitmore** [comment]
Need `wss` for web client?

**Comment by svk31** [comment]
Only if you're on a https domain, brut yea hosted wallets like bitshares.org can't use unsecure ws:// nodes

**Comment by svk31** [comment]
Works for me:

![image](https://user-images.githubusercontent.com/6890015/32602497-88518880-c546-11e7-9f11-2f7a1f18f06a.png)

**Comment by svk31** [comment]
Closing since it works fine for me, reopen if you're still having issues and it's not because of using ws from a https host.
