### ISSUE TITLE
Format DATE for non-US users

### ISSUE THREAD

**Issue by MarkoPaasila** [bitshares/bitshares-ui#714]
As a non-US user I find it hard to read dates in the MY TRADES / MARKET TRADES box. Can I have them in ISO-format, automatically localized, or manually localized?

![image](https://user-images.githubusercontent.com/6001014/32543695-03377d98-c47f-11e7-93c7-72c5024cbaff.png)

It doesn't help if the DATE format is based on selected language, as many users have no choice but US-english.

**Comment by svk31** [comment]
Thats how it is now, your screenshot regular Iso dates, not us dates, unless I'm missing something?

I actually fixed this for the last release.

**Comment by MarkoPaasila** [comment]
I can't see it. If there are trades on consecutive day's you can easily figure out that one number represents the day, and the other the month. Also if the other number is greater than 12. But if there's like 7/8/17 and 8/7 you can't tell what the date is unless you know how it's formatted. Here's the ISO standard from w3org:
```
Year:
      YYYY (eg 1997)
   Year and month:
      YYYY-MM (eg 1997-07)
   Complete date:
      YYYY-MM-DD (eg 1997-07-16)
   Complete date plus hours and minutes:
      YYYY-MM-DDThh:mmTZD (eg 1997-07-16T19:20+01:00)
   Complete date plus hours, minutes and seconds:
      YYYY-MM-DDThh:mm:ssTZD (eg 1997-07-16T19:20:30+01:00)
   Complete date plus hours, minutes, seconds and a decimal fraction of a
second
      YYYY-MM-DDThh:mm:ss.sTZD (eg 1997-07-16T19:20:30.45+01:00)
where:

     YYYY = four-digit year
     MM   = two-digit month (01=January, etc.)
     DD   = two-digit day of month (01 through 31)
     hh   = two digits of hour (00 through 23) (am/pm NOT allowed)
     mm   = two digits of minute (00 through 59)
     ss   = two digits of second (00 through 59)
     s    = one or more digits representing a decimal fraction of a second
     TZD  = time zone designator (Z or +hh:mm or -hh:mm)

```

By the way I use english in the interface, as there's no Finnish or Norwegian :-)

**Comment by wmbutler** [comment]
I like where @MarkoPaasila is going, but this does present a problem regarding horizontal space. We could solve this by consolidating My Open Orders, My Trades, Market Trades into a single container. This would give us all the room we need if we let each span the full double width.

I think the ISO times are a bit analytical, specifically the "T" and the time zone. I think we can agree that we should display the time in whatever time zone the users' device determines. So maybe:

`2017-01-01 02:34:56 pm`

Leaving padded numbers ensures that the times and dates will line up cleanly. Including am/pm addresses our less technical users.

![screen shot 2017-11-09 at 12 06 34 pm](https://user-images.githubusercontent.com/1254810/32621845-bcb69fd4-c546-11e7-87ef-b07b961bd1a6.png)

**Comment by MarkoPaasila** [comment]
Yes the "T" clutters it up.

I see the time is in 24 hour format already for me, so that's great. Does it automatically change to 12 hour format based on location or operating system locale?

**Comment by svk31** [comment]
The date format is set depending on the browser locale, which is not necessarily the language of the browser. The formats are limited to two types: en-US and "everyone else". In my case, the browser is in en-US, but my browser locale is no-NO. Therefore, I see dates formatted dd/mm hh:mm:ss, which is I want to see.

Bill, as you can see in his screenshot, has a en-US locale so his dates are formatted mm/dd hh:mm:ss, the way the Americans do it. I thought only the Americans used that in daily affairs but it seems the ISO standard is the same. 

I'll ask again, do you want the dates to be shown as mm/dd? Having the year is pointless and won't help clarify your issue, and only takes up space. am/pm is also pointless here, just wastes space.

**Comment by startailcoon** [comment]
Closing this as nothing new has come up since last year.

There is a hover state that will give the user more information of the dates as well, not sure if this was added before or after this issue, and should suffice imho.
