### ISSUE TITLE
Top "Account Dropdown Menu" Doesn't Scroll

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#715]
When a user has a local wallet with so many accounts that they will not all fit on the screen when he pulls down the "Account Dropdown Menu" then the menu should scroll to get to them all...

Steps to Reproduce:

1) Create a wallet with many accounts. I count 19 that will fit on my screen.
2) Make sure you didn't star any of them (or all of them, same thing).
3) Click on the active account name on the upper right to activate the menu.

Any accounts past what will fit on the screen will be off the bottom of the screen with no way to get to them.

Here is the thing, very few people will have that many accounts in their list. I doubt anyone would need over 19 accounts in that menu, but sure, there are cases so it would be good to fix this.

Another idea is to make it more obvious how we can star our accounts to get them in the menu. As soon as you star even one account then it eliminates the rest from the menu except the active one and the starred one. We can customize this menu. Someone who has a lot of accounts but doesn't know this might bump into this problem. All the accounts ARE accessible from the "b" menu anyway where they can be starred...

As the address book feature is implemented (issue #167) and this list of followed accounts merges with that then it will also have to remain clear what the starring does to order to prevent this long list from developing... or make it scroll, haha.

OR, just eliminate the "zero star --> all accounts are in the list" system so the user must add them himself... still, he might want a lot of accounts...

**Comment by startailcoon** [comment]
I guess this is also related to #630 As well.

**Comment by wmbutler** [comment]
I doubt we will implement a 'scrolling menu'. It makes more sense for a user to go the accounts screen if they are keeping more items in the menu than will fit on their screen.
