### ISSUE TITLE
[.1] Star on Upper Left of Followed Accounts Strangely Sorts Alphabetically

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#716]
In what I call the "Followed Accounts" table in the "b" menu there is a star in the upper left corner above all the other stars, I guess it is the column header. If you click on it it sorts the list alphabetically which is not as you would expect. Clicking on the word Account next to it also sorts alphabetically as you would expect.

I would expect clicking on the star to be a "select all stars" feature... right? We could make it one... or make it do nothing.

**Comment by landry314** [comment]
If this Address Book merger in issue #167 is happening, this might just get sorted into that rewrite.

**Comment by wmbutler** [comment]
Agreed regarding #167

**Comment by wmbutler** [comment]
I'd opt for the click action to be removed.

**Comment by efork** [comment]
Removed click, pr submitted

**Comment by startailcoon** [comment]
The star symbol sorts the list by "star" status ASC / DESC and secondly by name equally depending on the order.

I would expect clicking on the star in the header to sort by status ASC / DESC and name would always be in ASC order.

I don't agree that we should remove the sorting function entirely

![bitshares-sortingstar](https://user-images.githubusercontent.com/12114550/33675612-68a93a14-dab3-11e7-98c2-4a9647589e57.gif)

**Comment by svk31** [comment]
Don't agree that this needs to be removed either, like startail says there's nothing unexpected about that sorting.
