### ISSUE TITLE
[.5] Filled order in background resets borrow form fields (margin update) 

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#718]
If you are trying to update an existing margin position or start a new one and a trade goes through on your active account initiating a pop-up notification and adjusting your balances.  This in turn resets the form fields you are trying to adjust with the margin position.  

If many trades are going through in the background this makes it impossible to use the update margin position window.

I don't know if its the notification popup or more likely the changing balance that triggers the reset.  

The form should adjust its available balance numbers if your balance has changed but should not change the values you have entered in the form.

**Comment by wmbutler** [comment]
@calvinfroedge you still working on this?

**Comment by calvinfroedge** [comment]
Issue closed as this was merged
