### ISSUE TITLE
[.25][startailcoon] Margin update Inverted Price limited to 2 decimals. 

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#719]
The 2 decimal precision is fine for most SmartCoins but does not work for bBTC.  

If you go to borrow bBTC it shows 106,796.92 BTS/bitBTC  but if you click to invert the price it shows only 0.00 

 It should show 0.00000936

Need a smarter precision adjustment based on the asset and it's position.

When the SmartAsset is the quote currency (bBTC / BTS), use the assets precision number. 
When the SmartAsset is the base currency (BTS / bBTC), use BTS precision. 

In addtion, (and possibly for another issue) when quoting the price, it's not necessary to give the full bBTC / BTS.  The "per BTS" portion is presumed.
So Just:
106,796.92000 BTS 
or flipped
0.0000000936 bBTC
is ok.  

The same applies to the trade screen where we quote the price in the market and buy and sell fields.  the full "this per that" (BTS / open.BTC)  isn't necessary.  It is presumed that a price represents an amount "per 1 unit" of the other currency.  Just give the currency that the price is quoted in.  Saves space too.  As well, math tends to insight cognitive load, even if it's simply 10 / 1.   Just say 10

**Comment by Xeldal** [comment]
@wmbutler 
I'd call this a bug, unless your saying it is an intended function to not show the actual price in bBTC.

**Comment by startailcoon** [comment]
I can take this task

**Comment by wmbutler** [comment]
It's yours!
