### ISSUE TITLE
[.25][startailcoon] UI color is too hard on eyes on white theme

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#722]
Block number and sync status:

![0029-11-10 4 04 55](https://user-images.githubusercontent.com/861659/32624761-8dd24e66-c5cd-11e7-9d46-f4435d66fb45.png)

Node list (Access in Settings):

![0029-11-10 4 11 34](https://user-images.githubusercontent.com/861659/32624784-a6a33ad6-c5cd-11e7-91cd-d8e7d81c1907.png)

These colors are really terrible at least on white theme. Please consider use darker colors instead of hard colors like #00FF00.

**Comment by ethanwillis** [comment]
I'd like to claim this.

**Comment by wmbutler** [comment]
It's yours!

**Comment by wmbutler** [comment]
Can you have this finished today?

**Comment by wmbutler** [comment]
@ethanwillis

**Comment by startailcoon** [comment]
I'll fix this
