### ISSUE TITLE
[.1][startailcoon] Typo in Deposit/Withdraw for Blocktrades

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#723]
Steps to Reproduce:

1) Go to Deposit/Withdraw
2) Select Blocktrades as the Transfer Service
3) Look to the right of "Current Balance"

It says "PLEASE SEND YOUR TO THE ADDRESS BELOW".

There should be a word after "YOUR"... Coin?

**Comment by landry314** [comment]
Haha, there was a typo in the title of this issue too, how fitting...

**Comment by wmbutler** [comment]
Or 'asset'

**Comment by ethanwillis** [comment]
I'd like to claim this.

**Comment by wmbutler** [comment]
Can you have this finished today?

**Comment by ethanwillis** [comment]
@wmbutler Yes, this and #722 Will be finished today and Ill send over a PR

**Comment by wmbutler** [comment]
@ethanwillis

**Comment by startailcoon** [comment]
I'll fix this
