### ISSUE TITLE
Trying to Trade SBUZZ Freezes the Program

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#724]
We probably all got airdrops of this token.

When I go to the Portfolio (Balances) and then click on Trade on the SBUZZ row then it freezes the program. I have to reload to fix it. Anyone else have this happen? It was like that months ago too, by the way...

Maybe it is because there are no markets with recent trades?

Maybe this is a core issue and nothing to do with the GUI...

I am using the newest version of the Mac OS stand-alone application.

**Comment by svk31** [comment]
This was because the genius that created the asset set the asset itself as the preferred market, so the market link was going to the SBUZZ:SBUZZ market.
