### ISSUE TITLE
[0][startailcoon] Available assets trough BlockTrades aren't represented correctly

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#729]
During my rebuild of the Buy Modal I came across an issue regarding the BlockTrades API. I think this should be looked at more closely why we have different sets of assets throughout different parts.

This is just my initial observation so far.

Possible places to look further on
https://github.com/bitshares/bitshares-ui/blob/a3057b3a25a45c1a7843941334ad45fbf9186f7a/app/components/Account/AccountOverview.jsx#L544

which is used for the Buy Modal on 
https://github.com/bitshares/bitshares-ui/blob/a3057b3a25a45c1a7843941334ad45fbf9186f7a/app/components/Account/AccountOverview.jsx#L709

As well as in the Bridge lookup in GatewayActions
https://github.com/bitshares/bitshares-ui/blob/a3057b3a25a45c1a7843941334ad45fbf9186f7a/app/actions/GatewayActions.js#L67-L71

# Issues with BlockTrades API Asset Selections
Found an issue where the Buy Modal doesn't give the same assets for sending as the BlockTrades Bridge page gives. The Bridge also does not give the same results as the BlockTrades.us page or doesn't allow selecting an asset that their page does. 

A few examples follows

### Buy Modal Issues

For example, it's missing LTC and SBD.

![bitshares-buybts-modal](https://user-images.githubusercontent.com/12114550/32698096-0dd9db92-c79f-11e7-8a53-d89b6b7193d7.png)

![bitshares-brdigedeposit-sbd](https://user-images.githubusercontent.com/12114550/32698102-36917252-c79f-11e7-861e-585f5e43e658.png)
![bitshares-brdige-ltc](https://user-images.githubusercontent.com/12114550/32698103-36b74680-c79f-11e7-8f08-4c565b7af938.png)

### Bridge Issues

As their page allows sending LTC for open.DASH, the Bridge page doesn't allow you to do that type of selection.

![blocktrades-trade-opendash](https://user-images.githubusercontent.com/12114550/32698206-ba65a39e-c7a1-11e7-91b4-7eaebdb1d119.png)

**Comment by wmbutler** [comment]
I added two hours onto #651 Will that suffice for resolution? Was this bug addressed over there?

**Comment by startailcoon** [comment]
I did not look further into this issue than my initial findings here, so it's not resolved yet. I can try to solve this issue for the added hours on the other issue.

**Comment by startailcoon** [comment]
This can be related to #1244 as https://github.com/bitshares/bitshares-ui/blob/4c9ddbe7cc49c29be50308f7b9a4c1f8d537a1f4/app/stores/GatewayStore.js#L13 is somewhat related to how bridge assets are populated.

**Comment by startailcoon** [comment]
This issue has been resolved by another PR.
