### ISSUE TITLE
[0.25][startailcoon] Color and Label settlement price to indicate which side it represents

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#732]
**Problem:**
The settlement line on the chart does not indicate which direction (buy or sell) that is represents.  This would be fine if markets were always oriented in one direction but flipping markets is possible.  It takes a bit of mental work to figure out which way the settlement backstops.

**Solution:**
Color the line to match the side of the book it represents.

The settlement price is essentially an off the book buy order for SmartCoins.
When the market is oriented with SmartCoin as the BASE asset.  Color the line to match bid color.
When the market is oriented with SmartCoin as the Quote asset.  Color to match the ask color.

Optional: 
Where the line is labeled.  Include in the text "(bid)" or "(ask)"

**Comment by startailcoon** [comment]
I can do this task

**Comment by wmbutler** [comment]
Should I move this into 171119?

**Comment by startailcoon** [comment]
You could move it to 171201

**Comment by startailcoon** [comment]
@Xeldal I don't exactly understand what you mean with the following
> Optional: Where the line is labeled. Include in the text "(bid)" or "(ask)"

Do you mean where the line sais "Settlement Price"? I don't think we should add more text to that line. The color should be enough I think.

**Comment by Xeldal** [comment]
Yes, that is what I meant.  I agree the color should be enough.
