### ISSUE TITLE
[.5] GUI doesn't load with Firefox 57.0

### ISSUE THREAD

**Issue by tximiss** [bitshares/bitshares-ui#735]
Recently updated to Firefox Quantum 57.0 (64-bit), the wallet is not loading.

No problems with Chromium:
Version 62.0.3202.89 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by wmbutler** [comment]
@svk31 would be nice if you could prioritize this since.

**Comment by btsfav** [comment]
loads, no issues. check your extensions or something.

@wmbutler please close.

**Comment by tximiss** [comment]
All plugins deactivated:
![image](https://user-images.githubusercontent.com/4522822/32908994-9c2f62a4-cb05-11e7-9e15-08236c908b8e.png)
Before Firefox update was running well.

**Comment by btsfav** [comment]
![](https://i.imgur.com/njh3je1.png)

**Comment by tximiss** [comment]
btsfav, seriously, do you want to open a issue saying that Firefox Quantum is not giving problems under Microsoft??  Mine is under Ubuntu, i don't know if it is goes well in all the Linux flavors.

**Comment by btsfav** [comment]
browser behavior should make 0 differences between OS.

you could've just googled some of the errors + ubuntu and try some fixes first. don't want to waste worker time here if possible

**Comment by landry314** [comment]
@btsfav, why are you assuming this is the user's fault without any proof and being so dismissive of his issue? It might be a serious issue for all linux users, who knows? Wait to see if anyone else confirms this issue before trying to close it because "it works for you".

**Comment by wmbutler** [comment]
We do have a working browser solution with Chrome and we have about 125 items that are more critical to adoption than figuring out Firefox. I'm going to close this since we won't realistically have the bandwidth to look at it for at least a few months. We issue a warning for non-Chrome Browsers.

**Comment by startailcoon** [comment]
No issues on Firefox 57.0 on Ubuntu for me.

![screenshot from 2017-11-18 23-01-31](https://user-images.githubusercontent.com/12114550/32985160-87f8ec82-ccb4-11e7-9329-d7ee996d5821.png)

**Comment by landry314** [comment]
Firefox 57 with no extensions enabled does NOT work for me.

This link just remains loading forever:
https://bitshares.org/wallet/#/

**Comment by landry314** [comment]
Firefox 57 for Mac OS with no extensions enabled does NOT load this link:

https://bitshares.org/wallet/#/

It just remains loading forever.

**Comment by btsfav** [comment]
tired on my ubuntu today, no issues too.

@landry314 wallet.bitshares.org is the supported domain

**Comment by vanissoft** [comment]
For the record: It's ok with Firefox 57.0.4 on Manjaro-Rolling
![image](https://user-images.githubusercontent.com/4522822/35187688-f86309e0-fe27-11e7-9351-66a33bbf1d49.png)
