### ISSUE TITLE
[.25][startailcoon] Advanced account creation page and restore page need a "back" or "cancel" button/link

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#738]
https://wallet.bitshares.org/#/create-account/wallet
https://wallet.bitshares.org/#/wallet/backup/restore

**Comment by startailcoon** [comment]
I can take this

**Comment by startailcoon** [comment]
![bitshares_issue738](https://user-images.githubusercontent.com/12114550/33570417-13b37326-d92d-11e7-9155-36956ac5aef0.gif)
