### ISSUE TITLE
Chart snapping to the right on new tick

### ISSUE THREAD

**Issue by rmawatson** [bitshares/bitshares-ui#747]
When viewing a chart with "Clamp Chart Edge" unticked I am able to move the chart left to right. However when a new tick 'arrives' the chart snaps back to have the last bar aligned with the right hand side. I feel like it should stay where I have put it, or even better maintain a constant offset from the right hand edge.

Less important but relevant is that clicking the chart 'gear' icon also causes the chart to pop back to the right.

video attached.
[bitshares_snap_problem.zip](https://github.com/bitshares/bitshares-ui/files/1492577/bitshares_snap_problem.zip)

**Comment by wmbutler** [comment]
This will go away with #361
