### ISSUE TITLE
Fix export of operation history to CSV

### ISSUE THREAD

**Issue by xkrajnan** [bitshares/bitshares-ui#751]
The CSV contains a column titles which are misleading. Example:

DATE | OPERATION | MEMO | AMOUNT
-- | -- | -- | --
11/14/2017, 3:04:33 PM | transfer | xkrajnan-wallet sent 302 BTS to xkrajnan-wallet-2 | 0.21851 BTS
11/14/2017, 2:53:39 PM | account_create | openledger registered the account xkrajnan-wallet-2 | 1.22740 BTS

Column labeled AMOUNT in fact is transaction fee.

Column labeled MEMO is not a memo, but textual description of operation. It should be labeled accordingly. Also, it should be structured better, to simplify further machine processing (and for example import to Calc/Excel).

**Comment by wmbutler** [comment]
This is getting a complete rewrite in #68. Closing and linking to it.
