### ISSUE TITLE
Market does not load after inverting price

### ISSUE THREAD

**Issue by jedebel** [bitshares/bitshares-ui#752]
I have noticed that when I invert the price on the margin tab and than go to market the page will stay blank indefinitely with the three dot animation. If I hit the reload icon on the browser the market will load immediately. The failure to load the market only happens after inverting the price.

Mac OSX Sierra
Chrome Version 62.0.3202.75

**Comment by wmbutler** [comment]
Post a licecap

**Comment by jedebel** [comment]
![invertmarket](https://user-images.githubusercontent.com/30885090/33223861-6f521ad6-d129-11e7-8ffb-21aa16f149b0.gif)

**Comment by svk31** [comment]
I think I already fixed this in staging.
