### ISSUE TITLE
Tooltip in market depth chart should show amounts in both base and quote currency

### ISSUE THREAD

**Issue by ppitonak** [bitshares/bitshares-ui#755]
Market depth chart tooltip shows only price and amount in one currency when you hover over a point in chart, other exchanges show the amount in both base and quote currency.

![tooltip](https://user-images.githubusercontent.com/445100/33162816-d117bbbc-d02b-11e7-85ec-29c71ae47c9d.png)
![tooltip_polo](https://user-images.githubusercontent.com/445100/33162819-d134d580-d02b-11e7-8cbd-9cf9d8d4f90f.png)

**Comment by wmbutler** [comment]
Duplicate since we are moving to #361
