### ISSUE TITLE
[6] Help area css styling of Markdown

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#759]
We need better styling for the Help Markdown in the browser.

https://wallet.bitshares.org/#/help

I'd like to see a mockup plus css to complete this issue here.

**Comment by wmbutler** [comment]
Here is what the current help area looks like:

![screen shot 2017-11-26 at 11 56 56 am](https://user-images.githubusercontent.com/1254810/33242876-f1ec6db6-d2a0-11e7-8997-7407947355ee.png)

**Comment by calvinfroedge** [comment]
@wmbutler Maybe split up the mockup and css tasks?

**Comment by wmbutler** [comment]
I'd really like for someone who is comfortable with both take this. I am not inspired in this area at all!

**Comment by pavel-lipcean** [comment]
![4](https://user-images.githubusercontent.com/5729949/33572232-0171f918-d93b-11e7-9ad0-4a09a5901d19.png)

Hey,

Here's my mock-up for the Help Section. 

I would suggest to have a search input field in there - since - just to go through all the sections is a nightmare to be honest - users should be able to search by the keyword instantly. 

I re-grouped the homepage of the help section into a new - more action-packed area - that blue gradient area. There I combine all the call to action buttons and quick items for users to find and solve their problems. 

As you can see, here I keep it consistent - as in the settings area - so instead of 2 columns, I use all the 4 columns for the grid. 

Also, I introduce here, as in all the other mock-ups - the font-awesome icons. They are fast, modern and will suit all the design needs. And most of all - we will load just one file for them, not like now - multiple files for each icon.

**Comment by pavel-lipcean** [comment]
More than 5 hours on this mockup.

**Comment by wmbutler** [comment]
The title of this issue is: Help area css styling of Markdown. This was not a mockup issue. I'll clarify. Looking for someone who will apply some css styles to this help area to give it consistency.

**Comment by pavel-lipcean** [comment]
I can provide both the css styles and the mock-up. The mock-up was done to see how the end product would look like - as in mock-ups for any designer is faster to make the changes than in the code - it's like a guiding book.

**Comment by wmbutler** [comment]
@pavel-lipcean part of doing mock-ups is to address and respond to input.

- [ ] It's important that you not mix dark and light themes.
- [ ] Also, you added a search area, which, while nice, is beyond the scope of this issue. Please remove

Please submit revisions and let's keep moving forward.

**Comment by pavel-lipcean** [comment]
![help](https://user-images.githubusercontent.com/5729949/34344068-eb9a9e28-e9e9-11e7-97ab-45e1aa9da790.png)

**Comment by pavel-lipcean** [comment]
1) After recent header update, it was very hard for me to find the HELP area. I mean, I used the /#/help/ to get to it - but in the menu - couldn't find it. This is why a side menu (top right, like an icon) would be very helpful to place there the Help button. 

2) Here are some styles that I worked on for the help area, including blockquotes, paragraphs, headings and even the buttons. 

3) Still.. suggesting to use a proper layout at least for the first page in the Help Area, with some icons - to make it more attractive and less boring. 

4) Tested the new links, with the new hover state - works both in this new layout and the old layout.

**Comment by pavel-lipcean** [comment]
![help](https://user-images.githubusercontent.com/5729949/34344105-9396c278-e9ea-11e7-9199-707f3f389003.png)

**Comment by pavel-lipcean** [comment]
Here's a side-menu icon that can be placed on top right, to place there the HELP button, maybe Privacy and all additional items that are needed:

![898](https://user-images.githubusercontent.com/5729949/34344146-fae93bc2-e9ea-11e7-9332-a68b61687305.png)

**Comment by wmbutler** [comment]
I added 2 hours to cover your time on this. Thanks for the feedback. Would you consider styling the Settings Menu in the same way? I like how you have pinned the help indexes to the left side instead of it all floating in the middle.

These would then collapse into the hierarchical right side menu as the screen becomes narrower.

**Comment by pavel-lipcean** [comment]
Here's the help section, placed inside the menu - including on very small screen-size (the far-right one)

![3](https://user-images.githubusercontent.com/5729949/34452469-7f4123a2-ed48-11e7-9578-9a9bd1dc7e88.png)

**Comment by wmbutler** [comment]
Nice.

**Comment by wmbutler** [comment]
Please provide your BTS address for payment @pavel-lipcean

**Comment by wmbutler** [comment]
I can't find that bts account @pavel-lipcean
