### ISSUE TITLE
[.5] Error when install and run the program for Windows

### ISSUE THREAD

**Issue by vista7** [bitshares/bitshares-ui#761]
Hello! there error when install and run program **BitShares.Setup.2.0.171121.exe** and earlier versions. See screenshot:
![default](https://user-images.githubusercontent.com/33452731/33237702-230578f0-d2c6-11e7-89c3-51dc85c08af5.png)

OS - Windows 7x64 SP1.

**Comment by vista7** [comment]
@wmbutler do you need any info about this error from me?

**Comment by wmbutler** [comment]
You are the only one out of thousands of people who have had this issue. I honestly don't know...

**Comment by vista7** [comment]
@wmbutler i can give you a crash dump

**Comment by vista7** [comment]
@wmbutler thats a crash dump file - https://cloud.mail.ru/public/4GoD/PdfYd1Mmf

**Comment by btsfav** [comment]
@vista7 you can attach files here. no need to link to questionable websites.

**Comment by vista7** [comment]
@btsfav here not downloaded the dmp - files, so I provided a link to the cloud storage.

**Comment by leandrovaldez** [comment]
@vista7 can you try to download and reinstall this components:

 Microsoft Visual C++ 2005 SP1 Redistributable Package (x86)
 Microsoft Visual C++ 2005 SP1 Redistributable Package (x64)

the stack shows this:
STACK_TEXT:  
0018fa94 7729f801 c0000374 772d4270 0018fad8 ntdll!RtlReportCriticalFailure+0x57
0018faa4 7729f8e1 00000002 7f81c571 00000000 ntdll!RtlpReportHeapFailure+0x21
0018fad8 7724d9bc 00000008 006a0000 005b1058 ntdll!RtlpLogHeapFailure+0xa1
0018fb08 769798cd 006a0000 00000000 005b1060 ntdll!RtlFreeHeap+0x64
0018fb54 73c2a199 005b1060 771f22d0 73c2a160 msvcrt!free+0xcd
WARNING: Stack unwind information not available. Following frames may be wrong.
0018fb70 73c27ede 00000000 0018fba4 0020001e StdUtils+0xa199
0018fb88 73c315ec 0018fbb0 77209364 73c20000 StdUtils+0x7ede
0018fb90 77209364 73c20000 00000000 00000000 StdUtils+0x115ec
0018fbb0 7722a870 73c315b0 73c20000 00000000 ntdll!LdrpCallInitRoutine+0x14
0018fc38 7720d340 73c20000 0018fc5c 7f81c3d5 ntdll!LdrpUnloadDll+0x375
0018fc7c 76822e93 73c20000 00000000 004cb000 ntdll!LdrUnloadDll+0x4a
0018fc8c 004038b8 73c20000 7688d4c4 004df000 KERNELBASE!FreeLibrary+0x15
004cb000 005c003a 00730055 00720065 005c0073 BitShares_Setup_2_0_171121+0x38b8
004cb004 00730055 00720065 005c0073 043b0410 0x5c003a
004cb008 00720065 005c0073 043b0410 043a0435 0x730055
004cb00c 005c0073 043b0410 043a0435 005c0441 0x720065
004cb010 043b0410 043a0435 005c0441 00650044 0x5c0073
004cb014 043a0435 005c0441 00650044 006b0073 0x43b0410
004cb018 005c0441 00650044 006b0073 006f0074 0x43a0435
004cb01c 00650044 006b0073 006f0074 005c0070 0x5c0441
004cb020 006b0073 006f0074 005c0070 00690042 0x650044
004cb024 006f0074 005c0070 00690042 00530074 0x6b0073
004cb028 005c0070 00690042 00530074 00610068 +0x74
004cb02c 00690042 00530074 00610068 00650072 0x5c0070
004cb030 00530074 00610068 00650072 002e0073 0x690042
004cb034 00610068 00650072 002e0073 00650053 BitShares_Setup_2_0_171121+0x130074
00530074 00000000 00000000 00000000 00000000 0x610068

**Comment by vista7** [comment]
@ @leandrovaldez you mean that the crash is happening because it is not installed 
Microsoft Visual C++ 2005 SP1 Redistributable Package (x86)
Microsoft Visual C++ 2005 SP1 Redistributable Package (x64) ?

ОК, i will try to download and install this package.
