### ISSUE TITLE
[1] 24 Hour column in portfolio not available until viewing a Market page

### ISSUE THREAD

**Issue by mattbeckman** [bitshares/bitshares-ui#762]
Noticed this bug on a refreshed view of My Portfolio. Most stats for 24 hour column are 0.0% until after visiting a Market page. I suspect an extra call needs to be made before the cache is populated.

I'll take a look.

Loading/refreshing My Portfolio directly:

<img width="392" alt="screen shot 2017-11-25 at 11 08 49 pm" src="https://user-images.githubusercontent.com/928380/33237908-e9dc84dc-d235-11e7-8ea8-7393fcc6e38a.png">

After loading any Market view:

<img width="300" alt="screen shot 2017-11-25 at 11 09 18 pm" src="https://user-images.githubusercontent.com/928380/33237911-f464e6a6-d235-11e7-9f4d-4d404fcf1003.png">

**Comment by svk31** [comment]
I need to refactor the market stats fetching slightly and decided to do this while I was at it.
