### ISSUE TITLE
 multisig, by default ui mix account id and public key in permission, and can't use it in approve

### ISSUE THREAD

**Issue by rPman** [bitshares/bitshares-ui#768]
i created two accounts for multisig tests in wallet mode, using bitshares,openledger.org
main wallet - **trisity12**
second wallet - **shad4yp** .
I expected that main account **trisity12** must be limited control via **shad4yp** (need both conformation)

i added to main **trisity12** account on Active permission and Owner permission account **shad4yp** by name and setup weight: threshold=2, shad4yp=1, BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8:1 .
In interface i see **trisity12 used not by name but public key**.

other bug or discomfort of using multiple account
> next, i create here new account gr2rpman, and try to deposit open.btc (openledger) using 2 bitcoin transactions, first transaction come to gr2rpman, but when i reload page (by F5 key), current account switched back to trisity12 and I did not notice it. Second transaction sent to test that multisig account and i cant trade or send money.

under **shad4yp** i created proposed transaction to send open.btc from trisity12 to gr2rpman and approve it

under **trisity12** i am tried to approve this propose but see error:
> Failed to broadcast the transaction:
> 3030001 tx_missing_active_auth: missing required active authority
> 
> UPDATE PROPOSAL
> Fee paying account | trisity12
> Proposal object id | 1.10.5499
> Key approvals to add | BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8
> Fee | 0.06517 BTS
> 

both wallet have public and private keys in Account - Permission
In block explorer i see two updates about trisity12 permissions:

```
root:{} 4 items
 fee:{} 2 items
  account:1.2.469673
   active:{} 4 items
    weight_threshold:2
    account_auths:[] 1 item
     0:[] 2 items
      0:1.2.469682
      1:1
    key_auths:[] 1 item
     0:[] 2 items
      0:BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8
      1:1
    address_auths:[] 0 items
   extensions:{} 0 items
```
as i see, account_auths contains two records with weights and account id 1.2.469682 (it is shad4yp) and BTS7txK5GBDg58JNjuYaZ8YVKh7oNztpsq2JDG7GT9QJHTy6Y1uN8 and BTS5VvDj3Vi6qQuTejkABM5NbA1rmeqan9hJuFbVzKBK5n2fRk3xP - id a public keys of active and owner permission of trisity12

i am tried to approve proposed transaction in latest windows client https://github.com/bitshares/bitshares-ui/releases/tag/2.0.171121 with the same result

console log: https://pastebin.com/2dLqP5aK (i am cut signatures and digest fields, just in case)

How i can approve this transaction or give money back?

**Comment by svk31** [comment]
Because trisity12 has authority threshold 2 and the pub key of that account has weight 1, it cannot by itself sign anything requiring an active key signature.

To use a multisig setup like you want, you need three accounts. The active auths for trisity12 should contain `shad4yp` and an additional account, `shad5yp` for example. You should then propose transactions using one of shad4yp and shad5yp.
