### ISSUE TITLE
[7] Integrate new website

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#769]
- [ ] Code Review
- [ ] Coordination Efforts

**Comment by xeroc** [comment]
What 'website' is this all about?

**Comment by wmbutler** [comment]
@xeroc Richg and the marketing team have put together a new website for Bitshares that is more current than the existing one. We have made an effort to offload this effort to that team by separating the wallet to wallet.bitshares.org.

I have asked richg to comment here as this progresses.

**Comment by wmbutler** [comment]
This really needs to be claimed and @xeroc if you can resolve any issues that bitshares.fdn has with content, it would be much appreciated.

**Comment by wmbutler** [comment]
@svk31 is this getting pushed again?

**Comment by nbcks** [comment]
What exactly is this? What do you mean by 'integrate'?

**Comment by btsfav** [comment]
I think the reserve fund should only pay for this work (for bitshares.org) if the domain is held and maintained by a neutral non-profit organisation such as the foundation.

**Comment by wmbutler** [comment]
Meanwhile we have a site that is 2 year out of date with no forward motion.

**Comment by nbcks** [comment]
Is this just an issue to create/update the old website (www.bitshares.org)? Has the new website created by Richg been made yet? What's its URL?

**Comment by wmbutler** [comment]
The site has been created by Richg but there are politics between the domain being owned by Stan Larimer and the Foundation not feeling comfortable with this. I think that BF should work with RichG to put the site up under bitshares.org and edit the contents to include whatever legal verbiage we need but I honestly don't think it will happen.

**Comment by nbcks** [comment]
I see. Is Stan Larimer not going to give up ownership to the BF? I assumed he was stepping down after the Arisebank fiasco.

**Comment by wmbutler** [comment]
No. But there is no "Stepping Down" There is no place to step down from.

**Comment by nbcks** [comment]
Okay, disassociating himself with bitshares/not playing a part in it.

**Comment by wmbutler** [comment]
@nbcks I doubt he will do that. His son invented it and he is also a founder of the HERO MPA.

**Comment by btsfav** [comment]
> Meanwhile we have a site that is 2 year out of date with no forward motion.

cryptonomex has an outdated website, not bitshares.

**Comment by nbcks** [comment]
Why don't we setup an alternative domain (registered to the BF) and put the new website on that?

**Comment by nbcks** [comment]
We can always integrate/re-register bitshares.org at a later date. Right now the website looks very bad in my opinion and is surely turning new users away. Replacing it should be our top priority.

**Comment by wmbutler** [comment]
The website at bitshares.org is outdated. This is the site that outsiders view as what represents the BTS blockchain.

**Comment by gibbsfromncis** [comment]
@wmbutler if @svk31 is busy maybe I can help you with that?

**Comment by sschiessl-bcp** [comment]
@wmbutler 

I assume with the new owner of bitshares.org and their own efforts for a new landing page this can be closed?
