### ISSUE TITLE
[5][mattbeckman] Match table headers and fonts

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#771]
These Advanced Features need to be brought up to date with the new, more modern UI present in the Dashboard and Voting. This includes:

- proper styles
- proper highlighting on hover and select
- proper / consistent margin at the top of the page
- proper font style and size

Screens included in this issue for payment

- [ ] Issued Assets --> Update Asset
- [ ] Issus Asset / Burn Asset / Update Asset buttons (change to blue style button)

![screen shot 2017-11-27 at 10 38 27 pm](https://user-images.githubusercontent.com/1254810/33302697-bd7a7892-d3c3-11e7-879d-9e8ebb539a88.png)

- [ ] Permissions
- [ ] Whitelist
- [ ] Vesting Balances
- [ ] Signed messages

I've included a 5-hour estimate on this. Be sure to carefully perform all operations in order to get paid. Would love it if someone would claim it and have it ready prior tot he 12/1 release.

**Comment by mattbeckman** [comment]
I'll handle this one and attempt to get it done for 12/1.
