### ISSUE TITLE
[20][oxarbitrage] UDF Wrapper for Tradingview

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#773]
This is required for execution of #361

**Comment by wmbutler** [comment]
@oxarbitrage @calvinfroedge update on where we are with this?

**Comment by oxarbitrage** [comment]
I have everything i need from Calvin now, resuming the work in the wrapper, i'll update you here in 2 days.

**Comment by oxarbitrage** [comment]
first version with demo: https://github.com/oxarbitrage/udf-bitshares-wrapper
have a few issues in the chart data i need to go over with @svk31

**Comment by wmbutler** [comment]
Closing and will pay you for your time. Please post your bts address.

**Comment by wmbutler** [comment]
Please provide your BTS address for payment @oxarbitrage

**Comment by oxarbitrage** [comment]
thanks bill, payment received. the wrapper had been working good for some time now in the explorer but if it need adjustments when you guys start the integration to the wallet ill be here to do so.
