### ISSUE TITLE
[.25] No error message appears when sending without a memo key

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares-ui#777]
If a memo is given but no memo key is stored, nothing happens after the click.
On inspecting the console there was a message that the memo key is missing.

**Comment by wmbutler** [comment]
Please post a screencast. I don't understand the nature of the problem based on your description.

**Comment by svk31** [comment]
I understand it, I thought I'd added a notification for this but guess not. I'll see if I can fix it.

**Comment by sschiessl-bcp** [comment]
Sorry, my initial message was maybe a little too short.

This is how you can reproduce the error:
 - create a new local wallet
 - restore only the active key from an account
 - try sending any amount to any account with a given memo message
 - clicking the Send button will to nothing, no feedback, but the console will say something like: No memo key set
 - after also importing the memo private key everything works

Expected behavior: A popup saying "The memo key of this accoutn is missing, please import" or similar, if the memo key is missing. What I haven't tried is sending something without a memo message. Expectation would be that this still works even without a memo key.

I'll be happy to look into this on monday, if you haven't yet Sigve. I found that bug because I like to operate with a local wallet that does not have the owner key installed, not sure how often this happens for others, Im assuming not that often.

Best regards,
 Stefan

**Comment by abitmore** [comment]
Also caused https://github.com/bitshares/bitshares-ui/issues/680.
