### ISSUE TITLE
Remove OpenLedger support link from https://wallet.bitshares.org/#/deposit-withdraw/ 

### ISSUE THREAD

**Issue by OLPM** [bitshares/bitshares-ui#779]
Please, Remove information from this page (https://wallet.bitshares.org/#/deposit-withdraw/ ) about OpenLedger support. Users do not understand that this link is related to transfer service ONLY. All frontend issues from your site does to OpenLedger support and this situation gives a lot of  difficulties to OpenLedger support.

If it is necessary - you can add note like OpenLedger is responsible for transfer servise ONLY and provide link to web-site openledger.io. But please do not leave note like it now with link to OpenLedger support. 

<img width="858" alt="screen shot 2017-12-01 at 3 17 10 pm" src="https://user-images.githubusercontent.com/34161791/33483724-407fbaa6-d6b0-11e7-9675-68cba9f1325d.png">

**Comment by wmbutler** [comment]
Would you like for us to remove you as the default gateway provider? This support link is only displayed when your dropdown is selected.

**Comment by btsfav** [comment]
removing support link will give US in telegram / discord all the issues. 

so it's either staying or the gateway needs to be removed in my opinion.

**Comment by OLPM** [comment]
Or change text to: 
"For DEPOSIT AND WITHDRAWAL issues using "OpenLedger TRANSFER SERVICE", please contact Openledger at: 
https://openledger.io

**Comment by wmbutler** [comment]
@OLPM you know you can submit a PR right?

**Comment by wmbutler** [comment]
Closing this since OL can submit a PR.
