### ISSUE TITLE
Issue with login to cloud account with old user-defined password with strange characters.

### ISSUE THREAD

**Issue by matejbajzelj** [bitshares/bitshares-ui#780]
Greetings

I would like to report an issue with "cloud account login + old user-defined password + with special characters @ or !"...

I already posted an issue here. https://bitsharestalk.org/index.php/topic,25300.0.html (user Macario post), but was no reply.
I know how to login to online/local wallet accounts. So there is not a problem with account type login in settings.

I have the correct password, I have correct username, I used that account in the past (on multiple computers). But now I can't use it anymore.
I keep getting "invalid password". The password is saved in multiple password managers (no white space..password is trimmed for white space so that is not an issue).
I use the website for login https://wallet.bitshares.org/#/ .
Have also tried light client and issue is the same.

I have discovered that system for creating and login was changed in the last few months (That is how long I haven't used my account). 
Users can no longer pick their own passwords. So I think since most people can use old passwords with no problem, that there might be a specific character,
that cause an exception and in such case, the default response is "invalid password".

My password contains "@" and "!", would that be a problem?

I can't publish my login info publicly, but I am willing to provide such information to a developer for debugging purposes to discover the real reason why login doesn't work. 

Best regards,
Matej

**Comment by svk31** [comment]
Special characters can be used just fine so I doubt that's the issue. For example, I just set a new active key for the account `svk-laptop` on the testnet using the password `qwdlqkwdjqlw*'@ée&ée!`. Logging in with that account name and password works fine, feel free to try it yourself.

When the account creation was modified, the only thing that changed was how the initial password was defined, nothing has changed in terms of how the private keys are generated from your account name plus password.

If you know when you last successfully unlocked your account I suppose you can try downloading an old light client and see if that works, although I don't see why it should.

**Comment by Worldchamp** [comment]
I'm having the same exact issue.

**Comment by wmbutler** [comment]
Have you tried switching back to local wallet mode?

![cloud](https://user-images.githubusercontent.com/1254810/33851248-020ae6e6-de7c-11e7-8593-fb1c0fc9115b.gif)

**Comment by Worldchamp** [comment]
Yes, I have tried that. I am still having the same issue.

**Comment by matejbajzelj** [comment]
Is there an archive of older already build clients that I can test and try login? I know it worked in the past, but don't know which version it was. It was some time back in july - august.

**Comment by svk31** [comment]
Oldest client releases are here: https://github.com/bitshares/bitshares-core/releases?after=test-2.0.171023

The newer ones you'll find here: https://github.com/bitshares/bitshares-ui/releases
