### ISSUE TITLE
[2][startail] Add / Remove Contact

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#781]
We need more places to Add / Remove Contact. If the column has a plus sign, clicking it will add it to your contacts and toggle the icon to the contact icon. Clicking again would perform the reverse task. This issue is proposing that this is possible from:

## Account Explorer
Until the explorer uses the new table look and feel, I'm proposing it look like this. Note that I also proposed some abbreviations to the table header values.

![screen shot 2017-12-02 at 1 31 50 pm](https://user-images.githubusercontent.com/1254810/33519107-9492ef18-d765-11e7-85b1-d9db9ed33d3b.png)

## Account Listing
I think the contact column would look better between favorite(star) and the account name for this view. I didn't mock it up, but I think you get the picture here. The one consideration here is that clicking on the contact will make it disappear from the list. This could be a good argument for a confirmation of some sort.

![screen shot 2017-12-02 at 1 36 38 pm](https://user-images.githubusercontent.com/1254810/33519143-5bcf4518-d766-11e7-85d1-f14cd0e4c45c.png)

**Comment by wmbutler** [comment]
Potential conflicts with #167 on merge since it touches the same file.

**Comment by startailcoon** [comment]
![bitshares_issue781](https://user-images.githubusercontent.com/12114550/33575962-a039b146-d93e-11e7-9f7f-1e35957164a6.gif)
