### ISSUE TITLE
[.1] Too many false "gateway is down" alerts

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#783]
I get The OpenLedger Gateway is down or not responding a lot, although it's up and fully usable via Openledger.io - same node/s. 

Please check

**Comment by wmbutler** [comment]
I think this is related to the time comparison as blocks come in. I think we are displaying the message if we are 5 seconds behind. Should we extend this to 10 seconds to hide false positives?

**Comment by btsfav** [comment]
or 15 seconds. you need time to select the pair and enter details anyways. should be more than enough to alert I guess

**Comment by wmbutler** [comment]
#830

**Comment by svk31** [comment]
I've never seen this error myself but it is most likely related to the Openledger API.
