### ISSUE TITLE
[.5] Send Modal Positioning tweaks

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#796]
- [ ] Alignment on +/contact icon needs to come left a few px
- [ ] Noticeable vertical shift when adding a to address

![shift](https://user-images.githubusercontent.com/1254810/33633482-9e3e9a26-d9d6-11e7-8763-47c14320e395.gif)

**Comment by dot5enko** [comment]
i claim this issue

**Comment by dot5enko** [comment]
fixed 
![modal](https://user-images.githubusercontent.com/5626922/33785754-1ee973ae-dc6f-11e7-8f79-ce83befe8552.gif)
