### ISSUE TITLE
Typeahead to include user controlled accounts and contacts

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#797]
When entering a **To** address, it would be helpful to present a typeahead that includes controlled accounts and contacts. This would help users avoid sending funds to unknown accounts.

![contact](https://user-images.githubusercontent.com/1254810/33633755-85ca5f6a-d9d7-11e7-8c2b-81e1e4f27242.gif)

**Comment by dot5enko** [comment]
@wmbutler do we have such typeahead feature somewhere on the site as an example?

**Comment by GildedHonour** [comment]
Is this being worked on?

**Comment by wmbutler** [comment]
#828 Duplicate
