### ISSUE TITLE
[.1] Update links on bitshares.org

### ISSUE THREAD

**Issue by bitcoiners** [bitshares/bitshares-ui#798]
Please update bitshares.org website links to exchange. It still points to
https://bitshares.org/wallet
 instead of 
https://wallet.bitshares.org/

**Comment by wmbutler** [comment]
@xeroc

**Comment by wmbutler** [comment]
@svk and @xeroc please update this immediately. This makes the entire organization look incompetent.

![wallet](https://user-images.githubusercontent.com/1254810/33753017-c5a3458c-dbaa-11e7-847c-2b49e1f98b1f.gif)

**Comment by svk31** [comment]
Fixed here: https://github.com/bitshares/bitshares.github.io/commit/2130bcaa75c8443927fe78741de1961350bc8a35
