### ISSUE TITLE
[.1][dot5enko] Cancel button doesn't work when creating assets

### ISSUE THREAD

**Issue by mattbeckman** [bitshares/bitshares-ui#799]
It appears the cancel button doesn't do anything when creating a new asset. Moving away from the asset creation page therefore requires switching to some other section of the app via the top or dropdown menus.
<img width="986" alt="screen shot 2017-12-05 at 2 45 50 pm" src="https://user-images.githubusercontent.com/928380/33634997-1af73dfe-d9cb-11e7-90e1-7259bbf10435.png">

**Comment by wmbutler** [comment]
What should the cancel button do in your opinion? Should it perform the action of -1 in the broswer to go to the previous page? Should it reset form fields?

**Comment by startailcoon** [comment]
We could have one button to clear and one to go back

**Comment by mattbeckman** [comment]
IMO "Cancel" when creating something should return you to the view from whence you came.

I would be hesitant to add a 3rd button for UX simplicity reasons.

**Comment by wmbutler** [comment]
I just tested this.

- Cancel resets the form. I'd suggest renaming it to Reset and closing this issue.

Both the light client and the web browser have back arrows as well as a menu options.

**Comment by dot5enko** [comment]
i claim this
