### ISSUE TITLE
[1][dot5enko] Create Account in new UI missing

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#800]
see topic. 

perhaps this function could be added to an existing page? Not sure if we need an extra top entry in the drop-down

**Comment by wmbutler** [comment]
Agreed. Adding this to 171215. Possibly need to hotfix this.

**Comment by btsfav** [comment]
together with https://github.com/bitshares/bitshares-ui/issues/803

**Comment by wmbutler** [comment]
Let's do this:

- [ ] Add button "Create Account"
- [ ] Place it to the right of button "Show Hidden Accounts"
- [ ] Make both buttons "Bitshares Blue"

![screen shot 2017-12-07 at 1 58 43 am](https://user-images.githubusercontent.com/1254810/33704468-302f81b8-daf2-11e7-8f0b-1d7ed2413faa.png)

**Comment by dot5enko** [comment]
i claim this

**Comment by dot5enko** [comment]
@wmbutler i've made a link from a shown place to "create account" page. but it seems that page not works when you're logged in. You can check it now by going to https://wallet.bitshares.org/#/create-account/password. when all rules are accepted register button is still disabled. and when no user is logged everything is fine. so i need some extra time to get it work

**Comment by wmbutler** [comment]
@svk31 only Local Wallet type accounts can create accounts, right?

**Comment by wmbutler** [comment]
@dot5enko I think the Create Account button is only available for local wallet users and it creates an additional name under the the local wallet model. Don't confuse that with the Cloud Wallet account creation.

Here is what the new account form looks like under these circumstances:

![screen shot 2017-12-07 at 10 30 45 pm](https://user-images.githubusercontent.com/1254810/33751124-650617f6-db9e-11e7-9856-744b2242c143.png)

**Comment by btsfav** [comment]
any account type should be able to create accounts though. needs to be LTM

**Comment by wmbutler** [comment]
@btsfav but currently only Local Wallet accounts can create accounts. We lost this functionality. The goal is to regain this loss.

**Comment by wmbutler** [comment]
@dot5enko can you pls submit this tonight? I think it's an important one to have in place and it's a pretty easy win.

**Comment by dot5enko** [comment]
@wmbutler  yup. working on it now

**Comment by dot5enko** [comment]
done. button is only visible if user has local wallet.

**Comment by svk31** [comment]
Bumped this down to 1hr since 1.5 seems excessive.
