### ISSUE TITLE
[.5][dot5enko] Unable to specify bitCNY as Fee type when try to sell all BTS

### ISSUE THREAD

**Issue by oflyhigh** [bitshares/bitshares-ui#803]
# Steps to reproduce

* Login and open market https://wallet.bitshares.org/#/market/BTS_CNY
* Try to place an order to Sell all BTS asset, select ***bitCNY as Fee type***
![image](https://user-images.githubusercontent.com/25529332/33666158-1ef44b0e-dad4-11e7-8227-41bad4210a78.png)
* Press SELL button, ***Please confirm the transaction*** dialog appeared
![image](https://user-images.githubusercontent.com/25529332/33666261-6713cb1c-dad4-11e7-8e03-57ffc572b569.png)

# What we expect
The fee type was kept as bitCNY.

# The Result
The fee type was changed from bitCNY to BTS!

**Comment by dot5enko** [comment]
i claim this

**Comment by svk31** [comment]
Unable to reproduce this bug, the fee gets kept just fine for me. What was your bitCNY balance at the time of attempting to do this?

Oh and by the way, you should always pay fees in BTS if you have BTS, it's cheaper...

**Comment by svk31** [comment]
Ok nevermind I see what's happening, the fee isn't getting subtracted from your total when it's in a non-core asset.

**Comment by svk31** [comment]
Just for the record: you'd be better off paying that fee in BTS since it's cheaper.
