### ISSUE TITLE
Removing a contact where I hold the keys

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#805]
Should a user be able to "unfollow" / "remove contact" for accounts where they hold the keys? This could create a situation where users lose their active accounts.

For example, if I hold the keys to a secondary account, if I remove them as a contact, they get removed from my Accounts area. Just seems strange that a user would be required to follow an account that they own.

This can be a question for now.

**Comment by svk31** [comment]
Agreed that this shouldn't be possible, unintended effect of the contacts change.

**Comment by startailcoon** [comment]
Fixed
