### ISSUE TITLE
[.25] Theme Midnight (OL Dark) needs some care

### ISSUE THREAD

**Issue by btsfav** [bitshares/bitshares-ui#808]
Most pages are not real midnight bg, but borrow from the current "dark theme".

this needs some work please

Good:

![](https://i.imgur.com/yLlfmgJ.png)

Bad Deposit/WD (of many):

![](https://i.imgur.com/ZE23YWu.png)

**Comment by wmbutler** [comment]
This is not a problem on Chrome for Mac. Please state your browser and OS.

**Comment by btsfav** [comment]
Windows 7, light client

**Comment by svk31** [comment]
Is the right side gap the issue? If so I already fixed it. Deposit/Withdraw are both active because they have the same path for now, will change once the modals are ready.

**Comment by svk31** [comment]
Closing since I have no idea what the issue is.

**Comment by btsfav** [comment]
@svk31 the different shades of black is the issue
