### ISSUE TITLE
plz cant someone help I sent my bitcoin by mistake to another address 

### ISSUE THREAD

**Issue by Vanterpool7** [bitshares/bitshares-ui#809]
Im contact open ledger support to try to fix my problem and after a lot email they respond to me and tell me the bitshares is a different platform , the  bitshares support support to fix my problem because the money I sent. , I sent to a bitshares account no to open ledger account plz someone help from bitshares please if you cant contac me by at esv-ministry@hotmail.com

**Comment by wmbutler** [comment]
https://t.me/BitSharesDEX

**Comment by Vanterpool7** [comment]
hi sir IM spanish And I do not understand what you just say i see that you  put this https://t.me/BitSharesDEX , Im click but nothing happen

**Comment by wmbutler** [comment]
It's a telegram channel. We don't offer support here. This is a development site. You can also try discord:

https://discord.gg/GsjQfAJ

**Comment by Vanterpool7** [comment]
sir sorry but the page you just give me is a game store I don't think they related to bitshares .org

________________________________

**Comment by landry314** [comment]
@Vanterpool7, telegrama debe estar instalado en el dispositivo que está utilizando ahora para que funcione este enlace. (thanks google translate)

You must have telegram installed to use this link.

Github is a software development website and not a support site. You are in the wrong place. Bill is saying you need to ask your question on the bitshares telegram group... or on discord.
