### ISSUE TITLE
[.5][dot5enko] Remove unit of currency from labels in My Portfolio

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#812]
Unit of currency is implied based on the settings chosen in general settings. Displaying it is redundant and throws off a clean view.

- [ ] Price
- [ ] Value
- [ ] Total

![screen shot 2017-12-06 at 4 29 34 pm](https://user-images.githubusercontent.com/1254810/33688900-e32b3a0a-daa2-11e7-8855-c8953578408c.png)

**Comment by dot5enko** [comment]
i claim this

**Comment by dot5enko** [comment]
@wmbutler did it for all tabs in dashboard, not only portfolio. is it ok ?

**Comment by landry314** [comment]
It still helps to make it clearer. Settings are buried. Taking this away will confuse people.

**Comment by svk31** [comment]
I don't think this is a good idea either; will just cause confusion.

**Comment by wmbutler** [comment]
Units are present on every single page.

![screen shot 2017-12-14 at 4 55 30 pm](https://user-images.githubusercontent.com/1254810/34018480-9f669514-e0ef-11e7-9f94-2d33e9b30b81.png)

**Comment by startailcoon** [comment]
Little late now, but I think we could save the asset name in the total column at the bottom, but write it out as `Total bitUSD` for example. Will give the user at least two referens points. One top and one bottom.

**Comment by wmbutler** [comment]
I'd like to remove units from everywhere except the top right. It's silly to repeat this everywhere.

**Comment by wmbutler** [comment]
- [ ] Let's replace every occurrence of (bitUSD) with `*`
- [ ] Then place a * to the right of the chosen display in the account dropdown header: `1,000 bitUSD*`

**Comment by dot5enko** [comment]
@svk31, @landry314 what did you think about message above?
