### ISSUE TITLE
[.25][dot5enko] Remove border from tables and add a row hover state

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#813]
The account table is already displayed this way, but it would be nice if all tables adopted this look:

- [ ] Remove borders
- [ ] Add hover state to row

![screen shot 2017-12-06 at 5 09 33 pm](https://user-images.githubusercontent.com/1254810/33690275-78049248-daa8-11e7-97d8-fb72374f4234.png)

**Comment by dot5enko** [comment]
i claim this

**Comment by wmbutler** [comment]
Awesome. User the hover state on accounts/contacts for the hover color.

**Comment by dot5enko** [comment]
got it
