### ISSUE TITLE
[.5][bigspider] Fine Tune UI

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#819]
I've had some feedback on this top menu that I think is good and requires a very small change. If you claim this, please submit a licecap once the work is complete for a quick check before the PR.

- [ ] 25% smaller icon size (on top header)
- [ ] 25% larger font size (on top header)
- [ ] icons should hold the same color on hover/non-hover as the text
- [ ] Submenu should have a blue square hover-state the same way the top menu has a gray square hover state

![fine_tune](https://user-images.githubusercontent.com/1254810/33703390-812e1570-daed-11e7-9443-68c4075f71fa.gif)

**Comment by bigspider** [comment]
Can I claim this?

**Comment by bigspider** [comment]
Here is my current result:

![bitshares-819](https://user-images.githubusercontent.com/6681844/33743733-f867b9e4-dba5-11e7-84df-efb65d5f4d0b.gif)

I also added the same easing animation for the text in the submenu (earlier it was instantaneous).

Note: the size of the icons is hardcoded in the Icon component, which seems quite a bad idea to me and it should probably be refactored. I didn't do it as there are many instances of Icon, so it's a bigger change.

I'll submit the PR if you're happy with the result.

**Comment by svk31** [comment]
The header font size seems a bit too large for my taste, but otherwise looks good.

**Comment by bigspider** [comment]
Thank you!

Bitshare address for future reference: "spider-1"
