### ISSUE TITLE
[2][dot5enko] Can't paste values into input fields of exchange with Firefox 57

### ISSUE THREAD

**Issue by MarkoPaasila** [bitshares/bitshares-ui#823]
What's working:

- paste with right-click and "paste" in any field with Firefox or Chromium
- paste in search fields with CTRL+V with firefox and chromium
- paste with CTRL+V in exchange input fields with Chromium

What's not working:
- paste with CTRL+V into exchange input field with Firefox 57 on Linux. (Archlinux)

**Comment by wmbutler** [comment]
Please post a licecap.

**Comment by svk31** [comment]
I can reproduce it, must be related to the ExchangeInput component.

**Comment by diogo-gomes** [comment]
It's been reported on discord help that pasting with right click doesn't work on desktop client too.

I confirm that paste password with right click doen't work. Can you remove "low priority" because it's really bad for new users?

**Comment by calvinfroedge** [comment]
`Ctrl+V` needs to be allowed on the component...this is a quick fix, I can push later today

**Comment by btsfav** [comment]
@diogo-gomes on mac

**Comment by diogo-gomes** [comment]
> on mac

No, on Linux (I edited my comment)

**Comment by dot5enko** [comment]
i claim this issue. 
Fixed problems with exchange inputs.
@diogogomes what  about 

> paste password with right click doesn't work on Linux.

can you give more details ?

**Comment by diogogomes** [comment]
Steps:
1. Open a desktop client for Linux (deb package)
2. Copy password from somewhere.
3. Right-click shows a menu with the paste option.

Step 3 doesn't work. Many users have the habit to copy/paste with mouse and not with keyboard shortcuts and this issue is a barrier for them.

**Comment by dot5enko** [comment]
@diogogomes it's not an issue actually.  Electron, which is used to create a desktop app disable context menus. 
So, in order to make context menus we should use some external module for that and this is beyond current issue. I guess you can create another, but is it really a problem?

**Comment by diogogomes** [comment]
@dot5enko, I know one by sindresorhus [electron-context-menu](https://github.com/sindresorhus/electron-context-menu) but I never tried it.

For me, it's not a problem, I get this from users on BitShares support (Discord).

What's your opinion @wmbutler? Another issue for the context menu?

**Comment by dot5enko** [comment]
@diogogomes i'm not sure if its possible to paste any data from os buffer into input element within js,
therefore that task requires some research and doesn't fit current one.

**Comment by wmbutler** [comment]
This issue is about Firefox only. Open a different issue for the light client.

**Comment by dot5enko** [comment]
@wmbutler i claimed and fixed this issue, you misplaced asignee :)

**Comment by wmbutler** [comment]
Oops, sorry.
