### ISSUE TITLE
Bitshares app showed USDT address despite OMNI gateway turned off at openledger!

### ISSUE THREAD

**Issue by SatoshiEC** [bitshares/bitshares-ui#825]
On bitshares app (bitshares.171205 ) went to deposits and set to use openledger gateway, clicked on USDT to see deposit address.. It showed me this one:

16rqdysHyXuRA3y7zUVchMZRR36WspJCJE

After I transfered some tether to that address, checked again the deposit page and this message appeared “Gateway temporarily unavailable for this coin” What happens in this type of scenario? Logically I would expect my tether to arrivie as soon as the gateway is restored for this coin. But if it wont be restored, as one earlier post suggests, then what? Why the bitshares app gave me an address in the first place?

https://blog.openledger.info/2017/11/13/due-the-omni-issues-gateway-is-turned-off/

what shoud I do? Do I have access to the private key of that particular address?? Please help!

**Comment by wmbutler** [comment]
This is not a support channel. 

https://wallet.bitshares.org/#/help/gateways/openledger

**Comment by SatoshiEC** [comment]
Yeah but this is what openledger says: 

> _Hi Satoshiecuador,
> We are not able to help you because it is not our app and bitshares.org is not our site. 
> We are completely different companies with different development teams. OpenLeger is a separate independent platform, and in case of any bugs our support is able to help only if you are working through our web interface. Welcome to https://openledger.io/. Your login and password will remain the same. We are not able to help you if you have troubles with bitshares web or wallet interface.
> https://github.com/bitshares/bitshares-ui/issues_
 
So.. what do you recommend? 2k usd are at risk for some issue that is not my problem but an openledger or Bitshares gui issue and I find help nowhere!!
