### ISSUE TITLE
[5][dot5enko] Clearly identify known accounts when sending

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#828]
As talked about before, we should set a default setting to disallow transferring funds to unknown/none-followed accounts.

This setting should be set as on by default, while the user can disable it either in the settings or on the component that is affected by it.

**Comment by wmbutler** [comment]
It's important that users have confidence without restricting their actions. I'd propose this:

- [ ] Allow for a typeahead in the To input field for all contacts (including accounts the user owns in the local wallet). The typeahead will show eligible contacts eliminating potential problems.
- [ ] If the user has entered a contact's name, let's turn the "BASIC MEMBER #00000" and the contact icon green.
- [ ] If a user stops typing and it's an unknown user, that's very obvious and there are no security issues.
- [ ] If the user enters a valid account who is not in the contact list, it should appear as white as it does currently
- [ ] If the user clicks the plus sign, it should turn it green as described above.
- [ ] Change the question mark cursor to a finger pointer.

![contact](https://user-images.githubusercontent.com/1254810/33751459-a425ecfc-dba0-11e7-8055-3bbac8ef09eb.gif)

**Comment by dot5enko** [comment]
@wmbutler there are issues #797 and #796 which cover some of aspects you've listed above

**Comment by svk31** [comment]
Right, and we don't currently have a typeahead component so it would have to be built as part of either this issue or #797

**Comment by svk31** [comment]
For the record I don't think it's a good idea to limit transfers to only known accounts; it's too restrictive. The typeahead is a better solution.

**Comment by startailcoon** [comment]
I agree that typeahead is a good way to go. My initial thought was to make sure that the transactions was made safer for users.

**Comment by wmbutler** [comment]
Typeahead has been built. Whoever claims this issue can follow the checkboxes up there and build this.

**Comment by dot5enko** [comment]
i can claim this

**Comment by wmbutler** [comment]
Closed #797 and consolidated to this issue.

**Comment by wmbutler** [comment]
Progress?

**Comment by dot5enko** [comment]
@wmbutler everything ok, tweaking typeahead component to meet all requirements for this task. would be done in current milestone

**Comment by dot5enko** [comment]
@wmbutler check out current result. Still need to fix some typeahead styling: no outline, height of input should be same as other inputs. But i saw some improvements in @startailcoon changes: https://github.com/bitshares/bitshares-ui/issues/557#issuecomment-355058301 ![send](https://user-images.githubusercontent.com/5626922/34536350-7e4cb0dc-f0cd-11e7-9616-617ddf0e8987.gif)

**Comment by wmbutler** [comment]
I couldn't verify these two from your screens.

- [ ] Change the question mark cursor to a finger pointer.
- [ ] Tweak vertical alignment of contact icon relative to member # as well.

**Comment by dot5enko** [comment]
@wmbutler, cursor now is a pointer, i try to record it with licecap. yup, vertical alignment really needs few pixels of tweaking

**Comment by dot5enko** [comment]
Which one is correct ?
![image](https://user-images.githubusercontent.com/5626922/34605139-15296b26-f213-11e7-80f4-0ea253c634ae.png) 
![image](https://user-images.githubusercontent.com/5626922/34605156-280d8fa6-f213-11e7-93de-0fcd8349f220.png)
![image](https://user-images.githubusercontent.com/5626922/34605178-4821ceb0-f213-11e7-8678-a7585e7d61ee.png)

**Comment by dot5enko** [comment]
@wmbutler  i've seen that if i'm not unlocked my account wallet send modal do nothing when i click on send button. Seems it should say something or request for wallet unlock
