### ISSUE TITLE
[1][dot5enco] Setting -> General -> Login Mode gets changed if use navigates to a specified endpoint

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#831]
I think I may have discovered the source of confusion for logging in for users who previously had Local Wallet Accounts. it surprised me tonight while testing something else entirely.

If a user attempts to hit this endpoint:

https://wallet.bitshares.org/#/create-account/password

It modifies their Settings -> General -> Login Mode to Cloud Wallet. This then asks for a username and password for subsequent login attempts.

It might be a better idea to only switch to a Cloud Wallet Login if we fail to detect the local database in the browser.

![local_cloud](https://user-images.githubusercontent.com/1254810/33752199-f6cbd5c0-dba5-11e7-9718-75eb1370173f.gif)

**Comment by dot5enko** [comment]
i claim this

**Comment by svk31** [comment]
This was added specifically to prevent issues users were having with being in local wallet mode when what they had was a cloud wallet mode. One improvement we could make is to only switch the mode to cloud wallet once the user succesfully creates a new cloud wallet account.

**Comment by wmbutler** [comment]
@dot5enko don't work on this until this discussion has come to a clear decision.

@svk31 I see what you are saying here, but in my case, I have a local wallet. Is there any case where we would want to effectively hide the local wallet from a user that has one already? I feel like we should detect this when loading that endpoint and disallow the activity, but I also like your idea of only changing it after the user has created the account.

Maybe a message like:

"You are attempting to create a cloud wallet but we have detected a local wallet. Are you sure you wish to proceed?"

**Comment by dot5enko** [comment]
@wmbutler, ok. haven't started yed

**Comment by svk31** [comment]
No I suppose it makes sense to check if the user already has a wallet and not switch if that's the case. There's an easy way to check that: `!!WalletDb.getWallet()`

**Comment by dot5enko** [comment]
@svk31 , @wmbutler  so what we do: 

- change wallet to cloud if the user register new account
- do not change type to cloud if user just visiting create-account page

am i right?

**Comment by dot5enko** [comment]
@wmbutler, @svk31  what about making login popup to have two  tabs: local, which shows only if the local wallet was detected and cloud which shows in any case?

**Comment by wmbutler** [comment]
@dot5enko I think it's a bad idea to allow the option at the registration screen. Let's only switch to cloud wallet if the user completes the registration process.

**Comment by dot5enko** [comment]
@wmbutler done. can you check if its what you're expected?
