### ISSUE TITLE
[.25] Add bitSILVER and bitGOLD to default Margin Positions

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#833]
![screen shot 2017-12-08 at 12 12 15 am](https://user-images.githubusercontent.com/1254810/33753365-79bc1df4-dbac-11e7-9f4b-e5785b87a47e.png)

**Comment by dot5enko** [comment]
i claim this

**Comment by dot5enko** [comment]
@wmbutler  i've added GOLD and SILVER but it says:
![image](https://user-images.githubusercontent.com/5626922/33781638-1ab13e2c-dc5e-11e7-8a4b-f8f79850b40a.png) when i try to adjust it. Also there is no margin positions on https://wallet.bitshares.org/#/asset/GOLD and SILVER page as well, guess it's not possible to set margin on these assets

**Comment by svk31** [comment]
It's OK, that's because those asset had blackswan events that disabled them. We want to add them now because they're being re-enabled following the recent hardfork.

**Comment by dot5enko** [comment]
ok. created pr

**Comment by startailcoon** [comment]
There are more assets than gold and silver that are Smart Coins.

The recent list of revival are:
- [BTWTY](http://cryptofresh.com/a/BTWTY_BTS)
- [CASH.BTC](http://cryptofresh.com/a/CASH.BTC)
- [CASH.USD](http://cryptofresh.com/a/CASH.USD)
- [GOLD](http://cryptofresh.com/a/GOLD)
- [GOLOS](http://cryptofresh.com/a/GOLOS)
- [GRIDCOIN](http://cryptofresh.com/a/GRIDCOIN)
- [HKD](http://cryptofresh.com/a/HKD)
- [KRW](http://cryptofresh.com/a/KRW)
- [LATINUM.DJIA](http://cryptofresh.com/a/LATINUM.DJIA_USD)
- [NZD](http://cryptofresh.com/a/NZD)
- [RUB](http://cryptofresh.com/a/RUB)
- [SEK](http://cryptofresh.com/a/SEK)
- [SGD](http://cryptofresh.com/a/SGD)
- [SILVER](http://cryptofresh.com/a/SILVER)
- [TCNY](http://cryptofresh.com/a/TCNY)
- [TUSD](http://cryptofresh.com/a/TUSD)
