### ISSUE TITLE
Maybe move HELP to EXPLORER page

### ISSUE THREAD

**Issue by jonnybitcoin** [bitshares/bitshares-ui#84]
Maybe move HELP to EXPLORER page?

Also could put WORKERS on the EXPLORER page as well as it has witnesses and committee members already

**Comment by fractalnode** [comment]
and move EXPLORER next to SETTINGS. 
Dropdown only for accounts list

**Comment by svk31** [comment]
Help and Explorer links can now be found in a dropdown together with Settings.

**Comment by grctest** [comment]
> and move EXPLORER next to SETTINGS.
> Dropdown only for accounts list

Sorry to reply to a very old closed issue, but why was it decided to move the explorer to the settings drop down menu?

As it stands, the explore button is effectively hidden out of view & the majority of new users likely won't see this functionality as a result.


Wouldn't it make sense as the following? So as to promote the use of the explore functionality?

![image](https://user-images.githubusercontent.com/15861527/29363526-405ce6ba-8288-11e7-9a25-77fa2bd51477.png)
