### ISSUE TITLE
Get CVCOIN on Bitshares main UI for OPEN.BTC , BTS and BitUSD

### ISSUE THREAD

**Issue by thul3** [bitshares/bitshares-ui#843]
On the main page of bitshares UI there are many coins listed which have zero volume.
As an uprising coin which is soon joining 2 major exchanges i would like to ask to add CVCOIN to 
main UI of Bitshares Asset Exchange so people can see that coin instantly since we make already volume and would like to be easy found.Currently CVCOIN can only be found via search tab which results to ZERO volume from Bitshares Asset Exchange and all volume is just coming from OL.
CVCOIN is a bitshare network based token

**Comment by jamesnkh** [comment]
Yes, this coin will gain high adoption rate in Q1 2018 when the commercial products are out on both apple and google play stores. Please add the CVCOIN image for more exposure.

**Comment by harrypocrypviser** [comment]
I join the request of thul3 CVCOIN to be added to the main UI of Bitshares Asset Exchange. Crypviser has huge potential for near future.

**Comment by future213** [comment]
Please add this hidden gem on he main UI of Bitshares Asset Exchange. This coin has tremendous growth potential and should achieve all its targets in the near future.

**Comment by btsfav** [comment]
? you can trade EVERY bitshares based coin on the exchange.

**Comment by thangpham1** [comment]
Crypviser is the ultimate encryption technology in the future. Cvcoin will be very valuable and increasingly popular. Please add this hidden gem on he main UI of Bitshares Asset Exchange.

**Comment by cheeky772** [comment]
CVCoin will be the coin with validity people have been searching for, if at all they had any misgivings about cryptocurrency. This is not a speculative asset and there is no way it cannot be the king on the main UI Bitshares Asset Exchange. In my opinion, CVCoin will outclass Bitcoin in terms of practical utility.

**Comment by cektop** [comment]
CVCOIN please to main page of bitshares UI, everybody will profit.

**Comment by thul3** [comment]
@btsfav 

thats correct but you need to search for it in the "find markets" tab and you need to know the name.
CVCOIN is not being displayed on "my Markets" as standard coin which means many people don't know about that coin.
The zero volume of CVCOIN from Bitshares Asset Exchange proof this claim
Also there are many coins listed which have zero volume so it would be just fair to list CVCOIN there since its generating volume and joins in december major exchanges

**Comment by DieselDawgg** [comment]
I'm very surprised it's not already there in front for everyone to see when it's the next generation of business & personal encryption. Come on Ronnie, you know this..... Give crypviser a push mate

**Comment by btsfav** [comment]
@thul3 then teach people how to reach it. can't display all minor assets on the front page, at least until there's an algorithm for it

**Comment by barka80** [comment]
yeah CVCoin definitely deserves to be promoted on the main page, esp that it's built on bitshares network. besides it will surely catch a lot of attention in the coming weeks because of the wallet and beta release.

**Comment by thul3** [comment]
@btsfav 
I'm not asking to list all minor coins but to list CVCOIN where it belongs.
CVCOIN was in the past top 2-5 in volume for OL and generated even most income for OL.
Since you have no issue with coins being listed at mainpage which have ZERO volume it shouldn't be a problem for you that there will be a coin listed which actually generates volume for DEX.

**Comment by btswolf** [comment]
I support this, until a fair algorithm is in place

**Comment by wmbutler** [comment]
Further proving that we need to get rid of the featured markets area. This isn't sustainable. Markets should naturally rise to the top based on volume.

**Comment by peterpapp** [comment]
Yey; In my opinion, OL will generate much more income, if this Coin is on the startpage.
Crypviser could be the next MessangerApp on our (mobile) devices..

**Comment by btsfav** [comment]
thiis is the bitshares reference wallet, not openledger.io @peterpapp

**Comment by peterpapp** [comment]
Oh yes sorry 😄  my fault! @btsfav 
I can't believe I keep confusing that. ^^

**Comment by svk31** [comment]
Even if I add it to the list of markets in the dashboard page it won't show up as a featured market because the volume is very low, there's a filtering in place.

**Comment by thul3** [comment]
@svk31 It's not only about dashboard (volume will increase after dec 16 since everyone is waiting)
but about the my markets tab.There are many coins which have zero volume and where CVCOIN should be listed so every new investor who is not so experienced with Bitshares Asset Exchange instantly see's that that coin is being traded there

**Comment by svk31** [comment]
Yea I already added it to the default list of markets so it'll show up in the exchange page, that's why I closed the issue.

**Comment by thul3** [comment]
Still can't see it even CVCOIN has arround 0.3 OPEN.BTC volume.
Should be on OPEN.BTC higher than OPEN.EOS
![mym](https://user-images.githubusercontent.com/34402322/33965148-2abd9eb8-e05b-11e7-91c8-5ae2f37ff348.JPG)

**Comment by svk31** [comment]
Which makes sense since my commit was yesterday and the previous release was two weeks ago.

**Comment by thul3** [comment]
sorry :)

**Comment by henryb2000** [comment]
LISTING REQUEST FOR SUBMISSION

Digital Dollar Coin "DDCT"
Circularion: 1,000,000,000
Created: 12/07/2017
Block: 4694875

https://etherscan.io/address/0xb0dc7fdb068aba78cd79e1bf9006196ff3299c8f
http://digitaldollarcoin.com/
https://github.com/henryb2000/DDCT/wiki/DDCT  (source code)
Reddit:		https://www.reddit.com/r/CryptoCurrency/comments/7iwq7i/a_new_kid_in_town/
Bitcointalk: 	https://bitcointalk.org/index.php?action=profile;u=1412947;sa=showPosts

DESCRIPTION
A fully tradable and transferable digital decentralized asset that is simple to use and secure on the Blockchain and suitable for the P2P and centralized environments.

Thanks.

**Comment by thul3** [comment]
@svk31 

Why can't be CVCOIN be found anymore ?
