### ISSUE TITLE
[7] Unable to withdraw entire funds, must leave a satoshi dust

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#85]
This is a repost of https://github.com/bitshares/bitshares-core/issues/238.
>When you attempt to withdrawal an asset via Gateway, you are able to click the total amount of the asset you have (as a type of "Select ALL/MAX", if you click the amount which follows the "Available:" just above the asset drop-down listbox) which then fills that amount in the "AMOUNT TO WITHDRAW" edit box, but when you click the WITHDRAW button, it only gets a green border and does not actually succeed, and no error message is given - it just sits there, leaving the user with a puzzled experience.
The withdrawal will only go threw if you manually remove a portion (as little as a satoshi) of the asset.

**Comment by calvinfroedge** [comment]
I can take this issue

**Comment by abitmore** [comment]
I think gateway code should be managed by 3rd parties that submitted them, unless there are security issues. They make profit from it, so it shouldn't be funded by the worker.

**Comment by wmbutler** [comment]
Ah, so memos affect the fee? Is there an equation for this? If there is, I think it's important for us to spend time on this to factor in the cost of the memo.

**Comment by abitmore** [comment]
We can reuse the code of "transfer" feature.

**Comment by svk31** [comment]
Memos add a per kb fee, and I never found a way to properly estimate that so no, there's no code to calculate that. The transfer fee estimate is simply for a transfer without the memo. The final fee that's attached to the operation before broadcasting is retrieved from the API, it could be used but I didn't want to fire tons of API requests just for that so I've just left it as is.

**Comment by wmbutler** [comment]
@xeroc may need your help here. Really hate to abandon this bug if there is a solution. Happy to increase the estimate if it requires it.

**Comment by abitmore** [comment]
We can port the [fee calculation code](https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/chain/protocol/transfer.cpp#L28-L34) from bitshares-core, I think it should be doable in UI.
```
share_type transfer_operation::calculate_fee( const fee_parameters_type& schedule )const
{
   share_type core_fee_required = schedule.fee;
   if( memo )
      core_fee_required += calculate_data_fee( fc::raw::pack_size(memo), schedule.price_per_kbyte );
   return core_fee_required;
}
```
Serialize the `memo` field, get the size, times the fee rate.

Perhaps yoyow team has figured it out. I'll ask.

**Comment by svk31** [comment]
Hm ok so it's only the size of the memo itself we need, that makes it clearer. Maybe I can use Buffer to get the size then, that's the only real issue.

**Comment by svk31** [comment]
@abitmore In the code you linked, where does the `memo` come from? It's not defined anywhere as far as I can tell.

**Comment by svk31** [comment]
Ok so I've been looking into this and so far I can't seem to get it right, whether I use the whole memo_data object, just the message itself, an object containing {"message": "azdazd"}, and utf8 or binary encoding the byte size never fits what the witness_node seems to use.

Another major issue here is that the byte length depends on the encoded message, and in order to encode the message the wallet needs to be unlocked.

**Comment by wmbutler** [comment]
@svk31 increase the estimate on this as you put work into it. This is a problem worth solving.

**Comment by abitmore** [comment]
@svk31 `memo` is defined [here](https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/chain/include/graphene/chain/protocol/transfer.hpp#L60):
```
optional<memo_data> memo;
```
and `memo_data` is defined [here](https://github.com/bitshares/bitshares-core/blob/2.0.170710/libraries/chain/include/graphene/chain/protocol/memo.hpp#L40-L67):
```
   struct memo_data
   {
      public_key_type from;
      public_key_type to;
      uint64_t nonce = 0;
      vector<char> message;
   };
```
Perhaps you didn't serialize the `optional` part?

**Comment by abitmore** [comment]
>Another major issue here is that the byte length depends on the encoded message, and in order to encode the message the wallet needs to be unlocked.

While this is true, perhaps we can try to use a dummy key to encode, I guess the size should be same.
