### ISSUE TITLE
Error claiming balance

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#851]
https://bitsharestalk.org/index.php/topic,25459.msg313246.html#msg313246
>Getting the following error when trying to claim balance;
Error claiming balance: TypeError: e is undefined
>
>Also, the unclaimed amount of BTS shown is lower than the asset totals I see after importing keys.
>
>Anyone have any ideas as to what is going on here?

**Comment by dot5enko** [comment]
@wmbutler too little information to test & fix it

**Comment by wmbutler** [comment]
Removing from milestone and changed to question until we have more evidence and a way to reproduce.

**Comment by abitmore** [comment]
Too old. No follow-up. Closing.
