### ISSUE TITLE
Request password before backup .bin file

### ISSUE THREAD

**Issue by magicstone1412** [bitshares/bitshares-ui#852]
Today, I found that I could create backup .bin file without my password. I use my bin file to import to my company's computer. But that computer is not used only by me. I would like to suggest that to backup .bin file, the password must be inputted before downloading that file as same as brainkey. Could you please implement that feature in the next version? Thank you.

**Comment by btsfav** [comment]
I would be against this. If you're on a compromised computer/wallet, you'll give them your password on top of it. the .bin is encrypted with your password anyways, so this would be a double

**Comment by magicstone1412** [comment]
After extracting the .bin file, the old one will be expired. Have you thought this problem?

**Comment by svk31** [comment]
I would advise against using any cryptocurrency on a shared computer.

What do you mean the old one will have expired? Bin files contain private keys and the brain key encrypted with your password. Unless you change the private keys the bin file will always be valid. If you change the wallet password, that still does not affect old backups, which still use your old password. Only new wallet backups will use the new password.

**Comment by magicstone1412** [comment]
I mean if you backup the new one, the old one will be expired. **Maybe I am wrong in this situation?**

I totally agree with you that DO NOT use cryptocurrency on a shared computer. But that is a supposed situation. 

Think about steemit permission, you must input the password if you wanna see private key.

I think with my proposal, we can enforce 1 more security layer on the wallet. Thanks

**Comment by svk31** [comment]
Like I said above, backups remain valid forever unless you change the private keys of the accounts included in the backup.

I agree with @btsfav that the existing password encryption is suffient, that way you can still recover a backup from a compromised computer without exposing your password.

**Comment by wmbutler** [comment]
Closing.
