### ISSUE TITLE
Add All Candelstick Periods that Connected Node Supports

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#856]
I noticed that the node I'm connecting to has configured market history buckets-size =  [15,60,300,3600,86400] which means it has history for 15sec, 1min, 5min, 1hr, and 1day periods.  However in the ui only the 5min, 1hr, and 1day periods are options.

Every node could potentially provide a different set.  
If possible, allow the UI to display all available candle periods that the connected node has history for.  Within some guidelines.  You wouldn't want a period displayed for 1.25 hr  or 12.333333 mins etc.  If it's a whole number it should be fine.

As a side note, any node currently using the default bucket-size array, is wasting memory on two buckets that arn't being used by the UI.

**Comment by svk31** [comment]
The UI already does this; the available candles are set after querying the node what candles it supports.

**Comment by Xeldal** [comment]
hmm, I'm only getting 5min, 1hr, and 1day in UI connecting to kc-us-dex.xeldal.com  
I have buckets-size = [15,60,300,3600,86400] in config.

am I missing something?

**Comment by svk31** [comment]
That node does not work for me at all. Make sure you've done a full replay after modifying the buckets in the config.

**Comment by Xeldal** [comment]
wss://kc-us-dex.xeldal.com/ws is the full address of course.
Concerned that you're not able to connect.  First I've heard.

Is there a node you're aware of that you know has more than the 5min, 1hr, 1day?  That's all I get regardless of the where I'm connected.  

Using win7 desktop client bitshares.171205

**Comment by svk31** [comment]
OK I can connect to that. I see there's a filter in place that removes bucket options below 4 minutes, can't recall why we added that.

**Comment by Xeldal** [comment]
It's a rare thing for anyone to use a chart less than 5min period but I suppose if a node wants to provide the data for a tick chart(3sec) that we should probably display the option.  IDK.  I think the default config should probably be changed in any case; replace the 15sec and 1min with 30min and 12hr.  same default memory requirements, more useful data for UI.

Thanks for clarifying how the UI handles this.

**Comment by happyconcepts** [comment]
Sadly not enough vol for 15 sec and 1 minute intervals to show anything
worthwhile IMO

**Comment by svk31** [comment]
Yea that's probably the reason why we hid them in the first place.

**Comment by Xeldal** [comment]
That's not really the point.  There are many pairs that even the dailys don't have enough data to make a readable chart, but we are not blocking them.

I don't actually care about anything less than 15min.  It's a waste of memory to provide data for those periods, but if the server is providing the data, the wallet should show it.
