### ISSUE TITLE
Change Gray Tab Colors in Explore Section

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#857]
The gray colors for the tabs in EXPLORE -> Assets --> ANY SMARTCOIN -> Price Feed Data and Margin Positions are too close together. Gray and another very close gray? It is very unclear which is currently in the foreground from the colors of the tabs.

This is true in all three themes.

**Comment by landry314** [comment]
Another way to highlight like a border or text color change could work too.

**Comment by wmbutler** [comment]
The explorer has been rewritten in the upcoming release. Closing this and you can add a new one if you still don't like it.
