### ISSUE TITLE
Window 10 wallet crashes

### ISSUE THREAD

**Issue by effath** [bitshares/bitshares-ui#869]
I am trying to use the latest release with Windows 10.  It starts up fine but when I try to switch to exchange, the wallet  gets stuck and crashes, I guess as the block stop updating.  I also am not able to select anything on the wallet and must force a close using task manager.   IS there a fix for this?

**Comment by wmbutler** [comment]
Please switch to a different node: Settings -> Access and report back with your findings.

**Comment by svk31** [comment]
This is most likely an Electron issue, I'll try to update the electron version before pushing the next release.

**Comment by startailcoon** [comment]
I use win 10 and never had this issue

**Comment by wmbutler** [comment]
@effath post a licecap with console logs visible.

**Comment by effath** [comment]
How do get to the console from GUI?  I don't see it.  IT seems to be that there node are unreliable . They are not syncing or the latency is too long.   I just get progress bars waiting for the exchange tab to load.   I've tried several other nodes unsuccessfully. 

i rebooted the wallet and reconnected to wss://dexnode.net/ws and was finally under  1000MS on my connection...  So my question is this?  Is this a node problem or a sofware issue?

**Comment by wmbutler** [comment]
It's under the menu.

**Comment by wwg2018new** [comment]
@effath  how to run in  windows
