### ISSUE TITLE
Language option should always show on upper right corner like before

### ISSUE THREAD

**Issue by imYao** [bitshares/bitshares-ui#873]
like this:
![image](https://user-images.githubusercontent.com/5551341/34023420-cc906f7a-e17f-11e7-81c4-aba4a24b27dc.png)

**Comment by wmbutler** [comment]
Why? How many times do you have to change language? Once, ever. Valuable space like that makes no sense for something the user will never touch again.

**Comment by imYao** [comment]
@wmbutler I can't agree with you. Many new users, especially non-English users, don't know where to set up language. Many users can't read an English word, even a very simple word "setting". Once they don't understand the language of UI, they will leave...

Do you want to keep the vast majority of users out of the door of BitShares? Unless you can allow GUI to automatically switch to the corresponding language according to the user's IP address.
