### ISSUE TITLE
[0.5] Check cloud wallet login password against local wallets

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#874]
Some users appear to be attempting to login with cloud wallet mode when they should be using local wallet. The password validation method can be extend to also check the password against the user's local wallet if present even when they're using cloud mode.

**Comment by btsfav** [comment]
is there a way to display the account type clearly somewhere? would help with trouble shooting

**Comment by wmbutler** [comment]
This would be nice...open a separate issue.
