### ISSUE TITLE
Yellow Margin Calls In Order Books Are Confusing or Not Buyable

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#876]
I remember you could buy margin calls in the order books, now you can't. I don't know why.

If you can't they shouldn't be in the order book.

If you are suppose to then why can't you? Is this working properly? Anyone else?

**Comment by svk31** [comment]
You can, but there are some complicated conditions thst need to be met that I don't recall off the top of my head.

**Comment by wmbutler** [comment]
This isn't actionable.

**Comment by landry314** [comment]
See #877
