### ISSUE TITLE
[.5] Turkish characters do not display properly

### ISSUE THREAD

**Issue by vikramrajkumar** [bitshares/bitshares-ui#88]
_From @JianJolly on March 4, 2017 17:59_

When Turkish language is chosen, special characters won't show up in the same font type as the rest of the page. See the letters 'Ö', 'ı' and 'ç' in the screenshot below.

![1](https://cloud.githubusercontent.com/assets/19493352/23580996/cc44b112-0114-11e7-8d0c-fb2501672cc7.png)

_Copied from original issue: bitshares/bitshares-core#244_

**Comment by vikramrajkumar** [comment]
_From @abitmore on March 5, 2017 0:7_

UI issues belong to https://github.com/bitshares/bitshares-ui/issues

**Comment by wmbutler** [comment]
@JianJolly, Are the characters accurate? Is this strictly cosmetic?

**Comment by JianJolly** [comment]
The characters are accurate, but they don't look as a native part of the font family.

**Comment by wmbutler** [comment]
OK, I'm going to de-prioritize this since it's not a major bug.
