### ISSUE TITLE
Private key login

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#880]
For cloud wallet:  Is there a reason we are having people use a "password" instead of their private key to login?  If the password was compromised it is essentially the same as if the private key is compromised.  is it not?  Why the extra layer of complexity? 

Is it solely to provide the option for the user to set their own password?  What benefit is this?

The login / create account / restore account / import account / cloud/ local wallet etc process is a splintered mess.  

It took me 15 minutes to figure out how to login to an existing account from a private key.  It's no wonder so many are having issues regarding login.

At the very least we should add to login logic a check to see if the entered password works as a wif key for the account.

I'm starting to think it would be best if we simply dropped the cloud vs local login styles and just offered a single simple login with wif-key/password for individual accounts.   From there a user could define a key-ring file if they wanted to manage multiple accounts and to login with if desired.  And download for backup.

In settings you could add or remove keys from any number of key-ring files.  As well as load an active key-ring.

To login using the key-ring simply select "Use Key Ring", select the file, and enter your decryption password.  This would load a single key from the ring and the wallet would work exactly like any other single account login with an attached key-ring file for easily switching accounts.

This solves a lot of issues of complexity.  There is only 1 login type.  No more local vs cloud.  If a user wants easy access to multiple accounts he simply defines a key-ring and loads it to the session.  If a user desires a simple password instead of the complex wif-key.  All he needs is to define a key-ring and encrypt it with the password of his choosing.  This password would be useless to an attacker without the key-ring file, so password complexity is less important.

**Comment by svk31** [comment]
Cloud wallet login already allows both, you can use a private key or your password, as long as you supply the right account name.

The main benefit of using a password is that key management is far too complicated for the average user. Having a username and password is familiar.

**Comment by Xeldal** [comment]
Ok thanks.  I guess that also kind of illustrates my point though.  I must have been trying to login with the local wallet because it wasn't accepting my wif-key for a password.  

I hate the fact that there are 2 types of logins, 2 types of wallets.  I don't think there needs to be.  Everyday there is confusion and problems for new users regarding that. I'm Looking for ways to resolve this.

If you only have 1 account, which the vast majority of user will.  What is the difference in managing a private key and a sufficiently long password.  If you can manage the password you can manage the key.   Anyway, It's not really necessary to remove the functionality of having a password and not the point I want to stress.  Much like you can login to steemit with your master password or with any of your keys.  This is ok.

I think we can combine the two types of wallets\login into a single one account style login like the "cloud" login is now.  The local login is just providing a method for switching between multiple accounts using a list of keys in the local .bin file.  Either way your keys are exposed to the client.  1 isn't any safer once unlocked then the other.

Why do we have local login \ local wallet?  What else is it good for, besides having a list of accounts to switch between?  Can't this functionality be held within the "cloud" type wallet model?

Evey local wallet account is already a cloud wallet account by the fact that you can log in to each with their wif key.

It is silly that we are separating the two.
What am i missing.

Just get rid of the local wallet and add an option to manage a key-ring file

**Comment by svk31** [comment]
You are missing the fact that the local wallet provides better security at the cost of convenience. Every cloud wallet account can in theory be brute force attacked since the pub key is public and is generated from a "known" seed where only the password is missing. The local wallet on the other hand can only be brute forced if an attacker has access to your bin file backup. 

Getting rid of the local wallet is not an option. The vast majority of users should never have to even deal with a local wallet, your concern is mostly valid for users like yourself who have been around since the days when the local wallet was the only option and who don't quite understand the difference between the two models.

**Comment by Xeldal** [comment]
With a sufficiently long password it is exactly the same difficulty to brute force as the private key.  But anyway, like I said whether or not there is a password function in addition to the option of using the wif-key as the password is not important.  It is ok to have this option.

What I'm trying to get at is that there is no reason to separate the 2 models,  cloud and local.  They are both cloud.  Only with the local wallet you're just unlocking your password(wif-key) from a local file.  Otherwise it's the same thing.  We don't need an entirely new login path to have that function.

Every account whether local or cloud, is a cloud account.  the wif-key is their password.

Maybe I shouldn't say get rid of the local wallet.  I should say get rid of both cloud and local wallets.  And replace it with 1 wallet type.  1 login type.  You can use your master password or login with your wif-key password.  If you have a key-ring file.  This will allow you to easily switch between your accounts, access all the accounts with a single password, and carry them with you on a thumb drive.

2 wallet types, 2 login types not needed.

**Comment by wmbutler** [comment]
It sorta is. One method uses two pieces of information, saves data in the specific browser URL and allows for multiple accounts.

The other method allows the user to login from any browser and is 1:1 with the associated account. If you want to effect change here, you will need to lobby the community, not us.

**Comment by Xeldal** [comment]
>It sorta is. One method saves data in the specific browser URL and allows for multiple accounts.
>The other method allows the user to login from any browser and is 1:1 with the associated account.

99% of the functionality is identical.  Multiple accounts is the only difference and is easily integrated.  Consider a Local wallet with 1 account.  What is the difference?  If there is a difference, is it necessary?   

@wmbutler you are making my head spin. Did you read the thread?  I feel like I'm repeating myself to no good.  I'm well aware of the differences between the two(barely any).  The question is can they be combined to make a single login type.  A single wallet type.  The answer is, yes they can.  The response I'm getting from you seems to indicate that you don't care if it can or not.  You like the shit design we have and don't want to have to think about it or remake anything.  Is that about right?

>If you want to effect change here, you will need to lobby the community, not us, or better yet, fork the reference wallet, create your own brand and remove whichever you prefer. 

What are you doing here then?  Why even have github issues if you don't care what anybody has to say about what you're doing to the wallet.

It's fine if you don't like the idea Bill.  Tell me why your design is better.  Just dismissing my suggestions and criticisms with "why don't you fork your own project"  is arrogant, lazy and helps nothing.  

@svk31 I appreciate your willingness to discuss these things.  Your work is appreciated.

**Comment by btsfav** [comment]
local wallet is needed for security, there is zero chance to make the process easier in my opinion.

newbie friendly wallets are something 3rd partiy companies can offer, if they see value in it

**Comment by landry314** [comment]
I think the two methods are quite technically different and can't be integrated...

**Comment by Xeldal** [comment]
>local wallet is needed for security

My design has the same security characteristics as local wallet

> there is zero chance to make the process easier in my opinion.

I've already shown how it can be done.

> I think the two methods are quite technically different and can't be integrated...

care to share technically what exactly makes them incompatible?  I've just shown how they can be combined.  Where am I mistaken?
