### ISSUE TITLE
[1.25][dot5enko] Move language selection to account registration screen

### ISSUE THREAD

**Issue by todasun** [bitshares/bitshares-ui#883]
https://wallet.bitshares.org/  no language choose  icon button
![image](https://user-images.githubusercontent.com/10720816/34159741-34ec4890-e505-11e7-8a20-1cdac6fd1035.png)

https://openledger.io/  have 
![image](https://user-images.githubusercontent.com/10720816/34159774-55e7d1e0-e505-11e7-9a0b-d65329326f2f.png)
![image](https://user-images.githubusercontent.com/10720816/34159807-73abb7a0-e505-11e7-81e2-222c094552da.png)

not every newbee know english GUI！

**Comment by wmbutler** [comment]
It's in settings -> general. agreed we should put it on the account registration page.

**Comment by Ronolibert** [comment]
I'd like to work on this issue!

**Comment by wmbutler** [comment]
![screen shot 2017-12-24 at 1 04 24 pm](https://user-images.githubusercontent.com/1254810/34328671-006e231e-e8ab-11e7-8ca4-ce3619177aad.png)

**Comment by dot5enko** [comment]
i claim this

**Comment by wmbutler** [comment]
I changed this to 1 hour. Let me know if you need more. Not quite sure why I set it to 3, but it may be a 1.5 or 2.

**Comment by dot5enko** [comment]
Content of dropdown doesn't fit height of the page, so you need to scroll down the page to select some languages, is it ok? ![lng_slector](https://user-images.githubusercontent.com/5626922/34462193-e9cf9362-ee46-11e7-9c3d-9e34b56ad094.gif)

**Comment by wmbutler** [comment]
I see that the modal gets wider after selection. Is there a way to resolve that?

**Comment by dot5enko** [comment]
@wmbutler  made it 450px fixed width,but look at create account in russian now:
![fixed_width](https://user-images.githubusercontent.com/5626922/34463353-c192f090-ee61-11e7-86f8-af7350ff4948.gif)

**Comment by wmbutler** [comment]
Let's increase the button width to account for the Russian translation.

**Comment by dot5enko** [comment]
@wmbutler i don't think its a good idea to change width of only russian translate because that would be hardcode. probably we could make one button per row to fix this problem

**Comment by dot5enko** [comment]
@svk31 i forget to push width fix, please accept it https://github.com/bitshares/bitshares-ui/pull/942
