### ISSUE TITLE
Language option should always show on upper right corner like before

### ISSUE THREAD

**Issue by imYao** [bitshares/bitshares-ui#884]
For non English users, opening the BitShares wallet should directly see the language option switch button, otherwise they can't understand the UI language and can't do the next operation, they will close the wallet and leave.

More reasons are discussed here: https://github.com/bitshares/bitshares-ui/issues/873

**Comment by btsfav** [comment]
the wallet should auto-detect browser language and set it accordingly. you could then change language via settings if you want. 

see how rudex does it, maybe it can be copied

**Comment by wmbutler** [comment]
I'd disagree that it needs to be shown in the upper corner. Instead I'd suggest it be shown on the login screen.

**Comment by wmbutler** [comment]
Duplicate #883
