### ISSUE TITLE
add approval multisig

### ISSUE THREAD

**Issue by tcpaul** [bitshares/bitshares-ui#885]
Im trying to approve a proposal to send 1 BTS from an account "tester-bitspace" with multisig, to an account "paul-bitspace". With two weighted accounts "test-bitspace" and "zerfix-bitspace".

`approve_proposal test-bitspace 1.10.6409 {"active_approvals_to_add" : ["test-bitspace"]} true`

I want to add approval with another account "zerfix-bitspace".

I cant find an example of this flow anywhere

**Comment by wmbutler** [comment]
This is not a UI issue.
