### ISSUE TITLE
[5.5][dot5enko] Exchange Header

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#888]
We are planning to integrate TradingView for the charting, but I wanted to go ahead and submit a UX for the header which includes how we will display key metrics. This will help tradingview integration to at least have a design to draw inspiration from. I stole this look from GDAX largely. Principle changes over our existing layout allow for a full row of information without letting the order book cut into the left edge. The new design also stresses large information with small labels.

- [ ] Remove all up and down arrows
- [ ] All fonts are Roboto Regular (except 24hr, user Roboto Bold)
- [ ] User can click on the 24hour volume to toggle between each asset

## Current
![screen shot 2017-12-20 at 10 28 04 pm](https://user-images.githubusercontent.com/1254810/34240602-14eec65a-e5d5-11e7-916a-a97e609b66e5.png)

## Proposed
![screen shot 2017-12-20 at 10 20 25 pm](https://user-images.githubusercontent.com/1254810/34240592-03e9320a-e5d5-11e7-979a-2d5b08507160.png)

**Comment by dot5enko** [comment]
@wmbutler i claim this. Arrow in the latest price block is quite informative, do you really want to remove it? maybe we can make it like 24h price - with appropriate colors?

**Comment by Xeldal** [comment]
suggestions:
1) replace "24 hour price" with "24 hour change"

2) anywhere there is a "price" (ie "settlement price") where we currently list the quote over the base (ie bitUSD/BTS).  I suggest only listing the quote (ie bitUSD) like you have in the example for "latest trade price".  I haven't check every exchange in the universe but I haven't found a single one that lists the full fraction (quote/base).   A couple reasons come to mind.   A trading pair is listed BASE/QUOTE, if on the same page you're seeing lots of the opposite arrangement(ie QUOTE/BASE) like you do on our exchange.  It can be confusing as to whether you have the exchange oriented the right way or if its flipped.   Another reason is that the price of something almost always presumes that the base = 1 and so the full fraction isn't necessary.  

The price is how much of the QUOTE currency is necessary for 1 of the BASE.

so:
old-> Settlement Price = 0.640118 bitUSD/BTS
new-> Settlement Price = 0.640118 bitUSD  

The same should be applied throughout the entire exchange page.

**Comment by wmbutler** [comment]
- [ ] I agree with both of @Xeldal points here.

**Comment by dot5enko** [comment]
ok. start working

**Comment by wmbutler** [comment]
> @wmbutler i claim this. Arrow in the latest price block is quite informative, do you really want to remove it? maybe we can make it like 24h price - with appropriate colors?

- [ ] Use green/red pulse color anywhere a price change arrow indicator might have been before.

**Comment by wmbutler** [comment]
@dot5enko can you have this completed by Jan 4?

**Comment by dot5enko** [comment]
@wmbutler i'm working on it whole day. Still have few issues, try to accomplish them today

**Comment by wmbutler** [comment]
Happy to increase the hours if needed.

**Comment by dot5enko** [comment]
@wmbutler would be great if we can add two hours here.

**Comment by wmbutler** [comment]
Done. Any progress? Would love to see some screen shots. Also wanted to make sure that the div goes all the way across which would push My Market / Find Markets down as well.

**Comment by dot5enko** [comment]
hm... i haven't seen that from your screenshot, so now its only pushes chart and order list. But seems it would be not that hard to meet your requirements. This is the current state of header. Try to ccomplete it today

![image](https://user-images.githubusercontent.com/5626922/34648622-4a4afe76-f3a5-11e7-8da1-88251079fd68.png)

**Comment by dot5enko** [comment]
![image](https://user-images.githubusercontent.com/5626922/34650453-4f60d9e2-f3ca-11e7-83a6-e3ec5e1a5be6.png)
![image](https://user-images.githubusercontent.com/5626922/34650464-763b6c08-f3ca-11e7-8a23-25d991cbb6ef.png)

**Comment by wmbutler** [comment]
Looking awesome

- [ ] +/- sign on 24 hr change indicator
- [ ] The seocnd screenshot is better. Remember, there can be a lot of items added to that bar when assets are settled, etc.

**Comment by dot5enko** [comment]
yup, they're all stylized in that way: settle price, margin call prices. i'll try to make screenshota with all of them

**Comment by wmbutler** [comment]
- [ ] Add a line across the bottom of your header that helps delineate the header from the rest of the lower elements. Just something to add definition.

**Comment by dot5enko** [comment]
![image](https://user-images.githubusercontent.com/5626922/34854945-a4c898ce-f745-11e7-972b-7f910ded0149.png)
@wmbutler how about this border? i got color from bottom of "my markets"

**Comment by wmbutler** [comment]
- [ ] Maybe stick with a neutral gray or something? I was thinking something that just bridges my markets to left side. Remember, we are going to get fancier with this once we go to tradingview so this just needs to get us through to that.

**Comment by dot5enko** [comment]
ok. no problem)

**Comment by dot5enko** [comment]
![image](https://user-images.githubusercontent.com/5626922/34856120-073f9b14-f74c-11e7-94df-80f92d2728bb.png)

**Comment by wmbutler** [comment]
Schwing!

**Comment by dot5enko** [comment]
forget to make a screenshot with margin call price on it. Here is a simulated behaviour with appropriate colors:
![image](https://user-images.githubusercontent.com/5626922/34890191-9dbf68fc-f7d9-11e7-96cb-e3bbc3d30ad5.png)

**Comment by dot5enko** [comment]
Volume asset change on click:
![volume](https://user-images.githubusercontent.com/5626922/34920435-718ebea6-f97b-11e7-9317-3d1d9c345835.gif)

stats pulsation:
![pulsation](https://user-images.githubusercontent.com/5626922/34920484-198ad1da-f97c-11e7-90f3-b7f6499a4e16.gif)
