### ISSUE TITLE
[13.5][startailcoon] Dashboard Styles Refinement

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#889]
We are getting close with the look of the client but still missing some of the polish. I originally suggested that the tables extend to the edge of the browser. I still think it's a better choice to do that. Part of the problem is that the hover color of the secondary level menu didn't match the background. This created a problem for the tabs logically falling into place. By matching up the top background color with the hover/selected color, we have a place to put filters and action buttons so they don't look stranded.

- [ ] Extend table and all backgrounds to the full edge of browser with no gap
- [ ] Make hover color: #28384b
- [ ] Make background for active | hidden same color: #28384b
- [ ] Adjust for smaller fonts
- [ ] Include filter where applicable

>This also is the same color as the <td> in the table.

## Current
![screen shot 2017-12-21 at 1 17 58 am](https://user-images.githubusercontent.com/1254810/34244840-cfa0fbb4-e5ec-11e7-96de-436ac526b2ca.png)

## Proposed
![screen shot 2017-12-21 at 1 12 53 am](https://user-images.githubusercontent.com/1254810/34244847-d3a11dfc-e5ec-11e7-8cf8-4c614ea51199.png)

**Comment by happyconcepts** [comment]
@wmbutler I would like to implement this one. Happy holidays!

**Comment by happyconcepts** [comment]
Well I have been away awhile and hadn't seen #667 so I will of course defer to @diogo-gomes if he wants to claim it.

**Comment by wmbutler** [comment]
@happyconcepts Can you have this completed by Jan 4?

**Comment by happyconcepts** [comment]
Sure thing, but what does "Adjust for smaller fonts" mean exactly...how much smaller for example?

**Comment by wmbutler** [comment]
And Accounts / Contacts / Recent Activity with Filter:

![screen shot 2018-01-04 at 11 36 55 am](https://user-images.githubusercontent.com/1254810/34576653-3bb05af4-f144-11e7-9cbe-4ce407353082.png)

**Comment by happyconcepts** [comment]
@wmbutler thanks for the clarification on font sizes. 

I can't test this adequately right now for cross-browser issues; perhaps you or someone else who is more up to speed on the Tables Rewrite can take this issue after all.

**Comment by wmbutler** [comment]
Happy to, did you push your branch?

**Comment by wmbutler** [comment]
Moving to 170115. Please post some screenshots so we can fine tune this.

**Comment by happyconcepts** [comment]
@wmbutler I can't, no screenshots and some major RL complications. Sorry this one didn't work out.

**Comment by wmbutler** [comment]
OK, so should I take your name off of this one? Let me know how to proceed.

**Comment by wmbutler** [comment]
@startailcoon you self assigned this but I see no progress. Should I remove you to let someone else take a shot?

**Comment by startailcoon** [comment]
@wmbutler Question, in your "Proposed" image you have no left padding. Do you wish the table to span the full width of the window?

# Before
![image](https://user-images.githubusercontent.com/12114550/35828461-ceb3bd52-0abf-11e8-9f97-49377d558fb0.png)

# After
![image](https://user-images.githubusercontent.com/12114550/35828490-ea90919e-0abf-11e8-81d4-02bff0e82fa8.png)

# Very wide screens (optional)
Very wide screens may pose a very strange behavior. It could be good to limit the width to something maximum, but still keep it right aligned. Something like this maybe?

![image](https://user-images.githubusercontent.com/12114550/35828540-29a63564-0ac0-11e8-8702-d795038cd826.png)

Another option could be to fill the right screen with the table background? 
Open to suggestions here.

**Comment by startailcoon** [comment]
Next in line, will have this done in a few days for a view

**Comment by wmbutler** [comment]
Looking great. Is there any way we can get the active tab color for Portfilio, Open Orders et to match the color surrounding Filter, Active, Hidden? This would tie in the selected item more clearly. It's pretty good now, but my intention was to match selected tabs with the inner color.

**Comment by startailcoon** [comment]
Absolutely, adding those to the list of changes. Active tab should be the same, just think the above cap was made before I did that.

Should we keep or remove the active tab line? There's a blue line underneath it today.

**Comment by wmbutler** [comment]
Hard to say. Let's make a judgement call once the colors are right. My gut says that we won't need it because the color flowing into the next leve will be an adequate indicator, but I could see the argument both ways. Maybe @ahdigital will have an opinion.

**Comment by ahdigital** [comment]
On these particular tab bars that immediately follow the top nav bar, please remove the blue line. The blue line to denote active tabs works better for tab bars that appear standalone within the content body.

**Comment by startailcoon** [comment]
## Final Result

This is a preview of the final result.
I've had to fix a few issues that came out of this to the other sections of the program, as they use the same classes. I've added some extra margin padding on most of the menu items. 

I hope I haven't missed anything, please help me review the submitted PR.

![bitshares-newheaderstyle](https://user-images.githubusercontent.com/12114550/36061036-8b4d90cc-0e54-11e8-9906-e4c726a03677.gif)

**Comment by wmbutler** [comment]
Can you place the filter on the same line as the toggle options? This looks great.

**Comment by startailcoon** [comment]
I can do that

**Comment by wmbutler** [comment]
@startailcoon it was my intention to model all the submenus in the same way

**Comment by wmbutler** [comment]
voting, accounts, etc.

**Comment by startailcoon** [comment]
I miss understood the wide scope that you had in mind.

Lets summarize and see what we should do then.

### Dashboard
This is done

![image](https://user-images.githubusercontent.com/12114550/36065010-a7491216-0e94-11e8-93d7-ecd4290d3b74.png)

### Accounts
Should this be like the Dashboard, but without the tabs?
- Same background color just without the tabs?
- Full width table?

![image](https://user-images.githubusercontent.com/12114550/36065058-9e983574-0e95-11e8-9272-d431da083b0c.png)



### Explore
This could have the same background as the tabs I assume?
![bitshares-newstyle-explore](https://user-images.githubusercontent.com/12114550/36065022-f0bcbcc2-0e94-11e8-9cfc-dc53674536f9.gif)

### Voting
Should we move the proxy voting input from the tab view here?

![image](https://user-images.githubusercontent.com/12114550/36065030-1e97b8fe-0e95-11e8-9874-5ecf98e05866.png)

### Create Asset
Should this get the same design as the Dashboard Table?
- Same background as the tab?
- Full width table?

![image](https://user-images.githubusercontent.com/12114550/36065043-5add88fc-0e95-11e8-983e-973abf44f210.png)

**Comment by wmbutler** [comment]
- [x] Dashboard looks great
- [ ] Accounts is a strange one because we skip over the sub menu hierarchy, but maybe this is something @ahdigital can help us think through.
- [ ] Explore, yes, ideally it has the same background color as the active tab so it helps identify the active tab. Not sure how a sweeping change like this might affect the look, but it's the right pattern at least. Regarding the filter on the Explore area, it makes sense to place it on the left in the same design pattern as your preview comment from 5 days ago.
- [ ] Maybe if we match the background color of proxy voting to the other tabs and then change the input field color to something lighter we can address that. We run the risk of proxy getting lost if we put it on a sub level. The status of proxy sits at the top of the voting pyramid since the rest of the decisions rely on whether a proxy has been selected or not. 
- [ ] Create Asset: yes it should.

The only other thing that should be considered, but possibly not for this issue, is to move the Send control into the right burger menu.

Notice how dashboard, Exchange and Explore are always present. This creates a logical menu hierarchy for their sub menu items. Unfortunately, items like voting / accounts, etc lose this logical hierarchy because we don't have a place to display that chosen item (Voting for instance). I've been trying to think about how to accomplish this. Do we add a tab for whichever top level is currently selected and just replace it with whatever is selected next? It might be a workable solution. It give priority to Dashboard, Exchange and Settings as omnipresent, but those tabs are frequently accessed. I've been wanting to voice this concern but hadn't figured out the forum for it yet.

**Comment by startailcoon** [comment]
After a few changes, here's what's left to do

- [ ] Replace send tab with "active tab" to make the tab menu more consistent
- [ ] Replace tab sub-sub tab of Explore->Asset with a sub-menu.


Here's an update with most of the changes

## Account
![image](https://user-images.githubusercontent.com/12114550/36067014-40538958-0eb5-11e8-8449-3a42e820fcc5.png)

## Voting
![bitshares-voting](https://user-images.githubusercontent.com/12114550/36067017-518f41b2-0eb5-11e8-9407-daab66bd1373.gif)

## Explore
![image](https://user-images.githubusercontent.com/12114550/36067026-7558d05e-0eb5-11e8-9efd-5ed0b308478a.png)

**Comment by startailcoon** [comment]
# Variable Menu on Mobile

Mobile is a bit tricky, since we can't display all three items (Dashboard/Exchange/Explorer) plus the new variable active tab.

This is how this will work
- Fourth active tab will always show
- Second + Third tab will show only if screen estate permits so, while still leaving space for the variable tab.

This means we can at times seem to have space for more tabs than we do, as we need space for the fourth tab that isn't visible


![bitshares-dynamicheadernarrowscreen](https://user-images.githubusercontent.com/12114550/36072237-8a45c79e-0f1c-11e8-8196-0e90f6f4547f.gif)

**Comment by ahdigital** [comment]
I **think** in my PR 1140 I removed all links on mobile and added them to the menu.

**Comment by startailcoon** [comment]
I will look on your changes to the menu. I like your move to a more space saving notice if your logged in or not, and the name shaving if its to long.

I don't think we should get rid of the top tabs on mobile though.

I will incorporate your changes in my PR for the menu.

**Comment by startailcoon** [comment]
After merging with changes in PR 1140.
- [x] Merged with PR 1140 for Header.jsx, _header.scss, _theme-template.scss to incorperate dynamic header.
- [x] Fixed Theme specific issues with stylesheets from PR 1140

![bitshares-dynamicheadernarrowscreen-longusername](https://user-images.githubusercontent.com/12114550/36078279-901c1756-0f74-11e8-88a1-d6ea8be57fcd.gif)

**Comment by wmbutler** [comment]
Feel free to add another .5 if needed, but I was thinking that it would make sense to:

- [ ] Get the filter up above the TH in the same blue as the submenu highlight
- [ ] Place the text "type" into the th
- [ ] Place the text "Time" into the th over the transaction time

<img width="574" alt="screen shot 2018-02-11 at 2 52 08 pm" src="https://user-images.githubusercontent.com/1254810/36078407-4066ad68-0f3b-11e8-96ca-a1038ddddfa2.png">

**Comment by startailcoon** [comment]
Preview of the new Activity section. Please ignore all "connection issues" in my console :)


![bitshares-dynamicheader_transactions](https://user-images.githubusercontent.com/12114550/36116559-fe5c7928-1036-11e8-89d9-41f1204fce2a.gif)

**Comment by startailcoon** [comment]
Note for future reference 

The new `header-selector` should be implemented like the following directly under a `<Tab>` or a `<Div>`
The `selector` class will divide all inline div objects with a `|`

![image](https://user-images.githubusercontent.com/12114550/36116895-31dd452e-1038-11e8-8b20-abc878afb04c.png)



```
<div className="header-selector">
 <div className="selector">
  <div className={cnames("inline-block")}>My First Selector</div>
  <div className={cnames("inline-block")}>My Second Selector</div>
  <div className={cnames("inline-block")}>My Third Selector</div>
 </div>
 <div style={{float: "right"}}>Some floating object, like a button...</div>
</div>
```

**Comment by gibbsfromncis** [comment]
@startailcoon hey. my[ new feature "nested menus"](https://github.com/bitshares/bitshares-ui/issues/904#issuecomment-365401549) conflicts with your feature on Header.

I'll try to resolve conflicts by my self but can I ask you to test your feature again after my PR?

**Comment by gibbsfromncis** [comment]
@startailcoon Can you please checkout to my branch and check your changes are OK after my merge? https://github.com/gibbsfromncis/bitshares-ui/tree/904

I had a lot of conflicts on Header.jsx so I've removed all my changes, pulled yours and put my back. So everything should be fine but would be nice if you can check.

**Comment by startailcoon** [comment]
@gibbsfromncis it seems to act the right way, yes.
Added a comment on your PR for a small change.

**Comment by startailcoon** [comment]
@svk31 @wmbutler Due to the recent issue with multiple work on the same files and the tangling of all PRs this issues PR (#1143) has been left out with only partial changes.

I will rework a new PR, but it can't be done until later today at best.
