### ISSUE TITLE
Fee calculation error

### ISSUE THREAD

**Issue by JianJolly** [bitshares/bitshares-ui#89]
In the buy and sell widgets, when the fee is to be paid in BTS, the "use all my balance" function seems to calculate the fees in satohis, but doesn't divide the result by 1e+8 at the end. See below for examples.

![corewalleterror2](https://cloud.githubusercontent.com/assets/19493352/23625555/4383df70-02b2-11e7-89da-07df7c62d002.jpg)

![corewalleterror1](https://cloud.githubusercontent.com/assets/19493352/23625572/56761666-02b2-11e7-9f9a-d57553850a6f.jpg)

**Comment by svk31** [comment]
Good catch, thanks.
