### ISSUE TITLE
[1.5][pnomolos] Can't see some fee currency options when sending

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [bitshares/bitshares-ui#893]
Windows 7
google chrome (12/21/2017)
100% zoom

Hitting send, trying to pay fee in USD, can't find it. Realized tiny sliver at bottom is usd

![image](https://user-images.githubusercontent.com/22536095/34264372-b80256fc-e640-11e7-9381-00980385bdeb.png)

Definitely UI issue

**Comment by btsfav** [comment]
seems like this is a space issue and only when you got 3 fee-able assets. for more you got the scrollbar and it's a non-issue

**Comment by wmbutler** [comment]
We might need a typeahead here... or possible a smarter dropdown...

**Comment by pnomolos** [comment]
I can take a stab at this - thoughts on whether to do typeahead or smarter dropdown?

**Comment by wmbutler** [comment]
Let's improve the dropdown for now. We can add the typeahead as a feature after we fix this bug.

**Comment by pnomolos** [comment]
@wmbutler Right now the dropdown `overflow` attribute is set to hidden if there are less than 9 elements (or 8, don't remember exactly).  Would you prefer that I add a new attribute that can be passed through to mark the number of list elements the threshold should be at, or change how it works so the `overflow` attribute is modified client-side depending on the size of the dropdown.

**Comment by wmbutler** [comment]
@pnomolos it doesn't really matter to me.

**Comment by wmbutler** [comment]
Please complete by Jan 4.

**Comment by pnomolos** [comment]
@wmbutler Ready for review in #947, thanks! :)
