### ISSUE TITLE
Send asked me to pay and did pay higher fee than lifetime member should

### ISSUE THREAD

**Issue by o5j5vg55bv5hv5j5f8799f9** [bitshares/bitshares-ui#894]
I'm a lifetime member. 

Here's what I see when I select USD https://i.imgur.com/s8Cb7cb.png

That's not lifetime fee http://cryptofresh.com/fees?asset=USD

This is from explorer: 
![image](https://user-images.githubusercontent.com/22536095/34265054-d54b29ee-e642-11e7-8673-db1a09ee5309.png)

p.s. why does clicking on transfer open entire block instead of specific tx I clicked on?

**Comment by svk31** [comment]
Fees are always paid in full, lifetime members get a refund afterwards via vesting balances.

The block explorer only shows full blocks at the moment, linking to a specific trx can be requested in a new issue.
