### ISSUE TITLE
"Valid positive number" error in BTC withdrawals

### ISSUE THREAD

**Issue by JianJolly** [bitshares/bitshares-ui#90]
When a number less than 1 is entered in the Amount field, the BTC withdrawal window gives the following error:

![photo_2017-03-07_15-03-46](https://cloud.githubusercontent.com/assets/19493352/23655747/105d9f36-033f-11e7-993f-d2a4244051cf.jpg)

**Comment by svk31** [comment]
Already fixed here https://github.com/bitshares/bitshares-ui/commit/f52647be5bd0d3c158007be15c3cd4dc1dfa8b15
