### ISSUE TITLE
[1][pnomolos] Make Collateral Slider More Precise

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#900]
Instead of changing in increments of 5%, It would be nicer to use increments of 1%... I am always manually typing in collateral numbers to get it closer to what I want.

Does anyone agree?

**Comment by pnomolos** [comment]
Does it make sense to tie this in to #901?

**Comment by wmbutler** [comment]
@pnomolos this is a separate feature.

It's fine with me and an easy win.

**Comment by pnomolos** [comment]
OK I’ll take it as well :)

**Comment by pnomolos** [comment]
@wmbutler BTS account name is: pnomolos-1.  Thanks!
