### ISSUE TITLE
[.5] Add Max Collateral Feature To Margin Adjustment Window

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#901]
Imagine having a "Use Maximum Collateral" option right below the collateral ratio slider which would use as collateral all available BTS currently in the active account. I am always doing this manually. If I am going to sleep I always want to have the maximum collateral just in case some drastic crash happens.

This would help reduce margin calls because it would lower the margin call price for users who don't know they can enter more collateral than the 5% precision slider allows.

The only issue I see with this is having some BTS left over for fees. Maybe the maximum could actually be slightly less than the maximum, leaving only enough BTS to match the current price for collateral adjustment so that the user can unlock their BTS at a later date. We can't have the user stuck with locked up collateral and no fees to unlock it.

**Comment by wmbutler** [comment]
Useful and an easy win.

**Comment by landry314** [comment]
What I always do is truncate the collateral to the nearest whole number. This almost always leaves enough for fees. Having the collateral as a whole number looks nicer in the dashboard too. I suggest truncating the number like so unless it is too close to the nearest whole number below it then we could truncate it to the next whole number 1 BTS lower...

**Comment by wmbutler** [comment]
I was just thinking of a button that said "Maximize Collateral".

**Comment by wmbutler** [comment]
Suprised nobody has claimed this easy issue. Moving to next Sprint.

**Comment by pnomolos** [comment]
@wmbutler I can do this.  Should it use 95% of the available BTS currently in the active account (to leave some for fees)?

**Comment by wmbutler** [comment]
Maybe (max - 10) bts?

**Comment by pnomolos** [comment]
Perfect, I'll do that.

**Comment by wmbutler** [comment]
I've already used this feature several times.

**Comment by pnomolos** [comment]
Glad to hear it’s been useful already!
