### ISSUE TITLE
Make faucet default to API node provider for desktop client to incentivize operation of public API nodes

### ISSUE THREAD

**Issue by Ashaman-** [bitshares/bitshares-ui#902]
I currently run my own node for myself and a few friends. I'm interested in adding some redundancy to maximize my uptime and opening it up to the public + becoming a webwallet provider/registrar+faucet, however due to the effort involved in ensuring uptime and high hardware requirements (LOTS of RAM) of running a public API node I would like to see it generate some sort of revenue to offset (and hopefully eventually cover) its operational cost. 
If the default faucet sets itself to the API node that the desktop wallet automatically selects (assuming the API node is also a registrar and has a running faucet), it would incentivize the operation of public API nodes  - which are an essential component of our ecosystem.

**Comment by landry314** [comment]
Definitely! There are not enough nodes and the latency is too low in so many places in the world. I travel a lot and I can attest we need to incentivize more nodes for bitshares to really grow. It is an important next step!

**Comment by btsfav** [comment]
Impossible. Public nodes should be offered by paid witnesses or the infrastructure worker.

Wallets and affiliates rely on sign ups too

**Comment by Ashaman-** [comment]
Just read over the infrastructure worker. That makes more sense for funding public API nodes.
