### ISSUE TITLE
[15] Swap Old Charting or TradingView

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#905]
yes, javascript can be found here https://github.com/oxarbitrage/open-explorer/tree/master/app/charting_library

the code to call chart is at https://github.com/oxarbitrage/open-explorer/blob/master/app/sections/markets/markets.controller.js#L244-L261

includes:
https://github.com/oxarbitrage/open-explorer/blob/master/app/index.html#L78-L79

oxarbitrage/open-explorer
open-explorer - Bitshares open explorer

and udf server is needed: https://github.com/oxarbitrage/udf-bitshares-wrapper (this is python, not js) can use public udf node( http://23.94.69.140:5001/)

oxarbitrage/udf-bitshares-wrapper
udf-bitshares-wrapper - Tradingview UDF server for bitshares.

**Comment by wmbutler** [comment]
@svk31 I moved this to the next Sprint. You can move back if you think it's going to happen, but I assumed it was a big job.

**Comment by wmbutler** [comment]
Bump. Somebody want to work on this?

**Comment by sschiessl-bcp** [comment]
Would it be possible to enforce this @wmbutler ? Not everything should be on a volunteer pick what you like basis.

**Comment by clockworkgr** [comment]
Is the UDF server a requirement? or does it simply make things "easier" in terms of calls and packaging the data for the TV library?

**Comment by clockworkgr** [comment]
I also second stefan's suggestion to somehow force-assign this if possible. It's been on hold too long.

**Comment by svk31** [comment]
The UDF server is a requirement. I'll try to get started on this today or tomorrow.

**Comment by svk31** [comment]
So after gaining access to the Tradingview private repo docs I've learnt that the UDF server is not a requirement at all, in fact it's not recommended for use cases requiring real-time updates of data which is exactly our use case.

The Tradingview library offers a JS API that can be used to interface with any data input, so that's what we need to use. The documentation is not great but I intend to go forward with implementing it using the JS API and not the UDF wrapper.

**Comment by wmbutler** [comment]
@svk31 I think that's better because we won't have to rely on another level of abstraction.

**Comment by smogm** [comment]
Just switched to the 905-tradingview branch and it is just great! **Very nice work!**
**It looks so much better than the previous charts!**
Nice to see that progress, now it's simply some UI finetuning (e.g. enable drawing tools and maybe extend the height of the widget).

**Comment by smogm** [comment]
This issue is resolved and can be closed?

**Comment by wmbutler** [comment]
Yes, but it's not fully styled yet. Closing since we have another issue to complete the styling.
