### ISSUE TITLE
Missing dashboard displays

### ISSUE THREAD

**Issue by EdwardTatch** [bitshares/bitshares-ui#907]
Hello,

I was playing with the ui, following https://steemit.com/bitshares/@cm-steem/bitshares-ui-customization-guide

But for some reason, dashboard doesn't display my selected pair with logos, I followed everything from the tuto but it's seems like for some pairs it works (BTS:SILVER, USD:SILVER) but for some reason some do not (EUR:SILVER, etc).

Not sure why and at this point I have look everywhere to find an answer but without luck
<img width="1501" alt="capture d ecran 2017-12-25 a 17 08 23" src="https://user-images.githubusercontent.com/34829200/34341545-ba1f4b8c-e999-11e7-837f-5b3a4010bcbe.png">
<img width="1430" alt="capture d ecran 2017-12-25 a 17 09 37" src="https://user-images.githubusercontent.com/34829200/34341546-ba375056-e999-11e7-8123-45e39ca5839b.png">

If anyone could help me out, would be much appreciated, merry christmas !

**Comment by wmbutler** [comment]
Sorry, we don't really have anything to do with that guide. You should contact the creator.
