### ISSUE TITLE
Implement notification/warning for accounts with <1BTS

### ISSUE THREAD

**Issue by diogogomes** [bitshares/bitshares-ui#909]
### Use case 1

- Alice want to start using BitShares DEX, so Alice creates an account. :white_check_mark:
- Alice needs funds, so Alice makes the first deposit on the DEX (ex: Open.XX) :white_check_mark:
- Alice needs to pay the fees, so Alice makes a trade OPEN.XX / BTS :red_circle:

**How Alice buy BTS with her funds if she doesn't have BTS for the fees?**

@wmbutler on Telegram:
"Get Alice to buy some bts through the buy option in the portfolio as a first step."

Only possible using BlockTrades service.

#### Suggestion

Add a notification/warning for accounts <1BTS. Something like `Your account is without enough BitShares to use all features of this wallet. Please buy some BitShares.`

---

### Use case 2

- Bob want to sell all BTS for OPEN.XX, so Bob creates an order and pays the fees. :white_check_mark:
- Bob want to buy BTS again, so Bob creates an order and pays the fees. :red_circle:

**How Bob buy BTS with his funds if he doesn't have BTS for the fees?**

Possible step
Bob needs to buy some BitShares through the buy option in the portfolio.

Only possible using BlockTrades service.

#### Suggestion

Add a notification/warning when an order will drain all BTS funds or the balance will be <1BTS after the order. Something like `Your account will be without enough BitShares to use all features of this wallet. Please buy some BitShares.`

**Comment by wmbutler** [comment]
@diogogomes Fees will come out of OPEN.BTC in your USE case 1. Openledger keeps a pool of reserve funds for this purpose. Same for case 2

**Comment by HarukaMa** [comment]
There may be a situation where you are only owning some asset which has empty fee pool. Very edge though. Also paying through assets instead of core token is more expensive by design.

**Comment by wmbutler** [comment]
The solution to that is to notify the fee pool owner to add to it. I don't think this edge case is worth the effort, really.

**Comment by diogogomes** [comment]
Lately I have seen new users in the telegram and discord with the error `insufficient bitshares`. That's why I opened this issue.

**I would prefer that the tag be _feature_ instead of _question_.**

Regarding Open.XX was an example. If you prefer, I can create new user cases without the gateway.

**My suggestion is to implement a notification whenever the BitShares level gets too low.**

_(This issue may be low priority)_

**Comment by wmbutler** [comment]
I think what we are looking for is a more succinct and readable error message. How about.

`Insufficient BTS balance to cover fees`

**Comment by diogogomes** [comment]
`Insufficient BTS balance to cover fees ` sounds okay.

It would also be nice to have a notification to prevent these situations.

**Comment by wmbutler** [comment]
We already have this on most screens. We disable the action buttons in cases where a trade cannot be completed.

**Comment by diogogomes** [comment]
I'm talking about this prevent situations like Use Case 2

If Bob sells all BitShares, he will be without BitShares to use the DEX and his account will be freeze.

_Note: I'm seeing a grow of users on Reddit with stuck accounts_

Issue #977: Maybe if the user can always pay fees with other asset this use case can be resolved.

**Comment by wmbutler** [comment]
@diogogomes I think implementing #977 is a good first step. If we still have issues after that, we can look to this solution.

**Comment by diogogomes** [comment]
I agree
