### ISSUE TITLE
[3][Kennybll] Implement Help Area UX Styleguide

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#911]
See #759 for details.

**Comment by Kennybll** [comment]
I can do this!

**Comment by wmbutler** [comment]
Great. Can you finish it by Jan 4?

**Comment by Kennybll** [comment]
Yeah, as long is you like the PR...

**Comment by wmbutler** [comment]
Great. Finishing on 1/4 will allow us time to test and provide feedback.

**Comment by wmbutler** [comment]
@Kennybll you didn't really match this UX very well in my opinion. I've included a screenshot of each for your comparison.

## Style Guide UX

![screen shot 2018-01-03 at 12 48 55 am](https://user-images.githubusercontent.com/1254810/34511291-09b72f2a-f020-11e7-8156-be21df094218.png)

## Your Work

![screen shot 2018-01-03 at 12 49 07 am](https://user-images.githubusercontent.com/1254810/34511297-136c05d6-f020-11e7-9fa7-98ff27d539fa.png)

**Comment by Kennybll** [comment]
Okay I worked on it a bit more... though I think changing the markdown should be in another Issue and PR because we have different languages that would need to be changed around. @wmbutler

**Comment by wmbutler** [comment]
I'm not suggesting changing the markdown. This issue is about making the style presented in the UX visible in the application.

**Comment by Kennybll** [comment]
![image](https://user-images.githubusercontent.com/14302151/34580512-50288d1e-f15b-11e7-9077-1d62ea3fd452.png)

![image](https://user-images.githubusercontent.com/14302151/34580554-6d255244-f15b-11e7-87bf-abdeebe49547.png)

**Comment by wmbutler** [comment]
Nice

**Comment by Kennybll** [comment]
I couldn't get rid of scrollbar like in the style guide. The style guides also has a slight border around the content, but with the scrollbar it looks weird.

**Comment by wmbutler** [comment]
You should be able to set `scroll=auto`.

**Comment by Kennybll** [comment]
@wmbutler It is. I'm just saying if someone has a short screen, then the long list of pages will overflow, and to see the whole thing that have to scroll. That light border I was talking about would look nice when the screen height over larger than the height of the help nav menu. But if it's too short it would look like:
![image](https://user-images.githubusercontent.com/14302151/34592940-9c2124b2-f195-11e7-93b5-869b3e48fd26.png)
Which doesn't look too nice, at least to me. Otherwise everything is fine.

**Comment by Kennybll** [comment]
@svk31 Are you needing someone to take over for your steem witness?

**Comment by wmbutler** [comment]
This area is not for general conversations.

**Comment by wmbutler** [comment]
please provide your bts address for payment

**Comment by Kennybll** [comment]
kennybll-accnt
