### ISSUE TITLE
Price chart must be cleaned from buggly candlesticks of small amount trades

### ISSUE THREAD

**Issue by rPman** [bitshares/bitshares-ui#915]
When amount of exchange order too small, for example 0.0006cny/0.0001usd, price of this calculated not as expected and can be executed not in time (for example current market price 0.14676 but this small order calculated as 0.16667).

It makes wrong charts and used for malicious manipulation and just hinders.

This trash data must be cleared before generating price chart.

![image](https://user-images.githubusercontent.com/938140/34366590-d6e2b568-eaae-11e7-9777-30b1bb8e1047.png)
all of this up/down candles are bug trades.

**Comment by wmbutler** [comment]
This bug fix is already in progress and is part of #361
