### ISSUE TITLE
[2] Cannot download bin file from bitshares.org/wallet

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#916]
## Problem Statement
User navigates to https://bitshares.org/wallet. Site correctly indicates that a .bin file is available to download. User clicks download but no action occurred. User was competent and I trust that this was the case.

## Request
If you still have a local wallet at bitshares.org/wallet, please attempt the same download procedure and post a licecap if successful. If you verify the issue, please resolve the download problem.

**Comment by btsfav** [comment]
yep, doesn't work:

`INFO	browserEntropy gathered
app.js:12 Uncaught TypeError: Cannot read property 'toUncompressed' of null
    at t.get_shared_secret (https://bitshares.org/wallet/app.js:12:231179)
    at Function.t.encrypt_with_checksum (https://bitshares.org/wallet/app.js:26:48728)
    at https://bitshares.org/wallet/app.js:26:125237
    at i (https://bitshares.org/wallet/app.js:59:1091513)
    at e.exports (https://bitshares.org/wallet/app.js:31:46410)
    at y.(anonymous function) (https://bitshares.org/wallet/app.js:12:342099)
    at Number.b (https://bitshares.org/wallet/app.js:12:341957)
    at MessagePort.v (https://bitshares.org/wallet/app.js:12:341979)`

**Comment by wmbutler** [comment]
@svk31 this is a serious problem and needs to be addressed with a hotfix as soon as you are able. Or if any other devs can get to this first. I'm increasing the bounty to get it out the door.

**Comment by HarukaMa** [comment]
The wallet on https://bitshares.org/wallet is not connecting to any API nodes as it is running in deprecated mode, so it cannot get current running chain config, thus public key prefix defaulted to `GPH`. Pubkeys inside the wallet uses `BTS` as prefix, so they are not being read. I'm able to reproduce it using `build-github` script.

A possible one-shot temporary modification: Edit `node_modules/bitsharesjs-ws/cjs/src/ChainConfig.js`, and change `GPH` on line 12 to `BTS`. Works when tested locally, but it's kinda hacky though. Or do you need a better fix (still connect to API nodes even in deprecated mode)?

**Comment by wmbutler** [comment]
Just making sure you are seeing this @svk31

**Comment by svk31** [comment]
I'd already hard-coded the chainid for the database initialization, but I missed the use of ChainConfig directly in the backup component, nice catch @HarukaMa
