### ISSUE TITLE
[2] First Welcome Screen for wallet.bitshares.org

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#917]
## Current Layout

- bitshares logo is duplicated
- Create Account is duplicated
- Setting menu can be hidden in hamburger on right

![screen shot 2017-12-26 at 8 51 14 pm](https://user-images.githubusercontent.com/1254810/34369064-88cf31ce-ea7e-11e7-86f9-51d41da10807.png)

![register](https://user-images.githubusercontent.com/1254810/34369263-03275676-ea80-11e7-87ef-585e20d14925.gif)

## Proposed Layout

- Since we already have a logo in the header, let's just use that position in the Welcome screen. This will allow us to keep the logo consistently in the app regardless of which screen we are on.
- The language selector is happening in another issue.
- The hamburger will be a hierarchical menu of everything but for this, we need to be able to access at least: settings.
- [ ] Remove Create Account from top right

![screen shot 2017-12-26 at 9 02 59 pm](https://user-images.githubusercontent.com/1254810/34369285-35da7f26-ea80-11e7-9b05-3131fe19bb76.png)

You can see by doing this that the Welcome screen to the Login screen will flow smoothly.

**Comment by Xeldal** [comment]
Later, with the proposed feature #895 Both options at the bottom, "RESTORE" and "ADVANCED",  become unnecessary / redundant .

**RESTORE** is the same as providing your key-file (backup) which will be done from the proposed login screen.

**ADVANCED** option is just creating a key-file (backup), which can be done with all accounts after creation.  The other options in Advanced "Restore from backup" and Restore from brain-key" are also handled on the proposed login screen.

All use of the words "Local Wallet" and "Cloud Wallet" will also be unnecessary.

Question is, do we want users to be able to create a key-file (backup) without the account having a master-password? If so, why?  OR just have every new account create a master-password and every account can then download their key-file (backup) if desired.

The only reason I can come up with for not wanting a Master-Password is to avoid lessening the security of the account via brute force against the Master-Password.  However, with a sufficiently long Master-Password the security should be identical to an attack against the Private-Keys themselves. 

Until #895 is implemented, obviously these suggestions are not relevant.

**Comment by wmbutler** [comment]
@Xeldal this issue isn't about "restore / advanced" or the keyfile discussion. This issue is related to what the initial screen looks like on devices.

**Comment by Xeldal** [comment]
@wmbutler  Yes, I know what its about.    

Given that both Restore and Advanced are options **displayed on this welcome screen.**  It's relevant to discuss their inclusion, is it not?

You wouldn't want to display them if you were also planning the linked proposed feature.  
#895 

The moved comment now makes little sense in the other thread.

**Comment by wmbutler** [comment]
No, this issue is just about how the welcome screen should be presented as a single canvas.

**Comment by Xeldal** [comment]
So when you selectively add / remove element to the screen this is called "presenting as a single canvas"
and when I suggest to add / remove elements to the screen it's called beyond the scope of the issue. 

Got it.  Thanks.
