### ISSUE TITLE
[.5][startailcoon] Witness list page timezone issue

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares-ui#919]
On https://wallet.bitshares.org/#/explorer/witnesses, I guess the `Next vote update` field ignored timezone.

**Comment by HarukaMa** [comment]
Settlement order list is affected by this too.

**Comment by startailcoon** [comment]
### Both issues fixed

![bitshares-timezoneissues](https://user-images.githubusercontent.com/12114550/34432746-894cf5a2-ec7a-11e7-97b4-a1b4eb7e2f4a.gif)
