### ISSUE TITLE
Separate region to show margin call orders in Exchange

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#920]
Another solution to #877 .

Currently the margin call orders are consolidated in the order book, but they are in fact separately evaluated and executed, each one having different call limit price and margin call price. Putting them together would eliminate many useful information, like if they would cascade triggered or not.

If possible, they could be put into a separate box, listing every order / margin position's call price and size, like settlement orders.

However, showing them in the order book is still needed as they could be bought in specific situations. When they are not buyable they could hide from the order book as there are already a list to see them.

Credits to  @ fav for the idea.

**Comment by landry314** [comment]
There is a Settlement window so why not add margin calls there too until they are buyable then move them to the order book?

The unbuyable margin call order in the order book messes up the total column calculations and "lowest ask" feature... removing the unbuyable orders from there will immediately fix this. Settlements and Margin Calls are both orders about to execute under certain circumstances.

**Comment by wmbutler** [comment]
Moved to 180601. Need someone else to estimate.

**Comment by abitmore** [comment]
@wmbutler I'd rather label it "wont fix".
