### ISSUE TITLE
[1][HarukaMa] Margin Positions Tab views Incorrect Call Price 

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#921]
Small issue, but the `Price` column shows the current `Last Price` rather than the current `Call Price` that is the current `Settlment Price` +/- the offset (if I'm not wrong).

![image](https://user-images.githubusercontent.com/12114550/34422493-2d129ad0-ec16-11e7-91a8-170991140d5c.png)

![image](https://user-images.githubusercontent.com/12114550/34422520-4a3df4e2-ec16-11e7-94f9-e6ddd51a8e56.png)

**Comment by HarukaMa** [comment]
Did you mean "price" column instead of "call price"? "call price" is correctly calculated.

**Comment by startailcoon** [comment]
Yes, I did :)

**Comment by HarukaMa** [comment]
PR is at #954.

**Comment by wmbutler** [comment]
Please officially claim items before submitting PR's. Thanks for the PR!
