### ISSUE TITLE
[.5] Failed Withdrawals due to missing gate fee

### ISSUE THREAD

**Issue by DBCerigo** [bitshares/bitshares-ui#926]
Hi,

I'm trying to withdraw BTS from my openledger account to an ETH address. I'm doing so via the TRADE.X bridge. When I hit "WITHDRAW NOW" I get the popup showing me the fee and letting me input the ETH address, but when I hit "WITHDRAW" on this popup nothing happens. I checked the console and the app is throwing an error:
```
Uncaught TypeError: String.prototype.replace called on null or undefined
    at WithdrawModalBlocktrades.onSubmit (app.js:101050)
    at Object.invokeGuardedCallback (app.js:61847)
    at executeDispatch (app.js:61677)
    at Object.executeDispatchesInOrder (app.js:61697)
    at executeDispatchesAndRelease (app.js:45539)
    at executeDispatchesAndReleaseTopLevel (app.js:45550)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (app.js:79013)
    at Object.processEventQueue (app.js:45750)
    at runEventQueueInBatch (app.js:119420)
```

The line in which it throws is `var gateFee = parseFloat(String.prototype.replace.call(this.props.gateFee, /,/g, ""));`

I'm using Chrome on OSX

Hope you can help with a workaround as this understandable time urgent. 

Thanks

**Comment by DBCerigo** [comment]
Could be related to #777 and #588

**Comment by DBCerigo** [comment]
How should one get BTS from their OpenLedger account to other coins/tokens then?
Thanks

**Comment by wmbutler** [comment]
TRADE.X is not openledger. OPEN.X is.

**Comment by startailcoon** [comment]
There's no TRADE.X bridge in the current version. Are you using the latest version?

**Comment by DBCerigo** [comment]
In the end I traded to open.ETH and then used the gateway, so issue closed from me. 

I was using the web openledger.

Feel free to close now - though it's still a case of withdraw button throwing error and now message given to user so might want to fix. 

Thanks

**Comment by svk31** [comment]
This was already fixed here: https://github.com/bitshares/bitshares-ui/issues/765
