### ISSUE TITLE
[0.5] Market Link Error on Dashboard

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#927]
#### When a market is switched the icon for the market on the Dashboard appears to be invalid.

1. Load the Dashboard from a fresh instance
2. Go to the tab for `Open Orders` or `Margin Trading`
3. Click on the market icon without switching the market direction
4. Everything works

--- 
1. Go to the Dashboard again
2. Go to the tab for `Open Orders` or `Margin Trading`
3. Switch market direction, then click on the market icon.
4. Results in the following error

![image](https://user-images.githubusercontent.com/12114550/34449391-cb3e62d4-ecf7-11e7-8fd9-dbc6a1e7c016.png)

**Comment by wmbutler** [comment]
Nice catch.

**Comment by pnomolos** [comment]
I'll call this, and have a PR ready to go - just need verification that the style looks good :)

**Comment by wmbutler** [comment]
Please have this ready by Jan 04, 2018 if you intend to work it. This is a pretty important issue to resolve.

**Comment by pnomolos** [comment]
@wmbutler PR is in #933 👍  😄
