### ISSUE TITLE
Possibly Adding Ant Design

### ISSUE THREAD

**Issue by Kennybll** [bitshares/bitshares-ui#928]
So I've been looking at the design and I think it would be beneficial to use a library. I came from helping on busy.org who uses [Ant Design](https://ant.design/) for their UI. It looks nice and it could maybe work for this too. I see you guys are making changes to the UI as seen in Github issues.

Maybe we should look into Ant Design. It has ready to go components with lots of options. Customizable themes, and it's made for React. It even comes with autocomplete features that could help with issue #893 .

If this could be considered, I'm willing to work on the migration.

**Comment by wmbutler** [comment]
hrmmm, maybe at a later date. At this point, we are making incremental changes to the UI and I'm not sure if it's such a good idea to add yet another layer of abstraction.
