### ISSUE TITLE
[.5][Kennybll] Change triangle to burger in preparation for hierarchical right menu

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#929]
![screen shot 2017-12-30 at 4 40 53 pm](https://user-images.githubusercontent.com/1254810/34457751-52a845a4-ed80-11e7-82db-6e67d475ec9e.png)

**Comment by Kennybll** [comment]
I could do this!

**Comment by Kennybll** [comment]
@svk31 quick question do I get paid, and if so how much...
