### ISSUE TITLE
TROLLBOX link to bitshares.org and telegram

### ISSUE THREAD

**Issue by iPerky** [bitshares/bitshares-ui#93]
Could we add the light wallet trollbox to https://bitshares.org/
and possibly link to telegram https://t.me/BitSharesDEX

**Comment by wmbutler** [comment]
I'd suggest removing the trollbox entirely.

**Comment by happyconcepts** [comment]
I would suggest keeping the trollbox but Bill is hell bent to remove it.

**Comment by iPerky** [comment]
Why remove something that is easily disabled by shareholders

**Comment by wmbutler** [comment]
Because it is external JavaScript in a financial application. A serious financial app doesn't need it in my opinion. Risking security to watch anonymous trolls doesn't scream professionalism to me.

**Comment by wmbutler** [comment]
This is usually what the activity looks like on the trollbox.

![screen shot 2017-07-30 at 10 14 36 pm](https://user-images.githubusercontent.com/1254810/28761522-c72bf5b2-7574-11e7-9199-354f774a83c1.png)

**Comment by iPerky** [comment]
Scream professionalism, I like!

Ok drop The troll box
