### ISSUE TITLE
Unable to verify to withdraw fiat currency

### ISSUE THREAD

**Issue by chrisciszak** [bitshares/bitshares-ui#930]
The link in 'Click _here_ to register for deposits of USD' take me to unavailable OpenLedger page https://openledger.info/v/

**Comment by startailcoon** [comment]
This repository is for issues with the BitShares Wallet. For issues with a gateway like Open Ledger, please contact them directly on their own platforms. 

Open Ledger Support: https://openledger.freshdesk.com
Telegram: https://t.me/OpenLedgerDC

**Comment by chrisciszak** [comment]
Dont you think that you should also address it in your application? The
integration seems to be broken. I've never seen a serious app linking to a
non existing website.

If your integration with Open Ledger is not working, you should remove it
from the BitShares as it's confusing and doesn't look professional.

**Comment by wmbutler** [comment]
@chrisciszak what is is supposed to link to? Happy to add it, or you can issue a PR.
