### ISSUE TITLE
[1] orders disappear

### ISSUE THREAD

**Issue by bitcrab** [bitshares/bitshares-ui#932]
now in GDEX.BTO/bitCNY pair, only below buy orders appear in the latest GUI:

![bto1](https://user-images.githubusercontent.com/5886543/34459177-1a1ec778-ee23-11e7-9300-02964deb29cd.jpg)

but actually there are much more buy orders there which we can see in magicwallet:
![image](https://user-images.githubusercontent.com/5886543/34459182-4bbf0de2-ee23-11e7-8a4a-98b3bb45d436.png)

these orders also need to be shown in GUI, right?

**Comment by dot5enko** [comment]
they are in the gui. orders with same price are grouped (first on dex and two in app)

**Comment by bitcrab** [comment]
no, orders with price below 222300 are shown in magicwallet but not in GUI

**Comment by svk31** [comment]
Unable to reproduce but I think I know why. There's a filter in the GUI that removes orders that are very far from the market price, which was the case of your missing orders. I'll just remove that filter since I don't think it's needed anymore.
