### ISSUE TITLE
[8][ahdigital] Hierarchical Right Menu

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#935]
This menu can accommodate every cascading level of the Bitshares Wallet feature set in a logical way. This has been discussed in a PR, but I think it needs and issue to itself with a dedicated effort. Ideally, as the application moves towards smaller screens, the various levels will collapse into this unified right menu under the account name and the burger:

![screen shot 2017-12-18 at 9 12 53 pm](https://user-images.githubusercontent.com/1254810/34139068-43d6f94a-e438-11e7-8dbc-c1a2dce8f785.png)

The active screen would only show the currently selected level of Hierarchy in the header when the screen is sufficiently small. In this case, we are in Dashboard --> Portfolio, but we only see Portfolio displayed in the header:

![screen shot 2017-12-31 at 10 43 41 am](https://user-images.githubusercontent.com/1254810/34463088-a6dd01b8-ee17-11e7-9246-3324f293a724.png)

https://tympanus.net/Development/MultiLevelPushMenu/index2.html

See demo 2 which includes backlinks.

This framework, **but handled from the right side**, might work well with hierarchies defined:

- Dashboard
  - Portfolio
  - Open Orders
  - Margin Positions
  - Activity
- Send
- Deposit
- Withdraw
- Settings
  - General
  - Local Wallet
  - Accounts
  - Password
  - Backup
  - Restore
  - Access
  - Faucet
- News
- Help
- Exchange
- Explore
  - Blockchain
  - Assets
  - Accounts
  - Witnesses
  - Committee
  - Markets
  - Fees
- Advanced
  - Voting
    - Witnesses
    - Committee
    - Workers
  - Assets
  - Signed Messages
    - Sign Message
    - Verify Message
  - Vesting Balances
  - Whitelist
    - Whitelist
    - Blacklist
    - Whitelisted By
    - Blacklisted By
  - Permissions
    - Active Permissions
    - Owner Permissions
    - Memo Key
    - Cloud Wallet
- Accounts
  - Accounts
  - Contacts
  - Recent Activity
- account 1
- account 2
- account 3 etc..

**Comment by Kennybll** [comment]
I can work on this.

**Comment by startailcoon** [comment]
I'll have this worked on

**Comment by startailcoon** [comment]
#904 introduced a new sub-menu system. Should this new one be used or are we still replacing with the proposed one by OP?

**Comment by gibbsfromncis** [comment]
@startailcoon I would like recommend you to use this one - https://tympanus.net/Development/MultiLevelPushMenu/index2.html

It has cool animations and looks more scaleable.

**Comment by startailcoon** [comment]
Then it's set and I will work on implementing a new one.

Just wanted to make sure we don't do work we already have fixed.

**Comment by startailcoon** [comment]
Then it's set and I will work on implementing a new one.

Just wanted to make sure we don't do work we already have fixed.

**Comment by gibbsfromncis** [comment]
@startailcoon actually we do. But I guess it's better to take good library and just use it

**Comment by wmbutler** [comment]
That's the same library I recommended at the top of this issue....great minds think alike :)

**Comment by startailcoon** [comment]
I've released this task due to I'm to unexperienced with mixing in new JS code with React. Feel free to claim this for the next milestone.

Some hints on other users cases can be read at https://github.com/codrops/MultiLevelPushMenu/issues/11

**Comment by ahdigital** [comment]
I would like to have a crack at this please.

**Comment by gibbsfromncis** [comment]
@wmbutler can I take it?

**Comment by ahdigital** [comment]
I have made a start on this. I thought @wmbutler assigned me already but looks like it was @startailcoon. Lack on detail on github mobile site..

**Comment by startailcoon** [comment]
I did assign ahdigital yes, as requested and notified on telegram

**Comment by gibbsfromncis** [comment]
@startailcoon do you have dev chat on telegram? Can you invite me?

**Comment by startailcoon** [comment]
What's your Telegram handle so we can invite you to the group please?

**Comment by gibbsfromncis** [comment]
@startailcoon username is "gibbsfromncis" like on Github.

**Comment by diogogomes** [comment]
@startailcoon Sorry to ask this here, on Github, but can you add me too (diogogomes)?
I'm already in the DEV group but I think I can be more useful in the UI group. Thank you

**Comment by wmbutler** [comment]
@diogogomes I added you

**Comment by wmbutler** [comment]
@ahdigital closing this. Do you want to open separate issues for UX on this since we are going to ANT?
