### ISSUE TITLE
[2.5] UI freeze if all nodes are not connectable before timeout

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#937]
Telegram user reports: on poor network conditions, when starting the client, if the wallet fails to connect to every node before timeout, instead of trying again, it would trigger a infinite loop, consuming the whole CPU core and freezing the whole wallet / browser tab.

**Comment by startailcoon** [comment]
Could this be related to the latency checker that is done on start?

**Comment by lbn349** [comment]
Hi i was reporting this to HarukaMa. About 50% of the time it eventualy finds a node to connect to. 


Heres a screenshot of wat devtools does wen it freezes (notice the warning number top right reaches 10,000+ warnings , so it does a javascript loop/memory leak: 
![bitshares2](https://user-images.githubusercontent.com/35014105/34471635-89bd844e-ef1c-11e7-9806-12167adf4e7f.png)

and heres a screenshot of it  eventualy finding a node / working 50% of the time

![bitshares](https://user-images.githubusercontent.com/35014105/34471645-a53c6348-ef1c-11e7-9c47-aa5d1e77cfcd.png)


its some javascript loop firing off the warnings that makes it freeze wen it doesnt connect to nodes. Windows . thx

**Comment by lbn349** [comment]
also, it should have longer timeout for weak wifi connections thru vpn

**Comment by HarukaMa** [comment]
I think I found the reason, now trying to fix it.

**Comment by wmbutler** [comment]
Not sure how to proceed. Are you claiming this? Linking a PR to it?

**Comment by HarukaMa** [comment]
I'm not claiming this as I've hit a dead end here. PR should be another closely related issue, but won't resolve this altogether.

**Comment by zhyupe** [comment]
Did some research and found out this issue may be related to ReconnectingWebSocket reqired by bitsharesjs-ws.
This issue also occurs in web version, but seems won't be triggered in the development environment. 

*Note*: The words beyond is not conclusion, still need time to figure out the reason.

**Comment by zhyupe** [comment]
Claimed. Commit and explains on the way.

**Comment by zhyupe** [comment]
There are two causes in this issue:
1. `willTransitionTo` includes codes specially for `/init-error`, and uses an error handler `onResetError` which call `willTransitionTo` recursively, causing infinite loop in certain condition. 
2. Somehow the websockets created by the code described above are manually closed shortly after created and produce errors which are caught by `onResetError`.

As I can't figure out the reason for cause 2, I removed the code in the fix. Therefore, it can render the page of `init-error` and avoid the infinite loop. In addition, I think this is the correct behaviour. (Current behaviour is weird ... it won't let you choose the node until it connects to someone, when manually choosing isn't really necessary)

**Comment by wmbutler** [comment]
@svk31 will need your input on this.

**Comment by xmr-karnal** [comment]
Could this be the same issue as #1051 ?
