### ISSUE TITLE
[.25][zhyupe] QR code background color should be white

### ISSUE THREAD

**Issue by xiangxn** [bitshares/bitshares-ui#938]
QR code background color should be white, otherwise it will affect the recognition success rate, especially in the identification of pure js.

**Comment by startailcoon** [comment]
Please specify in what places it is not white, and we will make sure it is.

**Comment by xiangxn** [comment]
the QR code in Private key viewer

**Comment by zhyupe** [comment]
I'd like to claim this issue.

**Comment by wmbutler** [comment]
Please provide your bts address for payment
