### ISSUE TITLE
Market Buy/Sell orderbook not updating to include users new orders

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#939]
This needs to be looked into a bit, but there's clearly something not updating as expected.
When I create new orders they aren't visible in the order book unless I manually refresh the market.

I assume it needs to include checking to refresh data when users orders are changing.

### I just created these orders
![image](https://user-images.githubusercontent.com/12114550/34469172-4abb44dc-ef19-11e7-84db-2b1217fbb001.png)

### The order book is only showing my original order 
![image](https://user-images.githubusercontent.com/12114550/34469176-5a7ac8a2-ef19-11e7-9e93-298bf519d768.png)

### After reloading the market manually (CTRL+R) the orders are visible
![image](https://user-images.githubusercontent.com/12114550/34469186-704a2bbe-ef19-11e7-8a3d-4d5de8549451.png)

**Comment by btsfav** [comment]
sounds like a bad node

**Comment by svk31** [comment]
This is very surprising, the API node should notify you of new orders regardless of whether they belong to you or not, and I've never seen any issues like this before (meaning the orderbook has always stayed in sync for me)

**Comment by startailcoon** [comment]
It may very well have been a bad node. Today this works as it should. Not really sure what happened here. I should have taken some more logs when this happened.
