### ISSUE TITLE
[alexandrty] Openledger get-last-address returns memo as address for Steem

### ISSUE THREAD

**Issue by svk31** [bitshares/bitshares-ui#941]
Request URL:https://ol-api1.openledger.info/api/v0/ol/support/simple-api/get-last-address

![image](https://user-images.githubusercontent.com/6890015/34489545-0ea5b120-efdd-11e7-8420-5cfc23a3393f.png)

{"address":"pqpfdr-d940-qsj99ue6-5dwrq16e"}

This should return an address and a memo

**Comment by wmbutler** [comment]
@svk31 Did you notify OpenLedger?

**Comment by svk31** [comment]
Yes

**Comment by grctest** [comment]
I too experienced this on openledger today :(

**Comment by alexandrty** [comment]
OpenLedger fixed problem

**Comment by svk31** [comment]
Looks to have been fixed indeed, thanks @alexandrty
