### ISSUE TITLE
change of deposit address without intention

### ISSUE THREAD

**Issue by wolfpirker** [bitshares/bitshares-ui#943]
The issue I report here occurs in Basic Mode with Open.WAVES deposits; I tested it on bitshares.openledger.info. 
I only checked Open.LTC and Open.Waves, not sure if there is any other assets where there is this issue - with LTC I couldn't reproduce the issue.

If a Waves deposit address is created, and the deposit address dialog is opened again after more than 5 minutes, the deposit address is changed. I think the deposit address should only be changed if the "Get new Address" button is clicked. Due to this bug, people could send coins to the wrong address.

**Comment by wmbutler** [comment]
Please test at wallet.bitshares.org. If it occurs there, we will address it.

**Comment by startailcoon** [comment]
All I know is that we agreed on, when building the new Buy Modal, to regenerated new addresses upon opening the modal. 

https://github.com/bitshares/bitshares-ui/issues/651#issuecomment-342907487
>  Remove the "Get new address button". This can be triggered when the modal is first opened instead.

If this is the reason for it, I do not know though.

> Due to this bug, people could send coins to the wrong address.

Aren't all addresses always generated to be tied to the same user? If I generate a new address, every old address I've sent to before should still be valid, as far as I know how things works. But I'm not sure about these exchanges.

**Comment by wolfpirker** [comment]
> Aren't all addresses always generated to be tied to the same user? If I generate a new address, every old address I've sent to before should still be valid, as far as I know how things works. But I'm not sure about these exchanges.

Actually I received the Waves I tried to deposit yesterday, 3 days later after I sent them. So your explanation is quite possible, that the previous address still belongs to me. Because of the huge delay I feared they are lost.

> Please test at wallet.bitshares.org.
I couldn't reproduce the issue there, I cannot find the Basic mode. At openledger a "Switch to Basic Mode" button is shown at the top header bar.

**Comment by HarukaMa** [comment]
> Actually I received the Waves I tried to deposit yesterday, 3 days later after I sent them. So your explanation is quite possible, that the previous address still belongs to me. Because of the huge delay I feared they are lost.

So this is not really a bug, it's just how OpenLedger works. I guess they actually contributed the code of that section. Just a guess.

>I couldn't reproduce the issue there, I cannot find the Basic mode. At openledger a "Switch to Basic Mode" button is shown at the top header bar.

It could be triggered if you already own open.BTC or somehow it shows up in portfolio, then clicking the deposit button on the right. Basic mode is now only used in OpenLedger AFAIK.

**Comment by wmbutler** [comment]
New deposit modals coming this month. Please test on the new modal and provide feedback. We will be retiring the old deposit screens.

**Comment by startailcoon** [comment]
Closing this since it's not an issue, rather a problem with OL
