### ISSUE TITLE
[1][pnomolos] Remove Send modal immediately after clicking confirmation

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#945]
After Accepting the confirmation modal, we should remove the send modal behind it. In cases where the node is slow to respond, this creates a very confusing situation for the user because the confirmation screen has gone away but the original send modal is still in place.

Upon clicking confirm:

- [ ] Close the original send modal
- [ ] Then close the confirm modal

![send](https://user-images.githubusercontent.com/1254810/34511444-4a4df2e8-f021-11e7-961b-1b124f1f914c.gif)

**Comment by pnomolos** [comment]
@wmbutler I'd like to claim this.

**Comment by pnomolos** [comment]
@wmbutler This may be a bit bigger than hoped - right now when you click "Confirm" on the confirmation dialog it's removed immediately - whether or not an error occurred (if an error occurred it's brought back up).  However, this means that it's going to be unnecessarily complicated to hook in at that point unless the "Send" dialog is always closed irrespective of the transaction succeeding or not.

**Comment by wmbutler** [comment]
@pnomolos If and error occurs, the user can re-open the send modal. I don't see a problem with this. I think the send modal should go away either way. The send modal handles the gathering of data for the confirmation modal.

**Comment by pnomolos** [comment]
OK, in thinking about it offline that probably makes sense anyway :)

**Comment by svk31** [comment]
I think we should just close the Send modal once the user clicks Send.. The confirmation modal will then show up and will close itself once done.

**Comment by wmbutler** [comment]
@svk31 my only argument against this is that the user may find something small wrong on the confirmation screen and wish to correct a single piece of information. If we close the send modal, they will have to fill in the entire form again rather than tweaking a single value.

**Comment by pnomolos** [comment]
Well thanks to the magic of git I can revert my revert commit, maybe push
this out a milestone until it’s decided? :)

**Comment by startailcoon** [comment]
What if we just toggle the visibility of the modal when the user goes to confirm modal, then we can "unhide" it if the user press cancel on the confirm modal?

**Comment by wmbutler** [comment]
> Well thanks to the magic of git I can revert my revert commit, maybe push
this out a milestone until it’s decided? :)

I moved it to 180115

> What if we just toggle the visibility of the modal when the user goes to confirm modal, then we can "unhide" it if the user press cancel on the confirm modal?

That would work too. It would actually look better without the additional overlap. Then the cancel button would toggle visibility back and a successful transaction would close it. What would a failed transaction do?

**Comment by pnomolos** [comment]
A failed transaction would carry on as it already does, I would think - it just brings the confirm modal back up with the error message.  At which point if you press close/cancel (forget which it is right now) you'd end up back at the Send modal?

**Comment by pnomolos** [comment]
I've pushed an update to the PR, it's _better_ (I think) but still not optimal as the Send dialog now pops up briefly before the "Transaction Successful" notification pops up.
