### ISSUE TITLE
Color problems of the right menu icon

### ISSUE THREAD

**Issue by zhyupe** [bitshares/bitshares-ui#949]
It currently looks like this:
![image](https://user-images.githubusercontent.com/2197479/34524114-448cd554-f0d5-11e7-8f3b-546cbe1482c1.png)

Which should be:
![image](https://user-images.githubusercontent.com/2197479/34524127-4c0d3580-f0d5-11e7-9736-49bd822757e0.png)

This problem can be even worse with light theme:
![image](https://user-images.githubusercontent.com/2197479/34524269-d39f334a-f0d5-11e7-892d-6161c499cabd.png)
![image](https://user-images.githubusercontent.com/2197479/34524280-e129c322-f0d5-11e7-8507-6f811680ff1b.png)

Which should be:
![image](https://user-images.githubusercontent.com/2197479/34524450-882552c2-f0d6-11e7-8c5f-1f0b3aac0997.png)
![image](https://user-images.githubusercontent.com/2197479/34524466-911d918c-f0d6-11e7-9c4d-12b31eed8a4f.png)

**Comment by wmbutler** [comment]
Please post screenshots of your proposed fixes.

**Comment by zhyupe** [comment]
Dark theme:
(normal)
![image](https://user-images.githubusercontent.com/2197479/34595934-c4ba291a-f216-11e7-8d03-fe8e23428072.png)
(active)
![image](https://user-images.githubusercontent.com/2197479/34595936-ca54ce3e-f216-11e7-930b-223494a55eda.png)

Light theme:
(normal)
![image](https://user-images.githubusercontent.com/2197479/34595947-deeb1aba-f216-11e7-906a-cf08cea5a06b.png)
(active)
![image](https://user-images.githubusercontent.com/2197479/34595948-e3ddc770-f216-11e7-92a6-dab19b5bc818.png)
