### ISSUE TITLE
[4] Error claiming balance: AssertionError: Missing cipher text. BUG!

### ISSUE THREAD

**Issue by iscrawler** [bitshares/bitshares-ui#951]
Log in with a network name, create a new local wallet, export(through console command) then restore the 0.93 json file, which shows the unclaimed balance, import keys then wallet/lookup balances. It shows unclaimed balance & vested balances which i try to claim to my network username, from the drop-down, then get this error message: Error claiming balance: AssertionError: Missing cipher text.
![error](https://user-images.githubusercontent.com/35077121/34535306-68f11ea0-f076-11e7-93ae-794ca7c5892c.jpg)

**Comment by HarukaMa** [comment]
Seems that balance claim is causing a lot of issues, as I've seen different error notices in the telegram group. As potential developers are already claimed their old balances, is there a good way to trigger this process locally? I guess it could only be done in a private testnet, but how exactly?

**Comment by iscrawler** [comment]
Good question. How to exactly make it done?

**Comment by iscrawler** [comment]
It's not a question. It's a bug! At least 3 people getting same error!

**Comment by iscrawler** [comment]
Any news developers?

**Comment by landry314** [comment]
@iscrawler, someone needs to claim these 2 hours... that is $240.

**Comment by landry314** [comment]
Here are people talking about the exact same issue:
https://bitsharestalk.org/index.php?topic=24318.0

**Comment by svk31** [comment]
Hard to fix this kind of issue without a way to reproduce it. @abitmore @xeroc do you know of a way we could reproduce a balance import on the testnet (or on a private testnet)?

**Comment by HarukaMa** [comment]
More specifically, how does `initial_balances` works in genesis file? It seems the owner are addresses instead of public keys, but I couldn't find matching address for my already claimed balance.

**Comment by HarukaMa** [comment]
I've prepared a testnet genesis to test balance claim: https://gist.github.com/HarukaMa/7228806e21a39afbddad5463179201cf

Test account private key: `5JzxRLNNHU9SBBQVYJN4JRvz186DyxZWLw9quRU9KKuvFguzcLB`

**Comment by iscrawler** [comment]
@HarukaMa could you please tell me how to use it? any tutorial links maybe? Thank you.

**Comment by HarukaMa** [comment]
@iscrawler This is for developers to test balance claim in testnet. It may not be much useful as I can't reproduce the issue using this genesis.

**Comment by iscrawler** [comment]
Any news guys?

**Comment by wmbutler** [comment]
Nobody has claimed the issue so...no.

**Comment by iscrawler** [comment]
Sad. Will wait...A lot of money stuck :(

**Comment by nbcks** [comment]
I will take a look at this over the weekend

**Comment by iscrawler** [comment]
That would be very grate!

**Comment by abitmore** [comment]
Lack of useful info, so it's hard if not impossible to fix. For example, web console logs, addresses, public keys, and etc. Or someone already has those? May be different situation / solution for different people.

In the meanwhile, in the [forum post](https://bitsharestalk.org/index.php?topic=24318.0):
> If anyone here needs help trying to reclaim old stake, PM me here or on telegram @robrigo and I can help you for a service fee. Thanks and good luck. :)

Perhaps we can get some useful info from him.

**Comment by abitmore** [comment]
Found the error "Missing cipher text" in [aes.js](https://github.com/bitshares/bitsharesjs/blob/master/lib/ecc/src/aes.js). I believe in this repository it's thrown at [this line of code](https://github.com/bitshares/bitshares-ui/blob/2.0.180115/app/components/Wallet/ImportKeys.jsx#L376). Would it be related to Cloud Wallet Mode?

**Comment by nbcks** [comment]
I'll be working on this in a few hours, need to fix my PC first :(

**Comment by nbcks** [comment]
I've messaged Robrigo about this, I would have thought the error would be something to do with account names vs private keys.

**Comment by robrigo** [comment]
I've got an idea. Notice how the account name associated with the balance to be imported is "scrawler"? But the actual BTS 2.0 account is called i-scrawler? You probably need to get those two things to line up.

**Comment by robrigo** [comment]
One way you can reproduce this is to go back to BTS 0.9.3c, and create an unregistered account called i-scrawler, then do the export and try importing to BTS 2. **bts 0.9.3c exports must be fully replayed AND resynced!**

**Comment by abitmore** [comment]
> I've got an idea. Notice how the account name associated with the balance to be imported is "scrawler"? But the actual BTS 2.0 account is called i-scrawler? You probably need to get those two things to line up.

I've thought of that as well. However, when importing, name in 0.9.3 doesn't need to be identical to name in 2.0, or say, it's legit to import balances to a different name.

**Comment by robrigo** [comment]
Quote from fluxer555:

> I've seen it a few times. I usually have them create a new account with a fresh state/localstorage and it fixes the issue.
> I think the system sometimes gets confused when you swtich to "local wallet" mode from "cloud wallet" mode.
> There really should be tests around this stuff.
> I don't really know the underlying issues for most of these things, I just know workarounds.

**Comment by iscrawler** [comment]
@robrigo I have tried to import 0.9.3 wallet with i-scrawler name too . Same error. How I can fully sync 0.9.3 wallet? I just downloaded last fully synced blockchain(with last generated block). How I can sync if no working nodes nowadays?

**Comment by robrigo** [comment]
@iscrawler downloading the fully synced chain from bittorrent, installing that chain data into your app data folder, starting the client, and then letting it replay is step 1.

Step 2 is to make sure you let a "resync" happen on your account itself. You can resync from the 0.9.3c terminal. This also happens when you do a regen key command. 

You've got to replay AND sync fully to get a proper wallet state to be exported. Thanks TITAN!

**Comment by nbcks** [comment]
Could I please unclaim this issue? I have no idea of how to even go about solving this.

**Comment by abitmore** [comment]
>Step 2 is to make sure you let a "resync" happen on your account itself. You can resync from the 0.9.3c terminal. This also happens when you do a regen key command.

"rescan".

**Comment by iscrawler** [comment]
That is exactly what I did on Windows system. Waited for replaying chain, imported wallet.dat, rescan chain, etc. I'm going to repeat it on a Mac.

**Comment by iscrawler** [comment]
Same here on Mac :(. I'm going to try it with cli_wallet.

**Comment by robrigo** [comment]
I've got an old local wallet install, and can claim PTS / AGS unclaimed balances, no problem. In my spare time I've helped some people claim their stake, and I've noticed a lot of new users can't complete this process on their own. I don't know what is different about their wallet and mine, but I can claim the stake they can't, in my local wallet.

This smells like a regression bug that has crept into new releases, I wonder if an account created in an older bitshares 2 light wallet install can claim this stake?

**Comment by iscrawler** [comment]
I have tried the oldest compiled to a binary wallet. Same issue. Could anyone explain how or point me to step by step guide for how to import 0.9.3 to 2.0 using cli_wallet?

**Comment by iscrawler** [comment]
Hello guys. Any good news?)

**Comment by abitmore** [comment]
You provide no new info, we have no news.

**Comment by abitmore** [comment]
It's not recommended to claim balances via CLI. It's more buggy than GUI.

**Comment by abitmore** [comment]
The guide is here https://bitsharestalk.org/index.php?topic=20822.0

**Comment by iscrawler** [comment]
What kind of new info you need? I can send you my log files or something else. Just ask.

**Comment by iscrawler** [comment]
**abitmore** I didn't find in that guide anything about how to import wallet or private keys using CLI wallet 2.0. There is nothing about CLI wallet 2.0.

**Comment by abitmore** [comment]
CLI "2.0" is not recommended for claiming balance. Use the GUI.

**Comment by iscrawler** [comment]
@abitmore I know that it's not recommended, but there is a **BUG** in GUI wallet and you know it. I'm looking for any way to make it work.
@wmbutler If you think it's not a bug and it's just a simple question, so my question is - what does this error mean: **Error claiming balance: AssertionError: Missing cipher text** and how to fix it?

**Comment by svk31** [comment]
You shouldn't login with a cloud wallet account. Create a brand new wallet, then create an account in that wallet using the faucet, then try to restore the json file.

**Comment by iscrawler** [comment]
@wmbutler Good job Bill! You are awesome! It's amazing! Just close all tickets that you guys "developers" won't fix. Should I open another one?

**Comment by robrigo** [comment]
This is a big deal. It's one of the main reasons that I get people asking them to help claim stake... because my wallet is so old, it isn't cloud style, so it still works to do the claim process. I didn't realize that was the difference until you guys confirmed it in this issue. Don't have time to dig into it myself though.

@iscrawler hit me up out of band (Telegram) if you want help claiming. You'll need to trust me but I can walk you through if you're just trying to get your stake. Alternatively, you can try to create an old style wallet and try claiming that way. I had some issues trying to walk someone through trying to create the old style wallet recently... the UI seemed to be getting confused about whether I was logged in.

**Comment by iscrawler** [comment]
@svk31 @robrigo Thank you so much for this info guys. I definitely try to claim coins this way. This is valuable information. Thanks a lot.

**Comment by iscrawler** [comment]
@robrigo Thank you so much for your help! After almost 6 months of my unsuccessful efforts you made it finally. I'm really appreciate it! Thank you!

**Comment by Kaspler** [comment]
Thanks to @robrigo tip about using an old version of the wallet!

I was able to claim tokens using this version of the wallet (Mac OS):
[https://github.com/bitshares/bitshares-ui/releases/tag/2.0.151119](https://github.com/bitshares/bitshares-ui/releases/tag/2.0.151119)

And these instructions:
[https://docslocalcoinis.readthedocs.io/en/latest/bitshares/migration/howto-importing-wallet.html](https://docslocalcoinis.readthedocs.io/en/latest/bitshares/migration/howto-importing-wallet.html)

The UI is buggy, and the "claim" button was disabled, although I could see the unclaimed balance. The solution was to add another account to the wallet, then it was shown in the list of the accounts that could claim the balance.

Another issue was that sometimes there is an error in broadcasting the transaction. On the second attempt, it worked fine. 

My general advice for anyone struggling to claim the balance would be to play around with this version of the wallet and to create backups of the wallet on each step.
