### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by gabev** [bitshares/bitshares-ui#955]
I'm using the latest version 171219 .deb installed on Ubuntu. When I click on the indicators ,tools or the setting symbol the popup window doesn't show up properly ; it's hidden by the Markets column.

![screenshot from 2018-01-03 13-38-01](https://user-images.githubusercontent.com/9032546/34541787-7cc8d130-f08e-11e7-937b-8457e2c4bd27.png)

**Comment by wmbutler** [comment]
Closing due to imminent tradingview integration.
