### ISSUE TITLE
[4] Exchange charts only show 200 bars of data

### ISSUE THREAD

**Issue by steempower** [bitshares/bitshares-ui#96]
Exchange charts only show 200 bars of data; This means if you zoom out instead of showing more data the bars just get condensed into the center of the screen.

i have been informed that this is due to the API only returning 200 items. Suggest upon zoom out if more data is required the next 200 items should be pulled from the API server as required

**Comment by wmbutler** [comment]
Bars should condense right justified for at least an initial fix.

**Comment by wmbutler** [comment]
https://v.usetapes.com/99mFY4AKDq

**Comment by svk31** [comment]
In your video you have the 3m zoom selected, that means it will never show more than 3 months of data. 

I see react-stockcharts has added an api that lets you fetch more data on pan, so we could hook i to that to fetch more points.

**Comment by wmbutler** [comment]
Should I open a separate ticket on this for the right justified zoom request?

**Comment by wmbutler** [comment]
I see @calvinfroedge claimed this bt it looks like @svk31 worked it. Can you guys make sure the correct person is getting credit here?

**Comment by calvinfroedge** [comment]
@svk31 if you would like to claim the issue you can. I was assuming the estimate was for yet-to-be-completed work.

**Comment by wmbutler** [comment]
FYI, when I begin to add up payments, I will go by:

- Milestone 170901
- Who claimed it || [name in brackets]
- [hours in brackets]

**Comment by svk31** [comment]
It's an old issue, I already increased the amount of data being fetched back in march, that's the commit you see.

**Comment by wmbutler** [comment]
If it's an old issue, is there a reason it's still open? Should I close it and set the bounty to zero? I need some guidance here.

**Comment by svk31** [comment]
It's open because the suggestion of fetching more data on zoom/pan has not been implemented. I suggest we close this one and create a new one to implement data fetching on pan/zoom (not sure on zoom is possible).
