### ISSUE TITLE
Prices in USD, CNY, Euto and other FIAT currencies

### ISSUE THREAD

**Issue by bob-ggg** [bitshares/bitshares-ui#967]
The value of BTS in various currencies is provided by witnesses to support MPAs. I suggest to provide quotes based on one of these currencies. This feature is of particular interest for traders in bitCNY, bitUSD, etc. since it provides an immediate view of misalignment in value.  A possibly more complex option supports access to external sources of data (say, coinmarketcap)

**Comment by wmbutler** [comment]
Can you be more specific? Values are estimates in the portfolio. Are you referring to the Exchange?

**Comment by happyconcepts** [comment]
It appears to be more about price feeds for MPAs on the exchange and not about the UI display of market orders, right?

**Comment by bob-ggg** [comment]
Actually, as a trader I monitor the price of bitAssets pegged to FIAT and
buy/sell according to the difference between the "fair"price and the one
provided by the UI of DEX. Currently, I have to 1) get the open orders from
DEX of, say, bitUSD and 2) check the quotation of BTS on Coinmarketcap to
calculate, for instance, how much btUSD is worth vs. USD.
A simple rule, as an example, could be 1) buy when bitUSD < 0.9USD 2) sell
when bitUSD=USD
The implementation of this trivial rule requires the display of the price
of bitUSD in USD (bitCNY in CNY, etc)
Since the feed of the value of BTS in USD (CNY, EUR, etc) is provided every
hour by the witnesses, this feed could be used to compute the value of
bitAssets in FIAT currencies.
Another, maybe more complex option, would rely on external sources such as
coinmarketcap. I am not a dev, just a trader......
Thanks for your attention, Roberto

**Comment by wmbutler** [comment]
Unless you can offer some advice as to whom we would trust to know bitUSD:USD, I'm not sure we can be very helpful in resolving this issue.

**Comment by bob-ggg** [comment]
A simple solution would rely on the price feed offered for BTS by
coinmarketcap in USD. This is the most liquid market for BTS we have now.
With this number and the open orders from DEX, it is possible to compute
the current USD-based value of bitUSD. The same process is somewhat
trickier for bitCNY. A way to solve the puzzle is based on following the
most liquid path. Since the most liquid market for BTS is based on USD (at
least today), it is possible to convert the market quotation in USD to CNY
using forex quotes such as those provided by oanda.com. At this point a
simple triangulation gives the value of BTS in CNY  and the price of bitCNY
in CNY could be derived as previously described.
Thanks for your attention, Roberto

**Comment by wmbutler** [comment]
But then we rely on Coincap. It's a hard sell to this community I'd say.

**Comment by bob-ggg** [comment]
As an alternative, my understanding is that witnesses are posting the price
of BTS from external exchanges. When a holder of bitAssets requests a
forced liquidation, this is the price that is used to determine the value
of bitUSD or bitCNY vs USD and CNY. This hourly posting should be somewhere
in the blockchain.
Thanks, Roberto

**Comment by wmbutler** [comment]
Good thought. Probably the only person familar enough to claim this would be @svk31

**Comment by bob-ggg** [comment]
Could you make svk31 aware of this thread?
