### ISSUE TITLE
The user on the top-right changes when it shouldn't

### ISSUE THREAD

**Issue by sudoaza** [bitshares/bitshares-ui#968]
Go to wallet.bitshares.com/account/someaccount
On the top right it changes to someaccount and the dashboard shows the data for someaccount
From there on it's like you're that account.

Of course with accounts i don't own thats not a big deal since i don't have the keys, but could happen that changes to some of my other accounts and end un doing a tx with the wrong user.

**Comment by btsfav** [comment]
this has to happen, else you wouldn't be able to check the account's settings, votings and so on. 

it's a feature and in the wallet since the beginning

**Comment by sudoaza** [comment]
ok, cool.
