### ISSUE TITLE
Available Update Missing from Github Repository

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#971]
Within the BitShares Application an update notification is present but at:

  https://bitshares.org/download/

all the links are dead because the github repository is not updated here:

  https://github.com/bitshares/bitshares-ui/releases

**Comment by startailcoon** [comment]
There where a need to fix a minor UI issue, so the release was removed from the repository until @svk31 can rebuild it again. It will be out in a few days.

I believe he's currently traveling, and unable to update the repo.
