### ISSUE TITLE
[3][kapeer42] Exchange Order Scrolling

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#972]
When users decide to scroll through the order book, the bid and asks scroll independently. This offers no real advantage because it's important to always be able to see the closest bid/ask even when looking up and down the book. GDAX handles this elegantly and I think it would be wise for the DEX to do something similar:

## GDAX
![scroll1](https://user-images.githubusercontent.com/1254810/34641967-7a70e612-f2d1-11e7-870f-283d2ef1f468.gif)

## Bitshares DEX
![scroll2](https://user-images.githubusercontent.com/1254810/34641975-86580456-f2d1-11e7-950a-46d5b6ca535e.gif)

Additionally, I think we should get rid of the odd row coloring. It makes the hover state ambiguous and it's not really necessary for readability (using GDAX for reference).

- [ ] Scroll entire order book locking in visibility for highest bid / lowest ask
- [ ] Remove even / odd row colors

**Comment by startailcoon** [comment]
I love the idea. I've been frustrated many times because the list isn't scrolled at the point of sales/buy prices but at a different spot because I've scrolled in it, or that it's just no at the correct place for some reason.

**Comment by wmbutler** [comment]
Right, this would solve that problem elegantly.

**Comment by svk31** [comment]
I completely disagree, I think scrolling the two independently is far more useful and elegant. Having them scroll together would be very frustrating since you'll have no idea where you are in the orderbook. 

That being said I also never use the vertical orderbook since I have enough screen space to keep it horizontal.

**Comment by wmbutler** [comment]
This would only affect the vertical orderbook. At least go use GDAX for a minute. If you carefully consider this, it doesn't remove any functionality and it only enhances the experience by always keeping the closest pairs together.

**Comment by svk31** [comment]
It removes the ability to scroll bids while keeping asks visible and vice versa, I don't think removing that ability enhances the experience at all.

**Comment by wmbutler** [comment]
How so? We are only hiding visibility to the extreme high and extreme low bids simultaneously. There is a limited use case for being able to have those extremes visible at the same time.

Looking at a few other exchanges, it underscores my point.

<img width="341" alt="screen shot 2018-01-07 at 2 34 41 pm" src="https://user-images.githubusercontent.com/1254810/34653843-20bcfcb8-f3b8-11e7-836b-8582d0444d61.png">
<img width="234" alt="screen shot 2018-01-07 at 2 34 21 pm" src="https://user-images.githubusercontent.com/1254810/34653844-20c8b1c0-f3b8-11e7-97db-13f3576072b4.png">

Since you don't even use this view, I hope we can come to terms. You will still have your view. I'm not asking to eliminate the other one.

**Comment by startailcoon** [comment]
Can we make it a tickable option? With a lock symbol for example?

I see both options as valid points of habits. Depends on how you like it.

As we've always had it this way, it may be strange for some users if it just changes.

**Comment by svk31** [comment]
If you make it like the GDAX behaviour you eliminate the current behaviour, they're mutually exclusive. A lot of exchanges do things differently, that doesn't mean it's better. I think it's better to see both bids and asks at the same time, instead of the GDAX way where scrolling down the orderbook means you lose sight of the asks.

**Comment by wmbutler** [comment]
The most interesting point here is that @svk31 doesn't use the vertical mode. I find it interesting that you are defending a use pattern that you do not use. I'm not sure I understand your reasoning.

**Comment by startailcoon** [comment]
Just to give another example, here's how Kraken does their trading view.
They do not allow scrolling at all, instead they use grouping as a feature.

![kraken-trading](https://user-images.githubusercontent.com/12114550/34686796-0b091a28-f4ad-11e7-99fc-57ba5834b702.gif)

I don't see the benefit of having a scrollable trading list. It gets very long and it's easy to misread it as the closest price if the scrollbar is small. Except for the small bar, nothing tells you if you're at the top. I don't have the space to have the wallet in wide mode, so I'm not really fond of this.

![bitshares-trading](https://user-images.githubusercontent.com/12114550/34686971-98e0f64a-f4ad-11e7-933f-4116d1f03692.gif)

**Comment by wmbutler** [comment]
Right, the idea of hiding the closest bid/asks is not a "feature".

**Comment by HarukaMa** [comment]
It would also eliminate the issue that sometimes ask orders are not automatically scrolled to bottom when updating.

IMHO, vertical mode users should prefer to see an order book in whole like in a traditional trading environment, especially the closest orders, as it's the main difference from horizontal mode. Doing this is better I think.

I have never used grouping in different places though as I think it hides some important detailed information. I think being able to scroll over the order book is enough. In fact I've even tried to separate orders having same price to see individual orders(but failed).

**Comment by svk31** [comment]
Well like I said above I don't ever use the vertical orderbook since I have a 27" screen I won't oppose you on this. It's a very simple "fix" however, no more than 0.5 hours. What you want is the default behaviour, what we have currently is custom behaviour.

**Comment by wmbutler** [comment]
Adding some additional items to this.

<img width="273" alt="screen shot 2018-01-17 at 12 10 12 am" src="https://user-images.githubusercontent.com/1254810/35028314-1513b52c-fb1b-11e7-83cf-d21bab522ab6.png">

- [ ] Extend line just below header all the way across instead of breaking for the scroll bar
- [ ] Remove Units from the price (between the lowest bid and highest ask) and add label "Latest". Right justify so the Latest price is lined up with the prices in the orders list. `Latest 0.276043`. "Latest" can be in a label color (off gray, etc).
- [ ] Right justify the second header "BTS" in this case.

**Comment by kapeer42** [comment]
Can I claim this?

**Comment by dot5enko** [comment]
i guess it makes no sense now. look at #1062

**Comment by wmbutler** [comment]
@dot5enko It still makes sense. Remember #1062 is a bunch of css changes whereas this is just a scrolling change.

**Comment by kapeer42** [comment]
About the spread:
I think the instantaneous spread value is not very useful if the highest bid and/or lowest ask are tiny volumes far from the average bid/ask.
Also I think a percentage is more appropriate, maybe when you click on it, it switches between value and percentage.
In other terms: displayedSpread = `(xHoursAverageAsk / xHoursAverageBid - 1) * 100`%

**Comment by wmbutler** [comment]
It's nice to know the spread between the two at a glance and is easy to calculate. GDAX shows it and I'm assuming they did some market research before deciding to include this value.

**Comment by kapeer42** [comment]
Teaser
![peek 2018-01-27 23-50](https://user-images.githubusercontent.com/35779885/35477133-27855350-03bd-11e8-90e6-587f82c857cd.gif)
![percent](https://user-images.githubusercontent.com/35779885/35477147-79b524b6-03bd-11e8-9019-093f4314a3bb.gif)

**Comment by wmbutler** [comment]
Dig it!

**Comment by wmbutler** [comment]
@kapeer42 is there any chance you could set the scroll bar to auto on this issue?

## GDAX (scroll bar goes away)

![auto](https://user-images.githubusercontent.com/1254810/35699881-fdd78968-0756-11e8-8773-f19a65cf1d5f.gif)

## DEX (scroll bar stays)

![scroll](https://user-images.githubusercontent.com/1254810/35699912-07f9440e-0757-11e8-946e-9cb87c859719.gif)

**Comment by wmbutler** [comment]
Need your BTS address for payment @kapeer42

**Comment by kapeer42** [comment]
kapeer-42
