### ISSUE TITLE
[2][pnomolos] Implement context menu on desktop client

### ISSUE THREAD

**Issue by diogogomes** [bitshares/bitshares-ui#973]
_It's been reported on discord that pasting with right click doesn't work on desktop client._

The reason it's because **context menu it's not implemented on electron (desktop client)**.

The context menu is crucial especially for users without the habit of using keyboard shortcuts.

**Comment by wmbutler** [comment]
- [ ] Allow right click cut/copy/paste in Electron Client

**Comment by pnomolos** [comment]
I could take this - does using something like https://github.com/sindresorhus/electron-context-menu seem OK or should it be from scratch?

**Comment by svk31** [comment]
Copy paste already works fine in Linux at least, which OS is the issue for?

**Comment by wmbutler** [comment]
@diogogomes This is your issue. Which OS did you notice it on?

**Comment by diogogomes** [comment]
Sorry, for some reason I did not receive notification of the @svk31  message.

Yes, **Copy paste works but only with keyboard shortcuts**. **Context menu it's not implemented**.

I received this on Discord#help from an user that not have the habit of keyboard shortcuts.

I tested on **xUbuntu 16.04, desktop client <180108**.

**Comment by svk31** [comment]
Oh right I see, I tested with keyboard shortcuts.
