### ISSUE TITLE
Bitshares balance back to zero

### ISSUE THREAD

**Issue by siphon11** [bitshares/bitshares-ui#974]
Hi helpers,

Could you please help me find out why my balance is back to zero while I have more than 2000?

If I ask now it's because I already spend 2 full days trying to find out without success.

I didn't made any transaction, I just can't find where my balance is.

I can see my 2 accounts in www.cryptofresh.com but I don't know where to look at to see my balance in this service.

Would truly appreciate if you could point in the right direction.

Thank you

**Comment by btsfav** [comment]
this is not a help forum, please use the official help channels: 

https://discord.gg/gG5jb3D
https://bitsharestalk.org/index.php/board,45.0.html
