### ISSUE TITLE
[3][kapeer42] Gracefully handle send operation for accounts with 0 BTS

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#977]
New account holders often do not have BTS in their account. As such, when they attempt to send 1 OPEN.BTC to another user, we attempt to extract the fee as BTS. This feature proposes that **if** the sender has <= total transaction fee of BTS, we should automatically pick the send currency in the UI to pay the fee:

## Example
User has .003 BTS and wants to send 1 OPEN.BTC to another user. In this case the send modal would automatically switch to pay the fee in OPEN.BTC and calculate the proper amount of that coin.

**Comment by nbcks** [comment]
Could I claim this please?

**Comment by kapeer42** [comment]
Oh, I'm sorry if you were working on this, I thought I could just do it since it wasn't claimed :/

**Comment by nbcks** [comment]
Ah no worries, I didn't start on it.
