### ISSUE TITLE
BTS Price discrepancy

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#978]
BTS Settlement price is: .835 but Porfolio is showing it at $1

<img width="559" alt="screen shot 2018-01-07 at 11 03 54 pm" src="https://user-images.githubusercontent.com/1254810/34659515-27d7fcc2-f3ff-11e7-84eb-fa9ec902b19e.png">
<img width="692" alt="screen shot 2018-01-07 at 11 03 41 pm" src="https://user-images.githubusercontent.com/1254810/34659516-27e3b832-f3ff-11e7-9435-bf09b3601e6d.png">

**Comment by btsfav** [comment]
did you check your node or dust trades? never recognized this bug

**Comment by wmbutler** [comment]
It was stupid. I was viewing as BTS for my base currency.
