### ISSUE TITLE
Missing translation keys

### ISSUE THREAD

**Issue by JianJolly** [bitshares/bitshares-ui#98]
The explanations under "deposit/withdraw" don't seem to have a key to translate.

![1](https://cloud.githubusercontent.com/assets/19493352/23936270/b7d299cc-0959-11e7-9edf-40c32c79c360.jpg)

https://github.com/bitshares/bitshares-ui/blob/bitshares/web/app/assets/locales/locale-en.json

**Comment by svk31** [comment]
They're in here: https://github.com/bitshares/bitshares-ui/blob/bitshares/help/en/components/DepositWithdraw.md
