### ISSUE TITLE
[1][dot5enko] Unlock wallet doesn't unlock operations until refresh

### ISSUE THREAD

**Issue by vanissoft** [bitshares/bitshares-ui#980]
Tested in Ubuntu and Chromium in cloud wallet. After you unlock the wallet via lock button, the operations panels (buy and sell) doesn't show up until there is an update via new operation incoming or by doing a toggle with "my trades" and "market trades".
Some user has reported the same in Zephyr Telegram group.

**Comment by dot5enko** [comment]
Confirm such a problem.
claim it
