### ISSUE TITLE
[.5] Scam address warning in new send interface

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#981]
When you input "poloniex" into "TO" in old send interface, there is a warning: 

> This account is not the real Poloniex account, please send to this account: poloniexwallet.

This is not present on new beta interface. We should consider adding that as well as those fake accounts are still a problem.

**Comment by wmbutler** [comment]
@svk31 I'll let you be the arbiter of this.

**Comment by startailcoon** [comment]
If we want this, I can work on it for the next milestone.

**Comment by startailcoon** [comment]
![bitshares-scammer](https://user-images.githubusercontent.com/12114550/37247159-4fae1dce-24b7-11e8-9e06-9601518e76eb.gif)

**Comment by wmbutler** [comment]
Let's be more concise and replace the 'Lifetime Member #xxxx` with `Suspected Scammer: #xxxx`. Leave it in red.

**Comment by startailcoon** [comment]
Good idea, Updating the account selector to reflect this on all places it's used.

![bitshares-scammer_2](https://user-images.githubusercontent.com/12114550/37300828-4907fb04-2627-11e8-9595-24c7a16f9fa6.gif)

**Comment by wmbutler** [comment]
Are you sure it's necessary to display the additional orange text? Seems that the Suspected scammer is enough warning.

**Comment by diogogomes** [comment]
Maybe a `?` icon together with `Suspected Scammer` that shows the additional text on hover.

**Comment by startailcoon** [comment]
@wmbutler I did it to be consistent with how it was on the old modal, and to be clear about it. 

We can of course change it to be a tooltip maybe?

**Comment by wmbutler** [comment]
@startailcoon if you think `suspected scammer` isn't forceful enough, a tooltip will be fine.
