### ISSUE TITLE
[0.5] Cannot send until not edit "TO" input

### ISSUE THREAD

**Issue by ruslansalikhov** [bitshares/bitshares-ui#982]
Cannot send tokens second time, until not edit "TO" input again.

![2018-01-08 21 43 58](https://user-images.githubusercontent.com/2409521/34681407-9d0d8570-f4bd-11e7-8479-e5a23892c0d3.gif)

**Comment by wmbutler** [comment]
This is actually an issue with you are having a latent connection and the send modal is failing to close. This is resolved in #945 which will be released in the 15th

**Comment by ruslansalikhov** [comment]
@wmbutler it's another issue (input box was not reset (user saw text) but SendModal thought that it's empty. @svk31 fixed it already by commit 9d624f7 (thanks to him).

**Comment by wmbutler** [comment]
Sorry about that. Thanks.
