### ISSUE TITLE
[2][TBAPI-0KA] Operations should be eligible for cloud wallet users even if not logged in

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#984]
The local wallet allows users to initiate operations even if they aren't logged in. Seems we should be able to do the same for cloud wallet users. Discuss.

**Comment by gibbsfromncis** [comment]
@wmbutler I suppose I don't understand what are you talking about because I use local wallet account and it requires me to unlock my account and put password before I can do some operations like transfer, buy/sell etc.

**Comment by gibbsfromncis** [comment]
@wmbutler can you tell about which controls do you mean? Transfer/Deposit?

**Comment by AustinAmoruso** [comment]
Should we just prompt the login modal if an action requires the user to be logged in, instead of disabling features?

**Comment by gibbsfromncis** [comment]
@AustinAmoruso nice point. I agree it.

**Comment by wmbutler** [comment]
That and also the buy/sell controls in the exchange.

**Comment by gibbsfromncis** [comment]
@wmbutler Okay. So just make those disabled elements clickable and display Login modal?

**Comment by wmbutler** [comment]
And test to be sure that the flow works. Once the user logs in, they need to get the confirm screen, etc.

**Comment by TBAPI-0KA** [comment]
@wmbutler Please assign this one to me.

**Comment by gibbsfromncis** [comment]
@wmbutler i'm OK if @TBAPI-0KA take this one.

**Comment by TBAPI-0KA** [comment]
1. For exchange, I offer something like this (sorry, not a designer - of course, everything will be aligned and have proper colors):

![2018-03-05 01_30_06-bitshares - exchange - 984](https://user-images.githubusercontent.com/1467276/36952589-ad4f3202-201a-11e8-8cc8-36e1c0050093.png)

2. I found the difference of menu items behavior between testnet and real network. On testnet, they are indeed disabled, while on the real one user is able to open an appropriate page, and login modal will be shown during operation submission. I assume the behavior should be the same? If so, which option should be implemented: disable the menu item; enable the menu item, show lock icon on it (to indicate the reason why the item is disabled), and show login modal on click; enable menu item always, and handle permission verification on every separate page?

Also, perhaps somebody knows the reason why these menu items act differently on different nodes?

**Comment by wmbutler** [comment]
I'm not sure why you would want to hide the buy/sell controls. Seems to me the user should be able to see everything and even be able to initiate the buy operation. Prior to presentation of the confirm modal, the user would be asked to login, followed by the confirm modal.

**Comment by TBAPI-0KA** [comment]
@wmbutler You mean, when clicking on Buy/Sell button itself? Why not, seems logical.

What about menu items? Additional information - looks like they are disabled on testnet because a user cannot withdraw funds there at all, so it has nothing to do with this issue. However, the question about correct behavior still remains.

**Comment by wmbutler** [comment]
@TBAPI-0KA Let's start with the Exchange. I've observed cloud wallet users go in circles realizing that the had to login before they could execute the trade. I think there is a huge benefit to getting this part completed and then we can add some more areas as we run across them.

**Comment by TBAPI-0KA** [comment]
I only needed to enable Buy/Sell widgets on Exchange - somebody already wrote the code which asks for unlocking permission.

Please let me know if anything else is required here.

**Comment by TBAPI-0KA** [comment]
@wmbutler Please hold on with closing - seems like my solution is formal, and we have a little bit deeper issue here. I'm discussing some technical details with @svk31 on #1324 PR thread.

**Comment by abitmore** [comment]
Perhaps closed by accident. I'm reopening it.

**Comment by TBAPI-0KA** [comment]
It's completed now, can be closed.

**Comment by TBAPI-0KA** [comment]
@gibbsfromncis asked me to leave my Bitshares account here. It's absolutely the same as my Github nickname - TBAPI-0KA
