### ISSUE TITLE
[1][dot5enko] Separate Markets from Accounts / Contacts

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#985]
Currently, when clicking on the Bitshares logo in the upper left corner, we display markets and accounts. I'm proposing that we only display markets since accounts is a menu option currently.

<img width="1268" alt="screen shot 2018-01-08 at 8 53 35 pm" src="https://user-images.githubusercontent.com/1254810/34702931-07447c1c-f4b6-11e7-81fd-0cc638b9be8f.png">

**Comment by dot5enko** [comment]
i claim this

**Comment by dot5enko** [comment]
done
