### ISSUE TITLE
iOS Mobile Wallet

### ISSUE THREAD

**Issue by cogentgene** [bitshares/bitshares-ui#988]
# Proposal For an iOS Wallet to Increase User Adoption

Bitshares is a technological breakthrough that keeps hidden the many functions that could benefit society in many ways. With all of the hype in cryptocurrency market it is easy to overlook a stunning platform with so much potential. The fact that the current trading portal is so robust is evidence that the average user has a very large hurdle to jump in order to adopt this technology.

Today I propose to close the gap for average user adoption. I am not aware of any existing iOS wallet for Bitshares and believe having one in the open marketplace will accomplish several things:

1. Create market exposure to new users who are otherwise unaware of Bitshares
2. Create confidence in existing userbase via continuous UX improvement efforts. 
3. Bridge a usability gap that plagues so many other wallets not fit for an average person.

As I post some designs here, I welcome constructive criticism, tips & advice from real users who will likely use this tool. Feel free to dig into the design and rip it apart if it makes the final product all that much better! 

![login 2x](https://user-images.githubusercontent.com/3827304/34714616-59c96e22-f56d-11e7-8a3b-e6745a58806d.jpg)

Here is the login screen. I was trying to think of a good phrase for "local key" to indicate that the wallet can be accessed via a non-account method. 

![balance 2x](https://user-images.githubusercontent.com/3827304/34714703-9decd85a-f56d-11e7-8a44-7425196c373e.jpg)

The balance screen is fairly straight forward. We have all balances listed on individual line items. Note: while we could technically combine bitUSD bitCNY and others under BTS (as most people probably have one or the other in BTS pairs), I felt it would be more straight forward to have them on their own line. This reduces clutter and gives everything even weight. Of course I welcome your feedback on this issue.

The two key functions of the balance screen are to see the balances and to Send / Receive payment. I want to add some color to the top 2 icons to give them a bit more visual weight (coming soon). 

![send 2x](https://user-images.githubusercontent.com/3827304/34714846-0be3a1ea-f56e-11e7-8737-601a5c3e1fee.jpg)

The send screen has an account dropdown in case you want to send from a different account (signed in with multiple), a to field where users can type in a new username (past payments or contacts can show up as autosuggestions as user types), a scan button to scan a QR code of a nearby individual and lastly a contact button which brings up a search of contacts and automatically plugs that contact's ID into the field. 

![request 2x](https://user-images.githubusercontent.com/3827304/34714935-553ba3ce-f56e-11e7-9aee-dfa87bc9673e.jpg)

The request screen features a prominent QR code for close proximity use. Simply show your code to someone, they do a quick scan and voila info pre-filled. Of course, they can also just grab their username or that person can Copy or Share the info via one of the corresponding buttons. Copy simply copies the username, share opens up a screen to send that info to another program (think iOS share feature). 

I look forward to your feedback!

**Comment by wmbutler** [comment]
Closing this issue since this repo will never be home to a native mobile app. I do love the idea and hope you pursue it. In the meantime, please understand that we will continually add responsive design to the app via foundation so mobile devices can interact with almost every feature.

**Comment by 1TachiMore** [comment]
I need Ios code--
