### ISSUE TITLE
[1.5][nbcks] Login Bug

### ISSUE THREAD

**Issue by xeroc** [bitshares/bitshares-ui#989]
To reproduce:

1. Open an account in the cloud login
2. Reload the whole page
3. Click the unlock locker

Result: It will tell you that you don't have a local wallet and that you should create an account instead of asking for the password for the account that is shown in the top right

**Comment by wmbutler** [comment]
Thanks for the steps to reproduce.

**Comment by svk31** [comment]
This sounds like a probable culprit for the reports of people being unable to login with their password after creating an account. Cloud wallet is the wallet default though and you should only get switched to local wallet mode if you create a local wallet.

**Comment by nbcks** [comment]
could I claim this please?

**Comment by wmbutler** [comment]
This is important. If it takes additional time, please add it.

**Comment by nbcks** [comment]
@xeroc   When you say open an account do you mean create an account or login into an account?

**Comment by wmbutler** [comment]
@xeroc

**Comment by wmbutler** [comment]
@nbcks This issue is related to login, not account creation.

**Comment by svk31** [comment]
Think this is the bug I fixed here: https://github.com/bitshares/bitshares-ui/commit/bdcef977a6a4627e79da792286032f2f729a0683
