### ISSUE TITLE
Separate Burger Menu and Active Account switch list.

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#990]
Currently the menu burger and the active account in top right are joined, where clicking either operates the menu.

I propose separating the two.  
The burger is the menu
The Active account, when clicked, pulls down a list of accounts for switching. (if multiple accounts are available)

This cleans up the menu(its way too long) and provides quicker access to account switching.  Rather than it being all the way at the bottom of the menu.

**Comment by wmbutler** [comment]
Closing since we can handle this in the other issue.

**Comment by Xeldal** [comment]
Which other issue.  I'm not see anything that's related to this.

Are you saying you agree?  or that you disagree?
