### ISSUE TITLE
[.5][zhyupe] Lock Highlights with Menu

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#991]
Currently when you hover over the menu, it highlights the active account, and the burger.  When pressed it also highlights the lock icon.

I propose each of the 3 items should highlight independently on both hover and click.

Clicking any of the 3 should only highlight that specific one, not all 3.

![](https://media.giphy.com/media/3oFzm3dd23ha7FiHpC/giphy.gif)

**Comment by wmbutler** [comment]
I almost agree. I think it should just be 2. The menu with the user's name and the burger should be together but the lock should be separate.

**Comment by Xeldal** [comment]
Obviously if there are only 2 functions (a menu and a lock)  There should only be 2 highlights.  The suggestion for 3 only makes sense if you take action on #990 

wrt #990 I'm assuming you're tying to combine that issue here as I don't see any other relevant issue.

You've actually complained about that very thing yourself not too long ago.  Saying you didn't like having the accounts all the way at the bottom of the menu.  I think this is a good solution.  Are you saying you disagree with #990 ?

**Comment by wmbutler** [comment]
Planning to solve for accounts at the bottom by moving to hierarchical. This will mean fewer items in the list prior to accounts.

**Comment by Xeldal** [comment]
For the full list of accounts that makes sense, under a menu item.  Or a link to the full list accounts page that has all the other useful information currently found on the `Top Markets` page.  A link to this in the menu is certainly a good idea.  

However, I think the switch list, quick list, favorites list, whatever you call it, makes more sense to have  immediately available and not buried in a menu, even if it's top level, it's just clutter.  

It's extremely intuitive also, having it under the active account.  

Also, if the active account is intended to be used as the full menu, like it is now.  Why additionally have the burger icon?  Seems redundant and unnecessary.  It's very intuitive already that it is a button, so the burger, shouldn't be needed.  right?

If on the other hand you'd say the Active account is not intuitive enough as a menu button and needs the burger.  I'd ask why are we making it a button at all?  Just use the burger.

I say make the Active Account a button to switch active accounts.  De-clutter the menu.

**Comment by wmbutler** [comment]
> However, I think the switch list, quick list, favorites list, whatever you call it, makes more sense to have immediately available and not buried in a menu, even if it's top level, it's just clutter.

I'm not proposing to bury the account under the hierarchy. They will still be top level.

> It's extremely intuitive also, having it under the active account.

Agreed

> Also, if the active account is intended to be used as the full menu, like it is now. Why additionally have the burger icon? Seems redundant and unnecessary. It's very intuitive already that it is a button, so the burger, shouldn't be needed. right?

The burger is an acceped pattern for revealing more information and menus on both mobile and non mobile devices.

> If on the other hand you'd say the Active account is not intuitive enough as a menu button and needs the burger. I'd ask why are we making it a button at all? Just use the burger.

Because it's easier to click a larger area

> I say make the Active Account a button to switch active accounts. De-clutter the menu.

It's not a bad idea, but let's wait until we have the hierarchy in place to see how we feel about it then.

**Comment by zhyupe** [comment]
I'd like to claim this issue if it's just about the highlights ... menu structure is a much more complicated problem.

**Comment by zhyupe** [comment]
One problem here:
Should I simply remove the background like this:
![image](https://user-images.githubusercontent.com/2197479/34905471-47ee8b4a-f894-11e7-8bf4-008746af8b02.png)

Or move the lock button out of the menu area like this
![image](https://user-images.githubusercontent.com/2197479/34905500-c4d72748-f894-11e7-816f-fd7f2874e3ee.png)

**Comment by wmbutler** [comment]
Move the lock out of the menu area is the better option I think. But make sure your padding to the right of the lock looks comfortable.
