### ISSUE TITLE
[1][HarukaMa] Two Decimal Precision in Fee Schedule Makes Many Non-Zero Fees Say 0.00 BTS

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#992]
Go to Fee Schedule in Explore and you will see many fees which are less than 0.01 BTS (0.005 if it is rounding up and not truncating) displaying as "0.00 BTS" making them appear to be zero.

If a fee is actually zero it says "Free of Charge".

The precision needs to be changed to the 5 decimal points that BTS supports so we can see the actual fees.

**Comment by wmbutler** [comment]
Easy win

**Comment by HarukaMa** [comment]
I'd like to claim this.

**Comment by HarukaMa** [comment]
And I'm having another question. I know this sounds like a separate issue, but it's closely related.

We can choose to show some values in preferred unit, like bitCNY or bitUSD in Settings. It says "preferred unit of account" but it also affects these locations: open order value, worker budget value and fee schedule. In open order value we are not showing decimals; in budget and fee we are showing them, but only keeping 2 decimal digits.

Do we want to keep the current design and show the fee in preferred unit but remove the decimal limit, or should we show fees always in BTS?

**Comment by wmbutler** [comment]
Def a separate issue

**Comment by HarukaMa** [comment]
> Do we want to keep the current design and show the fee in preferred unit but remove the decimal limit, or should we show fees always in BTS?

This sole question for this issue though: Do we want it always in BTS, or configurable?

**Comment by wmbutler** [comment]
Let's do both `BTS / Preferred Unit`

**Comment by HarukaMa** [comment]
Got it, will show full precision on fee, and leaving others intact.

**Comment by landry314** [comment]
Good point @HarukaMa! I agree with Bill that both units would be best because BTS is the actual unit the fees are being paid in.

I forgot to say that to reproduce you need to set the preferred unit to BTS. I didn't realize this variable affected the unit in the Fee Schedule since fees are always paid in BTS (even when swapped in fee pools).

I am thinking since the precision of two decimal points in BTS also appears on the upper right below the account name, that it is a system wide variable setting this precision. If you change it to 5 decimal points be careful it doesn't change the account value displayed on the upper right as well. That would be very ugly. I actually think that the two decimal places in account value are unnecessary with the current value of BTS... When BTS hits $100 then it will start to matter! ;-)

**Comment by HarukaMa** [comment]
@landry314 I have added a new prop in EquivalentValueComponent to address the need of full precision, so other locations are not affected unless they explicitly requires it. In fAct, the balance on the upper-right corner is another component, so it will not be affected at all.

**Comment by HarukaMa** [comment]
Preferred unit is not BTS:
![0030-01-11 17 44 51](https://user-images.githubusercontent.com/861659/34816092-301bf208-f6f7-11e7-93c5-1ebcc24e7233.png)

Preferred unit is BTS:
![0030-01-11 17 44 36](https://user-images.githubusercontent.com/861659/34816094-304ad96a-f6f7-11e7-8aeb-f6360a1ad7a6.png)

although the fee in CNY is not accurate, as it's just calculated using market value, but when actually paying the fee it's converted using CER.

**Comment by landry314** [comment]
Is it not possible to get the CER conversion rate to create this value?

**Comment by HarukaMa** [comment]
@landry314 Seems possible, but need some more work as I couldn't find any existing code to do that. Trying to do it now...
