### ISSUE TITLE
[5][AustinAmoruso] Deposit (beta)  Asset Search Tweeks

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#993]
**Problems:**
- deposit popup loads blank.  Looks strange/bad.
- Asset search is cumbersome and annoying
- If no selection is made and dropdown closed, it automatically selects the last hovered item.
- After selection, changing to different asset requires manually deleting the text.  Annoying.
- Can't find all assets available for deposit. (temporarily disabled assets)

**Solutions:**
- Asset Selection should default to `BTS`
- Dropdown should show full list regardless of previous selection.
- Drop down should always show all assets whether enabled or not by gateways.
- After selection.  Display `Disabled by Gateway` if a disabled asset is selected.
- After selection. Clicking the dropdown again should show all available coins, not a filtered list.
- Asset textbox should not be the filter, should not be editable. ***
- First entry in dropdown can be an editable textbox `Filter:`

*** While it can work with the selection box being editable, I think it's much better flow and UX if the filter is separated from the actual selection.  

Optional: Gateway list should show all Gateways, defaulting to the first available one.  If a gateway doesn't support the coin selected, grey out the selection with `Not Supported`.   If the gateways supports the coin but it is currently disabled.  Gateway should still be selectable.

**Comment by wmbutler** [comment]
> Asset Selection should default to BTS

Disagree

> Dropdown should show full list regardless of previous selection

This is not scalable at anything over 25 assets

> Drop down should always show all assets whether enabled or not by gateways

I disagree. Why lead a user down a dead end?

> After selection. Display Disabled by Gateway if a disabled asset is selected.

See previous answer

> After selection. Clicking the dropdown again should show all available coins, not a filtered list.

This is a typeahead and is the only meaningful way to deal with an ever growing list of assets

> Asset textbox should not be the filter, should not be editable. ***

I have no idea what you mean

> First entry in dropdown can be an editable textbox Filter:

??

**Comment by Xeldal** [comment]
- Asset Selection should default to BTS
>Disagree

It should default to something.  I don't care specifically that it be BTS, only that its a reasonable choice, BTC would also be fine.  Leaving it default to nothing just looks terrible.  Do you actually like how it looks?

- Dropdown should show full list regardless of previous selection
>This is not scalable at anything over 25 assets

You're obviously missing the point.  You have to handle this situation anyway with an empty filter(typeAhead).  You don't necessarily have to show ALL available coins.  The point is to reset the filter.  Current function is UX nightmare.

- Drop down should always show all assets whether enabled or not by gateways
>I disagree. Why lead a user down a dead end?

The alternative is the user is confused because he previously deposited ETH but now there is no option.  Did it disappear??  did I lose my Coins??  Did the gateway run off??   The same is true for withdrawal.  The user may currently hold OPEN.ETH and now see there is no way to withdraw.  Why do prefer to confuse the user rather than inform them?

- After selection. Display Disabled by Gateway if a disabled asset is selected.
> see previous answer

See previous answer

- After selection. Clicking the dropdown again should show all available coins, not a filtered list.
>This is a typeahead and is the only meaningful way to deal with an ever growing list of assets

You're not getting it.  I'm not suggesting getting rid of the typeAhead filter.  

- Asset textbox should not be the filter, should not be editable. ***
> I have no idea what you mean

It is part of the problem in UX.  It's not obvious that it's a textbox.  Not obvious its editable, Not obvious it acts as a filter.  The selected coin BECOMES the filter and prevents the user from selecting anything else. When I select an item by choice or by the selection bug I described, all other options disappear.  User is forced to manually delete the selected coin and re-type in the filter again.  This is bad UX.  Each press of the dropdown should reset the filter.  There are other options but I don't want to confuse you.

- First entry in dropdown can be an editable textbox Filter:
>??

AKA typeAhead.  This solves the UX issue described above.  Dropdown shows a limited selection (your 25 limit) and the first item in the list is a filter(typeAhead).  It's pretty simple.  What do you not understand about it?   Most exchanges have this filter along side the list but because we're using a dropdown it would have to be in the dropdown itself to work.

**Comment by wmbutler** [comment]
Post a mock. I think it's dead simple to use.

**Comment by Xeldal** [comment]
Binance clearly understand UX.  They are doing EXACTLY what I've detailed above.


![](https://media.giphy.com/media/xT8peoin3TAc1fEblK/giphy.gif)

**Comment by wmbutler** [comment]
So, basically, you are asking to display an alphabetical list of the top 10 cryptos if nothing is entered.

**Comment by Xeldal** [comment]
No, that was not a point I made, not sure where you get that.  Please re-read the thread if you've forgotten but I'll try and reiterate the basic points again below.  
  
Notice in the above example that the selected coin is not the filter.  
The filter(typeAhead) is the first item in the dropdown.  
So making a selection does not change whats in the list, on subsequent clicks of the dropdown menu. 
Everytime the dropdown is opened it shows the full unfiltered list.  40-50 coins in this example.

Also notice that disabled coins are still listed but have "suspened" next to them.  This is important for UX as you don't want people thinking a coin is no longer available or de-listed simply because it's on maintenance.  Removing it from the list causes unnecessary confusion.

The other suggestion i made was for it to default to BTS which is less important and might be better to just default to the last selected coin from previous use.

**Comment by wmbutler** [comment]
I see. Whoever claims this, See @Xeldal screenshot for how we might tweak the typeahead widget to work like the screencast on Binance.

**Comment by AustinAmoruso** [comment]
I'll take this one

**Comment by wmbutler** [comment]
Assigned to you. Thanks. I also added an extra hour.

**Comment by AustinAmoruso** [comment]
Is the page in question this link https://wallet.bitshares.org/#/explorer/assets

**Comment by AustinAmoruso** [comment]
Is there a simple way to know wether the asset is suspend or not?

**Comment by AustinAmoruso** [comment]
Sample of what I have so far
https://gfycat.com/RequiredGranularHind

**Comment by wmbutler** [comment]
@AustinAmoruso this issue was about creating a better typeahead component. Can you please post a licecap of the result?

You shouldn't really have to implement logic for the component, because that is the responsibility of the person incorporating your component.

**Comment by AustinAmoruso** [comment]
I'm sorry I really missed that it was just building a better component and not trying to integrate it I can clean this up and fix it so there is a better component that works like the animation @Xeldal has.
Also this is what I have so far https://gfycat.com/RequiredGranularHind

**Comment by svk31** [comment]
Let's not copy Binance's grammatical errors at least, it should read "Suspended".

I do agree with Xeldal that the current Typeahead isn't very intuitive, and the way Austin has implemented it works much better for the deposit modal. I also added a placeholder text to make it clear where to click to start searching. 0148207a32fa6da6b5d9908892c7e57d333d0fa9

However, in other use cases like the Send modal the new behaviour isn't great, so perhaps we should implement a switch that lets you use the original or the new typeahead behaviour?

![image](https://user-images.githubusercontent.com/6890015/36156512-8a0cdf94-10d7-11e8-98ed-47d6ac6aafae.png)

![image](https://user-images.githubusercontent.com/6890015/36156591-d207e60e-10d7-11e8-83a7-0de0639655e9.png)

**Comment by svk31** [comment]
I've just noticed there's a bug, the new Typeahead only lets you select accounts from the list of contacts/your own accounts. It lets you enter other accounts but there's no way to select them, that needs to be fixed.

**Comment by wmbutler** [comment]
@AustinAmoruso please review the look of this. The secondary input for search looks like it's part of the base form, when instead it needs to look like it's part of the dropdown / typeahead element over the form.

You can use @Xeldal  example to style this appropriately.

**Comment by svk31** [comment]
Right I see what you mean Bill, you want the second input box to be hidden until the dropdown is activated.

**Comment by AustinAmoruso** [comment]
Will fix.

**Comment by AustinAmoruso** [comment]
Here is the updated look to the TypeAhead please note the all the items are manually set to suspended for look they can actually be controlled with `item.status`

![deposit](https://user-images.githubusercontent.com/1895601/36183034-5f512134-10e1-11e8-9198-9520c48f696e.gif)

**Comment by wmbutler** [comment]
This is MUCH better!!

**Comment by AustinAmoruso** [comment]
The suspended status is able to be set via the item.status. if you don't set item.status nothing will be displayed on the right. Whatever you set item.status to it will be displayed

**Comment by wmbutler** [comment]
Please post your BTS payment address here.

**Comment by AustinAmoruso** [comment]
austin-amoruso is my bts payment address
