### ISSUE TITLE
[.5][nbcks] Show Balance on Margin Positions Tab

### ISSUE THREAD

**Issue by Xeldal** [bitshares/bitshares-ui#994]
I would like to see my current balance of each SmartCoin in the Margin Positions tab.

I see my debt but not my current balance.  It's useful to compare the two.  

Currently I have to switch back to the poorly named `PORTFOLIO` tab or click `ADJUST` to make the comparison.

**Comment by nbcks** [comment]
Could I please claim this?

**Comment by wmbutler** [comment]
Collateralized BTS | Total BTS
--: | --:
2000.00000 | 5000.00000

**Comment by nbcks** [comment]
Thank you

**Comment by wmbutler** [comment]
Don't sum up the new column. Need a better plan for that because a total at the bottom won't make any sense when adding up net worth of the account.

**Comment by nbcks** [comment]
Right, got the graphics all working (including the summation row not including the balances). Having trouble getting the the actual balance of the asset given the account and call order. This has to be done tomorrow I believe so I will update if I'm still having trouble in two hours :(

**Comment by nbcks** [comment]
nvm, it's looking good!

**Comment by nbcks** [comment]
Sent the pull request

**Comment by wmbutler** [comment]
Please reference the PR from here so it's tied back to the issue.

**Comment by nbcks** [comment]
https://github.com/bitshares/bitshares-ui/pull/1020

Like this?

Should I also give my wallet name?

nickbuckner3

**Comment by wmbutler** [comment]
Thanks!

**Comment by nbcks** [comment]
So every time I should a) reference the PR in the issues and b) reference the issue in the PR and c) put the issue in the commit d) Give my wallet address?

**Comment by wmbutler** [comment]
No need for your wallet address. I have a cross-reference built for it once I have it for the first time.

**Comment by nbcks** [comment]
There is a bug in this which I will fix on the weekend - if you don't have as short position in an asset, yet you have some of it, the balance column will still display 0.

**Comment by wmbutler** [comment]
@nbcks open a separate issue.

**Comment by wmbutler** [comment]
@nbcks Please post your BTS address here for payment.

**Comment by nbcks** [comment]
my address is "nickbuckner3".

Thank you.
