### ISSUE TITLE
[.25][zhyupe] Asset creation fee in fee schedule is not accurate

### ISSUE THREAD

**Issue by HarukaMa** [bitshares/bitshares-ui#996]
The fee for asset creation works like this:

For 100% of the fee defined in network parameter:
- 50% of it goes directly into the fee pool of the new asset,
- 50% of it acts like network fee:
  - 80% goes over referral program,
  - 20% goes to network.

In fee schedule page, it is treated like other fees (whole 20% for LTM), which doesn't quite match the actual operations. Should we change how this fee shows in the table, or leave the responsibility of network understanding to creators? If we should change it, how to show it exactly?

Edit: After BSIP27 get implemented, asset creator could reclaim the 50% inside the fee pool, but it's still in the future, and the current way to show the fee is still not accurate.

**Comment by landry314** [comment]
Good catch @HarukaMa. I actually had this in my notes a month ago but I totally forgot to create an issue for it! You are absolutely right.

Since 50% goes into the fee pool, the referrer only gets 80% of 50% which is 40%. Therefore the cost to a lifetime member is just 60% of the standard fee, not 20% which is what is displayed now. Easy fix!

**Comment by zhyupe** [comment]
Claimed & Fixed (Though I think this is a bad solution, I didn't find a better way to fix this)

**Comment by abitmore** [comment]
> Therefore the cost to a lifetime member is just 60% of the standard fee

Please be aware that the 50% goes to fee pool belongs to the asset issuer and can be easily gotten out. See https://github.com/bitshares/bitshares-core/issues/188 and https://github.com/bitshares/bsips/blob/master/bsip-0027.md

**Comment by zhyupe** [comment]
> Please be aware that the 50% goes to fee pool belongs to the asset issuer and can be easily gotten out.
It's the same for standard user and LTM, and it's included in the fee for standard user.

**Comment by HarukaMa** [comment]
We should change that again after BSIP27. I think for now this is good to go as taking that out needs manual work on cli wallet.
