### ISSUE TITLE
[.5] Fee Schedule Has Impossible Lifetime Member Fee to Upgrade to Lifetime Membership

### ISSUE THREAD

**Issue by landry314** [bitshares/bitshares-ui#997]
Since a lifetime member can not upgrade his account to lifetime, it doesn't make sense in the Fee Schedule to display a lifetime member fee for this action.

When you upgrade an account to lifetime, 80% goes to the referrer, which can not be the same account which is upgrading. It can be another account you own and then referral fees will then go to that other account but it could technically also be a faucet...

Correct me if I am wrong here. I'm not feeling 100%. Regardless, another account which is lifetime would get the discount so displaying the fee as if it was discounted isn't accurate.

You simply can not upgrade a lifetime account to lifetime...

**Comment by HarukaMa** [comment]
If we want to eliminate impossible fees, annual membership fee should also be removed from the list then.

**Comment by landry314** [comment]
Well, it is in strikethrough font which is appropriate because it is a feature of the blockchain it is just not being used right now. There is a possibility it will come back one day.

**Comment by svk31** [comment]
This is nitpicking imo. The fee schedule is independent of your currently active account, it just displays the fees as they are, that means displaying all of them.

**Comment by HarukaMa** [comment]
@svk31 It's not about linking to currently active account; the point is you cannot upgrade to LTM if you are already LTM, so LTM fee of upgrading to LTM does not exist.

**Comment by svk31** [comment]
Sure, what I'm saying is the fee schedule is the fee schedule, it doesn't matter that you have an account that's already a lifetime member, the fee is still the same.

**Comment by wmbutler** [comment]
I do see the point here. Wouldn't is make more sense to place a `--` here? Easy win, almost zero effort.

**Comment by landry314** [comment]
@svk31, i think you are missing the point here. This is a fee that isn't possible so it should have - * next to it instead of a price just like all the other fees which are not possible (like the fee to create a witness for standard users).

**Comment by zhyupe** [comment]
Since fixing this issue might introduce conflict to #1005 and #1021,  I suggest fixing this after those PRs get merged.
I'd like to claim this then.

**Comment by svk31** [comment]
OK I think finally understand what you actually meant here, which is that the discounted fee for upgrading to lifetime member is impossible to actually get. Still nitpicking but easy enough to fix.

**Comment by svk31** [comment]
![image](https://user-images.githubusercontent.com/6890015/34935023-b8629616-f9dc-11e7-9607-07655c94f775.png)
