### ISSUE TITLE
[1.5][ahdigital][4][gibbsfromncis] Scan QR Code - Withdraw Modal

### ISSUE THREAD

**Issue by wmbutler** [bitshares/bitshares-ui#998]

**Comment by timelf123** [comment]
This probably needs to wait for the library installs ticket #999 correct?

**Comment by wmbutler** [comment]
Yes.

**Comment by gibbsfromncis** [comment]
@wmbutler I can take it

**Comment by wmbutler** [comment]
@gibbsfromncis this is fairly in-depth. Are you sure you want to claim it?

**Comment by gibbsfromncis** [comment]
@wmbutler I see there is issue like this - https://github.com/bitshares/bitshares-ui/issues/832. So it would be much easy for @startailcoon. 

So I can help with library install :)

**Comment by wmbutler** [comment]
Unfortunately, this issue is mired in some disagreements about how the URI should be defined for bitshares assets.

**Comment by wmbutler** [comment]
Actually, the scan QR code should be fairly straightforward since we are only interpreting existing QR codes and not actually displaying them. I think for our first coins, we handle the withdraw modal.

- [ ] Place a scan icon at the top of the withdraw modal or in the address area once a coin is selected?
- [ ] Properly fill in amount, btc address, memo and gateway specific rules
- [ ] Memos might be challenging because our gateway providers require specialized memos to route transactions.

BTC URI:

```
bitcoin:1ieuewiuwoiewuweoireuwori&amount=1
```

**Comment by ahdigital** [comment]
@wmbutler Did I see on telegram that @gibbsfromncis already worked on this?

If not, is this not a simple case of adding a scan button to the address field demonstrated below using the new upcoming design guidelines:

![image](https://user-images.githubusercontent.com/3088454/39001733-db26503c-43ee-11e8-9e78-f81826c21a93.png)

Whilst there is both a specific scan and QR code icon I opted for the camera icon since it's the easiest to understand when displayed at those dimensions.

**Comment by wmbutler** [comment]
@ahdigital I think your UX needs to include the subsequent screen that houses the camera action as well. Feel free to increase as needed.

**Comment by ahdigital** [comment]
![image](https://user-images.githubusercontent.com/3088454/39046242-6a82b57e-448d-11e8-804e-97e34820fd08.png)

![qr-iphone](https://user-images.githubusercontent.com/3088454/39046249-70fc8524-448d-11e8-9544-dfabb019bf93.png)

**Comment by wmbutler** [comment]
UX Complete. It's on to you @gibbsfromncis

**Comment by gibbsfromncis** [comment]
@wmbutler what kind of data encrypted on QR codes? Only wallet address?

**Comment by ahdigital** [comment]
@wmbutler Can the UX for this be closed?

**Comment by wmbutler** [comment]
Yes, I closed it and made it part of 180501
